-- Classification Lab: 73 more cases (Sept 24, 2026). Run AFTER add_classification_lab.sql.
-- Safe to run twice.

INSERT INTO cases (standard, title, engine, grade, subject) VALUES
  ('SCI-3.7A-CL', 'Classification Lab: Push, pull, or reach', 'classification_lab', 3, 'Science'),
  ('SCI-3.8A-CL', 'Classification Lab: Kinds of energy', 'classification_lab', 3, 'Science'),
  ('SCI-3.10C-CL', 'Classification Lab: Fast or slow', 'classification_lab', 3, 'Science'),
  ('SCI-3.11C-CL', 'Classification Lab: Keep it or remake it', 'classification_lab', 3, 'Science'),
  ('SCI-3.12A-CL', 'Classification Lab: Winter moves', 'classification_lab', 3, 'Science'),
  ('SCI-3.12B-CL', 'Classification Lab: Who makes food?', 'classification_lab', 3, 'Science'),
  ('ELAR-3.3D-CL', 'Classification Lab: Same, opposite, or sound-alike', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.6F-CL', 'Classification Lab: Mad or sad?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.8A-CL', 'Classification Lab: Theme or topic?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.9A-CL', 'Classification Lab: What kind of story?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.9D-CL', 'Classification Lab: How is it built?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.9E-CL', 'Classification Lab: Fact or opinion?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.10E-CL', 'Classification Lab: Who is telling it?', 'classification_lab', 3, 'ELAR'),
  ('ELAR-3.11D-CL', 'Classification Lab: Word jobs', 'classification_lab', 3, 'ELAR'),
  ('MA-3.2B-CL', 'Classification Lab: Hundreds place', 'classification_lab', 3, 'Math'),
  ('MA-3.2A-CL', 'Classification Lab: Same number, different form', 'classification_lab', 3, 'Math'),
  ('MA-3.4I-CL', 'Classification Lab: Even, odd, or neither', 'classification_lab', 3, 'Math'),
  ('MA-3.5B-CL', 'Classification Lab: Which operation?', 'classification_lab', 3, 'Math'),
  ('MA-3.7D-CL', 'Classification Lab: Pour it or weigh it', 'classification_lab', 3, 'Math'),
  ('MA-3.7B-CL', 'Classification Lab: Around or inside?', 'classification_lab', 3, 'Math'),
  ('MA-3.9C-CL', 'Classification Lab: Planned or not?', 'classification_lab', 3, 'Math'),
  ('SS-3.3C-CL', 'Classification Lab: Natural or made by people?', 'classification_lab', 3, 'Social Studies'),
  ('SS-3.4A-CL', 'Classification Lab: Which way?', 'classification_lab', 3, 'Social Studies'),
  ('SS-3.5A-CL', 'Classification Lab: Where does the money go?', 'classification_lab', 3, 'Social Studies'),
  ('SS-3.14B-CL', 'Classification Lab: Was the author there?', 'classification_lab', 3, 'Social Studies'),
  ('SS-3.15C-CL', 'Classification Lab: How long ago?', 'classification_lab', 3, 'Social Studies'),
  ('SCI-4.7-CL', 'Classification Lab: Which force?', 'classification_lab', 4, 'Science'),
  ('SCI-4.10A-CL', 'Classification Lab: Up or down the cycle', 'classification_lab', 4, 'Science'),
  ('SCI-4.10B-CL', 'Classification Lab: Break, move, drop', 'classification_lab', 4, 'Science'),
  ('SCI-4.10C-CL', 'Classification Lab: Today or always?', 'classification_lab', 4, 'Science'),
  ('SCI-4.11A-CL', 'Classification Lab: Will it run out?', 'classification_lab', 4, 'Science'),
  ('SCI-4.13B-CL', 'Classification Lab: Born with it?', 'classification_lab', 4, 'Science'),
  ('ELAR-4.3C-CL', 'Classification Lab: Greek and Latin roots', 'classification_lab', 4, 'ELAR'),
  ('ELAR-4.6F-CL', 'Classification Lab: Saw it or figured it out?', 'classification_lab', 4, 'ELAR'),
  ('ELAR-4.9D-CL', 'Classification Lab: Text structure', 'classification_lab', 4, 'ELAR'),
  ('ELAR-4.9B-CL', 'Classification Lab: Picture words', 'classification_lab', 4, 'ELAR'),
  ('ELAR-4.9A-CL', 'Classification Lab: Tall tale or legend?', 'classification_lab', 4, 'ELAR'),
  ('MA-4.2B-CL', 'Classification Lab: What is the digit worth?', 'classification_lab', 4, 'Math'),
  ('MA-4.3C-CL', 'Classification Lab: Hidden halves', 'classification_lab', 4, 'Math'),
  ('MA-4.5A-CL', 'Classification Lab: Which operation?', 'classification_lab', 4, 'Math'),
  ('MA-4.5D-CL', 'Classification Lab: Perimeter or area?', 'classification_lab', 4, 'Math'),
  ('MA-4.6C-CL', 'Classification Lab: Which triangle?', 'classification_lab', 4, 'Math'),
  ('MA-4.8A-CL', 'Classification Lab: Which system?', 'classification_lab', 4, 'Math'),
  ('MA-4.10A-CL', 'Classification Lab: Fixed or changing bill?', 'classification_lab', 4, 'Math'),
  ('SS-4.4B-CL', 'Classification Lab: Which industry?', 'classification_lab', 4, 'Social Studies'),
  ('SS-4.6A-CL', 'Classification Lab: Far from the beach', 'classification_lab', 4, 'Social Studies'),
  ('SS-4.10A-CL', 'Classification Lab: Price up or down?', 'classification_lab', 4, 'Social Studies'),
  ('SS-4.13B-CL', 'Classification Lab: Which Texas branch?', 'classification_lab', 4, 'Social Studies'),
  ('SS-4.14A-CL', 'Classification Lab: Texas or the U.S.?', 'classification_lab', 4, 'Social Studies'),
  ('SS-4.19A-CL', 'Classification Lab: Alamo sources', 'classification_lab', 4, 'Social Studies'),
  ('SCI-5.6A-CL', 'Classification Lab: Properties that matter', 'classification_lab', 5, 'Science'),
  ('SCI-5.8C-CL', 'Classification Lab: Where does the light go?', 'classification_lab', 5, 'Science'),
  ('SCI-5.8A-CL', 'Classification Lab: Where does the energy end up?', 'classification_lab', 5, 'Science'),
  ('SCI-5.10C-CL', 'Classification Lab: What built this landform?', 'classification_lab', 5, 'Science'),
  ('SCI-5.12A-CL', 'Classification Lab: What is it interacting with?', 'classification_lab', 5, 'Science'),
  ('SCI-5.13B-CL', 'Classification Lab: Born knowing it?', 'classification_lab', 5, 'Science'),
  ('ELAR-5.3C-CL', 'Classification Lab: Greek and Latin roots', 'classification_lab', 5, 'ELAR'),
  ('ELAR-5.3D-CL', 'Classification Lab: Say it again', 'classification_lab', 5, 'ELAR'),
  ('ELAR-5.6F-CL', 'Classification Lab: Trait or feeling?', 'classification_lab', 5, 'ELAR'),
  ('ELAR-5.9A-CL', 'Classification Lab: Genre check', 'classification_lab', 5, 'ELAR'),
  ('ELAR-5.9B-CL', 'Classification Lab: Which sound device?', 'classification_lab', 5, 'ELAR'),
  ('ELAR-5.9D-CL', 'Classification Lab: Text structure', 'classification_lab', 5, 'ELAR'),
  ('MA-5.4H-CL', 'Classification Lab: Flat, around, or inside?', 'classification_lab', 5, 'Math'),
  ('MA-5.4D-CL', 'Classification Lab: Add or multiply the pattern?', 'classification_lab', 5, 'Math'),
  ('MA-5.8A-CL', 'Classification Lab: On the axis?', 'classification_lab', 5, 'Math'),
  ('MA-5.10C-CL', 'Classification Lab: How will you pay?', 'classification_lab', 5, 'Math'),
  ('MA-5.10A-CL', 'Classification Lab: What kind of tax?', 'classification_lab', 5, 'Math'),
  ('SS-5.2A-CL', 'Classification Lab: Cause or result?', 'classification_lab', 5, 'Social Studies'),
  ('SS-5.7A-CL', 'Classification Lab: City, country, or in between?', 'classification_lab', 5, 'Social Studies'),
  ('SS-5.15C-CL', 'Classification Lab: Whose job is it?', 'classification_lab', 5, 'Social Studies'),
  ('SS-5.15A-CL', 'Classification Lab: Which U.S. branch?', 'classification_lab', 5, 'Social Studies'),
  ('SS-5.19A-CL', 'Classification Lab: What does the Bill of Rights protect?', 'classification_lab', 5, 'Social Studies'),
  ('SS-5.23A-CL', 'Classification Lab: Revolution sources', 'classification_lab', 5, 'Social Studies')
ON CONFLICT (standard) DO UPDATE SET
  title = EXCLUDED.title,
  engine = EXCLUDED.engine,
  grade = EXCLUDED.grade,
  subject = EXCLUDED.subject;

UPDATE cases SET learning_target = 'I can tell a contact force from a force that acts at a distance.', lesson_summary = 'Students sort pushes and pulls by whether they need touch or can act across a gap, like magnetism and gravity. Page 2 adds light and heat, which are not forces at all. About 20 minutes.' WHERE standard = 'SCI-3.7A-CL';
UPDATE cases SET learning_target = 'I can tell light energy and sound energy apart in everyday things.', lesson_summary = 'Students sort everyday things by the main energy they give off: light or sound. Page 2 adds things that give off only thermal or mechanical energy, and the Venn shows things that give off both light and sound. About 20 minutes.' WHERE standard = 'SCI-3.8A-CL';
UPDATE cases SET learning_target = 'I can tell a fast change to the land from a slow one.', lesson_summary = 'Students sort changes to Earth''s surface by how fast they happen, not by how big they are. Page 2 adds something that does not change the land at all. About 20 minutes.' WHERE standard = 'SCI-3.10C-CL';
UPDATE cases SET learning_target = 'I can tell reusing, recycling, and reducing apart.', lesson_summary = 'Students sort ways to save natural resources: reuse keeps the same object, and recycle breaks it down to make something new. Page 2 adds reducing, which means using less in the first place. About 20 minutes.' WHERE standard = 'SCI-3.11C-CL';
UPDATE cases SET learning_target = 'I can tell migration from hibernation and from plant dormancy.', lesson_summary = 'Students sort how living things get through cold winters: migration or hibernation. Page 2 adds dormant plants and an animal that just sleeps a lot, which fit neither. About 20 minutes.' WHERE standard = 'SCI-3.12A-CL';
UPDATE cases SET learning_target = 'I can tell producers from consumers in a food chain.', lesson_summary = 'Students sort living things by how they get energy: they make their own food or they eat. Page 2 adds nonliving things, and the Venn shows producers that live in water. About 20 minutes.' WHERE standard = 'SCI-3.12B-CL';
UPDATE cases SET learning_target = 'I can tell if two words are synonyms, antonyms, or neither.', lesson_summary = 'Students sort word pairs by meaning: synonyms or antonyms. Pairs that look or sound alike are the trap. Page 2 adds homophones, which sound the same but do not share a meaning. About 20 minutes.' WHERE standard = 'ELAR-3.3D-CL';
UPDATE cases SET learning_target = 'I can use what a character does and says to tell how they feel.', lesson_summary = 'Students read short moments that never name the feeling and infer if the character is mad or sad. Page 2 adds other feelings, like joy and nerves, including happy tears. About 20 minutes.' WHERE standard = 'ELAR-3.6F-CL';
UPDATE cases SET learning_target = 'I can tell a story''s theme from its topic.', lesson_summary = 'Students sort ideas about stories: theme or topic. A topic names what a story is about. A theme is a full message about life. Page 2 adds plot details, which are things that happen. About 20 minutes.' WHERE standard = 'ELAR-3.8A-CL';
UPDATE cases SET learning_target = 'I can tell a fable from a myth by what the story is for.', lesson_summary = 'Students sort short story descriptions as fables or myths by the story''s purpose. Animals and gods are the trap, since they show up in both. Page 2 adds fairy tales and legends. About 20 minutes.' WHERE standard = 'ELAR-3.9A-CL';
UPDATE cases SET learning_target = 'I can tell if a text is built as cause and effect or problem and solution.', lesson_summary = 'Students read tiny two-sentence passages and sort them by how they are built. Signal words like because and so are the trap. Page 2 adds passages that only list or describe. About 20 minutes.' WHERE standard = 'ELAR-3.9D-CL';
UPDATE cases SET learning_target = 'I can tell a fact from an opinion.', lesson_summary = 'Students sort sentences by whether they can be proved. Opinions that sound sure and facts about things people love or fear are the trap. Page 2 adds questions, which are neither. About 20 minutes.' WHERE standard = 'ELAR-3.9E-CL';
UPDATE cases SET learning_target = 'I can tell if a story is told in first person or third person.', lesson_summary = 'Students sort short bits of stories by the narrator''s point of view: first person or third person. Characters who say "I" inside quotation marks are the trap. Page 2 adds second person, where the narrator talks to "you." About 20 minutes.' WHERE standard = 'ELAR-3.10E-CL';
UPDATE cases SET learning_target = 'I can tell if a word is a noun or a verb in a sentence.', lesson_summary = 'Students sort the word in CAPITALS by the job it does in that sentence: noun or verb. Many words can do both jobs, so students must read the whole sentence. Page 2 adds words that describe. About 20 minutes.' WHERE standard = 'ELAR-3.11D-CL';
UPDATE cases SET learning_target = 'I can find the digit in the hundreds place, in any form of a number.', lesson_summary = 'Students sort numbers by the digit in the hundreds place. Numbers come as numerals, word form, and expanded form. Size is the trap: a big number can have a small hundreds digit. Page 2 adds numbers with 4 or 5 hundreds. About 20 minutes.' WHERE standard = 'MA-3.2B-CL';
UPDATE cases SET learning_target = 'I can tell which number a word form, expanded form, or place value form is equal to.', lesson_summary = 'Students sort numbers written in word form, expanded form, and place value form by their value: 3,405 or 3,045. Both use the same digits, which is the trap. Page 2 adds forms in a mixed-up order, forms like 34 hundreds, and numbers equal to neither. About 20 minutes.' WHERE standard = 'MA-3.2A-CL';
UPDATE cases SET learning_target = 'I can use the ones digit to tell if a number is even or odd.', lesson_summary = 'Students sort numbers as even or odd using the divisibility rule for 2: look at the ones digit. Size and the other digits are the trap. Page 2 adds fractions, which are not even or odd. About 20 minutes.' WHERE standard = 'MA-3.4I-CL';
UPDATE cases SET learning_target = 'I can tell if a word problem needs multiplying or dividing.', lesson_summary = 'Students sort word problems by the operation that solves them, without solving. Key words are the trap: "in all" and "each" show up in both kinds. Page 2 adds problems with groups that are not equal. About 20 minutes.' WHERE standard = 'MA-3.5B-CL';
UPDATE cases SET learning_target = 'I can tell when to measure liquid volume and when to measure weight.', lesson_summary = 'Students read what each question wants to know and decide if it needs liquid volume or weight. Things that pour, like flour and rice, are still weighed, and a heavy jug of milk is still a liquid volume question. Page 2 adds length questions that need neither. About 20 minutes.' WHERE standard = 'MA-3.7D-CL';
UPDATE cases SET learning_target = 'I can tell if a job needs perimeter or area.', lesson_summary = 'Students sort real-life jobs by what they need: perimeter (around the edge) or area (covering the inside). The same garden, rug, or picture shows up both ways, so students must read the job, not the object. Page 2 adds jobs that need neither. About 20 minutes.' WHERE standard = 'MA-3.7B-CL';
UPDATE cases SET learning_target = 'I can tell planned spending from unplanned spending and name a cost or benefit of each.', lesson_summary = 'Students sort spending choices by when the buyer decided: ahead of time or in the moment. A big price does not make a purchase planned, and a small one can be planned. Page 2 adds saving and getting a gift, which are not spending. The questions ask about costs and benefits. About 20 minutes.' WHERE standard = 'MA-3.9C-CL';
UPDATE cases SET learning_target = 'I can tell a natural landscape feature from one people made.', lesson_summary = 'Students sort Texas landscape features by who made them: nature or people. Lakes made by dams, parks and farms look natural but were shaped by people. Page 2 adds weather, which is not part of the landscape. About 20 minutes.' WHERE standard = 'SS-3.3C-CL';
UPDATE cases SET learning_target = 'I can tell a cardinal direction from an intermediate direction.', lesson_summary = 'Students sort map directions into cardinal (north, south, east, west) and intermediate (northeast, northwest, southeast, southwest). Page 2 adds words like left and behind that are not map directions. About 20 minutes.' WHERE standard = 'SS-3.4A-CL';
UPDATE cases SET learning_target = 'I can tell saving money from donating money.', lesson_summary = 'Students sort money choices into saving and donating. Saving for a gift is still saving, and a food bank is not a bank. Page 2 adds spending and earning, which are neither. About 20 minutes.' WHERE standard = 'SS-3.5A-CL';
UPDATE cases SET learning_target = 'I can tell a primary source from a secondary source.', lesson_summary = 'Students sort sources about the first Moon landing (Apollo 11, July 1969) by who made them: someone who was there or took part, or someone who was not. Page 2 adds sources that are not about the landing at all. About 20 minutes.' WHERE standard = 'SS-3.14B-CL';
UPDATE cases SET learning_target = 'I can tell if a span of time is a decade or a century.', lesson_summary = 'Students sort spans of time into a decade (10 years) or a century (100 years). From 1990 to 2000 and from 1900 to 2000 look alike but are not the same size. Page 2 adds spans that are only one year. About 20 minutes.' WHERE standard = 'SS-3.15C-CL';
UPDATE cases SET learning_target = 'I can tell which force is mainly at work: gravity, friction, or magnetism.', lesson_summary = 'Students sort events by the main force at work: gravity pulling things toward Earth, or friction slowing things that rub. Page 2 adds magnetism. The Venn sorts forces by what they do and whether they need contact. About 20 minutes.' WHERE standard = 'SCI-4.7-CL';
UPDATE cases SET learning_target = 'I can tell evaporation from condensation and explain how the Sun''s energy moves water through the water cycle.', lesson_summary = 'Students sort water-cycle events by the change that happens: liquid to gas, or gas to liquid drops. The white "steam" over a pot and dew are the traps. Page 2 adds precipitation and collection, and the Venn shows when the Sun''s heat is doing the work. About 20 minutes.' WHERE standard = 'SCI-4.10A-CL';
UPDATE cases SET learning_target = 'I can tell weathering from erosion and deposition, and name the water, wind, or ice that causes them.', lesson_summary = 'Students sort slow changes to Earth''s surface by what happens to the rock: it breaks (weathering) or it is carried away (erosion). Page 2 adds deposition, where pieces are dropped in a new place. The Venn separates the process from the cause by asking what ice does. About 20 minutes.' WHERE standard = 'SCI-4.10B-CL';
UPDATE cases SET learning_target = 'I can tell the difference between weather and climate.', lesson_summary = 'Students sort statements by time: what the air is like right now, or what it is usually like over many years. A rare or famous storm is the trap. Page 2 adds statements that are not about the air at all. About 20 minutes.' WHERE standard = 'SCI-4.10C-CL';
UPDATE cases SET learning_target = 'I can tell renewable natural resources from nonrenewable ones.', lesson_summary = 'Students sort natural resources by whether nature can replace them in a short time. Coal, oil, and natural gas formed from living things long ago, which is the trap. Page 2 adds human-made materials that are not natural resources at all. About 20 minutes.' WHERE standard = 'SCI-4.11A-CL';
UPDATE cases SET learning_target = 'I can tell an inherited physical trait from an acquired one.', lesson_summary = 'Students sort physical traits of people, animals, and plants by how the living thing got them: from its parents or during its life. Page 2 adds learned behaviors, which are not physical traits at all. About 20 minutes.' WHERE standard = 'SCI-4.13B-CL';
UPDATE cases SET learning_target = 'I can find the roots auto, graph, and meter in a word and use them to figure out what the word means.', lesson_summary = 'Students sort words by the Greek root they contain: auto (self) or graph (write). Page 2 adds words with meter and look-alike words that only seem to have auto. autograph appears only in the Venn center. About 20 minutes.' WHERE standard = 'ELAR-4.3C-CL';
UPDATE cases SET learning_target = 'I can tell what a text says directly from what I infer using clues and evidence.', lesson_summary = 'Students read one short scene and sort statements about it: did the words say it, or did the reader infer it from clues? Page 2 uses the same scene and adds guesses that no clue supports. About 20 minutes.' WHERE standard = 'ELAR-4.6F-CL';
UPDATE cases SET learning_target = 'I can recognize how the ideas in a short informational passage are organized.', lesson_summary = 'Students sort two-sentence passages as compare and contrast or cause and effect. Page 2 adds problem-and-solution passages. The word "but" shows up in all three kinds. About 20 minutes.' WHERE standard = 'ELAR-4.9D-CL';
UPDATE cases SET learning_target = 'I can explain whether an author creates an image with a simile or a metaphor.', lesson_summary = 'Students sort sentences into similes and metaphors by how the comparison is made. Page 2 adds personification and plain sentences that use "like" or "is" without comparing anything. About 20 minutes.' WHERE standard = 'ELAR-4.9B-CL';
UPDATE cases SET learning_target = 'I can tell a tall tale from a legend by its distinguishing characteristics.', lesson_summary = 'Students sort well-known stories as tall tales or legends. Both have heroes, so students must look for exaggeration told on purpose for humor. Page 2 adds fables. About 20 minutes.' WHERE standard = 'ELAR-4.9A-CL';
UPDATE cases SET learning_target = 'I can tell the value of a digit by the place it is in.', lesson_summary = 'Every number has exactly one 7. Students sort by the value of that 7: 700 or 70. Some numbers are written in expanded notation. Page 2 adds decimals and numbers where the 7 is worth something else. About 20 minutes.' WHERE standard = 'MA-4.2B-CL';
UPDATE cases SET learning_target = 'I can tell if a fraction is equal to 1/2 or to 1 whole.', lesson_summary = 'Students sort fractions by what they are equal to: 1/2 or 1 whole. Big numbers are the trap. Page 2 adds fractions that are close to 1/2 but not equal. About 20 minutes.' WHERE standard = 'MA-4.3C-CL';
UPDATE cases SET learning_target = 'I can tell which operation a word problem needs by what is happening in it.', lesson_summary = 'Students read multi-digit word problems and classify the operation that solves each one: multiply or divide. They do not solve. Key words like "each" and "in all" show up in both groups on purpose. Page 2 adds add and subtract problems, and the Venn adds two-step problems. About 20 minutes.' WHERE standard = 'MA-4.5A-CL';
UPDATE cases SET learning_target = 'I can tell if a rectangle problem needs perimeter or area.', lesson_summary = 'Students read problems about rectangles and classify what each needs: perimeter or area. They do not solve. The same size rectangle shows up both ways, and the side lengths are always in plain units like feet. Page 2 adds problems that need neither. About 20 minutes.' WHERE standard = 'MA-4.5D-CL';
UPDATE cases SET learning_target = 'I can use a triangle''s angles to tell if it is right, obtuse, or acute.', lesson_summary = 'Students read three angle measures and classify the triangle as right or obtuse. Tiny angles and angles close to 90° are the trap. Page 2 adds acute triangles, which go in Neither. About 20 minutes.' WHERE standard = 'MA-4.6C-CL';
UPDATE cases SET learning_target = 'I can tell if a unit of measure is metric or customary.', lesson_summary = 'Students sort units of measure by system: metric or customary. Units that measure the same thing, like a liter and a quart, are the trap. Page 2 adds time units, which both systems share. About 20 minutes.' WHERE standard = 'MA-4.8A-CL';
UPDATE cases SET learning_target = 'I can tell a fixed expense from a variable expense.', lesson_summary = 'Students sort expenses by whether the amount stays the same (fixed) or changes (variable). Bills that come every month are the trap. Page 2 adds money coming in, which is not an expense at all. About 20 minutes.' WHERE standard = 'MA-4.10A-CL';
UPDATE cases SET learning_target = 'I can tell whether an event belongs to the Texas cattle industry or the railroad industry.', lesson_summary = 'Students sort events from late 1800s Texas into the cattle industry or the railroad industry (4.4B, with 4.4C). Page 2 adds oil and gas events (4.5B), which fit neither, and the Venn shows where cattle and railroads met. About 20 minutes.' WHERE standard = 'SS-4.4B-CL';
UPDATE cases SET learning_target = 'I can tell which physical region of Texas a place is in.', lesson_summary = 'Students sort Texas places into the Coastal Plains or the Mountains and Basins. The trap is going by how a place looks instead of where it is. Page 2 adds places in the other two regions. About 20 minutes.' WHERE standard = 'SS-4.6A-CL';
UPDATE cases SET learning_target = 'I can explain how a change in supply or demand can make a price go up or down.', lesson_summary = 'Students sort events by what will likely happen to a price in a free enterprise system. The trap is thinking more stores or more sellers means higher prices. Page 2 adds events that change neither supply nor demand. About 20 minutes.' WHERE standard = 'SS-4.10A-CL';
UPDATE cases SET learning_target = 'I can tell which branch of Texas government does a particular job.', lesson_summary = 'Students sort jobs by the branch of Texas government that does them under the Texas Constitution: legislative or executive. Page 2 adds judicial jobs, which belong to neither group, and the Venn crosses the legislative branch with work on the state budget. About 20 minutes.' WHERE standard = 'SS-4.13B-CL';
UPDATE cases SET learning_target = 'I can explain whether a patriotic symbol or landmark stands for Texas or for the United States.', lesson_summary = 'Students sort symbols and landmarks by the place they stand for: Texas or the United States. Shared colors, animals and history are the trap. Page 2 adds symbols of other countries, and the Venn asks which flags flew over Texas. About 20 minutes.' WHERE standard = 'SS-4.14A-CL';
UPDATE cases SET learning_target = 'I can tell a primary source from a secondary source about the Texas Revolution.', lesson_summary = 'Students sort sources about the Texas Revolution by one fixed rule: was the maker there or part of it? Old paintings are the trap, and so are accounts that participants wrote years later. Page 2 adds sources about a different event. About 20 minutes.' WHERE standard = 'SS-4.19A-CL';
UPDATE cases SET learning_target = 'I can compare materials by whether they conduct or insulate electrical energy and by whether they are magnetic.', lesson_summary = 'Students sort materials by one physical property: whether they conduct or insulate electricity. Page 2 adds things that are energy rather than matter, and the Venn compares conducting electricity with magnetism. About 20 minutes.' WHERE standard = 'SCI-5.6A-CL';
UPDATE cases SET learning_target = 'I can tell whether light is mainly reflected, refracted, or absorbed when it meets an object.', lesson_summary = 'Students sort everyday light events by the main thing that happens to the light: it bounces off (reflected) or bends as it passes into a new material (refracted). Page 2 adds light that is absorbed, and the Venn shows a rainbow, where light is both refracted and reflected. About 20 minutes.' WHERE standard = 'SCI-5.8C-CL';
UPDATE cases SET learning_target = 'I can describe how energy transforms in a device and identify the useful form of energy it produces.', lesson_summary = 'Students sort everyday devices by the useful energy each one is built to produce: light or motion. Page 2 adds devices whose job is sound or thermal energy, and the Venn compares devices that use electricity with devices that produce light. About 20 minutes.' WHERE standard = 'SCI-5.8A-CL';
UPDATE cases SET learning_target = 'I can identify whether wind, water, or ice formed a landform such as a delta, canyon, or sand dune.', lesson_summary = 'Students sort real landforms by what formed them: wind or water. Page 2 adds landforms carved by glaciers, and the Venn separates landforms built by dropped material from landforms made by water. About 20 minutes.' WHERE standard = 'SCI-5.10C-CL';
UPDATE cases SET learning_target = 'I can tell whether an organism is interacting with a biotic factor or an abiotic factor in its ecosystem.', lesson_summary = 'Students sort interactions by the factor the organism is interacting with: biotic (living or once living) or abiotic (never living). Page 2 adds events with no living thing at all, and the Venn asks which factors a pond frog needs to survive. About 20 minutes.' WHERE standard = 'SCI-5.12A-CL';
UPDATE cases SET learning_target = 'I can tell whether an animal behavior is instinctual or learned and explain how it helps the animal survive.', lesson_summary = 'Students sort well-known animal behaviors as instincts or learned behaviors. Page 2 adds body structures, which are not behaviors at all, and the Venn compares instincts with behaviors that help an animal find food. About 20 minutes.' WHERE standard = 'SCI-5.13B-CL';
UPDATE cases SET learning_target = 'I can find the Greek roots geo and photo inside a word and use them to figure out what the word means.', lesson_summary = 'Students sort single words by the root they contain: geo (earth) or photo (light). Page 2 adds look-alike words that only share letters, plus words with a different root. The Venn pairs geo with graph. About 20 minutes.' WHERE standard = 'ELAR-5.3C-CL';
UPDATE cases SET learning_target = 'I can tell an adage from a pun and explain the meaning of each.', lesson_summary = 'Students sort sayings into adages and puns. Page 2 adds plain, literal statements that fit neither. The Venn crosses adages with sayings that give an instruction, since both adages and puns can sound like advice. About 20 minutes.' WHERE standard = 'ELAR-5.3D-CL';
UPDATE cases SET learning_target = 'I can use evidence to infer whether a sentence shows a character trait or a feeling in one moment.', lesson_summary = 'Students sort sentences about characters: does the evidence show a lasting trait or a feeling in one moment? Page 2 adds physical descriptions, which fit neither. The Venn crosses traits with details shown through a character''s actions. About 20 minutes.' WHERE standard = 'ELAR-5.6F-CL';
UPDATE cases SET learning_target = 'I can use the characteristics of myths and legends to tell the two genres apart.', lesson_summary = 'Students sort short story descriptions into myths and legends. Page 2 adds tall tales, which fit neither. The Venn crosses stories where a god appears with stories that explain something in nature. About 20 minutes.' WHERE standard = 'ELAR-5.9A-CL';
UPDATE cases SET learning_target = 'I can explain whether a line of poetry uses alliteration or onomatopoeia.', lesson_summary = 'Students sort lines of poetry by the sound device they use: alliteration or onomatopoeia. Each page line has only one device. Page 2 adds similes, which fit neither, and the Venn center holds lines that use both. About 20 minutes.' WHERE standard = 'ELAR-5.9B-CL';
UPDATE cases SET learning_target = 'I can tell whether an informational passage uses logical order or order of importance.', lesson_summary = 'Students sort tiny two-sentence passages by organizational pattern: logical order or order of importance. Page 2 adds compare-and-contrast passages that fit neither. The Venn checks whether the word "first" really signals time. About 20 minutes.' WHERE standard = 'ELAR-5.9D-CL';
UPDATE cases SET learning_target = 'I can tell if a problem is about area, volume, or perimeter.', lesson_summary = 'Students sort real jobs by what they measure: covering a surface (area) or filling a space (volume). Page 2 adds jobs that go around the edge (perimeter). The object in the job is the trap: a box can be an area job or a volume job. About 20 minutes.' WHERE standard = 'MA-5.4H-CL';
UPDATE cases SET learning_target = 'I can tell an additive pattern from a multiplicative pattern in a table or graph.', lesson_summary = 'Students sort tables and graph points by how each x turns into its y. Definition used: additive means y = x + the same number for every pair; multiplicative means y = x times the same number for every pair. Reading down the y column (it grows by a steady step either way) is the trap. About 20 minutes.' WHERE standard = 'MA-5.4D-CL';
UPDATE cases SET learning_target = 'I can tell if a point is on the x-axis, on the y-axis, or on neither.', lesson_summary = 'Students sort first-quadrant ordered pairs by the axis they sit on. Pairs like (5, 0) and (0, 5) use the same numbers, so order is the trap. Page 2 adds points near an axis but not on it, and the Venn puts the origin in the center. About 20 minutes.' WHERE standard = 'MA-5.8A-CL';
UPDATE cases SET learning_target = 'I can tell which payment methods use my own money and which use borrowed money.', lesson_summary = 'Students sort payments by whose money pays: your own (check, debit card, electronic payment from a bank account) or borrowed (credit). Page 2 adds bank moves that are not payments. The Venn and questions add advantages and disadvantages of credit. About 20 minutes.' WHERE standard = 'MA-5.10C-CL';
UPDATE cases SET learning_target = 'I can tell sales tax, property tax, and other kinds of tax apart.', lesson_summary = 'Students sort taxes by what they are paid on: a purchase (sales tax) or land and buildings someone owns (property tax). Page 2 adds income and payroll tax. The Venn sorts property tax against taxes a business owes. About 20 minutes.' WHERE standard = 'MA-5.10A-CL';
UPDATE cases SET learning_target = 'I can tell whether an event was a cause or a result of the American Revolution.', lesson_summary = 'Students sort events as causes or results of the American Revolution (5.2A, with 5.2C for the results). Page 2 adds later events, like the War of 1812, that belong to neither group. This is two groups, not a timeline. About 20 minutes.' WHERE standard = 'SS-5.2A-CL';
UPDATE cases SET learning_target = 'I can identify and describe rural, urban, and suburban settlement patterns.', lesson_summary = 'Students sort places by settlement pattern: rural or urban. Page 2 adds suburban places, which have traffic and stores but are neighborhoods outside a city. About 20 minutes.' WHERE standard = 'SS-5.7A-CL';
UPDATE cases SET learning_target = 'I can tell which powers belong to the national government and which belong to the states.', lesson_summary = 'Students sort government powers by level: national or state. Page 2 adds city jobs that belong to neither, and the Venn shows powers the two levels share. About 20 minutes.' WHERE standard = 'SS-5.15C-CL';
UPDATE cases SET learning_target = 'I can identify the basic job of the legislative, executive, and judicial branches of the U.S. government.', lesson_summary = 'Students sort actions of the national government by branch: legislative or judicial. Page 2 adds executive actions, like the President signing a bill, that belong to neither group. About 20 minutes.' WHERE standard = 'SS-5.15A-CL';
UPDATE cases SET learning_target = 'I can describe rights guaranteed in the Bill of Rights and tell which ones are in the First Amendment.', lesson_summary = 'Students sort everyday actions by where the right is protected: the First Amendment or another Bill of Rights amendment. Page 2 adds rights, like voting at 18, that come from later amendments. About 20 minutes.' WHERE standard = 'SS-5.19A-CL';
UPDATE cases SET learning_target = 'I can tell the difference between primary and secondary sources about the American Revolution.', lesson_summary = 'Students sort sources about the American Revolution as primary or secondary by asking whether the maker was there or took part. Page 2 adds sources about other events, which fit neither group. About 20 minutes.' WHERE standard = 'SS-5.23A-CL';
