-- Signal Check companions: Weigh-In + Thread for ALL Social Studies classic SC cases (G3-G5).
-- Skip Science. Standards use SS. prefix. Engine fact_check_desk routes to SignalCheckClient.
-- Safe to re-run (ON CONFLICT updates title/engine/grade/subject).

INSERT INTO cases (standard, title, engine, grade, subject) VALUES
  ('SS.3.2B-SC-WI', 'Same Fix Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.2B-SC-TH', 'Thread: Same Stoplight?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.3A-SC-WI', 'Same Weather Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.3A-SC-TH', 'Thread: Same Land?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.3C-SC-WI', 'Creek Change Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.3C-SC-TH', 'Thread: Just Nature?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.5B-SC-WI', 'Budget Plan Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.5B-SC-TH', 'Thread: Just a Wish List?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6A-SC-WI', 'Lemonade Price Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6A-SC-TH', 'Thread: Same Price Always?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6B-SC-WI', 'Scarce Now Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6B-SC-TH', 'Thread: Only at Zero?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6C-SC-WI', 'Sold Out Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.6C-SC-TH', 'Thread: Sold Out = Profit?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.7C-SC-WI', 'Whose Job Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.7C-SC-TH', 'Thread: Any Level?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.8A-SC-WI', 'Label Mix Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.8A-SC-TH', 'Thread: Same Label?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.9E-SC-WI', 'Loud Vote Weigh-In', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.3.9E-SC-TH', 'Thread: Loudest Wins?', 'fact_check_desk', 3, 'Social Studies'),
  ('SS.4.1B-SC-WI', 'Same Ways Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.1B-SC-TH', 'Thread: Same Ways of Life?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.2A-SC-WI', 'Explorer Why Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.2A-SC-TH', 'Thread: Just Curious?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.2C-SC-WI', 'Mission Spot Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.2C-SC-TH', 'Thread: Empty Land Only?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.3A-SC-WI', 'Alamo Survive Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.3A-SC-TH', 'Thread: No Survivors?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.3D-SC-WI', 'Republic Problems Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.3D-SC-TH', 'Thread: Problems Solved?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.4B-SC-WI', 'Cattle Boom Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.4B-SC-TH', 'Thread: Just Cows?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.6B-SC-WI', 'Region Match Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.6B-SC-TH', 'Thread: Same Region?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.9A-SC-WI', 'Needs Meet Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.9A-SC-TH', 'Thread: Mostly Hunting?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.11C-SC-WI', 'Texas Grow Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.11C-SC-TH', 'Thread: Just Population?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.17B-SC-WI', 'Texas Sound Weigh-In', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.4.17B-SC-TH', 'Thread: One Style?', 'fact_check_desk', 4, 'Social Studies'),
  ('SS.5.2A-SC-WI', 'Stamp Act Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.2A-SC-TH', 'Thread: Just the Stamp Act?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4A-SC-WI', '1812 Cause Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4A-SC-TH', 'Thread: Only Land?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4C-SC-WI', 'First to See Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4C-SC-TH', 'Thread: First to See It?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4D-SC-WI', 'Civil War Root Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4D-SC-TH', 'Thread: Separate Causes?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4E-SC-WI', '13th Fix Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.4E-SC-TH', 'Thread: Fixed by the 13th?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.7B-SC-WI', 'Anywhere City Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.7B-SC-TH', 'Thread: Anywhere Will Do?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.8B-SC-WI', 'Dam Debate Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.8B-SC-TH', 'Thread: No Downsides?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.13B-SC-WI', 'Colonial Say Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.13B-SC-TH', 'Thread: Just for Show?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.14B-SC-WI', 'Preamble Jobs Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.14B-SC-TH', 'Thread: Just Lawmaking?', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.15A-SC-WI', 'Branch Jobs Weigh-In', 'fact_check_desk', 5, 'Social Studies'),
  ('SS.5.15A-SC-TH', 'Thread: One Branch, Every Job?', 'fact_check_desk', 5, 'Social Studies')
ON CONFLICT (standard) DO UPDATE SET
  engine = EXCLUDED.engine,
  title = EXCLUDED.title,
  grade = EXCLUDED.grade,
  subject = EXCLUDED.subject;

-- After running: assign any of the standards above from Teacher -> Assign -> Signal Check.
