-- Sept 22, 2026 — Relay Station reading library, batch 2: Social Studies, Biographies, ELAR text types, Numbers (48 readings).
-- Safe to re-run. Text ships in lib/cases/relay-station/index.js.

INSERT INTO cases (standard, title, engine, grade, subject) VALUES
  ('RS.3.SS01', 'ClearKeys: Social Studies (Launch) - Finding Your Way', 'relay_station', 3, 'Social Studies'),
  ('RS.3.SS02', 'ClearKeys: Social Studies (Cruise) - Three Levels of Government', 'relay_station', 3, 'Social Studies'),
  ('RS.3.SS03', 'ClearKeys: Social Studies (Cruise) - Scarcity and Choices', 'relay_station', 3, 'Social Studies'),
  ('RS.3.SS04', 'ClearKeys: Social Studies (Orbit) - Being a Good Citizen', 'relay_station', 3, 'Social Studies'),
  ('RS.4.SS01', 'ClearKeys: Social Studies (Launch) - Texas Symbols', 'relay_station', 4, 'Social Studies'),
  ('RS.4.SS02', 'ClearKeys: Social Studies (Cruise) - Spanish Missions in Texas', 'relay_station', 4, 'Social Studies'),
  ('RS.4.SS03', 'ClearKeys: Social Studies (Cruise) - The Alamo and San Jacinto', 'relay_station', 4, 'Social Studies'),
  ('RS.4.SS04', 'ClearKeys: Social Studies (Orbit) - The Great Cattle Drives', 'relay_station', 4, 'Social Studies'),
  ('RS.5.SS01', 'ClearKeys: Social Studies (Launch) - Why People Came to the Colonies', 'relay_station', 5, 'Social Studies'),
  ('RS.5.SS02', 'ClearKeys: Social Studies (Cruise) - Three Branches of Government', 'relay_station', 5, 'Social Studies'),
  ('RS.5.SS03', 'ClearKeys: Social Studies (Cruise) - The Louisiana Purchase', 'relay_station', 5, 'Social Studies'),
  ('RS.5.SS04', 'ClearKeys: Social Studies (Orbit) - The Declaration of Independence', 'relay_station', 5, 'Social Studies'),
  ('RS.3.BIO01', 'ClearKeys: Biography (Launch) - Clara Barton', 'relay_station', 3, 'Social Studies'),
  ('RS.3.BIO02', 'ClearKeys: Biography (Cruise) - Helen Keller', 'relay_station', 3, 'Social Studies'),
  ('RS.3.BIO03', 'ClearKeys: Biography (Cruise) - Ruby Bridges', 'relay_station', 3, 'Social Studies'),
  ('RS.3.BIO04', 'ClearKeys: Biography (Orbit) - Jonas Salk', 'relay_station', 3, 'Social Studies'),
  ('RS.4.BIO01', 'ClearKeys: Biography (Launch) - Gail Borden', 'relay_station', 4, 'Social Studies'),
  ('RS.4.BIO02', 'ClearKeys: Biography (Cruise) - Joseph Glidden and Barbed Wire', 'relay_station', 4, 'Social Studies'),
  ('RS.4.BIO03', 'ClearKeys: Biography (Cruise) - Barbara Jordan', 'relay_station', 4, 'Social Studies'),
  ('RS.4.BIO04', 'ClearKeys: Biography (Orbit) - Michael DeBakey', 'relay_station', 4, 'Social Studies'),
  ('RS.5.BIO01', 'ClearKeys: Biography (Launch) - The Wright Brothers', 'relay_station', 5, 'Social Studies'),
  ('RS.5.BIO02', 'ClearKeys: Biography (Cruise) - Benjamin Franklin', 'relay_station', 5, 'Social Studies'),
  ('RS.5.BIO03', 'ClearKeys: Biography (Cruise) - George Washington Carver', 'relay_station', 5, 'Social Studies'),
  ('RS.5.BIO04', 'ClearKeys: Biography (Orbit) - Neil Armstrong', 'relay_station', 5, 'Social Studies'),
  ('RS.3.ELA01', 'ClearKeys: ELAR (Launch) - How-To: Plant a Seed', 'relay_station', 3, 'ELAR'),
  ('RS.3.ELA02', 'ClearKeys: ELAR (Cruise) - Poem: Rocket Ride', 'relay_station', 3, 'ELAR'),
  ('RS.3.ELA03', 'ClearKeys: ELAR (Cruise) - Opinion: Our School Needs a Garden', 'relay_station', 3, 'ELAR'),
  ('RS.3.ELA04', 'ClearKeys: ELAR (Orbit) - News Brief: Bake Sale Helps Shelter', 'relay_station', 3, 'ELAR'),
  ('RS.4.ELA01', 'ClearKeys: ELAR (Launch) - Recipe: Space Trail Mix', 'relay_station', 4, 'ELAR'),
  ('RS.4.ELA02', 'ClearKeys: ELAR (Cruise) - Poem: Night Watch', 'relay_station', 4, 'ELAR'),
  ('RS.4.ELA03', 'ClearKeys: ELAR (Cruise) - Opinion: Every Class Needs a Class Pet', 'relay_station', 4, 'ELAR'),
  ('RS.4.ELA04', 'ClearKeys: ELAR (Orbit) - News Brief: Robot Club Wins', 'relay_station', 4, 'ELAR'),
  ('RS.5.ELA01', 'ClearKeys: ELAR (Launch) - Poem: Three Space Haiku', 'relay_station', 5, 'ELAR'),
  ('RS.5.ELA02', 'ClearKeys: ELAR (Cruise) - Argument: Every Student Should Learn to Type', 'relay_station', 5, 'ELAR'),
  ('RS.5.ELA03', 'ClearKeys: ELAR (Cruise) - How-To: Care for a Class Plant', 'relay_station', 5, 'ELAR'),
  ('RS.5.ELA04', 'ClearKeys: ELAR (Orbit) - News Article: Students Launch Weather Balloon', 'relay_station', 5, 'ELAR'),
  ('RS.3.NUM01', 'ClearKeys: Numbers (Launch) - Class Pet Vote', 'relay_station', 3, 'Math'),
  ('RS.3.NUM02', 'ClearKeys: Numbers (Cruise) - Reading Log', 'relay_station', 3, 'Math'),
  ('RS.3.NUM03', 'ClearKeys: Numbers (Cruise) - Measuring a Bean Plant', 'relay_station', 3, 'Math'),
  ('RS.3.NUM04', 'ClearKeys: Numbers (Orbit) - Field Trip Plan', 'relay_station', 3, 'Math'),
  ('RS.4.NUM01', 'ClearKeys: Numbers (Launch) - Weather Data', 'relay_station', 4, 'Math'),
  ('RS.4.NUM02', 'ClearKeys: Numbers (Cruise) - Texas by the Numbers', 'relay_station', 4, 'Math'),
  ('RS.4.NUM03', 'ClearKeys: Numbers (Cruise) - The Class Store', 'relay_station', 4, 'Math'),
  ('RS.4.NUM04', 'ClearKeys: Numbers (Orbit) - Texas Revolution Timeline', 'relay_station', 4, 'Math'),
  ('RS.5.NUM01', 'ClearKeys: Numbers (Launch) - Pancake Recipe', 'relay_station', 5, 'Math'),
  ('RS.5.NUM02', 'ClearKeys: Numbers (Cruise) - Apollo 11 by the Numbers', 'relay_station', 5, 'Math'),
  ('RS.5.NUM03', 'ClearKeys: Numbers (Cruise) - Race Results', 'relay_station', 5, 'Math'),
  ('RS.5.NUM04', 'ClearKeys: Numbers (Orbit) - A Timeline of Flight', 'relay_station', 5, 'Math')
ON CONFLICT (standard) DO NOTHING;

SELECT count(*) AS library_readings FROM cases WHERE standard ~ '^RS\.[345]\.(SCI|LOG|SS|BIO|ELA|NUM)0[1-4]$';
