-- Adds the 36 new 3rd/4th grade Group Chat cases (engine defaults to 'group_chat').
-- Safe to run once — if you ever re-run it, add "on conflict (standard) do nothing" at the end.
insert into cases (standard, title, grade, subject) values
  ('3.6A', 'The Raft Load', 3, 'Science'),
  ('3.6B', 'Rice Thinks She Is a Liquid', 3, 'Science'),
  ('3.6C', 'The Leaky Glasses', 3, 'Science'),
  ('3.6D', 'The All-Steel Umbrella', 3, 'Science'),
  ('3.7A', 'Feather Says Gravity Skips Her', 3, 'Science'),
  ('3.7B', 'Wallop Only Knows One Setting', 3, 'Science'),
  ('3.8A', 'Nothing Here Is Plugged In', 3, 'Science'),
  ('3.8B', 'A Bigger Ball Will Not Fix It', 3, 'Science'),
  ('3.9A', 'The Moon Is Tied to the Wrong Thing', 3, 'Science'),
  ('3.9B', 'Jupiter Says He Should Be First', 3, 'Science'),
  ('3.10A', 'One of You Is Making This Up', 3, 'Science'),
  ('3.10B', 'What Is Soil Even Made Of?', 3, 'Science'),
  ('3.10C', 'That Cannot Be the Same Hill', 3, 'Science'),
  ('3.11A', 'Nothing In This Room Came From Nature', 3, 'Science'),
  ('3.11B', 'The Barrel Was Full in April', 3, 'Science'),
  ('3.11C', 'It Is Fine, I Will Just Recycle It', 3, 'Science'),
  ('3.12A', 'Cleo Says Everything Died in November', 3, 'Science'),
  ('3.12B', 'The Herons Will Just Eat Something Else', 3, 'Science'),
  ('3.12C', 'The Flood Ruined Everything', 3, 'Science'),
  ('3.12D', 'Somebody Carved That', 3, 'Science'),
  ('3.13A', 'Duck Wants Different Feet', 3, 'Science'),
  ('3.13B', 'Pick Out the Grubs, Keep the Beetles', 3, 'Science'),
  ('4.6A', 'The Pen Pal Package', 4, 'Science'),
  ('4.6B', 'Whisk Will Not Give Up', 4, 'Science'),
  ('4.7', 'Somebody Is Tilting the Table', 4, 'Science'),
  ('4.8A', 'The Middle Marbles Quit', 4, 'Science'),
  ('4.8C', 'The Warming Glove Demo', 4, 'Science'),
  ('4.9A', 'Chill Takes Credit for Sunset', 4, 'Science'),
  ('4.10B', 'Where Is All This Sand Coming From?', 4, 'Science'),
  ('4.10C', 'Packing on Seven Days of Evidence', 4, 'Science'),
  ('4.11A', 'Wendy Says Just Use Wind', 4, 'Science'),
  ('4.11B', 'Plug Says Nobody Would Miss Him', 4, 'Science'),
  ('4.11C', 'Rigby Wants to Drill Here', 4, 'Science'),
  ('4.12A', 'Soil Thinks They Eat Her', 4, 'Science'),
  ('4.12C', 'The Seashell on the Hilltop', 4, 'Science'),
  ('4.13A', 'The Ugly One in the Window Box', 4, 'Science');
