
INSERT INTO cases (standard, title, engine, grade, subject) VALUES
  ('3.11A-EX', 'Exhibit Hall: Meet water', 'exhibit_hall', 3, 'Science'),
  ('3.12D-EX', 'Exhibit Hall: A plant in the rock', 'exhibit_hall', 3, 'Science'),
  ('4.12C-EX', 'Exhibit Hall: When Texas was a sea', 'exhibit_hall', 4, 'Science'),
  ('4.12B-EX', 'Exhibit Hall: Who eats whom', 'exhibit_hall', 4, 'Science'),
  ('5.12B-EX', 'Exhibit Hall: When the wolves came back', 'exhibit_hall', 5, 'Science'),
  ('5.10C-EX', 'Exhibit Hall: Shaped by wind, water, and ice', 'exhibit_hall', 5, 'Science'),
  ('5.12A-EX', 'Exhibit Hall: Portrait of a healthy pond', 'exhibit_hall', 5, 'Science'),
  ('5.13A-EX', 'Exhibit Hall: Same job, different body', 'exhibit_hall', 5, 'Science'),
  ('ELA.3.7C-EX', 'Exhibit Hall: Meet Rosa', 'exhibit_hall', 3, 'ELAR'),
  ('ELA.3.8B-EX', 'Exhibit Hall: The sister''s part', 'exhibit_hall', 3, 'ELAR'),
  ('ELA.4.8A-EX', 'Exhibit Hall: The cracked pot', 'exhibit_hall', 4, 'ELAR'),
  ('ELA.4.9B-EX', 'Exhibit Hall: Words that paint pictures', 'exhibit_hall', 4, 'ELAR'),
  ('ELA.4.8B-EX', 'Exhibit Hall: Portrait of Leo', 'exhibit_hall', 4, 'ELAR'),
  ('ELA.4.10B-EX', 'Exhibit Hall: How the article is built', 'exhibit_hall', 4, 'ELAR'),
  ('ELA.5.10A-EX', 'Exhibit Hall: Save the monarchs', 'exhibit_hall', 5, 'ELAR'),
  ('ELA.5.9B-EX', 'Exhibit Hall: Who is speaking?', 'exhibit_hall', 5, 'ELAR'),
  ('ELA.5.13C-EX', 'Exhibit Hall: Which sources belong', 'exhibit_hall', 5, 'ELAR'),
  ('ELA.5.10G-EX', 'Exhibit Hall: Tricks writers use', 'exhibit_hall', 5, 'ELAR'),
  ('SS.3.9A-EX', 'Exhibit Hall: Good citizens in action', 'exhibit_hall', 3, 'Social Studies'),
  ('SS.3.3C-EX', 'Exhibit Hall: People changed this place', 'exhibit_hall', 3, 'Social Studies'),
  ('SS.3.13A-EX', 'Exhibit Hall: Meet Benjamin Franklin', 'exhibit_hall', 3, 'Social Studies'),
  ('SS.3.7A-EX', 'Exhibit Hall: Who does this job?', 'exhibit_hall', 3, 'Social Studies'),
  ('SS.4.2E-EX', 'Exhibit Hall: Meet Stephen F. Austin', 'exhibit_hall', 4, 'Social Studies'),
  ('SS.4.1A-EX', 'Exhibit Hall: Four ways of living in Texas', 'exhibit_hall', 4, 'Social Studies'),
  ('SS.5.2A-EX', 'Exhibit Hall: Road to revolution', 'exhibit_hall', 5, 'Social Studies'),
  ('SS.5.19A-EX', 'Exhibit Hall: Rights in real life', 'exhibit_hall', 5, 'Social Studies'),
  ('SS.5.16D-EX', 'Exhibit Hall: Portrait of Lady Liberty', 'exhibit_hall', 5, 'Social Studies'),
  ('SS.5.5A-EX', 'Exhibit Hall: Four problems to solve', 'exhibit_hall', 5, 'Social Studies'),
  ('3.3G-EX', 'Exhibit Hall: The same amount', 'exhibit_hall', 3, 'Math'),
  ('3.4E-EX', 'Exhibit Hall: Every way to show 4 × 6', 'exhibit_hall', 3, 'Math'),
  ('3.2A-EX', 'Exhibit Hall: Portrait of 4,352', 'exhibit_hall', 3, 'Math'),
  ('3.6A-EX', 'Exhibit Hall: Every kind of shape', 'exhibit_hall', 3, 'Math'),
  ('4.3D-EX', 'Exhibit Hall: Which is bigger', 'exhibit_hall', 4, 'Math'),
  ('4.6B-EX', 'Exhibit Hall: Symmetry everywhere', 'exhibit_hall', 4, 'Math'),
  ('4.7A-EX', 'Exhibit Hall: Portrait of a right angle', 'exhibit_hall', 4, 'Math'),
  ('4.9A-EX', 'Exhibit Hall: Four ways to show the data', 'exhibit_hall', 4, 'Math'),
  ('5.3H-EX', 'Exhibit Hall: Not 2/5', 'exhibit_hall', 5, 'Math'),
  ('5.5-EX', 'Exhibit Hall: Every kind of rectangle', 'exhibit_hall', 5, 'Math'),
  ('5.8A-EX', 'Exhibit Hall: Portrait of the coordinate plane', 'exhibit_hall', 5, 'Math'),
  ('5.2A-EX', 'Exhibit Hall: Portrait of 3.47', 'exhibit_hall', 5, 'Math')
ON CONFLICT (standard) DO UPDATE SET
  title = EXCLUDED.title,
  engine = EXCLUDED.engine,
  grade = EXCLUDED.grade,
  subject = EXCLUDED.subject;

