const REASONS = [
  { id: "point", label: "Doesn't prove the point" },
  { id: "place", label: "Wrong place" },
  { id: "myth", label: "A myth or mistake" },
  { id: "picture", label: "Misleading picture" },
  { id: "topic", label: "True but off-topic" },
];

const DESERT = {
  id: "3.13A-EX",
  standard: "3.13A-EX",
  grade: 3,
  subject: "Science",
  kicker: "Exhibit Hall · 3.13A",
  title: "Built for the desert",
  job: "Show four ways a body part helps in the desert.",
  detail: "Each spot is a different problem. Choose the piece that proves it.",
  mythId: "hump",
  stamps: ["Picture", "Note", "Test"],
  spots: [
    { id: "heat", label: "Let heat out" },
    { id: "sand", label: "Keep sand out" },
    { id: "ground", label: "Stay off hot ground" },
    { id: "hide", label: "Hard to see" },
  ],
  reasons: REASONS,
  cards: [
    { id: "ears", title: "Huge ears", tag: "A fennec fox", image: "/maker/ears.jpg", role: "strong", reason: "point", job: "heat" },
    { id: "heat", title: "An ear test", tag: "Heat leaving the body", image: "", role: "strong", reason: "point", job: "heat", kind: "graph", bars: [{ label: "Big ears", height: "82%" }, { label: "Small ears", height: "34%" }] },
    { id: "seeds", title: "Water from seeds", tag: "A field note", image: "", role: "weak", reason: "topic", job: "none", kind: "text", text: "Kangaroo rats get the water they need from the seeds they eat." },
    { id: "lashes", title: "Thick eyelashes", tag: "A camel", image: "/maker/lashes.jpg", role: "strong", reason: "point", job: "sand" },
    { id: "legs", title: "Long legs", tag: "A roadrunner", image: "/maker/legs.jpg", role: "strong", reason: "point", job: "ground" },
    { id: "lizard", title: "Sand-colored skin", tag: "A horned lizard", image: "/maker/lizard.jpg", role: "strong", reason: "point", job: "hide" },
    { id: "feet", title: "Wide feet", tag: "A camel", image: "/maker/feet.jpg", role: "strong", reason: "point", job: "sink" },
    { id: "dunes", title: "Just the desert", tag: "Sand and sky", image: "/maker/dunes.jpg", role: "weak", reason: "point", job: "none" },
    { id: "hump", title: "A camel's hump", tag: "Stores water for long walks", image: "/maker/hump.jpg", role: "myth", reason: "myth", job: "none" },
    { id: "duck", title: "Webbed feet", tag: "A duck", image: "/maker/duck.jpg", role: "place", reason: "place", job: "none" },
    { id: "bear", title: "Thick fur", tag: "A polar bear", image: "/maker/bear.jpg", role: "place", reason: "place", job: "none" },
  ],
  lateTitle: "Late field note",
  late: "At noon the sand was hot enough to hurt a bare foot. An animal standing taller kept its body farther from the sand.",
  mcPrompt: "Which source shows a body part that lets heat out?",
  mc: ["Huge ears", "An ear test", "Wide feet", "A camel's hump"],
  mcAnswer: "Huge ears",
  msPrompt: "Which sources tell about staying off hot sand? Choose all that apply.",
  ms: ["Long legs", "Late field note", "Just the desert", "Thick fur"],
  msAnswers: ["Long legs", "Late field note"],
  tfPrompt: "Our sources tell how many days a camel can go without water.",
  tfIsFalse: true,
  icLead: "The late note helps most with",
  ic: ["stay off hot ground", "let heat out", "how long a camel can drink"],
  icAnswer: "stay off hot ground",
};

const PLANTS = {
  id: "4.13A-EX",
  standard: "4.13A-EX",
  grade: 4,
  subject: "Science",
  kicker: "Exhibit Hall · 4.13A",
  title: "Built to live here",
  job: "Show four plant parts that help a plant live where it lives.",
  detail: "Each spot is a different problem. Choose the piece that proves it.",
  mythId: "spines",
  stamps: ["Picture", "Note", "Test"],
  spots: [
    { id: "keep", label: "Keep water in" },
    { id: "reach", label: "Reach deep water" },
    { id: "store", label: "Store water" },
    { id: "float", label: "Float on water" },
  ],
  reasons: REASONS,
  cards: [
    { id: "wax", title: "Waxy leaf", tag: "Water beads and rolls off", image: "/maker/wax.jpg", role: "strong", reason: "point", job: "keep" },
    { id: "test", title: "A water test", tag: "Water lost in one hot day", image: "", role: "strong", reason: "point", job: "keep", kind: "graph", bars: [{ label: "Waxy leaf", height: "28%" }, { label: "Plain leaf", height: "84%" }] },
    { id: "roots", title: "Deep roots", tag: "A mesquite", image: "/maker/roots.jpg", role: "strong", reason: "point", job: "reach" },
    { id: "stem", title: "Thick stem", tag: "A cactus", image: "/maker/stem.jpg", role: "strong", reason: "point", job: "store" },
    { id: "lily", title: "Lily pads", tag: "A pond plant", image: "/maker/lily.jpg", role: "strong", reason: "point", job: "float" },
    { id: "lean", title: "A lean toward the light", tag: "A houseplant", image: "/maker/lean.jpg", role: "weak", reason: "topic", job: "none" },
    { id: "spines", title: "Water in the spines", tag: "A common mistake", image: "", role: "myth", reason: "myth", job: "none", kind: "text", text: "A cactus stores its water in the spines." },
    { id: "fur", title: "Thick fur", tag: "A polar bear", image: "/maker/bear.jpg", role: "place", reason: "place", job: "none" },
    { id: "pretty", title: "Just a red flower", tag: "Pretty, but no job shown", image: "", role: "weak", reason: "point", job: "none", kind: "text", text: "The flower is red and easy to see." },
  ],
  lateTitle: "Late field note",
  late: "After two dry weeks, the soil on top was dust. Deeper down, around the long roots, the soil was still damp.",
  mcPrompt: "Which source shows a part that keeps water from leaving the plant?",
  mc: ["Waxy leaf", "A water test", "Lily pads", "Water in the spines"],
  mcAnswer: "Waxy leaf",
  msPrompt: "Which sources tell about reaching water? Choose all that apply.",
  ms: ["Deep roots", "Late field note", "Thick fur", "A lean toward the light"],
  msAnswers: ["Deep roots", "Late field note"],
  tfPrompt: "Our sources say a cactus stores its water in the spines.",
  tfIsFalse: true,
  icLead: "The late note helps most with",
  ic: ["reach deep water", "float on water", "how pretty a flower is"],
  icAnswer: "reach deep water",
};

const KITE = {
  id: "ELA.3.8A-EX",
  standard: "ELA.3.8A-EX",
  grade: 3,
  subject: "ELAR",
  kicker: "Exhibit Hall · 3.8A",
  title: "The lost kite",
  job: "Prove the theme is keep trying. The topic is only the kite.",
  detail: "Max's kite hit the ground. He taped the stick and tried again. The wind took it, and it fell. He asked his sister to hold the string. They tried once more. The kite climbed, and Max laughed.",
  mythId: "title",
  stamps: ["Picture", "Note", "Test"],
  spots: [
    { id: "again", label: "Tries again" },
    { id: "help", label: "Asks for help" },
    { id: "keeps", label: "Doesn't quit" },
    { id: "lesson", label: "Shows the lesson" },
  ],
  reasons: REASONS,
  cards: [
    { id: "tape", title: "Taped the stick", tag: "From the story", image: "", role: "strong", reason: "point", job: "again", kind: "text", text: "He taped the stick and tried again." },
    { id: "sister", title: "Asked his sister", tag: "From the story", image: "", role: "strong", reason: "point", job: "help", kind: "text", text: "He asked his sister to hold the string." },
    { id: "more", title: "Tried once more", tag: "From the story", image: "", role: "strong", reason: "point", job: "keeps", kind: "text", text: "They tried once more." },
    { id: "climbed", title: "The kite climbed", tag: "From the story", image: "", role: "strong", reason: "point", job: "lesson", kind: "text", text: "The kite climbed, and Max laughed." },
    { id: "about", title: "About a kite", tag: "A topic, not a theme", image: "", role: "weak", reason: "topic", job: "none", kind: "text", text: "This story is about a kite." },
    { id: "other", title: "A different story", tag: "Not this story", image: "", role: "place", reason: "place", job: "none", kind: "text", text: "Lila sold lemonade and shared the money." },
    { id: "title", title: "The title is the theme", tag: "A common mistake", image: "", role: "myth", reason: "myth", job: "none", kind: "text", text: "The theme is the title, The Lost Kite." },
    { id: "hair", title: "Curly hair", tag: "True, but not the theme", image: "", role: "weak", reason: "point", job: "none", kind: "text", text: "Max has curly hair." },
    { id: "photo", title: "A kite on the grass", tag: "A picture with no story", image: "/maker/kite.jpg", role: "weak", reason: "picture", job: "none" },
  ],
  lateTitle: "Late field note",
  late: "A reader wrote, The kite matters, but the story is really about not stopping after it fell.",
  mcPrompt: "Which source shows Max trying again after the kite fell?",
  mc: ["Taped the stick", "About a kite", "Curly hair", "The title is the theme"],
  mcAnswer: "Taped the stick",
  msPrompt: "Which sources help prove the theme, not just the topic? Choose all that apply.",
  ms: ["Tried once more", "Late field note", "About a kite", "A kite on the grass"],
  msAnswers: ["Tried once more", "Late field note"],
  tfPrompt: "Our sources say the theme of a story is always its title.",
  tfIsFalse: true,
  icLead: "The late note helps most with",
  ic: ["shows the lesson", "what Max looks like", "a different story"],
  icAnswer: "shows the lesson",
};

const TEXAS = {
  id: "SS.4.3A-EX",
  standard: "SS.4.3A-EX",
  grade: 4,
  subject: "Social Studies",
  kicker: "Exhibit Hall · 4.3A",
  title: "Why Texans fought",
  job: "Show four causes of the Texas Revolution. Leave out what happened later.",
  detail: "A cause comes before the fighting and helps explain why it started. An effect comes after.",
  mythId: "alamo",
  stamps: ["Picture", "Note", "Test"],
  spots: [
    { id: "law", label: "Stopped new settlers" },
    { id: "rules", label: "Took away the old rules" },
    { id: "austin", label: "Jailed a leader" },
    { id: "cannon", label: "A fight over a cannon" },
  ],
  reasons: REASONS,
  cards: [
    { id: "law", title: "A law in 1830", tag: "April 6, 1830", image: "", role: "strong", reason: "point", job: "law", kind: "text", text: "The Law of April 6, 1830 stopped new settlers from coming to Texas from the United States." },
    { id: "rules", title: "The old rules ended", tag: "Constitution of 1824", image: "", role: "strong", reason: "point", job: "rules", kind: "text", text: "Santa Anna ended the Mexican Constitution of 1824, the set of rules many Texans had counted on." },
    { id: "austin", title: "Austin was jailed", tag: "Mexico City", image: "", role: "strong", reason: "point", job: "austin", kind: "text", text: "Stephen F. Austin was jailed in Mexico City after he spoke up for the settlers." },
    { id: "cannon", title: "The Gonzales cannon", tag: "Settlers would not give it back, 1835", image: "/maker/cannon.jpg", role: "strong", reason: "point", job: "cannon" },
    { id: "republic", title: "Texas becomes a republic", tag: "An effect, not a cause", image: "", role: "weak", reason: "point", job: "none", kind: "text", text: "After the fighting, Texas became its own republic." },
    { id: "flowers", title: "Spring wildflowers", tag: "True, but off topic", image: "", role: "weak", reason: "topic", job: "none", kind: "text", text: "Bluebonnets cover the hills in spring." },
    { id: "alamo", title: "It started at the Alamo", tag: "A common mistake", image: "", role: "myth", reason: "myth", job: "none", kind: "text", text: "The Texas Revolution started at the Alamo." },
    { id: "sanjac", title: "The win at San Jacinto", tag: "A later battle", image: "", role: "place", reason: "place", job: "none", kind: "text", text: "Sam Houston's army won at San Jacinto in April 1836." },
  ],
  lateTitle: "Late field note",
  late: "Settlers at Gonzales refused to give a small cannon back. That standoff came after years of anger, not before the laws and the jail.",
  mcPrompt: "Which source shows a law that stopped new settlers?",
  mc: ["A law in 1830", "The Gonzales cannon", "Texas becomes a republic", "It started at the Alamo"],
  mcAnswer: "A law in 1830",
  msPrompt: "Which sources are about a cause, not something that happened later? Choose all that apply.",
  ms: ["Austin was jailed", "The old rules ended", "Texas becomes a republic", "The win at San Jacinto"],
  msAnswers: ["Austin was jailed", "The old rules ended"],
  tfPrompt: "Our sources say the Texas Revolution started at the Alamo.",
  tfIsFalse: true,
  icLead: "The late note helps most with",
  ic: ["a fight over a cannon", "spring wildflowers", "Texas becomes a republic"],
  icAnswer: "a fight over a cannon",
};

const CASES = {
  "3.13A-EX": DESERT,
  "4.13A-EX": PLANTS,
  "ELA.3.8A-EX": KITE,
  "SS.4.3A-EX": TEXAS,
};

export function getExhibitCase(standard) {
  return CASES[standard] || null;
}

export function publicExhibit(standard) {
  const exhibit = getExhibitCase(standard);
  if (!exhibit) return null;
  return {
    id: exhibit.id,
    standard: exhibit.standard,
    kicker: exhibit.kicker,
    title: exhibit.title,
    job: exhibit.job,
    detail: exhibit.detail,
    stamps: exhibit.stamps,
    spots: exhibit.spots,
    reasons: exhibit.reasons,
    cards: exhibit.cards.map(({ id, title, tag, image, kind, text, bars }) => ({ id, title, tag, image, kind, text, bars })),
    lateTitle: exhibit.lateTitle,
    late: exhibit.late,
    mcPrompt: exhibit.mcPrompt,
    mc: exhibit.mc,
    msPrompt: exhibit.msPrompt,
    ms: exhibit.ms,
    tfPrompt: exhibit.tfPrompt,
    icLead: exhibit.icLead,
    ic: exhibit.ic,
  };
}
