const GALLERY = [
  { id: "a", label: "A clear example" },
  { id: "b", label: "A clear example" },
  { id: "c", label: "A clear example" },
  { id: "edge", label: "The tricky one" },
];

function text(id, title, body, job, reason = "point", role = "strong") {
  return { id, title, tag: role === "myth" ? "A common mistake" : "A note", image: "", role, reason, job, kind: "text", text: body };
}
function photo(id, title, tag, image, job) {
  return { id, title, tag, image, role: "strong", reason: "point", job };
}
function drawn(id, title, tag, model, job) {
  return { id, title, tag, image: "", role: "strong", reason: "point", job, kind: "model", model };
}
function exhibit(fields) {
  return { stamps: ["Picture", "Note", "Test"], lateTitle: "Late field note", layout: "kinds", spots: GALLERY, ...fields };
}

export function kindCases(reasons) {
  const wrap = (item) => ({ ...item, reasons });
  return {
    "3.11C-EX": wrap(exhibit({
      id: "3.11C-EX", standard: "3.11C-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.11C", title: "Every careful use",
      job: "Show every kind of careful use. The tricky one still belongs.",
      detail: "Reduce means use less. Reuse means use it again. Recycle means make it into something new. Fixing something is still reduce.",
      mythId: "much",
      cards: [
        text("can", "A rinsed can", "A rinsed can goes in the recycling bin.", "kind"),
        text("jar", "The jar again", "A jar holds pencils instead of going in the trash.", "kind"),
        text("bag", "No new bag", "A cloth bag means you do not take a new plastic one.", "kind"),
        text("napkin", "One napkin", "Taking one napkin instead of a handful is using less.", "kind"),
        photo("fix", "Fix the strap", "Sew it, don't replace it", "/maker/kinds-repair.jpg", "edge"),
        text("much", "Use as much as you want", "If I recycle, I can use as much as I want.", "none", "myth", "myth"),
        text("trash", "A full trash bag", "A full trash bag is not recycling just because someone calls the bag blue.", "none", "picture", "weak"),
        text("toy", "A brand-new toy", "Buying a new toy is not reduce, reuse, or recycle.", "none", "topic", "weak"),
      ],
      late: "Sewing the strap keeps a backpack in use. That is using less, not buying new.",
      mcPrompt: "Which source is recycling?",
      mc: ["A rinsed can", "Use as much as you want", "A full trash bag", "A brand-new toy"],
      mcAnswer: "A rinsed can",
      msPrompt: "Which sources mean using less or using it again? Choose all that apply.",
      ms: ["The jar again", "One napkin", "Use as much as you want", "A brand-new toy"],
      msAnswers: ["The jar again", "One napkin"],
      tfPrompt: "Our sources say recycling means you can use as much as you want.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["fixing the strap", "a trash bag", "a new toy"],
      icAnswer: "fixing the strap",
    })),
    "4.7-EX": wrap(exhibit({
      id: "4.7-EX", standard: "4.7-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.7", title: "Every kind of force",
      job: "Show every kind of force. The tricky one still belongs.",
      detail: "A force can be a push, a pull, friction, or gravity. Some forces act without touching.",
      mythId: "hands",
      cards: [
        text("push", "A push", "A push starts the swing. Hands touch the swing.", "kind"),
        text("slide", "Friction on the slide", "Friction slows you down on the slide.", "kind"),
        text("ball", "Gravity", "Gravity pulls the ball down toward Earth.", "kind"),
        text("drawer", "A pull", "A pull opens the drawer. Hands touch the handle.", "kind"),
        photo("clip", "A pull without touching", "The magnet moves the clip", "/maker/kinds-magnet.jpg", "edge"),
        text("hands", "Only touching counts", "A force only counts when hands are touching the object.", "none", "myth", "myth"),
        text("lamp", "A glowing lamp", "A glowing lamp is energy being used. It is not a force on this wall.", "none", "place", "place"),
        text("wants", "The ball wants to stop", "Saying the ball wants to stop does not name a force.", "none", "topic", "weak"),
      ],
      late: "The magnet pulls the paper clip across the table. Nothing is touching the clip until they meet.",
      mcPrompt: "Which source is gravity?",
      mc: ["Gravity", "Only touching counts", "A glowing lamp", "The ball wants to stop"],
      mcAnswer: "Gravity",
      msPrompt: "Which sources are contact forces? Choose all that apply.",
      ms: ["A push", "A pull", "Only touching counts", "A glowing lamp"],
      msAnswers: ["A push", "A pull"],
      tfPrompt: "Our sources say a force only counts when hands are touching the object.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the magnet pulls without a hand on the clip", "a lamp", "what the ball wants"],
      icAnswer: "the magnet pulls without a hand on the clip",
    })),
    "5.6A-EX": wrap(exhibit({
      id: "5.6A-EX", standard: "5.6A-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.6A", title: "Every kind of test",
      job: "Show every kind of physical-property test. The tricky one still belongs.",
      detail: "Mass, magnetism, solubility, and heat can be tested. A test can show that something does not stick.",
      mythId: "all",
      cards: [
        text("mass", "Mass on a balance", "A balance measures mass. Color does not.", "kind"),
        photo("steel", "A steel clip", "The magnet sticks", "/maker/kinds-magnet.jpg", "kind"),
        text("sugar", "Sugar in water", "Sugar dissolves. That test is solubility.", "kind"),
        text("spoon", "A warm spoon", "A metal spoon warms in hot water. That is heat moving through it.", "kind"),
        photo("can", "An aluminum can", "The magnet does not stick", "/maker/kinds-aluminum.jpg", "edge"),
        text("all", "Every metal sticks", "Every metal sticks to a magnet.", "none", "myth", "myth"),
        text("red", "It is red", "It is red, so it has more mass.", "none", "topic", "weak"),
        text("rust", "The nail rusted", "The nail rusted, so that measurement is only a physical property.", "none", "picture", "weak"),
      ],
      late: "Aluminum is a metal. A magnet test can still say no. The no is a result.",
      mcPrompt: "Which source is a solubility test?",
      mc: ["Sugar in water", "Every metal sticks", "It is red", "The nail rusted"],
      mcAnswer: "Sugar in water",
      msPrompt: "Which sources are physical tests? Choose all that apply.",
      ms: ["Mass on a balance", "A warm spoon", "Every metal sticks", "It is red"],
      msAnswers: ["Mass on a balance", "A warm spoon"],
      tfPrompt: "Our sources say every metal sticks to a magnet.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the can does not stick, and the test still counts", "the color red", "rust"],
      icAnswer: "the can does not stick, and the test still counts",
    })),
    "ELA.3.10A-EX": wrap(exhibit({
      id: "ELA.3.10A-EX", standard: "ELA.3.10A-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.10A", title: "Every kind of purpose",
      job: "Show every kind of author's purpose. The tricky one still belongs.",
      detail: "Authors inform, entertain, or persuade. One text can do more than one of those.",
      mythId: "funny",
      cards: [
        text("weather", "A weather report", "It tells what the sky will do. The purpose is to inform.", "kind"),
        text("silly", "A silly story", "It is meant to make you laugh. The purpose is to entertain.", "kind"),
        text("vote", "Vote for the garden", "The poster asks you to choose the class garden. The purpose is to persuade.", "kind"),
        text("steps", "How to plant a seed", "The steps tell you how. The purpose is to inform.", "kind"),
        text("comic", "A funny comic", "It makes you laugh, and the last box says, \"Bring a bottle tomorrow.\"", "edge"),
        text("funny", "Funny cannot persuade", "If a text is funny, it cannot persuade.", "none", "myth", "myth"),
        text("list", "Apples and milk", "A shopping list has no purpose beyond the list.", "none", "topic", "weak"),
        text("born", "Born in May", "The author was born in May. That is not the purpose of the text.", "none", "place", "place"),
      ],
      late: "The comic's last box asks the reader to do something. The joke is not the only job.",
      mcPrompt: "Which source is written to persuade?",
      mc: ["Vote for the garden", "Funny cannot persuade", "Apples and milk", "Born in May"],
      mcAnswer: "Vote for the garden",
      msPrompt: "Which sources inform? Choose all that apply.",
      ms: ["A weather report", "How to plant a seed", "Funny cannot persuade", "Born in May"],
      msAnswers: ["A weather report", "How to plant a seed"],
      tfPrompt: "Our sources say a funny text cannot persuade.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the comic asks you to bring a bottle", "a shopping list", "a birthday"],
      icAnswer: "the comic asks you to bring a bottle",
    })),
    "ELA.4.9E-EX": wrap(exhibit({
      id: "ELA.4.9E-EX", standard: "ELA.4.9E-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.9E", title: "Every piece of the argument",
      job: "Show every kind of piece this argument uses. The tricky one still belongs.",
      detail: "An argument has a claim, facts that support it, and an audience. A chart can be evidence.",
      mythId: "want",
      cards: [
        text("claim", "The claim", "The school should open the library at lunch.", "kind"),
        text("forty", "Forty students", "Forty students had no quiet place to read.", "kind"),
        text("who", "Written to the principal", "The letter is for the principal, the person who can decide.", "kind"),
        text("quiet", "A quiet place", "A quiet place helps students finish homework.", "kind"),
        { id: "chart", title: "Checkout counts", tag: "Evidence", image: "", role: "strong", reason: "point", job: "edge", kind: "graph", bars: [{ label: "Mon", height: "45%" }, { label: "Wed", height: "70%" }, { label: "Fri", height: "90%" }] },
        text("want", "Just I want it", "An argument is just saying I want it.", "none", "myth", "myth"),
        text("volcano", "Another story", "The volcano erupted on the judge. That is a different text.", "none", "place", "place"),
        text("chairs", "Blue chairs", "The chairs are blue. That does not support the claim.", "none", "topic", "weak"),
      ],
      late: "The Friday bar is the tallest. The chart is counting checkouts, not decorating the page.",
      mcPrompt: "Which source is the claim?",
      mc: ["The claim", "Just I want it", "Another story", "Blue chairs"],
      mcAnswer: "The claim",
      msPrompt: "Which sources support the claim? Choose all that apply.",
      ms: ["Forty students", "A quiet place", "Just I want it", "Blue chairs"],
      msAnswers: ["Forty students", "A quiet place"],
      tfPrompt: "Our sources say an argument is just saying I want it.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the chart is evidence", "another story", "blue chairs"],
      icAnswer: "the chart is evidence",
    })),
    "ELA.5.10D-EX": wrap(exhibit({
      id: "ELA.5.10D-EX", standard: "ELA.5.10D-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.10D", title: "Every kind of feature",
      job: "Show every kind of text feature. The tricky one still belongs.",
      detail: "A feature helps a reader find or understand information. A tiny note at the bottom can be one.",
      mythId: "decor",
      cards: [
        text("head", "A heading", "A heading names what that section is about.", "kind"),
        text("diagram", "A labeled diagram", "Labels on the drawing name the parts of the pond.", "kind"),
        text("bold", "A bold word", "The bold word marks a term the reader needs.", "kind"),
        text("caption", "A caption", "The caption tells what the photo shows.", "kind"),
        text("foot", "A footnote", "A tiny number leads to a note that says where the fact came from.", "edge"),
        text("decor", "Pictures are decoration", "Pictures are only decoration.", "none", "myth", "myth"),
        text("border", "A fancy border", "A decorative border does not give information.", "none", "picture", "weak"),
        text("kite", "A story sentence", "Once the kite was lost in the tree. That sentence is not a text feature.", "none", "place", "place"),
      ],
      late: "The footnote is small on purpose. It still tells the reader where to check the fact.",
      mcPrompt: "Which source names a section?",
      mc: ["A heading", "Pictures are decoration", "A fancy border", "A story sentence"],
      mcAnswer: "A heading",
      msPrompt: "Which sources add information to a picture or a word? Choose all that apply.",
      ms: ["A labeled diagram", "A caption", "Pictures are decoration", "A fancy border"],
      msAnswers: ["A labeled diagram", "A caption"],
      tfPrompt: "Our sources say pictures are only decoration.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the footnote says where the fact came from", "a border", "a story sentence"],
      icAnswer: "the footnote says where the fact came from",
    })),
    "SS.3.5A-EX": wrap(exhibit({
      id: "SS.3.5A-EX", standard: "SS.3.5A-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.5A", title: "Every kind of money choice",
      job: "Show every kind of choice people make with money. The tricky one still belongs.",
      detail: "People earn, spend, save, and donate. Donating is not the same as wasting.",
      mythId: "waste",
      cards: [
        text("earn", "Wages", "Wages from a job are money you earn.", "kind"),
        text("spend", "A notebook", "Buying a notebook is spending.", "kind"),
        text("save", "Coins for later", "Putting coins aside for a later goal is saving.", "kind"),
        text("bank", "A savings jar", "A jar for a bike is still saving.", "kind"),
        text("give", "A food drive", "Money for a food drive leaves your hands, and it is not spent on yourself.", "edge"),
        text("waste", "Giving is wasting", "Giving money away is the same as wasting it.", "none", "myth", "myth"),
        text("tag", "A price tag", "A price tag by itself is not a choice you made.", "none", "topic", "weak"),
        text("double", "It comes back doubled", "If you donate, the money comes back doubled.", "none", "point", "weak"),
      ],
      late: "The food drive uses the money to buy food for other people. That is donating.",
      mcPrompt: "Which source is spending?",
      mc: ["A notebook", "Giving is wasting", "A price tag", "It comes back doubled"],
      mcAnswer: "A notebook",
      msPrompt: "Which sources keep money for later? Choose all that apply.",
      ms: ["Coins for later", "A savings jar", "Giving is wasting", "A price tag"],
      msAnswers: ["Coins for later", "A savings jar"],
      tfPrompt: "Our sources say giving money away is the same as wasting it.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the food drive is a donation", "a price tag", "money coming back doubled"],
      icAnswer: "the food drive is a donation",
    })),
    "SS.4.6A-EX": wrap(exhibit({
      id: "SS.4.6A-EX", standard: "SS.4.6A-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.6A", title: "Every kind of Texas region",
      job: "Show every kind of Texas region. The tricky one still belongs.",
      detail: "Texas has four physical regions. Mountains and basins are one of them, even far from the coast.",
      mythId: "only",
      cards: [
        photo("coast", "Coastal Plains", "Low land by the Gulf", "/maker/kinds-coast.jpg", "kind"),
        photo("hills", "North Central Plains", "Rolling land and more trees", "/maker/kinds-hills.jpg", "kind"),
        photo("flat", "Great Plains", "High, flat grassland", "/maker/kinds-plains.jpg", "kind"),
        text("marsh", "A Gulf marsh", "A marsh along the Gulf is still part of the Coastal Plains.", "kind"),
        photo("west", "Mountains and Basins", "Dry basins and real mountains", "/maker/kinds-mountains.jpg", "edge"),
        text("only", "Only plains and beaches", "Texas is only plains and beaches.", "none", "myth", "myth"),
        text("colorado", "Mountains in Colorado", "These peaks are the Rocky Mountains in Colorado, not a Texas region.", "none", "place", "place"),
        text("flag", "The Texas flag", "The flag is a symbol of Texas. It is not a physical region.", "none", "topic", "weak"),
      ],
      late: "The Mountains and Basins region is in far West Texas. Guadalupe Peak, the highest point in Texas, is there.",
      mcPrompt: "Which source is the Coastal Plains?",
      mc: ["Coastal Plains", "Only plains and beaches", "Mountains in Colorado", "The Texas flag"],
      mcAnswer: "Coastal Plains",
      msPrompt: "Which sources are Texas regions that are not the coast? Choose all that apply.",
      ms: ["North Central Plains", "Great Plains", "Only plains and beaches", "The Texas flag"],
      msAnswers: ["North Central Plains", "Great Plains"],
      tfPrompt: "Our sources say Texas is only plains and beaches.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["Mountains and Basins are in West Texas", "Colorado", "the flag"],
      icAnswer: "Mountains and Basins are in West Texas",
    })),
    "SS.5.15A-EX": wrap(exhibit({
      id: "SS.5.15A-EX", standard: "SS.5.15A-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.15A", title: "Every kind of branch",
      job: "Show every kind of branch in the U.S. government. The tricky one still belongs.",
      detail: "Congress writes laws. The president and the departments carry them out. Courts decide what they mean.",
      mythId: "alone",
      cards: [
        text("congress", "Congress", "Congress writes the laws. That is the legislative branch.", "kind"),
        text("carry", "Carry the laws out", "The president and the departments carry the laws out. That is the executive branch.", "kind"),
        text("bill", "A bill in Congress", "A bill has to pass Congress before it can become a law.", "kind"),
        text("sign", "Sign or veto", "The president can sign a bill or veto it. That is still the executive branch.", "kind"),
        text("court", "The Supreme Court", "The Court decides what a law means. It does not write the law.", "edge"),
        text("alone", "The president alone", "The president makes every law alone.", "none", "myth", "myth"),
        text("school", "A school principal", "A school principal is not a branch of the U.S. government.", "none", "place", "place"),
        text("most", "The biggest branch", "The branch with the most people is the only one that matters.", "none", "topic", "weak"),
      ],
      late: "A court can say a law does not fit the Constitution. That power is the judicial branch.",
      mcPrompt: "Which source is the legislative branch?",
      mc: ["Congress", "The president alone", "A school principal", "The biggest branch"],
      mcAnswer: "Congress",
      msPrompt: "Which sources are about the executive branch? Choose all that apply.",
      ms: ["Carry the laws out", "Sign or veto", "The president alone", "A school principal"],
      msAnswers: ["Carry the laws out", "Sign or veto"],
      tfPrompt: "Our sources say the president makes every law alone.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the Court is the judicial branch", "a principal", "the biggest branch"],
      icAnswer: "the Court is the judicial branch",
    })),
    "3.3C-EX": wrap(exhibit({
      id: "3.3C-EX", standard: "3.3C-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.3C", title: "Every kind of unit fraction",
      job: "Show every kind of unit fraction. The tricky one still belongs.",
      detail: "A unit fraction has a 1 on top. The pieces have to be equal. A bigger denominator makes a smaller piece.",
      mythId: "bigger",
      cards: [
        drawn("half", "1/2", "One of two equal parts", { type: "fraction", parts: 2, shaded: 1 }, "kind"),
        drawn("third", "1/3", "One of three equal parts", { type: "fraction", parts: 3, shaded: 1 }, "kind"),
        drawn("fourth", "1/4", "One of four equal parts", { type: "fraction", parts: 4, shaded: 1 }, "kind"),
        drawn("sixth", "1/6", "One of six equal parts", { type: "fraction", parts: 6, shaded: 1 }, "kind"),
        drawn("eighth", "1/8", "One of eight equal parts", { type: "fraction", parts: 8, shaded: 1, note: "Smaller piece, still a unit fraction" }, "edge"),
        text("bigger", "8 means bigger", "1/8 is bigger than 1/2 because 8 is bigger than 2.", "none", "myth", "myth"),
        text("three", "3/4", "Three of four parts are shaded. The top is not 1, so this is not a unit fraction.", "none", "topic", "weak"),
        text("uneven", "Unequal parts", "The bar is split into pieces that are not the same size, and the label says 1/4.", "none", "picture", "weak"),
      ],
      late: "Fold the same strip into eight equal parts. One of those parts is 1/8.",
      mcPrompt: "Which source is one half?",
      mc: ["1/2", "8 means bigger", "3/4", "Unequal parts"],
      mcAnswer: "1/2",
      msPrompt: "Which sources are unit fractions with a denominator bigger than 2? Choose all that apply.",
      ms: ["1/3", "1/4", "8 means bigger", "3/4"],
      msAnswers: ["1/3", "1/4"],
      tfPrompt: "Our sources say 1/8 is bigger than 1/2 because 8 is bigger than 2.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["one equal part out of eight", "3/4", "unequal parts"],
      icAnswer: "one equal part out of eight",
    })),
    "4.2B-EX": wrap(exhibit({
      id: "4.2B-EX", standard: "4.2B-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.2B", title: "Every way to show 3 tenths",
      job: "Show every way to represent 3 tenths. The tricky one still belongs.",
      detail: "3 tenths can look like a word, a decimal, or a fraction. 0.30 is the same amount as 0.3.",
      mythId: "thirty",
      cards: [
        text("word", "Three tenths", "The words name 3 out of 10 equal parts.", "kind"),
        drawn("dec", "0.3", "3 in the tenths place", { type: "place", cells: [{ label: "ones", value: "0" }, { label: "tenths", value: "3" }] }, "kind"),
        text("frac", "3/10", "3/10 is three of ten equal parts.", "kind"),
        text("line", "On a number line", "0.3 is three tenths of the way from 0 to 1.", "kind"),
        drawn("zero", "0.30", "30 hundredths", { type: "place", cells: [{ label: "ones", value: "0" }, { label: "tenths", value: "3" }, { label: "hundredths", value: "0" }] }, "edge"),
        text("thirty", "30 is bigger", "0.30 is bigger than 0.3 because 30 is bigger than 3.", "none", "myth", "myth"),
        text("hun", "0.03", "0.03 is 3 hundredths, not 3 tenths.", "none", "point", "weak"),
        text("whole", "The 3 in 43", "The 3 in 43 is not a tenth.", "none", "place", "place"),
      ],
      late: "30 hundredths is 3 tenths. The extra zero does not make the amount bigger.",
      mcPrompt: "Which source is the fraction for 3 tenths?",
      mc: ["3/10", "30 is bigger", "0.03", "The 3 in 43"],
      mcAnswer: "3/10",
      msPrompt: "Which sources name 3 tenths without an extra zero? Choose all that apply.",
      ms: ["Three tenths", "0.3", "30 is bigger", "0.03"],
      msAnswers: ["Three tenths", "0.3"],
      tfPrompt: "Our sources say 0.30 is bigger than 0.3 because 30 is bigger than 3.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["0.30 is the same amount as 0.3", "0.03", "the 3 in 43"],
      icAnswer: "0.30 is the same amount as 0.3",
    })),
    "5.4A-EX": wrap(exhibit({
      id: "5.4A-EX", standard: "5.4A-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.4A", title: "Prime or composite",
      job: "Show prime and composite numbers. The tricky one still belongs.",
      detail: "A prime number has exactly two factors, 1 and itself. 2 is prime. 1 is not.",
      mythId: "one",
      cards: [
        text("seven", "7 is prime", "The only factors of 7 are 1 and 7.", "kind"),
        text("nine", "9 is composite", "The factors of 9 are 1, 3, and 9.", "kind"),
        text("fifteen", "15 is composite", "The factors of 15 are 1, 3, 5, and 15.", "kind"),
        text("four", "4 is composite", "The factors of 4 are 1, 2, and 4.", "kind"),
        text("two", "2 is prime", "2 is even, and its only factors are 1 and 2.", "edge"),
        text("one", "1 is prime", "1 is a prime number because it is small.", "none", "myth", "myth"),
        text("odd", "9 is prime", "9 is prime because it is odd.", "none", "point", "weak"),
        text("jersey", "A jersey number", "A number on a jersey is not a question about factors.", "none", "topic", "weak"),
      ],
      late: "2 is the only even prime. Every other even number has 2 as a factor.",
      mcPrompt: "Which source is a prime number greater than 2?",
      mc: ["7 is prime", "1 is prime", "9 is prime", "A jersey number"],
      mcAnswer: "7 is prime",
      msPrompt: "Which sources are composite? Choose all that apply.",
      ms: ["9 is composite", "4 is composite", "1 is prime", "9 is prime"],
      msAnswers: ["9 is composite", "4 is composite"],
      tfPrompt: "Our sources say 1 is a prime number because it is small.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["2 is the only even prime", "1 is prime", "a jersey"],
      icAnswer: "2 is the only even prime",
    })),
  };
}
