function text(id, title, body, job, reason = "point", role = "strong") {
  return { id, title, tag: role === "myth" ? "A common mistake" : "A note", image: "", role, reason, job, kind: "text", text: body };
}
function photo(id, title, tag, image, job, reason = "point", role = "strong") {
  return { id, title, tag, image, role, reason, job };
}
function model(id, title, tag, modelValue, job, reason = "point", role = "strong") {
  return { id, title, tag, image: "", role, reason, job, kind: "model", model: modelValue };
}
function exhibit(fields) {
  return {
    stamps: ["Picture", "Note", "Test"],
    lateTitle: "Late field note",
    ...fields,
  };
}

export function lockedCases(reasons) {
  const withReasons = (item) => ({ ...item, reasons });
  return {
    "3.11A-EX": withReasons(exhibit({
      id: "3.11A-EX", standard: "3.11A-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.11A", title: "Meet water",
      job: "Show four ways people use water.",
      detail: "A pretty picture of water is not enough. The source has to show a use.",
      mythId: "faucet",
      spots: [
        { id: "farm", label: "Farming" },
        { id: "move", label: "Moving goods" },
        { id: "build", label: "Building" },
        { id: "make", label: "Making a product" },
      ],
      cards: [
        photo("farm", "Farm sprinklers", "Watering crops", "/maker/sprinkler.jpg", "farm"),
        photo("move", "A river barge", "Carrying goods", "/maker/barge.jpg", "move"),
        photo("build", "Wet concrete", "Water mixed into the build", "/maker/concrete.jpg", "build"),
        photo("make", "Rolls of paper", "A mill uses water", "/maker/paper.jpg", "make"),
        photo("pretty", "Just a waterfall", "Pretty, but no use shown", "/maker/pond.jpg", "none", "topic", "weak"),
        text("wind", "Wind power", "This card is about wind turning a turbine, not about water.", "none", "place", "place"),
        text("faucet", "Water from a faucet", "Water is not a natural resource because it comes from a faucet.", "none", "myth", "myth"),
      ],
      late: "The paper mill pulls river water in, uses it, and has to watch what it sends back.",
      mcPrompt: "Which source shows water used to grow food?",
      mc: ["Farm sprinklers", "A river barge", "Just a waterfall", "Water from a faucet"],
      mcAnswer: "Farm sprinklers",
      msPrompt: "Which sources show people using water to make or build something? Choose all that apply.",
      ms: ["Wet concrete", "Rolls of paper", "Just a waterfall", "Wind power"],
      msAnswers: ["Wet concrete", "Rolls of paper"],
      tfPrompt: "Our sources say water is not a natural resource because it comes from a faucet.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["making a product", "a pretty waterfall", "wind power"],
      icAnswer: "making a product",
    })),
    "3.12D-EX": withReasons(exhibit({
      id: "3.12D-EX", standard: "3.12D-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.12D", title: "A plant in the rock",
      job: "Show four clues that something once lived.",
      detail: "A fossil is a clue left in rock. A toy is not a fossil.",
      mythId: "carved",
      spots: [
        { id: "leaf", label: "A leaf print" },
        { id: "shell", label: "A shell turned to stone" },
        { id: "tooth", label: "A tooth in the rock" },
        { id: "track", label: "A track" },
      ],
      cards: [
        photo("leaf", "A fern in the rock", "The shape of a leaf", "/maker/fern.jpg", "leaf"),
        photo("shell", "A stone spiral", "An ammonite shell", "/maker/ammonite.jpg", "shell"),
        photo("tooth", "A tooth in limestone", "Not a rock that just looks sharp", "/maker/tooth.jpg", "tooth"),
        text("track", "A track in the stone", "Three-toed tracks pressed into rock, then hardened.", "track"),
        photo("toy", "A plastic dinosaur", "A toy, not a fossil", "/maker/toydino.jpg", "none", "picture", "weak"),
        text("beach", "A shell from the beach", "This shell is new. It was picked up this summer.", "none", "place", "place"),
        text("carved", "Someone carved it", "Someone scratched that plant shape in with a nail. Rocks do not keep plants.", "none", "myth", "myth"),
      ],
      late: "The fern print is flatter than a carving, and the rock around it is the same age as the print.",
      mcPrompt: "Which source is a real leaf clue in rock?",
      mc: ["A fern in the rock", "A plastic dinosaur", "A shell from the beach", "Someone carved it"],
      mcAnswer: "A fern in the rock",
      msPrompt: "Which sources are fossils, not toys or new shells? Choose all that apply.",
      ms: ["A stone spiral", "A tooth in limestone", "A plastic dinosaur", "A shell from the beach"],
      msAnswers: ["A stone spiral", "A tooth in limestone"],
      tfPrompt: "Our sources say the plant shape was scratched in with a nail.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a leaf print", "a plastic toy", "a new seashell"],
      icAnswer: "a leaf print",
    })),
    "4.12C-EX": withReasons(exhibit({
      id: "4.12C-EX", standard: "4.12C-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.12C", title: "When Texas was a sea",
      job: "Show four clues that this Texas rock was once under the sea.",
      detail: "The clue has to be old and in the rock, not a souvenir from a trip.",
      mythId: "flood",
      spots: [
        { id: "spiral", label: "A sea animal's shell" },
        { id: "tooth", label: "A sea hunter's tooth" },
        { id: "clam", label: "A clam in the rock" },
        { id: "coral", label: "Coral turned to stone" },
      ],
      cards: [
        photo("spiral", "An ammonite", "A sea animal's coiled shell", "/maker/ammonite.jpg", "spiral"),
        photo("tooth", "A shark tooth", "From an animal that lived in the sea", "/maker/tooth.jpg", "tooth"),
        text("clam", "A clam in limestone", "The two shells are still closed inside the Texas rock.", "clam"),
        text("coral", "Stone coral", "The holes match a coral colony, and the rock around it is limestone.", "coral"),
        photo("toy", "A toy dinosaur", "Plastic, not stone", "/maker/toydino.jpg", "none", "picture", "weak"),
        text("beach", "A shell from last summer", "A modern shell from a beach bag.", "none", "place", "place"),
        text("flood", "Last year's flood", "The shells washed up in last year's flood. They are not old.", "none", "myth", "myth"),
      ],
      late: "Limestone full of sea shells can form on a seafloor, then rise to become a hill.",
      mcPrompt: "Which source is a sea animal's shell in the rock?",
      mc: ["An ammonite", "A toy dinosaur", "A shell from last summer", "Last year's flood"],
      mcAnswer: "An ammonite",
      msPrompt: "Which sources are fossils of sea life? Choose all that apply.",
      ms: ["A shark tooth", "A clam in limestone", "A toy dinosaur", "A shell from last summer"],
      msAnswers: ["A shark tooth", "A clam in limestone"],
      tfPrompt: "Our sources say the shells were left by last year's flood.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["coral turned to stone", "a plastic toy", "a beach souvenir"],
      icAnswer: "coral turned to stone",
    })),
    "4.12B-EX": withReasons(exhibit({
      id: "4.12B-EX", standard: "4.12B-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.12B", title: "Who eats whom",
      job: "Show how energy moves through a food web.",
      detail: "Start with the sun. Then show who makes food, who eats, and who breaks leftovers down.",
      mythId: "skip",
      spots: [
        { id: "sun", label: "Energy from the sun" },
        { id: "plant", label: "A producer" },
        { id: "eater", label: "A consumer" },
        { id: "rot", label: "A decomposer" },
      ],
      cards: [
        photo("sun", "Sun on the leaves", "The energy starts here", "/maker/sun.jpg", "sun"),
        photo("plant", "Grass", "A producer makes food", "/maker/sunplant.jpg", "plant"),
        photo("eater", "An elk grazing", "A consumer eats the plant", "/maker/elk.jpg", "eater"),
        text("rot", "A mushroom on a log", "A decomposer breaks the dead log down.", "rot"),
        text("rock", "A rock", "A rock is not in the food web. Nothing eats it for energy.", "none", "topic", "weak"),
        photo("toy", "A toy dinosaur", "Not a living consumer", "/maker/toydino.jpg", "none", "picture", "weak"),
        text("skip", "Animals make the energy", "Animals make their own energy. They do not need plants or the sun.", "none", "myth", "myth"),
      ],
      late: "When the elk dies, decomposers use what is left. The energy does not vanish. It moves.",
      mcPrompt: "Which source shows where the energy enters the web?",
      mc: ["Sun on the leaves", "An elk grazing", "A rock", "Animals make the energy"],
      mcAnswer: "Sun on the leaves",
      msPrompt: "Which sources are living parts of the web, not a rock or a toy? Choose all that apply.",
      ms: ["Grass", "An elk grazing", "A rock", "A toy dinosaur"],
      msAnswers: ["Grass", "An elk grazing"],
      tfPrompt: "Our sources say animals make their own energy and do not need plants.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a decomposer", "a rock", "a toy"],
      icAnswer: "a decomposer",
    })),
    "5.12B-EX": withReasons(exhibit({
      id: "5.12B-EX", standard: "5.12B-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.12B", title: "When the wolves came back",
      job: "Prove one change can move through a food web.",
      detail: "Use only the chain the notes support: wolves, elk, willows, beavers.",
      mythId: "only",
      spots: [
        { id: "wolf", label: "Wolves return" },
        { id: "elk", label: "Elk change where they eat" },
        { id: "willow", label: "Young trees grow back" },
        { id: "beaver", label: "Beavers get food and wood" },
      ],
      cards: [
        photo("wolf", "Wolves return", "A predator is back", "/maker/wolf.jpg", "wolf"),
        photo("elk", "Elk leave the riverbank", "They graze less where wolves can surprise them", "/maker/elk.jpg", "elk"),
        photo("willow", "Willows grow back", "Young trees are no longer eaten down", "/maker/willow.jpg", "willow"),
        photo("beaver", "A beaver dam", "Beavers use the new willow", "/maker/beaver.jpg", "beaver"),
        text("howl", "A wolf howling", "A howl is a sound. It does not show a change in the web.", "none", "topic", "weak"),
        text("reef", "A coral reef", "This food web is in the ocean, not this valley.", "none", "place", "place"),
        text("only", "Wolves only affect their prey", "Wolves only change the animals they eat. Plants and beavers stay the same.", "none", "myth", "myth"),
      ],
      late: "After the willows grew back along the river, more beaver dams were counted there.",
      mcPrompt: "Which source shows the change that starts this chain?",
      mc: ["Wolves return", "A wolf howling", "A coral reef", "Wolves only affect their prey"],
      mcAnswer: "Wolves return",
      msPrompt: "Which sources show what happened after the elk grazed less by the river? Choose all that apply.",
      ms: ["Willows grow back", "A beaver dam", "A wolf howling", "A coral reef"],
      msAnswers: ["Willows grow back", "A beaver dam"],
      tfPrompt: "Our sources say wolves change only the animals they eat.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["beavers get food and wood", "a coral reef", "a howl"],
      icAnswer: "beavers get food and wood",
    })),
    "5.10C-EX": withReasons(exhibit({
      id: "5.10C-EX", standard: "5.10C-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.10C", title: "Shaped by wind, water, and ice",
      job: "Show four landforms made by wind, water, or ice.",
      detail: "A volcano is heat from below. It does not belong on this wall.",
      mythId: "quake",
      spots: [
        { id: "delta", label: "A river builds land" },
        { id: "canyon", label: "Water cuts down" },
        { id: "dune", label: "Wind piles sand" },
        { id: "ice", label: "Ice carves a valley" },
      ],
      cards: [
        photo("delta", "A river delta", "Water drops sand at the sea", "/maker/delta.jpg", "delta"),
        photo("canyon", "A canyon", "A river cut the rock", "/maker/canyon.jpg", "canyon"),
        photo("dune", "Sand dunes", "Wind built these", "/maker/dunes.jpg", "dune"),
        photo("ice", "A glacier valley", "Ice carved the U shape", "/maker/glacier.jpg", "ice"),
        photo("volcano", "A volcano", "Heat from inside Earth, not wind, water, or ice", "/maker/volcano.jpg", "none", "topic", "weak"),
        text("city", "A city skyline", "People built this. Wind and water did not.", "none", "place", "place"),
        text("quake", "One earthquake", "A canyon cracks open in one earthquake.", "none", "myth", "myth"),
      ],
      late: "The dunes sit far from the river. Their sand was pushed by wind, not dropped by the water.",
      mcPrompt: "Which source shows wind building a landform?",
      mc: ["Sand dunes", "A volcano", "A city skyline", "One earthquake"],
      mcAnswer: "Sand dunes",
      msPrompt: "Which sources were made by water? Choose all that apply.",
      ms: ["A river delta", "A canyon", "A volcano", "A city skyline"],
      msAnswers: ["A river delta", "A canyon"],
      tfPrompt: "Our sources say a canyon opens in one earthquake.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["wind piles sand", "a volcano", "a city"],
      icAnswer: "wind piles sand",
    })),
    "5.12A-EX": withReasons(exhibit({
      id: "5.12A-EX", standard: "5.12A-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.12A", title: "Portrait of a healthy pond",
      job: "Show four parts that keep a pond alive.",
      detail: "Include living and nonliving parts. Trash does not keep the pond healthy.",
      mythId: "dead",
      spots: [
        { id: "light", label: "Sunlight" },
        { id: "plant", label: "Plants" },
        { id: "animal", label: "Animals" },
        { id: "water", label: "Clean water" },
      ],
      cards: [
        photo("light", "Sun on the water", "A nonliving part the plants need", "/maker/pond.jpg", "light"),
        text("plant", "Cattails", "Plants at the edge give cover and food.", "plant"),
        photo("animal", "A fish", "An animal in the web", "/maker/fishpond.jpg", "animal"),
        text("water", "Clear water", "The sample is clear enough to see through.", "water"),
        text("bottle", "A plastic bottle", "Trash makes the pond less healthy.", "none", "topic", "weak"),
        photo("lizard", "A desert lizard", "This animal is not part of this pond.", "/maker/lizard.jpg", "none", "place", "place"),
        text("dead", "Nonliving things do not matter", "Sunlight and water do not matter to the living things.", "none", "myth", "myth"),
      ],
      late: "On a cloudy week the cattails grew more slowly. The living plants were waiting on the sun.",
      mcPrompt: "Which source is the nonliving energy the plants use?",
      mc: ["Sun on the water", "A plastic bottle", "A desert lizard", "Nonliving things do not matter"],
      mcAnswer: "Sun on the water",
      msPrompt: "Which sources are living parts of the pond? Choose all that apply.",
      ms: ["Cattails", "A fish", "A plastic bottle", "A desert lizard"],
      msAnswers: ["Cattails", "A fish"],
      tfPrompt: "Our sources say sunlight and water do not matter to the living things.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["plants", "a plastic bottle", "a desert lizard"],
      icAnswer: "plants",
    })),
    "5.13A-EX": withReasons(exhibit({
      id: "5.13A-EX", standard: "5.13A-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.13A", title: "Same job, different body",
      job: "Match four body parts to the job they do.",
      detail: "The part has to do the job on the spot. A desert trick from another case does not belong unless it matches.",
      mythId: "same",
      spots: [
        { id: "reach", label: "Reach food up high" },
        { id: "swim", label: "Push water" },
        { id: "grab", label: "Grab and hold" },
        { id: "breathe", label: "Take oxygen from water" },
      ],
      cards: [
        photo("reach", "A giraffe's neck", "Leaves other animals cannot reach", "/maker/giraffe.jpg", "reach"),
        photo("swim", "Webbed feet", "A duck pushes water", "/maker/duck.jpg", "swim"),
        photo("grab", "A talon", "It locks around a branch", "/maker/talon.jpg", "grab"),
        photo("breathe", "Gills", "A fish pulls oxygen from water", "/maker/gills.jpg", "breathe"),
        photo("fur", "Thick fur", "This keeps an animal warm. That is a different job.", "/maker/bear.jpg", "none", "topic", "weak"),
        photo("toy", "A toy dinosaur", "A toy has no working body part.", "/maker/toydino.jpg", "none", "picture", "weak"),
        text("same", "One body part fits every job", "If a body part helps one animal, the same part helps every animal.", "none", "myth", "myth"),
      ],
      late: "The gill cover opens and closes underwater. Lungs would not do that job.",
      mcPrompt: "Which source shows a body part for reaching food up high?",
      mc: ["A giraffe's neck", "Webbed feet", "Thick fur", "One body part fits every job"],
      mcAnswer: "A giraffe's neck",
      msPrompt: "Which sources are body parts that move an animal or grab? Choose all that apply.",
      ms: ["Webbed feet", "A talon", "Thick fur", "A toy dinosaur"],
      msAnswers: ["Webbed feet", "A talon"],
      tfPrompt: "Our sources say one body part can do every animal's job.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["take oxygen from water", "reach food up high", "thick fur"],
      icAnswer: "take oxygen from water",
    })),
    "ELA.3.7C-EX": withReasons(exhibit({
      id: "ELA.3.7C-EX", standard: "ELA.3.7C-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.7C", title: "Meet Rosa",
      job: "Prove what Rosa is like, using lines from the story.",
      detail: "Rosa stayed after the game to pick up bats. She gave her extra water to a teammate. She told the coach the truth when she stepped out of bounds. She said sorry when she bumped Rio.",
      mythId: "brave",
      spots: [
        { id: "help", label: "She helps" },
        { id: "share", label: "She shares" },
        { id: "truth", label: "She tells the truth" },
        { id: "sorry", label: "She makes it right" },
      ],
      cards: [
        text("help", "Stayed for the bats", "Rosa stayed after the game to pick up bats.", "help"),
        text("share", "Gave her water", "She gave her extra water to a teammate.", "share"),
        text("truth", "Told the coach", "She told the coach the truth when she stepped out of bounds.", "truth"),
        text("sorry", "Said sorry", "She said sorry when she bumped Rio.", "sorry"),
        text("name", "Her name is Rosa", "The story says her name. It does not show what she is like.", "none", "topic", "weak"),
        text("rio", "Rio scored", "Rio scored the last point. That line is about Rio, not Rosa.", "none", "place", "place"),
        text("brave", "Always brave", "The story says Rosa was always brave, even when it never shows that.", "none", "myth", "myth"),
      ],
      late: "A reader wrote: the water, the bats, and the sorry all show Rosa thinking about other people.",
      mcPrompt: "Which line shows Rosa telling the truth?",
      mc: ["Told the coach", "Her name is Rosa", "Rio scored", "Always brave"],
      mcAnswer: "Told the coach",
      msPrompt: "Which lines show Rosa helping or sharing? Choose all that apply.",
      ms: ["Stayed for the bats", "Gave her water", "Her name is Rosa", "Rio scored"],
      msAnswers: ["Stayed for the bats", "Gave her water"],
      tfPrompt: "Our sources say the story calls Rosa always brave.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["she makes it right", "Rio scored", "her name"],
      icAnswer: "she makes it right",
    })),
    "ELA.3.8B-EX": withReasons(exhibit({
      id: "ELA.3.8B-EX", standard: "ELA.3.8B-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.8B", title: "The sister's part",
      job: "Show how Nia and her little brother treat each other.",
      detail: "Nia wanted the window seat. She let Ben have it anyway. Ben held the map upside down. Nia turned it around and did not laugh. When Ben was scared of the tunnel, Nia told him the light was coming. At the station, Ben carried Nia's bag.",
      mythId: "alone",
      spots: [
        { id: "give", label: "Nia gives something up" },
        { id: "kind", label: "Nia is kind about a mistake" },
        { id: "calm", label: "Nia helps him feel safe" },
        { id: "back", label: "Ben helps Nia back" },
      ],
      cards: [
        text("give", "The window seat", "Nia let Ben have the window seat.", "give"),
        text("kind", "The upside-down map", "Nia turned the map around and did not laugh.", "kind"),
        text("calm", "The tunnel", "Nia told him the light was coming.", "calm"),
        text("back", "Ben carried the bag", "At the station, Ben carried Nia's bag.", "back"),
        text("hair", "Nia has braids", "That tells how she looks, not how they treat each other.", "none", "topic", "weak"),
        text("other", "A different train", "Leo missed his train in another story.", "none", "place", "place"),
        text("alone", "They never help", "Brothers and sisters in stories never help each other.", "none", "myth", "myth"),
      ],
      late: "Ben's bag was small, but he picked it up without being asked.",
      mcPrompt: "Which line shows Nia giving something up?",
      mc: ["The window seat", "Nia has braids", "A different train", "They never help"],
      mcAnswer: "The window seat",
      msPrompt: "Which lines show one of them helping the other? Choose all that apply.",
      ms: ["The tunnel", "Ben carried the bag", "Nia has braids", "A different train"],
      msAnswers: ["The tunnel", "Ben carried the bag"],
      tfPrompt: "Our sources say brothers and sisters in stories never help each other.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["Ben helps Nia back", "how Nia looks", "a different story"],
      icAnswer: "Ben helps Nia back",
    })),
    "ELA.4.8A-EX": withReasons(exhibit({
      id: "ELA.4.8A-EX", standard: "ELA.4.8A-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.8A", title: "The cracked pot",
      job: "Prove the theme is that everyone has something to offer.",
      detail: "A gardener carried two pots on a pole. One was cracked. Water leaked out and flowers grew on that side of the path. The perfect pot was proud. The cracked pot was sad. The gardener said, Those flowers are there because of your crack.",
      mythId: "word",
      spots: [
        { id: "leak", label: "The crack does something" },
        { id: "flowers", label: "Something good grows" },
        { id: "words", label: "The gardener explains" },
        { id: "theme", label: "What it means" },
      ],
      cards: [
        text("leak", "Water leaked", "Water leaked from the crack on every trip.", "leak"),
        text("flowers", "Flowers on the path", "Flowers grew only on the cracked pot's side.", "flowers"),
        text("words", "Because of your crack", "The gardener said the flowers were there because of the crack.", "words"),
        text("theme", "A use for the flaw", "The thing that looked like a problem was watering the flowers.", "theme"),
        text("plot", "A gardener and two pots", "That is the topic. It does not say what the story means.", "none", "topic", "weak"),
        text("other", "Another fable", "A fox said the grapes were sour. That is a different story.", "none", "place", "place"),
        text("word", "Theme is one word", "A theme is one word, like flowers.", "none", "myth", "myth"),
      ],
      late: "The perfect pot carried water well. The story still says the cracked pot had a gift.",
      mcPrompt: "Which line shows the gardener explaining the crack?",
      mc: ["Because of your crack", "A gardener and two pots", "Another fable", "Theme is one word"],
      mcAnswer: "Because of your crack",
      msPrompt: "Which lines show the crack causing something good? Choose all that apply.",
      ms: ["Water leaked", "Flowers on the path", "A gardener and two pots", "Another fable"],
      msAnswers: ["Water leaked", "Flowers on the path"],
      tfPrompt: "Our sources say a theme is just one word, like flowers.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["what it means", "another fable", "the topic only"],
      icAnswer: "what it means",
    })),
    "ELA.4.9B-EX": withReasons(exhibit({
      id: "ELA.4.9B-EX", standard: "ELA.4.9B-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.9B", title: "Words that paint pictures",
      job: "Sort four kinds of picture-making language.",
      detail: "A simile compares with like or as. A metaphor says something is something else. Personification gives a thing a human action.",
      mythId: "as",
      spots: [
        { id: "sim", label: "A simile" },
        { id: "met", label: "A metaphor" },
        { id: "per", label: "Personification" },
        { id: "more", label: "Personification again" },
      ],
      cards: [
        text("sim", "Quiet as a mouse", "The room was as quiet as a mouse.", "sim"),
        text("met", "The room was a zoo", "The classroom was a zoo.", "met"),
        text("per", "The wind whispered", "The wind whispered through the door.", "per"),
        text("more", "The sun smiled", "The sun smiled down on the field.", "more"),
        text("like", "I like pizza", "Like here means enjoy. It does not compare two things.", "none", "topic", "weak"),
        text("brown", "The dog is brown", "That is a fact. It does not make a picture with a comparison.", "none", "place", "place"),
        text("as", "Any as is a simile", "Any sentence with as is a simile.", "none", "myth", "myth"),
      ],
      late: "The sun smiled is not a simile. The sun is doing something a person does.",
      mcPrompt: "Which line is a simile?",
      mc: ["Quiet as a mouse", "I like pizza", "The dog is brown", "Any as is a simile"],
      mcAnswer: "Quiet as a mouse",
      msPrompt: "Which lines give a thing a human action? Choose all that apply.",
      ms: ["The wind whispered", "The sun smiled", "I like pizza", "The dog is brown"],
      msAnswers: ["The wind whispered", "The sun smiled"],
      tfPrompt: "Our sources say any sentence with as is a simile.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["personification again", "a plain fact", "I like pizza"],
      icAnswer: "personification again",
    })),
    "ELA.4.8B-EX": withReasons(exhibit({
      id: "ELA.4.8B-EX", standard: "ELA.4.8B-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.8B", title: "Portrait of Leo",
      job: "Show how Leo changes, and who helps him change.",
      detail: "On Monday Leo hid the good markers. His grandmother said, A full table is better than a full pocket. On the rainy day he watched her share her umbrella with a stranger. On Friday he put the markers in the middle of the table.",
      mythId: "same",
      spots: [
        { id: "before", label: "Leo at the start" },
        { id: "words", label: "Someone challenges him" },
        { id: "see", label: "He sees another way" },
        { id: "after", label: "Leo at the end" },
      ],
      cards: [
        text("before", "Hid the markers", "On Monday Leo hid the good markers.", "before"),
        text("words", "A full table", "His grandmother said a full table is better than a full pocket.", "words"),
        text("see", "The umbrella", "He watched her share her umbrella with a stranger.", "see"),
        text("after", "Markers in the middle", "On Friday he put the markers in the middle of the table.", "after"),
        text("looks", "Leo wears red", "His shirt color does not show a change.", "none", "topic", "weak"),
        text("other", "Mina shared", "Mina shared her lunch in a different story.", "none", "place", "place"),
        text("same", "Characters stay the same", "Main characters stay the same from the first page to the last.", "none", "myth", "myth"),
      ],
      late: "The markers did not change. Leo did. He moved them where other people could reach them.",
      mcPrompt: "Which line shows Leo before he changes?",
      mc: ["Hid the markers", "Leo wears red", "Mina shared", "Characters stay the same"],
      mcAnswer: "Hid the markers",
      msPrompt: "Which lines show what helps Leo change? Choose all that apply.",
      ms: ["A full table", "The umbrella", "Leo wears red", "Mina shared"],
      msAnswers: ["A full table", "The umbrella"],
      tfPrompt: "Our sources say main characters stay the same the whole story.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["Leo at the end", "what he wears", "a different story"],
      icAnswer: "Leo at the end",
    })),
    "ELA.4.10B-EX": withReasons(exhibit({
      id: "ELA.4.10B-EX", standard: "ELA.4.10B-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.10B", title: "How the article is built",
      job: "Show four text structures.",
      detail: "The structure is how the information is organized, not the topic of bees.",
      mythId: "one",
      spots: [
        { id: "seq", label: "Sequence" },
        { id: "cause", label: "Cause and effect" },
        { id: "desc", label: "Description" },
        { id: "qa", label: "Question and answer" },
      ],
      cards: [
        text("seq", "First, next, last", "First the egg hatches. Next the larva eats. Last the adult flies.", "seq"),
        text("cause", "Because the hive got hot", "Because the hive got hot, the bees fanned their wings.", "cause"),
        text("desc", "A bee's body", "A honeybee has two pairs of wings, a striped body, and a stinger.", "desc"),
        text("qa", "Why do bees dance?", "The article asks why bees dance, then answers with the waggle dance.", "qa"),
        text("story", "Max taped the kite", "That is a story event, not a structure in this article.", "none", "topic", "weak"),
        text("poem", "The wind whispered", "That is figurative language from a poem.", "none", "place", "place"),
        text("one", "Articles have one shape", "Every article is just a list of facts in no order.", "none", "myth", "myth"),
      ],
      late: "The question heading sits above the paragraph that answers it.",
      mcPrompt: "Which source is organized as a sequence?",
      mc: ["First, next, last", "Max taped the kite", "The wind whispered", "Articles have one shape"],
      mcAnswer: "First, next, last",
      msPrompt: "Which sources show cause and effect or a question being answered? Choose all that apply.",
      ms: ["Because the hive got hot", "Why do bees dance?", "Max taped the kite", "The wind whispered"],
      msAnswers: ["Because the hive got hot", "Why do bees dance?"],
      tfPrompt: "Our sources say every article is just a list of facts in no order.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["question and answer", "a kite story", "a poem"],
      icAnswer: "question and answer",
    })),
    "ELA.5.10A-EX": withReasons(exhibit({
      id: "ELA.5.10A-EX", standard: "ELA.5.10A-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.10A", title: "Save the monarchs",
      job: "Prove the author wants the reader to help.",
      detail: "Monarchs lay eggs on milkweed. Without it, the caterpillars have no food. You can plant milkweed in a pot. One pot will not save every butterfly, but it gives the next egg a leaf. The last line says, Start with one pot.",
      mythId: "inform",
      spots: [
        { id: "fact", label: "A fact that creates a need" },
        { id: "help", label: "What the reader can do" },
        { id: "hope", label: "Why a small act matters" },
        { id: "call", label: "The call to act" },
      ],
      cards: [
        text("fact", "Eggs on milkweed", "Monarchs lay eggs on milkweed, and the caterpillars eat it.", "fact"),
        text("help", "Plant one pot", "You can plant milkweed in a pot.", "help"),
        text("hope", "The next egg", "One pot gives the next egg a leaf.", "hope"),
        text("call", "Start with one pot", "The last line tells the reader to start with one pot.", "call"),
        photo("color", "Orange wings", "A true fact about color. It does not ask the reader to help.", "/maker/monarch.jpg", "none", "topic", "weak"),
        text("toy", "A butterfly toy ad", "Buy this toy butterfly. It lights up.", "none", "place", "place"),
        text("inform", "Just the facts", "Every article only wants to inform. It never wants the reader to do something.", "none", "myth", "myth"),
      ],
      late: "The orange wings are true, and they are not why the last line says to plant a pot.",
      mcPrompt: "Which source is the author's call to act?",
      mc: ["Start with one pot", "Orange wings", "A butterfly toy ad", "Just the facts"],
      mcAnswer: "Start with one pot",
      msPrompt: "Which sources tell the reader what to do or why it helps? Choose all that apply.",
      ms: ["Plant one pot", "The next egg", "Orange wings", "A butterfly toy ad"],
      msAnswers: ["Plant one pot", "The next egg"],
      tfPrompt: "Our sources say an article never asks the reader to do something.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a fact that does not ask for help", "the call to act", "a toy ad"],
      icAnswer: "a fact that does not ask for help",
    })),
    "ELA.5.9B-EX": withReasons(exhibit({
      id: "ELA.5.9B-EX", standard: "ELA.5.9B-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.9B", title: "Who is speaking?",
      job: "Prove the speaker of the poem is the oak, not the poet.",
      detail: "I have stood in this yard longer than the fence. Children have climbed my lowest arm. Last night the wind pulled at my fingers. I will still be here when the leaves return.",
      mythId: "poet",
      spots: [
        { id: "old", label: "The speaker is old" },
        { id: "body", label: "The speaker has branches" },
        { id: "storm", label: "The speaker felt the storm" },
        { id: "hope", label: "The speaker expects spring" },
      ],
      cards: [
        text("old", "Longer than the fence", "I have stood in this yard longer than the fence.", "old"),
        text("body", "My lowest arm", "Children have climbed my lowest arm.", "body"),
        text("storm", "The wind pulled", "The wind pulled at my fingers.", "storm"),
        text("hope", "When the leaves return", "I will still be here when the leaves return.", "hope"),
        text("birthday", "The poet was born in May", "That is a fact about the poet, not a line from the poem.", "none", "topic", "weak"),
        text("other", "A different speaker", "I am a river, and I never sleep. That is another poem.", "none", "place", "place"),
        text("poet", "The speaker is the poet", "The speaker of a poem is always the poet.", "none", "myth", "myth"),
      ],
      late: "Fingers and arms in this poem are branches. A person does not wait for their own leaves.",
      mcPrompt: "Which line shows the speaker has branches?",
      mc: ["My lowest arm", "The poet was born in May", "A different speaker", "The speaker is the poet"],
      mcAnswer: "My lowest arm",
      msPrompt: "Which lines could not be about an ordinary person? Choose all that apply.",
      ms: ["Longer than the fence", "When the leaves return", "The poet was born in May", "A different speaker"],
      msAnswers: ["Longer than the fence", "When the leaves return"],
      tfPrompt: "Our sources say the speaker of a poem is always the poet.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the speaker has branches", "the poet's birthday", "another poem"],
      icAnswer: "the speaker has branches",
    })),
    "ELA.5.13C-EX": withReasons(exhibit({
      id: "ELA.5.13C-EX", standard: "ELA.5.13C-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.13C", title: "Which sources belong",
      job: "Choose sources that help answer: How did the 1900 Galveston storm change the city?",
      detail: "A source belongs if it is about that storm and that question. An ad and a different storm do not.",
      mythId: "any",
      spots: [
        { id: "there", label: "Someone who was there" },
        { id: "photo", label: "A photo from then" },
        { id: "later", label: "A later source that studies it" },
        { id: "numbers", label: "Numbers about the damage" },
      ],
      cards: [
        text("there", "A survivor's letter", "A letter from 1900 describes the water reaching the second floor.", "there"),
        text("photo", "A 1900 photograph", "The photo shows houses reduced to piles of lumber.", "photo"),
        text("later", "A museum panel", "A panel written later explains how the city built a seawall after the storm.", "later"),
        text("numbers", "A damage count", "The report lists lives lost and buildings destroyed.", "numbers"),
        text("ad", "A movie poster", "See the storm movie this Friday. It is not a source about 1900.", "none", "picture", "weak"),
        text("other", "A storm in 2017", "This article is about a different hurricane.", "none", "place", "place"),
        text("any", "Any storm source works", "If a source says storm, it answers this question.", "none", "myth", "myth"),
      ],
      late: "The movie poster uses the word storm, and it was made to sell tickets.",
      mcPrompt: "Which source is from a person who was there?",
      mc: ["A survivor's letter", "A movie poster", "A storm in 2017", "Any storm source works"],
      mcAnswer: "A survivor's letter",
      msPrompt: "Which sources help answer what the city did or lost? Choose all that apply.",
      ms: ["A museum panel", "A damage count", "A movie poster", "A storm in 2017"],
      msAnswers: ["A museum panel", "A damage count"],
      tfPrompt: "Our sources say any source with the word storm answers the question.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a source that does not belong", "someone who was there", "a damage count"],
      icAnswer: "a source that does not belong",
    })),
    "ELA.5.10G-EX": withReasons(exhibit({
      id: "ELA.5.10G-EX", standard: "ELA.5.10G-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.10G", title: "Tricks writers use",
      job: "Tell hyperbole, an anecdote, and an unfair grouping apart from a plain fact.",
      detail: "Hyperbole exaggerates on purpose. An anecdote is a short true-feeling story used to make a point. Stereotyping lumps a whole group together. That one is unfair.",
      mythId: "fact",
      spots: [
        { id: "hyper", label: "Hyperbole" },
        { id: "story", label: "An anecdote" },
        { id: "unfair", label: "An unfair grouping" },
        { id: "plain", label: "A plain fact" },
      ],
      cards: [
        text("hyper", "A million times", "I have told you a million times to close the door.", "hyper"),
        text("story", "One rainy tryout", "The coach tells about one rainy tryout to show why practice matters.", "story"),
        text("unfair", "All fourth graders", "All fourth graders hate reading. That lumps every student together, and it is unfair.", "unfair"),
        text("plain", "The door is shut", "The door is shut. That is a fact, not a trick.", "plain"),
        text("simile", "Quiet as a mouse", "That is a simile, a different kind of language.", "none", "place", "place"),
        text("joke", "A joke with no point", "The writer tells a joke that does not support the idea.", "none", "topic", "weak"),
        text("fact", "Exaggeration is always a lie", "If a sentence is not literally true, the writer is lying.", "none", "myth", "myth"),
      ],
      late: "A million times is not a count. The writer wants you to feel how often the door was left open.",
      mcPrompt: "Which source is hyperbole?",
      mc: ["A million times", "Quiet as a mouse", "A joke with no point", "Exaggeration is always a lie"],
      mcAnswer: "A million times",
      msPrompt: "Which sources are a short story used as proof, or an unfair lump? Choose all that apply.",
      ms: ["One rainy tryout", "All fourth graders", "Quiet as a mouse", "A joke with no point"],
      msAnswers: ["One rainy tryout", "All fourth graders"],
      tfPrompt: "Our sources say any exaggeration is just a lie.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["hyperbole", "a simile", "a joke with no point"],
      icAnswer: "hyperbole",
    })),
    "SS.3.9A-EX": withReasons(exhibit({
      id: "SS.3.9A-EX", standard: "SS.3.9A-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.9A", title: "Good citizens in action",
      job: "Show four ways people practice good citizenship.",
      detail: "Citizenship is how you treat the community. Winning a contest is not the same thing.",
      mythId: "adults",
      spots: [
        { id: "truth", label: "Tell the truth" },
        { id: "fair", label: "Treat people fairly" },
        { id: "care", label: "Care for the place" },
        { id: "voice", label: "Use your voice" },
      ],
      cards: [
        text("truth", "Told the truth", "A student told the teacher what really happened at recess.", "truth"),
        text("fair", "Took turns", "The team made sure every player got a turn.", "fair"),
        text("care", "Picked up litter", "Neighbors picked up litter in the park.", "care"),
        text("voice", "Spoke at the meeting", "A student explained an idea at the class meeting and listened to replies.", "voice"),
        text("prize", "Won the spelling bee", "Winning is an achievement. It is not citizenship by itself.", "none", "topic", "weak"),
        text("yell", "Yelled over people", "A crowd shouted so no one else could talk.", "none", "picture", "weak"),
        text("adults", "Only adults count", "Only adults can be good citizens.", "none", "myth", "myth"),
      ],
      late: "The student at the meeting did not win a vote. Speaking and listening still counted.",
      mcPrompt: "Which source shows someone caring for a shared place?",
      mc: ["Picked up litter", "Won the spelling bee", "Yelled over people", "Only adults count"],
      mcAnswer: "Picked up litter",
      msPrompt: "Which sources show fairness or a respectful voice? Choose all that apply.",
      ms: ["Took turns", "Spoke at the meeting", "Won the spelling bee", "Yelled over people"],
      msAnswers: ["Took turns", "Spoke at the meeting"],
      tfPrompt: "Our sources say only adults can be good citizens.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["use your voice", "a prize", "shouting"],
      icAnswer: "use your voice",
    })),
    "SS.3.3C-EX": withReasons(exhibit({
      id: "SS.3.3C-EX", standard: "SS.3.3C-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.3C", title: "People changed this place",
      job: "Prove that people changed Cedar Creek.",
      detail: "A flood is nature. Count a change only if people did it.",
      mythId: "only",
      spots: [
        { id: "road", label: "They built" },
        { id: "dam", label: "They held water back" },
        { id: "plant", label: "They planted" },
        { id: "harm", label: "They polluted" },
      ],
      cards: [
        text("road", "A new road", "People paved a road along the creek.", "road"),
        text("dam", "A small dam", "People built a dam that made a pond.", "dam"),
        text("plant", "Tree-planting day", "The class planted trees on the bare bank.", "plant"),
        text("harm", "Litter on the bank", "Trash from the picnic area piled up on the bank.", "harm"),
        text("flood", "A spring flood", "Rain swelled the creek. No person caused that water.", "none", "topic", "weak"),
        text("mountain", "A mountain photo", "This mountain is in another state.", "none", "place", "place"),
        text("only", "Only building counts", "Only building changes land. Planting trees does nothing.", "none", "myth", "myth"),
      ],
      late: "The new trees hold the bank. Planting changed the place, even though no one poured concrete.",
      mcPrompt: "Which source shows people building something?",
      mc: ["A new road", "A spring flood", "A mountain photo", "Only building counts"],
      mcAnswer: "A new road",
      msPrompt: "Which sources show people changing the land on purpose or by leaving waste? Choose all that apply.",
      ms: ["A small dam", "Litter on the bank", "A spring flood", "A mountain photo"],
      msAnswers: ["A small dam", "Litter on the bank"],
      tfPrompt: "Our sources say planting trees does not change the land.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["they planted", "a flood", "another state"],
      icAnswer: "they planted",
    })),
    "SS.3.13A-EX": withReasons(exhibit({
      id: "SS.3.13A-EX", standard: "SS.3.13A-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.13A", title: "Meet Benjamin Franklin",
      job: "Show four things Franklin invented or built, and why they mattered.",
      detail: "He did not invent the light bulb, and he did not discover electricity. He showed that lightning is electricity.",
      mythId: "discover",
      spots: [
        { id: "rod", label: "A safer building" },
        { id: "eyes", label: "Help for eyes" },
        { id: "heat", label: "A better stove" },
        { id: "swim", label: "Something he made as a boy" },
      ],
      cards: [
        photo("rod", "A lightning rod", "It carries a strike away from the building", "/maker/rod.jpg", "rod"),
        text("eyes", "Bifocal glasses", "The top of the lens was for far away. The bottom was for up close.", "eyes"),
        text("heat", "The Franklin stove", "It warmed a room using less wood than an open fireplace.", "heat"),
        text("swim", "Swim fins", "As a boy he made wooden fins to help his hands pull through water.", "swim"),
        text("bulb", "A light bulb", "The light bulb came long after Franklin, from a later inventor.", "none", "place", "place"),
        text("money", "His face on money", "The bill honors him. It is not an invention.", "none", "topic", "weak"),
        text("discover", "He discovered electricity", "Franklin discovered electricity.", "none", "myth", "myth"),
      ],
      late: "The kite experiment was a test about lightning. It was not the invention of electricity.",
      mcPrompt: "Which source shows an invention that protects a building?",
      mc: ["A lightning rod", "A light bulb", "His face on money", "He discovered electricity"],
      mcAnswer: "A lightning rod",
      msPrompt: "Which sources are inventions for seeing or heating? Choose all that apply.",
      ms: ["Bifocal glasses", "The Franklin stove", "A light bulb", "His face on money"],
      msAnswers: ["Bifocal glasses", "The Franklin stove"],
      tfPrompt: "Our sources say Franklin discovered electricity.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a safer building", "a light bulb", "his picture on money"],
      icAnswer: "a safer building",
    })),
    "SS.3.7A-EX": withReasons(exhibit({
      id: "SS.3.7A-EX", standard: "SS.3.7A-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.7A", title: "Who does this job?",
      job: "Match four jobs in a local community to the work they do.",
      detail: "Local means the city or town, not the whole state.",
      mythId: "governor",
      spots: [
        { id: "mayor", label: "Leads the city" },
        { id: "council", label: "Makes local rules" },
        { id: "police", label: "Keeps people safe" },
        { id: "school", label: "Runs the schools" },
      ],
      cards: [
        text("mayor", "The mayor", "The mayor leads the city government.", "mayor"),
        text("council", "The city council", "The council votes on local rules and how the city spends money.", "council"),
        text("police", "Police officers", "Police officers enforce laws and help in emergencies.", "police"),
        text("school", "The school board", "The school board makes decisions for the local schools.", "school"),
        text("state", "The governor", "The governor leads the state, not the city.", "none", "place", "place"),
        text("store", "A shop owner", "A shop owner runs a business. That is not a government job.", "none", "topic", "weak"),
        text("governor", "The governor runs the schools", "The governor picks the homework for every class in town.", "none", "myth", "myth"),
      ],
      late: "The school board meets in the city. The governor works for the whole state.",
      mcPrompt: "Which source is the person who leads the city?",
      mc: ["The mayor", "The governor", "A shop owner", "The governor runs the schools"],
      mcAnswer: "The mayor",
      msPrompt: "Which sources make rules for the city or the local schools? Choose all that apply.",
      ms: ["The city council", "The school board", "The governor", "A shop owner"],
      msAnswers: ["The city council", "The school board"],
      tfPrompt: "Our sources say the governor picks the homework for every class in town.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["runs the schools", "leads the city", "a shop"],
      icAnswer: "runs the schools",
    })),
    "SS.4.2E-EX": withReasons(exhibit({
      id: "SS.4.2E-EX", standard: "SS.4.2E-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.2E", title: "Meet Stephen F. Austin",
      job: "Show four true things Austin did for the Texas colonies.",
      detail: "He died of illness in December 1836. He did not die defending the Alamo.",
      mythId: "alamo",
      spots: [
        { id: "grant", label: "A land grant" },
        { id: "families", label: "Brought families" },
        { id: "map", label: "Mapped the land" },
        { id: "town", label: "A colony town" },
      ],
      cards: [
        text("grant", "The land grant", "Austin carried out his father's plan to settle families on a land grant.", "grant"),
        text("families", "The Old Three Hundred", "He brought about 300 families to Texas.", "families"),
        text("map", "A map he drew", "He drew maps so settlers could find the land.", "map"),
        text("town", "San Felipe", "San Felipe de Austin was the capital of his colony.", "town"),
        text("houston", "San Jacinto", "Sam Houston's army won at San Jacinto. That card is about Houston.", "none", "place", "place"),
        text("skyline", "The city skyline today", "The modern city named Austin is not the colony he founded.", "none", "topic", "weak"),
        text("alamo", "He died at the Alamo", "Austin died defending the Alamo.", "none", "myth", "myth"),
      ],
      late: "Austin died of an illness in December 1836, months after the Alamo.",
      mcPrompt: "Which source shows Austin bringing settlers?",
      mc: ["The Old Three Hundred", "San Jacinto", "The city skyline today", "He died at the Alamo"],
      mcAnswer: "The Old Three Hundred",
      msPrompt: "Which sources are about his colony, not a later battle or a modern city? Choose all that apply.",
      ms: ["A map he drew", "San Felipe", "San Jacinto", "The city skyline today"],
      msAnswers: ["A map he drew", "San Felipe"],
      tfPrompt: "Our sources say Austin died defending the Alamo.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["he died at the Alamo", "a land grant", "San Jacinto"],
      icAnswer: "he died at the Alamo",
    })),
    "SS.4.1A-EX": withReasons(exhibit({
      id: "SS.4.1A-EX", standard: "SS.4.1A-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.1A", title: "Four ways of living in Texas",
      job: "Show how four American Indian nations used the Texas land in different ways.",
      detail: "These are four nations, not one way of life. Do not treat them as if they all lived the same.",
      mythId: "same",
      spots: [
        { id: "farm", label: "Farmed in the east" },
        { id: "coast", label: "Fished the Gulf" },
        { id: "trade", label: "Farmed and traded in the west" },
        { id: "plains", label: "Hunted bison" },
      ],
      cards: [
        text("farm", "The Caddo", "Caddo people farmed corn, beans, and squash in East Texas and built settled villages.", "farm"),
        text("coast", "The Karankawa", "Karankawa people lived along the Gulf Coast and fished, hunted, and gathered.", "coast"),
        text("trade", "The Jumano", "Jumano people in West Texas farmed along rivers and traded with other nations.", "trade"),
        text("plains", "The Comanche", "Comanche people became skilled bison hunters on the plains and used horses.", "plains"),
        text("city", "A downtown skyline", "This is a modern city. It does not show how these nations lived.", "none", "place", "place"),
        text("one", "One house for all", "A single grass hut is labeled as every nation's home.", "none", "picture", "weak"),
        text("same", "They all lived one way", "All American Indians in Texas lived, farmed, and hunted in the same way.", "none", "myth", "myth"),
      ],
      late: "The Caddo villages and the Comanche bison hunts used different parts of Texas. Neither one is the whole story.",
      mcPrompt: "Which source shows farming in East Texas?",
      mc: ["The Caddo", "A downtown skyline", "One house for all", "They all lived one way"],
      mcAnswer: "The Caddo",
      msPrompt: "Which sources show a nation using the coast or the plains? Choose all that apply.",
      ms: ["The Karankawa", "The Comanche", "A downtown skyline", "One house for all"],
      msAnswers: ["The Karankawa", "The Comanche"],
      tfPrompt: "Our sources say all American Indians in Texas lived in the same way.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["they all lived one way", "farmed in the east", "a modern city"],
      icAnswer: "they all lived one way",
    })),
    "SS.5.2A-EX": withReasons(exhibit({
      id: "SS.5.2A-EX", standard: "SS.5.2A-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.2A", title: "Road to revolution",
      job: "Show four causes that built anger before independence.",
      detail: "A cause comes before the Declaration. The Declaration is a result, not one of these causes.",
      mythId: "one",
      spots: [
        { id: "tax", label: "A tax on paper" },
        { id: "town", label: "More taxes on goods" },
        { id: "tea", label: "The tea protest" },
        { id: "laws", label: "Laws that punished Boston" },
      ],
      cards: [
        text("tax", "The Stamp Act", "In 1765 the Stamp Act taxed printed paper.", "tax"),
        text("town", "The Townshend Acts", "These acts taxed goods such as glass, paper, and tea.", "town"),
        text("tea", "The Boston Tea Party", "In 1773 colonists dumped tea to protest the tea tax.", "tea"),
        text("laws", "The Intolerable Acts", "Britain answered by closing Boston's port and sending more control.", "laws"),
        text("declare", "The Declaration", "The Declaration of Independence is signed in 1776. That is a result.", "none", "topic", "weak"),
        text("later", "The War of 1812", "This war comes decades later.", "none", "place", "place"),
        text("one", "One tax did it", "One tax started the whole war by itself.", "none", "myth", "myth"),
      ],
      late: "The Intolerable Acts came after the tea protest. Anger had already been building for years.",
      mcPrompt: "Which source is the 1765 tax on paper?",
      mc: ["The Stamp Act", "The Declaration", "The War of 1812", "One tax did it"],
      mcAnswer: "The Stamp Act",
      msPrompt: "Which sources are protests or punishments, not the Declaration? Choose all that apply.",
      ms: ["The Boston Tea Party", "The Intolerable Acts", "The Declaration", "The War of 1812"],
      msAnswers: ["The Boston Tea Party", "The Intolerable Acts"],
      tfPrompt: "Our sources say one tax started the whole war by itself.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["laws that punished Boston", "the Declaration", "a later war"],
      icAnswer: "laws that punished Boston",
    })),
    "SS.5.19A-EX": withReasons(exhibit({
      id: "SS.5.19A-EX", standard: "SS.5.19A-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.19A", title: "Rights in real life",
      job: "Show four rights the Bill of Rights protects.",
      detail: "A right here means a protection in the Bill of Rights, not every freedom a person might wish for.",
      mythId: "school",
      spots: [
        { id: "press", label: "Freedom of the press" },
        { id: "religion", label: "Freedom of religion" },
        { id: "assembly", label: "Freedom to gather" },
        { id: "trial", label: "A fair trial" },
      ],
      cards: [
        text("press", "A newspaper prints a story", "The paper can print a story the mayor dislikes.", "press"),
        text("religion", "A place of worship", "People may meet to practice their religion.", "religion"),
        text("assembly", "A peaceful protest", "People gather peacefully with signs.", "assembly"),
        text("trial", "A jury trial", "A person accused of a crime can have a jury.", "trial"),
        text("drive", "A driver's license", "Driving a car is not a right listed in the Bill of Rights.", "none", "topic", "weak"),
        text("yell", "Shouting down a class", "Free speech does not mean there are no rules at school.", "none", "picture", "weak"),
        text("school", "No rules at school", "Free speech means a student never has to follow a school rule.", "none", "myth", "myth"),
      ],
      late: "A student may wear an armband to share an idea. The school can still have rules that keep class going.",
      mcPrompt: "Which source shows freedom of the press?",
      mc: ["A newspaper prints a story", "A driver's license", "Shouting down a class", "No rules at school"],
      mcAnswer: "A newspaper prints a story",
      msPrompt: "Which sources show gathering or a fair trial? Choose all that apply.",
      ms: ["A peaceful protest", "A jury trial", "A driver's license", "Shouting down a class"],
      msAnswers: ["A peaceful protest", "A jury trial"],
      tfPrompt: "Our sources say free speech means a student never has to follow a school rule.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["no rules at school", "freedom of the press", "a driver's license"],
      icAnswer: "no rules at school",
    })),
    "SS.5.16D-EX": withReasons(exhibit({
      id: "SS.5.16D-EX", standard: "SS.5.16D-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.16D", title: "Portrait of Lady Liberty",
      job: "Show four true things the Statue of Liberty stands for.",
      detail: "France gave the statue to the United States. It was not built by Americans alone.",
      mythId: "built",
      spots: [
        { id: "gift", label: "A gift" },
        { id: "torch", label: "The torch" },
        { id: "chains", label: "Broken chains" },
        { id: "poem", label: "The welcome" },
      ],
      cards: [
        photo("gift", "The statue", "A gift from the people of France", "/maker/liberty.jpg", "gift"),
        text("torch", "The torch", "The torch stands for liberty lighting the way.", "torch"),
        text("chains", "Broken chains", "Broken chains at her feet stand for the end of slavery.", "chains"),
        text("poem", "The New Colossus", "The poem welcomes people arriving at the harbor.", "poem"),
        text("bell", "The Liberty Bell", "The bell is in Philadelphia. It is a different symbol.", "none", "place", "place"),
        text("brown", "She was brown", "New copper is brown. The green color came later. The card pretends the brown photo is how she was meant to look forever.", "none", "picture", "weak"),
        text("built", "Americans built her alone", "The statue was built by Americans with no help from France.", "none", "myth", "myth"),
      ],
      late: "The poem was added later, on a plaque. The welcome became part of what people see in her.",
      mcPrompt: "Which source shows who gave the statue?",
      mc: ["The statue", "The Liberty Bell", "She was brown", "Americans built her alone"],
      mcAnswer: "The statue",
      msPrompt: "Which sources tell what a part of the statue means? Choose all that apply.",
      ms: ["The torch", "Broken chains", "The Liberty Bell", "She was brown"],
      msAnswers: ["The torch", "Broken chains"],
      tfPrompt: "Our sources say Americans built the statue with no help from France.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the welcome", "the Liberty Bell", "the color of the copper"],
      icAnswer: "the welcome",
    })),
    "SS.5.5A-EX": withReasons(exhibit({
      id: "SS.5.5A-EX", standard: "SS.5.5A-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.5A", title: "Four problems to solve",
      job: "Show four arguments the Constitutional Convention had to settle.",
      detail: "Say what the compromise did, including when it was unjust.",
      mythId: "easy",
      spots: [
        { id: "states", label: "Big states and small states" },
        { id: "people", label: "How enslaved people were counted" },
        { id: "trade", label: "Trade" },
        { id: "power", label: "How strong the nation would be" },
      ],
      cards: [
        text("states", "The Great Compromise", "Congress got two houses. One is by population. One gives every state two votes.", "states"),
        text("people", "The Three-Fifths Compromise", "Enslaved people were counted as three-fifths of a person for representation. That gave slave states more power. It was unjust.", "people"),
        text("trade", "The trade compromise", "Congress could tax imports. It could not tax exports, and it put off ending the slave trade.", "trade"),
        text("power", "A stronger nation", "The new plan replaced the weak Articles of Confederation with a stronger national government.", "power"),
        text("later", "The Civil War", "The Civil War comes decades later. It is not a compromise at this meeting.", "none", "place", "place"),
        text("king", "They crowned a king", "The delegates did not create a king.", "none", "picture", "weak"),
        text("easy", "Everyone already agreed", "The states already agreed, so the convention had nothing hard to solve.", "none", "myth", "myth"),
      ],
      late: "Counting enslaved people as less than a whole person was a political deal. It was not fairness.",
      mcPrompt: "Which source settled the fight between big states and small states?",
      mc: ["The Great Compromise", "The Civil War", "They crowned a king", "Everyone already agreed"],
      mcAnswer: "The Great Compromise",
      msPrompt: "Which sources are compromises that involved slavery? Choose all that apply.",
      ms: ["The Three-Fifths Compromise", "The trade compromise", "The Civil War", "They crowned a king"],
      msAnswers: ["The Three-Fifths Compromise", "The trade compromise"],
      tfPrompt: "Our sources say the states already agreed, so nothing hard had to be solved.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["how enslaved people were counted", "a later war", "a king"],
      icAnswer: "how enslaved people were counted",
    })),
    "3.3G-EX": withReasons(exhibit({
      id: "3.3G-EX", standard: "3.3G-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.3G", title: "The same amount",
      job: "Prove that 1/2 and 2/4 are the same amount.",
      detail: "The wholes have to be the same size. A bigger pizza does not make a fair compare.",
      mythId: "bigger",
      spots: [
        { id: "line", label: "Same point on a line" },
        { id: "strip", label: "Same-size strips" },
        { id: "circle", label: "Same-size circles" },
        { id: "set", label: "A set of equal parts" },
      ],
      cards: [
        text("line", "The same point", "1/2 and 2/4 land on the same point of a number line.", "line"),
        model("strip", "Two strips", "Same length, same amount shaded", { type: "fraction", parts: 4, shaded: 2, note: "2 of 4 matches 1 of 2" }, "strip"),
        model("circle", "Two circles", "Same-size wholes", { type: "fraction", parts: 2, shaded: 1, note: "1 of 2 shaded" }, "circle"),
        text("set", "Two of four counters", "2 shaded counters out of 4 is the same share as 1 out of 2.", "set"),
        text("pizza", "Different pizzas", "1/2 of a large pizza is more food than 2/4 of a small one. The wholes are not equal.", "none", "picture", "weak"),
        text("unequal", "Unequal parts", "The bar is split into pieces that are not the same size.", "none", "topic", "weak"),
        text("bigger", "Four means bigger", "2/4 is bigger because 4 is bigger than 2.", "none", "myth", "myth"),
      ],
      late: "Fold a same-size strip in half, then in fourths. The 1/2 mark and the 2/4 mark touch.",
      mcPrompt: "Which source shows 1/2 and 2/4 on a number line?",
      mc: ["The same point", "Different pizzas", "Unequal parts", "Four means bigger"],
      mcAnswer: "The same point",
      msPrompt: "Which sources use same-size wholes? Choose all that apply.",
      ms: ["Two strips", "Two circles", "Different pizzas", "Unequal parts"],
      msAnswers: ["Two strips", "Two circles"],
      tfPrompt: "Our sources say 2/4 is bigger because 4 is bigger than 2.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["same-size strips", "different pizzas", "unequal parts"],
      icAnswer: "same-size strips",
    })),
    "3.4E-EX": withReasons(exhibit({
      id: "3.4E-EX", standard: "3.4E-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.4E", title: "Every way to show 4 × 6",
      job: "Show four true ways to represent 4 × 6.",
      detail: "4 × 6 means 4 groups of 6, or 6 added four times. It does not mean 4 + 6.",
      mythId: "plus",
      spots: [
        { id: "add", label: "Repeated addition" },
        { id: "groups", label: "Equal groups" },
        { id: "array", label: "An array" },
        { id: "jumps", label: "Jumps on a line" },
      ],
      cards: [
        text("add", "6 + 6 + 6 + 6", "Six is added four times.", "add"),
        text("groups", "4 groups of 6", "Four circles with six dots in each.", "groups"),
        model("array", "A 4 by 6 array", "4 rows of 6", { type: "array", rows: 4, cols: 6 }, "array"),
        text("jumps", "Jumps of 6", "Four jumps of 6 land on 24.", "jumps"),
        text("plus", "4 + 6", "4 + 6 = 10. That is addition, not 4 groups of 6.", "none", "myth", "myth"),
        model("wrong", "A 4 by 5 array", "One column short", { type: "array", rows: 4, cols: 5 }, "none", "picture", "weak"),
        text("uneven", "Unequal groups", "One group has 6, one has 4, one has 8.", "none", "topic", "weak"),
      ],
      late: "A 6 by 4 array is still 24. Turning the array does not change the product.",
      mcPrompt: "Which source is repeated addition for 4 × 6?",
      mc: ["6 + 6 + 6 + 6", "4 + 6", "A 4 by 5 array", "Unequal groups"],
      mcAnswer: "6 + 6 + 6 + 6",
      msPrompt: "Which sources show exactly four groups or rows of six? Choose all that apply.",
      ms: ["4 groups of 6", "A 4 by 6 array", "4 + 6", "A 4 by 5 array"],
      msAnswers: ["4 groups of 6", "A 4 by 6 array"],
      tfPrompt: "Our sources say 4 × 6 is the same as 4 + 6.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["an array", "4 + 6", "unequal groups"],
      icAnswer: "an array",
    })),
    "3.2A-EX": withReasons(exhibit({
      id: "3.2A-EX", standard: "3.2A-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.2A", title: "Portrait of 4,352",
      job: "Show what each digit in 4,352 is worth.",
      detail: "The 3 is in the hundreds place. It is worth 300, not 3.",
      mythId: "three",
      spots: [
        { id: "expand", label: "Expanded form" },
        { id: "words", label: "Words" },
        { id: "chart", label: "A place-value chart" },
        { id: "hundreds", label: "How many hundreds" },
      ],
      cards: [
        text("expand", "4,000 + 300 + 50 + 2", "Each digit is written with its value.", "expand"),
        text("words", "Four thousand three hundred fifty-two", "The number in words.", "words"),
        model("chart", "Place-value chart", "4 thousands, 3 hundreds, 5 tens, 2 ones", { type: "place", cells: [{ label: "thousands", value: "4" }, { label: "hundreds", value: "3" }, { label: "tens", value: "5" }, { label: "ones", value: "2" }] }, "chart"),
        text("hundreds", "43 hundreds + 52", "43 hundreds is 4,300, plus 52 more is 4,352.", "hundreds"),
        text("miss", "4,000 + 300 + 5 + 2", "The 5 was written as 5 ones, not 5 tens.", "none", "picture", "weak"),
        text("small", "400 + 300 + 50 + 2", "The 4 was written as 400, not 4,000.", "none", "topic", "weak"),
        text("three", "The 3 is worth 3", "The 3 in 4,352 is worth 3.", "none", "myth", "myth"),
      ],
      late: "Cover the 4 and the 52. The 3 is still in the hundreds place, so it is 300.",
      mcPrompt: "Which source is the expanded form of 4,352?",
      mc: ["4,000 + 300 + 50 + 2", "4,000 + 300 + 5 + 2", "400 + 300 + 50 + 2", "The 3 is worth 3"],
      mcAnswer: "4,000 + 300 + 50 + 2",
      msPrompt: "Which sources give the 3 a value of 300? Choose all that apply.",
      ms: ["Four thousand three hundred fifty-two", "Place-value chart", "4,000 + 300 + 5 + 2", "The 3 is worth 3"],
      msAnswers: ["Four thousand three hundred fifty-two", "Place-value chart"],
      tfPrompt: "Our sources say the 3 in 4,352 is worth 3.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["how many hundreds", "400 instead of 4,000", "5 ones instead of 5 tens"],
      icAnswer: "how many hundreds",
    })),
    "3.6A-EX": withReasons(exhibit({
      id: "3.6A-EX", standard: "3.6A-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.6A", title: "Every kind of shape",
      job: "Show a triangle, a square, a rectangle, and a circle.",
      detail: "A square is a special rectangle. A tilted square is still a square. A blob is not a polygon.",
      mythId: "sides",
      spots: [
        { id: "tri", label: "A triangle" },
        { id: "sq", label: "A square" },
        { id: "rect", label: "A rectangle" },
        { id: "cir", label: "A circle" },
      ],
      cards: [
        model("tri", "A triangle", "3 straight sides", { type: "shape", shape: "triangle" }, "tri"),
        model("sq", "A square", "4 equal sides and 4 square corners", { type: "shape", shape: "square" }, "sq"),
        model("rect", "A rectangle", "4 square corners, opposite sides equal", { type: "shape", shape: "rectangle" }, "rect"),
        model("cir", "A circle", "A round shape, no corners", { type: "shape", shape: "circle" }, "cir"),
        text("blob", "A blob", "The outline curves in a way that is not a circle and has no straight sides.", "none", "topic", "weak"),
        model("rhomb", "A leaning diamond", "4 equal sides, but the corners are not square", { type: "shape", shape: "rhombus" }, "none", "picture", "weak"),
        text("sides", "A circle has sides", "A circle has four curved sides.", "none", "myth", "myth"),
      ],
      late: "A square can also be called a rectangle because it has four square corners. It still belongs on the square spot if that is the best fit.",
      mcPrompt: "Which source has exactly three straight sides?",
      mc: ["A triangle", "A blob", "A leaning diamond", "A circle has sides"],
      mcAnswer: "A triangle",
      msPrompt: "Which sources have four square corners? Choose all that apply.",
      ms: ["A square", "A rectangle", "A blob", "A leaning diamond"],
      msAnswers: ["A square", "A rectangle"],
      tfPrompt: "Our sources say a circle has four curved sides.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a square", "a blob", "a circle has sides"],
      icAnswer: "a square",
    })),
    "4.3D-EX": withReasons(exhibit({
      id: "4.3D-EX", standard: "4.3D-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.3D", title: "Which is bigger",
      job: "Prove that 3/4 is greater than 2/3.",
      detail: "Compare same-size wholes. Thirds are larger pieces than fourths, but 2 pieces are not automatically more than 3.",
      mythId: "thirds",
      spots: [
        { id: "bars", label: "Same-size bars" },
        { id: "line", label: "A number line" },
        { id: "common", label: "A common denominator" },
        { id: "bench", label: "Distance from 1" },
      ],
      cards: [
        model("bars", "Fraction bars", "Same-size wholes", { type: "fraction", parts: 4, shaded: 3, note: "3/4 shaded" }, "bars"),
        text("line", "On the number line", "3/4 sits to the right of 2/3.", "line"),
        text("common", "9/12 and 8/12", "3/4 = 9/12 and 2/3 = 8/12. 9 twelfths is more.", "common"),
        text("bench", "Closer to 1", "3/4 is 1/4 away from 1. 2/3 is 1/3 away. 1/4 is the smaller gap.", "bench"),
        text("thirds", "Thirds are bigger", "Thirds are bigger pieces than fourths, so 2/3 wins.", "none", "myth", "myth"),
        text("pizzas", "Different-size wholes", "3/4 of a large bar next to 2/3 of a short bar.", "none", "picture", "weak"),
        text("equal", "3/4 = 6/8", "That is true, and it never compares 3/4 to 2/3.", "none", "topic", "weak"),
      ],
      late: "Once both fractions are twelfths, the bigger numerator is the greater fraction.",
      mcPrompt: "Which source rewrites both fractions with the same denominator?",
      mc: ["9/12 and 8/12", "Thirds are bigger", "Different-size wholes", "3/4 = 6/8"],
      mcAnswer: "9/12 and 8/12",
      msPrompt: "Which sources compare 3/4 and 2/3 directly? Choose all that apply.",
      ms: ["Fraction bars", "On the number line", "Different-size wholes", "3/4 = 6/8"],
      msAnswers: ["Fraction bars", "On the number line"],
      tfPrompt: "Our sources say 2/3 is greater because thirds are bigger pieces.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a common denominator", "different-size wholes", "an equivalent that does not compare"],
      icAnswer: "a common denominator",
    })),
    "4.6B-EX": withReasons(exhibit({
      id: "4.6B-EX", standard: "4.6B-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.6B", title: "Symmetry everywhere",
      job: "Show four figures that have a line of symmetry.",
      detail: "A line of symmetry folds the figure onto itself. The letter S does not have one.",
      mythId: "diagonal",
      spots: [
        { id: "one", label: "One line" },
        { id: "letter", label: "A letter" },
        { id: "four", label: "Four lines" },
        { id: "many", label: "More than four" },
      ],
      cards: [
        text("one", "A butterfly", "One line down the middle matches the wings.", "one"),
        text("letter", "The letter A", "A vertical line splits A into matching halves.", "letter"),
        model("four", "A square", "Four lines of symmetry", { type: "shape", shape: "square" }, "four"),
        model("many", "A circle", "Every diameter is a line of symmetry", { type: "shape", shape: "circle" }, "many"),
        text("ess", "The letter S", "S looks balanced, but a fold does not match.", "none", "picture", "weak"),
        text("diagonal", "A rectangle's diagonal", "A diagonal of a long rectangle is a line of symmetry.", "none", "myth", "myth"),
        text("blob", "A random blob", "No fold matches.", "none", "topic", "weak"),
      ],
      late: "Turn the square. The fold from corner to corner matches, and so does the fold across the middle.",
      mcPrompt: "Which source has exactly one line of symmetry down the middle?",
      mc: ["A butterfly", "The letter S", "A rectangle's diagonal", "A random blob"],
      mcAnswer: "A butterfly",
      msPrompt: "Which sources have more than one line of symmetry? Choose all that apply.",
      ms: ["A square", "A circle", "The letter S", "A random blob"],
      msAnswers: ["A square", "A circle"],
      tfPrompt: "Our sources say a diagonal of a long rectangle is a line of symmetry.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["four lines", "the letter S", "a blob"],
      icAnswer: "four lines",
    })),
    "4.7A-EX": withReasons(exhibit({
      id: "4.7A-EX", standard: "4.7A-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.7A", title: "Portrait of a right angle",
      job: "Show four models of a 90 degree angle.",
      detail: "Longer rays do not make a bigger angle. The opening does.",
      mythId: "rays",
      spots: [
        { id: "quarter", label: "A quarter circle" },
        { id: "paper", label: "A paper corner" },
        { id: "clock", label: "A clock" },
        { id: "square", label: "A square's corner" },
      ],
      cards: [
        text("quarter", "A quarter of a circle", "Two radii with a quarter turn between them make 90 degrees.", "quarter"),
        text("paper", "The corner of a sheet", "The corner of a notebook page is a right angle.", "paper"),
        text("clock", "3:00", "The hands at 3:00 form a right angle.", "clock"),
        model("square", "A square corner", "Each corner is 90 degrees", { type: "shape", shape: "square" }, "square"),
        text("two", "2:00", "At 2:00 the hands are 60 degrees, not 90.", "none", "picture", "weak"),
        text("straight", "A straight line", "A straight line is 180 degrees.", "none", "place", "place"),
        text("rays", "Longer rays", "Longer rays make a bigger angle.", "none", "myth", "myth"),
      ],
      late: "Stretch the rays on the paper corner. The corner is still the same square corner.",
      mcPrompt: "Which clock time is a right angle?",
      mc: ["3:00", "2:00", "A straight line", "Longer rays"],
      mcAnswer: "3:00",
      msPrompt: "Which sources are square corners you can hold or draw? Choose all that apply.",
      ms: ["The corner of a sheet", "A square corner", "2:00", "A straight line"],
      msAnswers: ["The corner of a sheet", "A square corner"],
      tfPrompt: "Our sources say longer rays make a bigger angle.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a paper corner", "2:00", "a straight line"],
      icAnswer: "a paper corner",
    })),
    "4.9A-EX": withReasons(exhibit({
      id: "4.9A-EX", standard: "4.9A-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.9A", title: "Four ways to show the data",
      job: "Show the same data four ways: cats 2, dogs 5, birds 3.",
      detail: "The display has to match those three numbers.",
      mythId: "picture",
      spots: [
        { id: "table", label: "A frequency table" },
        { id: "bar", label: "A bar graph" },
        { id: "dot", label: "A dot plot" },
        { id: "picto", label: "A pictograph" },
      ],
      cards: [
        text("table", "A frequency table", "Cats 2, dogs 5, birds 3.", "table"),
        { id: "bar", title: "A bar graph", tag: "Dogs tallest, then birds, then cats", image: "", role: "strong", reason: "point", job: "bar", kind: "graph", bars: [{ label: "Dogs", height: "100%" }, { label: "Birds", height: "60%" }, { label: "Cats", height: "40%" }] },
        text("dot", "A dot plot", "Two dots over cats, five over dogs, three over birds.", "dot"),
        text("picto", "A pictograph", "Each picture is one pet. Dogs have five pictures.", "picto"),
        text("wrong", "Dogs have 4", "This table says dogs 4. The data says 5.", "none", "picture", "weak"),
        text("story", "A story about a dog", "The story does not show the counts.", "none", "topic", "weak"),
        text("picture", "Pictures are just cute", "A pictograph is only decoration. The pictures do not stand for numbers.", "none", "myth", "myth"),
      ],
      late: "If each picture stands for 1 pet, five dog pictures means 5 dogs, the same as the table.",
      mcPrompt: "Which source is the frequency table?",
      mc: ["A frequency table", "Dogs have 4", "A story about a dog", "Pictures are just cute"],
      mcAnswer: "A frequency table",
      msPrompt: "Which sources can show dogs as the greatest number? Choose all that apply.",
      ms: ["A bar graph", "A dot plot", "Dogs have 4", "A story about a dog"],
      msAnswers: ["A bar graph", "A dot plot"],
      tfPrompt: "Our sources say the pictures in a pictograph do not stand for numbers.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a pictograph", "a wrong table", "a story"],
      icAnswer: "a pictograph",
    })),
    "5.3H-EX": withReasons(exhibit({
      id: "5.3H-EX", standard: "5.3H-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.3H", title: "Not 2/5",
      job: "Prove that 1/2 + 1/3 = 5/6.",
      detail: "You cannot add the numerators and the denominators. 1/2 + 1/3 is not 2/5.",
      mythId: "add",
      spots: [
        { id: "rewrite", label: "Common denominators" },
        { id: "bars", label: "Fraction bars" },
        { id: "line", label: "Jumps on a line" },
        { id: "area", label: "An area model" },
      ],
      cards: [
        text("rewrite", "3/6 + 2/6", "1/2 = 3/6 and 1/3 = 2/6. Together that is 5/6.", "rewrite"),
        model("bars", "Bars that match", "Same-size wholes", { type: "fraction", parts: 6, shaded: 5, note: "5/6" }, "bars"),
        text("line", "Two jumps", "A jump of 1/2 and a jump of 1/3 land on 5/6.", "line"),
        text("area", "An area model", "A rectangle split into sixths shows 3 shaded plus 2 shaded.", "area"),
        text("add", "2/5", "1/2 + 1/3 = 2/5 if you add straight across.", "none", "myth", "myth"),
        text("sizes", "Different wholes", "1/2 of a long bar plus 1/3 of a short bar.", "none", "picture", "weak"),
        text("cant", "You cannot add them", "You cannot add fractions with different denominators.", "none", "topic", "weak"),
      ],
      late: "The sixths are the same size, so 3 of them plus 2 of them is 5 of them.",
      mcPrompt: "Which source rewrites the addends with a common denominator?",
      mc: ["3/6 + 2/6", "2/5", "Different wholes", "You cannot add them"],
      mcAnswer: "3/6 + 2/6",
      msPrompt: "Which sources show the sum as 5/6? Choose all that apply.",
      ms: ["Bars that match", "Two jumps", "2/5", "Different wholes"],
      msAnswers: ["Bars that match", "Two jumps"],
      tfPrompt: "Our sources say 1/2 + 1/3 = 2/5.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["common denominators", "adding straight across", "different wholes"],
      icAnswer: "common denominators",
    })),
    "5.5-EX": withReasons(exhibit({
      id: "5.5-EX", standard: "5.5-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.5", title: "Every kind of rectangle",
      job: "Show four rectangles, including a square.",
      detail: "A square is a rectangle. A leaning parallelogram is not, if the corners are not square.",
      mythId: "square",
      spots: [
        { id: "long", label: "A long rectangle" },
        { id: "tall", label: "A tall rectangle" },
        { id: "door", label: "A door" },
        { id: "sq", label: "A square" },
      ],
      cards: [
        model("long", "A long rectangle", "Four square corners", { type: "shape", shape: "rectangle" }, "long"),
        text("tall", "A tall rectangle", "Taller than it is wide, with four square corners.", "tall"),
        text("door", "A door", "A door is a rectangle.", "door"),
        model("sq", "A square", "A rectangle with equal sides", { type: "shape", shape: "square" }, "sq"),
        model("lean", "A leaning shape", "Opposite sides parallel, corners not square", { type: "shape", shape: "rhombus" }, "none", "picture", "weak"),
        text("blob", "A blob", "No straight sides.", "none", "topic", "weak"),
        text("square", "A square is not a rectangle", "A square cannot be a rectangle.", "none", "myth", "myth"),
      ],
      late: "Check the corners, not the side lengths. Four square corners is enough to call it a rectangle.",
      mcPrompt: "Which source is a square that still counts as a rectangle?",
      mc: ["A square", "A leaning shape", "A blob", "A square is not a rectangle"],
      mcAnswer: "A square",
      msPrompt: "Which sources have four square corners and are not squares? Choose all that apply.",
      ms: ["A long rectangle", "A door", "A leaning shape", "A blob"],
      msAnswers: ["A long rectangle", "A door"],
      tfPrompt: "Our sources say a square cannot be a rectangle.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a square", "a leaning shape", "a blob"],
      icAnswer: "a square",
    })),
    "5.8A-EX": withReasons(exhibit({
      id: "5.8A-EX", standard: "5.8A-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.8A", title: "Portrait of the coordinate plane",
      job: "Show the parts of the coordinate plane and how to plot (3, 5).",
      detail: "Go over on the x-axis first, then up on the y-axis. (3, 5) is not (5, 3).",
      mythId: "up",
      spots: [
        { id: "x", label: "The x-axis" },
        { id: "y", label: "The y-axis" },
        { id: "origin", label: "The origin" },
        { id: "point", label: "The point (3, 5)" },
      ],
      cards: [
        text("x", "The x-axis", "The horizontal number line.", "x"),
        text("y", "The y-axis", "The vertical number line.", "y"),
        text("origin", "The origin", "(0, 0) is where the axes cross.", "origin"),
        text("point", "Over 3, up 5", "Start at the origin, move right 3, then up 5.", "point"),
        text("swap", "(5, 3) by mistake", "The point was plotted right 5 and up 3.", "none", "picture", "weak"),
        text("slant", "Slanted axes", "The axes in this picture are not perpendicular.", "none", "topic", "weak"),
        text("up", "Up first", "You go up first, then over.", "none", "myth", "myth"),
      ],
      late: "The first number of (3, 5) tells the x-move. The second number tells the y-move.",
      mcPrompt: "Which source is the origin?",
      mc: ["The origin", "(5, 3) by mistake", "Slanted axes", "Up first"],
      mcAnswer: "The origin",
      msPrompt: "Which sources name an axis? Choose all that apply.",
      ms: ["The x-axis", "The y-axis", "(5, 3) by mistake", "Slanted axes"],
      msAnswers: ["The x-axis", "The y-axis"],
      tfPrompt: "Our sources say you plot a point by going up first, then over.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the point (3, 5)", "slanted axes", "up first"],
      icAnswer: "the point (3, 5)",
    })),
    "5.2A-EX": withReasons(exhibit({
      id: "5.2A-EX", standard: "5.2A-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.2A", title: "Portrait of 3.47",
      job: "Show what each digit in 3.47 is worth.",
      detail: "The 4 is tenths. The 7 is hundredths. The 4 is not worth 4 ones.",
      mythId: "ones",
      spots: [
        { id: "expand", label: "Expanded form" },
        { id: "words", label: "Words" },
        { id: "chart", label: "A place-value chart" },
        { id: "tenths", label: "The 4" },
      ],
      cards: [
        text("expand", "3 + 0.4 + 0.07", "Each digit is written with its value.", "expand"),
        text("words", "Three and forty-seven hundredths", "The number in words.", "words"),
        model("chart", "Place-value chart", "ones, tenths, hundredths", { type: "place", cells: [{ label: "ones", value: "3" }, { label: "tenths", value: "4" }, { label: "hundredths", value: "7" }] }, "chart"),
        text("tenths", "The 4 is 4 tenths", "The 4 is one place to the right of the decimal, so it is 0.4.", "tenths"),
        text("swap", "3 + 0.7 + 0.04", "The 4 and the 7 were swapped.", "none", "picture", "weak"),
        text("money", "347 cents only", "This card treats 3.47 as 347 and drops the decimal.", "none", "topic", "weak"),
        text("ones", "The 4 is worth 4", "The 4 in 3.47 is worth 4 ones.", "none", "myth", "myth"),
      ],
      late: "Move one place right from the ones. That place is tenths, so the 4 is 4 tenths.",
      mcPrompt: "Which source is the expanded form of 3.47?",
      mc: ["3 + 0.4 + 0.07", "3 + 0.7 + 0.04", "347 cents only", "The 4 is worth 4"],
      mcAnswer: "3 + 0.4 + 0.07",
      msPrompt: "Which sources put the 4 in the tenths place? Choose all that apply.",
      ms: ["Three and forty-seven hundredths", "Place-value chart", "3 + 0.7 + 0.04", "The 4 is worth 4"],
      msAnswers: ["Three and forty-seven hundredths", "Place-value chart"],
      tfPrompt: "Our sources say the 4 in 3.47 is worth 4 ones.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the 4", "swapped digits", "dropping the decimal"],
      icAnswer: "the 4",
    })),
  };
}
