const RING = [
  { id: "n", label: "Above" },
  { id: "e", label: "Right" },
  { id: "s", label: "Below" },
  { id: "w", label: "Left" },
];

function text(id, title, body, job, reason = "point", role = "strong") {
  return { id, title, tag: role === "myth" ? "A common mistake" : "A note", image: "", role, reason, job, kind: "text", text: body };
}
function photo(id, title, tag, image, job, reason = "point", role = "strong") {
  return { id, title, tag, image, role, reason, job };
}
function drawn(id, title, tag, model, job) {
  return { id, title, tag, image: "", role: "strong", reason: "point", job, kind: "model", model };
}
function exhibit(fields) {
  return { stamps: ["Picture", "Note", "Test"], lateTitle: "Late field note", layout: "portrait", spots: RING, ...fields };
}

export function portraitCases(reasons) {
  const wrap = (item) => ({ ...item, reasons });
  return {
    "3.9A-EX": wrap(exhibit({
      id: "3.9A-EX", standard: "3.9A-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.9A", title: "Portrait of a day",
      job: "Put true, important pieces around Earth. Order does not matter.",
      detail: "Day and night come from Earth spinning. The Sun is not racing around Earth once a day.",
      mythId: "race",
      center: { title: "Earth", caption: "The bright half is the side facing the Sun.", kind: "model", model: { type: "day" } },
      cards: [
        text("spin", "Earth spins", "One full spin is about one day.", "ring"),
        text("day", "Facing the Sun", "The side facing the Sun is in daylight.", "ring"),
        text("night", "Facing away", "The side facing away from the Sun is in night.", "ring"),
        text("still", "The Sun stays put", "Day and night are not made by the Sun circling Earth.", "ring"),
        text("stars", "The stars seem to move", "As Earth turns, the stars look like they slide across the sky.", "ring"),
        text("race", "The Sun races around", "The Sun travels around Earth once every day.", "none", "myth", "myth"),
        text("moon", "The Moon blocks the Sun", "The Moon covers the Sun every night. That is why it gets dark.", "none", "place", "place"),
        text("lamp", "A lamp switch", "Someone turned a lamp off. That is not day and night.", "none", "topic", "weak"),
      ],
      late: "A place on Earth moves from daylight into night as Earth keeps spinning.",
      mcPrompt: "Which source explains daylight?",
      mc: ["Facing the Sun", "The Sun races around", "The Moon blocks the Sun", "A lamp switch"],
      mcAnswer: "Facing the Sun",
      msPrompt: "Which sources are about Earth's spin? Choose all that apply.",
      ms: ["Earth spins", "Facing away", "The Sun races around", "A lamp switch"],
      msAnswers: ["Earth spins", "Facing away"],
      tfPrompt: "Our sources say the Sun travels around Earth once every day.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a place moves into night", "the Moon", "a lamp"],
      icAnswer: "a place moves into night",
    })),
    "4.10B-EX": wrap(exhibit({
      id: "4.10B-EX", standard: "4.10B-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.10B", title: "Portrait of a canyon",
      job: "Put true, important pieces around this canyon. Order does not matter.",
      detail: "Weathering breaks rock. Erosion moves it. Deposition drops it. A canyon is not one crack from an earthquake.",
      mythId: "quake",
      center: { title: "A river canyon", caption: "A river still runs at the bottom.", image: "/maker/canyon-portrait.jpg" },
      cards: [
        text("break", "Weathering", "Weathering breaks the rock into smaller pieces.", "ring"),
        text("carry", "Erosion", "The river carries those pieces away. That is erosion.", "ring"),
        text("slow", "A long time", "The river has been cutting for a very long time, not one afternoon.", "ring"),
        text("drop", "Deposition", "Some carried rock is dropped where the water slows. That is deposition.", "ring"),
        text("layers", "Layers in the walls", "The stripes in the walls are rock layers that were there as the canyon got deeper.", "ring"),
        text("quake", "One earthquake", "A canyon cracks open in one earthquake.", "none", "myth", "myth"),
        text("volcano", "A volcano", "A volcano builds rock up. It does not carve this canyon.", "none", "place", "place"),
        text("ditch", "A dug ditch", "A machine dug this ditch in one day. It is not the canyon.", "none", "picture", "weak"),
      ],
      late: "The river is still moving pieces. The canyon is not finished.",
      mcPrompt: "Which source is erosion?",
      mc: ["Erosion", "One earthquake", "A volcano", "A dug ditch"],
      mcAnswer: "Erosion",
      msPrompt: "Which sources are slow changes to rock? Choose all that apply.",
      ms: ["Weathering", "Deposition", "One earthquake", "A dug ditch"],
      msAnswers: ["Weathering", "Deposition"],
      tfPrompt: "Our sources say a canyon cracks open in one earthquake.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the river is still cutting", "a volcano", "a ditch"],
      icAnswer: "the river is still cutting",
    })),
    "5.8B-EX": wrap(exhibit({
      id: "5.8B-EX", standard: "5.8B-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.8B", title: "Portrait of a circuit",
      job: "Put true, important pieces around this closed circuit. Order does not matter.",
      detail: "A closed path lets the bulb light. Opening the path turns it off. The bulb does not use the electricity up and leave the rest of the wire empty.",
      mythId: "used",
      center: { title: "A closed circuit", caption: "Battery, wire, and bulb in one loop.", kind: "model", model: { type: "circuit" } },
      cards: [
        text("battery", "The battery", "The battery is the energy source for this loop.", "ring"),
        text("closed", "A closed path", "The wire has to make a complete loop.", "ring"),
        text("bulb", "The bulb lights", "The bulb lights when the path is closed.", "ring"),
        text("switch", "The switch", "A switch can open the path and turn the bulb off.", "ring"),
        text("change", "Energy changes", "Electrical energy can change into light at the bulb.", "ring"),
        text("used", "Used up", "The bulb uses up the electricity, so the wire after it is empty.", "none", "myth", "myth"),
        text("magnet", "A fridge magnet", "A magnet on a fridge is not this circuit.", "none", "place", "place"),
        text("gap", "A broken wire", "The wire is cut, and the label says the bulb still lights.", "none", "picture", "weak"),
      ],
      late: "Open the switch and the bulb goes out. Close it and the loop works again.",
      mcPrompt: "Which source is the energy source?",
      mc: ["The battery", "Used up", "A fridge magnet", "A broken wire"],
      mcAnswer: "The battery",
      msPrompt: "Which sources describe a working loop? Choose all that apply.",
      ms: ["A closed path", "The bulb lights", "Used up", "A broken wire"],
      msAnswers: ["A closed path", "The bulb lights"],
      tfPrompt: "Our sources say the bulb uses up the electricity and leaves the wire empty.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a switch opens and closes the loop", "a magnet", "a broken wire"],
      icAnswer: "a switch opens and closes the loop",
    })),
    "ELA.3.10C-EX": wrap(exhibit({
      id: "ELA.3.10C-EX", standard: "ELA.3.10C-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.10C", title: "Portrait of a poster",
      job: "Put true, important pieces around this poster. Order does not matter.",
      detail: "Ask what the poster wants the reader to know and do. The paper color is not the message.",
      mythId: "afraid",
      center: {
        title: "Library Garden Day",
        caption: "The whole poster.",
        kind: "text",
        text: "Library Garden Day. Saturday at 10. Bring a shovel if you can. We will plant tomatoes. Everyone in the neighborhood is welcome.",
      },
      cards: [
        text("come", "The message", "Come help plant tomatoes on Saturday at 10.", "ring"),
        text("invite", "The purpose", "The poster invites people. It does not try to scare them.", "ring"),
        text("who", "Who it is for", "Everyone in the neighborhood is welcome.", "ring"),
        text("shovel", "A helpful detail", "Bring a shovel if you can. That detail is not the whole message.", "ring"),
        text("when", "The time", "Saturday at 10 tells people when to come.", "ring"),
        text("afraid", "Be afraid", "The author wants readers to be afraid of gardens.", "none", "myth", "myth"),
        text("kite", "Another text", "Once there was a girl who lost her kite. That is not this poster.", "none", "place", "place"),
        text("yellow", "Yellow paper", "The poster is printed on yellow paper. That is not its message.", "none", "topic", "weak"),
      ],
      late: "A purpose can be to invite. The time and the shovel are details that support that invitation.",
      mcPrompt: "Which source is the poster's message?",
      mc: ["The message", "Be afraid", "Another text", "Yellow paper"],
      mcAnswer: "The message",
      msPrompt: "Which sources support the invitation? Choose all that apply.",
      ms: ["Who it is for", "The time", "Be afraid", "Another text"],
      msAnswers: ["Who it is for", "The time"],
      tfPrompt: "Our sources say the author wants readers to be afraid of gardens.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the time supports the invitation", "another text", "yellow paper"],
      icAnswer: "the time supports the invitation",
    })),
    "ELA.4.7D-EX": wrap(exhibit({
      id: "ELA.4.7D-EX", standard: "ELA.4.7D-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.7D", title: "Portrait of a summary",
      job: "Put the pieces that belong in a summary around this story. Order does not matter.",
      detail: "A summary keeps the important events and leaves out tiny details. It does not copy every sentence.",
      mythId: "copy",
      center: {
        title: "One more point",
        caption: "The story.",
        kind: "text",
        text: "Nia's team needed one more point. She passed to Mateo instead of shooting. He scored. They won, and Nia grinned.",
      },
      cards: [
        text("need", "They needed a point", "The team needed one more point.", "ring"),
        text("pass", "Nia passed", "Nia passed the ball instead of shooting.", "ring"),
        text("won", "They won", "Mateo scored, and the team won.", "ring"),
        text("rule", "What a summary does", "A summary keeps the important events and leaves tiny details out.", "ring"),
        text("glad", "Nia was glad", "Nia grinned at the end.", "ring"),
        text("copy", "Copy it all", "A summary should copy every sentence.", "none", "myth", "myth"),
        text("shoes", "Blue shoelaces", "Nia's shoelaces were blue. That does not belong in the summary.", "none", "topic", "weak"),
        text("fair", "Another story", "The volcano erupted on the judge. That is a different story.", "none", "place", "place"),
      ],
      late: "Passing, scoring, and winning are the events. The grin shows how it ended.",
      mcPrompt: "Which source belongs in the summary?",
      mc: ["Nia passed", "Copy it all", "Blue shoelaces", "Another story"],
      mcAnswer: "Nia passed",
      msPrompt: "Which sources are important events? Choose all that apply.",
      ms: ["They needed a point", "They won", "Blue shoelaces", "Copy it all"],
      msAnswers: ["They needed a point", "They won"],
      tfPrompt: "Our sources say a summary should copy every sentence.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the grin shows the ending", "blue shoelaces", "another story"],
      icAnswer: "the grin shows the ending",
    })),
    "ELA.5.8A-EX": wrap(exhibit({
      id: "ELA.5.8A-EX", standard: "ELA.5.8A-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.8A", title: "Portrait of a theme",
      job: "Put true ideas this story suggests around it. Order does not matter.",
      detail: "A theme is an idea the story suggests. One event is not the theme.",
      mythId: "event",
      center: {
        title: "The mural",
        caption: "The story.",
        kind: "text",
        text: "Pia kept every marker in her own box. The mural was too big for one person. She opened the box. The class shared the colors, and the wall was finished.",
      },
      cards: [
        text("share", "Sharing finishes the work", "The wall gets finished because the class shares the colors.", "ring"),
        text("hold", "Holding back can stop the work", "While Pia keeps every marker, the mural cannot be finished.", "ring"),
        text("idea", "A theme is an idea", "A theme is an idea the story suggests, not one action.", "ring"),
        text("big", "Too big alone", "Some jobs are too big for one person.", "ring"),
        text("end", "The ending matters", "The finished wall shows what changed when she shared.", "ring"),
        text("event", "She opened a box", "The theme is that Pia opened a box.", "none", "myth", "myth"),
        text("garden", "Afraid of gardens", "The theme is that people should be afraid of gardens.", "none", "place", "place"),
        text("first", "The first sentence", "The theme is always the first sentence, word for word.", "none", "topic", "weak"),
      ],
      late: "Opening the box is an event. The idea is what that event shows about sharing.",
      mcPrompt: "Which source is a theme of this story?",
      mc: ["Sharing finishes the work", "She opened a box", "Afraid of gardens", "The first sentence"],
      mcAnswer: "Sharing finishes the work",
      msPrompt: "Which sources are ideas, not just events? Choose all that apply.",
      ms: ["Holding back can stop the work", "Too big alone", "She opened a box", "The first sentence"],
      msAnswers: ["Holding back can stop the work", "Too big alone"],
      tfPrompt: "Our sources say the theme is that Pia opened a box.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["an event is not the theme", "another story", "the first sentence"],
      icAnswer: "an event is not the theme",
    })),
    "SS.3.4C-EX": wrap(exhibit({
      id: "SS.3.4C-EX", standard: "SS.3.4C-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.4C", title: "Portrait of a map",
      job: "Put true, important pieces around this map. Order does not matter.",
      detail: "A map needs a title, a compass rose, and a key. The top of the page is not uphill.",
      mythId: "hill",
      center: { title: "Mesquite Springs", caption: "A street map of a model town.", kind: "model", model: { type: "map" } },
      cards: [
        text("rose", "The compass rose", "The compass rose shows north, south, east, and west.", "ring"),
        text("key", "The key", "The key tells what the symbols mean.", "ring"),
        text("title", "The title", "The title tells what place the map shows.", "ring"),
        text("grid", "The grid", "A grid helps you name a square, like B3.", "ring"),
        text("school", "A symbol needs the key", "A picture of a school means a school only if the key says so.", "ring"),
        text("hill", "Top means uphill", "Whatever is at the top of the page is uphill.", "none", "myth", "myth"),
        text("globe", "A globe", "A globe of the whole Earth is not a street map of this town.", "none", "place", "place"),
        text("border", "A fancy border", "A decorated border with no key is not the map.", "none", "picture", "weak"),
      ],
      late: "Find B3, then use the key. The compass rose tells you which way is north on this map.",
      mcPrompt: "Which source tells what the symbols mean?",
      mc: ["The key", "Top means uphill", "A globe", "A fancy border"],
      mcAnswer: "The key",
      msPrompt: "Which sources help you read the map? Choose all that apply.",
      ms: ["The compass rose", "The grid", "Top means uphill", "A globe"],
      msAnswers: ["The compass rose", "The grid"],
      tfPrompt: "Our sources say the top of the page is always uphill.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the key and the compass rose", "a globe", "a border"],
      icAnswer: "the key and the compass rose",
    })),
    "SS.4.14A-EX": wrap(exhibit({
      id: "SS.4.14A-EX", standard: "SS.4.14A-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.14A", title: "Portrait of the Texas flag",
      job: "Put true, important pieces around the Texas flag. Order does not matter.",
      detail: "This flag stands for Texas. It has one star, not fifty. The pledge teaches what the colors stand for.",
      mythId: "fifty",
      center: { title: "The Texas flag", caption: "One white star on a blue stripe.", kind: "model", model: { type: "flag" } },
      cards: [
        text("star", "One star", "The single white star is the Lone Star.", "ring"),
        text("blue", "Loyalty", "In the pledge, the blue stripe stands for loyalty.", "ring"),
        text("colors", "White and red", "In the pledge, white stands for purity and red stands for bravery.", "ring"),
        text("state", "Republic, then state", "Texas flew this flag as a republic, and it stayed the state flag.", "ring"),
        text("where", "The star's place", "The white star sits on the blue stripe.", "ring"),
        text("fifty", "Fifty stars", "The Texas flag has 50 stars.", "none", "myth", "myth"),
        text("us", "The United States flag", "This is a different flag. It does not stand for Texas alone.", "none", "place", "place"),
        text("cloth", "Cotton cloth", "The cloth is cotton. That is not what the flag means.", "none", "topic", "weak"),
      ],
      late: "The lone star was already on the flag when Texas was a republic.",
      mcPrompt: "Which source is the Lone Star?",
      mc: ["One star", "Fifty stars", "The United States flag", "Cotton cloth"],
      mcAnswer: "One star",
      msPrompt: "Which sources tell what the flag stands for? Choose all that apply.",
      ms: ["Loyalty", "White and red", "Fifty stars", "Cotton cloth"],
      msAnswers: ["Loyalty", "White and red"],
      tfPrompt: "Our sources say the Texas flag has 50 stars.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the star goes back to the republic", "the United States flag", "cotton cloth"],
      icAnswer: "the star goes back to the republic",
    })),
    "SS.5.14B-EX": wrap(exhibit({
      id: "SS.5.14B-EX", standard: "SS.5.14B-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.14B", title: "Portrait of the Preamble",
      job: "Put true, important pieces around the Preamble. Order does not matter.",
      detail: "The Preamble states purposes of the Constitution. A famous line from the Declaration is not one of those purposes.",
      mythId: "king",
      center: {
        title: "We the People",
        caption: "The opening of the Constitution.",
        kind: "text",
        text: "We the People of the United States, in Order to form a more perfect Union...",
      },
      cards: [
        text("people", "From the people", "The opening says the government's power comes from the people.", "ring"),
        text("justice", "Establish justice", "One purpose is to establish justice.", "ring"),
        text("defense", "Common defense", "One purpose is to provide for the common defense.", "ring"),
        text("liberty", "Blessings of liberty", "One purpose is to secure the blessings of liberty.", "ring"),
        text("left", "Who was left out", "In 1787 many people were left out of those words. Later amendments widened who they protect.", "ring"),
        text("king", "One ruler", "The Constitution was written so one person could rule.", "none", "myth", "myth"),
        text("declare", "The Declaration", "\"Life, liberty, and the pursuit of happiness\" is in the Declaration of Independence.", "none", "place", "place"),
        text("ink", "Brown ink", "The ink looks brown. That is not a purpose of the Constitution.", "none", "topic", "weak"),
      ],
      late: "The 13th, 14th, and 15th Amendments are later changes. They are not sentences in the Preamble.",
      mcPrompt: "Which source is a purpose in the Preamble?",
      mc: ["Establish justice", "One ruler", "The Declaration", "Brown ink"],
      mcAnswer: "Establish justice",
      msPrompt: "Which sources are purposes named in the Preamble? Choose all that apply.",
      ms: ["Common defense", "Blessings of liberty", "One ruler", "The Declaration"],
      msAnswers: ["Common defense", "Blessings of liberty"],
      tfPrompt: "Our sources say the Constitution was written so one person could rule.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["later amendments widened the words", "the Declaration", "brown ink"],
      icAnswer: "later amendments widened the words",
    })),
    "3.6C-EX": wrap(exhibit({
      id: "3.6C-EX", standard: "3.6C-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.6C", title: "Portrait of this rectangle",
      job: "Put true, important pieces around this rectangle. Order does not matter.",
      detail: "Area counts the square units inside. It is not the distance around the outside.",
      mythId: "around",
      center: { title: "3 rows of 5", caption: "Each dot is one square unit.", kind: "model", model: { type: "array", rows: 3, cols: 5 } },
      cards: [
        text("inside", "Inside the shape", "Area is the number of square units inside.", "ring"),
        drawn("rows", "3 rows of 5", "Count the rows", { type: "array", rows: 3, cols: 5 }, "ring"),
        text("add", "5 + 5 + 5", "Three rows of 5 are 5 + 5 + 5 = 15.", "ring"),
        text("times", "3 × 5 = 15", "The area is 15 square units.", "ring"),
        text("strip", "Another shape, same area", "A 1 by 15 strip of the same squares also has area 15.", "ring"),
        text("around", "The distance around", "Area is the distance around the outside.", "none", "myth", "myth"),
        text("addends", "3 + 5 = 8", "3 + 5 = 8, so the area is 8.", "none", "point", "weak"),
        text("uneven", "Unequal pieces", "The rectangle is split into pieces that are not the same size, and the label says 15.", "none", "picture", "weak"),
      ],
      late: "Count the square units. There are 15, not 8.",
      mcPrompt: "Which source gives the area?",
      mc: ["3 × 5 = 15", "The distance around", "3 + 5 = 8", "Unequal pieces"],
      mcAnswer: "3 × 5 = 15",
      msPrompt: "Which sources count the inside? Choose all that apply.",
      ms: ["Inside the shape", "5 + 5 + 5", "The distance around", "3 + 5 = 8"],
      msAnswers: ["Inside the shape", "5 + 5 + 5"],
      tfPrompt: "Our sources say area is the distance around the outside.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the count is 15, not 8", "the distance around", "unequal pieces"],
      icAnswer: "the count is 15, not 8",
    })),
    "4.6A-EX": wrap(exhibit({
      id: "4.6A-EX", standard: "4.6A-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.6A", title: "Portrait of a ray",
      job: "Put true, important pieces around this ray. Order does not matter.",
      detail: "A ray has one endpoint and goes on in one direction. A segment stops at both ends.",
      mythId: "both",
      center: { title: "Ray AB", caption: "The dot is the endpoint. The arrow does not stop.", kind: "model", model: { type: "ray" } },
      cards: [
        text("end", "One endpoint", "A ray starts at one endpoint.", "ring"),
        text("forever", "One direction", "It goes on without stopping in one direction.", "ring"),
        text("segment", "Not a segment", "A line segment stops at both ends. A ray does not.", "ring"),
        text("angle", "Two rays", "An angle is two rays that share an endpoint.", "ring"),
        text("name", "Name the endpoint first", "Ray AB starts at A and goes through B.", "ring"),
        text("both", "Stops at both ends", "A ray stops at both ends.", "none", "myth", "myth"),
        text("segpic", "A segment", "This drawing stops at two dots, but the label says ray.", "none", "picture", "weak"),
        text("circle", "A circle", "A circle has no endpoint and no single direction.", "none", "place", "place"),
      ],
      late: "If both ends are dots, it is a segment. A ray keeps an arrow on one end.",
      mcPrompt: "Which source describes a ray?",
      mc: ["One endpoint", "Stops at both ends", "A segment", "A circle"],
      mcAnswer: "One endpoint",
      msPrompt: "Which sources are true of a ray? Choose all that apply.",
      ms: ["One direction", "Not a segment", "Stops at both ends", "A circle"],
      msAnswers: ["One direction", "Not a segment"],
      tfPrompt: "Our sources say a ray stops at both ends.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["two dots make a segment", "stops at both ends", "a circle"],
      icAnswer: "two dots make a segment",
    })),
    "5.6B-EX": wrap(exhibit({
      id: "5.6B-EX", standard: "5.6B-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.6B", title: "Portrait of this box",
      job: "Put true, important pieces around this box. Order does not matter.",
      detail: "Volume counts the cubic units inside. It is not the distance around the box, and it is not 2 + 3 + 4.",
      mythId: "around",
      center: { title: "2 × 3 × 4", caption: "Four layers of cubes.", kind: "model", model: { type: "prism", layers: 4 } },
      cards: [
        text("space", "Cubic units inside", "Volume is the number of cubic units that fill the box.", "ring"),
        text("layer", "One layer", "One layer is 2 × 3 = 6 cubes.", "ring"),
        text("four", "Four layers", "6 × 4 = 24 cubic units.", "ring"),
        text("formula", "Length × width × height", "2 × 3 × 4 = 24.", "ring"),
        text("order", "Same volume", "4 × 2 × 3 is still 24. The order of the factors does not change it.", "ring"),
        text("around", "The distance around", "Volume is the distance around the box.", "none", "myth", "myth"),
        text("sum", "2 + 3 + 4 = 9", "2 + 3 + 4 = 9, so the volume is 9.", "none", "point", "weak"),
        text("flat", "A flat 24", "A flat rectangle of 24 squares is the area, not the volume of the box.", "none", "picture", "weak"),
      ],
      late: "Stack the layers. Six cubes in a layer, four layers, 24 cubes.",
      mcPrompt: "Which source is the volume?",
      mc: ["Length × width × height", "The distance around", "2 + 3 + 4 = 9", "A flat 24"],
      mcAnswer: "Length × width × height",
      msPrompt: "Which sources help find the cubic units? Choose all that apply.",
      ms: ["One layer", "Four layers", "The distance around", "2 + 3 + 4 = 9"],
      msAnswers: ["One layer", "Four layers"],
      tfPrompt: "Our sources say volume is the distance around the box.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["four layers make 24", "the distance around", "a flat rectangle"],
      icAnswer: "four layers make 24",
    })),
  };
}
