function text(id, title, body, job, reason = "point", role = "strong") {
  return { id, title, tag: role === "myth" ? "A common mistake" : role === "place" ? "Wrong place" : "A note", image: "", role, reason, job, kind: "text", text: body };
}
function photo(id, title, tag, image, job, reason = "point", role = "strong") {
  return { id, title, tag, image, role, reason, job };
}
function exhibit(fields) {
  return { stamps: ["Picture", "Note", "Test"], lateTitle: "Late field note", layout: "split", ...fields };
}

export function splitCases(reasons) {
  const all = [...reasons, { id: "side", label: "Wrong side" }];
  const wrap = (item) => ({ ...item, reasons: all });
  return {
    "3.10B-EX": wrap(exhibit({
      id: "3.10B-EX", standard: "3.10B-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.10B", title: "Sand or clay",
      job: "Show how sand and clay are different, and what they share.",
      detail: "Sand feels gritty and lets water through. Clay feels sticky and holds water. Both come from weathered rock.",
      mythId: "dirt",
      spots: [{ id: "left", label: "Sand" }, { id: "right", label: "Clay" }, { id: "both", label: "Both" }],
      cards: [
        photo("grit", "Gritty grains", "Sand up close", "/maker/sand.jpg", "left"),
        text("drain", "Water drains fast", "Water runs through sand and does not sit on top.", "left"),
        photo("ball", "A sticky ball", "Clay holds its shape", "/maker/clay.jpg", "right"),
        text("puddle", "Holds a puddle", "Water sits on clay instead of sinking in.", "right"),
        text("rock", "Weathered rock", "Sand and clay both form when rock breaks down.", "both"),
        text("fast", "Clay drains fast", "Clay lets water drain as fast as sand.", "none", "side", "weak"),
        text("bag", "A bag of potting soil", "This bag is a store mix. It does not show how sand or clay formed.", "none", "place", "place"),
        text("dirt", "Just dirt", "Soil is just dirt. Nothing else is in it.", "none", "myth", "myth"),
      ],
      late: "A handful of sand fell apart. A handful of wet clay stayed in a ball. Both started as broken rock.",
      mcPrompt: "Which source shows sand up close?",
      mc: ["Gritty grains", "A sticky ball", "Clay drains fast", "Just dirt"],
      mcAnswer: "Gritty grains",
      msPrompt: "Which sources are true of clay, not sand? Choose all that apply.",
      ms: ["A sticky ball", "Holds a puddle", "Water drains fast", "Clay drains fast"],
      msAnswers: ["A sticky ball", "Holds a puddle"],
      tfPrompt: "Our sources say soil is just dirt and nothing else.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["both", "a bag of potting soil", "clay drains fast"],
      icAnswer: "both",
    })),
    "4.13B-EX": wrap(exhibit({
      id: "4.13B-EX", standard: "4.13B-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.13B", title: "Born with it or picked it up",
      job: "Sort physical traits that come from parents and traits that do not.",
      detail: "Inherited traits are passed from parents. Acquired traits happen during a life. A learned trick is not a physical trait.",
      mythId: "scar",
      spots: [{ id: "left", label: "Inherited" }, { id: "right", label: "Acquired" }, { id: "both", label: "Both are physical traits" }],
      cards: [
        text("fur", "Fur like the mother", "The puppies have the same fur color as their mother.", "left"),
        text("ears", "Ear shape", "The puppies' ears match a parent's ear shape.", "left"),
        text("cut", "A haircut", "The short fur was cut. It was not passed down.", "right"),
        text("tan", "A tan line", "The pale band came from a summer in the sun.", "right"),
        text("body", "You can see them", "Inherited and acquired traits here are both things you can see on the body.", "both"),
        text("sit", "Learned to sit", "Sitting on command is a behavior, not a physical trait.", "none", "topic", "weak"),
        text("muscles", "Muscles pass down", "A bodybuilder's muscles will pass to his children.", "none", "side", "weak"),
        text("scar", "Scars pass down", "Children are born with every scar their parents had.", "none", "myth", "myth"),
      ],
      late: "The tan line faded in winter. The ear shape did not.",
      mcPrompt: "Which source is an inherited trait?",
      mc: ["Fur like the mother", "A haircut", "Learned to sit", "Scars pass down"],
      mcAnswer: "Fur like the mother",
      msPrompt: "Which sources are acquired, not inherited? Choose all that apply.",
      ms: ["A haircut", "A tan line", "Ear shape", "Muscles pass down"],
      msAnswers: ["A haircut", "A tan line"],
      tfPrompt: "Our sources say children are born with their parents' scars.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["an acquired trait can fade", "a learned trick", "scars pass down"],
      icAnswer: "an acquired trait can fade",
    })),
    "5.13B-EX": wrap(exhibit({
      id: "5.13B-EX", standard: "5.13B-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.13B", title: "Born knowing or taught",
      job: "Sort survival behaviors that are instinct and behaviors that are learned.",
      detail: "Instinct happens without being taught. Learned behavior comes from experience. A body part is not a behavior.",
      mythId: "never",
      spots: [{ id: "left", label: "Instinct" }, { id: "right", label: "Learned" }, { id: "both", label: "Both help survival" }],
      cards: [
        text("turtle", "Hatchlings to the sea", "Sea turtle hatchlings head toward the ocean without a lesson.", "left"),
        text("web", "A first web", "A spider spins its first web without being shown how.", "left"),
        text("orca", "A pack hunt", "Orcas learn hunting moves from older whales.", "right"),
        text("chimp", "A stick tool", "A chimp learns to use a stick by watching others.", "right"),
        text("help", "They help the animal live", "Instinct and learned behavior can both help an animal survive.", "both"),
        text("sit", "Sit is instinct", "A dog sitting on command is instinct.", "none", "side", "weak"),
        text("shell", "A hard shell", "A shell is a body part, not a behavior.", "none", "topic", "weak"),
        text("never", "Animals never learn", "Animals never learn anything. Every behavior is instinct.", "none", "myth", "myth"),
      ],
      late: "The dog's sit was practiced. The turtle did not practice the walk to the sea.",
      mcPrompt: "Which source is an instinct?",
      mc: ["Hatchlings to the sea", "Sit is instinct", "A hard shell", "Animals never learn"],
      mcAnswer: "Hatchlings to the sea",
      msPrompt: "Which sources are learned behaviors? Choose all that apply.",
      ms: ["A pack hunt", "A stick tool", "A first web", "A hard shell"],
      msAnswers: ["A pack hunt", "A stick tool"],
      tfPrompt: "Our sources say animals never learn anything.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a learned behavior", "a body part", "animals never learn"],
      icAnswer: "a learned behavior",
    })),
    "SS.3.10B-EX": wrap(exhibit({
      id: "SS.3.10B-EX", standard: "SS.3.10B-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.10B", title: "Two Texas celebrations",
      job: "Show how Juneteenth and Cinco de Mayo are different, and what they share.",
      detail: "Juneteenth marks June 19, 1865, when freedom was announced in Galveston. Cinco de Mayo marks the Mexican army's victory at Puebla on May 5, 1862. Mexico's Independence Day is September 16.",
      mythId: "indep",
      spots: [{ id: "left", label: "Juneteenth" }, { id: "right", label: "Cinco de Mayo" }, { id: "both", label: "Both" }],
      cards: [
        text("june", "June 19, 1865", "Freedom for enslaved people in Texas was announced in Galveston.", "left"),
        text("galveston", "Galveston", "The announcement that is remembered on Juneteenth happened in Galveston.", "left"),
        text("puebla", "The Battle of Puebla", "On May 5, 1862, the Mexican army won a battle at Puebla.", "right"),
        text("mexico", "A Mexican victory", "Cinco de Mayo remembers a victory in Mexico, not Texas freedom.", "right"),
        text("gather", "Food, music, and memory", "Both celebrations bring people together with food, music, and history.", "both"),
        text("mexico-start", "Started in Mexico", "Juneteenth started in Mexico.", "none", "side", "weak"),
        text("july", "Fourth of July fireworks", "This celebration is a different holiday.", "none", "place", "place"),
        text("indep", "Mexico's Independence Day", "Cinco de Mayo is Mexico's Independence Day.", "none", "myth", "myth"),
      ],
      late: "September 16 is Mexico's Independence Day. May 5 is the Battle of Puebla.",
      mcPrompt: "Which source belongs with Juneteenth?",
      mc: ["June 19, 1865", "The Battle of Puebla", "Fourth of July fireworks", "Mexico's Independence Day"],
      mcAnswer: "June 19, 1865",
      msPrompt: "Which sources belong with Cinco de Mayo? Choose all that apply.",
      ms: ["The Battle of Puebla", "A Mexican victory", "June 19, 1865", "Started in Mexico"],
      msAnswers: ["The Battle of Puebla", "A Mexican victory"],
      tfPrompt: "Our sources say Cinco de Mayo is Mexico's Independence Day.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["Cinco de Mayo is not Independence Day", "Juneteenth", "the Fourth of July"],
      icAnswer: "Cinco de Mayo is not Independence Day",
    })),
    "SS.4.6B-EX": wrap(exhibit({
      id: "SS.4.6B-EX", standard: "SS.4.6B-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.6B", title: "Coast or mountains",
      job: "Compare the Coastal Plains with the Mountains and Basins.",
      detail: "Both regions are in Texas. They do not look or feel the same.",
      mythId: "desert",
      spots: [{ id: "left", label: "Coastal Plains" }, { id: "right", label: "Mountains and Basins" }, { id: "both", label: "Both" }],
      cards: [
        photo("marsh", "Marshes and flat land", "The Coastal Plains", "/maker/marsh.jpg", "left"),
        text("humid", "Humid air", "The Coastal Plains get more rain and feel humid.", "left"),
        photo("peaks", "Mountains and shrubs", "The Mountains and Basins", "/maker/mountains.jpg", "right"),
        text("dry", "Little rain", "The Mountains and Basins are dry.", "right"),
        text("texas", "Part of Texas", "Both regions are in Texas, and people ranch in both.", "both"),
        text("drycoast", "The coast is a desert", "The Coastal Plains get very little rain.", "none", "side", "weak"),
        text("colorado", "The Colorado Rockies", "These mountains are not in Texas.", "none", "place", "place"),
        text("desert", "All of Texas is desert", "All of Texas is desert.", "none", "myth", "myth"),
      ],
      late: "A ranch can sit on the humid coast or in the dry west. The land around the ranch is not the same.",
      mcPrompt: "Which source shows the Coastal Plains?",
      mc: ["Marshes and flat land", "Mountains and shrubs", "The Colorado Rockies", "All of Texas is desert"],
      mcAnswer: "Marshes and flat land",
      msPrompt: "Which sources describe the Mountains and Basins? Choose all that apply.",
      ms: ["Mountains and shrubs", "Little rain", "Humid air", "The coast is a desert"],
      msAnswers: ["Mountains and shrubs", "Little rain"],
      tfPrompt: "Our sources say all of Texas is desert.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["both", "the Colorado Rockies", "the coast is a desert"],
      icAnswer: "both",
    })),
    "SS.5.9A-EX": wrap(exhibit({
      id: "SS.5.9A-EX", standard: "SS.5.9A-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.9A", title: "North or south colonies",
      job: "Compare how the New England and Southern colonies made a living.",
      detail: "New England ships, fishing, and trade. The Southern colonies grew tobacco, rice, and indigo on plantations that used enslaved labor. Both traded with England.",
      mythId: "same",
      spots: [{ id: "left", label: "New England" }, { id: "right", label: "Southern colonies" }, { id: "both", label: "Both" }],
      cards: [
        text("ships", "Shipbuilding", "New England towns built ships.", "left"),
        text("fish", "Fishing and trade", "New England harbors depended on fishing and trade.", "left"),
        text("crops", "Tobacco, rice, and indigo", "Large Southern plantations grew these crops.", "right"),
        text("labor", "Enslaved labor", "Those plantations made their money by forcing enslaved people to do the work.", "right"),
        text("england", "Traded with England", "Both regions sold goods to England and bought goods back.", "both"),
        text("rice", "New England grew rice", "New England's main cash crop was rice.", "none", "side", "weak"),
        text("cattle", "A Texas cattle drive", "This is a later Texas industry, not a colonial one.", "none", "place", "place"),
        text("same", "Every colony was the same", "Every colony earned money the same way.", "none", "myth", "myth"),
      ],
      late: "The ships and the plantations both ended up in English trade. The work behind them was not the same.",
      mcPrompt: "Which source belongs with New England?",
      mc: ["Shipbuilding", "Tobacco, rice, and indigo", "A Texas cattle drive", "Every colony was the same"],
      mcAnswer: "Shipbuilding",
      msPrompt: "Which sources belong with the Southern colonies? Choose all that apply.",
      ms: ["Tobacco, rice, and indigo", "Enslaved labor", "Fishing and trade", "New England grew rice"],
      msAnswers: ["Tobacco, rice, and indigo", "Enslaved labor"],
      tfPrompt: "Our sources say every colony earned money the same way.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["both", "a Texas cattle drive", "New England grew rice"],
      icAnswer: "both",
    })),
    "ELA.3.9A-EX": wrap(exhibit({
      id: "ELA.3.9A-EX", standard: "ELA.3.9A-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.9A", title: "Fable or fairy tale",
      job: "Show how fables and fairy tales are different, and what they share.",
      detail: "A fable often has talking animals and a moral. A fairy tale often has magic, royalty, and 'once upon a time.' Both have a problem and a lesson.",
      mythId: "castle",
      spots: [{ id: "left", label: "Fable" }, { id: "right", label: "Fairy tale" }, { id: "both", label: "Both" }],
      cards: [
        text("animals", "Talking animals", "The fox and the crow speak.", "left"),
        text("moral", "A stated moral", "The last line tells the lesson in one sentence.", "left"),
        text("magic", "A magic spell", "A wish changes the character.", "right"),
        text("once", "Once upon a time", "The story opens with royalty and once upon a time.", "right"),
        text("problem", "A problem and a lesson", "Both kinds of story have a problem and something to learn.", "both"),
        text("castle", "Fables have castles", "Fables always take place in a castle.", "none", "side", "weak"),
        text("news", "A newspaper headline", "This is informational text, not a traditional story.", "none", "topic", "weak"),
        text("legend", "A real hero", "A legend about a hero people say was real is a different kind of story.", "none", "place", "place"),
      ],
      late: "The fox story states the moral. The castle story leaves the lesson inside the ending. Both still teach one.",
      mcPrompt: "Which source is a fable clue?",
      mc: ["Talking animals", "A magic spell", "A newspaper headline", "Fables have castles"],
      mcAnswer: "Talking animals",
      msPrompt: "Which sources point to a fairy tale? Choose all that apply.",
      ms: ["A magic spell", "Once upon a time", "A stated moral", "A newspaper headline"],
      msAnswers: ["A magic spell", "Once upon a time"],
      tfPrompt: "Our sources say fables always take place in a castle.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["both", "a newspaper", "a legend"],
      icAnswer: "both",
    })),
    "ELA.4.7B-EX": wrap(exhibit({
      id: "ELA.4.7B-EX", standard: "ELA.4.7B-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.7B", title: "Two views of the storm",
      job: "Compare a diary and an encyclopedia article about the same hurricane.",
      detail: "The diary tells what one person felt. The encyclopedia gives dates and wind speeds. They are about the same storm in the same town.",
      mythId: "agree",
      spots: [{ id: "left", label: "Diary" }, { id: "right", label: "Encyclopedia" }, { id: "both", label: "Both" }],
      cards: [
        text("felt", "I could not sleep", "The diary says the wind sounded like a train and the writer could not sleep.", "left"),
        text("window", "The window cracked", "The diary describes one cracked window in the writer's room.", "left"),
        text("date", "September 13", "The article gives the date the hurricane came ashore.", "right"),
        text("wind", "Wind speed", "The article lists the top wind speed.", "right"),
        text("town", "Same storm, same town", "Both sources are about this hurricane in this town.", "both"),
        text("speed", "The diary's wind speed", "The diary gives the official wind speed.", "none", "side", "weak"),
        text("other", "A different storm", "This map is from a hurricane ten years later.", "none", "place", "place"),
        text("agree", "Sources always match", "Two sources on one event always say the same thing.", "none", "myth", "myth"),
      ],
      late: "The article never says the writer could not sleep. The diary never lists the official wind speed.",
      mcPrompt: "Which source is from the diary?",
      mc: ["I could not sleep", "September 13", "A different storm", "Sources always match"],
      mcAnswer: "I could not sleep",
      msPrompt: "Which sources belong in the encyclopedia? Choose all that apply.",
      ms: ["September 13", "Wind speed", "The window cracked", "The diary's wind speed"],
      msAnswers: ["September 13", "Wind speed"],
      tfPrompt: "Our sources say two sources on one event always say the same thing.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the diary and the article do different jobs", "a different storm", "sources always match"],
      icAnswer: "the diary and the article do different jobs",
    })),
    "ELA.5.13D-EX": wrap(exhibit({
      id: "ELA.5.13D-EX", standard: "ELA.5.13D-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.13D", title: "There or later",
      job: "Sort primary and secondary sources about the 1900 Galveston storm.",
      detail: "A primary source comes from the time. A secondary source is written later about that time. Primary is not always more accurate.",
      mythId: "always",
      spots: [{ id: "left", label: "Primary" }, { id: "right", label: "Secondary" }, { id: "both", label: "Both" }],
      cards: [
        text("letter", "A survivor's letter", "A letter written in 1900 describes the water in the house.", "left"),
        text("photo", "A photograph from 1900", "The picture was taken in Galveston that year.", "left"),
        text("book", "A textbook page", "A chapter written long after the storm explains what happened.", "right"),
        text("sign", "A museum sign", "The sign was written later for visitors.", "right"),
        text("agree", "Facts that agree", "A letter and a later book can report the same fact.", "both"),
        text("there", "The textbook author was there", "The textbook was written by someone who lived through the storm.", "none", "side", "weak"),
        text("movie", "A movie poster", "The poster is an ad, not a source from 1900 or a study of it.", "none", "topic", "weak"),
        text("always", "Primary is always right", "A primary source is always more accurate than a secondary one.", "none", "myth", "myth"),
      ],
      late: "The letter and the textbook both say the water rose fast. The letter is from 1900. The textbook is not.",
      mcPrompt: "Which source is primary?",
      mc: ["A survivor's letter", "A textbook page", "A movie poster", "Primary is always right"],
      mcAnswer: "A survivor's letter",
      msPrompt: "Which sources were made later? Choose all that apply.",
      ms: ["A textbook page", "A museum sign", "A photograph from 1900", "The textbook author was there"],
      msAnswers: ["A textbook page", "A museum sign"],
      tfPrompt: "Our sources say a primary source is always more accurate.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["both can report the same fact", "a movie poster", "primary is always right"],
      icAnswer: "both can report the same fact",
    })),
    "3.7D-EX": wrap(exhibit({
      id: "3.7D-EX", standard: "3.7D-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.7D", title: "Pour it or weigh it",
      job: "Decide when to measure capacity and when to measure weight.",
      detail: "Capacity is how much a container holds. Weight is how heavy something is. A bag of rice can be measured both ways.",
      mythId: "bigger",
      spots: [{ id: "left", label: "Capacity" }, { id: "right", label: "Weight" }, { id: "both", label: "Both" }],
      cards: [
        text("pitcher", "A juice pitcher", "You measure how much juice the pitcher holds.", "left"),
        text("tank", "A fish tank", "You measure how much water the tank holds.", "left"),
        text("pumpkin", "A pumpkin", "You measure how heavy the pumpkin is.", "right"),
        text("pack", "A backpack", "You measure how heavy the full backpack is.", "right"),
        text("rice", "A bag of rice", "You can measure how much the bag holds and how heavy it is.", "both"),
        text("ruler", "A pencil and a ruler", "Length is a different measurement.", "none", "topic", "weak"),
        text("pool", "A bathroom scale", "Weigh the water in a swimming pool with a bathroom scale.", "none", "side", "weak"),
        text("bigger", "Bigger weighs more", "Bigger things always weigh more.", "none", "myth", "myth"),
      ],
      late: "A big empty box can be lighter than a small bag of rice. Size is not weight.",
      mcPrompt: "Which source asks for capacity?",
      mc: ["A juice pitcher", "A pumpkin", "A pencil and a ruler", "Bigger weighs more"],
      mcAnswer: "A juice pitcher",
      msPrompt: "Which sources ask for weight? Choose all that apply.",
      ms: ["A pumpkin", "A backpack", "A fish tank", "A pencil and a ruler"],
      msAnswers: ["A pumpkin", "A backpack"],
      tfPrompt: "Our sources say bigger things always weigh more.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["bigger is not the same as heavier", "a juice pitcher", "a ruler"],
      icAnswer: "bigger is not the same as heavier",
    })),
    "4.10A-EX": wrap(exhibit({
      id: "4.10A-EX", standard: "4.10A-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.10A", title: "Same every month?",
      job: "Sort fixed expenses and variable expenses.",
      detail: "A fixed expense stays the same each month. A variable expense changes. A paycheck is income, not an expense.",
      mythId: "same",
      spots: [{ id: "left", label: "Fixed" }, { id: "right", label: "Variable" }, { id: "both", label: "Both are expenses" }],
      cards: [
        text("rent", "Rent", "The rent is the same amount every month.", "left"),
        text("car", "A car payment", "The car payment does not change this year.", "left"),
        text("food", "Groceries", "The grocery bill is different every week.", "right"),
        text("power", "The electric bill", "The electric bill goes up in summer and down in winter.", "right"),
        text("plan", "A family plans for them", "Fixed and variable costs are both expenses a family plans for.", "both"),
        text("pay", "A paycheck", "A paycheck is money coming in, not an expense.", "none", "topic", "weak"),
        text("phone", "A phone bill with extras", "The plan is fixed, but the extras change the total.", "none", "point", "weak"),
        text("same", "The electric bill never changes", "The electric bill is the same every month.", "none", "myth", "myth"),
      ],
      late: "Rent stayed $900 all year. The electric bill was $80 in April and $140 in August.",
      mcPrompt: "Which source is a fixed expense?",
      mc: ["Rent", "Groceries", "A paycheck", "The electric bill never changes"],
      mcAnswer: "Rent",
      msPrompt: "Which sources are variable expenses? Choose all that apply.",
      ms: ["Groceries", "The electric bill", "A car payment", "A paycheck"],
      msAnswers: ["Groceries", "The electric bill"],
      tfPrompt: "Our sources say the electric bill is the same every month.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a variable expense", "a paycheck", "the electric bill never changes"],
      icAnswer: "a variable expense",
    })),
    "5.4D-EX": wrap(exhibit({
      id: "5.4D-EX", standard: "5.4D-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.4D", title: "Plus or times",
      job: "Tell an adding pattern from a multiplying pattern.",
      detail: "y = x + 4 means each y is 4 more than x. y = 4x means each y is 4 times x. Only y = 4x passes through (0, 0). Both follow a rule and make a straight line.",
      mythId: "add",
      spots: [{ id: "left", label: "Adding" }, { id: "right", label: "Multiplying" }, { id: "both", label: "Both" }],
      cards: [
        text("plus", "y = x + 4", "When x is 1, y is 5. When x is 2, y is 6. Each y is 4 more than x.", "left"),
        text("notzero", "It misses (0, 0)", "When x is 0, y = 0 + 4, so the line does not pass through the origin.", "left"),
        text("times", "y = 4x", "When x is 1, y is 4. When x is 2, y is 8. Each y is 4 times x.", "right"),
        text("zero", "It hits (0, 0)", "When x is 0, y = 4 times 0, so the line passes through the origin.", "right"),
        text("rule", "A rule and a straight line", "Both patterns follow a rule, and both graphs are straight lines.", "both"),
        text("double", "2, 4, 8, 16 adds 4", "The table 2, 4, 8, 16 adds 4 each time.", "none", "side", "weak"),
        text("none", "No rule", "The y values are 3, 9, 4, 1. There is no rule.", "none", "topic", "weak"),
        text("add", "Same jump means adding", "If y goes up by the same amount each step, the rule must be adding.", "none", "myth", "myth"),
      ],
      late: "y = 4x goes 0, 4, 8, 12. It rises by 4 each time, and it is still multiplying.",
      mcPrompt: "Which source is the adding pattern?",
      mc: ["y = x + 4", "y = 4x", "No rule", "Same jump means adding"],
      mcAnswer: "y = x + 4",
      msPrompt: "Which sources belong with multiplying? Choose all that apply.",
      ms: ["y = 4x", "It hits (0, 0)", "It misses (0, 0)", "2, 4, 8, 16 adds 4"],
      msAnswers: ["y = 4x", "It hits (0, 0)"],
      tfPrompt: "Our sources say a pattern that rises by the same amount must be adding.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["multiplying can rise by the same amount", "no rule", "the adding line"],
      icAnswer: "multiplying can rise by the same amount",
    })),
  };
}
