function text(id, title, body, job, reason = "point", role = "strong") {
  return { id, title, tag: role === "myth" ? "A common mistake" : role === "place" ? "Wrong place" : "A note", image: "", role, reason, job, kind: "text", text: body };
}
function photo(id, title, tag, image, job, reason = "point", role = "strong") {
  return { id, title, tag, image, role, reason, job };
}
function drawn(id, title, tag, model, job, reason = "point", role = "strong") {
  return { id, title, tag, image: "", role, reason, job, kind: "model", model };
}
function exhibit(fields) {
  return { stamps: ["Picture", "Note", "Test"], lateTitle: "Late field note", layout: "line", ...fields };
}
function spots(count) {
  return Array.from({ length: count }, (_, index) => ({
    id: String(index + 1),
    label: index === 0 ? "1 · First" : index === count - 1 ? `${count} · Last` : String(index + 1),
  }));
}

export function lineCases(reasons) {
  const all = [...reasons, { id: "order", label: "Out of order" }];
  const wrap = (item) => ({ ...item, reasons: all });
  return {
    "3.13B-EX": wrap(exhibit({
      id: "3.13B-EX", standard: "3.13B-EX", grade: 3, subject: "Science",
      kicker: "Exhibit Hall · 3.13B", title: "A beetle's year",
      job: "Put a beetle's changes in the order they happen.",
      detail: "A beetle does not look the same its whole life. A cricket does not make a pupa. A butterfly chrysalis is not a beetle.",
      mythId: "first",
      spots: spots(5),
      cards: [
        photo("egg", "Eggs on a leaf", "The start", "/maker/beetle-egg.jpg", "1"),
        photo("larva", "A soft larva", "It eats and grows", "/maker/beetle-larva.jpg", "2"),
        photo("pupa", "A pupa", "It changes inside", "/maker/beetle-pupa.jpg", "3"),
        photo("adult", "The adult beetle", "Hard wing covers", "/maker/beetle-adult.jpg", "4"),
        text("eggs", "New eggs", "The adult can lay eggs, and the cycle can start again.", "5"),
        text("nymph", "A cricket nymph", "A young cricket looks like a small adult. Crickets skip the pupa.", "none", "place", "place"),
        text("wings", "A butterfly case", "This chrysalis belongs to a butterfly, not a beetle.", "none", "picture", "weak"),
        text("first", "The adult comes first", "The adult beetle hatches first, before any egg.", "none", "order", "myth"),
      ],
      late: "The cricket nymph never makes a pupa. The beetle does.",
      mcPrompt: "Which source is the beetle's pupa?",
      mc: ["A pupa", "A cricket nymph", "A butterfly case", "The adult comes first"],
      mcAnswer: "A pupa",
      msPrompt: "Which sources are part of the beetle's life, in the middle or at the end? Choose all that apply.",
      ms: ["A soft larva", "The adult beetle", "A cricket nymph", "A butterfly case"],
      msAnswers: ["A soft larva", "The adult beetle"],
      tfPrompt: "Our sources say the adult beetle hatches before any egg.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["a cricket is not this beetle", "the eggs", "the adult comes first"],
      icAnswer: "a cricket is not this beetle",
    })),
    "4.9B-EX": wrap(exhibit({
      id: "4.9B-EX", standard: "4.9B-EX", grade: 4, subject: "Science",
      kicker: "Exhibit Hall · 4.9B", title: "29 nights",
      job: "Put six Moon shapes in the order they appear.",
      detail: "The lit part grows from dark to full, then shrinks. Earth's shadow does not make the phases. An eclipse is not a phase.",
      mythId: "shadow",
      spots: spots(6),
      cards: [
        drawn("newm", "Dark side", "Almost no light", { type: "moon", phase: "new" }, "1"),
        drawn("cres", "A thin sliver", "The lit part is small and growing", { type: "moon", phase: "crescent" }, "2"),
        drawn("quart", "Half lit, growing", "Half of the side we see is lit", { type: "moon", phase: "quarter" }, "3"),
        drawn("gib", "Mostly lit", "More than half is lit, and it is still growing", { type: "moon", phase: "gibbous" }, "4"),
        drawn("fullm", "Fully lit", "The whole side we see is lit", { type: "moon", phase: "full" }, "5"),
        drawn("third", "Half lit, shrinking", "Half is lit again, and the lit part is shrinking", { type: "moon", phase: "third" }, "6"),
        text("shadow", "Earth's shadow", "Earth's shadow makes the Moon's phases.", "none", "myth", "myth"),
        text("eclipse", "A lunar eclipse", "The Moon is dark for a short time during an eclipse. That is not a phase.", "none", "picture", "weak"),
        text("jump", "Full moon next", "The full moon comes right after the dark new moon.", "none", "order", "weak"),
      ],
      late: "After the full moon, the lit part shrinks. It does not jump back to dark.",
      mcPrompt: "Which source is the full moon?",
      mc: ["Fully lit", "Dark side", "Earth's shadow", "A lunar eclipse"],
      mcAnswer: "Fully lit",
      msPrompt: "Which sources show the lit part growing, before the moon is full? Choose all that apply.",
      ms: ["A thin sliver", "Mostly lit", "Half lit, shrinking", "Full moon next"],
      msAnswers: ["A thin sliver", "Mostly lit"],
      tfPrompt: "Our sources say Earth's shadow makes the Moon's phases.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the lit part shrinks after full", "Earth's shadow", "a lunar eclipse"],
      icAnswer: "the lit part shrinks after full",
    })),
    "5.10B-EX": wrap(exhibit({
      id: "5.10B-EX", standard: "5.10B-EX", grade: 5, subject: "Science",
      kicker: "Exhibit Hall · 5.10B", title: "From mud to stone",
      job: "Order how sediment becomes rock, then add coal's own path.",
      detail: "Rock breaks, moves, settles, gets buried, and can be cemented. Coal comes from buried swamp plants, not from dinosaurs, and not from every rock.",
      mythId: "dino",
      spots: spots(6),
      cards: [
        text("break", "Rock breaks apart", "Weathering breaks rock into smaller pieces.", "1"),
        text("move", "Pieces are carried", "Water or wind moves the pieces. That is erosion.", "2"),
        text("settle", "Layers settle", "The pieces stop and stack in layers.", "3"),
        text("press", "Buried and pressed", "Later layers bury the stack and press it.", "4"),
        text("glue", "Minerals cement it", "Minerals glue the pressed pieces into sedimentary rock.", "5"),
        text("coal", "Coal's own path", "In some swamps, buried plants became coal. Most sedimentary rock did not.", "6"),
        text("dino", "Oil from dinosaurs", "Oil comes from dinosaurs.", "none", "myth", "myth"),
        text("first", "Rock, then burial", "The solid rock forms first, and only then gets buried.", "none", "order", "weak"),
        text("volcano", "A lava flow", "Lava cools into igneous rock. That is a different kind of rock.", "none", "place", "place"),
      ],
      late: "Most oil came from tiny sea life, not from dinosaurs. Coal came from plants.",
      mcPrompt: "Which source is cementing the sedimentary rock?",
      mc: ["Minerals cement it", "A lava flow", "Oil from dinosaurs", "Rock, then burial"],
      mcAnswer: "Minerals cement it",
      msPrompt: "Which sources happen before the layers are cemented? Choose all that apply.",
      ms: ["Rock breaks apart", "Layers settle", "A lava flow", "Oil from dinosaurs"],
      msAnswers: ["Rock breaks apart", "Layers settle"],
      tfPrompt: "Our sources say oil comes from dinosaurs.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["oil and coal are not dinosaur bones", "a lava flow", "rock, then burial"],
      icAnswer: "oil and coal are not dinosaur bones",
    })),
    "SS.3.1A-EX": wrap(exhibit({
      id: "SS.3.1A-EX", standard: "SS.3.1A-EX", grade: 3, subject: "Social Studies",
      kicker: "Exhibit Hall · 3.1A", title: "How our town grew",
      job: "Put the changes in Mesquite Springs in order. This is a model town.",
      detail: "People settled by a river. Later a railroad, a school, a highway, and a library changed the town. The highway did not come first.",
      mythId: "road",
      spots: spots(5),
      cards: [
        text("river", "By the river", "The first families settle where they can get water.", "1"),
        text("rail", "The railroad", "Tracks reach the town, and more goods come and go.", "2"),
        text("school", "A schoolhouse", "The growing town builds a school.", "3"),
        text("highway", "The highway", "A highway later connects the town to other cities.", "4"),
        text("library", "A new library", "The newest building in this story is the library.", "5"),
        text("road", "Highway first", "The highway was built before the railroad.", "none", "order", "myth"),
        text("color", "The town's favorite color", "A favorite color does not show how the town changed.", "none", "topic", "weak"),
        text("city", "A New York skyscraper", "This building is not in Mesquite Springs.", "none", "place", "place"),
      ],
      late: "The railroad is already busy in an old photo. The highway is not in that photo.",
      mcPrompt: "Which source comes first?",
      mc: ["By the river", "The highway", "Highway first", "A New York skyscraper"],
      mcAnswer: "By the river",
      msPrompt: "Which sources come after the railroad? Choose all that apply.",
      ms: ["A schoolhouse", "A new library", "By the river", "Highway first"],
      msAnswers: ["A schoolhouse", "A new library"],
      tfPrompt: "Our sources say the highway was built before the railroad.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the railroad comes before the highway", "a favorite color", "a skyscraper"],
      icAnswer: "the railroad comes before the highway",
    })),
    "SS.4.4B-EX": wrap(exhibit({
      id: "SS.4.4B-EX", standard: "SS.4.4B-EX", grade: 4, subject: "Social Studies",
      kicker: "Exhibit Hall · 4.4B", title: "Longhorn boom",
      job: "Order how the Texas cattle industry grew, and why the long drives ended.",
      detail: "After the Civil War, wild longhorns were driven north to railroads and cities that wanted beef. Barbed wire and railroads in Texas later ended those long drives. Cowboys included Mexican vaqueros and Black cowboys.",
      mythId: "only",
      spots: spots(5),
      cards: [
        photo("horns", "Wild longhorns", "After the Civil War", "/maker/longhorn.jpg", "1"),
        text("beef", "Cities want beef", "Northern cities will pay for beef.", "2"),
        text("trail", "The Chisholm Trail", "Herds are driven north. The cowboys include Mexican vaqueros and Black cowboys.", "3"),
        text("kansas", "A Kansas railroad", "The drives meet railroads that can haul cattle farther.", "4"),
        text("wire", "Barbed wire", "Fences and new Texas railroads later end the long open drives.", "5"),
        text("start", "Fences at the start", "Barbed wire ended the drives before they began.", "none", "order", "weak"),
        text("oil", "An oil derrick", "Oil is a later Texas industry, not this cattle story.", "none", "place", "place"),
        text("only", "Only in Texas", "Cowboys only worked in Texas.", "none", "myth", "myth"),
      ],
      late: "The Kansas railroad was the goal of many drives. Barbed wire came later and closed the open range.",
      mcPrompt: "Which source starts this story?",
      mc: ["Wild longhorns", "Barbed wire", "An oil derrick", "Only in Texas"],
      mcAnswer: "Wild longhorns",
      msPrompt: "Which sources belong before the drives end? Choose all that apply.",
      ms: ["Cities want beef", "The Chisholm Trail", "Fences at the start", "An oil derrick"],
      msAnswers: ["Cities want beef", "The Chisholm Trail"],
      tfPrompt: "Our sources say cowboys only worked in Texas.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["barbed wire comes after the drives", "an oil derrick", "only in Texas"],
      icAnswer: "barbed wire comes after the drives",
    })),
    "SS.5.4C-EX": wrap(exhibit({
      id: "SS.5.4C-EX", standard: "SS.5.4C-EX", grade: 5, subject: "Social Studies",
      kicker: "Exhibit Hall · 5.4C", title: "Growing west",
      job: "Order how the United States claimed land farther west.",
      detail: "France sold a claim to the United States in 1803. Native nations already lived on that land. The Corps of Discovery crossed it from 1804 to 1806. The phrase Manifest Destiny came later, in 1845.",
      mythId: "first",
      spots: spots(6),
      cards: [
        text("buy", "1803 · The Purchase", "The United States buys France's claim. Native nations already live on the land.", "1"),
        text("set", "1804 · They set out", "The Corps of Discovery leaves, crossing lands where people already live.", "2"),
        text("saca", "Sacagawea joins", "Sacagawea, a Shoshone woman, joins the Corps and interprets.", "3"),
        text("ocean", "1805 · The Pacific", "The Corps reaches the Pacific Ocean.", "4"),
        text("back", "1806 · The return", "The Corps returns east.", "5"),
        text("idea", "1845 · A name", "The phrase Manifest Destiny is used for the idea that the United States should keep expanding.", "6"),
        text("first", "First to see it", "Lewis and Clark were the first people to see the West.", "none", "myth", "myth"),
        text("early", "The name came first", "Manifest Destiny was the name used before the Louisiana Purchase.", "none", "order", "weak"),
        text("gold", "Gold in 1849", "The California Gold Rush is a later event. It did not start this story.", "none", "place", "place"),
      ],
      late: "Sacagawea joined before the Corps reached the Pacific. The phrase Manifest Destiny was still decades away.",
      mcPrompt: "Which source is the Louisiana Purchase?",
      mc: ["1803 · The Purchase", "1845 · A name", "Gold in 1849", "First to see it"],
      mcAnswer: "1803 · The Purchase",
      msPrompt: "Which sources happen during the Corps of Discovery? Choose all that apply.",
      ms: ["Sacagawea joins", "1805 · The Pacific", "1845 · A name", "Gold in 1849"],
      msAnswers: ["Sacagawea joins", "1805 · The Pacific"],
      tfPrompt: "Our sources say Lewis and Clark were the first people to see the West.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["Sacagawea joins before 1845", "the Gold Rush", "first to see it"],
      icAnswer: "Sacagawea joins before 1845",
    })),
    "ELA.3.8C-EX": wrap(exhibit({
      id: "ELA.3.8C-EX", standard: "ELA.3.8C-EX", grade: 3, subject: "ELAR",
      kicker: "Exhibit Hall · 3.8C", title: "The lemonade plan",
      job: "Put the story events in order, from the problem to how it is solved.",
      detail: "Ana wants a stand. She has no lemons. She solves that problem, sells lemonade, and then shares the money. Curly hair is not an event.",
      mythId: "end",
      spots: spots(5),
      cards: [
        text("idea", "The idea", "Ana says she wants a lemonade stand.", "1"),
        text("nolemon", "No lemons", "She opens the kitchen and finds no lemons.", "2"),
        text("tree", "The neighbor's tree", "A neighbor lets her pick lemons.", "3"),
        text("sale", "The big sale", "The stand sells every cup.", "4"),
        text("share", "Sharing the money", "Ana splits the money with the neighbor.", "5"),
        text("end", "The ending first", "Ana shares the money before she has the idea.", "none", "order", "myth"),
        text("hair", "Curly hair", "Ana has curly hair. That is a description, not an event.", "none", "topic", "weak"),
        text("other", "A different story", "In that story, a boy loses his dog. It is not this plot.", "none", "place", "place"),
      ],
      late: "The neighbor's lemons solve the problem. Sharing the money comes after the sale.",
      mcPrompt: "Which source is the problem?",
      mc: ["No lemons", "Sharing the money", "Curly hair", "The ending first"],
      mcAnswer: "No lemons",
      msPrompt: "Which sources happen after Ana gets lemons? Choose all that apply.",
      ms: ["The big sale", "Sharing the money", "The idea", "A different story"],
      msAnswers: ["The big sale", "Sharing the money"],
      tfPrompt: "Our sources say Ana shares the money before she has the idea.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the sale comes before sharing", "curly hair", "another story"],
      icAnswer: "the sale comes before sharing",
    })),
    "ELA.4.8C-EX": wrap(exhibit({
      id: "ELA.4.8C-EX", standard: "ELA.4.8C-EX", grade: 4, subject: "ELAR",
      kicker: "Exhibit Hall · 4.8C", title: "The science fair disaster",
      job: "Order the plot from the setup to the resolution.",
      detail: "The problem builds, the volcano erupts at the worst moment, and then the story settles. The gym being loud is the setting, not a plot event.",
      mythId: "peak",
      spots: spots(6),
      cards: [
        text("setup", "The setup", "Leo signs up with a baking-soda volcano.", "1"),
        text("fail", "It will not erupt", "At home, the volcano only fizzes.", "2"),
        text("judges", "The judges arrive", "The judges stop at Leo's table. The problem is getting worse.", "3"),
        text("boom", "It erupts", "The volcano erupts on a judge. This is the climax.", "4"),
        text("clean", "The cleanup", "Leo wipes the table. The excitement falls.", "5"),
        text("ribbon", "A ribbon", "The judge gives him a ribbon for explaining what went wrong.", "6"),
        text("peak", "Climax first", "The volcano erupts on the judge before Leo even signs up.", "none", "order", "myth"),
        text("gym", "A loud gym", "The gym is loud. That is the setting, not an event.", "none", "topic", "weak"),
        text("poem", "A line of poetry", "\"The stars blinked.\" That line is from a poem, not this plot.", "none", "place", "place"),
      ],
      late: "The ribbon comes after the cleanup. The eruption is the biggest moment, not the ending.",
      mcPrompt: "Which source is the climax?",
      mc: ["It erupts", "The setup", "Climax first", "A loud gym"],
      mcAnswer: "It erupts",
      msPrompt: "Which sources are falling action or the resolution? Choose all that apply.",
      ms: ["The cleanup", "A ribbon", "It will not erupt", "A line of poetry"],
      msAnswers: ["The cleanup", "A ribbon"],
      tfPrompt: "Our sources say the eruption happens before Leo signs up.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the ribbon is not the climax", "the setting", "a poem"],
      icAnswer: "the ribbon is not the climax",
    })),
    "ELA.5.8C-EX": wrap(exhibit({
      id: "ELA.5.8C-EX", standard: "ELA.5.8C-EX", grade: 5, subject: "ELAR",
      kicker: "Exhibit Hall · 5.8C", title: "Lost in the library",
      job: "Order the scenes of the play, up to the climax and after it.",
      detail: "A stage direction is not a plot event. The ending does not come first.",
      mythId: "done",
      spots: spots(6),
      cards: [
        text("open", "Scene 1", "Two friends enter with a map of the old library.", "1"),
        text("map", "The lost map", "The map slips through a grate.", "2"),
        text("door", "The locked door", "The main door locks behind them.", "3"),
        text("secret", "The librarian's secret", "The librarian admits she moved the exit signs. This is the climax.", "4"),
        text("out", "The way out", "They follow the unmoved sign to a side door.", "5"),
        text("end", "The last scene", "They return the map and the lights come up.", "6"),
        text("done", "Ending first", "The last scene opens the play.", "none", "order", "myth"),
        text("lights", "Lights dim", "The script says \"Lights dim.\" That is a stage direction, not a plot event.", "none", "topic", "weak"),
        text("other", "Another play", "In the other play, a crew is lost at sea.", "none", "place", "place"),
      ],
      late: "The locked door comes before the librarian's secret. The last scene comes after the way out.",
      mcPrompt: "Which source is the climax?",
      mc: ["The librarian's secret", "Scene 1", "Ending first", "Lights dim"],
      mcAnswer: "The librarian's secret",
      msPrompt: "Which sources come after the climax? Choose all that apply.",
      ms: ["The way out", "The last scene", "The lost map", "Another play"],
      msAnswers: ["The way out", "The last scene"],
      tfPrompt: "Our sources say the last scene opens the play.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the ending is not first", "a stage direction", "another play"],
      icAnswer: "the ending is not first",
    })),
    "3.9E-EX": wrap(exhibit({
      id: "3.9E-EX", standard: "3.9E-EX", grade: 3, subject: "Math",
      kicker: "Exhibit Hall · 3.9E", title: "Maya's bike fund",
      job: "Put Maya's savings in order until she can buy the bike.",
      detail: "The goal is $30. She adds money until the total is $30, and then she buys the bike. A candy receipt is spending, not saving.",
      mythId: "never",
      spots: spots(6),
      cards: [
        text("goal", "The $30 goal", "Maya writes the goal. She has $0.", "1"),
        text("w1", "Total $5", "After week 1 she has saved $5.", "2"),
        text("w2", "Total $10", "After week 2 she has $10.", "3"),
        text("bday", "Total $20", "A birthday gift of $10 brings the total to $20.", "4"),
        text("w4", "Total $30", "She saves $10 more. She has $30.", "5"),
        text("bike", "The bike", "She spends the $30 on the bike.", "6"),
        text("early", "The bike at $10", "She buys the bike when she has only $10.", "none", "order", "weak"),
        text("candy", "A candy receipt", "She spent $3 on candy. That is not a step in the savings plan.", "none", "topic", "weak"),
        text("never", "Never spend", "Saving means you can never spend the money.", "none", "myth", "myth"),
      ],
      late: "At $20 she still needed $10. The bike came after the total reached $30.",
      mcPrompt: "Which source is the goal?",
      mc: ["The $30 goal", "The bike", "A candy receipt", "Never spend"],
      mcAnswer: "The $30 goal",
      msPrompt: "Which sources show the total going up? Choose all that apply.",
      ms: ["Total $5", "Total $20", "A candy receipt", "The bike at $10"],
      msAnswers: ["Total $5", "Total $20"],
      tfPrompt: "Our sources say saving means you can never spend the money.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the bike comes after $30", "the candy", "never spend"],
      icAnswer: "the bike comes after $30",
    })),
    "4.5B-EX": wrap(exhibit({
      id: "4.5B-EX", standard: "4.5B-EX", grade: 4, subject: "Math",
      kicker: "Exhibit Hall · 4.5B", title: "The growing tower",
      job: "Order the tile towers, then place the rule that fits.",
      detail: "Each tower uses 3 more tiles than the one before it. The rule is tiles = step × 3. A tower of 13 does not fit.",
      mythId: "plus",
      spots: spots(6),
      cards: [
        drawn("a", "3 tiles", "The smallest tower", { type: "array", rows: 1, cols: 3 }, "1"),
        drawn("b", "6 tiles", "Two rows of 3", { type: "array", rows: 2, cols: 3 }, "2"),
        drawn("c", "9 tiles", "Three rows of 3", { type: "array", rows: 3, cols: 3 }, "3"),
        drawn("d", "12 tiles", "Four rows of 3", { type: "array", rows: 4, cols: 3 }, "4"),
        drawn("e", "15 tiles", "Five rows of 3", { type: "array", rows: 5, cols: 3 }, "5"),
        text("rule", "Tiles = step × 3", "Step 1 makes 3. Step 2 makes 6. Step 5 makes 15.", "6"),
        text("bad", "13 tiles", "This tower has 13 tiles. It does not follow the rule.", "none", "point", "weak"),
        text("skip", "15 before 9", "The 15-tile tower comes before the 9-tile tower.", "none", "order", "weak"),
        text("plus", "Add 2", "The rule is add 2 tiles each step.", "none", "myth", "myth"),
      ],
      late: "From 9 tiles to 12 tiles is a jump of 3, not 2. The 15-tile tower is the largest.",
      mcPrompt: "Which source is the rule?",
      mc: ["Tiles = step × 3", "13 tiles", "Add 2", "15 before 9"],
      mcAnswer: "Tiles = step × 3",
      msPrompt: "Which towers fit the rule? Choose all that apply.",
      ms: ["6 tiles", "12 tiles", "13 tiles", "Add 2"],
      msAnswers: ["6 tiles", "12 tiles"],
      tfPrompt: "Our sources say the rule is add 2 tiles each step.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["the jump is 3, and 15 is last", "13 tiles", "add 2"],
      icAnswer: "the jump is 3, and 15 is last",
    })),
    "5.10E-EX": wrap(exhibit({
      id: "5.10E-EX", standard: "5.10E-EX", grade: 5, subject: "Math",
      kicker: "Exhibit Hall · 5.10E", title: "The family budget",
      job: "Order how the Rivera family closed a $60 gap.",
      detail: "Income is $400. Expenses start at $460. They cut some costs and add some income. Earning more is not the only fix. Buying a bigger TV does not help.",
      mythId: "only",
      spots: spots(6),
      cards: [
        text("gap", "Short $60", "Income $400. Expenses $460. They are short $60.", "1"),
        text("stream", "Short $45", "They cut a $15 streaming plan. The gap is $45.", "2"),
        text("cook", "Short $25", "Cooking at home saves $20 more. The gap is $25.", "3"),
        text("bike", "Short $10", "They sell an old bike for $15. The gap is $10.", "4"),
        text("shift", "Short $0", "One extra shift adds $10. Income now covers expenses.", "5"),
        text("ok", "A balanced month", "The next month starts at $410 income and $410 expenses.", "6"),
        text("early", "Balanced on day one", "The family was already balanced before they changed anything.", "none", "order", "weak"),
        text("tv", "A bigger TV", "They buy a bigger TV. That adds an expense.", "none", "topic", "weak"),
        text("only", "Only earn more", "The only way to fix a budget is to earn more money.", "none", "myth", "myth"),
      ],
      late: "Cutting the streaming plan and cooking at home were spending changes. The extra shift was not the only fix.",
      mcPrompt: "Which source is the starting problem?",
      mc: ["Short $60", "A balanced month", "A bigger TV", "Only earn more"],
      mcAnswer: "Short $60",
      msPrompt: "Which sources cut spending? Choose all that apply.",
      ms: ["Short $45", "Short $25", "A bigger TV", "Only earn more"],
      msAnswers: ["Short $45", "Short $25"],
      tfPrompt: "Our sources say the only fix is to earn more money.",
      tfIsFalse: true,
      icLead: "The late note helps most with",
      ic: ["spending cuts were part of the fix", "a bigger TV", "only earn more"],
      icAnswer: "spending cuts were part of the fix",
    })),
  };
}
