// Expedition Station — The Canyon Makers (SCI.4.10B-XP)
// Grade 4 · Science · Cindara (lava world). Main standard 4.10B (model and
// describe slow changes to Earth's surface caused by weathering, erosion, and
// deposition from water, wind, and ice); also practices 4.1B (plan and conduct
// a simple experimental investigation), 4.1E (collect observations and
// measurements as evidence), 4.1G (develop and use models), 4.2B (analyze data
// for patterns), 4.3A (explanations supported by data and models), 4.3C
// (respectful scientific discussion), 4.5A (patterns), 4.5B (cause and
// effect), 4.5G (stability and change).
//
// Earth-true rule: Cindara and the time-lapse camera are invented, but every
// process, fact, and data table is real Earth science.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Break it, move it, drop it", machine: "Rock Lab", icon: "cells", speaker: "nova",
    line: "The time-lapse camera caught six changes near the outpost. Let's sort them before we fast-forward the river.",
    question: "Sort each change: is it weathering, erosion, or deposition?",
    hint: "Weathering breaks rock into pieces. Erosion carries the pieces away. Deposition drops them in a new place.",
    meter: { heat: 10, label: "Canyon mapped +10%", story: "The camera clips are sorted" },
    discovery: { id: "arches", name: "Stone arches", who: "Nova", fact: "Arches National Park in Utah has more than 2,000 natural stone arches. Weathering and erosion slowly shaped them over a very long time." },
    answer: { kind: "sort", bins: { e1: "weather", e2: "erode", e3: "deposit", e4: "weather", e5: "erode", e6: "deposit" } },
    rightFeedback: "Cracking rock is weathering, carrying pieces away is erosion, and dropping them is deposition.",
    sort: {
      bins: [{ id: "weather", label: "Weathering" }, { id: "erode", label: "Erosion" }, { id: "deposit", label: "Deposition" }],
      items: [
        { id: "e1", label: "Ice cracks a boulder into two pieces" },
        { id: "e2", label: "A fast river carries pebbles downstream" },
        { id: "e3", label: "Sand piles up where a river slows down" },
        { id: "e4", label: "Plant roots split a rock as they grow" },
        { id: "e5", label: "Wind blows loose sand across the desert" },
        { id: "e6", label: "A melting glacier leaves a pile of rocks behind" },
      ],
    },
    wrong: [
      { item: "e1", hint: "The boulder stays in the same place. It just breaks into smaller pieces. Which process breaks rock?" },
      { item: "e2", hint: "The pebbles are being moved to a new place. Which process carries pieces away?" },
      { item: "e3", hint: "The sand is being dropped and piled up. Which process drops pieces in a new place?" },
      { item: "e4", hint: "The roots break the rock, but they don't carry it anywhere. Which process breaks rock?" },
      { item: "e5", hint: "The wind is moving the sand to a new place. Which process carries pieces away?" },
      { item: "e6", hint: "The glacier is dropping the rocks it carried. Which process drops pieces in a new place?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "What cracked the cliff?", machine: "Rock Lab", icon: "scan", speaker: "kai",
    line: "The cliff by the landing pad has cracks all over it. The rock is breaking into smaller and smaller pieces, but the pieces are still right there.",
    question: "What is this slow change called?",
    hint: "Are the pieces moving to a new place, or just breaking apart?",
    meter: { heat: 10, label: "Canyon mapped +10%", story: "The cliff cracks are named" },
    discovery: { id: "roots", name: "Root power", who: "Nova", fact: "Tree roots can grow into tiny cracks in rock. As the roots get thicker, they slowly push the rock apart. That's why roots can crack sidewalks too." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Weathering: rock breaking down into smaller pieces" },
      { id: "b", text: "Erosion: rock pieces being carried away" },
      { id: "c", text: "Deposition: rock pieces being dropped in a new place" },
      { id: "d", text: "Melting: rock turning into lava" },
    ],
    rightFeedback: "Rock breaking into smaller pieces is weathering. Nothing has moved yet.",
    wrong: [
      { choice: "b", hint: "Erosion moves pieces to a new place. Kai said the pieces are still right there." },
      { choice: "c", hint: "Deposition drops pieces that were carried from somewhere else. These pieces haven't moved." },
      { choice: "d", hint: "Melting rock takes huge heat. These rocks are cracking, not melting. What breaks rock into pieces?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The ice wedge", machine: "Freeze Chamber", icon: "trail", speaker: "nova",
    line: "High on the canyon rim, nights are freezing and days are warm. The camera shows ice splitting a rock. The steps got shuffled.",
    question: "Put the steps of ice wedging in order, first to last.",
    hint: "Water has to get into the crack before it can freeze. Water gets bigger when it freezes.",
    meter: { supplies: 1, label: "Rock samples +1", story: "The ice wedge is explained" },
    discovery: { id: "hoodoos", name: "Hoodoos", who: "Nova", fact: "Bryce Canyon in Utah has thousands of tall, thin rock towers called hoodoos. Ice wedging helps shape them, because water freezes and thaws in their cracks on many nights each year." },
    answer: { kind: "order", correct: ["seep", "freeze", "widen", "melt", "split"] },
    items: [
      { id: "widen", text: "The ice pushes on the sides and makes the crack wider." },
      { id: "split", text: "After many nights, the rock breaks apart." },
      { id: "seep", text: "Rain water trickles into a small crack in the rock." },
      { id: "melt", text: "In the day, the ice melts, and water trickles deeper into the bigger crack." },
      { id: "freeze", text: "At night, the water freezes and gets bigger." },
    ],
    rightFeedback: "Water gets in, freezes, pushes, melts, and does it again. Over many nights, the rock splits.",
    wrong: [
      { position: 0, hint: "The first step has to put water into the crack." },
      { position: 1, hint: "After the water is in the crack, what happens to it on a freezing night?" },
      { position: 2, hint: "Frozen water takes up more space. What does that do to the crack?" },
      { position: 3, hint: "The rock doesn't break after just one night. What happens in the warm day before the next freeze?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The movers", machine: "Rock Lab", icon: "relay", speaker: "vega",
    line: "Weathering makes the pieces. But something has to move them, or the canyon would fill up with rubble.",
    question: "Pick every force that can carry rock pieces away (erosion).",
    items: [
      { id: "water", text: "Moving water, like rivers and rain" },
      { id: "wind", text: "Wind" },
      { id: "ice", text: "Ice, like a slow-moving glacier" },
      { id: "gravity", text: "Gravity pulling rocks downhill" },
      { id: "moon", text: "Moonlight" },
      { id: "sound", text: "Loud sounds echoing in the canyon" },
    ],
    hint: "Think about what can push or pull rock pieces from one place to another.",
    meter: { supplies: 1, label: "Rock samples +1", story: "All the movers are listed" },
    answer: { kind: "multi", correct: ["water", "wind", "ice", "gravity"] },
    rightFeedback: "Water, wind, ice, and gravity all move rock pieces. That's erosion.",
    wrong: [
      { pick: "moon", hint: "Moonlight is just light. It can't push rocks. What can push or pull rock pieces?" },
      { pick: "sound", hint: "Echoes don't carry rocks away. What can push or pull rock pieces?" },
      { missing: true, hint: "There are four movers. Think about water, air, ice, and what makes things roll downhill." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Fast-forward the river", machine: "Time-Lapse Camera", icon: "quake", speaker: "vega",
    line: "Surprise! Kai hooked the time-lapse camera to the old rock records. We can watch a river carve a canyon near the outpost, fast-forwarded millions of years!",
    question: "Part 1: Put the steps of canyon making in order. Part 2: What does the actual cutting? Part 3: How long does a big canyon take to form?",
    parts: [
      { type: "order", prompt: "Put the steps in order, first to last.", items: [
        { id: "deeper", text: "Year after year, the canyon gets deeper and wider." },
        { id: "flow", text: "A river flows across flat rock." },
        { id: "carry", text: "The moving water carries the pieces downstream." },
        { id: "break", text: "Water and sand rub the riverbed and break off tiny pieces of rock." },
      ] },
      { type: "choice", prompt: "What does the actual cutting of the canyon?", choices: [
        { id: "a", text: "Moving water, plus the sand and pebbles it carries, scraping the rock" },
        { id: "b", text: "Fish nibbling the rock" },
        { id: "c", text: "The heat of the Sun melting the rock" },
        { id: "d", text: "One big earthquake splitting the ground" },
      ] },
      { type: "choice", prompt: "How long does it take a river to carve a big canyon?", choices: [
        { id: "a", text: "Millions of years" },
        { id: "b", text: "One night" },
        { id: "c", text: "About a week" },
        { id: "d", text: "About 10 years" },
      ] },
    ],
    hint: "Weathering breaks the rock, erosion carries the pieces away. It happens a tiny bit at a time.",
    meter: { heat: 10, label: "Canyon mapped +10%", story: "The camera shows the canyon being born" },
    discovery: { id: "grandcanyon", name: "The Grand Canyon", who: "Kai", fact: "The Colorado River carved the Grand Canyon in Arizona over millions of years. In places, the canyon is more than 1.6 kilometers (1 mile) deep." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["flow", "break", "carry", "deeper"] },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "A river breaks and carries away a tiny bit of rock at a time. Over millions of years, that makes a canyon!",
    wrong: [
      { step: 1, position: 0, hint: "Start at the very beginning, before there is any canyon at all." },
      { step: 1, position: 1, hint: "Before the water can carry pieces away, the pieces have to break off." },
      { step: 1, position: 2, hint: "Once pieces break off, what does the moving water do with them?" },
      { step: 2, choice: "b", hint: "Fish don't eat rock. What in the river scrapes against the riverbed?" },
      { step: 2, choice: "c", hint: "Sunlight can't melt rock. What is moving across the riverbed all day long?" },
      { step: 2, choice: "d", hint: "The camera shows slow cutting, not one sudden crack. What in the river scrapes the rock?" },
      { step: 3, choice: "b", hint: "Weathering and erosion are slow. A river removes only a tiny bit of rock each year." },
      { step: 3, choice: "c", hint: "A week is much too fast. A river removes only a tiny bit of rock each year." },
      { step: 3, choice: "d", hint: "In 10 years, a river barely changes a canyon. Big canyons take much, much longer." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Same thing?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Weathering and erosion are the same thing. They both just mean rocks wearing away."',
    nova: 'Nova: "They\'re different. Weathering breaks the rock. Erosion moves the pieces somewhere else."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the cracked cliff by the landing pad. Did the pieces move?",
    meter: { heat: 5, label: "Canyon mapped +5%", story: "Kai learns two words for two jobs" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Weathering breaks rock into pieces, even if they stay in place. Erosion carries the pieces away. The cracked cliff was weathered, but its pieces hadn't moved yet." },
      { id: "B", text: "Nova, because she is the scientist." },
      { id: "C", text: "Kai. Both words start with a vowel, so they mean the same thing." },
      { id: "D", text: "Kai. Rocks can only break when they are moving." },
    ],
    writtenPrompt: "Tell Kai in your own words how weathering and erosion are different.",
    debateHints: {
      wrongWho: "Remember the cracked cliff. The rock broke, but the pieces stayed put. Was that the same as being carried away?",
      wrongReason: "Right person, check the reason. Pick the one that uses evidence about what each process does.",
      right: "Nova is right — weathering breaks rock, and erosion moves the pieces.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Where will the sand land?", machine: "Map Table", icon: "water", speaker: "nova",
    line: "Our river rushes down the canyon and flows into a wide, calm lake. It's carrying tons of sand and mud. Where will the river drop it?",
    question: "Where will the river most likely drop (deposit) the most sand and mud?",
    hint: "Fast water can carry sand. What happens to the sand when the water slows down?",
    meter: { supplies: 1, label: "Rock samples +1", story: "The new sand bar is on the map" },
    discovery: { id: "deltaname", name: "Deltas", who: "Nova", fact: "A delta is land built from sand and mud a river drops where it meets a lake or ocean. Deltas are named after the Greek letter delta (Δ), because the Nile River's delta is shaped like a triangle." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "At the river's mouth, where the water slows down as it enters the calm lake" },
      { id: "b", text: "At the top of the steep canyon, where the water is fastest" },
      { id: "c", text: "In the middle of the fastest rapids" },
      { id: "d", text: "It won't drop it anywhere. The sand disappears." },
    ],
    rightFeedback: "Slow water can't hold as much sand, so it drops it at the river's mouth. That can build a delta.",
    wrong: [
      { choice: "b", hint: "Fast water picks sand up and carries it. Where does the water slow down?" },
      { choice: "c", hint: "Rapids are fast and rough. They keep sand moving. Where does the water get calm?" },
      { choice: "d", hint: "Sand never just disappears. It gets dropped somewhere. Where does the water slow down?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The mushroom rock", machine: "Wind Scanner", icon: "static", speaker: "kai",
    line: "Out in the windy desert past the outpost, there's a rock shaped like a mushroom. It's skinny at the bottom and wide at the top!",
    question: "What most likely made the bottom of the rock so skinny?",
    hint: "Wind can pick up sand, but heavy sand grains don't fly very high.",
    meter: { heat: 5, label: "Canyon mapped +5%", story: "The wind's work is explained" },
    discovery: { id: "dunes", name: "Tall sand dunes", who: "Kai", fact: "Great Sand Dunes National Park in Colorado has the tallest sand dunes in North America. The tallest is about 230 meters (750 feet) high. Wind piled up all that sand." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Wind blew sand low along the ground, and the sand slowly wore away the bottom of the rock." },
      { id: "b", text: "Someone carved it with a tool." },
      { id: "c", text: "The top of the rock grew bigger over time." },
      { id: "d", text: "A river flooded the desert every day." },
    ],
    rightFeedback: "Wind-blown sand stays close to the ground, so it wears away the bottom of the rock the most.",
    wrong: [
      { choice: "b", hint: "No one lives out there. What blows across the desert and carries sand?" },
      { choice: "c", hint: "Rocks don't grow. Something wore away the bottom. What carries sand in a desert?" },
      { choice: "d", hint: "Deserts are very dry. What moves sand across a desert instead of water?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Who made this landform?", machine: "Map Table", icon: "log", speaker: "vega",
    line: "We found six landforms on Cindara that look just like ones on Earth. Each one was shaped by water, wind, or ice.",
    question: "Sort each landform by what shaped it: water, wind, or ice.",
    hint: "Rivers carve and drop sand at their mouths. Wind piles up desert sand. Glaciers scrape valleys and leave rock piles.",
    meter: { supplies: 1, label: "Rock samples +1", story: "Every landform has a maker" },
    answer: { kind: "sort", bins: { l1: "water", l2: "wind", l3: "ice", l4: "water", l5: "ice", l6: "wind" } },
    rightFeedback: "Rivers made the canyon and the delta, wind made the dune and mushroom rock, and glaciers made the U-shaped valley and moraine.",
    sort: {
      bins: [{ id: "water", label: "Water" }, { id: "wind", label: "Wind" }, { id: "ice", label: "Ice" }],
      items: [
        { id: "l1", label: "A deep, narrow canyon with a river at the bottom" },
        { id: "l2", label: "A tall sand dune in the desert" },
        { id: "l3", label: "A long ridge of mixed rocks left where a glacier melted (a moraine)" },
        { id: "l4", label: "A fan of mud and sand where a river meets a lake (a delta)" },
        { id: "l5", label: "A wide, U-shaped valley scraped out by a glacier" },
        { id: "l6", label: "A mushroom-shaped rock in a windy desert" },
      ],
    },
    wrong: [
      { item: "l3", hint: "A moraine is left behind when a glacier melts. What is a glacier made of?" },
      { item: "l2", hint: "Sand dunes form in dry deserts. What piles up the sand there?" },
      { item: "l4", hint: "A delta forms at a river's mouth. What carried the mud and sand there?" },
      { item: "l1", hint: "There's a river at the bottom. What carved the canyon?" },
      { item: "l5", hint: "The clue says a glacier scraped it. What is a glacier made of?" },
      { item: "l6", hint: "Remember Kai's mushroom rock. What blew sand against it?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The stream table test", machine: "Stream Table", icon: "tank", speaker: "vega",
    line: "Surprise! A rockslide warning came in. Nova built a stream table: a long tray of sand with water poured in at one end. She tilted it with 1, 2, 3, then 4 blocks and poured 1 liter of water each time. Then she weighed the sand that washed out the bottom.",
    question: "Part 1: How many more grams of sand washed out with 4 blocks than with 1 block? Part 2: What pattern does the data show? Part 3: What did Nova change on purpose? Part 4: Pick the things Nova kept the same for a fair test.",
    data: {
      title: "Sand washed out of the stream table",
      columns: ["Trial", "Slope (blocks)", "Water poured", "Sand washed out (g)"],
      rows: [
        ["1", "1 block", "1 liter", "18"],
        ["2", "2 blocks", "1 liter", "40"],
        ["3", "3 blocks", "1 liter", "65"],
        ["4", "4 blocks", "1 liter", "90"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many more grams of sand washed out with 4 blocks than with 1 block?", unit: "g" },
      { type: "choice", prompt: "What pattern does the data show?", choices: [
        { id: "a", text: "The steeper the slope, the faster the water, and the more sand it carries away." },
        { id: "b", text: "The steeper the slope, the less sand washes away." },
        { id: "c", text: "The slope makes no difference." },
        { id: "d", text: "More water was poured on the steep slopes." },
      ] },
      { type: "choice", prompt: "What did Nova change on purpose?", choices: [
        { id: "a", text: "The slope (the number of blocks)" },
        { id: "b", text: "The amount of water" },
        { id: "c", text: "The amount of sand that washed out" },
        { id: "d", text: "The kind of tray" },
      ] },
      { type: "multi", prompt: "Pick the things Nova kept the same.", choices: [
        { id: "water", text: "The amount of water poured" },
        { id: "sand", text: "The kind of sand in the tray" },
        { id: "tray", text: "The same stream table tray" },
        { id: "slope", text: "The number of blocks" },
        { id: "washed", text: "The amount of sand that washed out" },
      ] },
    ],
    hint: "Read the Slope column and the Sand column together. As one goes up, what does the other do?",
    meter: { heat: 10, label: "Canyon mapped +10%", story: "The crew knows which slopes erode fastest" },
    discovery: { id: "santaelena", name: "Santa Elena Canyon", who: "Nova", fact: "In Big Bend National Park in Texas, the Rio Grande carved Santa Elena Canyon. Its rock walls rise about 460 meters (1,500 feet) above the river." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 72 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["water", "sand", "tray"] },
    ] },
    rightFeedback: "Steeper slopes make faster water, and faster water causes more erosion. That was a fair test!",
    wrong: [
      { step: 1, value: 90, hint: "90 g washed out with 4 blocks. How much more is that than with 1 block?" },
      { step: 1, value: 108, hint: "You need how many more, not the total. Should you add or subtract?" },
      { step: 1, value: 25, hint: "That's the change from 3 blocks to 4 blocks. Compare 4 blocks with 1 block." },
      { step: 2, choice: "b", hint: "Look at the Sand column. Did the numbers go up or down as the slope got steeper?" },
      { step: 2, choice: "c", hint: "The sand amounts changed a lot from trial to trial. What changed along with them?" },
      { step: 2, choice: "d", hint: "Check the Water poured column. Every trial used 1 liter." },
      { step: 3, choice: "b", hint: "Check the Water poured column. It was 1 liter every time." },
      { step: 3, choice: "c", hint: "The sand that washed out is what Nova measured. What did she change to see what would happen?" },
      { step: 3, choice: "d", hint: "Nova used the same tray every time. Which column changes from trial to trial?" },
      { step: 4, pick: "slope", hint: "The slope is what Nova changed on purpose." },
      { step: 4, pick: "washed", hint: "The sand that washed out is what Nova measured. It changed each time." },
      { step: 4, missing: true, hint: "Three things stayed the same. Think about the water, the sand, and the tray." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The rock pile riddle", machine: "Ice Scanner", icon: "shield", speaker: "kai",
    line: "Up in Cindara's cold northern hills, there's a long ridge of mixed-up rocks. Big boulders, pebbles, and sand are all jumbled together. There's no river nearby.",
    question: "What most likely left this jumbled pile of rocks?",
    hint: "Rivers sort rocks by size as they slow down. What can carry boulders and sand all mixed together?",
    meter: { heat: 10, label: "Canyon mapped +10%", story: "The rock ridge is explained" },
    discovery: { id: "moraines", name: "Moraines", who: "Kai", fact: "A moraine is a ridge of rocks and sand left behind by a glacier. Much of Long Island in New York is made of moraines dropped by glaciers thousands of years ago." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "A glacier carried the rocks, then dropped them when the ice melted." },
      { id: "b", text: "Wind blew the big boulders there." },
      { id: "c", text: "The rocks fell from space." },
      { id: "d", text: "A river dropped them yesterday." },
    ],
    rightFeedback: "Glaciers carry rocks of every size. When the ice melts, it drops them in a jumbled pile called a moraine.",
    wrong: [
      { choice: "b", hint: "Wind can move sand, but it can't lift big boulders. What is strong enough to carry boulders and sand together?" },
      { choice: "c", hint: "The rocks match the hills around them. What in the cold hills could carry rocks and then drop them?" },
      { choice: "d", hint: "There's no river nearby, and rivers sort rocks by size. What else can carry rocks in cold places?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's mistake", machine: "Map Table", icon: "log", speaker: "kai",
    line: "I labeled the new land at the river's mouth on our map. I wrote: \"EROSION — the river is wearing away land here.\" But the land is getting bigger every year.",
    question: "Part 1: What did Kai get wrong? Part 2: What should the label say?",
    parts: [
      { type: "choice", prompt: "What did Kai get wrong?", choices: [
        { id: "a", text: "The land is growing, so the river is dropping sand there, not wearing land away." },
        { id: "b", text: "Nothing. Erosion makes land bigger." },
        { id: "c", text: "He should have called it weathering, because rocks are breaking." },
        { id: "d", text: "He put the label on the wrong river." },
      ] },
      { type: "choice", prompt: "What should the label say?", choices: [
        { id: "a", text: "DEPOSITION — the slow river drops sand and mud here and builds a delta." },
        { id: "b", text: "WEATHERING — ice is cracking rocks here." },
        { id: "c", text: "EROSION — wind is blowing sand away here." },
        { id: "d", text: "MELTING — lava is cooling into new land here." },
      ] },
    ],
    hint: "Is the land at the river's mouth shrinking or growing? Which process adds pieces to a place?",
    meter: { supplies: 1, label: "Rock samples +1", story: "Kai's map label is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "A delta grows because of deposition. Erosion takes material away. Deposition drops it off.",
    wrong: [
      { step: 1, choice: "b", hint: "Erosion carries pieces away, so it makes land smaller. This land is growing." },
      { step: 1, choice: "c", hint: "Weathering breaks rock. At the river's mouth, sand and mud are piling up. Which process is that?" },
      { step: 1, choice: "d", hint: "The river is right. The process is wrong. Is the land growing or shrinking?" },
      { step: 2, choice: "b", hint: "There's no ice at the warm river mouth. What is the slow river doing with its sand?" },
      { step: 2, choice: "c", hint: "The land is growing, not blowing away. What is the river doing with its sand?" },
      { step: 2, choice: "d", hint: "There's no lava at the river's mouth. The new land is made of sand and mud. Which process drops them?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Overnight canyon?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "I bet this canyon formed in one giant flood, all in one night!"',
    nova: 'Nova: "Floods can move a lot of rock, but a canyon this deep forms slowly, a tiny bit each year, over a very long time."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the time-lapse camera and the stream table. How much sand moved each time?",
    meter: { heat: 5, label: "Canyon mapped +5%", story: "Kai sees how slow the canyon grew" },
    discovery: { id: "paloduro", name: "Palo Duro Canyon", who: "Nova", fact: "Palo Duro Canyon in the Texas Panhandle is the second-largest canyon in the United States. A branch of the Red River slowly carved it over a very long time." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A river wears away only a tiny bit of rock each year. The camera showed the canyon getting deeper slowly, over millions of years." },
      { id: "B", text: "Nova, because floods never happen." },
      { id: "C", text: "Kai. Water is so strong that it can cut deep rock in one night." },
      { id: "D", text: "Kai. The canyon looks old, so it must have formed fast." },
    ],
    writtenPrompt: "Tell Kai in your own words how a deep canyon forms.",
    debateHints: {
      wrongWho: "Remember the time-lapse camera. Did the canyon appear in one frame, or get deeper a little at a time?",
      wrongReason: "Right person, check the reason. Floods do happen. Pick the reason that uses evidence about time.",
      right: "Nova is right — canyons form slowly over a very long time.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Save the outpost hill", machine: "Outpost Crew", icon: "dial", speaker: "vega",
    line: "The hill behind the outpost has bare soil, and every rainstorm washes more of it down into our garden. We need to slow the erosion.",
    question: "Which changes would slow down erosion on the hill? Pick every one.",
    items: [
      { id: "grass", text: "Plant grass and bushes so their roots hold the soil" },
      { id: "wall", text: "Build low rock walls across the slope to slow the water" },
      { id: "mulch", text: "Cover bare soil with straw or mulch" },
      { id: "trees", text: "Cut down the trees on the hill" },
      { id: "steep", text: "Dig the hill so it is even steeper" },
      { id: "hose", text: "Spray the hill with a hose every day" },
    ],
    hint: "Remember the stream table. What made less sand wash away? Also think about what holds soil in place.",
    meter: { supplies: 1, label: "Rock samples +1", story: "The outpost hill is protected" },
    answer: { kind: "multi", correct: ["grass", "wall", "mulch"] },
    rightFeedback: "Roots hold soil, walls slow the water, and a cover keeps raindrops from knocking soil loose.",
    wrong: [
      { pick: "trees", hint: "Tree roots hold soil in place. What happens to the soil if the trees are gone?" },
      { pick: "steep", hint: "Remember the stream table. Steeper slopes lost more sand, not less." },
      { pick: "hose", hint: "More moving water means more erosion, not less." },
      { missing: true, hint: "There are three changes that help. Think about roots, slowing the water, and covering the soil." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The canyon's whole story", machine: "Time-Lapse Camera", icon: "relay", speaker: "vega",
    line: "This is it! The time-lapse camera finished its run. The outpost council wants to know if the canyon and the new delta are connected before they build the new bridge.",
    question: "Part 1: How many meters deeper did the canyon get from Frame 1 to Frame 4? Part 2: Why did the delta grow while the canyon got deeper? Part 3: If the pattern keeps going, how deep will the canyon be at Frame 5? Part 4: Write 2–3 sentences to Commander Vega explaining how weathering, erosion, and deposition made the canyon and the delta. Use the log.",
    data: {
      title: "Time-lapse camera log",
      columns: ["Frame", "Years from start", "Canyon depth (m)", "Delta width at the lake (m)"],
      rows: [
        ["1", "0", "10", "0"],
        ["2", "100,000", "40", "200"],
        ["3", "200,000", "70", "400"],
        ["4", "300,000", "100", "600"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many meters deeper did the canyon get from Frame 1 to Frame 4?", unit: "m" },
      { type: "choice", prompt: "Why did the delta grow while the canyon got deeper?", choices: [
        { id: "a", text: "The rock pieces carved out of the canyon were carried downstream and dropped where the river slows at the lake." },
        { id: "b", text: "The delta and the canyon have nothing to do with each other." },
        { id: "c", text: "Lava flowed into the lake and built the delta." },
        { id: "d", text: "The lake made new sand by itself." },
      ] },
      { type: "choice", prompt: "If the pattern keeps going, how deep will the canyon be at Frame 5?", choices: [
        { id: "a", text: "About 130 m" },
        { id: "b", text: "About 100 m" },
        { id: "c", text: "About 1,000 m" },
        { id: "d", text: "About 10 m" },
      ] },
      { type: "write", prompt: "Explain to Commander Vega how weathering, erosion, and deposition made the canyon and the delta. Use the log.", minWords: 20 },
    ],
    rubric: ["Explains that weathering broke the rock and erosion carried the pieces away", "Explains that deposition dropped the pieces at the lake to build the delta", "Uses the log as evidence and says the change was slow"],
    hint: "Read the log from top to bottom. Look at how the depth and the delta width change in each frame.",
    meter: { heat: 15, label: "Canyon mapped +15%", story: "The canyon's story is complete and the bridge is planned" },
    discovery: { id: "padre", name: "Padre Island", who: "Kai", fact: "Padre Island in Texas is one of the longest barrier islands in the world. It is made of sand that waves and currents dropped along the coast." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 90 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The canyon and the delta are one story: rock broken and carried away upstream, then dropped downstream. Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 100, hint: "100 m is the depth at Frame 4. The canyon was already 10 m deep at Frame 1. How much deeper did it get?" },
      { step: 1, value: 110, hint: "You need how much deeper, not a total. Should you add or subtract?" },
      { step: 1, value: 30, hint: "That's the change for just one frame. Compare Frame 1 with Frame 4." },
      { step: 2, choice: "b", hint: "Look at both columns. When the canyon got deeper, what happened to the delta? Where did the rock go?" },
      { step: 2, choice: "c", hint: "A delta is made of sand and mud a river drops. Where did the river get all that sand?" },
      { step: 2, choice: "d", hint: "Lakes don't make sand. The sand came from somewhere upstream. Where?" },
      { step: 3, choice: "b", hint: "100 m is Frame 4. The canyon keeps getting deeper. How much does it grow each frame?" },
      { step: 3, choice: "c", hint: "That's much too big a jump. The canyon grows about 30 m each frame." },
      { step: 3, choice: "d", hint: "The canyon doesn't get shallower. It grows about 30 m each frame." },
    ],
  },
};

export default {
  id: "SCI.4.10B-XP",
  standard: "SCI.4.10B-XP",
  engine: "expedition_station",
  title: "The Canyon Makers",
  planet: "Cindara",
  outpost: "Canyon Rim Outpost · dry season",
  grade: 4,
  subject: "Science",
  teks: "4.10B",
  supportingTeks: ["4.1B", "4.1E", "4.1G", "4.2B", "4.3A", "4.3C", "4.5A", "4.5B", "4.5G"],
  skillsChip: "4.10B · Weathering, erosion, deposition",
  iCan: "I can model and describe how weathering, erosion, and deposition from water, wind, and ice slowly change Earth's surface.",
  blurb: "A river is carving a canyon near the Cindara outpost. The crew fast-forwards it with a time-lapse camera to see how rock breaks, moves, and settles.",
  mission: "Use the time-lapse camera to find out how the river carved the canyon and built the new delta, so the crew can plan a safe bridge.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.10 · CINDARA CANYON RIM",
  playableActs: [1, 2, 3],
  earthTrue: "Cindara and the time-lapse camera are invented. Every process, fact, and data table in this quest is real Earth science.",
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Canyon mapped", heatUnit: "%", supplies: "Rock samples", suppliesUnit: "samples" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. A river near our Cindara outpost is carving a deep canyon.",
    "We want to build a bridge across it, so we need to know how it formed and how it's still changing. Kai set up a time-lapse camera that can fast-forward millions of years.",
    "Rock here breaks, moves, and settles just like it does on Earth. Watch closely. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Break it and move it", "Act 2 · Where the sand lands", "Act 3 · The canyon's whole story"],
    completes: [
      "You watched a river start a canyon, {firstName}!",
      "You found where the sand lands and ran a fair test, {firstName}!",
      "You told the canyon's whole story, {firstName}! The bridge plans are on the way.",
    ],
    teasers: [
      "Next on Cindara: Kai thinks weathering and erosion are the same thing, and the river is heading for a lake. Act 2 is open now, or come back to it next time.",
      "Next on Cindara: a jumbled rock ridge, a mislabeled map, and a canyon Kai thinks formed overnight. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The river is carrying tons of sand, and Kai and I already disagree about something.",
      "Let's follow the sand downstream.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The time-lapse camera is almost done.",
      "Help us put the canyon's whole story together.",
    ],
  }),
  tasks,
};
