// Expedition Station — The Cooling Core (SCI.5.6A-XP)
// Grade 5 · Science · Cindara. Main standard 5.6A (compare matter by
// physical properties: mass, magnetism, relative density, physical state,
// volume, solubility, conducting or insulating thermal and electric energy);
// also practices 5.6B (mixtures keep their properties), 5.6C (solutions and
// conservation of matter), 5.6D (particles too small to see), 5.1B and 5.1C
// (investigations and safety), 5.2B (analyze data), 5.3A (explanations).
//
// Earth-true rule: every material is real and behaves as it does on Earth.
// Fully locked until the student screen supports the science task types
// (sort, choice, multi, order, number, parts, write, data tables).
import { CREW, acts, lockEverything } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Load the magnet crane", machine: "Sample Bay", icon: "magnet", speaker: "kai",
    line: "The tremor scattered parts all over the yard. Load everything the magnet crane can lift.",
    question: "Sort each part: will the magnet crane pick it up?",
    hint: "Is every metal attracted to a magnet?",
    meter: { heat: 15, label: "Cooling +15%", story: "The yard is cleared" },
    answer: { kind: "sort", bins: { s1: "yes", s2: "yes", s3: "no", s4: "no", s5: "no", s6: "no" } },
    rightFeedback: "Only the iron nail and steel bolt are magnetic.",
    sort: {
      bins: [{ id: "yes", label: "The magnet lifts it" }, { id: "no", label: "The magnet doesn't lift it" }],
      items: [
        { id: "s1", label: "Iron nail" },
        { id: "s2", label: "Steel bolt" },
        { id: "s3", label: "Copper wire" },
        { id: "s4", label: "Aluminum can" },
        { id: "s5", label: "Glass bead" },
        { id: "s6", label: "Plastic cap" },
      ],
    },
    wrong: [
      { item: "s3", hint: "Copper is a metal, but not all metals are magnetic. Watch the crane: does it lift the wire?" },
      { item: "s4", hint: "Aluminum is a metal, but a magnet won't pick it up." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The coolant pool test", machine: "Sample Bay", icon: "water", speaker: "nova",
    line: "We need to know which samples float before we wash them in the coolant pool.",
    question: "Sort each sample: will it float or sink in water?",
    hint: "Think about the tiny air holes in pumice.",
    meter: { heat: 10, label: "Cooling +10%", story: "The samples are washed safely" },
    discovery: { id: "pumice", name: "Pumice", who: "Nova", fact: "Pumice is a volcanic rock so full of air bubbles that it can float on water." },
    answer: { kind: "sort", bins: { f1: "float", f2: "sink", f3: "float", f4: "sink" } },
    rightFeedback: "Pumice and wood float. Basalt and glass sink.",
    sort: {
      bins: [{ id: "float", label: "Floats" }, { id: "sink", label: "Sinks" }],
      items: [
        { id: "f1", label: "Pumice" },
        { id: "f2", label: "Basalt" },
        { id: "f3", label: "Wood block" },
        { id: "f4", label: "Glass marble" },
      ],
    },
    wrong: [{ item: "f1", hint: "Pumice is a rock, but it's full of tiny air holes. Drop it in the pool and watch." }],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Sort by state", machine: "Sample Bay", icon: "cells", speaker: "kai",
    line: "Our sample sorter has three bins: solid, liquid, and gas.",
    question: "Sort each sample by its physical state.",
    hint: "Does it keep its shape, take the shape of its container, or spread out to fill the space?",
    meter: { supplies: 1, label: "Samples +1", story: "The sorter is set up" },
    discovery: { id: "obsidian", name: "Obsidian", who: "Kai", fact: "Obsidian is volcanic glass. It forms when lava cools very quickly." },
    answer: { kind: "sort", bins: { t1: "solid", t2: "liquid", t3: "gas", t4: "liquid" } },
    rightFeedback: "Obsidian is solid, lava and coolant water are liquids, and steam is a gas.",
    sort: {
      bins: [{ id: "solid", label: "Solid" }, { id: "liquid", label: "Liquid" }, { id: "gas", label: "Gas" }],
      items: [
        { id: "t1", label: "Obsidian chunk" },
        { id: "t2", label: "Lava from the vent" },
        { id: "t3", label: "Steam from the vent" },
        { id: "t4", label: "Coolant water" },
      ],
    },
    wrong: [
      { item: "t3", hint: "Steam is water as a gas. The cloud you can see forms when some of it cools into tiny droplets." },
      { item: "t2", hint: "Lava flows and takes the shape of the ground it runs over. Solid, liquid, or gas?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Measure the rock", machine: "Log", icon: "cylinder", speaker: "nova",
    line: "The graduated cylinder had 50 mL of water. I dropped in a basalt chunk, and the water rose to 68 mL.",
    question: "What is the volume of the basalt chunk?",
    unit: "mL",
    hint: "The rock pushed the water up. By how much?",
    meter: { supplies: 1, label: "Samples +1", story: "The basalt is logged" },
    discovery: { id: "basalt", name: "Basalt", who: "Nova", fact: "Basalt is the most common volcanic rock on Earth." },
    answer: { kind: "number", value: 18 },
    rightFeedback: "68 mL − 50 mL = 18 mL. That's the rock's volume.",
    wrong: [
      { value: 68, hint: "68 mL is the water AND the rock. How much did the water go up?" },
      { value: 118, hint: "The rock pushed the water up. Should you add or subtract?" },
      { value: 50, hint: "50 mL is the water before the rock went in." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The supply spill", machine: "Mix Lab", icon: "snap", speaker: "vega",
    line: "Surprise, a supply spill! Iron filings, sand, and salt spilled into one pile. We need all three back.",
    question: "Part 1: Pick the safety gear. Part 2: Put the steps in order to get all three back. Part 3: Why can't a filter get the salt back by itself?",
    parts: [
      { type: "multi", prompt: "Pick all the safety rules you'll follow.", choices: [
        { id: "goggles", text: "Wear safety goggles" },
        { id: "notaste", text: "Never taste lab materials" },
        { id: "taste", text: "Taste the water to check for salt" },
        { id: "noshoes", text: "Take off your shoes" },
      ] },
      { type: "order", prompt: "Put the steps in order.", items: [
        { id: "magnet", text: "Pull out the iron filings with a magnet" },
        { id: "water", text: "Add water and stir so the salt dissolves" },
        { id: "filter", text: "Pour it through a filter to catch the sand" },
        { id: "evaporate", text: "Let the water evaporate to get the salt back" },
      ] },
      { type: "choice", prompt: "Why can't a filter get the salt back by itself?", choices: [
        { id: "a", text: "The dissolved salt is spread through the water, so it passes right through the filter." },
        { id: "b", text: "Salt is magnetic, so it sticks to the filter." },
        { id: "c", text: "Salt grains are bigger than sand grains." },
        { id: "d", text: "The filter melts in salt water." },
      ] },
    ],
    hint: "Which property can you use for each material: magnetism, dissolving, or grain size?",
    meter: { heat: 10, label: "Cooling +10%", story: "All the supplies are recovered" },
    discovery: { id: "desalination", name: "Salt from seawater", who: "Nova", fact: "People have made salt for thousands of years by letting seawater evaporate in shallow pools." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["goggles", "notaste"] },
      { kind: "order", correct: ["magnet", "water", "filter", "evaporate"], alsoAccept: [["water", "filter", "magnet", "evaporate"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Every material is back, and nobody broke a safety rule!",
    wrong: [
      { step: 1, pick: "taste", hint: "Never taste anything in a lab, even if you think it's just salt water." },
      { step: 1, pick: "noshoes", hint: "Shoes protect your feet in a lab. Keep them on." },
      { step: 1, missing: true, hint: "There are two safety rules to pick." },
      { step: 2, position: 2, hint: "You can only get the salt back after the filter separates the salty water from the sand." },
      { step: 2, position: 1, hint: "The salt has to dissolve in water before the filter can separate it from the sand." },
      { step: 3, choice: "b", hint: "Salt isn't magnetic. What happens to salt in water?" },
      { step: 3, choice: "c", hint: "Once salt dissolves, you can't see the grains at all. Where did they go?" },
      { step: 3, choice: "d", hint: "Filters don't melt in salt water. What happened to the salt when it dissolved?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Where did the salt go?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "I stirred 20 g of salt into 200 g of water, and the salt is gone!"',
    nova: 'Nova: "It\'s still there. The scale says 220 g."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Compare the total mass before and after mixing.",
    meter: { heat: 5, label: "Cooling +5%", story: "The crew trusts the scale" },
    discovery: { id: "dissolve", name: "Dissolving", who: "Nova", fact: "Salt dissolves faster in warm water than in cold water." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. The mass before (200 g + 20 g) equals the mass after (220 g), so the salt is still in the water. Matter is conserved." },
      { id: "B", text: "Nova, because salt water looks cloudy." },
      { id: "C", text: "Kai. If you can't see it, it's gone." },
      { id: "D", text: "Kai. The water destroyed the salt." },
    ],
    writtenPrompt: "Tell Kai in your own words how you know the salt is still there.",
    debateHints: {
      wrongWho: "Look at the scale. If the salt were gone, what would it read?",
      wrongReason: "Right person, check the reason. What does the scale prove?",
      right: "Nova is right — the mass shows the salt is still there.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The repair patch", machine: "Mix Lab", icon: "flask", speaker: "kai",
    line: "I mixed iron filings into sand to make a repair patch. Now I need some of the iron back.",
    question: "Can the crew still pull the iron filings out with a magnet? Why?",
    hint: "Did anything new form, or are they only mixed?",
    meter: { supplies: 1, label: "Samples +1", story: "The iron goes back in the kit" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Yes. In a mixture, each substance keeps its own properties, so the iron is still magnetic." },
      { id: "b", text: "No. Mixing turned the iron into sand." },
      { id: "c", text: "No. Sand blocks magnets." },
      { id: "d", text: "Yes, but only if you add water first." },
    ],
    rightFeedback: "The magnet sweeps the pile and pulls out the iron.",
    wrong: [
      { choice: "b", hint: "Mixing doesn't make a new substance. Is the iron still iron?" },
      { choice: "c", hint: "Magnets can pull iron through sand. Try it in the Mix Lab." },
      { choice: "d", hint: "You don't need water. Is the iron still magnetic after mixing?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The weather balloon", machine: "Mix Lab", icon: "balloon", speaker: "nova",
    line: "I filled a balloon with air for the weather probe.",
    question: "Which model shows what's inside the balloon?",
    hint: "If the balloon were empty, what would happen to its shape?",
    meter: { heat: 5, label: "Cooling +5%", story: "The weather probe launches" },
    discovery: { id: "hotairballoon", name: "Hot air balloons", who: "Nova", fact: "Hot air balloons rise because hot air is less dense than the cooler air around it." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "An empty balloon with nothing inside" },
      { id: "b", text: "Many tiny air particles, too small to see, spread through the whole balloon" },
      { id: "c", text: "Tiny particles packed tightly at the bottom" },
      { id: "d", text: "One big bubble of air in the middle" },
    ],
    rightFeedback: "Air is made of particles too small to see, and they fill the whole balloon.",
    wrong: [
      { choice: "a", hint: "Then what's keeping the balloon stretched out?" },
      { choice: "c", hint: "Particles packed tightly at the bottom sounds more like a solid. Gas spreads out." },
      { choice: "d", hint: "Air is made of tiny particles, not one big bubble." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The dissolving test", machine: "Sample Bay", icon: "flask", speaker: "kai",
    line: "We need to know which materials dissolve in water before we mix the new coolant.",
    question: "Pick every material that dissolves in water.",
    items: [
      { id: "salt", text: "Salt" },
      { id: "sugar", text: "Sugar" },
      { id: "sand", text: "Sand" },
      { id: "iron", text: "Iron filings" },
      { id: "basalt", text: "Crushed basalt" },
    ],
    hint: "Let each one sit in water for a minute. What settles at the bottom?",
    meter: { supplies: 1, label: "Samples +1", story: "The coolant recipe is ready" },
    answer: { kind: "multi", correct: ["salt", "sugar"] },
    rightFeedback: "Salt and sugar dissolve. The others settle to the bottom.",
    wrong: [
      { pick: "sand", hint: "Sand makes the water muddy, but let it sit. Does it settle?" },
      { pick: "iron", hint: "Iron filings sink to the bottom. Do they dissolve?" },
      { pick: "basalt", hint: "Crushed rock sinks and stays rock. Does it dissolve?" },
      { missing: true, hint: "There's one more material that dissolves." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The strange result", machine: "Test Bay", icon: "quake", speaker: "vega",
    line: "Surprise, one of Nova's results doesn't fit! She tested whether water temperature changes how fast salt dissolves. She used the same amount of salt and water every time and ran 3 trials at each temperature. Kai's note: \"I might have stirred harder on the last room-temperature one.\"",
    question: "Part 1: What pattern do you see? Part 2: Which result is most likely an error? Part 3: What could have caused it? Part 4: Pick two things that had to stay the same for a fair test.",
    data: {
      title: "Seconds for the salt to dissolve",
      columns: ["Water temperature", "Trial 1", "Trial 2", "Trial 3"],
      rows: [
        ["10°C", "182", "178", "185"],
        ["25°C", "121", "118", "64"],
        ["40°C", "70", "73", "68"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What pattern do you see?", choices: [
        { id: "a", text: "The warmer the water, the faster the salt dissolved." },
        { id: "b", text: "The colder the water, the faster the salt dissolved." },
        { id: "c", text: "Temperature didn't change anything." },
      ] },
      { type: "choice", prompt: "Which result is most likely an error?", choices: [
        { id: "a", text: "10°C, trial 3 (185 seconds)" },
        { id: "b", text: "25°C, trial 3 (64 seconds)" },
        { id: "c", text: "40°C, trial 2 (73 seconds)" },
      ] },
      { type: "choice", prompt: "What could have caused it?", choices: [
        { id: "a", text: "Kai stirred harder during that trial." },
        { id: "b", text: "The salt was a different color." },
        { id: "c", text: "It was a different day of the week." },
      ] },
      { type: "multi", prompt: "Pick two things that had to stay the same.", choices: [
        { id: "salt", text: "The amount of salt" },
        { id: "water", text: "The amount of water" },
        { id: "temp", text: "The water temperature" },
        { id: "shirt", text: "The color of Nova's lab coat" },
      ] },
    ],
    hint: "Look for a number that doesn't match the other trials at the same temperature.",
    meter: { heat: 5, label: "Cooling +5%", story: "Nova reruns the odd trial" },
    discovery: { id: "trials", name: "Repeated trials", who: "Nova", fact: "Scientists repeat tests several times so one odd result doesn't fool them." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["salt", "water"] },
    ] },
    rightFeedback: "Warmer water dissolved salt faster, and you caught the odd trial!",
    wrong: [
      { step: 1, choice: "b", hint: "Compare the times. Which temperature took the fewest seconds?" },
      { step: 1, choice: "c", hint: "The times get shorter as the water gets warmer. Does that look like no change?" },
      { step: 2, choice: "a", hint: "185 is close to 182 and 178. Look for a number that doesn't match its row." },
      { step: 2, choice: "c", hint: "73 is close to 70 and 68. Look for a number that doesn't match its row." },
      { step: 3, choice: "b", hint: "Color doesn't change how fast salt dissolves. Read Kai's note." },
      { step: 3, choice: "c", hint: "The day doesn't change how fast salt dissolves. Read Kai's note." },
      { step: 4, pick: "temp", hint: "Temperature is the thing Nova changed on purpose. What had to stay the same?" },
      { step: 4, pick: "shirt", hint: "A lab coat color can't change the results. What else could?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The heat panel", machine: "Sample Bay", icon: "shield", speaker: "kai",
    line: "We need a panel that keeps the heat of the lava vent away from the control room.",
    question: "Which material insulates best?",
    hint: "Which materials let heat move through easily?",
    meter: { heat: 10, label: "Cooling +10%", story: "The control room stays cool" },
    discovery: { id: "oven", name: "Oven mitts", who: "Nova", fact: "Oven mitts are made of materials that insulate, so heat can't easily reach your hand." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Copper sheet" },
      { id: "b", text: "Aluminum foil" },
      { id: "c", text: "Ceramic tile" },
      { id: "d", text: "Steel plate" },
    ],
    rightFeedback: "Ceramic is an insulator. The metals all conduct heat.",
    wrong: [
      { choice: "a", hint: "Copper is shiny, but heat flows right through it." },
      { choice: "b", hint: "Aluminum conducts heat. Think about how fast a foil pan heats up." },
      { choice: "d", hint: "Steel is a metal, and metals conduct heat." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Fix the sensor circuit", machine: "Power Grid", icon: "circuit", speaker: "nova",
    line: "The circuit to the heat sensor is broken. We need to close the gap and make it safe to touch.",
    question: "Part 1: Which material should connect the gap? Part 2: Which material should cover the wire so no one gets shocked?",
    parts: [
      { type: "choice", prompt: "Which material should connect the gap?", choices: [
        { id: "copper", text: "Copper wire" },
        { id: "rubber", text: "Rubber band" },
        { id: "glass", text: "Glass rod" },
        { id: "wood", text: "Wooden stick" },
      ] },
      { type: "choice", prompt: "Which material should cover the wire?", choices: [
        { id: "copper", text: "Copper" },
        { id: "rubber", text: "Rubber" },
        { id: "aluminum", text: "Aluminum" },
        { id: "iron", text: "Iron" },
      ] },
    ],
    hint: "Conductors let electricity move through. Insulators block it.",
    meter: { supplies: 1, label: "Samples +1", story: "The heat sensor turns on" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "copper" }, { kind: "choice", correct: "rubber" }] },
    rightFeedback: "Copper carries the electricity, and rubber keeps hands safe.",
    wrong: [
      { step: 1, choice: "rubber", hint: "Rubber blocks electricity. The sensor stays dark." },
      { step: 1, choice: "glass", hint: "Glass is an insulator. Electricity can't flow through it." },
      { step: 1, choice: "wood", hint: "Dry wood is an insulator. The sensor stays dark." },
      { step: 2, choice: "copper", hint: "Copper would let the electricity reach your hand. What blocks it?" },
      { step: 2, choice: "aluminum", hint: "Aluminum conducts electricity. What blocks it?" },
      { step: 2, choice: "iron", hint: "Iron conducts electricity. What blocks it?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The big rock debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Big rocks always sink, and small rocks float."',
    nova: 'Nova: "It depends on what the rock is made of. Remember the pool test?"',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "What happened to the pumice in task 2?",
    meter: { heat: 5, label: "Cooling +5%", story: "Kai rethinks his rock rule" },
    discovery: { id: "icebergs", name: "Icebergs", who: "Nova", fact: "Icebergs float because ice is less dense than liquid water. Most of an iceberg is hidden under the water." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A big pumice rock floats and a small basalt pebble sinks, so size doesn't decide it. The material does." },
      { id: "B", text: "Nova, because rocks never sink." },
      { id: "C", text: "Kai. Heavier things always sink." },
      { id: "D", text: "Kai. Size is the only thing that matters." },
    ],
    writtenPrompt: "Tell Kai in your own words what decides whether a rock floats.",
    debateHints: {
      wrongWho: "Picture a big pumice rock and a tiny basalt pebble in the pool. What happens?",
      wrongReason: "Right person, check the reason. What decides floating: size or material?",
      right: "Nova is right — the material decides, not the size.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The sweet coolant", machine: "Mix Lab", icon: "flask", speaker: "kai",
    line: "I stirred sugar into water, and the grains disappeared.",
    question: "Without tasting it, how can the crew prove the sugar is still there? Pick two ways.",
    items: [
      { id: "mass", text: "The total mass is the same as before mixing." },
      { id: "evaporate", text: "Evaporating the water leaves sugar crystals behind." },
      { id: "taste", text: "Taste it." },
      { id: "look", text: "Look for sugar grains." },
    ],
    hint: "How did Nova prove the salt was still there in task 6?",
    meter: { supplies: 1, label: "Samples +1", story: "The coolant passes inspection" },
    answer: { kind: "multi", correct: ["mass", "evaporate"] },
    rightFeedback: "The scale and evaporation both prove it, and nobody tasted anything.",
    wrong: [
      { pick: "taste", hint: "Never taste lab materials. How else can you prove it?" },
      { pick: "look", hint: "The grains dissolved, so you can't see them. That doesn't prove anything." },
      { missing: true, hint: "Pick two ways." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Rebuild the shield", machine: "Sample Bay", icon: "relay", speaker: "vega",
    line: "This is it! The cooling core needs a new heat shield. It must insulate heat, must NOT be magnetic (it sits next to the navigation compass), and must stay solid at 700°C.",
    question: "Part 1: Pick the material. Part 2: Match each other material to the rule it breaks. Part 3: Write 2–3 sentences to Commander Vega explaining your choice, using the data.",
    data: {
      title: "Shield materials",
      columns: ["Material", "Magnetic?", "Heat test", "Solid at 700°C?"],
      rows: [
        ["Steel plate", "Yes", "Conducts heat", "Yes"],
        ["Aluminum sheet", "No", "Conducts heat", "No (melts around 660°C)"],
        ["Ceramic tile", "No", "Insulates", "Yes"],
        ["Plastic panel", "No", "Insulates", "No"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which material should the shield be?", choices: [
        { id: "steel", text: "Steel plate" },
        { id: "aluminum", text: "Aluminum sheet" },
        { id: "ceramic", text: "Ceramic tile" },
        { id: "plastic", text: "Plastic panel" },
      ] },
      { type: "sort", prompt: "Match each material to a rule it breaks.", bins: [
        { id: "magnetic", label: "It's magnetic" },
        { id: "melts", label: "It melts below 700°C" },
      ], items: [
        { id: "steel", label: "Steel plate" },
        { id: "aluminum", label: "Aluminum sheet" },
        { id: "plastic", label: "Plastic panel" },
      ] },
      { type: "write", prompt: "Explain your choice to Commander Vega. Use the data.", minWords: 20 },
    ],
    rubric: ["Makes a claim (which material)", "Uses data from the table as evidence", "Explains how each property meets a rule"],
    hint: "Check every material against all three rules, one at a time.",
    meter: { heat: 10, label: "Cooling +10%", story: "The cooling core is back online" },
    discovery: { id: "spaceshuttle", name: "Heat shields", who: "Kai", fact: "Spacecraft use heat shields made of materials like ceramic tiles to protect them from extreme heat." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "ceramic" },
      { kind: "sort", bins: { steel: "magnetic", aluminum: "melts", plastic: "melts" } },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Ceramic it is! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "aluminum", hint: "Aluminum isn't magnetic, but check the last column. What happens at 700°C?" },
      { step: 1, choice: "steel", hint: "Steel would pull the compass needle. Check the Magnetic column." },
      { step: 1, choice: "plastic", hint: "Plastic insulates, but check the last column. Does it stay solid?" },
      { step: 2, item: "aluminum", hint: "Aluminum isn't magnetic. Look at the Solid at 700°C column." },
      { step: 2, item: "steel", hint: "Steel stays solid at 700°C. Look at the Magnetic column." },
    ],
  },
};

export default lockEverything({
  id: "SCI.5.6A-XP",
  standard: "SCI.5.6A-XP",
  engine: "expedition_station",
  title: "The Cooling Core",
  planet: "Cindara",
  outpost: "Core Station · after the tremor",
  grade: 5,
  subject: "Science",
  teks: "5.6A",
  supportingTeks: ["5.6B", "5.6C", "5.6D", "5.1B", "5.1C", "5.2B", "5.3A"],
  skillsChip: "5.6A · Properties of matter",
  iCan: "I can compare materials by their properties, like magnetism, whether they float, their state, and whether they dissolve or conduct heat. I can separate mixtures and explain what happens in a solution.",
  blurb: "A lava tremor cracked the cooling core that keeps the Cindara outpost from overheating. Every fix depends on knowing what materials can do.",
  mission: "Sort samples, recover spilled supplies, and choose the right material to rebuild the core's heat shield.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.60 · CINDARA CORE STATION",
  playableActs: [],
  earthTrue: "Every material in this quest is real and behaves as it does on Earth. Only the planet and crew are invented.",
  meterStart: { heat: 30, supplies: 0, journal: 0 },
  meterLabels: { heat: "Cooling", heatUnit: "%", supplies: "Samples", suppliesUnit: "samples" },
  journalMax: 10,
  opening: [
    "Specialist {name}, this is Commander Vega. A lava tremor cracked the cooling core on Cindara.",
    "Parts and samples are scattered everywhere, and the crew needs to rebuild the core's heat shield.",
    "Every material behaves just like it does on Earth. Use what you know. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Sort the tremor site", "Act 2 · Mixtures and solutions", "Act 3 · Rebuild the shield"],
    completes: [
      "The tremor site is sorted and the supplies are back, {firstName}!",
      "The coolant is mixed and tested, {firstName}!",
      "The cooling core is back online, {firstName}! Cindara's outpost is safe.",
    ],
    teasers: [
      "Next on Cindara: the crew needs to mix new coolant, and Kai thinks the salt disappeared. Act 2 opens on your next station visit.",
      "Next on Cindara: it's time to rebuild the heat shield. Act 3 opens on your next station visit.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. We're mixing new coolant, and Kai and I already disagree about something.",
      "Let's run some tests.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The cooling core needs a new heat shield.",
      "Test the materials and choose the one that meets every rule.",
    ],
  }),
  tasks,
});
