// Expedition Station — The Creature Pens (MA.3.7B-XP)
// Grade 3 · Math · Solara (jungle moon). Main standard 3.7B (perimeter of a
// polygon, or a missing side length when given the perimeter and the other
// side lengths). Also practices 3.6C (area of rectangles) as the contrast:
// fence goes AROUND a pen (perimeter), grass mats cover the INSIDE (area).
// Grade 3 limits: whole-number side lengths, numbers within 100.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Fence the capybara pen", machine: "Fence Counter", icon: "grid", speaker: "kai",
    line: "Our rescue camp has its first guests: two capybaras! Their pen is a rectangle, 5 meters long and 3 meters wide. The fence goes all the way around the edge.",
    question: "How many meters of fence go all the way around the capybara pen?",
    unit: "meters",
    visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "3 m" }, title: "Capybara pen" },
    hint: "Perimeter is the distance around. Walk the edge: 5 + 3 + 5 + 3. A rectangle has 4 sides, not 2.",
    meter: { heat: 10, label: "Pens ready +10%", story: "The capybara pen is fenced" },
    discovery: { id: "capybara", name: "Capybaras", who: "Nova", fact: "Capybaras are the biggest rodents on Earth. They have webbed toes that help them swim in rivers and ponds." },
    answer: { kind: "number", value: 16 },
    rightFeedback: "5 + 3 + 5 + 3 = 16. The capybara pen needs 16 meters of fence!",
    wrong: [
      { value: 15, hint: "15 is the number of squares inside. That's area. The fence goes around the edge." },
      { value: 8, hint: "5 + 3 = 8 is only two sides. A rectangle has 4 sides. Add the other two." },
      { value: 12, hint: "It looks like you counted the edge squares. Measure the sides instead: 5 + 3 + 5 + 3." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Around the tapir pen", machine: "Fence Counter", icon: "cells", speaker: "nova",
    line: "A young tapir just arrived. Her pen is 6 meters long and 4 meters wide. Before Kai cuts the fence, we need to plan.",
    question: "Part 1: How do we find the distance around the pen? Part 2: How many meters of fence does the tapir pen need?",
    parts: [
      { type: "choice", prompt: "How do we find the distance around the tapir pen?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "4 m" }, title: "Tapir pen" },
        choices: [
          { id: "a", text: "Add all 4 sides: 6 + 4 + 6 + 4." },
          { id: "b", text: "Add the 2 sides we can see labeled: 6 + 4." },
          { id: "c", text: "Multiply 6 × 4." },
          { id: "d", text: "Count the squares inside the pen." },
        ] },
      { type: "number", prompt: "How many meters of fence does the tapir pen need?", unit: "meters" },
    ],
    hint: "The fence wraps around every side. The top and bottom are both 6 m. The left and right are both 4 m.",
    meter: { heat: 5, label: "Pens ready +5%", story: "The tapir pen is fenced" },
    discovery: { id: "tapir", name: "Tapirs", who: "Nova", fact: "Baby tapirs have white stripes and spots. The pattern helps them hide in the speckled light of the forest floor." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 20 }] },
    rightFeedback: "6 + 4 + 6 + 4 = 20. The tapir pen needs 20 meters of fence!",
    wrong: [
      { step: 1, choice: "b", hint: "Only 2 sides have labels, but the pen has 4 sides. The sides across from each other match." },
      { step: 1, choice: "c", hint: "6 × 4 counts the squares inside. That's area. Fence goes around the edge." },
      { step: 1, choice: "d", hint: "The squares inside tell the area. We need the distance around." },
      { step: 2, value: 24, hint: "24 is the area, the squares inside. Add the 4 sides instead." },
      { step: 2, value: 10, hint: "6 + 4 = 10 is only 2 sides. Add the other 2 sides too." },
      { step: 2, value: 16, hint: "Check each side. The long sides are 6 m, the short sides are 4 m: 6 + 4 + 6 + 4." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The triangle perch pen", machine: "Side Scanner", icon: "scan", speaker: "kai",
    line: "The parrots want a pen shaped like a triangle, tucked between three big trees. I measured each side and put it in the table.",
    question: "What is the perimeter of the triangle pen?",
    unit: "meters",
    data: {
      title: "Parrot pen · triangle",
      columns: ["Side", "Length"],
      rows: [
        ["Side A", "9 m"],
        ["Side B", "7 m"],
        ["Side C", "8 m"],
      ],
    },
    hint: "A triangle has 3 sides. Add all 3 lengths: 9 + 7 + 8.",
    meter: { heat: 5, label: "Pens ready +5%", story: "The parrot pen is fenced" },
    discovery: { id: "macawlife", name: "Long-lived macaws", who: "Kai", fact: "Scarlet macaws are big rainforest parrots. Some live more than 50 years." },
    answer: { kind: "number", value: 24 },
    rightFeedback: "9 + 7 + 8 = 24. The triangle pen needs 24 meters of fence!",
    wrong: [
      { value: 16, hint: "9 + 7 = 16 is only 2 sides. A triangle has 3 sides. Add Side C too." },
      { value: 15, hint: "7 + 8 = 15 is only 2 sides. Add Side A too." },
      { value: 23, hint: "Close! Check your adding: 9 + 7 = 16, then 16 + 8 = ?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The five-sided mud pen", machine: "Side Scanner", icon: "dial", speaker: "nova",
    line: "The tortoises get a pen with 5 sides, so it fits around a muddy spot they love. I need to write the fence length on the gate sign.",
    question: "Part 1: What is the perimeter of the pentagon pen? Part 2: Which sign is right?",
    parts: [
      { type: "number", prompt: "Add all 5 sides. What is the perimeter of the pen?", unit: "meters",
        data: {
          title: "Tortoise pen · pentagon",
          columns: ["Side", "Length"],
          rows: [
            ["Side A", "5 m"],
            ["Side B", "8 m"],
            ["Side C", "5 m"],
            ["Side D", "6 m"],
            ["Side E", "6 m"],
          ],
        } },
      { type: "choice", prompt: "Which sign should Nova hang on the gate?", choices: [
        { id: "a", text: "Fence: 30 meters" },
        { id: "b", text: "Fence: 30 square meters" },
        { id: "c", text: "Fence: 24 meters" },
        { id: "d", text: "Fence: 5 meters" },
      ] },
    ],
    hint: "A pentagon has 5 sides. Add them one at a time: 5 + 8 + 5 + 6 + 6. Fence is a length, so it is measured in meters.",
    meter: { heat: 5, label: "Pens ready +5%", story: "The tortoise pen sign is up" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 30 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "5 + 8 + 5 + 6 + 6 = 30. The sign says 30 meters of fence!",
    wrong: [
      { step: 1, value: 24, hint: "24 is only 4 sides. A pentagon has 5 sides. Did you skip one?" },
      { step: 1, value: 25, hint: "It looks like one side is missing. Add all 5: 5 + 8 + 5 + 6 + 6." },
      { step: 1, value: 29, hint: "Close! Check your adding. 5 + 8 = 13, 13 + 5 = 18, then add 6 and 6." },
      { step: 2, choice: "b", hint: "Square meters measure the space inside. Fence is a length around the edge, so use meters." },
      { step: 2, choice: "c", hint: "24 meters leaves out one side. Add all 5 sides." },
      { step: 2, choice: "d", hint: "5 is the number of sides, not the length around." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The sloth surprise", machine: "Fence Roll", icon: "quake", speaker: "vega",
    line: "Surprise! A rescue team dropped off a baby sloth. Its pen has 6 sides and wraps around a tree. We have one roll of fence that is 60 meters long.",
    question: "Part 1: What is the perimeter of the sloth pen? Part 2: How much fence is left on the roll? Part 3: A square nest-box pen has sides of 3 meters. Is there enough fence left for it?",
    parts: [
      { type: "number", prompt: "Add all 6 sides. What is the perimeter of the sloth pen?", unit: "meters",
        data: {
          title: "Sloth pen · hexagon",
          columns: ["Side", "Length"],
          rows: [
            ["Side A", "7 m"],
            ["Side B", "9 m"],
            ["Side C", "7 m"],
            ["Side D", "7 m"],
            ["Side E", "9 m"],
            ["Side F", "7 m"],
          ],
        } },
      { type: "number", prompt: "The roll has 60 meters of fence. How many meters are left after the sloth pen?", unit: "meters" },
      { type: "choice", prompt: "The square nest-box pen has 4 sides of 3 meters. Is there enough fence left?", choices: [
        { id: "a", text: "Yes. It needs 12 meters, and there are 14 left. 2 meters will be extra." },
        { id: "b", text: "No. It needs 9 meters, because 3 × 3 = 9." },
        { id: "c", text: "Yes. It needs only 3 meters, because all the sides are the same." },
        { id: "d", text: "No. It needs 16 meters." },
      ] },
    ],
    hint: "Add 7 + 9 + 7 + 7 + 9 + 7. Then subtract that from 60. A square has 4 equal sides, so add 3 four times.",
    meter: { heat: 10, label: "Pens ready +10%", story: "The sloth pen is fenced" },
    discovery: { id: "slothswim", name: "Swimming sloths", who: "Nova", fact: "Sloths are slow in trees but good swimmers. They can hold their breath underwater for a long time by slowing down their hearts." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 46 }, { kind: "number", value: 14 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "7 + 9 + 7 + 7 + 9 + 7 = 46. 60 − 46 = 14 left, and the nest-box pen needs 12. The sloth is safe!",
    wrong: [
      { step: 1, value: 16, hint: "7 + 9 = 16 is only 2 sides. A hexagon has 6 sides. Add all of them." },
      { step: 1, value: 39, hint: "That's only 5 sides. Count the rows in the table. There are 6 sides." },
      { step: 1, value: 44, hint: "Close! Check your adding. There are four 7s and two 9s." },
      { step: 2, value: 46, hint: "46 meters is the fence we USED. How much is left of the 60? Subtract." },
      { step: 2, value: 106, hint: "Don't add. We used 46 of the 60 meters. Subtract to find what's left." },
      { step: 2, value: 24, hint: "Check your subtraction: 60 − 46 = ?" },
      { step: 3, choice: "b", hint: "3 × 3 = 9 is the squares inside. Fence goes around 4 sides: 3 + 3 + 3 + 3." },
      { step: 3, choice: "c", hint: "Every side needs fence, even when the sides are the same. A square has 4 sides." },
      { step: 3, choice: "d", hint: "Add the 4 sides again: 3 + 3 + 3 + 3." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The missing short side", machine: "Side Finder", icon: "trail", speaker: "nova",
    line: "The capybaras need a bigger pond pen. Commander Vega says it's a rectangle with 30 meters of fence all around. The long sides are 9 meters. I lost the short side number!",
    question: "How many meters long is each short side of the pond pen?",
    unit: "meters",
    data: {
      title: "Pond pen · rectangle · perimeter 30 m",
      columns: ["Side", "Length"],
      rows: [
        ["Long side", "9 m"],
        ["Short side", "?"],
        ["Long side", "9 m"],
        ["Short side", "?"],
      ],
    },
    hint: "The two long sides use 9 + 9 = 18 meters. The rest of the 30 meters is split between the 2 short sides.",
    meter: { supplies: 1, label: "Pens built +1", story: "The pond pen is measured" },
    discovery: { id: "capybarafriends", name: "Capybara friends", who: "Kai", fact: "Capybaras are so calm that birds often ride on their backs. The birds snack on bugs in the capybara's fur." },
    answer: { kind: "number", value: 6 },
    rightFeedback: "9 + 9 = 18, and 30 − 18 = 12. Two short sides share 12, so each one is 6 meters!",
    wrong: [
      { value: 21, hint: "30 − 9 = 21 only takes away one long side. There are 2 long sides and 2 short sides." },
      { value: 12, hint: "12 meters is BOTH short sides together. Split it between the 2 short sides." },
      { value: 3, hint: "Check: 9 + 3 + 9 + 3 = 24, not 30. Try a bigger short side." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The squares-inside debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The new tortoise yard is 5 meters by 4 meters. I counted 20 squares inside, so we need 20 meters of fence."',
    nova: 'Nova: "We need 18 meters. Fence goes around the edge: 5 + 4 + 5 + 4 = 18. The 20 squares are the space inside."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "4 m" }, title: "Tortoise yard" },
    hint: "Trace the gold edge with your finger. Is the fence on the edge, or on the squares inside?",
    meter: { heat: 5, label: "Pens ready +5%", story: "The tortoise yard gets the right fence" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Perimeter is the distance around the edge, so add the 4 sides: 5 + 4 + 5 + 4 = 18." },
      { id: "B", text: "Nova, because 18 is a smaller number, so it saves fence." },
      { id: "C", text: "Kai. Perimeter is the number of squares inside the pen." },
      { id: "D", text: "Kai. You always multiply the sides to find how much fence you need." },
    ],
    writtenPrompt: "Tell Kai in your own words why the yard needs 18 meters of fence, not 20.",
    debateHints: {
      wrongWho: "The squares inside tell the area. Does the fence go inside the yard, or around it?",
      wrongReason: "Right person, check the reason. What does perimeter measure?",
      right: "Nova is right. Perimeter is the distance around: 5 + 4 + 5 + 4 = 18 meters. The 20 squares are the area.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Two pens, one fence", machine: "Fence Counter", icon: "cells", speaker: "kai",
    line: "I built two play pens for the parrots. Pen A is long and skinny: 2 meters by 8 meters. Pen B is 4 meters by 6 meters. They look so different!",
    question: "Part 1: What is the perimeter of Pen A? Part 2: What is the perimeter of Pen B? Part 3: What do you notice?",
    parts: [
      { type: "number", prompt: "Pen A is 2 m by 8 m. How many meters of fence go around it?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 2, cols: 8, perimeter: true, sideLabels: { top: "8 m", left: "2 m" }, title: "Pen A" } },
      { type: "number", prompt: "Pen B is 4 m by 6 m. How many meters of fence go around it?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "4 m" }, title: "Pen B" } },
      { type: "choice", prompt: "What do you notice about the two pens?", choices: [
        { id: "a", text: "They use the same amount of fence, 20 meters, even though they are different shapes." },
        { id: "b", text: "Pen A needs more fence, because it is longer." },
        { id: "c", text: "Pen B needs more fence, because it is wider." },
        { id: "d", text: "Different shapes can never have the same perimeter." },
      ] },
    ],
    hint: "Add all 4 sides of each pen. Pen A: 8 + 2 + 8 + 2. Pen B: 6 + 4 + 6 + 4.",
    meter: { supplies: 2, label: "Pens built +2", story: "Both parrot play pens are fenced" },
    discovery: { id: "parrotfeet", name: "Parrot feet", who: "Nova", fact: "Parrots have two toes pointing forward and two pointing back. That helps them grip branches and hold food like a hand." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 20 }, { kind: "number", value: 20 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "8 + 2 + 8 + 2 = 20 and 6 + 4 + 6 + 4 = 20. Different shapes, the same perimeter!",
    wrong: [
      { step: 1, value: 16, hint: "16 is the squares inside Pen A. That's area. Add the 4 sides." },
      { step: 1, value: 10, hint: "8 + 2 = 10 is only 2 sides. Add the other 2 sides." },
      { step: 2, value: 24, hint: "24 is the squares inside Pen B. That's area. Add the 4 sides." },
      { step: 2, value: 10, hint: "6 + 4 = 10 is only 2 sides. Add the other 2 sides." },
      { step: 3, choice: "b", hint: "Pen A is longer, but it is also thinner. Compare the two numbers you found." },
      { step: 3, choice: "c", hint: "Pen B is wider, but it is also shorter. Compare the two numbers you found." },
      { step: 3, choice: "d", hint: "Look at your answers. Did the two pens need different amounts of fence?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's fence order", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote: "The tapir mud pen is 8 meters long and 5 meters wide. 8 + 5 = 13. Order 13 meters of fence." The fence came, and it only reached halfway around!',
    question: "Part 1: What went wrong? Part 2: How much fence does the pen really need?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 8, perimeter: true, sideLabels: { top: "8 m", left: "5 m" }, title: "Tapir mud pen" },
        choices: [
          { id: "a", text: "He only added 2 sides. He forgot the other long side and the other short side." },
          { id: "b", text: "He should have multiplied 8 × 5." },
          { id: "c", text: "He should have counted the squares inside." },
          { id: "d", text: "Nothing. 13 meters is right." },
        ] },
      { type: "number", prompt: "How many meters of fence does the tapir mud pen really need?", unit: "meters" },
    ],
    hint: "A rectangle has 4 sides. The sides across from each other are the same length: 8 + 5 + 8 + 5.",
    meter: { supplies: 1, label: "Pens built +1", story: "Kai's fence order is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 26 }] },
    rightFeedback: "Fixed! 8 + 5 + 8 + 5 = 26 meters. Kai forgot the two sides he couldn't see labeled.",
    wrong: [
      { step: 1, choice: "b", hint: "8 × 5 = 40 is the squares inside. That's area, not fence." },
      { step: 1, choice: "c", hint: "The squares inside tell the area. Fence goes around the edge." },
      { step: 1, choice: "d", hint: "The fence only reached halfway around. How many sides did Kai add?" },
      { step: 2, value: 13, hint: "13 is only 2 sides. Add the other long side and the other short side too." },
      { step: 2, value: 40, hint: "40 is the squares inside. That's area. Add the 4 sides." },
      { step: 2, value: 21, hint: "That's only 3 sides. Add all 4: 8 + 5 + 8 + 5." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "More room, same fence", machine: "Pen Planner", icon: "snap", speaker: "vega",
    line: "Surprise! The capybaras had four babies. The family needs more room to roam, but we have just 24 meters of fence. Kai and Nova each drew a plan.",
    question: "Part 1: What is the perimeter of Kai's pen? Part 2: What is the perimeter of Nova's pen? Part 3: What is the area of Nova's pen? Part 4: Which pen should we build?",
    parts: [
      { type: "number", prompt: "Kai's pen is 2 m by 10 m. What is its perimeter?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 2, cols: 10, perimeter: true, sideLabels: { top: "10 m", left: "2 m" }, title: "Kai's plan · area 20 square meters" } },
      { type: "number", prompt: "Nova's pen is 6 m by 6 m. What is its perimeter?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 6, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "6 m" }, title: "Nova's plan" } },
      { type: "number", prompt: "Nova's pen has 6 rows of 6 squares. What is its area?", unit: "square meters" },
      { type: "choice", prompt: "Kai's pen has an area of 20 square meters. Which pen gives the capybaras more room?", choices: [
        { id: "a", text: "Nova's pen. Both use 24 meters of fence, but hers has 36 square meters inside." },
        { id: "b", text: "Kai's pen, because it is longer." },
        { id: "c", text: "They give the same room, because they use the same fence." },
        { id: "d", text: "Kai's pen, because 10 is the biggest side." },
      ] },
    ],
    hint: "Perimeter: add the 4 sides. Area: rows × squares in each row. Same fence does not always mean same room inside.",
    meter: { heat: 10, label: "Pens ready +10%", story: "The capybara family has room to roam" },
    discovery: { id: "capybarababies", name: "Capybara babies", who: "Nova", fact: "Baby capybaras can walk and swim just a few hours after they are born." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 24 }, { kind: "number", value: 24 }, { kind: "number", value: 36 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "Both pens use 24 meters of fence, but Nova's pen holds 36 square meters. Same perimeter, more area!",
    wrong: [
      { step: 1, value: 20, hint: "20 is the squares inside Kai's pen. That's area. Add the 4 sides: 10 + 2 + 10 + 2." },
      { step: 1, value: 12, hint: "10 + 2 = 12 is only 2 sides. Add the other 2 sides." },
      { step: 2, value: 36, hint: "36 is the squares inside. That's area. Add the 4 sides: 6 + 6 + 6 + 6." },
      { step: 2, value: 12, hint: "6 + 6 = 12 is only 2 sides. A square has 4 sides." },
      { step: 3, value: 24, hint: "24 is the fence around. Area counts the squares inside: 6 rows × 6 squares." },
      { step: 3, value: 12, hint: "6 + 6 = 12 adds sides. There are 6 rows with 6 squares in EACH row. Multiply." },
      { step: 4, choice: "b", hint: "Longer isn't always roomier. Compare the areas: 20 and 36." },
      { step: 4, choice: "c", hint: "Same fence doesn't mean same room. Compare the areas: 20 and 36." },
      { step: 4, choice: "d", hint: "A long side doesn't give more room. Compare the areas: 20 and 36." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Around or inside?", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "My job list is a mess! Some jobs go around the edge of a pen. Some jobs cover the inside. I need to know which is perimeter and which is area.",
    question: "Sort each job. Does it need perimeter or area?",
    hint: "Around the edge is perimeter, measured in meters. Covering the inside is area, measured in square meters.",
    meter: { supplies: 1, label: "Pens built +1", story: "Kai's job list is sorted" },
    discovery: { id: "anaconda", name: "Green anacondas", who: "Nova", fact: "Green anacondas live in rainforest rivers and swamps. They are the heaviest snakes on Earth." },
    answer: { kind: "sort", bins: { j1: "perim", j2: "area", j3: "perim", j4: "area", j5: "perim", j6: "area" } },
    rightFeedback: "Every job is sorted! Fences, ropes, and borders go around. Mats, tiles, and blankets cover the inside.",
    sort: {
      bins: [
        { id: "perim", label: "Perimeter (around the edge)" },
        { id: "area", label: "Area (covers the inside)" },
      ],
      items: [
        { id: "j1", label: "Fence to go around the tapir pen" },
        { id: "j2", label: "Grass mats to cover the capybara pen floor" },
        { id: "j3", label: "Rope to wrap around the parrot perch pen" },
        { id: "j4", label: "Square tiles to cover the tortoise shelter floor" },
        { id: "j5", label: "A row of plants along the edge of the sloth pen" },
        { id: "j6", label: "Leaf blankets to cover the nest-box floor" },
      ],
    },
    wrong: [
      { item: "j1", hint: "A fence goes around the edge. That's perimeter." },
      { item: "j2", hint: "Mats cover the whole floor. That's area." },
      { item: "j3", hint: "Rope that wraps around the pen follows the edge. That's perimeter." },
      { item: "j4", hint: "Tiles cover the inside of the floor. That's area." },
      { item: "j5", hint: "Plants along the edge follow the outside of the pen. That's perimeter." },
      { item: "j6", hint: "Blankets cover the floor inside. That's area." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The lost aviary side", machine: "Side Finder", icon: "water", speaker: "nova",
    line: "The new parrot aviary has 5 sides. Commander Vega used exactly 42 meters of fence. Rain smeared my note, and one side length washed away!",
    question: "What is the length of Side E?",
    unit: "meters",
    data: {
      title: "Parrot aviary · pentagon · perimeter 42 m",
      columns: ["Side", "Length"],
      rows: [
        ["Side A", "9 m"],
        ["Side B", "9 m"],
        ["Side C", "8 m"],
        ["Side D", "8 m"],
        ["Side E", "?"],
      ],
    },
    hint: "Add the 4 sides you know: 9 + 9 + 8 + 8. The whole fence is 42 meters. What is left for Side E?",
    meter: { heat: 5, label: "Pens ready +5%", story: "The aviary side is found" },
    answer: { kind: "number", value: 8 },
    rightFeedback: "9 + 9 + 8 + 8 = 34, and 42 − 34 = 8. Side E is 8 meters!",
    wrong: [
      { value: 34, hint: "34 is the 4 sides we know, added up. How much more makes 42?" },
      { value: 76, hint: "Don't add the perimeter to the sides. The 4 sides plus Side E must make 42. Subtract." },
      { value: 9, hint: "Check: 9 + 9 + 8 + 8 + 9 = 43, not 42. Try again." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Equal-side shortcuts", machine: "Fence Counter", icon: "dial", speaker: "kai",
    line: "Two pens have sides that are all the same length. There's a hexagon pen for the sloths with every side 8 meters. There's a square pen for the tortoise babies with 36 meters of fence.",
    question: "Part 1: What is the perimeter of the hexagon pen? Part 2: How long is each side of the square pen?",
    parts: [
      { type: "number", prompt: "The hexagon pen has 6 sides. Each side is 8 meters. What is its perimeter?", unit: "meters",
        data: {
          title: "Sloth pen · hexagon",
          columns: ["Side", "Length"],
          rows: [
            ["Side A", "8 m"],
            ["Side B", "8 m"],
            ["Side C", "8 m"],
            ["Side D", "8 m"],
            ["Side E", "8 m"],
            ["Side F", "8 m"],
          ],
        } },
      { type: "number", prompt: "The square pen has 4 equal sides and 36 meters of fence. How long is each side?", unit: "meters" },
    ],
    hint: "Hexagon: add 8 six times, or think 6 × 8. Square: 4 equal sides make 36. What number added 4 times makes 36?",
    meter: { heat: 5, label: "Pens ready +5%", story: "The equal-side pens are fenced" },
    discovery: { id: "slothturn", name: "Sloth necks", who: "Nova", fact: "Three-toed sloths have extra bones in their necks. They can turn their heads much farther than people can." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 48 }, { kind: "number", value: 9 }] },
    rightFeedback: "8 + 8 + 8 + 8 + 8 + 8 = 48 meters. And 9 + 9 + 9 + 9 = 36, so each square side is 9 meters!",
    wrong: [
      { step: 1, value: 14, hint: "6 + 8 = 14 adds the number of sides to one side. Add 8 for EACH of the 6 sides." },
      { step: 1, value: 40, hint: "That's only 5 sides of 8. A hexagon has 6 sides." },
      { step: 1, value: 32, hint: "That's only 4 sides of 8. A hexagon has 6 sides." },
      { step: 2, value: 32, hint: "36 − 4 = 32. The 36 meters is shared by 4 equal sides. What added 4 times makes 36?" },
      { step: 2, value: 18, hint: "18 is half of 36. That's 2 sides together. A square has 4 sides." },
      { step: 2, value: 6, hint: "Check: 6 + 6 + 6 + 6 = 24, not 36. Try a bigger side." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Fence and grass", machine: "Pen Planner", icon: "grid", speaker: "nova",
    line: "The tapir's new pen is 5 meters wide and 7 meters long. Kai is putting up the fence. I'm laying square grass mats, 1 meter on each side, to cover the floor.",
    question: "Part 1: How many meters of fence does Kai need? Part 2: How many square meters of grass do I need?",
    parts: [
      { type: "number", prompt: "How many meters of fence go around the pen?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 7, perimeter: true, sideLabels: { top: "7 m", left: "5 m" }, title: "Tapir's new pen" } },
      { type: "number", prompt: "How many square meters of grass cover the floor?", unit: "square meters" },
    ],
    hint: "Fence goes around: add the 4 sides. Grass covers the inside: 5 rows × 7 squares in each row.",
    meter: { supplies: 1, label: "Pens built +1", story: "The tapir's new pen is ready" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 24 }, { kind: "number", value: 35 }] },
    rightFeedback: "7 + 5 + 7 + 5 = 24 meters of fence, and 5 × 7 = 35 square meters of grass. Around and inside!",
    wrong: [
      { step: 1, value: 35, hint: "35 is the squares inside. That's the grass. Fence goes around: 7 + 5 + 7 + 5." },
      { step: 1, value: 12, hint: "7 + 5 = 12 is only 2 sides. Add the other 2 sides." },
      { step: 2, value: 24, hint: "24 is the fence around. Grass covers the inside: 5 rows × 7 squares." },
      { step: 2, value: 12, hint: "7 + 5 = 12 adds 2 sides. There are 5 rows with 7 squares in EACH row. Multiply." },
      { step: 2, value: 30, hint: "That's 5 rows of 6. Each row has 7 squares." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Release night", machine: "Pen Planner", icon: "relay", speaker: "vega",
    line: "This is it! Tonight the healed animals move to their big forest pens. Surprise! The tapir pen has to bend around a giant tree, so it's shaped like an L with 6 sides. We have 40 meters of fence.",
    question: "Part 1: What is the perimeter of the L-shaped pen? Part 2: How much fence is left? Part 3: A rectangle pen also has a 34-meter perimeter and long sides of 10 meters. How long is each short side? Part 4: Which pen has more room?",
    parts: [
      { type: "number", prompt: "Add all 6 sides. What is the perimeter of the L-shaped pen?", unit: "meters",
        data: {
          title: "Tapir forest pen · L shape",
          columns: ["Side", "Length"],
          rows: [
            ["Top", "10 m"],
            ["Right", "4 m"],
            ["Inner bottom", "6 m"],
            ["Inner side", "3 m"],
            ["Bottom", "4 m"],
            ["Left", "7 m"],
          ],
        } },
      { type: "number", prompt: "We have 40 meters of fence. How many meters are left after the L-shaped pen?", unit: "meters" },
      { type: "number", prompt: "A rectangle pen also has a perimeter of 34 meters. Its long sides are 10 meters each. How long is each short side?", unit: "meters" },
      { type: "choice", prompt: "The L-shaped pen is a 10 by 7 rectangle with a 6 by 3 corner cut out for the tree. The rectangle pen is 10 by 7. Which pen has more room inside?", choices: [
        { id: "a", text: "The rectangle pen. Both use 34 meters of fence, but the L is missing a corner, so it has less area." },
        { id: "b", text: "They have the same room, because they have the same perimeter." },
        { id: "c", text: "The L-shaped pen, because it has more sides." },
        { id: "d", text: "The L-shaped pen, because it bends around the tree." },
      ] },
    ],
    hint: "Add the 6 sides: 10 + 4 + 6 + 3 + 4 + 7. For the rectangle, the 2 long sides use 20 meters. Split the rest between the 2 short sides.",
    meter: { heat: 15, label: "Pens ready +15%", story: "The animals move to their forest pens on Solara" },
    discovery: { id: "tapirswim", name: "Tapir snorkels", who: "Kai", fact: "Tapirs are great swimmers. Their long, bendy nose can poke above the water like a snorkel." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 34 }, { kind: "number", value: 6 }, { kind: "number", value: 7 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "The L needs 34 meters, leaving 6. The rectangle's short sides are 7 meters. Same fence, but the rectangle has more room!",
    wrong: [
      { step: 1, value: 14, hint: "10 + 4 = 14 is only 2 sides. The L has 6 sides. Add all of them." },
      { step: 1, value: 27, hint: "It looks like one side is missing. Add all 6 rows of the table." },
      { step: 1, value: 70, hint: "10 × 7 is the space inside a full rectangle. Perimeter adds the 6 sides." },
      { step: 2, value: 34, hint: "34 meters is the fence we USED. How much of the 40 is left? Subtract." },
      { step: 2, value: 74, hint: "Don't add. We used 34 of the 40 meters. Subtract." },
      { step: 3, value: 24, hint: "34 − 10 = 24 takes away only one long side. There are 2 long sides." },
      { step: 3, value: 14, hint: "14 meters is BOTH short sides together. Split it between the 2 short sides." },
      { step: 4, choice: "b", hint: "Same fence doesn't mean same room. The L has a corner cut out." },
      { step: 4, choice: "c", hint: "More sides doesn't mean more room. The L is the rectangle with a corner cut out." },
      { step: 4, choice: "d", hint: "Bending around the tree cuts out a corner. Does that add room or take it away?" },
    ],
  },
};

export default {
  id: "MA.3.7B-XP",
  standard: "MA.3.7B-XP",
  engine: "expedition_station",
  title: "The Creature Pens",
  planet: "Solara",
  outpost: "Jungle Moon · animal rescue camp",
  grade: 3,
  subject: "Math",
  teks: "3.7B",
  supportingTeks: ["3.6C"],
  skillsChip: "3.7B · Find the perimeter of polygons",
  iCan: "I can find the perimeter of a polygon by adding all its side lengths, find a missing side when I know the perimeter, and tell perimeter apart from area.",
  blurb: "The crew runs an animal rescue camp in the jungle on Solara. They have to fence pens for capybaras, tapirs, sloths, tortoises, and parrots before the animals move to their forest homes.",
  mission: "Measure and fence every rescue pen, find missing sides, and give the animals the most room for release night.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.7B · SOLARA RESCUE CAMP",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Pens ready", heatUnit: "%", supplies: "Pens built", suppliesUnit: "pens" },
  journalMax: 10,
  grade3Limits: "Whole-number side lengths. Perimeters and missing sides within 100.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. We've opened an animal rescue camp on Solara.",
    "Every rescued animal needs a pen with a fence all the way around it.",
    "Help Kai and Nova measure the fences so no one wanders off. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Fence the first pens", "Act 2 · Fix the fences", "Act 3 · Release night"],
    completes: [
      "The first pens are fenced, {firstName}!",
      "The fences are fixed and the capybara family has room, {firstName}!",
      "Release night was a success, {firstName}! Every animal on Solara has a safe forest pen.",
    ],
    teasers: [
      "Next on Solara: more animals, missing sides, and a fence mix-up. Act 2 is open now, or come back to it next time.",
      "Next on Solara: release night is almost here. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The first pens are fenced, but some notes went missing.",
      "Kai keeps mixing up perimeter and area, so let's check his work together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Release night is coming.",
      "Help the crew sort the last jobs and plan the big forest pens.",
    ],
  }),
  tasks,
};
