// Expedition Station — The Crew Poems (ELA.4.9B-XP)
// Grade 4 · ELAR · Lumara (glowing garden). Main standard 4.9B (explain
// figurative language such as simile, metaphor, and personification that the
// poet uses to create images; poetry elements such as line, stanza, rhyme, and
// rhythm); also practices 4.10D (how imagery, literal and figurative language,
// and sound devices achieve specific purposes), 4.3B (context clues), 4.6F
// (inferences), 4.12A (compose a poem), and 4.11D (edit).
// All poems are original, written for this quest: the crew holds a poetry
// night in the Glow Garden, and a Lumaran gardener reads a poem too.
//
// Poem passages set `poem: true`. Each paragraph is a stanza and each
// "sentence" is one line, so ids like "B2.3" mean poem B, stanza 2, line 3.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "The Lantern Bugs", genre: "Poem by Nova (rhyming)", poem: true }, [
    [
      "The lantern bugs come out at night,",
      "like sparks that jumped from a campfire bright.",
      "They float above the flower beds,",
      "like tiny moons on silver threads.",
    ],
    [
      "Their wings hum soft as a whispered song,",
      "and the garden listens all night long.",
      "When morning comes, they dim and fade,",
      "and sleep beneath the leafy shade.",
    ],
  ]),
  B: passage("B", { title: "Night Shift", genre: "Poem by Kai (free verse)", poem: true }, [
    [
      "The glow garden is a busy city at night.",
      "The fern-lamps are streetlights.",
      "Beetles are buses, humming down the stem roads.",
    ],
    [
      "Up high, the moon is a silver lantern",
      "hanging over the leafy rooftops.",
      "And me?",
      "I am the night guard, counting every light.",
    ],
  ]),
  C: passage("C", { title: "Evening Watch", genre: "Poem by Commander Vega", poem: true }, [
    [
      "At dusk, the old glowtree stretches her arms.",
      "She yawns, and her leaves wake up, one by one.",
      "The breeze whispers the news of the day to her.",
    ],
    [
      "The flowers nod good night to the setting sun.",
      "The path glows green beneath my boots.",
      "I walk home slowly with my hands in my pockets.",
    ],
  ]),
  D: passage("D", { title: "Harvest Song", genre: "Poem by Gardener Oreli of Lumara", poem: true }, [
    [
      "My garden is a quilt of light,",
      "stitched with rows of blue and gold.",
      "The sweet smell of moonmelons drifts over the fence.",
    ],
    [
      "The honey-moths are busy as bakers,",
      "dusting every flower with yellow pollen.",
      "Crunchy leaves snap and crackle under my feet.",
    ],
    [
      "Tomorrow we will pick and share,",
      "and the garden will sing its thank-you song.",
    ],
  ]),
  E: {
    id: "E",
    title: "Kai's card for the Poem Wall",
    genre: "Note (has mistakes)",
    ...editText(
      "E",
      "Our crew came to Lumara for {are} first poetry night. Nova's lantern bugs {glows} like sparks. The old glowtree {stretch} her arms at dusk. {i} will never forget this garden.",
      {
        are: ["our", "hour"],
        glows: ["glow", "glowing"],
        stretch: ["stretches", "stretching"],
        i: ["I", "eye"],
      }
    ),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Count the stanzas", machine: "Poem Scanner", icon: "scan", speaker: "nova", passage: ["A"],
    line: "I'm reading first tonight! Before I start, can you check how my poem is built? I always mix up lines and stanzas.",
    question: "Read Nova's poem, \"The Lantern Bugs.\" How is the poem built?",
    hint: "A line is one row of words in a poem. A stanza is a group of lines, like a paragraph in a story.",
    meter: { heat: 10, label: "Stage lights +10%", story: "The first stage lantern flickers on" },
    discovery: { id: "dragonfly", name: "Dragonflies", who: "Nova", fact: "Dragonflies can fly forward, backward, and even hover in one spot, like tiny helicopters." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "2 stanzas, with 4 lines in each stanza" },
      { id: "b", text: "8 stanzas, with 1 line in each stanza" },
      { id: "c", text: "4 stanzas, with 2 lines in each stanza" },
      { id: "d", text: "1 stanza, with 8 lines in it" },
    ],
    rightFeedback: "Right! Nova's poem has 2 stanzas, and each stanza has 4 lines.",
    wrong: [
      { choice: "b", hint: "Each row is one line. A stanza is a GROUP of lines. How many groups are there?" },
      { choice: "c", hint: "Look for the space between groups of lines. How many lines are in each group?" },
      { choice: "d", hint: "There is a break in the middle of the poem. That break splits it into more than one stanza." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Spot the simile", machine: "Poem Scanner", icon: "scan", speaker: "kai", passage: ["A"],
    line: "Nova says her first stanza has a simile in it. My scanner is ready. Point it at the right line!",
    question: "Highlight a line in stanza 1 that uses a simile.",
    hint: "A simile compares two different things using the word \"like\" or \"as.\"",
    meter: { heat: 10, label: "Stage lights +10%", story: "Kai's scanner beeps" },
    discovery: { id: "cricketears", name: "Cricket ears", who: "Kai", fact: "Crickets hear with ears on their front legs, just below the knees." },
    answer: { kind: "highlight", groups: [["A1.2", "A1.4"]] },
    rightFeedback: "Got it! The bugs are compared to sparks and to tiny moons, using the word \"like.\"",
    wrong: [
      { sentence: "A1.1", hint: "That line tells when the bugs come out. Does it compare them to something else using like or as?" },
      { sentence: "A1.3", hint: "That line tells where the bugs float. Look for a line with the word \"like.\"" },
      { sentence: "A2.1", hint: "That IS a simile, but it's in stanza 2. Find one in stanza 1." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Rhyme time", machine: "Echo Finder", icon: "static", speaker: "vega", passage: ["A"],
    line: "Nova's poem has a nice bounce to it. I think it's the rhyming words at the ends of the lines.",
    question: "Which word pairs from Nova's poem rhyme? Pick every one.",
    hint: "Rhyming words end with the same sound, like cat and hat. Look at the last word of each line.",
    meter: { supplies: 1, label: "Poem cards +1", story: "Vega writes the rhymes on a poem card" },
    answer: { kind: "multi", correct: ["a", "b", "c", "d"] },
    items: [
      { id: "a", text: "night / bright" },
      { id: "b", text: "beds / threads" },
      { id: "c", text: "song / long" },
      { id: "d", text: "fade / shade" },
      { id: "e", text: "bugs / beds" },
      { id: "f", text: "night / song" },
    ],
    rightFeedback: "Yes! Every two lines in Nova's poem end with a rhyming pair.",
    wrong: [
      { pick: "e", hint: "Bugs and beds START with the same sound, but they don't END with the same sound. That's not a rhyme." },
      { pick: "f", hint: "Say night and song out loud. Do they end with the same sound?" },
      { missing: true, hint: "There are more rhyming pairs. Check the last words of all 8 lines." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Sparks in the dark", machine: "Picture Maker", icon: "crew", speaker: "nova", passage: ["A"],
    line: "My favorite line is \"like sparks that jumped from a campfire bright.\" Can you see what I was picturing?",
    question: "\"The lantern bugs come out at night, like sparks that jumped from a campfire bright.\" What picture does this simile create?",
    hint: "Think about what sparks from a campfire look like. How big are they? How do they move?",
    meter: { heat: 10, label: "Stage lights +10%", story: "The crowd of Lumarans claps" },
    discovery: { id: "spiders", name: "Spiders", who: "Nova", fact: "Spiders are not insects. Spiders have eight legs, and insects have six." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Small, bright lights popping and drifting up into the dark" },
      { id: "b", text: "The garden is on fire." },
      { id: "c", text: "The bugs are hot enough to burn you." },
      { id: "d", text: "The bugs are big and brown, like logs." },
    ],
    rightFeedback: "That's it! Sparks are tiny, bright, and float up, just like the lantern bugs.",
    wrong: [
      { choice: "b", hint: "A simile doesn't mean it really happens. What do sparks and the bugs have in common?" },
      { choice: "c", hint: "Nova isn't talking about heat. What do sparks LOOK like in the dark?" },
      { choice: "d", hint: "The bugs are compared to sparks, not logs. What do sparks look like?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The bugs want answers", machine: "Stage Crowd", icon: "snap", speaker: "vega", passage: ["A"],
    line: "Surprise! As Nova finishes, every lantern bug in the garden lands on the stage. The Lumarans say that means the bugs want to hear the poem explained!",
    question: "Part 1: Highlight the line where the garden does something only a person could do. Part 2: What does that line help you picture? Part 3: Why did Nova end the poem with the bugs dimming and sleeping?",
    parts: [
      { type: "highlight", prompt: "Highlight the line where the garden acts like a person.", passage: "A" },
      { type: "choice", prompt: "What does \"the garden listens all night long\" help you picture?", choices: [
        { id: "a", text: "The garden is so quiet and still that it seems to be enjoying the song." },
        { id: "b", text: "The plants in the garden have ears." },
        { id: "c", text: "The garden is loud and noisy all night." },
        { id: "d", text: "Nobody ever comes to the garden at night." },
      ] },
      { type: "choice", prompt: "Why did Nova end her poem with the bugs dimming and sleeping?", choices: [
        { id: "a", text: "To show the night is over and give the poem a calm, quiet ending" },
        { id: "b", text: "To show that the bugs are sick" },
        { id: "c", text: "To teach readers how to catch lantern bugs" },
        { id: "d", text: "To make the word \"fade\" rhyme with \"night\"" },
      ] },
    ],
    hint: "Personification gives a human action to something that isn't a person. Then think about how the poem moves from night to morning.",
    meter: { heat: 15, label: "Stage lights +15%", story: "The lantern bugs rise and light up the stage" },
    discovery: { id: "sensitiveplant", name: "The sensitive plant", who: "Kai", fact: "A plant called the sensitive plant folds up its leaves when you touch it. After a few minutes, the leaves open again." },
    answer: { kind: "parts", parts: [
      { kind: "highlight", groups: [["A2.2"]] },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The lantern bugs rise into the air and light up the whole stage! You explained Nova's poem.",
    wrong: [
      { step: 1, sentence: "A2.1", hint: "That line compares the bugs' wings to a song. Which line gives the GARDEN a human action?" },
      { step: 1, sentence: "A2.4", hint: "Bugs really can rest in the shade. Which line makes the garden do something only people do?" },
      { step: 1, sentence: "A1.3", hint: "That line tells where the bugs float. Look in stanza 2 for the garden." },
      { step: 2, choice: "b", hint: "Personification doesn't mean the plants really have ears. What does it feel like when someone listens quietly?" },
      { step: 2, choice: "c", hint: "When you listen, are you loud or quiet? What does that tell you about the garden?" },
      { step: 2, choice: "d", hint: "The poem doesn't say that. Think about what \"listens\" tells you about how the garden feels." },
      { step: 3, choice: "b", hint: "Nothing in the poem says the bugs are sick. What time of day is it at the end?" },
      { step: 3, choice: "c", hint: "The poem doesn't give steps or directions. How does the ending make you feel?" },
      { step: 3, choice: "d", hint: "Fade rhymes with shade, not night. Think about what happens when morning comes." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Sort the sparkles", machine: "Poem Sorter", icon: "cells", speaker: "kai", passage: ["A", "B", "C"],
    line: "I built a sorter with three glowing bins. Now I need someone who knows their figurative language to load it.",
    question: "Sort each line: is it a simile, a metaphor, or personification?",
    hint: "Simile: compares with like or as. Metaphor: says one thing IS another. Personification: gives a human action to something that isn't a person.",
    meter: { supplies: 1, label: "Poem cards +1", story: "Kai's sorter glows in three colors" },
    discovery: { id: "ladybugs", name: "Ladybugs", who: "Nova", fact: "Ladybugs eat tiny bugs called aphids. One ladybug can eat thousands of aphids in its life, which helps protect garden plants." },
    answer: { kind: "sort", bins: { s1: "simile", s2: "metaphor", s3: "personification", s4: "simile", s5: "metaphor", s6: "personification" } },
    rightFeedback: "Sorted! Similes use like or as, metaphors say one thing IS another, and personification makes things act like people.",
    sort: {
      bins: [
        { id: "simile", label: "Simile" },
        { id: "metaphor", label: "Metaphor" },
        { id: "personification", label: "Personification" },
      ],
      items: [
        { id: "s1", label: "like tiny moons on silver threads" },
        { id: "s2", label: "the moon is a silver lantern" },
        { id: "s3", label: "She yawns, and her leaves wake up" },
        { id: "s4", label: "Their wings hum soft as a whispered song" },
        { id: "s5", label: "The fern-lamps are streetlights." },
        { id: "s6", label: "The flowers nod good night to the setting sun." },
      ],
    },
    wrong: [
      { item: "s4", hint: "Look for the word \"as\" in that line. A comparison with like or as is a simile." },
      { item: "s2", hint: "There's no like or as. The line says the moon IS a lantern. What is that called?" },
      { item: "s5", hint: "The line says fern-lamps ARE streetlights, with no like or as. That's a metaphor." },
      { item: "s6", hint: "Can flowers really say good night? That's a human action. What is that called?" },
      { item: "s1", hint: "That line uses the word \"like\" to compare the bugs to moons." },
      { item: "s3", hint: "Trees can't really yawn. Giving a human action to a thing is personification." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The yawning tree", machine: "Poem Scanner", icon: "scan", speaker: "vega", passage: ["C"],
    line: "My poem is about the garden waking up at dusk. I made the plants act a little like people.",
    question: "Highlight one line from stanza 1 and one line from stanza 2 where something in nature acts like a person.",
    hint: "Look for plants or wind doing things that only people really do, like yawning, whispering, or saying good night.",
    meter: { heat: 10, label: "Stage lights +10%", story: "Vega takes a bow" },
    answer: { kind: "highlight", groups: [["C1.1", "C1.2", "C1.3"], ["C2.1"]] },
    rightFeedback: "Yes! Trees don't yawn and flowers don't say good night. Vega used personification.",
    wrong: [
      { sentence: "C2.2", hint: "In the Glow Garden, the path really does glow. Is anything acting like a person in that line?" },
      { sentence: "C2.3", hint: "Vega IS a person, so walking home is not personification. Find a line where a plant acts like a person." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Is the moon a lantern?", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["B"],
    line: "Kai: \"My poem says the moon is a silver lantern. So on Lumara, the moon really IS a lantern!\"",
    nova: "Nova: \"No, Kai. That's a metaphor. You compared the moon to a lantern to make a picture.\"",
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "A metaphor compares two different things. Does comparing change what something really is?",
    meter: { heat: 10, label: "Stage lights +10%", story: "The crowd laughs, and Kai laughs too" },
    discovery: { id: "moonphases", name: "Moon shapes", who: "Nova", fact: "The Moon looks like it changes shape during the month, but it is always round. We just see different amounts of its sunny side." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A metaphor compares two different things to create a picture. The moon glows and hangs in the sky like a lantern, but it is still a moon." },
      { id: "B", text: "Nova, because a metaphor always uses the word \"like\" or \"as.\"" },
      { id: "C", text: "Kai. Poems always tell exactly what is real." },
      { id: "D", text: "Kai. Lumara is a different planet, so its moon can be a lantern." },
    ],
    writtenPrompt: "Tell Kai in your own words what his metaphor really means.",
    debateHints: {
      wrongWho: "Does the poem say the moon IS a lantern to be true, or to help us picture how it looks?",
      wrongReason: "Right person, check the reason. Similes use like or as. What does a metaphor do?",
      right: "Nova is right. The moon isn't really a lantern. Kai's metaphor helps us picture it glowing and hanging in the sky.",
    },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Kai's label mix-up", machine: "Card Repair", icon: "log", speaker: "kai", passage: ["A"],
    line: "I made a poem card for Nova's poem. It says: METAPHOR: \"Their wings hum soft as a whispered song.\" Nova just raised one eyebrow at me.",
    question: "Part 1: What did Kai get wrong? Part 2: Kai wants a real metaphor. Which rewrite IS a metaphor?",
    parts: [
      { type: "choice", prompt: "What did Kai get wrong?", choices: [
        { id: "a", text: "The line uses \"as\" to compare, so it is a simile, not a metaphor." },
        { id: "b", text: "The line doesn't compare anything at all." },
        { id: "c", text: "It's personification, because wings are body parts." },
        { id: "d", text: "Kai spelled \"whispered\" wrong." },
      ] },
      { type: "choice", prompt: "Which rewrite is a metaphor?", choices: [
        { id: "a", text: "Their wings are a whispered song." },
        { id: "b", text: "Their wings hum like a whispered song." },
        { id: "c", text: "Their wings hum very quietly." },
        { id: "d", text: "Their wings whisper secrets to the flowers." },
      ] },
    ],
    hint: "Similes use like or as. A metaphor says one thing IS another thing.",
    meter: { supplies: 1, label: "Poem cards +1", story: "Kai fixes his poem card" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Card fixed! \"Soft as a song\" is a simile. \"Their wings are a whispered song\" is a metaphor.",
    wrong: [
      { step: 1, choice: "b", hint: "The line compares the sound of the wings to a song. Which word shows the comparison?" },
      { step: 1, choice: "c", hint: "Bugs really do have wings, and wings really can hum. Look at the word \"as.\"" },
      { step: 1, choice: "d", hint: "The spelling is fine. Think about the kind of comparison the line makes." },
      { step: 2, choice: "b", hint: "That still uses \"like,\" so it's still a simile. Which one says the wings ARE a song?" },
      { step: 2, choice: "c", hint: "That doesn't compare the wings to anything. A metaphor needs a comparison." },
      { step: 2, choice: "d", hint: "Wings whispering secrets is a human action. That's personification, not a metaphor." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Lights out on stage", machine: "Judges' Table", icon: "quake", speaker: "vega", passage: ["B", "A"],
    line: "Surprise! The power cell for the stage lights just popped. While Kai fixes it in the dark, the Lumaran judges want the crowd to talk about Kai's poem.",
    question: "Part 1: How is Kai's poem different from Nova's? Part 2: Highlight the line where Kai compares the WHOLE garden to something. Part 3: What picture does that metaphor create?",
    parts: [
      { type: "choice", prompt: "How is Kai's poem different from Nova's?", choices: [
        { id: "a", text: "Nova's poem rhymes and has a steady beat. Kai's poem is free verse, with no rhyme and lines of different lengths." },
        { id: "b", text: "Kai's poem rhymes, but Nova's poem does not." },
        { id: "c", text: "Kai's poem has no stanzas at all." },
        { id: "d", text: "Nova's poem has no comparisons in it." },
      ] },
      { type: "highlight", prompt: "Highlight the line where Kai compares the whole garden to something.", passage: "B" },
      { type: "choice", prompt: "What picture does \"The glow garden is a busy city at night\" create?", choices: [
        { id: "a", text: "A garden full of lights and bugs moving everywhere, like a city that stays awake" },
        { id: "b", text: "A garden with tall buildings made of bricks" },
        { id: "c", text: "An empty, dark garden where nothing moves" },
        { id: "d", text: "A garden that is being turned into roads" },
      ] },
    ],
    hint: "Read both poems out loud. Listen for rhyme and a steady beat. Then find where Kai says the garden IS something.",
    meter: { heat: 15, label: "Stage lights +15%", story: "Kai gets the stage lights back on" },
    discovery: { id: "monarchs", name: "Monarch butterflies", who: "Kai", fact: "Some monarch butterflies fly up to 3,000 miles to spend the winter somewhere warm." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B1.1"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The lights blink back on! Kai's free-verse poem turns the whole garden into a busy city.",
    wrong: [
      { step: 1, choice: "b", hint: "Check the ends of the lines. Which poem has night / bright and song / long?" },
      { step: 1, choice: "c", hint: "Kai's poem has a break in the middle, so it has 2 stanzas. Listen for rhyme instead." },
      { step: 1, choice: "d", hint: "Nova's poem has similes, like \"like tiny moons.\" Think about rhyme and beat." },
      { step: 2, sentence: "B1.2", hint: "That compares just the fern-lamps. Which line is about the WHOLE garden?" },
      { step: 2, sentence: "B2.1", hint: "That compares the moon to a lantern. Find the line about the whole garden." },
      { step: 2, sentence: "B2.4", hint: "That line is about Kai himself. Which line says the garden IS something?" },
      { step: 3, choice: "b", hint: "A metaphor doesn't mean the garden really has buildings. What is a busy city like at night?" },
      { step: 3, choice: "c", hint: "Kai said BUSY city. Is a busy city empty and still?" },
      { step: 3, choice: "d", hint: "Nothing is being built. What does a city at night look and feel like?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Smell it, hear it", machine: "Sense Detector", icon: "scan", speaker: "nova", passage: ["D"],
    line: "Gardener Oreli's poem makes me feel like I'm standing in her garden. I think she used imagery for more than just seeing.",
    question: "Highlight one line that helps you SMELL the garden and one line that helps you HEAR it.",
    hint: "Imagery uses words that help you see, hear, smell, taste, or feel. Look for sound words and smell words.",
    meter: { heat: 10, label: "Stage lights +10%", story: "Nova sniffs the moonmelon air" },
    discovery: { id: "dew", name: "Dew", who: "Nova", fact: "Dew forms at night when the air cools. Water vapor in the air turns into tiny drops on grass and leaves." },
    answer: { kind: "highlight", groups: [["D1.3"], ["D2.3"]] },
    rightFeedback: "Yes! You can smell the sweet moonmelons and hear the leaves snap and crackle.",
    wrong: [
      { sentence: "D1.1", hint: "That metaphor helps you SEE the garden. Find a line about a smell and one about a sound." },
      { sentence: "D2.2", hint: "Yellow pollen is something you see. Look for words like smell, snap, or crackle." },
      { sentence: "D3.1", hint: "That line tells a plan for tomorrow. Which lines use smell and sound words?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Busy as bakers", machine: "Word Lens", icon: "static", speaker: "kai", passage: ["D"],
    line: "The honey-moths are \"dusting\" the flowers? I thought dusting meant cleaning. That's what I do to my tools!",
    question: "\"The honey-moths are busy as bakers, dusting every flower with yellow pollen.\" What does \"dusting\" mean in this line?",
    hint: "Think about the simile. What does a baker do with flour? Then look at what the moths leave on the flowers.",
    meter: { supplies: 1, label: "Poem cards +1", story: "Kai adds a new word to his card" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Sprinkling lightly with a fine powder" },
      { id: "b", text: "Wiping away dirt with a cloth" },
      { id: "c", text: "Eating every bit of something" },
      { id: "d", text: "Painting with thick stripes" },
    ],
    rightFeedback: "Right! Bakers dust cakes with flour, and the moths dust flowers with pollen.",
    wrong: [
      { choice: "b", hint: "That's one meaning of dusting, but the moths are ADDING yellow pollen. What do bakers dust with?" },
      { choice: "c", hint: "The line says the moths dust flowers WITH pollen. Are they eating it or spreading it?" },
      { choice: "d", hint: "Pollen is a fine powder, not paint. How would a baker put a little flour on top of a cake?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "A quilt of light", machine: "Picture Maker", icon: "crew", speaker: "vega", passage: ["D"],
    line: "Gardener Oreli could have written \"My garden has lots of lights.\" She wrote \"My garden is a quilt of light\" instead. I want to know why.",
    question: "Why did Oreli call her garden \"a quilt of light\"? Pick every reason that fits.",
    hint: "Picture a quilt. What does it look like? How does it feel? Who makes it?",
    meter: { supplies: 1, label: "Poem cards +1", story: "Vega pins Oreli's line to the Poem Wall" },
    discovery: { id: "tulips", name: "Tulips", who: "Kai", fact: "Tulips close their petals at night and open them again in the morning." },
    answer: { kind: "multi", correct: ["a", "b"] },
    items: [
      { id: "a", text: "It helps you picture rows of different colors fitting together like quilt patches." },
      { id: "b", text: "It makes the garden feel cozy and cared for, like a quilt someone made by hand." },
      { id: "c", text: "It tells you the garden is really made of cloth." },
      { id: "d", text: "It tells you exactly how many plants are in the garden." },
    ],
    rightFeedback: "Yes! The metaphor shows the colorful rows AND makes the garden feel warm and loved.",
    wrong: [
      { pick: "c", hint: "A metaphor compares. It doesn't mean the garden is really cloth." },
      { pick: "d", hint: "The line doesn't give any numbers. What does a quilt help you picture?" },
      { missing: true, hint: "There is more than one reason. Think about how a quilt LOOKS and how it FEELS." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The thank-you song", machine: "Meaning Finder", icon: "brief", speaker: "nova", passage: ["D"],
    line: "Oreli's last line gave me goosebumps. \"The garden will sing its thank-you song.\" But gardens can't sing. So what does she mean?",
    question: "What does Oreli most likely mean by \"the garden will sing its thank-you song\"?",
    hint: "Read the line just before it. What will the people do tomorrow? How might the garden seem to feel about that?",
    meter: { heat: 10, label: "Stage lights +10%", story: "The crowd hums along" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "The plants will open their mouths and really sing." },
      { id: "b", text: "When everyone picks and shares the harvest, the garden will seem happy and full of joyful sounds." },
      { id: "c", text: "The garden is too loud for people to sleep." },
      { id: "d", text: "Oreli will sing a song by herself tomorrow." },
    ],
    rightFeedback: "Right! The garden can't really sing, but sharing the harvest will make it feel joyful and thankful.",
    wrong: [
      { choice: "a", hint: "That's reading the line literally. Personification gives the garden a human action to show a feeling." },
      { choice: "c", hint: "Nothing in the poem says the garden is too loud. Look at the line about picking and sharing." },
      { choice: "d", hint: "The line says the GARDEN will sing, not Oreli. What feeling does a thank-you song show?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The Poem Wall", machine: "Poem Wall", icon: "relay", speaker: "vega", passage: ["E", "D"],
    line: "Surprise! The moon is setting, and the lantern bugs are gathering on the Poem Wall. Gardener Oreli says every guest must add a poem before the last light fades. That means you too!",
    question: "Part 1: Fix the 4 mistakes on Kai's Poem Wall card. Part 2: Pick the line that is a metaphor. Part 3: Write 2–3 lines of your own garden poem using a simile or a metaphor.",
    parts: [
      { type: "edit", prompt: "Fix the 4 mistakes on Kai's card.", passage: "E" },
      { type: "choice", prompt: "Which line would be the best METAPHOR to start a garden poem?", choices: [
        { id: "a", text: "The glow garden is a treasure chest of light." },
        { id: "b", text: "The glow garden shines like a treasure chest." },
        { id: "c", text: "The glow garden has many lights." },
        { id: "d", text: "The glow garden hums a happy tune." },
      ] },
      { type: "write", prompt: "Write 2–3 lines of your own poem about the Glow Garden. Use at least one simile or metaphor.", minWords: 12 },
    ],
    teacherScoredPart: 3,
    rubric: ["Writes 2–3 lines of poetry about the garden", "Uses a simile (like or as) or a metaphor (is, are)", "The comparison creates a clear picture"],
    hint: "For your poem: pick something in the garden. What does it look or sound like? Compare it with like or as, or say it IS something else.",
    meter: { heat: 15, label: "Stage lights +15%", story: "Your poem glows on the Poem Wall" },
    discovery: { id: "snails", name: "Garden snails", who: "Nova", fact: "Garden snails make a slimy trail that helps them glide over rough ground. They are most active at night and on rainy days." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "E:are": "our", "E:glows": "glow", "E:stretch": "stretches", "E:i": "I" } },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 12 },
    ] },
    rightFeedback: "Your poem is on the Poem Wall, and the lantern bugs light it up! Your teacher will read what you wrote.",
    wrong: [
      { step: 1, token: "E:are", hint: "The poetry night belongs to the crew. Which word shows that something belongs to us?" },
      { step: 1, token: "E:glows", hint: "There are many bugs. Do we say \"the bugs glows\" or \"the bugs glow\"?" },
      { step: 1, token: "E:stretch", hint: "There is one tree. Do we say \"the tree stretch\" or \"the tree stretches\"?" },
      { step: 1, token: "E:i", hint: "When you write about yourself, how do you always write the word I?" },
      { step: 2, choice: "b", hint: "That line uses \"like,\" so it's a simile. Which one says the garden IS something?" },
      { step: 2, choice: "c", hint: "That line doesn't compare the garden to anything. A metaphor needs a comparison." },
      { step: 2, choice: "d", hint: "Humming a tune is a human action. That's personification, not a metaphor." },
    ],
  },
};

export default {
  id: "ELA.4.9B-XP",
  standard: "ELA.4.9B-XP",
  engine: "expedition_station",
  title: "The Crew Poems",
  planet: "Lumara",
  outpost: "Glow Garden · poetry night",
  grade: 4,
  subject: "ELAR",
  teks: "4.9B",
  supportingTeks: ["4.10D", "4.3B", "4.6F", "4.12A", "4.11D"],
  skillsChip: "4.9B · Explain figurative language in poems",
  iCan: "I can find similes, metaphors, and personification in a poem and explain the picture they create. I can tell lines, stanzas, and rhymes apart.",
  blurb: "On Lumara, the crew holds a poetry night in the Glow Garden. Nova, Kai, Vega, and a Lumaran gardener each read a poem full of glowing bugs, yawning trees, and moons that look like lanterns.",
  mission: "Explain the similes, metaphors, and personification in the crew's poems, then add a poem of your own to the Poem Wall.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.9B · LUMARA GLOW GARDEN",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Stage lights", heatUnit: "%", supplies: "Poem cards", suppliesUnit: "cards" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega in the Glow Garden on Lumara.",
    "Tonight the Lumarans invited our crew to poetry night. Each of us wrote a poem, and so did Gardener Oreli.",
    "The Lumarans say a poem isn't finished until someone explains the pictures it paints. Help us do that. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Nova's lantern bugs", "Act 2 · Kai's night city", "Act 3 · The Poem Wall"],
    completes: [
      "The lantern bugs lit up the stage, {firstName}! You explained Nova's poem.",
      "The stage lights are back on, {firstName}. The judges loved Kai's night city.",
      "Your poem glows on the Poem Wall, {firstName}! Poetry night was a success.",
    ],
    teasers: [
      "Next on Lumara: Kai and Commander Vega read their poems. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: Gardener Oreli reads her harvest poem, and the Poem Wall is waiting. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Kai here. It's my turn on stage, and I'm a little nervous.",
      "My poem doesn't rhyme at all. Commander Vega's poem is next. Let's listen closely.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Gardener Oreli is reading the last poem of the night.",
      "After that, every guest adds a poem to the Poem Wall. Get your best comparisons ready.",
    ],
  }),
  tasks,
};
