// Expedition Station — The Crystal Count (MA.3.2A-XP)
// Grade 3 · Math · Frostveil. Main standard 3.2A (compose and decompose
// numbers up to 100,000 with objects, pictures, numbers, and expanded
// notation); also practices 3.2B (base-10 place value relationships) and
// 3.2C (a number between two multiples of 10, 100, 1,000; rounding).
// Most numbers stay in the hundreds and thousands so the base-ten blocks can
// show them; ten thousands appear as numbers and expanded notation.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Bundle the loose crystals", machine: "Crystal Bundler", icon: "cells", speaker: "kai",
    line: "The cave floor is covered in ice crystals! The supply log says we collected 263. Crystals go in bundles: 10 loose crystals make a rod, and 10 rods make a flat.",
    question: "Build 263 with the crystal bundles.",
    hint: "The 2 is in the hundreds place, the 6 is in the tens place, and the 3 is in the ones place. How many flats, rods, and loose crystals is that?",
    meter: { heat: 10, label: "Log complete +10%", story: "The first crystals are bundled" },
    discovery: { id: "icehotel", name: "The ice hotel", who: "Nova", fact: "In Sweden, a hotel is built out of snow and ice every winter. In spring, it melts away." },
    visual: { type: "blocks", places: ["hundreds", "tens", "ones"], title: "Crystal bundles" },
    answer: { kind: "number", value: 263 },
    rightFeedback: "2 flats, 6 rods, and 3 loose crystals make 263!",
    wrong: [
      { value: 236, hint: "Check the tens and ones. 263 has 6 tens and 3 ones, not 3 tens and 6 ones." },
      { value: 623, hint: "The 2 is in the hundreds place. How many flats do you need?" },
      { value: 362, hint: "Read 263 from left to right. The first digit tells how many hundreds." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Read the crate shelf", machine: "Supply Log", icon: "log", speaker: "nova",
    line: "A big crate holds 1,000 crystals. On this shelf there is 1 crate, 3 flats, no rods, and 5 loose crystals.",
    question: "How many crystals are on the shelf? Type the number for the supply log.",
    hint: "Count each place: thousands, hundreds, tens, ones. There are no tens, so what digit goes in the tens place?",
    meter: { heat: 5, label: "Log complete +5%", story: "The crate shelf is logged" },
    discovery: { id: "baker", name: "Snowiest winter", who: "Kai", fact: "Mount Baker in Washington State got about 1,140 inches of snow in one winter. That's a world record!" },
    visual: { type: "blocks", mode: "show", places: ["thousands", "hundreds", "tens", "ones"], counts: { thousands: 1, hundreds: 3, tens: 0, ones: 5 }, title: "Crate shelf" },
    answer: { kind: "number", value: 1305 },
    rightFeedback: "1 thousand, 3 hundreds, 0 tens, 5 ones is 1,305!",
    wrong: [
      { value: 135, hint: "There are no rods, but the tens place still needs a 0. Otherwise the 1 moves out of the thousands place." },
      { value: 1350, hint: "The 5 is loose crystals, so it goes in the ones place. What goes in the tens place?" },
      { value: 1035, hint: "Count the flats again. There are 3 hundreds and 0 tens." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The messy pile", machine: "Crystal Bundler", icon: "cells", speaker: "kai",
    line: "Oops, I forgot to bundle some! This pile has 2 flats, 3 rods, and 14 loose crystals.",
    question: "How many crystals are in the pile?",
    hint: "14 loose crystals is more than 10. Bundle 10 of them into a rod. Now how many rods and loose crystals are there?",
    meter: { heat: 5, label: "Log complete +5%", story: "The messy pile is bundled" },
    discovery: { id: "narwhal", name: "Narwhals", who: "Nova", fact: "A narwhal's long tusk is really a tooth. It grows out through the whale's upper lip." },
    visual: { type: "blocks", mode: "show", places: ["hundreds", "tens", "ones"], counts: { hundreds: 2, tens: 3, ones: 14 }, title: "Kai's pile" },
    answer: { kind: "number", value: 244 },
    rightFeedback: "14 ones is 1 ten and 4 ones. So the pile is 2 hundreds, 4 tens, 4 ones: 244!",
    wrong: [
      { value: 2314, hint: "You can't write 14 in the ones place. Only one digit fits there. Bundle 10 ones into a rod first." },
      { value: 234, hint: "Don't lose the extra ten! 14 ones is 1 ten and 4 ones." },
      { value: 334, hint: "10 ones make 1 ten, not 1 hundred. Which place gets the new bundle?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Stretch the number", machine: "Supply Log", icon: "log", speaker: "nova",
    line: "The log needs every number written in expanded form, too. That shows what each digit is worth. Today's count is 4,527.",
    question: "Which is 4,527 in expanded form?",
    hint: "Write the value of each digit. The 4 is in the thousands place, so it is worth 4,000.",
    meter: { supplies: 1, label: "Crates +1", story: "The first crate is packed" },
    choices: [
      { id: "a", text: "4,000 + 500 + 20 + 7" },
      { id: "b", text: "4 + 5 + 2 + 7" },
      { id: "c", text: "400 + 500 + 20 + 7" },
      { id: "d", text: "4,000 + 50 + 2 + 7" },
    ],
    answer: { kind: "choice", correct: "a" },
    rightFeedback: "4,000 + 500 + 20 + 7 = 4,527. Each part shows what its digit is worth.",
    wrong: [
      { choice: "b", hint: "Those are just the digits. Expanded form shows what each digit is worth. What is the 4 worth?" },
      { choice: "c", hint: "The 4 is in the thousands place. Is it worth 400 or 4,000?" },
      { choice: "d", hint: "Look at the 5 and the 2. The 5 is in the hundreds place, and the 2 is in the tens place." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The rod avalanche", machine: "Crystal Bundler", icon: "snap", speaker: "vega",
    line: "Surprise, a rod avalanche! The bundler jammed and dumped 23 rods in one heap. Then Nova found 17 more loose crystals.",
    question: "Part 1: How many crystals are in 23 rods? Part 2: Which is the same as 23 tens? Part 3: Add the 17 loose crystals and build the new total with the fewest blocks.",
    parts: [
      { type: "number", prompt: "Each rod is 10 crystals. How many crystals are in 23 rods?", visual: { type: "blocks", mode: "show", places: ["hundreds", "tens", "ones"], counts: { hundreds: 0, tens: 23, ones: 0 }, title: "The rod heap" } },
      { type: "choice", prompt: "Which is the same as 23 tens?", choices: [
        { id: "a", text: "2 hundreds 3 tens" },
        { id: "b", text: "2 thousands 3 hundreds" },
        { id: "c", text: "23 hundreds" },
        { id: "d", text: "3 hundreds 2 tens" },
      ] },
      { type: "number", prompt: "Now add the 17 loose crystals. Build the new total with the fewest blocks.", visual: { type: "blocks", places: ["hundreds", "tens", "ones"], title: "Rebuild the heap" } },
    ],
    hint: "10 rods make 1 flat. How many flats can you make from 23 rods? Then bundle 10 of the 17 loose crystals into a rod.",
    meter: { heat: 10, label: "Log complete +10%", story: "The avalanche heap is bundled" },
    discovery: { id: "everest", name: "Mount Everest", who: "Nova", fact: "Mount Everest is the tallest mountain on Earth. It is about 8,849 meters tall, and its top is always covered in snow and ice." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 230 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 247 },
    ] },
    rightFeedback: "23 tens is 230, and 230 + 17 is 247. The heap is bundled!",
    wrong: [
      { step: 1, value: 23, hint: "23 is the number of rods. Each rod has 10 crystals." },
      { step: 1, value: 2300, hint: "That would be 23 hundreds. Each rod is only 10 crystals." },
      { step: 2, choice: "b", hint: "23 tens is 230. Is that the same as 2,300?" },
      { step: 2, choice: "c", hint: "Rods are tens, not hundreds. 10 tens make 1 hundred." },
      { step: 2, choice: "d", hint: "Close! 20 tens make 2 hundreds. How many tens are left over?" },
      { step: 3, value: 2317, hint: "You can't write 17 in the ones place. Bundle 10 loose crystals into a rod first." },
      { step: 3, value: 237, hint: "Don't lose a ten! 17 ones is 1 ten and 7 ones." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Many ways to pack", machine: "Crate Packer", icon: "grid", speaker: "kai",
    line: "Crate 7 needs 350 crystals. Nova packed it with 3 flats and 5 rods. I want to pack it a different way!",
    question: "Pick every way that makes exactly 350 crystals.",
    items: [
      { id: "a", text: "3 hundreds 5 tens" },
      { id: "b", text: "2 hundreds 15 tens" },
      { id: "c", text: "35 tens" },
      { id: "d", text: "3 hundreds 15 tens" },
      { id: "e", text: "5 hundreds 3 tens" },
    ],
    hint: "Trade 1 hundred for 10 tens. The number stays the same. Check each one: how many crystals does it make?",
    meter: { heat: 5, label: "Log complete +5%", story: "Crate 7 is packed" },
    discovery: { id: "greenland", name: "Greenland's ice", who: "Nova", fact: "A giant sheet of ice covers most of Greenland. In the thickest places, the ice is more than 3,000 meters deep." },
    visual: { type: "blocks", mode: "show", places: ["hundreds", "tens", "ones"], counts: { hundreds: 3, tens: 5, ones: 0 }, title: "Nova's way" },
    answer: { kind: "multi", correct: ["a", "b", "c"] },
    rightFeedback: "300 + 50, 200 + 150, and 35 tens all make 350. One number, many ways!",
    wrong: [
      { pick: "d", hint: "15 tens is 150. Is 300 + 150 the same as 350?" },
      { pick: "e", hint: "5 hundreds 3 tens is 530. The digits switched places." },
      { missing: true, hint: "There are three ways. Did you check 35 tens? 10 tens make 100." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Fix Kai's log", machine: "Repair", icon: "log", speaker: "nova",
    line: "Kai counted 3 crates, 4 rods, and 5 loose crystals. He wrote 3,000 + 40 + 5 in the log. Then he wrote the number as 345. Something doesn't look right.",
    question: "Part 1: What went wrong? Part 2: Write the right number.",
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's log?", choices: [
        { id: "a", text: "There are no hundreds, so he needed a 0 in the hundreds place. Without it, the 3 moved to the hundreds place." },
        { id: "b", text: "He should have added the digits: 3 + 4 + 5 = 12." },
        { id: "c", text: "Nothing is wrong. 345 is the same as 3,000 + 40 + 5." },
      ] },
      { type: "number", prompt: "Write 3,000 + 40 + 5 as a number." },
    ],
    hint: "Say each place: thousands, hundreds, tens, ones. How many hundreds are there?",
    meter: { supplies: 1, label: "Crates +1", story: "Kai's log is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 3045 },
    ] },
    rightFeedback: "Fixed! 3,000 + 40 + 5 = 3,045. The 0 holds the hundreds place.",
    wrong: [
      { step: 1, choice: "b", hint: "Adding the digits doesn't tell us the number. What is each digit worth?" },
      { step: 1, choice: "c", hint: "345 is only three hundred forty-five. Kai counted 3 whole crates of 1,000!" },
      { step: 2, value: 345, hint: "That's Kai's mistake. Where is the thousands place?" },
      { step: 2, value: 3450, hint: "The 5 is ones and the 4 is tens. Which place gets the 0?" },
      { step: 2, value: 30405, hint: "Only one digit goes in each place. 3,000 has the 3 in the thousands place." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Inside a thousand-crate", machine: "Crate Packer", icon: "battery", speaker: "kai",
    line: "A rod is 10 crystals. A flat is 10 rods. A thousand-crate is 10 flats. Each size is 10 times as much as the one before it.",
    question: "How many rods fill one thousand-crate?",
    unit: "rods",
    hint: "One crate is 10 flats, and each flat is 10 rods. How many rods is 10 groups of 10?",
    meter: { supplies: 1, label: "Crates +1", story: "The thousand-crate is full" },
    visual: { type: "blocks", mode: "show", places: ["thousands", "hundreds", "tens", "ones"], counts: { thousands: 1, hundreds: 0, tens: 0, ones: 0 }, title: "One thousand-crate" },
    answer: { kind: "number", value: 100 },
    rightFeedback: "10 flats × 10 rods = 100 rods. And 100 rods × 10 crystals = 1,000!",
    wrong: [
      { value: 10, hint: "10 is how many flats fill the crate. Each flat is 10 rods." },
      { value: 1000, hint: "1,000 is how many loose crystals. How many rods of 10 is that?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The ice ruler", machine: "Ice Ruler", icon: "trail", speaker: "nova",
    line: "The ice ruler is a number line. The storeroom holds 4,630 crystals. I marked it on the ruler.",
    question: "Part 1: 4,630 is between which two thousands? Part 2: Round 4,630 to the nearest thousand. Tap it on the ruler.",
    parts: [
      { type: "choice", prompt: "4,630 is between which two thousands?", choices: [
        { id: "a", text: "4,000 and 5,000" },
        { id: "b", text: "4,600 and 4,700" },
        { id: "c", text: "3,000 and 4,000" },
      ] },
      { type: "number", prompt: "Round 4,630 to the nearest thousand. Tap the thousand it is closer to.", visual: { type: "numline", min: 4000, max: 5000, step: 100, pick: true, marks: [{ value: 4630, label: "4,630" }], label: "Crystals in the storeroom" } },
    ],
    hint: "Find the halfway point, 4,500. Is 4,630 before or after it?",
    meter: { heat: 5, label: "Log complete +5%", story: "The storeroom is logged" },
    discovery: { id: "vostok", name: "The coldest place", who: "Kai", fact: "The coldest air temperature ever measured was about −89°C, at Vostok Station in Antarctica." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 5000 },
    ] },
    rightFeedback: "4,630 is past the halfway point, 4,500. So it rounds to 5,000!",
    wrong: [
      { step: 1, choice: "b", hint: "4,600 and 4,700 are hundreds. The question asks about thousands." },
      { step: 1, choice: "c", hint: "4,630 is more than 4,000. Which thousand comes next?" },
      { step: 2, value: 4000, hint: "4,630 is past 4,500, the halfway point. Which thousand is closer?" },
      { step: 2, value: 4600, hint: "That's the nearest hundred. Round to the nearest thousand." },
      { step: 2, value: 4700, hint: "That's a hundred. Tap one of the thousands at the ends of the ruler." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The supply ship", machine: "Supply Log", icon: "quake", speaker: "vega",
    line: "Surprise, the supply ship is early! The pilot reads the load over the radio: \"forty-two thousand, three hundred six crystals.\"",
    question: "Part 1: Write the number. Part 2: Pick the expanded form. Part 3: What is the 4 worth?",
    parts: [
      { type: "number", prompt: "Write forty-two thousand, three hundred six as a number." },
      { type: "choice", prompt: "Which is 42,306 in expanded form?", choices: [
        { id: "a", text: "40,000 + 2,000 + 300 + 6" },
        { id: "b", text: "40,000 + 2,000 + 30 + 6" },
        { id: "c", text: "4,000 + 2,000 + 300 + 6" },
        { id: "d", text: "42 + 300 + 6" },
      ] },
      { type: "number", prompt: "In 42,306, what is the 4 worth?" },
    ],
    hint: "Say it in parts: forty-two thousand is 42,000. Three hundred six is 306. Every place needs a digit, even if it's 0.",
    meter: { heat: 10, label: "Log complete +10%", story: "The supply ship is unloaded" },
    discovery: { id: "freshwater", name: "Frozen fresh water", who: "Nova", fact: "About two-thirds of all the fresh water on Earth is frozen in glaciers and ice sheets." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 42306 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 40000 },
    ] },
    rightFeedback: "42,306 = 40,000 + 2,000 + 300 + 6. The 4 is worth 40,000!",
    wrong: [
      { step: 1, value: 4236, hint: "There are no tens, so the tens place needs a 0. Say it again: three hundred SIX." },
      { step: 1, value: 42360, hint: "Three hundred six has 0 tens and 6 ones. Which place gets the 6?" },
      { step: 1, value: 42036, hint: "Three hundred six has 3 hundreds. Check the hundreds place." },
      { step: 2, choice: "b", hint: "The 0 is in the tens place, so there are no tens. What is the 3 worth?" },
      { step: 2, choice: "c", hint: "The 4 is in the ten thousands place. Is it worth 4,000 or 40,000?" },
      { step: 2, choice: "d", hint: "42 is really 42 thousands. Expanded form shows what each digit is worth." },
      { step: 3, value: 4, hint: "The digit is 4, but its place gives it value. Which place is it in?" },
      { step: 3, value: 4000, hint: "Count the places from the right: ones, tens, hundreds, thousands, ten thousands." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Match the crate tags", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "Every crate has a tag, but some tags are written in different ways. Match each tag to its expanded form so we can stack them.",
    question: "Sort each tag into the bin with the same number.",
    hint: "Find what each tag is worth. 56 hundreds is 5,600.",
    meter: { supplies: 2, label: "Crates +2", story: "The crates are stacked" },
    answer: { kind: "sort", bins: { t1: "b1", t2: "b2", t3: "b3", t4: "b4", t5: "b1", t6: "b2" } },
    rightFeedback: "Every tag is in the right bin. Some numbers can be written lots of ways!",
    sort: {
      bins: [
        { id: "b1", label: "5,000 + 600 + 20" },
        { id: "b2", label: "5,000 + 600 + 2" },
        { id: "b3", label: "5,000 + 60 + 2" },
        { id: "b4", label: "500 + 60 + 2" },
      ],
      items: [
        { id: "t1", label: "5,620" },
        { id: "t2", label: "5,602" },
        { id: "t3", label: "5,062" },
        { id: "t4", label: "562" },
        { id: "t5", label: "5 thousands 6 hundreds 2 tens" },
        { id: "t6", label: "56 hundreds 2 ones" },
      ],
    },
    wrong: [
      { item: "t6", hint: "56 hundreds is 5,600. Add 2 ones. Which bin is 5,602?" },
      { item: "t5", hint: "2 tens is 20, not 2. Which bin has + 20?" },
      { item: "t3", hint: "5,062 has 0 hundreds. Look for a bin with no hundreds part." },
      { item: "t4", hint: "562 has no thousands. Look for the bin that starts with 500." },
      { item: "t2", hint: "5,602 has 0 tens and 2 ones. Which bin ends in + 2 with 600?" },
      { item: "t1", hint: "5,620 has 2 tens, so the tens part is 20." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "What is the 4 worth?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Crate 12 has 3,482 crystals. The 4 in 3,482 is worth 4. A 4 is a 4!"',
    nova: 'Nova: "The 4 is in the hundreds place. That means it stands for 4 flats, so it\'s worth 400."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Say the places from the right: ones, tens, hundreds, thousands. Which place is the 4 in?",
    meter: { heat: 5, label: "Log complete +5%", story: "Kai rethinks the digit rule" },
    discovery: { id: "woodfrog", name: "Wood frogs", who: "Nova", fact: "Wood frogs can freeze almost solid in winter. Their hearts stop, and in spring they thaw out and hop away." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A digit's value depends on its place. The 4 is in the hundreds place, so it's worth 4 hundreds, or 400." },
      { id: "B", text: "Nova, because 4 is an even number." },
      { id: "C", text: "Kai. A digit is always worth the same, no matter where it is." },
      { id: "D", text: "Kai. The 4 is less than the 8, so it's worth less." },
    ],
    writtenPrompt: "Tell Kai in your own words why the 4 in 3,482 is worth 400.",
    debateHints: {
      wrongWho: "Picture 3,482 in blocks: 3 crates, 4 flats, 8 rods, 2 ones. How many crystals are in 4 flats?",
      wrongReason: "Right person, check the reason. What decides how much a digit is worth?",
      right: "Nova is right — the 4 is in the hundreds place, so it's worth 400.",
    },
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Round the cave bin", machine: "Ice Ruler", icon: "trail", speaker: "nova",
    line: "The cave bin has 368 crystals. Commander Vega wants a quick number for her report, so we'll round it two ways.",
    question: "Part 1: Round 368 to the nearest hundred. Part 2: Round 368 to the nearest ten.",
    parts: [
      { type: "number", prompt: "368 is between 300 and 400. Tap the hundred it is closer to.", visual: { type: "numline", min: 300, max: 400, step: 10, pick: true, marks: [{ value: 368, label: "368" }], label: "Crystals in the cave bin" } },
      { type: "number", prompt: "368 is between 360 and 370. Tap the ten it is closer to.", visual: { type: "numline", min: 360, max: 370, step: 1, pick: true, marks: [{ value: 368, label: "368" }], label: "Crystals in the cave bin" } },
    ],
    hint: "Find the halfway point between the two ends. Is 368 before or after it?",
    meter: { heat: 5, label: "Log complete +5%", story: "Vega's report is ready" },
    discovery: { id: "icecore", name: "Ancient ice", who: "Kai", fact: "Scientists drill long tubes of ice out of Antarctica. Some of that ice is more than 800,000 years old!" },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 400 },
      { kind: "number", value: 370 },
    ] },
    rightFeedback: "368 rounds to 400 to the nearest hundred, and to 370 to the nearest ten.",
    wrong: [
      { step: 1, value: 300, hint: "The halfway point is 350. 368 is past it, so which hundred is closer?" },
      { step: 1, value: 370, hint: "That's the nearest ten. Part 1 asks for the nearest hundred." },
      { step: 2, value: 360, hint: "The halfway point is 365. 368 is past it, so which ten is closer?" },
      { step: 2, value: 400, hint: "That's the nearest hundred. Part 2 asks for the nearest ten." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Trade up the flats", machine: "Crystal Bundler", icon: "grid", speaker: "kai",
    line: "My last pile has 2 crates, 15 flats, and 8 loose crystals. That's too many flats for one shelf!",
    question: "Trade 10 flats for 1 crate. Then build the pile with the fewest blocks.",
    hint: "10 hundreds make 1 thousand. After the trade, how many crates and flats are there?",
    meter: { supplies: 1, label: "Crates +1", story: "The last pile is packed" },
    visual: { type: "blocks", places: ["thousands", "hundreds", "tens", "ones"], title: "Kai's last pile" },
    answer: { kind: "number", value: 3508 },
    rightFeedback: "15 hundreds is 1 thousand 5 hundreds. So the pile is 3,508!",
    wrong: [
      { value: 2158, hint: "Only one digit fits in each place. Trade 10 flats for 1 crate first." },
      { value: 2508, hint: "You made the trade, but where did the new crate go? Add it to the 2 crates." },
      { value: 3580, hint: "The 8 is loose crystals, so it goes in the ones place. There are no rods." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Close the supply log", machine: "Supply Log", icon: "relay", speaker: "vega",
    line: "This is it! A snow slide knocked over the last shelf. It has 3 crates, 0 flats, 14 rods, and 6 loose crystals. We need the final count before the ship leaves.",
    question: "Part 1: How many crystals are on the shelf? Part 2: Pick the expanded form. Part 3: Round it to the nearest thousand. Part 4: The main base stores 10 times as many as 3,000. How many is that?",
    parts: [
      { type: "number", prompt: "How many crystals are on the shelf?", visual: { type: "blocks", mode: "show", places: ["thousands", "hundreds", "tens", "ones"], counts: { thousands: 3, hundreds: 0, tens: 14, ones: 6 }, title: "The fallen shelf" } },
      { type: "choice", prompt: "Which is 3,146 in expanded form?", choices: [
        { id: "a", text: "3,000 + 100 + 40 + 6" },
        { id: "b", text: "3,000 + 400 + 10 + 6" },
        { id: "c", text: "300 + 100 + 40 + 6" },
        { id: "d", text: "3 + 1 + 4 + 6" },
      ] },
      { type: "number", prompt: "Round 3,146 to the nearest thousand. Tap it on the ruler.", visual: { type: "numline", min: 3000, max: 4000, step: 100, pick: true, marks: [{ value: 3146, label: "3,146" }], label: "Final count" } },
      { type: "number", prompt: "The main base stores 10 times as many crystals as 3,000. How many is that?" },
    ],
    hint: "Bundle 10 rods into a flat first. For Part 4, 10 thousands make 1 ten thousand.",
    meter: { heat: 15, label: "Log complete +15%", story: "The supply log is closed" },
    discovery: { id: "emperor", name: "Emperor penguins", who: "Nova", fact: "Emperor penguins are the biggest penguins. They can dive more than 500 meters deep to catch fish." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 3146 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 3000 },
      { kind: "number", value: 30000 },
    ] },
    rightFeedback: "3,146 crystals, about 3,000. And the main base stores 30,000. The supply log is closed!",
    wrong: [
      { step: 1, value: 31406, hint: "Only one digit fits in each place. Bundle 10 rods into 1 flat first." },
      { step: 1, value: 3046, hint: "Don't lose the flat you made! 14 tens is 1 hundred and 4 tens." },
      { step: 1, value: 3140, hint: "Don't forget the 6 loose crystals in the ones place." },
      { step: 2, choice: "b", hint: "The 1 is in the hundreds place and the 4 is in the tens place." },
      { step: 2, choice: "c", hint: "The 3 is in the thousands place. Is it worth 300 or 3,000?" },
      { step: 2, choice: "d", hint: "Those are just the digits. What is each digit worth?" },
      { step: 3, value: 4000, hint: "The halfway point is 3,500. Is 3,146 before or after it?" },
      { step: 3, value: 3100, hint: "That's the nearest hundred. Round to the nearest thousand." },
      { step: 4, value: 3010, hint: "10 times as many is not 10 more. 10 thousands make 1 ten thousand. What are 30 thousands?" },
      { step: 4, value: 300, hint: "That's smaller! 10 times as many should be bigger. 3 thousands becomes 3 ten thousands." },
    ],
  },
};

export default {
  id: "MA.3.2A-XP",
  standard: "MA.3.2A-XP",
  engine: "expedition_station",
  title: "The Crystal Count",
  planet: "Frostveil",
  outpost: "Crystal Caves · supply day",
  grade: 3,
  subject: "Math",
  teks: "3.2A",
  supportingTeks: ["3.2B", "3.2C"],
  skillsChip: "3.2A · Place value to 100,000",
  iCan: "I can build and break apart numbers with blocks, pictures, and expanded form. I can tell what a digit is worth and round numbers on a number line.",
  blurb: "The ice caves of Frostveil sparkle with crystals, and the supply ship is coming. The crew has to count, bundle, and log every crystal before it leaves.",
  mission: "Bundle the ice crystals into rods, flats, and crates, and close the supply log.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.21 · FROSTVEIL CRYSTAL CAVES",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Log complete", heatUnit: "%", supplies: "Crates", suppliesUnit: "crates" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We've reached the Crystal Caves on Frostveil.",
    "The caves are full of ice crystals, and the supply ship needs an exact count. Loose crystals get bundled into rods of 10, rods into flats of 100, and flats into crates of 1,000.",
    "Help Kai and Nova bundle every crystal and fill in the supply log. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Bundle the crystals", "Act 2 · Pack the crates", "Act 3 · Close the supply log"],
    completes: [
      "Every loose crystal is bundled, {firstName}!",
      "The crates are packed and the supply ship is unloaded, {firstName}!",
      "The supply log is closed, {firstName}! The ship is ready to fly.",
    ],
    teasers: [
      "Next on Frostveil: the crates need packing, and Kai's log has a mistake. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the supply ship leaves soon, and the log isn't done. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The crystals are bundled, and now they need to go into crates.",
      "Kai's been writing in the supply log again. Let's check his numbers.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The supply ship leaves the Crystal Caves soon.",
      "Help the crew match the crate tags, round the counts, and close the supply log.",
    ],
  }),
  tasks,
};
