// Expedition Station — The Dark Canopy (ELA.4.6F-XP)
// Grade 4 · ELAR · Lumara. Main standard 4.6F (make inferences and use
// evidence); also practices 4.7C (text evidence), 4.11C (revise), 4.11D (edit),
// 4.3B and 4.3C (vocabulary), 4.8A and 4.8B (theme, characters), 4.7B (compare
// sources). All passages are original, written for this quest.
//
// Fully locked until the student screen can show passages and the ELAR task
// types (choice, highlight, edit, parts, write). See CONTENT_NOTES in catalog.js.
import { CREW, acts, lockEverything, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Nova's Field Log, Day 1", genre: "Informational narrative" }, [
    [
      "Something is wrong in the canopy.",
      "For as long as the crew has lived on Lumara, the glow-moths have lit up the treetops every night.",
      "Tonight I counted only six glowing moths.",
      "Last month I counted more than two hundred.",
    ],
    [
      "I checked the moth traps three times.",
      "Each time, my hands shook a little more.",
      "The moths were there, sitting on the leaves, but their wings stayed dark.",
    ],
    [
      "Glow-moths do not glow to light up the forest.",
      "They glow to find each other.",
      "A moth flashes its wings, and another moth flashes back.",
      "That is how they meet and build nests together.",
      "A moth that cannot be seen is a moth that is alone.",
    ],
    [
      "Kai says the new floodlights by the landing pad make the outpost safer at night.",
      "They are so bright that I can read my notes without a lamp, even at midnight.",
      "They switched on for the first time eleven days ago.",
    ],
    ["Tomorrow I will walk the canopy trail again.", "I hope I am wrong about what I am starting to think."],
  ]),
  B: {
    id: "B",
    title: "Kai's message to Mission Control",
    genre: "Message (has mistakes)",
    ...editText("B", "Mission Control, the new floodlights {is} working great. They light up the {hole} landing pad. Nova thinks the lights bother the moths, but I'm not sure. {we} will know more soon.", {
      is: ["are", "was"],
      hole: ["whole", "holes"],
      we: ["We", "Wee"],
    }),
  },
  C: passage("C", { title: "The Lantern Keeper", genre: "Legend (traditional tale)" }, [
    [
      "Long ago, in the high branches of Lumara, lived a keeper named Oru.",
      "Every evening, Oru climbed from tree to tree and lit a hundred lanterns.",
      "\"No one in my forest will ever be lost in the dark,\" he said proudly.",
    ],
    ["The lanterns burned all night.", "Travelers praised Oru, and his chest swelled like a seed pod in the rain."],
    [
      "But season after season, the forest grew quieter.",
      "The night songs of the tree frogs faded.",
      "The glow-moths, which once danced like sparks, hid under the leaves.",
      "Oru did not notice.",
      "He was too busy polishing lanterns.",
    ],
    [
      "One night, a small voice called from a branch.",
      "It was an old glow-moth, her wings as dim as ash.",
      "\"Keeper,\" she said, \"your light is kind, but it is too loud. We cannot hear each other's light.\"",
    ],
    ["Oru laughed.", "\"Light does not make noise, little one.\""],
    ["\"Then blow out your lanterns for one night,\" said the moth, \"and listen.\""],
    [
      "Oru frowned.",
      "He was not used to taking advice from a moth.",
      "Still, his steps were light as he moved from tree to tree, blowing out each flame.",
    ],
    [
      "Darkness fell over the canopy.",
      "For a long moment, nothing happened.",
      "Then, far away, one tiny spark flashed.",
      "Another answered it.",
      "Then ten, then a hundred, until the whole forest shimmered like a river of stars.",
    ],
    [
      "Oru sat in the dark and smiled.",
      "From that night on, he lit only one lantern, low and small, and let the forest keep the rest of the night for itself.",
    ],
  ]),
  D: passage("D", { title: "Nova's Field Log, Day 5", genre: "Informational narrative with data" }, [
    [
      "Today we ran a test.",
      "With Commander Vega's permission, Kai turned off the floodlights on the east side of the outpost from sunset to sunrise.",
      "The west side stayed lit, just like before.",
      "Everything else stayed the same.",
      "Both sides have the same trees, the same flowers, and the same number of moth traps.",
    ],
    ["At midnight I counted glowing moths on both sides.", "East side (lights off): 58 glowing moths.", "West side (lights on): 4 glowing moths."],
    [
      "Kai stood next to me on the east trail and didn't say anything for a long time.",
      "Then he said, \"I misjudged the lights. I'll talk to Vega about new ones.\"",
      "He sounded disappointed, but he didn't argue.",
    ],
    ["There may be other reasons, too.", "We only tested one night.", "Tomorrow we will switch sides to make sure the results are not about the trees."],
  ]),
  E: {
    id: "E",
    title: "Mission Report draft",
    genre: "Report (has mistakes)",
    ...editText("E", "The glow-moths of {lumara} stopped glowing after the new floodlights {was} turned on. {glow-moths} flash {there} wings to find each other. On the night of the test, the dark side had 58 glowing moths. The lit side had only 4.", {
      lumara: ["Lumara", "lumaras"],
      was: ["were", "is"],
      "glow-moths": ["Glow-moths", "glow-moth"],
      there: ["their", "they're"],
    }),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Clear the static", machine: "Decipher", icon: "static", speaker: "nova", passage: ["A"],
    line: "My log came through with static on one word. Help me clear it.",
    question: "Read Passage A. \"Something is wrong in the canopy.\" What does canopy mean here?",
    hint: "Look at the next sentence for a clue.",
    meter: { heat: 15, label: "Glow +15%", story: "Nova's log comes through clearly" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The top layer of the forest, where the treetops are" },
      { id: "b", text: "A cloth roof over a bed or a tent" },
      { id: "c", text: "A deep cave under the forest" },
      { id: "d", text: "A path through the middle of the forest" },
    ],
    rightFeedback: "Static cleared! The canopy is the top layer of the forest.",
    wrong: [
      { choice: "b", hint: "That's another meaning of canopy. Which meaning fits with \"treetops\" in the next sentence?" },
      { choice: "c", hint: "The moths light up the treetops. Is a cave near the treetops?" },
      { choice: "d", hint: "Read the next sentence. Where do the glow-moths light up?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Lock the scanner", machine: "Trace", icon: "scan", speaker: "nova", passage: ["A"],
    line: "I need to know exactly why the moths glow. Point my scanner at the right line.",
    question: "Why do glow-moths glow? Highlight the sentence that tells you.",
    hint: "Look for the sentence that starts to explain why.",
    meter: { heat: 10, label: "Glow +10%", story: "The scanner locks on" },
    discovery: { id: "firefly", name: "Fireflies", who: "Nova", fact: "Fireflies flash their lights to find each other. Each kind of firefly has its own flash pattern." },
    answer: { kind: "highlight", groups: [["A3.2"]] },
    rightFeedback: "Locked on: \"They glow to find each other.\"",
    wrong: [
      { sentence: "A1.2", hint: "That tells what the moths do every night, not why they glow." },
      { sentence: "A3.1", hint: "That sentence tells why they DON'T glow. Read the next one." },
      { sentence: "A3.3", hint: "That shows how they flash. Which sentence says why?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Fix Kai's message", machine: "Repair", icon: "log", speaker: "kai", passage: ["B"],
    line: "I'm sending this to Mission Control, but Nova says it has 3 mistakes. Can you fix them before it goes?",
    question: "Tap each mistake in Kai's message and pick the fix.",
    hint: "Read it out loud in your head. Does every word sound and look right?",
    meter: { heat: 10, label: "Glow +10%", story: "Kai's message arrives clean" },
    answer: { kind: "edit", fixes: { "B:is": "are", "B:hole": "whole", "B:we": "We" } },
    rightFeedback: "Message sent clean!",
    wrong: [
      { token: "B:is", hint: "Floodlights is more than one. Should it be \"is\" or \"are\"?" },
      { token: "B:hole", hint: "A hole is a gap in the ground. Which word means all of it?" },
      { token: "B:we", hint: "\"we\" starts a new sentence. What does the first word of a sentence need?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Read Nova's mood", machine: "Read the Crew", icon: "crew", speaker: "kai", passage: ["A"],
    line: "Nova seems different today. You read her log. How is she feeling?",
    question: "Part 1: How does Nova feel in Passage A? Part 2: Highlight the sentence that shows it.",
    parts: [
      { type: "choice", prompt: "How does Nova feel?", choices: [
        { id: "a", text: "Worried" },
        { id: "b", text: "Excited" },
        { id: "c", text: "Bored" },
        { id: "d", text: "Angry at Kai" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows how she feels.", passage: "A" },
    ],
    hint: "What do her hands do when she checks the traps?",
    meter: { supplies: 1, label: "Journal notes +1", story: "Kai checks in on Nova" },
    discovery: { id: "beetle", name: "Glowing beetles", who: "Kai", fact: "Some click beetles have two glowing spots that look like tiny headlights." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "highlight", groups: [["A2.2", "A5.2"]] }] },
    rightFeedback: "Nova is worried, and her shaking hands show it.",
    wrong: [
      { step: 1, choice: "b", hint: "Excited? Read how her hands felt when she checked the traps." },
      { step: 1, choice: "c", hint: "Would someone who's bored check the traps three times?" },
      { step: 1, choice: "d", hint: "Nova doesn't say anything angry about Kai. What do her hands do?" },
      { step: 2, sentence: "A1.3", hint: "That tells what she counted, not how she feels." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "What Nova suspects", machine: "Trace", icon: "snap", speaker: "vega", passage: ["A"],
    line: "Surprise, Mission Control wants an answer now! Nova won't say it, but she has a guess about why the moths went dark.",
    question: "Part 1: What does Nova think is making the moths stop glowing? Part 2: Highlight TWO sentences that best support your answer.",
    parts: [
      { type: "choice", prompt: "What does Nova think is causing the problem?", choices: [
        { id: "a", text: "The new floodlights" },
        { id: "b", text: "The moth traps" },
        { id: "c", text: "Cold weather" },
        { id: "d", text: "The moths are sick" },
      ] },
      { type: "highlight", prompt: "Highlight two sentences that support your answer.", passage: "A", count: 2 },
    ],
    hint: "Nova never says it directly. Which new thing happened eleven days ago?",
    meter: { heat: 10, label: "Glow +10%", story: "The crew knows where to look" },
    discovery: { id: "lightpollution", name: "Light pollution", who: "Nova", fact: "Bright lights at night can confuse animals like moths, baby sea turtles, and birds that travel at night." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A3.2", "A3.5"], ["A4.2", "A4.3"]] },
    ] },
    rightFeedback: "Right: the moths glow to find each other, and the new lights are brighter than their glow.",
    wrong: [
      { step: 1, choice: "b", hint: "Nova checked the traps and the moths were fine. What changed eleven days ago?" },
      { step: 1, choice: "c", hint: "Where does Nova's log talk about the weather?" },
      { step: 1, choice: "d", hint: "The moths are sitting on the leaves. Does Nova say they're sick?" },
      { step: 2, sentence: "A1.3", hint: "That shows the problem, not the cause. Find a sentence about why moths glow, and one about the lights." },
      { step: 2, sentence: "A2.1", hint: "That shows how careful Nova is, not the cause." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "How Oru changes", machine: "Read the Crew", icon: "crew", speaker: "nova", passage: ["C"],
    line: "This old Lumaran legend sounds a lot like what's happening here. Read it with me.",
    question: "Part 1: How does Oru change from the beginning of the story to the end? Part 2: Highlight one sentence from the beginning and one from the end that show the change.",
    parts: [
      { type: "choice", prompt: "How does Oru change?", choices: [
        { id: "a", text: "He goes from being proud of his hundred lanterns to listening and lighting only one small lantern." },
        { id: "b", text: "He stops caring about the forest." },
        { id: "c", text: "He becomes afraid of the dark." },
        { id: "d", text: "He learns to light even more lanterns." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from the beginning and one from the end.", passage: "C", count: 2 },
    ],
    hint: "Compare what Oru does in the first paragraph and the last paragraph.",
    meter: { heat: 5, label: "Glow +5%", story: "The legend gives Nova an idea" },
    discovery: { id: "treefrog", name: "Tree frogs", who: "Kai", fact: "Male tree frogs call at night to find mates. Some calls can be heard from far away." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["C1.2", "C1.3", "C2.2"], ["C9.1", "C9.2"]] },
    ] },
    rightFeedback: "Oru changes from proud to wise.",
    wrong: [
      { step: 1, choice: "b", hint: "At the end, Oru lets the forest keep the night. Does that sound like he stopped caring?" },
      { step: 1, choice: "c", hint: "Oru sits in the dark and smiles. Is he afraid?" },
      { step: 1, choice: "d", hint: "Read the last paragraph. How many lanterns does he light?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The light steps", machine: "Decipher", icon: "static", speaker: "kai", passage: ["C"],
    line: "Wait, this legend says Oru's steps were light. Did his feet glow?",
    question: "\"His steps were light as he moved from tree to tree.\" What does light mean here?",
    hint: "Is the story talking about brightness or about how he walked?",
    meter: { supplies: 1, label: "Journal notes +1", story: "Kai learns a new meaning" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Glowing" },
      { id: "b", text: "Not heavy; soft and quiet" },
      { id: "c", text: "Pale in color" },
      { id: "d", text: "Easy to understand" },
    ],
    rightFeedback: "Right: light steps are soft and quiet.",
    wrong: [
      { choice: "a", hint: "That's another meaning of light. Is the story about how bright his feet were?" },
      { choice: "c", hint: "Steps don't have a color. How was he walking?" },
      { choice: "d", hint: "That meaning doesn't fit steps. How was Oru walking?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Smooth Kai's report", machine: "Repair", icon: "log", speaker: "kai",
    line: "My next message is choppy: \"The floodlights are bright. The floodlights help pilots land.\"",
    question: "Pick the best way to combine the two sentences.",
    hint: "Which choice says the same thing in fewer words?",
    meter: { heat: 5, label: "Glow +5%", story: "Kai's report reads smoothly" },
    discovery: { id: "owl", name: "Owl eyes", who: "Nova", fact: "Owls have huge eyes that help them see in very dim light." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "The floodlights are bright, the floodlights help pilots land." },
      { id: "b", text: "The bright floodlights help pilots land." },
      { id: "c", text: "The floodlights and pilots are bright and land." },
      { id: "d", text: "Bright floodlights, pilots, land." },
    ],
    rightFeedback: "Smooth! \"The bright floodlights help pilots land.\"",
    wrong: [
      { choice: "a", hint: "That's two sentences joined with only a comma, and it still repeats \"the floodlights.\"" },
      { choice: "c", hint: "Are the pilots bright? That changes the meaning." },
      { choice: "d", hint: "That isn't a complete sentence." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Two views of the lights", machine: "Two Accounts", icon: "split", speaker: "nova", passage: ["A", "B"],
    line: "Kai and I see the floodlights very differently. Compare what we each wrote.",
    question: "Part 1: How is Kai's view of the floodlights different from Nova's? Part 2: Highlight one sentence from each passage that shows their views.",
    parts: [
      { type: "choice", prompt: "How are their views different?", choices: [
        { id: "a", text: "Kai thinks the lights are good for the outpost. Nova worries they're hurting the moths." },
        { id: "b", text: "They both think the lights are a problem." },
        { id: "c", text: "Nova likes the lights. Kai wants them off." },
        { id: "d", text: "Neither of them has noticed the lights." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from Passage A and one from Passage B.", passage: ["A", "B"], count: 2 },
    ],
    hint: "What does Kai say the lights do? What does Nova worry about?",
    meter: { supplies: 1, label: "Journal notes +1", story: "The crew talks it through" },
    discovery: { id: "mothbutterfly", name: "Moths and butterflies", who: "Kai", fact: "Most moths fly at night, and most butterflies fly during the day." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A4.1", "A4.2", "A5.2"], ["B-s1", "B-s2", "B-s3"]] },
    ] },
    rightFeedback: "Kai sees safety; Nova sees a problem for the moths.",
    wrong: [
      { step: 1, choice: "b", hint: "Kai's message says the lights are \"working great.\" Does that sound like a problem?" },
      { step: 1, choice: "c", hint: "Who wrote that the lights are working great?" },
      { step: 1, choice: "d", hint: "Both passages talk about the floodlights." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The lights-off test", machine: "Read the Crew", icon: "quake", speaker: "vega", passage: ["D"],
    line: "Surprise, the test results are in! Read Nova's Day 5 log.",
    question: "Part 1: What does Kai realize after the test? Part 2: Highlight the sentence that shows it. Part 3: Nova's draft conclusion says, \"The lights did it.\" Pick a stronger sentence that uses evidence.",
    parts: [
      { type: "choice", prompt: "What does Kai realize?", choices: [
        { id: "a", text: "The floodlights are keeping the moths from glowing, and he was wrong about them." },
        { id: "b", text: "Nova's test was unfair." },
        { id: "c", text: "The trees on the east side are better for moths." },
        { id: "d", text: "He is angry at Nova for turning off the lights." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows what Kai realizes.", passage: "D" },
      { type: "choice", prompt: "Pick the strongest conclusion.", choices: [
        { id: "a", text: "The lights were really, really bad." },
        { id: "b", text: "On the night of the test, 58 moths glowed on the dark side but only 4 glowed on the lit side, so the floodlights are likely the problem." },
        { id: "c", text: "Moths like the dark." },
        { id: "d", text: "Kai should not have put up the lights." },
      ] },
    ],
    hint: "Look at what Kai says, not only how he sounds.",
    meter: { heat: 5, label: "Glow +5%", story: "The east side glows again" },
    discovery: { id: "seaturtle", name: "Baby sea turtles", who: "Nova", fact: "Baby sea turtles find the ocean by heading toward the brightest horizon. Bright beach lights can lead them the wrong way." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["D3.2"]] },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Great reading: Kai changed his mind, and your conclusion uses the numbers.",
    wrong: [
      { step: 1, choice: "b", hint: "Nova kept everything else the same. Does Kai say the test was unfair?" },
      { step: 1, choice: "c", hint: "Both sides have the same trees. Read what Kai says on the trail." },
      { step: 1, choice: "d", hint: "The log says Kai didn't argue. What does he say?" },
      { step: 2, sentence: "D3.3", hint: "That shows how he sounded. Which sentence shows what he realized?" },
      { step: 3, choice: "a", hint: "That has no evidence. Mission Control wants numbers." },
      { step: 3, choice: "c", hint: "That's true, but it doesn't use the test results." },
      { step: 3, choice: "d", hint: "That's an opinion, not a conclusion from the test." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Was it a fair test?", machine: "Trace", icon: "scan", speaker: "kai", passage: ["D"],
    line: "Vega will ask if the test was fair. Help me find the proof.",
    question: "Highlight the sentence that shows Nova tried to make her test fair.",
    hint: "A fair test changes only one thing. Which sentence says that?",
    meter: { supplies: 1, label: "Journal notes +1", story: "Kai has his proof for Vega" },
    discovery: { id: "mushroom", name: "Glowing mushrooms", who: "Nova", fact: "Some mushrooms glow in the dark. People have called their soft green light \"foxfire.\"" },
    answer: { kind: "highlight", groups: [["D1.4", "D1.5"]] },
    rightFeedback: "Right: everything else stayed the same.",
    wrong: [
      { sentence: "D2.1", hint: "That describes the counting, not what made the test fair." },
      { sentence: "D1.2", hint: "That tells what changed. Which sentence shows everything else stayed the same?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Punctuate the log", machine: "Repair", icon: "log", speaker: "nova",
    line: "I'm adding one more line to my log, but I'm not sure about the punctuation.",
    question: "Pick the correctly punctuated line.",
    hint: "Where do the quotation marks and the comma go?",
    meter: { heat: 5, label: "Glow +5%", story: "Nova's log is ready to send" },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "We should switch sides tomorrow Nova said." },
      { id: "b", text: "\"We should switch sides tomorrow\" Nova said." },
      { id: "c", text: "\"We should switch sides tomorrow,\" Nova said." },
      { id: "d", text: "\"We should switch sides tomorrow,\" nova said." },
    ],
    rightFeedback: "Perfect punctuation!",
    wrong: [
      { choice: "a", hint: "Nova's exact words need quotation marks around them." },
      { choice: "b", hint: "Almost! Something goes after \"tomorrow\" and before the closing quotation mark." },
      { choice: "d", hint: "Check the name. What does a name always start with?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The shared lesson", machine: "Brief", icon: "brief", speaker: "vega", passage: ["A", "C", "D"],
    line: "The legend and Nova's logs seem to be telling the same story. What do they teach?",
    question: "What lesson do \"The Lantern Keeper\" and Nova's logs share?",
    hint: "A theme is a lesson. What did Oru and Kai both learn?",
    meter: { supplies: 1, label: "Journal notes +1", story: "Vega adds the lesson to the mission file" },
    discovery: { id: "stars", name: "Dark skies", who: "Kai", fact: "Far away from city lights, people can see thousands of stars in the night sky." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Moths are beautiful." },
      { id: "b", text: "Something meant to help can cause harm, so it's important to notice and listen." },
      { id: "c", text: "Always work hard." },
      { id: "d", text: "Lanterns are better than floodlights." },
    ],
    rightFeedback: "That's the theme both stories share.",
    wrong: [
      { choice: "a", hint: "That's what the stories are about. What do they teach?" },
      { choice: "c", hint: "Oru worked hard, and it didn't help. What did he learn?" },
      { choice: "d", hint: "Oru blew out his lanterns, too. Think bigger: what lesson fits both?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Decode misjudged", machine: "Decipher", icon: "static", speaker: "nova", passage: ["D"],
    line: "Kai said, \"I misjudged the lights.\" Let's make sure we know what he meant.",
    question: "What does the prefix mis- tell you about the word misjudged?",
    hint: "Think of misspell and misread.",
    meter: { heat: 5, label: "Glow +5%", story: "Kai and Nova agree on a plan" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Mis- means wrongly, so misjudged means judged wrongly." },
      { id: "b", text: "Mis- means again, so misjudged means judged again." },
      { id: "c", text: "Mis- means not, so misjudged means never judged." },
      { id: "d", text: "Mis- means before, so misjudged means judged early." },
    ],
    rightFeedback: "Right: Kai judged the lights wrongly.",
    wrong: [
      { choice: "b", hint: "That's what re- means, as in reread. What does mis- mean in misspell?" },
      { choice: "c", hint: "Kai did judge the lights. Did he judge them right or wrong?" },
      { choice: "d", hint: "That's what pre- means, as in preview. Think of misspell." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Send the mission report", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["E", "A", "C", "D"],
    line: "This is it. Fix the report, finish it, and send it to Mission Control.",
    question: "Part 1: Fix the 4 mistakes in the report. Part 2: Pick the best concluding sentence. Part 3: Write 2–3 sentences explaining why the moths stopped glowing, using evidence from two different passages.",
    parts: [
      { type: "edit", prompt: "Fix the 4 mistakes in the report.", passage: "E" },
      { type: "choice", prompt: "Pick the best concluding sentence.", choices: [
        { id: "a", text: "Moths are really cool insects." },
        { id: "b", text: "The floodlights should be dimmed or shielded at night so the moths can see each other's light again." },
        { id: "c", text: "In conclusion, this is my report about moths." },
        { id: "d", text: "Kai likes the floodlights because they are bright." },
      ] },
      { type: "write", prompt: "Explain why the moths stopped glowing. Use evidence from two different passages.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["Answers the question", "Uses evidence from two different passages", "Complete sentences with capitals and end punctuation"],
    hint: "Your conclusion should say what the crew should do next.",
    meter: { heat: 10, label: "Glow +10%", story: "Mission Control approves the plan" },
    discovery: { id: "fireflyseason", name: "Firefly nights", who: "Nova", fact: "In many places, fireflies are easiest to see on warm summer nights, just after sunset." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "E:lumara": "Lumara", "E:was": "were", "E:glow-moths": "Glow-moths", "E:there": "their" } },
      { kind: "choice", correct: "b" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Report sent! Your teacher will read your explanation.",
    wrong: [
      { step: 1, token: "E:lumara", hint: "Lumara is the name of a planet. What do names start with?" },
      { step: 1, token: "E:was", hint: "The floodlights is more than one. \"Was\" or \"were\"?" },
      { step: 1, token: "E:glow-moths", hint: "This word starts a new sentence." },
      { step: 1, token: "E:there", hint: "The wings belong to the moths. Which \"there\" shows that something belongs to someone?" },
      { step: 2, choice: "a", hint: "That's off topic. What should the crew do next?" },
      { step: 2, choice: "c", hint: "That doesn't say anything new. What should the crew do next?" },
      { step: 2, choice: "d", hint: "That doesn't wrap up the report. What should the crew do next?" },
    ],
  },
};

// Passage B has no sentence ids from passage(); give its three sentences ids
// so task 9 can ask students to highlight one.
passages.B.sentences = [
  { id: "B-s1", text: "Mission Control, the new floodlights is working great." },
  { id: "B-s2", text: "They light up the hole landing pad." },
  { id: "B-s3", text: "Nova thinks the lights bother the moths, but I'm not sure." },
  { id: "B-s4", text: "we will know more soon." },
];

export default lockEverything({
  id: "ELA.4.6F-XP",
  standard: "ELA.4.6F-XP",
  engine: "expedition_station",
  title: "The Dark Canopy",
  planet: "Lumara",
  outpost: "Canopy Outpost · night shift",
  grade: 4,
  subject: "ELAR",
  teks: "4.6F",
  supportingTeks: ["4.7C", "4.11C", "4.11D", "4.3B", "4.3C", "4.8A", "4.8B", "4.7B"],
  skillsChip: "4.6F · Make inferences and use evidence",
  iCan: "I can make inferences and prove them with evidence from the text. I can revise and edit a message so it's clear and correct.",
  blurb: "The glow-moths of Lumara's canopy have stopped glowing, and the forest is going dark. Nova is investigating, and every clue is in the crew's logs.",
  mission: "Read the crew's logs and an old legend to figure out why the moths went dark, then send the report to Mission Control.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.61 · LUMARA CANOPY",
  playableActs: [],
  meterStart: { heat: 30, supplies: 0, journal: 0 },
  meterLabels: { heat: "Glow", heatUnit: "%", supplies: "Journal notes", suppliesUnit: "notes" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {name}, this is Commander Vega. Something strange is happening on Lumara.",
    "The glow-moths in the canopy have stopped glowing, and the forest is going dark. Nova has been keeping field logs.",
    "Read everything carefully. The answer is in the words. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The first clues", "Act 2 · The legend and the test", "Act 3 · The report"],
    completes: [
      "You found Nova's first clue, {firstName}!",
      "The test proved it, {firstName}! The moths glow again on the dark side.",
      "Your report is on its way to Mission Control, {firstName}! Lumara's canopy will glow again.",
    ],
    teasers: [
      "Next on Lumara: Nova found an old legend, and she's planning a test. Act 2 opens on your next station visit.",
      "Next on Lumara: it's time to write the report. Act 3 opens on your next station visit.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. I found an old Lumaran legend that sounds a lot like what's happening.",
      "And Commander Vega said yes to a test.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Mission Control needs a full report.",
      "Help the crew get every word right.",
    ],
  }),
  tasks,
});
