// Expedition Station — The Decimal Dials (MA.4.2F-XP)
// Grade 4 · Math · Mechara. Main standard 4.2F (compare and order decimals
// using concrete and visual models to the hundredths). Also practices 4.2E
// (represent tenths and hundredths with models and money), 4.2G (relate
// decimals to fractions that name tenths and hundredths), and 4.2H (the
// decimal for a point on a number line). Decimal answers are numbers.
// Earth-true rule: Mechara and its factory are invented; every fact is real.
import { CREW, acts } from "./_shared.js";

const TENTHS_LINE = { type: "numline", min: 0, max: 1, step: 0.1, pick: true, title: "Speed dial · 0 to 1", label: "Dial setting" };

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Seven tenths, please", machine: "Speed Dial", icon: "dial", speaker: "kai",
    line: "Welcome to the Gearworks Factory! Every machine here has a dial from 0 to 1. The first conveyor belt needs to run at seven tenths.",
    question: "Set the speed dial to seven tenths. Tap it on the dial.",
    visual: TENTHS_LINE,
    hint: "The dial from 0 to 1 is cut into 10 equal jumps. Each jump is one tenth. Count 7 jumps from 0.",
    meter: { heat: 10, label: "Factory power +10%", story: "The first conveyor belt is rolling" },
    discovery: { id: "dime", name: "Where \"dime\" comes from", who: "Kai", fact: "The word dime comes from an old French word that means one tenth. A dime is one tenth of a dollar!" },
    answer: { kind: "number", value: 0.7 },
    rightFeedback: "Seven tenths is 0.7. The belt is rolling!",
    wrong: [
      { value: 7, hint: "7 is a whole number, way past 1. Seven TENTHS is 7 small jumps, written 0.7." },
      { value: 0.07, hint: "0.07 is seven hundredths, which is tiny. Seven tenths is 0.7." },
      { value: 0.3, hint: "That's 3 jumps. Count 7 jumps from 0: 0.1, 0.2, 0.3 ..." },
      { value: 0.8, hint: "One jump too far. Count again from 0." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The glowing panel", machine: "Hundredths Panel", icon: "grid", speaker: "nova",
    line: "This control panel has 100 little squares in a 10 by 10 grid. Each square is one hundredth of the panel. Right now, 3 full columns are glowing.",
    question: "Part 1: 3 columns of 10 squares are lit. What decimal of the panel is lit? Part 2: Which decimal names the same amount?",
    parts: [
      { type: "number", prompt: "Each square is 0.01 of the panel. The lit part is 3 columns of 10 squares. What decimal of the panel is lit?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 10, cols: 3, title: "Lit squares: 3 columns of 10", sideLabels: { top: "3 columns", left: "10 squares" } } },
      { type: "choice", prompt: "30 hundredths is the same as how many tenths?", choices: [
        { id: "a", text: "0.3, because 3 columns of 10 hundredths make 3 tenths" },
        { id: "b", text: "0.03, because there are 3 columns" },
        { id: "c", text: "3.0, because 3 columns are lit" },
        { id: "d", text: "30.0, because 30 squares are lit" },
      ] },
    ],
    hint: "Count the lit squares: 10, 20, 30. That's 30 out of 100, or 30 hundredths. Each full column is one tenth.",
    meter: { heat: 5, label: "Factory power +5%", story: "The control panel is glowing" },
    discovery: { id: "meterstick", name: "Meter sticks", who: "Nova", fact: "A meter stick has 100 centimeters. So each centimeter is one hundredth of a meter, or 0.01 meter." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.3 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "30 hundredths is 0.30, and that's the same as 3 tenths, or 0.3!",
    wrong: [
      { step: 1, value: 30, hint: "30 squares are lit, but each square is only 0.01. 30 hundredths is written 0.30." },
      { step: 1, value: 0.03, hint: "0.03 is just 3 squares. Here 3 whole COLUMNS are lit. That's 30 squares." },
      { step: 1, value: 3, hint: "3 would mean 3 whole panels! Only part of one panel is lit." },
      { step: 2, choice: "b", hint: "0.03 is only 3 little squares. Each column is 10 squares, one tenth." },
      { step: 2, choice: "c", hint: "3.0 means 3 whole panels. We only have part of one panel." },
      { step: 2, choice: "d", hint: "30.0 means 30 whole panels. The panel is not even full." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Coins for the parts machine", machine: "Parts Machine", icon: "cells", speaker: "kai",
    line: "The parts machine takes Earth coins. A new bolt costs $0.46. A dime is one tenth of a dollar. A penny is one hundredth.",
    question: "Part 1: Build $0.46 with dimes and pennies. Part 2: How many tenths of a dollar are in $0.46?",
    parts: [
      { type: "number", prompt: "Tap dimes and pennies to put exactly $0.46 in the tray.", unit: "dollars",
        visual: { type: "money", kinds: ["d", "p"], title: "Parts machine coin slot" } },
      { type: "number", prompt: "The 4 is in the tenths place. How many dimes (tenths of a dollar) are in $0.46?", unit: "dimes" },
    ],
    hint: "In $0.46, the 4 is in the tenths place and the 6 is in the hundredths place. Use 4 dimes and 6 pennies.",
    meter: { supplies: 1, label: "Gears tuned +1", story: "A new bolt drops out of the machine" },
    discovery: { id: "penny", name: "What's in a penny", who: "Kai", fact: "A U.S. penny made since 1982 is mostly zinc inside. Only a thin coat on the outside is copper." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.46 }, { kind: "number", value: 4 }] },
    rightFeedback: "4 dimes and 6 pennies make $0.46. That's 4 tenths and 6 hundredths of a dollar!",
    wrong: [
      { step: 1, value: 0.64, hint: "Switch them! 4 dimes (tenths) and 6 pennies (hundredths)." },
      { step: 1, value: 0.1, hint: "That's 10¢. Keep adding coins until you reach 46¢." },
      { step: 1, value: 46, hint: "46 cents is right! Type it in dollars: 0.46." },
      { step: 2, value: 6, hint: "6 is in the hundredths place. Those are pennies. Look at the tenths place." },
      { step: 2, value: 46, hint: "46 is the number of pennies it would take. How many DIMES?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The tiny oil drop", machine: "Oil Gauge", icon: "water", speaker: "nova",
    line: "The oil gauge on the robot arm reads 0.07. The arm's manual only uses fractions.",
    question: "Which fraction means the same as 0.07?",
    hint: "Read 0.07 out loud: seven hundredths. The 7 is in the hundredths place.",
    meter: { heat: 5, label: "Factory power +5%", story: "The robot arm is oiled" },
    choices: [
      { id: "a", text: "7/100" },
      { id: "b", text: "7/10" },
      { id: "c", text: "70/100" },
      { id: "d", text: "1/7" },
    ],
    answer: { kind: "choice", correct: "a" },
    rightFeedback: "0.07 is seven hundredths, so it equals 7/100.",
    wrong: [
      { choice: "b", hint: "7/10 is 0.7, seven tenths. Look where the 7 is in 0.07." },
      { choice: "c", hint: "70/100 is 0.70. That's ten times more than 0.07." },
      { choice: "d", hint: "Decimals name tenths or hundredths. 0.07 is 7 out of 100." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The wobbly needle", machine: "Fine-Tune Dial", icon: "snap", speaker: "vega",
    line: "Surprise! The main press is shaking. Its fine-tune dial zooms in between 2.3 and 2.4. We need it set to exactly 2.37. Then we check it against the old setting, 2.4.",
    question: "Part 1: Tap 2.37 on the fine-tune dial. Part 2: Compare 2.37 and 2.4. Part 3: What does the 7 in 2.37 mean?",
    parts: [
      { type: "number", prompt: "The dial goes from 2.3 to 2.4 in hundredths. Tap 2.37.",
        visual: { type: "numline", min: 2.3, max: 2.4, step: 0.01, pick: true, title: "Fine-tune dial · 2.3 to 2.4", label: "Press setting" } },
      { type: "choice", prompt: "Which is true?", choices: [
        { id: "a", text: "2.37 < 2.4" },
        { id: "b", text: "2.37 > 2.4" },
        { id: "c", text: "2.37 = 2.4" },
      ] },
      { type: "choice", prompt: "What does the 7 in 2.37 mean?", choices: [
        { id: "a", text: "7 hundredths, or 7/100" },
        { id: "b", text: "7 tenths, or 7/10" },
        { id: "c", text: "7 ones" },
        { id: "d", text: "7 wholes and 37 parts" },
      ] },
    ],
    hint: "Each tick is one hundredth. 2.37 is 7 ticks past 2.3. Is 2.37 before or after 2.4 on the dial?",
    meter: { heat: 10, label: "Factory power +10%", story: "The main press stops shaking" },
    discovery: { id: "gears", name: "Gear teeth", who: "Kai", fact: "Gears are wheels with teeth. When two gears fit together, one turns one way and the other turns the opposite way." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 2.37 }, { kind: "choice", correct: "a" }, { kind: "choice", correct: "a" }] },
    rightFeedback: "2.37 sits just before 2.4 on the dial, so 2.37 < 2.4. The 7 means 7 hundredths!",
    wrong: [
      { step: 1, value: 2.3, hint: "That's where the dial starts. Count 7 small ticks past 2.3." },
      { step: 1, value: 2.4, hint: "That's the end of the dial. 2.37 is a little before 2.4." },
      { step: 1, value: 2.7, hint: "2.7 is off this dial. Each tick here is one hundredth." },
      { step: 2, choice: "b", hint: "37 looks bigger than 4, but compare tenths first: 3 tenths is less than 4 tenths." },
      { step: 2, choice: "c", hint: "2.4 is the same as 2.40. Is 2.37 the same as 2.40?" },
      { step: 3, choice: "b", hint: "The 3 is in the tenths place. The 7 is one place farther right." },
      { step: 3, choice: "c", hint: "The 2 is in the ones place. The 7 is after the decimal point." },
      { step: 3, choice: "d", hint: "2.37 is 2 wholes, 3 tenths, and 7 hundredths. What does the 7 stand for?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Same glow, two names", machine: "Panel Checker", icon: "grid", speaker: "kai",
    line: "Panel A is cut into 10 strips, and 4 strips glow. That's 0.4. Panel B is cut into 100 squares. 4 full columns glow. That's 0.40. Hmm, which panel is brighter?",
    question: "Part 1: How many hundredths glow on Panel B? Part 2: Compare 0.4 and 0.40.",
    parts: [
      { type: "number", prompt: "Panel B shows 4 columns of 10 squares. How many hundredths glow?", unit: "hundredths",
        visual: { type: "array", mode: "show", style: "tiles", rows: 10, cols: 4, title: "Panel B: 4 columns of 10", sideLabels: { top: "4 columns", left: "10 squares" } } },
      { type: "choice", prompt: "Which is true?", choices: [
        { id: "a", text: "0.4 = 0.40" },
        { id: "b", text: "0.4 < 0.40" },
        { id: "c", text: "0.4 > 0.40" },
      ] },
    ],
    hint: "One column of 10 hundredths is the same as one tenth. So 4 columns is 40 hundredths and also 4 tenths.",
    meter: { heat: 5, label: "Factory power +5%", story: "Both panels glow the same" },
    discovery: { id: "welding", name: "Welding robots", who: "Nova", fact: "Many car factories use robot arms to weld metal parts together. A robot can make the same weld over and over without getting tired." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 40 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "40 hundredths is the same as 4 tenths. 0.4 = 0.40. Both panels glow the same!",
    wrong: [
      { step: 1, value: 4, hint: "4 columns glow, but each column has 10 squares. Count the squares: 10, 20, 30, 40." },
      { step: 1, value: 0.4, hint: "Yes, it's 0.40 of the panel! This part asks how many hundredths. Count the squares." },
      { step: 2, choice: "b", hint: "The extra 0 doesn't make it bigger. 4 strips out of 10 covers the same as 40 squares out of 100." },
      { step: 2, choice: "c", hint: "Both panels have the same amount glowing. 4 tenths and 40 hundredths match." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Line up the readings", machine: "Pressure Board", icon: "log", speaker: "nova",
    line: "Four steam pipes gave pressure readings. The safety robot needs them lined up from least to greatest.",
    question: "Put the pressure readings in order from least to greatest.",
    visual: { type: "bars", title: "Steam pipe pressure", categories: [
      { label: "Pipe A", value: 0.45 }, { label: "Pipe B", value: 0.3 }, { label: "Pipe C", value: 0.25 }, { label: "Pipe D", value: 0.4 },
    ], step: 0.25, max: 1, axis: "Pressure reading" },
    hint: "Write each one in hundredths: 0.45, 0.30, 0.25, 0.40. Now compare them like whole numbers of hundredths.",
    meter: { supplies: 1, label: "Gears tuned +1", story: "The steam pipes are in order" },
    items: [
      { id: "a", text: "Pipe A · 0.45" },
      { id: "b", text: "Pipe B · 0.3" },
      { id: "c", text: "Pipe C · 0.25" },
      { id: "d", text: "Pipe D · 0.4" },
    ],
    answer: { kind: "order", correct: ["c", "b", "d", "a"] },
    rightFeedback: "0.25 < 0.3 < 0.4 < 0.45. The shortest bar comes first!",
    wrong: [
      { position: 0, hint: "Which is least? Compare the tenths first. 0.25 has only 2 tenths." },
      { position: 1, hint: "0.3 is the same as 0.30. Is 0.30 more or less than 0.40?" },
      { position: 2, hint: "0.4 is 0.40 and 0.45 is 0.45. Which is less?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The more-digits debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Robot Nine reads 0.25 and Robot Four reads 0.3. 0.25 has more digits, and 25 is bigger than 3. So 0.25 is bigger!"',
    nova: 'Nova: "Not so fast! 0.3 is 3 tenths, which is 30 hundredths. 0.25 is only 25 hundredths. So 0.3 is bigger."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Compare the tenths place first. Or write both in hundredths: 0.25 and 0.30.",
    meter: { heat: 5, label: "Factory power +5%", story: "The crew agrees on the robot readings" },
    discovery: { id: "hundredths", name: "Hundredths of a second", who: "Nova", fact: "In swimming races, times are measured to the hundredth of a second. Some races are won by just 0.01 second!" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 0.3 is 30 hundredths, and 30 hundredths is more than 25 hundredths." },
      { id: "B", text: "Nova, because 3 is an odd number." },
      { id: "C", text: "Kai. A decimal with more digits is always bigger." },
      { id: "D", text: "Kai. 25 is bigger than 3, so 0.25 is bigger than 0.3." },
    ],
    writtenPrompt: "Tell Kai in your own words why 0.3 is greater than 0.25.",
    debateHints: {
      wrongWho: "Shade 0.25 and 0.3 on hundredths grids. 0.3 fills 3 whole columns. 0.25 fills only 2 columns and half of another.",
      wrongReason: "Right person, check the reason. Think about tenths and hundredths.",
      right: "Nova is right. 0.3 = 0.30, and 30 hundredths is more than 25 hundredths. More digits doesn't mean bigger!",
    },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Dimes or pennies?", machine: "Coin Slot", icon: "cells", speaker: "vega",
    line: "The snack robot takes coins. Kai paid with 5 dimes. Nova paid with 45 pennies. Kai says his 5 coins can't beat her 45 coins.",
    question: "Part 1: How much is 5 dimes? Part 2: Compare $0.50 and $0.45. Part 3: Build $0.5 with the fewest dimes.",
    parts: [
      { type: "number", prompt: "How much are Kai's 5 dimes worth? Type your answer in dollars, like 0.85.", unit: "dollars",
        visual: { type: "money", mode: "show", show: ["d", "d", "d", "d", "d"], title: "Kai's coins" } },
      { type: "choice", prompt: "Who paid more?", choices: [
        { id: "a", text: "Kai. $0.50 > $0.45, even with fewer coins." },
        { id: "b", text: "Nova. 45 coins is more than 5 coins." },
        { id: "c", text: "They paid the same." },
      ] },
      { type: "number", prompt: "0.5 of a dollar is 5 tenths of a dollar. Build it with dimes.", unit: "dollars",
        visual: { type: "money", kinds: ["d", "p"], title: "Coin slot" } },
    ],
    hint: "Each dime is one tenth of a dollar, $0.10. 5 dimes is 5 tenths, $0.50. Now compare 50 hundredths and 45 hundredths.",
    meter: { heat: 5, label: "Factory power +5%", story: "The snack robot hands out treats" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.5 }, { kind: "choice", correct: "a" }, { kind: "number", value: 0.5 }] },
    rightFeedback: "5 dimes = $0.50, which is 0.5 of a dollar. $0.50 > $0.45, so Kai paid more!",
    wrong: [
      { step: 1, value: 5, hint: "There are 5 coins, but each dime is worth 10¢. Count by 10s." },
      { step: 1, value: 0.05, hint: "That's 5 pennies. Each dime is a tenth of a dollar: 0.1, 0.2, 0.3 ..." },
      { step: 1, value: 50, hint: "50 cents is right! Type it in dollars: 0.50." },
      { step: 2, choice: "b", hint: "Count the value, not the coins. 50¢ or 45¢, which is more?" },
      { step: 2, choice: "c", hint: "$0.50 is 50 hundredths. $0.45 is 45 hundredths. Are they equal?" },
      { step: 3, value: 0.05, hint: "That's 5 pennies, 5 hundredths. You need 5 tenths. Use dimes." },
      { step: 3, value: 0.45, hint: "That's 45¢. 0.5 is the same as 0.50. Add one more dime." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Conveyor speed trap", machine: "Speed Tracker", icon: "quake", speaker: "vega",
    line: "Surprise! Three conveyor belts are racing out of control. The speed tracker shows 0.62, 0.58, and 0.6. The fastest belt must be stopped first!",
    question: "Part 1: Tap 0.62 on the speed tracker. Part 2: Which belt is fastest? Part 3: Which fraction equals 0.58?",
    data: {
      title: "Belt speeds",
      columns: ["Belt", "Speed reading"],
      rows: [["Red belt", "0.62"], ["Blue belt", "0.58"], ["Green belt", "0.6"]],
    },
    parts: [
      { type: "number", prompt: "The tracker goes from 0.5 to 0.7 in hundredths. Tap the Red belt's speed, 0.62.",
        visual: { type: "numline", min: 0.5, max: 0.7, step: 0.01, labelEvery: 5, pick: true, marks: [{ value: 0.58, label: "Blue" }, { value: 0.6, label: "Green" }], title: "Speed tracker · 0.5 to 0.7", label: "Belt speed" } },
      { type: "choice", prompt: "Which belt is fastest?", choices: [
        { id: "red", text: "Red belt, 0.62" },
        { id: "blue", text: "Blue belt, 0.58" },
        { id: "green", text: "Green belt, 0.6" },
      ] },
      { type: "choice", prompt: "Which fraction equals the Blue belt's speed, 0.58?", choices: [
        { id: "a", text: "58/100" },
        { id: "b", text: "58/10" },
        { id: "c", text: "5/8" },
        { id: "d", text: "8/100" },
      ] },
    ],
    hint: "On the tracker, numbers get bigger as you go right. 0.6 is 0.60. Which reading is farthest right?",
    meter: { heat: 10, label: "Factory power +10%", story: "The runaway belts are stopped" },
    discovery: { id: "assemblyline", name: "The moving assembly line", who: "Kai", fact: "In 1913, a car factory started using a moving assembly line. Building one car went from more than 12 hours to about 1 and a half hours." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.62 }, { kind: "choice", correct: "red" }, { kind: "choice", correct: "a" }] },
    rightFeedback: "0.58 < 0.60 < 0.62. The Red belt is fastest, and 0.58 = 58/100. Belts stopped!",
    wrong: [
      { step: 1, value: 0.6, hint: "That's the Green belt. 0.62 is 2 small ticks past 0.6." },
      { step: 1, value: 0.58, hint: "That's the Blue belt. 0.62 is to the right of 0.6." },
      { step: 1, value: 0.7, hint: "That's the end of the tracker. 0.62 is 2 ticks past 0.6." },
      { step: 2, choice: "blue", hint: "58 looks big, but 0.58 has only 5 tenths. The others have 6 tenths." },
      { step: 2, choice: "green", hint: "0.6 is 0.60. Is 0.60 more than 0.62?" },
      { step: 3, choice: "b", hint: "58/10 is more than 5 wholes! 0.58 is 58 hundredths." },
      { step: 3, choice: "c", hint: "Decimals name tenths or hundredths. 0.58 is 58 out of 100." },
      { step: 3, choice: "d", hint: "That's only the 8. The whole number is 58 hundredths." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Half-power sort", machine: "Sort Bay", icon: "cells", speaker: "nova",
    line: "The factory is switching to a half-power plan. Every robot must be sorted. Is its battery reading more than 0.5, or less than 0.5?",
    question: "Sort each robot's battery reading.",
    hint: "Think of 0.5 as 0.50, fifty hundredths. Write each reading in hundredths and compare it to 50.",
    meter: { supplies: 1, label: "Gears tuned +1", story: "Every robot is sorted" },
    discovery: { id: "vacuum", name: "Robot vacuums", who: "Nova", fact: "Many robot vacuums can find their way back to their charging dock by themselves when their battery gets low." },
    answer: { kind: "sort", bins: { s1: "more", s2: "less", s3: "less", s4: "more", s5: "more", s6: "less" } },
    rightFeedback: "Every robot is sorted! Comparing to 0.50 made it easy.",
    sort: {
      bins: [
        { id: "more", label: "More than 0.5" },
        { id: "less", label: "Less than 0.5" },
      ],
      items: [
        { id: "s1", label: "Lift bot · 0.7" },
        { id: "s2", label: "Sweeper bot · 0.45" },
        { id: "s3", label: "Paint bot · 0.09" },
        { id: "s4", label: "Welder bot · 0.51" },
        { id: "s5", label: "Loader bot · 0.6" },
        { id: "s6", label: "Drill bot · 0.38" },
      ],
    },
    wrong: [
      { item: "s1", hint: "0.7 is 70 hundredths. Is 70 more or less than 50?" },
      { item: "s2", hint: "0.45 has more digits, but it's only 45 hundredths. That's less than 50." },
      { item: "s3", hint: "0.09 is just 9 hundredths. That's a tiny bit of battery." },
      { item: "s4", hint: "0.51 is 51 hundredths. Just 1 hundredth more than 0.50!" },
      { item: "s5", hint: "0.6 is 60 hundredths. Is that more or less than 50?" },
      { item: "s6", hint: "0.38 is 38 hundredths. Compare it to 50." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Fix Kai's lineup", machine: "Repair", icon: "log", speaker: "kai",
    line: 'I lined up three sensor readings from least to greatest: "0.6, 0.8, 0.15." I put 0.15 last because 15 is the biggest number!',
    question: "Part 1: What went wrong? Part 2: Put the readings in the right order, least to greatest.",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He compared 15 to 6 and 8 like whole numbers. 0.15 is only 1 tenth and 5 hundredths." },
        { id: "b", text: "He should have put 0.8 first." },
        { id: "c", text: "Decimals can't be put in order." },
        { id: "d", text: "Nothing. 0.15 really is the greatest." },
      ] },
      { type: "order", prompt: "Put the readings in order from least to greatest.", items: [
        { id: "six", text: "0.6" },
        { id: "eight", text: "0.8" },
        { id: "fifteen", text: "0.15" },
      ] },
    ],
    hint: "Compare the tenths place first. 0.15 has 1 tenth. 0.6 has 6 tenths. 0.8 has 8 tenths.",
    meter: { supplies: 1, label: "Gears tuned +1", story: "Kai's lineup is fixed" },
    discovery: { id: "echo", name: "Robot distance sensors", who: "Kai", fact: "Some robots send out sound or light and time how long it takes to bounce back. That tells them how far away things are." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "order", correct: ["fifteen", "six", "eight"] }] },
    rightFeedback: "Fixed! 0.15 < 0.6 < 0.8. That's 15, 60, and 80 hundredths.",
    wrong: [
      { step: 1, choice: "b", hint: "0.8 has the most tenths. Should the biggest go first in least to greatest?" },
      { step: 1, choice: "c", hint: "Decimals can be ordered, just like whole numbers. Compare place by place." },
      { step: 1, choice: "d", hint: "Write each in hundredths: 0.60, 0.80, 0.15. Is 15 hundredths the most?" },
      { step: 2, position: 0, hint: "Which has the fewest tenths? That one comes first." },
      { step: 2, position: 1, hint: "6 tenths is less than 8 tenths." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Fractions on the fuel tanks", machine: "Fuel Gauge", icon: "water", speaker: "nova",
    line: "The old fuel tanks are labeled with fractions. Tank A is 43/100 full. Tank B is 6/10 full. The new gauges only show decimals.",
    question: "Part 1: Write 43/100 as a decimal. Part 2: Write 6/10 as a decimal. Part 3: Which tank has more fuel?",
    data: {
      title: "Fuel tank labels",
      columns: ["Tank", "Old label", "New gauge"],
      rows: [["Tank A", "43/100", "?"], ["Tank B", "6/10", "?"]],
    },
    parts: [
      { type: "number", prompt: "Write 43/100 as a decimal." },
      { type: "number", prompt: "Write 6/10 as a decimal." },
      { type: "choice", prompt: "Which tank has more fuel?", choices: [
        { id: "b", text: "Tank B. 0.6 = 0.60, and 0.60 > 0.43." },
        { id: "a", text: "Tank A. 43 is bigger than 6." },
        { id: "same", text: "They have the same amount." },
      ] },
    ],
    hint: "43/100 is forty-three hundredths. 6/10 is six tenths. Write 6 tenths as hundredths to compare.",
    meter: { heat: 5, label: "Factory power +5%", story: "The fuel gauges are updated" },
    discovery: { id: "ramp", name: "Ramps are machines", who: "Nova", fact: "A ramp is a simple machine. It lets you raise a heavy load by pushing it a longer way with less force." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.43 }, { kind: "number", value: 0.6 }, { kind: "choice", correct: "b" }] },
    rightFeedback: "43/100 = 0.43 and 6/10 = 0.6 = 0.60. Tank B has more fuel!",
    wrong: [
      { step: 1, value: 4.3, hint: "4.3 is more than 4 wholes. 43/100 is less than one whole tank." },
      { step: 1, value: 43, hint: "43 hundredths is written with a decimal point: 0.43." },
      { step: 2, value: 0.06, hint: "0.06 is six hundredths. 6/10 is six TENTHS." },
      { step: 2, value: 6, hint: "6 would be 6 whole tanks. 6/10 is 6 tenths, written 0.6." },
      { step: 3, choice: "a", hint: "43 hundredths vs 60 hundredths. Which is more?" },
      { step: 3, choice: "same", hint: "0.43 and 0.60 are not the same. Compare the tenths: 4 and 6." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Read the gauge needles", machine: "Gauge Wall", icon: "trail", speaker: "vega",
    line: "Two gauges on the factory wall have needles but no numbers. The crew needs to read them for the logbook.",
    question: "Part 1: What decimal is at needle A? Part 2: What decimal is at needle B?",
    parts: [
      { type: "number", prompt: "This gauge goes from 1 to 2 in tenths. What decimal is at needle A?",
        visual: { type: "numline", min: 1, max: 2, step: 0.1, labelEvery: 10, marks: [{ value: 1.4, label: "A" }], title: "Gauge 1 · 1 to 2", label: "Tenths" } },
      { type: "number", prompt: "This gauge goes from 3.5 to 3.6 in hundredths. What decimal is at needle B?",
        visual: { type: "numline", min: 3.5, max: 3.6, step: 0.01, labelEvery: 10, marks: [{ value: 3.56, label: "B" }], title: "Gauge 2 · 3.5 to 3.6", label: "Hundredths" } },
    ],
    hint: "Count the jumps from the start. On gauge 1, each jump is 0.1. On gauge 2, each jump is 0.01.",
    meter: { supplies: 1, label: "Gears tuned +1", story: "The logbook is filled in" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 1.4 }, { kind: "number", value: 3.56 }] },
    rightFeedback: "Needle A is at 1.4, and needle B is at 3.56. The logbook is done!",
    wrong: [
      { step: 1, value: 0.4, hint: "Don't forget the whole number. This gauge starts at 1." },
      { step: 1, value: 1.04, hint: "Each jump on this gauge is one tenth, not one hundredth. 4 jumps is 1.4." },
      { step: 1, value: 1.6, hint: "Count the jumps from 1, not back from 2." },
      { step: 2, value: 3.6, hint: "That's the end of the gauge. Count the small jumps from 3.5." },
      { step: 2, value: 3.506, hint: "Each jump is one hundredth. 6 jumps past 3.50 is 3.56." },
      { step: 2, value: 0.56, hint: "Don't forget the 3 wholes. This gauge starts at 3.5." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The master dial", machine: "Master Dial", icon: "relay", speaker: "vega",
    line: "This is it! The master dial runs the whole factory. Four test readings came in: 1.9, 1.09, 1.1, and 1.19. Surprise! Kai's note says \"1.09 is the biggest, it has the most digits.\" The master dial must be set to the least reading.",
    question: "Part 1: Compare 1.09 and 1.9. Part 2: Order all four readings least to greatest. Part 3: Pay the power fee of $1.09. Part 4: Which is the same as 1.09?",
    parts: [
      { type: "choice", prompt: "Which is true?", choices: [
        { id: "a", text: "1.09 < 1.9" },
        { id: "b", text: "1.09 > 1.9" },
        { id: "c", text: "1.09 = 1.9" },
      ] },
      { type: "order", prompt: "Put the readings in order from least to greatest.", items: [
        { id: "r19", text: "1.9" },
        { id: "r109", text: "1.09" },
        { id: "r11", text: "1.1" },
        { id: "r119", text: "1.19" },
      ] },
      { type: "number", prompt: "The power fee is the least reading in dollars. Build $1.09.", unit: "dollars",
        visual: { type: "money", kinds: ["b1", "d", "p"], title: "Power fee tray" } },
      { type: "choice", prompt: "Which is the same as 1.09?", choices: [
        { id: "a", text: "1 and 9/100" },
        { id: "b", text: "1 and 9/10" },
        { id: "c", text: "109/10" },
        { id: "d", text: "19/100" },
      ] },
    ],
    hint: "The ones are all 1, so compare the tenths: 1.09 has 0 tenths, 1.1 has 1 tenth, 1.19 has 1 tenth, 1.9 has 9 tenths. Then check hundredths.",
    meter: { heat: 15, label: "Factory power +15%", story: "The whole factory hums at full power" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["r109", "r11", "r119", "r19"] },
      { kind: "number", value: 1.09 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "1.09 < 1.1 < 1.19 < 1.9. The master dial is set to 1.09, and the Gearworks Factory is humming. Great decimal work, specialist!",
    wrong: [
      { step: 1, choice: "b", hint: "More digits doesn't mean bigger. 1.09 has 0 tenths, and 1.9 has 9 tenths." },
      { step: 1, choice: "c", hint: "1.9 is 1.90. Is 1.09 the same as 1.90?" },
      { step: 2, position: 0, hint: "Which reading has 0 tenths? It is the least." },
      { step: 2, position: 1, hint: "1.1 is 1.10 and 1.19 is 1.19. Which is less?" },
      { step: 2, position: 2, hint: "1.19 has 1 tenth. 1.9 has 9 tenths. Which is less?" },
      { step: 3, value: 1.9, hint: "That's $1.90. The fee is $1.09: 1 dollar, 0 dimes, 9 pennies." },
      { step: 3, value: 1.1, hint: "That's $1.10. Take out a dime and add 9 pennies." },
      { step: 3, value: 109, hint: "Those are the right digits! Type it in dollars: 1.09." },
      { step: 4, choice: "b", hint: "1 and 9/10 is 1.9. In 1.09, the 9 is in the hundredths place." },
      { step: 4, choice: "c", hint: "109/10 is more than 10 wholes! 1.09 is just a little more than 1." },
      { step: 4, choice: "d", hint: "19/100 is less than 1. 1.09 has 1 whole plus 9 hundredths." },
    ],
  },
};

export default {
  id: "MA.4.2F-XP",
  standard: "MA.4.2F-XP",
  engine: "expedition_station",
  title: "The Decimal Dials",
  planet: "Mechara",
  outpost: "Gearworks Factory · tune-up day",
  grade: 4,
  subject: "Math",
  teks: "4.2F",
  supportingTeks: ["4.2E", "4.2G", "4.2H"],
  skillsChip: "4.2F · Compare and order decimals",
  iCan: "I can compare and order decimals to the hundredths using grids, number lines, and money, and match decimals to fractions.",
  blurb: "The Gearworks Factory on Mechara runs on decimal dials. The crew needs help reading, comparing, and ordering tenths and hundredths to tune every machine.",
  mission: "Tune the robot factory's decimal dials so every machine runs at just the right setting.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.2F · MECHARA GEARWORKS",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Factory power", heatUnit: "%", supplies: "Gears tuned", suppliesUnit: "gears" },
  journalMax: 10,
  earthTrue: "Mechara and the Gearworks Factory are invented. Every fact and every bit of math works the way it does on Earth.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're at the Gearworks Factory on Mechara, the robot city.",
    "Every machine here runs on a decimal dial. The dials show tenths and hundredths, and some are set all wrong.",
    "Help Kai and Nova read, compare, and order the dials so the factory runs smoothly. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Read the dials", "Act 2 · Compare the readings", "Act 3 · Set the master dial"],
    completes: [
      "The first dials are tuned and the press is steady, {firstName}!",
      "Every reading is compared and the runaway belts are stopped, {firstName}!",
      "The master dial is set, {firstName}! The Gearworks Factory is running at full power.",
    ],
    teasers: [
      "Next on Mechara: the machines give readings that need comparing. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: the master dial that runs the whole factory. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The factory machines are sending lots of decimal readings.",
      "Kai has a funny idea about which decimals are bigger, so let's check it together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. It's time to set the master dial.",
      "Sort the robots, fix Kai's lineup, and find the right setting for the whole factory.",
    ],
  }),
  tasks,
};
