// Expedition Station — The Ecosystem Balance (SCI.5.12A-XP)
// Grade 5 · Science · Solara. Main standard 5.12A (observe and describe how
// a variety of organisms survive by interacting with biotic and abiotic
// factors in a healthy ecosystem); also practices 5.12B (predict how changes
// in the ecosystem affect the cycling of matter and flow of energy in a food
// web), 5.1A (ask questions and define problems), 5.2B (analyze data to find
// patterns), 5.2D (evaluate data and predict), 5.3A (develop explanations
// supported by evidence), 5.3B (communicate explanations and solutions),
// 5.3C (listen to and evaluate others' explanations), 5.5E (systems and
// system models), 5.5F (flow of energy and cycling of matter), 5.5G
// (stability and change).
//
// Earth-true rule: every organism is a real rainforest organism and every
// interaction happens in real tropical rainforests on Earth.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Living or not?", machine: "Field Scanner", icon: "scan", speaker: "nova",
    line: "The field scanner splits everything it finds into two groups. Biotic things are living or were once living. Abiotic things were never alive.",
    question: "Sort each thing the scanner found: biotic or abiotic?",
    hint: "Is it alive now, or was it ever alive? If yes, it's biotic.",
    meter: { heat: 15, label: "Balance +15%", story: "The scanner is calibrated" },
    answer: { kind: "sort", bins: { b1: "biotic", b2: "abiotic", b3: "biotic", b4: "abiotic", b5: "biotic", b6: "abiotic", b7: "biotic", b8: "abiotic" } },
    rightFeedback: "Living and once-living things are biotic. Sunlight, rain, soil minerals, and warm air are abiotic.",
    sort: {
      bins: [{ id: "biotic", label: "Biotic (living or once living)" }, { id: "abiotic", label: "Abiotic (never alive)" }],
      items: [
        { id: "b1", label: "Kapok tree" },
        { id: "b2", label: "Sunlight" },
        { id: "b3", label: "Mushroom on a log" },
        { id: "b4", label: "Rainwater" },
        { id: "b5", label: "Fallen dead leaf" },
        { id: "b6", label: "Minerals in the soil" },
        { id: "b7", label: "Capybara" },
        { id: "b8", label: "Warm, humid air" },
      ],
    },
    wrong: [
      { item: "b5", hint: "The leaf isn't alive now. But was it ever part of a living tree?" },
      { item: "b3", hint: "A mushroom isn't a plant or an animal, but it grows and needs food. It's a living fungus." },
      { item: "b4", hint: "Living things need water, but was the water itself ever alive?" },
      { item: "b2", hint: "Plants use sunlight, but sunlight was never alive." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Who does what?", machine: "Food Web Board", icon: "cells", speaker: "kai",
    line: "The food web board has three rows: producers, consumers, and decomposers. I need every organism in the right row.",
    question: "Sort each organism by its job in the ecosystem.",
    hint: "Producers make their own food from sunlight. Consumers eat other living things. Decomposers break down dead things.",
    meter: { heat: 10, label: "Balance +10%", story: "The food web board is sorted" },
    discovery: { id: "rootfungi", name: "Root helpers", who: "Nova", fact: "Many fungi grow on and around tree roots. They help the tree soak up water and nutrients, and the tree shares some of its sugar with them." },
    answer: { kind: "sort", bins: { r1: "producer", r2: "consumer", r3: "decomposer", r4: "producer", r5: "consumer", r6: "decomposer", r7: "consumer" } },
    rightFeedback: "Trees and orchids are producers. Animals are consumers. Fungi and bacteria are decomposers.",
    sort: {
      bins: [{ id: "producer", label: "Producer" }, { id: "consumer", label: "Consumer" }, { id: "decomposer", label: "Decomposer" }],
      items: [
        { id: "r1", label: "Cecropia tree" },
        { id: "r2", label: "Three-toed sloth" },
        { id: "r3", label: "Shelf fungus on a dead log" },
        { id: "r4", label: "Orchid" },
        { id: "r5", label: "Jaguar" },
        { id: "r6", label: "Soil bacteria" },
        { id: "r7", label: "Blue morpho caterpillar" },
      ],
    },
    wrong: [
      { item: "r3", hint: "Fungi can't make food from sunlight. They get food by breaking down dead things." },
      { item: "r7", hint: "A caterpillar munches leaves. Does it make its own food, or eat it?" },
      { item: "r6", hint: "Bacteria are tiny, but they have a big job: breaking down dead plants and animals." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Follow the energy", machine: "Food Web Board", icon: "trail", speaker: "vega",
    line: "Every food chain on Solara starts in the same place. Build this one from the start of the energy to the top.",
    question: "Put the food chain in order, from where the energy starts to the top predator.",
    hint: "Where does a plant get the energy to make its food? Then who eats whom?",
    meter: { supplies: 1, label: "Web links +1", story: "The first food chain is built" },
    answer: { kind: "order", correct: ["sun", "cecropia", "sloth", "harpy"] },
    items: [
      { id: "sloth", text: "Three-toed sloth eats cecropia leaves" },
      { id: "harpy", text: "Harpy eagle catches the sloth" },
      { id: "sun", text: "The Sun shines on the canopy" },
      { id: "cecropia", text: "Cecropia tree uses sunlight to make food" },
    ],
    rightFeedback: "Sun, cecropia tree, sloth, harpy eagle. The energy moves up the chain one step at a time.",
    wrong: [
      { position: 0, hint: "The energy doesn't start with a living thing. What gives plants the energy to make food?" },
      { position: 1, hint: "After the Sun, which organism can capture that energy and make food?" },
      { position: 2, hint: "The eagle eats the sloth, so the sloth has to come before the eagle." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Plants in the treetops", machine: "Canopy Lift", icon: "dial", speaker: "nova",
    line: "Up in the canopy, I found orchids growing on tree branches, high above the ground. Their roots hang in the air!",
    question: "Why does an orchid grow high on a branch instead of on the forest floor?",
    hint: "What does a producer need to make its food? Where is there more of it?",
    meter: { heat: 10, label: "Balance +10%", story: "Nova's canopy survey is done" },
    discovery: { id: "epiphytes", name: "Air plants", who: "Nova", fact: "Plants that grow on other plants are called epiphytes. Many orchids and ferns are epiphytes. They get water from rain and damp air instead of from soil." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "More sunlight reaches the branches high up, and the orchid needs sunlight to make food." },
      { id: "b", text: "It's hiding from the rain." },
      { id: "c", text: "Orchids eat the tree's bark." },
      { id: "d", text: "The forest floor has too much sunlight." },
    ],
    rightFeedback: "Sunlight is an abiotic factor. The orchid climbs toward it by growing on a biotic factor: the tree.",
    wrong: [
      { choice: "b", hint: "Orchids up high get lots of rain. What do they get more of up there?" },
      { choice: "c", hint: "Orchids are producers. They make their own food. What do they need to do that?" },
      { choice: "d", hint: "The thick canopy blocks light. Is the forest floor bright or dim?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The fallen giant", machine: "Field Scanner", icon: "quake", speaker: "vega",
    line: "Surprise! A storm knocked down a giant kapok tree last night. Kai wants to haul it away, but Nova says the forest needs it.",
    question: "Part 1: Pick every organism that will help break down the fallen tree. Part 2: What happens to the matter in the tree? Part 3: Put the steps of the cycle in order.",
    parts: [
      { type: "multi", prompt: "Pick every organism that will help break down the tree.", choices: [
        { id: "fungi", text: "Fungi" },
        { id: "termites", text: "Termites" },
        { id: "bacteria", text: "Bacteria" },
        { id: "jaguar", text: "Jaguar" },
        { id: "orchid", text: "Orchid" },
      ] },
      { type: "choice", prompt: "What happens to the matter in the fallen tree?", choices: [
        { id: "a", text: "Decomposers break it down, and the nutrients go back into the soil for new plants." },
        { id: "b", text: "It disappears forever." },
        { id: "c", text: "It turns back into sunlight." },
        { id: "d", text: "It stays exactly the same for thousands of years." },
      ] },
      { type: "order", prompt: "Put the cycle in order.", items: [
        { id: "roots", text: "A new seedling's roots take in the nutrients" },
        { id: "falls", text: "The tree dies and falls" },
        { id: "soil", text: "Nutrients from the wood go into the soil" },
        { id: "decomp", text: "Fungi, termites, and bacteria break down the wood" },
      ] },
    ],
    hint: "Who eats dead things? Where do the nutrients go after that?",
    meter: { heat: 10, label: "Balance +10%", story: "The fallen tree stays to feed the forest" },
    discovery: { id: "fastrot", name: "Fast decomposers", who: "Nova", fact: "In a warm, wet rainforest, a fallen leaf can break down in just a few months. In a cold forest, the same leaf can take years." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["fungi", "termites", "bacteria"] },
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["falls", "decomp", "soil", "roots"] },
    ] },
    rightFeedback: "The old tree will feed a whole new generation of plants. Matter cycles!",
    wrong: [
      { step: 1, pick: "jaguar", hint: "Jaguars hunt living animals. They don't eat dead wood." },
      { step: 1, pick: "orchid", hint: "Orchids are producers. They make food from sunlight, not from dead wood." },
      { step: 1, missing: true, hint: "There are three decomposers in the list." },
      { step: 2, choice: "b", hint: "Matter doesn't vanish. Where do the tree's nutrients end up?" },
      { step: 2, choice: "c", hint: "Energy comes from the Sun, but matter doesn't turn into sunlight. Where do the nutrients go?" },
      { step: 2, choice: "d", hint: "Decomposers are busy in a warm, wet forest. Does the log last forever?" },
      { step: 3, position: 0, hint: "Decomposers can only start after the tree dies." },
      { step: 3, position: 1, hint: "The nutrients can't reach the soil until something breaks down the wood." },
      { step: 3, position: 2, hint: "The seedling can only take in nutrients after they're in the soil." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Do we need decomposers?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Decomposers aren\'t important. They don\'t even eat living things. The forest would be fine without them."',
    nova: 'Nova: "Without decomposers, dead stuff would pile up, and the nutrients would never go back into the soil."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the fallen kapok tree. What would happen to it with no decomposers?",
    meter: { heat: 5, label: "Balance +5%", story: "Kai thanks the mushrooms" },
    discovery: { id: "thinsoil", name: "Thin soil", who: "Nova", fact: "Rainforest soil is thin and has few nutrients. Most of the nutrients are stored in living plants, and decomposers quickly recycle them when things die." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Decomposers break down dead things and return nutrients to the soil. Plants need those nutrients to grow, and every other organism depends on plants." },
      { id: "B", text: "Nova, because mushrooms look cool." },
      { id: "C", text: "Kai. Only animals that hunt are important." },
      { id: "D", text: "Kai. Dead things just disappear on their own." },
    ],
    writtenPrompt: "Tell Kai in your own words why the forest needs decomposers.",
    debateHints: {
      wrongWho: "Picture a forest with no decomposers for 100 years. What would pile up? What would plants be missing?",
      wrongReason: "Right person, check the reason. What job do decomposers do for the whole food web?",
      right: "Nova is right — decomposers keep matter cycling back to the plants.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Where did the energy come from?", machine: "Food Web Board", icon: "battery", speaker: "nova",
    line: "An ocelot just caught an agouti. The agouti had been eating fallen fruit from a palm tree.",
    question: "Where did the energy in the ocelot's meal first come from?",
    hint: "Trace it back. The ocelot ate the agouti. What did the agouti eat? Where did the palm get its energy?",
    meter: { heat: 5, label: "Balance +5%", story: "The energy trail is traced" },
    discovery: { id: "photosynthesis", name: "Making food from light", who: "Nova", fact: "Plants use energy from sunlight to turn water and carbon dioxide from the air into sugar. This is called photosynthesis, and it gives off the oxygen we breathe." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "The agouti" },
      { id: "b", text: "The soil" },
      { id: "c", text: "The Sun" },
      { id: "d", text: "The river water" },
    ],
    rightFeedback: "Sun to palm to agouti to ocelot. All the energy in the chain started as sunlight.",
    wrong: [
      { choice: "a", hint: "The agouti passed the energy on. But where did the agouti's food get its energy?" },
      { choice: "b", hint: "Soil gives plants nutrients (matter), not energy. What gives a plant energy?" },
      { choice: "d", hint: "Plants need water, but water isn't where the energy comes from." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "What the kapok needs", machine: "Field Scanner", icon: "water", speaker: "kai",
    line: "We're planting a young kapok tree where the old one fell. I want to make sure it gets everything it needs from its surroundings.",
    question: "Pick every abiotic factor the young kapok tree needs to survive and grow.",
    items: [
      { id: "sun", text: "Sunlight" },
      { id: "water", text: "Water" },
      { id: "air", text: "Carbon dioxide from the air" },
      { id: "minerals", text: "Nutrients in the soil" },
      { id: "toucan", text: "A toucan" },
      { id: "jaguar", text: "A jaguar" },
    ],
    hint: "Abiotic means never alive. Which of these was never alive, and does a tree use it?",
    meter: { supplies: 1, label: "Web links +1", story: "The young kapok is planted" },
    answer: { kind: "multi", correct: ["sun", "water", "air", "minerals"] },
    rightFeedback: "Sunlight, water, air, and soil nutrients. The tree needs all four abiotic factors.",
    wrong: [
      { pick: "toucan", hint: "A toucan is alive, so it's biotic, not abiotic." },
      { pick: "jaguar", hint: "A jaguar is a living thing, so it's biotic. And trees don't need jaguars to grow." },
      { missing: true, hint: "There are four abiotic factors the tree needs. Think about what a plant uses to make food and grow." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Kai's backward web", machine: "Food Web Board", icon: "log", speaker: "kai",
    line: "I drew our food chain with arrows: harpy eagle → sloth → cecropia tree. Nova says something's off.",
    question: "Part 1: What went wrong with Kai's arrows? Part 2: Which arrow is drawn the right way?",
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "The arrows point backward. In a food web, arrows point from the food to the eater, the way the energy flows." },
        { id: "b", text: "He left out the jaguar." },
        { id: "c", text: "Arrows should point from the biggest animal to the smallest." },
        { id: "d", text: "Food webs shouldn't have arrows at all." },
      ] },
      { type: "choice", prompt: "Which arrow is drawn the right way?", choices: [
        { id: "a", text: "Cecropia tree → sloth" },
        { id: "b", text: "Sloth → cecropia tree" },
        { id: "c", text: "Harpy eagle → sloth" },
        { id: "d", text: "Sloth → Sun" },
      ] },
    ],
    hint: "Energy moves from the food into the animal that eats it. Which way should the arrow point?",
    meter: { supplies: 1, label: "Web links +1", story: "Kai's arrows point the right way" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Now the arrows follow the energy: cecropia tree → sloth → harpy eagle.",
    wrong: [
      { step: 1, choice: "b", hint: "The jaguar isn't in this chain. Look at which way the arrows point." },
      { step: 1, choice: "c", hint: "Size doesn't decide it. Arrows show the path the energy takes." },
      { step: 1, choice: "d", hint: "Arrows are useful. They show which way energy flows. Kai's just point the wrong way." },
      { step: 2, choice: "b", hint: "Does the tree get energy by eating the sloth? The arrow points to the eater." },
      { step: 2, choice: "c", hint: "That's Kai's backward arrow. Does the sloth eat the eagle?" },
      { step: 2, choice: "d", hint: "The Sun gives energy. It never gets energy from a sloth." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The missing jaguars", machine: "Population Log", icon: "static", speaker: "vega",
    line: "Surprise! The riverbank looks bare. Nova pulled five years of population counts from the river station. Something changed, and it spread through the food web.",
    question: "Part 1: What happened to jaguars and capybaras? Part 2: Why did the capybaras increase? Part 3: Why did the grass patches shrink? Part 4: Why did capybaras drop in Year 5?",
    data: {
      title: "River station counts",
      columns: ["Year", "Jaguars", "Capybaras", "Riverside grass patches"],
      rows: [
        ["Year 1", "12", "80", "500"],
        ["Year 2", "9", "115", "460"],
        ["Year 3", "6", "150", "370"],
        ["Year 4", "4", "190", "250"],
        ["Year 5", "3", "160", "170"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What pattern do you see from Year 1 to Year 4?", choices: [
        { id: "a", text: "As jaguars went down, capybaras went up." },
        { id: "b", text: "Jaguars and capybaras both went down." },
        { id: "c", text: "Jaguars and capybaras both went up." },
      ] },
      { type: "choice", prompt: "Why did the capybaras increase?", choices: [
        { id: "a", text: "Fewer jaguars were hunting them." },
        { id: "b", text: "The capybaras had less grass to eat." },
        { id: "c", text: "The river got colder." },
      ] },
      { type: "choice", prompt: "Why did the grass patches shrink?", choices: [
        { id: "a", text: "More capybaras were eating the grass." },
        { id: "b", text: "Jaguars ate the grass." },
        { id: "c", text: "Decomposers stopped working." },
      ] },
      { type: "choice", prompt: "Why did capybaras drop in Year 5?", choices: [
        { id: "a", text: "There wasn't enough grass left to feed them all." },
        { id: "b", text: "The jaguars came back." },
        { id: "c", text: "Capybaras stopped eating grass." },
      ] },
    ],
    hint: "Read each column from top to bottom. Who eats whom in this food chain?",
    meter: { heat: 5, label: "Balance +5%", story: "The crew finds the cause" },
    discovery: { id: "toppredator", name: "Top predators", who: "Nova", fact: "Jaguars are top predators. Adult jaguars have almost no natural predators. By hunting plant eaters, they help keep plants from being eaten up." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Losing one predator changed the whole riverbank. That's how connected a food web is!",
    wrong: [
      { step: 1, choice: "b", hint: "Read the Capybaras column from Year 1 to Year 4. Is it going down?" },
      { step: 1, choice: "c", hint: "Read the Jaguars column. Is it going up?" },
      { step: 2, choice: "b", hint: "Less food would make a population shrink, not grow. What eats capybaras?" },
      { step: 2, choice: "c", hint: "The table doesn't show anything about temperature. What changed in the Jaguars column?" },
      { step: 3, choice: "b", hint: "Jaguars are meat eaters. Who eats the grass?" },
      { step: 3, choice: "c", hint: "Nothing in the data shows that. Which grass eater increased?" },
      { step: 4, choice: "b", hint: "Check the Jaguars column in Year 5. Did they come back?" },
      { step: 4, choice: "c", hint: "Capybaras always eat grass. What's left of the grass by Year 5?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The nut planters", machine: "Canopy Lift", icon: "grid", speaker: "nova",
    line: "Agoutis are small rodents that crack open Brazil nut shells. They eat some nuts and bury the rest to save for later. The nuts they forget can sprout into new trees.",
    question: "What would most likely happen to the Brazil nut trees if the agoutis disappeared?",
    hint: "Who plants the Brazil nut seeds? What happens if nobody does?",
    meter: { heat: 10, label: "Balance +10%", story: "The agouti burrows are protected" },
    discovery: { id: "agouti", name: "Forgetful gardeners", who: "Nova", fact: "Agoutis are one of the few animals with teeth strong enough to open a Brazil nut shell. The nuts they bury and forget grow into new trees." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Nothing would change. The trees don't need animals." },
      { id: "b", text: "Fewer new Brazil nut trees would grow, because fewer seeds would get opened and buried." },
      { id: "c", text: "More new Brazil nut trees would grow, because nobody would eat the nuts." },
      { id: "d", text: "The trees would start growing faster." },
    ],
    rightFeedback: "The agoutis and the trees need each other. The tree feeds the agouti, and the agouti plants the tree.",
    wrong: [
      { choice: "a", hint: "Read Nova's report again. Who buries the nuts so they can sprout?" },
      { choice: "c", hint: "Uneaten nuts would stay locked in their hard shells under the tree. Who spreads and plants them?" },
      { choice: "d", hint: "Agoutis don't change how fast a tree grows. What do they do for new trees?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The leaf bag test", machine: "Test Bay", icon: "cylinder", speaker: "kai",
    line: "Nova put 40 g of dead leaves in each of two mesh bags on the forest floor. Bag A has big holes, so termites and beetles can crawl in. Bag B has tiny holes that keep them out.",
    question: "After 8 weeks, how many more grams of leaves broke down in Bag A than in Bag B?",
    unit: "g",
    data: {
      title: "Leaf bags after 8 weeks",
      columns: ["Bag", "Start", "After 8 weeks"],
      rows: [
        ["Bag A (big holes)", "40 g", "12 g"],
        ["Bag B (tiny holes)", "40 g", "30 g"],
      ],
    },
    hint: "First find how many grams broke down in each bag. Then compare.",
    meter: { supplies: 1, label: "Web links +1", story: "The decomposer test is logged" },
    discovery: { id: "termites", name: "Termite recyclers", who: "Kai", fact: "Termites eat dead wood and leaves. Tiny living things in their guts help them digest the wood, and this returns nutrients to the forest." },
    answer: { kind: "number", value: 18 },
    rightFeedback: "Bag A lost 28 g and Bag B lost 10 g. 28 − 10 = 18 g more broke down when the bigger decomposers could get in.",
    wrong: [
      { value: 28, hint: "28 g broke down in Bag A. How much broke down in Bag B? Compare them." },
      { value: 10, hint: "10 g broke down in Bag B. How much broke down in Bag A?" },
      { value: 42, hint: "12 g and 30 g are what's left, not what broke down. Subtract from 40 g first." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Why so few eagles?", machine: "Population Log", icon: "brief", speaker: "vega",
    line: "Nova's survey counted hundreds of sloths in the valley. She found only two harpy eagles.",
    question: "Why are there so many fewer harpy eagles than sloths?",
    hint: "Think about the energy. Does all of the energy in the sloth's food get passed on to the eagle?",
    meter: { heat: 10, label: "Balance +10%", story: "The valley survey makes sense" },
    discovery: { id: "tenth", name: "Energy steps", who: "Nova", fact: "When an animal eats, only about one tenth of the energy in its food gets passed on to the animal that eats it. Most is used to move, grow, and stay warm." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Energy is used up at each step of the food chain, so there's only enough left to feed a few top predators." },
      { id: "b", text: "Eagles don't need any energy." },
      { id: "c", text: "Sloths eat harpy eagles." },
      { id: "d", text: "Eagles get their energy straight from the Sun." },
    ],
    rightFeedback: "Each step up the chain has less energy to share, so there are fewer animals at the top.",
    wrong: [
      { choice: "b", hint: "Every animal needs energy to live. Where does the eagle get it?" },
      { choice: "c", hint: "Check the food chain. Who eats whom?" },
      { choice: "d", hint: "Only producers capture energy from sunlight. The eagle has to eat." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Do animals need abiotic things?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Abiotic factors only matter to plants. Animals just need food."',
    nova: 'Nova: "Animals need abiotic factors too. Poison dart frogs need damp air and pools of water, and every animal needs air and water."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Could any animal live without water or air? Are water and air living?",
    meter: { heat: 5, label: "Balance +5%", story: "Kai adds water and air to his list" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Animals need abiotic factors like water, air, and the right temperature to survive. A frog's skin dries out without damp air and water." },
      { id: "B", text: "Nova, because frogs are green." },
      { id: "C", text: "Kai. Animals get everything they need from food." },
      { id: "D", text: "Kai. Only plants use sunlight, so abiotic things don't matter to animals." },
    ],
    writtenPrompt: "Tell Kai in your own words how an animal depends on abiotic factors.",
    debateHints: {
      wrongWho: "Picture a jaguar with plenty of food but no water to drink. Could it survive?",
      wrongReason: "Right person, check the reason. Which abiotic factors does an animal need?",
      right: "Nova is right — animals depend on abiotic factors like water, air, and temperature.",
    },
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The dry season surprise", machine: "Population Log", icon: "relay", speaker: "vega",
    line: "This is it! Solara's dry season came early and stayed long. The river station logged the rain and the fruiting trees. The council needs your prediction before the next dry season.",
    question: "Part 1: Which abiotic factor changed? Part 2: Pick every animal that loses food first. Part 3: Put the chain of effects in order. Part 4: Write a prediction for Commander Vega, using the data as evidence.",
    data: {
      title: "River station log",
      columns: ["Month", "Rain (cm)", "Fruiting palm trees"],
      rows: [
        ["Month 1", "30", "140"],
        ["Month 2", "22", "120"],
        ["Month 3", "9", "70"],
        ["Month 4", "4", "35"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which abiotic factor changed?", choices: [
        { id: "rain", text: "The amount of rain" },
        { id: "palms", text: "The number of palm trees with fruit" },
        { id: "jaguars", text: "The number of jaguars" },
        { id: "sunlight", text: "The Sun stopped shining" },
      ] },
      { type: "multi", prompt: "Pick every animal that loses food first.", choices: [
        { id: "agouti", text: "Agoutis (eat fallen fruit and seeds)" },
        { id: "toucan", text: "Toucans (eat fruit)" },
        { id: "spider", text: "Spider monkeys (eat mostly fruit)" },
        { id: "ocelot", text: "Ocelots (hunt agoutis)" },
        { id: "fungi", text: "Fungi (break down dead things)" },
      ] },
      { type: "order", prompt: "Put the chain of effects in order.", items: [
        { id: "ocelots", text: "Ocelots find fewer agoutis to eat" },
        { id: "rain", text: "Less rain falls" },
        { id: "agoutis", text: "Agoutis have less food, so fewer survive" },
        { id: "fruit", text: "Fewer palm trees make fruit" },
      ] },
      { type: "write", prompt: "Predict what will happen to the food web if next dry season is this long. Use the data as evidence.", minWords: 20 },
    ],
    rubric: ["Makes a prediction about the food web", "Uses numbers from the log as evidence", "Explains how the change moves through the food web (energy or matter)"],
    hint: "Start with the abiotic change. Then follow the energy up the food chain, one step at a time.",
    meter: { heat: 10, label: "Balance +10%", story: "Solara's food web is ready for the dry season" },
    discovery: { id: "ownrain", name: "Forests make rain", who: "Kai", fact: "Rainforest trees give off huge amounts of water vapor through their leaves. That vapor helps form clouds, so a big rainforest makes much of its own rain." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "rain" },
      { kind: "multi", correct: ["agouti", "toucan", "spider"] },
      { kind: "order", correct: ["rain", "fruit", "agoutis", "ocelots"] },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Great prediction! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "palms", hint: "Palm trees are living, so they're biotic. Which column shows something that was never alive?" },
      { step: 1, choice: "jaguars", hint: "Jaguars aren't in the log, and they're biotic. Which abiotic factor is in the table?" },
      { step: 1, choice: "sunlight", hint: "The Sun kept shining. Which column went way down?" },
      { step: 2, pick: "ocelot", hint: "Ocelots eat agoutis, not fruit. They lose food later, after the agoutis do." },
      { step: 2, pick: "fungi", hint: "Fungi break down dead things. Do they eat fruit from living trees?" },
      { step: 2, missing: true, hint: "There are three fruit eaters in the list." },
      { step: 3, position: 0, hint: "The change starts with something abiotic. What happened first?" },
      { step: 3, position: 1, hint: "What does less rain do to the palm trees first?" },
      { step: 3, position: 2, hint: "The ocelots feel it last. Who has to go hungry before them?" },
    ],
  },
};

export default {
  id: "SCI.5.12A-XP",
  standard: "SCI.5.12A-XP",
  engine: "expedition_station",
  title: "The Ecosystem Balance",
  planet: "Solara",
  outpost: "Jungle Moon · river research station",
  grade: 5,
  subject: "Science",
  teks: "5.12A",
  supportingTeks: ["5.12B", "5.1A", "5.2B", "5.2D", "5.3A", "5.3B", "5.3C", "5.5E", "5.5F", "5.5G"],
  skillsChip: "5.12A · Organisms in an ecosystem",
  iCan: "I can describe how organisms survive by interacting with living and nonliving parts of an ecosystem. I can trace energy in a food web and predict what happens when something in the ecosystem changes.",
  blurb: "The river research station on Solara watches over a real rainforest ecosystem. A storm, a missing predator, and a long dry season are putting its balance to the test.",
  mission: "Sort the living and nonliving parts of the forest, trace energy through the food web, and predict how changes will ripple through the ecosystem.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.12 · SOLARA RIVER STATION",
  playableActs: [1, 2, 3],
  earthTrue: "Every organism in this quest is a real rainforest organism, and every interaction happens in real rainforests on Earth. Only the planet and crew are invented.",
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Balance", heatUnit: "%", supplies: "Web links", suppliesUnit: "links" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're at the river research station on Solara.",
    "This jungle works just like a rainforest on Earth. Every living thing depends on other living things and on sunlight, water, air, and soil.",
    "Something is throwing the forest out of balance. Help us figure out what. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Map the forest", "Act 2 · Follow the energy", "Act 3 · Predict the changes"],
    completes: [
      "The forest is mapped and the fallen tree is feeding new life, {firstName}!",
      "You traced the energy and found what happened to the jaguars, {firstName}!",
      "Solara's ecosystem is ready for the dry season, {firstName}! The forest is back in balance.",
    ],
    teasers: [
      "Next on Solara: Kai says decomposers don't matter, and the riverbank is starting to look bare. Act 2 is open now, or come back to it next time.",
      "Next on Solara: the dry season is coming. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai and I already disagree about decomposers.",
      "And the river station logs show something strange happening on the riverbank.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The river station needs predictions.",
      "Help the crew figure out how changes will ripple through the food web.",
    ],
  }),
  tasks,
};
