// Expedition Station — The Energy Hunt (SCI.3.8A-XP)
// Grade 3 · Science · Lumara (glowing garden). Main standard 3.8A (2024 TEKS):
// identify everyday examples of energy, including light, sound, and thermal
// energy (heat), in the surrounding environment. Practices
// 3.1B (plan and conduct
// investigations), 3.1D (use tools such as thermometers), 3.1E (collect
// observations as evidence), 3.2B (analyze data for patterns), 3.2C (use math
// to compare data), 3.3A (explanations supported by evidence), 3.3C (respectful
// scientific discussion), 3.5B (cause and effect).
//
// Earth-true rule: Lumara and the crew are invented, but every lamp, drum,
// thermometer reading, and energy fact is real Earth science. The grade 5
// Light Lab covers reflect/refract/absorb; this quest stays on naming forms of
// energy, sound from vibrations, light sources, and heat moving warm to cool.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Three kinds of clues", machine: "Clue Sorter", icon: "cells", speaker: "nova",
    line: "Welcome to the energy hunt! Energy is all around the garden outpost. Today we look for three kinds: light, sound, and thermal energy (heat).",
    question: "Sort each clue: is it mostly light, sound, or thermal energy (heat)?",
    hint: "Can you see it glow? Can you hear it? Can you feel it warm you?",
    meter: { heat: 5, label: "Hunt map +5%", story: "The first clues are sorted" },
    answer: { kind: "sort", bins: { e1: "light", e2: "sound", e3: "thermal", e4: "light", e5: "sound", e6: "thermal" } },
    rightFeedback: "You see light, you hear sound, and you feel thermal energy as warmth.",
    sort: {
      bins: [{ id: "light", label: "Light" }, { id: "sound", label: "Sound" }, { id: "thermal", label: "Thermal energy (heat)" }],
      items: [
        { id: "e1", label: "A flashlight shining on the path" },
        { id: "e2", label: "A bird singing in a tree" },
        { id: "e3", label: "A heater warming the hut" },
        { id: "e4", label: "A tablet screen glowing" },
        { id: "e5", label: "A bell ringing at the gate" },
        { id: "e6", label: "A warm mug of cocoa" },
      ],
    },
    wrong: [
      { item: "e3", hint: "Stand by a heater. Do you see it, hear it, or feel it warm you?" },
      { item: "e6", hint: "Hold the mug in your hands. What do you feel?" },
      { item: "e2", hint: "A song is something you hear. Which kind of energy do your ears notice?" },
      { item: "e5", hint: "The bell goes ding! Which kind of energy do your ears notice?" },
      { item: "e1", hint: "The flashlight lets you see the path. Which kind of energy is that?" },
      { item: "e4", hint: "The screen glows so you can see it. Which kind of energy is that?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The two-job lamp", machine: "Lamp Stand", icon: "scan", speaker: "kai",
    line: "I found an old desk lamp in the storage hut. When I turn it on, it glows. And when I hold my hand near the bulb, it feels hot!",
    question: "Which kinds of energy does the old lamp give off? Pick every one.",
    items: [
      { id: "light", text: "Light" },
      { id: "thermal", text: "Thermal energy (heat)" },
      { id: "sound", text: "Loud sound" },
      { id: "cold", text: "Cold energy" },
    ],
    hint: "Kai saw something AND felt something. What did he see? What did he feel?",
    meter: { heat: 5, label: "Hunt map +5%", story: "The lamp gets two energy tags" },
    answer: { kind: "multi", correct: ["light", "thermal"] },
    rightFeedback: "The lamp gives off light you can see and heat you can feel. One thing can give off more than one kind of energy.",
    wrong: [
      { pick: "sound", hint: "Kai didn't say the lamp made any noise. What did he see and feel?" },
      { pick: "cold", hint: "The bulb felt hot, not cold. Is 'cold energy' a kind of energy we are hunting?" },
      { missing: true, hint: "Kai saw the lamp glow AND felt it get hot. Pick both kinds of energy." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The twangy band", machine: "Sound Bench", icon: "static", speaker: "kai",
    line: "I stretched a rubber band around a seed box and plucked it. Twang! I can see it wiggling back and forth really fast.",
    question: "What is making the twang sound?",
    hint: "Watch the rubber band. What is it doing while you hear the sound?",
    meter: { supplies: 1, label: "Energy tags +1", story: "Kai tags the rubber band" },
    discovery: { id: "vocalcords", name: "Your voice", who: "Nova", fact: "When you talk or sing, two small flaps in your throat called vocal cords vibrate. Put your fingers on your throat and hum to feel them buzz." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The rubber band is vibrating, moving back and forth very fast." },
      { id: "b", text: "The seed box is getting warm." },
      { id: "c", text: "The rubber band is glowing." },
      { id: "d", text: "The rubber band is holding still." },
    ],
    rightFeedback: "Sound is made when something vibrates. The fast wiggle of the band makes the twang.",
    wrong: [
      { choice: "b", hint: "Warmth is thermal energy. What did Kai see the band doing when it made a sound?" },
      { choice: "c", hint: "The band doesn't glow. What did Kai see it doing?" },
      { choice: "d", hint: "Kai saw it wiggling. Press the band so it holds still. Does the twang stop?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Makers of light", machine: "Glow Scanner", icon: "grid", speaker: "nova",
    line: "Light has to come from somewhere. A light source makes its own light. Let's find the light sources around the outpost.",
    question: "Pick every light source, something that makes its own light.",
    items: [
      { id: "sun", text: "The Sun" },
      { id: "campfire", text: "A campfire" },
      { id: "flashlight", text: "A flashlight that is turned on" },
      { id: "mirror", text: "A mirror" },
      { id: "paper", text: "A sheet of white paper" },
    ],
    hint: "Would it still shine in a dark room with no other lights? If yes, it makes its own light.",
    meter: { supplies: 1, label: "Energy tags +1", story: "The light sources are tagged" },
    answer: { kind: "multi", correct: ["sun", "campfire", "flashlight"] },
    rightFeedback: "The Sun, a fire, and a flashlight make their own light. A mirror and white paper only look bright when light hits them.",
    wrong: [
      { pick: "mirror", hint: "Take a mirror into a dark closet. Does it shine? Or does it need light from somewhere else?" },
      { pick: "paper", hint: "White paper looks bright in the day. In a dark room, does it glow on its own?" },
      { missing: true, hint: "There are three things that make their own light. Think about fire, too." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The dark, cold hut", machine: "Sleep Hut", icon: "quake", speaker: "vega",
    line: "Surprise! A storm knocked out the lights in the sleeping hut, and it's getting chilly. Kai found a flashlight and turned on a small heater. Nova is reading the hut's thermometer.",
    question: "Part 1: What should the crew use so they can see in the dark hut? Part 2: How many degrees warmer was the hut at 8:00 than at 7:00? Part 3: What kind of energy did the heater give the hut?",
    data: {
      title: "Sleeping hut temperature",
      columns: ["Time", "Temperature"],
      rows: [
        ["7:00 p.m.", "12°C"],
        ["7:30 p.m.", "16°C"],
        ["8:00 p.m.", "20°C"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What should the crew use so they can see in the dark hut?", choices: [
        { id: "a", text: "The flashlight, because it is a light source" },
        { id: "b", text: "A mirror, because it is shiny" },
        { id: "c", text: "A white blanket, because it is bright" },
        { id: "d", text: "Nothing. Their eyes will see fine in the dark." },
      ] },
      { type: "number", prompt: "How many degrees warmer was the hut at 8:00 than at 7:00?", unit: "°C" },
      { type: "choice", prompt: "What kind of energy did the heater give the hut?", choices: [
        { id: "a", text: "Thermal energy (heat)" },
        { id: "b", text: "Sound energy" },
        { id: "c", text: "Cold energy" },
        { id: "d", text: "No energy at all" },
      ] },
    ],
    hint: "We need light to see. For the table, start at 12 and count up to 20.",
    meter: { heat: 10, label: "Hunt map +10%", story: "The hut is bright and cozy again" },
    discovery: { id: "bodyheat", name: "Body heat", who: "Kai", fact: "Your body gives off thermal energy all the time. That's why a room full of people warms up, even with the heater off." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 8 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The flashlight gave light to see, and the heater warmed the hut by 8 degrees. The crew can sleep!",
    wrong: [
      { step: 1, choice: "b", hint: "A mirror only shines when light hits it. In a dark hut, is there any light to bounce?" },
      { step: 1, choice: "c", hint: "A white blanket doesn't make light. In the dark, it looks dark too." },
      { step: 1, choice: "d", hint: "Eyes need light to see. Which thing makes light?" },
      { step: 2, value: 20, hint: "20°C is the temperature at 8:00. How much did it go up from 12°C?" },
      { step: 2, value: 32, hint: "You want to know how much warmer. Should you add or subtract?" },
      { step: 2, value: 4, hint: "4 degrees is how much it warmed in the first half hour. Compare 7:00 with 8:00." },
      { step: 3, choice: "b", hint: "The heater hums a little, but what did it do to the hut's temperature?" },
      { step: 3, choice: "c", hint: "The hut got warmer, not colder. What kind of energy makes things warmer?" },
      { step: 3, choice: "d", hint: "The temperature went up 8 degrees. Something gave the hut energy. What kind?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Where does cold go?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "When I hold an ice cube, cold moves out of the ice and into my hand. That\'s why my hand feels cold."',
    nova: 'Nova: "It\'s the other way. Heat moves out of your warm hand and into the cooler ice. Your hand feels cold because it is losing heat."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Heat moves from a warmer thing to a cooler thing. Which one is warmer, your hand or the ice?",
    meter: { heat: 5, label: "Hunt map +5%", story: "Kai rethinks the ice cube" },
    discovery: { id: "warmtocool", name: "Heat on the move", who: "Nova", fact: "Heat always moves from a warmer thing to a cooler thing. There is no such thing as 'cold' moving. Cold just means less heat." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Heat moves from warmer things to cooler things. Your warm hand gives heat to the ice, so the ice melts and your hand cools down." },
      { id: "B", text: "Nova, because ice is clear." },
      { id: "C", text: "Kai. Ice is full of cold, and cold spreads out into things." },
      { id: "D", text: "Kai. The ice feels cold, so the cold must be moving." },
    ],
    writtenPrompt: "Tell Kai in your own words why his hand feels cold when he holds ice.",
    debateHints: {
      wrongWho: "The ice melts in Kai's hand. Melting needs heat. Where did the heat come from?",
      wrongReason: "Right person, check the reason. Which way does heat move?",
      right: "Nova is right — heat moves from the warm hand into the cool ice.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The dancing rice", machine: "Sound Bench", icon: "snap", speaker: "nova",
    line: "I sprinkled some rice on top of a drum. When Kai taps the drum, the rice jumps and dances! When the drum stops sounding, the rice stops too.",
    question: "What does the dancing rice show about sound?",
    hint: "Kai's tap is a push. What is the drum skin doing while you hear the boom?",
    meter: { heat: 5, label: "Hunt map +5%", story: "The drum gets a sound tag" },
    discovery: { id: "silentspace", name: "Silent space", who: "Kai", fact: "Sound needs something like air or water to travel through. Space has almost no air, so astronauts use radios to talk outside their spaceship." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "The rice is making the sound." },
      { id: "b", text: "The tap makes the drum skin vibrate. The vibrating drum makes the sound and shakes the rice." },
      { id: "c", text: "The drum is giving off heat that makes the rice jump." },
      { id: "d", text: "Sound only happens when things are very big." },
    ],
    rightFeedback: "The drum skin vibrates, and you can see it move the rice. Vibrations make sound.",
    wrong: [
      { choice: "a", hint: "Tap the drum with no rice on it. Is there still a boom?" },
      { choice: "c", hint: "The drum doesn't get warm. The rice jumps only while the drum is sounding. What is the skin doing?" },
      { choice: "d", hint: "A tiny rubber band makes a sound too. What do all sounds need?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The cooling cocoa", machine: "Heat Log", icon: "log", speaker: "vega",
    line: "Nova made a mug of hot cocoa and left it on the table. The room is 22°C. Every 5 minutes, she checked the cocoa with a thermometer.",
    question: "Part 1: How many degrees did the cocoa cool from 0 to 10 minutes? Part 2: Why did the cocoa cool down?",
    data: {
      title: "Cocoa temperature over time",
      columns: ["Minutes", "Cocoa temperature"],
      rows: [
        ["0", "70°C"],
        ["5", "60°C"],
        ["10", "52°C"],
        ["15", "46°C"],
        ["20", "41°C"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many degrees did the cocoa cool from 0 to 10 minutes?", unit: "°C" },
      { type: "choice", prompt: "Why did the cocoa cool down?", choices: [
        { id: "a", text: "Heat moved from the warm cocoa into the cooler air and table." },
        { id: "b", text: "Cold moved from the air into the cocoa." },
        { id: "c", text: "The cocoa used up its light." },
        { id: "d", text: "The thermometer made it cold." },
      ] },
    ],
    hint: "Subtract the 10-minute temperature from the starting temperature. Then think: which is warmer, the cocoa or the room?",
    meter: { supplies: 1, label: "Energy tags +1", story: "The cocoa log is finished" },
    discovery: { id: "blowsoup", name: "Blowing on soup", who: "Nova", fact: "Blowing on hot soup helps it cool faster. Moving air carries heat away from the soup more quickly." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 18 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "70 − 52 = 18 degrees. Heat moved out of the warm cocoa into the cooler room.",
    wrong: [
      { step: 1, value: 52, hint: "52°C is the temperature at 10 minutes. How much did it drop from 70°C?" },
      { step: 1, value: 10, hint: "The cocoa cooled 10 degrees in the first 5 minutes. Look all the way to 10 minutes." },
      { step: 1, value: 122, hint: "You want to know how much it cooled. Should you add or subtract?" },
      { step: 2, choice: "b", hint: "Cold doesn't move. Heat does. Which way does heat move, warm to cool or cool to warm?" },
      { step: 2, choice: "c", hint: "Cocoa doesn't glow. The temperature went down. What kind of energy left it?" },
      { step: 2, choice: "d", hint: "A thermometer only measures. It doesn't change the temperature. Where did the heat go?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Heat in, heat out", machine: "Heat Sorter", icon: "tank", speaker: "kai",
    line: "Heat moves from warmer to cooler. So some things at the outpost are gaining heat, and some are losing it.",
    question: "Look at the FIRST thing in each card. Is it gaining heat (getting warmer) or losing heat (getting cooler)?",
    hint: "Which is warmer, the first thing or what is around it? Heat moves from the warmer one to the cooler one.",
    meter: { heat: 5, label: "Hunt map +5%", story: "The heat cards are sorted" },
    discovery: { id: "vacuumflask", name: "Keep-warm bottles", who: "Kai", fact: "A keep-warm bottle has a double wall with almost no air in between. That slows heat from moving out, so hot drinks stay hot for hours." },
    answer: { kind: "sort", bins: { h1: "gain", h2: "lose", h3: "gain", h4: "lose", h5: "gain", h6: "lose" } },
    rightFeedback: "Cold things near warm things gain heat. Hot things near cooler things lose heat.",
    sort: {
      bins: [{ id: "gain", label: "Gaining heat (getting warmer)" }, { id: "lose", label: "Losing heat (getting cooler)" }],
      items: [
        { id: "h1", label: "An ice pop held in a warm hand" },
        { id: "h2", label: "A hot baked potato set on a cool plate" },
        { id: "h3", label: "Cold milk left in a sunny window" },
        { id: "h4", label: "A warm pie cooling on the counter" },
        { id: "h5", label: "A cold spoon dipped in hot soup" },
        { id: "h6", label: "Hot bath water in a cool room" },
      ],
    },
    wrong: [
      { item: "h1", hint: "The hand is warmer than the ice pop. Which way does the heat go?" },
      { item: "h5", hint: "The soup is hotter than the spoon. Does the spoon get warmer or cooler?" },
      { item: "h3", hint: "Sunlight warms things. Is the cold milk getting warmer or cooler?" },
      { item: "h2", hint: "The potato is hotter than the plate. Does the potato gain or lose heat?" },
      { item: "h6", hint: "The water is warmer than the room. What happens to bath water if you wait?" },
      { item: "h4", hint: "The word 'cooling' is a clue. Is the pie gaining or losing heat?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Sun spot, shade spot", machine: "Heat Log", icon: "dial", speaker: "vega",
    line: "Surprise, the new glow-lily seedlings are drooping in the heat! Nova put two thermometers of the same kind in the garden, one in a sunny spot and one in the shade of a big glow tree. She read both at the same times.",
    question: "Part 1: How many degrees warmer was the sunny spot at 3:00? Part 2: What does the table show? Part 3: Pick the two things Nova kept the same. Part 4: Where should the crew move the seedlings?",
    data: {
      title: "Garden temperatures (°C)",
      columns: ["Time", "Sunny spot", "Shady spot"],
      rows: [
        ["9:00 a.m.", "24", "21"],
        ["12:00 p.m.", "33", "25"],
        ["3:00 p.m.", "36", "27"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many degrees warmer was the sunny spot than the shady spot at 3:00?", unit: "°C" },
      { type: "choice", prompt: "What does the table show?", choices: [
        { id: "a", text: "The sunny spot was warmer every time. Sunlight gives the ground thermal energy." },
        { id: "b", text: "The shady spot was warmer every time." },
        { id: "c", text: "Both spots were always the same temperature." },
        { id: "d", text: "Sunlight has no energy, so it can't warm anything." },
      ] },
      { type: "multi", prompt: "Pick the two things Nova kept the same.", choices: [
        { id: "kind", text: "The kind of thermometer" },
        { id: "times", text: "The times she read them" },
        { id: "spot", text: "Sun or shade" },
        { id: "temp", text: "The temperatures she read" },
      ] },
      { type: "choice", prompt: "The seedlings droop when they get too hot. Where should the crew move them?", choices: [
        { id: "a", text: "Into the shade of the glow tree" },
        { id: "b", text: "Into the sunniest spot" },
        { id: "c", text: "Next to the heater in the hut" },
        { id: "d", text: "It doesn't matter where they go." },
      ] },
    ],
    hint: "Read across each row to compare sun and shade. Subtract to find the difference.",
    meter: { heat: 10, label: "Hunt map +10%", story: "The seedlings rest in the cool shade" },
    discovery: { id: "treeshade", name: "Cool tree shade", who: "Nova", fact: "Trees shade the ground from sunlight. On a hot day, a shady park can feel much cooler than a sunny parking lot nearby." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 9 },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["kind", "times"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The sun spot was 9 degrees warmer at 3:00. Sunlight carries energy that heats the ground, so the seedlings go in the shade.",
    wrong: [
      { step: 1, value: 36, hint: "36°C is the sunny spot's temperature. How much warmer is it than the shady spot's 27°C?" },
      { step: 1, value: 63, hint: "You want to know how much warmer. Should you add or subtract?" },
      { step: 1, value: 8, hint: "8 degrees is the difference at 12:00. Look at the 3:00 row." },
      { step: 2, choice: "b", hint: "Compare the two columns. Which one has the bigger numbers?" },
      { step: 2, choice: "c", hint: "At 3:00 the spots were 36 and 27. Is that the same?" },
      { step: 2, choice: "d", hint: "If sunlight had no energy, why would the sunny spot get so much warmer?" },
      { step: 3, pick: "spot", hint: "Sun or shade is the one thing Nova changed on purpose." },
      { step: 3, pick: "temp", hint: "The temperatures are what Nova measured. They came out different." },
      { step: 3, missing: true, hint: "There are two things that stayed the same. Read Commander Vega's message again." },
      { step: 4, choice: "b", hint: "The seedlings are already too hot. Which spot was cooler?" },
      { step: 4, choice: "c", hint: "A heater gives off thermal energy. Would that help plants that are too hot?" },
      { step: 4, choice: "d", hint: "The table shows the two spots are very different. Which one is cooler?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Map in the dark", machine: "Map Tent", icon: "trail", speaker: "kai",
    line: "It's the last night of the hunt. I'm in my tent, and it's totally dark. I want to read the hunt map, but I can't see a thing!",
    question: "What does Kai need so he can see the map?",
    hint: "What do our eyes need to see anything at all?",
    meter: { heat: 5, label: "Hunt map +5%", story: "Kai can read the map again" },
    discovery: { id: "anglerfish", name: "Anglerfish", who: "Nova", fact: "Deep in the ocean, where sunlight never reaches, anglerfish carry their own light. A glowing lure on the head attracts small fish to eat." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "He should open his eyes really wide." },
      { id: "b", text: "He should put on sunglasses." },
      { id: "c", text: "He needs a light source, like a flashlight. Light lets us see." },
      { id: "d", text: "He should hold the map closer to his face." },
    ],
    rightFeedback: "Without light, we can't see. A flashlight is a light source, so it lets Kai see the map.",
    wrong: [
      { choice: "a", hint: "Wide-open eyes still can't see with no light. What is missing in the tent?" },
      { choice: "b", hint: "Sunglasses block some light. There is no light in the tent to start with." },
      { choice: "d", hint: "Close or far, the map is still dark. What does Kai need to see it?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's silent bell", machine: "Repair Bench", icon: "brief", speaker: "kai",
    line: "I made a doorbell for the hut! I wrapped a thick cloth tightly around the metal bell so it won't get scratched. But when I shake it, all I get is a dull thud.",
    question: "Part 1: What went wrong? Part 2: How should Kai fix the bell?",
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "The tight cloth stops the bell from vibrating, so it can't ring." },
        { id: "b", text: "The cloth makes the bell too hot to ring." },
        { id: "c", text: "Bells need light to make sound." },
        { id: "d", text: "Kai shook the bell too gently to make any sound." },
      ] },
      { type: "choice", prompt: "How should Kai fix the bell?", choices: [
        { id: "a", text: "Take off the cloth so the metal can vibrate freely." },
        { id: "b", text: "Wrap a second cloth around it." },
        { id: "c", text: "Shine a flashlight on the bell." },
        { id: "d", text: "Put the bell next to the heater." },
      ] },
    ],
    hint: "What does a bell have to do to make a sound? Can it do that with a cloth squeezing it?",
    meter: { supplies: 1, label: "Energy tags +1", story: "The doorbell rings loud and clear" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "A bell rings when the metal vibrates. With the cloth off, it can vibrate and ring again.",
    wrong: [
      { step: 1, choice: "b", hint: "The cloth doesn't heat the bell. What does a bell need to do to make a sound?" },
      { step: 1, choice: "c", hint: "Bells ring in the dark too. Sound comes from something vibrating." },
      { step: 1, choice: "d", hint: "Kai shook it, and it only thudded. Touch a ringing bell and the ring stops. What is the cloth doing?" },
      { step: 2, choice: "b", hint: "One cloth already stopped the vibrating. Would two cloths help?" },
      { step: 2, choice: "c", hint: "Light doesn't make things ring. What needs to happen to the metal?" },
      { step: 2, choice: "d", hint: "Heat won't make the bell ring. What is stopping the metal from vibrating?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The chilly bench", machine: "Heat Sorter", icon: "scan", speaker: "nova",
    line: "Two benches sit side by side in the shade, one metal and one wood. My thermometer says they are both 20°C. But when I sit on the metal one, it feels much colder!",
    question: "Why does the metal bench feel colder, even though both benches are the same temperature?",
    hint: "Your body is warmer than 20°C. Which way does heat move when you touch the bench?",
    meter: { heat: 5, label: "Hunt map +5%", story: "The bench mystery is solved" },
    discovery: { id: "metalchill", name: "Chilly metal", who: "Kai", fact: "A metal doorknob feels colder than a wooden door, even in the same room. Metal pulls heat out of your hand faster than wood does." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Heat moves out of Nova's warm body into the metal faster than into the wood, so the metal feels colder." },
      { id: "b", text: "The metal bench is full of cold that moves into Nova." },
      { id: "c", text: "The thermometer is wrong. The metal bench must be colder." },
      { id: "d", text: "Metal makes its own cold." },
    ],
    rightFeedback: "Both benches are 20°C. Metal just carries heat away from your body faster, so it feels colder.",
    wrong: [
      { choice: "b", hint: "Remember the ice cube debate. Does cold move, or does heat move?" },
      { choice: "c", hint: "Nova checked both with a thermometer, and they match. So why would one FEEL colder?" },
      { choice: "d", hint: "Nothing makes 'cold.' Cold just means less heat. Where is Nova's heat going?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Warmest to coolest", machine: "Heat Log", icon: "cylinder", speaker: "vega",
    line: "For the hunt map, we need to line up four things we found today by how much thermal energy they have.",
    question: "Put the things in order from warmest to coolest.",
    hint: "Think about how each one would feel if you touched it. The hottest goes first.",
    meter: { supplies: 1, label: "Energy tags +1", story: "The heat line is on the map" },
    answer: { kind: "order", correct: ["cocoa", "hand", "pond", "icepop"] },
    items: [
      { id: "pond", text: "Pond water in the shade" },
      { id: "icepop", text: "An ice pop from the freezer" },
      { id: "cocoa", text: "A mug of steaming cocoa" },
      { id: "hand", text: "Your warm hand" },
    ],
    rightFeedback: "Steaming cocoa is hottest, then your hand, then shady pond water, then a frozen ice pop.",
    wrong: [
      { position: 0, hint: "Which one is steaming? That's the warmest." },
      { position: 1, hint: "Your hand warms up an ice pop and feels cool next to hot cocoa. Where does it go?" },
      { position: 2, hint: "Shady pond water feels cool, but it isn't frozen." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The great energy hunt", machine: "Hunt Board", icon: "relay", speaker: "vega",
    line: "This is it! The crew spread out across the whole garden outpost to find energy. Our last stop is the campfire, where wind chimes are tinkling in the breeze. Let's finish the hunt map!",
    question: "Part 1: Pick every kind of energy the campfire gives off. Part 2: What makes the wind chimes' sound? Part 3: How many finds did the crew make in all? Part 4: Explain your hunt to Commander Vega.",
    data: {
      title: "Energy hunt finds",
      columns: ["Kind of energy", "Number of finds"],
      rows: [
        ["Light", "7"],
        ["Sound", "5"],
        ["Thermal energy (heat)", "4"],
      ],
    },
    parts: [
      { type: "multi", prompt: "The campfire glows, crackles, and warms your hands. Pick every kind of energy it gives off.", choices: [
        { id: "light", text: "Light" },
        { id: "sound", text: "Sound" },
        { id: "thermal", text: "Thermal energy (heat)" },
        { id: "cold", text: "Cold energy" },
      ] },
      { type: "choice", prompt: "What makes the wind chimes' sound?", choices: [
        { id: "a", text: "The breeze bumps the metal tubes, and they vibrate." },
        { id: "b", text: "The chimes glow in the sunlight." },
        { id: "c", text: "The campfire's heat makes the chimes sing." },
        { id: "d", text: "The chimes make sound only when they hold still." },
      ] },
      { type: "number", prompt: "How many finds did the crew make in all?", unit: "finds" },
      { type: "write", prompt: "Explain your hunt to Commander Vega. Name one light, one sound, and one heat example from the outpost, and tell how you know each one.", minWords: 20 },
    ],
    rubric: ["Names a real example of light, of sound, and of thermal energy", "Tells how they know (you see light, sound comes from vibrations, heat feels warm or moves warm to cool)", "Uses a clue from the quest (the lamp, the drum, the cocoa, the sunny spot, or the campfire)"],
    hint: "Glows, crackles, warms: that's three clues. For the table, add all three numbers.",
    meter: { heat: 10, label: "Hunt map +10%", story: "The hunt map is complete" },
    discovery: { id: "soundwater", name: "Sound in water", who: "Kai", fact: "Sound travels about four times faster through water than through air. That's one reason whales can hear each other's songs from very far away." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["light", "sound", "thermal"] },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 16 },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The hunt map is full of light, sound, and heat! Your teacher will read your explanation.",
    wrong: [
      { step: 1, pick: "cold", hint: "A campfire warms you. Is there really such a thing as cold energy?" },
      { step: 1, missing: true, hint: "The fire glows, crackles, and warms your hands. That's three kinds of energy." },
      { step: 2, choice: "b", hint: "Glowing is light, not sound. What do the tubes do when the wind hits them?" },
      { step: 2, choice: "c", hint: "The chimes are far from the fire, and they ring on cold days too. What makes all sounds?" },
      { step: 2, choice: "d", hint: "Hold a chime still and it goes quiet. Sounds come from things that move back and forth." },
      { step: 3, value: 12, hint: "7 + 5 = 12 is only light and sound. Add the thermal finds too." },
      { step: 3, value: 7, hint: "7 is only the light finds. Add all three rows." },
      { step: 3, value: 15, hint: "Check your adding: 7 + 5 + 4." },
    ],
  },
};

export default {
  id: "SCI.3.8A-XP",
  standard: "SCI.3.8A-XP",
  engine: "expedition_station",
  title: "The Energy Hunt",
  planet: "Lumara",
  outpost: "Glow Garden · the garden outpost",
  grade: 3,
  subject: "Science",
  teks: "3.8A",
  supportingTeks: ["3.1B", "3.1D", "3.1E", "3.2B", "3.2C", "3.3A", "3.3C", "3.5B"],
  skillsChip: "3.8A · Light, sound, and heat all around",
  iCan: "I can find everyday examples of light, sound, and thermal energy (heat) around me. I can tell that sound comes from vibrations, light comes from a source and lets us see, and heat moves from warmer things to cooler things.",
  blurb: "The crew is on an energy hunt around Lumara's garden outpost. They track down light, sound, and heat in lamps, drums, cocoa, sunny spots, and a crackling campfire.",
  mission: "Find and sort light, sound, and thermal energy, test how sound and heat work, and fill in the outpost's energy hunt map.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.80 · LUMARA GARDEN OUTPOST",
  playableActs: [1, 2, 3],
  earthTrue: "Lumara and the crew are invented. Every lamp, drum, thermometer reading, and energy fact in this quest is real Earth science.",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Hunt map", heatUnit: "%", supplies: "Energy tags", suppliesUnit: "tags" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Welcome to the garden outpost on Lumara.",
    "Energy is hiding all around us: in lamps, bells, warm cocoa, and sunny spots. Our job is to find it.",
    "Light, sound, and heat work here just like on Earth. Look, listen, and feel. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Spot the energy", "Act 2 · Sound and heat", "Act 3 · The big hunt"],
    completes: [
      "You tagged light, sound, and heat, and you warmed up the hut, {firstName}!",
      "You made rice dance and saved the seedlings from the heat, {firstName}!",
      "The energy hunt map is complete, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Lumara: Kai thinks cold can move, and a drum makes rice dance. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: a silent bell, a chilly bench, and the great energy hunt. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai and I already disagree about ice cubes.",
      "Then we'll test sound and heat.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. It's the last night of the energy hunt.",
      "Fix what's broken, then finish the hunt map.",
    ],
  }),
  tasks,
};
