// Expedition Station — The Fable Fire (ELA.3.8A-XP)
// Grade 3 · ELAR · Cindara. Main standard 3.8A (infer the theme of a work,
// distinguishing theme from topic); also practices 3.9A (characteristics of
// folktales, fables, and fairy tales), 3.6F (inference), 3.7C (text evidence),
// 3.3B (context clues), 3.8B (characters), 3.8C (plot), 3.7B (written response).
// All tales are original, written for this quest: around a lava-rock fire, the
// people of Cindara tell their fables and folktales, and the crew collects them.
import { CREW, acts, passage } from "./_shared.js";

const passages = {
  A: passage("A", { title: "The Cinder Fox and the Last Ember", genre: "Fable" }, [
    [
      "On the coldest night of the year, the great fire on Cindara burned low.",
      "Only one bright ember was left, glowing orange in the ashes.",
      "Cinder Fox saw it first.",
      "\"Mine!\" she said, and she tucked the ember under her thick, bushy tail.",
    ],
    [
      "Soon a lava lizard crept up, shivering.",
      "\"Please, Fox, may I warm my toes by your ember?\" he asked.",
      "\"No,\" said Fox. \"If I share it, there will be less heat for me.\"",
      "A family of glow moths asked next, and Fox turned her back on them too.",
    ],
    [
      "But an ember needs air to keep burning.",
      "Under Fox's heavy tail, the ember was smothered.",
      "Its orange glow faded to gray, and then it went cold.",
      "Fox shivered alone in the dark.",
    ],
    [
      "Across the rocks, she saw a warm light.",
      "The lizard and the moths had piled their tiny sparks and dry moss in a ring.",
      "Together, they had made a crackling fire.",
      "\"Come and sit with us,\" called the lizard. \"There is room for everyone.\"",
      "Fox sat down, and her cheeks grew hot, but not from the fire.",
    ],
    ["Moral: A fire that is shared warms everyone, but a fire kept to yourself can leave you cold."],
  ]),
  B: passage("B", { title: "Why the Pebble Crabs Guard the Lava River", genre: "Folktale" }, [
    [
      "Long, long ago, before anyone can remember, a village sat beside the Red River of Cindara.",
      "The river was not made of water. It was made of slow, glowing lava.",
      "One day, the lava began to rise and creep toward the village.",
    ],
    [
      "The villagers ran to the strongest creature they knew, the great Rock Bull.",
      "\"Please push the lava back!\" they begged.",
      "Rock Bull pushed with all his might, but the lava was too hot, and he backed away.",
    ],
    [
      "Next the villagers asked Flame Hawk, the fastest flier in the sky.",
      "Flame Hawk flapped her wings to cool the lava, but it only glowed brighter.",
      "The lava kept creeping closer.",
    ],
    [
      "At last, a tiny pebble crab stepped forward.",
      "\"We can help,\" she said.",
      "Rock Bull laughed. \"You are no bigger than a seed!\"",
    ],
    [
      "The crab did not argue.",
      "She picked up one cool, gray stone and set it at the edge of the river.",
      "Then a hundred more pebble crabs came, and then a thousand.",
      "Each crab carried just one stone, but stone by stone, they built a long, low wall.",
      "The lava bumped against the wall and stopped.",
    ],
    [
      "The village was saved, and Rock Bull bowed his great head to the tiny crabs.",
      "That is why, even today, pebble crabs line the banks of the Red River, each one guarding a single stone.",
      "And that is why the people of Cindara still say, \"No helper is too small.\"",
    ],
  ]),
  C: passage("C", { title: "The Smallest Spark", genre: "Fable" }, [
    [
      "Spark Beetle had the smallest light on all of Cindara.",
      "Her glow was only as big as a grain of sand.",
      "The lantern lizards, whose tails glowed like torches, laughed at her. \"Why do you even bother to shine?\" they said.",
      "Spark Beetle felt so small that she hid under a rock.",
    ],
    [
      "One night, a great cloud of ash rolled over the hills.",
      "The lantern lizards ran into their caves and hid their tails from the ash.",
      "In the dark, a young moth named Dusk lost her way home.",
      "\"Help!\" she cried. \"I can't see anything!\"",
    ],
    [
      "Spark Beetle heard her.",
      "She was scared, but she crawled out and let her tiny light glow.",
      "\"Follow me,\" she called.",
      "Dusk followed the little dot of light, step by step, all the way home.",
    ],
    [
      "The next morning, the lantern lizards heard what had happened.",
      "They never laughed at Spark Beetle again.",
    ],
    ["Moral: No light is too small to help someone find the way."],
  ]),
  D: passage("D", { title: "The Singing Stone", genre: "Fairy tale" }, [
    [
      "Once upon a time, a young prince lived in a castle of black glass on top of a volcano.",
      "In the castle garden sat a magic stone that sang whenever someone told the truth.",
    ],
    [
      "One day, the prince broke his mother's favorite bowl.",
      "He hid the pieces and said, \"The wind knocked it over.\"",
      "The magic stone stayed silent.",
    ],
    [
      "All week, the prince could not sleep.",
      "His secret felt as heavy as a mountain.",
    ],
    [
      "At last, he went to the queen.",
      "\"I broke your bowl, and I am sorry,\" he said.",
      "At once, the magic stone began to sing, and the prince felt as light as a feather.",
      "The queen hugged him. \"A bowl can be fixed,\" she said. \"Trust is much harder to fix.\"",
    ],
  ]),
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Smothered ember", machine: "Word Kiln", icon: "static", speaker: "nova", passage: ["A"],
    line: "Fire-keeper Sarn just told us the first tale. One word in it made me curious. Let's figure it out together.",
    question: "Read Passage A. \"Under Fox's heavy tail, the ember was smothered.\" What does smothered mean here?",
    hint: "Read the sentence just before it. What does an ember need to keep burning?",
    meter: { heat: 5, label: "Story fire +5%", story: "The first tale is in Nova's recorder" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Covered up so it could not get air" },
      { id: "b", text: "Made hotter and brighter" },
      { id: "c", text: "Broken into tiny pieces" },
      { id: "d", text: "Carried far away" },
    ],
    rightFeedback: "Right! The heavy tail covered the ember, so it could not get air and went out.",
    wrong: [
      { choice: "b", hint: "Read what happens next. The glow faded to gray. Did it get hotter?" },
      { choice: "c", hint: "Nothing says the ember broke. The sentence before says it needs air. What did the tail do to the air?" },
      { choice: "d", hint: "The ember stayed under Fox's tail. What does a heavy tail do to something under it?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Is it a fable?", machine: "Tale Sorter", icon: "scan", speaker: "vega", passage: ["A"],
    line: "Sarn calls this tale a fable. Before we file it, let's check that it really is one.",
    question: "What makes \"The Cinder Fox and the Last Ember\" a fable? Pick every clue.",
    hint: "Fables are short. Their characters are often animals that act like people. They teach a lesson.",
    meter: { heat: 5, label: "Story fire +5%", story: "The tale is filed under Fables" },
    discovery: { id: "fabula", name: "The word fable", who: "Nova", fact: "The word fable comes from the Latin word fabula, which means a story or tale." },
    answer: { kind: "multi", correct: ["a", "b", "c"] },
    items: [
      { id: "a", text: "The animals talk and act like people." },
      { id: "b", text: "It ends with a moral, or lesson." },
      { id: "c", text: "It is short, with just a few characters." },
      { id: "d", text: "It gives true facts about how lizards live." },
      { id: "e", text: "It starts with \"Once upon a time\" and has a castle." },
    ],
    rightFeedback: "Yes! Talking animals, a short story, and a lesson at the end. That's a fable!",
    wrong: [
      { pick: "d", hint: "A lava lizard that asks to warm its toes is not a true fact. Fables are made-up stories." },
      { pick: "e", hint: "Look at how the tale starts. Is there a castle anywhere in it?" },
      { missing: true, hint: "There is more than one clue. Think about the characters, the length, and the ending." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Find the moral", machine: "Lesson Lamp", icon: "log", speaker: "kai",
    passage: ["A"],
    line: "Sarn says every fable hides a lesson for the listener. I bet this one says it right out loud somewhere.",
    question: "Highlight the sentence that states the moral of the fable.",
    hint: "A fable often states its moral in the very last line, for the listener.",
    meter: { heat: 5, label: "Story fire +5%", story: "Kai lights the lesson lamp" },
    answer: { kind: "highlight", groups: [["A5.1"]] },
    rightFeedback: "Found it! The last line tells the lesson for everyone listening.",
    wrong: [
      { sentence: "A4.4", hint: "The lizard's words hint at the lesson. Which sentence tells the lesson to the listener, at the very end?" },
      { sentence: "A1.4", hint: "That tells what Fox did. A moral is a lesson for the listener. Look at the end." },
      { sentence: "A3.1", hint: "That is a fact about embers. Which sentence begins with the word Moral?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Hot cheeks", machine: "Read the Crew", icon: "crew", speaker: "nova", passage: ["A"],
    line: "At the end, Fox's cheeks grow hot, but not from the fire. I want to know why.",
    question: "Part 1: How does Fox feel at the end? Part 2: Highlight a sentence that helps show why she feels that way.",
    parts: [
      { type: "choice", prompt: "How does Fox feel at the end?", choices: [
        { id: "a", text: "Embarrassed, because she was selfish and the others were kind" },
        { id: "b", text: "Too warm, because she sat too close to the fire" },
        { id: "c", text: "Angry at the lizard" },
        { id: "d", text: "Proud of her ember" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that helps show why Fox feels this way.", passage: "A" },
    ],
    hint: "The tale says her cheeks were NOT hot from the fire. Think about what Fox did earlier and what the lizard does now.",
    meter: { supplies: 1, label: "Story stones +1", story: "Nova understands Cinder Fox" },
    discovery: { id: "moral", name: "The moral", who: "Kai", fact: "The lesson of a fable is called its moral. Many old fables say the moral in the very last line." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A4.4", "A2.3", "A2.4"]] },
    ] },
    rightFeedback: "Yes! Fox would not share, but the lizard still made room for her. No wonder she felt embarrassed.",
    wrong: [
      { step: 1, choice: "b", hint: "The tale says her cheeks were hot, but NOT from the fire. So why else could they be hot?" },
      { step: 1, choice: "c", hint: "The lizard invites Fox to sit with them. Would that make her angry?" },
      { step: 1, choice: "d", hint: "Her ember went cold. Is there anything left to be proud of?" },
      { step: 2, sentence: "A3.1", hint: "That is a fact about embers. Find a sentence about how Fox or the lizard acted." },
      { step: 2, sentence: "A1.1", hint: "That tells about the night. Find what Fox said, or what the lizard said to her." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The fire sputters!", machine: "Theme Forge", icon: "quake", speaker: "vega", passage: ["A"],
    line: "Surprise! The storytelling fire is sputtering. Sarn says it only roars again when a listener names the tale's true theme, not just its topic.",
    question: "Part 1: Pick the TOPIC of the fable. Part 2: Pick the THEME. Part 3: Highlight TWO sentences from the story that support the theme.",
    parts: [
      { type: "choice", prompt: "What is the TOPIC? (What is the story about?)", choices: [
        { id: "a", text: "A fox and a fire on a cold night" },
        { id: "b", text: "Sharing what you have helps everyone." },
        { id: "c", text: "Never trust a lizard." },
        { id: "d", text: "How to build a campfire" },
      ] },
      { type: "choice", prompt: "What is the THEME? (What lesson does the story teach?)", choices: [
        { id: "a", text: "An ember goes out under a fox's tail." },
        { id: "b", text: "When you share, everyone is better off, but greed can leave you with nothing." },
        { id: "c", text: "Sharing" },
        { id: "d", text: "Lizards are good at making fires." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence that shows Fox being greedy and one that shows what sharing did for the others.", passage: "A", count: 2 },
    ],
    hint: "The topic is what the story is about, in a few words. The theme is the lesson, told as a full sentence.",
    meter: { heat: 10, label: "Story fire +10%", story: "The fire roars back to life" },
    discovery: { id: "firetriangle", name: "What fire needs", who: "Nova", fact: "A fire needs three things to keep burning: heat, fuel, and oxygen from the air. Take away any one, and the fire goes out." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["A1.4", "A2.3", "A2.4"], ["A4.2", "A4.3", "A4.4"]] },
    ] },
    rightFeedback: "The fire roars! The topic is a fox and a fire. The theme is the lesson: sharing helps everyone, and greed can leave you cold.",
    wrong: [
      { step: 1, choice: "b", hint: "That is a lesson, so it's the theme. The topic just names what the story is about." },
      { step: 1, choice: "c", hint: "The lizard is kind in this tale. What is the story mostly about?" },
      { step: 1, choice: "d", hint: "The tale doesn't teach how to build a fire. Who is in the story, and what do they want?" },
      { step: 2, choice: "a", hint: "That is something that happens in the story. A theme is the lesson it teaches." },
      { step: 2, choice: "c", hint: "One word names a topic. A theme is a whole sentence. What does the tale teach about sharing?" },
      { step: 2, choice: "d", hint: "That is about the characters, not a lesson for the listener." },
      { step: 3, sentence: "A5.1", hint: "The moral states the lesson. Find story events that SHOW it, one about Fox and one about the others." },
      { step: 3, sentence: "A3.1", hint: "That is a fact about embers. Find what Fox did, and what the lizard and moths did." },
      { step: 3, sentence: "A1.1", hint: "That tells about the night. Find a sentence where Fox is greedy." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Theme or topic?", machine: "Sort Bay", icon: "cells", speaker: "kai", passage: ["B"],
    line: "Sarn's second tale is a folktale about pebble crabs. I wrote idea cards, but they got mixed up. Some are themes, and some are only topics.",
    question: "Sort each card. Is it a theme (a lesson, in a full sentence) or a topic (what the tale is about, in a word or two)?",
    hint: "A theme teaches a lesson and is a full sentence. A topic just names a thing or an idea.",
    meter: { heat: 5, label: "Story fire +5%", story: "The idea cards are sorted" },
    discovery: { id: "aesop", name: "Very old fables", who: "Kai", fact: "Many famous fables are called Aesop's fables. People in ancient Greece told them more than 2,000 years ago." },
    answer: { kind: "sort", bins: { s1: "topic", s2: "topic", s3: "theme", s4: "topic", s5: "theme", s6: "topic", s7: "theme" } },
    rightFeedback: "Sorted! Pebble crabs, a lava river, teamwork, and courage are topics. The full-sentence lessons are themes.",
    sort: {
      bins: [{ id: "theme", label: "Theme (a lesson)" }, { id: "topic", label: "Topic (a word or two)" }],
      items: [
        { id: "s1", label: "Pebble crabs" },
        { id: "s2", label: "A lava river" },
        { id: "s3", label: "Even small helpers can make a big difference." },
        { id: "s4", label: "Teamwork" },
        { id: "s5", label: "When everyone does a little, big problems can be solved." },
        { id: "s6", label: "Courage" },
        { id: "s7", label: "Don't judge someone by how big they are." },
      ],
    },
    wrong: [
      { item: "s1", hint: "Pebble crabs are characters in the tale. Does that teach a lesson?" },
      { item: "s2", hint: "A lava river is part of the setting. Is it a lesson, or just a thing?" },
      { item: "s3", hint: "Read it again. It is a full sentence that teaches something. What kind of card is that?" },
      { item: "s4", hint: "Teamwork is one word. It names an idea, but it doesn't say what we should learn about it." },
      { item: "s5", hint: "This card tells a lesson in a full sentence. Is that a topic or a theme?" },
      { item: "s6", hint: "Courage is one word. What would the lesson about courage be?" },
      { item: "s7", hint: "This card tells readers what to do or not do. That's a lesson. Where do lessons go?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Folktale clues", machine: "Tale Sorter", icon: "scan", speaker: "vega", passage: ["B"],
    line: "Sarn says the pebble crab tale is a folktale, passed from grandparent to grandchild. Let's find the clues.",
    question: "Which clues show that \"Why the Pebble Crabs Guard the Lava River\" is a folktale? Pick every one.",
    hint: "Folktales are very old stories. They often start long ago, repeat things in threes, and explain why something is the way it is.",
    meter: { supplies: 1, label: "Story stones +1", story: "The tale is filed under Folktales" },
    answer: { kind: "multi", correct: ["a", "b", "c"] },
    items: [
      { id: "a", text: "It begins \"Long, long ago.\"" },
      { id: "b", text: "It explains why something on Cindara is the way it is today." },
      { id: "c", text: "Three helpers try, and the third one saves the day." },
      { id: "d", text: "It has a castle and a magic wand." },
      { id: "e", text: "It is a report with true facts about lava." },
    ],
    rightFeedback: "Right! Long ago, a pattern of three, and a \"that is why\" ending. Classic folktale!",
    wrong: [
      { pick: "d", hint: "Look again. Is there a castle or a wand anywhere in the tale?" },
      { pick: "e", hint: "Talking crabs and a bowing bull are not true facts. This is a made-up story." },
      { missing: true, hint: "There is more than one clue. Check the first line, the last paragraph, and how many helpers try." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Stone by stone", machine: "Evidence Net", icon: "snap", speaker: "nova", passage: ["B"],
    line: "My theme card for the folktale says: Even small helpers can make a big difference. Let's pin proof under it.",
    question: "Highlight TWO sentences: one that shows what the small crabs DID, and one that shows what HAPPENED because of it.",
    hint: "Look in paragraphs 5 and 6. What did the crabs carry, and what did the lava do?",
    meter: { heat: 5, label: "Story fire +5%", story: "Proof is pinned under the theme" },
    discovery: { id: "panchatantra", name: "Fables from India", who: "Nova", fact: "The Panchatantra is a very old collection of animal fables from India. Its stories are more than 1,500 years old and have been told in many languages." },
    answer: { kind: "highlight", groups: [["B5.2", "B5.3", "B5.4"], ["B5.5", "B6.1"]] },
    rightFeedback: "Proof pinned! The crabs each carried one stone, and together they stopped the lava.",
    wrong: [
      { sentence: "B4.3", hint: "That shows Rock Bull thought the crab was too small. Find what the crabs actually did." },
      { sentence: "B2.3", hint: "That is about Rock Bull, the biggest helper. Find sentences about the small crabs." },
      { sentence: "B1.2", hint: "That tells about the setting. Look in paragraphs 5 and 6." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "One-word theme?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    passage: ["B"],
    line: 'Kai: "I found the theme of the pebble crab tale. It\'s teamwork! One word. Done!"',
    nova: 'Nova: "Teamwork is the topic. A theme is the whole lesson, like: Even small helpers can make a big difference when they work together."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Does one word teach a lesson? Or does it just name what the story is about?",
    meter: { heat: 5, label: "Story fire +5%", story: "The crew agrees on what a theme is" },
    discovery: { id: "grimm", name: "Collecting folktales", who: "Kai", fact: "Two brothers in Germany, Jacob and Wilhelm Grimm, wrote down folktales that people told out loud. Their first book of tales came out in 1812." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A theme is a lesson told in a full sentence. One word, like teamwork, only names the topic." },
      { id: "B", text: "Nova, because a theme has to use lots of big words." },
      { id: "C", text: "Kai. A theme is always one word, like teamwork or friendship." },
      { id: "D", text: "Kai. The theme is what happens in the story, and the crabs work as a team." },
    ],
    writtenPrompt: "Tell Kai in your own words how a theme is different from a topic.",
    debateHints: {
      wrongWho: "Teamwork names an idea, but what does the tale TEACH about it? A lesson needs a full sentence.",
      wrongReason: "Right person, check the reason. What makes something a theme instead of a topic?",
      right: "Nova is right. A theme is a lesson in a full sentence. One word only names the topic.",
    },
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The lava river rises!", machine: "Tale Timeline", icon: "trail", speaker: "vega", passage: ["B"],
    line: "Surprise! A thin stream of real lava is creeping toward our camp. Sarn smiles and says, \"Remember the pebble crabs.\" Quick, help us use the tale!",
    question: "Part 1: Put the events of the folktale in order. Part 2: Figure out what creep means. Part 3: Highlight the sentence that explains why something is the way it is today.",
    parts: [
      { type: "order", prompt: "Put the events in order, first to last.", items: [
        { id: "e4", text: "A tiny pebble crab stepped forward." },
        { id: "e2", text: "Rock Bull pushed the lava, but backed away." },
        { id: "e5", text: "The crabs built a wall, stone by stone." },
        { id: "e1", text: "The lava began to rise toward the village." },
        { id: "e3", text: "Flame Hawk flapped her wings, but the lava glowed brighter." },
      ] },
      { type: "choice", prompt: "\"The lava began to rise and creep toward the village.\" What does creep mean?", choices: [
        { id: "a", text: "Move slowly and quietly" },
        { id: "b", text: "Jump up quickly" },
        { id: "c", text: "Freeze and stop" },
        { id: "d", text: "Make a loud noise" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that explains why something on Cindara is the way it is today.", passage: "B" },
    ],
    hint: "The helpers try one at a time. Also, the lava is slow. And a folktale's \"that is why\" line explains something about today.",
    meter: { heat: 10, label: "Story fire +10%", story: "The villagers build a stone wall, just like the crabs" },
    discovery: { id: "redcrabs", name: "Crabs on the move", who: "Nova", fact: "On Christmas Island in the Indian Ocean, millions of red crabs march from the forest to the sea at the same time each year to lay their eggs." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["e1", "e2", "e3", "e4", "e5"] },
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B6.2", "B6.3"]] },
    ] },
    rightFeedback: "The camp is safe! Everyone carried one stone each, and the lava stopped at the wall. The tale's lesson came true.",
    wrong: [
      { step: 1, position: 0, hint: "Every problem starts somewhere. What did the lava do first?" },
      { step: 1, position: 1, hint: "The villagers ran to the strongest creature first. Who was that?" },
      { step: 1, position: 2, hint: "Who did the villagers ask second, after Rock Bull?" },
      { step: 1, position: 3, hint: "The crab had to offer to help before the wall could be built." },
      { step: 2, choice: "b", hint: "The river is made of SLOW lava. Would it jump quickly?" },
      { step: 2, choice: "c", hint: "The lava kept creeping closer. Did it stop?" },
      { step: 2, choice: "d", hint: "Nothing in the tale says the lava was loud. How does slow lava move?" },
      { step: 3, sentence: "B1.1", hint: "That tells when and where the tale begins. Find the \"that is why\" sentence at the end." },
      { step: 3, sentence: "B5.5", hint: "That is what happened long ago. Which sentence tells about today?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Under a rock", machine: "Read the Crew", icon: "crew", speaker: "nova", passage: ["C"],
    line: "The last tale is about a beetle with a very tiny light. At first, she doesn't seem to like herself much.",
    question: "Part 1: How does Spark Beetle feel at the start of the fable? Part 2: Highlight the sentence that shows what she DID because she felt that way.",
    parts: [
      { type: "choice", prompt: "How does Spark Beetle feel at the start?", choices: [
        { id: "a", text: "Small and ashamed of her light" },
        { id: "b", text: "Proud of her bright glow" },
        { id: "c", text: "Angry and ready to fight" },
        { id: "d", text: "Sleepy and bored" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows what Spark Beetle did because of how she felt.", passage: "C" },
    ],
    hint: "The lizards laugh at her. What does she do right after that?",
    meter: { supplies: 1, label: "Story stones +1", story: "Nova adds Spark Beetle to the character board" },
    discovery: { id: "fireflies", name: "Fireflies", who: "Kai", fact: "Fireflies are really beetles, not flies. They make light inside their bodies and flash it to send signals to each other." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["C1.4"]] },
    ] },
    rightFeedback: "Yes! She felt so small that she hid under a rock.",
    wrong: [
      { step: 1, choice: "b", hint: "Her glow is as tiny as a grain of sand, and others laugh at it. Would she feel proud?" },
      { step: 1, choice: "c", hint: "She doesn't fight anyone. What does she do after the lizards laugh?" },
      { step: 1, choice: "d", hint: "Nothing says she is sleepy. How might it feel to be laughed at?" },
      { step: 2, sentence: "C1.3", hint: "That shows what the lizards did. Which sentence shows what Spark Beetle did next?" },
      { step: 2, sentence: "C1.2", hint: "That tells how big her light is. What did she DO?" },
      { step: 2, sentence: "C3.2", hint: "That is later, when she is brave. Look at the start of the fable." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's theme card", machine: "Repair", icon: "log", speaker: "kai", passage: ["C"],
    line: "I wrote the theme card for \"The Smallest Spark.\" It says: Spark Beetle leads Dusk home in the dark. Nova says I made a mistake. What did I do wrong?",
    question: "Part 1: What went wrong with Kai's theme card? Part 2: Pick the best fix.",
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "He told what happens in the story, not the lesson it teaches." },
        { id: "b", text: "He spelled Dusk's name wrong." },
        { id: "c", text: "He used a full sentence, but a theme should be one word." },
        { id: "d", text: "He wrote about the wrong tale." },
      ] },
      { type: "choice", prompt: "Pick the best fix for the theme card.", choices: [
        { id: "a", text: "Light" },
        { id: "b", text: "Even someone small can make a big difference for others." },
        { id: "c", text: "Spark Beetle is small and has a tiny light." },
        { id: "d", text: "A moth gets lost when ash covers the hills." },
      ] },
    ],
    hint: "A theme isn't a summary of the plot. Ask: what lesson could anyone use, even someone who is not a beetle?",
    meter: { heat: 5, label: "Story fire +5%", story: "Kai's theme card is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Fixed! The plot is what happens. The theme is the lesson: even someone small can make a big difference.",
    wrong: [
      { step: 1, choice: "b", hint: "Dusk is spelled just right. Does Kai's card tell a lesson, or does it tell events?" },
      { step: 1, choice: "c", hint: "Themes ARE full sentences. The problem is what Kai's sentence says." },
      { step: 1, choice: "d", hint: "Spark Beetle and Dusk are in this tale. Is Kai's card a lesson or a plot event?" },
      { step: 2, choice: "a", hint: "One word names a topic. A theme is a full-sentence lesson." },
      { step: 2, choice: "c", hint: "That describes a character. What lesson does the fable teach?" },
      { step: 2, choice: "d", hint: "That is another event from the story. A theme is a lesson, not an event." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Two tales, one lesson", machine: "Twin Flames", icon: "relay", speaker: "vega", passage: ["B", "C"],
    line: "Sarn says two of tonight's tales are cousins. Different stories, same heart. Can you see it?",
    question: "Part 1: What theme do the pebble crab folktale and \"The Smallest Spark\" share? Part 2: How are the tales different? Part 3: Highlight one sentence from each tale that shows the shared theme.",
    parts: [
      { type: "choice", prompt: "What theme do both tales share?", choices: [
        { id: "a", text: "Even small helpers can make a big difference." },
        { id: "b", text: "Always share your fire with others." },
        { id: "c", text: "Lava is very dangerous." },
        { id: "d", text: "Moths can get lost in the dark." },
      ] },
      { type: "choice", prompt: "How are the two tales different?", choices: [
        { id: "a", text: "They have different characters and topics, but the same lesson." },
        { id: "b", text: "They have different themes." },
        { id: "c", text: "One teaches a lesson, and the other does not." },
        { id: "d", text: "They are the same story with new names." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from each tale that shows a small character making a big difference.", passage: ["B", "C"], count: 2 },
    ],
    hint: "Crabs and lava in one tale. A beetle and the dark in the other. What do the small characters do in BOTH?",
    meter: { heat: 10, label: "Story fire +10%", story: "Two tales are linked in the collection" },
    discovery: { id: "snowmonkeys", name: "Hot spring monkeys", who: "Nova", fact: "In Japan, snow monkeys warm up in natural hot springs in winter. Hot rock deep underground heats the water." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B5.4", "B5.5", "B6.1"], ["C3.4", "C3.2"]] },
    ] },
    rightFeedback: "You see it! Different characters and topics, but both tales teach that even small helpers can make a big difference.",
    wrong: [
      { step: 1, choice: "b", hint: "That's the lesson of the Cinder Fox fable. What do the crabs and the beetle have in common?" },
      { step: 1, choice: "c", hint: "That is about a topic in one tale. There's no lava in \"The Smallest Spark.\"" },
      { step: 1, choice: "d", hint: "That is an event from one tale, not a lesson both tales teach." },
      { step: 2, choice: "b", hint: "Look back at Part 1. Do the tales teach the same lesson or different ones?" },
      { step: 2, choice: "c", hint: "Both tales teach a lesson. What is different about them?" },
      { step: 2, choice: "d", hint: "One has crabs and lava. One has a beetle and the dark. Are they really the same story?" },
      { step: 3, sentence: "B4.3", hint: "That shows Rock Bull doubting the crab. Find where the crabs make a difference." },
      { step: 3, sentence: "C1.2", hint: "That shows the beetle is small. Find where she makes a big difference." },
      { step: 3, sentence: "C1.4", hint: "That's when she hides. Find where her little light helps someone." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Carve the theme stone", machine: "Theme Chisel", icon: "brief", speaker: "nova", passage: ["A", "C"],
    line: "The people of Cindara carve each tale's theme on a lava stone by the fire. Sarn asked us to carve one!",
    question: "Pick \"The Cinder Fox and the Last Ember\" or \"The Smallest Spark.\" Write its theme as a full sentence. Then add one detail from the tale that supports it.",
    hint: "Start with: The theme of this tale is... Use a full sentence that teaches a lesson, not just a word. Then tell what a character did.",
    meter: { supplies: 1, label: "Story stones +1", story: "A new theme stone sits by the fire" },
    answer: { kind: "write", minWords: 15 },
    minWords: 15,
    teacherScored: true,
    rubric: ["States a theme as a full-sentence lesson (not a topic word or plot event)", "Uses a detail from the tale that supports the theme", "Complete sentences with capitals and end punctuation"],
    rightFeedback: "Your theme stone is carved! Your teacher will read what you wrote.",
    wrong: [],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The mystery tale", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["D"],
    line: "Surprise! A child from the village steps up and tells one more tale. Sarn says it's a new kind. Name it, find its theme, and send it with our collection.",
    question: "Part 1: What kind of tale is \"The Singing Stone\"? Part 2: Pick its theme, not its topic. Part 3: Write 2–3 sentences that state the theme and give a detail from the tale as proof.",
    parts: [
      { type: "choice", prompt: "What kind of tale is \"The Singing Stone\"?", choices: [
        { id: "a", text: "A fairy tale, because it starts \"Once upon a time\" and has a prince, a queen, and magic" },
        { id: "b", text: "A fable, because it ends with a moral stated on its own line" },
        { id: "c", text: "A folktale that explains why something is the way it is today" },
        { id: "d", text: "An informational text with true facts about volcanoes" },
      ] },
      { type: "choice", prompt: "Which is the theme, not the topic?", choices: [
        { id: "a", text: "A broken bowl" },
        { id: "b", text: "Telling the truth is better than hiding a mistake." },
        { id: "c", text: "Honesty" },
        { id: "d", text: "A prince breaks a bowl and hides the pieces." },
      ] },
      { type: "write", prompt: "State the theme in a full sentence. Then give a detail from the tale as proof.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["States the theme as a full-sentence lesson", "Uses a detail from the tale as proof", "Complete sentences with capitals and end punctuation"],
    hint: "Fairy tales often have royalty and magic. For the theme, ask: what did the prince learn that anyone could use?",
    meter: { heat: 10, label: "Story fire +10%", story: "The tale collection is sent to Mission Control" },
    discovery: { id: "pompeii", name: "Pompeii", who: "Kai", fact: "Almost 2,000 years ago, ash from Mount Vesuvius buried the Roman town of Pompeii. Scientists have dug up much of the town to learn how people lived." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Collection sent! Your teacher will read your theme statement.",
    wrong: [
      { step: 1, choice: "b", hint: "Look at the end. Is there a line that starts with Moral? What about the magic stone and the castle?" },
      { step: 1, choice: "c", hint: "Does the tale say \"that is why\" about something today? Look at how it starts and who is in it." },
      { step: 1, choice: "d", hint: "A singing magic stone is not a true fact. This is a made-up story." },
      { step: 2, choice: "a", hint: "A bowl is a thing in the story. That's a topic. What lesson does the prince learn?" },
      { step: 2, choice: "c", hint: "One word names the topic. Turn it into a lesson: what is true about honesty?" },
      { step: 2, choice: "d", hint: "That is what happens in the story. The theme is the lesson it teaches." },
    ],
  },
};

export default {
  id: "ELA.3.8A-XP",
  standard: "ELA.3.8A-XP",
  engine: "expedition_station",
  title: "The Fable Fire",
  planet: "Cindara",
  outpost: "Ember Ring Village · storytelling night",
  grade: 3,
  subject: "ELAR",
  teks: "3.8A",
  supportingTeks: ["3.9A", "3.6F", "3.7C", "3.3B", "3.8B", "3.8C", "3.7B"],
  skillsChip: "3.8A · Infer theme, not just topic",
  iCan: "I can figure out the theme of a story and tell it apart from the topic. I can tell fables, folktales, and fairy tales apart.",
  blurb: "Around a lava-rock fire on Cindara, the villagers tell their oldest fables and folktales. The crew wants to collect them all, but each tale's lesson is hidden inside the story.",
  mission: "Listen to the tales of Cindara, find each one's theme, and prove it with evidence before the collection goes to Mission Control.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.8A · CINDARA EMBER RING",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Story fire", heatUnit: "%", supplies: "Story stones", suppliesUnit: "stones" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega on Cindara. Tonight we are guests at the Ember Ring.",
    "The villagers gather around a lava-rock fire to tell their oldest fables and folktales. Fire-keeper Sarn has agreed to let us collect them.",
    "Every tale hides a lesson. Help us find each theme, and prove it. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The last ember", "Act 2 · The lava river", "Act 3 · The smallest spark"],
    completes: [
      "The fire roars again, {firstName}! You found the theme of the first fable, not just its topic.",
      "Great work, {firstName}! The pebble crab folktale is in the collection, and our camp is safe.",
      "The tale collection is on its way to Mission Control, {firstName}! Sarn says you listen like a true Cindaran.",
    ],
    teasers: [
      "Next on Cindara: Sarn tells a very old folktale about a river of lava. Act 2 is open now, or come back to it next time.",
      "Next on Cindara: one more fable, and a surprise tale from a village child. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The fire is warm, and Sarn is telling a folktale that is older than anyone can remember.",
      "It's about tiny pebble crabs and a river of lava. Let's find its lesson.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Sarn has saved the smallest tale for last.",
      "Listen closely. Then help us finish the collection and send it home.",
    ],
  }),
  tasks,
};
