// Expedition Station — The Fossil Dig (SCI.3.12D-XP)
// Grade 3 · Science · Cindara (lava world). Main standard 3.12D (explore and
// explain how fossils provide evidence of organisms that lived long ago and of
// environments that existed long ago, such as fossils of plants and animals
// that lived in a different environment than today). Supporting practices:
// 3.1E (collect observations as evidence), 3.2B (analyze data for patterns),
// 3.2C (use math to compare data), 3.3A (explanations supported by evidence),
// 3.3C (respectful scientific discussion), 3.5A (identify and use patterns),
// 3.5B (cause and effect), 3.5G (how things change over time).
//
// Earth-true rule: Cindara and the crew are invented. Lava rock on Cindara
// holds no fossils, so the crew studies REAL Earth fossils in rock samples
// sent from Earth. Every fossil, place, and fact is real Earth science.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "What's in the crate?", machine: "Earth Rock Vault", icon: "scan", speaker: "nova",
    line: "The supply ship from Earth brought a crate of rock samples. Some of them hold fossils! Our lava rock here never does, so these are a treat.",
    question: "What is a fossil?",
    hint: "Think about something that was once alive, a very long time ago.",
    meter: { heat: 5, label: "Fossil hall +5%", story: "The Earth crate is open" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The remains or traces of a plant or animal that lived long ago, kept in rock." },
      { id: "b", text: "Any rock that has a cool shape." },
      { id: "c", text: "A bone from an animal that died last year." },
      { id: "d", text: "A statue of a dinosaur made by people." },
    ],
    rightFeedback: "A fossil is the remains or traces of a living thing from long ago, kept in rock.",
    wrong: [
      { choice: "b", hint: "A fossil has to come from something that was once alive. Was a plain rock ever alive?" },
      { choice: "c", hint: "Fossils take thousands to millions of years to form. Is last year long ago enough?" },
      { choice: "d", hint: "People made the statue. A fossil comes from a real living thing. What is left of it?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Bones or tracks?", machine: "Sorting Tray", icon: "cells", speaker: "nova",
    line: "Scientists sort fossils into two groups. Body fossils are parts of the living thing. Trace fossils are signs it left behind, like marks it made.",
    question: "Sort each fossil: is it a body fossil or a trace fossil?",
    hint: "Is it a part of the animal or plant? Or is it a mark or sign the animal left?",
    meter: { supplies: 1, label: "Fossils cataloged +1", story: "The fossils are sorted into two groups" },
    discovery: { id: "coprolite", name: "Fossil poop", who: "Kai", fact: "Fossil poop is called a coprolite. It is a trace fossil, and scientists can study it to find out what an animal ate." },
    answer: { kind: "sort", bins: { f1: "body", f2: "trace", f3: "body", f4: "trace", f5: "body", f6: "trace" } },
    rightFeedback: "Bones, teeth, and shells are body fossils. Footprints, burrows, and fossil poop are trace fossils.",
    sort: {
      bins: [{ id: "body", label: "Body fossil" }, { id: "trace", label: "Trace fossil" }],
      items: [
        { id: "f1", label: "A dinosaur leg bone turned to stone" },
        { id: "f2", label: "A dinosaur footprint in rock" },
        { id: "f3", label: "A shark tooth" },
        { id: "f4", label: "A tunnel a worm dug in the mud" },
        { id: "f5", label: "A clam shell in rock" },
        { id: "f6", label: "Fossil poop" },
      ],
    },
    wrong: [
      { item: "f2", hint: "A footprint is not part of the dinosaur's body. It is a mark the dinosaur left." },
      { item: "f4", hint: "The worm is gone. Only the tunnel it dug is left. Is that a part of the worm, or a sign of it?" },
      { item: "f6", hint: "Poop is something an animal left behind, not a part of its body." },
      { item: "f1", hint: "A bone is a part of the dinosaur's body." },
      { item: "f3", hint: "A tooth is a part of the shark's body." },
      { item: "f5", hint: "The shell is a part of the clam's body." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "From shell to stone", machine: "Story Wall", icon: "trail", speaker: "kai",
    line: "I made cards that show how a sea animal's shell became a fossil. Then I dropped them. Oops.",
    question: "Put the steps in order to show how a fossil forms.",
    hint: "The animal has to be buried before layers can pile up on top of it.",
    meter: { heat: 5, label: "Fossil hall +5%", story: "The fossil story is in order" },
    discovery: { id: "palmwood", name: "Wood made of stone", who: "Nova", fact: "Texas's state stone is petrified palmwood. It formed when minerals in water slowly filled and replaced the wood of ancient palm trees." },
    answer: { kind: "order", correct: ["dies", "buried", "layers", "rock", "erode"] },
    items: [
      { id: "layers", text: "More layers of mud and sand pile up on top, for a very long time." },
      { id: "erode", text: "Wind and water wear away the rock, and the fossil is uncovered." },
      { id: "dies", text: "A sea animal with a shell dies." },
      { id: "rock", text: "The layers press down and harden into rock, with the shell's shape inside." },
      { id: "buried", text: "Mud and sand quickly cover the shell." },
    ],
    rightFeedback: "Dies, gets buried, layers pile up, the layers turn to rock, and erosion uncovers it. That takes millions of years!",
    wrong: [
      { position: 0, hint: "What has to happen to the animal first, before anything else?" },
      { position: 1, hint: "Right after the animal dies, something has to cover it quickly." },
      { position: 2, hint: "Layers pile up on top before they can harden into rock." },
      { position: 3, hint: "The fossil can't be uncovered until the layers have turned into rock." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Oldest on the bottom", machine: "Core Scanner", icon: "grid", speaker: "vega",
    line: "Earth sent a tall core of rock. It has layers stacked like pancakes. Layers of mud and sand settle on top of older layers.",
    question: "Which fossil is the OLDEST?",
    data: {
      title: "Earth rock core (read from top to bottom)",
      columns: ["Layer", "Where it is", "Fossil found"],
      rows: [
        ["1", "Top", "Snail shell"],
        ["2", "Middle", "Fish bone"],
        ["3", "Bottom", "Trilobite"],
      ],
    },
    hint: "New layers settle on top of old ones. Where are the oldest layers?",
    meter: { supplies: 1, label: "Fossils cataloged +1", story: "The rock core is dated" },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "The snail shell in Layer 1" },
      { id: "b", text: "The fish bone in Layer 2" },
      { id: "c", text: "The trilobite in Layer 3" },
      { id: "d", text: "They are all the same age." },
    ],
    rightFeedback: "The bottom layer settled first, so the trilobite is the oldest fossil.",
    wrong: [
      { choice: "a", hint: "Layer 1 is on top. It was the last layer to settle. Is that old or young?" },
      { choice: "b", hint: "The middle layer settled on top of another layer. Which layer was there first?" },
      { choice: "d", hint: "The layers settled one at a time, over a long time. Which one came first?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Giant steps", machine: "Earth Rock Vault", icon: "quake", speaker: "vega",
    line: "Surprise! Earth sent a heavy slab copied from a riverbed in Texas. It shows two trails of real dinosaur footprints. Nova measured one print from each trail.",
    question: "Part 1: Is a footprint a body fossil or a trace fossil? Part 2: How much longer is the plant-eater's print than the meat-eater's print? Part 3: The prints were pressed into soft mud. What does that tell us?",
    data: {
      title: "Dinosaur prints on the Texas slab",
      columns: ["Trail", "Shape of print", "Length of one print"],
      rows: [
        ["Big plant-eater", "Round, like a giant tub", "About 90 cm"],
        ["Meat-eater", "Three toes", "About 50 cm"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Is a dinosaur footprint a body fossil or a trace fossil?", choices: [
        { id: "a", text: "A trace fossil, because it is a mark the dinosaur left." },
        { id: "b", text: "A body fossil, because it is part of the dinosaur." },
        { id: "c", text: "Not a fossil at all, because there are no bones." },
      ] },
      { type: "number", prompt: "How many centimeters longer is the plant-eater's print than the meat-eater's print?", unit: "cm" },
      { type: "choice", prompt: "The prints were pressed into soft mud that later turned to rock. What does that tell us about this place long ago?", choices: [
        { id: "a", text: "The ground was soft, wet mud, like the edge of a sea or river." },
        { id: "b", text: "The ground was hot lava, like on Cindara." },
        { id: "c", text: "The ground was hard, dry rock." },
        { id: "d", text: "The ground was covered in thick ice." },
      ] },
    ],
    hint: "A footprint is a sign the animal left. Subtract to find how much longer.",
    meter: { heat: 10, label: "Fossil hall +10%", story: "The dinosaur slab is on display" },
    discovery: { id: "glenrose", name: "Dinosaur Valley", who: "Nova", fact: "At Dinosaur Valley State Park near Glen Rose, Texas, you can see real dinosaur footprints in the rock of the Paluxy River. They were made about 113 million years ago in mud near an ancient sea." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 40 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Footprints are trace fossils, the plant-eater's print is 40 cm longer, and soft mud means this was a wet place near water long ago.",
    wrong: [
      { step: 1, choice: "b", hint: "The footprint is not a piece of the dinosaur. It is a mark it made." },
      { step: 1, choice: "c", hint: "Fossils don't have to be bones. Marks left by living things long ago count too." },
      { step: 2, value: 140, hint: "You want to know how much LONGER. Should you add or subtract?" },
      { step: 2, value: 90, hint: "90 cm is the plant-eater's print. How much longer is it than 50 cm?" },
      { step: 2, value: 50, hint: "50 cm is the meat-eater's print. How much longer is the 90 cm print?" },
      { step: 3, choice: "b", hint: "No animal could walk on hot lava. What kind of ground holds a footprint?" },
      { step: 3, choice: "c", hint: "Try stepping on hard rock. Does your foot leave a print? What kind of ground does?" },
      { step: 3, choice: "d", hint: "The slab says the prints were pressed into mud. What kind of place has soft mud?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Fossil or fake?", machine: "Sorting Tray", icon: "cells", speaker: "kai",
    line: "I mixed some everyday things in with the Earth fossils to test you. Can you spot the real fossils?",
    question: "Sort each object: is it a fossil or not a fossil?",
    hint: "A fossil comes from a living thing that lived long ago, and it is kept in rock or something like rock.",
    meter: { supplies: 1, label: "Fossils cataloged +1", story: "The fakes are pulled out" },
    discovery: { id: "amber", name: "Trapped in amber", who: "Nova", fact: "Some insects are kept as fossils in amber. Amber is tree sap that trapped them millions of years ago and slowly hardened." },
    answer: { kind: "sort", bins: { o1: "fossil", o2: "not", o3: "fossil", o4: "not", o5: "fossil", o6: "not" } },
    rightFeedback: "The fern print, the insect in amber, and the mammoth tooth are from long ago. The beach shell, the dinner bone, and the toy are not fossils.",
    sort: {
      bins: [{ id: "fossil", label: "Fossil" }, { id: "not", label: "Not a fossil" }],
      items: [
        { id: "o1", label: "The print of a fern leaf in old rock" },
        { id: "o2", label: "A seashell picked up on a beach today" },
        { id: "o3", label: "An ancient insect trapped in amber" },
        { id: "o4", label: "A chicken bone from last week's dinner" },
        { id: "o5", label: "A mammoth tooth turned to stone" },
        { id: "o6", label: "A plastic toy dinosaur" },
      ],
    },
    wrong: [
      { item: "o2", hint: "This shell came from an animal living today. Is today long ago?" },
      { item: "o4", hint: "Last week is not long ago, and the bone hasn't turned to stone." },
      { item: "o6", hint: "A toy was made by people. Was it ever alive?" },
      { item: "o1", hint: "The fern is gone, but its print is kept in old rock. That's a sign of a plant from long ago." },
      { item: "o3", hint: "The insect lived long ago and was kept in hardened tree sap." },
      { item: "o5", hint: "Mammoths lived long ago, and this tooth turned to stone." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Shells up high", machine: "Telescope Link", icon: "static", speaker: "nova",
    line: "Earth scientists sent a photo from high on a tall mountain. Nothing lives in the sea up there. But the rock is full of fossil seashells!",
    question: "What do the fossil seashells tell us about that mountain rock long ago?",
    hint: "Where do animals with seashells live?",
    meter: { heat: 5, label: "Fossil hall +5%", story: "The mountain photo is explained" },
    discovery: { id: "everest", name: "Sea fossils on Mount Everest", who: "Nova", fact: "Rocks near the top of Mount Everest hold fossils of tiny sea animals. That rock formed on the floor of an ocean long ago and was slowly pushed up." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The rock formed under an ocean long ago, and later it was pushed up high." },
      { id: "b", text: "Birds carried the shells up the mountain." },
      { id: "c", text: "Sea animals used to climb mountains." },
      { id: "d", text: "The mountain was always there, just like it is today." },
    ],
    rightFeedback: "Seashell fossils are clues that the rock was once under the sea. The land changed over a very long time.",
    wrong: [
      { choice: "b", hint: "The shells are inside the rock, in its layers. Could birds put them inside solid rock?" },
      { choice: "c", hint: "Sea animals with shells need water to live. Where did they live?" },
      { choice: "d", hint: "Sea animals can't live on a dry mountain. So was this place always the same?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Only dinosaurs?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Fossils are just dinosaur bones. If it isn\'t a dinosaur, it isn\'t a fossil."',
    nova: 'Nova: "Fossils come from all kinds of living things, like plants, shells, fish, and insects. Footprints count too."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Look back at the sorting tray. Were all the fossils dinosaur bones?",
    meter: { heat: 5, label: "Fossil hall +5%", story: "Kai learns fossils aren't just dinosaurs" },
    discovery: { id: "trilobite", name: "Trilobites", who: "Kai", fact: "Trilobites were sea animals with hard shells and many legs. They lived for more than 250 million years and died out before the first dinosaurs." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. We found a fern print, a clam shell, a shark tooth, and an insect in amber. None of them are dinosaurs, but they are all fossils." },
      { id: "B", text: "Nova, because dinosaurs are too big to be fossils." },
      { id: "C", text: "Kai. Only dinosaurs lived long ago." },
      { id: "D", text: "Kai. Dinosaur bones are the only things that can turn to stone." },
    ],
    writtenPrompt: "Tell Kai in your own words why fossils are not only dinosaur bones.",
    debateHints: {
      wrongWho: "Think about the fern print and the clam shell. Are they dinosaurs? Are they fossils?",
      wrongReason: "Right person, check the reason. What fossils did we find that were not dinosaurs?",
      right: "Nova is right. Fossils come from plants and animals of every kind, plus the marks they left.",
    },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The dry Texas mystery", machine: "Earth Rock Vault", icon: "water", speaker: "vega",
    line: "A rock sample came from dry land in Texas, far from any ocean. It's full of fossils.",
    question: "Which fossils are clues that this dry land was once under the sea? Pick every one.",
    items: [
      { id: "shark", text: "Shark tooth" },
      { id: "coral", text: "Coral" },
      { id: "ammonite", text: "Ammonite (a coiled sea shell)" },
      { id: "clam", text: "Clam shell" },
      { id: "mammoth", text: "Mammoth tooth" },
      { id: "pinecone", text: "Pine cone" },
    ],
    hint: "Which of these living things can only live in the ocean?",
    meter: { supplies: 1, label: "Fossils cataloged +1", story: "The Texas sample tells its story" },
    discovery: { id: "texassea", name: "A sea over Texas", who: "Nova", fact: "Long ago, a shallow sea covered much of Texas. That's why fossils of sea animals, like coiled ammonite shells, are found across the state today." },
    answer: { kind: "multi", correct: ["shark", "coral", "ammonite", "clam"] },
    rightFeedback: "Sharks, coral, ammonites, and clams live in the sea. Their fossils show an ocean covered this land long ago.",
    wrong: [
      { pick: "mammoth", hint: "Mammoths were big hairy elephants that walked on land. Could they live in the sea?" },
      { pick: "pinecone", hint: "Pine trees grow on land. Is a pine cone a clue for an ocean?" },
      { missing: true, hint: "There are four sea fossils. Think about which animals need salt water to live." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The layer cake", machine: "Core Scanner", icon: "quake", speaker: "vega",
    line: "Surprise, the scanner beeped! A new core from Earth has four layers, and each one holds different fossils. Each layer tells us what the land was like when it formed.",
    question: "Part 1: Which layer is the oldest? Part 2: What was this place like when Layer 4 formed? Part 3: Put the places in order from oldest to youngest. Part 4: What does the core show?",
    data: {
      title: "Earth rock core (read from top to bottom)",
      columns: ["Layer", "Where it is", "Fossils found"],
      rows: [
        ["1", "Top", "Mammoth tooth, grass seeds"],
        ["2", "Upper middle", "Fern leaves, tree trunks"],
        ["3", "Lower middle", "Clam shells, sand ripples"],
        ["4", "Bottom", "Coral, fish bones"],
      ],
    },
    parts: [
      { type: "number", prompt: "Which layer number is the oldest?", unit: "layer" },
      { type: "choice", prompt: "What was this place like when Layer 4 formed?", choices: [
        { id: "a", text: "An ocean" },
        { id: "b", text: "A dry grassland" },
        { id: "c", text: "A snowy mountain" },
        { id: "d", text: "A desert" },
      ] },
      { type: "order", prompt: "Put the places in order from oldest to youngest.", items: [
        { id: "grass", text: "Grassland with mammoths" },
        { id: "sea", text: "Warm ocean with coral" },
        { id: "forest", text: "Wet forest with ferns" },
        { id: "shore", text: "Sandy shore with clams" },
      ] },
      { type: "choice", prompt: "What does the core show?", choices: [
        { id: "a", text: "This place changed a lot over a very long time." },
        { id: "b", text: "This place has always been the same." },
        { id: "c", text: "Mammoths lived in the ocean." },
        { id: "d", text: "The top layer is the oldest." },
      ] },
    ],
    hint: "Start at the bottom. Each fossil is a clue about where that living thing lived.",
    meter: { heat: 10, label: "Fossil hall +10%", story: "The layer cake is decoded" },
    discovery: { id: "waco", name: "A mammoth herd in Texas", who: "Kai", fact: "At Waco Mammoth National Monument in Texas, scientists dug up fossils of a whole herd of Columbian mammoths from the Ice Age." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 4 },
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["sea", "shore", "forest", "grass"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Ocean, then shore, then forest, then grassland. The fossils show this place changed a lot over time!",
    wrong: [
      { step: 1, value: 1, hint: "Layer 1 is on top. New layers settle on top of old ones. Which layer is at the bottom?" },
      { step: 1, value: 2, hint: "Layer 2 is near the top. Which layer settled first, at the very bottom?" },
      { step: 1, value: 3, hint: "Layer 3 has another layer under it. Which layer is at the very bottom?" },
      { step: 2, choice: "b", hint: "Grass seeds are in Layer 1, at the top. What fossils are in Layer 4?" },
      { step: 2, choice: "c", hint: "Coral and fish need water. Could they live on a snowy mountain?" },
      { step: 2, choice: "d", hint: "Coral and fish need water. Could they live in a desert?" },
      { step: 3, position: 0, hint: "The oldest layer is at the bottom. What fossils are in Layer 4?" },
      { step: 3, position: 1, hint: "Look at Layer 3, just above the bottom. Clams and sand ripples show what kind of place?" },
      { step: 3, position: 2, hint: "Layer 2 has ferns and tree trunks. It comes before the top layer." },
      { step: 4, choice: "b", hint: "Each layer has very different fossils. Did the place stay the same?" },
      { step: 4, choice: "c", hint: "The mammoth tooth is with grass seeds. Mammoths walked on land." },
      { step: 4, choice: "d", hint: "New layers settle on top of old ones. Is the top layer old or young?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Ferns in the ice", machine: "Telescope Link", icon: "static", speaker: "nova",
    line: "Time to build our Fossil Hall! First exhibit: Earth scientists found fossil ferns and tree leaves in Antarctica. Today it is the coldest, iciest land on Earth.",
    question: "What do the fossil plants tell us about Antarctica long ago?",
    hint: "Ferns and trees need warmth and water to grow. Can they grow in thick ice?",
    meter: { heat: 10, label: "Fossil hall +10%", story: "The Antarctica exhibit is up" },
    discovery: { id: "antarctica", name: "Forests in Antarctica", who: "Nova", fact: "Scientists have found fossil leaves and tree trunks in Antarctica. Millions of years ago, Antarctica was much warmer and had forests." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Long ago, Antarctica was warmer and wetter, so plants could grow there." },
      { id: "b", text: "Ferns grow best in ice and snow." },
      { id: "c", text: "Antarctica has always been covered in ice." },
      { id: "d", text: "The wind blew the fossils there from far away." },
    ],
    rightFeedback: "Plants that need warmth grew there, so Antarctica's environment was very different long ago.",
    wrong: [
      { choice: "b", hint: "Ferns grow in warm, shady, wet places. Could they grow in ice?" },
      { choice: "c", hint: "Ferns and trees can't grow in thick ice. So was it always icy?" },
      { choice: "d", hint: "The fossils are inside layers of rock, with tree trunks too. Could wind carry whole trees inside rock?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's upside-down sign", machine: "Exhibit Wall", icon: "log", speaker: "kai",
    line: "I made the sign for the rock-layer exhibit! I wrote: \"The top layer is the oldest, because it's the first one we see.\"",
    question: "Part 1: What went wrong with Kai's sign? Part 2: Fix it. Put the layers in order from OLDEST to YOUNGEST.",
    data: {
      title: "Exhibit rock layers (top to bottom)",
      columns: ["Layer", "Where it is", "Fossil found"],
      rows: [
        ["A", "Top", "Mammoth tooth"],
        ["B", "Middle", "Dinosaur footprint"],
        ["C", "Bottom", "Trilobite"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's sign?", choices: [
        { id: "a", text: "He mixed it up. New layers settle on top, so the bottom layer is the oldest." },
        { id: "b", text: "He spelled a word wrong. The top layer really is the oldest." },
        { id: "c", text: "All the layers formed on the same day, so none is older." },
        { id: "d", text: "The middle layer is always the oldest." },
      ] },
      { type: "order", prompt: "Put the layers in order from oldest to youngest.", items: [
        { id: "A", text: "Layer A: mammoth tooth" },
        { id: "B", text: "Layer B: dinosaur footprint" },
        { id: "C", text: "Layer C: trilobite" },
      ] },
    ],
    hint: "Think about stacking pancakes. Which pancake went on the plate first?",
    meter: { supplies: 1, label: "Fossils cataloged +1", story: "Kai's sign is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["C", "B", "A"] },
    ] },
    rightFeedback: "Bottom is oldest: trilobite, then dinosaur footprint, then mammoth tooth. Kai's new sign is right!",
    wrong: [
      { step: 1, choice: "b", hint: "Spelling isn't the problem. Which layer settled first, the top or the bottom?" },
      { step: 1, choice: "c", hint: "Layers pile up slowly over a very long time. Which one came first?" },
      { step: 1, choice: "d", hint: "The middle layer has a layer under it. Which layer is under all the others?" },
      { step: 2, position: 0, hint: "Start with the oldest layer. It is at the bottom." },
      { step: 2, position: 1, hint: "After the bottom layer, which layer settled next?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Cave kids and dinosaurs?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "For the exhibit, let\'s show people riding dinosaurs. People and dinosaurs lived at the same time!"',
    nova: 'Nova: "The fossils say no. Dinosaur fossils are in much older, deeper layers than any fossils of people."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Remember: deeper layers are older. Where are dinosaur fossils found compared with fossils of people?",
    meter: { heat: 5, label: "Fossil hall +5%", story: "The exhibit shows the real timeline" },
    discovery: { id: "timeline", name: "Dinosaurs and people", who: "Nova", fact: "The last big dinosaurs died out about 66 million years ago. The first people like us appeared only about 300,000 years ago." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Dinosaur fossils are always in older, deeper layers than fossils of people. Dinosaurs died out millions of years before people lived." },
      { id: "B", text: "Nova, because people are smaller than dinosaurs." },
      { id: "C", text: "Kai. Movies show people with dinosaurs, so it must be true." },
      { id: "D", text: "Kai. All fossils are the same age." },
    ],
    writtenPrompt: "Tell Kai in your own words why people never rode dinosaurs.",
    debateHints: {
      wrongWho: "Think about the rock layers. Are dinosaur fossils ever found in the same layers as fossils of people?",
      wrongReason: "Right person, check the reason. What do the rock layers show?",
      right: "Nova is right. The rock layers show dinosaurs lived millions of years before people.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Water or land?", machine: "Exhibit Wall", icon: "cells", speaker: "vega",
    line: "The Fossil Hall needs two display cases. One for living things that lived in water, and one for living things that lived on land.",
    question: "Sort each fossil: did this living thing live in water or on land?",
    hint: "Think about where this kind of plant or animal lives, or needed to live.",
    meter: { heat: 5, label: "Fossil hall +5%", story: "The display cases are full" },
    answer: { kind: "sort", bins: { w1: "water", w2: "land", w3: "water", w4: "land", w5: "water", w6: "land" } },
    rightFeedback: "Ammonites, sharks, and coral lived in the sea. Ferns, mammoths, and the dinosaur that left the track lived on land.",
    sort: {
      bins: [{ id: "water", label: "Lived in water" }, { id: "land", label: "Lived on land" }],
      items: [
        { id: "w1", label: "Ammonite shell" },
        { id: "w2", label: "Fern leaf" },
        { id: "w3", label: "Shark tooth" },
        { id: "w4", label: "Mammoth tooth" },
        { id: "w5", label: "Coral" },
        { id: "w6", label: "Three-toed dinosaur track" },
      ],
    },
    wrong: [
      { item: "w1", hint: "Ammonites were coiled shellfish, like the Texas sea fossils. Where did they live?" },
      { item: "w5", hint: "Coral grows under the sea. Does it live on land?" },
      { item: "w6", hint: "The dinosaur walked across mud and left a track. Did it swim or walk?" },
      { item: "w2", hint: "Ferns are plants that grow on land, in shady, wet forests." },
      { item: "w3", hint: "Sharks swim in the ocean." },
      { item: "w4", hint: "Mammoths were like big hairy elephants that walked on land." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The last crate", machine: "Earth Rock Vault", icon: "relay", speaker: "vega",
    line: "This is it! One last core arrived from a hill in Texas, just in time for the Fossil Hall opening. Nova needs your help to write the big exhibit card.",
    question: "Part 1: Which layer is the oldest? Part 2: What was this place like when Layer 3 formed? Part 3: How did this place change over time? Part 4: Write 2–3 sentences for the exhibit card. Use the fossils as evidence.",
    data: {
      title: "Texas hill core (read from top to bottom)",
      columns: ["Layer", "Where it is", "Fossils found"],
      rows: [
        ["1", "Top", "No fossils, just soil"],
        ["2", "Middle", "Dinosaur footprints in old mud"],
        ["3", "Bottom", "Clam shells and coral"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which layer is the oldest?", choices: [
        { id: "a", text: "Layer 3, at the bottom" },
        { id: "b", text: "Layer 1, at the top" },
        { id: "c", text: "Layer 2, in the middle" },
      ] },
      { type: "choice", prompt: "What was this place like when Layer 3 formed?", choices: [
        { id: "a", text: "A shallow sea" },
        { id: "b", text: "A dry desert" },
        { id: "c", text: "An icy land" },
        { id: "d", text: "A pine forest" },
      ] },
      { type: "choice", prompt: "How did this place change over time?", choices: [
        { id: "a", text: "It was a sea, then muddy ground where dinosaurs walked, then dry land." },
        { id: "b", text: "It was dry land, then it turned into a sea." },
        { id: "c", text: "It never changed." },
        { id: "d", text: "Dinosaurs lived in the sea with the coral." },
      ] },
      { type: "write", prompt: "Write the exhibit card. What do the fossils tell us about this place long ago?", minWords: 15 },
    ],
    rubric: ["Says the bottom layer is the oldest", "Uses a fossil as evidence (clams, coral, or footprints)", "Says the place changed from a sea to land over a long time"],
    hint: "Read the core from the bottom up. Each fossil is a clue about the place.",
    meter: { heat: 10, label: "Fossil hall +10%", story: "The Fossil Hall opens" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 15 },
    ] },
    rightFeedback: "The Fossil Hall is open, and your exhibit card tells the story of the rocks! Your teacher will read your card.",
    wrong: [
      { step: 1, choice: "b", hint: "Layer 1 is on top. New layers settle on top of old ones. Is the top old or young?" },
      { step: 1, choice: "c", hint: "Layer 2 has a layer under it. Which layer is at the very bottom?" },
      { step: 2, choice: "b", hint: "Clams and coral need water to live. Could they live in a desert?" },
      { step: 2, choice: "c", hint: "Coral grows in warm water. Could it grow in ice?" },
      { step: 2, choice: "d", hint: "Clams and coral are sea animals. Do they live in a forest?" },
      { step: 3, choice: "b", hint: "Read from the bottom up. The sea fossils are at the bottom, so the sea came first." },
      { step: 3, choice: "c", hint: "Each layer has different fossils. Did the place stay the same?" },
      { step: 3, choice: "d", hint: "The footprints and the coral are in different layers. Did they live at the same time?" },
    ],
  },
};

export default {
  id: "SCI.3.12D-XP",
  standard: "SCI.3.12D-XP",
  engine: "expedition_station",
  title: "The Fossil Dig",
  planet: "Cindara",
  outpost: "Lava Ridge Lab · Earth sample season",
  grade: 3,
  subject: "Science",
  teks: "3.12D",
  supportingTeks: ["3.1E", "3.2B", "3.2C", "3.3A", "3.3C", "3.5A", "3.5B", "3.5G"],
  skillsChip: "3.12D · Fossils are clues to long ago",
  iCan: "I can explain how fossils show what plants and animals lived long ago and what the land was like, such as sea fossils found on dry land.",
  blurb: "Cindara's lava rock has no fossils, so Earth sends rock samples to the crew. They study real Earth fossils to find out what lived long ago and how places changed.",
  mission: "Study Earth fossils and rock layers, and build a Fossil Hall that tells the story of long ago.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.12 · CINDARA LAVA RIDGE LAB",
  playableActs: [1, 2, 3],
  earthTrue: "Cindara and the crew are invented. Every fossil, place, and fact in this quest is real Earth science.",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Fossil hall built", heatUnit: "%", supplies: "Fossils cataloged", suppliesUnit: "fossils" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. The rock on Cindara is cooled lava, and it holds no fossils.",
    "So Earth is sending us crates of rock with real fossils inside. We're going to build a Fossil Hall at the lab.",
    "Every fossil is a clue about life long ago. Look closely and follow the evidence. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Open the crate", "Act 2 · Clues to long ago", "Act 3 · Build the Fossil Hall"],
    completes: [
      "You learned how fossils form and read real dinosaur tracks, {firstName}!",
      "You spotted the fakes and decoded the layer cake, {firstName}!",
      "The Fossil Hall is open, and it tells the true story of long ago, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Cindara: Kai thinks every fossil is a dinosaur, and a mountain is full of seashells. Act 2 is open now, or come back to it next time.",
      "Next on Cindara: it's time to build the Fossil Hall, and Kai's exhibit sign is upside down. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Fossils don't just tell us what lived long ago. They tell us what the land was like.",
      "Let's read the clues.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our fossils are cataloged. Time to build the Fossil Hall.",
      "Every exhibit has to match the evidence.",
    ],
  }),
  tasks,
};
