// Expedition Station — The Freight Split (MA.5.3C-XP)
// Grade 5 · Math · Cindara. Main standard 5.3C (quotients of up to a
// four-digit dividend by a two-digit divisor, using strategies and the
// standard algorithm); also practices 5.3A (estimate to find solutions, here
// with compatible numbers) and 5.3B (multiply a three-digit number by a
// two-digit number, here to check division). Dividends up to 9,999, divisors
// 11–99. Answers are whole numbers or choices. Remainders are interpreted in
// context: round up, drop it, or the answer IS the remainder.
import { CREW, acts } from "./_shared.js";

const LOADS = [
  { label: "Freighter A", value: 1400 },
  { label: "Freighter B", value: 1000 },
  { label: "Freighter C", value: 1800 },
  { label: "Freighter D", value: 1200 },
];

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Ballpark the big pile", machine: "Estimate Scope", icon: "scan", speaker: "vega",
    line: "The first shipment is 1,512 lava rocks. Each freighter carries 24 rocks. Before we load, let's get a quick ballpark with compatible numbers.",
    question: "Part 1: Which compatible numbers are best for estimating 1,512 ÷ 24? Part 2: What is your estimate?",
    parts: [
      { type: "choice", prompt: "Pick the best compatible numbers for 1,512 ÷ 24.", choices: [
        { id: "a", text: "1,500 ÷ 25" },
        { id: "b", text: "1,000 ÷ 24" },
        { id: "c", text: "2,000 ÷ 20" },
        { id: "d", text: "1,512 ÷ 10" },
      ] },
      { type: "number", prompt: "Use your compatible numbers. About how many freighters will we need?", unit: "freighters" },
    ],
    hint: "Compatible numbers are close to the real numbers AND easy to divide. 1,512 is close to 1,500. 24 is close to 25. How many 25s are in 100? In 1,500?",
    meter: { heat: 5, label: "Freight moved +5%", story: "The first pile is sized up" },
    discovery: { id: "maunaloa", name: "Mauna Loa", who: "Nova", fact: "Mauna Loa in Hawaii is the largest active volcano on Earth. It covers about half of the Big Island of Hawaii." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 60 }] },
    rightFeedback: "1,512 is close to 1,500 and 24 is close to 25. There are 4 twenty-fives in 100, so 1,500 ÷ 25 = 60. About 60 freighters!",
    wrong: [
      { step: 1, choice: "b", hint: "1,000 is far from 1,512. Pick numbers that stay close to the real ones." },
      { step: 1, choice: "c", hint: "2,000 is far from 1,512. Pick numbers that are close AND easy to divide." },
      { step: 1, choice: "d", hint: "10 is far from 24. Change both numbers just a little so they divide easily." },
      { step: 2, value: 6, hint: "1,500 ÷ 25 is bigger than that. There are 4 twenty-fives in 100, so 15 hundreds have 15 × 4 twenty-fives." },
      { step: 2, value: 600, hint: "Too big! Check: 600 × 25 is 15,000, not 1,500." },
      { step: 2, value: 75, hint: "1,500 ÷ 20 = 75, but we used 25 as our compatible divisor. Try 1,500 ÷ 25." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The exact count", machine: "Division Deck", icon: "cells", speaker: "kai",
    line: "Our estimate said about 60 freighters. Now let's find the exact number. 1,512 rocks, 24 rocks in each freighter.",
    question: "What is 1,512 ÷ 24?",
    unit: "freighters",
    hint: "Use the standard algorithm. 24 goes into 151 how many times? 24 × 6 = 144. Subtract, bring down the 2, and divide again.",
    meter: { supplies: 1, label: "Freighters loaded +1", story: "The first shipment fits exactly" },
    discovery: { id: "obelus", name: "The division sign", who: "Kai", fact: "The ÷ sign is called an obelus. People have used it to mean divide for more than 350 years." },
    answer: { kind: "number", value: 63 },
    rightFeedback: "151 ÷ 24 is 6 with 7 left. Bring down the 2 to make 72. 72 ÷ 24 = 3. That's 63 freighters, close to our estimate of 60!",
    wrong: [
      { value: 60, hint: "60 was our estimate. Now find the exact answer with the standard algorithm." },
      { value: 62, hint: "Check the last step. After 151 − 144 = 7, bring down the 2 to make 72. How many 24s are in 72?" },
      { value: 603, hint: "There is no extra 0 here. After the 6, bring down the 2 to make 72, and 24 goes in 3 times." },
      { value: 36, hint: "You have the right digits in the wrong order. The first digit you found goes in the tens place." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Multiply to check", machine: "Check Crane", icon: "dial", speaker: "nova",
    line: "Kai loaded the next shipment. He says 3,276 rocks ÷ 42 rocks per freighter = 78 freighters. We can check division with multiplication.",
    question: "Part 1: Multiply 78 × 42. Part 2: Is Kai's quotient right?",
    parts: [
      { type: "number", prompt: "What is 78 × 42?", unit: "rocks" },
      { type: "choice", prompt: "Is 3,276 ÷ 42 = 78 correct?", choices: [
        { id: "a", text: "Yes. 78 × 42 = 3,276, the same as the dividend." },
        { id: "b", text: "No. 78 × 42 should equal 42, the divisor." },
        { id: "c", text: "No. You can't check division with multiplication." },
        { id: "d", text: "Yes, because 78 is less than 3,276." },
      ] },
    ],
    hint: "Multiply 78 × 2, then 78 × 40. Don't forget the 0 when you multiply by the 4 tens. Then add the two products.",
    meter: { heat: 5, label: "Freight moved +5%", story: "Kai's load checks out" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 3276 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "78 × 2 = 156 and 78 × 40 = 3,120. 156 + 3,120 = 3,276. The product matches the dividend, so Kai is right!",
    wrong: [
      { step: 1, value: 468, hint: "When you multiply by the 4 in 42, it's really 40. 78 × 40 = 3,120, not 312." },
      { step: 1, value: 3176, hint: "Close! Add again carefully: 3,120 + 156." },
      { step: 1, value: 120, hint: "78 + 42 = 120. We need to multiply, not add." },
      { step: 2, choice: "b", hint: "Quotient × divisor should give back the dividend, the number we started with." },
      { step: 2, choice: "c", hint: "Multiplication undoes division. That's why it's a great way to check!" },
      { step: 2, choice: "d", hint: "Being smaller doesn't prove it. Check if 78 × 42 gives back 3,276." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Chunk by chunk", machine: "Partial Quotient Press", icon: "grid", speaker: "kai",
    line: "The obsidian shipment has 1,872 rocks, packed 16 to a crate. I like taking away big chunks of 16 at a time. That's called partial quotients.",
    question: "Part 1: Put the partial-quotient steps in order. Part 2: What is 1,872 ÷ 16?",
    parts: [
      { type: "order", prompt: "Put the steps in order, first to last.", items: [
        { id: "ten", text: "Take away 10 groups of 16: 272 − 160 = 112" },
        { id: "add", text: "Add up the groups: 100 + 10 + 7" },
        { id: "hundred", text: "Take away 100 groups of 16: 1,872 − 1,600 = 272" },
        { id: "seven", text: "Take away 7 groups of 16: 112 − 112 = 0" },
      ] },
      { type: "number", prompt: "What is 1,872 ÷ 16?", unit: "crates" },
    ],
    hint: "Start with the biggest chunk you can take away: 100 groups of 16 is 1,600. Keep taking away smaller chunks until nothing is left. Then add the groups.",
    meter: { supplies: 1, label: "Freighters loaded +1", story: "The obsidian is crated" },
    discovery: { id: "surtsey", name: "Surtsey", who: "Nova", fact: "In 1963, an undersea volcano near Iceland built a brand-new island called Surtsey. Scientists have watched plants and birds settle there ever since." },
    answer: { kind: "parts", parts: [{ kind: "order", correct: ["hundred", "ten", "seven", "add"] }, { kind: "number", value: 117 }] },
    rightFeedback: "100 groups, then 10 groups, then 7 groups, and nothing is left. 100 + 10 + 7 = 117 crates!",
    wrong: [
      { step: 1, position: 0, hint: "Start with the biggest chunk. 100 groups of 16 is 1,600." },
      { step: 1, position: 1, hint: "After 1,872 − 1,600, you have 272 left. Which step starts with 272?" },
      { step: 1, position: 2, hint: "After taking away 160, you have 112 left. Which step starts with 112?" },
      { step: 2, value: 17, hint: "You forgot the 100 groups from the first step. Add 100 + 10 + 7." },
      { step: 2, value: 107, hint: "Don't forget the 10 groups from the second step. Add 100 + 10 + 7." },
      { step: 2, value: 1117, hint: "Add the groups: 100 + 10 + 7. Is that more than a thousand?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Lava on the rails", machine: "Rail Yard", icon: "quake", speaker: "vega",
    line: "Surprise! A slow lava flow is creeping toward the rail yard. We must move 4,875 basalt rocks into rail carts right now. Each cart holds 38 rocks.",
    question: "Part 1: Pick the best estimate. Part 2: Find the whole-number part of 4,875 ÷ 38. Part 3: What is the remainder? Part 4: Check it. What is 128 × 38?",
    parts: [
      { type: "choice", prompt: "Which is the best estimate for 4,875 ÷ 38?", choices: [
        { id: "a", text: "4,800 ÷ 40 = 120" },
        { id: "b", text: "4,000 ÷ 40 = 100" },
        { id: "c", text: "5,000 ÷ 50 = 100" },
        { id: "d", text: "4,800 ÷ 4 = 1,200" },
      ] },
      { type: "number", prompt: "4,875 ÷ 38. How many full carts? Type the whole-number part of the quotient.", unit: "carts" },
      { type: "number", prompt: "How many rocks are left over? Type the remainder.", unit: "rocks" },
      { type: "number", prompt: "Check: what is 128 × 38?", unit: "rocks" },
    ],
    hint: "48 hundreds ÷ 4 tens is about 120. Then divide: 38 goes into 48 once, into 107 two times, into 315 eight times. To check, multiply the quotient by 38 and add the remainder.",
    meter: { heat: 10, label: "Freight moved +10%", story: "The basalt is saved from the lava" },
    discovery: { id: "ash", name: "Volcanic ash", who: "Kai", fact: "Volcanic ash is not soft like ash from a campfire. It is made of tiny, sharp bits of rock and glass, so it can scratch windows and clog engines." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 128 }, { kind: "number", value: 11 }, { kind: "number", value: 4864 }] },
    rightFeedback: "4,875 ÷ 38 = 128 R 11, close to our estimate of 120. Check: 128 × 38 = 4,864, and 4,864 + 11 = 4,875. Every rock is off the rails!",
    wrong: [
      { step: 1, choice: "b", hint: "4,000 is pretty far from 4,875. Try compatible numbers that stay closer, like 4,800." },
      { step: 1, choice: "c", hint: "50 is far from 38. Pick a divisor closer to 38 that is still easy." },
      { step: 1, choice: "d", hint: "38 is close to 40, not 4. Dividing by 4 makes the answer 10 times too big." },
      { step: 2, value: 12, hint: "Too small. After 38 goes into 48 and 107, there's still a 5 to bring down. That gives a third digit." },
      { step: 2, value: 129, hint: "Check the last step: 38 × 9 = 342, which is more than 315. Try 8." },
      { step: 2, value: 127, hint: "Check the last step: 315 − 38 × 7 leaves 49, which is more than 38. One more cart fits!" },
      { step: 3, value: 49, hint: "A remainder can't be 38 or more, or another cart would fit. Recheck the last digit of the quotient." },
      { step: 3, value: 0, hint: "Check: 128 × 38 is 4,864. How far is that from 4,875?" },
      { step: 4, value: 1408, hint: "When you multiply by the 3 in 38, it's really 30. 128 × 30 = 3,840, not 384." },
      { step: 4, value: 4875, hint: "That's the dividend. 128 × 38 is a little less, because of the remainder. Multiply to find it." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "No crate left behind", machine: "Freighter Dock", icon: "relay", speaker: "nova",
    line: "The ash-glass order is 940 crates. Each freighter carries 36 crates. Every single crate has to leave today.",
    question: "Part 1: What is the whole-number part of 940 ÷ 36? Part 2: What is the remainder? Part 3: How many freighters do we need to carry all the crates?",
    parts: [
      { type: "number", prompt: "940 ÷ 36. Type the whole-number part of the quotient.", unit: "freighters" },
      { type: "number", prompt: "What is the remainder?", unit: "crates" },
      { type: "number", prompt: "How many freighters do we need so EVERY crate leaves?", unit: "freighters" },
    ],
    hint: "36 × 26 = 936. The leftover crates still need a ride. One more freighter can carry them.",
    meter: { supplies: 2, label: "Freighters loaded +2", story: "Every ash-glass crate is shipped" },
    discovery: { id: "containers", name: "Shipping containers", who: "Kai", fact: "Most shipping containers on cargo ships are about 6 meters (20 feet) or 12 meters (40 feet) long, so they stack neatly like building blocks." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 26 }, { kind: "number", value: 4 }, { kind: "number", value: 27 }] },
    rightFeedback: "940 ÷ 36 = 26 R 4. Those 4 leftover crates need a freighter too, so we round up to 27 freighters.",
    wrong: [
      { step: 1, value: 25, hint: "Check: 36 × 25 = 900, which leaves 40. That's enough for one more freighter." },
      { step: 1, value: 27, hint: "36 × 27 = 972, which is more than 940. How many FULL freighters fit?" },
      { step: 2, value: 40, hint: "40 is more than 36, so another freighter would fit. Recheck the quotient." },
      { step: 3, value: 26, hint: "26 freighters leaves 4 crates on the dock! Every crate has to go." },
      { step: 3, value: 30, hint: "The 4 leftover crates need just one more freighter, not 4 more." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Full crates only", machine: "Crate Packer", icon: "tank", speaker: "kai",
    line: "The traders on the next moon only buy FULL crates of fire opals. We have 1,000 opals, and a full crate holds 24.",
    question: "Part 1: What is the whole-number part of 1,000 ÷ 24? Part 2: What is the remainder? Part 3: How many full crates can we sell?",
    parts: [
      { type: "number", prompt: "1,000 ÷ 24. Type the whole-number part of the quotient.", unit: "crates" },
      { type: "number", prompt: "What is the remainder?", unit: "opals" },
      { type: "number", prompt: "How many FULL crates can we sell?", unit: "crates" },
    ],
    hint: "24 × 40 = 960. How many more 24s fit in the 40 that is left? The leftover opals can't fill a crate.",
    meter: { heat: 5, label: "Freight moved +5%", story: "The opal crates are packed" },
    discovery: { id: "kilauea", name: "Kīlauea", who: "Nova", fact: "Kīlauea in Hawaii erupted almost nonstop from 1983 to 2018. That's 35 years of flowing lava!" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 41 }, { kind: "number", value: 16 }, { kind: "number", value: 41 }] },
    rightFeedback: "1,000 ÷ 24 = 41 R 16. The 16 leftover opals can't fill a crate, so we drop the remainder. We can sell 41 full crates.",
    wrong: [
      { step: 1, value: 40, hint: "24 × 40 = 960 leaves 40 opals. That's enough for one more crate." },
      { step: 1, value: 42, hint: "24 × 42 = 1,008. That's more than 1,000." },
      { step: 2, value: 40, hint: "40 is more than 24, so another crate fits. Recheck the quotient." },
      { step: 3, value: 42, hint: "A 42nd crate would only have 16 opals. The traders only buy FULL crates." },
      { step: 3, value: 16, hint: "16 is the number of leftover opals. How many full crates are there?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The museum's share", machine: "Share Splitter", icon: "split", speaker: "vega",
    line: "We found 2,500 glowing ember stones. We'll share them equally among 32 freighters. Any stones left over go to the Cindara rock museum.",
    question: "Part 1: How many ember stones does each freighter get? Part 2: How many stones go to the museum?",
    parts: [
      { type: "number", prompt: "2,500 shared equally among 32 freighters. How many stones does each freighter get?", unit: "stones" },
      { type: "number", prompt: "How many leftover stones go to the museum?", unit: "stones" },
    ],
    hint: "32 goes into 250 seven times (32 × 7 = 224). Subtract, bring down the 0, and divide again. The museum gets what is left.",
    meter: { supplies: 1, label: "Freighters loaded +1", story: "The museum gets a gift" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 78 }, { kind: "number", value: 4 }] },
    rightFeedback: "2,500 ÷ 32 = 78 R 4. Each freighter gets 78 stones, and this time the answer to the question is the remainder: 4 stones go to the museum.",
    wrong: [
      { step: 1, value: 79, hint: "32 × 79 = 2,528. That's more stones than we have." },
      { step: 1, value: 77, hint: "32 × 77 = 2,464 leaves 36 stones. That's enough to give each freighter one more." },
      { step: 2, value: 78, hint: "78 is how many each freighter gets. The museum gets the leftovers." },
      { step: 2, value: 36, hint: "36 is more than 32, so every freighter could get one more. Recheck your quotient." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The giant leftover", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "I split 500 rocks into freighters of 24. I got 19 R 44. Remainders can be any size, even bigger than the divisor!"',
    nova: 'Nova: "Not so fast, Kai. If 44 rocks are left, you can fill another freighter of 24. The remainder has to be smaller than the divisor."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    visual: { type: "bars", title: "Kai's split of 500 rocks", categories: [
      { label: "Each full freighter", value: 24 },
      { label: "Kai's leftover", value: 44 },
    ], step: 4, max: 48, axis: "Rocks" },
    hint: "Look at the leftover bar. Is it big enough to fill one more freighter of 24?",
    meter: { heat: 5, label: "Freight moved +5%", story: "Kai redoes his split" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. If the remainder is 24 or more, another group of 24 fits. 500 ÷ 24 is really 20 R 20." },
      { id: "B", text: "Nova, because a remainder always has to be 0." },
      { id: "C", text: "Kai. The remainder can be any number you like." },
      { id: "D", text: "Kai. A bigger remainder means you divided more carefully." },
    ],
    writtenPrompt: "Tell Kai in your own words why a remainder must be smaller than the divisor.",
    debateHints: {
      wrongWho: "Kai has 44 rocks left. Could those 44 rocks fill one more freighter that holds 24?",
      wrongReason: "Right person, check the reason. Remainders don't have to be 0. They just have to be smaller than the divisor.",
      right: "Nova is right. 44 rocks is enough for another freighter, so 500 ÷ 24 = 20 R 20. A remainder is always less than the divisor.",
    },
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The ash storm manifest", machine: "Manifest Board", icon: "static", speaker: "vega",
    line: "Surprise! An ash storm is coming, and the port closes at sundown. Here is tonight's shipment list. Every freighter holds 48 rocks, and every rock must leave before the storm.",
    question: "Part 1: How many freighters for the basalt? Part 2: How many for the obsidian? Part 3: How many for the pumice, so every rock leaves? Part 4: How many freighters in all?",
    data: {
      title: "Tonight's shipments",
      columns: ["Shipment", "Kind of rock", "Rocks"],
      rows: [
        ["1", "Basalt", "2,448"],
        ["2", "Obsidian", "1,152"],
        ["3", "Pumice", "3,000"],
      ],
    },
    parts: [
      { type: "number", prompt: "Basalt: 2,448 ÷ 48. How many freighters?", unit: "freighters" },
      { type: "number", prompt: "Obsidian: 1,152 ÷ 48. How many freighters?", unit: "freighters" },
      { type: "number", prompt: "Pumice: 3,000 ÷ 48. How many freighters do we need so EVERY rock leaves?", unit: "freighters" },
      { type: "number", prompt: "How many freighters do we need in all?", unit: "freighters" },
    ],
    hint: "Divide each shipment by 48. Watch for a remainder: if rocks are left over, they still need a freighter. Then add all three answers.",
    meter: { supplies: 3, label: "Freighters loaded +3", story: "The port clears before the ash storm" },
    discovery: { id: "geothermal", name: "Warm homes from hot rock", who: "Nova", fact: "Iceland uses heat from hot rock deep underground to warm most of its homes. This is called geothermal energy." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 51 }, { kind: "number", value: 24 }, { kind: "number", value: 63 }, { kind: "number", value: 138 }] },
    rightFeedback: "2,448 ÷ 48 = 51 and 1,152 ÷ 48 = 24. 3,000 ÷ 48 = 62 R 24, so pumice needs 63 freighters. 51 + 24 + 63 = 138 freighters beat the storm!",
    wrong: [
      { step: 1, value: 501, hint: "There's no zero in this quotient. 48 goes into 244 five times, and 48 goes into 48 once." },
      { step: 1, value: 50, hint: "48 × 50 = 2,400 leaves 48 rocks. That fills one more freighter." },
      { step: 2, value: 34, hint: "Check: 48 × 34 is more than 1,152. 48 goes into 115 two times, not three." },
      { step: 2, value: 23, hint: "48 × 23 = 1,104 leaves 48 rocks. That fills one more freighter." },
      { step: 3, value: 62, hint: "3,000 ÷ 48 = 62 R 24. Those 24 pumice rocks still need a ride before the storm." },
      { step: 3, value: 24, hint: "24 is the remainder. How many freighters carry ALL the pumice?" },
      { step: 4, value: 137, hint: "Did you use 62 for the pumice? The leftover pumice needs its own freighter." },
      { step: 4, value: 3, hint: "There are 3 shipments, but we need the number of freighters. Add your three answers." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "What do we do with the leftovers?", machine: "Sort Bay", icon: "brief", speaker: "nova",
    line: "Remainders are tricky. Sometimes we round up, sometimes we drop the remainder, and sometimes the remainder IS the answer. The question tells us which.",
    question: "Sort each problem by what you do with the remainder.",
    hint: "Ask: does every item need a spot? Round up. Do we only count full groups? Drop it. Does the question ask what's left over? The answer is the remainder.",
    meter: { heat: 5, label: "Freight moved +5%", story: "The remainder rules are sorted" },
    answer: { kind: "sort", bins: { r1: "up", r2: "drop", r3: "rem", r4: "up", r5: "drop", r6: "rem" } },
    rightFeedback: "Every card is in the right bin! The question tells you what to do with the remainder.",
    sort: {
      bins: [
        { id: "up", label: "Round up" },
        { id: "drop", label: "Drop the remainder" },
        { id: "rem", label: "The answer is the remainder" },
      ],
      items: [
        { id: "r1", label: "1,000 miners ride shuttles that hold 24 each. How many shuttles so everyone gets a ride?" },
        { id: "r2", label: "Pack 500 rocks in boxes of 12. How many FULL boxes can we ship?" },
        { id: "r3", label: "Share 700 crystals equally among 16 labs. How many crystals are left for Nova?" },
        { id: "r4", label: "A freighter holds 45 crates. How many freighters carry all 1,000 crates?" },
        { id: "r5", label: "Kai has 300 bolts. Each robot needs 14 bolts. How many robots can he build?" },
        { id: "r6", label: "Deal 850 cards into 32 equal piles. How many cards are left in Kai's hand?" },
      ],
    },
    wrong: [
      { item: "r1", hint: "Every miner needs a ride, even the leftover ones. That means one more shuttle." },
      { item: "r2", hint: "Only FULL boxes count. The leftover rocks can't fill a box." },
      { item: "r3", hint: "The question asks about the crystals left over. That's the remainder." },
      { item: "r4", hint: "ALL the crates must go, so the leftover crates need one more freighter." },
      { item: "r5", hint: "Kai can't build part of a robot. Only complete robots count." },
      { item: "r6", hint: "The cards left in Kai's hand are the leftovers. That's the remainder." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Read the freighter loads", machine: "Load Graph", icon: "log", speaker: "kai",
    line: "Four freighters just came back from the rock quarry. The graph shows how many rocks each one carried.",
    question: "Part 1: Freighter C's rocks go into 24 equal bins. How many rocks in each bin? Part 2: Freighter A's rocks go into 35 equal bins. How many in each? Part 3: All four loads are stored equally in 45 sheds. How many rocks go in each shed?",
    parts: [
      { type: "number", prompt: "Freighter C's rocks are split into 24 equal bins. How many rocks in each bin?", unit: "rocks",
        visual: { type: "bars", title: "Rocks carried by each freighter", categories: LOADS, step: 200, max: 2000, axis: "Rocks" } },
      { type: "number", prompt: "Freighter A's rocks are split into 35 equal bins. How many rocks in each bin?", unit: "rocks",
        visual: { type: "bars", title: "Rocks carried by each freighter", categories: LOADS, step: 200, max: 2000, axis: "Rocks" } },
      { type: "number", prompt: "Add all four loads. Then share them equally among 45 sheds. How many rocks go in each shed?", unit: "rocks",
        visual: { type: "bars", title: "Rocks carried by each freighter", categories: LOADS, step: 200, max: 2000, axis: "Rocks" } },
    ],
    hint: "Read the top of each bar first. C carried 1,800 and A carried 1,400. For Part 3, add all four bars, then divide by 45.",
    meter: { supplies: 2, label: "Freighters loaded +2", story: "The quarry loads are stored" },
    discovery: { id: "fuji", name: "Mount Fuji", who: "Kai", fact: "Mount Fuji in Japan is a cone-shaped volcano built from many layers of lava and ash. It is Japan's tallest mountain, about 3,776 meters (12,388 feet) high." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 75 }, { kind: "number", value: 40 }, { kind: "number", value: 120 }] },
    rightFeedback: "1,800 ÷ 24 = 75 and 1,400 ÷ 35 = 40. All four loads make 5,400 rocks, and 5,400 ÷ 45 = 120 rocks in each shed.",
    wrong: [
      { step: 1, value: 50, hint: "1,200 ÷ 24 = 50, but that's Freighter D. Freighter C carried 1,800." },
      { step: 1, value: 705, hint: "There's no zero in this quotient. 24 goes into 180 seven times, with 12 left. Bring down the 0 to make 120." },
      { step: 2, value: 4, hint: "Too small! 35 × 4 is only 140. Try 35 × 40." },
      { step: 2, value: 28, hint: "1,000 ÷ 35 isn't a whole number, and that's Freighter B. Freighter A carried 1,400." },
      { step: 3, value: 12, hint: "Too small! 45 × 12 is only 540. You need a 0 in the ones place: 5,400 ÷ 45." },
      { step: 3, value: 1200, hint: "Too big! 45 × 1,200 is way more than 5,400. Check your place values." },
      { step: 3, value: 5400, hint: "5,400 is the total. Now share it equally among 45 sheds." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The missing zero", machine: "Repair", icon: "snap", speaker: "nova",
    line: 'Kai divided 2,448 rocks into freighters of 24: "24 goes into 24 once. Bring down the 4. Then bring down the 8, and 48 ÷ 24 = 2. So it\'s 12 freighters!" Hmm. That seems way too small.',
    question: "Part 1: What went wrong? Part 2: What is the right quotient? Part 3: Check it. What is 102 × 24?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "24 doesn't go into 4, so he needed a 0 in the tens place of the quotient." },
        { id: "b", text: "He should have divided 2,448 by 12 instead." },
        { id: "c", text: "24 goes into 24 two times, not once." },
        { id: "d", text: "Nothing. 12 freighters is right." },
      ] },
      { type: "number", prompt: "What is 2,448 ÷ 24?", unit: "freighters" },
      { type: "number", prompt: "Check: what is 102 × 24?", unit: "rocks" },
    ],
    hint: "Estimate first: 2,400 ÷ 24 = 100. So the answer must be about 100, not 12. When 24 can't go into the 4, write a 0 in the quotient.",
    meter: { heat: 5, label: "Freight moved +5%", story: "Kai finds his missing zero" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 102 }, { kind: "number", value: 2448 }] },
    rightFeedback: "24 ÷ 24 = 1. 24 can't go into 4, so write a 0. Then 48 ÷ 24 = 2. That's 102 freighters, and 102 × 24 = 2,448 proves it!",
    wrong: [
      { step: 1, choice: "b", hint: "The freighters hold 24 rocks, so we divide by 24. Look at what happened when Kai brought down the 4." },
      { step: 1, choice: "c", hint: "24 × 1 = 24, so once is right. Look at the next step, when he brought down the 4." },
      { step: 1, choice: "d", hint: "Check: 12 × 24 = 288, not 2,448. Something is missing!" },
      { step: 2, value: 12, hint: "That's Kai's answer. 12 × 24 is only 288. Where does the 0 go?" },
      { step: 2, value: 120, hint: "Check: 120 × 24 = 2,880, too big. The 0 goes in the tens place, not the ones." },
      { step: 2, value: 1002, hint: "Too big! Estimate: 2,400 ÷ 24 is about 100, not 1,000." },
      { step: 3, value: 288, hint: "Multiply 102 × 24, not 12 × 24. Don't drop the hundreds." },
      { step: 3, value: 2408, hint: "102 × 4 = 408 and 102 × 20 = 2,040. Add them: 408 + 2,040." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The area model bay", machine: "Area Model Bay", icon: "cells", speaker: "vega",
    line: "The magma-glass order is 3,432 pieces for 26 freighters. Nova drew an area model: a big rectangle with 26 down the side, split into sections.",
    question: "Part 1: The first section is 26 × 100. What is its area? Part 2: How much of 3,432 is left? Part 3: The next section is 26 × ? = 780. What is the missing side? Part 4: What is 3,432 ÷ 26?",
    parts: [
      { type: "number", prompt: "First section: 26 × 100 = ?", unit: "pieces" },
      { type: "number", prompt: "3,432 minus that first section leaves how many?", unit: "pieces" },
      { type: "number", prompt: "Second section: 26 × ? = 780. What is the missing side length?" },
      { type: "number", prompt: "The last section is 26 × 2 = 52. Add the side lengths. What is 3,432 ÷ 26?", unit: "pieces per freighter" },
    ],
    hint: "Each section is 26 times a friendly number. 26 × 100 = 2,600. Subtract it from 3,432. Then 26 × 3 = 78, so 26 × 30 = 780. The top side lengths add up to the quotient.",
    meter: { supplies: 1, label: "Freighters loaded +1", story: "The magma glass is split evenly" },
    discovery: { id: "sulfur", name: "Yellow sulfur", who: "Nova", fact: "Bright yellow sulfur crystals can grow around cracks on volcanoes, where hot gases escape from underground." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 2600 }, { kind: "number", value: 832 }, { kind: "number", value: 30 }, { kind: "number", value: 132 }] },
    rightFeedback: "26 × 100 = 2,600, leaving 832. 26 × 30 = 780, leaving 52. 26 × 2 = 52, leaving 0. 100 + 30 + 2 = 132 pieces per freighter!",
    wrong: [
      { step: 1, value: 126, hint: "That's 26 + 100. The area of a section is length times width: 26 × 100." },
      { step: 1, value: 260, hint: "26 × 10 = 260. We need 26 × 100." },
      { step: 2, value: 932, hint: "Subtract carefully: 3,432 − 2,600. Regroup from the thousands." },
      { step: 2, value: 6032, hint: "We take the section away. Subtract 2,600 from 3,432." },
      { step: 3, value: 3, hint: "26 × 3 = 78, not 780. What times 26 makes 780?" },
      { step: 3, value: 300, hint: "26 × 300 = 7,800. That's too big. Try 26 × 30." },
      { step: 4, value: 32, hint: "Don't forget the first section's side of 100. Add 100 + 30 + 2." },
      { step: 4, value: 1302, hint: "Add the side lengths: 100 + 30 + 2. Is that more than a thousand?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The last rumble", machine: "Mega Freighter Dock", icon: "relay", speaker: "vega",
    line: "Surprise! The big volcano is rumbling. Everything in the freight yard must go: 9,216 rocks, into freighters that hold 64 each. Then, just as we finish, a late cart rolls in with 50 more rocks!",
    question: "Part 1: Pick the best estimate. Part 2: What is 9,216 ÷ 64? Part 3: Check it. What is 144 × 64? Part 4: With the 50 late rocks, how many freighters do we need in all?",
    parts: [
      { type: "choice", prompt: "Which is the best estimate for 9,216 ÷ 64?", choices: [
        { id: "a", text: "9,000 ÷ 60 = 150" },
        { id: "b", text: "9,000 ÷ 6 = 1,500" },
        { id: "c", text: "10,000 ÷ 100 = 100" },
        { id: "d", text: "9,216 ÷ 64 is about 9,000" },
      ] },
      { type: "number", prompt: "What is 9,216 ÷ 64?", unit: "freighters" },
      { type: "number", prompt: "Check: what is 144 × 64?", unit: "rocks" },
      { type: "number", prompt: "The late cart adds 50 rocks. Now there are 9,266 rocks. How many freighters do we need so EVERY rock leaves?", unit: "freighters" },
    ],
    hint: "90 hundreds ÷ 6 tens is 150. Divide: 64 goes into 92 once, into 281 four times, into 256 four times. The 50 extra rocks are less than 64, but they still need their own freighter.",
    meter: { heat: 15, label: "Freight moved +15%", story: "The whole freight yard is saved" },
    discovery: { id: "stromboli", name: "The lighthouse volcano", who: "Kai", fact: "The Stromboli volcano in Italy has been erupting in small bursts for thousands of years. Sailors call it the Lighthouse of the Mediterranean." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 144 }, { kind: "number", value: 9216 }, { kind: "number", value: 145 }] },
    rightFeedback: "9,216 ÷ 64 = 144, close to our estimate of 150. 144 × 64 = 9,216 checks out. The 50 late rocks make 9,266 ÷ 64 = 144 R 50, so we round up to 145 freighters. Great work, specialist. The freight yard is clear!",
    wrong: [
      { step: 1, choice: "b", hint: "64 is close to 60, not 6. Dividing by 6 makes the answer 10 times too big." },
      { step: 1, choice: "c", hint: "100 is far from 64. Pick a divisor that stays close, like 60." },
      { step: 1, choice: "d", hint: "Dividing by 64 makes the number much smaller. Try 9,000 ÷ 60." },
      { step: 2, value: 14, hint: "Too small! Estimate said about 150. After 92 and 281, there's still a 6 to bring down." },
      { step: 2, value: 143, hint: "Check the last step: 256 ÷ 64 = 4, not 3." },
      { step: 2, value: 1404, hint: "There's no zero here. Estimate said about 150, not 1,400." },
      { step: 3, value: 1440, hint: "When you multiply by the 6 in 64, it's really 60. 144 × 60 = 8,640, not 864." },
      { step: 3, value: 9116, hint: "Close! Add again carefully: 8,640 + 576." },
      { step: 4, value: 144, hint: "144 freighters are full, but the 50 late rocks would be left behind! They need a ride." },
      { step: 4, value: 194, hint: "The 50 late rocks fit in ONE more freighter. Don't add 50 freighters." },
      { step: 4, value: 50, hint: "50 is the leftover rocks. How many freighters carry everything?" },
    ],
  },
};

export default {
  id: "MA.5.3C-XP",
  standard: "MA.5.3C-XP",
  engine: "expedition_station",
  title: "The Freight Split",
  planet: "Cindara",
  outpost: "Ember Freight Yard · shipping day",
  grade: 5,
  subject: "Math",
  teks: "5.3C",
  supportingTeks: ["5.3A", "5.3B"],
  skillsChip: "5.3C · Divide by two-digit numbers",
  iCan: "I can divide a number up to four digits by a two-digit number, estimate with compatible numbers, check my answer with multiplication, and decide what to do with a remainder.",
  blurb: "A giant shipment of lava rock is piling up at Cindara's freight yard. The crew has to split it into freighters, and every rock has to be counted exactly.",
  mission: "Split the lava-rock shipment into freighters, deal with every remainder, and clear the freight yard before the volcano rumbles.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.3C · CINDARA FREIGHT YARD",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Freight moved", heatUnit: "%", supplies: "Freighters loaded", suppliesUnit: "freighters" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're at the Ember Freight Yard on Cindara, the lava world.",
    "The mines dug up a huge shipment of lava rock. It has to be split evenly into freighters and sent across the planet.",
    "Kai and Nova need a sharp divider. Estimate, divide, and check every load. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Size up the shipment", "Act 2 · Leftover rocks", "Act 3 · Clear the yard"],
    completes: [
      "The first shipments are split and checked, {firstName}!",
      "Every remainder is handled, and the port beat the ash storm, {firstName}!",
      "The freight yard is clear, {firstName}! Every rock made it out before the volcano rumbled.",
    ],
    teasers: [
      "Next on Cindara: some loads don't split evenly. What do we do with the leftover rocks? Act 2 is open now, or come back to it next time.",
      "Next on Cindara: the volcano is waking up, and the whole yard must be cleared. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Not every shipment splits evenly.",
      "Sometimes rocks are left over, and we have to decide what to do with them.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The volcano above the yard is rumbling.",
      "Help the crew split the last loads and clear the freight yard for good.",
    ],
  }),
  tasks,
};
