// Expedition Station — The Garden Plots (MA.4.5D-XP)
// Grade 4 · Math · Lumara. Main standard 4.5D (solve problems about the
// perimeter and area of rectangles with whole-number dimensions); also
// practices 4.5C (use models to find the formulas P = l + w + l + w or
// 2l + 2w, P = 4s for a square, and A = l × w). Grade 4 stretch beyond the
// grade 3 Greenhouse Floor quest: formulas, missing sides from area or
// perimeter, same area with different perimeters, and multi-step fence-cost
// and seed-packet problems.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Walk the fence line", machine: "Fence Tracker", icon: "trail", speaker: "kai",
    line: "Our first new plot is a rectangle, 7 meters long and 4 meters wide. The glowmoss fence goes all the way around the edge.",
    question: "How many meters of fence does the plot need? Find the perimeter.",
    unit: "meters",
    visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 7, perimeter: true, sideLabels: { top: "7 m", left: "4 m" }, title: "Plot 1" },
    hint: "Perimeter is the distance around. Walk every side: 7 + 4 + 7 + 4.",
    meter: { heat: 10, label: "Fence built +10%", story: "Plot 1 is fenced" },
    discovery: { id: "threesisters", name: "The Three Sisters", who: "Nova", fact: "Many Native American farmers planted corn, beans, and squash together. The corn holds up the beans, and the big squash leaves shade the soil." },
    answer: { kind: "number", value: 22 },
    rightFeedback: "7 + 4 + 7 + 4 = 22. Plot 1 needs 22 meters of fence!",
    wrong: [
      { value: 11, hint: "7 + 4 = 11 is only two sides. A rectangle has four sides. Walk all the way around." },
      { value: 28, hint: "7 × 4 = 28 is the area, the squares inside. The fence goes around the edge." },
      { value: 18, hint: "It looks like you counted the edge tiles. Corner tiles touch two sides. Add the side lengths instead: 7 + 4 + 7 + 4." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Double the sides", machine: "Formula Board", icon: "cells", speaker: "nova",
    line: "Plot 2 is 9 meters long and 5 meters wide. A rectangle has two long sides that match and two short sides that match. That gives us a shortcut.",
    question: "Part 1: Which formula finds the perimeter of Plot 2? Part 2: What is the perimeter?",
    parts: [
      { type: "choice", prompt: "Which formula finds the perimeter of a 9 m by 5 m rectangle?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 9, perimeter: true, sideLabels: { top: "9 m", left: "5 m" }, title: "Plot 2" },
        choices: [
          { id: "a", text: "P = 2 × 9 + 2 × 5 (two lengths plus two widths)" },
          { id: "b", text: "P = 9 × 5" },
          { id: "c", text: "P = 9 + 5" },
          { id: "d", text: "P = 2 × 9 + 5" },
        ] },
      { type: "number", prompt: "Use the formula. What is the perimeter of Plot 2?", unit: "meters" },
    ],
    hint: "P = 2l + 2w. Two lengths: 2 × 9. Two widths: 2 × 5. Then add.",
    meter: { heat: 5, label: "Fence built +5%", story: "Plot 2 is fenced" },
    discovery: { id: "beanroots", name: "Bean roots", who: "Kai", fact: "Bean plants have tiny bumps on their roots. Helpful bacteria live in the bumps and add nitrogen, a plant food, to the soil." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 28 }] },
    rightFeedback: "2 × 9 + 2 × 5 = 18 + 10 = 28. Plot 2 needs 28 meters of fence!",
    wrong: [
      { step: 1, choice: "b", hint: "9 × 5 finds the area inside. Perimeter adds the sides around the edge." },
      { step: 1, choice: "c", hint: "9 + 5 is only one length and one width. The fence has two of each." },
      { step: 1, choice: "d", hint: "That counts both lengths but only one width. Double the width too." },
      { step: 2, value: 45, hint: "9 × 5 = 45 is the area. Use 2 × 9 + 2 × 5 for the fence." },
      { step: 2, value: 14, hint: "9 + 5 = 14 is only half the way around. Double it." },
      { step: 2, value: 23, hint: "2 × 9 + 5 = 23 forgot one width. Add both widths: 2 × 5." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The square sunroot bed", machine: "Formula Board", icon: "grid", speaker: "kai",
    line: "The sunroot bed is a square. Every side is 6 meters long. All four sides match, so there's an even faster formula.",
    question: "Part 1: Which formula finds the perimeter of a square? Part 2: What is the perimeter? Part 3: What is the area?",
    parts: [
      { type: "choice", prompt: "A square has four sides that are all s meters long. Which formula finds its perimeter?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 6, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "6 m" }, title: "Sunroot bed" },
        choices: [
          { id: "a", text: "P = 4 × s" },
          { id: "b", text: "P = s × s" },
          { id: "c", text: "P = 2 × s" },
          { id: "d", text: "P = s + 4" },
        ] },
      { type: "number", prompt: "Each side is 6 meters. What is the perimeter of the sunroot bed?", unit: "meters" },
      { type: "number", prompt: "Now use A = l × w. What is the area of the sunroot bed?", unit: "square meters" },
    ],
    hint: "A square has 4 equal sides, so P = 4 × 6. For area, multiply length × width: 6 × 6.",
    meter: { heat: 5, label: "Fence built +5%", story: "The sunroot bed is fenced" },
    discovery: { id: "potatostems", name: "Potatoes", who: "Nova", fact: "A potato is not a root. It is a swollen underground stem that stores food. The eyes on a potato can sprout into new plants." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 24 }, { kind: "number", value: 36 }] },
    rightFeedback: "P = 4 × 6 = 24 meters, and A = 6 × 6 = 36 square meters. Same side length, two different jobs!",
    wrong: [
      { step: 1, choice: "b", hint: "s × s finds the area of a square. The fence needs all four sides added." },
      { step: 1, choice: "c", hint: "2 × s is only two sides. A square has four." },
      { step: 1, choice: "d", hint: "Adding 4 doesn't count the sides. There are 4 sides of length s, so multiply." },
      { step: 2, value: 36, hint: "6 × 6 = 36 is the area. The fence is 4 sides of 6 meters." },
      { step: 2, value: 12, hint: "6 + 6 = 12 is only two sides. Count all four." },
      { step: 3, value: 24, hint: "24 meters is the perimeter. Area counts the squares inside: 6 × 6." },
      { step: 3, value: 12, hint: "6 + 6 = 12 adds the sides. Area multiplies length × width." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Cover the glowberry patch", machine: "Area Scanner", icon: "scan", speaker: "nova",
    line: "The glowberry patch is 12 meters long and 8 meters wide. I need to cover every square meter with fresh soil.",
    question: "Part 1: Which formula finds how much soil covers the patch? Part 2: What is the area of the patch?",
    parts: [
      { type: "choice", prompt: "Which formula finds the area of the glowberry patch?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 8, cols: 12, perimeter: true, sideLabels: { top: "12 m", left: "8 m" }, title: "Glowberry patch" },
        choices: [
          { id: "a", text: "A = 12 × 8 (length × width)" },
          { id: "b", text: "A = 12 + 8" },
          { id: "c", text: "A = 2 × 12 + 2 × 8" },
          { id: "d", text: "A = 4 × 12" },
        ] },
      { type: "number", prompt: "What is the area of the glowberry patch?", unit: "square meters" },
    ],
    hint: "The model has 8 rows with 12 squares in each row. That's why A = l × w works: 12 × 8.",
    meter: { heat: 5, label: "Fence built +5%", story: "The glowberry patch gets new soil" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 96 }] },
    rightFeedback: "A = 12 × 8 = 96. The patch needs 96 square meters of soil!",
    wrong: [
      { step: 1, choice: "b", hint: "12 + 8 adds two sides. Soil covers the squares inside, so multiply." },
      { step: 1, choice: "c", hint: "2 × 12 + 2 × 8 is the perimeter, the distance around. Soil covers the inside." },
      { step: 1, choice: "d", hint: "4 × 12 is for the perimeter of a square with 12 m sides. This patch is a rectangle, and we need area." },
      { step: 2, value: 40, hint: "40 meters is the perimeter. Area is length × width: 12 × 8." },
      { step: 2, value: 20, hint: "12 + 8 = 20 adds the sides. There are 8 rows of 12 squares. Multiply." },
      { step: 2, value: 86, hint: "Close! Check your facts: 10 × 8 = 80 and 2 × 8 = 16. Add them." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The night-moth swarm", machine: "Fence Tracker", icon: "quake", speaker: "vega",
    line: "Surprise! A swarm of hungry night-moths is heading for the new moonmelon field. The field is 15 meters long and 9 meters wide. We have to fence it and plant it tonight!",
    question: "Part 1: What is the perimeter of the field? Part 2: Fence costs 3 dollars for each meter. What will the fence cost? Part 3: What is the area of the field?",
    parts: [
      { type: "number", prompt: "The moonmelon field is 15 m by 9 m. Use P = 2l + 2w. What is the perimeter?", unit: "meters",
        data: {
          title: "Moonmelon field order",
          columns: ["Item", "Amount"],
          rows: [["Length", "15 m"], ["Width", "9 m"], ["Fence price", "3 dollars per meter"]],
        } },
      { type: "number", prompt: "Each meter of fence costs 3 dollars. How much does the whole fence cost?", unit: "dollars" },
      { type: "number", prompt: "Use A = l × w. What is the area of the field?", unit: "square meters" },
    ],
    hint: "Perimeter first: 2 × 15 + 2 × 9. Then multiply the meters of fence by 3 dollars. Area is 15 × 9.",
    meter: { heat: 10, label: "Fence built +10%", story: "The moonmelons are safe from the moths" },
    discovery: { id: "purplecarrots", name: "Purple carrots", who: "Nova", fact: "Long ago, most carrots were purple or yellow. Orange carrots became popular only a few hundred years ago." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 48 }, { kind: "number", value: 144 }, { kind: "number", value: 135 }] },
    rightFeedback: "P = 30 + 18 = 48 meters. 48 × 3 = 144 dollars. A = 15 × 9 = 135 square meters. The field is safe!",
    wrong: [
      { step: 1, value: 24, hint: "15 + 9 = 24 is only half the fence. Double it, or use 2 × 15 + 2 × 9." },
      { step: 1, value: 135, hint: "15 × 9 = 135 is the area. The fence goes around the edge." },
      { step: 1, value: 39, hint: "2 × 15 + 9 = 39 forgot a width. There are two widths of 9." },
      { step: 2, value: 51, hint: "48 + 3 = 51. Each meter costs 3 dollars, so multiply 48 × 3." },
      { step: 2, value: 405, hint: "That's 135 × 3. The fence price goes with the meters of fence, the perimeter." },
      { step: 2, value: 72, hint: "72 is 24 × 3, only half of the fence. The whole fence is 48 meters." },
      { step: 3, value: 48, hint: "48 meters is the perimeter. Area counts the squares inside: 15 × 9." },
      { step: 3, value: 125, hint: "Close! Try 10 × 9 = 90 and 5 × 9 = 45. Add them." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The missing width", machine: "Plot Planner", icon: "dial", speaker: "nova",
    line: "The starleaf plot must be 72 square meters. My notes say it is 9 meters long, but a glow-slug ate the width!",
    question: "How many meters wide is the starleaf plot?",
    unit: "meters",
    data: {
      title: "Plot notes",
      columns: ["Plot", "Length", "Width", "Area"],
      rows: [["Plot 2", "9 m", "5 m", "45 sq m"], ["Glowberry patch", "12 m", "8 m", "96 sq m"], ["Starleaf plot", "9 m", "?", "72 sq m"]],
    },
    hint: "Area = length × width. So 9 × ? = 72. Think of your 9s facts, or divide 72 ÷ 9.",
    meter: { supplies: 1, label: "Plots planted +1", story: "The starleaf plot is planted" },
    discovery: { id: "peanuts", name: "Peanuts", who: "Kai", fact: "Peanuts grow underground! After a peanut flower fades, a stalk bends down and pushes into the soil, where the peanut pods grow." },
    answer: { kind: "number", value: 8 },
    rightFeedback: "9 × 8 = 72, so the starleaf plot is 8 meters wide!",
    wrong: [
      { value: 63, hint: "72 − 9 = 63. Area is length × width, so we need 9 × ? = 72." },
      { value: 27, hint: "That treats 72 like the perimeter. 72 is the AREA, so think 9 × ? = 72." },
      { value: 9, hint: "9 meters is the length we already know. Which number times 9 makes 72?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The same-number debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The mint square is 4 m by 4 m. Its perimeter is 16 and its area is 16. See? Perimeter and area are the same thing!"',
    nova: 'Nova: "They only matched this time. Perimeter is the length around, in meters. Area is the squares inside, in square meters. A 5 m by 3 m plot has a perimeter of 16 m but an area of only 15 square meters."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "3 m" }, title: "Nova's 5 m by 3 m plot" },
    hint: "Find the perimeter and the area of the 5 m by 3 m plot. Do they match?",
    meter: { heat: 5, label: "Fence built +5%", story: "Kai learns perimeter and area are different" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Perimeter measures the distance around and area measures the squares inside. They measure different things, even when the numbers match." },
      { id: "B", text: "Nova, because 5 by 3 is a bigger plot." },
      { id: "C", text: "Kai. The mint square proves perimeter and area are always equal." },
      { id: "D", text: "Kai. Both are measured in meters, so they are the same." },
    ],
    writtenPrompt: "Tell Kai in your own words why perimeter and area are not the same thing.",
    debateHints: {
      wrongWho: "Try the 5 m by 3 m plot. 5 + 3 + 5 + 3 = 16, but 5 × 3 = 15. Are they always the same?",
      wrongReason: "Right person, check the reason. What does each measurement tell us?",
      right: "Nova is right. Perimeter is a length around (meters). Area is squares inside (square meters). They can match by chance, but they measure different things.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Same soil, less fence", machine: "Plot Planner", icon: "cells", speaker: "vega",
    line: "We have 36 square meters of soil for a new pumpkin plot. Fence is scarce, so we want the plot that uses the least fence.",
    question: "Part 1: What is the perimeter of the 3 m by 12 m plot? Part 2: What is the perimeter of the 6 m by 6 m plot? Part 3: Which plot should the crew build?",
    data: {
      title: "Pumpkin plot choices (all 36 square meters)",
      columns: ["Plot", "Length", "Width", "Area"],
      rows: [["A", "18 m", "2 m", "36 sq m"], ["B", "12 m", "3 m", "36 sq m"], ["C", "6 m", "6 m", "36 sq m"]],
    },
    parts: [
      { type: "number", prompt: "Plot B is 12 m by 3 m. What is its perimeter?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 12, perimeter: true, sideLabels: { top: "12 m", left: "3 m" }, title: "Plot B" } },
      { type: "number", prompt: "Plot C is a 6 m square. What is its perimeter?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 6, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "6 m" }, title: "Plot C" } },
      { type: "choice", prompt: "Plot A (18 m by 2 m) needs 40 m of fence. Which plot should the crew build?", choices: [
        { id: "c", text: "Plot C. All three have the same area, but Plot C needs the least fence." },
        { id: "a", text: "Plot A. It is the longest, so it has the most room." },
        { id: "b", text: "Plot B. It is in the middle." },
        { id: "any", text: "Any of them. Same area means same fence." },
      ] },
    ],
    hint: "Use P = 2l + 2w for Plot B and P = 4s for Plot C. Then compare all three fences.",
    meter: { supplies: 2, label: "Plots planted +2", story: "The pumpkin plot is planted" },
    discovery: { id: "giantpumpkins", name: "Giant pumpkins", who: "Kai", fact: "The biggest pumpkins grown on Earth weigh more than 1,000 kilograms. That's heavier than some small cars!" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 30 }, { kind: "number", value: 24 }, { kind: "choice", correct: "c" }] },
    rightFeedback: "Plot B needs 30 m and Plot C needs 24 m. Same area, different perimeters. Plot C saves the most fence!",
    wrong: [
      { step: 1, value: 36, hint: "12 × 3 = 36 is the area. The fence goes around: 2 × 12 + 2 × 3." },
      { step: 1, value: 15, hint: "12 + 3 = 15 is only half the fence. Double it." },
      { step: 1, value: 27, hint: "2 × 12 + 3 = 27 forgot a width. Add both widths." },
      { step: 2, value: 36, hint: "6 × 6 = 36 is the area. The fence is 4 sides of 6 m: 4 × 6." },
      { step: 2, value: 12, hint: "6 + 6 = 12 is only two sides. A square has four." },
      { step: 3, choice: "a", hint: "Plot A has the same area as the others, 36 square meters. It needs the MOST fence." },
      { step: 3, choice: "b", hint: "Compare the fences: 40 m, 30 m, and 24 m. Which is the least?" },
      { step: 3, choice: "any", hint: "Look at your answers. Same area, but the fences are different lengths." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's fence order", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote: "The herb plot is 14 m long and 6 m wide. Fence needed: 14 + 6 = 20 meters." He ordered the fence, but it came up way short!',
    question: "Part 1: What went wrong? Part 2: How many meters of fence does the herb plot really need?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 6, cols: 14, perimeter: true, sideLabels: { top: "14 m", left: "6 m" }, title: "Herb plot" },
        choices: [
          { id: "a", text: "He added only one length and one width. The fence goes around all four sides." },
          { id: "b", text: "He should have multiplied 14 × 6." },
          { id: "c", text: "He should have used 4 × 14." },
          { id: "d", text: "Nothing. The fence company made a mistake." },
        ] },
      { type: "number", prompt: "What is the real perimeter of the herb plot?", unit: "meters" },
    ],
    hint: "Trace the edge with your finger. There are two lengths of 14 and two widths of 6. Try 2 × 14 + 2 × 6.",
    meter: { supplies: 1, label: "Plots planted +1", story: "Kai's fence order is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 40 }] },
    rightFeedback: "Fixed! 2 × 14 + 2 × 6 = 28 + 12 = 40 meters. Kai needs 20 more meters of fence.",
    wrong: [
      { step: 1, choice: "b", hint: "14 × 6 finds the area, the squares inside. A fence needs a length around." },
      { step: 1, choice: "c", hint: "4 × s only works for a square. This plot has two different side lengths." },
      { step: 1, choice: "d", hint: "Check Kai's math. Did 14 + 6 go all the way around the plot?" },
      { step: 2, value: 20, hint: "20 is Kai's short order. That's only half the way around. Double it." },
      { step: 2, value: 84, hint: "14 × 6 = 84 is the area. The fence goes around: 2 × 14 + 2 × 6." },
      { step: 2, value: 34, hint: "2 × 14 + 6 = 34 forgot a width. There are two widths of 6." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The leftover fence roll", machine: "Plot Planner", icon: "snap", speaker: "vega",
    line: "Surprise! A supply pod dropped one last roll of fence. It is exactly 34 meters long. Nova wants to use all of it for a glowbean plot that is 11 meters long.",
    question: "Part 1: How wide can the plot be? Part 2: What is the area of the plot? Part 3: One seed packet plants 6 square meters. How many packets do we need?",
    parts: [
      { type: "number", prompt: "The fence (perimeter) is 34 m. The two lengths are 11 m each. How many meters wide is the plot?", unit: "meters",
        data: {
          title: "Glowbean plot",
          columns: ["Measure", "Amount"],
          rows: [["Fence roll (perimeter)", "34 m"], ["Length", "11 m"], ["Width", "?"], ["One seed packet plants", "6 sq m"]],
        } },
      { type: "number", prompt: "Now you know both sides. What is the area of the glowbean plot?", unit: "square meters" },
      { type: "number", prompt: "One seed packet plants 6 square meters. How many packets cover the whole plot?", unit: "packets" },
    ],
    hint: "The two lengths use 11 + 11 = 22 m of fence. The rest is split between two equal widths. Then A = l × w, and divide the area by 6.",
    meter: { heat: 10, label: "Fence built +10%", story: "The glowbean plot uses every meter of fence" },
    discovery: { id: "tendrils", name: "Pea tendrils", who: "Nova", fact: "Pea plants grow thin, curly tendrils. The tendrils wrap around fences and strings to help the plant climb toward sunlight." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 6 }, { kind: "number", value: 66 }, { kind: "number", value: 11 }] },
    rightFeedback: "34 − 22 = 12, and 12 ÷ 2 = 6 m wide. A = 11 × 6 = 66 square meters. 66 ÷ 6 = 11 seed packets!",
    wrong: [
      { step: 1, value: 12, hint: "12 m is what's left for BOTH widths. Split it into two equal widths." },
      { step: 1, value: 23, hint: "34 − 11 = 23 took away only one length. The plot has two lengths of 11." },
      { step: 1, value: 3, hint: "34 is the perimeter, not the area, so don't divide 34 by 11. Take away both lengths first." },
      { step: 2, value: 34, hint: "34 m is the perimeter. Area is length × width: 11 × 6." },
      { step: 2, value: 17, hint: "11 + 6 = 17 adds the sides. Area multiplies them." },
      { step: 3, value: 66, hint: "66 is the area. Each packet plants 6 square meters, so divide 66 ÷ 6." },
      { step: 3, value: 396, hint: "That multiplied 66 × 6. Each packet covers 6 square meters, so we need fewer packets than 66. Divide." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Around or inside?", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "The garden job list got scrambled. Some jobs need the distance around a plot. Some need the space inside it.",
    question: "Sort each job: is it a perimeter job or an area job?",
    hint: "Ask: does this job go along the edge (perimeter), or does it cover the whole inside (area)?",
    meter: { supplies: 1, label: "Plots planted +1", story: "Every garden job is sorted" },
    discovery: { id: "mulch", name: "Mulch", who: "Nova", fact: "Gardeners spread mulch, like wood chips or straw, on top of the soil. Mulch keeps the soil damp and blocks weeds from growing." },
    answer: { kind: "sort", bins: { j1: "perim", j2: "perim", j3: "perim", j4: "area", j5: "area", j6: "area" } },
    rightFeedback: "Every job is sorted! Fences, border lights, and edging go around. Soil, seeds, and mulch cover the inside.",
    sort: {
      bins: [
        { id: "perim", label: "Perimeter job (around)" },
        { id: "area", label: "Area job (inside)" },
      ],
      items: [
        { id: "j1", label: "Build a fence around the melon plot" },
        { id: "j2", label: "Hang glow lights along the edge of the bed" },
        { id: "j3", label: "Lay stone edging around the herb plot" },
        { id: "j4", label: "Spread soil over the whole berry patch" },
        { id: "j5", label: "Plant seeds to fill the entire plot" },
        { id: "j6", label: "Cover the bed with a layer of mulch" },
      ],
    },
    wrong: [
      { item: "j1", hint: "A fence runs along the edge of the plot. That's the distance around." },
      { item: "j2", hint: "Lights along the edge follow the outside. That's perimeter." },
      { item: "j3", hint: "Edging goes around the plot, not over it. That's perimeter." },
      { item: "j4", hint: "Soil covers the whole inside of the patch. That's area." },
      { item: "j5", hint: "Seeds fill the entire plot, not just the edge. That's area." },
      { item: "j6", hint: "Mulch covers the whole bed. That's area." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Pick every fence formula", machine: "Formula Board", icon: "grid", speaker: "nova",
    line: "The crew wrote formulas on the board for the fence around an 8 m by 5 m bed. Some of them work and some don't.",
    question: "Part 1: Pick every formula that finds the perimeter. Part 2: What is the perimeter?",
    parts: [
      { type: "multi", prompt: "Which formulas find the perimeter of an 8 m by 5 m rectangle?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 8, perimeter: true, sideLabels: { top: "8 m", left: "5 m" }, title: "Lantern-flower bed" },
        choices: [
          { id: "lwlw", text: "P = 8 + 5 + 8 + 5" },
          { id: "2l2w", text: "P = 2 × 8 + 2 × 5" },
          { id: "lxw", text: "P = 8 × 5" },
          { id: "4s", text: "P = 4 × 8" },
          { id: "lw", text: "P = 8 + 5" },
        ] },
      { type: "number", prompt: "What is the perimeter of the lantern-flower bed?", unit: "meters" },
    ],
    hint: "A rectangle has two lengths and two widths. l + w + l + w and 2l + 2w both add all four sides.",
    meter: { heat: 5, label: "Fence built +5%", story: "The lantern-flower bed is fenced" },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["lwlw", "2l2w"] }, { kind: "number", value: 26 }] },
    rightFeedback: "8 + 5 + 8 + 5 = 26 and 2 × 8 + 2 × 5 = 26. Two formulas, the same fence!",
    wrong: [
      { step: 1, pick: "lxw", hint: "8 × 5 is the area formula, l × w. It counts squares inside." },
      { step: 1, pick: "4s", hint: "4 × s is for a square. This bed has two different side lengths." },
      { step: 1, pick: "lw", hint: "8 + 5 is only one length and one width. That's half the fence." },
      { step: 1, missing: true, hint: "Two formulas work. One adds all four sides. The other doubles the length and the width." },
      { step: 2, value: 40, hint: "8 × 5 = 40 is the area. Add all four sides for the fence." },
      { step: 2, value: 13, hint: "8 + 5 = 13 is only half the way around. Double it." },
      { step: 2, value: 32, hint: "4 × 8 = 32 treats the bed like a square. The widths are only 5 m." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "More fence, more room?", machine: "Area Scanner", icon: "scan", speaker: "kai",
    line: "Plot A is 10 m by 2 m. Plot B is a square, 5 m on each side. Plot A has more fence around it, so it must have more room inside. Right?",
    question: "Part 1: What is the perimeter of Plot A? Part 2: What is the area of Plot A? Part 3: What is the area of Plot B? Part 4: Is Kai right?",
    parts: [
      { type: "number", prompt: "Plot A is 10 m by 2 m. What is its perimeter?", unit: "meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 2, cols: 10, perimeter: true, sideLabels: { top: "10 m", left: "2 m" }, title: "Plot A" } },
      { type: "number", prompt: "What is the area of Plot A?", unit: "square meters" },
      { type: "number", prompt: "Plot B is 5 m by 5 m. Its perimeter is 20 m. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "5 m" }, title: "Plot B" } },
      { type: "choice", prompt: "Plot A has 24 m of fence. Plot B has 20 m. Is Kai right?", choices: [
        { id: "a", text: "No. Plot A has the bigger perimeter, but Plot B has the bigger area. More fence doesn't always mean more room." },
        { id: "b", text: "Yes. A bigger perimeter always means a bigger area." },
        { id: "c", text: "No. They have the same area because they are both rectangles." },
        { id: "d", text: "Yes, because 10 is the longest side." },
      ] },
    ],
    hint: "Use 2l + 2w for the fence and l × w for the room inside. Then compare both plots.",
    meter: { supplies: 1, label: "Plots planted +1", story: "Kai rethinks long skinny plots" },
    discovery: { id: "deerfence", name: "Jumping deer", who: "Nova", fact: "White-tailed deer can leap over a fence about 2 and a half meters tall. That's taller than most grown-ups! Gardeners build tall fences to keep deer out." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 24 }, { kind: "number", value: 20 }, { kind: "number", value: 25 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "Plot A: 24 m of fence, 20 square meters. Plot B: 20 m of fence, 25 square meters. The shorter fence holds more room!",
    wrong: [
      { step: 1, value: 20, hint: "10 × 2 = 20 is the area. The fence goes around: 2 × 10 + 2 × 2." },
      { step: 1, value: 12, hint: "10 + 2 = 12 is only half the fence. Double it." },
      { step: 2, value: 24, hint: "24 meters is the perimeter. Area is 10 × 2." },
      { step: 2, value: 12, hint: "10 + 2 = 12 adds the sides. Area multiplies them." },
      { step: 3, value: 20, hint: "20 meters is Plot B's perimeter. Area is 5 × 5." },
      { step: 3, value: 10, hint: "5 + 5 = 10 adds two sides. Area multiplies: 5 × 5." },
      { step: 4, choice: "b", hint: "Check your numbers. Plot A has more fence but fewer square meters inside." },
      { step: 4, choice: "c", hint: "Being rectangles doesn't make areas match. Compare 20 and 25." },
      { step: 4, choice: "d", hint: "A long side doesn't guarantee more room. Plot A is only 2 m wide." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The square herb garden", machine: "Plot Planner", icon: "trail", speaker: "nova",
    line: "Commander Vega wants a square herb garden with an area of exactly 49 square meters. Then we'll fence it.",
    question: "Part 1: How long is each side of the square? Part 2: How much fence does it need?",
    parts: [
      { type: "number", prompt: "A square has 4 equal sides. Its area is 49 square meters. How long is each side?", unit: "meters" },
      { type: "number", prompt: "Use P = 4 × s. How many meters of fence go around the herb garden?", unit: "meters" },
    ],
    hint: "For a square, A = s × s. Which number times itself makes 49? Then multiply that side by 4.",
    meter: { heat: 5, label: "Fence built +5%", story: "The square herb garden is fenced" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 7 }, { kind: "number", value: 28 }] },
    rightFeedback: "7 × 7 = 49, so each side is 7 m. P = 4 × 7 = 28 meters of fence!",
    wrong: [
      { step: 1, value: 45, hint: "49 − 4 = 45. Area is side × side. Which number times itself makes 49?" },
      { step: 1, value: 12, hint: "Dividing 49 by 4 is for perimeter, and it doesn't work out evenly. For area, find s × s = 49." },
      { step: 1, value: 24, hint: "About half of 49 would be s + s. Area multiplies: s × s = 49." },
      { step: 2, value: 49, hint: "49 is the area. The fence is 4 sides of 7 meters." },
      { step: 2, value: 14, hint: "7 + 7 = 14 is only two sides. Use all four: 4 × 7." },
      { step: 2, value: 196, hint: "That's 4 × 49. Multiply the SIDE by 4, not the area." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The glow-harvest field", machine: "Fence Tracker", icon: "relay", speaker: "vega",
    line: "This is it! The glow-harvest festival starts at moonrise. We need one giant festival field, 18 meters long and 12 meters wide. Surprise: the fence costs 4 dollars a meter, and each seed packet only plants 8 square meters!",
    question: "Part 1: What is the perimeter of the field? Part 2: What will the fence cost? Part 3: What is the area? Part 4: How many seed packets do we need?",
    parts: [
      { type: "number", prompt: "The festival field is 18 m by 12 m. What is its perimeter?", unit: "meters",
        data: {
          title: "Festival field supply sheet",
          columns: ["Item", "Amount"],
          rows: [["Length", "18 m"], ["Width", "12 m"], ["Fence price", "4 dollars per meter"], ["One seed packet plants", "8 sq m"]],
        } },
      { type: "number", prompt: "Fence costs 4 dollars for each meter. How much does the fence cost?", unit: "dollars" },
      { type: "number", prompt: "What is the area of the festival field?", unit: "square meters" },
      { type: "number", prompt: "One seed packet plants 8 square meters. How many packets plant the whole field?", unit: "packets" },
    ],
    hint: "Fence first: 2 × 18 + 2 × 12, then × 4 dollars. Seeds use area: 18 × 12, then divide by 8.",
    meter: { heat: 15, label: "Fence built +15%", story: "The glow-harvest field is ready on Lumara" },
    discovery: { id: "companionplants", name: "Marigold helpers", who: "Kai", fact: "Many gardeners plant marigolds next to their vegetables. The bright flowers attract helpful insects, like ladybugs, that eat garden pests." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 60 }, { kind: "number", value: 240 }, { kind: "number", value: 216 }, { kind: "number", value: 27 }] },
    rightFeedback: "P = 36 + 24 = 60 m. 60 × 4 = 240 dollars. A = 18 × 12 = 216 square meters. 216 ÷ 8 = 27 packets. Happy glow-harvest!",
    wrong: [
      { step: 1, value: 30, hint: "18 + 12 = 30 is only half the fence. Double it." },
      { step: 1, value: 216, hint: "18 × 12 = 216 is the area. The fence goes around: 2 × 18 + 2 × 12." },
      { step: 1, value: 48, hint: "2 × 18 + 12 = 48 forgot a width. There are two widths of 12." },
      { step: 2, value: 64, hint: "60 + 4 = 64. Each meter costs 4 dollars, so multiply 60 × 4." },
      { step: 2, value: 864, hint: "That's 216 × 4. The fence price goes with the meters of fence, the perimeter." },
      { step: 2, value: 120, hint: "120 is 30 × 4, only half of the fence. The whole fence is 60 m." },
      { step: 3, value: 60, hint: "60 meters is the perimeter. Area is 18 × 12." },
      { step: 3, value: 196, hint: "Close! Try 18 × 10 = 180 and 18 × 2 = 36. Add them." },
      { step: 4, value: 216, hint: "216 is the area. Each packet plants 8 square meters, so divide 216 ÷ 8." },
      { step: 4, value: 1728, hint: "That multiplied 216 × 8. Each packet covers 8 square meters, so we need fewer packets. Divide." },
      { step: 4, value: 30, hint: "240 ÷ 8 = 30 used the fence cost. Seeds cover the area: 216 ÷ 8." },
    ],
  },
};

export default {
  id: "MA.4.5D-XP",
  standard: "MA.4.5D-XP",
  engine: "expedition_station",
  title: "The Garden Plots",
  planet: "Lumara",
  outpost: "Glow Garden · new plot fields",
  grade: 4,
  subject: "Math",
  teks: "4.5D",
  supportingTeks: ["4.5C"],
  skillsChip: "4.5D · Perimeter and area of rectangles",
  iCan: "I can use the formulas P = 2l + 2w, P = 4s, and A = l × w to solve problems about the perimeter and area of rectangles, including finding a missing side.",
  blurb: "The crew is fencing and planting new garden plots in the glowing garden on Lumara. They need the right amount of fence, soil, and seeds before the glow-harvest festival.",
  mission: "Fence the new plots, plant them, and get the festival field ready for the glow-harvest.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.5D · LUMARA PLOT FIELDS",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Fence built", heatUnit: "%", supplies: "Plots planted", suppliesUnit: "plots" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. The glowing garden on Lumara is growing fast.",
    "We need new garden plots. Every plot needs the right amount of fence around it and seeds inside it.",
    "Help Kai and Nova use perimeter and area to plan them. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Fence the first plots", "Act 2 · Plan with less fence", "Act 3 · The glow-harvest"],
    completes: [
      "The first plots are fenced, {firstName}!",
      "The plots are planned and every meter of fence is used, {firstName}!",
      "The festival field is ready, {firstName}! Lumara's glow-harvest can begin.",
    ],
    teasers: [
      "Next on Lumara: fence is running low, so we plan smarter plots. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: the glow-harvest festival is almost here. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Fence is running low, so every plot has to be planned carefully.",
      "Kai keeps mixing up perimeter and area, so let's check his work together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The glow-harvest festival is coming.",
      "Help the crew sort the garden jobs and plan the giant festival field.",
    ],
  }),
  tasks,
};
