// Expedition Station — The Greenhouse Test (SCI.4.12A-XP)
// Grade 4 · Science · Lumara (glowing garden). Main standard 4.12A (investigate
// and explain how most producers can make their own food using sunlight,
// water, and carbon dioxide through the cycling of matter); also practices
// 4.1B (plan and conduct simple descriptive and experimental investigations),
// 4.1E (collect observations and measurements as evidence), 4.2B (analyze data
// for patterns), 4.2C (use math to compare data), 4.2D (evaluate experimental
// design), 4.3A (explanations supported by data), 4.3B (communicate
// explanations), 4.3C (respectful scientific discussion), 4.5B (cause and
// effect), 4.5E (matter cycles and energy flows through systems).
//
// Earth-true rule: Lumara glows, but the plants in the crew's greenhouse are
// real Earth plants. Every process, fact, and data table is real Earth science.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Who can make lunch?", machine: "Greenhouse Roll Call", icon: "cells", speaker: "nova",
    line: "Our greenhouse is full of Earth plants, and the garden is full of Earth critters. First question: who can make their own food?",
    question: "Sort each living thing: can it make its own food, or not?",
    hint: "Producers make their own food using sunlight. Anything that has to eat or soak up food from something else can't.",
    meter: { heat: 10, label: "Leaf power +10%", story: "The greenhouse roll call is done" },
    discovery: { id: "mushrooms", name: "Mushrooms aren't plants", who: "Nova", fact: "Mushrooms are not plants. They are fungi, and they can't make their own food. They get food by breaking down dead leaves and wood." },
    answer: { kind: "sort", bins: { c1: "makes", c2: "cant", c3: "makes", c4: "cant", c5: "makes", c6: "cant" } },
    rightFeedback: "Bean plants, grass, and oak trees are producers. Rabbits, mushrooms, and Kai all have to get food from something else.",
    sort: {
      bins: [{ id: "makes", label: "Makes its own food (producer)" }, { id: "cant", label: "Can't make its own food" }],
      items: [
        { id: "c1", label: "A bean plant" },
        { id: "c2", label: "A rabbit" },
        { id: "c3", label: "Grass" },
        { id: "c4", label: "A mushroom" },
        { id: "c5", label: "An oak tree" },
        { id: "c6", label: "Kai" },
      ],
    },
    wrong: [
      { item: "c4", hint: "A mushroom grows in the ground like a plant, but it isn't green and can't use sunlight to make food." },
      { item: "c2", hint: "A rabbit eats plants. Does it make food in its own body from sunlight?" },
      { item: "c6", hint: "Kai eats snacks all day! People can't make food from sunlight." },
      { item: "c1", hint: "A bean plant has green leaves that use sunlight to make food." },
      { item: "c3", hint: "Grass is a green plant. It makes its own food in its leaves." },
      { item: "c5", hint: "An oak tree is a plant with green leaves. It makes its own food." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The food recipe", machine: "Leaf Kitchen", icon: "flask", speaker: "vega",
    line: "The garden council wants to know what our plants need to make food. Nova says it's a short list.",
    question: "Pick everything a plant takes in to make its own food.",
    items: [
      { id: "sun", text: "Sunlight" },
      { id: "water", text: "Water" },
      { id: "co2", text: "Carbon dioxide from the air" },
      { id: "soil", text: "Soil to eat" },
      { id: "sugar", text: "Sugar from the ground" },
      { id: "oxygen", text: "Oxygen" },
    ],
    hint: "There are three things: one gives energy, one comes up from the roots, and one comes from the air.",
    meter: { heat: 10, label: "Leaf power +10%", story: "The food recipe is posted" },
    discovery: { id: "chlorophyll", name: "Chlorophyll", who: "Nova", fact: "Chlorophyll is the green material inside leaves. It catches the Sun's light energy so the plant can make food." },
    answer: { kind: "multi", correct: ["sun", "water", "co2"] },
    rightFeedback: "Sunlight, water, and carbon dioxide. With those, a plant makes its own sugar.",
    wrong: [
      { pick: "soil", hint: "Roots grow in soil and take in water from it, but plants don't eat the soil." },
      { pick: "sugar", hint: "Sugar is what the plant makes. It doesn't take sugar in from the ground." },
      { pick: "oxygen", hint: "Oxygen is what the plant gives off when it makes food. Which gas does it take in from the air?" },
      { missing: true, hint: "There are three. Think about energy, what the roots drink, and a gas in the air." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Bubbles in the tank", machine: "Pond Tank", icon: "water", speaker: "kai",
    line: "I put an Earth water plant in a tank under the sun lamp. Now tiny bubbles are coming off its leaves!",
    question: "The plant is making food. What gas is in the bubbles?",
    hint: "When a plant makes food, it gives off a gas that people and animals breathe in.",
    meter: { heat: 10, label: "Leaf power +10%", story: "The tank bubbles are explained" },
    discovery: { id: "bubbles", name: "Oxygen bubbles", who: "Kai", fact: "Water plants give off tiny bubbles of oxygen when light shines on them. In dim light, the bubbles slow down or stop." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Oxygen" },
      { id: "b", text: "Carbon dioxide" },
      { id: "c", text: "Sugar" },
      { id: "d", text: "Soil" },
    ],
    rightFeedback: "Plants give off oxygen when they make food. You can see it bubble out of water plants!",
    wrong: [
      { choice: "b", hint: "Carbon dioxide is what the plant takes in to make food. What does it give off?" },
      { choice: "c", hint: "Sugar is the food the plant keeps. Bubbles are a gas. Which gas does the plant give off?" },
      { choice: "d", hint: "Soil isn't a gas, and there's no soil in the bubbles. What gas do we breathe in?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Measure the bean", machine: "Growth Ruler", icon: "dial", speaker: "nova",
    line: "I've been measuring a bean plant on the sunny shelf every day for two weeks.",
    question: "How many centimeters did the bean plant grow in two weeks?",
    unit: "cm",
    data: {
      title: "Sunny shelf bean plant",
      columns: ["Day", "Height (cm)", "Notes"],
      rows: [
        ["1", "3", "Two small green leaves"],
        ["7", "9", "Four green leaves"],
        ["14", "15", "Eight green leaves, strong stem"],
      ],
    },
    hint: "Compare the height on Day 14 with the height on Day 1.",
    meter: { supplies: 1, label: "Test trays +1", story: "The first bean is measured" },
    answer: { kind: "number", value: 12 },
    rightFeedback: "15 cm − 3 cm = 12 cm of growth in two weeks.",
    wrong: [
      { value: 15, hint: "15 cm is how tall it is now. It was already 3 cm tall on Day 1." },
      { value: 18, hint: "You want how much it grew. Should you add or subtract?" },
      { value: 6, hint: "That's how much it grew in one week. Look at Day 1 and Day 14." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The sealed greenhouse", machine: "Air Sensor", icon: "quake", speaker: "vega",
    line: "Surprise! Kai sealed every greenhouse vent last night to keep the heat in. Now it's a bright sunny day, and the air sensor is acting strange.",
    question: "Part 1: Why did the carbon dioxide go down during the day? Part 2: Why did the oxygen go up? Part 3: Why did carbon dioxide go back up a little at night? Part 4: What should Kai do?",
    data: {
      title: "Greenhouse air sensor (vents sealed)",
      columns: ["Time", "Light", "Carbon dioxide", "Oxygen"],
      rows: [
        ["6 AM", "Dark", "Normal", "Normal"],
        ["10 AM", "Bright", "Going down", "Going up"],
        ["3 PM", "Bright", "Very low", "High"],
        ["11 PM", "Dark", "Going up a little", "Going down a little"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Why did the carbon dioxide go down during the day?", choices: [
        { id: "a", text: "The plants took it in from the air to make food in the sunlight." },
        { id: "b", text: "The sun lamp burned it up." },
        { id: "c", text: "The soil soaked it all up." },
        { id: "d", text: "The sensor is broken." },
      ] },
      { type: "choice", prompt: "Why did the oxygen go up during the day?", choices: [
        { id: "a", text: "The plants gave off oxygen while they made food." },
        { id: "b", text: "Oxygen leaked in through the sealed vents." },
        { id: "c", text: "Sunlight turned into oxygen." },
        { id: "d", text: "The plants stopped breathing." },
      ] },
      { type: "choice", prompt: "Why did the carbon dioxide go back up a little at night?", choices: [
        { id: "a", text: "In the dark, the plants couldn't make food, but living things kept breathing out carbon dioxide." },
        { id: "b", text: "The Moon makes carbon dioxide." },
        { id: "c", text: "Plants make more food at night." },
        { id: "d", text: "The glass walls turn into carbon dioxide at night." },
      ] },
      { type: "choice", prompt: "What should Kai do so the plants can keep making food?", choices: [
        { id: "a", text: "Open the vents so fresh air with carbon dioxide can come in." },
        { id: "b", text: "Turn off the lights to save the plants' energy." },
        { id: "c", text: "Pour sugar on the soil." },
        { id: "d", text: "Stop watering the plants." },
      ] },
    ],
    hint: "Plants take in carbon dioxide and give off oxygen when they make food. They need light to do it.",
    meter: { heat: 10, label: "Leaf power +10%", story: "The vents are open again" },
    discovery: { id: "extraco2", name: "Greenhouse air", who: "Kai", fact: "Some greenhouse farmers add extra carbon dioxide to the air inside. With more carbon dioxide, their plants can make more food and grow faster." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The plants used up the carbon dioxide in the sealed air. Open vents bring in more. Great detective work!",
    wrong: [
      { step: 1, choice: "b", hint: "Lamps give light, not fire. Check the Light column. What do plants do when it's bright?" },
      { step: 1, choice: "c", hint: "Plants take in carbon dioxide through their leaves, not the soil. What were they doing in the bright light?" },
      { step: 1, choice: "d", hint: "Look for a pattern. The change only happened when it was bright. What do plants do in light?" },
      { step: 2, choice: "b", hint: "The vents were sealed shut. Something inside the greenhouse gave off the oxygen." },
      { step: 2, choice: "c", hint: "Sunlight gives plants energy, but it doesn't turn into oxygen. Who gives off oxygen when making food?" },
      { step: 2, choice: "d", hint: "Living things never stop breathing. What do plants give off while they make food?" },
      { step: 3, choice: "b", hint: "The Moon doesn't make any gas. What did the plants stop doing when it got dark?" },
      { step: 3, choice: "c", hint: "Plants need light to make food. Check the Light column at 11 PM." },
      { step: 3, choice: "d", hint: "Glass doesn't change into gas. Living things breathe out carbon dioxide all the time." },
      { step: 4, choice: "b", hint: "Plants need light to make food. Turning it off would stop them." },
      { step: 4, choice: "c", hint: "Plants make their own sugar. What ran out in the sealed air?" },
      { step: 4, choice: "d", hint: "Plants need water to make food. What ran low in the sensor table?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Dirt for dinner?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Plants get their food from the soil. That\'s why we put them in dirt. The roots slurp up food!"',
    nova: 'Nova: "Roots take in water from the soil, but plants make their own food in their leaves with sunlight, water, and carbon dioxide."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the recipe. What are the three things a plant needs to make food? Is soil one of them?",
    meter: { heat: 5, label: "Leaf power +5%", story: "Kai rethinks the soil" },
    discovery: { id: "willow", name: "The willow tree test", who: "Nova", fact: "About 400 years ago, a scientist grew a small willow tree in a pot of soil for 5 years. The tree gained about 74 kilograms, but the soil lost only a tiny bit." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Plants make their own food (sugar) in their leaves using sunlight, water, and carbon dioxide. Roots mostly take in water, not food." },
      { id: "B", text: "Nova, because soil is too dirty to eat." },
      { id: "C", text: "Kai. The soil gets used up as the plant grows bigger." },
      { id: "D", text: "Kai. Plants have roots, and roots are like mouths." },
    ],
    writtenPrompt: "Tell Kai in your own words where a plant's food comes from.",
    debateHints: {
      wrongWho: "Remember the bubbles and the air sensor. Where does a plant make its food?",
      wrongReason: "Right person, check the reason. What does a plant use to make food, and where?",
      right: "Nova is right. Plants make their own food. The soil gives them water, not dinner.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Plan a fair test", machine: "Test Bench", icon: "log", speaker: "nova",
    line: "I want to test whether bean plants need light to grow well. One tray goes on the sunny shelf. One tray goes in a dark cabinet.",
    question: "To make it a fair test, what should Nova keep the same for both trays? Pick every one.",
    items: [
      { id: "kind", text: "The kind of plant" },
      { id: "water", text: "How much water each plant gets" },
      { id: "soil", text: "The kind and amount of soil" },
      { id: "pot", text: "The size of the pots" },
      { id: "light", text: "Light or dark" },
      { id: "height", text: "How tall the plants end up" },
    ],
    hint: "In a fair test, you change only one thing on purpose. Everything else stays the same.",
    meter: { supplies: 1, label: "Test trays +1", story: "The fair test is planned" },
    answer: { kind: "multi", correct: ["kind", "water", "soil", "pot"] },
    rightFeedback: "Same plants, same water, same soil, same pots. Only the light changes. That's a fair test!",
    wrong: [
      { pick: "light", hint: "Light is the one thing Nova is changing on purpose. That's what she's testing." },
      { pick: "height", hint: "Height is what Nova will measure to see what happened. She can't keep it the same." },
      { missing: true, hint: "There are four things to keep the same. Think about the plants, water, soil, and pots." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Lunch for the roots", machine: "Root Window", icon: "scan", speaker: "kai",
    line: "Our root window lets us see roots growing in the dark soil. But wait. Roots can't catch any sunlight down there. How do they get food?",
    question: "How do a plant's roots get food?",
    hint: "The food is made in one part of the plant. Then it has to get to all the other parts.",
    meter: { heat: 5, label: "Leaf power +5%", story: "The root puzzle is solved" },
    discovery: { id: "sugartrip", name: "Sugar on the move", who: "Nova", fact: "Sugar made in the leaves travels through tubes in the stem to every part of the plant, even the roots underground." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Sugar made in the green leaves travels down the stem to the roots." },
      { id: "b", text: "Roots make their own food from the dirt." },
      { id: "c", text: "Roots don't need any food." },
      { id: "d", text: "Worms bring food to the roots." },
    ],
    rightFeedback: "The leaves make the sugar, and the stem carries it down to feed the roots.",
    wrong: [
      { choice: "b", hint: "Making food takes sunlight, and there's no sunlight underground. Where is the food made?" },
      { choice: "c", hint: "Roots are alive and growing. Every living part needs food. Where does it come from?" },
      { choice: "d", hint: "Worms help loosen the soil, but they don't deliver food. What part of the plant makes food?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Sprouts in the drawer", machine: "Seed Drawer", icon: "snap", speaker: "vega",
    line: "I found bean seeds that sprouted inside a dark drawer! They have little white roots and shoots, but no green leaves yet.",
    question: "The sprouts have no light and no green leaves. How did they get food to start growing?",
    hint: "Before a plant has leaves, it needs food from somewhere. What's packed inside a seed?",
    meter: { supplies: 1, label: "Test trays +1", story: "The drawer sprouts are planted" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "They used food stored inside the seed. Soon they'll need light on green leaves to make more." },
      { id: "b", text: "They made food from the darkness." },
      { id: "c", text: "They ate the wood of the drawer." },
      { id: "d", text: "Sprouts never need food." },
    ],
    rightFeedback: "A seed carries a packed lunch. Once it runs out, the plant must make its own food with light.",
    wrong: [
      { choice: "b", hint: "Plants need light, not darkness, to make food. What was inside the seed?" },
      { choice: "c", hint: "Plants don't eat wood. The food came from inside the seed itself." },
      { choice: "d", hint: "Growing takes food and energy. Where could the sprout's first food come from?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The snail jar", machine: "Mini World Jar", icon: "tank", speaker: "vega",
    line: "Surprise! Nova sealed a water plant and a pond snail inside a clear jar four weeks ago. No one opened it, and both are still alive on the sunny shelf!",
    question: "Part 1: What does the plant give the snail? Part 2: What does the snail give the plant? Part 3: Sort what the plant takes in and gives off. Part 4: Predict what would happen in a dark closet.",
    parts: [
      { type: "choice", prompt: "What does the plant give the snail?", choices: [
        { id: "a", text: "Oxygen to breathe and leaves to eat" },
        { id: "b", text: "Carbon dioxide to breathe" },
        { id: "c", text: "Sunlight" },
        { id: "d", text: "Nothing at all" },
      ] },
      { type: "choice", prompt: "What does the snail give the plant?", choices: [
        { id: "a", text: "Carbon dioxide that it breathes out" },
        { id: "b", text: "Oxygen that it breathes out" },
        { id: "c", text: "Sugar that it makes" },
        { id: "d", text: "Sunlight" },
      ] },
      { type: "sort", prompt: "Sort: does the plant take it in or give it off?", bins: [
        { id: "in", label: "Plant takes it in" },
        { id: "out", label: "Plant gives it off" },
      ], items: [
        { id: "co2", label: "Carbon dioxide" },
        { id: "water", label: "Water" },
        { id: "light", label: "Sunlight energy" },
        { id: "oxygen", label: "Oxygen" },
      ] },
      { type: "choice", prompt: "What would happen if the jar sat in a dark closet for weeks?", choices: [
        { id: "a", text: "The plant couldn't make food or oxygen, so the plant and the snail would both be in trouble." },
        { id: "b", text: "Nothing would change. The jar would be fine." },
        { id: "c", text: "The snail would make food for the plant." },
        { id: "d", text: "The plant would grow faster in the dark." },
      ] },
    ],
    hint: "The plant and the snail trade gases. One takes in what the other gives off.",
    meter: { heat: 10, label: "Leaf power +10%", story: "The snail jar is back on the sunny shelf" },
    discovery: { id: "breath", name: "Your breath feeds plants", who: "Nova", fact: "Every time you breathe out, you give off carbon dioxide. Plants can use it to make food, and they give back oxygen for you to breathe." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "sort", bins: { co2: "in", water: "in", light: "in", oxygen: "out" } },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Oxygen and carbon dioxide go around and around between the plant and the snail. That's matter cycling!",
    wrong: [
      { step: 1, choice: "b", hint: "Animals breathe in oxygen, not carbon dioxide. What does a plant give off?" },
      { step: 1, choice: "c", hint: "Sunlight comes from the Sun, not the plant. What gas does the plant give off?" },
      { step: 1, choice: "d", hint: "The snail has lived for weeks in a sealed jar. It must be getting air and food from somewhere." },
      { step: 2, choice: "b", hint: "Animals breathe in oxygen and breathe out another gas. Which one?" },
      { step: 2, choice: "c", hint: "Snails are consumers. They can't make sugar. What gas does the snail breathe out?" },
      { step: 2, choice: "d", hint: "The snail can't make light. What gas does it breathe out?" },
      { step: 3, item: "oxygen", hint: "Remember the bubbles in the tank. Oxygen comes out of the plant." },
      { step: 3, item: "co2", hint: "The plant takes carbon dioxide in from the air to make food." },
      { step: 3, item: "water", hint: "Water goes into the plant. It's one of the three things it needs to make food." },
      { step: 3, item: "light", hint: "Sunlight energy goes into the leaves. The plant uses it to make food." },
      { step: 4, choice: "b", hint: "Plants need light to make food. What happens without it?" },
      { step: 4, choice: "c", hint: "Snails are consumers. They can't make food for anyone." },
      { step: 4, choice: "d", hint: "Plants need light to make food. Without food, can a plant stay healthy?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The purple plant", machine: "Leaf Scanner", icon: "cells", speaker: "kai",
    line: "This Earth plant has dark purple leaves. It isn't green at all. So it must not need light, right?",
    question: "Does the purple plant need light to make food?",
    hint: "Green material in leaves catches light. Can other colors hide it?",
    meter: { heat: 10, label: "Leaf power +10%", story: "The purple plant moves to the sunny shelf" },
    discovery: { id: "purpleleaves", name: "Hidden green", who: "Nova", fact: "Red and purple leaves still have green chlorophyll inside. Other colors cover up the green, but the leaves still use sunlight to make food." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Yes. Its leaves still have green chlorophyll hidden under the purple, so they need light to make food." },
      { id: "b", text: "No. Only green plants need light." },
      { id: "c", text: "No. Purple plants get their food from the soil." },
      { id: "d", text: "No. Purple plants eat bugs instead." },
    ],
    rightFeedback: "The purple hides the green. The leaves still catch sunlight and make food.",
    wrong: [
      { choice: "b", hint: "Look closely. The purple plant has leaves and grows like other plants. Could the green be hidden?" },
      { choice: "c", hint: "Remember the debate. No plant eats soil. Where does a plant make its food?" },
      { choice: "d", hint: "A few plants trap bugs, but even they make food with light. Is the green hidden?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's tall-plant mistake", machine: "Test Bench", icon: "log", speaker: "kai",
    line: "I ran Nova's light test! On Day 7, the dark-cabinet plants were 4 cm TALLER. So I wrote: \"Plants don't need light!\" Then I kept watching...",
    question: "Part 1: On Day 21, how much taller is Tray L than Tray D? Part 2: What went wrong with Kai's conclusion? Part 3: Pick a better conclusion.",
    data: {
      title: "Kai's light test (bean plants)",
      columns: ["Day", "Tray L (sunny shelf)", "Tray D (dark cabinet)"],
      rows: [
        ["0", "2 cm, just sprouted", "2 cm, just sprouted"],
        ["7", "8 cm, green, sturdy", "12 cm, pale yellow, thin"],
        ["14", "14 cm, green, sturdy", "14 cm, pale, drooping"],
        ["21", "20 cm, green, sturdy", "14 cm, fallen over, dying"],
      ],
    },
    parts: [
      { type: "number", prompt: "On Day 21, how many cm taller is Tray L than Tray D?", unit: "cm" },
      { type: "choice", prompt: "What went wrong with Kai's conclusion?", choices: [
        { id: "a", text: "He looked only at height on Day 7. The dark plants were stretching, pale, and weak, using up food stored in the seed." },
        { id: "b", text: "He used a ruler." },
        { id: "c", text: "He should have looked only at Tray D." },
        { id: "d", text: "Nothing. Taller always means healthier." },
      ] },
      { type: "choice", prompt: "Pick a better conclusion.", choices: [
        { id: "a", text: "Bean plants need light to make food and stay healthy. Without light, they grew tall and pale for a while, then died." },
        { id: "b", text: "Plants grow best in the dark." },
        { id: "c", text: "Light and dark don't matter to plants." },
        { id: "d", text: "Plants only need light for the first week." },
      ] },
    ],
    hint: "Read every row and every note, not just one number. How do the plants look?",
    meter: { supplies: 1, label: "Test trays +1", story: "Kai rewrites his conclusion" },
    discovery: { id: "stretching", name: "Stretching for light", who: "Nova", fact: "Plants grown in the dark grow tall, thin, and pale yellow. They stretch upward searching for light until their stored food runs out." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 6 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Tall isn't the same as healthy. Careful scientists read all the data before they decide.",
    wrong: [
      { step: 1, value: 20, hint: "20 cm is Tray L's height. How much taller than Tray D is it?" },
      { step: 1, value: 34, hint: "You want the difference between the trays. Should you add or subtract?" },
      { step: 1, value: 4, hint: "4 cm was the difference on Day 7, and Tray D was ahead then. Look at the Day 21 row." },
      { step: 2, choice: "b", hint: "Measuring with a ruler is good science. What did Kai ignore in the notes?" },
      { step: 2, choice: "c", hint: "You need both trays to compare. What did Kai ignore about how the plants looked?" },
      { step: 2, choice: "d", hint: "Check the Day 21 row. The taller plants on Day 7 ended up dying." },
      { step: 3, choice: "b", hint: "Check Day 21. The dark plants fell over and were dying." },
      { step: 3, choice: "c", hint: "The two trays ended up very different. Light made the difference." },
      { step: 3, choice: "d", hint: "After the seed's stored food runs out, the plant still has to make food. What does that take?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Pick the best spot", machine: "Shelf Planner", icon: "grid", speaker: "vega",
    line: "The council gave us four new bean plants. Each one gets set up a different way for a week.",
    question: "Predict: which bean plant will be able to make the most food?",
    hint: "Which plant has all three things it needs: sunlight, water, and carbon dioxide from the air?",
    meter: { heat: 10, label: "Leaf power +10%", story: "The new beans are on the best shelf" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "A plant on the sunny shelf, watered, in open air" },
      { id: "b", text: "A plant in a dark cabinet, watered, in open air" },
      { id: "c", text: "A plant on the sunny shelf, never watered, in open air" },
      { id: "d", text: "A plant on the sunny shelf, watered, sealed in a small airtight box" },
    ],
    rightFeedback: "Sunlight, water, and fresh air with carbon dioxide. That plant has everything it needs to make food.",
    wrong: [
      { choice: "b", hint: "Remember Kai's dark tray. What does a plant need to catch in its leaves?" },
      { choice: "c", hint: "Water is one of the three things a plant needs to make food." },
      { choice: "d", hint: "Remember the sealed greenhouse. What ran out when no fresh air could get in?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Hours of light", machine: "Sun Lamp Timer", icon: "battery", speaker: "nova",
    line: "New test! Three bean plants get different hours of sun lamp light each day. Everything else is the same.",
    question: "Part 1: What is Nova changing on purpose? Part 2: What is she measuring? Part 3: Predict how tall Plant 4, with 14 hours of light, might grow.",
    data: {
      title: "Hours of light test (after 2 weeks)",
      columns: ["Plant", "Hours of light each day", "Height (cm)"],
      rows: [
        ["1", "2", "6"],
        ["2", "6", "11"],
        ["3", "10", "16"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What is Nova changing on purpose?", choices: [
        { id: "a", text: "The hours of light each day" },
        { id: "b", text: "The height of the plants" },
        { id: "c", text: "The kind of plant" },
        { id: "d", text: "The amount of water" },
      ] },
      { type: "choice", prompt: "What is Nova measuring?", choices: [
        { id: "a", text: "The height of each plant in centimeters" },
        { id: "b", text: "The hours of light" },
        { id: "c", text: "The size of the pots" },
        { id: "d", text: "The color of the lamp" },
      ] },
      { type: "choice", prompt: "Predict: how tall might Plant 4 grow with 14 hours of light?", choices: [
        { id: "a", text: "Taller than 16 cm" },
        { id: "b", text: "Shorter than 6 cm" },
        { id: "c", text: "Exactly 11 cm" },
        { id: "d", text: "0 cm, because more light stops growth" },
      ] },
    ],
    hint: "What does Nova set up differently for each plant? What does she write down at the end? Then look for a pattern.",
    meter: { supplies: 1, label: "Test trays +1", story: "The light timer test is logged" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Nova changes the light and measures the height. More light meant more food and more growth.",
    wrong: [
      { step: 1, choice: "b", hint: "Height is the result Nova writes down at the end. What does she set up differently?" },
      { step: 1, choice: "c", hint: "All three are bean plants. What's different in the table?" },
      { step: 1, choice: "d", hint: "Nova said everything else is the same, including water. What's different in the table?" },
      { step: 2, choice: "b", hint: "Nova chooses the hours of light. What does she measure at the end?" },
      { step: 2, choice: "c", hint: "The pots are all the same. What number does she record for each plant?" },
      { step: 2, choice: "d", hint: "The lamp is the same for all. What number does she record for each plant?" },
      { step: 3, choice: "b", hint: "Look at the pattern. More hours of light meant taller plants." },
      { step: 3, choice: "c", hint: "11 cm is Plant 2 with 6 hours. More light has meant taller plants each time." },
      { step: 3, choice: "d", hint: "The pattern shows more light, more growth. Would 14 hours stop it?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Proof for the council", machine: "Greenhouse Report", icon: "relay", speaker: "vega",
    line: "This is it! The garden council wants proof of how plants make food before they build a second greenhouse. Nova ran one last test with three bean plants.",
    question: "Part 1: How much taller is Plant A than Plant J on Day 14? Part 2: What does Plant J show? Part 3: Why did Plant C barely grow? Part 4: Write 2–3 sentences to the council explaining how plants make food. Use the data.",
    data: {
      title: "Final test (all plants started at 5 cm, sunny shelf)",
      columns: ["Plant", "Setup", "Day 14 height (cm)", "Notes"],
      rows: [
        ["A", "Watered, leaves uncovered", "17", "Green and strong"],
        ["J", "Watered, leaves coated with clear jelly", "8", "Leaves turning yellow"],
        ["C", "Not watered, leaves uncovered", "6", "Wilted and brown"],
      ],
    },
    parts: [
      { type: "number", prompt: "On Day 14, how many cm taller is Plant A than Plant J?", unit: "cm" },
      { type: "choice", prompt: "The jelly blocked the tiny holes in Plant J's leaves. What does Plant J show?", choices: [
        { id: "a", text: "Leaves need to take in carbon dioxide from the air to make food." },
        { id: "b", text: "Jelly is a kind of plant food." },
        { id: "c", text: "Plants don't need their leaves." },
        { id: "d", text: "Plants make food in the soil." },
      ] },
      { type: "choice", prompt: "Why did Plant C barely grow?", choices: [
        { id: "a", text: "Without water, it couldn't make food, even with sunlight and air." },
        { id: "b", text: "It got too much light." },
        { id: "c", text: "Its soil ran out of food." },
        { id: "d", text: "Its leaves were coated with jelly." },
      ] },
      { type: "write", prompt: "Explain to the council how plants make their own food. Use the data.", minWords: 20 },
    ],
    rubric: ["Names sunlight, water, and carbon dioxide as what plants use to make food", "Uses the test data as evidence (Plant A, J, or C)", "Mentions that plants give off oxygen, or that food is made in the leaves"],
    hint: "Compare each plant to Plant A. What was each one missing?",
    meter: { heat: 15, label: "Leaf power +15%", story: "The second greenhouse is approved" },
    discovery: { id: "foodchain", name: "It starts with plants", who: "Kai", fact: "Almost all food on Earth starts with producers. Bread comes from wheat, and even milk comes from cows that ate grass." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 9 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Proof delivered! Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 17, hint: "17 cm is Plant A's height. How much taller than Plant J is it?" },
      { step: 1, value: 25, hint: "You want the difference. Should you add or subtract?" },
      { step: 1, value: 12, hint: "12 cm is how much Plant A grew from 5 cm. Compare Plant A with Plant J on Day 14." },
      { step: 2, choice: "b", hint: "Plant J grew much less than Plant A. Did the jelly help or hurt?" },
      { step: 2, choice: "c", hint: "Plant J's leaves were blocked, and it did poorly. So are leaves important?" },
      { step: 2, choice: "d", hint: "The jelly was on the leaves, not the soil. What gas goes in through tiny holes in leaves?" },
      { step: 3, choice: "b", hint: "All three plants sat on the same sunny shelf. Check the Setup column for Plant C." },
      { step: 3, choice: "c", hint: "Plants don't get food from soil. Check the Setup column. What was Plant C missing?" },
      { step: 3, choice: "d", hint: "That was Plant J. Check the Setup column for Plant C." },
    ],
  },
};

export default {
  id: "SCI.4.12A-XP",
  standard: "SCI.4.12A-XP",
  engine: "expedition_station",
  title: "The Greenhouse Test",
  planet: "Lumara",
  outpost: "Crew Greenhouse · test season",
  grade: 4,
  subject: "Science",
  teks: "4.12A",
  supportingTeks: ["4.1B", "4.1E", "4.2B", "4.2C", "4.2D", "4.3A", "4.3B", "4.3C", "4.5B", "4.5E"],
  skillsChip: "4.12A · How plants make food",
  iCan: "I can investigate and explain how plants make their own food using sunlight, water, and carbon dioxide. I can explain how matter cycles between plants and animals.",
  blurb: "The glowing garden of Lumara wants a second greenhouse. First the crew has to prove how their Earth plants make their own food.",
  mission: "Run fair tests on the crew's Earth plants and prove how producers make food from sunlight, water, and carbon dioxide.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.12 · LUMARA CREW GREENHOUSE",
  playableActs: [1, 2, 3],
  earthTrue: "Lumara and its glowing garden are invented. The plants in the crew's greenhouse are real Earth plants, and every fact and data table is real Earth science.",
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Leaf power", heatUnit: "%", supplies: "Test trays", suppliesUnit: "trays" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. The garden council of Lumara wants to build a second greenhouse.",
    "But first they want proof. How do our Earth plants make their own food?",
    "Nova has test trays ready, and Kai has... ideas. Help us find the truth. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · What plants need", "Act 2 · Soil, seeds, and snails", "Act 3 · Proof for the council"],
    completes: [
      "You found out what plants need to make food, {firstName}!",
      "You solved the soil puzzle and the snail jar, {firstName}!",
      "You proved how plants make food, {firstName}! The second greenhouse is on the way.",
    ],
    teasers: [
      "Next on Lumara: Kai thinks plants eat dirt, and a jar holds a surprise. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: Kai's plants grew taller in the dark. Does that mean they don't need light? Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai has a new idea about soil, and I'm not so sure about it.",
      "Let's dig in.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The council meets soon.",
      "Help us finish the tests and write the proof.",
    ],
  }),
  tasks,
};
