// Expedition Station — The Greenhouse Floor (MA.3.6C-XP)
// Grade 3 · Math · Lumara. Main standard 3.6C (area of rectangles with whole
// number side lengths: rows × unit squares in each row); also practices 3.6D
// (composite figures made of rectangles, additive property of area) and 3.6E
// (equal-area parts as unit fractions; equal shares need not be the same
// shape). Grade 3 limits: side lengths up to 10, areas within 100.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Count the floor tiles", machine: "Floor Scanner", icon: "grid", speaker: "kai",
    line: "The new greenhouse has a bare floor. Each glow tile is a square, 1 meter on each side. I laid the first patch of tiles.",
    question: "Count the unit squares. What is the area of the tiled patch?",
    unit: "square meters",
    visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "3 m" }, title: "First tile patch" },
    hint: "Area is how many unit squares cover the inside. Count every tile, not just the ones on the edge.",
    meter: { heat: 10, label: "Floor tiled +10%", story: "The first tile patch is down" },
    discovery: { id: "greenhouseglass", name: "Greenhouses", who: "Nova", fact: "Greenhouse glass lets sunlight in and holds warmth inside. Plants can grow there even when it is cold outside." },
    answer: { kind: "number", value: 15 },
    rightFeedback: "15 unit squares cover the patch. Its area is 15 square meters!",
    wrong: [
      { value: 8, hint: "3 + 5 = 8. That adds two side lengths. Area counts ALL the squares inside the patch." },
      { value: 16, hint: "16 is the distance around the edge. That's perimeter. Area counts the squares that cover the inside." },
      { value: 12, hint: "It looks like you counted only the edge tiles. Don't forget the tiles in the middle!" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Rows times squares", machine: "Tile Layer", icon: "cells", speaker: "nova",
    line: "Counting one tile at a time is slow. This walkway has 4 rows of tiles, with 6 tiles in each row. There's a faster way to find the area.",
    question: "Part 1: What is a fast way to find the area? Part 2: What is the area of the walkway?",
    parts: [
      { type: "choice", prompt: "What is a fast way to find the area of 4 rows with 6 tiles in each row?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "4 m" }, title: "Walkway" },
        choices: [
          { id: "a", text: "Multiply the rows by the tiles in each row: 4 × 6." },
          { id: "b", text: "Add the rows and the tiles in a row: 4 + 6." },
          { id: "c", text: "Count only the tiles on the outside edge." },
          { id: "d", text: "Add 6 + 6, because the long sides are 6." },
        ] },
      { type: "number", prompt: "What is the area of the walkway?", unit: "square meters" },
    ],
    hint: "Each row has 6 tiles. There are 4 rows. Count by 6s four times: 6, 12, ...",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The walkway is tiled" },
    discovery: { id: "soillife", name: "Living soil", who: "Nova", fact: "One spoonful of healthy soil holds billions of tiny living things. They are far too small to see." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 24 }] },
    rightFeedback: "4 rows × 6 squares in each row = 24. The walkway is 24 square meters!",
    wrong: [
      { step: 1, choice: "b", hint: "4 + 6 adds the side lengths. Each of the 4 rows has 6 tiles, so we need 4 groups of 6." },
      { step: 1, choice: "c", hint: "The middle tiles are part of the floor too. Area covers the whole inside." },
      { step: 1, choice: "d", hint: "6 + 6 is only 2 rows. There are 4 rows of 6." },
      { step: 2, value: 10, hint: "4 + 6 = 10. There are 4 rows with 6 tiles in EACH row. Multiply." },
      { step: 2, value: 20, hint: "20 is the distance around the walkway. That's perimeter. How many squares cover it?" },
      { step: 2, value: 18, hint: "That's 3 rows of 6. Count all 4 rows." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Build the herb bed", machine: "Tile Layer", icon: "grid", speaker: "kai",
    line: "Next up is the herb bed. Commander Vega wants it 3 meters wide and 7 meters long.",
    question: "Build a bed with 3 rows of 7 tiles on the Tile Layer. What is the area of the herb bed?",
    unit: "square meters",
    visual: { type: "array", style: "tiles", maxRows: 8, maxCols: 10, rowWord: "rows", fills: "product", title: "Herb bed" },
    hint: "Make 3 rows. Put 7 squares in each row. Then multiply 3 × 7.",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The herb bed is laid out" },
    answer: { kind: "number", value: 21, build: { rows: 3, cols: 7 } },
    rightFeedback: "3 rows of 7 unit squares is 21. The herb bed is 21 square meters!",
    wrong: [
      { value: 10, hint: "3 + 7 = 10. That adds the sides. Area is 3 rows with 7 squares in each row." },
      { value: 20, hint: "20 is the distance around the bed. That's perimeter. Count the squares inside." },
      { value: 24, hint: "That's 3 rows of 8. Each row has 7 squares." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Label the sprout tray", machine: "Floor Scanner", icon: "dial", speaker: "nova",
    line: "The sprout tray floor is 2 rows of 9 tiles. Each tile is 1 meter on each side. I need to write its area on the label.",
    question: "Part 1: What is the area of the sprout tray? Part 2: Which label is right?",
    parts: [
      { type: "number", prompt: "What is the area of the sprout tray?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 2, cols: 9, perimeter: true, sideLabels: { top: "9 m", left: "2 m" }, title: "Sprout tray" } },
      { type: "choice", prompt: "Which label should Nova write?", choices: [
        { id: "a", text: "18 square meters" },
        { id: "b", text: "18 meters" },
        { id: "c", text: "11 square meters" },
        { id: "d", text: "22 meters" },
      ] },
    ],
    hint: "2 rows with 9 squares in each row. Area is counted in SQUARE units, because we count squares.",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The sprout tray is labeled" },
    discovery: { id: "earthworms", name: "Earthworms", who: "Kai", fact: "Earthworms dig tunnels in the soil. The tunnels let air and water reach plant roots." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 18 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "2 × 9 = 18 unit squares. The label says 18 square meters!",
    wrong: [
      { step: 1, value: 11, hint: "2 + 9 = 11. There are 2 rows with 9 squares in EACH row. Multiply." },
      { step: 1, value: 22, hint: "22 is the distance around the tray. That's perimeter. Count the squares inside." },
      { step: 2, choice: "b", hint: "Meters measure a length. We counted squares, so the unit is square meters." },
      { step: 2, choice: "c", hint: "11 comes from adding 2 + 9. The area is 2 rows of 9." },
      { step: 2, choice: "d", hint: "22 meters is the distance around the edge. The label needs the area." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The exact moonbean bed", machine: "Plot Planner", icon: "snap", speaker: "vega",
    line: "Surprise! A seed shipment of moonbeans just landed. They need a bed of exactly 36 square meters. The first bed must be 4 meters wide.",
    question: "Part 1: Build a bed with 4 rows and an area of 36. How many squares go in each row? Part 2: A second bed must also be 36 square meters, but with 6 rows. How many squares go in each row? Part 3: Compare the two beds.",
    parts: [
      { type: "number", prompt: "Build it: 4 rows, 36 square meters in all. How many squares are in each row?", unit: "squares",
        visual: { type: "array", style: "tiles", maxRows: 10, maxCols: 10, rowWord: "rows", fills: "cols", title: "Moonbean bed 1" } },
      { type: "number", prompt: "The second bed has 6 rows and is also 36 square meters. How many squares are in each row?", unit: "squares",
        visual: { type: "array", style: "tiles", maxRows: 10, maxCols: 10, rowWord: "rows", fills: "cols", title: "Moonbean bed 2" } },
      { type: "choice", prompt: "Bed 1 is 4 by 9. Bed 2 is 6 by 6. Which is true?", choices: [
        { id: "a", text: "They have the same area, 36 square meters, even though their shapes are different." },
        { id: "b", text: "Bed 1 has more area, because 9 is the longest side." },
        { id: "c", text: "Bed 2 has more area, because it has more rows." },
        { id: "d", text: "They can't both be 36, because they don't look the same." },
      ] },
    ],
    hint: "Think: 4 × ? = 36. Then think: 6 × ? = 36. Different rectangles can cover the same number of squares.",
    meter: { heat: 10, label: "Floor tiled +10%", story: "The moonbean beds are ready" },
    discovery: { id: "towardlight", name: "Reaching for light", who: "Nova", fact: "Plants slowly bend toward light. A plant on a windowsill will lean toward the window." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 9, build: { rows: 4, cols: 9 } }, { kind: "number", value: 6, build: { rows: 6, cols: 6 } }, { kind: "choice", correct: "a" }] },
    rightFeedback: "4 × 9 = 36 and 6 × 6 = 36. Two different beds, the same area!",
    wrong: [
      { step: 1, value: 32, hint: "36 − 4 = 32. We need 4 equal rows that make 36 squares. What times 4 makes 36?" },
      { step: 1, value: 8, hint: "4 rows of 8 is 32 squares. That's not enough. Try one more in each row." },
      { step: 1, value: 4, hint: "4 is the number of rows. How many squares go in EACH row?" },
      { step: 2, value: 30, hint: "36 − 6 = 30. We need 6 equal rows that make 36. What times 6 makes 36?" },
      { step: 2, value: 7, hint: "6 rows of 7 is 42 squares. That's too many. Try one less." },
      { step: 3, choice: "b", hint: "A longer side doesn't always mean more area. Count the squares: 4 × 9 and 6 × 6." },
      { step: 3, choice: "c", hint: "Bed 2 has more rows, but each row is shorter. Count the squares in each bed." },
      { step: 3, choice: "d", hint: "Shapes can look different and still cover the same number of squares." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The missing side", machine: "Plot Planner", icon: "trail", speaker: "nova",
    line: "The glowberry plot must be 42 square meters. It is 7 meters long. I forgot to write down how wide it is!",
    question: "Build a bed with 7 squares in each row and an area of 42. How many meters wide is the plot?",
    unit: "meters",
    visual: { type: "array", style: "tiles", maxRows: 10, maxCols: 10, rowWord: "rows", fills: "rows", title: "Glowberry plot" },
    hint: "Put 7 squares in each row. Add rows until you have 42 squares. Think: 7 × ? = 42.",
    meter: { supplies: 1, label: "Garden plots +1", story: "The glowberry plot is measured" },
    discovery: { id: "roots", name: "Roots", who: "Kai", fact: "Roots hold a plant in the ground. They soak up water from the soil for the whole plant." },
    answer: { kind: "number", value: 6, build: { rows: 6, cols: 7 } },
    rightFeedback: "6 rows of 7 is 42. The plot is 6 meters wide, because 6 × 7 = 42.",
    wrong: [
      { value: 35, hint: "42 − 7 = 35. We need to find how many rows of 7 make 42 squares." },
      { value: 7, hint: "7 meters is the length we already know. How many rows of 7 make 42?" },
      { value: 5, hint: "5 rows of 7 is only 35 squares. Add another row." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The adding-sides debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The fern bed is 5 meters by 4 meters. 5 + 4 = 9. So the area is 9 square meters. Easy!"',
    nova: 'Nova: "The area is 20 square meters. The bed has 5 rows of unit squares with 4 squares in each row, so 5 × 4 = 20."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Picture the bed covered in 1-meter squares. How many rows? How many squares in each row?",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The fern bed is measured the right way" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Area counts the unit squares that cover the bed. 5 rows of 4 squares is 5 × 4 = 20." },
      { id: "B", text: "Nova, because 20 is a bigger number." },
      { id: "C", text: "Kai. You find area by adding the side lengths." },
      { id: "D", text: "Kai. 9 is the answer, because the bed only has two sides." },
    ],
    writtenPrompt: "Tell Kai in your own words why the fern bed is 20 square meters, not 9.",
    debateHints: {
      wrongWho: "Draw 5 rows with 4 squares in each row. Are there only 9 squares?",
      wrongReason: "Right person, check the reason. What does area count?",
      right: "Nova is right. Area counts unit squares: 5 rows × 4 squares in each row = 20 square meters.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The long bed and the wide bed", machine: "Floor Scanner", icon: "cells", speaker: "kai",
    line: "I have two starleaf beds. Bed A is long and skinny: 3 by 8. Bed B is 4 by 6. The long one must have more room, right?",
    question: "Part 1: What is the area of Bed A? Part 2: What is the area of Bed B? Part 3: Which bed has more area?",
    parts: [
      { type: "number", prompt: "Bed A: 3 rows of 8 squares. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 8, perimeter: true, sideLabels: { top: "8 m", left: "3 m" }, title: "Bed A" } },
      { type: "number", prompt: "Bed B: 4 rows of 6 squares. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "4 m" }, title: "Bed B" } },
      { type: "choice", prompt: "Which bed has more area?", choices: [
        { id: "a", text: "Neither. They both have an area of 24 square meters." },
        { id: "b", text: "Bed A, because it is longer." },
        { id: "c", text: "Bed B, because it is wider." },
      ] },
    ],
    hint: "Multiply rows × squares in each row for each bed. Then compare the two areas.",
    meter: { supplies: 2, label: "Garden plots +2", story: "Both starleaf beds are measured" },
    discovery: { id: "butterflyfeet", name: "Butterfly feet", who: "Nova", fact: "Butterflies taste with their feet. They stand on a leaf to check if it is a good place to lay their eggs." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 24 }, { kind: "number", value: 24 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "3 × 8 = 24 and 4 × 6 = 24. Longer doesn't always mean more area!",
    wrong: [
      { step: 1, value: 11, hint: "3 + 8 = 11. There are 3 rows with 8 squares in EACH row. Multiply." },
      { step: 1, value: 22, hint: "22 is the distance around Bed A. That's perimeter. Count the squares inside." },
      { step: 2, value: 10, hint: "4 + 6 = 10. There are 4 rows with 6 squares in EACH row. Multiply." },
      { step: 2, value: 20, hint: "20 is the distance around Bed B. That's perimeter. Count the squares inside." },
      { step: 3, choice: "b", hint: "Bed A is longer, but it has fewer rows. Compare the two areas you found." },
      { step: 3, choice: "c", hint: "Bed B is wider, but its rows are shorter. Compare the two areas you found." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's border count", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote: "The seedling room floor is 5 rows of 6 tiles. I walked around the edge and counted 18 tiles. The area is 18 square meters." Something is off.',
    question: "Part 1: What went wrong? Part 2: What is the real area of the floor?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "5 m" }, title: "Seedling room floor" },
        choices: [
          { id: "a", text: "He only counted the tiles on the border. He missed the tiles in the middle." },
          { id: "b", text: "He should have added 5 + 6." },
          { id: "c", text: "He should have counted the long side twice." },
          { id: "d", text: "Nothing. 18 is right." },
        ] },
      { type: "number", prompt: "What is the real area of the seedling room floor?", unit: "square meters" },
    ],
    hint: "Area covers the whole floor, middle and all. Try 5 rows × 6 squares in each row.",
    meter: { supplies: 1, label: "Garden plots +1", story: "Kai's floor count is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 30 }] },
    rightFeedback: "Fixed! 5 rows × 6 squares = 30 square meters. The middle tiles count too.",
    wrong: [
      { step: 1, choice: "b", hint: "5 + 6 = 11. Adding the sides doesn't count the squares either." },
      { step: 1, choice: "c", hint: "Look at the floor. Are there tiles Kai didn't count at all?" },
      { step: 1, choice: "d", hint: "Look at the middle of the floor. Did Kai count those tiles?" },
      { step: 2, value: 18, hint: "18 is only the border tiles. Add the tiles in the middle, or multiply 5 × 6." },
      { step: 2, value: 11, hint: "5 + 6 = 11. There are 5 rows with 6 squares in EACH row." },
      { step: 2, value: 22, hint: "22 is the distance around the floor. That's perimeter. Count ALL the squares." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The L-shaped greenhouse", machine: "Floor Scanner", icon: "quake", speaker: "vega",
    line: "Surprise! A glow-vine grew so fast that we had to add a side room. Now the greenhouse floor is shaped like an L. It is a big rectangle, 5 by 6, plus a small rectangle, 2 by 4, stuck onto the side.",
    question: "Part 1: What is the area of the big rectangle? Part 2: What is the area of the small rectangle? Part 3: What is the area of the whole L-shaped floor?",
    parts: [
      { type: "number", prompt: "Big rectangle: 5 rows of 6 squares. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 5, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "5 m" }, title: "Big rectangle" } },
      { type: "number", prompt: "Small side room: 2 rows of 4 squares. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 2, cols: 4, perimeter: true, sideLabels: { top: "4 m", left: "2 m" }, title: "Side room" } },
      { type: "number", prompt: "The two rectangles don't overlap. What is the area of the whole L-shaped floor?", unit: "square meters" },
    ],
    hint: "Split the L into two rectangles that don't overlap. Find the area of each one. Then add the two areas.",
    meter: { heat: 10, label: "Floor tiled +10%", story: "The L-shaped floor is tiled" },
    discovery: { id: "cactus", name: "Cactus water", who: "Nova", fact: "A cactus stores water in its thick stem. It can live a long time without rain." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 30 }, { kind: "number", value: 8 }, { kind: "number", value: 38 }] },
    rightFeedback: "30 + 8 = 38. Split the L into rectangles, then add. The whole floor is 38 square meters!",
    wrong: [
      { step: 1, value: 11, hint: "5 + 6 = 11. There are 5 rows with 6 squares in EACH row. Multiply." },
      { step: 1, value: 22, hint: "22 is the distance around the big rectangle. That's perimeter. Count the squares inside." },
      { step: 2, value: 6, hint: "2 + 4 = 6. There are 2 rows with 4 squares in each row. Multiply." },
      { step: 2, value: 12, hint: "12 is the distance around the side room. That's perimeter. Count its squares." },
      { step: 3, value: 30, hint: "30 is only the big rectangle. Add the side room's area too." },
      { step: 3, value: 240, hint: "Don't multiply the two areas. Put the two parts together by adding: 30 + 8." },
      { step: 3, value: 36, hint: "Check your adding. 30 + 8 = ?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Sort the plot cards", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "The plot cards got mixed up. Each card shows how long and how wide a plot is. Vega wants plots of 24 square meters and plots of 36 square meters.",
    question: "Sort each plot card by its area.",
    hint: "Multiply the two side lengths to find each area. If it isn't 24 or 36, it goes in the last bin.",
    meter: { supplies: 1, label: "Garden plots +1", story: "Every plot card is sorted" },
    discovery: { id: "redwoods", name: "Tallest trees", who: "Nova", fact: "Coast redwood trees are the tallest trees on Earth. Some grow taller than 100 meters." },
    answer: { kind: "sort", bins: { p1: "a24", p2: "a24", p3: "a36", p4: "a36", p5: "other", p6: "other" } },
    rightFeedback: "Every plot card is in the right bin! 4 × 6 and 3 × 8 make 24. 6 × 6 and 4 × 9 make 36.",
    sort: {
      bins: [
        { id: "a24", label: "24 square meters" },
        { id: "a36", label: "36 square meters" },
        { id: "other", label: "Some other area" },
      ],
      items: [
        { id: "p1", label: "4 m by 6 m" },
        { id: "p2", label: "3 m by 8 m" },
        { id: "p3", label: "6 m by 6 m" },
        { id: "p4", label: "4 m by 9 m" },
        { id: "p5", label: "5 m by 5 m" },
        { id: "p6", label: "5 m by 7 m" },
      ],
    },
    wrong: [
      { item: "p1", hint: "4 rows of 6 squares. 4 × 6 = 24." },
      { item: "p2", hint: "3 rows of 8 squares. 3 × 8 = 24, even though it looks long and skinny." },
      { item: "p3", hint: "6 rows of 6 squares. 6 × 6 = 36." },
      { item: "p4", hint: "4 rows of 9 squares. 4 × 9 = 36." },
      { item: "p5", hint: "5 × 5 = 25. That's not 24 or 36." },
      { item: "p6", hint: "5 + 7 = 12, just like 6 + 6. But area multiplies: 5 × 7 = 35, not 36." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The mystery bench", machine: "Numberless", icon: "water", speaker: "nova",
    line: "I'm covering the top of a potting bench with square tiles. The bench top is a rectangle. Every row has the same number of tiles, and there are no gaps.",
    question: "Part 1: Pick the questions we could answer with this story. Part 2: Now the numbers show up. Solve it.",
    parts: [
      { type: "multi", prompt: "Which questions could we answer once we know the numbers?", choices: [
        { id: "area", text: "What is the area of the bench top?" },
        { id: "tiles", text: "How many tiles does Nova need?" },
        { id: "color", text: "What color are the tiles?" },
        { id: "plants", text: "How tall are the plants on the bench?" },
      ] },
      { type: "number", prompt: "The bench top has 7 rows with 8 tiles in each row. Build it. What is the area of the bench top?", unit: "square units",
        visual: { type: "array", style: "tiles", maxRows: 10, maxCols: 10, rowWord: "rows", fills: "product", title: "Potting bench top" } },
    ],
    hint: "The bench top is covered in rows of unit squares. Multiply the rows by the squares in each row.",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The potting bench is tiled" },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["area", "tiles"] }, { kind: "number", value: 56, build: { rows: 7, cols: 8 } }] },
    rightFeedback: "7 rows × 8 squares = 56. The bench top is 56 square units, so Nova needs 56 tiles!",
    wrong: [
      { step: 1, pick: "color", hint: "The story tells us about rows of tiles, not colors. Can we answer that?" },
      { step: 1, pick: "plants", hint: "The story doesn't tell us anything about the plants. Pick questions about the tiles." },
      { step: 1, missing: true, hint: "Two questions can be answered. Each tile covers one square unit, so tiles and area match." },
      { step: 2, value: 15, hint: "7 + 8 = 15. There are 7 rows with 8 tiles in EACH row. Multiply." },
      { step: 2, value: 30, hint: "30 is the distance around the bench top. That's perimeter. Count the squares inside." },
      { step: 2, value: 54, hint: "Close! Count by 8s seven times: 8, 16, 24, ... Check your last jump." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Two ways to share", machine: "Plot Planner", icon: "grid", speaker: "nova",
    line: "Kai and I each have a square bed, 4 by 4. The beds are exactly the same. Kai cut his bed into 4 long strips. I cut mine into 4 small squares, each 2 by 2.",
    question: "Part 1: What is the area of each part? Part 2: What fraction of a bed is each part? Part 3: Are a strip and a small square equal shares?",
    parts: [
      { type: "number", prompt: "Each bed is 16 square meters, cut into 4 equal parts. What is the area of each part?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 4, perimeter: true, sideLabels: { top: "4 m", left: "4 m" }, title: "One 4 by 4 bed" } },
      { type: "choice", prompt: "What fraction of the whole bed is each part?", choices: [
        { id: "a", text: "1/4 of the bed" },
        { id: "b", text: "1/2 of the bed" },
        { id: "c", text: "1/16 of the bed" },
        { id: "d", text: "4/1 of the bed" },
      ] },
      { type: "choice", prompt: "Kai's strip is 1 by 4. Nova's square is 2 by 2. Are they equal shares?", choices: [
        { id: "a", text: "Yes. They look different, but both have an area of 4 square meters, so each is 1/4 of the same-size bed." },
        { id: "b", text: "No. Equal shares must be the same shape." },
        { id: "c", text: "No. The strip is longer, so it is bigger." },
        { id: "d", text: "No. The square is fatter, so it is bigger." },
      ] },
    ],
    hint: "Count the squares in one strip (1 row of 4). Then count the squares in one small square (2 rows of 2).",
    meter: { heat: 5, label: "Floor tiled +5%", story: "The beds are shared fairly" },
    discovery: { id: "compost", name: "Compost", who: "Kai", fact: "Compost is made from old leaves and food scraps. Tiny living things break them down into rich food for soil." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 4 }, { kind: "choice", correct: "a" }, { kind: "choice", correct: "a" }] },
    rightFeedback: "Each part is 4 square meters, or 1/4 of the bed. Equal shares can be different shapes!",
    wrong: [
      { step: 1, value: 12, hint: "16 − 4 = 12. We are cutting 16 into 4 equal parts. What times 4 makes 16?" },
      { step: 1, value: 8, hint: "8 square meters would be half of the bed. We cut it into 4 equal parts." },
      { step: 2, choice: "b", hint: "There are 4 equal parts, not 2. Each part is one of 4." },
      { step: 2, choice: "c", hint: "16 is the number of squares. The bed was cut into 4 equal parts." },
      { step: 2, choice: "d", hint: "One part out of 4 equal parts is written 1 over 4." },
      { step: 3, choice: "b", hint: "Count the squares in each. Equal shares need the same area, not the same shape." },
      { step: 3, choice: "c", hint: "The strip is longer but thinner. Count its squares: 1 × 4." },
      { step: 3, choice: "d", hint: "The small square is wider but shorter. Count its squares: 2 × 2." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Four fair plots", machine: "Plot Planner", icon: "dial", speaker: "kai",
    line: "The sunpetal bed is 4 meters by 6 meters. All four of us want our own plot. Every plot has to have the same area.",
    question: "Part 1: Pick every cut that makes 4 plots with equal areas. Part 2: What is the area of each plot?",
    parts: [
      { type: "multi", prompt: "Which cuts make 4 plots that each have the same area?",
        visual: { type: "array", mode: "show", style: "tiles", rows: 4, cols: 6, perimeter: true, sideLabels: { top: "6 m", left: "4 m" }, title: "Sunpetal bed" },
        choices: [
          { id: "rows", text: "Cut it into 4 rows. Each plot is 1 m by 6 m." },
          { id: "blocks", text: "Cut it into 4 blocks. Each plot is 2 m by 3 m." },
          { id: "mixed", text: "Cut it into two plots that are 2 m by 4 m and two plots that are 2 m by 2 m." },
          { id: "sixths", text: "Cut it into 6 columns. Each plot is 4 m by 1 m." },
          { id: "big", text: "Cut off one big plot that is 3 m by 6 m and split the rest into 3 tiny plots." },
        ] },
      { type: "number", prompt: "The bed is 24 square meters, cut into 4 equal plots. What is the area of each plot?", unit: "square meters" },
    ],
    hint: "Find the area of each plot in a cut. The cut works only if there are 4 plots and they all have the same area.",
    meter: { heat: 5, label: "Floor tiled +5%", story: "Everyone has a fair plot" },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["rows", "blocks"] }, { kind: "number", value: 6 }] },
    rightFeedback: "1 × 6 = 6 and 2 × 3 = 6. Both cuts make 4 plots of 6 square meters. Each plot is 1/4 of the bed!",
    wrong: [
      { step: 1, pick: "mixed", hint: "2 by 4 is 8 square meters, but 2 by 2 is only 4. Those plots aren't equal." },
      { step: 1, pick: "sixths", hint: "That makes 6 plots, not 4. Each one would be 1/6 of the bed." },
      { step: 1, pick: "big", hint: "3 by 6 is 18 square meters. That plot is way bigger than the others." },
      { step: 1, missing: true, hint: "Two cuts work. Plots can be different shapes and still have the same area." },
      { step: 2, value: 20, hint: "24 − 4 = 20. We are sharing 24 into 4 equal plots. What times 4 makes 24?" },
      { step: 2, value: 4, hint: "4 is the number of plots. How many square meters does EACH plot get?" },
      { step: 2, value: 8, hint: "4 plots of 8 is 32. That's more than the whole bed. Try a smaller number." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Glow-night floor check", machine: "Floor Scanner", icon: "relay", speaker: "vega",
    line: "This is it! The greenhouse lights up tonight. The main hall floor is an L: the top part is 3 rows of 8 squares, and a 3 by 3 part hangs down under the left side. Kai and Nova split it two different ways. Surprise! They must match.",
    question: "Part 1: Way 1, top piece plus bottom piece. What is the whole area? Part 2: Way 2, what is the area of the tall left piece? Part 3: Way 2, what is the whole area? Part 4: Why do both ways match?",
    parts: [
      { type: "number", prompt: "Way 1 (Kai): top piece is 3 by 8. Bottom piece is 3 by 3. Add them. What is the area of the whole L?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 8, perimeter: true, sideLabels: { top: "8 m", left: "3 m" }, title: "Way 1 · top piece (bottom piece is 3 by 3)" } },
      { type: "number", prompt: "Way 2 (Nova): cut straight down instead. The tall left piece is 6 rows of 3 squares. What is its area?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 6, cols: 3, perimeter: true, sideLabels: { top: "3 m", left: "6 m" }, title: "Way 2 · tall left piece" } },
      { type: "number", prompt: "The right piece left over is 3 by 5. Add it to the tall left piece. What is the area of the whole L?", unit: "square meters",
        visual: { type: "array", mode: "show", style: "tiles", rows: 3, cols: 5, perimeter: true, sideLabels: { top: "5 m", left: "3 m" }, title: "Way 2 · right piece" } },
      { type: "choice", prompt: "Why did both ways give the same area?", choices: [
        { id: "a", text: "Both ways cover the same floor with no overlaps and no gaps, so the total squares stay the same." },
        { id: "b", text: "It was luck. Different cuts usually give different areas." },
        { id: "c", text: "Because both ways used a 3 by 3 piece." },
        { id: "d", text: "Because Kai and Nova both added 8 + 3." },
      ] },
    ],
    hint: "Find each piece's area with rows × squares in each row. Then add the pieces. The floor didn't change, only the cut did.",
    meter: { heat: 15, label: "Floor tiled +15%", story: "The greenhouse glows on Lumara" },
    discovery: { id: "stomata", name: "Leaf pores", who: "Nova", fact: "Leaves have tiny holes called stomata. Air goes in and water vapor comes out through them." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 33 }, { kind: "number", value: 18 }, { kind: "number", value: 33 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "24 + 9 = 33, and 18 + 15 = 33. Two ways to split, the same area. The greenhouse is ready to glow!",
    wrong: [
      { step: 1, value: 24, hint: "24 is only the top piece. Add the 3 by 3 bottom piece too." },
      { step: 1, value: 48, hint: "48 would be a full 6 by 8 rectangle. The L has a missing corner. Add just the two pieces: 24 + 9." },
      { step: 1, value: 17, hint: "Don't add the side lengths. Find each area first: 3 × 8 and 3 × 3." },
      { step: 2, value: 9, hint: "6 + 3 = 9. There are 6 rows with 3 squares in EACH row. Multiply." },
      { step: 2, value: 21, hint: "Close! Count by 3s six times: 3, 6, 9, ... Check your last jump." },
      { step: 3, value: 15, hint: "15 is only the right piece. Add the tall left piece too." },
      { step: 3, value: 34, hint: "Check your adding. 18 + 15 = ?" },
      { step: 4, choice: "b", hint: "It isn't luck. Did the floor itself change, or only the cut?" },
      { step: 4, choice: "c", hint: "Way 2 didn't use a 3 by 3 piece. Think about what both ways cover." },
      { step: 4, choice: "d", hint: "Adding sides doesn't find area. Think about the squares that cover the floor." },
    ],
  },
};

export default {
  id: "MA.3.6C-XP",
  standard: "MA.3.6C-XP",
  engine: "expedition_station",
  title: "The Greenhouse Floor",
  planet: "Lumara",
  outpost: "Glow Garden · greenhouse build",
  grade: 3,
  subject: "Math",
  teks: "3.6C",
  supportingTeks: ["3.6D", "3.6E"],
  skillsChip: "3.6C · Find the area of rectangles",
  iCan: "I can find the area of a rectangle by multiplying the number of rows by the number of unit squares in each row, split L-shapes into rectangles, and share a shape into equal-area parts.",
  blurb: "The crew is building a new greenhouse in the glowing garden on Lumara. They have to tile the floor with square meters and plan fair garden plots before glow night.",
  mission: "Tile the greenhouse floor, plan the garden plots, and get the greenhouse glowing for glow night.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.6C · LUMARA GREENHOUSE",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Floor tiled", heatUnit: "%", supplies: "Garden plots", suppliesUnit: "plots" },
  journalMax: 10,
  grade3Limits: "Whole-number side lengths up to 10. Areas within 100 square units.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're building a new greenhouse on Lumara.",
    "The floor has to be covered with square glow tiles, and every garden plot needs the right area.",
    "Help Kai and Nova tile the floor and plan the plots. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Lay the first tiles", "Act 2 · Plan the garden plots", "Act 3 · Glow night"],
    completes: [
      "The first tiles are down, {firstName}!",
      "The plots are planned and the L-shaped floor is tiled, {firstName}!",
      "The greenhouse is glowing, {firstName}! Lumara's new garden is ready.",
    ],
    teasers: [
      "Next on Lumara: time to plan the garden plots. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: glow night is almost here. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The first tiles are down, so now we plan the garden plots.",
      "Kai keeps mixing up how to find area, so let's check his work together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Glow night is coming.",
      "Help the crew share the last beds fairly and check the big floor so the greenhouse can glow.",
    ],
  }),
  tasks,
};
