// Expedition Station — The Lava Lock (MA.4.3C-XP)
// Grade 4 · Math · Cindara. Main standard 4.3C (equivalent fractions);
// also practices 4.3D (compare fractions with different numerators and
// denominators) and 4.3G (fractions as distances on a number line).
import { CREW, acts, lockLater } from "./_shared.js";

const tasks = lockLater({
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Match the coolant tanks", machine: "Fill", icon: "tank", speaker: "kai",
    line: "Coolant Tank A shows 2/5. Tank B is the same size, but its gauge is marked in tenths. The lava lock needs both tanks at the same level.",
    question: "Fill Tank B to match Tank A. Set the gauge, then press Pour.",
    hint: "Each fifth is split into 2 tenths. How many tenths make 2 fifths?",
    meter: { heat: 15, label: "Cooling +15%", story: "The lava lock stops steaming" },
    answer: { kind: "frac", n: 4, d: 10 },
    rightFeedback: "Matched! 2/5 and 4/10 are the same amount.",
    wrong: [
      { n: 2, d: 10, hint: "2/10 is only 1 fifth. Each fifth is 2 tenths." },
      { n: 5, d: 10, hint: "5/10 is half the tank. Is 2/5 half?" },
    ],
    fill: { denom: 10, start: 0, match: { n: 2, d: 5, label: "Tank A" } },
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The coolant debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "3/4 is the same as 4/5. I just added 1 to the top and 1 to the bottom!"',
    nova: 'Nova: "Adding changes the size of the pieces. 3/4 is the same as 6/8, because I multiplied the top and bottom by 2."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Draw 3/4 and 4/5 on two same-size bars. Do they cover the same amount?",
    meter: { heat: 10, label: "Cooling +10%", story: "The right coolant mix goes into the lock" },
    discovery: { id: "lavaheat", name: "Lava", who: "Nova", fact: "Lava can be hotter than 1,000°C (about 1,800°F)." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Multiplying the top and bottom by the same number splits every piece the same way, so the amount stays the same. Adding doesn't." },
      { id: "B", text: "Nova, because 6/8 has bigger numbers." },
      { id: "C", text: "Kai. If you add the same number to the top and bottom, the fraction stays the same." },
      { id: "D", text: "Kai. 3/4 and 4/5 are both one piece away from a whole, so they're equal." },
    ],
    writtenPrompt: "Tell Kai in your own words why 3/4 is not the same as 4/5.",
    debateHints: {
      wrongWho: "Draw both on same-size bars. 3/4 is 1/4 away from a whole. 4/5 is 1/5 away. Are those gaps the same size?",
      wrongReason: "Right person, check the reason. What do you do to the top and bottom to make an equal fraction?",
      right: "Nova is right — multiply the top and bottom by the same number.",
    },
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Tune the heat sensor", machine: "Tune", icon: "dial", speaker: "kai",
    line: "The heat sensor reads 2/3 on a dial marked in thirds. Our control dial is marked in twelfths. Set it to the same spot so the sensors agree.",
    question: "What spot in twelfths matches 2/3? Turn the dial, then press Lock signal.",
    hint: "Each third is split into 4 twelfths. How many twelfths make 2 thirds?",
    meter: { heat: 10, label: "Cooling +10%", story: "The heat sensors agree" },
    discovery: { id: "pumice", name: "Pumice", who: "Kai", fact: "Pumice is a volcanic rock so full of air bubbles that it can float on water." },
    answer: { kind: "frac", n: 8, d: 12 },
    rightFeedback: "Locked! 2/3 and 8/12 are the same spot.",
    wrong: [
      { n: 2, d: 12, hint: "You changed only the bottom number. Each third is 4 twelfths." },
      { n: 6, d: 12, hint: "6/12 is half. 2/3 is more than half." },
    ],
    tune: { denom: 12, mode: "point", start: { n: 0, d: 12 } },
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Fill the cooling pipe", machine: "Fill", icon: "scoop", speaker: "nova",
    line: "The cooling pipe has to be filled to 3/4. Its gauge is marked in eighths. Our scoops hold 1/8 or 2/8.",
    question: "How many eighths is 3/4? Then fill the pipe with scoops two different ways.",
    missingPrompt: "How many eighths is the same as 3/4?",
    hint: "Each fourth is 2 eighths. How many eighths make 3 fourths?",
    meter: { supplies: 2, label: "Crystals +2", story: "Cooling crystals form in the pipe" },
    discovery: { id: "obsidian", name: "Obsidian", who: "Nova", fact: "Obsidian is volcanic glass. It forms when lava cools very quickly." },
    answer: { kind: "scoops", missing: { n: 6, d: 8 }, target: { n: 6, d: 8 }, start: { n: 0, d: 8 }, scoopSizes: [1, 2], waysNeeded: 2 },
    rightFeedback: "Two ways to 6/8, which is the same as 3/4!",
    wrong: [
      { n: 3, d: 8, hint: "You changed only the bottom number. Each fourth is 2 eighths." },
      { n: 4, d: 8, hint: "4/8 is half. 3/4 is more than half." },
    ],
    fill: { denom: 8, start: 0, target: 6 },
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The lava rises", machine: "Fill", icon: "snap", speaker: "vega",
    line: "Surprise, the lava is rising! The coolant tank shows 3/4. The lock is only safe when the coolant is at 5/6 or higher. The gauge is marked in twelfths.",
    question: "Step 1: Write the coolant level (3/4) in twelfths. Step 2: How many twelfths below the safe line (5/6) is the coolant?",
    stepPrompts: ["Step 1: What is the coolant level (3/4) in twelfths?", "Step 2: How many twelfths below the 5/6 safe line is the coolant?"],
    stepButtons: ["Check level", "Check gap"],
    hint: "Write both fractions in twelfths. Then count the twelfths between them.",
    meter: { heat: 10, label: "Cooling +10%", story: "The crew tops off the coolant just in time" },
    discovery: { id: "hotspot", name: "Hot spots", who: "Nova", fact: "Some volcanoes, like the ones in Hawaii, form over hot spots deep inside the Earth." },
    answer: { kind: "steps", steps: [{ n: 9, d: 12 }, { n: 1, d: 12 }] },
    rightFeedback: "The coolant is 9/12, just 1/12 below the 10/12 safe line. Kai tops it off!",
    wrong: [
      { step: 1, n: 3, d: 12, hint: "You changed only the bottom number. Each fourth is 3 twelfths." },
      { step: 1, n: 10, d: 12, hint: "10/12 is the safe line (5/6). What is 3/4 in twelfths?" },
      { step: 2, n: 2, d: 12, hint: "Write 5/6 in twelfths first. Each sixth is 2 twelfths." },
      { step: 2, n: 10, d: 12, hint: "That's where the safe line is. How far below it is the coolant?" },
    ],
    fill: { denom: 12, start: 0, safe: 10 },
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Track the lava flow", machine: "Travel", icon: "trail", speaker: "nova",
    line: "The lava flow has moved 3/5 of a kilometer down the slope. Our map track is marked in tenths of a kilometer.",
    question: "Mark how far the lava has moved on the track in tenths.",
    hint: "Each fifth of a kilometer is 2 tenths.",
    meter: { heat: 5, label: "Cooling +5%", story: "The crew knows where to put the barrier" },
    discovery: { id: "geyser", name: "Geysers", who: "Kai", fact: "Hot springs and geysers get their heat from hot rock deep underground." },
    answer: { kind: "frac", n: 6, d: 10 },
    rightFeedback: "3/5 km is the same as 6/10 km.",
    wrong: [
      { n: 3, d: 10, hint: "You changed only the bottom number. Each fifth is 2 tenths." },
      { n: 5, d: 10, hint: "5/10 is half a kilometer. 3/5 is a little farther." },
    ],
    travel: { denom: 10, max: 1, mode: "point", label: "km" },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Check Kai's gauge log", machine: "Repair", icon: "log", speaker: "nova",
    line: "Kai wrote: \"The vent gauge reads 5/6. On the new gauge in twelfths, that's 10/6, because I doubled the top number.\" That doesn't look right.",
    question: "Tap the part of Kai's log that is wrong. Pick what went wrong, then write the right fraction in twelfths.",
    hint: "To go from sixths to twelfths, what happens to every piece?",
    meter: { supplies: 1, label: "Crystals +1", story: "The vent gauge is set right" },
    answer: { kind: "mistake", tap: "frac", error: "A", fix: { n: 10, d: 12 } },
    rightFeedback: "Fixed! 5/6 is the same as 10/12.",
    repair: {
      log: [
        { id: "start", text: "The vent gauge reads 5/6." },
        { id: "frac", text: "In twelfths, that's 10/6," },
        { id: "why", text: "because I doubled the top number." },
      ],
      errors: [
        { id: "A", text: "He doubled only the top. To keep the same amount, double the top AND the bottom." },
        { id: "B", text: "5/6 can't be written in twelfths." },
        { id: "C", text: "He should have added 6 to the top." },
      ],
    },
    wrong: [
      { error: "B", hint: "Each sixth can be split into 2 twelfths, so 5/6 can be written in twelfths." },
      { error: "C", hint: "Adding changes the amount. Look at what Kai did to the bottom number." },
      { n: 10, d: 6, hint: "That's Kai's answer. 10/6 is more than a whole gauge." },
      { n: 5, d: 12, hint: "You changed only the bottom number. Each sixth is 2 twelfths." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Tile the heat shield", machine: "Fill", icon: "grid", speaker: "kai",
    line: "The heat shield grid has 12 equal squares. 2/3 of it needs ceramic tiles.",
    question: "How many twelfths is 2/3? Shade the grid, then press Check.",
    hint: "Split the grid into 3 equal groups. How many squares are in 2 groups?",
    meter: { heat: 5, label: "Cooling +5%", story: "The control room stays cool" },
    discovery: { id: "ash", name: "Volcanic ash", who: "Nova", fact: "Volcanic ash can travel thousands of kilometers on the wind." },
    answer: { kind: "frac", n: 8, d: 12 },
    rightFeedback: "8 of 12 squares is the same as 2/3!",
    wrong: [
      { n: 2, d: 12, hint: "Split the grid into 3 equal groups first. How many squares in 2 groups?" },
      { n: 6, d: 12, hint: "6/12 is half the grid. 2/3 is more than half." },
    ],
    fill: { denom: 12, grid: { rows: 3, cols: 4 }, start: 0, shade: true },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The vent check", machine: "Numberless", icon: "trail", speaker: "nova",
    line: "Kai and I each walked part of the same trail to check the steam vents.",
    question: "First, pick the questions we could answer with this story. Then the numbers will show up.",
    hint: "Write both distances in tenths. Then compare.",
    meter: { supplies: 1, label: "Crystals +1", story: "Every vent is checked" },
    answer: { kind: "numberless", sensible: ["farther", "howmuch"], missing: { n: 1, d: 10 } },
    rightFeedback: "Nova walked 7/10 km and Kai walked 6/10 km, so Nova walked 1/10 km farther.",
    numberless: {
      questions: [
        { id: "farther", text: "Who walked farther?" },
        { id: "howmuch", text: "How much farther did one of them walk?" },
        { id: "boots", text: "What color are their boots?" },
        { id: "time", text: "What time did they start?" },
      ],
      reveal: "Kai walked 3/5 km. Nova walked 7/10 km.",
      ask: "How much farther did Nova walk than Kai?",
      denom: 10,
    },
    wrong: [
      { step: "questions", hint: "Can the story tell us that? Pick only questions about how far they walked." },
      { n: 4, d: 10, hint: "Write Kai's 3/5 in tenths first. Each fifth is 2 tenths." },
      { n: 7, d: 10, hint: "That's how far Nova walked. How much FARTHER than Kai?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The cracked bridges", machine: "Travel", icon: "quake", speaker: "vega",
    line: "Surprise, a lava quake! Three rock bridges cross the lava river. Cracks have spread 5/6, 3/4, and 7/12 of the way across. The crew must cross the bridge with the least cracking.",
    question: "Step 1: Write 5/6 in twelfths. Step 2: Write 3/4 in twelfths. Step 3: Which bridge has the least cracking? Enter its fraction.",
    hint: "Write every fraction in twelfths. Then compare.",
    meter: { heat: 5, label: "Cooling +5%", story: "The crew crosses safely" },
    discovery: { id: "newland", name: "New land", who: "Nova", fact: "New land forms when lava cools and hardens. Hawaii's Big Island is still growing." },
    answer: { kind: "steps", steps: [{ n: 10, d: 12 }, { n: 9, d: 12 }, { n: 7, d: 12 }] },
    rightFeedback: "10/12, 9/12, and 7/12 — the 7/12 bridge is safest!",
    wrong: [
      { step: 1, n: 5, d: 12, hint: "You changed only the bottom number. Each sixth is 2 twelfths." },
      { step: 2, n: 3, d: 12, hint: "You changed only the bottom number. Each fourth is 3 twelfths." },
      { step: 3, n: 5, d: 6, hint: "5/6 is 10/12, the MOST cracked. Which is the least?" },
      { step: 3, n: 3, d: 4, hint: "3/4 is 9/12. Is there a smaller one?" },
    ],
    travel: { denom: 12, max: 1, mode: "point", tracks: [{ who: "bridge A", mark: { n: 5, d: 6 } }, { who: "bridge B", mark: { n: 3, d: 4 } }, { who: "bridge C", mark: { n: 7, d: 12 } }], label: "of the way across" },
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Sort the crystal cards", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "Each crystal card shows a fraction. Sort each card into the bin with the fraction it's equal to.",
    question: "Sort each card into the right bin.",
    hint: "Multiply or divide the top and bottom by the same number to find an equal fraction.",
    meter: { supplies: 1, label: "Crystals +1", story: "The crystals are sorted for the lock" },
    discovery: { id: "basalt", name: "Basalt", who: "Nova", fact: "Basalt is the most common volcanic rock on Earth." },
    answer: { kind: "sort", bins: { k1: "half", k2: "half", k3: "twothirds", k4: "twothirds", k5: "threefifths", k6: "none" } },
    rightFeedback: "Every crystal card is in the right bin!",
    sort: {
      bins: [
        { id: "half", label: "Equal to 1/2" },
        { id: "twothirds", label: "Equal to 2/3" },
        { id: "threefifths", label: "Equal to 3/5" },
        { id: "none", label: "Not equal to any of these" },
      ],
      items: [
        { id: "k1", label: "5/10" },
        { id: "k2", label: "6/12" },
        { id: "k3", label: "4/6" },
        { id: "k4", label: "8/12" },
        { id: "k5", label: "6/10" },
        { id: "k6", label: "4/5" },
      ],
    },
    wrong: [
      { item: "k6", hint: "Is 4/5 equal to 1/2, 2/3, or 3/5? Try writing each in tenths or fifteenths." },
      { item: "k5", hint: "Divide the top and bottom of 6/10 by 2." },
      { item: "k4", hint: "Divide the top and bottom of 8/12 by 4." },
      { item: "k2", hint: "6 is half of 12." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The nearly-full debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Tank A is 7/8 full and Tank B is 9/10 full. Tank A has more, because eighths are bigger pieces than tenths."',
    nova: 'Nova: "Look at how far each is from full. Tank A is 1/8 away from full. Tank B is only 1/10 away. Tank B is closer to full, so it has more."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Which tank has the smaller empty space at the top?",
    meter: { heat: 5, label: "Cooling +5%", story: "The fuller tank goes to the lock" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 7/8 is missing 1/8 and 9/10 is missing 1/10. 1/10 is smaller, so 9/10 is closer to full and is greater." },
      { id: "B", text: "Nova, because 9 and 10 are bigger numbers than 7 and 8." },
      { id: "C", text: "Kai. Eighths are bigger pieces, so 7/8 is always more." },
      { id: "D", text: "Kai. The fraction with the smaller bottom number is always bigger." },
    ],
    writtenPrompt: "Tell Kai in your own words how Nova compared the tanks.",
    debateHints: {
      wrongWho: "Picture both tanks. Which one has the smaller empty space at the top?",
      wrongReason: "Right person, check the reason. How did Nova use the distance from full?",
      right: "Nova is right — 9/10 is closer to full than 7/8.",
    },
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Set the lock dial", machine: "Tune", icon: "dial", speaker: "nova",
    line: "The lava lock opens at 3/4. The lock dial is marked in twelfths.",
    question: "What spot in twelfths is the same as 3/4? Set the dial, then press Lock signal.",
    hint: "Each fourth is 3 twelfths.",
    meter: { heat: 10, label: "Cooling +10%", story: "The lock dial is set" },
    discovery: { id: "volcanologist", name: "Volcanologists", who: "Kai", fact: "Scientists who study volcanoes are called volcanologists." },
    answer: { kind: "frac", n: 9, d: 12 },
    rightFeedback: "9/12 is the same as 3/4. The lock is ready!",
    wrong: [
      { n: 3, d: 12, hint: "You changed only the bottom number. Each fourth is 3 twelfths." },
      { n: 8, d: 12, hint: "8/12 is the same as 2/3. 3/4 is a little more." },
    ],
    tune: { denom: 12, mode: "point", start: { n: 0, d: 12 } },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Top off the lock tank", machine: "Fill", icon: "battery", speaker: "kai",
    line: "The lock tank is at 7/12. It needs to reach 5/6 before the lock can seal. The gauge is marked in twelfths.",
    question: "How many twelfths do we need to add? Set the gauge, then press Pour.",
    hint: "Write 5/6 in twelfths first. Then count up from 7/12.",
    meter: { supplies: 1, label: "Crystals +1", story: "The lock tank is full" },
    answer: { kind: "frac", n: 3, d: 12 },
    rightFeedback: "5/6 is 10/12, so we add 3/12. The tank is ready!",
    wrong: [
      { n: 2, d: 12, hint: "Write 5/6 in twelfths first. Each sixth is 2 twelfths." },
      { n: 10, d: 12, hint: "That's where the tank needs to reach. How much do we ADD from 7/12?" },
    ],
    fill: { denom: 12, start: 7, target: 10 },
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Seal the lava lock", machine: "Fill", icon: "relay", speaker: "vega",
    line: "This is it! Three coolant cells are 1/2, 2/3, and 3/4 full. The lock seals when the fullest cell goes in first. The gauge is marked in twelfths.",
    question: "Step 1: Write 1/2 in twelfths. Step 2: Write 2/3 in twelfths. Step 3: Which cell is fullest? Enter its amount in twelfths.",
    hint: "Write every cell in twelfths. Then compare.",
    meter: { heat: 10, label: "Cooling +10%", story: "The lava lock is sealed" },
    discovery: { id: "soil", name: "Volcanic soil", who: "Nova", fact: "Volcanic soil is often full of nutrients, so many farms grow near volcanoes." },
    answer: { kind: "steps", steps: [{ n: 6, d: 12 }, { n: 8, d: 12 }, { n: 9, d: 12 }] },
    rightFeedback: "6/12, 8/12, 9/12 — the 3/4 cell goes in first, and the lava lock is sealed!",
    wrong: [
      { step: 1, n: 1, d: 12, hint: "Half of 12 equal parts is how many parts?" },
      { step: 2, n: 2, d: 12, hint: "You changed only the bottom number. Each third is 4 twelfths." },
      { step: 3, n: 8, d: 12, hint: "8/12 is 2/3. What is 3/4 in twelfths?" },
      { step: 3, n: 6, d: 12, hint: "6/12 is the smallest. Which is the fullest?" },
    ],
    fill: { denom: 12, cells: [{ n: 1, d: 2 }, { n: 2, d: 3 }, { n: 3, d: 4 }] },
  },
});

export default {
  id: "MA.4.3C-XP",
  standard: "MA.4.3C-XP",
  engine: "expedition_station",
  title: "The Lava Lock",
  planet: "Cindara",
  outpost: "Lava Lock Station · 900°C",
  grade: 4,
  subject: "Math",
  teks: "4.3C",
  supportingTeks: ["4.3D", "4.3G"],
  skillsChip: "4.3C · Equivalent fractions",
  iCan: "I can tell if two fractions are equal by using a number line or by multiplying the top and bottom by the same number. I can compare fractions with different tops and bottoms.",
  blurb: "On Cindara, a giant stone gate called the lava lock holds back a river of lava. It's overheating, and every gauge at the station is marked a different way.",
  mission: "Match the coolant levels and seal the lava lock.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.33 · CINDARA LAVA LOCK",
  playableActs: [1],
  meterStart: { heat: 35, supplies: 0, journal: 0 },
  meterLabels: { heat: "Cooling", heatUnit: "%", supplies: "Crystals", suppliesUnit: "crystals" },
  journalMax: 10,
  opening: [
    "Specialist {name}, this is Commander Vega. The lava lock on Cindara is overheating.",
    "The coolant tanks and sensors there are all marked differently, so the readings don't agree.",
    "Help Kai and Nova match the fractions, and keep that lava where it belongs. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Cool the lava lock", "Act 2 · Track the lava flow", "Act 3 · Seal the lock"],
    completes: [
      "The lava lock is cooling down, {firstName}!",
      "The crew made it across the lava river, {firstName}!",
      "The lava lock is sealed, {firstName}! Cindara is safe.",
    ],
    teasers: [
      "Next on Cindara: a lava flow is heading down the slope. Act 2 opens on your next station visit.",
      "Next on Cindara: it's time to seal the lock for good. Act 3 opens on your next station visit.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. A lava flow is moving down the slope, and Kai's gauge log has a mistake in it.",
      "Let's track the flow and fix the readings.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The crew is at the lava lock.",
      "Help them sort the cooling crystals and seal the lock for good.",
    ],
  }),
  tasks,
};
