// Expedition Station — The Light Lab (SCI.5.8C-XP)
// Grade 5 · Science · Lumara. Main standard 5.8C (2024 TEKS): demonstrate
// that light travels in a straight line until it strikes an object and is
// reflected, refracted, or absorbed (plus passing through transparent
// materials). Supporting practices: 5.1A (ask questions, define problems),
// 5.1B (plan investigations, design solutions), 5.1G (models), 5.2B (analyze
// data), 5.2D (evaluate designs), 5.3A (explanations), 5.3C (respectful
// scientific discussion).
//
// Earth-true rule: every mirror, lens, prism, and material behaves exactly as
// it does on Earth. Only the planet and crew are invented.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Bounce, bend, or soak", machine: "Light Sorter", icon: "cells", speaker: "nova",
    line: "The garden's light lab is waking up. Every beam here does one of three things when it hits something.",
    question: "Sort each light event: is the light reflected, refracted, or absorbed?",
    hint: "Reflect means bounce. Refract means bend as it goes into something new. Absorb means soak in, often as warmth.",
    meter: { heat: 10, label: "Beam path +10%", story: "The light sorter hums on" },
    answer: { kind: "sort", bins: { r1: "reflect", r2: "refract", r3: "absorb", r4: "reflect", r5: "refract", r6: "absorb" } },
    rightFeedback: "Mirrors and foil bounce light. Water and lenses bend it. Dark things soak it up.",
    sort: {
      bins: [{ id: "reflect", label: "Reflected (bounces)" }, { id: "refract", label: "Refracted (bends)" }, { id: "absorb", label: "Absorbed (soaks in)" }],
      items: [
        { id: "r1", label: "Lamp light bounces off a mirror onto the wall" },
        { id: "r2", label: "Light changes direction as it enters a bowl of water" },
        { id: "r3", label: "Sunlight warms a black stone" },
        { id: "r4", label: "Shiny foil sends a spot of light onto the ceiling" },
        { id: "r5", label: "Light bends as it passes through a hand lens" },
        { id: "r6", label: "Dark soil gets warm in the sun" },
      ],
    },
    wrong: [
      { item: "r4", hint: "The light didn't go into the foil. It came back off it. Bounce, bend, or soak?" },
      { item: "r6", hint: "The soil got warm. Where did the light's energy go?" },
      { item: "r5", hint: "Light goes through the lens and comes out going a new direction. That's bending." },
      { item: "r2", hint: "The light goes into the water and changes direction. Is that bouncing or bending?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Three cards in a row", machine: "Beam Bench", icon: "trail", speaker: "kai",
    line: "I lined up three cards, each with a small hole in the middle. The flashlight beam goes through all three and makes a dot on the wall. Now I'm sliding the middle card 2 cm to the side.",
    question: "What happens to the dot on the wall? Why?",
    hint: "Can light curve to find a hole that's out of line?",
    meter: { heat: 5, label: "Beam path +5%", story: "Kai lines the cards back up" },
    discovery: { id: "pinholecamera", name: "Pinhole cameras", who: "Nova", fact: "A pinhole camera is a dark box with a tiny hole. Light travels straight through the hole and makes an upside-down picture on the back wall." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The dot disappears. Light travels in a straight line, so it hits the middle card instead of curving to the hole." },
      { id: "b", text: "The dot stays. The light bends around to find the hole." },
      { id: "c", text: "The dot gets brighter, because the card moved out of the way." },
      { id: "d", text: "The dot stays, because light goes right through cards." },
    ],
    rightFeedback: "The dot vanishes. Light only makes it through when all three holes are in a straight line.",
    wrong: [
      { choice: "b", hint: "Light doesn't hunt for holes. It keeps going straight until it hits something." },
      { choice: "c", hint: "Only the hole moved, not the whole card. What's in the beam's straight path now?" },
      { choice: "d", hint: "A card is opaque. If light went through cards, why would you need holes?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The window test", machine: "Light Sorter", icon: "scan", speaker: "vega",
    line: "We're building new windows for the seedling hut. First we need to know how much light each material lets through.",
    question: "Sort each material: transparent, translucent, or opaque?",
    hint: "Transparent: you see clearly through it. Translucent: some light gets through, but things look blurry. Opaque: no light gets through.",
    meter: { supplies: 1, label: "Test cards +1", story: "The window samples are labeled" },
    answer: { kind: "sort", bins: { w1: "transparent", w2: "translucent", w3: "opaque", w4: "transparent", w5: "translucent", w6: "opaque" } },
    rightFeedback: "Clear glass and plastic wrap are transparent. Waxed paper and frosted glass are translucent. Wood and metal are opaque.",
    sort: {
      bins: [{ id: "transparent", label: "Transparent" }, { id: "translucent", label: "Translucent" }, { id: "opaque", label: "Opaque" }],
      items: [
        { id: "w1", label: "Clear glass pane" },
        { id: "w2", label: "Waxed paper" },
        { id: "w3", label: "Wooden board" },
        { id: "w4", label: "Clear plastic wrap" },
        { id: "w5", label: "Frosted glass" },
        { id: "w6", label: "Metal pan" },
      ],
    },
    wrong: [
      { item: "w5", hint: "Frosted glass lets light in, but can you see clearly through it?" },
      { item: "w2", hint: "Hold waxed paper up to a lamp. Some light glows through, but the lamp looks fuzzy." },
      { item: "w6", hint: "Does any light get through a metal pan at all?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The pot's shadow", machine: "Beam Bench", icon: "grid", speaker: "nova",
    line: "I set a clay flower pot between the lamp and the lab wall. A dark shape showed up on the wall.",
    question: "Why is there a shadow on the wall behind the pot?",
    hint: "Think about the path from the lamp to the wall, and what's in the way.",
    meter: { heat: 5, label: "Beam path +5%", story: "Nova traces the shadow" },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "The pot gives off darkness onto the wall." },
      { id: "b", text: "The light bends around the pot and misses that spot." },
      { id: "c", text: "Light travels in straight lines. The opaque pot blocks the light, so it can't reach that part of the wall." },
      { id: "d", text: "The wall soaks up the light only in that spot." },
    ],
    rightFeedback: "A shadow is just a place the light can't reach, because something opaque is in its straight path.",
    wrong: [
      { choice: "a", hint: "Darkness isn't something that shines. A shadow is where something is missing. What's missing?" },
      { choice: "b", hint: "If light bent around the pot, it would fill in the shadow. Does it?" },
      { choice: "d", hint: "Move the pot away and the dark spot is gone. So the wall isn't causing it. What is?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The lamps blink out", machine: "Beam Bench", icon: "quake", speaker: "vega",
    line: "Surprise, the garden's night lamps are blinking out one by one! Before the last lamp goes, we need to understand how we see and how shadows form.",
    question: "Part 1: Put the light's path in order so Nova can see a white garden stone. Part 2: Pick the objects that will cast a dark shadow. Part 3: If the last lamp goes out completely, can Nova still see the white stone?",
    parts: [
      { type: "order", prompt: "Put the light's path in order.", items: [
        { id: "eye", text: "The bounced light enters Nova's eyes" },
        { id: "bounce", text: "The stone reflects some of the light" },
        { id: "lamp", text: "Light leaves the lamp" },
        { id: "travel", text: "Light travels in a straight line to the stone" },
      ] },
      { type: "multi", prompt: "Pick every object that will cast a dark shadow.", choices: [
        { id: "pot", text: "Clay pot" },
        { id: "can", text: "Metal watering can" },
        { id: "jar", text: "Clear glass jar" },
        { id: "bag", text: "Clear plastic bag" },
      ] },
      { type: "choice", prompt: "The last lamp goes out, and the room is totally dark. Can Nova see the white stone?", choices: [
        { id: "a", text: "No. With no light to reflect off the stone, no light reaches her eyes." },
        { id: "b", text: "Yes. White things glow on their own." },
        { id: "c", text: "Yes. Her eyes send out light to see it." },
      ] },
    ],
    hint: "We see an object when light bounces off it and travels into our eyes.",
    meter: { heat: 10, label: "Beam path +10%", story: "Kai rewires the last lamp" },
    discovery: { id: "catseyeshine", name: "Glowing cat eyes", who: "Nova", fact: "Cats' eyes seem to glow at night because a shiny layer at the back of each eye reflects light. The eyes don't make any light of their own." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["lamp", "travel", "bounce", "eye"] },
      { kind: "multi", correct: ["pot", "can"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Light from the lamp bounces off the stone into Nova's eyes. No light, no seeing!",
    wrong: [
      { step: 1, position: 0, hint: "Where does the light start?" },
      { step: 1, position: 1, hint: "The light has to get to the stone before it can bounce off it." },
      { step: 1, position: 2, hint: "What does the stone do when the light hits it?" },
      { step: 2, pick: "jar", hint: "Clear glass is transparent. Most of the light passes right through it." },
      { step: 2, pick: "bag", hint: "A clear bag is transparent. The light goes through, so the shadow is barely there." },
      { step: 2, missing: true, hint: "There are two opaque objects." },
      { step: 3, choice: "b", hint: "White things reflect a lot of light, but they don't make light. What happens with no lamp?" },
      { step: 3, choice: "c", hint: "Eyes take light in. They don't send it out. Where would the light come from?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Flashlight eyes?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "We see things because our eyes send out beams, like little flashlights."',
    nova: 'Nova: "No, light from a lamp or the Sun bounces off things and travels into our eyes."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Remember what happened when the last lamp went out.",
    meter: { heat: 5, label: "Beam path +5%", story: "Kai puts away his flashlight-eyes idea" },
    discovery: { id: "ibnalhaytham", name: "Ibn al-Haytham", who: "Nova", fact: "About 1,000 years ago, a scientist named Ibn al-Haytham did experiments showing that we see when light travels from objects into our eyes, not out of our eyes." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. In a totally dark room, you can't see anything, even with your eyes open. If eyes sent out light, you could still see." },
      { id: "B", text: "Nova, because eyes are round." },
      { id: "C", text: "Kai. You have to open your eyes to see, so the light must come out of them." },
      { id: "D", text: "Kai. Cats' eyes glow, so eyes make light." },
    ],
    writtenPrompt: "Tell Kai in your own words how light helps us see.",
    debateHints: {
      wrongWho: "Picture a room with no light at all. Can you see anything with your eyes open?",
      wrongReason: "Right person, check the reason. What does a dark room prove?",
      right: "Nova is right — light travels into our eyes, not out of them.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The broken pencil", machine: "Water Tank", icon: "water", speaker: "kai",
    line: "I put a pencil in a glass of water, and it looks broken right at the water line! Did the water snap it?",
    question: "Why does the pencil look broken?",
    hint: "What happens to light when it goes from water into air?",
    meter: { supplies: 1, label: "Test cards +1", story: "Kai pulls out a perfectly good pencil" },
    discovery: { id: "archerfish", name: "Archerfish", who: "Nova", fact: "Archerfish shoot jets of water to knock bugs off leaves above the water. They hit their target even though light bends where the water meets the air." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "The water really bent the pencil." },
      { id: "b", text: "Light from the part under water refracts (bends) when it leaves the water and goes into the air, so that part looks shifted." },
      { id: "c", text: "The water absorbs the bottom of the pencil." },
      { id: "d", text: "The glass reflects the pencil back to itself." },
    ],
    rightFeedback: "The pencil is fine. The light bends at the water line, so our eyes see the bottom part in the wrong spot.",
    wrong: [
      { choice: "a", hint: "Pull the pencil out. Is it bent?" },
      { choice: "c", hint: "You can still see the bottom of the pencil, so the light isn't soaked up. It changed direction." },
      { choice: "d", hint: "The glass is transparent, so light goes through it. What happens at the line where water meets air?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The color fan", machine: "Prism Stand", icon: "split", speaker: "nova",
    line: "I shined a thin beam of white lamp light into a glass prism. A fan of colors came out the other side!",
    question: "Part 1: What did the prism do to the light? Part 2: Put these colors in order, starting with the one that bends the least.",
    parts: [
      { type: "choice", prompt: "What did the prism do to the light?", choices: [
        { id: "a", text: "It refracted the white light. Each color bent a different amount, so the colors spread apart." },
        { id: "b", text: "It painted colors onto the light." },
        { id: "c", text: "It absorbed the white light and made new light." },
        { id: "d", text: "It reflected the light straight back to the lamp." },
      ] },
      { type: "order", prompt: "Put the colors in order, starting with the one that bends the least.", items: [
        { id: "green", text: "Green" },
        { id: "violet", text: "Violet" },
        { id: "orange", text: "Orange" },
        { id: "blue", text: "Blue" },
        { id: "red", text: "Red" },
        { id: "yellow", text: "Yellow" },
      ] },
    ],
    hint: "Red bends the least and violet bends the most. The colors come out in the same order every time.",
    meter: { heat: 10, label: "Beam path +10%", story: "The lab wall glows with color" },
    discovery: { id: "diamondsparkle", name: "Diamond sparkle", who: "Kai", fact: "Diamonds flash with tiny colors because they bend light even more strongly than glass or water does." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["red", "orange", "yellow", "green", "blue", "violet"] },
    ] },
    rightFeedback: "The prism bent the light, and the colors fanned out from red to violet.",
    wrong: [
      { step: 1, choice: "b", hint: "The prism is clear glass. The colors were already in the white light. What did the glass do to them?" },
      { step: 1, choice: "c", hint: "The light goes through the prism and comes out. It wasn't soaked up." },
      { step: 1, choice: "d", hint: "The colors came out the other side, so the light went through the prism." },
      { step: 2, position: 0, hint: "Start with red. It bends the least." },
      { step: 2, position: 1, hint: "After red comes orange, then yellow. Think of a rainbow." },
      { step: 2, position: 3, hint: "Green sits in the middle, between yellow and blue." },
      { step: 2, position: 5, hint: "Violet bends the most, so it goes last." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Warm beds for seeds", machine: "Sun Patch", icon: "tank", speaker: "vega",
    line: "The fire-bean seeds need warm soil to sprout. We'll cover their beds with whatever soaks up the most light.",
    question: "Pick every material that will absorb the most light and warm up the seed beds.",
    items: [
      { id: "black", text: "Black rubber mat" },
      { id: "soil", text: "Dark brown soil" },
      { id: "white", text: "White sheet" },
      { id: "foil", text: "Aluminum foil" },
      { id: "mirror", text: "Mirror tile" },
    ],
    hint: "Dark, dull things absorb more light. Light, shiny things reflect more.",
    meter: { supplies: 1, label: "Test cards +1", story: "The seed beds warm up" },
    discovery: { id: "glowtoys", name: "Glow-in-the-dark toys", who: "Nova", fact: "Glow-in-the-dark toys soak up light energy. Then they give it off slowly, so they keep glowing for a while after the lights go out." },
    answer: { kind: "multi", correct: ["black", "soil"] },
    rightFeedback: "The black mat and dark soil soak up light and turn it into warmth.",
    wrong: [
      { pick: "white", hint: "White reflects most of the light that hits it. Will it warm up much?" },
      { pick: "foil", hint: "Shiny foil bounces light away. It stays cooler." },
      { pick: "mirror", hint: "A mirror reflects almost all the light. Does that warm the soil?" },
      { missing: true, hint: "There's one more dark material." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The cloth cover test", machine: "Sun Patch", icon: "log", speaker: "vega",
    line: "Surprise, the moss nursery is overheating! We need a cover that stays cool under the grow lamps. Nova put a black cloth and a white cloth, the same size, under the same lamp, at the same distance, and checked a thermometer under each one.",
    question: "Part 1: How many degrees did the black cloth warm up in 10 minutes? Part 2: What does the data show? Part 3: Pick two things that had to stay the same for a fair test. Part 4: Predict a gray cloth's temperature at 10 minutes.",
    data: {
      title: "Temperature under each cloth (°C)",
      columns: ["Minutes under the lamp", "Black cloth", "White cloth"],
      rows: [
        ["0", "22", "22"],
        ["5", "29", "24"],
        ["10", "34", "26"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many degrees did the black cloth warm up from 0 to 10 minutes?", unit: "°C" },
      { type: "choice", prompt: "What does the data show?", choices: [
        { id: "a", text: "The black cloth absorbed more light and warmed more. The white cloth reflected more light and stayed cooler." },
        { id: "b", text: "The white cloth absorbed more light." },
        { id: "c", text: "Both cloths warmed the same amount." },
        { id: "d", text: "The black cloth made its own heat." },
      ] },
      { type: "multi", prompt: "Pick two things that had to stay the same.", choices: [
        { id: "distance", text: "How far each cloth was from the lamp" },
        { id: "size", text: "The size of each cloth" },
        { id: "color", text: "The color of each cloth" },
        { id: "day", text: "The day of the week" },
      ] },
      { type: "choice", prompt: "Nova tests a gray cloth the same way. What will it most likely read at 10 minutes?", choices: [
        { id: "a", text: "About 30°C" },
        { id: "b", text: "About 38°C" },
        { id: "c", text: "About 22°C" },
      ] },
    ],
    hint: "Subtract the start temperature from the end temperature. Then compare the two columns.",
    meter: { heat: 10, label: "Beam path +10%", story: "The moss nursery gets white covers" },
    discovery: { id: "coolroofs", name: "Cool roofs", who: "Kai", fact: "Some buildings have white or light-colored roofs. They reflect more sunlight, so the building stays cooler inside on hot days." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 12 },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["distance", "size"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Black warmed 12°C and white only 4°C. White covers will keep the moss cool!",
    wrong: [
      { step: 1, value: 34, hint: "34°C is the temperature at the end. How much did it go up from the start?" },
      { step: 1, value: 4, hint: "4 degrees is how much the white cloth warmed. Check the black cloth column." },
      { step: 1, value: 56, hint: "Should you add or subtract to find how much it warmed?" },
      { step: 2, choice: "b", hint: "Which column has the bigger numbers at 10 minutes?" },
      { step: 2, choice: "c", hint: "Black went up 12 degrees and white went up 4. Is that the same?" },
      { step: 2, choice: "d", hint: "At 0 minutes, both cloths were 22°C. The warmth came from the lamp's light." },
      { step: 3, pick: "color", hint: "Color is the thing Nova changed on purpose. What had to stay the same?" },
      { step: 3, pick: "day", hint: "The day of the week can't change the temperatures. What could?" },
      { step: 4, choice: "b", hint: "Would gray absorb more light than black? Look at the black cloth's reading." },
      { step: 4, choice: "c", hint: "22°C is the starting temperature. Gray absorbs some light, so it will warm up some." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The mirror bounce", machine: "Mirror Rig", icon: "relay", speaker: "kai",
    line: "I'm aiming a flashlight at a flat mirror. The beam comes in slanting down from the left side.",
    question: "Which way will the beam go after it hits the mirror?",
    hint: "A mirror bounces light off at the same slant it came in, just on the other side.",
    meter: { heat: 10, label: "Beam path +10%", story: "Kai's beam hits the target" },
    discovery: { id: "ambulancemirror", name: "Mirror writing", who: "Nova", fact: "Some ambulances have their name printed backward on the front. In a car's rearview mirror, drivers see the word the right way around." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Straight through the mirror and out the back" },
      { id: "b", text: "It stops at the mirror and disappears" },
      { id: "c", text: "Up and away to the right, at the same slant it came in" },
      { id: "d", text: "Along the mirror's surface, curving around the edge" },
    ],
    rightFeedback: "The beam bounces off to the right at the same slant. That's reflection.",
    wrong: [
      { choice: "a", hint: "A mirror has a shiny coat on the back. Does light pass through it?" },
      { choice: "b", hint: "A mirror reflects almost all the light that hits it. Where does it go?" },
      { choice: "d", hint: "Light travels in straight lines. It bounces off. It doesn't slide along the mirror." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's sun shade", machine: "Repair Bench", icon: "brief", speaker: "kai",
    line: "The night-bloom flowers need full shade all day. I built them a sun shade out of clear plastic wrap, but they're still getting blasted with sunlight!",
    question: "Part 1: What went wrong? Part 2: What should Kai use instead?",
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "Clear plastic wrap is transparent, so most of the light passes right through it." },
        { id: "b", text: "Plastic wrap reflects extra light onto the flowers." },
        { id: "c", text: "The sunlight bent around the edges of the shade." },
        { id: "d", text: "Plastic wrap makes its own light." },
      ] },
      { type: "choice", prompt: "What should Kai use instead?", choices: [
        { id: "board", text: "A wooden board" },
        { id: "glass", text: "A clear glass pane" },
        { id: "wax", text: "A sheet of waxed paper" },
        { id: "wrap", text: "Two layers of clear plastic wrap" },
      ] },
    ],
    hint: "Look back at your window test. Which kind of material blocks all the light?",
    meter: { supplies: 1, label: "Test cards +1", story: "The night-blooms rest in the shade" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "choice", correct: "board" }] },
    rightFeedback: "An opaque board blocks the light, so the flowers finally get real shade.",
    wrong: [
      { step: 1, choice: "b", hint: "Can you see through plastic wrap? What does that tell you about the light?" },
      { step: 1, choice: "c", hint: "The flowers are in bright light right under the shade, not just at the edges. What is the light going through?" },
      { step: 1, choice: "d", hint: "Plastic wrap doesn't make light. The light comes from the Sun. How is it getting through?" },
      { step: 2, choice: "glass", hint: "Clear glass is transparent too. The light would pour right through." },
      { step: 2, choice: "wax", hint: "Waxed paper is translucent. It still lets some light through." },
      { step: 2, choice: "wrap", hint: "Two clear layers are still clear. Which material is opaque?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The beetle lens", machine: "Lens Stand", icon: "scan", speaker: "nova",
    line: "I'm looking at a tiny glow beetle through a hand lens. It looks three times bigger!",
    question: "What is the hand lens doing to the light?",
    hint: "A hand lens is clear, curved glass. Does light go through it, bounce off it, or soak into it?",
    meter: { heat: 5, label: "Beam path +5%", story: "Nova sketches the beetle's legs" },
    discovery: { id: "lighthouselens", name: "Lighthouse lenses", who: "Kai", fact: "Many lighthouses use a special glass lens invented by Augustin-Jean Fresnel in the 1820s. It bends the lamp's light into a strong beam that ships can see from far away." },
    answer: { kind: "choice", correct: "d" },
    choices: [
      { id: "a", text: "Reflecting the light back to the beetle" },
      { id: "b", text: "Absorbing the light and making it warmer" },
      { id: "c", text: "Blocking the light so the beetle looks darker and bigger" },
      { id: "d", text: "Refracting (bending) the light that passes through it, so the beetle looks bigger" },
    ],
    rightFeedback: "The curved glass bends the light, and the beetle looks bigger to Nova's eyes.",
    wrong: [
      { choice: "a", hint: "Nova sees the beetle through the lens, so the light goes through it. What happens to light going through curved glass?" },
      { choice: "b", hint: "The lens is clear. It lets light pass through instead of soaking it up." },
      { choice: "c", hint: "A clear lens doesn't block light. If it did, Nova couldn't see through it." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The dark pond", machine: "Mirror Rig", icon: "water", speaker: "kai",
    line: "The mirror pond shines so bright in the daytime. I bet it makes its own light. Let's use it as a night lamp!",
    question: "Will the mirror pond light up the garden on a night with no moon and no lamps? Why?",
    hint: "Where does the pond's bright light come from in the daytime?",
    meter: { heat: 5, label: "Beam path +5%", story: "Kai builds a real night lamp instead" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Yes. Mirrors store up sunlight and let it out at night." },
      { id: "b", text: "No. A mirror only reflects light that hits it. With no light coming in, nothing bounces out." },
      { id: "c", text: "Yes. Water always glows at night." },
      { id: "d", text: "No, because mirrors absorb all the light that hits them." },
    ],
    rightFeedback: "A mirror doesn't make light. It only bounces back the light that hits it.",
    wrong: [
      { choice: "a", hint: "Take a mirror into a dark closet. Does it shine?" },
      { choice: "c", hint: "Plain water doesn't make light. Where did the daytime shine come from?" },
      { choice: "d", hint: "Right answer, wrong reason. Mirrors bounce back almost all the light that hits them. Why is there nothing to bounce at night?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Around the garden wall", machine: "Mirror Rig", icon: "relay", speaker: "vega",
    line: "This is it! The rare sunseed sprouts are behind a tall garden wall, and they need light. Our lamp beam starts out heading east. It must turn north to get past the wall, then turn west to land on the sprouts.",
    question: "Part 1: How many flat mirrors do you need to turn the beam twice? Part 2: Which material should the turning pieces be made of? Part 3: Put the beam's path in order. Part 4: Explain your design to Commander Vega.",
    parts: [
      { type: "number", prompt: "How many flat mirrors do you need?", unit: "mirrors" },
      { type: "choice", prompt: "Which material should the turning pieces be made of?", choices: [
        { id: "mirror", text: "Mirror" },
        { id: "glass", text: "Clear glass" },
        { id: "felt", text: "Black felt" },
        { id: "wax", text: "Waxed paper" },
      ] },
      { type: "order", prompt: "Put the beam's path in order.", items: [
        { id: "m2", text: "The beam hits mirror 2 and turns west" },
        { id: "sprouts", text: "The beam lands on the sunseed sprouts" },
        { id: "lamp", text: "The beam leaves the lamp heading east" },
        { id: "m1", text: "The beam hits mirror 1 and turns north" },
      ] },
      { type: "write", prompt: "Explain your design to Commander Vega. Tell how the light travels and what the mirrors do.", minWords: 15 },
    ],
    rubric: ["States the number of mirrors and the material", "Explains that light travels in straight lines between mirrors", "Explains that mirrors reflect the beam to change its direction"],
    hint: "Light only travels in straight lines. Each mirror can turn the beam one time.",
    meter: { heat: 10, label: "Beam path +10%", story: "The sunseed sprouts glow with light" },
    discovery: { id: "periscope", name: "Periscopes", who: "Kai", fact: "A periscope is a tube with a mirror at each end. Submarine crews use periscopes to see above the water while the submarine stays hidden below." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 2 },
      { kind: "choice", correct: "mirror" },
      { kind: "order", correct: ["lamp", "m1", "m2", "sprouts"] },
      { kind: "write", minWords: 15 },
    ] },
    rightFeedback: "Two mirrors bounce the beam around the wall. Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 1, hint: "One mirror turns the beam once. The beam needs to turn north AND then west." },
      { step: 1, value: 3, hint: "Count the turns: east to north, then north to west. One mirror for each turn." },
      { step: 1, value: 0, hint: "Light can't curve around a wall on its own. What will turn it?" },
      { step: 2, choice: "glass", hint: "Clear glass is transparent. The beam would go straight through instead of turning." },
      { step: 2, choice: "felt", hint: "Black felt absorbs light. The beam would stop there." },
      { step: 2, choice: "wax", hint: "Waxed paper is translucent. It spreads a little light through instead of turning the beam." },
      { step: 3, position: 0, hint: "Where does the beam start?" },
      { step: 3, position: 1, hint: "The beam heads east first. Which mirror turns it north?" },
      { step: 3, position: 2, hint: "After the beam heads north, which mirror turns it west?" },
    ],
  },
};

export default {
  id: "SCI.5.8C-XP",
  standard: "SCI.5.8C-XP",
  engine: "expedition_station",
  title: "The Light Lab",
  planet: "Lumara",
  outpost: "Glow Garden · the light lab",
  grade: 5,
  subject: "Science",
  teks: "5.8C",
  supportingTeks: ["5.1A", "5.1B", "5.1G", "5.2B", "5.2D", "5.3A", "5.3C"],
  skillsChip: "5.8C · How light travels",
  iCan: "I can show that light travels in a straight line until it hits something, and then it is reflected, refracted, absorbed, or passes through.",
  blurb: "Lumara's glowing garden has a light lab full of mirrors, lenses, prisms, and water tanks. The crew needs to understand real light to keep the garden growing.",
  mission: "Trace light beams, test materials, bend light with water and prisms, and use mirrors to send light around the garden wall.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.80 · LUMARA LIGHT LAB",
  playableActs: [1, 2, 3],
  earthTrue: "Every mirror, lens, prism, and material in this quest behaves exactly as it does on Earth. Only the planet and crew are invented.",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Beam path", heatUnit: "%", supplies: "Test cards", suppliesUnit: "cards" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Welcome to the light lab in Lumara's glowing garden.",
    "The garden's rare plants need light in just the right places, and the crew needs to learn how light moves.",
    "Every beam here behaves just like light on Earth. Use what you know. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Straight-line light", "Act 2 · Bend and soak", "Act 3 · Mirrors and lenses"],
    completes: [
      "The lamps are back on, and you know how light travels, {firstName}!",
      "The prism is shining and the moss is safe, {firstName}!",
      "The beam made it around the wall, {firstName}! The sunseed sprouts are growing.",
    ],
    teasers: [
      "Next on Lumara: Kai has a strange idea about how eyes work, and a pencil looks broken. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: mirrors, lenses, and a wall that blocks the light. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai and I already disagree about how we see.",
      "Then we'll bend light with water and a prism.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The sunseed sprouts behind the garden wall are in the dark.",
      "Learn how mirrors and lenses work, then get light to those sprouts.",
    ],
  }),
  tasks,
};
