// Expedition Station — The Lost Rover (ELA.3.8C-XP)
// Grade 3 · ELAR · Frostveil. Main standard 3.8C (analyze plot elements,
// including the sequence of events, the conflict, and the resolution); also
// practices 3.10B (how text structure helps the author's purpose), 3.6F
// (inference), 3.7C (text evidence), 3.7D (retell), 3.3B (context clues), and
// 3.8B (characters). All passages are original, written for this quest. A
// young station helper named Liko goes after a little rover lost in a
// snowstorm (Passages A–D), and a short second story about two friends and one
// block of ice (Passage E) gives a different kind of conflict to compare.
import { CREW, acts, passage } from "./_shared.js";

const passages = {
  A: passage("A", { title: "The Lost Rover, Part 1: The Storm Warning", genre: "Story (beginning)" }, [
    [
      "Liko was the youngest helper at Snowcap Station.",
      "Her favorite job was caring for Button, a little rover about the size of a sled.",
      "Every afternoon, Button rolled out to the ice fields to scoop up snow samples.",
      "It always came home before dark.",
    ],
    [
      "Kai had built Button with a green lamp on top.",
      "Whenever someone flashed a light at Button, its lamp blinked back the same number of times.",
      "\"That way, we can always find it,\" Kai liked to say.",
    ],
    [
      "One afternoon, the sky turned the color of an old gray spoon.",
      "Commander Vega looked at the weather screen and frowned.",
      "\"A big storm is coming,\" she said. \"Everyone stays inside tonight.\"",
    ],
    [
      "Liko waited by the door.",
      "The sun sank low, and snow began to swirl.",
      "Button did not come home.",
    ],
  ]),
  B: passage("B", { title: "The Lost Rover, Part 2: Into the Wind", genre: "Story (the problem grows)" }, [
    [
      "Liko checked the tracker screen. Button's dot was near Needle Ridge, and it was not moving.",
      "A red warning flashed: Button's battery was running low.",
      "If the battery ran out in the cold, Button might never wake up again.",
    ],
    [
      "Liko wanted to run outside and find Button right away.",
      "But the wind howled, and the snow was so thick that she could not see the flagpole by the door.",
      "Rushing into a storm alone would be foolish, a silly choice that could get her hurt.",
    ],
    [
      "So Liko asked Kai for help.",
      "Kai clipped one end of a long rope to his belt and the other end to hers.",
      "\"We stay together, and we follow the rope line,\" he said.",
      "Step by step, they pushed into the wind.",
    ],
  ]),
  C: passage("C", { title: "The Lost Rover, Part 3: The Blinking Light", genre: "Story (turning point)" }, [
    [
      "At Needle Ridge, the snow came up to Liko's knees.",
      "She called Button's name again and again, but the wind swallowed her voice.",
    ],
    [
      "Then Liko had an idea.",
      "She switched her headlamp on and off, one, two, three times.",
      "For a long moment, nothing happened.",
    ],
    [
      "Then, far to the left, a tiny green light blinked back three times.",
      "\"There you are!\" Liko shouted.",
      "Button was stuck in a deep snowdrift, with only its antenna poking out.",
    ],
    [
      "Liko and Kai dug with their gloves until Button's wheels were free.",
    ],
  ]),
  D: passage("D", { title: "The Lost Rover, Part 4: Home Again", genre: "Story (ending)" }, [
    [
      "Kai carried Button, and Liko held the rope as they followed it back to the station.",
      "Inside, Nova plugged Button into the charger.",
      "Its screen flickered, and then it beeped a happy beep.",
    ],
    [
      "Commander Vega wrapped a warm blanket around Liko.",
      "\"You were brave, and you were also smart,\" she said. \"You asked for help.\"",
    ],
    [
      "The next day, Liko and Kai painted Button bright orange so it would be easy to spot in the snow.",
      "They made a new rule, too: Button must head home at the first sign of a storm.",
      "That night, Liko fell asleep with Button humming softly beside her bed.",
    ],
  ]),
  E: passage("E", { title: "One Block of Ice", genre: "Short story" }, [
    [
      "Oona and Bram were best friends at Snowcap Station.",
      "Every winter, the station held an ice sculpture contest.",
      "This year, only one big block of clear ice was left.",
    ],
    [
      "Oona wanted to carve a snow owl.",
      "Bram wanted to carve a sled dog.",
      "They both grabbed the block at the same time, and neither one would let go.",
      "\"I saw it first!\" they shouted together.",
    ],
    [
      "For two days, the friends did not speak to each other.",
      "Oona carved a tiny owl from a leftover chunk, but it looked lonely.",
      "Bram's little dog kept cracking.",
    ],
    [
      "On the morning of the contest, Bram knocked on Oona's door.",
      "\"What if we carve a dog pulling a sled, with an owl riding on top?\" he asked.",
      "Oona grinned.",
      "They carved all day, side by side.",
    ],
    [
      "Their sculpture did not win first prize.",
      "But it made everyone laugh, and Oona and Bram were friends again.",
    ],
  ]),
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Meet Liko", machine: "Read the Crew", icon: "crew", speaker: "vega", passage: ["A"],
    line: "Every story starts with a character. Tonight's story is about our youngest helper. Tell me who she is.",
    question: "Read Passage A. Which sentence best describes Liko?",
    hint: "Look at the first paragraph. What is Liko's favorite job?",
    meter: { heat: 15, label: "Rover beacon +15%", story: "The story file opens" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "A young helper who takes care of a little rover named Button" },
      { id: "b", text: "The commander who runs Snowcap Station" },
      { id: "c", text: "An engineer who built Button's green lamp" },
      { id: "d", text: "A rover that collects snow samples" },
    ],
    rightFeedback: "Right! Liko is the youngest helper, and caring for Button is her favorite job.",
    wrong: [
      { choice: "b", hint: "Commander Vega runs the station. Which character is the youngest helper?" },
      { choice: "c", hint: "Kai built the lamp. What does paragraph 1 say Liko does?" },
      { choice: "d", hint: "That describes Button, not Liko. Who takes care of Button?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Something goes wrong", machine: "Trace", icon: "scan", speaker: "nova", passage: ["A"],
    line: "Every story has a problem, called the conflict. The first part of this story ends when the problem shows up.",
    question: "Highlight the sentence in Passage A that shows the main problem of the story.",
    hint: "The problem is what goes wrong for Liko. Read the last paragraph.",
    meter: { heat: 10, label: "Rover beacon +10%", story: "The problem is on the plot board" },
    discovery: { id: "whiteout", name: "Whiteouts", who: "Nova", fact: "In a whiteout, blowing snow and clouds make everything look white. People can't see the ground or the sky, so it's easy to get lost even close to home." },
    answer: { kind: "highlight", groups: [["A4.3"]] },
    rightFeedback: "Locked on! Button did not come home, and a storm is on the way. That's the problem.",
    wrong: [
      { sentence: "A3.3", hint: "The storm warning sets things up, but nothing has gone wrong yet. What happens that worries Liko?" },
      { sentence: "A1.4", hint: "That tells what USUALLY happens. What happens differently this time?" },
      { sentence: "A4.2", hint: "That tells about the weather. What is missing when the sun goes down?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "A foolish plan", machine: "Decipher", icon: "static", speaker: "kai", passage: ["B"],
    line: "Part 2 uses the word foolish. The sentence gives a clue right after the comma.",
    question: "\"Rushing into a storm alone would be foolish, a silly choice that could get her hurt.\" What does foolish mean?",
    hint: "Read the words after the comma. They tell you what foolish means.",
    meter: { supplies: 1, label: "Trail flags +1", story: "Kai plants a flag by the door" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Not wise" },
      { id: "b", text: "Brave" },
      { id: "c", text: "Very fast" },
      { id: "d", text: "Very cold" },
    ],
    rightFeedback: "Yes! The clue says it would be a silly choice that could get her hurt. That's not wise.",
    wrong: [
      { choice: "b", hint: "Would a brave choice be called silly? Look at the words after the comma." },
      { choice: "c", hint: "Rushing is fast, but the clue calls the choice silly. What does that tell you?" },
      { choice: "d", hint: "The storm is cold, but foolish describes the choice. Read the clue after the comma." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Beat the battery", machine: "Cause & Effect", icon: "log", speaker: "nova", passage: ["B"],
    line: "Liko can't wait until morning. Something makes this problem urgent.",
    question: "Part 1: Why does Liko need to find Button tonight? Part 2: Highlight the sentence that tells what could happen if she waits.",
    parts: [
      { type: "choice", prompt: "Why does Liko need to find Button tonight?", choices: [
        { id: "a", text: "Its battery is running low, and it might stop working in the cold." },
        { id: "b", text: "Button has the station's only snow samples." },
        { id: "c", text: "Commander Vega told her to go outside." },
        { id: "d", text: "Button is scared of the dark." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that tells what could happen if Liko waits.", passage: "B" },
    ],
    hint: "Read paragraph 1 of Passage B. What does the red warning say?",
    meter: { heat: 10, label: "Rover beacon +10%", story: "The tracker shows Needle Ridge" },
    discovery: { id: "coldbattery", name: "Cold batteries", who: "Kai", fact: "Batteries lose power faster when they get very cold. That's why a phone can shut off early on a freezing day." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "highlight", groups: [["B1.3"]] }] },
    rightFeedback: "Right! If the battery runs out in the cold, Button might never wake up again.",
    wrong: [
      { step: 1, choice: "b", hint: "The story never says that. What does the red warning on the tracker say?" },
      { step: 1, choice: "c", hint: "Vega said everyone stays INSIDE. Look at the tracker warning." },
      { step: 1, choice: "d", hint: "Button is a rover. What is wrong with its battery?" },
      { step: 2, sentence: "B1.1", hint: "That tells where Button is. Which sentence tells what could happen if Liko waits?" },
      { step: 2, sentence: "B1.2", hint: "Close! That says the battery is low. Which sentence tells what could happen next?" },
      { step: 2, sentence: "B2.1", hint: "That tells what Liko wants to do. What could happen to Button?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The problem grows", machine: "Plot Board", icon: "snap", speaker: "vega", passage: ["A", "B"],
    line: "Surprise! The storm just got stronger, and the power flickered. Before anyone goes out, I need the whole problem mapped on the plot board.",
    question: "Part 1: What is the main conflict? Part 2: Highlight TWO sentences in Passage B that make the problem harder, one about the battery and one about the storm. Part 3: How does Liko handle the problem?",
    parts: [
      { type: "choice", prompt: "What is the main conflict in the story?", choices: [
        { id: "a", text: "Liko must find Button in a dangerous snowstorm before its battery runs out." },
        { id: "b", text: "Liko and Kai argue about who should fix Button." },
        { id: "c", text: "Commander Vega does not like Button." },
        { id: "d", text: "The sky turns the color of an old gray spoon." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence about the battery and one about the storm.", passage: "B", count: 2 },
      { type: "choice", prompt: "How does Liko handle the problem?", choices: [
        { id: "a", text: "She asks Kai for help, and they tie themselves together with a rope." },
        { id: "b", text: "She runs into the storm alone." },
        { id: "c", text: "She waits until morning." },
        { id: "d", text: "She asks Nova to build a new rover." },
      ] },
    ],
    hint: "A conflict is the big problem a character must solve. What does Liko have to do, and what makes it hard?",
    meter: { heat: 10, label: "Rover beacon +10%", story: "Liko and Kai clip on the rope" },
    discovery: { id: "signaldelay", name: "Messages to Mars", who: "Kai", fact: "Radio messages between Earth and Mars take from about 4 to 24 minutes to travel one way. So people can't steer a Mars rover like a toy car. They plan its drives ahead of time." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B1.2", "B1.3"], ["B2.2"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Great mapping! A low battery AND a wild storm make Liko's problem harder, so she asks for help.",
    wrong: [
      { step: 1, choice: "b", hint: "Liko and Kai work together. What is the big problem Liko has to solve?" },
      { step: 1, choice: "c", hint: "Nothing in the story says that. What went wrong at the end of Part 1?" },
      { step: 1, choice: "d", hint: "That describes the sky. It's a detail, not the problem." },
      { step: 2, sentence: "B2.1", hint: "That tells what Liko wants. Which sentences show what makes the problem harder?" },
      { step: 2, sentence: "B3.1", hint: "That is how Liko handles the problem. Find the sentences that make it harder." },
      { step: 2, sentence: "B1.1", hint: "That tells where Button is. Find the sentence about the battery." },
      { step: 3, choice: "b", hint: "Liko WANTS to, but does she? Read paragraph 3 of Passage B." },
      { step: 3, choice: "c", hint: "The battery can't wait. What does Liko do instead?" },
      { step: 3, choice: "d", hint: "Nova isn't in Part 2. Who does Liko ask for help?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The turning point", machine: "Trace", icon: "scan", speaker: "nova", passage: ["C"],
    line: "The climax is the turning point, the most exciting moment when things start to change. Find it in Part 3.",
    question: "Highlight the sentence in Passage C that is the turning point of the story.",
    hint: "Before this moment, Liko can't find Button. After it, she knows where Button is. Which sentence changes everything?",
    meter: { heat: 10, label: "Rover beacon +10%", story: "The green light is on the plot board" },
    discovery: { id: "searchdogs", name: "Snow search dogs", who: "Nova", fact: "Some dogs are trained to find people buried in snow. They use their strong sense of smell and can search a snowy slope much faster than people can." },
    answer: { kind: "highlight", groups: [["C3.1"]] },
    rightFeedback: "Yes! The green light blinking back is the turning point. Now Liko knows where Button is.",
    wrong: [
      { sentence: "C1.2", hint: "Here Liko still can't find Button. Which moment changes that?" },
      { sentence: "C2.2", hint: "That's Liko's plan. Does it work yet? Look for the moment it pays off." },
      { sentence: "C4.1", hint: "By then, Liko already knows where Button is. Which moment came first and changed everything?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Line up the rescue", machine: "Timeline", icon: "log", speaker: "kai", passage: ["A", "B", "C"],
    line: "My plot board fell off the wall, and all the event cards are mixed up. Help me put them back.",
    question: "Put the events from Parts 1 to 3 in order, first to last.",
    hint: "Use the part numbers and time words like \"one afternoon,\" \"then,\" and \"step by step.\"",
    meter: { supplies: 1, label: "Trail flags +1", story: "The plot board is back on the wall" },
    discovery: { id: "quietsnow", name: "Quiet snow", who: "Kai", fact: "Fresh, fluffy snow makes the world sound quieter. The tiny air spaces between snowflakes soak up sound." },
    answer: { kind: "order", correct: ["warn", "missing", "ask", "flash", "blink", "dig"] },
    items: [
      { id: "flash", text: "Liko flashed her headlamp three times." },
      { id: "warn", text: "Commander Vega warned that a big storm was coming." },
      { id: "dig", text: "Liko and Kai dug Button out of the snowdrift." },
      { id: "missing", text: "Button did not come home before dark." },
      { id: "ask", text: "Liko asked Kai to help her." },
      { id: "blink", text: "A tiny green light blinked back." },
    ],
    rightFeedback: "Perfect! Warning, missing rover, help, signal, answer, rescue. The plot is in order.",
    wrong: [
      { position: 0, hint: "What happened in Part 1 before Button was missing? Vega looked at the weather screen." },
      { position: 1, hint: "The problem comes right after the warning. What didn't happen when the sun sank low?" },
      { position: 2, hint: "Before Liko went out, what smart thing did she do in Part 2?" },
      { position: 3, hint: "The light had to blink back AFTER something. What did Liko do with her headlamp?" },
      { position: 4, hint: "They couldn't dig Button out until they found it. What helped them find it?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Why three flashes?", machine: "Cause & Effect", icon: "static", speaker: "vega", passage: ["C", "A"],
    line: "Liko's headlamp idea saved the night. But why did she think it would work? The answer is back in Part 1.",
    question: "Part 1: Why did Liko flash her headlamp? Part 2: Highlight the sentence in Passage A that explains why her idea worked.",
    parts: [
      { type: "choice", prompt: "Why did Liko flash her headlamp?", choices: [
        { id: "a", text: "She knew Button's lamp would blink back and show where it was." },
        { id: "b", text: "She wanted to scare away the storm." },
        { id: "c", text: "Her headlamp was broken." },
        { id: "d", text: "She was sending a message to Commander Vega." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence in Passage A that explains why the idea worked.", passage: "A" },
    ],
    hint: "Go back to paragraph 2 of Passage A. What did Kai build Button to do?",
    meter: { heat: 10, label: "Rover beacon +10%", story: "Vega nods at the headlamp plan" },
    discovery: { id: "dustyrover", name: "A rover washed by wind", who: "Nova", fact: "The Mars rover Opportunity ran on solar panels. Dust piled up on them, but gusts of wind sometimes blew the panels clean, so the rover kept exploring for about 14 years." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "highlight", groups: [["A2.2"]] }] },
    rightFeedback: "Right! Button blinks back at flashing lights, so three flashes brought three blinks.",
    wrong: [
      { step: 1, choice: "b", hint: "A light can't stop a storm. What does Button do when a light flashes at it?" },
      { step: 1, choice: "c", hint: "The headlamp worked fine. Why would Liko switch it on and off?" },
      { step: 1, choice: "d", hint: "Vega is back at the station. Who was Liko signaling?" },
      { step: 2, sentence: "A2.1", hint: "Close! That says Button has a green lamp. Which sentence tells what the lamp DOES?" },
      { step: 2, sentence: "A2.3", hint: "That's what Kai says. Which sentence explains how the lamp works?" },
      { step: 2, sentence: "A1.2", hint: "That tells who Button is. Find the sentence about the lamp blinking back." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Beginning, middle, end", machine: "Sort Bay", icon: "cells", speaker: "nova",
    passage: ["A", "B", "C", "D"],
    line: "A plot has a beginning, a middle, and an end. Let's sort these event cards into the right part of the story.",
    question: "Sort each event: beginning, middle, or end of the story?",
    hint: "The beginning sets things up. The middle is where the problem grows and turns. The end shows how things work out.",
    meter: { supplies: 1, label: "Trail flags +1", story: "The plot board has three neat rows" },
    answer: { kind: "sort", bins: { b1: "begin", b2: "begin", m1: "middle", m2: "middle", e1: "end", e2: "end" } },
    rightFeedback: "Sorted! Setup, problem and turning point, then home again.",
    sort: {
      bins: [
        { id: "begin", label: "Beginning" },
        { id: "middle", label: "Middle" },
        { id: "end", label: "End" },
      ],
      items: [
        { id: "m1", label: "Liko and Kai follow the rope line into the wind." },
        { id: "e1", label: "Nova plugs Button into the charger." },
        { id: "b1", label: "Button rolls out to scoop snow every afternoon." },
        { id: "e2", label: "Liko and Kai paint Button bright orange." },
        { id: "m2", label: "A green light blinks back from a snowdrift." },
        { id: "b2", label: "Vega sees a storm coming on the weather screen." },
      ],
    },
    wrong: [
      { item: "b1", hint: "This tells what Button does every day, before anything goes wrong. Which part sets things up?" },
      { item: "b2", hint: "The warning comes in Part 1, before Button goes missing. Which part is that?" },
      { item: "m1", hint: "They are still searching. The problem isn't solved yet. Which part is that?" },
      { item: "m2", hint: "This is the turning point, but Button isn't home yet. Which part holds the turning point?" },
      { item: "e1", hint: "Button is safe and charging. The problem is solved. Which part is that?" },
      { item: "e2", hint: "This happens the next day, after the rescue. Which part is that?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Home before the lights go out", machine: "Plot Board", icon: "quake", speaker: "vega", passage: ["D", "A", "B", "C"],
    line: "Surprise! Mission Control wants the ending of the story before the station's backup lights shut off for the night. Show them how the problem gets solved.",
    question: "Part 1: Highlight the sentence in Passage D that shows the main problem is solved. Part 2: Why do Liko and Kai paint Button orange? Part 3: Why did the author tell the story in four parts, in time order?",
    parts: [
      { type: "highlight", prompt: "Highlight the sentence that shows the main problem is solved.", passage: "D" },
      { type: "choice", prompt: "Why do Liko and Kai paint Button bright orange?", choices: [
        { id: "a", text: "So Button is easy to spot in the snow if it gets lost again" },
        { id: "b", text: "Because orange is Liko's favorite color" },
        { id: "c", text: "To keep Button's battery warm" },
        { id: "d", text: "Because the old paint washed off in the storm" },
      ] },
      { type: "choice", prompt: "Why did the author tell the story in four parts, in time order?", choices: [
        { id: "a", text: "To show step by step how the problem starts, grows, turns, and gets solved" },
        { id: "b", text: "To teach facts about how batteries work" },
        { id: "c", text: "To list the station's rules" },
        { id: "d", text: "To compare Liko and Kai" },
      ] },
    ],
    hint: "The main problem was a lost rover with a low battery. When is Button found AND safe again?",
    meter: { heat: 10, label: "Rover beacon +10%", story: "The ending reaches Mission Control" },
    discovery: { id: "penguinhuddle", name: "Penguin huddles", who: "Nova", fact: "In freezing winter storms, emperor penguins huddle in a big crowd to share warmth. They slowly take turns moving from the chilly outside edge to the warm middle." },
    answer: { kind: "parts", parts: [
      { kind: "highlight", groups: [["D1.3", "D1.2"]] },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Mission Control has it! Button is charged and safe, the new rules keep it from happening again, and the four parts walk us through the whole plot.",
    wrong: [
      { step: 1, sentence: "D3.3", hint: "That's the last sentence, but the problem was already solved before it. When is Button safe again?" },
      { step: 1, sentence: "D2.2", hint: "Vega praises Liko here. Which sentence shows Button is okay?" },
      { step: 1, sentence: "D3.1", hint: "That happens the next day. Which sentence shows Button waking up?" },
      { step: 2, choice: "b", hint: "The story doesn't say that. Read the whole sentence in paragraph 3." },
      { step: 2, choice: "c", hint: "Paint doesn't warm a battery. What does the sentence say orange will do?" },
      { step: 2, choice: "d", hint: "The story never says the paint washed off. Why would bright orange help in snow?" },
      { step: 3, choice: "b", hint: "The story mentions a battery, but it's not teaching facts. What do the four parts show, in order?" },
      { step: 3, choice: "c", hint: "One rule shows up at the end, but the story isn't a list. What do the parts show?" },
      { step: 3, choice: "d", hint: "The story doesn't compare them. Think about what happens in Part 1, then 2, then 3, then 4." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "One block, two friends", machine: "Trace", icon: "scan", speaker: "nova", passage: ["E"],
    line: "Kai found another story in the station library. This one has a very different kind of problem.",
    question: "Highlight the sentence in Passage E that shows the conflict between Oona and Bram.",
    hint: "The conflict is where the two friends clash. Look in paragraph 2.",
    meter: { heat: 10, label: "Rover beacon +10%", story: "A second story goes on the board" },
    discovery: { id: "icefestival", name: "A city of ice", who: "Nova", fact: "Every winter in Harbin, China, artists build a giant festival of buildings made from blocks of ice cut from a frozen river. At night, colored lights glow inside the ice." },
    answer: { kind: "highlight", groups: [["E2.3", "E2.4"]] },
    rightFeedback: "Yes! Both friends want the same block, and neither one will let go.",
    wrong: [
      { sentence: "E1.3", hint: "That's WHY there's trouble, but the friends haven't clashed yet. Which sentence shows them fighting over it?" },
      { sentence: "E2.1", hint: "That tells what Oona wants. Where do the two friends clash?" },
      { sentence: "E3.1", hint: "That happens because of the fight. Which sentence shows the fight itself?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "No bad guy?", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["E"],
    line: 'Kai: "Story E doesn\'t have a conflict. There\'s no bad guy and no storm. Oona and Bram are both nice!"',
    nova: 'Nova: "A conflict is any problem the characters have to solve. Oona and Bram both want the same block of ice, and they stop speaking. That\'s a conflict."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Does a story need a villain to have a problem? What problem do Oona and Bram have to solve?",
    meter: { supplies: 1, label: "Trail flags +1", story: "The crew agrees on what a conflict is" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A conflict is a problem the characters must solve. It can be between two friends, with nature, or inside one character. No bad guy is needed." },
      { id: "B", text: "Nova, because Story E is shorter than Liko's story." },
      { id: "C", text: "Kai. Every conflict needs a bad guy." },
      { id: "D", text: "Kai. Nice characters never have problems." },
    ],
    writtenPrompt: "Tell Kai in your own words what the conflict in Story E is.",
    debateHints: {
      wrongWho: "Look at paragraph 2. Do Oona and Bram have a problem, even though they are both nice?",
      wrongReason: "Right person, check the reason. What is a conflict?",
      right: "Nova is right. A conflict is a problem, not a villain.",
    },
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Kai's mixed-up retelling", machine: "Repair", icon: "log", speaker: "kai", passage: ["A", "B", "C", "D"],
    line: "I retold Liko's story for the station newsletter. Nova says something is off. Can you find my mistake and fix it?",
    question: "Part 1: What went wrong in Kai's retelling? Part 2: Put Kai's sentences in the right order.",
    data: {
      title: "Kai's retelling",
      columns: ["Sentence", "What Kai wrote"],
      rows: [
        ["1", "Liko and Kai dug Button out of a snowdrift."],
        ["2", "A big storm came, and Button did not come home."],
        ["3", "Liko flashed her light, and Button blinked back."],
        ["4", "Nova charged Button, and it beeped."],
      ],
    },
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's retelling?", choices: [
        { id: "a", text: "The events are out of order. The rescue comes before the problem." },
        { id: "b", text: "He left out the storm." },
        { id: "c", text: "He named the wrong main character." },
        { id: "d", text: "He told the story in too many parts." },
      ] },
      { type: "order", prompt: "Put Kai's sentences in the right order, first to last.", items: [
        { id: "r1", text: "Liko and Kai dug Button out of a snowdrift." },
        { id: "r2", text: "A big storm came, and Button did not come home." },
        { id: "r3", text: "Liko flashed her light, and Button blinked back." },
        { id: "r4", text: "Nova charged Button, and it beeped." },
      ] },
    ],
    hint: "A retelling has to follow the story's order. Can Liko dig Button out before she knows it's lost?",
    meter: { heat: 5, label: "Rover beacon +5%", story: "Kai's newsletter is fixed" },
    discovery: { id: "snowgoggles", name: "Snow goggles", who: "Kai", fact: "Long ago, Inuit people carved snow goggles from bone, antler, or wood. Thin slits let in just a little light, which protected their eyes from the bright glare off the snow." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["r2", "r3", "r1", "r4"] },
    ] },
    rightFeedback: "Fixed! Problem, turning point, rescue, then home. Now the retelling makes sense.",
    wrong: [
      { step: 1, choice: "b", hint: "Look at sentence 2. The storm is there. Where is it in the list?" },
      { step: 1, choice: "c", hint: "Liko is in Kai's retelling. What's wrong with the ORDER of his sentences?" },
      { step: 1, choice: "d", hint: "He only wrote four sentences. Check which one comes first." },
      { step: 2, position: 0, hint: "Start with the problem. What went wrong at the beginning?" },
      { step: 2, position: 1, hint: "How did Liko find Button in the storm?" },
      { step: 2, position: 2, hint: "After Button blinked back, what did Liko and Kai do next out in the snow?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Tell it your way", machine: "Brief", icon: "brief", speaker: "vega", passage: ["A", "B", "C", "D"],
    line: "Mission Control wants a short retelling of Liko's story for the station log. Keep it in order, and include the problem and how it was solved.",
    question: "Retell Liko's story in 2–3 sentences. Tell the beginning, the middle, and the end in order. Name the problem and how it was solved.",
    hint: "Try: At first... Then... In the end... Use your plot board from Act 2.",
    meter: { heat: 5, label: "Rover beacon +5%", story: "The retelling goes in the station log" },
    answer: { kind: "write", minWords: 20 },
    minWords: 20,
    teacherScored: true,
    rubric: ["Tells the beginning, middle, and end in order", "Names the conflict and the resolution", "Complete sentences with capitals and end punctuation"],
    rightFeedback: "Thanks! Your teacher will read your retelling.",
    wrong: [],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Two stories, two problems", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["A", "B", "C", "D", "E"],
    line: "Surprise! Mission Control wants to add both stories to the station library tonight, but only if we can explain how their plots are different. Let's send it.",
    question: "Part 1: How are the two conflicts different? Part 2: Highlight TWO sentences, one from Passage D and one from Passage E, that show each problem is solved. Part 3: How does telling events in time order help both authors?",
    parts: [
      { type: "choice", prompt: "How are the two conflicts different?", choices: [
        { id: "a", text: "Liko struggles against a storm to save Button. Oona and Bram struggle against each other over one block of ice." },
        { id: "b", text: "Both stories are about a lost rover." },
        { id: "c", text: "Liko's story has a problem, but Story E does not." },
        { id: "d", text: "Both conflicts are about a snowstorm." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from Passage D and one from Passage E that show each problem is solved.", passage: ["D", "E"], count: 2 },
      { type: "choice", prompt: "How does telling events in time order help both authors?", choices: [
        { id: "a", text: "Readers can follow how each problem starts, gets worse, and is solved." },
        { id: "b", text: "It makes the stories rhyme." },
        { id: "c", text: "It lets the authors skip the ending." },
        { id: "d", text: "It turns the stories into lists of facts." },
      ] },
    ],
    hint: "Ask: who or what is each character up against? Then find the moment each problem is fixed.",
    meter: { heat: 10, label: "Rover beacon +10%", story: "Both stories are in the station library" },
    discovery: { id: "igloo", name: "Warm snow houses", who: "Nova", fact: "An igloo is a dome built from blocks of packed snow. The snow traps air and holds in heat, so inside can be many degrees warmer than the windy cold outside." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["D1.3", "D1.2"], ["E5.2", "E4.4"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Transmission sent! One conflict is with nature, one is between friends, and time order helps readers follow both plots.",
    wrong: [
      { step: 1, choice: "b", hint: "Story E has no rover. What problem do Oona and Bram have?" },
      { step: 1, choice: "c", hint: "Remember the crew debate. Oona and Bram have a problem, even with no bad guy." },
      { step: 1, choice: "d", hint: "Story E has no storm. What are Oona and Bram fighting about?" },
      { step: 2, sentence: "D3.3", hint: "That's the last sentence, but it's not when the problem was solved. When is Button safe again?" },
      { step: 2, sentence: "E5.1", hint: "Losing the prize isn't the problem. The problem was the fight. When do they become friends again?" },
      { step: 2, sentence: "E2.4", hint: "That's the conflict, not the solution. Look near the end of Passage E." },
      { step: 3, choice: "b", hint: "Neither story rhymes. What does time order show readers?" },
      { step: 3, choice: "c", hint: "Both stories have endings. What does time order help readers follow?" },
      { step: 3, choice: "d", hint: "They are stories, not lists of facts. What does time order show about each problem?" },
    ],
  },
};

export default {
  id: "ELA.3.8C-XP",
  standard: "ELA.3.8C-XP",
  engine: "expedition_station",
  title: "The Lost Rover",
  planet: "Frostveil",
  outpost: "Snowcap Station · storm night",
  grade: 3,
  subject: "ELAR",
  teks: "3.8C",
  supportingTeks: ["3.10B", "3.6F", "3.7C", "3.7D", "3.3B", "3.8B"],
  skillsChip: "3.8C · Plot: sequence, conflict, resolution",
  iCan: "I can put story events in order. I can tell a story's conflict, turning point, and resolution.",
  blurb: "A snowstorm hits icy Frostveil, and little rover Button doesn't come home. Follow young helper Liko's story from the first warning to the rescue.",
  mission: "Read Liko's story in four parts. Map its plot on the crew's plot board, compare it with a second story, and send the plots to Mission Control.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.8C · FROSTVEIL SNOWCAP",
  playableActs: [1, 2, 3],
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Rover beacon", heatUnit: "%", supplies: "Trail flags", suppliesUnit: "flags" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega at Snowcap Station on Frostveil.",
    "Our youngest helper, Liko, wrote a story about the night our little rover got lost in a storm.",
    "Help us map its plot: what happens first, what goes wrong, and how it all works out. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The storm warning", "Act 2 · The blinking light", "Act 3 · Two stories"],
    completes: [
      "The problem is mapped, {firstName}! Liko and Kai are roped together and heading into the wind.",
      "Great work, {firstName}! Button is home, charged, and painted bright orange.",
      "Both plots are on their way to Mission Control, {firstName}! The station library thanks you.",
    ],
    teasers: [
      "Next on Frostveil: out at Needle Ridge, Liko has an idea. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: a second story about two friends and one block of ice. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Liko and Kai just reached Needle Ridge.",
      "Read Parts 3 and 4 to find the turning point and see how the story ends.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Kai found a second story in the station library.",
      "It has a very different problem. Let's compare the two plots.",
    ],
  }),
  tasks,
};
