// Expedition Station — The Melting Point (SCI.3.6C-XP)
// Grade 3 · Science · Cindara (lava world). Main standard 3.6C (predict,
// observe, and record changes in the state of matter caused by heating or
// cooling, such as ice becoming liquid water, condensation forming on the
// outside of a glass, or liquid water being heated to become water vapor);
// also practices 3.6D (combine materials based on their physical properties
// to create or modify objects, and justify the choice), 3.1B (plan and
// conduct investigations), 3.1D (use tools such as thermometers), 3.1E
// (collect observations as evidence), 3.2B (analyze data for patterns),
// 3.2C (use math to compare data), 3.2D (evaluate a design using criteria),
// 3.3A (explanations supported by data), 3.3C (respectful scientific
// discussion), 3.5B (cause and effect), 3.5G (conditions and change).
//
// Earth-true rule: Cindara and the crew are invented, but every material,
// temperature, process, and data table is real Earth science.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Hot or cold?", machine: "Sample Bay", icon: "cells", speaker: "nova",
    line: "Before we build anything near the lava fields, let's look at how heat and cold change things. I made six cards from Earth.",
    question: "Sort each change: was it caused by heating or by cooling?",
    hint: "Did the thing get warmer, or did it get colder?",
    meter: { heat: 5, label: "Shelter +5%", story: "The change cards are sorted" },
    answer: { kind: "sort", bins: { h1: "heat", h2: "cool", h3: "heat", h4: "cool", h5: "heat", h6: "cool" } },
    rightFeedback: "Melting and boiling need heat. Freezing, hardening, and drops on a cold glass come from cooling.",
    sort: {
      bins: [{ id: "heat", label: "Heating" }, { id: "cool", label: "Cooling" }],
      items: [
        { id: "h1", label: "An ice cube melts in the sun" },
        { id: "h2", label: "A puddle freezes on a cold night" },
        { id: "h3", label: "Butter melts in a hot pan" },
        { id: "h4", label: "Drops form on a glass of ice water" },
        { id: "h5", label: "Water in a pot boils and makes steam" },
        { id: "h6", label: "Melted candle wax gets hard again" },
      ],
    },
    wrong: [
      { item: "h4", hint: "The glass is full of ice water, so it is cold. Water vapor in the air touches the cold glass and turns into drops." },
      { item: "h6", hint: "Wax melts when it is hot. What has to happen for it to get hard again?" },
      { item: "h2", hint: "A puddle turns into ice on a cold night. Is that heating or cooling?" },
      { item: "h1", hint: "The sun warms the ice. Is that heating or cooling?" },
      { item: "h3", hint: "The pan is hot. Is that heating or cooling?" },
      { item: "h5", hint: "The pot is on a hot stove. Is that heating or cooling?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Ice on a hot rock", machine: "Test Bay", icon: "scan", speaker: "kai",
    line: "I brought an ice cube from the ship's freezer. I'm going to set it on a warm rock near the lava field. Make a prediction first!",
    question: "Predict: what will happen to the ice cube on the warm rock?",
    hint: "What does heat do to ice?",
    meter: { heat: 5, label: "Shelter +5%", story: "The first prediction is logged" },
    discovery: { id: "zero", name: "Melting and freezing point", who: "Nova", fact: "Ice melts at 0°C (32°F). Liquid water freezes into ice at that same temperature." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It will melt into liquid water." },
      { id: "b", text: "It will get bigger and harder." },
      { id: "c", text: "It will turn into a rock." },
      { id: "d", text: "Nothing will happen to it." },
    ],
    rightFeedback: "The warm rock heats the ice, and the ice melts into liquid water.",
    wrong: [
      { choice: "b", hint: "Ice gets harder in the cold. The rock is warm. What does heat do to ice?" },
      { choice: "c", hint: "Ice is frozen water. It can't turn into a rock. What does heat do to it?" },
      { choice: "d", hint: "Ice only stays ice when it is cold. The rock is warm. What will change?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Ice to steam", machine: "Heat Lab", icon: "trail", speaker: "nova",
    line: "I put an ice cube in a metal pot on our lava-rock stove. Kai took notes, but they got mixed up.",
    question: "Put the changes in order, from the start to the end.",
    hint: "Ice has to melt before the water can boil.",
    meter: { supplies: 1, label: "Test logs +1", story: "The heating notes are in order" },
    discovery: { id: "boil", name: "Boiling point", who: "Nova", fact: "At sea level, water boils at 100°C (212°F). Boiling water turns into water vapor, a gas you can't see." },
    answer: { kind: "order", correct: ["solid", "melt", "boil", "vapor"] },
    items: [
      { id: "boil", text: "The water gets very hot and starts to bubble and boil." },
      { id: "vapor", text: "The water turns into water vapor (a gas) and rises into the air." },
      { id: "solid", text: "A solid ice cube sits in the pot." },
      { id: "melt", text: "The ice melts into liquid water." },
    ],
    rightFeedback: "Solid ice, then liquid water, then water vapor. Heating changed the state each time.",
    wrong: [
      { position: 0, hint: "What was in the pot at the very start, before any heating?" },
      { position: 1, hint: "The ice has to melt into liquid water before the water can boil." },
      { position: 2, hint: "The water has to boil before it turns into water vapor and rises." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Read the thermometer", machine: "Heat Lab", icon: "dial", speaker: "kai",
    line: "The thermometer in the pot said 30°C when we started. When the water began to boil, it said 100°C.",
    question: "How many degrees warmer did the water get?",
    unit: "°C",
    hint: "Start at 30. How far up is 100?",
    meter: { supplies: 1, label: "Test logs +1", story: "The temperatures are recorded" },
    answer: { kind: "number", value: 70 },
    rightFeedback: "100 − 30 = 70. The water got 70 degrees warmer before it boiled.",
    wrong: [
      { value: 130, hint: "You want to know how much the temperature went up. Should you add or subtract?" },
      { value: 100, hint: "100°C is where the water ended. It started at 30°C. How much did it go up?" },
      { value: 30, hint: "30°C is where the water started. How much warmer did it get?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The melting snacks", machine: "Supply Crate", icon: "quake", speaker: "vega",
    line: "Surprise! A crate of chocolate bars fell off the rover onto the warm rocks. Nova is timing what happens to one bar.",
    question: "Part 1: Predict what will happen to the chocolate. Part 2: Read the table. At what minute was the chocolate all liquid? Part 3: How can the crew make the chocolate solid again?",
    data: {
      title: "Chocolate bar on a warm rock",
      columns: ["Time", "What we see", "State"],
      rows: [
        ["0 minutes", "Hard bar with sharp edges", "Solid"],
        ["5 minutes", "Soft and bendy", "Solid, starting to melt"],
        ["10 minutes", "Runny puddle", "Liquid"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Predict: what will happen to the chocolate on the warm rocks?", choices: [
        { id: "a", text: "It will melt and turn into a liquid." },
        { id: "b", text: "It will freeze and get harder." },
        { id: "c", text: "It will turn into a gas right away." },
        { id: "d", text: "It will stay the same." },
      ] },
      { type: "number", prompt: "At what minute was the chocolate all liquid?", unit: "minutes" },
      { type: "choice", prompt: "How can the crew make the melted chocolate solid again?", choices: [
        { id: "a", text: "Cool it down in the cold cave or a fridge." },
        { id: "b", text: "Heat it more on the warm rocks." },
        { id: "c", text: "Stir it in the sun." },
        { id: "d", text: "Nothing. Melted chocolate can never be solid again." },
      ] },
    ],
    hint: "Heating makes solids melt. What does cooling do to a liquid?",
    meter: { heat: 10, label: "Shelter +10%", story: "The snacks are saved in the cool cave" },
    discovery: { id: "chocolate", name: "Melting chocolate", who: "Kai", fact: "Chocolate melts at about the same temperature as your body. That's why it can melt in your hand." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 10 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Heat melted the chocolate, and cooling can make it solid again. The snacks are saved!",
    wrong: [
      { step: 1, choice: "b", hint: "Things freeze when they get cold. The rocks are warm. What does heat do?" },
      { step: 1, choice: "c", hint: "A solid has to melt into a liquid first. What will the chocolate do on the warm rocks?" },
      { step: 1, choice: "d", hint: "The rocks are warm. What does heat do to a solid like chocolate?" },
      { step: 2, value: 5, hint: "At 5 minutes it was soft, but still solid. Find the row that says Liquid." },
      { step: 2, value: 0, hint: "At 0 minutes the bar was still hard. Find the row that says Liquid." },
      { step: 3, choice: "b", hint: "More heat keeps it liquid. What is the opposite of heating?" },
      { step: 3, choice: "c", hint: "The sun would keep it warm and runny. What is the opposite of heating?" },
      { step: 3, choice: "d", hint: "Think about melted wax or a frozen puddle. What happens when a liquid cools down?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "New water?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "When ice melts, it turns into a new kind of water. It isn\'t the same stuff anymore."',
    nova: 'Nova: "It\'s the same water. Only its state changed. If we freeze it again, it turns back into ice."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "What happens if you put melted ice back in the freezer?",
    meter: { heat: 5, label: "Shelter +5%", story: "Kai rethinks melted ice" },
    discovery: { id: "backforth", name: "Back and forth", who: "Nova", fact: "Water can change from ice to liquid and back again many times. Heating melts it, and cooling freezes it. It is still water." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Melting only changes water from a solid to a liquid. Cool it again and it freezes back into ice, so it is the same water." },
      { id: "B", text: "Nova, because ice and water are both cold." },
      { id: "C", text: "Kai. Liquid water looks different from ice, so it must be new stuff." },
      { id: "D", text: "Kai. Heat makes brand-new water out of ice." },
    ],
    writtenPrompt: "Tell Kai in your own words why melted ice is still water.",
    debateHints: {
      wrongWho: "Put the melted water back in the freezer. What does it turn into?",
      wrongReason: "Right person, check the reason. What happens when you cool the water again?",
      right: "Nova is right — melting and freezing only change the state. It is still water.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The sweaty bottle", machine: "Test Bay", icon: "flask", speaker: "nova",
    line: "I took an ice-cold bottle of water out of the cooler. A few minutes later, the outside of the bottle is covered in drops!",
    question: "Where did the drops on the outside of the bottle come from?",
    hint: "The air around us has water vapor in it. What happens when it touches something cold?",
    meter: { heat: 5, label: "Shelter +5%", story: "The bottle mystery is solved" },
    discovery: { id: "condense", name: "Condensation", who: "Nova", fact: "When water vapor in the air touches something cold, it cools and turns back into liquid drops. This is called condensation." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Water vapor in the air touched the cold bottle, cooled, and turned into liquid drops." },
      { id: "b", text: "Water leaked out through tiny holes in the bottle." },
      { id: "c", text: "The cold bottle made brand-new water." },
      { id: "d", text: "Someone splashed water on the bottle." },
    ],
    rightFeedback: "Cooling turned water vapor from the air into liquid drops. That's condensation!",
    wrong: [
      { choice: "b", hint: "The bottle has no holes, and the cap is on tight. Where else could the water come from?" },
      { choice: "c", hint: "Cold things can't make new water. What is in the air all around the bottle?" },
      { choice: "d", hint: "Nobody touched it. The drops showed up on their own. What is in the air?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The hot spot test", machine: "Heat Lab", icon: "tank", speaker: "kai",
    line: "The ground by the lava field is as hot as a pot of boiling water. I want to know which building materials would melt there.",
    question: "Predict: which materials would melt in a spot as hot as boiling water? Pick every one.",
    items: [
      { id: "ice", text: "Ice block" },
      { id: "butter", text: "Butter" },
      { id: "wax", text: "Candle wax" },
      { id: "chocolate", text: "Chocolate" },
      { id: "stone", text: "Stone block" },
      { id: "glass", text: "Glass window" },
    ],
    hint: "Think about what melts in a warm kitchen. Stone and glass only melt in fire far hotter than boiling water.",
    meter: { supplies: 1, label: "Test logs +1", story: "The melt list is ready" },
    answer: { kind: "multi", correct: ["ice", "butter", "wax", "chocolate"] },
    rightFeedback: "Ice, butter, wax, and chocolate all melt at that heat. Stone and glass stay solid.",
    wrong: [
      { pick: "stone", hint: "Stones stay solid next to a campfire. It takes the heat deep inside a volcano to melt rock." },
      { pick: "glass", hint: "A glass pot can hold boiling water without melting. Glass needs much more heat to melt." },
      { missing: true, hint: "There are four materials that would melt. Think about the ice, the snacks, and a candle." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "States of Cindara", machine: "Sample Bay", icon: "cells", speaker: "vega",
    line: "The lava field has matter in every state. Our sample sorter has three bins.",
    question: "Sort each sample: is it a solid, a liquid, or a gas?",
    hint: "Does it keep its own shape, flow and take the shape of its container, or spread out into the air?",
    meter: { heat: 5, label: "Shelter +5%", story: "The lava field samples are sorted" },
    discovery: { id: "lavarock", name: "Lava becomes rock", who: "Kai", fact: "Lava is melted rock. When it cools, it hardens into solid rock, such as basalt." },
    answer: { kind: "sort", bins: { m1: "liquid", m2: "solid", m3: "gas", m4: "solid", m5: "liquid", m6: "gas" } },
    rightFeedback: "Hot lava and melted butter flow like liquids. Cooled lava rock and ice are solids. Steam and water vapor are gases.",
    sort: {
      bins: [{ id: "solid", label: "Solid" }, { id: "liquid", label: "Liquid" }, { id: "gas", label: "Gas" }],
      items: [
        { id: "m1", label: "Hot lava flowing down a hill" },
        { id: "m2", label: "Lava rock that has cooled" },
        { id: "m3", label: "Steam rising from a hot spring" },
        { id: "m4", label: "An ice block" },
        { id: "m5", label: "Melted butter" },
        { id: "m6", label: "Water vapor in the air" },
      ],
    },
    wrong: [
      { item: "m1", hint: "Hot lava is melted rock. It flows and takes the shape of the ground. Solid, liquid, or gas?" },
      { item: "m2", hint: "When lava cools, it hardens and keeps its shape. Solid, liquid, or gas?" },
      { item: "m3", hint: "Steam is water as a gas. It rises and spreads out into the air." },
      { item: "m6", hint: "Water vapor is water as a gas. You can't see it, but it is in the air." },
      { item: "m4", hint: "An ice block keeps its own shape. Solid, liquid, or gas?" },
      { item: "m5", hint: "Melted butter flows and takes the shape of the pan. Solid, liquid, or gas?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The ice race", machine: "Test Bay", icon: "quake", speaker: "vega",
    line: "Surprise, the ice delivery for the shelter's cooler came early! Nova set 3 ice cubes, all the same size, from the same freezer, in 3 places. She timed how long each one took to melt.",
    question: "Part 1: Predict which cube will melt first. Part 2: How many more minutes did the cave cube take than the sunny cube? Part 3: What does the table show? Part 4: Pick the things Nova kept the same.",
    data: {
      title: "Minutes for each ice cube to melt",
      columns: ["Cube", "Place", "Minutes to melt"],
      rows: [
        ["A", "Warm rock by the lava field", "5"],
        ["B", "Sunny spot", "15"],
        ["C", "Cool, shady cave", "35"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Predict: which cube will melt first?", choices: [
        { id: "a", text: "Cube A, on the warm rock by the lava field" },
        { id: "b", text: "Cube B, in the sunny spot" },
        { id: "c", text: "Cube C, in the cool cave" },
        { id: "d", text: "They will all melt at the same time." },
      ] },
      { type: "number", prompt: "How many more minutes did Cube C take to melt than Cube B?", unit: "minutes" },
      { type: "choice", prompt: "What does the table show?", choices: [
        { id: "a", text: "The more heat there is, the faster ice melts." },
        { id: "b", text: "Ice melts fastest where it is coolest." },
        { id: "c", text: "Where the ice sits does not matter." },
        { id: "d", text: "Bigger ice cubes melt faster." },
      ] },
      { type: "multi", prompt: "Pick the things Nova kept the same.", choices: [
        { id: "size", text: "The size of the ice cubes" },
        { id: "freezer", text: "The freezer the cubes came from" },
        { id: "place", text: "Where each cube sat" },
        { id: "time", text: "How long each cube took to melt" },
      ] },
    ],
    hint: "Compare the Place column with the Minutes column. Which place is hottest?",
    meter: { heat: 10, label: "Shelter +10%", story: "The crew knows where ice lasts longest" },
    discovery: { id: "icevolcano", name: "Ice on volcanoes", who: "Nova", fact: "Some volcanoes on Earth, like ones in Iceland, are covered in ice. When they erupt, the heat melts the ice very fast and can cause floods." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 20 },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["size", "freezer"] },
    ] },
    rightFeedback: "More heat made the ice melt faster. And you spotted what kept the test fair!",
    wrong: [
      { step: 1, choice: "b", hint: "The sun is warm, but which spot is right next to the lava field?" },
      { step: 1, choice: "c", hint: "The cave is cool. Does ice melt faster where it is warm or where it is cool?" },
      { step: 1, choice: "d", hint: "The three places are not equally warm. Which one has the most heat?" },
      { step: 2, value: 35, hint: "35 minutes is how long Cube C took. How much longer is that than Cube B's 15 minutes?" },
      { step: 2, value: 50, hint: "You want to know how many MORE minutes. Should you add or subtract?" },
      { step: 2, value: 30, hint: "30 is the difference between Cube C and Cube A. Compare Cube C with Cube B." },
      { step: 3, choice: "b", hint: "Look at the table. The cave cube took the longest. Is the cave warm or cool?" },
      { step: 3, choice: "c", hint: "The times were very different: 5, 15, and 35 minutes. So did the place matter?" },
      { step: 3, choice: "d", hint: "All the cubes were the same size. What was different about them?" },
      { step: 4, pick: "place", hint: "The place is the one thing Nova changed on purpose." },
      { step: 4, pick: "time", hint: "The melting time is what Nova measured. It was different for each cube." },
      { step: 4, missing: true, hint: "There are two things that stayed the same. Read Commander Vega's message again." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Choose the walls", machine: "Build Site", icon: "shield", speaker: "vega",
    line: "Time to build! The shelter's front wall faces the lava field, where the ground gets as hot as boiling water.",
    question: "Which material should the crew use for the front wall so it stays solid near the heat?",
    hint: "Look back at the hot spot test. Which materials stayed solid?",
    meter: { heat: 10, label: "Shelter +10%", story: "The front wall goes up" },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Ice blocks" },
      { id: "b", text: "Wax bricks" },
      { id: "c", text: "Stone blocks" },
      { id: "d", text: "Butter bricks" },
    ],
    rightFeedback: "Stone stays solid near the heat, so the wall will keep its shape.",
    wrong: [
      { choice: "a", hint: "Ice melts at 0°C. The ground here is as hot as boiling water. What would happen to the wall?" },
      { choice: "b", hint: "Wax melted in the hot spot test. Would a wax wall keep its shape?" },
      { choice: "d", hint: "Butter melts in a warm pan. Would a butter wall stay standing near lava?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Seal the cracks", machine: "Build Site", icon: "snap", speaker: "kai",
    line: "The back wall faces a cool, shady cliff. There are small cracks between the stones there. I'll seal them with candle wax.",
    question: "Part 1: Put Kai's steps in order. Part 2: Why should the wax go on the cool back wall, not the hot front wall?",
    parts: [
      { type: "order", prompt: "Put Kai's steps in order.", items: [
        { id: "pour", text: "Pour the liquid wax into the cracks." },
        { id: "harden", text: "The wax hardens into a solid plug." },
        { id: "heat", text: "Heat the solid wax until it melts." },
        { id: "cool", text: "Let the wax cool down." },
      ] },
      { type: "choice", prompt: "Why should the wax go on the cool back wall?", choices: [
        { id: "a", text: "The heat by the lava would melt the wax again, and it would drip out." },
        { id: "b", text: "Wax only sticks to shady stones." },
        { id: "c", text: "Heat would turn the wax into ice." },
        { id: "d", text: "It doesn't matter. Wax never melts once it is hard." },
      ] },
    ],
    hint: "Heating turns wax into a liquid that can flow. Cooling turns it back into a solid.",
    meter: { supplies: 1, label: "Test logs +1", story: "The cracks are sealed" },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["heat", "pour", "cool", "harden"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Heat made the wax flow into the cracks, and cooling made it solid. Keeping it away from the lava keeps it solid.",
    wrong: [
      { step: 1, position: 0, hint: "Solid wax can't flow into a crack. What has to happen to it first?" },
      { step: 1, position: 1, hint: "Once the wax is liquid, it can be poured. When does it go into the cracks?" },
      { step: 1, position: 2, hint: "The wax has to cool down before it can harden." },
      { step: 2, choice: "b", hint: "Wax sticks to warm stones too. What does heat do to wax?" },
      { step: 2, choice: "c", hint: "Heat never makes ice. What does heat do to solid wax?" },
      { step: 2, choice: "d", hint: "Kai just melted hard wax with heat. What would the lava's heat do?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Will the stones melt?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "All solids melt at the same temperature. If the butter melted by the lava field, the stone walls will melt too!"',
    nova: 'Nova: "Different solids melt at different temperatures. Ice melts at 0°C, but stone needs far more heat than boiling water."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Remember the hot spot test. Did every material melt?",
    meter: { heat: 5, label: "Shelter +5%", story: "Kai trusts the stone walls" },
    discovery: { id: "magma", name: "Melted rock", who: "Kai", fact: "Rock only melts when it gets extremely hot, about 700°C to 1,200°C. Melted rock underground is called magma. When it comes out of a volcano, it is called lava." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. In the hot spot test, butter and wax melted, but stone and glass stayed solid. Different solids melt at different temperatures." },
      { id: "B", text: "Nova, because stone is gray." },
      { id: "C", text: "Kai. All solids are the same, so they melt the same way." },
      { id: "D", text: "Kai. Anything near lava melts right away." },
    ],
    writtenPrompt: "Tell Kai in your own words why the stone walls won't melt like the butter.",
    debateHints: {
      wrongWho: "Think about the hot spot test. Did the stone block melt like the butter?",
      wrongReason: "Right person, check the reason. What did the hot spot test show?",
      right: "Nova is right — each solid has its own melting temperature.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The leaky tank?", machine: "Build Site", icon: "water", speaker: "nova",
    line: "The shelter's cold water tank is covered in drops on the outside. Kai thinks it leaks! I added blue food coloring to the water inside. The drops on the outside are still clear.",
    question: "What does the blue coloring test show?",
    hint: "If the tank leaked, what color would the drops be?",
    meter: { heat: 5, label: "Shelter +5%", story: "The tank passes inspection" },
    discovery: { id: "dew", name: "Morning dew", who: "Nova", fact: "Dew on grass in the morning forms the same way. Water vapor in the air condenses on cool surfaces during the night." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The drops came from water vapor in the air, not from inside the tank. The tank doesn't leak." },
      { id: "b", text: "The tank leaks, and the blue color got lost on the way out." },
      { id: "c", text: "The food coloring made the drops." },
      { id: "d", text: "The tank is melting." },
    ],
    rightFeedback: "Clear drops means the water came from the air. The cold tank cooled the water vapor, and it condensed.",
    wrong: [
      { choice: "b", hint: "Water leaking out of the tank would still be blue. The drops are clear. Where did they come from?" },
      { choice: "c", hint: "The coloring is inside the tank, and the drops are clear. Where did the clear water come from?" },
      { choice: "d", hint: "The tank is made of metal and is cold. It isn't melting. What is in the air around it?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The steam vent", machine: "Heat Lab", icon: "relay", speaker: "vega",
    line: "This is it! A pool of water next to the shelter is sitting on hot rock, and the crew needs to know if it will become a steam vent. Nova tested a pot of pool water on the lava-rock stove.",
    question: "Part 1: Read the table. At what temperature did the water boil? Part 2: Why was there less water in the pot at 15 minutes? Part 3: Nova held a cold lid over the pot. What will form on the lid? Part 4: Write 2–3 sentences to Commander Vega explaining what heating and cooling did to the water. Use the table.",
    data: {
      title: "Heating a pot of pool water",
      columns: ["Time", "Temperature", "What we see"],
      rows: [
        ["0 minutes", "20°C", "Still, liquid water"],
        ["5 minutes", "60°C", "Liquid water, tiny bubbles on the bottom"],
        ["10 minutes", "100°C", "Big bubbles, boiling, steam rising"],
        ["15 minutes", "100°C", "Still boiling, less water in the pot"],
      ],
    },
    parts: [
      { type: "number", prompt: "At what temperature did the water start to boil?", unit: "°C" },
      { type: "choice", prompt: "Why was there less water in the pot at 15 minutes?", choices: [
        { id: "a", text: "Heat turned some of the liquid water into water vapor, and it went into the air." },
        { id: "b", text: "The water soaked into the metal pot." },
        { id: "c", text: "The water turned into ice." },
        { id: "d", text: "The heat destroyed the water forever." },
      ] },
      { type: "choice", prompt: "Nova holds a cold metal lid over the boiling pot. Predict: what will form on the lid?", choices: [
        { id: "a", text: "Drops of liquid water, because the vapor cools and condenses." },
        { id: "b", text: "Little rocks." },
        { id: "c", text: "Nothing. Vapor can never turn back into liquid." },
        { id: "d", text: "Melted metal." },
      ] },
      { type: "write", prompt: "Explain to Commander Vega what heating and cooling did to the water. Use the table.", minWords: 20 },
    ],
    rubric: ["Says heating turned liquid water into water vapor (a gas)", "Uses the table as evidence (a time, a temperature, or what was seen)", "Says cooling turned the vapor back into liquid drops"],
    hint: "Read the table from top to bottom. Look for the row where the water starts to boil.",
    meter: { heat: 10, label: "Shelter +10%", story: "The shelter is finished and the steam vent is mapped" },
    discovery: { id: "geyser", name: "Geysers", who: "Kai", fact: "A geyser is a hot spring where hot rock underground heats water until it shoots up as hot water and steam. Old Faithful in Yellowstone is a famous one." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 100 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The shelter is safe, and you explained the whole change! Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 60, hint: "At 60°C there were only tiny bubbles. Find the row that says boiling." },
      { step: 1, value: 20, hint: "20°C is where the water started. Find the row that says boiling." },
      { step: 1, value: 10, hint: "10 is the time in minutes. Look in the Temperature column for that row." },
      { step: 2, choice: "b", hint: "Metal pots don't soak up water. What does boiling turn liquid water into?" },
      { step: 2, choice: "c", hint: "Ice forms when water gets very cold. The pot was 100°C. What does heat do to water?" },
      { step: 2, choice: "d", hint: "Water is never destroyed. It changed state. What did you see rising from the pot?" },
      { step: 3, choice: "b", hint: "Water vapor can't turn into rocks. What happens when vapor touches something cold?" },
      { step: 3, choice: "c", hint: "Think about the drops on the cold bottle. What happens when vapor cools?" },
      { step: 3, choice: "d", hint: "Boiling water isn't nearly hot enough to melt a metal lid. What happens to vapor on a cold lid?" },
    ],
  },
};

export default {
  id: "SCI.3.6C-XP",
  standard: "SCI.3.6C-XP",
  engine: "expedition_station",
  title: "The Melting Point",
  planet: "Cindara",
  outpost: "Lava Field Camp · building season",
  grade: 3,
  subject: "Science",
  teks: "3.6C",
  supportingTeks: ["3.6D", "3.1B", "3.1D", "3.1E", "3.2B", "3.2C", "3.2D", "3.3A", "3.3C", "3.5B", "3.5G"],
  skillsChip: "3.6C · Heating and cooling change matter",
  iCan: "I can predict, observe, and record how heating and cooling change matter, like ice melting, water boiling into vapor, and drops forming on a cold glass. I can choose materials for a shelter based on how they act in heat.",
  blurb: "The crew needs a shelter near Cindara's lava fields. Before they build, they have to find out what heat and cold do to ice, water, wax, chocolate, and stone.",
  mission: "Heat and cool materials, record what changes, and build a shelter that stays solid near the lava.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.60 · CINDARA LAVA FIELD CAMP",
  playableActs: [1, 2, 3],
  earthTrue: "Cindara and the crew are invented. Every material, temperature, process, and data table in this quest is real Earth science.",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Shelter built", heatUnit: "%", supplies: "Test logs", suppliesUnit: "logs" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Our crew needs a shelter near the lava fields of Cindara.",
    "Heat changes things here fast. Before we build, we have to test what heating and cooling do to our materials.",
    "Heat and cold work here just like they do on Earth. Predict, watch, and record. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Heat it up", "Act 2 · Cool it down", "Act 3 · Build the shelter"],
    completes: [
      "You watched ice melt and water boil, and you saved the snacks, {firstName}!",
      "You solved the sweaty bottle and won the ice race, {firstName}!",
      "The shelter is built and it stays solid near the lava, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Cindara: Kai thinks melted ice is a new kind of water, and a cold bottle starts to drip. Act 2 is open now, or come back to it next time.",
      "Next on Cindara: it's time to build the shelter, and Kai is worried the stone walls will melt. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Today we find out what cooling does, and Kai and I already disagree about something.",
      "Let's run some tests.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our tests are done. It's time to build the shelter.",
      "Choose materials that stay solid near the heat.",
    ],
  }),
  tasks,
};
