// Expedition Station — The Migration Map (SCI.3.12A-XP)
// Grade 3 · Science · Cloudreach (sky reef). Main standard 3.12A (explain how
// temperature and precipitation affect animal growth and behavior through
// migration and hibernation, and plant responses through dormancy); also
// practices 3.1E (collect observations and measurements as evidence), 3.2B
// (identify patterns in data), 3.2C (use math to compare data), 3.3A (develop
// explanations supported by data), 3.3C (respectful scientific discussion),
// 3.5B (cause and effect), 3.5G (conditions that change a system).
//
// Earth-true rule: Cloudreach and the crew are invented, but every animal,
// migration, data pattern, and fact is real Earth science.
import { CREW, acts } from "./_shared.js";

const POND = {
  title: "Ducks at a Texas pond (Sept–April)",
  columns: ["Month", "Average high temperature", "Ducks seen"],
  rows: [
    ["September", "91°F", "10"],
    ["October", "82°F", "40"],
    ["November", "71°F", "90"],
    ["December", "63°F", "140"],
    ["January", "62°F", "150"],
    ["February", "66°F", "120"],
    ["March", "73°F", "60"],
    ["April", "80°F", "20"],
  ],
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Winter plans", machine: "Flyway Board", icon: "cells", speaker: "nova",
    line: "From up here on the sky reef, we can watch animals all over Earth get ready for winter. Every animal has a plan. Let's sort them.",
    question: "Sort each animal: does it migrate, hibernate, or stay active all winter?",
    hint: "Does the animal travel far away, go into a deep winter rest, or keep looking for food all winter?",
    meter: { heat: 10, label: "Flyway map +10%", story: "The winter plans are sorted" },
    answer: { kind: "sort", bins: { a1: "migrate", a2: "hibernate", a3: "migrate", a4: "hibernate", a5: "stay", a6: "stay", a7: "migrate" } },
    rightFeedback: "Whales, hummingbirds, and caribou travel. Bears and bats rest. Squirrels and cardinals keep going all winter.",
    sort: {
      bins: [{ id: "migrate", label: "Migrate" }, { id: "hibernate", label: "Hibernate" }, { id: "stay", label: "Stay active" }],
      items: [
        { id: "a1", label: "A gray whale swims to warm water" },
        { id: "a2", label: "A black bear rests in a den for months" },
        { id: "a3", label: "A hummingbird flies south for winter" },
        { id: "a4", label: "A little brown bat rests in a cave all winter" },
        { id: "a5", label: "A gray squirrel digs up nuts it buried" },
        { id: "a6", label: "A cardinal eats seeds at a snowy feeder" },
        { id: "a7", label: "Caribou walk hundreds of miles to a forest" },
      ],
    },
    wrong: [
      { item: "a2", hint: "The bear stays in one den and hardly moves for months. Is that traveling or a deep winter rest?" },
      { item: "a4", hint: "The bat stays in the same cave all winter in a deep rest. Is it traveling?" },
      { item: "a5", hint: "The squirrel is up and looking for food. Is it resting or traveling?" },
      { item: "a6", hint: "The cardinal is eating in the snow. It didn't leave, and it isn't resting." },
      { item: "a1", hint: "The whale swims a long way to a new place. What is that called?" },
      { item: "a3", hint: "The hummingbird flies far away for the winter. What is that called?" },
      { item: "a7", hint: "The caribou walk a long way to a new place. What is that called?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "What is migration?", machine: "Word Scope", icon: "scan", speaker: "vega",
    line: "Mission Control wants one clear meaning for the word on our map. We're calling it the Migration Map, after all!",
    question: "What does it mean when an animal migrates?",
    hint: "Think about the gray whale. Where does it go, and does it come back?",
    meter: { heat: 10, label: "Flyway map +10%", story: "The map has its big word" },
    discovery: { id: "graywhale", name: "Gray whale road trip", who: "Nova", fact: "Gray whales eat in cold Arctic waters in summer. In winter they swim to warm lagoons in Mexico to have their calves. The round trip can be 10,000 miles or more." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It travels a long way to a new place when the season changes, and later it goes back." },
      { id: "b", text: "It sleeps in a den all winter." },
      { id: "c", text: "It moves away once and never comes back." },
      { id: "d", text: "It grows thicker fur for winter." },
    ],
    rightFeedback: "Migration is a long trip that happens with the seasons. Many animals make the trip every year.",
    wrong: [
      { choice: "b", hint: "Resting in a den all winter is hibernation. Migrating animals are on the move." },
      { choice: "c", hint: "Migrating animals go back when the season changes again. The gray whale returns north every spring." },
      { choice: "d", hint: "Thicker fur helps some animals stay warm, but they don't go anywhere. Migration is about traveling." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Why the hummingbird goes", machine: "Cause Chain", icon: "trail", speaker: "kai",
    line: "I'm building a cause-and-effect chain for a hummingbird in Texas. My cards fell off the board in the wind!",
    question: "Put the cause-and-effect chain in order, from first to last.",
    hint: "The weather changes first. Then the plants and bugs change. Then the bird has a problem to solve.",
    meter: { supplies: 1, label: "Field tags +1", story: "The hummingbird chain is built" },
    discovery: { id: "hummerfuel", name: "Fueling up", who: "Nova", fact: "Before migrating, a ruby-throated hummingbird eats so much that it can almost double its weight. Many fly nonstop about 500 miles across the Gulf of Mexico." },
    answer: { kind: "order", correct: ["cold", "fewer", "hungry", "fly"] },
    items: [
      { id: "fly", text: "The hummingbird flies south to a warmer place with flowers and bugs." },
      { id: "hungry", text: "The hummingbird can't find enough food." },
      { id: "cold", text: "Fall comes, and the days get cooler and shorter." },
      { id: "fewer", text: "Fewer flowers bloom, and fewer tiny bugs fly around." },
    ],
    rightFeedback: "Cooler weather means fewer flowers and bugs. Less food means the hummingbird has to move.",
    wrong: [
      { position: 0, hint: "What changes first? Start with the weather." },
      { position: 1, hint: "After the weather cools, what happens to the flowers and bugs?" },
      { position: 2, hint: "Fewer flowers and bugs cause a problem for the bird. What is the problem?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Duck count", machine: "Sky Scope", icon: "grid", speaker: "nova",
    line: "Our sky scope is watching a pond in Texas. A class there counted ducks every month and made this bar graph.",
    question: "How many more ducks were seen in December than in October?",
    unit: "ducks",
    visual: { type: "bars", title: "Ducks seen at the pond", categories: [{ label: "Oct", value: 40 }, { label: "Dec", value: 140 }, { label: "Feb", value: 120 }, { label: "Apr", value: 20 }], step: 20, axis: "Ducks seen" },
    hint: "Find the December bar and the October bar. How far apart are they?",
    meter: { supplies: 1, label: "Field tags +1", story: "The duck count is logged" },
    answer: { kind: "number", value: 100 },
    rightFeedback: "140 − 40 = 100 more ducks in December. Lots of ducks come to Texas for the winter!",
    wrong: [
      { value: 180, hint: "\"How many more\" means compare. Should you add or subtract?" },
      { value: 140, hint: "140 is how many ducks were seen in December. How many MORE than October is that?" },
      { value: 120, hint: "120 is the February bar. Look for the December bar." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The bear that stopped", machine: "Tracker Screen", icon: "quake", speaker: "vega",
    line: "Surprise! We've been tracking a black bear in the mountains. It ate and ate all fall. Now, in December, its tracker hasn't moved for three weeks!",
    question: "Part 1: What is the bear most likely doing? Part 2: Pick every way the bear got ready in the fall. Part 3: Why do bears do this in winter?",
    parts: [
      { type: "choice", prompt: "What is the bear most likely doing?", choices: [
        { id: "a", text: "Hibernating in a den" },
        { id: "b", text: "Migrating to a warm place" },
        { id: "c", text: "Looking for berries in the snow" },
        { id: "d", text: "Hunting fish in the river" },
      ] },
      { type: "multi", prompt: "Pick every way the bear got ready in the fall.", choices: [
        { id: "eat", text: "It ate lots of food." },
        { id: "fat", text: "It stored fat on its body." },
        { id: "den", text: "It found a safe den." },
        { id: "fly", text: "It flew south." },
        { id: "nuts", text: "It buried nuts to dig up later." },
      ] },
      { type: "choice", prompt: "Why do bears hibernate in winter?", choices: [
        { id: "a", text: "Cold, snowy winters leave little food, so resting saves energy until spring." },
        { id: "b", text: "Bears are too lazy to look for food." },
        { id: "c", text: "The snow makes bears fall asleep." },
        { id: "d", text: "Bears hibernate to grow new teeth." },
      ] },
    ],
    hint: "The bear isn't moving at all. What happens to food in the mountains when winter comes?",
    meter: { heat: 15, label: "Flyway map +15%", story: "The bear's den is marked on the map" },
    discovery: { id: "bearfast", name: "Months without a meal", who: "Nova", fact: "A hibernating black bear can go months without eating, drinking, or going to the bathroom. It lives off the fat it stored in the fall." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["eat", "fat", "den"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The bear stored fat, found a den, and is hibernating until spring brings food back.",
    wrong: [
      { step: 1, choice: "b", hint: "A migrating animal travels far. This tracker hasn't moved at all." },
      { step: 1, choice: "c", hint: "Then the tracker would be moving around. It hasn't moved in three weeks." },
      { step: 1, choice: "d", hint: "Hunting means moving. The tracker has stayed in one spot." },
      { step: 2, pick: "fly", hint: "Bears can't fly! And this bear stayed in the mountains." },
      { step: 2, pick: "nuts", hint: "Squirrels bury nuts. A hibernating bear stores food in a different place: its own body." },
      { step: 2, missing: true, hint: "There are three ways. Think about food, fat, and a place to rest." },
      { step: 3, choice: "b", hint: "Bears aren't lazy. What happens to their food when winter comes?" },
      { step: 3, choice: "c", hint: "Snow doesn't make animals sleep. What happens to berries, plants, and insects in winter?" },
      { step: 3, choice: "d", hint: "Hibernation isn't about teeth. It's about getting through a time with little food." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Cold feathers?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Birds migrate because they feel cold. Their feathers can\'t keep them warm in winter."',
    nova: 'Nova: "The main reason is food. Cold weather means fewer bugs, seeds, and flowers, so birds go where the food is."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the cardinal eating seeds at the snowy feeder. Why can it stay?",
    meter: { heat: 10, label: "Flyway map +10%", story: "Kai rethinks why birds fly south" },
    discovery: { id: "chickadee", name: "Puffball birds", who: "Kai", fact: "Chickadees stay all winter in places that freeze. They fluff up their feathers to trap warm air, like wearing a puffy coat." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Many birds, like cardinals and chickadees, stay all winter because they can still find seeds. Birds that eat bugs and flower nectar leave when that food runs out." },
      { id: "B", text: "Nova, because birds don't like snow." },
      { id: "C", text: "Kai. Feathers only work in summer." },
      { id: "D", text: "Kai. Every bird leaves when it gets cold." },
    ],
    writtenPrompt: "Tell Kai in your own words why most birds migrate.",
    debateHints: {
      wrongWho: "If cold were the only reason, why do cardinals and chickadees stay all winter in the snow?",
      wrongReason: "Right person, check the reason. What do the birds that stay still have that the birds that leave don't?",
      right: "Nova is right. Cold weather matters because it makes food run out. Birds follow the food.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Read the pond log", machine: "Data Deck", icon: "log", speaker: "nova",
    line: "Here's the whole pond log from Texas, with the temperature for each month too. Let's look for a pattern.",
    question: "What pattern do you see in the pond log?",
    data: POND,
    hint: "Look down both columns. When the temperature goes down, what happens to the number of ducks?",
    meter: { supplies: 1, label: "Field tags +1", story: "The pond pattern is on the map" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "In the cooler months, more ducks came to the pond. In the warmer months, fewer ducks were there." },
      { id: "b", text: "In the warmer months, more ducks came to the pond." },
      { id: "c", text: "The number of ducks stayed the same all year." },
      { id: "d", text: "The ducks came in April and left in December." },
    ],
    rightFeedback: "The coolest months, December and January, had the most ducks. The warm months had the fewest.",
    wrong: [
      { choice: "b", hint: "Check September. It was the warmest month. How many ducks were there?" },
      { choice: "c", hint: "Look at the Ducks seen column. Do the numbers stay the same?" },
      { choice: "d", hint: "April had only 20 ducks, and December had 140. When were most ducks there?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The bat cloud", machine: "Sky Scope", icon: "scan", speaker: "kai",
    line: "Whoa! Every summer evening, a giant cloud of bats pours out of a cave near San Antonio, Texas. But in the fall, most of them fly away to Mexico.",
    question: "Why do these bats leave Texas in the fall?",
    hint: "These bats eat flying insects. What happens to insects when the weather gets cold?",
    meter: { heat: 10, label: "Flyway map +10%", story: "The bat flyway is on the map" },
    discovery: { id: "brackencave", name: "The biggest bat colony", who: "Nova", fact: "Bracken Cave near San Antonio, Texas, is the summer home of millions of Mexican free-tailed bats. It is the biggest bat colony in the world." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Cold weather means fewer flying insects, so the bats go south where insects are still flying." },
      { id: "b", text: "The cave gets too crowded in the fall." },
      { id: "c", text: "Bats only like to live in Mexico." },
      { id: "d", text: "The bats are going to find snow." },
    ],
    rightFeedback: "When it gets cold, there are fewer insects to catch. The bats follow their food south.",
    wrong: [
      { choice: "b", hint: "The cave is crowded all summer. What changes in the fall?" },
      { choice: "c", hint: "They spend the whole summer in Texas! What changes in the fall that makes them leave?" },
      { choice: "d", hint: "Bats that migrate go somewhere warmer. What do they need to find there?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The frozen frog", machine: "Field Lab", icon: "flask", speaker: "nova",
    line: "In the far north, a scientist found a wood frog under the leaves in winter. It was cold, hard, and not moving. In spring, it hopped away!",
    question: "What was happening to the wood frog in winter?",
    hint: "The frog came back to life in spring. It was resting, not gone.",
    meter: { supplies: 1, label: "Field tags +1", story: "The frog's winter rest is logged" },
    discovery: { id: "boxturtle", name: "Buried turtles", who: "Nova", fact: "In winter, box turtles dig down into soft soil or leaves and stay still for months. Their bodies slow way down until warm weather returns." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It was dormant. Its body slowed way down to get through the cold, and warm weather woke it up." },
      { id: "b", text: "It was migrating south under the leaves." },
      { id: "c", text: "It was taking a normal nap." },
      { id: "d", text: "It was hunting bugs under the leaves." },
    ],
    rightFeedback: "The frog was dormant. Cold weather slowed its body almost to a stop until spring.",
    wrong: [
      { choice: "b", hint: "The frog stayed in one spot all winter. Migrating means traveling far." },
      { choice: "c", hint: "A normal nap lasts hours, and you can wake up easily. This frog was frozen for months!" },
      { choice: "d", hint: "The frog wasn't moving at all. In winter there are almost no bugs to hunt." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The banded duck", machine: "Data Deck", icon: "quake", speaker: "vega",
    line: "Surprise! The Texas class spotted a duck with a tiny band on its leg. The band says it was tagged in Canada, far to the north. Let's use the pond log to solve its mystery.",
    question: "Part 1: How many more ducks were seen in January than in September? Part 2: Why did the banded duck come to Texas? Part 3: Why did most ducks leave in March and April? Part 4: Pick the two months with the most ducks.",
    data: POND,
    parts: [
      { type: "number", prompt: "How many more ducks were seen in January than in September?", unit: "ducks" },
      { type: "choice", prompt: "Why did the banded duck fly from Canada to Texas for the winter?", choices: [
        { id: "a", text: "Its lake in Canada froze over, so it couldn't reach food. Texas ponds stay open in winter." },
        { id: "b", text: "It wanted to see the Texas class." },
        { id: "c", text: "Texas is the coldest place it could find." },
        { id: "d", text: "It got lost in a storm." },
      ] },
      { type: "choice", prompt: "Why did most ducks leave the pond in March and April?", choices: [
        { id: "a", text: "Spring warmed the north, so the ducks flew back to nest where lakes thaw and food grows." },
        { id: "b", text: "The Texas pond dried up in March." },
        { id: "c", text: "The ducks were scared of the class." },
        { id: "d", text: "The ducks started to hibernate." },
      ] },
      { type: "multi", prompt: "Pick the two months with the most ducks.", choices: [
        { id: "dec", text: "December" },
        { id: "jan", text: "January" },
        { id: "sep", text: "September" },
        { id: "nov", text: "November" },
        { id: "feb", text: "February" },
      ] },
    ],
    hint: "Canada is much colder than Texas in winter. What happens to a lake when it gets very cold?",
    meter: { heat: 15, label: "Flyway map +15%", story: "The banded duck's trip is on the map" },
    discovery: { id: "whooper", name: "The tallest bird", who: "Kai", fact: "Whooping cranes are the tallest birds in North America, about 5 feet tall. The only wild flock that migrates on its own flies from Canada to the Texas coast every fall." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 140 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["dec", "jan"] },
    ] },
    rightFeedback: "Frozen lakes up north mean no food, so the ducks spend winter in Texas and go home in spring.",
    wrong: [
      { step: 1, value: 160, hint: "\"How many more\" means compare. Should you add or subtract?" },
      { step: 1, value: 150, hint: "150 is how many ducks came in January. How many MORE than September is that?" },
      { step: 1, value: 10, hint: "10 is the September count. Compare it with January." },
      { step: 2, choice: "b", hint: "Ducks don't migrate to visit people. What happens to lakes in Canada in winter?" },
      { step: 2, choice: "c", hint: "Look at the temperatures. Texas stays warmer than Canada in winter. What can the duck find in Texas?" },
      { step: 2, choice: "d", hint: "The log shows about 150 ducks came, not just one. That's a pattern, not an accident." },
      { step: 3, choice: "b", hint: "The class still saw 20 ducks in April, so the pond was still there. What was changing up north?" },
      { step: 3, choice: "c", hint: "The class was there all winter too. What changes up north in spring?" },
      { step: 3, choice: "d", hint: "Ducks don't hibernate, and spring is when animals wake up. Where did the ducks go?" },
      { step: 4, pick: "sep", hint: "Check the Ducks seen column. September had only 10 ducks." },
      { step: 4, pick: "nov", hint: "November had 90 ducks. Two months had even more." },
      { step: 4, pick: "feb", hint: "February had 120 ducks. Two months had even more." },
      { step: 4, missing: true, hint: "Pick two months. Find the two biggest numbers in the Ducks seen column." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The bare pecan tree", machine: "Reef Garden", icon: "water", speaker: "vega",
    line: "Plants can't fly south or dig a den. So what does a pecan tree in Texas do when winter comes? Our scope shows it has dropped all its leaves.",
    question: "Why does the pecan tree drop its leaves and stop growing in winter?",
    hint: "Plants need sunlight, water, and warmth to grow. What does winter bring less of?",
    meter: { heat: 10, label: "Flyway map +10%", story: "The plants join the map" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It goes dormant. Cold weather and short days slow it down, so it rests until spring warms up." },
      { id: "b", text: "The tree has died." },
      { id: "c", text: "The tree is migrating to a warmer place." },
      { id: "d", text: "Birds ate all the leaves." },
    ],
    rightFeedback: "The tree is dormant. It rests all winter and grows new leaves when spring comes.",
    wrong: [
      { choice: "b", hint: "The tree grows new leaves every spring. Is it dead, or just resting?" },
      { choice: "c", hint: "Trees have roots in the ground. They can't travel anywhere." },
      { choice: "d", hint: "The leaves fall to the ground every fall. What is the tree doing to get through the cold?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's missing caribou", machine: "Flyway Board", icon: "relay", speaker: "kai",
    line: "Our camera on the Arctic tundra saw thousands of caribou all summer. In fall, they vanished. So I pinned them on the map under \"Hibernating.\"",
    question: "Part 1: What did Kai get wrong? Part 2: How should Kai fix the map?",
    parts: [
      { type: "choice", prompt: "What did Kai get wrong?", choices: [
        { id: "a", text: "He thought the caribou were hibernating just because they left the camera. They really walked away to a new place." },
        { id: "b", text: "He pinned the caribou in the wrong color." },
        { id: "c", text: "Caribou don't live on the tundra." },
        { id: "d", text: "The camera was broken." },
      ] },
      { type: "choice", prompt: "How should Kai fix the map?", choices: [
        { id: "a", text: "Move the caribou to \"Migrate.\" They walk south to forests where they can dig through snow to find food." },
        { id: "b", text: "Move the caribou to \"Stay active\" on the tundra." },
        { id: "c", text: "Leave them under \"Hibernating.\" Big animals always hibernate." },
        { id: "d", text: "Take the caribou off the map." },
      ] },
    ],
    hint: "The caribou disappeared from the camera. Did they stop moving, or did they go somewhere else?",
    meter: { supplies: 1, label: "Field tags +1", story: "The caribou are back on the right part of the map" },
    discovery: { id: "caribou", name: "Long-distance walkers", who: "Nova", fact: "Some caribou herds in Alaska and Canada travel more than 1,000 miles in a year. That's one of the longest trips of any land animal." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The caribou migrated! Leaving one place doesn't mean an animal is hibernating.",
    wrong: [
      { step: 1, choice: "b", hint: "The color doesn't matter. Look at which group Kai picked." },
      { step: 1, choice: "c", hint: "The camera saw thousands of caribou on the tundra all summer. What happened in fall?" },
      { step: 1, choice: "d", hint: "The camera worked all summer. Where could the caribou have gone?" },
      { step: 2, choice: "b", hint: "The caribou left the tundra, so they aren't staying there." },
      { step: 2, choice: "c", hint: "Big animals don't always hibernate. The caribou left the tundra. What is that called?" },
      { step: 2, choice: "d", hint: "The caribou didn't vanish forever. They went somewhere. Fix the label instead." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "More than a nap", machine: "Field Lab", icon: "dial", speaker: "nova",
    line: "Kai says hibernating is just a long sleep. I checked a little brown bat hibernating in a cave. Its body was doing some surprising things.",
    question: "What happens to an animal's body during hibernation? Pick every one.",
    items: [
      { id: "temp", text: "Its body temperature drops." },
      { id: "heart", text: "Its heartbeat slows way down." },
      { id: "breath", text: "It breathes much more slowly." },
      { id: "fat", text: "It lives off stored fat instead of eating." },
      { id: "morning", text: "It wakes up every morning for breakfast." },
      { id: "fast", text: "Its heart beats faster to keep it warm." },
    ],
    hint: "Hibernation helps an animal use as little energy as it can. What would slow down?",
    meter: { heat: 10, label: "Flyway map +10%", story: "Hibernation is explained on the map" },
    discovery: { id: "batheart", name: "Slow bat hearts", who: "Nova", fact: "An active little brown bat's heart beats hundreds of times a minute. While it hibernates, its heart can slow to as few as 10 beats a minute." },
    answer: { kind: "multi", correct: ["temp", "heart", "breath", "fat"] },
    rightFeedback: "Hibernation is much more than a nap. The body cools and slows down to save energy all winter.",
    wrong: [
      { pick: "morning", hint: "A hibernating animal doesn't eat for weeks or months. It uses the fat it stored." },
      { pick: "fast", hint: "Hibernation saves energy. Would a faster heart save energy or use more?" },
      { missing: true, hint: "There are four changes. Think about temperature, heartbeat, breathing, and food." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The rainy spring", machine: "Sky Scope", icon: "water", speaker: "kai",
    line: "Last spring was very rainy at the Texas pond. The pond filled to the top, plants grew thick, and lots of bugs hatched. The frogs laid their eggs there.",
    question: "What most likely happened to the tadpoles in the pond?",
    hint: "Rain filled the pond and helped plants and bugs grow. What do tadpoles need to grow?",
    meter: { supplies: 1, label: "Field tags +1", story: "The rain's effect is on the map" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "They had plenty of water and food, so many grew into frogs." },
      { id: "b", text: "The rain made the tadpoles migrate." },
      { id: "c", text: "The rain made the tadpoles hibernate." },
      { id: "d", text: "Rain doesn't change anything for animals." },
    ],
    rightFeedback: "Lots of rain meant a full pond and lots of food. The tadpoles could grow and change into frogs.",
    wrong: [
      { choice: "b", hint: "Tadpoles can't leave the pond. They live in the water until they grow legs." },
      { choice: "c", hint: "Spring is a time for growing, not a winter rest. What did the rain give the tadpoles?" },
      { choice: "d", hint: "Rain filled the pond and helped plants and bugs grow. That changes a lot for tadpoles!" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The early freeze", machine: "Forecast Deck", icon: "relay", speaker: "vega",
    line: "Surprise! Our weather screens show a very cold fall coming to the far north this year. Lakes in Canada will freeze in October, weeks earlier than last year. Mission Control wants our predictions for the Migration Map.",
    question: "Part 1: Predict the November duck count at the Texas pond. Part 2: Sort what each animal will do this winter. Part 3: Write 2–3 sentences to Commander Vega explaining your duck prediction. Use cause and effect.",
    data: {
      title: "Lakes in the far north",
      columns: ["", "Last year", "This year (forecast)"],
      rows: [
        ["Lakes freeze over", "Early December", "Mid October"],
        ["November ducks at the Texas pond", "90", "?"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Predict the November duck count at the Texas pond.", choices: [
        { id: "a", text: "More than 90. The lakes freeze sooner, so ducks will fly south sooner." },
        { id: "b", text: "Fewer than 90. The ducks will stay on the frozen lakes." },
        { id: "c", text: "No ducks. It will be too cold for ducks to fly." },
        { id: "d", text: "Exactly 90. Weather never changes when animals migrate." },
      ] },
      { type: "sort", prompt: "Sort what each animal will do this winter.", bins: [
        { id: "migrate", label: "Migrate" },
        { id: "hibernate", label: "Hibernate" },
        { id: "stay", label: "Stay active" },
      ], items: [
        { id: "crane", label: "Sandhill crane" },
        { id: "groundhog", label: "Groundhog" },
        { id: "cardinal", label: "Cardinal" },
        { id: "freetail", label: "Mexican free-tailed bat" },
        { id: "bear", label: "Black bear" },
      ] },
      { type: "write", prompt: "Explain your duck prediction to Commander Vega. Use cause and effect.", minWords: 20 },
    ],
    rubric: ["Makes a clear prediction about the duck count", "Explains that frozen lakes mean ducks can't reach food", "Uses cause and effect (because, so) and the forecast as evidence"],
    hint: "Think about the banded duck. What made it fly to Texas? When will that happen this year?",
    meter: { heat: 20, label: "Flyway map +20%", story: "The Migration Map is complete" },
    discovery: { id: "sandhill", name: "Loud winter guests", who: "Kai", fact: "Many sandhill cranes spend the winter in Texas. Their loud, rattling calls can be heard more than a mile away." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "sort", bins: { crane: "migrate", groundhog: "hibernate", cardinal: "stay", freetail: "migrate", bear: "hibernate" } },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Great predicting! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "b", hint: "Ducks can't reach food on a frozen lake. Would they stay or leave?" },
      { step: 1, choice: "c", hint: "Ducks fly south to get away from frozen lakes. The cold makes them leave, not stop." },
      { step: 1, choice: "d", hint: "The forecast says the lakes freeze weeks sooner. Would that change when ducks arrive?" },
      { step: 2, item: "crane", hint: "Sandhill cranes fly south to places like Texas for winter. What is that called?" },
      { step: 2, item: "groundhog", hint: "A groundhog stays in its burrow in a deep winter rest. What is that called?" },
      { step: 2, item: "cardinal", hint: "Remember the cardinal at the snowy feeder. Did it leave or rest?" },
      { step: 2, item: "freetail", hint: "Remember the bat cloud from the Texas cave. Where did those bats go in the fall?" },
      { step: 2, item: "bear", hint: "Remember the bear whose tracker stopped moving. What was it doing?" },
    ],
  },
};

export default {
  id: "SCI.3.12A-XP",
  standard: "SCI.3.12A-XP",
  engine: "expedition_station",
  title: "The Migration Map",
  planet: "Cloudreach",
  outpost: "Sky Reef · flyway watch",
  grade: 3,
  subject: "Science",
  teks: "3.12A",
  supportingTeks: ["3.1E", "3.2B", "3.2C", "3.3A", "3.3C", "3.5B", "3.5G"],
  skillsChip: "3.12A · Weather and animal migration",
  iCan: "I can explain how temperature and rain change what animals do and how they grow. I can tell about migration, hibernation, and how plants go dormant.",
  blurb: "From the sky reef of Cloudreach, the crew can watch animals all over Earth. As winter comes, the animals start to move, rest, or hang on. The crew is building a map of it all.",
  mission: "Track real Earth animals as the seasons change, and explain how weather makes them migrate, hibernate, or go dormant.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.12 · CLOUDREACH FLYWAY",
  playableActs: [1, 2, 3],
  earthTrue: "Cloudreach and the sky scope are invented. Every animal, migration, fact, and data pattern in this quest is real Earth science.",
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Flyway map", heatUnit: "%", supplies: "Field tags", suppliesUnit: "tags" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. From the sky reef, our scope can see animals all over Earth.",
    "Winter is coming there. Some animals are taking long trips. Some are settling in for a long rest.",
    "Help us figure out what each animal does and why the weather makes it happen. Let's build the Migration Map. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Winter plans", "Act 2 · Follow the food", "Act 3 · Predict the freeze"],
    completes: [
      "The first animals are on the map, {firstName}! You even found the bear's den.",
      "You solved the banded duck mystery, {firstName}! The flyways are filling in.",
      "The Migration Map is complete, {firstName}! Mission Control is using your predictions.",
    ],
    teasers: [
      "Next on Cloudreach: Kai thinks birds fly south because they're cold, and a duck shows up wearing a mystery band. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the caribou vanish, a tree goes bare, and a big freeze is coming. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai and I already disagree about why birds fly south.",
      "Let's follow the food and find out.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our weather screens show a big change coming up north.",
      "Help us finish the map and make our predictions.",
    ],
  }),
  tasks,
};
