// Expedition Station — The Missing Map (ELA.3.6F-XP)
// Grade 3 · ELAR · Frostveil. Main standard 3.6F (make inferences and use
// evidence to support understanding); also practices 3.7C (text evidence),
// 3.7B (write a response), 3.3B (context clues and multiple-meaning words),
// 3.8A (theme), 3.8C (plot: sequence of events), 3.11D (edit). All passages are
// original, written for this quest. A light, kind mystery: the outpost map goes
// missing the night before a trek, and the clues lead to a frostkit den.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Commander Vega's Log, Morning", genre: "Log (informational narrative)" }, [
    [
      "Tomorrow the crew plans to hike to the Glass Falls.",
      "Snow covers the trail, so it is easy to get lost.",
      "Our map is printed on soft blue cloth so it will not rip in the wind.",
      "We cannot go without it.",
    ],
    [
      "This morning, the map was gone.",
      "Its tube was lying on the floor under the window.",
      "The tube was empty, and the cap had rolled under a chair.",
    ],
    [
      "The window was open a crack, and the room felt as cold as a freezer.",
      "I found three tiny wet spots on the windowsill.",
      "Each spot was shaped like a little flower with three petals.",
    ],
    [
      "When I asked about the map, Kai looked down at his boots.",
      "His cheeks turned pink.",
      "\"I think this might be my fault,\" he said quietly.",
    ],
  ]),
  B: {
    id: "B",
    title: "Kai's note to Vega",
    genre: "Note (has mistakes)",
    ...editText(
      "B",
      "Vega, I am so sorry about the map. I looked at it late last {nite} by the window. Then I rolled it up and put it back in the tube. The heater {were} too hot, so I opened the window a crack. {i} heard a soft scratching sound, but I thought it was only the wind. I forgot to close the window before I went to sleep.",
      {
        nite: ["night", "knight"],
        were: ["was", "are"],
        i: ["I", "eye"],
      }
    ),
  },
  C: passage("C", { title: "Nova's Field Notes: Frostkits", genre: "Informational text" }, [
    [
      "Frostkits are small snow animals that live near our outpost.",
      "They are about the size of a house cat.",
      "Their thick white fur helps them hide in the snow.",
    ],
    ["A frostkit has three toes on each paw.", "Its footprints look like tiny flowers pressed into the snow."],
    [
      "Frostkits are curious and gentle.",
      "They sleep in the daytime and explore at night.",
      "Most of the time, they stay far away from people.",
    ],
    [
      "In the cold season, a mother frostkit digs a den deep inside a snowdrift.",
      "She lines the den with soft, dry things, like moss, feathers, and scraps of cloth.",
      "A soft lining keeps her babies warm.",
    ],
  ]),
  D: passage("D", { title: "Kai's Report: The Torn Corner", genre: "Report (description)" }, [
    ["At sunrise, Nova found something half buried in the snow.", "It was one corner of our map, about as big as my hand."],
    [
      "The piece shows a small square for the outpost.",
      "A dotted line leaves the square and heads north.",
      "Next to the line, someone had written, \"Stay on the trail past Ridge Rock.\"",
    ],
    ["The edges of the piece are ragged, not straight like a cut from scissors.", "Along one side, Nova counted six tiny bite marks."],
    [
      "The piece was lying about twenty steps from the window.",
      "Next to it, a line of small flower-shaped prints led away across the snow.",
      "The prints ended at the big snowdrift behind Ridge Rock.",
    ],
  ]),
  E: passage("E", { title: "Nova's Log, Ridge Rock", genre: "Log (narrative)" }, [
    ["We followed the prints to the snowdrift behind Ridge Rock.", "Near the bottom, we found a round hole, just big enough for a small animal."],
    ["Kai shined a dim light inside.", "A mother frostkit blinked back at us.", "Three tiny kits were curled up beside her, fast asleep."],
    [
      "Under the kits, I could see a patch of blue cloth with dotted lines on it.",
      "Kai let out a long breath.",
      "\"Well, we found our map,\" he whispered.",
    ],
    [
      "Commander Vega shook her head, and then she smiled.",
      "\"The kits need it more than we do,\" she said softly.",
      "We tiptoed away, and nobody said a word until we were far from the den.",
    ],
    ["That night, I drew a new map from memory and from the torn corner.", "Kai closed the window and checked the latch twice."],
  ]),
  F: {
    id: "F",
    title: "Mission Report draft",
    genre: "Report (has mistakes)",
    ...editText(
      "F",
      "The crew's map went missing on {frostveil} last week. A curious frostkit carried it out the open window. The frostkits use the soft cloth to keep {there} babies warm. Nova {drawed} a new map for the trek. Kai {close} the window every night now.",
      {
        frostveil: ["Frostveil", "frostveils"],
        there: ["their", "they're"],
        drawed: ["drew", "drawn"],
        close: ["closes", "closing"],
      }
    ),
  },
};

// Passage B has no sentence ids from passage(); give its sentences ids so a
// task can ask students to highlight one.
passages.B.sentences = [
  { id: "B-s1", text: "Vega, I am so sorry about the map." },
  { id: "B-s2", text: "I looked at it late last nite by the window." },
  { id: "B-s3", text: "Then I rolled it up and put it back in the tube." },
  { id: "B-s4", text: "The heater were too hot, so I opened the window a crack." },
  { id: "B-s5", text: "i heard a soft scratching sound, but I thought it was only the wind." },
  { id: "B-s6", text: "I forgot to close the window before I went to sleep." },
];

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Open a crack", machine: "Decipher", icon: "static", speaker: "vega", passage: ["A"],
    line: "My log says the window was open a crack. Kai thinks that means the glass broke. Help us read it right.",
    question: "Read Passage A. \"The window was open a crack.\" What does a crack mean here?",
    hint: "The sentence says the window was OPEN a crack. How open do you think it was?",
    meter: { heat: 15, label: "Trail map +15%", story: "Vega's log is clear" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Opened just a tiny bit" },
      { id: "b", text: "A thin break in the glass" },
      { id: "c", text: "A loud snapping sound" },
      { id: "d", text: "Opened all the way" },
    ],
    rightFeedback: "Right! The window was open just a tiny bit.",
    wrong: [
      { choice: "b", hint: "A crack can be a break in glass. But the sentence says the window was OPEN a crack. What does that mean?" },
      { choice: "c", hint: "A crack can be a sound, like thunder. Does a sound fit how open a window is?" },
      { choice: "d", hint: "If the window were wide open, would Vega say \"a crack\"? Think small." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Spots on the sill", machine: "Trace", icon: "scan", speaker: "nova", passage: ["A"],
    line: "I think something small walked across the windowsill last night. Point my scanner at the proof.",
    question: "Nova thinks the wet spots were made by tiny feet. Highlight the sentence that best supports her idea.",
    hint: "Footprints have a shape. Which sentence tells what the spots looked like?",
    meter: { heat: 10, label: "Trail map +10%", story: "The scanner locks on the windowsill" },
    discovery: { id: "snowflake", name: "Snowflakes", who: "Nova", fact: "Most snowflakes have six sides or six points. Each one grows in its own way as it falls." },
    answer: { kind: "highlight", groups: [["A3.3"]] },
    rightFeedback: "Locked on! Spots shaped like little flowers could be tiny footprints.",
    wrong: [
      { sentence: "A3.2", hint: "That tells you there were spots. Which sentence tells what the spots looked like?" },
      { sentence: "A3.1", hint: "That tells about the window and the cold. What did the spots look like?" },
      { sentence: "A2.2", hint: "That tells where the tube was. Look at the clues on the windowsill." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Fix Kai's note", machine: "Repair", icon: "log", speaker: "kai", passage: ["B"],
    line: "I wrote Vega a note, but I was so upset that I made 3 mistakes. Can you fix them?",
    question: "Tap each mistake in Kai's note and pick the fix.",
    hint: "Read it slowly. Does every word look right and sound right?",
    meter: { heat: 10, label: "Trail map +10%", story: "Kai's note is ready for Vega" },
    answer: { kind: "edit", fixes: { "B:nite": "night", "B:were": "was", "B:i": "I" } },
    rightFeedback: "Note fixed! Now Vega can read exactly what happened.",
    wrong: [
      { token: "B:nite", hint: "Nite is not the right spelling. Which word means the time when it is dark?" },
      { token: "B:were", hint: "There is only one heater. Which word fits one thing: \"was\" or \"are\"?" },
      { token: "B:i", hint: "When you write about yourself, how do you always write the word I?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Read Kai's face", machine: "Read the Crew", icon: "crew", speaker: "nova", passage: ["A"],
    line: "Kai has been really quiet today. Vega's log tells us why.",
    question: "Part 1: How does Kai feel in Passage A? Part 2: Highlight a sentence that shows it.",
    parts: [
      { type: "choice", prompt: "How does Kai feel?", choices: [
        { id: "a", text: "Sorry, like he did something wrong" },
        { id: "b", text: "Excited about the trek" },
        { id: "c", text: "Angry at Vega" },
        { id: "d", text: "Sleepy and bored" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows how Kai feels.", passage: "A" },
    ],
    hint: "Look at the last paragraph. What do Kai's eyes and cheeks do?",
    meter: { supplies: 1, label: "Clues +1", story: "Nova gives Kai a friendly pat" },
    discovery: { id: "arcticfox", name: "Arctic foxes", who: "Nova", fact: "Arctic foxes grow thick white fur in winter. In summer, their fur turns brown or gray." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "highlight", groups: [["A4.1", "A4.2", "A4.3"]] }] },
    rightFeedback: "Yes! Kai looks down, his cheeks turn pink, and he says it might be his fault.",
    wrong: [
      { step: 1, choice: "b", hint: "Would someone who is excited look down at his boots? Read the last paragraph." },
      { step: 1, choice: "c", hint: "Kai doesn't say anything angry. What does he say about the map?" },
      { step: 1, choice: "d", hint: "Nothing says Kai is sleepy. Why might his cheeks turn pink?" },
      { step: 2, sentence: "A2.1", hint: "That tells what happened to the map, not how Kai feels." },
      { step: 2, sentence: "A3.1", hint: "That is about the window. Find a sentence about Kai." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Who took the map?", machine: "Trace", icon: "snap", speaker: "vega", passage: ["A", "C"],
    line: "Surprise! Nova just sent her field notes about frostkits. Put them next to my log. I think we have a suspect.",
    question: "Part 1: What most likely took the map? Part 2: Highlight TWO clues, one from Passage A and one from Passage C, that support your answer.",
    parts: [
      { type: "choice", prompt: "What most likely took the map?", choices: [
        { id: "a", text: "A curious frostkit" },
        { id: "b", text: "Kai hid the map" },
        { id: "c", text: "The wind blew it out of the tube" },
        { id: "d", text: "Nova borrowed it" },
      ] },
      { type: "highlight", prompt: "Highlight one clue from Passage A and one from Passage C.", passage: ["A", "C"], count: 2 },
    ],
    hint: "The log never names the thief. Compare the spots on the windowsill with what frostkit footprints look like.",
    meter: { heat: 10, label: "Trail map +10%", story: "The crew has a suspect" },
    discovery: { id: "tracks", name: "Animal tracks", who: "Kai", fact: "Scientists can tell which animal walked by looking at the shape and size of its tracks in snow or mud." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A3.3", "A3.1"], ["C2.2", "C2.1", "C4.2"]] },
    ] },
    rightFeedback: "Great detective work! Flower-shaped spots on the sill match frostkit footprints.",
    wrong: [
      { step: 1, choice: "b", hint: "Kai feels bad, but that doesn't mean he hid it. Do Kai's boots make flower-shaped prints?" },
      { step: 1, choice: "c", hint: "Wind can blow things, but could wind leave little flower-shaped spots on the windowsill?" },
      { step: 1, choice: "d", hint: "Neither passage says Nova took the map. Look at the clues on the windowsill." },
      { step: 2, sentence: "C3.3", hint: "Careful! That clue makes a frostkit seem LESS likely. Find a clue that matches the windowsill." },
      { step: 2, sentence: "A4.3", hint: "That shows how Kai feels, not what took the map." },
      { step: 2, sentence: "C1.2", hint: "That tells how big a frostkit is. Which clue matches the spots Vega found?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Why the map?", machine: "Trace", icon: "scan", speaker: "kai", passage: ["C"],
    line: "Okay, a frostkit took it. But why would a snow animal want a map? It can't read!",
    question: "Kai wonders why a frostkit would take a soft cloth map. Highlight the sentence in Nova's notes that helps explain it.",
    hint: "Remember, the map is made of soft cloth. What do frostkits do with soft things?",
    meter: { heat: 10, label: "Trail map +10%", story: "Kai understands the frostkit" },
    discovery: { id: "snowden", name: "Snow dens", who: "Nova", fact: "Snow has lots of air trapped inside it. That air holds in heat, so a den dug in snow can stay much warmer than the wind outside." },
    answer: { kind: "highlight", groups: [["C4.2", "C4.3"]] },
    rightFeedback: "That's it! A mother frostkit lines her den with soft things, like cloth.",
    wrong: [
      { sentence: "C1.3", hint: "That tells how frostkits hide. Why would one want something soft?" },
      { sentence: "C3.2", hint: "That tells when frostkits are awake. It explains WHEN, not WHY." },
      { sentence: "C4.1", hint: "Close! That tells where the den is. Which sentence tells what goes inside it?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Ragged edges", machine: "Decipher", icon: "static", speaker: "nova", passage: ["D"],
    line: "Kai used a big word in his report. Let's make sure we know it before we go on.",
    question: "\"The edges of the piece are ragged, not straight like a cut from scissors.\" What does ragged mean?",
    hint: "The sentence tells you what ragged is NOT. What is the opposite of a straight scissor cut?",
    meter: { supplies: 1, label: "Clues +1", story: "Nova adds a word to the clue board" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Rough and uneven" },
      { id: "b", text: "Smooth and even" },
      { id: "c", text: "Wet and cold" },
      { id: "d", text: "Bright blue" },
    ],
    rightFeedback: "Right! Ragged edges are rough and uneven, not neat like a scissor cut.",
    wrong: [
      { choice: "b", hint: "The sentence says ragged is NOT like a straight cut. Would smooth edges be straight?" },
      { choice: "c", hint: "The piece was in the snow, but the sentence compares ragged to a scissor cut. Look at that clue." },
      { choice: "d", hint: "The map is blue, but the sentence is about the edges and how they were cut." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Animal or person?", machine: "Trace", icon: "scan", speaker: "vega", passage: ["D"],
    line: "Before we go looking, I want proof that an animal took the map, not a person.",
    question: "Which clues in Kai's report show that an animal took the map, not a person? Pick every one.",
    hint: "Think about what a person would NOT leave behind.",
    meter: { heat: 5, label: "Trail map +5%", story: "Vega is convinced" },
    discovery: { id: "northup", name: "North on maps", who: "Kai", fact: "On most maps, north is at the top. A compass rose shows which way is north, south, east, and west." },
    answer: { kind: "multi", correct: ["a", "b"] },
    items: [
      { id: "a", text: "Tiny bite marks along one side" },
      { id: "b", text: "Small flower-shaped prints in the snow" },
      { id: "c", text: "Words written on the piece" },
      { id: "d", text: "A dotted line that heads north" },
      { id: "e", text: "The piece was found at sunrise" },
    ],
    rightFeedback: "Right! People don't leave bite marks or flower-shaped prints.",
    wrong: [
      { pick: "c", hint: "Those words were written when the map was made. Do they show who took it?" },
      { pick: "d", hint: "The dotted line is part of the map itself. Does it show who took it?" },
      { pick: "e", hint: "Sunrise tells WHEN the piece was found, not WHO took the map." },
      { missing: true, hint: "There is more than one clue. Look at paragraphs 3 and 4 of Kai's report." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "What happened that night", machine: "Timeline", icon: "log", speaker: "nova", passage: ["B", "A"],
    line: "Let's line up what happened the night the map went missing. Kai's note has most of the answers.",
    question: "Part 1: Put the events in order. Part 2: Highlight the sentence in Kai's note that shows when the frostkit was in the room.",
    parts: [
      { type: "order", prompt: "Put the events in order, first to last.", items: [
        { id: "e3", text: "Kai heard a soft scratching sound." },
        { id: "e5", text: "Vega found the empty tube on the floor." },
        { id: "e1", text: "Kai rolled up the map and put it back in the tube." },
        { id: "e4", text: "A frostkit carried the map out the window." },
        { id: "e2", text: "Kai opened the window a crack." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows when the frostkit was in the room.", passage: "B" },
    ],
    hint: "Use time words like \"then\" and \"so\" in Kai's note. Vega's log is from the next morning.",
    meter: { supplies: 1, label: "Clues +1", story: "The timeline is on the clue board" },
    discovery: { id: "bearpaws", name: "Polar bear paws", who: "Nova", fact: "Polar bears have fur on the bottoms of their paws. It helps them grip the ice and keeps their feet warm." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["e1", "e2", "e3", "e4", "e5"] },
      { kind: "highlight", groups: [["B-s5"]] },
    ] },
    rightFeedback: "Perfect timeline! That \"wind\" Kai heard was really the frostkit.",
    wrong: [
      { step: 1, position: 0, hint: "What did Kai do with the map first, before he touched the window?" },
      { step: 1, position: 1, hint: "The window had to be open before anything could come in. What did Kai do after he put the map away?" },
      { step: 1, position: 2, hint: "The scratching sound came before the map was gone. What did Kai hear?" },
      { step: 1, position: 3, hint: "Vega found the tube in the morning, after everything else happened." },
      { step: 2, sentence: "B-s4", hint: "That is when the window opened. Which sentence tells about a sound in the room?" },
      { step: 2, sentence: "B-s6", hint: "That tells what Kai forgot. Which sentence has a clue about the frostkit?" },
      { step: 2, sentence: "B-s3", hint: "That's when Kai put the map away. What did he hear later?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Snow is falling!", machine: "Read the Crew", icon: "quake", speaker: "vega", passage: ["D", "C"],
    line: "Surprise! Snow is starting to fall, and soon the prints will be covered. We have to decide where to search right now.",
    question: "Part 1: Where is the map most likely? Part 2: Highlight TWO sentences, one from each passage, that prove it. Part 3: Pick the best search plan.",
    parts: [
      { type: "choice", prompt: "Where is the map most likely?", choices: [
        { id: "a", text: "In the snowdrift behind Ridge Rock" },
        { id: "b", text: "At the Glass Falls" },
        { id: "c", text: "Under a chair in the outpost" },
        { id: "d", text: "Blowing along the north trail" },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from Kai's report and one from Nova's notes.", passage: ["D", "C"], count: 2 },
      { type: "choice", prompt: "Pick the best search plan for the crew.", choices: [
        { id: "a", text: "Let's search everywhere until we find it." },
        { id: "b", text: "Let's search the snowdrift behind Ridge Rock, because the prints end there and frostkits dig dens in snowdrifts." },
        { id: "c", text: "Frostkits are cute, so let's go see one." },
        { id: "d", text: "Let's go to the Glass Falls, because the map shows the trail." },
      ] },
    ],
    hint: "Where did the prints end? Where do mother frostkits dig their dens?",
    meter: { heat: 10, label: "Trail map +10%", story: "The crew heads for Ridge Rock" },
    discovery: { id: "whitesnow", name: "Clear ice, white snow", who: "Kai", fact: "A single ice crystal is clear like glass. A pile of snow looks white because light bounces around all the tiny crystals." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["D4.3", "D4.2"], ["C4.1"]] },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Smart thinking! The prints and Nova's notes both point to the snowdrift.",
    wrong: [
      { step: 1, choice: "b", hint: "The torn corner shows the trail, but where did the prints lead?" },
      { step: 1, choice: "c", hint: "The tube was on the floor, but a piece of the map was found outside. Where did the prints go?" },
      { step: 1, choice: "d", hint: "The dotted line on the map heads north, but where did the frostkit's prints end?" },
      { step: 2, sentence: "D2.3", hint: "Those words are written on the map. They don't show where the map went." },
      { step: 2, sentence: "C3.2", hint: "That tells when frostkits are awake, not where they live." },
      { step: 2, sentence: "D4.1", hint: "That tells where the piece was found. Where did the prints end?" },
      { step: 3, choice: "a", hint: "The snow is falling fast. Which plan uses the clues to pick one place?" },
      { step: 3, choice: "c", hint: "That is an opinion, not a plan that uses evidence." },
      { step: 3, choice: "d", hint: "The frostkit didn't follow the trail. Where did its prints go?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Inside the den", machine: "Trace", icon: "scan", speaker: "nova", passage: ["E"],
    line: "We found the den! Kai says we found the map, too. Let's make sure the log proves it.",
    question: "Kai whispers, \"We found our map.\" Highlight the sentence that shows how he knows.",
    hint: "Kai is saying what he thinks. Which sentence tells what the crew SAW?",
    meter: { supplies: 1, label: "Clues +1", story: "The mystery is solved" },
    discovery: { id: "bearcubs", name: "Polar bear cubs", who: "Nova", fact: "Polar bear cubs are born in snow dens in the middle of winter. They stay inside with their mother for a few months." },
    answer: { kind: "highlight", groups: [["E3.1"]] },
    rightFeedback: "Right! Blue cloth with dotted lines is the map.",
    wrong: [
      { sentence: "E3.3", hint: "That is what Kai says. Which sentence shows what the crew SAW that made him say it?" },
      { sentence: "E2.2", hint: "That shows a frostkit lives there. What shows the map is there?" },
      { sentence: "E1.2", hint: "That shows the crew found a den. What did they see inside?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Vega's choice", machine: "Brief", icon: "brief", speaker: "kai", passage: ["E"],
    line: "Vega left our map in the den! I want to understand why she did that.",
    question: "Why did Commander Vega let the frostkits keep the map? Write 1–2 sentences. Use a detail from Nova's log.",
    hint: "Read paragraph 4 of Nova's log. What did Vega say about the kits?",
    meter: { heat: 5, label: "Trail map +5%", story: "Kai understands Vega's choice" },
    answer: { kind: "write", minWords: 15 },
    minWords: 15,
    teacherScored: true,
    rubric: ["Explains why Vega left the map", "Uses a detail from Nova's log", "Complete sentences with capitals and end punctuation"],
    rightFeedback: "Thanks! Your teacher will read your answer.",
    wrong: [],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The lesson", machine: "Brief", icon: "brief", speaker: "vega", passage: ["E"],
    line: "Mission Control likes every report to end with a lesson. What did this mystery teach us?",
    question: "What lesson does the crew learn at Ridge Rock?",
    hint: "A lesson is bigger than one animal or one map. What did Vega choose to do, and why?",
    meter: { supplies: 1, label: "Clues +1", story: "Vega adds the lesson to the mission file" },
    discovery: { id: "northstar", name: "The North Star", who: "Kai", fact: "Long ago, travelers used the North Star to find which way was north. It stays in almost the same spot in the night sky." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Frostkits are small and white." },
      { id: "b", text: "Being kind can matter more than getting back what is yours." },
      { id: "c", text: "Always carry two maps." },
      { id: "d", text: "Maps should be made of cloth." },
    ],
    rightFeedback: "Yes! The crew chose kindness over getting their map back.",
    wrong: [
      { choice: "a", hint: "That's a fact about frostkits. What lesson did the crew learn?" },
      { choice: "c", hint: "That might be a good idea, but the log doesn't talk about it. What did Vega choose to do?" },
      { choice: "d", hint: "That's about the map, not a lesson. Why did Vega leave the map with the kits?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Checked twice", machine: "Read the Crew", icon: "crew", speaker: "nova", passage: ["E"],
    line: "Last night Kai checked the window latch twice. He never does that!",
    question: "Why did Kai check the latch twice?",
    hint: "Think about how the frostkit got in, and how Kai felt about it.",
    meter: { heat: 5, label: "Trail map +5%", story: "The outpost is snug for the night" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "He wanted to be sure the window was shut, so nothing would get in again." },
      { id: "b", text: "The latch was broken." },
      { id: "c", text: "He wanted to let the cold air in." },
      { id: "d", text: "He forgot how to close a window." },
    ],
    rightFeedback: "Right! Kai doesn't want the window left open again.",
    wrong: [
      { choice: "b", hint: "The log never says the latch was broken. Why would Kai want to be extra sure?" },
      { choice: "c", hint: "A closed latch keeps cold air out. What is Kai trying to stop?" },
      { choice: "d", hint: "Kai closed it just fine. Remember how the frostkit got in." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Send the mission report", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["F", "A", "C", "D", "E"],
    line: "Surprise! Mission Control wants our report before the trek. Fix it, add proof, and send it.",
    question: "Part 1: Fix the 4 mistakes in the report. Part 2: Pick the best evidence to add. Part 3: Write 2–3 sentences telling what happened to the map, using clues from two different passages.",
    parts: [
      { type: "edit", prompt: "Fix the 4 mistakes in the report.", passage: "F" },
      { type: "choice", prompt: "Pick the best evidence to add to the report.", choices: [
        { id: "a", text: "Frostkits are the cutest animals on Frostveil." },
        { id: "b", text: "Small flower-shaped prints led from the window to the den behind Ridge Rock." },
        { id: "c", text: "The hike to the Glass Falls is long." },
        { id: "d", text: "Kai likes warm rooms." },
      ] },
      { type: "write", prompt: "Tell what happened to the map. Use clues from two different passages.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["Tells what happened to the map", "Uses clues from two different passages", "Complete sentences with capitals and end punctuation"],
    hint: "Good evidence is a clue from the text that proves what happened.",
    meter: { heat: 10, label: "Trail map +10%", story: "Mission Control approves the trek" },
    discovery: { id: "compass", name: "Compasses", who: "Nova", fact: "A compass needle points north because Earth acts like a giant magnet." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "F:frostveil": "Frostveil", "F:there": "their", "F:drawed": "drew", "F:close": "closes" } },
      { kind: "choice", correct: "b" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Report sent! Your teacher will read what you wrote.",
    wrong: [
      { step: 1, token: "F:frostveil", hint: "Frostveil is the name of a planet. What do names start with?" },
      { step: 1, token: "F:there", hint: "The babies belong to the frostkits. Which word shows that something belongs to someone?" },
      { step: 1, token: "F:drawed", hint: "Drawed isn't a real word. Yesterday I draw, or yesterday I ___?" },
      { step: 1, token: "F:close", hint: "Kai is one person. Kai close or Kai closes?" },
      { step: 2, choice: "a", hint: "That's an opinion, not evidence. Which choice is a clue from the text?" },
      { step: 2, choice: "c", hint: "That's true, but it doesn't prove what happened to the map." },
      { step: 2, choice: "d", hint: "That doesn't tell what happened to the map. Which clue proves it?" },
    ],
  },
};

export default {
  id: "ELA.3.6F-XP",
  standard: "ELA.3.6F-XP",
  engine: "expedition_station",
  title: "The Missing Map",
  planet: "Frostveil",
  outpost: "North Ridge Outpost · morning shift",
  grade: 3,
  subject: "ELAR",
  teks: "3.6F",
  supportingTeks: ["3.7C", "3.7B", "3.3B", "3.8A", "3.8C", "3.11D"],
  skillsChip: "3.6F · Make inferences and use evidence",
  iCan: "I can make inferences and prove them with clues from the text. I can fix mistakes in a note or report.",
  blurb: "The night before a big trek on icy Frostveil, the crew's map disappears. Tiny wet spots, a torn corner, and a trail of prints are the only clues.",
  mission: "Read the crew's logs, notes, and reports to figure out what happened to the map, then send the report to Mission Control.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.6F · FROSTVEIL NORTH RIDGE",
  playableActs: [1, 2, 3],
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Trail map", heatUnit: "%", supplies: "Clues", suppliesUnit: "clues" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega on Frostveil. We have a mystery.",
    "Tomorrow the crew hikes to the Glass Falls, but this morning our map was gone. Nobody knows where it went.",
    "The clues are in our logs and notes. Read carefully and prove every idea. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The empty tube", "Act 2 · The torn corner", "Act 3 · The den at Ridge Rock"],
    completes: [
      "You found our suspect, {firstName}! A curious frostkit came in through the window.",
      "Great work, {firstName}! The clues point to the snowdrift behind Ridge Rock.",
      "Your report is on its way to Mission Control, {firstName}! The crew is ready for the trek.",
    ],
    teasers: [
      "Next on Frostveil: Nova found a torn piece of the map in the snow. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the crew follows the prints to Ridge Rock. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. At sunrise I found a torn corner of our map in the snow.",
      "Kai wrote a report about it. Let's see where the clues lead.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. We followed the prints to Ridge Rock.",
      "Read Nova's log to find out what we saw, then help us send the report.",
    ],
  }),
  tasks,
};
