// Expedition Station — The Mixing Lab (SCI.4.6B-XP)
// Grade 4 · Science · Cloudreach (sky reef). Main standard 4.6B (investigate
// and compare a variety of mixtures, including solutions that are composed of
// liquids in liquids and solids in liquids); also 4.6C (demonstrate that
// matter is conserved when mixtures such as soil and water or oil and water
// are formed), and practices 4.1B (plan and conduct fair tests), 4.1D (measure
// with tools like balances), 4.2B (analyze data for patterns), 4.3A
// (explanations supported by data), 4.3C (respectful scientific discussion),
// 4.5B (cause and effect), 4.5E (matter is conserved).
//
// Earth-true rule: Cloudreach and the Mix Deck are invented, but every
// material in the lab is a real Earth material and behaves as it does on Earth.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Jars in the wind", machine: "Mix Deck", icon: "cells", speaker: "nova",
    line: "A big gust rattled the Mix Deck, and the labels blew off our jars. Let's sort them back onto the right shelves.",
    question: "Sort each jar: is it a mixture where you can still see the parts, or a solution that looks the same all the way through?",
    hint: "Look closely at each jar. Can you still pick out the different parts, or does it look the same everywhere?",
    meter: { heat: 10, label: "Mix Deck +10%", story: "The jars are back on their shelves" },
    discovery: { id: "airmix", name: "Air is a mixture", who: "Nova", fact: "Air is a mixture of gases. It is mostly nitrogen, and about one part in every five is oxygen." },
    answer: { kind: "sort", bins: { j1: "mix", j2: "sol", j3: "sol", j4: "mix", j5: "sol", j6: "mix", j7: "mix" } },
    rightFeedback: "Sand, oil, trail mix, and pebbles with iron filings all keep parts you can see. Salt, sugar, and food coloring spread evenly through the water, so those are solutions.",
    sort: {
      bins: [{ id: "mix", label: "Mixture: you can still see the parts" }, { id: "sol", label: "Solution: looks the same all the way through" }],
      items: [
        { id: "j1", label: "Sand + water" },
        { id: "j2", label: "Salt + water" },
        { id: "j3", label: "Sugar + water" },
        { id: "j4", label: "Oil + water" },
        { id: "j5", label: "Food coloring + water" },
        { id: "j6", label: "Trail mix" },
        { id: "j7", label: "Pebbles + iron filings" },
      ],
    },
    wrong: [
      { item: "j4", hint: "Oil and water swirl together when you shake them. Let the jar sit. Does the oil stay spread out, or make its own layer?" },
      { item: "j5", hint: "The color spreads through all the water. Can you still pick out drops of coloring, or is it the same color everywhere?" },
      { item: "j1", hint: "Sand makes the water cloudy for a moment. Then what settles on the bottom?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The vanishing test", machine: "Stir Station", icon: "flask", speaker: "kai",
    line: "I put a spoonful of each material into its own cup of water and stirred for one minute.",
    question: "Pick every material that dissolves in water.",
    items: [
      { id: "salt", text: "Salt" },
      { id: "sugar", text: "Sugar" },
      { id: "color", text: "Food coloring" },
      { id: "sand", text: "Sand" },
      { id: "oil", text: "Cooking oil" },
      { id: "iron", text: "Iron filings" },
    ],
    hint: "When something dissolves, it spreads out so evenly that you can't see separate bits of it anymore.",
    meter: { supplies: 1, label: "Sample jars +1", story: "The dissolving list is posted" },
    discovery: { id: "deadsea", name: "The Dead Sea", who: "Kai", fact: "The Dead Sea, between Israel and Jordan, is almost ten times saltier than the ocean. So much salt is dissolved in it that people float easily on top." },
    answer: { kind: "multi", correct: ["salt", "sugar", "color"] },
    rightFeedback: "Salt, sugar, and food coloring dissolve. Sand and iron filings sink, and oil floats in a layer on top.",
    wrong: [
      { pick: "sand", hint: "Sand swirls around while you stir. Wait a minute. Where does it end up?" },
      { pick: "oil", hint: "Look at the top of the cup. Did the oil spread through the water, or did it make its own layer?" },
      { pick: "iron", hint: "Iron filings sink to the bottom and stay there. Did they dissolve?" },
      { missing: true, hint: "Three materials dissolve. Don't forget the liquid one." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Liquid meets liquid", machine: "Stir Station", icon: "water", speaker: "nova",
    line: "Some solutions are a solid dissolved in a liquid. Others are a liquid dissolved in a liquid.",
    question: "Which of these is a liquid dissolved in a liquid?",
    hint: "Check both parts. Which one starts as two liquids?",
    meter: { heat: 5, label: "Mix Deck +5%", story: "Nova labels the solution shelf" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Food coloring stirred into water" },
      { id: "b", text: "Salt stirred into water" },
      { id: "c", text: "Sugar stirred into water" },
      { id: "d", text: "Sand stirred into water" },
    ],
    rightFeedback: "Food coloring is a liquid, and it dissolves in water, another liquid.",
    wrong: [
      { choice: "b", hint: "Salt water is a solution, but what was the salt before you stirred it in: a solid or a liquid?" },
      { choice: "c", hint: "Sugar dissolves, but sugar grains are solid. Look for two liquids." },
      { choice: "d", hint: "Sand doesn't dissolve at all, and it's a solid. Look for two liquids that make a solution." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Weigh the muddy jar", machine: "Balance Bench", icon: "dial", speaker: "kai",
    line: "The balance says the water weighs 250 g and the sand weighs 40 g. Now I'll pour the sand into the water.",
    question: "What will the balance read for the jar of sand and water together? (Don't count the jar.)",
    unit: "g",
    hint: "Nothing gets added and nothing escapes. What happens to the two masses?",
    meter: { supplies: 1, label: "Sample jars +1", story: "The first mass is logged" },
    answer: { kind: "number", value: 290 },
    rightFeedback: "250 g + 40 g = 290 g. The mixture has the same mass as its parts.",
    wrong: [
      { value: 250, hint: "250 g is only the water. The sand is still in the jar. Does it still have mass?" },
      { value: 210, hint: "The sand went into the jar, not out of it. Should you add or subtract?" },
      { value: 40, hint: "40 g is only the sand. What about the water?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The gust-tub rescue", machine: "Separation Rig", icon: "snap", speaker: "vega",
    line: "Surprise! A gust knocked four jars into one tub: pebbles, iron filings, sand, and sugar. The whole tub weighed 500 g. We need every material back.",
    question: "Part 1: Put the steps in order. Part 2: Why does the filter catch the sand but not the sugar? Part 3: How much sugar should the crew get back?",
    parts: [
      { type: "order", prompt: "Put the steps in order to get all four materials back.", items: [
        { id: "sieve", text: "Shake the dry pile through a sieve to catch the pebbles" },
        { id: "magnet", text: "Sweep a magnet over the dry pile to pull out the iron filings" },
        { id: "water", text: "Add water and stir so the sugar dissolves" },
        { id: "filter", text: "Pour it through a filter to catch the sand" },
        { id: "evaporate", text: "Let the water evaporate to get the sugar back" },
      ] },
      { type: "choice", prompt: "Why does the filter catch the sand but not the sugar?", choices: [
        { id: "a", text: "The sugar dissolved into pieces too tiny to see, so it slips through the filter with the water. Sand grains are too big." },
        { id: "b", text: "Sugar is magnetic, so it pulls itself through the filter." },
        { id: "c", text: "The sand dissolved, and the sugar did not." },
        { id: "d", text: "Filters only catch things that are dark." },
      ] },
      { type: "number", prompt: "The crew got back 180 g of pebbles, 60 g of iron filings, and 150 g of sand. How many grams of sugar should be left after the water evaporates?", unit: "g" },
    ],
    hint: "Use a different property for each material: size, magnetism, and dissolving. Then remember the whole tub weighed 500 g.",
    meter: { heat: 10, label: "Mix Deck +10%", story: "Every jar is full again" },
    discovery: { id: "goldpan", name: "Panning for gold", who: "Kai", fact: "Gold is very heavy for its size. Miners swirl sand and water in a pan, and the gold settles to the bottom while the lighter sand washes away." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["sieve", "magnet", "water", "filter", "evaporate"], alsoAccept: [["magnet", "sieve", "water", "filter", "evaporate"]] },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 110 },
    ] },
    rightFeedback: "All four materials are back, and 180 + 60 + 150 + 110 = 500 g. Nothing was lost!",
    wrong: [
      { step: 1, position: 2, hint: "The sugar has to dissolve before the filter can separate it from the sand. What comes first?" },
      { step: 1, position: 3, hint: "If the water evaporates first, the sand and sugar end up mixed again. Filter first." },
      { step: 2, choice: "b", hint: "Sugar isn't magnetic. What happened to the sugar when it went into the water?" },
      { step: 2, choice: "c", hint: "Sand doesn't dissolve. Which one disappeared into the water?" },
      { step: 2, choice: "d", hint: "Color doesn't matter to a filter. Think about the size of the pieces." },
      { step: 3, value: 890, hint: "The 500 g already includes the sugar. Should you add everything, or take away what you already got back?" },
      { step: 3, value: 500, hint: "500 g is the whole tub. Take away the pebbles, iron, and sand." },
      { step: 3, value: 320, hint: "You took away the pebbles. Take away the iron filings and sand too." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Does sweet weigh nothing?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Once sugar or salt dissolves, it\'s gone. You can\'t see it, so it can\'t weigh anything."',
    nova: 'Nova: "Look at my balance log. Every jar got heavier by exactly what I stirred in."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    data: {
      title: "Nova's balance log",
      columns: ["Jar", "Water", "Stirred in", "Mass after it dissolved"],
      rows: [
        ["A", "200 g", "25 g sugar", "225 g"],
        ["B", "150 g", "10 g salt", "160 g"],
        ["C", "300 g", "40 g sugar", "340 g"],
      ],
    },
    hint: "If the dissolved sugar weighed nothing, what would Jar A weigh after stirring?",
    meter: { heat: 5, label: "Mix Deck +5%", story: "Kai double-checks the balance" },
    discovery: { id: "lavoisier", name: "The careful weigher", who: "Nova", fact: "In the 1700s, a French scientist named Antoine Lavoisier weighed materials very carefully before and after they changed. He showed that matter is not lost. It only changes form." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. In every jar, the mass after equals the water plus what was stirred in. The dissolved sugar and salt are still there, in pieces too small to see." },
      { id: "B", text: "Nova, because sugar water tastes sweet." },
      { id: "C", text: "Kai. If you can't see something, it has no mass." },
      { id: "D", text: "Kai. The water ate the sugar and salt." },
    ],
    writtenPrompt: "Tell Kai in your own words how the balance log proves the sugar and salt are still in the water.",
    debateHints: {
      wrongWho: "Check Jar A. If the sugar weighed nothing, the balance would read 200 g. What does it read?",
      wrongReason: "Right person, check the reason. What do the numbers in the log prove?",
      right: "Nova is right. The mass after mixing always equals the mass of the parts.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The smudged log", machine: "Balance Bench", icon: "log", speaker: "nova",
    line: "Rain from the reef clouds smudged one number in my mass table. Can you figure it out?",
    question: "How many grams of salt did Nova stir into the water?",
    unit: "g",
    data: {
      title: "Mass before and after mixing",
      columns: ["Mixture", "Liquid", "Added", "Mixed jar"],
      rows: [
        ["Oil + water", "180 g water", "45 g oil", "225 g"],
        ["Soil + water", "300 g water", "120 g soil", "420 g"],
        ["Salt + water", "200 g water", "? g salt", "218 g"],
      ],
    },
    hint: "In the first two rows, the liquid plus what was added equals the mixed jar. What goes with 200 g to make 218 g?",
    meter: { supplies: 1, label: "Sample jars +1", story: "The mass table is complete" },
    answer: { kind: "number", value: 18 },
    rightFeedback: "218 g − 200 g = 18 g of salt. The parts always add up to the mixture.",
    wrong: [
      { value: 418, hint: "The 218 g already includes the water. Should you add or subtract?" },
      { value: 218, hint: "218 g is the whole jar, water and salt together. How much of it is salt?" },
      { value: 200, hint: "200 g is the water. How much more than that does the jar weigh?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Plan a fair stir", machine: "Test Bay", icon: "scan", speaker: "kai",
    line: "I want to find out if stirring makes sugar dissolve faster. I'll set up two cups.",
    question: "Which setup is a fair test of stirring?",
    hint: "In a fair test, you change only one thing. Everything else stays the same.",
    meter: { heat: 5, label: "Mix Deck +5%", story: "Kai's test is ready to run" },
    discovery: { id: "smallpieces", name: "Small pieces win", who: "Nova", fact: "Crushed sugar dissolves faster than a sugar cube. Smaller pieces have more surface touching the water." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Same water temperature, same amount of water and sugar. Stir one cup and don't stir the other." },
      { id: "b", text: "Stir the cup of warm water. Don't stir the cup of cold water." },
      { id: "c", text: "Put more sugar in the stirred cup and less in the other." },
      { id: "d", text: "Use a sugar cube in the stirred cup and loose sugar in the other." },
    ],
    rightFeedback: "Only the stirring changes, so any difference comes from stirring.",
    wrong: [
      { choice: "b", hint: "Two things changed: stirring and temperature. Which one made the difference?" },
      { choice: "c", hint: "The amount of sugar changed too. Keep everything the same except stirring." },
      { choice: "d", hint: "The size of the sugar pieces changed too. Keep everything the same except stirring." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The oily puddle", machine: "Separation Rig", icon: "scoop", speaker: "nova",
    line: "Someone spilled cooking oil into our rinse water. We need the oil out before we water the reef garden.",
    question: "What is the best way to separate the oil from the water?",
    hint: "What happened to the oil in the vanishing test? Where did it go in the cup?",
    meter: { supplies: 1, label: "Sample jars +1", story: "The rinse water is clean again" },
    discovery: { id: "oilboom", name: "Oil spill booms", who: "Nova", fact: "Oil is less dense than water, so it floats. After an oil spill, cleanup crews circle the oil with floating barriers called booms." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Let it sit so the oil floats to the top, then scoop the oil off." },
      { id: "b", text: "Pull the oil out with a magnet." },
      { id: "c", text: "Pour it through a sieve." },
      { id: "d", text: "Stir it hard until the oil dissolves." },
    ],
    rightFeedback: "Oil doesn't dissolve in water. It floats in its own layer, so you can scoop it off the top.",
    wrong: [
      { choice: "b", hint: "Oil isn't magnetic. What does oil do when it sits in water?" },
      { choice: "c", hint: "Both liquids would pour right through the sieve holes. Where does the oil float?" },
      { choice: "d", hint: "Oil doesn't dissolve in water, no matter how hard you stir. It comes back as a layer." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Four cups, two questions", machine: "Test Bay", icon: "quake", speaker: "vega",
    line: "Surprise! Nova and Kai ran one test for both of their questions: does stirring matter, and does temperature matter? Each cup got 10 g of the same sugar in 200 mL of water.",
    question: "Part 1: Which two cups test only stirring? Part 2: What pattern do you see? Part 3: How many seconds faster was the stirred cold cup? Part 4: Pick everything that stayed the same in every cup.",
    data: {
      title: "Seconds for 10 g of sugar to dissolve",
      columns: ["Cup", "Water", "Stirred?", "Seconds"],
      rows: [
        ["A", "Cold (10°C)", "No", "600"],
        ["B", "Cold (10°C)", "Yes", "150"],
        ["C", "Warm (40°C)", "No", "300"],
        ["D", "Warm (40°C)", "Yes", "60"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which two cups test ONLY stirring?", choices: [
        { id: "ab", text: "Cups A and B" },
        { id: "ad", text: "Cups A and D" },
        { id: "bc", text: "Cups B and C" },
        { id: "ac", text: "Cups A and C" },
      ] },
      { type: "choice", prompt: "What pattern do you see?", choices: [
        { id: "a", text: "Warmer water and stirring both made the sugar dissolve faster." },
        { id: "b", text: "Only stirring made a difference." },
        { id: "c", text: "Only temperature made a difference." },
        { id: "d", text: "Cold water made the sugar dissolve faster." },
      ] },
      { type: "number", prompt: "In cold water, how many seconds faster did the sugar dissolve when it was stirred?", unit: "seconds" },
      { type: "multi", prompt: "Pick everything that stayed the same in every cup.", choices: [
        { id: "sugar", text: "The amount of sugar" },
        { id: "water", text: "The amount of water" },
        { id: "kind", text: "The kind of sugar" },
        { id: "temp", text: "The water temperature" },
        { id: "stir", text: "Whether the cup was stirred" },
      ] },
    ],
    hint: "To test one thing, find two cups where only that one thing is different.",
    meter: { heat: 10, label: "Mix Deck +10%", story: "The dissolving rules are posted on the wall" },
    discovery: { id: "rockcandy", name: "Rock candy", who: "Kai", fact: "Hot water can dissolve much more sugar than cold water. Rock candy grows when a hot, super-sweet sugar solution cools and sugar crystals form on a string or stick." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "ab" },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 450 },
      { kind: "multi", correct: ["sugar", "water", "kind"] },
    ] },
    rightFeedback: "Stirring and warm water both speed up dissolving, and you found the fair comparisons!",
    wrong: [
      { step: 1, choice: "ad", hint: "Cup A is cold and still. Cup D is warm and stirred. Two things changed." },
      { step: 1, choice: "bc", hint: "Cup B is cold and stirred. Cup C is warm and still. Two things changed." },
      { step: 1, choice: "ac", hint: "Cups A and C are both unstirred. What changed between them?" },
      { step: 2, choice: "b", hint: "Compare cups A and C. Neither was stirred. Did temperature change the time?" },
      { step: 2, choice: "c", hint: "Compare cups A and B. Both were cold. Did stirring change the time?" },
      { step: 2, choice: "d", hint: "Compare cups A and C. Which one took fewer seconds?" },
      { step: 3, value: 750, hint: "You want the difference between the two times. Should you add or subtract?" },
      { step: 3, value: 150, hint: "150 seconds is how long the stirred cup took. How much faster was it than the unstirred cup?" },
      { step: 3, value: 600, hint: "600 seconds is how long the unstirred cup took. Find the difference." },
      { step: 4, pick: "temp", hint: "Cups A and B were cold, and C and D were warm. Did the temperature stay the same?" },
      { step: 4, pick: "stir", hint: "Some cups were stirred and some weren't. That changed." },
      { step: 4, missing: true, hint: "Three things stayed the same. Read Commander Vega's message again." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Pick the right tool", machine: "Separation Rig", icon: "magnet", speaker: "kai",
    line: "The reef garden crew sent us five mixtures to separate. Our rig has a filter, a magnet, a sieve, and a warm drying tray.",
    question: "Sort each mixture to the best tool for getting the solid part back.",
    hint: "Ask: Is one part magnetic? Are the pieces different sizes? Did something dissolve?",
    meter: { heat: 5, label: "Mix Deck +5%", story: "The garden crew gets their materials back" },
    discovery: { id: "waterfilter", name: "Sand filters", who: "Kai", fact: "Many water treatment plants clean drinking water by letting it trickle through thick layers of sand and gravel that trap tiny bits of dirt." },
    answer: { kind: "sort", bins: { m1: "filter", m2: "magnet", m3: "sieve", m4: "evap", m5: "evap" } },
    rightFeedback: "Filter the sand, pull the iron with a magnet, sieve the pebbles, and evaporate the water to get dissolved salt and sugar back.",
    sort: {
      bins: [
        { id: "filter", label: "Filter" },
        { id: "magnet", label: "Magnet" },
        { id: "sieve", label: "Sieve" },
        { id: "evap", label: "Drying tray (evaporation)" },
      ],
      items: [
        { id: "m1", label: "Sand stirred into water" },
        { id: "m2", label: "Iron filings mixed with sand" },
        { id: "m3", label: "Pebbles mixed with sand" },
        { id: "m4", label: "Salt dissolved in water" },
        { id: "m5", label: "Sugar dissolved in water" },
      ],
    },
    wrong: [
      { item: "m4", hint: "Dissolved salt passes right through a filter with the water. How can you get rid of the water instead?" },
      { item: "m5", hint: "Dissolved sugar slips through filters and sieves. What happens if the water evaporates?" },
      { item: "m3", hint: "Pebbles aren't magnetic. Pebbles and sand are very different sizes, though." },
      { item: "m2", hint: "Iron filings and sand grains are about the same size. Which tool only grabs iron?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's shrinking dish", machine: "Balance Bench", icon: "relay", speaker: "kai",
    line: 'Kai: "I stirred 20 g of salt into 200 g of water in an open dish and left it on the sunny deck overnight. This morning it weighed 150 g. Matter is NOT conserved!"',
    question: "Part 1: What went wrong? Part 2: How should Kai fix his test? Part 3: How many grams of matter left the dish?",
    data: {
      title: "Kai's salt dish",
      columns: ["When", "Mass"],
      rows: [
        ["Before mixing (water + salt)", "220 g"],
        ["Right after stirring", "220 g"],
        ["Next morning (open dish, sunny deck)", "150 g"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "Some of the water evaporated into the air overnight, so that matter left the dish." },
        { id: "b", text: "The salt disappeared because it dissolved." },
        { id: "c", text: "Dissolved salt weighs nothing." },
        { id: "d", text: "The balance got tired overnight." },
      ] },
      { type: "choice", prompt: "How should Kai fix his test?", choices: [
        { id: "a", text: "Cover the dish so nothing can escape, and weigh it right after mixing." },
        { id: "b", text: "Use more salt." },
        { id: "c", text: "Leave it in the sun even longer." },
        { id: "d", text: "Weigh only the salt." },
      ] },
      { type: "number", prompt: "How many grams of matter left the dish overnight?", unit: "g" },
    ],
    hint: "Look at the row for right after stirring. When did the mass change, and what could leave an open dish on a sunny deck?",
    meter: { supplies: 1, label: "Sample jars +1", story: "Kai reruns his test with a lid" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 70 },
    ] },
    rightFeedback: "The mass stayed 220 g after mixing. The missing 70 g was water vapor that escaped into the air. It's still matter, just not in the dish.",
    wrong: [
      { step: 1, choice: "b", hint: "Look at the row for right after stirring. The salt had dissolved, and the mass was still 220 g." },
      { step: 1, choice: "c", hint: "Right after stirring, the dish still weighed 220 g. The salt counted. What happened overnight?" },
      { step: 1, choice: "d", hint: "Balances don't get tired. What can leave an open dish in the sun?" },
      { step: 2, choice: "b", hint: "More salt won't stop water from escaping. How can Kai keep everything in the dish?" },
      { step: 2, choice: "c", hint: "More sun means even more water evaporates. How can Kai keep it in?" },
      { step: 2, choice: "d", hint: "To test conservation, you need the mass of the whole mixture. How can Kai keep everything in the dish?" },
      { step: 3, value: 50, hint: "Don't forget the salt. The dish started at 220 g, not 200 g." },
      { step: 3, value: 150, hint: "150 g is what was left. How much went missing?" },
      { step: 3, value: 220, hint: "220 g is the starting mass. Subtract what was left in the morning." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Mud for the reef beds", machine: "Balance Bench", icon: "tank", speaker: "nova",
    line: "The reef garden beds need wet soil. I'll pour 100 g of soil into 250 g of water. Some soil will cloud the water, and some will sink.",
    question: "What will the mud mixture weigh? (Don't count the jar.)",
    hint: "Does sinking or clouding the water add or remove any soil?",
    meter: { heat: 5, label: "Mix Deck +5%", story: "The reef beds get their mud" },
    discovery: { id: "soilmix", name: "Soil is a mixture", who: "Nova", fact: "Soil is a mixture. It has tiny bits of rock, bits of dead plants and animals, water, and air." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "350 g, the same as the soil and water added together" },
      { id: "b", text: "Less than 350 g, because the soil that sinks doesn't count" },
      { id: "c", text: "250 g, because the soil hides in the water" },
      { id: "d", text: "More than 350 g, because mud is heavier than soil and water" },
    ],
    rightFeedback: "100 g + 250 g = 350 g. Soil and water keep all their mass when they mix.",
    wrong: [
      { choice: "b", hint: "The sunken soil is still in the jar. Does it still have mass?" },
      { choice: "c", hint: "Hidden isn't gone. The soil is still in the jar." },
      { choice: "d", hint: "Nothing new was added. Where would extra mass come from?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Where the grains hide", machine: "Stir Station", icon: "static", speaker: "kai",
    line: "I stirred sugar into water, and the grains disappeared. I still can't believe it.",
    question: "What really happened to the sugar grains?",
    hint: "The sugar still has mass, but you can't see it. What could make something too hard to see?",
    meter: { supplies: 1, label: "Sample jars +1", story: "Kai finally believes the sugar is there" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "The sugar turned into water." },
      { id: "b", text: "The sugar broke into pieces too tiny to see and spread evenly through the water." },
      { id: "c", text: "The sugar sank to the bottom and is hiding under the cup." },
      { id: "d", text: "The sugar floated away into the air." },
    ],
    rightFeedback: "Dissolved sugar is still there, in pieces much too small to see. That's why the water tastes sweet everywhere and still weighs more.",
    wrong: [
      { choice: "a", hint: "If sugar turned into water, you couldn't get sugar back by evaporating. But you can!" },
      { choice: "c", hint: "Look at the bottom of the cup. Are there any grains there?" },
      { choice: "d", hint: "The cup got heavier when the sugar went in. Would it if the sugar floated away?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Plant food for the reef", machine: "Mix Deck", icon: "flask", speaker: "vega",
    line: "This is it! The sky reef garden needs a plant-food solution. It must dissolve completely so it won't clog the sprinklers. Nova tested four powders.",
    question: "Part 1: Pick the powder that makes a solution. Part 2: Find the mass of the plant food. Part 3: Pick how to prove the powder is still in the clear water. Part 4: Write to Commander Vega explaining your choice, using the data.",
    data: {
      title: "Powder test (5 g of powder in 100 mL of water, stirred 1 minute)",
      columns: ["Powder", "Right after stirring", "After 10 minutes"],
      rows: [
        ["Chalk powder", "Cloudy white", "White layer on the bottom"],
        ["Epsom salt", "Clear", "Still clear, nothing on the bottom"],
        ["Clay powder", "Muddy brown", "Brown mud on the bottom"],
        ["Cornstarch", "Cloudy white", "White layer on the bottom"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which powder makes a solution?", choices: [
        { id: "chalk", text: "Chalk powder" },
        { id: "epsom", text: "Epsom salt" },
        { id: "clay", text: "Clay powder" },
        { id: "starch", text: "Cornstarch" },
      ] },
      { type: "number", prompt: "Kai stirs 25 g of that powder into 500 g of water. What is the mass of the plant food?", unit: "g" },
      { type: "choice", prompt: "Without tasting it, how can the crew prove the powder is still in the clear water?", choices: [
        { id: "a", text: "Let a small dish of it evaporate and look for crystals left behind." },
        { id: "b", text: "Look for grains floating in the water." },
        { id: "c", text: "Hold a magnet over it." },
        { id: "d", text: "Shake it and see if it gets cloudy." },
      ] },
      { type: "write", prompt: "Explain your choice to Commander Vega. Use the data and the mass.", minWords: 20 },
    ],
    rubric: ["Makes a claim (which powder)", "Uses data from the table as evidence (clear, nothing settles)", "Explains that the mass is conserved (500 g + 25 g = 525 g)"],
    hint: "A solution looks the same all the way through and nothing settles out. Then add the parts to find the mass.",
    meter: { heat: 15, label: "Mix Deck +15%", story: "The reef garden sprinklers turn on" },
    discovery: { id: "epsom", name: "Epsom salt", who: "Nova", fact: "Epsom salt is named after Epsom, a town in England. Long ago, people found it dissolved in the water of a spring there." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "epsom" },
      { kind: "number", value: 525 },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Epsom salt it is! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "chalk", hint: "Check the last column. What settled on the bottom of the chalk cup?" },
      { step: 1, choice: "clay", hint: "Muddy water with mud on the bottom is a mixture, not a solution. It would clog the sprinklers." },
      { step: 1, choice: "starch", hint: "Cornstarch made the water cloudy, then settled. Does a solution do that?" },
      { step: 2, value: 500, hint: "500 g is only the water. The dissolved powder still has mass." },
      { step: 2, value: 475, hint: "The powder went into the water, not out of it. Should you add or subtract?" },
      { step: 3, choice: "b", hint: "Dissolved pieces are too small to see. Looking won't prove anything." },
      { step: 3, choice: "c", hint: "Epsom salt isn't magnetic. How did the crew get the sugar back in the gust tub?" },
      { step: 3, choice: "d", hint: "A solution stays clear when you shake it. How could you get the powder back out?" },
    ],
  },
};

export default {
  id: "SCI.4.6B-XP",
  standard: "SCI.4.6B-XP",
  engine: "expedition_station",
  title: "The Mixing Lab",
  planet: "Cloudreach",
  outpost: "Sky Reef · Mix Deck",
  grade: 4,
  subject: "Science",
  teks: "4.6B",
  supportingTeks: ["4.6C", "4.1B", "4.1D", "4.2B", "4.3A", "4.3C", "4.5B", "4.5E"],
  skillsChip: "4.6B · Mixtures and solutions",
  iCan: "I can investigate and compare mixtures, including solutions of liquids in liquids and solids in liquids. I can separate mixtures and show that matter is conserved when mixtures form.",
  blurb: "A big gust scrambled the Mix Deck on Cloudreach's sky reef. The crew's lab uses real Earth materials, and the reef garden is waiting for supplies.",
  mission: "Sort mixtures and solutions, separate spilled materials, prove that dissolved matter still has mass, and mix a plant-food solution for the reef garden.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.6 · CLOUDREACH MIX DECK",
  playableActs: [1, 2, 3],
  earthTrue: "Cloudreach and the Mix Deck are invented. Every material in this quest is real and behaves just as it does on Earth.",
  meterStart: { heat: 30, supplies: 0, journal: 0 },
  meterLabels: { heat: "Mix Deck", heatUnit: "%", supplies: "Sample jars", suppliesUnit: "jars" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. A big gust just rattled the Mix Deck on Cloudreach's sky reef.",
    "Labels blew away, jars tipped over, and the reef garden is waiting for supplies from our lab.",
    "Everything in the lab is a real Earth material, and it behaves just like it does on Earth. Use what you know. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · After the gust", "Act 2 · Dissolving tests", "Act 3 · Supplies for the reef garden"],
    completes: [
      "The jars are sorted and the gust tub is empty, {firstName}!",
      "The dissolving tests are done, {firstName}! Kai even trusts the balance now.",
      "The reef garden has its plant food, {firstName}! The Mix Deck is back in business.",
    ],
    teasers: [
      "Next on Cloudreach: Kai thinks dissolved sugar weighs nothing. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the reef garden needs mud, separated supplies, and plant food. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The jars are sorted, but Kai and I already disagree about something.",
      "Let's run some dissolving tests.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The sky reef garden is waiting on our lab.",
      "Separate their mixtures, check our masses, and mix the plant food.",
    ],
  }),
  tasks,
};
