// Expedition Station — The Moon Watch (SCI.4.9B-XP)
// Grade 4 · Science · Lumara (glowing garden). Main standard 4.9B (collect
// and analyze data to identify sequences and predict patterns of change in
// the observable appearance of the Moon from Earth); also practices 4.1E
// (collect observations and measurements as evidence), 4.1F (construct
// appropriate tables to organize data), 4.2B (analyze data by identifying
// significant features and patterns), 4.2D (evaluate experimental data and
// predict), 4.3A (explanations supported by data and models), 4.3C
// (respectful scientific discussion), 4.5A (identify and use patterns to
// explain phenomena and make predictions), 4.5D (examine and model the parts
// of a system and their interactions).
//
// Earth-true rule: Lumara, its observatory, and the crew are invented. The
// crew watches EARTH's Moon through the telescope, and every phase, pattern,
// fact, and data table is real Earth science as seen from Earth's Northern
// Hemisphere. Moon shapes are described in words only.
import { CREW, acts } from "./_shared.js";

// The crew's Moon log for one month (Northern Hemisphere view).
const MOON_LOG = {
  title: "Crew Moon log · Month 1",
  columns: ["Day", "What the Moon looks like", "Phase"],
  rows: [
    ["1", "Can't see it at all", "New moon"],
    ["4", "Thin sliver, lit on the right", "Waxing crescent"],
    ["8", "Right half lit", "First quarter"],
    ["11", "More than half lit, dark sliver on the left", "Waxing gibbous"],
    ["15", "Whole round face lit", "Full moon"],
    ["19", "More than half lit, dark sliver on the right", "Waning gibbous"],
    ["22", "Left half lit", "Third quarter"],
    ["26", "Thin sliver, lit on the left", "Waning crescent"],
    ["30", "Can't see it at all", "New moon"],
  ],
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Where does the glow come from?", machine: "Garden Telescope", icon: "scan", speaker: "nova",
    line: "The garden flowers glow all by themselves. But look at Earth's Moon through our telescope. Its light works a different way.",
    question: "Why can we see the Moon shining from Earth?",
    hint: "Does the Moon make its own light, like a lamp? Or does light bounce off it, like a mirror?",
    meter: { heat: 10, label: "Scope focus +10%", story: "The telescope is locked on Earth's Moon" },
    discovery: { id: "grayrock", name: "A dark gray Moon", who: "Nova", fact: "The Moon's surface is dark gray rock and dust. It reflects only about 12 out of every 100 parts of the sunlight that hits it, about as much as an old road." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Sunlight hits the Moon and bounces off toward Earth." },
      { id: "b", text: "The Moon makes its own light, like a small star." },
      { id: "c", text: "Earth's city lights shine on the Moon and light it up." },
      { id: "d", text: "The Moon is on fire, like the Sun." },
    ],
    rightFeedback: "The Moon doesn't make light. We see sunlight bouncing off it.",
    wrong: [
      { choice: "b", hint: "Stars make their own light. The Moon is a ball of rock. Where does its light come from?" },
      { choice: "c", hint: "City lights are far too weak to light up the Moon. What big, bright light shines on it?" },
      { choice: "d", hint: "The Moon is cold rock, not a burning ball of gas. What shines on it?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Line up the Moon cards", machine: "Star Chart Table", icon: "trail", speaker: "kai",
    line: "I made a card for every Moon phase. Then a garden breeze blew them all over the chart table. Oops.",
    question: "Start with the new moon. Put the eight phases in the order we see them from Earth.",
    hint: "After the new moon, the lit part grows until the whole face is lit. Then it shrinks. Crescent, quarter, gibbous, full, and back.",
    meter: { supplies: 1, label: "Moon logs +1", story: "The phase cards are back in order" },
    discovery: { id: "monthword", name: "Moon + month", who: "Kai", fact: "The word \"month\" comes from an old word for \"Moon.\" Long ago, people kept track of time by counting how many times the Moon went through its phases." },
    answer: { kind: "order", correct: ["new", "wxc", "fq", "wxg", "full", "wng", "tq", "wnc"] },
    items: [
      { id: "full", text: "Full moon: the whole round face is lit" },
      { id: "wnc", text: "Waning crescent: a thin sliver lit on the left" },
      { id: "fq", text: "First quarter: the right half is lit" },
      { id: "new", text: "New moon: we can't see the lit side at all" },
      { id: "wng", text: "Waning gibbous: more than half lit, shrinking" },
      { id: "wxc", text: "Waxing crescent: a thin sliver lit on the right" },
      { id: "tq", text: "Third quarter: the left half is lit" },
      { id: "wxg", text: "Waxing gibbous: more than half lit, growing" },
    ],
    rightFeedback: "New, waxing crescent, first quarter, waxing gibbous, full, waning gibbous, third quarter, waning crescent. Then it starts again!",
    wrong: [
      { position: 0, hint: "The brief says to start with the new moon." },
      { position: 1, hint: "Right after the new moon, only a thin sliver shows. Which card is a sliver lit on the right?" },
      { position: 2, hint: "The sliver grows until half the Moon is lit. Which half-lit card comes first?" },
      { position: 3, hint: "After half, the lit part keeps growing. \"Gibbous\" means more than half. Is it growing or shrinking?" },
      { position: 4, hint: "The lit part grows until the whole face is lit. What is that phase called?" },
      { position: 5, hint: "After the full moon, the lit part starts to shrink. Which gibbous card is shrinking?" },
      { position: 6, hint: "The shrinking Moon gets down to half lit again. Which half is lit now, left or right?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Growing or shrinking?", machine: "Moon Sorter", icon: "cells", speaker: "nova",
    line: "Two big words for Moon watchers: waxing and waning. Waxing means the lit part is growing. Waning means it is shrinking.",
    question: "Sort each Moon report from Earth's Northern Hemisphere: is the Moon waxing or waning?",
    hint: "From Earth's Northern Hemisphere, a waxing Moon is lit on the right. A waning Moon is lit on the left.",
    meter: { heat: 10, label: "Scope focus +10%", story: "The waxing and waning reports are sorted" },
    answer: { kind: "sort", bins: { r1: "wax", r2: "wane", r3: "wax", r4: "wane", r5: "wax", r6: "wane" } },
    rightFeedback: "Lit on the right and growing means waxing. Lit on the left and shrinking means waning.",
    sort: {
      bins: [{ id: "wax", label: "Waxing (growing)" }, { id: "wane", label: "Waning (shrinking)" }],
      items: [
        { id: "r1", label: "A thin sliver lit on the right, a little wider each night" },
        { id: "r2", label: "The left half is lit" },
        { id: "r3", label: "The right half is lit" },
        { id: "r4", label: "A thin sliver lit on the left, a little thinner each night" },
        { id: "r5", label: "Almost full, with a dark sliver on the left" },
        { id: "r6", label: "The night after a full moon, a dark sliver shows on the right" },
      ],
    },
    wrong: [
      { item: "r1", hint: "The sliver gets wider each night. Is the lit part growing or shrinking?" },
      { item: "r2", hint: "From the Northern Hemisphere, a waning Moon is lit on the left side." },
      { item: "r3", hint: "From the Northern Hemisphere, a waxing Moon is lit on the right side." },
      { item: "r4", hint: "The sliver gets thinner each night. Is the lit part growing or shrinking?" },
      { item: "r5", hint: "The lit part is on the right and it is almost full. Is it on its way to full, or past it?" },
      { item: "r6", hint: "After the full moon, the lit part can only get smaller. Growing or shrinking?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "A week between", machine: "Moon Log", icon: "log", speaker: "vega",
    line: "Here's our first month of Moon watching. Every night the sky was clear, we wrote down the day and the Moon's shape.",
    question: "How many days passed from the first quarter moon to the full moon?",
    unit: "days",
    hint: "Find the Day for First quarter and the Day for Full moon. How far apart are they?",
    data: MOON_LOG,
    meter: { supplies: 1, label: "Moon logs +1", story: "The first week is measured" },
    answer: { kind: "number", value: 7 },
    rightFeedback: "Day 15 − Day 8 = 7 days. The main phases come about one week apart.",
    wrong: [
      { value: 23, hint: "The Moon changed from Day 8 to Day 15. Should you add or subtract to find the days between?" },
      { value: 15, hint: "15 is the day of the full moon. How many days after the first quarter was that?" },
      { value: 8, hint: "8 is the day of the first quarter. How many days later was the full moon?" },
      { value: 4, hint: "Check the rows again. Use First quarter and Full moon, not the rows next to them." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Cloudy nights", machine: "Garden Telescope", icon: "quake", speaker: "vega",
    line: "Surprise! Glow-pollen clouds covered the telescope dome for days. We missed some nights. Can you fill the gaps with patterns?",
    question: "Part 1: The Moon was hidden on Day 10. What phase was it most likely in? Part 2: How many days from the new moon on Day 1 to the full moon on Day 15? Part 3: On Day 3, Kai saw a faint glow on the dark part of the crescent. What is the best explanation?",
    data: {
      title: "Moon log with cloudy gaps",
      columns: ["Day", "What the Moon looks like", "Phase"],
      rows: [
        ["1", "Can't see it at all", "New moon"],
        ["3", "Thin sliver, lit on the right", "Waxing crescent"],
        ["8", "Right half lit", "First quarter"],
        ["10", "Cloudy, no data", "?"],
        ["15", "Whole round face lit", "Full moon"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What phase was the Moon most likely in on Day 10?", choices: [
        { id: "a", text: "Waxing gibbous: more than half lit and growing" },
        { id: "b", text: "Waning crescent: a thin sliver lit on the left" },
        { id: "c", text: "New moon: can't see it at all" },
        { id: "d", text: "Third quarter: the left half is lit" },
      ] },
      { type: "number", prompt: "How many days from the new moon to the full moon?", unit: "days" },
      { type: "choice", prompt: "What made the faint glow on the dark part of the crescent?", choices: [
        { id: "a", text: "Sunlight bounced off Earth and lit the Moon's dark side a little." },
        { id: "b", text: "The Moon's dark side makes its own dim light." },
        { id: "c", text: "The telescope lens was dirty." },
        { id: "d", text: "Earth's shadow glows on the Moon." },
      ] },
    ],
    hint: "Day 10 sits between the first quarter and the full moon. What happens to the lit part in between?",
    meter: { heat: 10, label: "Scope focus +10%", story: "The cloudy gaps are filled with patterns" },
    discovery: { id: "earthshine", name: "Earthshine", who: "Nova", fact: "When the Moon is a thin crescent, you can sometimes see its dark part glowing faintly. That glow is sunlight that bounced off Earth, then off the Moon, and back to your eyes. It is called earthshine." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 14 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The Moon keeps waxing between first quarter and full. About two weeks takes it from new to full. And that faint glow is earthshine!",
    wrong: [
      { step: 1, choice: "b", hint: "A waning crescent comes near the end of the cycle. Day 10 is between the first quarter and the full moon." },
      { step: 1, choice: "c", hint: "The new moon was on Day 1. The Moon has been growing since then. What comes between half lit and full?" },
      { step: 1, choice: "d", hint: "The third quarter comes after the full moon. Day 10 is before the full moon on Day 15." },
      { step: 2, value: 16, hint: "The Moon changed from Day 1 to Day 15. Should you add or subtract?" },
      { step: 2, value: 15, hint: "15 is the day of the full moon. The count started on Day 1, not Day 0." },
      { step: 2, value: 7, hint: "7 days is new moon to first quarter, or first quarter to full. How long is new moon all the way to full?" },
      { step: 3, choice: "b", hint: "The Moon never makes its own light. What big, bright planet is right next to it, reflecting sunlight?" },
      { step: 3, choice: "c", hint: "Then every part of the picture would look smudged. The glow was only on the Moon's dark part. What else reflects sunlight?" },
      { step: 3, choice: "d", hint: "A shadow is dark. It can't glow. What reflects sunlight onto the Moon?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Shadow or sunlight?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "I figured it out! Earth\'s shadow covers part of the Moon. That\'s what makes the phases."',
    nova: 'Nova: "The Sun always lights half of the Moon. The phases are how much of that sunny half we can see from Earth as the Moon circles us."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "At the full moon, the whole face is lit. Where is Earth then? If Earth's shadow made the phases, could the Moon ever be full?",
    meter: { heat: 5, label: "Scope focus +5%", story: "Kai lets go of the shadow idea" },
    discovery: { id: "redmoon", name: "Lunar eclipses", who: "Nova", fact: "Earth's shadow does fall on the Moon sometimes, but only during a full moon. That's a lunar eclipse. The Moon can turn coppery red, because Earth's air bends a little reddish sunlight onto it." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Half of the Moon is always in sunlight. As the Moon orbits Earth, we see different amounts of that lit half. Earth's shadow only makes a lunar eclipse." },
      { id: "B", text: "Nova, because shadows only happen in the daytime." },
      { id: "C", text: "Kai. Earth blocks more and more sunlight every night." },
      { id: "D", text: "Kai. Clouds of Earth's shadow drift across the Moon." },
    ],
    writtenPrompt: "Tell Kai in your own words what really makes the Moon's phases.",
    debateHints: {
      wrongWho: "Earth's shadow points away from the Sun. At the full moon, the Moon is on that side of Earth, but it is fully lit. What does that tell you?",
      wrongReason: "Right person, check the reason. Shadows happen at night too. What does the Sun always do to half of the Moon?",
      right: "Nova is right. The phases come from how much of the sunlit half we see. Earth's shadow only makes eclipses.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Rules for a waxing Moon", machine: "Pattern Board", icon: "grid", speaker: "vega",
    line: "Let's write rules on the pattern board for a waxing Moon, as seen from Earth's Northern Hemisphere.",
    question: "Pick every rule that is true for a waxing Moon seen from the Northern Hemisphere.",
    items: [
      { id: "right", text: "The lit part is on the right side." },
      { id: "grows", text: "The lit part gets bigger each night." },
      { id: "afternew", text: "It comes after the new moon and before the full moon." },
      { id: "left", text: "The lit part is on the left side." },
      { id: "shrinks", text: "The lit part gets smaller each night." },
      { id: "afterfull", text: "It comes right after the full moon." },
    ],
    hint: "Waxing means growing. Look at the Moon log rows between Day 1 and Day 15.",
    data: MOON_LOG,
    meter: { supplies: 1, label: "Moon logs +1", story: "The waxing rules are on the board" },
    discovery: { id: "southflip", name: "Upside-down Moon", who: "Kai", fact: "People in Earth's Southern Hemisphere, like Australia, see the Moon flipped. For them, a waxing Moon is lit on the left side." },
    answer: { kind: "multi", correct: ["right", "grows", "afternew"] },
    rightFeedback: "A waxing Moon grows each night, it is lit on the right, and it comes between new and full.",
    wrong: [
      { pick: "left", hint: "Check the log for Day 4 and Day 8. Which side is lit while the Moon is growing?" },
      { pick: "shrinks", hint: "Waxing means growing. What does waning mean?" },
      { pick: "afterfull", hint: "Check the log after Day 15. Is the Moon growing or shrinking after the full moon?" },
      { missing: true, hint: "There are three true rules. Think about which side is lit, what the lit part does, and where it fits in the cycle." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "One week ahead", machine: "Prediction Dial", icon: "dial", speaker: "nova",
    line: "Tonight the right half of Earth's Moon is lit. It's the first quarter. I want to set the telescope timer for next week.",
    question: "Predict: What will the Moon look like about 7 days from tonight?",
    hint: "The main phases come about a week apart. What comes after first quarter, two steps later?",
    data: MOON_LOG,
    meter: { heat: 5, label: "Scope focus +5%", story: "The telescope timer is set" },
    discovery: { id: "fullrise", name: "Full moon rising", who: "Nova", fact: "A full moon rises in the east at about the same time the Sun sets in the west. It stays up all night and sets around sunrise." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The whole round face will be lit. It will be a full moon." },
      { id: "b", text: "We won't see it at all. It will be a new moon." },
      { id: "c", text: "The left half will be lit. It will be a third quarter moon." },
      { id: "d", text: "It will look exactly the same as tonight." },
    ],
    rightFeedback: "First quarter on Day 8, full moon on Day 15. One week later, the whole face is lit.",
    wrong: [
      { choice: "b", hint: "The new moon comes about two weeks after the first quarter, not one. Check the log." },
      { choice: "c", hint: "The third quarter is about two weeks after the first quarter. What comes after one week?" },
      { choice: "d", hint: "The Moon's shape changes a little every night. Look at the log a week after Day 8." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Kai's log mix-up", machine: "Moon Log", icon: "log", speaker: "kai",
    line: "I took the night shift and filled in the log myself. Nova says one of my phase names is wrong. I don't see it!",
    question: "Part 1: What went wrong in Kai's log? Part 2: What should Day 19 say?",
    data: {
      title: "Kai's night-shift log",
      columns: ["Day", "What the Moon looks like", "Kai's phase name"],
      rows: [
        ["15", "Whole round face lit", "Full moon"],
        ["19", "More than half lit, dark sliver on the right", "Waxing gibbous"],
        ["22", "Left half lit", "Third quarter"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's log?", choices: [
        { id: "a", text: "Day 19 is after the full moon, so the Moon is shrinking, but Kai called it waxing." },
        { id: "b", text: "Day 15 can't be a full moon." },
        { id: "c", text: "The third quarter should have the right half lit." },
        { id: "d", text: "Nothing. The Moon grows again right after a full moon." },
      ] },
      { type: "choice", prompt: "What should Day 19 say?", choices: [
        { id: "a", text: "Waning gibbous" },
        { id: "b", text: "Waxing crescent" },
        { id: "c", text: "New moon" },
        { id: "d", text: "First quarter" },
      ] },
    ],
    hint: "After the full moon, is the lit part growing or shrinking? Which word goes with shrinking?",
    meter: { supplies: 1, label: "Moon logs +1", story: "Kai's night-shift log is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "After a full moon, the lit part shrinks. More than half lit and shrinking is a waning gibbous.",
    wrong: [
      { step: 1, choice: "b", hint: "The whole face was lit on Day 15. That is a full moon. Look at Day 19." },
      { step: 1, choice: "c", hint: "From the Northern Hemisphere, the third quarter has the left half lit. Kai got that one right. Look at Day 19." },
      { step: 1, choice: "d", hint: "After a full moon, the lit part shrinks until the new moon. Is Day 19 growing or shrinking?" },
      { step: 2, choice: "b", hint: "A crescent is just a thin sliver. Day 19 is more than half lit." },
      { step: 2, choice: "c", hint: "At a new moon we can't see the Moon at all. On Day 19, more than half is lit." },
      { step: 2, choice: "d", hint: "The first quarter is half lit and comes before the full moon. Day 19 is after it." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The missing week", machine: "Garden Telescope", icon: "quake", speaker: "vega",
    line: "Surprise! A glow-vine grew right over the telescope, and we lost a whole week of Moon watching. The garden council still wants a full log.",
    question: "Part 1: What did the Moon most likely look like on Day 22? Part 2: Put the waning phases in order, starting right after the full moon. Part 3: How many days from the full moon on Day 15 to the third quarter on Day 22? Part 4: Pick every true statement about a waning Moon seen from the Northern Hemisphere.",
    data: {
      title: "Moon log with a missing week",
      columns: ["Day", "What the Moon looks like", "Phase"],
      rows: [
        ["15", "Whole round face lit", "Full moon"],
        ["16 to 25", "Vine over the telescope, no data", "?"],
        ["26", "Thin sliver, lit on the left", "Waning crescent"],
        ["30", "Can't see it at all", "New moon"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What did the Moon most likely look like on Day 22?", choices: [
        { id: "a", text: "The left half was lit (third quarter)." },
        { id: "b", text: "The right half was lit (first quarter)." },
        { id: "c", text: "The whole face was lit (full moon)." },
        { id: "d", text: "A thin sliver was lit on the right (waxing crescent)." },
      ] },
      { type: "order", prompt: "Put the waning phases in order, starting right after the full moon.", items: [
        { id: "tq", text: "Third quarter: the left half is lit" },
        { id: "wnc", text: "Waning crescent: a thin sliver lit on the left" },
        { id: "wng", text: "Waning gibbous: more than half lit, shrinking" },
      ] },
      { type: "number", prompt: "How many days from the full moon to the third quarter?", unit: "days" },
      { type: "multi", prompt: "Pick every true statement about a waning Moon seen from the Northern Hemisphere.", choices: [
        { id: "left", text: "The lit part is on the left side." },
        { id: "smaller", text: "The lit part gets smaller each night." },
        { id: "beforenew", text: "It ends with a new moon." },
        { id: "bigger", text: "The lit part gets bigger each night." },
        { id: "right", text: "The lit part is on the right side." },
      ] },
    ],
    hint: "After a full moon, the lit part shrinks from gibbous, to half, to a sliver. Each step takes about a week.",
    meter: { heat: 10, label: "Scope focus +10%", story: "The missing week is filled in" },
    discovery: { id: "bluemoon", name: "Blue moon", who: "Kai", fact: "A Moon cycle is a little shorter than most calendar months. So once every two or three years, a month has two full moons. The second one is called a blue moon, but it doesn't look blue!" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["wng", "tq", "wnc"] },
      { kind: "number", value: 7 },
      { kind: "multi", correct: ["left", "smaller", "beforenew"] },
    ] },
    rightFeedback: "Day 22 was a third quarter with the left half lit. The waning Moon shrinks from gibbous to half to a sliver, one week at a time.",
    wrong: [
      { step: 1, choice: "b", hint: "The right half is lit at the first quarter, while the Moon is growing. After the full moon, which half stays lit?" },
      { step: 1, choice: "c", hint: "The full moon was on Day 15. One week later, the lit part has shrunk. How much is left?" },
      { step: 1, choice: "d", hint: "A sliver lit on the right comes after a new moon. Day 22 is after the full moon." },
      { step: 2, position: 0, hint: "Right after the full moon, the Moon is still more than half lit. Which phase is that?" },
      { step: 2, position: 1, hint: "After the gibbous, the lit part shrinks to half. Which phase is half lit on the left?" },
      { step: 3, value: 37, hint: "The Moon changed from Day 15 to Day 22. Should you add or subtract?" },
      { step: 3, value: 22, hint: "22 is the day of the third quarter. How many days after Day 15 is that?" },
      { step: 3, value: 14, hint: "14 days would take the Moon from full all the way to new. The third quarter is halfway there." },
      { step: 4, pick: "bigger", hint: "Waning means shrinking. Does the lit part get bigger or smaller?" },
      { step: 4, pick: "right", hint: "Check Day 26 in the log. Which side of the waning Moon is lit?" },
      { step: 4, missing: true, hint: "There are three true statements. Think about the lit side, the size, and how the waning part ends." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "One whole month later", machine: "Prediction Dial", icon: "dial", speaker: "nova",
    line: "Tonight Earth's Moon is full again. The garden council wants to hold a Moon Glow party on the next full moon.",
    question: "Predict: What will the Moon look like about 29 to 30 days from tonight?",
    hint: "The whole cycle takes about 29 and a half days. Where does the pattern end up after one full cycle?",
    meter: { heat: 10, label: "Scope focus +10%", story: "The Moon Glow party is on the calendar" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Full again, because the phase cycle repeats about every 29 and a half days." },
      { id: "b", text: "A new moon, because the Moon is used up after a month." },
      { id: "c", text: "A thin crescent, because the Moon gets smaller every month." },
      { id: "d", text: "We can't predict it. The Moon's shapes are random." },
    ],
    rightFeedback: "The phases repeat in the same order about every 29 and a half days. So about a month from tonight, the Moon is full again.",
    wrong: [
      { choice: "b", hint: "The Moon never gets used up. The new moon comes about two weeks after the full moon. What comes after a whole cycle?" },
      { choice: "c", hint: "The Moon isn't getting smaller. The same pattern repeats every cycle. Where does the cycle start over?" },
      { choice: "d", hint: "Look at the log. The phases always come in the same order. Patterns help us predict." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Phase or eclipse?", machine: "Moon Sorter", icon: "cells", speaker: "kai",
    line: "Okay, I get it now. Phases and eclipses are different things. Let me prove it by sorting these sky reports.",
    question: "Sort each report: is it a normal Moon phase, or a lunar eclipse caused by Earth's shadow?",
    hint: "Phases change slowly over days and nights. An eclipse happens only at a full moon and is over in a few hours.",
    meter: { supplies: 1, label: "Moon logs +1", story: "Phases and eclipses are sorted" },
    answer: { kind: "sort", bins: { e1: "phase", e2: "eclipse", e3: "phase", e4: "eclipse", e5: "phase", e6: "eclipse" } },
    rightFeedback: "Phases come from how much of the sunlit half we see. Eclipses come from Earth's shadow, only at a full moon.",
    sort: {
      bins: [{ id: "phase", label: "Normal Moon phase" }, { id: "eclipse", label: "Lunar eclipse (Earth's shadow)" }],
      items: [
        { id: "e1", label: "A thin crescent gets a little wider each night for a week" },
        { id: "e2", label: "During one full-moon night, the Moon turns coppery red for about an hour" },
        { id: "e3", label: "The right half is lit, and a week later the whole face is lit" },
        { id: "e4", label: "A dark curved edge slowly slides across a full moon, and hours later it is full again" },
        { id: "e5", label: "The Moon can't be seen at all for a night or two between crescents" },
        { id: "e6", label: "It only happens when the Sun, Earth, and Moon line up at a full moon" },
      ],
    },
    wrong: [
      { item: "e1", hint: "The change happens slowly over many nights. That's the normal phase pattern." },
      { item: "e2", hint: "A full moon turning red for an hour is special. Earth's air bends reddish light into Earth's shadow." },
      { item: "e3", hint: "First quarter to full over a week is the normal pattern of phases." },
      { item: "e4", hint: "The Moon was full before and after, all in one night. What passed across it?" },
      { item: "e5", hint: "Not seeing the Moon between crescents is the new moon, a normal phase." },
      { item: "e6", hint: "Earth has to be right between the Sun and the Moon for its shadow to reach the Moon." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Two weeks ahead", machine: "Prediction Dial", icon: "dial", speaker: "vega",
    line: "It's Day 4, and a thin sliver lit on the right is glowing over the garden. Nova wants to plan her next big telescope night.",
    question: "Predict: What phase will the Moon be in about 15 days after Day 4?",
    hint: "Day 4 + 15 = Day 19. Find Day 19 in the log, or count the phases forward about two weeks.",
    data: MOON_LOG,
    meter: { heat: 5, label: "Scope focus +5%", story: "Nova's telescope night is planned" },
    discovery: { id: "daymoon", name: "The daytime Moon", who: "Vega", fact: "The Moon isn't only a night sight. On many days of the month you can see it in the daytime sky, especially near the first quarter in the afternoon." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Waning gibbous: more than half lit, dark sliver on the right" },
      { id: "b", text: "Waxing crescent: a thin sliver lit on the right" },
      { id: "c", text: "Waxing gibbous: more than half lit, dark sliver on the left" },
      { id: "d", text: "New moon: can't see it at all" },
    ],
    rightFeedback: "Day 4 + 15 days = Day 19. About two weeks moves the Moon about halfway around the cycle, from waxing crescent to waning gibbous.",
    wrong: [
      { choice: "b", hint: "That's what the Moon looks like tonight. After 15 days, will it look the same?" },
      { choice: "c", hint: "The waxing gibbous comes on about Day 11. Day 4 + 15 is later than that. Check Day 19." },
      { choice: "d", hint: "The new moon is on Day 30. Day 4 + 15 = Day 19. Check the log." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The pattern rules", machine: "Pattern Board", icon: "grid", speaker: "nova",
    line: "After a whole month of watching, we can write the big rules of the Moon's pattern.",
    question: "Pick every rule that our Moon log supports.",
    items: [
      { id: "cycle", text: "The phases repeat about every 29 and a half days." },
      { id: "order", text: "The phases always come in the same order." },
      { id: "week", text: "The main phases (new, first quarter, full, third quarter) come about a week apart." },
      { id: "overnight", text: "A full moon turns into a new moon overnight." },
      { id: "reverse", text: "Every other month, the order runs backward." },
      { id: "shrink", text: "The Moon itself gets smaller in size after the full moon." },
    ],
    hint: "Check the log. Count the days between main phases, and look at the order.",
    data: MOON_LOG,
    meter: { supplies: 1, label: "Moon logs +1", story: "The pattern rules are on the board" },
    discovery: { id: "laterise", name: "The late Moon", who: "Kai", fact: "The Moon rises about 50 minutes later each day, on average. That's because it moves a bit farther along its orbit around Earth every day." },
    answer: { kind: "multi", correct: ["cycle", "order", "week"] },
    rightFeedback: "Same order, about a week between main phases, and the whole cycle repeats about every 29 and a half days.",
    wrong: [
      { pick: "overnight", hint: "Check the log. How many days passed from the full moon to the new moon?" },
      { pick: "reverse", hint: "The order never flips. It is always new, crescent, quarter, gibbous, full, and back down." },
      { pick: "shrink", hint: "The Moon is always the same size and always round. Only the part we see lit changes." },
      { missing: true, hint: "There are three rules the log supports. Think about the cycle length, the order, and the days between main phases." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The Moon Glow festival", machine: "Garden Telescope", icon: "relay", speaker: "vega",
    line: "This is it! The garden council wants to hold the Moon Glow festival on the next full moon. Here's our log from two months of Moon watching. They need a prediction they can trust.",
    question: "Part 1: How many days passed from the first full moon to the second full moon? Part 2: About what day will the next full moon be? Part 3: What will the Moon look like on Day 52? Part 4: Write 2–3 sentences to the garden council. Predict the next full moon and explain how the log supports your prediction.",
    data: {
      title: "Crew Moon log · Two months",
      columns: ["Day", "What the Moon looks like", "Phase"],
      rows: [
        ["1", "Can't see it at all", "New moon"],
        ["16", "Whole round face lit", "Full moon"],
        ["30", "Can't see it at all", "New moon"],
        ["38", "Right half lit", "First quarter"],
        ["45", "Whole round face lit", "Full moon"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many days from the full moon on Day 16 to the full moon on Day 45?", unit: "days" },
      { type: "choice", prompt: "About what day will the next full moon be?", choices: [
        { id: "a", text: "About Day 74 or 75" },
        { id: "b", text: "About Day 52" },
        { id: "c", text: "About Day 60" },
        { id: "d", text: "About Day 90" },
      ] },
      { type: "choice", prompt: "What will the Moon most likely look like on Day 52, one week after the full moon on Day 45?", choices: [
        { id: "a", text: "The left half will be lit (third quarter)." },
        { id: "b", text: "The right half will be lit (first quarter)." },
        { id: "c", text: "The whole face will be lit (full moon)." },
        { id: "d", text: "We won't see it at all (new moon)." },
      ] },
      { type: "write", prompt: "Predict the next full moon for the garden council and explain how the log supports your prediction.", minWords: 20 },
    ],
    rubric: ["Predicts the next full moon around Day 74 or 75 (about 29 to 30 days after Day 45)", "Uses the log as evidence, such as the days between the two full moons", "Explains that the phases repeat in the same order about every 29 and a half days"],
    hint: "Find the pattern in the log first. How long did one whole cycle take? Then use it to count ahead.",
    meter: { heat: 15, label: "Scope focus +15%", story: "The Moon Glow festival date is set" },
    discovery: { id: "harvestmoon", name: "Harvest moon", who: "Nova", fact: "The full moon closest to the first day of fall is called the harvest moon. Long ago, its bright light after sunset helped farmers keep bringing in their crops." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 29 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The festival is set! Your teacher will read your prediction.",
    wrong: [
      { step: 1, value: 61, hint: "The Moon changed from Day 16 to Day 45. Should you add or subtract?" },
      { step: 1, value: 45, hint: "45 is the day of the second full moon. How many days after Day 16 was that?" },
      { step: 1, value: 14, hint: "14 days is about full moon to new moon. Use the two full moon rows." },
      { step: 2, choice: "b", hint: "Day 52 is only one week after Day 45. A whole cycle takes much longer. What did Part 1 show?" },
      { step: 2, choice: "c", hint: "Day 60 is about when the next new moon comes, halfway through the cycle. Add a whole cycle to Day 45." },
      { step: 2, choice: "d", hint: "That's about two cycles away. The next full moon is one cycle after Day 45." },
      { step: 3, choice: "b", hint: "The right half is lit before a full moon, while the Moon is waxing. Day 52 is after the full moon." },
      { step: 3, choice: "c", hint: "The full moon was on Day 45. One week later, the Moon has started to shrink." },
      { step: 3, choice: "d", hint: "The new moon comes about two weeks after the full moon, not one. What comes one week after?" },
    ],
  },
};

export default {
  id: "SCI.4.9B-XP",
  standard: "SCI.4.9B-XP",
  engine: "expedition_station",
  title: "The Moon Watch",
  planet: "Lumara",
  outpost: "Glow Garden Observatory · Moon month",
  grade: 4,
  subject: "Science",
  teks: "4.9B",
  supportingTeks: ["4.1E", "4.1F", "4.2B", "4.2D", "4.3A", "4.3C", "4.5A", "4.5D"],
  skillsChip: "4.9B · Moon phases",
  iCan: "I can collect and study Moon data to put the Moon's phases in order. I can use the pattern to predict how the Moon will look from Earth.",
  blurb: "From the observatory on Lumara, the crew watches Earth's Moon through a giant telescope for a whole month. They log its shapes, crack its pattern, and predict the date for the Moon Glow festival.",
  mission: "Log Earth's Moon for a month, put its phases in order, and use the pattern to predict the next full moon.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.9 · LUMARA OBSERVATORY",
  playableActs: [1, 2, 3],
  earthTrue: "Lumara and its observatory are invented. The crew watches Earth's real Moon, and every phase, pattern, fact, and data table is real Earth science as seen from Earth's Northern Hemisphere.",
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Scope focus", heatUnit: "%", supplies: "Moon logs", suppliesUnit: "logs" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. The Glow Garden observatory on Lumara has a telescope strong enough to see Earth's Moon.",
    "The garden council wants to hold a Moon Glow festival on the next full moon. To pick the night, we need to know the Moon's pattern.",
    "For one month, we'll log what Earth's Moon looks like from Earth. Then we'll use the pattern to predict. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Start the Moon log", "Act 2 · Waxing, waning, and a shadow", "Act 3 · Predict the full moon"],
    completes: [
      "The Moon log is started, and you filled the cloudy gaps with patterns, {firstName}!",
      "You fixed the log and filled in a missing week, {firstName}! The waning Moon has no secrets from you.",
      "You cracked the Moon's pattern, {firstName}! The Moon Glow festival is on the calendar.",
    ],
    teasers: [
      "Next on Lumara: Kai has a big idea about Earth's shadow, and Nova doesn't agree. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: the council needs a festival date, and it's time to predict. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The Moon is past full, and Kai thinks he knows why it's changing.",
      "Let's check his idea against our log.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our Moon log covers a whole month now.",
      "Time to use the pattern to make predictions the garden council can trust.",
    ],
  }),
  tasks,
};
