// Expedition Station — The Outpost Debate (ELA.4.9E-XP)
// Grade 4 · ELAR · Frostveil. Main standard 4.9E (argumentative text: identify
// the claim, explain how the author uses facts, identify the intended
// audience); also practices 4.10A (author's purpose and message), 4.6F
// (inference), 4.7C (text evidence), 4.3B (context clues), 4.11D (edit), and
// 4.12C (compose an argument). All passages are original, written for this quest.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Kai's Proposal: Move to Pinecrest Valley", genre: "Argument (proposal)" }, [
    [
      "Frostveil Outpost should move our camp down to Pinecrest Valley before winter!",
      "The wind up here on the ridge is fierce, and winter is coming fast.",
    ],
    [
      "Pinecrest Valley sits 300 meters lower than our ridge, so it is sheltered from the worst winds.",
      "Tall rock walls surround the valley on three sides.",
      "The valley also has a frozen lake that we could melt for drinking water.",
    ],
    [
      "Also, the valley is much prettier than this rocky ridge.",
      "I have a really good feeling about it!",
      "Moving would be a fun adventure for everyone!",
    ],
    ["The valley is the best place on all of Frostveil.", "Let's pack up and go!"],
  ]),
  B: passage("B", { title: "Nova's Counter-Proposal: Stay and Strengthen the Dome", genre: "Argument (counter-proposal)" }, [
    [
      "Our crew should stay on the ridge this winter and make our dome stronger.",
      "I know moving sounds exciting, but my measurements show it is not the safest choice.",
    ],
    [
      "For three weeks, I measured the wind and the new snow on the ridge and in the valley.",
      "The valley did have less wind, about half as much as the ridge.",
      "But the valley got more than twice as much new snow.",
      "Snow blows off the rock walls and piles up in deep drifts on the valley floor.",
    ],
    [
      "Our dome already has a heater, a landing pad, and a radio tower.",
      "Moving all of it would take about 12 days.",
      "The first big winter storm is expected in 9 days.",
    ],
    [
      "Kai is right that the wind is strong up here.",
      "We can block it by building a snow wall on the windy side and adding new bolts to the dome.",
      "Staying and strengthening our dome is the safest way to keep everyone warm this winter.",
    ],
  ]),
  C: passage("C", { title: "A Letter from Pilot Ruiz", genre: "Letter" }, [
    ["Dear Commander Vega,"],
    [
      "I am writing about the crew's plan to move camp to Pinecrest Valley.",
      "As your supply pilot, I respectfully ask you to keep the outpost on the ridge this winter.",
    ],
    [
      "My supply plane needs a long, flat strip of ground to land safely.",
      "The landing pad on the ridge is 600 meters long and has bright landing lights.",
      "The flattest ground in the valley is only 250 meters long, with rock walls at both ends.",
      "Thick fog also fills the valley on most winter mornings.",
    ],
    [
      "If I cannot land, I cannot bring you food, fuel, or spare parts until spring.",
      "I know this decision is yours, and I trust your judgment.",
      "Please radio your answer before my next flight on Day 5.",
    ],
    ["Respectfully,", "Pilot Ansel Ruiz"],
  ]),
  D: passage("D", { title: "Calling All Snow Pups!", genre: "Poster" }, [
    ["Calling all Snow Pups!", "Our dome is staying on the ridge, and YOU can help keep it warm and cozy!"],
    ["Close the door fast!", "Every time the door stays open, warm air rushes out."],
    ["Wear your layers!", "Air gets trapped between your layers, and that trapped air helps keep you warm."],
    ["Fill a snow bag for the new snow wall!", "The wall will slow down the wind, like a giant shield for our dome."],
    ["Every Snow Pup who helps gets a gold star!"],
  ]),
  E: {
    id: "E",
    title: "Kai's Proposal, Draft 2",
    genre: "Argument draft (has mistakes)",
    ...editText("E", "{Everybody knows} the valley is the best place for our camp. The valley has {les} wind than the ridge because rock walls surround it. {their} is also a frozen lake we could use for water.", {
      "Everybody knows": ["I believe", "Nobody knows"],
      les: ["less", "lest"],
      their: ["There", "They're"],
    }),
  },
  F: {
    id: "F",
    title: "Commander Vega's Announcement",
    genre: "Announcement (has mistakes)",
    ...editText("F", "Crew, we {is} staying on the ridge this winter. The valley gets more than twice as much new snow, and it is {to} foggy for the supply plane. Together we will make our dome the strongest on {frostveil}.", {
      is: ["are", "am"],
      to: ["too", "two"],
      frostveil: ["Frostveil", "frostveils"],
    }),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Pin down Kai's claim", machine: "Claim Finder", icon: "scan", speaker: "vega", passage: ["A"],
    line: "Kai wants the whole outpost to move before winter. First, let's be clear about exactly what he's asking for.",
    question: "A claim is what the author wants you to believe or do. Highlight the sentence that states Kai's claim.",
    hint: "Look for the sentence that says what the crew SHOULD do.",
    meter: { heat: 10, label: "Decision ready +10%", story: "Vega writes Kai's claim on the board" },
    discovery: { id: "windchill", name: "Wind chill", who: "Nova", fact: "Wind makes cold air feel even colder on your skin, because it blows away the thin layer of warm air around your body. Scientists call this wind chill." },
    answer: { kind: "highlight", groups: [["A1.1"]] },
    rightFeedback: "Claim found! Kai says the outpost should move to Pinecrest Valley before winter.",
    wrong: [
      { sentence: "A1.2", hint: "That tells about the wind, which is part of his reason. Which sentence says what the crew should do?" },
      { sentence: "A2.1", hint: "That's a fact Kai uses to support his claim. What does he want the crew to do?" },
      { sentence: "A4.1", hint: "That's Kai's opinion about the valley, but it doesn't say what the crew should do." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Decode sheltered", machine: "Decipher", icon: "static", speaker: "kai", passage: ["A"],
    line: "I used a big word in my proposal. Let's make sure everyone knows what I meant.",
    question: "\"Pinecrest Valley sits 300 meters lower than our ridge, so it is sheltered from the worst winds.\" What does sheltered mean?",
    hint: "Read the next sentence. What surrounds the valley?",
    meter: { heat: 5, label: "Decision ready +5%", story: "Kai's big word is cleared up" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Hit hard by" },
      { id: "b", text: "Protected from" },
      { id: "c", text: "Far above" },
      { id: "d", text: "Covered in snow from" },
    ],
    rightFeedback: "Right! Low ground with rock walls around it is protected from the worst winds.",
    wrong: [
      { choice: "a", hint: "That's the opposite. Kai thinks the valley is a better place to be in the wind." },
      { choice: "c", hint: "The valley is 300 meters LOWER. Is it above anything?" },
      { choice: "d", hint: "The sentence is about wind, not snow. What do rock walls do to wind?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Facts on ice", machine: "Sort Bay", icon: "cells", speaker: "nova", passage: ["A"],
    line: "Kai's proposal mixes facts and opinions. A fact can be checked or measured. An opinion is what someone thinks or feels.",
    question: "Sort each statement from Kai's proposal: fact or opinion?",
    hint: "Ask: could someone measure it or go check it? If not, it's an opinion.",
    meter: { heat: 10, label: "Decision ready +10%", story: "Kai's statements are sorted" },
    discovery: { id: "snowfence", name: "Snow fences", who: "Kai", fact: "Snow fences are built along roads to slow the wind. When the wind slows down, it drops its snow behind the fence instead of on the road." },
    answer: { kind: "sort", bins: { f1: "fact", f2: "fact", f3: "fact", o1: "opinion", o2: "opinion", o3: "opinion" } },
    rightFeedback: "Sorted! Heights, walls, and lakes can be checked. Prettiest, fun, and best are opinions.",
    sort: {
      bins: [{ id: "fact", label: "Fact" }, { id: "opinion", label: "Opinion" }],
      items: [
        { id: "f1", label: "The valley sits 300 meters lower than the ridge." },
        { id: "o1", label: "The valley is much prettier than this rocky ridge." },
        { id: "f2", label: "Tall rock walls surround the valley on three sides." },
        { id: "o2", label: "Moving would be a fun adventure for everyone." },
        { id: "f3", label: "The valley has a frozen lake." },
        { id: "o3", label: "The valley is the best place on all of Frostveil." },
      ],
    },
    wrong: [
      { item: "f1", hint: "300 meters can be measured. Is that a fact or an opinion?" },
      { item: "o1", hint: "Pretty to whom? Someone else might like the ridge better. That's an opinion." },
      { item: "o3", hint: "It sounds very sure, but can anyone measure or prove \"best\"?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Nova's answer", machine: "Claim Finder", icon: "scan", speaker: "nova", passage: ["B"],
    line: "I wrote a counter-proposal. That means I'm arguing for a different plan. Can you find my claim?",
    question: "Highlight a sentence that states Nova's claim.",
    hint: "Nova's claim says what she thinks the crew should do instead of moving.",
    meter: { heat: 5, label: "Decision ready +5%", story: "Nova's claim goes up next to Kai's" },
    answer: { kind: "highlight", groups: [["B1.1", "B4.3"]] },
    rightFeedback: "Found it! Nova says the crew should stay and make the dome stronger.",
    wrong: [
      { sentence: "B2.3", hint: "That's one of her measured facts. Which sentence says what the crew should do?" },
      { sentence: "B4.1", hint: "There, Nova agrees with Kai about the wind. Find where she says what the crew should do." },
      { sentence: "B1.2", hint: "That hints at her opinion, but it doesn't say what the crew should do instead." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Snap in the storm", machine: "Fact Check", icon: "snap", speaker: "vega", passage: ["A", "B"],
    line: "Surprise! A wind gust just snapped a bolt on the dome. The crew is nervous. I need to know which facts each side really has.",
    question: "Part 1: How does Nova use the snow fact to support her claim? Part 2: Highlight one fact Kai uses and one fact Nova uses. Part 3: Why does agreeing with Kai about the wind make Nova's argument stronger?",
    parts: [
      { type: "choice", prompt: "Nova says the valley gets more than twice as much new snow. How does that fact support her claim?", choices: [
        { id: "a", text: "It shows the valley gets deep snow drifts, so moving there would not be safer." },
        { id: "b", text: "It shows the valley is prettier in winter." },
        { id: "c", text: "It proves there is no wind on the ridge." },
        { id: "d", text: "It shows that Nova likes snow." },
      ] },
      { type: "highlight", prompt: "Highlight one fact from Kai's proposal (A) and one fact from Nova's (B).", passage: ["A", "B"], count: 2 },
      { type: "choice", prompt: "Nova writes, \"Kai is right that the wind is strong up here.\" Why does that make her argument stronger?", choices: [
        { id: "a", text: "It shows she listened to Kai and has a plan for the wind problem: a snow wall and new bolts." },
        { id: "b", text: "It means she really wants to move to the valley." },
        { id: "c", text: "It makes her argument longer." },
        { id: "d", text: "It shows the wind is not a problem at all." },
      ] },
    ],
    hint: "A fact can be measured or checked. Look for numbers and things you could see.",
    meter: { heat: 10, label: "Decision ready +10%", story: "Kai tightens the new bolt while the crew talks" },
    discovery: { id: "katabatic", name: "Downhill winds", who: "Nova", fact: "In Antarctica, cold, heavy air slides down off the high ice. These winds can blow faster than 150 kilometers per hour." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A2.1", "A2.2", "A2.3"], ["B2.2", "B2.3", "B2.4", "B3.1", "B3.2", "B3.3"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Strong work! Both sides have facts, and Nova even answers Kai's best point.",
    wrong: [
      { step: 1, choice: "b", hint: "Nova doesn't talk about pretty. What could deep snow drifts do to a camp?" },
      { step: 1, choice: "c", hint: "Nova agrees the ridge is windy. What does the snow fact say about the valley?" },
      { step: 1, choice: "d", hint: "Her feelings aren't the point. How does more snow make the valley less safe?" },
      { step: 2, sentence: "A3.1", hint: "\"Prettier\" is an opinion. Find a fact Kai could measure or check." },
      { step: 2, sentence: "A4.1", hint: "That sounds sure, but \"best\" is an opinion. Find a fact in Kai's proposal." },
      { step: 2, sentence: "B1.1", hint: "That's Nova's claim. Find one of the facts she uses to support it." },
      { step: 3, choice: "b", hint: "Nova still says the crew should stay. What does she say they can do about the wind?" },
      { step: 3, choice: "c", hint: "Longer isn't stronger. What does Nova offer to do about the wind?" },
      { step: 3, choice: "d", hint: "Nova says the wind IS strong. What is her plan for it?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Read the snow log", machine: "Data Deck", icon: "grid", speaker: "nova", passage: ["B"],
    line: "Here are the measurements behind my counter-proposal. Numbers don't have feelings, so let's see what they say.",
    question: "Part 1: What does the table show about new snow? Part 2: Highlight the sentence in Nova's counter-proposal that the snow columns support. Part 3: How does the table help Nova's argument?",
    data: {
      title: "Nova's measurements (weekly averages)",
      columns: ["Week", "Ridge wind (km/h)", "Valley wind (km/h)", "Ridge new snow (cm)", "Valley new snow (cm)"],
      rows: [
        ["1", "48", "22", "10", "25"],
        ["2", "55", "26", "14", "31"],
        ["3", "51", "24", "12", "29"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What does the table show about new snow?", choices: [
        { id: "a", text: "Every week, the valley got more than twice as much new snow as the ridge." },
        { id: "b", text: "Every week, the ridge got more new snow than the valley." },
        { id: "c", text: "The ridge and the valley got the same amount of new snow." },
        { id: "d", text: "The valley got less wind and less snow." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence in Passage B that the snow columns support.", passage: "B" },
      { type: "choice", prompt: "How does the table help Nova's argument?", choices: [
        { id: "a", text: "It gives measured facts that back up her claim that the valley is not the safer choice." },
        { id: "b", text: "It proves Kai's proposal has no facts at all." },
        { id: "c", text: "It makes her proposal look more colorful." },
        { id: "d", text: "It shows the ridge has less wind than the valley." },
      ] },
    ],
    hint: "Compare the two snow columns week by week. Is the valley number more than double the ridge number?",
    meter: { heat: 5, label: "Decision ready +5%", story: "Nova pins the table to the board" },
    discovery: { id: "drifts", name: "Snowdrifts", who: "Kai", fact: "Wind can pick up loose snow and pile it into drifts. Some snowdrifts grow taller than a grown-up." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B2.3"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! 25, 31, and 29 are all more than double 10, 14, and 12. The data backs Nova up.",
    wrong: [
      { step: 1, choice: "b", hint: "Check Week 1: 10 cm on the ridge and 25 cm in the valley. Which is more?" },
      { step: 1, choice: "c", hint: "Compare the two snow columns. Are the numbers the same?" },
      { step: 1, choice: "d", hint: "The valley did get less wind. Look again at the snow columns." },
      { step: 2, sentence: "B2.2", hint: "That sentence matches the wind columns. Which sentence is about snow?" },
      { step: 2, sentence: "B2.1", hint: "That tells how Nova collected the data. Which sentence tells what the snow numbers show?" },
      { step: 3, choice: "b", hint: "Kai does have some facts. What does the table add to Nova's side?" },
      { step: 3, choice: "c", hint: "Tables help because of what's in them. What kind of evidence is it?" },
      { step: 3, choice: "d", hint: "Check the wind columns: 48 on the ridge, 22 in the valley. Which is windier?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The weak link", machine: "Fact Check", icon: "scan", speaker: "vega", passage: ["A"],
    line: "Some of Kai's reasons have facts behind them. Some don't. A reason with no evidence is a weak reason.",
    question: "Highlight one reason in Kai's proposal that has no facts to back it up.",
    hint: "Look for a feeling or an opinion that nobody could measure.",
    meter: { supplies: 1, label: "Evidence cards +1", story: "Vega marks one of Kai's reasons as weak" },
    answer: { kind: "highlight", groups: [["A3.1", "A3.2", "A3.3", "A4.1"]] },
    rightFeedback: "Right! Pretty, good feelings, fun, and best are opinions. None of them has evidence.",
    wrong: [
      { sentence: "A2.1", hint: "300 meters lower can be measured. That's a fact. Find a reason nobody could check." },
      { sentence: "A2.3", hint: "Nova could go look at the lake. That's a fact. Find a reason that's just a feeling." },
      { sentence: "A1.2", hint: "Nova's wind measurements back that one up. Find a reason with no evidence at all." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Dear Commander", machine: "Audience Scan", icon: "log", speaker: "kai", passage: ["C"],
    line: "A letter just came in on the supply plane. It sounds a lot more serious than my proposal.",
    question: "Part 1: Who is the pilot's letter written for? Part 2: Highlight a sentence that shows who the reader is. Part 3: How did the pilot write for his reader?",
    parts: [
      { type: "choice", prompt: "Who is the letter written for?", choices: [
        { id: "a", text: "Commander Vega" },
        { id: "b", text: "The young crew kids" },
        { id: "c", text: "Kai" },
        { id: "d", text: "Other supply pilots" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows who the reader is.", passage: "C" },
      { type: "choice", prompt: "How did the pilot write for his reader?", choices: [
        { id: "a", text: "He was polite and serious, and he said the decision was hers to make." },
        { id: "b", text: "He used silly nicknames and lots of exclamation points." },
        { id: "c", text: "He told a funny story about flying." },
        { id: "d", text: "He wrote short rules for kids to follow." },
      ] },
    ],
    hint: "Look at how the letter starts, and who gets to make the decision.",
    meter: { heat: 5, label: "Decision ready +5%", story: "The letter goes on Vega's desk" },
    discovery: { id: "researchstation", name: "Winter at the South Pole", who: "Kai", fact: "Scientists live at research stations in Antarctica all year. In winter, only a small crew stays, and planes almost never fly in until spring." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["C1.1", "C4.2", "C4.3"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! \"Dear Commander Vega\" and \"this decision is yours\" show the letter is for the commander.",
    wrong: [
      { step: 1, choice: "b", hint: "Would a letter for kids start with \"Dear Commander\"?" },
      { step: 1, choice: "c", hint: "Kai isn't named in the letter. Who does the pilot say will make the decision?" },
      { step: 1, choice: "d", hint: "Read the first line. Who is the letter addressed to?" },
      { step: 2, sentence: "C3.2", hint: "That's a fact about the landing pad. Which sentence speaks right to the reader?" },
      { step: 2, sentence: "C2.2", hint: "That sentence tells what the pilot wants. Which one names the reader or says the decision is hers?" },
      { step: 3, choice: "b", hint: "Look for exclamation points in the letter. Are there any?" },
      { step: 3, choice: "c", hint: "The letter gives facts and a request, not a story." },
      { step: 3, choice: "d", hint: "The letter is for the commander. Does it read like rules for kids?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Loudest wins?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: "Kai: \"My proposal has four exclamation points, and Nova's has zero! An argument that sounds more excited must be stronger.\"",
    nova: "Nova: \"An argument is strong when facts support the claim. I measured the wind and snow for three weeks.\"",
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Exclamation points show feelings. What actually proves a claim?",
    meter: { supplies: 1, label: "Evidence cards +1", story: "The crew agrees on what makes an argument strong" },
    discovery: { id: "muskox", name: "Musk oxen", who: "Nova", fact: "When wolves come near, musk oxen stand shoulder to shoulder in a tight circle with their horns facing out. Their young stay safe in the middle." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A strong argument uses facts and evidence to support its claim. Exclamation points show excitement, but they don't prove anything." },
      { id: "B", text: "Nova, because longer arguments always win." },
      { id: "C", text: "Kai. The more excited an argument sounds, the more true it is." },
      { id: "D", text: "Kai. Exclamation points make readers pay attention, so they make an argument correct." },
    ],
    writtenPrompt: "Tell Kai in your own words what makes an argument strong.",
    debateHints: {
      wrongWho: "Count the facts, not the exclamation points. Whose argument has measured evidence?",
      wrongReason: "Right person, check the reason. What actually makes an argument strong?",
      right: "Nova is right. Facts make an argument strong, not how loud it sounds.",
    },
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Fog on the radio", machine: "Purpose Probe", icon: "relay", speaker: "vega", passage: ["C"],
    line: "Surprise! Pilot Ruiz just radioed: fog is already rolling into the valley, and he needs my answer before Day 5. Help me read his letter closely.",
    question: "Part 1: What is the pilot's claim? Part 2: Highlight one fact about the landing ground and one fact about fog or supplies. Part 3: What is the author's purpose for writing the letter?",
    parts: [
      { type: "choice", prompt: "What is the pilot's claim?", choices: [
        { id: "a", text: "The outpost should stay on the ridge this winter." },
        { id: "b", text: "The valley is foggy in winter." },
        { id: "c", text: "Vega should radio him before Day 5." },
        { id: "d", text: "His plane is the best plane on Frostveil." },
      ] },
      { type: "highlight", prompt: "Highlight one fact about how long the landing ground is, and one fact about fog or supplies.", passage: "C", count: 2 },
      { type: "choice", prompt: "What is the author's purpose for writing the letter?", choices: [
        { id: "a", text: "To persuade Vega to keep the outpost on the ridge so supplies can still reach the crew" },
        { id: "b", text: "To entertain Vega with a story about flying" },
        { id: "c", text: "To teach the crew kids how planes work" },
        { id: "d", text: "To describe how beautiful the valley looks from the air" },
      ] },
    ],
    hint: "A claim is what the writer wants. A fact supports it. The purpose is WHY the writer wrote.",
    meter: { heat: 10, label: "Decision ready +10%", story: "Vega radios the pilot: \"Answer coming soon.\"" },
    discovery: { id: "polarnight", name: "Polar night", who: "Nova", fact: "Near the North and South Poles, the sun does not rise at all for weeks or even months in winter. This is called polar night." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["C3.2", "C3.3"], ["C3.4", "C4.1"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Great reading! The pilot wants the outpost to stay, backs it up with facts, and writes to persuade Vega.",
    wrong: [
      { step: 1, choice: "b", hint: "That's a fact he uses. What does he want Vega to do?" },
      { step: 1, choice: "c", hint: "That's a request about timing. What does he ask her to decide?" },
      { step: 1, choice: "d", hint: "The pilot never says that. Reread the second paragraph." },
      { step: 2, sentence: "C3.1", hint: "That tells what his plane needs, but it has no measurement. Find the sentences with the lengths." },
      { step: 2, sentence: "C2.2", hint: "That's his claim. Find the facts that support it." },
      { step: 2, sentence: "C4.2", hint: "That's a polite line for his reader, not a fact." },
      { step: 3, choice: "b", hint: "Is there a story in the letter? What does the pilot ask for?" },
      { step: 3, choice: "c", hint: "Who is the letter written to? Not the kids." },
      { step: 3, choice: "d", hint: "The pilot says the valley is foggy and too short to land. Does that sound like praise?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Evidence face-off", machine: "Two Sides", icon: "split", speaker: "vega", passage: ["A", "B"],
    line: "Tomorrow the crew votes. Before we do, I want a fair comparison of both arguments.",
    question: "Part 1: How is Nova's evidence different from Kai's? Part 2: Pick every point that Kai and Nova BOTH agree on.",
    parts: [
      { type: "choice", prompt: "How is Nova's evidence different from Kai's?", choices: [
        { id: "a", text: "Nova measured for three weeks and gives numbers. Kai gives some facts, but also feelings and opinions." },
        { id: "b", text: "Kai uses more numbers than Nova." },
        { id: "c", text: "Neither of them uses any facts." },
        { id: "d", text: "Nova only uses opinions." },
      ] },
      { type: "multi", prompt: "Pick every point that Kai and Nova BOTH agree on.", choices: [
        { id: "a", text: "The wind on the ridge is strong." },
        { id: "b", text: "The valley has less wind than the ridge." },
        { id: "c", text: "The valley gets less snow than the ridge." },
        { id: "d", text: "Moving would be a fun adventure." },
        { id: "e", text: "The dome already has a radio tower." },
      ] },
    ],
    hint: "Put the two passages side by side. Which ideas show up in both?",
    meter: { heat: 5, label: "Decision ready +5%", story: "Vega's comparison chart is ready for the vote" },
    discovery: { id: "foxtail", name: "Arctic fox tails", who: "Kai", fact: "Arctic foxes wrap their long, fluffy tails around their noses and paws like a scarf to stay warm while they sleep." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["a", "b"] },
    ] },
    rightFeedback: "Fair and square! They agree about the wind. Nova's numbers show the snow is the bigger danger.",
    wrong: [
      { step: 1, choice: "b", hint: "Count the numbers. Who measured for three weeks?" },
      { step: 1, choice: "c", hint: "Both have facts. Kai says the valley is 300 meters lower. What makes Nova's different?" },
      { step: 1, choice: "d", hint: "Nova's proposal is full of measurements. Are those opinions?" },
      { step: 2, pick: "c", hint: "Nova measured more than twice as much snow in the valley. Kai never mentions snow." },
      { step: 2, pick: "d", hint: "Only Kai says that, and it's an opinion." },
      { step: 2, pick: "e", hint: "Only Nova mentions the radio tower. The point has to be in BOTH arguments." },
      { step: 2, missing: true, hint: "There are two points. Compare Kai's first two paragraphs with Nova's second and last paragraphs." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's mistake", machine: "Repair", icon: "log", speaker: "kai", passage: ["E"],
    line: "I rewrote my proposal for the vote. Nova says I made a big mistake, plus some small ones. Can you help me fix it?",
    question: "Part 1: What is Kai's big mistake in Draft 2? Part 2: Tap each mistake and pick the fix.",
    parts: [
      { type: "choice", prompt: "What is Kai's big mistake?", choices: [
        { id: "a", text: "He states an opinion as if it were a fact that everyone agrees with." },
        { id: "b", text: "He uses too many facts." },
        { id: "c", text: "He forgot to include any claim." },
        { id: "d", text: "He wrote it for the supply pilot instead of the crew." },
      ] },
      { type: "edit", prompt: "Fix the 3 mistakes in Kai's draft.", passage: "E" },
    ],
    hint: "Can anyone prove that a place is \"the best\"? Then check the spelling and the start of each sentence.",
    meter: { heat: 5, label: "Decision ready +5%", story: "Kai's fixed draft is ready for the vote" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "edit", fixes: { "E:Everybody knows": "I believe", "E:les": "less", "E:their": "There" } },
    ] },
    rightFeedback: "Fixed! \"I believe\" shows it's Kai's opinion, and the spelling and capitals are right.",
    wrong: [
      { step: 1, choice: "b", hint: "Facts make an argument stronger. Look at the first sentence of the draft." },
      { step: 1, choice: "c", hint: "Kai does say where the camp should be. What's wrong with HOW he says it?" },
      { step: 1, choice: "d", hint: "The draft is for the crew vote. Look at \"Everybody knows.\" Is that true?" },
      { step: 2, token: "E:Everybody knows", hint: "Not everybody agrees, because Nova doesn't! Pick words that show it's Kai's own opinion." },
      { step: 2, token: "E:les", hint: "Check the spelling. Which word means a smaller amount?" },
      { step: 2, token: "E:their", hint: "This starts a sentence and points to where something is. Which word fits?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Snow Pup poster", machine: "Audience Scan", icon: "brief", speaker: "nova", passage: ["D"],
    line: "The crew voted to stay! Kai made a poster to get the youngest crew kids to help.",
    question: "Part 1: Who is the poster written for? Part 2: Pick every clue that shows it was written for young kids.",
    parts: [
      { type: "choice", prompt: "Who is the poster written for?", choices: [
        { id: "a", text: "The young crew kids, called Snow Pups" },
        { id: "b", text: "Commander Vega" },
        { id: "c", text: "Pilot Ruiz" },
        { id: "d", text: "Scientists on another planet" },
      ] },
      { type: "multi", prompt: "Pick every clue that shows the poster was written for young kids.", choices: [
        { id: "a", text: "It uses short, simple sentences." },
        { id: "b", text: "It calls the readers \"Snow Pups.\"" },
        { id: "c", text: "It promises a gold star for helping." },
        { id: "d", text: "It has a table of wind measurements." },
        { id: "e", text: "It starts with \"Dear Commander Vega.\"" },
      ] },
    ],
    hint: "Think about how you would write to a little kid. Then check what's really on the poster.",
    meter: { supplies: 1, label: "Evidence cards +1", story: "The poster goes up in the dome hallway" },
    discovery: { id: "groundsquirrel", name: "Arctic ground squirrels", who: "Nova", fact: "Arctic ground squirrels hibernate for up to eight months. During that long sleep, their bodies can cool to just below freezing." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["a", "b", "c"] },
    ] },
    rightFeedback: "Right! Short sentences, a fun nickname, and a gold star are made for young readers.",
    wrong: [
      { step: 1, choice: "b", hint: "Would Vega be called a Snow Pup? Look at the first line." },
      { step: 1, choice: "c", hint: "The poster is about helping in the dome. Who does it call out to?" },
      { step: 1, choice: "d", hint: "The poster talks about \"our dome.\" Who lives there?" },
      { step: 2, pick: "d", hint: "Look again. Is there a table on the poster?" },
      { step: 2, pick: "e", hint: "That's how the pilot's letter starts, not the poster." },
      { step: 2, missing: true, hint: "There are three clues. Look at the words, the nickname, and the reward." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Why the rules work", machine: "Purpose Probe", icon: "crew", speaker: "vega", passage: ["D"],
    line: "Kai's poster doesn't just give orders. It gives reasons. That's what makes kids want to help.",
    question: "Part 1: What is the author's main purpose for the poster? Part 2: Highlight a sentence that uses a fact to explain why one of the rules works.",
    parts: [
      { type: "choice", prompt: "What is the author's main purpose?", choices: [
        { id: "a", text: "To persuade the young kids to help keep the dome warm" },
        { id: "b", text: "To entertain the kids with a story about snow" },
        { id: "c", text: "To explain how to build a dome from the start" },
        { id: "d", text: "To tell the pilot where to land" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that uses a fact to explain why a rule works.", passage: "D" },
    ],
    hint: "The rules are the short commands. Look for a sentence right after a rule that tells WHY.",
    meter: { heat: 5, label: "Decision ready +5%", story: "The Snow Pups line up to fill snow bags" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["D2.2", "D3.2", "D4.2"]] },
    ] },
    rightFeedback: "Right! Each rule comes with a fact, like warm air rushing out the open door.",
    wrong: [
      { step: 1, choice: "b", hint: "Is there a story? The poster asks the kids to DO something." },
      { step: 1, choice: "c", hint: "The dome is already built. What does the poster ask kids to do?" },
      { step: 1, choice: "d", hint: "The poster is for the Snow Pups, not the pilot." },
      { step: 2, sentence: "D2.1", hint: "That's the rule. Which sentence tells WHY closing the door fast helps?" },
      { step: 2, sentence: "D5.1", hint: "That's a reward, not a fact that explains a rule." },
      { step: 2, sentence: "D1.2", hint: "That's the poster's big message. Find a sentence that explains why one rule works." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Answer the Snow Pups", machine: "Transmit", icon: "trail", speaker: "vega", passage: ["F", "B", "C"],
    line: "Surprise! The Snow Pups marched into my office. They want to know why they can't live in the pretty valley. Let's finish my announcement and answer them.",
    question: "Part 1: Fix the 3 mistakes in Vega's announcement. Part 2: Pick the fact that best supports staying. Part 3: Write 2–3 sentences for the Snow Pups with a claim and one fact.",
    parts: [
      { type: "edit", prompt: "Fix the 3 mistakes in the announcement.", passage: "F" },
      { type: "choice", prompt: "Which fact best supports Vega's claim that staying is the safer choice?", choices: [
        { id: "a", text: "The valley got more than twice as much new snow as the ridge." },
        { id: "b", text: "The valley is much prettier than the ridge." },
        { id: "c", text: "Kai had a really good feeling about the valley." },
        { id: "d", text: "Moving would be a fun adventure." },
      ] },
      { type: "write", prompt: "Write 2–3 sentences for the Snow Pups. Tell them why the crew is staying on the ridge. Include your claim and one fact from the passages.", minWords: 15 },
    ],
    teacherScoredPart: 3,
    rubric: ["States a clear claim", "Supports the claim with at least one fact from the passages", "Written for young kids: clear, simple words", "Complete sentences with capitals and end punctuation"],
    hint: "Your claim says what you think. Your fact proves it. Keep the words simple for young kids.",
    meter: { heat: 10, label: "Decision ready +10%", story: "The Snow Pups cheer, and the snow wall goes up" },
    discovery: { id: "aurora", name: "Northern lights", who: "Kai", fact: "The northern lights happen when tiny bits from the sun crash into the air high above Earth and make it glow green, pink, and purple." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "F:is": "are", "F:to": "too", "F:frostveil": "Frostveil" } },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 15 },
    ] },
    rightFeedback: "Announcement sent! Your teacher will read your argument for the Snow Pups.",
    wrong: [
      { step: 1, token: "F:is", hint: "\"We\" is more than one person. \"We is\" or \"we are\"?" },
      { step: 1, token: "F:to", hint: "This word means \"very\" or \"more than is okay.\" Which spelling is that?" },
      { step: 1, token: "F:frostveil", hint: "Frostveil is the name of a planet. What do names start with?" },
      { step: 2, choice: "b", hint: "That's an opinion. Which choice is a fact someone measured?" },
      { step: 2, choice: "c", hint: "A feeling isn't evidence. Which choice has a measurement?" },
      { step: 2, choice: "d", hint: "Fun is an opinion, and it doesn't show safety. Find the measured fact." },
    ],
  },
};

export default {
  id: "ELA.4.9E-XP",
  standard: "ELA.4.9E-XP",
  engine: "expedition_station",
  title: "The Outpost Debate",
  planet: "Frostveil",
  outpost: "Ridge Camp Dome · before the first storm",
  grade: 4,
  subject: "ELAR",
  teks: "4.9E",
  supportingTeks: ["4.10A", "4.6F", "4.7C", "4.3B", "4.11D", "4.12C"],
  skillsChip: "4.9E · Claims, facts, and audience in argumentative text",
  iCan: "I can find the claim in an argument, explain how the author uses facts to support it, and tell who the argument was written for.",
  blurb: "Winter is coming to Frostveil, and the crew can't agree. Kai wants to move camp to the valley. Nova wants to stay and strengthen the dome. Every argument is on the table.",
  mission: "Read each argument, weigh the facts, figure out who each writer is talking to, and help the crew make the safest choice before the first storm.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.9E · FROSTVEIL RIDGE CAMP",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Decision ready", heatUnit: "%", supplies: "Evidence cards", suppliesUnit: "cards" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Winter is coming to Frostveil, and our crew has a big choice to make.",
    "Kai wants to move camp down to Pinecrest Valley. Nova wants to stay on the ridge and make our dome stronger. They both wrote arguments.",
    "Read them carefully. A strong argument needs more than a loud voice. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Two plans", "Act 2 · Weighing the evidence", "Act 3 · The crew votes"],
    completes: [
      "You found both claims and the facts behind them, {firstName}!",
      "You read the data and the pilot's letter like a pro, {firstName}!",
      "The crew is staying, {firstName}! The snow wall is going up, and everyone knows why.",
    ],
    teasers: [
      "Next on Frostveil: Nova's measurements come in, and a letter arrives on the supply plane. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the crew votes, and the youngest crew members need an answer. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. My three weeks of measurements are ready.",
      "And Pilot Ruiz just sent Commander Vega a letter about our plan.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The crew votes tomorrow.",
      "Help us compare the arguments, fix the drafts, and explain the choice to everyone.",
    ],
  }),
  tasks,
};
