// Expedition Station — The Parts Depot (MA.3.4A-XP)
// Grade 3 · Math · Mechara. Main standard 3.4A (solve with fluency one- and
// two-step addition and subtraction problems within 1,000 using place value,
// properties of operations, and the relationship between addition and
// subtraction); also practices 3.4B (round to the nearest 10 or 100, or use
// compatible numbers, to estimate) and 3.5A (represent problems with pictorial
// models, number lines, and equations). Grade 3 limits: whole numbers within 1,000.
import { CREW, acts } from "./_shared.js";

const HTO = ["hundreds", "tens", "ones"];

const STOCK = {
  title: "Depot stock log",
  columns: ["Part", "On the shelf"],
  rows: [["Bolts", "318"], ["Gears", "245"], ["Springs", "160"], ["Wheels", "407"]],
};

const WEEK = {
  title: "Parts used this week",
  columns: ["Part", "At the start", "Used by robots"],
  rows: [["Bolts", "725", "348"], ["Gears", "610", "195"], ["Springs", "530", "206"], ["Wheels", "400", "128"]],
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "The first bolt drop", machine: "Bolt Builder", icon: "grid", speaker: "kai",
    line: "Welcome to the Parts Depot! The bolt shelf has 245 bolts. A delivery bot just dropped off 132 more.",
    question: "Build 245 + 132 with the blocks. How many bolts are on the shelf now?",
    unit: "bolts",
    visual: { type: "blocks", places: HTO, title: "Bolt Builder" },
    hint: "Add each place. Hundreds: 2 + 1. Tens: 4 + 3. Ones: 5 + 2.",
    meter: { heat: 10, label: "Depot stocked +10%", story: "The bolt shelf is filling up" },
    discovery: { id: "hexbolts", name: "Six-sided bolts", who: "Kai", fact: "Most bolt heads have six flat sides. Six sides give a wrench lots of places to grip, even in a tight spot." },
    answer: { kind: "number", value: 377 },
    rightFeedback: "3 hundreds, 7 tens, 7 ones. 245 + 132 = 377 bolts!",
    wrong: [
      { value: 113, hint: "245 − 132 = 113. The bot ADDED bolts. Should there be more or fewer now?" },
      { value: 367, hint: "Check the tens. 4 tens + 3 tens = 7 tens." },
      { value: 387, hint: "Check the tens. 4 tens + 3 tens is 7 tens, not 8 tens." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Jump the gear line", machine: "Gear Counter", icon: "trail", speaker: "nova",
    line: "The gear bin has 370 gears. A repair bot rolls in with 60 more gears.",
    question: "Start at 370. Jump forward 60 by tens on the number line. Tap where you land.",
    unit: "gears",
    visual: { type: "numline", min: 300, max: 500, step: 10, pick: true, marks: [{ value: 370, label: "start" }], title: "Gear bin · jumps of 10", label: "gears" },
    hint: "60 is 6 tens. Make 6 jumps of 10: 380, 390, 400, ...",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The gear bin is counted" },
    answer: { kind: "number", value: 430 },
    rightFeedback: "380, 390, 400, 410, 420, 430. 370 + 60 = 430 gears!",
    wrong: [
      { value: 310, hint: "That's 370 − 60. The bot brought MORE gears. Jump forward." },
      { value: 420, hint: "That's 5 jumps. 60 is 6 tens, so make 6 jumps of 10." },
      { value: 440, hint: "That's 7 jumps. 60 is 6 tens, so make 6 jumps of 10." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Spring takeout", machine: "Spring Shelf", icon: "cells", speaker: "kai",
    line: "The spring shelf had 452 springs. The hopper robots just took 127 springs for their legs.",
    question: "What is 452 − 127? Build how many springs are left.",
    unit: "springs",
    visual: { type: "blocks", places: HTO, title: "Spring Shelf" },
    hint: "You can't take 7 ones from 2 ones. Trade 1 ten for 10 ones. Now you have 12 ones and 4 tens.",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The hopper robots got their springs" },
    discovery: { id: "rust", name: "Rust", who: "Nova", fact: "Iron and steel can rust when they stay wet in the air. Rust is flaky and reddish-brown, and it makes the metal weaker." },
    answer: { kind: "number", value: 325 },
    rightFeedback: "Trade a ten for 10 ones: 12 − 7 = 5. Then 4 tens − 2 tens = 2 tens and 4 − 1 = 3 hundreds. 325 springs!",
    wrong: [
      { value: 335, hint: "In the ones, you did 7 − 2. But we are taking 7 away from 2. Trade 1 ten for 10 ones first." },
      { value: 579, hint: "452 + 127 = 579. The robots TOOK springs. Should there be more or fewer?" },
      { value: 425, hint: "That's 452 − 27. Don't forget to take away the 1 hundred too." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The wheel guess", machine: "Estimator", icon: "dial", speaker: "nova",
    line: "Two wheel crates just came in. One has 386 wheels. The other has 213 wheels.",
    question: "Part 1: Round each crate to the nearest hundred. About how many wheels is that? Part 2: Find the exact total.",
    parts: [
      { type: "number", prompt: "Round 386 and 213 to the nearest hundred and add. About how many wheels?", unit: "wheels",
        visual: { type: "numline", min: 200, max: 400, step: 10, marks: [{ value: 213, label: "213" }, { value: 386, label: "386" }], title: "Which hundred is each crate closer to?", label: "wheels" } },
      { type: "number", prompt: "What is 386 + 213 exactly?", unit: "wheels" },
    ],
    hint: "386 is closer to 400 than to 300. 213 is closer to 200 than to 300. Then add the exact numbers place by place.",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The wheel crates are counted" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 600 }, { kind: "number", value: 599 }] },
    rightFeedback: "About 400 + 200 = 600. The exact total is 599, very close to our guess!",
    wrong: [
      { step: 1, value: 500, hint: "386 is past 350, so it rounds UP to 400, not down to 300." },
      { step: 1, value: 700, hint: "213 is closer to 200 than to 300. It rounds down." },
      { step: 2, value: 173, hint: "386 − 213 = 173. We are putting the two crates together. Add." },
      { step: 2, value: 589, hint: "Check the tens. 8 tens + 1 ten = 9 tens." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The loader bot tumble", machine: "Stock Log", icon: "snap", speaker: "vega",
    line: "Surprise! A loader bot tripped on a cable. Its crate tipped, and 85 bolts rolled down a drain! Then a gear truck pulled up with 150 new gears.",
    question: "Part 1: How many bolts are left? Part 2: How many gears are there now? Part 3: How many more gears than bolts does the depot have now?",
    parts: [
      { type: "number", prompt: "85 bolts rolled away. How many bolts are left?", unit: "bolts", data: STOCK },
      { type: "number", prompt: "The truck brought 150 gears. How many gears are there now?", unit: "gears", data: STOCK },
      { type: "number", prompt: "How many more gears than bolts are there now?", unit: "gears" },
    ],
    hint: "Read the stock log. Subtract the lost bolts. Add the new gears. Then compare the two new numbers by subtracting.",
    meter: { heat: 10, label: "Depot stocked +10%", story: "The stock log is fixed after the tumble" },
    discovery: { id: "rivets", name: "Rivets", who: "Kai", fact: "The Eiffel Tower in France is held together by about 2.5 million metal pins called rivets." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 233 }, { kind: "number", value: 395 }, { kind: "number", value: 162 }] },
    rightFeedback: "318 − 85 = 233 bolts. 245 + 150 = 395 gears. 395 − 233 = 162 more gears!",
    wrong: [
      { step: 1, value: 373, hint: "In the tens, you did 8 − 1. But we take 8 tens away from 1 ten. Trade 1 hundred for 10 tens first." },
      { step: 1, value: 403, hint: "The bolts rolled AWAY. Should there be more or fewer bolts?" },
      { step: 1, value: 243, hint: "Check the tens. After you trade 1 hundred for 10 tens, you have 11 tens. 11 − 8 = 3 tens." },
      { step: 2, value: 95, hint: "The truck BROUGHT gears. Add 150 to 245." },
      { step: 2, value: 385, hint: "Check the tens. 4 tens + 5 tens = 9 tens." },
      { step: 3, value: 628, hint: "How many MORE means compare. Subtract the smaller number from the bigger one." },
      { step: 3, value: 172, hint: "Check the tens. 9 tens − 3 tens = 6 tens." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Fill the spring shelf", machine: "Equation Bay", icon: "cells", speaker: "nova",
    line: "The big spring shelf holds 600 springs. Right now it has 275. I drew a strip: [ 275 | ? ] = 600.",
    question: "Part 1: Pick every equation that matches the strip. Part 2: Build how many more springs we need.",
    parts: [
      { type: "multi", prompt: "The strip shows 275 and a missing part that make 600. Pick every equation that matches.", choices: [
        { id: "add", text: "275 + ? = 600" },
        { id: "sub", text: "600 − 275 = ?" },
        { id: "both", text: "275 + 600 = ?" },
        { id: "back", text: "275 − 600 = ?" },
      ] },
      { type: "number", prompt: "How many more springs fill the shelf? Build it.", unit: "springs",
        visual: { type: "blocks", places: HTO, title: "Missing part" } },
    ],
    hint: "The whole strip is 600. One part is 275. You can count up from 275 to 600, or subtract 600 − 275.",
    meter: { supplies: 2, label: "Shelves filled +2", story: "The spring shelf is full" },
    discovery: { id: "steel", name: "Steel", who: "Nova", fact: "Steel is made mostly of iron with a tiny bit of carbon mixed in. That makes it much stronger than plain iron." },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["add", "sub"] }, { kind: "number", value: 325 }] },
    rightFeedback: "275 + 325 = 600, and 600 − 275 = 325. Addition and subtraction are two ways to see the same strip!",
    wrong: [
      { step: 1, pick: "both", hint: "600 is the WHOLE strip. Adding 600 more would make it longer than the shelf." },
      { step: 1, pick: "back", hint: "We can't take 600 away from 275. The whole is 600." },
      { step: 1, missing: true, hint: "Two equations match: one with a missing part in an addition, and one subtraction." },
      { step: 2, value: 875, hint: "275 + 600 = 875. The shelf only holds 600. Find the missing part." },
      { step: 2, value: 475, hint: "In the ones and tens, you took the smaller digit from the bigger one. 600 has 0 tens and 0 ones, so trade a hundred first." },
      { step: 2, value: 425, hint: "Count up: 275 + 25 = 300. Then 300 + 300 = 600. Add the jumps: 25 + 300." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The zero trouble debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The gear rack had 503 gears. Robots took 278. In each place I take the small digit from the big one: 8 − 3 = 5, 7 − 0 = 7, 5 − 2 = 3. That\'s 375!"',
    nova: 'Nova: "You can\'t flip the digits. 3 ones minus 8 ones needs a trade, and there are 0 tens. So trade 1 hundred for 10 tens, then 1 ten for 10 ones. 503 − 278 = 225."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    visual: { type: "blocks", mode: "show", places: HTO, counts: { hundreds: 5, tens: 0, ones: 3 }, title: "503 gears on the rack" },
    hint: "Check with addition. Does 375 + 278 make 503? Does 225 + 278?",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The gear rack count is right" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. You always take the bottom number away from the top. With 0 tens, trade a hundred, then a ten. 225 + 278 = 503, so 225 checks out." },
      { id: "B", text: "Nova, because a smaller answer is always safer." },
      { id: "C", text: "Kai. You always take the smaller digit from the bigger digit." },
      { id: "D", text: "Kai. There are 0 tens, so you just skip that place." },
    ],
    writtenPrompt: "Tell Kai in your own words why 503 − 278 is not 375.",
    debateHints: {
      wrongWho: "Add to check: 375 + 278 = 653. Is that the 503 gears we started with?",
      wrongReason: "Right person, check the reason. How can you check a subtraction answer?",
      right: "Nova is right. Trade across the zero: 4 hundreds, 9 tens, 13 ones. 503 − 278 = 225, and 225 + 278 = 503.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Sort the rush orders", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "Six rush orders just printed out! Before I pack them, I want to know about how big each one is.",
    question: "Round each number to the nearest hundred. Sort each order by its estimate.",
    hint: "Round each number first. 198 rounds to 200 and 103 rounds to 100. Then add or subtract the rounded numbers.",
    meter: { supplies: 1, label: "Shelves filled +1", story: "The rush orders are sorted" },
    discovery: { id: "tighten", name: "Righty-tighty", who: "Kai", fact: "Most bolts and screws tighten when you turn them to the right, the way a clock's hands go. People say \"righty-tighty, lefty-loosey.\"" },
    answer: { kind: "sort", bins: { o1: "b300", o2: "b300", o3: "b500", o4: "b500", o5: "b700", o6: "b700" } },
    rightFeedback: "Every order is in the right bin! Rounding first makes a quick estimate.",
    sort: {
      bins: [
        { id: "b300", label: "About 300" },
        { id: "b500", label: "About 500" },
        { id: "b700", label: "About 700" },
      ],
      items: [
        { id: "o1", label: "198 bolts + 103 bolts" },
        { id: "o2", label: "612 gears − 289 gears" },
        { id: "o3", label: "251 springs + 249 springs" },
        { id: "o4", label: "815 wheels − 307 wheels" },
        { id: "o5", label: "486 bolts + 212 bolts" },
        { id: "o6", label: "903 gears − 196 gears" },
      ],
    },
    wrong: [
      { item: "o1", hint: "198 rounds to 200 and 103 rounds to 100. 200 + 100 = ?" },
      { item: "o2", hint: "612 rounds to 600 and 289 rounds to 300. 600 − 300 = ?" },
      { item: "o3", hint: "251 rounds up to 300. 249 rounds down to 200. 300 + 200 = ?" },
      { item: "o4", hint: "815 rounds to 800 and 307 rounds to 300. 800 − 300 = ?" },
      { item: "o5", hint: "486 rounds to 500 and 212 rounds to 200. 500 + 200 = ?" },
      { item: "o6", hint: "903 rounds to 900 and 196 rounds to 200. 900 − 200 = ?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's wheel count", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote: "Rack A has 467 wheels. Rack B has 285. 7 + 5 = 12, write 2. 6 + 8 = 14, write 4. 4 + 2 = 6. So 467 + 285 = 642." Something is off.',
    question: "Part 1: What went wrong? Part 2: Build the right total.",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He didn't regroup. 12 ones is 1 ten and 2 ones, and 14 tens is 1 hundred and 4 tens. He dropped the extra ten and hundred." },
        { id: "b", text: "He should have subtracted, because the racks are different sizes." },
        { id: "c", text: "He added the hundreds wrong. 4 + 2 = 7." },
        { id: "d", text: "Nothing. 642 is right." },
      ] },
      { type: "number", prompt: "Add 467 + 285 the right way. Build the total.", unit: "wheels",
        visual: { type: "blocks", places: HTO, title: "Wheel racks together" } },
    ],
    hint: "Estimate first: 467 is about 500 and 285 is about 300. Is 642 close to 800?",
    meter: { supplies: 1, label: "Shelves filled +1", story: "Kai's wheel count is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 752 }] },
    rightFeedback: "Fixed! 12 ones → 2 ones and 1 ten. 6 + 8 + 1 = 15 tens → 5 tens and 1 hundred. 4 + 2 + 1 = 7 hundreds. 752 wheels!",
    wrong: [
      { step: 1, choice: "b", hint: "Both racks go together, so we add. The mistake is in how Kai added." },
      { step: 1, choice: "c", hint: "4 + 2 is 6. Kai's hundreds fact is right. What happened to the extra 1 ten from 12 ones?" },
      { step: 1, choice: "d", hint: "Estimate: about 500 + 300 = 800. Is 642 close to that?" },
      { step: 2, value: 642, hint: "That's Kai's answer. Don't drop the regrouped ten and hundred." },
      { step: 2, value: 742, hint: "You carried the ten into the tens, but 15 tens is 1 hundred and 5 tens. Carry the hundred too." },
      { step: 2, value: 652, hint: "You carried the hundred but not the ten. 12 ones gives 1 extra ten." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The rover rush", machine: "Wheel Rack", icon: "quake", speaker: "vega",
    line: "Surprise! A rover team zoomed in and took 260 wheels from our rack of 540. An hour later, a delivery truck brought 175 new wheels.",
    question: "Part 1: How many wheels were left after the rover team? Part 2: How many are there after the truck? Part 3: Is your answer reasonable?",
    parts: [
      { type: "number", prompt: "Start at 540. Jump back 260. Tap where you land.", unit: "wheels",
        visual: { type: "numline", min: 200, max: 600, step: 20, pick: true, marks: [{ value: 540, label: "start" }], title: "Wheel rack · count back", label: "wheels" } },
      { type: "number", prompt: "The truck brought 175 wheels. How many wheels are on the rack now?", unit: "wheels" },
      { type: "choice", prompt: "Is your answer reasonable?", choices: [
        { id: "a", text: "Yes. Round to the nearest ten: 540 − 260 + 180 = 460. That's close to 455." },
        { id: "b", text: "No. It should be about 975, because you add all three numbers." },
        { id: "c", text: "No. The answer has to be exactly 460." },
        { id: "d", text: "Yes, because it is less than 540." },
      ] },
    ],
    hint: "Jump back 200 to 340, then back 60 more. Then add 175. Round each number to check.",
    meter: { heat: 10, label: "Depot stocked +10%", story: "The rover team is rolling and the rack is refilled" },
    discovery: { id: "potterwheel", name: "The first wheels", who: "Nova", fact: "Some of the very first wheels were not used for carts. People used spinning wheels to shape clay pots." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 280 }, { kind: "number", value: 455 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "540 − 260 = 280. 280 + 175 = 455. The estimate of 460 is close, so 455 makes sense!",
    wrong: [
      { step: 1, value: 320, hint: "In the tens, you did 6 − 4. But we take 6 tens away from 4 tens. Trade a hundred first. Or jump back 200, then 60." },
      { step: 1, value: 340, hint: "That's 540 − 200. Keep going: jump back 60 more." },
      { step: 2, value: 105, hint: "The truck BROUGHT wheels. Add 175 to 280." },
      { step: 2, value: 355, hint: "8 tens + 7 tens = 15 tens. That's 1 hundred and 5 tens. Did you add the extra hundred?" },
      { step: 3, choice: "b", hint: "The rover team TOOK wheels. Only the truck adds wheels." },
      { step: 3, choice: "c", hint: "An estimate is close, not exact. 455 is close to 460." },
      { step: 3, choice: "d", hint: "Lots of wrong numbers are less than 540. Compare with an estimate." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The weekly parts log", machine: "Stock Log", icon: "scan", speaker: "vega",
    line: "It's the end of the week. Nova made a table of how many parts we started with and how many the robots used.",
    question: "Part 1: How many bolts are left? Part 2: How many gears are left? Part 3: Which part has the most left?",
    parts: [
      { type: "number", prompt: "How many bolts are left?", unit: "bolts", data: WEEK },
      { type: "number", prompt: "How many gears are left?", unit: "gears", data: WEEK },
      { type: "choice", prompt: "Springs have 324 left and wheels have 272 left. Which part has the most left?", choices: [
        { id: "a", text: "Gears" },
        { id: "b", text: "Bolts, because they started with the most." },
        { id: "c", text: "Wheels, because the robots used the fewest." },
        { id: "d", text: "Springs" },
      ] },
    ],
    hint: "Left = at the start − used. Trade when the top digit is too small. Then compare all four answers.",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The weekly log is done" },
    discovery: { id: "stainless", name: "Stainless steel", who: "Nova", fact: "Stainless steel has a metal called chromium mixed in. The chromium helps keep it from rusting." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 377 }, { kind: "number", value: 415 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "725 − 348 = 377 bolts and 610 − 195 = 415 gears. Gears have the most left!",
    wrong: [
      { step: 1, value: 423, hint: "You took the smaller digit from the bigger one in each place. 5 ones − 8 ones needs a trade." },
      { step: 1, value: 1073, hint: "725 + 348 adds the bolts that were USED. Subtract to find what's left." },
      { step: 2, value: 585, hint: "0 ones − 5 ones needs a trade. Don't flip the digits." },
      { step: 2, value: 805, hint: "The robots USED gears. Subtract 195 from 610." },
      { step: 3, choice: "b", hint: "Bolts started with the most, but the robots used a lot. Compare what is LEFT." },
      { step: 3, choice: "c", hint: "Wheels had the fewest used, but only 272 are left. Compare what is LEFT." },
      { step: 3, choice: "d", hint: "Springs have 324 left. Is that more than 415?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Nova's make-a-hundred trick", machine: "Shortcut Lab", icon: "dial", speaker: "nova",
    line: "The spring order is 198 coil springs and 346 flat springs. 198 is so close to 200! I have a trick.",
    question: "Part 1: Which trick gives the same total as 198 + 346? Part 2: What is the total?",
    parts: [
      { type: "choice", prompt: "Which trick keeps the total the same?", choices: [
        { id: "a", text: "Move 2 from 346 over to 198. 198 + 346 = 200 + 344." },
        { id: "b", text: "Just change 198 to 200. 198 + 346 = 200 + 346." },
        { id: "c", text: "Switch to 346 − 198." },
        { id: "d", text: "Round both: 200 + 300." },
      ] },
      { type: "number", prompt: "How many springs are in the order?", unit: "springs" },
    ],
    hint: "If you give 2 to one number, you have to take 2 from the other. Then the total stays the same.",
    meter: { heat: 5, label: "Depot stocked +5%", story: "The spring order is added fast" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 544 }] },
    rightFeedback: "200 + 344 = 544, and so does 198 + 346. Moving 2 over keeps the total the same!",
    wrong: [
      { step: 1, choice: "b", hint: "Changing 198 to 200 adds 2 springs that aren't really there. Take 2 from the other number too." },
      { step: 1, choice: "c", hint: "Subtracting finds a difference, not a total. We are adding the springs." },
      { step: 1, choice: "d", hint: "Rounding gives an estimate. We need the exact total." },
      { step: 2, value: 546, hint: "That's 200 + 346. You added 2 but didn't take 2 away from 346." },
      { step: 2, value: 148, hint: "346 − 198 = 148. The order has BOTH kinds of springs. Add." },
      { step: 2, value: 534, hint: "Check the tens. 200 + 344: 0 tens + 4 tens = 4 tens." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Count back the gear order", machine: "Gear Counter", icon: "trail", speaker: "kai",
    line: "We had 683 gears. The clock-tower robots ordered 253. I'll jump back 200, then 50, then 3.",
    question: "Part 1: Tap where Kai lands after all his jumps. Part 2: Which addition checks the answer?",
    parts: [
      { type: "number", prompt: "683 − 253. Jump back 200, then 50, then 3. Tap where you land.", unit: "gears",
        visual: { type: "numline", min: 400, max: 700, step: 10, pick: true, marks: [{ value: 683, label: "683" }], title: "Gear counter · count back", label: "gears" } },
      { type: "choice", prompt: "Which addition checks 683 − 253?", choices: [
        { id: "a", text: "430 + 253 = 683" },
        { id: "b", text: "683 + 253 = 936" },
        { id: "c", text: "430 + 683 = 1,113" },
        { id: "d", text: "253 + 200 = 453" },
      ] },
    ],
    hint: "683 − 200 = 483. 483 − 50 = 433. 433 − 3 = ? To check, add your answer to the part you took away.",
    meter: { supplies: 1, label: "Shelves filled +1", story: "The clock-tower order ships out" },
    discovery: { id: "bikechain", name: "Bike chains", who: "Kai", fact: "On a bike, a chain links the gear by the pedals to a gear on the back wheel. Pedaling pulls the chain and turns the wheel." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 430 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "683 → 483 → 433 → 430. And 430 + 253 = 683, so it checks!",
    wrong: [
      { step: 1, value: 530, hint: "You jumped back only 100. The first jump is 200." },
      { step: 1, value: 420, hint: "You went back 10 too far. 253 is 200 + 50 + 3." },
      { step: 1, value: 440, hint: "Don't forget the last jump. 433 − 3 = 430." },
      { step: 2, choice: "b", hint: "That adds the two numbers from the problem. To check, add the answer to the part taken away." },
      { step: 2, choice: "c", hint: "The answer plus the part taken away should give back the start, 683." },
      { step: 2, choice: "d", hint: "That doesn't use the answer at all. Add 430 to 253." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Three spring orders", machine: "Order Packer", icon: "cells", speaker: "kai",
    line: "Three robots want springs: 125 springs, 250 springs, and 175 springs. The spring shelf has 900.",
    question: "Part 1: Which order makes adding easiest? Part 2: How many springs in all? Part 3: Build how many are left on the shelf.",
    parts: [
      { type: "choice", prompt: "What is the easiest way to add 125 + 250 + 175?", choices: [
        { id: "a", text: "Add 125 + 175 first. They make 300. Then add 250." },
        { id: "b", text: "You must add them in the order they came." },
        { id: "c", text: "Add 250 + 175 first, because they are the biggest." },
        { id: "d", text: "Subtract 125 from 175 first." },
      ] },
      { type: "number", prompt: "How many springs do the three robots want in all?", unit: "springs",
        data: { title: "Spring orders", columns: ["Robot", "Springs"], rows: [["Robot 1", "125"], ["Robot 2", "250"], ["Robot 3", "175"]] } },
      { type: "number", prompt: "900 springs on the shelf. Build how many are left after the orders.", unit: "springs",
        visual: { type: "blocks", places: HTO, title: "Springs left" } },
    ],
    hint: "25 + 75 = 100, so 125 + 175 = 300. You can add in any order. Then subtract the total from 900.",
    meter: { heat: 5, label: "Depot stocked +5%", story: "Three robots get their springs" },
    discovery: { id: "ferriswheel", name: "The first Ferris wheel", who: "Nova", fact: "The first Ferris wheel was built in Chicago in 1893. It was more than 250 feet tall." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 550 }, { kind: "number", value: 350 }] },
    rightFeedback: "125 + 175 = 300, and 300 + 250 = 550. 900 − 550 = 350 springs left!",
    wrong: [
      { step: 1, choice: "b", hint: "You can add numbers in any order and the total stays the same. Look for two that make a friendly number." },
      { step: 1, choice: "c", hint: "That works, but it's not the easiest. Which two numbers make a hundred?" },
      { step: 1, choice: "d", hint: "All three orders go out, so we add. We don't subtract here." },
      { step: 2, value: 300, hint: "That's 125 + 175. Add the 250 too." },
      { step: 2, value: 375, hint: "That's 125 + 250. Add the 175 too." },
      { step: 3, value: 1450, hint: "The orders LEAVE the shelf. Subtract 550 from 900." },
      { step: 3, value: 450, hint: "0 tens − 5 tens needs a trade. Trade 1 hundred for 10 tens: 8 hundreds, 10 tens." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Grand restock day", machine: "Bolt Builder", icon: "relay", speaker: "vega",
    line: "It's Grand Restock Day! The bolt shelf has 468 bolts, and a truck drops off 285 more. Surprise! A crowd of builder bots rolls in and buys 396 bolts at once!",
    question: "Part 1: How many bolts after the truck? Part 2: How many after the builder bots? Part 3: Is your answer reasonable? Part 4: The shelf holds 900. How many more fill it?",
    parts: [
      { type: "number", prompt: "468 + 285. Build how many bolts are on the shelf after the truck.", unit: "bolts",
        visual: { type: "blocks", places: HTO, title: "Bolt Builder" } },
      { type: "number", prompt: "The builder bots buy 396 bolts. How many bolts are left?", unit: "bolts" },
      { type: "choice", prompt: "Round each number to the nearest hundred. Is your answer reasonable?", choices: [
        { id: "a", text: "Yes. 500 + 300 − 400 = 400, and 357 is close to 400." },
        { id: "b", text: "No. It should be about 1,100, because you add all three." },
        { id: "c", text: "No. The answer must be exactly 400." },
        { id: "d", text: "Yes, because it is an odd number." },
      ] },
      { type: "number", prompt: "The shelf holds 900 bolts. How many more bolts will fill it?", unit: "bolts" },
    ],
    hint: "Add the truck's bolts. Subtract what the bots bought. Round to check. Then find the missing part from your answer to 900.",
    meter: { heat: 10, label: "Depot stocked +10%", story: "The Parts Depot is fully stocked" },
    discovery: { id: "aluminum", name: "Aluminum cans", who: "Kai", fact: "An aluminum can can be recycled and made into a new can again and again." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 753 }, { kind: "number", value: 357 }, { kind: "choice", correct: "a" }, { kind: "number", value: 543 }] },
    rightFeedback: "468 + 285 = 753. 753 − 396 = 357. That's close to 400. 900 − 357 = 543 more bolts. The depot is ready!",
    wrong: [
      { step: 1, value: 643, hint: "8 + 5 = 13 ones and 6 + 8 = 14 tens. Regroup! Carry the extra ten and the extra hundred." },
      { step: 1, value: 183, hint: "The truck ADDED bolts. Add 285 to 468." },
      { step: 1, value: 743, hint: "You carried the hundred but not the ten. 13 ones gives 1 extra ten." },
      { step: 2, value: 443, hint: "You took the smaller digit from the bigger one. 3 ones − 6 ones needs a trade." },
      { step: 2, value: 1149, hint: "The bots BOUGHT bolts. Subtract 396 from 753." },
      { step: 2, value: 457, hint: "Check the hundreds. After trading, 6 hundreds − 3 hundreds = 3 hundreds." },
      { step: 3, choice: "b", hint: "The bots took bolts away. Only the truck adds." },
      { step: 3, choice: "c", hint: "An estimate is close, not exact." },
      { step: 3, choice: "d", hint: "Being odd doesn't tell us if an answer is close. Compare with an estimate." },
      { step: 4, value: 657, hint: "0 ones − 7 ones needs a trade. 900 has 0 tens too, so trade a hundred, then a ten." },
      { step: 4, value: 1257, hint: "We need the missing part up to 900. Subtract 357 from 900, or count up." },
      { step: 4, value: 643, hint: "Check the hundreds. After you trade, 8 hundreds − 3 hundreds = 5 hundreds." },
    ],
  },
};

export default {
  id: "MA.3.4A-XP",
  standard: "MA.3.4A-XP",
  engine: "expedition_station",
  title: "The Parts Depot",
  planet: "Mechara",
  outpost: "Robot City · the Parts Depot",
  grade: 3,
  subject: "Math",
  teks: "3.4A",
  supportingTeks: ["3.4B", "3.5A"],
  skillsChip: "3.4A · Add and subtract within 1,000",
  iCan: "I can add and subtract within 1,000 using place value, number lines, and equations, and I can estimate to check if my answer makes sense.",
  blurb: "The robots of Mechara get their bolts, gears, springs, and wheels at the Parts Depot. The crew has to add deliveries, subtract orders, and keep the stock log right.",
  mission: "Restock the Parts Depot, fill every robot's order, and keep the stock log exactly right.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.4A · MECHARA PARTS DEPOT",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Depot stocked", heatUnit: "%", supplies: "Shelves filled", suppliesUnit: "shelves" },
  journalMax: 10,
  grade3Limits: "Whole numbers within 1,000. Addition and subtraction with regrouping. Rounding to the nearest 10 or 100.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. We've landed in the robot city on Mechara.",
    "Every robot here gets its bolts, gears, springs, and wheels from one place: the Parts Depot.",
    "Help Kai and Nova add the deliveries, subtract the orders, and keep the shelves full. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Open the depot", "Act 2 · Rush orders", "Act 3 · Grand Restock Day"],
    completes: [
      "The depot is open and the stock log is right, {firstName}!",
      "Every rush order is packed and the wheel rack is full, {firstName}!",
      "The Parts Depot is fully stocked, {firstName}! Every robot in the city can keep moving.",
    ],
    teasers: [
      "Next on Mechara: rush orders are pouring in. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: Grand Restock Day is coming. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Rush orders are printing out, and the robots are waiting.",
      "Kai's math has a few slips, so let's check his work together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Grand Restock Day is almost here.",
      "Help the crew finish the weekly log and fill every shelf in the depot.",
    ],
  }),
  tasks,
};
