// Expedition Station — The Pattern Machine (MA.4.5B-XP)
// Grade 4 · Math · Mechara. Main standard 4.5B (use input-output tables and
// numerical expressions to generate a number pattern that follows a rule
// relating each value to its position); also practices 4.5A (multi-step
// problems with strip diagrams and equations with a letter for the unknown).
// Rules are "add n to the position" or "multiply the position by n".
import { CREW, acts } from "./_shared.js";

const table = (title, pairs, cols = ["Position", "Value"]) => ({
  title,
  columns: cols,
  rows: pairs.map(([a, b]) => [String(a), String(b)]),
});

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Robots on the belt", machine: "Line Counter", icon: "grid", speaker: "kai",
    line: "Welcome to the Mechara assembly line! Every spot on the belt has a position number. The machine puts robots at each spot. Look at the table.",
    question: "How many robots will the machine put at position 5?",
    unit: "robots",
    data: table("Assembly line · robots at each spot", [[1, 4], [2, 8], [3, 12], [4, 16], [5, "?"]]),
    hint: "Compare each position to its value. Position 1 has 4. Position 2 has 8. What do you do to the position to get the value?",
    meter: { heat: 10, label: "Line speed +10%", story: "The first belt is running" },
    discovery: { id: "lightcurtain", name: "Robot safety", who: "Kai", fact: "Many factory robots work behind fences or invisible light beams called light curtains. If a person steps through the beams, the robot stops right away." },
    answer: { kind: "number", value: 20 },
    rightFeedback: "The rule is multiply the position by 4. 5 × 4 = 20 robots!",
    wrong: [
      { value: 17, hint: "The values go up by 4, not by 1. Look at 4, 8, 12, 16. What comes next?" },
      { value: 9, hint: "Adding 4 to the position works for no spot here. Position 2 has 8, and 2 + 4 is 6. Try multiplying." },
      { value: 24, hint: "Check position 5. 5 × 4 is 20. Did you jump one spot too far?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Crack the bolt rule", machine: "Bolt Press", icon: "dial", speaker: "nova",
    line: "The bolt press drops bolts into each bin. The robots here follow a secret rule. I wrote down what it did.",
    question: "Which rule tells the value from the position?",
    data: table("Bolt press · bolts in each bin", [[1, 4], [2, 5], [3, 6], [4, 7]]),
    choices: [
      { id: "a", text: "Add 3 to the position" },
      { id: "b", text: "Multiply the position by 3" },
      { id: "c", text: "Add 1 to the position" },
      { id: "d", text: "Multiply the position by 4" },
    ],
    hint: "Test a rule on every row. Position 1 has 4 bolts. Position 4 has 7 bolts. What gets you from 1 to 4 and also from 4 to 7?",
    meter: { heat: 5, label: "Line speed +5%", story: "The bolt press is decoded" },
    discovery: { id: "binary", name: "Computers count with 0 and 1", who: "Nova", fact: "Computers store numbers, words, and pictures using only two digits, 0 and 1. This is called binary." },
    answer: { kind: "choice", correct: "a" },
    rightFeedback: "1 + 3 = 4, 2 + 3 = 5, 3 + 3 = 6, 4 + 3 = 7. The rule is add 3 to the position!",
    wrong: [
      { choice: "b", hint: "Test position 2. 2 × 3 = 6, but the table shows 5. That rule doesn't fit." },
      { choice: "c", hint: "The values go up by 1 each time, but 1 + 1 = 2, not 4. The rule must turn the position into the value." },
      { choice: "d", hint: "That works for position 1, since 1 × 4 = 4. Test position 2: 2 × 4 = 8, not 5." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Build the gear stack", machine: "Gear Stacker", icon: "cells", speaker: "kai",
    line: "The gear stacker uses the rule multiply the position by 3. The value cards fell off the screen and got mixed up!",
    question: "Put the values in order for positions 1 to 5.",
    items: [
      { id: "v9", text: "9" },
      { id: "v15", text: "15" },
      { id: "v3", text: "3" },
      { id: "v12", text: "12" },
      { id: "v6", text: "6" },
    ],
    hint: "Use the rule on each position: 1 × 3, 2 × 3, 3 × 3, 4 × 3, 5 × 3.",
    meter: { supplies: 1, label: "Rules cracked +1", story: "The gear stacks are sorted" },
    discovery: { id: "morse", name: "Morse code", who: "Nova", fact: "Morse code spells out letters with a pattern of short and long signals called dots and dashes. The letter S is dot, dot, dot." },
    answer: { kind: "order", correct: ["v3", "v6", "v9", "v12", "v15"] },
    rightFeedback: "3, 6, 9, 12, 15. Each value is its position times 3!",
    wrong: [
      { position: 0, hint: "Position 1 comes first. 1 × 3 = 3." },
      { position: 1, hint: "Position 2 is next. 2 × 3 = 6." },
      { position: 2, hint: "Position 3 is next. 3 × 3 = 9." },
      { position: 3, hint: "Position 4 is next. 4 × 3 = 12." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Write it as math", machine: "Code Panel", icon: "log", speaker: "nova",
    line: "The robot line in Hall 4 uses the rule multiply the position by 4. I want to type one expression into the code panel.",
    question: "Which expression gives the value at position 7?",
    choices: [
      { id: "a", text: "4 × 7" },
      { id: "b", text: "7 + 4" },
      { id: "c", text: "4 × 6" },
      { id: "d", text: "28 × 4" },
    ],
    hint: "The rule says multiply the position by 4. The position is 7. Put those two numbers in a multiplication.",
    meter: { heat: 5, label: "Line speed +5%", story: "The code panel is set" },
    answer: { kind: "choice", correct: "a" },
    rightFeedback: "4 × 7 = 28. The expression uses the position and the rule!",
    wrong: [
      { choice: "b", hint: "That adds 4. The rule says multiply the position by 4." },
      { choice: "c", hint: "Use position 7, not 6. Which expression has a 7 in it?" },
      { choice: "d", hint: "28 is already the value. Use the position, 7, in the expression." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The belt skips ahead", machine: "Line Counter", icon: "snap", speaker: "vega",
    line: "Surprise! A power surge made the conveyor belt jump ahead. Some screen cells are blank now. We have to crack the rule to fill them in.",
    question: "Part 1: Which rule fits the table? Part 2: What is the value at position 6? Part 3: What is the value at position 10? Part 4: Which position has a value of 35?",
    data: table("Conveyor belt · wheels at each spot", [[1, 11], [2, 12], [3, 13], [6, "?"], [10, "?"]]),
    parts: [
      { type: "choice", prompt: "Which rule turns each position into its value?", choices: [
        { id: "a", text: "Add 10 to the position" },
        { id: "b", text: "Multiply the position by 11" },
        { id: "c", text: "Add 1 to the position" },
        { id: "d", text: "Multiply the position by 10" },
      ] },
      { type: "number", prompt: "What is the value at position 6?", unit: "wheels" },
      { type: "number", prompt: "What is the value at position 10?", unit: "wheels" },
      { type: "number", prompt: "The value is 35. What is the position?", unit: "position" },
    ],
    hint: "Position 1 has 11. 1 + 10 = 11. Check that rule on positions 2 and 3. To go backward, take 10 away from the value.",
    meter: { heat: 10, label: "Line speed +10%", story: "The belt is back on track" },
    discovery: { id: "saltcube", name: "Salt crystals", who: "Nova", fact: "Grains of table salt are tiny cube-shaped crystals. Inside, the salt particles line up in a pattern that repeats again and again." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 16 }, { kind: "number", value: 20 }, { kind: "number", value: 25 }] },
    rightFeedback: "Add 10 to the position! 6 + 10 = 16, 10 + 10 = 20, and 25 + 10 = 35.",
    wrong: [
      { step: 1, choice: "b", hint: "Test position 2. 2 × 11 = 22, but the table shows 12." },
      { step: 1, choice: "c", hint: "The values go up by 1, but 1 + 1 = 2, not 11. What turns 1 into 11?" },
      { step: 1, choice: "d", hint: "Test position 1. 1 × 10 = 10, but the table shows 11." },
      { step: 2, value: 14, hint: "After 13, the table skips to position 6. Use the rule on position 6: 6 + 10." },
      { step: 2, value: 60, hint: "That multiplies by 10. The rule is add 10 to the position." },
      { step: 3, value: 100, hint: "That multiplies by 10. The rule is add 10: 10 + 10." },
      { step: 3, value: 17, hint: "Use the rule on position 10, not the next value after 16." },
      { step: 4, value: 45, hint: "35 is the value. Go backward: take 10 away from 35." },
      { step: 4, value: 35, hint: "35 is the value, not the position. What position plus 10 makes 35?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Jump to spot 25", machine: "Far Scanner", icon: "trail", speaker: "kai",
    line: "The belt in Hall 6 is super long. I don't want to count spot by spot all the way to position 25. There has to be a faster way!",
    question: "The rule is multiply the position by 5. What is the value at position 25?",
    unit: "arms",
    data: table("Hall 6 · robot arms at each spot", [[1, 5], [2, 10], [3, 15], [4, 20], [25, "?"]]),
    hint: "You don't have to list every spot. Use the rule on position 25: 25 × 5.",
    meter: { supplies: 1, label: "Rules cracked +1", story: "Kai jumps to spot 25" },
    discovery: { id: "barcode", name: "Barcodes", who: "Kai", fact: "A barcode is a pattern of black bars and white spaces. A scanner reads the pattern and turns it into numbers." },
    answer: { kind: "number", value: 125 },
    rightFeedback: "25 × 5 = 125. The rule lets you jump right to any position!",
    wrong: [
      { value: 30, hint: "That adds 5 to the position. The rule is multiply the position by 5." },
      { value: 120, hint: "That's the value at position 24. Use position 25: 25 × 5." },
      { value: 25, hint: "25 is the position. Use the rule to find the value." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Quality check", machine: "Sort Bay", icon: "cells", speaker: "vega",
    line: "The rule on this line is multiply the position by 6. Some robots came out with the wrong number of parts. Help me find them.",
    question: "Sort each card. Does it fit the rule multiply the position by 6?",
    hint: "Multiply each position by 6. Does the answer match the value on the card?",
    meter: { supplies: 1, label: "Rules cracked +1", story: "The bad robots are pulled off the line" },
    answer: { kind: "sort", bins: { p3: "fit", p5: "fit", p8: "fit", p4: "bad", p7: "bad", p9: "bad" } },
    rightFeedback: "3 × 6 = 18, 5 × 6 = 30, and 8 × 6 = 48 fit. The other three break the rule!",
    sort: {
      bins: [
        { id: "fit", label: "Fits the rule" },
        { id: "bad", label: "Breaks the rule" },
      ],
      items: [
        { id: "p3", label: "Position 3 → Value 18" },
        { id: "p4", label: "Position 4 → Value 10" },
        { id: "p5", label: "Position 5 → Value 30" },
        { id: "p7", label: "Position 7 → Value 13" },
        { id: "p8", label: "Position 8 → Value 48" },
        { id: "p9", label: "Position 9 → Value 56" },
      ],
    },
    wrong: [
      { item: "p3", hint: "3 × 6 = 18. This card fits." },
      { item: "p4", hint: "4 + 6 = 10. That's adding. 4 × 6 is 24." },
      { item: "p5", hint: "5 × 6 = 30. This card fits." },
      { item: "p7", hint: "7 + 6 = 13. That's adding. 7 × 6 is 42." },
      { item: "p8", hint: "8 × 6 = 48. This card fits." },
      { item: "p9", hint: "Check it: 9 × 6 = 54, not 56." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Which outputs belong?", machine: "Output Chute", icon: "water", speaker: "nova",
    line: "This machine takes an input from 1 to 10 and uses the rule multiply the input by 9. A pile of number tags landed by the chute.",
    question: "Pick every output that could come out of this machine.",
    data: table("Output chute · rule: multiply the input by 9", [[1, 9], [2, "?"], [3, 27], [4, "?"], [5, "?"]], ["Input", "Output"]),
    items: [
      { id: "o18", text: "18" },
      { id: "o19", text: "19" },
      { id: "o45", text: "45" },
      { id: "o60", text: "60" },
      { id: "o72", text: "72" },
      { id: "o90", text: "90" },
    ],
    hint: "For each tag, ask: is there an input from 1 to 10 that times 9 makes this number?",
    meter: { heat: 5, label: "Line speed +5%", story: "The output tags are sorted" },
    discovery: { id: "jacquard", name: "Loom cards", who: "Kai", fact: "Over 200 years ago, a weaving machine called the Jacquard loom used cards with punched holes to weave patterns into cloth. That idea helped inspire early computers." },
    answer: { kind: "multi", correct: ["o18", "o45", "o72", "o90"] },
    rightFeedback: "2 × 9 = 18, 5 × 9 = 45, 8 × 9 = 72, and 10 × 9 = 90!",
    wrong: [
      { pick: "o19", hint: "10 + 9 = 19, but that adds. The rule multiplies by 9. 2 × 9 = 18." },
      { pick: "o60", hint: "Check it: 6 × 9 = 54 and 7 × 9 = 63. No input makes 60." },
      { missing: true, hint: "There are 4 outputs that fit. Try inputs 2, 5, 8, and 10." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Add 4 or times 4?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Look at the table: 4, 8, 12, 16. The values go up by 4 each time. So the rule is add 4. Easy!"',
    nova: 'Nova: "The values do go up by 4. But the rule that turns the POSITION into the VALUE is multiply the position by 4. That one gets us to any spot fast."',
    data: table("Hall 9 · sensors at each spot", [[1, 4], [2, 8], [3, 12], [4, 16]]),
    question: "Whose rule tells the value right from the position? Pick the best reason, then tell Kai why.",
    hint: "Try Kai's add-4 rule on the position. Is 1 + 4 equal to 4? Now try 1 × 4.",
    meter: { heat: 5, label: "Line speed +5%", story: "The crew agrees on the rule" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Both see the pattern, but only multiply the position by 4 turns a position into its value, like 25 × 4 = 100." },
      { id: "B", text: "Kai. Adding 4 to the position gives the value." },
      { id: "C", text: "Kai. The only way to find position 25 is to keep adding 4 again and again." },
      { id: "D", text: "Nova, because multiplying always gives a bigger number than adding." },
    ],
    writtenPrompt: "Tell Kai in your own words why multiply by 4 is the rule for the position.",
    rightFeedback: "Nova is right. Adding 4 tells the next value. Multiplying the position by 4 tells any value.",
    debateHints: {
      wrongWho: "Test Kai's idea on position 2. 2 + 4 = 6, but the value is 8. What about 2 × 4?",
      wrongReason: "Right person, check the reason. Multiplying isn't always bigger: 1 × 4 is less than 1 + 4.",
      right: "Nova is right. The values go up by 4, but the rule that turns a position into a value is multiply by 4!",
    },
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The blackout table", machine: "Code Panel", icon: "quake", speaker: "vega",
    line: "Surprise! The lights in Hall 10 flickered and wiped part of the table. The next batch needs 12 spots filled. Let's rebuild the rule fast.",
    question: "Part 1: Which rule fits the table? Part 2: Which expression finds the value at position 12? Part 3: What is the value at position 12? Part 4: Which position has a value of 56?",
    data: table("Hall 10 · bolts at each spot", [[1, 8], [2, 16], [3, 24], [4, "?"], [12, "?"]]),
    parts: [
      { type: "choice", prompt: "Which rule turns each position into its value?", choices: [
        { id: "a", text: "Multiply the position by 8" },
        { id: "b", text: "Add 8 to the position" },
        { id: "c", text: "Add 7 to the position" },
        { id: "d", text: "Multiply the position by 2" },
      ] },
      { type: "choice", prompt: "Which expression finds the value at position 12?", choices: [
        { id: "a", text: "8 × 12" },
        { id: "b", text: "8 + 12" },
        { id: "c", text: "24 + 8" },
        { id: "d", text: "12 × 12" },
      ] },
      { type: "number", prompt: "What is the value at position 12?", unit: "bolts" },
      { type: "number", prompt: "The value is 56. What is the position?", unit: "position" },
    ],
    hint: "1 × 8 = 8, 2 × 8 = 16, 3 × 8 = 24. To go backward, ask: what times 8 makes 56?",
    meter: { heat: 10, label: "Line speed +10%", story: "Hall 10 is back online" },
    discovery: { id: "crickets", name: "Cricket thermometers", who: "Nova", fact: "Crickets chirp faster when it's warm and slower when it's cool. By counting their chirps, you can make a good guess of the temperature." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "choice", correct: "a" }, { kind: "number", value: 96 }, { kind: "number", value: 7 }] },
    rightFeedback: "The rule is multiply by 8. 8 × 12 = 96, and 7 × 8 = 56. Hall 10 is saved!",
    wrong: [
      { step: 1, choice: "b", hint: "Test position 2. 2 + 8 = 10, but the table shows 16." },
      { step: 1, choice: "c", hint: "That works for position 1, since 1 + 7 = 8. Test position 2: 2 + 7 = 9, not 16." },
      { step: 1, choice: "d", hint: "Test position 1. 1 × 2 = 2, but the table shows 8." },
      { step: 2, choice: "b", hint: "That adds 8. The rule multiplies the position by 8." },
      { step: 2, choice: "c", hint: "24 + 8 finds the next value, position 4. We need position 12." },
      { step: 2, choice: "d", hint: "Multiply the position by the rule's number, 8. Not by 12 again." },
      { step: 3, value: 20, hint: "That adds 8. Multiply: 8 × 12." },
      { step: 3, value: 88, hint: "That's 8 × 11. Check: 8 × 12 = 8 × 10 + 8 × 2." },
      { step: 4, value: 48, hint: "48 is 56 − 8. The rule multiplies, so go backward by dividing: 56 ÷ 8." },
      { step: 4, value: 8, hint: "8 × 8 = 64. Try one less." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Fix Kai's table", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai filled in the table for the rule add 5 to the position. He wrote: "Position 1 → 6. Position 2 → 11. Position 3 → 16." Something is off.',
    question: "Part 1: What went wrong? Part 2: What is the right value at position 3? Part 3: What is the right value at position 10?",
    data: table("Kai's table · rule: add 5 to the position", [[1, 6], [2, 11], [3, 16]]),
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He added 5 to the value before it, not to the position." },
        { id: "b", text: "He should have multiplied the position by 5." },
        { id: "c", text: "Position 1 should be 5, not 6." },
        { id: "d", text: "Nothing. His table is right." },
      ] },
      { type: "number", prompt: "Use the rule on the position. What is the value at position 3?", unit: "value" },
      { type: "number", prompt: "What is the value at position 10?", unit: "value" },
    ],
    hint: "The rule works on the position number. For position 2, do 2 + 5. Don't start from the last value.",
    meter: { supplies: 1, label: "Rules cracked +1", story: "Kai's table is fixed" },
    discovery: { id: "spiderweb", name: "Spider web patterns", who: "Kai", fact: "Orb-weaver spiders spin webs with straight spokes and a spiral that loops around and around in an even pattern." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 8 }, { kind: "number", value: 15 }] },
    rightFeedback: "Fixed! 1 + 5 = 6, 2 + 5 = 7, 3 + 5 = 8, and 10 + 5 = 15.",
    wrong: [
      { step: 1, choice: "b", hint: "The rule says add 5, so adding is right. Check WHAT Kai added 5 to." },
      { step: 1, choice: "c", hint: "1 + 5 = 6. Kai got position 1 right. Check position 2." },
      { step: 1, choice: "d", hint: "Test position 2 with the rule: 2 + 5 = 7. Kai wrote 11." },
      { step: 2, value: 16, hint: "That's Kai's answer. Add 5 to the position: 3 + 5." },
      { step: 2, value: 15, hint: "That multiplies by 5. The rule is add 5 to the position." },
      { step: 3, value: 51, hint: "That keeps adding 5 to each value, like Kai did. Use the position: 10 + 5." },
      { step: 3, value: 50, hint: "That multiplies by 5. The rule is add 5: 10 + 5." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The bolt count", machine: "Strip Scanner", icon: "cells", speaker: "kai",
    line: "The line needs 90 bolts in all. We have 3 full boxes with 24 bolts each. The rest are loose bolts, and nobody counted them.",
    question: "Part 1: Which equation matches the strip diagram? Part 2: How many loose bolts, b, are there?",
    data: {
      title: "Strip diagram · 90 bolts in all",
      columns: ["Box 1", "Box 2", "Box 3", "Loose"],
      rows: [["24", "24", "24", "b"]],
    },
    parts: [
      { type: "choice", prompt: "Which equation matches the strip diagram?", choices: [
        { id: "a", text: "3 × 24 + b = 90" },
        { id: "b", text: "3 + 24 + b = 90" },
        { id: "c", text: "3 × 24 = b + 24" },
        { id: "d", text: "90 + b = 3 × 24" },
      ] },
      { type: "number", prompt: "Solve it. What number does b stand for?", unit: "bolts" },
    ],
    hint: "First find how many bolts are in the 3 boxes: 3 × 24. Then ask: that number plus what makes 90?",
    meter: { heat: 5, label: "Line speed +5%", story: "Every bolt is counted" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 18 }] },
    rightFeedback: "3 × 24 = 72, and 72 + 18 = 90. There are 18 loose bolts, so b = 18!",
    wrong: [
      { step: 1, choice: "b", hint: "There are 3 boxes of 24, not just 24 and 3. Groups of the same size mean multiply." },
      { step: 1, choice: "c", hint: "The whole strip is 90. Which equation has the total, 90, by itself?" },
      { step: 1, choice: "d", hint: "90 is the total of all the parts. It shouldn't have b added to it." },
      { step: 2, value: 66, hint: "90 − 24 only takes away one box. There are 3 boxes: 3 × 24 = 72." },
      { step: 2, value: 162, hint: "The boxes plus b make 90, so b is less than 90. Subtract: 90 − 72." },
      { step: 2, value: 72, hint: "72 is the bolts in the boxes. How many more make 90?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Gears left over", machine: "Gear Bin", icon: "dial", speaker: "nova",
    line: "I opened 4 crates with 15 gears in each. Then the robots used 12 gears to fix the belt. I want to know how many gears are left, g.",
    question: "Part 1: Which equation shows the problem? Part 2: How many gears, g, are left?",
    data: {
      title: "Strip diagram · gears",
      columns: ["Crate 1", "Crate 2", "Crate 3", "Crate 4"],
      rows: [["15", "15", "15", "15"], ["Used: 12", "Left: g", "", ""]],
    },
    parts: [
      { type: "choice", prompt: "Which equation shows the problem?", choices: [
        { id: "a", text: "4 × 15 − 12 = g" },
        { id: "b", text: "4 + 15 − 12 = g" },
        { id: "c", text: "4 × 15 + 12 = g" },
        { id: "d", text: "15 − 12 × 4 = g" },
      ] },
      { type: "number", prompt: "Solve it. What number does g stand for?", unit: "gears" },
    ],
    hint: "Find all the gears first: 4 crates of 15. Then take away the 12 that were used.",
    meter: { supplies: 1, label: "Rules cracked +1", story: "The gear bin is counted" },
    discovery: { id: "sunflower", name: "Sunflower spirals", who: "Nova", fact: "The seeds in a sunflower head grow in spirals. One set of spirals curves one way, and another set curves the other way." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 48 }] },
    rightFeedback: "4 × 15 = 60, and 60 − 12 = 48. So g = 48 gears left!",
    wrong: [
      { step: 1, choice: "b", hint: "4 crates of 15 means 4 equal groups. Multiply, don't add." },
      { step: 1, choice: "c", hint: "The robots USED 12 gears. Should you add them or take them away?" },
      { step: 1, choice: "d", hint: "Find all the gears in the crates first: 4 × 15. Then take away 12." },
      { step: 2, value: 72, hint: "The 12 gears were used up. Take them away: 60 − 12." },
      { step: 2, value: 60, hint: "60 is all the gears. Don't forget the 12 that were used." },
      { step: 2, value: 7, hint: "4 + 15 − 12 = 7, but there are 4 crates of 15. Multiply first." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Race of the two lines", machine: "Speed Board", icon: "relay", speaker: "vega",
    line: "Two lines are racing to spot 10. Line A uses the rule add 4 to the position. Line B uses the rule multiply the position by 4.",
    question: "Part 1: What is Line A's value at position 10? Part 2: What is Line B's value at position 10? Part 3: What do you notice?",
    data: {
      title: "The race · values at each spot",
      columns: ["Position", "Line A (add 4)", "Line B (times 4)"],
      rows: [["1", "5", "4"], ["2", "6", "8"], ["3", "7", "12"], ["10", "?", "?"]],
    },
    parts: [
      { type: "number", prompt: "Line A: add 4 to the position. What is the value at position 10?", unit: "robots" },
      { type: "number", prompt: "Line B: multiply the position by 4. What is the value at position 10?", unit: "robots" },
      { type: "choice", prompt: "What do you notice about the two lines?", choices: [
        { id: "a", text: "Line A's values go up by 1 each spot. Line B's values go up by 4, so Line B pulls far ahead." },
        { id: "b", text: "Both lines give the same values, because both rules use 4." },
        { id: "c", text: "Line A is always ahead, because it starts with more." },
        { id: "d", text: "Line B goes up by 1 each spot." },
      ] },
    ],
    hint: "Use each rule on position 10. Then look down each column. How much does each one grow from spot to spot?",
    meter: { heat: 5, label: "Line speed +5%", story: "Line B wins the race" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 14 }, { kind: "number", value: 40 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "10 + 4 = 14 and 10 × 4 = 40. Adding grows by 1 each spot. Multiplying by 4 grows by 4 each spot!",
    wrong: [
      { step: 1, value: 40, hint: "That multiplies. Line A adds 4 to the position: 10 + 4." },
      { step: 1, value: 13, hint: "Use the rule on position 10: 10 + 4." },
      { step: 2, value: 14, hint: "That adds. Line B multiplies the position by 4: 10 × 4." },
      { step: 2, value: 44, hint: "Use position 10, not 11. 10 × 4 = 40." },
      { step: 3, choice: "b", hint: "Look at position 2: Line A has 6 and Line B has 8. They are not the same." },
      { step: 3, choice: "c", hint: "Line A is ahead only at position 1. Look at position 10." },
      { step: 3, choice: "d", hint: "Line B goes 4, 8, 12. How much does it go up each time?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The Master Machine", machine: "Master Machine", icon: "scan", speaker: "vega",
    line: "Surprise! The Master Machine switched on by itself. It runs every line in the city. It needs 200 robots by spot 20, or the whole city shuts down!",
    question: "Part 1: Which rule fits? Part 2: What is the value at position 5? Part 3: Which position has a value of 63? Part 4: Which expression finds the value at position 20? Part 5: Solve 7 × 20 + r = 200 to find how many more robots, r, the city needs.",
    data: table("Master Machine · robots at each spot", [[1, 7], [2, 14], [3, 21], [5, "?"], ["?", 63]]),
    parts: [
      { type: "choice", prompt: "Which rule turns each position into its value?", choices: [
        { id: "a", text: "Multiply the position by 7" },
        { id: "b", text: "Add 7 to the position" },
        { id: "c", text: "Add 6 to the position" },
        { id: "d", text: "Multiply the position by 3" },
      ] },
      { type: "number", prompt: "What is the value at position 5?", unit: "robots" },
      { type: "number", prompt: "The value is 63. What is the position?", unit: "position" },
      { type: "choice", prompt: "Which expression finds the value at position 20?", choices: [
        { id: "a", text: "7 × 20" },
        { id: "b", text: "7 + 20" },
        { id: "c", text: "20 × 20" },
        { id: "d", text: "21 + 7" },
      ] },
      { type: "number", prompt: "The line makes 7 × 20 robots. Solve 7 × 20 + r = 200. What is r?", unit: "robots" },
    ],
    hint: "1 × 7 = 7, 2 × 7 = 14. To go backward, ask: what times 7 makes 63? For r, find 7 × 20 first, then see how many more make 200.",
    meter: { heat: 10, label: "Line speed +10%", story: "The Master Machine keeps the city running" },
    discovery: { id: "zebra", name: "Zebra stripes", who: "Nova", fact: "Every zebra has its own stripe pattern. No two zebras have stripes that are exactly the same." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 35 }, { kind: "number", value: 9 }, { kind: "choice", correct: "a" }, { kind: "number", value: 60 }] },
    rightFeedback: "Multiply by 7! 5 × 7 = 35, 9 × 7 = 63, and 7 × 20 = 140. 140 + 60 = 200, so r = 60. You saved Mechara, specialist!",
    wrong: [
      { step: 1, choice: "b", hint: "Test position 2. 2 + 7 = 9, but the table shows 14." },
      { step: 1, choice: "c", hint: "That works for position 1, since 1 + 6 = 7. Test position 2: 2 + 6 = 8, not 14." },
      { step: 1, choice: "d", hint: "Test position 1. 1 × 3 = 3, but the table shows 7." },
      { step: 2, value: 28, hint: "28 comes after 21, but that's position 4. The table skips to position 5: 5 × 7." },
      { step: 2, value: 12, hint: "That adds 7. The rule multiplies: 5 × 7." },
      { step: 3, value: 56, hint: "63 − 7 = 56, but the rule multiplies. Go backward by dividing: 63 ÷ 7." },
      { step: 3, value: 70, hint: "70 is 63 + 7. What times 7 makes 63?" },
      { step: 4, choice: "b", hint: "That adds 7. The rule multiplies the position by 7." },
      { step: 4, choice: "c", hint: "Multiply the position by the rule's number, 7." },
      { step: 4, choice: "d", hint: "21 + 7 is position 4. We want position 20." },
      { step: 5, value: 340, hint: "7 × 20 + r = 200, so r is less than 200. Subtract: 200 − 140." },
      { step: 5, value: 173, hint: "Use 7 × 20 = 140, not 7 + 20. Then 200 − 140." },
      { step: 5, value: 140, hint: "140 is what the line makes. How many more robots make 200?" },
    ],
  },
};

export default {
  id: "MA.4.5B-XP",
  standard: "MA.4.5B-XP",
  engine: "expedition_station",
  title: "The Pattern Machine",
  planet: "Mechara",
  outpost: "Robot city · assembly lines",
  grade: 4,
  subject: "Math",
  teks: "4.5B",
  supportingTeks: ["4.5A"],
  skillsChip: "4.5B · Input-output tables and rules",
  iCan: "I can use a rule and an input-output table to make a number pattern, find the value at any position, and write equations with a letter for the unknown.",
  blurb: "The robot assembly lines of Mechara follow secret number rules. The crew needs help cracking each rule so the lines can build the right robots at every spot.",
  mission: "Crack the rules of the robot assembly lines and keep every machine building the right number of robots.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.5B · MECHARA ASSEMBLY LINES",
  playableActs: [1, 2, 3],
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Line speed", heatUnit: "%", supplies: "Rules cracked", suppliesUnit: "rules" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We've landed in the robot city on Mechara.",
    "Every assembly line here follows a number rule. The rule turns each spot's position into a value.",
    "The rules got scrambled, and the lines are slowing down. Help Kai and Nova crack them. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Start the belts", "Act 2 · Jump down the line", "Act 3 · The Master Machine"],
    completes: [
      "The belts are running and the first rules are cracked, {firstName}!",
      "You can jump to any spot on the line now, even after the blackout, {firstName}!",
      "The Master Machine is running, {firstName}! Every line in the robot city follows its rule again.",
    ],
    teasers: [
      "Next on Mechara: the belts get really long. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: the Master Machine that runs the whole city. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The belts in this part of the city are super long.",
      "Counting spot by spot would take forever. Let's use the rules to jump ahead.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Kai's tables need fixing, and the bolt counts are off.",
      "Then we'll face the Master Machine that runs every line in the city.",
    ],
  }),
  tasks,
};
