// Expedition Station — The Pollen Scoops (MA.4.3A-XP)
// Grade 4 · Math · Lumara. Main standard 4.3A (a fraction a/b as a sum of
// unit fractions 1/b, and other sums with the same denominator); also
// practices 4.3B (decompose a fraction in more than one way, with pictures,
// and record it with numbers).
// Denominators 2, 3, 4, 5, 6, 8, 10, 12. Most answers are no more than 1;
// the final challenge uses a small improper fraction (7/4 = 1 3/4).
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Count the pollen scoops", machine: "Fill", icon: "tank", speaker: "kai",
    line: "The glow bees are hungry! I'm mixing their pollen one scoop at a time. Each scoop is 1/5 of the jar. I poured 1/5 + 1/5 + 1/5.",
    question: "How full is the jar now? Set the gauge, then press Pour.",
    hint: "Each scoop is one fifth. Count the fifths: 1, 2, 3.",
    meter: { heat: 15, label: "Hive glow +15%", story: "The first glow bees buzz awake" },
    answer: { kind: "frac", n: 3, d: 5 },
    rightFeedback: "Yes! 1/5 + 1/5 + 1/5 = 3/5. Three fifths of the jar is full.",
    wrong: [
      { n: 3, d: 15, hint: "You added the bottom numbers too. Every scoop is still a fifth, so the bottom stays 5." },
      { n: 2, d: 5, hint: "Count every scoop. Kai poured three 1/5 scoops." },
    ],
    fill: { denom: 5, start: 0, pours: [{ n: 1, d: 5 }, { n: 1, d: 5 }, { n: 1, d: 5 }] },
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The one-way debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The bees need 3/4 of a jar. There is only ONE way to make 3/4: 1/4 + 1/4 + 1/4. That\'s the rule!"',
    nova: 'Nova: "That\'s one way, Kai. But 1/4 + 2/4 makes 3/4 too. Any fourths that add up to 3 fourths will work."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Picture 3 fourths of a jar. Could you pour it as one small scoop and one bigger scoop?",
    meter: { heat: 10, label: "Hive glow +10%", story: "The crew agrees on the pollen mix" },
    discovery: { id: "waggle", name: "The waggle dance", who: "Nova", fact: "Honey bees do a wiggly dance called the waggle dance. It tells other bees which way to fly to find flowers." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 1 fourth + 2 fourths is 3 fourths. You can break a fraction into a sum in more than one way." },
      { id: "B", text: "Nova, because 2 is a bigger number than 1." },
      { id: "C", text: "Kai. A fraction can only be broken into pieces like 1/4." },
      { id: "D", text: "Kai. You can't add fractions that have different top numbers." },
    ],
    writtenPrompt: "Tell Kai in your own words why 1/4 + 2/4 also makes 3/4.",
    debateHints: {
      wrongWho: "Count the fourths in 1/4 + 2/4. Is it 3 fourths?",
      wrongReason: "Right person, check the reason. What do 1 fourth and 2 fourths add up to?",
      right: "Nova is right — 3/4 = 1/4 + 1/4 + 1/4, and 3/4 = 1/4 + 2/4, too.",
    },
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Power the glow dial", machine: "Tune", icon: "dial", speaker: "kai",
    line: "The hive lamp runs on light power. The dial is marked in eighths. The lamp needs 1/8 + 1/8 + 1/8 + 1/8 + 1/8 of power.",
    question: "What fraction is that sum? Turn the dial, then press Lock signal.",
    hint: "Count the 1/8 pieces. Each one is one eighth.",
    meter: { heat: 10, label: "Hive glow +10%", story: "The hive lamp starts to glow" },
    discovery: { id: "sunlight", name: "Sunlight", who: "Kai", fact: "Light from the Sun takes about 8 minutes to travel all the way to Earth." },
    answer: { kind: "frac", n: 5, d: 8 },
    rightFeedback: "Locked! Five 1/8 pieces make 5/8.",
    wrong: [
      { n: 5, d: 40, hint: "You added the bottom numbers. Each piece is still an eighth, so the bottom stays 8." },
      { n: 4, d: 8, hint: "Count the pieces again. There are five 1/8 pieces." },
    ],
    tune: { denom: 8, mode: "point", start: { n: 0, d: 8 } },
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Top off the pollen jar", machine: "Fill", icon: "scoop", speaker: "nova",
    line: "This pollen jar already has 1/6 in it. The bees need it filled to 5/6. Our scoops hold 1/6 or 2/6.",
    question: "How much more pollen does the jar need? Then fill it with scoops two different ways.",
    missingPrompt: "How much more pollen gets the jar from 1/6 up to 5/6?",
    hint: "Count the sixths from 1/6 up to 5/6.",
    meter: { supplies: 2, label: "Honey jars +2", story: "The pollen jar is ready for the bees" },
    discovery: { id: "pollenbasket", name: "Pollen baskets", who: "Nova", fact: "Honey bees carry pollen home in little pockets of hair on their back legs called pollen baskets." },
    answer: { kind: "scoops", missing: { n: 4, d: 6 }, target: { n: 5, d: 6 }, start: { n: 1, d: 6 }, scoopSizes: [1, 2], waysNeeded: 2 },
    rightFeedback: "4/6 = 1/6 + 1/6 + 1/6 + 1/6, and 4/6 = 2/6 + 2/6. Two ways to the same amount!",
    wrong: [
      { n: 5, d: 6, hint: "5/6 is the line we need to reach. The jar already has 1/6. How much MORE?" },
      { n: 6, d: 6, hint: "You added 1/6 and 5/6. Count up from 1/6 to 5/6 instead." },
    ],
    fill: { denom: 6, start: 1, target: 5 },
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The pollen gust", machine: "Fill", icon: "snap", speaker: "vega",
    line: "Surprise, a gust of wind! It blew pollen out of the big jar. Now the jar is only 3/8 full. It has to be completely full, 8/8, before the bees wake up.",
    question: "Step 1: How much pollen do we need to add to fill the jar? Step 2: Kai adds two 2/8 scoops. How much more is still needed?",
    stepPrompts: ["Step 1: The jar is at 3/8. How much do we need to add to reach 8/8?", "Step 2: Kai adds two 2/8 scoops. How much more pollen is still needed?"],
    stepButtons: ["Check the gap", "Check the last scoop"],
    hint: "Count the eighths from 3/8 up to 8/8. Then take away Kai's two scoops.",
    meter: { heat: 10, label: "Hive glow +10%", story: "The jar is full again before the bees wake" },
    discovery: { id: "beeeyes", name: "Bee eyes", who: "Nova", fact: "Honey bees have five eyes: two big eyes on the sides of their heads and three tiny eyes on top." },
    answer: { kind: "steps", steps: [{ n: 5, d: 8 }, { n: 1, d: 8 }] },
    rightFeedback: "We needed 5/8, and 5/8 = 2/8 + 2/8 + 1/8. The jar is full!",
    wrong: [
      { step: 1, n: 3, d: 8, hint: "3/8 is what's left in the jar. How much do we ADD to get to 8/8?" },
      { step: 1, n: 11, d: 8, hint: "You added 3/8 and 8/8. Count up from 3/8 to 8/8 instead." },
      { step: 2, n: 4, d: 8, hint: "4/8 is what Kai's two scoops add up to. How much more is still needed after that?" },
      { step: 2, n: 3, d: 8, hint: "Kai used TWO 2/8 scoops. 2/8 + 2/8 = 4/8. How far is 4/8 from 5/8?" },
    ],
    fill: { denom: 8, start: 3, strip: false },
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Follow the glow bee", machine: "Travel", icon: "trail", speaker: "nova",
    line: "A glow bee is flying down the flower path to light it up. The path is marked in tenths. She flies 2/10, then 3/10, then 4/10.",
    question: "Where does the glow bee land? Mark the spot on the path.",
    hint: "Add the hops: 2 tenths + 3 tenths + 4 tenths.",
    meter: { heat: 5, label: "Hive glow +5%", story: "The flower path glows bright" },
    discovery: { id: "hummingbird", name: "Hummingbirds", who: "Kai", fact: "Hummingbirds help flowers too. Pollen sticks to their heads and beaks while they drink nectar." },
    answer: { kind: "frac", n: 9, d: 10 },
    rightFeedback: "2/10 + 3/10 + 4/10 = 9/10. She landed at 9/10 of the path!",
    wrong: [
      { n: 9, d: 30, hint: "You added the bottom numbers. The hops are all tenths, so the bottom stays 10." },
      { n: 7, d: 10, hint: "That's only two hops. Add all three: 2/10, 3/10, and 4/10." },
    ],
    travel: { denom: 10, max: 1, mode: "point", moves: [{ n: 2, d: 10 }, { n: 3, d: 10 }, { n: 4, d: 10 }], label: "of the flower path" },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Check Kai's nectar notes", machine: "Repair", icon: "log", speaker: "nova",
    line: "Kai wrote this in his notes: \"I mixed 2/5 cup of nectar and 2/5 cup more. That's 4/10 cup, because 2 + 2 = 4 and 5 + 5 = 10.\" Hmm, that's not right.",
    question: "Tap the part of Kai's note that is wrong. Pick what went wrong, then write the right amount.",
    hint: "The cups are measured in fifths. When you add fifths to fifths, what size are the pieces?",
    meter: { supplies: 1, label: "Honey jars +1", story: "The nectar notes are fixed" },
    answer: { kind: "mistake", tap: "frac", error: "A", fix: { n: 4, d: 5 } },
    rightFeedback: "Fixed! 2/5 + 2/5 = 4/5. The pieces stay fifths.",
    repair: {
      log: [
        { id: "start", text: "I mixed 2/5 cup of nectar and 2/5 cup more." },
        { id: "frac", text: "That's 4/10 cup," },
        { id: "why", text: "because 2 + 2 = 4 and 5 + 5 = 10." },
      ],
      errors: [
        { id: "A", text: "He added the bottom numbers. The pieces are still fifths, so only the top numbers get added." },
        { id: "B", text: "You can't add 2/5 and 2/5." },
        { id: "C", text: "He should have written 2/10." },
      ],
    },
    wrong: [
      { error: "B", hint: "You can add them. Picture 2 fifths of a cup and 2 more fifths." },
      { error: "C", hint: "2/10 is even less nectar. Look at what Kai did to the bottom numbers." },
      { n: 4, d: 10, hint: "That's Kai's answer. 4/10 is less than half a cup. Is 2/5 + 2/5 less than half?" },
      { n: 5, d: 5, hint: "5/5 is a full cup. Count the fifths again: 2 fifths + 2 fifths." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Plant the flower bed", machine: "Fill", icon: "grid", speaker: "kai",
    line: "The glow flower bed has 12 equal squares. I planted sunpetals in 3/12, moonbells in 4/12, and starblooms in 2/12.",
    question: "What fraction of the bed is planted? Shade the grid, then press Check.",
    hint: "Each square is 1/12. Add the squares: 3 + 4 + 2.",
    meter: { heat: 5, label: "Hive glow +5%", story: "New flowers open for the bees" },
    discovery: { id: "nightflowers", name: "Night flowers", who: "Nova", fact: "Some flowers open only at night. Moths and bats visit them and carry their pollen." },
    answer: { kind: "frac", n: 9, d: 12 },
    rightFeedback: "3/12 + 4/12 + 2/12 = 9/12. Nine of the 12 squares are planted!",
    wrong: [
      { n: 9, d: 36, hint: "You added the bottom numbers. Every square is still 1/12, so the bottom stays 12." },
      { n: 7, d: 12, hint: "That's only the sunpetals and moonbells. Add the starblooms too." },
    ],
    fill: { denom: 12, grid: { rows: 3, cols: 4 }, start: 0, shade: true, pours: [{ n: 3, d: 12 }, { n: 4, d: 12 }, { n: 2, d: 12 }] },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The two-pollen jar", machine: "Numberless", icon: "water", speaker: "nova",
    line: "Kai and I mixed two kinds of pollen into one jar for the glow bees. Some is blue pollen and some is gold pollen. The jar is not full.",
    question: "First, pick the questions we could answer with this story. Then the numbers will show up.",
    hint: "Both amounts are in tenths. Add the tenths together.",
    meter: { supplies: 1, label: "Honey jars +1", story: "The two-pollen mix goes to the hive" },
    answer: { kind: "numberless", sensible: ["total", "more"], missing: { n: 8, d: 10 } },
    rightFeedback: "3/10 + 5/10 = 8/10. The jar has 8/10 pollen in all.",
    numberless: {
      questions: [
        { id: "total", text: "How much pollen is in the jar in all?" },
        { id: "more", text: "Is there more blue pollen or more gold pollen?" },
        { id: "bees", text: "How many bees live in the hive?" },
        { id: "smell", text: "What does the pollen smell like?" },
      ],
      reveal: "The jar has 3/10 blue pollen and 5/10 gold pollen.",
      ask: "How much pollen is in the jar in all?",
      denom: 10,
    },
    wrong: [
      { step: "questions", hint: "Can the story tell us that? Pick only questions about how much pollen is in the jar." },
      { n: 8, d: 20, hint: "You added the bottom numbers. Both amounts are tenths, so the bottom stays 10." },
      { n: 2, d: 10, hint: "2/10 is how much MORE gold there is. The question asks how much in all." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The dimming lamps", machine: "Tune", icon: "quake", speaker: "vega",
    line: "Surprise, the garden lamps are dimming! Three lamps each need 5/6 power. Each lamp already has some power cells in it. The dials are marked in sixths.",
    question: "Step 1: Lamp A has a 2/6 cell. How much more power does it need? Step 2: Lamp B has three 1/6 cells. How much more does it need? Step 3: Lamp C has a 3/6 cell and a 1/6 cell. How much more does it need?",
    stepPrompts: [
      "Step 1: Lamp A has a 2/6 cell. 5/6 = 2/6 + ? How much more does it need?",
      "Step 2: Lamp B has 1/6 + 1/6 + 1/6. 5/6 = 1/6 + 1/6 + 1/6 + ? How much more?",
      "Step 3: Lamp C has 3/6 + 1/6. 5/6 = 3/6 + 1/6 + ? How much more?",
    ],
    stepButtons: ["Power Lamp A", "Power Lamp B", "Power Lamp C"],
    hint: "For each lamp, add up the cells it has. Then count up to 5/6.",
    meter: { heat: 5, label: "Hive glow +5%", story: "All three lamps shine again" },
    discovery: { id: "rainbow", name: "White light", who: "Nova", fact: "White sunlight is really all the colors of the rainbow mixed together." },
    answer: { kind: "steps", steps: [{ n: 3, d: 6 }, { n: 2, d: 6 }, { n: 1, d: 6 }] },
    rightFeedback: "5/6 = 2/6 + 3/6 = 1/6 + 1/6 + 1/6 + 2/6 = 3/6 + 1/6 + 1/6. Three ways to make 5/6, and every lamp shines!",
    wrong: [
      { step: 1, n: 7, d: 6, hint: "You added 2/6 and 5/6. Count up from 2/6 to 5/6 instead." },
      { step: 1, n: 2, d: 6, hint: "2/6 + 2/6 is only 4/6. Count up from 2/6 to 5/6." },
      { step: 2, n: 3, d: 6, hint: "3/6 is what Lamp B already has. How much MORE does it need?" },
      { step: 2, n: 1, d: 6, hint: "Three 1/6 cells make 3/6, not 4/6. Count up from 3/6 to 5/6." },
      { step: 3, n: 4, d: 6, hint: "4/6 is what Lamp C already has. How much MORE does it need?" },
      { step: 3, n: 2, d: 6, hint: "Add both cells first: 3/6 + 1/6 = 4/6. How far is 4/6 from 5/6?" },
    ],
    tune: { denom: 6, mode: "point", start: { n: 0, d: 6 } },
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Sort the pollen sums", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "Each honey card shows a pollen recipe. Sort each card into the bin with the amount it adds up to.",
    question: "Sort each card into the right bin.",
    hint: "The bottom numbers match in each card, so just add the top numbers.",
    meter: { supplies: 1, label: "Honey jars +1", story: "The honey cards are sorted for the festival" },
    discovery: { id: "honeycomb", name: "Honeycomb", who: "Nova", fact: "Bees build honeycomb out of wax. Each little room is a six-sided shape called a hexagon." },
    answer: { kind: "sort", bins: { p1: "threefourths", p2: "fiveeighths", p3: "fiveeighths", p4: "whole", p5: "threefourths", p6: "none" } },
    rightFeedback: "Every honey card is in the right bin!",
    sort: {
      bins: [
        { id: "threefourths", label: "Adds up to 3/4" },
        { id: "fiveeighths", label: "Adds up to 5/8" },
        { id: "whole", label: "Adds up to 1 whole" },
        { id: "none", label: "None of these" },
      ],
      items: [
        { id: "p1", label: "1/4 + 1/4 + 1/4" },
        { id: "p2", label: "2/8 + 3/8" },
        { id: "p3", label: "1/8 + 1/8 + 3/8" },
        { id: "p4", label: "2/4 + 2/4" },
        { id: "p5", label: "1/4 + 2/4" },
        { id: "p6", label: "2/8 + 2/8" },
      ],
    },
    wrong: [
      { item: "p6", hint: "2/8 + 2/8 is 4/8. Is that 3/4, 5/8, or 1 whole?" },
      { item: "p3", hint: "Count the eighths: 1 + 1 + 3." },
      { item: "p4", hint: "2 fourths + 2 fourths is 4 fourths. How many fourths make 1 whole?" },
      { item: "p5", hint: "1 fourth + 2 fourths is how many fourths?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The twelfths debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "For the festival honey, I\'ll mix 2/12 and 5/12. That makes 7/24. You add the tops and you add the bottoms!"',
    nova: 'Nova: "The pieces are twelfths, Kai. Adding more twelfths doesn\'t change their size. 2/12 + 5/12 = 7/12."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Picture 2 twelfth-pieces and 5 more twelfth-pieces. What size are the pieces now?",
    meter: { heat: 5, label: "Hive glow +5%", story: "The festival honey is mixed just right" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 2 twelfths + 5 twelfths is 7 twelfths. The size of the pieces stays the same, so the bottom number stays 12." },
      { id: "B", text: "Nova, because 12 is a bigger number than 7." },
      { id: "C", text: "Kai. When you add fractions, you always add the tops and the bottoms." },
      { id: "D", text: "Kai. 7/24 has bigger numbers, so it's more honey." },
    ],
    writtenPrompt: "Tell Kai in your own words why 2/12 + 5/12 is 7/12.",
    debateHints: {
      wrongWho: "7/24 is less than 1/3 of the jar. Could adding 5/12 to 2/12 give you less than 5/12?",
      wrongReason: "Right person, check the reason. What happens to the size of the pieces when you add twelfths?",
      right: "Nova is right — 2 twelfths + 5 twelfths = 7 twelfths.",
    },
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Warm the hive", machine: "Tune", icon: "dial", speaker: "nova",
    line: "The hive heater dial is marked in tenths. For the festival, it must be set to 1/10 + 1/10 + 2/10 + 3/10.",
    question: "What spot on the dial is that sum? Set the dial, then press Lock signal.",
    hint: "Add the sizes of the pieces, not how many pieces there are: 1 + 1 + 2 + 3 tenths.",
    meter: { heat: 10, label: "Hive glow +10%", story: "The hive is warm and cozy" },
    discovery: { id: "greenleaves", name: "Green leaves", who: "Kai", fact: "Most leaves look green because they bounce green light back to our eyes." },
    answer: { kind: "frac", n: 7, d: 10 },
    rightFeedback: "1/10 + 1/10 + 2/10 + 3/10 = 7/10. The hive is warm!",
    wrong: [
      { n: 7, d: 40, hint: "You added the bottom numbers. Every piece is tenths, so the bottom stays 10." },
      { n: 4, d: 10, hint: "There are 4 pieces, but they are different sizes. Add the sizes: 1 + 1 + 2 + 3 tenths." },
    ],
    tune: { denom: 10, mode: "point", start: { n: 0, d: 10 } },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Mix the festival honey", machine: "Fill", icon: "battery", speaker: "kai",
    line: "The festival honey pot is marked in twelfths. It already has 3/12. It needs to reach 10/12. Our honey scoops hold 1/12, 2/12, or 3/12.",
    question: "How much more honey does the pot need? Then fill it with scoops two different ways.",
    missingPrompt: "How much more honey gets the pot from 3/12 up to 10/12?",
    hint: "Count the twelfths from 3/12 up to 10/12.",
    meter: { supplies: 2, label: "Honey jars +2", story: "The festival honey pot is full" },
    answer: { kind: "scoops", missing: { n: 7, d: 12 }, target: { n: 10, d: 12 }, start: { n: 3, d: 12 }, scoopSizes: [1, 2, 3], waysNeeded: 2 },
    rightFeedback: "Two different ways to make 7/12, like 3/12 + 3/12 + 1/12 and 2/12 + 2/12 + 3/12!",
    wrong: [
      { n: 10, d: 12, hint: "10/12 is the line we need to reach. The pot already has 3/12. How much MORE?" },
      { n: 13, d: 12, hint: "You added 3/12 and 10/12. Count up from 3/12 to 10/12 instead." },
    ],
    fill: { denom: 12, start: 3, target: 10 },
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The queen's flower", machine: "Travel", icon: "relay", speaker: "vega",
    line: "This is it! The queen bee is waiting at the festival flower. It sits at 7/4 on the path, which is 1 3/4. The path goes from 0 to 2 and is marked in fourths. Two glow bees fly there in hops.",
    question: "Step 1: Bee A hops 3/4, then 3/4. Where does she land? Step 2: How much farther must Bee A fly to reach 7/4? Step 3: Bee B hops 2/4, then 2/4. How much farther must she fly to reach 7/4?",
    stepPrompts: [
      "Step 1: Bee A hops 3/4, then 3/4. Where does she land?",
      "Step 2: How much farther must Bee A fly to reach the flower at 7/4?",
      "Step 3: Bee B hops 2/4, then 2/4. How much farther must she fly to reach 7/4?",
    ],
    stepButtons: ["Check Bee A", "Check Bee A's last hop", "Check Bee B"],
    hint: "Add each bee's hops in fourths. Then count the fourths up to 7/4.",
    meter: { heat: 10, label: "Hive glow +10%", story: "Both bees reach the queen, and the festival begins" },
    discovery: { id: "honey", name: "Honey", who: "Nova", fact: "One honey bee makes only about 1/12 of a teaspoon of honey in its whole life. It takes a lot of bees to fill a jar!" },
    answer: { kind: "steps", steps: [{ n: 6, d: 4 }, { n: 1, d: 4 }, { n: 3, d: 4 }] },
    rightFeedback: "7/4 = 3/4 + 3/4 + 1/4, and 7/4 = 2/4 + 2/4 + 3/4. Two ways to reach the queen's flower!",
    wrong: [
      { step: 1, n: 6, d: 8, hint: "You added the bottom numbers. The hops are fourths, so the bottom stays 4." },
      { step: 1, n: 7, d: 4, hint: "7/4 is the flower. Where does Bee A land after her two hops?" },
      { step: 2, n: 7, d: 4, hint: "7/4 is where the flower is. How much FARTHER does Bee A fly from 6/4?" },
      { step: 2, n: 2, d: 4, hint: "Count the jumps from 6/4 to 7/4 on the path." },
      { step: 3, n: 4, d: 4, hint: "4/4 is how far Bee B has flown. How much farther to 7/4?" },
      { step: 3, n: 1, d: 4, hint: "Bee B's hops make 2/4 + 2/4 = 4/4, not 6/4. Count up from 4/4 to 7/4." },
    ],
    travel: { denom: 4, max: 2, mode: "point", marks: [{ n: 7, d: 4, label: "Flower" }], label: "of the festival path" },
  },
};

export default {
  id: "MA.4.3A-XP",
  standard: "MA.4.3A-XP",
  engine: "expedition_station",
  title: "The Pollen Scoops",
  planet: "Lumara",
  outpost: "Glow Hive · pollen kitchen",
  grade: 4,
  subject: "Math",
  teks: "4.3A",
  supportingTeks: ["4.3B"],
  skillsChip: "4.3A · Fractions as sums",
  iCan: "I can break a fraction into a sum of smaller fractions with the same bottom number, like 5/8 = 1/8 + 1/8 + 3/8. I can show the same fraction as a sum in more than one way.",
  blurb: "On Lumara, the glow bees light up the garden at night, but only if they eat the right pollen mix. The crew has to mix it one scoop at a time.",
  mission: "Mix pollen for the glow bees, one scoop at a time, and get the hive ready for the queen's festival.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.31 · LUMARA GLOW HIVE",
  playableActs: [1, 2, 3],
  meterStart: { heat: 35, supplies: 0, journal: 0 },
  meterLabels: { heat: "Hive glow", heatUnit: "%", supplies: "Honey jars", suppliesUnit: "jars" },
  journalMax: 10,
  opening: [
    "Specialist {name}, this is Commander Vega. The glow bees of Lumara are getting dim.",
    "They light up the garden at night, but only when they eat the right pollen mix. Every mix is made one scoop at a time.",
    "Help Kai and Nova add up the scoops so the hive glows again. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Mix the morning pollen", "Act 2 · Light the flower paths", "Act 3 · The queen's festival"],
    completes: [
      "The glow bees are awake and buzzing, {firstName}!",
      "The flower paths and lamps are shining, {firstName}!",
      "The queen bee's festival has begun, {firstName}! Lumara glows again.",
    ],
    teasers: [
      "Next on Lumara: the flower paths are going dark. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: the queen bee's festival is almost here. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The glow bees need to light the flower paths, and Kai's nectar notes have a mix-up.",
      "Let's add up every scoop and every hop.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The queen bee's festival is tonight.",
      "Help the crew sort the honey, warm the hive, and guide the bees to the queen's flower.",
    ],
  }),
  tasks,
};
