// Expedition Station — The Power Grid (SCI.4.8C-XP)
// Grade 4 · Science · Mechara (robot city). Main standard 4.8C (demonstrate and
// explain that electrical energy moves in a closed path that can produce light
// and thermal energy); also practices 4.8B (differentiate between conductors
// and insulators of thermal and electrical energy), 4.1B (plan and conduct
// simple investigations), 4.1G (develop and use models), 4.2B (analyze data
// for patterns), 4.3A (explanations supported by data), 4.3C (respectful
// scientific discussion), 4.5B (cause and effect), 4.5D (energy transfer and
// transformation in systems).
//
// Earth-true rule: Mechara and the outpost are invented, but every circuit,
// material, fact, and data table works the way it does on Earth.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "The parts bin", machine: "Parts Bin", icon: "cells", speaker: "kai",
    line: "Our wire crate spilled all over the workshop floor. Before we wire anything, let's sort what lets electricity flow and what blocks it.",
    question: "Sort each item: is it a conductor or an insulator of electricity?",
    hint: "Metals let electricity flow easily. Plastic, rubber, wood, and glass block it.",
    meter: { heat: 10, label: "Grid charge +10%", story: "The parts bin is sorted" },
    answer: { kind: "sort", bins: { p1: "cond", p2: "cond", p3: "cond", p4: "ins", p5: "ins", p6: "ins", p7: "ins" } },
    rightFeedback: "Copper, aluminum, and steel are metals, so they conduct. Rubber, plastic, wood, and glass are insulators.",
    sort: {
      bins: [{ id: "cond", label: "Conductor" }, { id: "ins", label: "Insulator" }],
      items: [
        { id: "p1", label: "Copper wire" },
        { id: "p2", label: "Aluminum foil" },
        { id: "p3", label: "Steel paper clip" },
        { id: "p4", label: "Rubber band" },
        { id: "p5", label: "Plastic straw" },
        { id: "p6", label: "Wooden craft stick" },
        { id: "p7", label: "Glass marble" },
      ],
    },
    wrong: [
      { item: "p2", hint: "Aluminum foil is thin, but it is still a metal. Do metals let electricity flow?" },
      { item: "p3", hint: "The paper clip is made of steel. Steel is a metal." },
      { item: "p7", hint: "Glass is hard and shiny, but it is not a metal. Electricity can't flow through it easily." },
      { item: "p6", hint: "Wood is not a metal. It blocks electricity." },
      { item: "p1", hint: "Copper is a metal. Most wires are made of it because electricity flows through it easily." },
      { item: "p4", hint: "Rubber is stretchy and soft. It blocks electricity." },
      { item: "p5", hint: "Plastic is not a metal. It blocks electricity." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "What makes a circuit?", machine: "Circuit Bench", icon: "battery", speaker: "nova",
    line: "The outpost's hallway lamp is dark. To light it, we need to build a circuit. Let's make sure we have every part.",
    question: "What does a circuit need to light a bulb?",
    hint: "Energy has to come from somewhere, travel along a path, and reach the bulb. Then it has to get back.",
    meter: { heat: 10, label: "Grid charge +10%", story: "The circuit parts are ready" },
    discovery: { id: "switch", name: "Light switches", who: "Nova", fact: "A light switch opens or closes a gap in a circuit. Flip it on, and the loop closes so electrical energy can flow to the light." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "An energy source like a battery, wires, and a bulb, all connected in a complete loop." },
      { id: "b", text: "Just a bulb. Bulbs make their own light." },
      { id: "c", text: "A battery and a bulb sitting side by side on the table, not touching." },
      { id: "d", text: "A wire and a bulb. Wires hold electricity inside them." },
    ],
    rightFeedback: "A circuit needs an energy source, wires, and a device like a bulb, joined in a closed loop.",
    wrong: [
      { choice: "b", hint: "A bulb with nothing hooked to it stays dark. Where does the energy come from?" },
      { choice: "c", hint: "The parts are there, but nothing connects them. Electrical energy needs a path to travel on." },
      { choice: "d", hint: "A wire is only a path. It doesn't store energy. What energy source is missing?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Follow the flow", machine: "Circuit Bench", icon: "trail", speaker: "kai",
    line: "I wrote down how energy moves around our hallway lamp circuit, but my notes got shuffled.",
    question: "Put the steps in order. Start at the battery.",
    hint: "The energy leaves the battery, travels to the bulb, and then has to get back to the battery.",
    meter: { supplies: 1, label: "Circuit badges +1", story: "The energy path is on the board" },
    answer: { kind: "order", correct: ["store", "out", "bulb", "back"] },
    items: [
      { id: "bulb", text: "The energy reaches the bulb, and the bulb gives off light and heat." },
      { id: "back", text: "The path goes through the second wire back to the other end of the battery." },
      { id: "store", text: "The battery holds stored energy." },
      { id: "out", text: "Electrical energy flows out of one end of the battery into the first wire." },
    ],
    rightFeedback: "Battery, first wire, bulb, second wire, and back to the battery. That's a closed loop!",
    wrong: [
      { position: 0, hint: "Start with where the energy comes from before anything moves." },
      { position: 1, hint: "The energy has to travel through a wire before it can reach the bulb." },
      { position: 2, hint: "The bulb lights up before the path goes back to the battery." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The bulb test", machine: "Test Bench", icon: "scan", speaker: "nova",
    line: "I left a gap in a working circuit. Then I put one item at a time across the gap to see if the bulb would light.",
    question: "What do all the items that lit the bulb have in common?",
    data: {
      title: "Nova's gap test",
      columns: ["Item across the gap", "Made of", "Did the bulb light?"],
      rows: [
        ["Key", "Brass (a metal)", "Yes"],
        ["Spoon", "Steel", "Yes"],
        ["Eraser", "Rubber", "No"],
        ["Ruler", "Plastic", "No"],
        ["Coin", "Copper and nickel (metals)", "Yes"],
        ["Pencil box", "Wood", "No"],
      ],
    },
    hint: "Look at the Made of column for every row that says Yes.",
    meter: { supplies: 1, label: "Circuit badges +1", story: "The test results are logged" },
    discovery: { id: "gold", name: "Gold in electronics", who: "Kai", fact: "Tiny bits of gold are used on the connectors inside computers and phones. Gold conducts electricity well and never rusts." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "They are all made of metal." },
      { id: "b", text: "They are all small." },
      { id: "c", text: "They are all things you use at school." },
      { id: "d", text: "They are all soft." },
    ],
    rightFeedback: "The key, spoon, and coin are all metal. Metals are conductors, so they closed the gap.",
    wrong: [
      { choice: "b", hint: "The eraser is small too, and it did not light the bulb. Check the Made of column." },
      { choice: "c", hint: "The ruler and eraser are school things, and they did not light the bulb. Check the Made of column." },
      { choice: "d", hint: "A key and a spoon are hard, not soft. Check the Made of column." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Lights out in the hallway", machine: "Circuit Bench", icon: "quake", speaker: "vega",
    line: "Surprise! A repair robot rolled through the hallway and knocked our lamp circuit apart. Kai rebuilt it four different ways. Only one way will work.",
    question: "Part 1: Which circuit will light the bulb? Part 2: Sort each circuit: is the loop open or closed? Part 3: What kinds of energy does the lit bulb give off?",
    parts: [
      { type: "choice", prompt: "Which circuit will light the bulb?", choices: [
        { id: "a", text: "Circuit A: One wire goes from the top of the battery to the bulb. A second wire goes from the bulb to the bottom of the battery." },
        { id: "b", text: "Circuit B: One wire goes from the top of the battery to the bulb. There is no second wire." },
        { id: "c", text: "Circuit C: Two wires go from the bulb to the top of the battery. Nothing touches the bottom of the battery." },
        { id: "d", text: "Circuit D: Two wires go from the battery to the bulb, but a plastic straw sits in the middle of one wire." },
      ] },
      { type: "sort", prompt: "Sort each circuit: is the loop open or closed?", bins: [
        { id: "closed", label: "Closed loop" },
        { id: "open", label: "Open loop" },
      ], items: [
        { id: "ca", label: "Circuit A" },
        { id: "cb", label: "Circuit B" },
        { id: "cc", label: "Circuit C" },
        { id: "cd", label: "Circuit D" },
      ] },
      { type: "choice", prompt: "Circuit A's bulb glows. What kinds of energy does the bulb give off?", choices: [
        { id: "a", text: "Light energy and thermal energy (heat)" },
        { id: "b", text: "Only sound energy" },
        { id: "c", text: "No energy. It just looks bright." },
        { id: "d", text: "New batteries" },
      ] },
    ],
    hint: "Trace each path with your finger. Can you go from one end of the battery, through the bulb, and back to the other end using only metal?",
    meter: { heat: 10, label: "Grid charge +10%", story: "The hallway lamp glows again" },
    discovery: { id: "filament", name: "Glowing wire", who: "Nova", fact: "Old-style light bulbs have a very thin wire inside called a filament. Electrical energy makes it so hot that it glows and gives off light." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "sort", bins: { ca: "closed", cb: "open", cc: "open", cd: "open" } },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Only Circuit A makes a complete loop, and its bulb turns electrical energy into light and heat!",
    wrong: [
      { step: 1, choice: "b", hint: "Energy can get to the bulb, but how does it get back to the battery?" },
      { step: 1, choice: "c", hint: "Both wires go to the same end of the battery. The loop has to connect both ends." },
      { step: 1, choice: "d", hint: "A plastic straw is an insulator. It makes a gap in the loop." },
      { step: 2, item: "cb", hint: "Circuit B has only one wire. There is no path back to the battery." },
      { step: 2, item: "cc", hint: "Circuit C never reaches the bottom of the battery, so the loop isn't complete." },
      { step: 2, item: "cd", hint: "Plastic blocks electricity. The straw breaks the loop." },
      { step: 2, item: "ca", hint: "Trace Circuit A: battery top, wire, bulb, wire, battery bottom. Is the path complete?" },
      { step: 3, choice: "b", hint: "A bulb doesn't make noise when it glows. What can you see, and what can you feel if you hold your hand near it?" },
      { step: 3, choice: "c", hint: "Being bright means the bulb is giving off light energy. Is it warm too?" },
      { step: 3, choice: "d", hint: "A bulb can't make batteries. What can you see and feel from a glowing bulb?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "One wire or two?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Why use two wires for the heater? One wire from the battery should be enough. The energy just goes to the heater and stops."',
    nova: 'Nova: "One wire isn\'t enough. The energy needs a second wire to get back to the battery and close the loop."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about Circuit B in the hallway. It had only one wire.",
    meter: { heat: 5, label: "Grid charge +5%", story: "Kai grabs a second wire" },
    discovery: { id: "birds", name: "Birds on power lines", who: "Nova", fact: "A bird can sit on one power line safely because it isn't part of a complete loop. The electricity stays in the wire and doesn't flow through the bird." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Electrical energy only moves in a closed path. With one wire, there is no way back to the battery, so nothing flows." },
      { id: "B", text: "Nova, because two wires look neater." },
      { id: "C", text: "Kai. The energy only needs to reach the heater." },
      { id: "D", text: "Kai. A second wire would take the energy away from the heater." },
    ],
    writtenPrompt: "Tell Kai in your own words why the heater needs two wires.",
    debateHints: {
      wrongWho: "Remember Circuit B. It had one wire from the battery to the bulb. Did the bulb light?",
      wrongReason: "Right person, check the reason. What does electrical energy need to move?",
      right: "Nova is right — electricity needs a complete loop, out and back.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Heat makers", machine: "Heater Hut", icon: "dial", speaker: "vega",
    line: "Nights on Mechara get cold. We need machines that turn electrical energy into thermal energy to keep the crew warm.",
    question: "Pick every device whose main job is to turn electrical energy into thermal energy (heat).",
    items: [
      { id: "heater", text: "Space heater" },
      { id: "toaster", text: "Toaster" },
      { id: "blanket", text: "Electric blanket" },
      { id: "stove", text: "Electric stove burner" },
      { id: "fan", text: "Ceiling fan" },
      { id: "bell", text: "Doorbell" },
    ],
    hint: "Which ones do you use to warm something up?",
    meter: { supplies: 1, label: "Circuit badges +1", story: "The heater list is ready" },
    answer: { kind: "multi", correct: ["heater", "toaster", "blanket", "stove"] },
    rightFeedback: "Heaters, toasters, electric blankets, and stove burners all turn electrical energy into heat.",
    wrong: [
      { pick: "fan", hint: "A ceiling fan's job is to spin and move air. It turns electrical energy into motion." },
      { pick: "bell", hint: "A doorbell's job is to ring. It turns electrical energy into sound." },
      { missing: true, hint: "There are four heat makers. Think about what warms a room, a bed, bread, and a pot of soup." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Why the coat?", machine: "Wire Spool", icon: "shield", speaker: "kai",
    line: "Every wire on this spool has copper inside and a plastic coat on the outside. Why not just use bare copper?",
    question: "Why are wires covered in plastic?",
    hint: "Copper is a conductor. Plastic is an insulator. What does an insulator do?",
    meter: { heat: 5, label: "Grid charge +5%", story: "The heater wires are coated" },
    discovery: { id: "polelinks", name: "Glass on power poles", who: "Kai", fact: "Power poles use glass or ceramic pieces to hold up the wires. These insulators keep electricity from flowing into the pole." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Plastic is an insulator. It keeps the electrical energy in the copper path and keeps it from flowing into people or other wires." },
      { id: "b", text: "Plastic helps electricity flow faster." },
      { id: "c", text: "Plastic makes the wire a conductor." },
      { id: "d", text: "The plastic is only there to add color." },
    ],
    rightFeedback: "The copper carries the energy, and the plastic insulator keeps it on the right path and keeps us safe.",
    wrong: [
      { choice: "b", hint: "Plastic blocks electricity. Would it help electricity flow?" },
      { choice: "c", hint: "The copper inside is already the conductor. Plastic is an insulator. What does it do?" },
      { choice: "d", hint: "Colors can help people tell wires apart, but that's not the main reason. What does plastic do to electricity?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Handle with care", machine: "Heater Hut", icon: "cells", speaker: "nova",
    line: "The heater hut has a hot plate for soup. Some tools will let heat move right into your hand. Others will keep your hand cool.",
    question: "Sort each item: is it a thermal conductor or a thermal insulator?",
    hint: "Metals let heat move through them easily. Wood, plastic, cloth, and foam slow heat down.",
    meter: { supplies: 1, label: "Circuit badges +1", story: "The soup tools are sorted" },
    discovery: { id: "handles", name: "Pot handles", who: "Nova", fact: "Many metal pots have handles made of wood or plastic. The metal pot conducts heat to the food, and the handle insulates your hand." },
    answer: { kind: "sort", bins: { t1: "cond", t2: "cond", t3: "cond", t4: "ins", t5: "ins", t6: "ins" } },
    rightFeedback: "The metal spoon, pot, and foil conduct heat. Wood, cloth, and foam are thermal insulators.",
    sort: {
      bins: [{ id: "cond", label: "Thermal conductor" }, { id: "ins", label: "Thermal insulator" }],
      items: [
        { id: "t1", label: "Metal spoon" },
        { id: "t2", label: "Copper-bottom pot" },
        { id: "t3", label: "Aluminum foil" },
        { id: "t4", label: "Wooden spoon" },
        { id: "t5", label: "Cloth oven mitt" },
        { id: "t6", label: "Foam cup" },
      ],
    },
    wrong: [
      { item: "t3", hint: "Foil is thin, but it is metal. Metal lets heat move through quickly." },
      { item: "t5", hint: "People wear oven mitts to hold hot pans. Does the mitt let heat through, or slow it down?" },
      { item: "t6", hint: "A foam cup keeps hot cocoa from burning your hand. It slows heat down." },
      { item: "t1", hint: "A metal spoon left in hot soup gets hot all the way up. Metal conducts heat." },
      { item: "t2", hint: "Copper is a metal. Pots use it so heat moves quickly into the food." },
      { item: "t4", hint: "A wooden spoon stays cool in hot soup. Wood slows heat down." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The cold heater", machine: "Heater Hut", icon: "quake", speaker: "vega",
    line: "Surprise! The heater hut is freezing, and the crew is shivering. Nova tested the heater circuit. It has a switch, a small light that shows when it's on, and a heating coil.",
    question: "Part 1: How many degrees did the coil warm up in Test 2? Part 2: Why did the coil stay cold in Test 1? Part 3: Why did the coil stay cold in Test 3? Part 4: Pick every kind of energy the circuit made in Test 2.",
    data: {
      title: "Heater circuit tests (5 minutes each)",
      columns: ["Test", "Switch", "Wires", "Did the light glow?", "Coil temperature after 5 minutes"],
      rows: [
        ["1", "Open (off)", "All connected", "No", "20°C"],
        ["2", "Closed (on)", "All connected", "Yes", "65°C"],
        ["3", "Closed (on)", "One wire came loose", "No", "20°C"],
      ],
    },
    parts: [
      { type: "number", prompt: "The coil started at 20°C in every test. How many degrees did it warm up in Test 2?", unit: "°C" },
      { type: "choice", prompt: "Why did the coil stay at 20°C in Test 1?", choices: [
        { id: "a", text: "The open switch made a gap, so the loop was not closed and no electrical energy flowed." },
        { id: "b", text: "The battery was empty in Test 1." },
        { id: "c", text: "The coil was made of plastic." },
        { id: "d", text: "The light used up all the energy." },
      ] },
      { type: "choice", prompt: "The switch was closed in Test 3. Why did the coil still stay cold?", choices: [
        { id: "a", text: "The loose wire made a gap, so the loop was open." },
        { id: "b", text: "A closed switch always makes a circuit cold." },
        { id: "c", text: "Coils only heat up at night." },
        { id: "d", text: "The light was too bright." },
      ] },
      { type: "multi", prompt: "Pick every kind of energy the circuit made in Test 2.", choices: [
        { id: "light", text: "Light energy from the small light" },
        { id: "thermal", text: "Thermal energy from the coil" },
        { id: "water", text: "Water from the coil" },
        { id: "battery", text: "More battery energy" },
      ] },
    ],
    hint: "Compare the tests. What was different in the one test where the coil got hot?",
    meter: { heat: 10, label: "Grid charge +10%", story: "The heater hut is warm again" },
    discovery: { id: "toaster", name: "Toaster wires", who: "Kai", fact: "The wires inside a toaster glow orange when it's on. Electrical energy turns into so much thermal energy that the wires get hot enough to toast bread." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 45 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["light", "thermal"] },
    ] },
    rightFeedback: "Only a closed loop let energy flow, and then the circuit made both light and heat. The crew is warm!",
    wrong: [
      { step: 1, value: 65, hint: "65°C is where the coil ended. It started at 20°C. How much did it go up?" },
      { step: 1, value: 85, hint: "The coil warmed from 20°C to 65°C. Should you add or subtract to find the change?" },
      { step: 1, value: 20, hint: "20°C is where the coil started. How much warmer did it get?" },
      { step: 2, choice: "b", hint: "The same battery worked in Test 2. Check the Switch column for Test 1." },
      { step: 2, choice: "c", hint: "The same coil got hot in Test 2, so it isn't plastic. Check the Switch column." },
      { step: 2, choice: "d", hint: "The light didn't glow in Test 1 either. Check the Switch column. What does an open switch do?" },
      { step: 3, choice: "b", hint: "The closed switch in Test 2 made the coil hot. Check the Wires column for Test 3." },
      { step: 3, choice: "c", hint: "The tests don't say anything about night. Check the Wires column for Test 3." },
      { step: 3, choice: "d", hint: "The light didn't glow at all in Test 3. Check the Wires column." },
      { step: 4, pick: "water", hint: "A heating coil doesn't make water. What did the coil give off?" },
      { step: 4, pick: "battery", hint: "A circuit uses battery energy. It doesn't make more of it." },
      { step: 4, missing: true, hint: "There are two kinds. What did the small light make? What did the coil make?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Outlet safety", machine: "Safety Station", icon: "shield", speaker: "vega",
    line: "Before we connect the outpost to Mechara's big power grid, every crew member takes the safety check. Big power lines and wall outlets carry far more energy than our little batteries.",
    question: "Which is the safest rule for wall outlets?",
    hint: "Your body can become part of a circuit. Would that be safe?",
    meter: { heat: 10, label: "Grid charge +10%", story: "The crew passes the safety check" },
    discovery: { id: "wethands", name: "Water and electricity", who: "Nova", fact: "Tap water has tiny bits of minerals in it that let electricity flow. That's why you should never touch plugs or switches with wet hands." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Never poke anything into an outlet or play with it. Ask an adult to plug things in if you need help." },
      { id: "b", text: "It's safe to poke a metal fork into an outlet if you're quick." },
      { id: "c", text: "Outlets are safe to touch with wet hands." },
      { id: "d", text: "A plastic straw in an outlet is fun to play with." },
    ],
    rightFeedback: "Never play with outlets. Your body can become part of a circuit, and that is very dangerous.",
    wrong: [
      { choice: "b", hint: "A metal fork is a conductor. It could let electricity flow into your body. Is that safe?" },
      { choice: "c", hint: "Water can let electricity flow. Wet hands make outlets more dangerous, not less." },
      { choice: "d", hint: "Outlets are never toys. What's the safest rule?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's mistake", machine: "Circuit Bench", icon: "relay", speaker: "kai",
    line: "I wired a lamp for the lookout tower. First wire from the top of the battery to the bulb. Second wire from the bulb back down toward the battery. The bulb won't light! The second wire stops a finger's width short of the battery.",
    question: "Part 1: What went wrong? Part 2: What is the best fix?",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's circuit?", choices: [
        { id: "a", text: "There is a gap between the second wire and the battery, so the loop is open." },
        { id: "b", text: "The bulb is too big for the battery." },
        { id: "c", text: "The first wire used up all the energy." },
        { id: "d", text: "Copper wire blocks electricity." },
      ] },
      { type: "choice", prompt: "What is the best fix?", choices: [
        { id: "a", text: "Connect the end of the second wire to the bottom of the battery so the loop is closed." },
        { id: "b", text: "Wrap plastic tape across the gap." },
        { id: "c", text: "Add a second bulb and leave the gap." },
        { id: "d", text: "Fill the gap with a rubber eraser." },
      ] },
    ],
    hint: "Trace the path. Where does it stop?",
    meter: { supplies: 1, label: "Circuit badges +1", story: "The lookout tower lamp is on" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Closing the gap makes a complete loop, and the lookout lamp lights up!",
    wrong: [
      { step: 1, choice: "b", hint: "Kai said the wire stops short of the battery. What does a gap do to a loop?" },
      { step: 1, choice: "c", hint: "Wires don't use up energy. Kai said the second wire doesn't reach the battery. What does that do?" },
      { step: 1, choice: "d", hint: "Copper is a conductor. The problem is where the wire stops." },
      { step: 2, choice: "b", hint: "Plastic tape is an insulator. It would still leave the loop open." },
      { step: 2, choice: "c", hint: "A new bulb won't help if the loop still has a gap." },
      { step: 2, choice: "d", hint: "Rubber is an insulator. Electricity can't flow through it." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Used up by the first bulb?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The watchtower string has three bulbs in one loop. The first bulb uses up all the electricity. So after the first bulb, the loop can be open. Nothing is left to flow back anyway!"',
    nova: 'Nova: "Electrical energy moves around the whole closed path. If you open the loop anywhere, nothing flows, and even the first bulb goes dark."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about Test 3 in the heater hut. One loose wire made the whole circuit stop.",
    meter: { heat: 5, label: "Grid charge +5%", story: "Kai closes the watchtower loop" },
    discovery: { id: "holiday", name: "Holiday lights", who: "Kai", fact: "In some old strings of holiday lights, all the bulbs were in one loop. If one bulb burned out, it made a gap and the whole string went dark." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Electricity only flows in a closed path. A gap anywhere in the loop stops the flow everywhere, even at the first bulb." },
      { id: "B", text: "Nova, because three bulbs are prettier than one." },
      { id: "C", text: "Kai. The first bulb gets all the energy, so the rest of the loop doesn't matter." },
      { id: "D", text: "Kai. Electricity stops once it reaches a bulb." },
    ],
    writtenPrompt: "Tell Kai in your own words why the loop has to stay closed after the first bulb.",
    debateHints: {
      wrongWho: "Remember Test 3. One loose wire, and the light and the coil both stopped. Can the loop be open?",
      wrongReason: "Right person, check the reason. What happens to the flow when there is a gap anywhere?",
      right: "Nova is right — a gap anywhere stops the flow everywhere.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Will it glow?", machine: "Test Bench", icon: "grid", speaker: "nova",
    line: "Kai wired five new lamps for the outpost walls. Let's predict which ones will light before we flip the power on.",
    question: "Sort each circuit: will the bulb light or stay dark?",
    hint: "Trace each path. Does it make a complete loop through only conductors, from one end of the battery to the other?",
    meter: { supplies: 1, label: "Circuit badges +1", story: "Every wall lamp is checked" },
    answer: { kind: "sort", bins: { l1: "light", l2: "dark", l3: "light", l4: "dark", l5: "dark" } },
    rightFeedback: "Only the complete loops of metal light up. Open switches, rubber, and missing wires all leave gaps.",
    sort: {
      bins: [{ id: "light", label: "Bulb lights" }, { id: "dark", label: "Bulb stays dark" }],
      items: [
        { id: "l1", label: "Battery, copper wire, bulb, copper wire, back to the battery" },
        { id: "l2", label: "Battery, copper wire, bulb, copper wire, open switch, back to the battery" },
        { id: "l3", label: "Battery, copper wire, bulb, steel paper clip, copper wire, back to the battery" },
        { id: "l4", label: "Battery, copper wire, bulb, rubber band, copper wire, back to the battery" },
        { id: "l5", label: "Battery, copper wire, bulb, and no wire back to the battery" },
      ],
    },
    wrong: [
      { item: "l3", hint: "A steel paper clip is metal, so it conducts. Is the loop still complete?" },
      { item: "l2", hint: "An open switch makes a gap in the loop." },
      { item: "l4", hint: "Rubber is an insulator. It makes a gap in the loop." },
      { item: "l5", hint: "There's no path back to the battery. The loop is open." },
      { item: "l1", hint: "Trace it: battery, wire, bulb, wire, battery. Is that a complete loop?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Power up the grid", machine: "Grid Panel", icon: "battery", speaker: "vega",
    line: "This is it! Mechara's city council will connect our outpost to the grid tonight. They want to see our test results and our plan for the main heater line first.",
    question: "Part 1: Which material should carry the energy in the main line? Part 2: Which material should coat the outside of the line? Part 3: Why did the copper get warm? Part 4: Write 2–3 sentences to Commander Vega explaining how the closed loop makes light and heat. Use the test results.",
    data: {
      title: "Nova's material test (each item placed in the gap of a working circuit for 1 minute)",
      columns: ["Material", "Did the bulb light?", "Did the material feel warm?"],
      rows: [
        ["Copper strip", "Yes, bright", "Yes, a little"],
        ["Aluminum strip", "Yes, bright", "Yes, a little"],
        ["Rubber strip", "No", "No"],
        ["Plastic strip", "No", "No"],
        ["Glass rod", "No", "No"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Which material should carry the energy in the main heater line?", choices: [
        { id: "a", text: "Copper, because it lit the bulb, so it is a conductor." },
        { id: "b", text: "Rubber, because it stayed cool." },
        { id: "c", text: "Glass, because it is clear." },
        { id: "d", text: "Plastic, because it is light and bendy." },
      ] },
      { type: "choice", prompt: "Which material should coat the outside of the line to keep people safe?", choices: [
        { id: "a", text: "Rubber, because it did not light the bulb, so it is an insulator." },
        { id: "b", text: "Aluminum, because it lit the bulb." },
        { id: "c", text: "Copper, because it felt warm." },
        { id: "d", text: "No coat is needed." },
      ] },
      { type: "choice", prompt: "Why did the copper strip get a little warm?", choices: [
        { id: "a", text: "Some of the electrical energy flowing through it changed into thermal energy." },
        { id: "b", text: "The glass rod heated it up." },
        { id: "c", text: "Copper is always warm." },
        { id: "d", text: "The bulb was blowing hot air on it." },
      ] },
      { type: "write", prompt: "Explain to Commander Vega how the closed loop makes light and heat. Use the test results.", minWords: 20 },
    ],
    rubric: ["Says electrical energy flows only in a complete, closed loop", "Uses the test results as evidence (conductors lit the bulb, insulators did not)", "Explains that the electrical energy changes into light and thermal energy"],
    hint: "The bulb lit only when a conductor closed the gap. Look at both the bulb column and the warm column.",
    meter: { heat: 15, label: "Grid charge +15%", story: "The outpost is on Mechara's power grid" },
    discovery: { id: "led", name: "LED lights", who: "Nova", fact: "LED bulbs change more of their electrical energy into light and less into heat than old-style bulbs. That's why they stay cooler and use less energy." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The outpost is on the grid! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "b", hint: "Rubber didn't light the bulb. Can the energy flow through it?" },
      { step: 1, choice: "c", hint: "Being clear doesn't matter. Did the glass rod light the bulb?" },
      { step: 1, choice: "d", hint: "Plastic didn't light the bulb. Can energy flow through it?" },
      { step: 2, choice: "b", hint: "Aluminum is a conductor. A coat should block electricity, not carry it." },
      { step: 2, choice: "c", hint: "Copper is the conductor inside. What kind of material blocks electricity?" },
      { step: 2, choice: "d", hint: "Bare wire is dangerous. What would keep the energy on its path?" },
      { step: 3, choice: "b", hint: "The glass rod was tested on its own and stayed cool. Where did the copper's heat come from?" },
      { step: 3, choice: "c", hint: "Check the table. The copper got warm while energy flowed through it. What changed?" },
      { step: 3, choice: "d", hint: "A bulb doesn't blow air. What happens to some electrical energy as it flows through a wire?" },
    ],
  },
};

export default {
  id: "SCI.4.8C-XP",
  standard: "SCI.4.8C-XP",
  engine: "expedition_station",
  title: "The Power Grid",
  planet: "Mechara",
  outpost: "Bolt Ridge Outpost · first night",
  grade: 4,
  subject: "Science",
  teks: "4.8C",
  supportingTeks: ["4.8B", "4.1B", "4.1G", "4.2B", "4.3A", "4.3C", "4.5B", "4.5D"],
  skillsChip: "4.8C · Closed circuits",
  iCan: "I can show and explain that electrical energy moves in a closed path. I can explain how a circuit can make light and heat.",
  blurb: "The crew's new outpost on Mechara is dark and cold. The crew has to wire the lights and heaters, sort conductors from insulators, and prove that electricity needs a closed loop.",
  mission: "Wire the outpost's lights and heaters, find every gap in the loop, and get the outpost ready for Mechara's power grid.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.8 · MECHARA BOLT RIDGE",
  playableActs: [1, 2, 3],
  earthTrue: "Mechara and the outpost are invented. Every circuit, material, fact, and data table in this quest works the way it does on Earth.",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Grid charge", heatUnit: "%", supplies: "Circuit badges", suppliesUnit: "badges" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We just landed at our new outpost on Mechara, the robot city.",
    "The lights are dark, and the heaters are cold. Nothing is wired yet.",
    "Electricity here works just like it does on Earth. Help Kai and Nova wire the outpost before night falls. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Light the hallway", "Act 2 · Warm the heater hut", "Act 3 · Join the grid"],
    completes: [
      "The hallway lamp is glowing, {firstName}!",
      "The heater hut is warm, {firstName}! The crew can finally stop shivering.",
      "The outpost is on Mechara's power grid, {firstName}! Every light and heater is working.",
    ],
    teasers: [
      "Next on Mechara: the heater hut is freezing, and Kai thinks one wire is enough. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: a safety check, a lamp that won't light, and a big night on the grid. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The lights work, but the heater hut is freezing.",
      "Kai already has an idea about the heater wires. I'm not sure I agree.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Tonight the city connects us to Mechara's power grid.",
      "Let's make sure every circuit is safe and every loop is closed.",
    ],
  }),
  tasks,
};
