// Expedition Station — The Precision Lab (MA.5.2B-XP)
// Grade 5 · Math · Frostveil. Main standard 5.2B (compare and order two
// decimals to thousandths and show the comparison with >, <, or =). Also
// practices 5.2A (the value of a digit through thousandths, expanded notation
// and numerals) and 5.2C (round decimals to tenths or hundredths).
// Number lines are zoomed in so every tick is one hundredth or one thousandth.
// Earth-true rule: Frostveil and its lab are invented; every fact is real.
import { CREW, acts } from "./_shared.js";

const PV_COLS = ["Sample", "Ones", ".", "Tenths", "Hundredths", "Thousandths"];

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "The long ice core", machine: "Core Ruler", icon: "scan", speaker: "nova",
    line: "Welcome to the Precision Lab, where we measure everything to the thousandth! Our first ice core is 2.475 meters long.",
    question: "Look at the place value chart. What is the value of the 7 in 2.475?",
    data: { title: "Ice core length (meters)", columns: PV_COLS, rows: [["Core 1", "2", ".", "4", "7", "5"]] },
    hint: "Find the 7 in the chart. Which column is it in? The second place after the decimal point is hundredths.",
    meter: { heat: 10, label: "Lab precision +10%", story: "The core ruler is lined up" },
    discovery: { id: "millimeter", name: "Tiny millimeters", who: "Nova", fact: "A millimeter is one thousandth of a meter. So 0.001 meter is 1 millimeter, about as thick as a paper clip wire." },
    choices: [
      { id: "a", text: "0.07 (7 hundredths)" },
      { id: "b", text: "0.7 (7 tenths)" },
      { id: "c", text: "0.007 (7 thousandths)" },
      { id: "d", text: "7 (7 ones)" },
    ],
    answer: { kind: "choice", correct: "a" },
    rightFeedback: "The 7 is in the hundredths place, so it's worth 0.07 meter.",
    wrong: [
      { choice: "b", hint: "The 4 is in the tenths place. The 7 is one place to the right of it." },
      { choice: "c", hint: "The thousandths place is the third place after the point. That's the 5." },
      { choice: "d", hint: "The ones place holds the 2. The 7 comes after the decimal point." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Rebuild the crystal label", machine: "Label Printer", icon: "log", speaker: "kai",
    line: "The label printer broke! It printed a crystal's mass in pieces: 4 + 0.2 + 0.005 grams. I need it as one number.",
    question: "Write 4 + 0.2 + 0.005 as a single decimal number.",
    data: { title: "Label pieces", columns: ["Piece", "Place"], rows: [["4", "Ones"], ["0.2", "Tenths"], ["0.005", "Thousandths"]] },
    hint: "Put each digit in its place: 4 ones, 2 tenths, 0 hundredths, 5 thousandths. Don't forget a 0 for the empty place.",
    meter: { heat: 5, label: "Lab precision +5%", story: "The crystal has a new label" },
    discovery: { id: "frostflowers", name: "Frost flowers", who: "Kai", fact: "On very cold, calm nights, tiny ice spikes called frost flowers can grow on brand-new sea ice. They look like a field of white blossoms." },
    answer: { kind: "number", value: 4.205 },
    rightFeedback: "4 ones, 2 tenths, 0 hundredths, 5 thousandths is 4.205 grams!",
    wrong: [
      { value: 4.25, hint: "4.25 puts the 5 in the hundredths place. 0.005 is 5 thousandths. Hold the hundredths place with a 0." },
      { value: 4.025, hint: "That puts the 2 in the hundredths place. 0.2 is 2 tenths, right after the point." },
      { value: 4.2005, hint: "That's one place too far. Thousandths is the third place after the point." },
      { value: 4.7, hint: "Don't add the digits together. Each piece goes in its own place." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Zoom in on the scale", machine: "Micro Scale", icon: "dial", speaker: "nova",
    line: "The micro scale zooms in between 0.35 and 0.36 gram. Each tiny tick is one thousandth. A snow crystal just landed on it: 0.358 gram.",
    question: "Part 1: Tap 0.358 on the zoomed scale. Part 2: Compare 0.358 and 0.35.",
    parts: [
      { type: "number", prompt: "Each tick is 0.001. Tap 0.358 on the scale.",
        visual: { type: "numline", min: 0.35, max: 0.36, step: 0.001, labelEvery: 5, pick: true, title: "Micro scale · 0.35 to 0.36 gram", label: "Mass in grams" } },
      { type: "choice", prompt: "Which is true?", choices: [
        { id: "a", text: "0.358 > 0.35" },
        { id: "b", text: "0.358 < 0.35" },
        { id: "c", text: "0.358 = 0.35" },
      ] },
    ],
    hint: "0.35 is the same as 0.350. Count 8 thousandths past 0.350. Numbers get bigger as you go right.",
    meter: { heat: 5, label: "Lab precision +5%", story: "The micro scale is reading true" },
    discovery: { id: "luge", name: "Thousandths of a second", who: "Nova", fact: "In Olympic luge races, sleds are timed to the thousandth of a second. Racers can finish just 0.001 second apart!" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 0.358 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "0.358 is 8 ticks past 0.350, so 0.358 > 0.35!",
    wrong: [
      { step: 1, value: 0.35, hint: "That's where the scale starts. Count 8 small ticks to the right." },
      { step: 1, value: 0.36, hint: "That's the end of the scale. 0.358 is a little before 0.36." },
      { step: 1, value: 0.355, hint: "That's the middle tick, 5 thousandths. Count 3 more ticks." },
      { step: 2, choice: "b", hint: "Write 0.35 as 0.350. Is 358 thousandths less than 350 thousandths?" },
      { step: 2, choice: "c", hint: "0.358 has 8 extra thousandths. It sits to the right of 0.35 on the scale." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Two scales, one crystal", machine: "Symbol Board", icon: "grid", speaker: "kai",
    line: "Scale A says the blue crystal is 5.06 grams. Scale B says 5.060 grams. And the green crystal is 5.6 grams. I need the right symbols on the board.",
    question: "Part 1: Compare 5.06 and 5.060. Part 2: Compare 5.6 and 5.06.",
    data: { title: "Crystal masses (grams)", columns: PV_COLS, rows: [["Blue, Scale A", "5", ".", "0", "6", ""], ["Blue, Scale B", "5", ".", "0", "6", "0"], ["Green", "5", ".", "6", "", ""]] },
    parts: [
      { type: "choice", prompt: "5.06 ___ 5.060", choices: [
        { id: "eq", text: "=" },
        { id: "lt", text: "<" },
        { id: "gt", text: ">" },
      ] },
      { type: "choice", prompt: "5.6 ___ 5.06", choices: [
        { id: "gt", text: ">" },
        { id: "lt", text: "<" },
        { id: "eq", text: "=" },
      ] },
    ],
    hint: "Line up the places. A 0 at the very end doesn't change the value. Then compare tenths first.",
    meter: { heat: 5, label: "Lab precision +5%", story: "Both scales agree" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "eq" }, { kind: "choice", correct: "gt" }] },
    rightFeedback: "5.06 = 5.060, because an end zero changes nothing. And 5.6 > 5.06, because 6 tenths beats 0 tenths!",
    wrong: [
      { step: 1, choice: "lt", hint: "The extra 0 is in the thousandths place. 0 thousandths adds nothing." },
      { step: 1, choice: "gt", hint: "Check every place: 5 ones, 0 tenths, 6 hundredths in both. Same value." },
      { step: 2, choice: "lt", hint: "5.06 has more digits, but compare the tenths: 6 tenths vs 0 tenths." },
      { step: 2, choice: "eq", hint: "Both have a 6, but in different places. 5.6 has 6 tenths. 5.06 has 6 hundredths." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The vault door alarm", machine: "Crystal Vault", icon: "snap", speaker: "vega",
    line: "Surprise! The crystal vault is closing for the night. Three crystals must go in, lightest first, or the door locks. They weigh 2.35, 2.305, and 2.3 grams.",
    question: "Part 1: Which is the expanded form of 2.305? Part 2: Order the crystals from least to greatest. Part 3: Compare 2.305 and 2.35.",
    data: { title: "Vault crystals (grams)", columns: PV_COLS, rows: [["Red", "2", ".", "3", "5", ""], ["White", "2", ".", "3", "0", "5"], ["Gold", "2", ".", "3", "", ""]] },
    parts: [
      { type: "choice", prompt: "Which is the expanded form of 2.305?", choices: [
        { id: "a", text: "2 + 0.3 + 0.005" },
        { id: "b", text: "2 + 0.3 + 0.05" },
        { id: "c", text: "2 + 3 + 5" },
        { id: "d", text: "2 + 0.03 + 0.005" },
      ] },
      { type: "order", prompt: "Put the crystals in order from least to greatest.", items: [
        { id: "red", text: "Red · 2.35 g" },
        { id: "white", text: "White · 2.305 g" },
        { id: "gold", text: "Gold · 2.3 g" },
      ] },
      { type: "choice", prompt: "2.305 ___ 2.35", choices: [
        { id: "lt", text: "<" },
        { id: "gt", text: ">" },
        { id: "eq", text: "=" },
      ] },
    ],
    hint: "Give every mass three decimal places: 2.350, 2.305, 2.300. Now compare them like thousandths.",
    meter: { heat: 10, label: "Lab precision +10%", story: "The crystals are safe in the vault" },
    discovery: { id: "hail", name: "Weighing gems", who: "Kai", fact: "Jewelers weigh gems in carats. One carat is 0.2 grams, so a 1-carat gem weighs just 2 tenths of a gram." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["gold", "white", "red"] },
      { kind: "choice", correct: "lt" },
    ] },
    rightFeedback: "2.300 < 2.305 < 2.350. Gold, White, then Red. The vault door is shut tight!",
    wrong: [
      { step: 1, choice: "b", hint: "0.05 is 5 hundredths. In 2.305, the 5 is in the thousandths place." },
      { step: 1, choice: "c", hint: "The 3 and the 5 are after the decimal point. They are tenths and thousandths, not ones." },
      { step: 1, choice: "d", hint: "The 3 is right after the point, so it's 3 tenths, 0.3." },
      { step: 2, position: 0, hint: "2.3 is 2.300. That's the least. It goes first." },
      { step: 2, position: 1, hint: "2.305 or 2.350? Compare the hundredths: 0 is less than 5." },
      { step: 3, choice: "gt", hint: "2.305 is longer, but longer isn't bigger. Compare hundredths: 0 vs 5." },
      { step: 3, choice: "eq", hint: "Write 2.35 as 2.350. Is 2.305 the same as 2.350?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Line up the ice cores", machine: "Core Rack", icon: "cells", speaker: "nova",
    line: "We drilled four more ice cores. They go on the rack from shortest to longest, so we can compare the ice layers.",
    question: "Put the ice cores in order from least to greatest length.",
    data: { title: "Ice core lengths (meters)", columns: PV_COLS, rows: [
      ["Core A", "1", ".", "4", "8", "2"], ["Core B", "1", ".", "4", "2", "8"], ["Core C", "1", ".", "5", "", ""], ["Core D", "1", ".", "4", "5", ""],
    ] },
    hint: "Fill the empty places with zeros: 1.482, 1.428, 1.500, 1.450. All the ones match, so compare the tenths, then hundredths.",
    meter: { supplies: 1, label: "Core tubes +1", story: "The cores are racked in order" },
    discovery: { id: "bubbles", name: "Air from long ago", who: "Nova", fact: "Ice cores have tiny air bubbles trapped inside. Scientists study that old air to learn what Earth's air was like long ago." },
    items: [
      { id: "a", text: "Core A · 1.482 m" },
      { id: "b", text: "Core B · 1.428 m" },
      { id: "c", text: "Core C · 1.5 m" },
      { id: "d", text: "Core D · 1.45 m" },
    ],
    answer: { kind: "order", correct: ["b", "d", "a", "c"] },
    rightFeedback: "1.428 < 1.45 < 1.482 < 1.5. Core C is the shortest to write but the longest core!",
    wrong: [
      { position: 0, hint: "Three cores have 4 tenths. Look at their hundredths. Which is smallest?" },
      { position: 1, hint: "1.45 is 1.450. Is 1.450 more or less than 1.482?" },
      { position: 2, hint: "1.5 is 1.500. It has 5 tenths, more than any other core." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The longer-number debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Sample X is 0.305 kilogram and Sample Y is 0.35 kilogram. 0.305 has more digits, and 305 is bigger than 35. So Sample X is heavier!"',
    nova: 'Nova: "Wait! Write 0.35 as 0.350. That\'s 350 thousandths. 0.305 is only 305 thousandths. Sample Y is heavier."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Give both numbers three decimal places. Then compare place by place, starting with tenths.",
    meter: { heat: 5, label: "Lab precision +5%", story: "The crew agrees on the samples" },
    discovery: { id: "seaice", name: "Salt leaves sea ice", who: "Nova", fact: "Sea ice that lasts through a summer loses most of its salt. Arctic explorers have melted old sea ice for drinking water." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 0.35 = 0.350, and 350 thousandths is more than 305 thousandths." },
      { id: "B", text: "Nova, because 0.35 is easier to read." },
      { id: "C", text: "Kai. A decimal with more digits is always greater." },
      { id: "D", text: "Kai. 305 is bigger than 35, so 0.305 is bigger than 0.35." },
    ],
    writtenPrompt: "Tell Kai in your own words why 0.35 is greater than 0.305.",
    debateHints: {
      wrongWho: "Line up the places. Both have 3 tenths. Now look at hundredths: 0.305 has 0 hundredths and 0.35 has 5 hundredths.",
      wrongReason: "Right person, check the reason. Think about place value, not how the number looks.",
      right: "Nova is right. 0.35 = 0.350, and 350 thousandths > 305 thousandths. More digits doesn't mean greater!",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Round the core sample", machine: "Rounding Gauge", icon: "trail", speaker: "vega",
    line: "The supply log only has room for short numbers. An ice core sample weighs 3.768 kilograms. Round it for the log.",
    question: "Part 1: Round 3.768 to the nearest hundredth. Tap it on the gauge. Part 2: Round 3.768 to the nearest tenth.",
    parts: [
      { type: "number", prompt: "The gauge zooms in from 3.76 to 3.77. Is 3.768 closer to 3.76 or 3.77? Tap the hundredth it rounds to.",
        visual: { type: "numline", min: 3.76, max: 3.77, step: 0.001, labelEvery: 5, pick: true, marks: [{ value: 3.768, label: "Sample" }], title: "Rounding gauge · 3.76 to 3.77 kg", label: "Mass in kilograms" } },
      { type: "number", prompt: "Now round 3.768 to the nearest tenth. Type your answer.", unit: "kilograms" },
    ],
    hint: "To round to hundredths, look at the thousandths digit. 5 or more rounds up. To round to tenths, look at the hundredths digit.",
    meter: { supplies: 1, label: "Core tubes +1", story: "The supply log is filled in" },
    discovery: { id: "diamonddust", name: "Diamond dust", who: "Kai", fact: "On very cold, clear days, tiny ice crystals can float in the air and sparkle in the sun. This is called diamond dust." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 3.77 }, { kind: "number", value: 3.8 }] },
    rightFeedback: "3.768 rounds to 3.77 (8 thousandths rounds up) and to 3.8 (6 hundredths rounds up)!",
    wrong: [
      { step: 1, value: 3.76, hint: "The thousandths digit is 8. 8 is 5 or more, so round up to 3.77." },
      { step: 1, value: 3.768, hint: "That's the exact mass. Rounding means picking the closest hundredth, 3.76 or 3.77." },
      { step: 1, value: 3.765, hint: "That's the halfway tick. Round to a hundredth at one end of the gauge." },
      { step: 2, value: 3.7, hint: "Look at the hundredths digit: 6. 6 is 5 or more, so the tenths go up." },
      { step: 2, value: 3.77, hint: "That's rounded to the hundredth. For the nearest tenth, keep only one place after the point." },
      { step: 2, value: 4, hint: "That's rounded to the nearest whole. Keep one place after the point: tenths." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Sort the freezer shelves", machine: "Sort Freezer", icon: "tank", speaker: "nova",
    line: "The freezer has three shelves. Shelf rules: under 2.45 grams, exactly 2.45 grams, or over 2.45 grams. Every crystal needs a shelf.",
    question: "Sort each crystal by comparing its mass to 2.45 grams.",
    hint: "Write 2.45 as 2.450. Give each mass three decimal places and compare it to 2.450.",
    meter: { supplies: 1, label: "Core tubes +1", story: "Every crystal is on the right shelf" },
    discovery: { id: "lakeice", name: "Lakes freeze on top", who: "Nova", fact: "Lakes freeze from the top down. The ice works like a lid, and fish keep swimming in the liquid water underneath." },
    answer: { kind: "sort", bins: { s1: "less", s2: "more", s3: "equal", s4: "less", s5: "more", s6: "less" } },
    rightFeedback: "Every crystal is shelved! Comparing each one to 2.450 made it easy.",
    sort: {
      bins: [
        { id: "less", label: "Less than 2.45 g" },
        { id: "equal", label: "Equal to 2.45 g" },
        { id: "more", label: "Greater than 2.45 g" },
      ],
      items: [
        { id: "s1", label: "Crystal 1 · 2.405 g" },
        { id: "s2", label: "Crystal 2 · 2.5 g" },
        { id: "s3", label: "Crystal 3 · 2.450 g" },
        { id: "s4", label: "Crystal 4 · 2.449 g" },
        { id: "s5", label: "Crystal 5 · 2.451 g" },
        { id: "s6", label: "Crystal 6 · 2.4 g" },
      ],
    },
    wrong: [
      { item: "s1", hint: "2.405 is longer, but compare hundredths: 0 is less than 5. It's less than 2.450." },
      { item: "s2", hint: "2.5 is 2.500. 5 tenths is more than 4 tenths." },
      { item: "s3", hint: "2.450 and 2.45 have the same digits in every place. The end 0 adds nothing." },
      { item: "s4", hint: "2.449 is just 1 thousandth less than 2.450." },
      { item: "s5", hint: "2.451 is just 1 thousandth more than 2.450." },
      { item: "s6", hint: "2.4 is 2.400. That's less than 2.450." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Whiteout in the lab", machine: "Backup Scale", icon: "quake", speaker: "vega",
    line: "Surprise! A whiteout knocked out the main power. The backup scale shows only tick marks. Sample Z weighs 4.506 grams, and the old log says 4.56 grams. Which is right?",
    question: "Part 1: Tap 4.506 on the backup scale. Part 2: Compare 4.506 and 4.56. Part 3: Round 4.506 to the nearest hundredth. Part 4: What is the value of the 6 in 4.506?",
    parts: [
      { type: "number", prompt: "Each tick is 0.001. Tap 4.506 on the backup scale.",
        visual: { type: "numline", min: 4.5, max: 4.51, step: 0.001, labelEvery: 5, pick: true, title: "Backup scale · 4.5 to 4.51 grams", label: "Mass in grams" } },
      { type: "choice", prompt: "4.506 ___ 4.56", choices: [
        { id: "lt", text: "<" },
        { id: "gt", text: ">" },
        { id: "eq", text: "=" },
      ] },
      { type: "number", prompt: "Round 4.506 to the nearest hundredth.", unit: "grams" },
      { type: "choice", prompt: "What is the value of the 6 in 4.506?", choices: [
        { id: "a", text: "0.006 (6 thousandths)" },
        { id: "b", text: "0.06 (6 hundredths)" },
        { id: "c", text: "0.6 (6 tenths)" },
        { id: "d", text: "6 (6 ones)" },
      ] },
    ],
    hint: "4.56 is 4.560. Compare hundredths: 4.506 has 0 hundredths. To round, look at the thousandths digit.",
    meter: { heat: 10, label: "Lab precision +10%", story: "The power is back and the log is fixed" },
    discovery: { id: "fahrenheit", name: "The first scale", who: "Kai", fact: "In 1724, a scientist named Daniel Fahrenheit shared a temperature scale for thermometers. The United States still uses his scale for weather reports today." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 4.506 },
      { kind: "choice", correct: "lt" },
      { kind: "number", value: 4.51 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "4.506 < 4.56, so the old log was wrong. 4.506 rounds to 4.51, and the 6 is worth 0.006!",
    wrong: [
      { step: 1, value: 4.5, hint: "That's where the scale starts. Count 6 small ticks to the right." },
      { step: 1, value: 4.51, hint: "That's the end of the scale. 4.506 is 6 ticks past 4.500." },
      { step: 1, value: 4.505, hint: "That's the middle tick. Count 1 more." },
      { step: 2, choice: "gt", hint: "4.506 is longer, but compare hundredths: 0 vs 6. Longer isn't bigger." },
      { step: 2, choice: "eq", hint: "Both have a 5 and a 6, but in different places. Line them up: 4.506 and 4.560." },
      { step: 3, value: 4.5, hint: "That's rounded to the nearest tenth. The thousandths digit is 6, so the hundredths go up." },
      { step: 3, value: 4.56, hint: "Careful! 4.506 has 0 hundredths. It's between 4.50 and 4.51." },
      { step: 3, value: 4.506, hint: "That's the exact mass. Round to two places after the point." },
      { step: 4, choice: "b", hint: "The hundredths place holds the 0. The 6 is one place farther right." },
      { step: 4, choice: "c", hint: "The tenths place holds the 5. The 6 is two places farther right." },
      { step: 4, choice: "d", hint: "The ones place holds the 4. The 6 is after the decimal point." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The snowmelt jar", machine: "Melt Gauge", icon: "water", speaker: "nova",
    line: "We melted a jar of fresh snow. It made 5.017 liters of water. The report needs this number in expanded form.",
    question: "Part 1: Which is the expanded form of 5.017? Part 2: What is the value of the 7 in 5.017?",
    data: { title: "Snowmelt (liters)", columns: PV_COLS, rows: [["Jar 1", "5", ".", "0", "1", "7"]] },
    parts: [
      { type: "choice", prompt: "Which is the expanded form of 5.017?", choices: [
        { id: "a", text: "5 + 0.01 + 0.007" },
        { id: "b", text: "5 + 0.1 + 0.07" },
        { id: "c", text: "5 + 0.1 + 0.7" },
        { id: "d", text: "5 + 1 + 7" },
      ] },
      { type: "number", prompt: "Type the value of the 7 as a decimal.", unit: "liters" },
    ],
    hint: "The 0 holds the tenths place. So the 1 is in the hundredths place and the 7 is in the thousandths place.",
    meter: { heat: 5, label: "Lab precision +5%", story: "The snowmelt report is done" },
    discovery: { id: "snowmelt", name: "Snow is mostly air", who: "Nova", fact: "On average, about 10 inches of fresh snow melts down to only about 1 inch of water. Fluffy snow can melt down even more." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 0.007 }] },
    rightFeedback: "5.017 = 5 + 0.01 + 0.007. The 7 is worth 0.007, just 7 thousandths!",
    wrong: [
      { step: 1, choice: "b", hint: "Don't skip the 0! It holds the tenths place, so the 1 is in the hundredths place." },
      { step: 1, choice: "c", hint: "0.1 + 0.7 would be 8 tenths. Look at where the 1 and 7 really sit." },
      { step: 1, choice: "d", hint: "The 1 and 7 come after the decimal point. They are parts of a liter, not ones." },
      { step: 2, value: 7, hint: "7 would be 7 whole liters. The 7 is in the thousandths place." },
      { step: 2, value: 0.07, hint: "0.07 is 7 hundredths. The 7 is the third place after the point." },
      { step: 2, value: 0.7, hint: "0.7 is 7 tenths. The 7 is the third place after the point." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Fix Kai's temperature log", machine: "Repair", icon: "log", speaker: "kai",
    line: 'I logged two ice probe readings: 0.4 and 0.399. I wrote "0.4 < 0.399" because 399 is way bigger than 4!',
    question: "Part 1: What went wrong? Part 2: Pick the correct comparison. Part 3: How many thousandths is 0.4?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He compared 399 and 4 like whole numbers. 0.4 has 4 tenths, and 0.399 has only 3 tenths." },
        { id: "b", text: "He should have compared the last digits, 4 and 9." },
        { id: "c", text: "Decimals with different lengths can't be compared." },
        { id: "d", text: "Nothing. 0.399 really is greater." },
      ] },
      { type: "choice", prompt: "Which comparison is correct?", choices: [
        { id: "a", text: "0.4 > 0.399" },
        { id: "b", text: "0.4 < 0.399" },
        { id: "c", text: "0.4 = 0.399" },
      ] },
      { type: "number", prompt: "Write 0.4 as thousandths. 0.4 = ___ thousandths.", unit: "thousandths" },
    ],
    hint: "Start at the tenths place. 4 tenths or 3 tenths? You can also write 0.4 as 0.400.",
    meter: { supplies: 1, label: "Core tubes +1", story: "Kai's log is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "choice", correct: "a" }, { kind: "number", value: 400 }] },
    rightFeedback: "Fixed! 0.4 = 0.400, and 400 thousandths > 399 thousandths. So 0.4 > 0.399.",
    wrong: [
      { step: 1, choice: "b", hint: "The last digits are in different places. Start comparing at the tenths place." },
      { step: 1, choice: "c", hint: "They can! Just give them the same number of places: 0.400 and 0.399." },
      { step: 1, choice: "d", hint: "Write 0.4 as 0.400. Is 399 thousandths more than 400 thousandths?" },
      { step: 2, choice: "b", hint: "That's Kai's mistake. 4 tenths is more than 3 tenths." },
      { step: 2, choice: "c", hint: "0.399 is close to 0.4, but it's 1 thousandth less." },
      { step: 3, value: 4, hint: "0.4 is 4 tenths. Each tenth is 100 thousandths." },
      { step: 3, value: 40, hint: "40 would be hundredths. How many thousandths? Write 0.4 as 0.400." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The heavy block report", machine: "Report Screen", icon: "brief", speaker: "vega",
    line: "A block of glacier ice weighs 12.649 kilograms. Mission Control wants it rounded two ways. Watch out: round from the exact number every time!",
    question: "Part 1: Round 12.649 to the nearest tenth. Part 2: Round 12.649 to the nearest hundredth. Part 3: Compare 12.649 and 12.65.",
    data: { title: "Ice block (kilograms)", columns: ["Sample", "Tens", "Ones", ".", "Tenths", "Hundredths", "Thousandths"], rows: [["Block 7", "1", "2", ".", "6", "4", "9"]] },
    parts: [
      { type: "number", prompt: "Round 12.649 to the nearest tenth.", unit: "kilograms" },
      { type: "number", prompt: "Round 12.649 to the nearest hundredth.", unit: "kilograms" },
      { type: "choice", prompt: "12.649 ___ 12.65", choices: [
        { id: "lt", text: "<" },
        { id: "gt", text: ">" },
        { id: "eq", text: "=" },
      ] },
    ],
    hint: "For tenths, look only at the hundredths digit, 4. For hundredths, look only at the thousandths digit, 9.",
    meter: { heat: 5, label: "Lab precision +5%", story: "Mission Control has the report" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 12.6 }, { kind: "number", value: 12.65 }, { kind: "choice", correct: "lt" }] },
    rightFeedback: "12.649 rounds to 12.6 and to 12.65. And 12.649 < 12.650, by just 1 thousandth!",
    wrong: [
      { step: 1, value: 12.7, hint: "Don't round twice! Look only at the hundredths digit, 4. 4 is less than 5, so keep 6 tenths." },
      { step: 1, value: 12.65, hint: "That's rounded to the hundredth. For the nearest tenth, keep one place after the point." },
      { step: 1, value: 13, hint: "That's rounded to the nearest whole. Keep the tenths place." },
      { step: 2, value: 12.64, hint: "The thousandths digit is 9. 9 is 5 or more, so the hundredths go up." },
      { step: 2, value: 12.6, hint: "That's rounded to the tenth. Keep two places after the point." },
      { step: 3, choice: "gt", hint: "12.649 has more digits, but write 12.65 as 12.650. Which is more?" },
      { step: 3, choice: "eq", hint: "12.649 rounds to 12.65, but it isn't equal. It's 1 thousandth less." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Matching probe readings", machine: "Probe Check", icon: "static", speaker: "nova",
    line: "Our test probe should read 0.7 degrees. Five backup probes gave readings. Only the ones that equal 0.7 can stay in the lab.",
    question: "Pick every reading that is equal to 0.7.",
    hint: "Zeros at the end don't change a decimal. Zeros right after the point do! Write each reading with three places.",
    meter: { supplies: 1, label: "Core tubes +1", story: "The good probes are kept" },
    items: [
      { id: "a", text: "Probe A · 0.70" },
      { id: "b", text: "Probe B · 0.07" },
      { id: "c", text: "Probe C · 0.700" },
      { id: "d", text: "Probe D · 0.707" },
      { id: "e", text: "Probe E · 0.007" },
    ],
    answer: { kind: "multi", correct: ["a", "c"] },
    rightFeedback: "0.7 = 0.70 = 0.700. Probes A and C stay in the lab!",
    wrong: [
      { pick: "b", hint: "0.07 is 7 hundredths. The 0 after the point pushes the 7 to the right." },
      { pick: "d", hint: "0.707 is 7 thousandths more than 0.700. Close, but not equal." },
      { pick: "e", hint: "0.007 is only 7 thousandths. That's much less than 0.7." },
      { missing: true, hint: "There are two matching readings. Write 0.7 as 0.70 and 0.700." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The final core count", machine: "Master Rack", icon: "relay", speaker: "vega",
    line: "This is it! The supply ship leaves in one hour. Four prize ice cores must be packed shortest first: 3.09, 3.1, 3.009, and 3.19 meters. Surprise! Kai's note says \"3.009 is the longest, it has the most digits.\"",
    question: "Part 1: Compare 3.09 and 3.009. Part 2: Order all four cores least to greatest. Part 3: Round the longest core to the nearest tenth. Part 4: Which core has a 9 in the thousandths place?",
    data: { title: "Prize ice cores (meters)", columns: PV_COLS, rows: [
      ["Core P", "3", ".", "0", "9", ""], ["Core Q", "3", ".", "1", "", ""], ["Core R", "3", ".", "0", "0", "9"], ["Core S", "3", ".", "1", "9", ""],
    ] },
    parts: [
      { type: "choice", prompt: "3.09 ___ 3.009", choices: [
        { id: "gt", text: ">" },
        { id: "lt", text: "<" },
        { id: "eq", text: "=" },
      ] },
      { type: "order", prompt: "Put the cores in order from least to greatest.", items: [
        { id: "p", text: "Core P · 3.09 m" },
        { id: "q", text: "Core Q · 3.1 m" },
        { id: "r", text: "Core R · 3.009 m" },
        { id: "s", text: "Core S · 3.19 m" },
      ] },
      { type: "number", prompt: "Round the longest core, 3.19 meters, to the nearest tenth.", unit: "meters" },
      { type: "choice", prompt: "Which core has a 9 in the thousandths place?", choices: [
        { id: "r", text: "Core R · 3.009" },
        { id: "p", text: "Core P · 3.09" },
        { id: "s", text: "Core S · 3.19" },
        { id: "q", text: "Core Q · 3.1" },
      ] },
    ],
    hint: "Give every core three places: 3.090, 3.100, 3.009, 3.190. All have 3 ones, so compare tenths, then hundredths, then thousandths.",
    meter: { heat: 15, label: "Lab precision +15%", story: "The prize cores are packed and the ship takes off" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "gt" },
      { kind: "order", correct: ["r", "p", "q", "s"] },
      { kind: "number", value: 3.2 },
      { kind: "choice", correct: "r" },
    ] },
    rightFeedback: "3.009 < 3.09 < 3.1 < 3.19. Kai had it backward: 3.009 is the shortest! The cores are packed. Amazing precision, specialist!",
    wrong: [
      { step: 1, choice: "lt", hint: "3.009 has more digits, but compare hundredths: 9 vs 0. 3.09 is greater." },
      { step: 1, choice: "eq", hint: "The 9 is in different places. 3.09 is 3.090, and 3.009 is 3.009." },
      { step: 2, position: 0, hint: "Which core has 0 tenths and 0 hundredths? That one is shortest." },
      { step: 2, position: 1, hint: "3.09 has 0 tenths. 3.1 has 1 tenth. Which is less?" },
      { step: 2, position: 2, hint: "3.1 is 3.10, and 3.19 is 3.19. Which is less?" },
      { step: 3, value: 3.1, hint: "Look at the hundredths digit: 9. 9 is 5 or more, so the tenths go up." },
      { step: 3, value: 3.19, hint: "That's the exact length. Keep only one place after the point." },
      { step: 3, value: 3, hint: "That's rounded to the nearest whole. Keep the tenths place." },
      { step: 4, choice: "p", hint: "In 3.09, the 9 is in the hundredths place, the second place after the point." },
      { step: 4, choice: "s", hint: "In 3.19, the 9 is in the hundredths place. Thousandths is the third place." },
      { step: 4, choice: "q", hint: "3.1 has no 9 at all. Look for a 9 three places after the point." },
    ],
  },
};

export default {
  id: "MA.5.2B-XP",
  standard: "MA.5.2B-XP",
  engine: "expedition_station",
  title: "The Precision Lab",
  planet: "Frostveil",
  outpost: "Precision Lab · measure-to-the-thousandth day",
  grade: 5,
  subject: "Math",
  teks: "5.2B",
  supportingTeks: ["5.2A", "5.2C"],
  skillsChip: "5.2B · Compare and order decimals to thousandths",
  iCan: "I can compare and order decimals to the thousandths using >, <, and =, show digit values in expanded form, and round decimals to tenths or hundredths.",
  blurb: "The Precision Lab on Frostveil measures ice cores, crystals, and snowmelt to the thousandth. The crew needs help comparing, ordering, and rounding every reading.",
  mission: "Measure, compare, and order the lab's ice samples to the thousandth so the prize cores ship out on time.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.2B · FROSTVEIL PRECISION LAB",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Lab precision", heatUnit: "%", supplies: "Core tubes", suppliesUnit: "tubes" },
  journalMax: 10,
  earthTrue: "Frostveil and the Precision Lab are invented. Every fact and every bit of math works the way it does on Earth.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're at the Precision Lab on Frostveil, the ice planet.",
    "This lab measures ice cores, crystals, and snowmelt to the thousandth. One tiny mistake can mix up the whole log.",
    "Help Kai and Nova read, compare, order, and round every reading. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Read the tiny digits", "Act 2 · Compare the samples", "Act 3 · Pack the prize cores"],
    completes: [
      "The first samples are measured and the vault is locked, {firstName}!",
      "Every sample is compared and the whiteout is over, {firstName}!",
      "The prize cores are packed, {firstName}! The Precision Lab's log is perfect.",
    ],
    teasers: [
      "Next on Frostveil: new ice cores need comparing, and Kai has a big idea about long decimals. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the prize ice cores must be packed before the supply ship leaves. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. We drilled more ice cores, and the numbers are getting tricky.",
      "Kai thinks a longer decimal is always bigger. Let's check that together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The supply ship is coming for our prize ice cores.",
      "Fix Kai's log, finish the reports, and pack the cores in the right order.",
    ],
  }),
  tasks,
};
