// Expedition Station — The Radar Grid (MA.5.8C-XP)
// Grade 5 · Math · Cloudreach. Main standard 5.8C (graph ordered pairs in the
// first quadrant, including pairs from number patterns and input-output tables);
// also practices 5.8A (key attributes of the coordinate plane), 5.8B (the
// process for graphing), and 5.4C (generate a pattern from y = ax or y = x + a).
// Grids stay at max 8–10.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Switch on the radar", machine: "Radar Screen", icon: "dial", speaker: "kai",
    line: "The storm radar is back on! Two number lines cross at the corner of the screen. One goes across, and one goes up. There's a glowing dot where they meet.",
    question: "What is the name of the point where the x-axis and the y-axis meet, at (0, 0)?",
    visual: { type: "coords", max: 8, title: "Storm radar", points: [{ x: 0, y: 0, label: "?" }] },
    hint: "This point is where every trip on the grid starts. Both number lines are at zero there.",
    meter: { heat: 10, label: "Storm tracking +10%", story: "The radar screen lights up" },
    discovery: { id: "radar", name: "Weather radar", who: "Nova", fact: "Weather radar sends out radio waves. The waves bounce off raindrops, hail, and snow and come back, so forecasters can see where it is raining." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The origin" },
      { id: "b", text: "The x-axis" },
      { id: "c", text: "The y-axis" },
      { id: "d", text: "The ordered pair" },
    ],
    rightFeedback: "Yes! The origin is (0, 0), where the two axes meet.",
    wrong: [
      { choice: "b", hint: "The x-axis is the whole number line that goes across. What do we call the one point where the two axes cross?" },
      { choice: "c", hint: "The y-axis is the whole number line that goes up. What do we call the one point where the two axes cross?" },
      { choice: "d", hint: "(0, 0) is written as an ordered pair, but the point itself has a special name. Where does every trip start?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Drop the first probe", machine: "Probe Launcher", icon: "relay", speaker: "nova",
    line: "Commander Vega wants our first weather probe at (3, 5). The probe will measure the wind inside the rain clouds.",
    question: "Drop the probe at (3, 5). Tap the spot on the grid.",
    visual: { type: "coords", max: 8, pick: true, title: "Storm radar", points: [{ x: 0, y: 0, label: "Origin" }] },
    hint: "Start at the origin. The first number tells you how far to go across. The second number tells you how far to go up.",
    meter: { supplies: 1, label: "Probes +1", story: "Probe 1 is measuring the wind" },
    discovery: { id: "radiosonde", name: "Weather balloons", who: "Nova", fact: "Every day, weather balloons carry small instruments called radiosondes high into the sky. They measure temperature, wind, and how wet the air is." },
    answer: { kind: "point", x: 3, y: 5 },
    rightFeedback: "Probe down! You moved right 3 and up 5 to reach (3, 5).",
    wrong: [
      { point: { x: 5, y: 3 }, hint: "That's (5, 3). You switched the numbers. Go across first (3), then up (5)." },
      { point: { x: 3, y: 0 }, hint: "You moved right 3. Now move up 5 from there." },
      { point: { x: 0, y: 5 }, hint: "You moved up 5, but you forgot to move right 3 first." },
      { point: { x: 3, y: 3 }, hint: "Right 3 is correct. Check how far up you went. The second number is 5." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Find the storm eye", machine: "Radar Screen", icon: "quake", speaker: "kai",
    line: "The radar shows three things in the sky: a rain cloud, a flock of sky rays, and the calm eye of the storm.",
    question: "Which ordered pair names the Storm Eye?",
    visual: { type: "coords", max: 8, title: "Storm radar", points: [{ x: 6, y: 2, label: "Rain cloud" }, { x: 4, y: 7, label: "Storm Eye" }, { x: 1, y: 3, label: "Sky rays" }] },
    hint: "Start at the origin. Count how far across the Storm Eye is. Then count how far up it is.",
    meter: { heat: 10, label: "Storm tracking +10%", story: "The crew spots the storm's eye" },
    discovery: { id: "eye", name: "The eye of a storm", who: "Nova", fact: "The calm center of a hurricane is called the eye. The strongest winds swirl in a ring around it called the eyewall." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "(4, 7)" },
      { id: "b", text: "(7, 4)" },
      { id: "c", text: "(6, 2)" },
      { id: "d", text: "(4, 4)" },
    ],
    rightFeedback: "Right! The Storm Eye is 4 across and 7 up, so it's at (4, 7).",
    wrong: [
      { choice: "b", hint: "(7, 4) switches the numbers. The x-coordinate (across) comes first, then the y-coordinate (up)." },
      { choice: "c", hint: "(6, 2) is the rain cloud. Find the point labeled Storm Eye." },
      { choice: "d", hint: "The Storm Eye is 4 across, but check how far up it is." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Write the probe steps", machine: "Probe Launcher", icon: "log", speaker: "nova",
    line: "Kai is training new crew members to drop probes. He needs the steps for plotting any ordered pair, like (2, 6), in the right order.",
    question: "Put the steps for graphing (2, 6) in order.",
    hint: "Every trip starts at the same place. The first number in the pair is used first.",
    meter: { supplies: 1, label: "Probes +1", story: "The new crew can drop probes too" },
    discovery: { id: "latlong", name: "Map grids", who: "Kai", fact: "Maps of Earth use a grid of lines called latitude and longitude. A pair of numbers can name any place on Earth, a lot like an ordered pair." },
    answer: { kind: "order", correct: ["origin", "right", "up", "plot"] },
    items: [
      { id: "up", text: "Move up 6, parallel to the y-axis." },
      { id: "plot", text: "Draw a dot and label it (2, 6)." },
      { id: "origin", text: "Start at the origin, (0, 0)." },
      { id: "right", text: "Move right 2, parallel to the x-axis." },
    ],
    rightFeedback: "Start at the origin, move right 2, move up 6, then plot. That's the process for any ordered pair!",
    wrong: [
      { position: 0, hint: "Every point on the grid starts from the same place: (0, 0)." },
      { position: 1, hint: "The first number, the x-coordinate, tells you how far to move across. Do that before you move up." },
      { position: 2, hint: "After moving across, the second number tells you how far to move up." },
      { position: 3, hint: "You only draw the dot after you finish both moves." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Probes on the edge", machine: "Probe Launcher", icon: "snap", speaker: "vega",
    line: "Surprise! The storm is spreading out. We need two probes right on the edges of the radar grid, sitting on the axes themselves.",
    question: "Part 1: Which axis do you move along for the x-coordinate? Part 2: Drop a probe at (0, 4). Part 3: Drop a probe at (6, 0).",
    parts: [
      { type: "choice", prompt: "The x-coordinate tells you to move parallel to which line?", choices: [
        { id: "a", text: "The x-axis, the number line that goes across" },
        { id: "b", text: "The y-axis, the number line that goes up" },
        { id: "c", text: "It doesn't tell you to move at all" },
      ] },
      { type: "point", prompt: "Drop a probe at (0, 4).", visual: { type: "coords", max: 8, pick: true, title: "Storm radar" } },
      { type: "point", prompt: "Drop a probe at (6, 0).", visual: { type: "coords", max: 8, pick: true, title: "Storm radar", points: [{ x: 0, y: 4, label: "Probe A" }] } },
    ],
    hint: "A 0 means you don't move that way at all. (0, 4) means move right 0, up 4.",
    meter: { heat: 10, label: "Storm tracking +10%", story: "The probes guard the edges of the storm" },
    discovery: { id: "thunder", name: "Thunder", who: "Nova", fact: "Light travels much faster than sound. That's why you see a flash of lightning before you hear the thunder." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "point", x: 0, y: 4 },
      { kind: "point", x: 6, y: 0 },
    ] },
    rightFeedback: "(0, 4) sits on the y-axis and (6, 0) sits on the x-axis. Both edges are covered!",
    wrong: [
      { step: 1, choice: "b", hint: "The y-coordinate is the one that moves you up. The x-coordinate moves you across." },
      { step: 1, choice: "c", hint: "The x-coordinate tells how far to move across from the origin." },
      { step: 2, point: { x: 4, y: 0 }, hint: "That's (4, 0). The first number is 0, so don't move across at all. Just move up 4." },
      { step: 2, point: { x: 4, y: 4 }, hint: "The first number is 0. Don't move right. Stay on the y-axis and move up 4." },
      { step: 3, point: { x: 0, y: 6 }, hint: "That's (0, 6). The first number is 6, so move right 6. The 0 means don't move up." },
      { step: 3, point: { x: 6, y: 6 }, hint: "Right 6 is correct. The second number is 0, so don't move up at all." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Does order matter?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Probe B goes at (2, 5). I\'ll put it at (5, 2). It\'s the same numbers, so it\'s the same spot!"',
    nova: 'Nova: "Not the same, Kai. (2, 5) means right 2, up 5. (5, 2) means right 5, up 2. Those are different places on the grid."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Try both on the grid. Does right 2, up 5 land in the same place as right 5, up 2?",
    meter: { heat: 5, label: "Storm tracking +5%", story: "Probe B goes to the right spot" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. The first number always tells how far to move across, and the second tells how far to move up. Switching them gives a different point." },
      { id: "B", text: "Nova, because 5 is bigger than 2." },
      { id: "C", text: "Kai. The numbers are the same, so the point is the same." },
      { id: "D", text: "Kai. You can move up or across first. It doesn't matter." },
    ],
    writtenPrompt: "Tell Kai in your own words why (2, 5) and (5, 2) are different points.",
    debateHints: {
      wrongWho: "Start at the origin. Go right 2, up 5. Now go back and go right 5, up 2. Did you land in the same place?",
      wrongReason: "Right person, check the reason. What does each number in an ordered pair tell you to do?",
      right: "Nova is right. In an ordered pair, the order matters!",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Fix Kai's probe", machine: "Repair", icon: "log", speaker: "nova",
    line: "Oops. Kai was supposed to drop Probe C at (2, 5), but the radar shows it somewhere else. It's measuring clear sky instead of the storm.",
    question: "Part 1: What went wrong? Part 2: Put Probe C where it belongs.",
    parts: [
      { type: "choice", prompt: "Look at where Kai's probe landed. What went wrong?", visual: { type: "coords", max: 8, title: "Storm radar", points: [{ x: 5, y: 2, label: "Kai's probe" }] }, choices: [
        { id: "a", text: "He switched the numbers. He moved right 5 and up 2, so he plotted (5, 2)." },
        { id: "b", text: "He started at 1 instead of the origin." },
        { id: "c", text: "He moved up 5 but forgot to move right." },
        { id: "d", text: "Nothing went wrong. (5, 2) is the same as (2, 5)." },
      ] },
      { type: "point", prompt: "Drop Probe C at (2, 5).", visual: { type: "coords", max: 8, pick: true, title: "Storm radar", points: [{ x: 5, y: 2, label: "Kai's probe" }] } },
    ],
    hint: "Kai's probe is 5 across and 2 up. The plan said (2, 5).",
    meter: { supplies: 1, label: "Probes +1", story: "Probe C is inside the storm" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "point", x: 2, y: 5 },
    ] },
    rightFeedback: "Fixed! Probe C is at (2, 5): right 2, up 5.",
    wrong: [
      { step: 1, choice: "b", hint: "Count from the origin. Kai's probe is exactly 5 across and 2 up. Which numbers did he use?" },
      { step: 1, choice: "c", hint: "Kai's probe isn't on the y-axis. He did move right. How far right, and how far up?" },
      { step: 1, choice: "d", hint: "Order matters! (5, 2) means right 5, up 2. (2, 5) means right 2, up 5." },
      { step: 2, point: { x: 5, y: 2 }, hint: "That's where Kai put it. Go across 2 first, then up 5." },
      { step: 2, point: { x: 2, y: 2 }, hint: "Right 2 is correct. The second number is 5, so move up 5." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "How far apart?", machine: "Radar Screen", icon: "trail", speaker: "kai",
    line: "Two probes are floating at the same height in a long storm cloud. Probe D is at (2, 6), and Probe E is at (7, 6).",
    question: "How many units apart are Probe D and Probe E?",
    unit: "units",
    visual: { type: "coords", max: 8, title: "Storm radar", points: [{ x: 2, y: 6, label: "Probe D" }, { x: 7, y: 6, label: "Probe E" }] },
    hint: "Both probes are 6 units up, so they're on the same line. Count the units across from 2 to 7.",
    meter: { heat: 5, label: "Storm tracking +5%", story: "The crew knows how wide the cloud is" },
    discovery: { id: "cumulonimbus", name: "Thunderstorm clouds", who: "Nova", fact: "Thunderstorm clouds are called cumulonimbus clouds. They can tower higher than Mount Everest, the tallest mountain on Earth." },
    answer: { kind: "number", value: 5 },
    rightFeedback: "7 − 2 = 5. The probes are 5 units apart.",
    wrong: [
      { value: 9, hint: "You added 2 + 7. Count the units from 2 to 7 instead, or subtract." },
      { value: 6, hint: "6 is how far up both probes are. How far apart are they going across?" },
      { value: 4, hint: "Count the jumps between the grid lines, not the lines themselves. From 2 to 7 is how many jumps?" },
      { value: 12, hint: "Both probes are at the same height, so only the x-coordinates change. How far is it from 2 to 7?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The hail pattern", machine: "Pattern Pad", icon: "grid", speaker: "nova",
    line: "The Pattern Pad tracks a hail cloud. Every hour it follows the rule y = x + 3, where x is the hour and y is how many units north it is.",
    question: "Use the rule to find y when x is 5. Then plot that point, (x, y), on the grid.",
    data: {
      title: "Hail cloud: y = x + 3",
      columns: ["Hour (x)", "Units north (y)"],
      rows: [["1", "4"], ["2", "5"], ["3", "6"], ["4", "7"], ["5", "?"]],
    },
    visual: { type: "coords", max: 10, pick: true, title: "Hail cloud track", points: [{ x: 1, y: 4 }, { x: 2, y: 5 }, { x: 3, y: 6 }, { x: 4, y: 7 }] },
    hint: "Add 3 to the x value: 5 + 3 = ? Then go right 5 and up that many.",
    meter: { supplies: 1, label: "Probes +1", story: "The hail cloud's next spot is marked" },
    discovery: { id: "hail", name: "Hail", who: "Nova", fact: "Hailstones grow when strong winds toss them up and down inside a storm cloud. Each trip adds another layer of ice." },
    answer: { kind: "point", x: 5, y: 8 },
    rightFeedback: "5 + 3 = 8, so the hail cloud will be at (5, 8).",
    wrong: [
      { point: { x: 8, y: 5 }, hint: "You switched the numbers. The hour (x) goes first: right 5, then up 8." },
      { point: { x: 5, y: 7 }, hint: "Use the rule. 5 + 3 is how much?" },
      { point: { x: 5, y: 15 }, hint: "The rule says add 3, not multiply." },
      { point: { x: 4, y: 7 }, hint: "That's the point for hour 4. Find the point for hour 5." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Where is the storm going?", machine: "Pattern Pad", icon: "quake", speaker: "vega",
    line: "Surprise, the big storm is moving! Nova tracked it for three hours. We need to know where it will be next so the sky creatures can get out of the way.",
    question: "Part 1: Find the missing number in the table. Part 2: Which rule matches the table? Part 3: Plot where the storm will be at hour 4.",
    data: {
      title: "The big storm's path",
      columns: ["Hour (x)", "Units north (y)"],
      rows: [["1", "2"], ["2", "4"], ["3", "?"], ["4", "?"]],
    },
    parts: [
      { type: "number", prompt: "The storm moves the same way every hour. How many units north is it at hour 3?", unit: "units north" },
      { type: "choice", prompt: "Which rule matches the table?", choices: [
        { id: "a", text: "y = 2x" },
        { id: "b", text: "y = x + 2" },
        { id: "c", text: "y = x + 1" },
        { id: "d", text: "y = 3x" },
      ] },
      { type: "point", prompt: "Plot where the storm will be at hour 4.", visual: { type: "coords", max: 10, pick: true, title: "Big storm track", points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }] } },
    ],
    hint: "Look at how y changes: 2, 4, ... Each y is double its x.",
    meter: { heat: 10, label: "Storm tracking +10%", story: "The sky creatures move out of the storm's way" },
    discovery: { id: "tracking", name: "Tracking hurricanes", who: "Kai", fact: "Forecasters plot a hurricane's position on a map every few hours. Connecting the points shows its path and helps them predict where it will go." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 6 },
      { kind: "choice", correct: "a" },
      { kind: "point", x: 4, y: 8 },
    ] },
    rightFeedback: "The rule is y = 2x, so at hour 4 the storm will be at (4, 8). Warning sent!",
    wrong: [
      { step: 1, value: 5, hint: "The y values go 2, 4, ... They jump by 2 each hour, not 1." },
      { step: 1, value: 8, hint: "8 is too far. From 4, add the same jump again: 4 + 2." },
      { step: 2, choice: "b", hint: "Test it with hour 1: 1 + 2 = 3, but the table says 2. Try another rule." },
      { step: 2, choice: "c", hint: "Test it with hour 2: 2 + 1 = 3, but the table says 4. Try another rule." },
      { step: 2, choice: "d", hint: "Test it with hour 1: 3 × 1 = 3, but the table says 2. Try another rule." },
      { step: 3, point: { x: 8, y: 4 }, hint: "You switched the numbers. The hour (x) goes first: right 4, then up 8." },
      { step: 3, point: { x: 4, y: 6 }, hint: "Use the rule: 2 × 4 = ? Go up that many." },
      { step: 3, point: { x: 4, y: 10 }, hint: "Each hour the storm moves up 2. From 6 at hour 3, where is it at hour 4?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Sort the edge probes", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "The crew dropped a whole net of probes. Some landed right on the axes, and some landed out in the sky.",
    question: "Sort each probe: on the x-axis, on the y-axis, or not on an axis.",
    hint: "A point on the x-axis hasn't moved up at all, so its y-coordinate is 0. A point on the y-axis hasn't moved across, so its x-coordinate is 0.",
    meter: { supplies: 1, label: "Probes +1", story: "The probe net is mapped" },
    answer: { kind: "sort", bins: { p1: "xaxis", p2: "yaxis", p3: "none", p4: "yaxis", p5: "xaxis", p6: "none" } },
    rightFeedback: "Points with y = 0 are on the x-axis. Points with x = 0 are on the y-axis!",
    sort: {
      bins: [
        { id: "xaxis", label: "On the x-axis" },
        { id: "yaxis", label: "On the y-axis" },
        { id: "none", label: "Not on an axis" },
      ],
      items: [
        { id: "p1", label: "(6, 0)" },
        { id: "p2", label: "(0, 4)" },
        { id: "p3", label: "(3, 3)" },
        { id: "p4", label: "(0, 9)" },
        { id: "p5", label: "(8, 0)" },
        { id: "p6", label: "(2, 5)" },
      ],
    },
    wrong: [
      { item: "p1", hint: "(6, 0) moves right 6 and up 0. It stays on the line that goes across." },
      { item: "p5", hint: "(8, 0) moves right 8 and up 0. Which axis goes across?" },
      { item: "p2", hint: "(0, 4) moves right 0 and up 4. It stays on the line that goes up." },
      { item: "p4", hint: "(0, 9) moves right 0 and up 9. Which axis goes up?" },
      { item: "p3", hint: "(3, 3) moves right 3 and up 3. Is either number 0?" },
      { item: "p6", hint: "(2, 5) moves right 2 and up 5. Is either number 0?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The hail cloud's edge", machine: "Radar Screen", icon: "dial", speaker: "nova",
    line: "A hail cloud is hugging the edge of the radar. Its dot sits right on one of the number lines.",
    question: "Where is the Hail Cloud?",
    visual: { type: "coords", max: 8, title: "Storm radar", points: [{ x: 0, y: 6, label: "Hail Cloud" }, { x: 5, y: 3, label: "Rain cloud" }] },
    hint: "Count from the origin. How far across is the Hail Cloud? How far up?",
    meter: { heat: 5, label: "Storm tracking +5%", story: "The hail cloud is on the map" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "On the y-axis, at (0, 6)" },
      { id: "b", text: "On the x-axis, at (6, 0)" },
      { id: "c", text: "On the y-axis, at (6, 0)" },
      { id: "d", text: "At the origin, (0, 0)" },
    ],
    rightFeedback: "Right! It moved 0 across and 6 up, so it's on the y-axis at (0, 6).",
    wrong: [
      { choice: "b", hint: "The x-axis goes across. The Hail Cloud is on the line that goes up. Which number comes first?" },
      { choice: "c", hint: "It is on the y-axis. Check the order: the across number comes first, and it moved 0 across." },
      { choice: "d", hint: "The origin is the corner where the axes meet. The Hail Cloud is higher up than that." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "The rain rule", machine: "Pattern Pad", icon: "water", speaker: "kai",
    line: "The rain probes follow the rule y = 3x. The x value is the hour, and y is how many millimeters of rain have fallen.",
    question: "Pick every ordered pair (x, y) that fits the rule y = 3x.",
    hint: "For each pair, multiply the first number by 3. Does it equal the second number?",
    meter: { supplies: 1, label: "Probes +1", story: "The rain graph is ready to plot" },
    answer: { kind: "multi", correct: ["p0", "p1", "p2", "p3"] },
    items: [
      { id: "p0", text: "(0, 0)" },
      { id: "p1", text: "(1, 3)" },
      { id: "p2", text: "(2, 6)" },
      { id: "p3", text: "(3, 9)" },
      { id: "s1", text: "(3, 1)" },
      { id: "s2", text: "(2, 5)" },
    ],
    rightFeedback: "3 × 0 = 0, 3 × 1 = 3, 3 × 2 = 6, and 3 × 3 = 9. All four fit y = 3x!",
    wrong: [
      { pick: "s1", hint: "(3, 1) switches the numbers. For x = 3, y should be 3 × 3." },
      { pick: "s2", hint: "(2, 5) fits y = x + 3, not y = 3x. What is 3 × 2?" },
      { missing: true, hint: "There are more pairs that fit. Don't forget x = 0: 3 × 0 = 0." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Follow the lightning", machine: "Probe Launcher", icon: "relay", speaker: "nova",
    line: "Lightning just flashed! Commander Vega sends the directions: \"Start at the origin. Move right 8. Then move up 1. Drop the probe there.\"",
    question: "Follow Vega's directions and drop the probe.",
    visual: { type: "coords", max: 10, pick: true, title: "Storm radar" },
    hint: "Move right first, along the x-axis. Then move up, parallel to the y-axis.",
    meter: { heat: 10, label: "Storm tracking +10%", story: "The probe records the lightning" },
    discovery: { id: "lightning", name: "Lightning", who: "Kai", fact: "Lightning flashes somewhere on Earth more than 40 times every second." },
    answer: { kind: "point", x: 8, y: 1 },
    rightFeedback: "Right 8, up 1. The probe is at (8, 1)!",
    wrong: [
      { point: { x: 1, y: 8 }, hint: "That's (1, 8). Vega said move right 8 first, then up 1." },
      { point: { x: 8, y: 0 }, hint: "You moved right 8. Now move up 1." },
      { point: { x: 9, y: 1 }, hint: "Count the jumps from 0, not the lines. Right 8 lands on the 8." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Save Sky Village", machine: "Pattern Pad", icon: "snap", speaker: "vega",
    line: "This is it! A super storm is heading across Cloudreach. It follows the rule y = x + 2, where x is the hour and y is how many units north it is. Sky Village floats at (6, 8).",
    question: "Part 1: Finish the table for hour 2. Part 2: Finish the table for hour 4. Part 3: Plot the storm at hour 5. Part 4: Will the storm reach Sky Village?",
    data: {
      title: "Super storm: y = x + 2",
      columns: ["Hour (x)", "Units north (y)"],
      rows: [["0", "2"], ["1", "3"], ["2", "?"], ["3", "5"], ["4", "?"]],
    },
    parts: [
      { type: "number", prompt: "Use the rule. What is y when x is 2?", unit: "units north" },
      { type: "number", prompt: "Use the rule. What is y when x is 4?", unit: "units north" },
      { type: "point", prompt: "Plot where the storm will be at hour 5.", visual: { type: "coords", max: 10, pick: true, title: "Super storm track", points: [{ x: 0, y: 2 }, { x: 1, y: 3 }, { x: 2, y: 4 }, { x: 3, y: 5 }, { x: 4, y: 6 }, { x: 6, y: 8, label: "Sky Village" }] } },
      { type: "choice", prompt: "Sky Village is at (6, 8). Will the storm reach it if it keeps following the rule?", choices: [
        { id: "a", text: "Yes. At hour 6, y = 6 + 2 = 8, so the storm will be at (6, 8)." },
        { id: "b", text: "No. The storm only goes up to 6 units north." },
        { id: "c", text: "No. (6, 8) would have to be (8, 6) to be on the path." },
        { id: "d", text: "Yes, because every point on the grid is in the storm's path." },
      ] },
    ],
    hint: "Add 2 to each hour to get y. Then keep the pattern going.",
    meter: { heat: 15, label: "Storm tracking +15%", story: "Sky Village is warned in time" },
    discovery: { id: "rainbow", name: "Rainbows", who: "Nova", fact: "A rainbow forms when sunlight shines through raindrops. The drops bend the light and split it into its colors." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 4 },
      { kind: "number", value: 6 },
      { kind: "point", x: 5, y: 7 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The storm follows y = x + 2 right to (6, 8). Sky Village got the warning in time!",
    wrong: [
      { step: 1, value: 3, hint: "3 is the y for hour 1. Add 2 to hour 2." },
      { step: 1, value: 2, hint: "2 is the hour. The rule says add 2 to it." },
      { step: 2, value: 8, hint: "The rule says add 2, not multiply by 2. What is 4 + 2?" },
      { step: 2, value: 5, hint: "5 is the y for hour 3. What is 4 + 2?" },
      { step: 3, point: { x: 7, y: 5 }, hint: "You switched the numbers. The hour (x) goes first: right 5, then up 7." },
      { step: 3, point: { x: 5, y: 6 }, hint: "Use the rule: 5 + 2 = ? Go up that many." },
      { step: 3, point: { x: 6, y: 8 }, hint: "That's Sky Village. Plot the storm at hour 5 first." },
      { step: 4, choice: "b", hint: "The pattern keeps going. What is y when x is 6?" },
      { step: 4, choice: "c", hint: "Test (6, 8) with the rule: 6 + 2 = 8. Does it fit?" },
      { step: 4, choice: "d", hint: "Only points that fit the rule are on the path. Test (6, 8): does 6 + 2 = 8?" },
    ],
  },
};

export default {
  id: "MA.5.8C-XP",
  standard: "MA.5.8C-XP",
  engine: "expedition_station",
  title: "The Radar Grid",
  planet: "Cloudreach",
  outpost: "Sky Reef · storm season",
  grade: 5,
  subject: "Math",
  teks: "5.8C",
  supportingTeks: ["5.8A", "5.8B", "5.4C"],
  skillsChip: "5.8C · Graph ordered pairs",
  iCan: "I can graph ordered pairs in the first quadrant, including points from a number pattern or an input-output table. I can describe how to plot a point.",
  blurb: "Storm season has come to the floating reefs of Cloudreach. The crew drops weather probes on the storm radar grid and tracks where the big storm is heading.",
  mission: "Drop weather probes on the radar grid and track the super storm's path.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.8 · CLOUDREACH STORM RADAR",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Storm tracking", heatUnit: "%", supplies: "Probes", suppliesUnit: "probes" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Storm season has reached the sky reef on Cloudreach.",
    "Our storm radar is a grid, and every spot on it has an ordered pair. We need weather probes dropped in exactly the right places.",
    "Help Kai and Nova plot the probes and track the storm before it reaches the sky creatures. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Set up the radar", "Act 2 · Track the storm", "Act 3 · Save Sky Village"],
    completes: [
      "The radar is set up and the first probes are in place, {firstName}!",
      "We know where the big storm is heading, {firstName}!",
      "Sky Village is safe, {firstName}! You tracked the super storm across the whole grid.",
    ],
    teasers: [
      "Next on Cloudreach: the big storm starts to move. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: a super storm is heading for Sky Village. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The big storm is on the move, and one of Kai's probes landed in the wrong spot.",
      "Let's fix it and figure out where the storm is going.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. A super storm is crossing Cloudreach, and Sky Village is in the area.",
      "Use the radar grid and the storm's pattern to find out if the village is in danger.",
    ],
  }),
  tasks,
};
