// Expedition Station — The Rival Pilots (ELA.4.8B-XP)
// Grade 4 · ELAR · Cloudreach. Main standard 4.8B (explain the interactions of
// the characters and the changes they undergo). Also practices 4.8D (influence
// of the setting on the plot), 4.8C (plot elements, turning point), 4.6F
// (inference), 4.7C (text evidence), 4.3B (context clues), 4.11D (editing).
// All passages are original, written for this quest: one short story told in
// four parts (A–D), Tobin's pilot journal (E), Nova's crew log about the race
// course (F), and Kai's race report with mistakes (G).
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "The Sky Race, Part 1: The Launch Dock", genre: "Realistic fiction (story, part 1)" }, [
    [
      "Every year, pilots from all over Cloudreach gather for the Sky Race.",
      "The course winds through the Coral Clouds, where giant reefs float on the wind like huge sponges.",
      "Between the reefs run gust lanes, narrow rivers of fast wind that can push a sky-skiff twice as fast or flip it upside down.",
    ],
    [
      "Mira Dash had won the junior race two years in a row.",
      "She strutted across the launch dock with her goggles pushed up on her head, waving at the crowd.",
      "\"I don't need to study the wind,\" she told everyone. \"The wind should study me!\"",
    ],
    [
      "At the far end of the dock, Tobin Reyes checked the straps on his skiff for the third time.",
      "He had drawn a careful map of every gust lane on the course.",
      "When a reporter asked him a question, his face turned red, and he only nodded.",
    ],
    [
      "Mira hurried past and bumped his map with her elbow.",
      "It fluttered off the dock and sank into the clouds below.",
      "\"Oops,\" she said, and she laughed.",
      "Tobin opened his mouth, then closed it again.",
      "He said nothing at all.",
    ],
  ]),
  B: passage("B", { title: "The Sky Race, Part 2: The Storm", genre: "Realistic fiction (story, part 2)" }, [
    [
      "The starting horn blew, and twelve skiffs shot into the sky.",
      "Mira dove straight into the fastest gust lane.",
      "She zoomed ahead of everyone, whooping into the wind.",
    ],
    [
      "Tobin stayed in the slow, steady air along the edge of the reef.",
      "Without his map, he had to fly by memory, watching which way the cloud-coral leaned.",
      "When the coral leans hard, the wind is strong, he reminded himself.",
    ],
    [
      "Halfway through the course, the sky turned the dark purple of a bruise.",
      "The air grew cold, and the cloud-coral began to shake.",
      "A storm was rolling in from the west.",
      "The judges' horn blew three times, the signal for every pilot to land at once.",
    ],
    [
      "Mira did not turn back.",
      "\"A little wind can't stop a champion,\" she said.",
      "She pushed deeper into the gust lane just as the storm swept into it.",
      "A wall of wind slammed her skiff sideways, and her steering fin snapped.",
    ],
  ]),
  C: passage("C", { title: "The Sky Race, Part 3: Under the Reef", genre: "Realistic fiction (story, part 3)" }, [
    [
      "Tobin saw Mira's skiff spinning toward the dark reef.",
      "Every part of him wanted to fly back to the safe, quiet dock.",
      "Instead, he turned his skiff toward the storm.",
    ],
    [
      "He pulled up beside her and tossed her a tow line.",
      "\"Hold on!\" Mira shouted. \"I'll steer us out through the gust lane!\"",
      "\"No!\" Tobin shouted back, louder than he had ever spoken in his life.",
      "\"The storm is inside the gust lane. We have to go under the reef, where the air is calm!\"",
    ],
    ["Mira stared at him.", "For once, she did not argue.", "\"Okay,\" she said. \"You lead.\""],
    [
      "Tobin guided them down beneath the floating reef.",
      "The thick coral blocked the worst of the wind like a giant umbrella.",
      "Slowly and carefully, the two skiffs drifted home through the calm air below.",
    ],
  ]),
  D: passage("D", { title: "The Sky Race, Part 4: The Next Morning", genre: "Realistic fiction (story, part 4)" }, [
    ["The judges stopped the race when the storm hit, so no one won the Sky Race that year."],
    [
      "The next morning, Mira found Tobin at the launch dock.",
      "She held out a new map, one she had drawn herself.",
      "\"I asked the old pilots about the wind all night,\" she said. \"I should have listened to you. And I'm sorry about your map.\"",
    ],
    [
      "Tobin smiled.",
      "When the reporter came by, he did not just nod this time.",
      "\"Mira is the bravest pilot I know,\" he said in a clear voice. \"Next year, we're going to study the course together.\"",
    ],
    ["Mira grinned.", "\"And next year,\" she added, \"I'm still going to win.\""],
  ]),
  E: passage("E", { title: "Tobin's Pilot Journal", genre: "Journal entry" }, [
    [
      "Today I shouted at the fastest pilot in Cloudreach.",
      "I didn't plan to.",
      "The words just burst out, because Mira was about to fly straight into the storm.",
    ],
    [
      "My whole life, I've stayed quiet even when I knew the answer.",
      "I was afraid people would laugh at me.",
      "Today I learned that sometimes staying quiet is the dangerous choice.",
    ],
    ["Mira listened to me.", "I think that surprised both of us."],
  ]),
  F: passage("F", { title: "Nova's Crew Log: The Coral Clouds Course", genre: "Crew log (informational)" }, [
    [
      "The Sky Race course runs through the Coral Clouds, the thickest reefs on Cloudreach.",
      "Pilots have raced here for more than a hundred years, and the old pilots still teach the young ones how to read the wind.",
    ],
    [
      "On warm afternoons, warm air rises off the reefs, and storms often build on the west side of the course.",
      "That is why the race usually starts early in the morning.",
      "This year, a broken starting horn delayed the race until the middle of the afternoon.",
    ],
    [
      "Under the biggest reefs, the air stays much calmer, even in a storm.",
      "Old pilots call that space the quiet shelf.",
      "A pilot who knows the course can hide there until the wind dies down.",
    ],
  ]),
  G: {
    id: "G",
    title: "Kai's Race Report",
    genre: "Report (has mistakes)",
    ...editText("G", "Mira and Tobin {was} both in the Sky Race. A storm {brake} Mira's steering fin. {Mira} towed the broken skiff under the reef. {them} both landed safely.", {
      was: ["were", "is"],
      brake: ["broke", "breaked"],
      Mira: ["Tobin", "Nova"],
      them: ["They", "Them"],
    }),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Strut check", machine: "Decipher", icon: "static", speaker: "nova", passage: ["A"],
    line: "The Sky Race story came through the radio. One word is fuzzy on my screen. Help me clear it.",
    question: "Read Part 1. \"She strutted across the launch dock with her goggles pushed up on her head, waving at the crowd.\" What does strutted mean?",
    hint: "Look at the clues around it. She is waving at the crowd and bragging. How would a person like that walk?",
    meter: { heat: 15, label: "Tailwind +15%", story: "The story comes in clearly" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Tiptoed slowly and quietly" },
      { id: "b", text: "Walked in a proud, showy way" },
      { id: "c", text: "Tripped and almost fell" },
      { id: "d", text: "Ran away in a hurry" },
    ],
    rightFeedback: "Cleared! Strutting is walking in a proud, showy way, just like Mira.",
    wrong: [
      { choice: "a", hint: "She is waving at the crowd. Is she trying to be quiet?" },
      { choice: "c", hint: "Nothing in the sentence says she fell. Read what she says next. How does she feel about herself?" },
      { choice: "d", hint: "She is waving at the crowd, not running from it. Think about how a proud person walks." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The champion's words", machine: "Trait Scanner", icon: "scan", speaker: "kai", passage: ["A"],
    line: "Mira is the two-time champ. I think she's pretty sure of herself. Can you prove it?",
    question: "Mira is proud. Highlight the sentence where Mira's own words show that she is proud.",
    hint: "Look for Mira talking. What does she say about the wind?",
    meter: { heat: 10, label: "Tailwind +10%", story: "The trait scanner locks on" },
    discovery: { id: "albatross", name: "Albatross wings", who: "Nova", fact: "The wandering albatross has the longest wings of any bird alive, over 10 feet from tip to tip. It can glide over the ocean for hours without flapping." },
    answer: { kind: "highlight", groups: [["A2.3"]] },
    rightFeedback: "Locked on! \"The wind should study me!\" Only a very proud pilot would say that.",
    wrong: [
      { sentence: "A2.1", hint: "That tells what Mira did before. Find a sentence where Mira is talking." },
      { sentence: "A2.2", hint: "That shows how she walks. The question asks for her own words. Look for quotation marks." },
      { sentence: "A4.3", hint: "Mira is talking there, but \"Oops\" shows she is careless. Which words show she thinks she's better than the wind?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The quiet pilot", machine: "Trait Scanner", icon: "crew", speaker: "nova", passage: ["A"],
    line: "Now let's meet the other pilot. Tobin is very different from Mira.",
    question: "Part 1: Which word best describes Tobin at the start of the race? Part 2: Highlight a sentence that shows it.",
    parts: [
      { type: "choice", prompt: "Which word best describes Tobin?", choices: [
        { id: "a", text: "Careful" },
        { id: "b", text: "Reckless" },
        { id: "c", text: "Bossy" },
        { id: "d", text: "Lazy" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows this trait.", passage: "A" },
    ],
    hint: "What does Tobin do before the race to get ready?",
    meter: { supplies: 1, label: "Pilot badges +1", story: "Nova pins Tobin's badge on the board" },
    discovery: { id: "hollowbones", name: "Light bones", who: "Kai", fact: "Many birds have hollow bones with thin braces inside. Their bones are strong but light, which helps them fly." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A3.1", "A3.2"]] },
    ] },
    rightFeedback: "Right! Tobin checks his straps three times and maps every gust lane. He is careful.",
    wrong: [
      { step: 1, choice: "b", hint: "Reckless means not thinking about danger. Who checks the straps three times?" },
      { step: 1, choice: "c", hint: "Tobin barely talks at all. Does that sound bossy?" },
      { step: 1, choice: "d", hint: "Drawing a map of every gust lane takes a lot of work. Is that lazy?" },
      { step: 2, sentence: "A3.3", hint: "That shows Tobin is shy. Find a sentence that shows how he gets ready." },
      { step: 2, sentence: "A4.5", hint: "That shows he is quiet. Which sentence shows him getting ready carefully?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The lost map", machine: "Cause Tracker", icon: "trail", speaker: "vega", passage: ["A", "B"],
    line: "One small bump on the dock changed the whole race. Track what it caused.",
    question: "Mira knocks Tobin's map off the dock. How does this affect Tobin during the race in Part 2?",
    hint: "Read the second paragraph of Part 2. What does Tobin have to do without his map?",
    meter: { heat: 10, label: "Tailwind +10%", story: "The tracker finds the link" },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "He quits the race and goes home." },
      { id: "b", text: "He flies into the fastest gust lane to catch up." },
      { id: "c", text: "He has to fly by memory and watch the cloud-coral to find the wind." },
      { id: "d", text: "He borrows Mira's map." },
    ],
    rightFeedback: "Yes! Without his map, Tobin reads the cloud-coral to know where the wind is strong.",
    wrong: [
      { choice: "a", hint: "Tobin is still flying in Part 2. Where does he fly?" },
      { choice: "b", hint: "That's what Mira does. What does Tobin do?" },
      { choice: "d", hint: "Mira doesn't have a map at the start. What does Tobin watch instead?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Storm on the course", machine: "Storm Tracker", icon: "quake", speaker: "vega", passage: ["B"],
    line: "Surprise! A real gust just rattled our station windows. Cloudreach weather is no joke. Let's see what the storm did to the race.",
    question: "Part 1: What does the storm cause to happen to Mira? Part 2: Highlight the sentence that shows the storm causing the problem. Part 3: Why does Mira keep flying after the judges' signal?",
    parts: [
      { type: "choice", prompt: "What does the storm cause to happen?", choices: [
        { id: "a", text: "The storm pushes Mira across the finish line first." },
        { id: "b", text: "Wind slams Mira's skiff sideways and snaps her steering fin." },
        { id: "c", text: "The storm blows Tobin's map back to him." },
        { id: "d", text: "The storm makes Mira turn around and land." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows the storm causing the problem.", passage: "B" },
      { type: "choice", prompt: "Why does Mira keep flying?", choices: [
        { id: "a", text: "She didn't hear the horn." },
        { id: "b", text: "She wants to help Tobin." },
        { id: "c", text: "She thinks she is too good of a pilot for the storm to stop her." },
        { id: "d", text: "Her skiff is broken and can't turn." },
      ] },
    ],
    hint: "The storm is part of the setting. Find the sentence where the wind does something to Mira's skiff. Then read what Mira says right after the horn.",
    meter: { heat: 10, label: "Tailwind +10%", story: "The crew spots Mira's spinning skiff" },
    discovery: { id: "beaufort", name: "Measuring wind", who: "Kai", fact: "Sailors and weather watchers use the Beaufort scale to describe wind. It goes from 0, which means calm, up to 12, which means hurricane-force wind." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["B4.4"]] },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Great reading! The storm snapped Mira's fin, and her pride kept her in the gust lane.",
    wrong: [
      { step: 1, choice: "a", hint: "Read the last sentence of Part 2. Does Mira finish the race?" },
      { step: 1, choice: "c", hint: "The map fell into the clouds in Part 1. It doesn't come back. What happens to Mira's skiff?" },
      { step: 1, choice: "d", hint: "Part 2 says, \"Mira did not turn back.\" What happens to her skiff?" },
      { step: 2, sentence: "B3.3", hint: "That tells the storm is coming. Find the sentence where the storm hurts Mira's skiff." },
      { step: 2, sentence: "B4.3", hint: "Close! That's Mira's choice. Which sentence shows what the wind does to her skiff?" },
      { step: 2, sentence: "B3.2", hint: "That shows the storm getting close. What does the wind do to Mira?" },
      { step: 3, choice: "a", hint: "She answers the horn: \"A little wind can't stop a champion.\" What does that tell you?" },
      { step: 3, choice: "b", hint: "Tobin isn't near Mira yet. Read what Mira says after the horn." },
      { step: 3, choice: "d", hint: "Her fin snaps AFTER she keeps going. Read what she says first." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Two pilots, two bins", machine: "Trait Sorter", icon: "cells", speaker: "kai", passage: ["A", "B"],
    line: "I built a sorter with two bins, one for each pilot. Help me load it with the right actions.",
    question: "Sort each action: did Mira do it, or did Tobin?",
    hint: "Mira is proud and rushes ahead. Tobin is careful and quiet. Check Parts 1 and 2.",
    meter: { supplies: 1, label: "Pilot badges +1", story: "Kai's sorter blinks green" },
    discovery: { id: "geese", name: "Flying in a V", who: "Nova", fact: "Geese often fly in a V shape. Each goose gets a little lift from the air swirling off the wings of the goose in front, so the flock saves energy." },
    answer: { kind: "sort", bins: { t1: "mira", t2: "tobin", t3: "mira", t4: "tobin", t5: "mira", t6: "tobin" } },
    sort: {
      bins: [
        { id: "mira", label: "Mira (proud, reckless)" },
        { id: "tobin", label: "Tobin (careful, shy)" },
      ],
      items: [
        { id: "t1", label: "Brags that the wind should study her" },
        { id: "t2", label: "Checks the straps three times" },
        { id: "t3", label: "Laughs when the map falls" },
        { id: "t4", label: "Turns red and only nods" },
        { id: "t5", label: "Dives into the fastest gust lane" },
        { id: "t6", label: "Stays in the slow, steady air" },
      ],
    },
    rightFeedback: "Sorted! Mira rushes and brags. Tobin gets ready carefully and keeps quiet.",
    wrong: [
      { item: "t1", hint: "Who said, \"The wind should study me!\"?" },
      { item: "t2", hint: "Which pilot is careful before the race?" },
      { item: "t3", hint: "Who said \"Oops\" and laughed?" },
      { item: "t4", hint: "Which pilot is too shy to answer the reporter?" },
      { item: "t5", hint: "Who zoomed ahead of everyone, whooping into the wind?" },
      { item: "t6", hint: "Which pilot stays safe at the edge of the reef?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Into the storm", machine: "Motive Reader", icon: "crew", speaker: "nova", passage: ["C"],
    line: "Tobin could have flown home. He didn't. I want to know why.",
    question: "Part 1: Why does Tobin turn his skiff toward the storm? Part 2: Highlight the sentence that shows this choice was hard for him.",
    parts: [
      { type: "choice", prompt: "Why does Tobin turn toward the storm?", choices: [
        { id: "a", text: "He wants to pass Mira and win the race." },
        { id: "b", text: "He sees Mira is in danger and wants to help her, even though he is scared." },
        { id: "c", text: "He wants to find his lost map." },
        { id: "d", text: "He likes flying in storms." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows the choice was hard.", passage: "C" },
    ],
    hint: "What does Tobin see right before he turns? What did every part of him want to do?",
    meter: { heat: 5, label: "Tailwind +5%", story: "Tobin's skiff heads into the wind" },
    discovery: { id: "thermals", name: "Riding warm air", who: "Kai", fact: "Hawks and eagles often circle inside thermals, columns of warm rising air. The rising air lifts them higher without flapping." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["C1.2"]] },
    ] },
    rightFeedback: "Yes! Tobin wanted to fly home, but he went to help Mira anyway.",
    wrong: [
      { step: 1, choice: "a", hint: "The judges already told everyone to land. Is Tobin thinking about winning?" },
      { step: 1, choice: "c", hint: "The map is gone. Read the first sentence of Part 3. What does Tobin see?" },
      { step: 1, choice: "d", hint: "Every part of him wanted to go back to the safe dock. Does he like storms?" },
      { step: 2, sentence: "C1.3", hint: "That shows what he did. Which sentence shows what he WANTED to do instead?" },
      { step: 2, sentence: "C1.1", hint: "That shows what he saw. Which sentence shows he felt scared?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Why the storm hit", machine: "Weather Log", icon: "dial", speaker: "nova", passage: ["F", "B"],
    line: "I've been studying the race course. The setting explains a lot about what went wrong.",
    question: "Part 1: Read Nova's crew log. Why did the storm hit during the race this year? Part 2: Highlight TWO sentences that support your answer.",
    parts: [
      { type: "choice", prompt: "Why did the storm hit during the race?", choices: [
        { id: "a", text: "Storms often build on warm afternoons, and this year the race was delayed until the afternoon." },
        { id: "b", text: "Mira flew too fast and made the storm." },
        { id: "c", text: "Storms only happen during the Sky Race." },
        { id: "d", text: "The old pilots forgot to warn anyone." },
      ] },
      { type: "highlight", prompt: "Highlight two sentences that support your answer.", passage: "F", count: 2 },
    ],
    hint: "When do storms often build? When did the race start this year?",
    meter: { supplies: 1, label: "Pilot badges +1", story: "Nova adds the log to the race file" },
    discovery: { id: "fog", name: "Fog", who: "Nova", fact: "Fog is a cloud that forms down low, touching the ground. Walking through fog is walking through a cloud." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["F2.1"], ["F2.3"]] },
    ] },
    rightFeedback: "Right! Afternoon storms plus a late start put the storm right in the middle of the race.",
    wrong: [
      { step: 1, choice: "b", hint: "Pilots can't make storms. What does the log say about warm afternoons?" },
      { step: 1, choice: "c", hint: "The log says storms often build on warm afternoons. What was different about this year's start time?" },
      { step: 1, choice: "d", hint: "The log doesn't say that. What delayed the race?" },
      { step: 2, sentence: "F2.2", hint: "That tells when the race USUALLY starts. Which sentence tells what happened THIS year?" },
      { step: 2, sentence: "F3.1", hint: "That explains a safe place to hide, not why the storm hit during the race." },
      { step: 2, sentence: "F1.1", hint: "That tells where the course is. Find one sentence about storms and one about the start time." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The shout", machine: "Interaction Meter", icon: "relay", speaker: "vega", passage: ["C"],
    line: "Something big happened between these two pilots in the storm. Show me how one changed the other.",
    question: "Part 1: How does Tobin's shout affect Mira? Part 2: Highlight a sentence that shows how Mira reacts.",
    parts: [
      { type: "choice", prompt: "How does Tobin's shout affect Mira?", choices: [
        { id: "a", text: "She gets angry and flies off alone." },
        { id: "b", text: "She laughs at him, just like on the dock." },
        { id: "c", text: "She is surprised, stops arguing, and lets him lead." },
        { id: "d", text: "She lets go of the tow line." },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows how Mira reacts.", passage: "C" },
    ],
    hint: "Read Part 3, paragraph 3. What does Mira do, and what does she say?",
    meter: { heat: 5, label: "Tailwind +5%", story: "The two skiffs dive under the reef together" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "c" },
      { kind: "highlight", groups: [["C3.1", "C3.2", "C3.3"]] },
    ] },
    rightFeedback: "Yes! Tobin speaks up, and for once Mira listens: \"You lead.\"",
    wrong: [
      { step: 1, choice: "a", hint: "The two skiffs drift home together. Did Mira fly off alone?" },
      { step: 1, choice: "b", hint: "That happened on the dock in Part 1. What does Mira say this time?" },
      { step: 1, choice: "d", hint: "They drift home together, so she held on. What does she say to Tobin?" },
      { step: 2, sentence: "C2.2", hint: "That's what Mira says BEFORE Tobin shouts. What does she do after?" },
      { step: 2, sentence: "C2.3", hint: "That's Tobin's shout. Find Mira's reaction." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Scrambled race recorder", machine: "Event Rebuilder", icon: "snap", speaker: "kai", passage: ["A", "B", "C", "D"],
    line: "Surprise! Lightning static scrambled the race recorder. The events are all mixed up, and the judges need them back in order.",
    question: "Part 1: Put the events in order. Part 2: Which event is the turning point, when both pilots begin to change? Part 3: How does the setting help the pilots get home safely?",
    parts: [
      { type: "order", prompt: "Put the events in order, first to last.", items: [
        { id: "shout", text: "Tobin shouts that they must fly under the reef." },
        { id: "map", text: "Mira knocks Tobin's map into the clouds." },
        { id: "newmap", text: "Mira gives Tobin a new map she drew." },
        { id: "dive", text: "Mira dives into the fastest gust lane." },
        { id: "storm", text: "The storm snaps Mira's steering fin." },
      ] },
      { type: "choice", prompt: "Which event is the turning point for both pilots?", choices: [
        { id: "a", text: "The starting horn blows." },
        { id: "b", text: "Tobin shouts his plan, and Mira says, \"You lead.\"" },
        { id: "c", text: "Mira's map falls off the dock." },
        { id: "d", text: "The judges stop the race." },
      ] },
      { type: "choice", prompt: "How does the setting help the pilots get home?", choices: [
        { id: "a", text: "The gust lane pushes them home fast." },
        { id: "b", text: "The storm stops as soon as Tobin arrives." },
        { id: "c", text: "The thick floating reef blocks the worst of the wind, so the air under it is calm." },
        { id: "d", text: "The cloud-coral catches Mira's broken fin." },
      ] },
    ],
    hint: "The turning point is the moment when things start to go a new way for both characters. For Part 3, reread the last paragraph of Part 3 of the story.",
    meter: { heat: 10, label: "Tailwind +10%", story: "The race recorder plays back in order" },
    discovery: { id: "wright", name: "The first airplane flight", who: "Kai", fact: "In 1903, Orville and Wilbur Wright made the first powered airplane flight near Kitty Hawk, North Carolina. The first flight lasted only 12 seconds." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["map", "dive", "storm", "shout", "newmap"] },
      { kind: "choice", correct: "b" },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Recorder fixed! Tobin speaks up and Mira listens. That moment changes both of them, and the reef keeps them safe.",
    wrong: [
      { step: 1, position: 0, hint: "What happens on the dock before the race even starts?" },
      { step: 1, position: 1, hint: "After the horn blows, what does Mira do first?" },
      { step: 1, position: 2, hint: "The storm has to hit Mira before Tobin can come help her." },
      { step: 1, position: 3, hint: "Tobin shouts during the storm. The new map comes the next morning." },
      { step: 2, choice: "a", hint: "Nobody has changed yet when the horn blows. When does Tobin speak up and Mira listen?" },
      { step: 2, choice: "c", hint: "That's Tobin's map, and it happens at the beginning. When do both pilots start acting differently?" },
      { step: 2, choice: "d", hint: "The judges stopping the race doesn't change the pilots. When does Mira first listen to Tobin?" },
      { step: 3, choice: "a", hint: "Tobin said the storm is INSIDE the gust lane. Where do they fly instead?" },
      { step: 3, choice: "b", hint: "The story doesn't say the storm stops. What blocks the wind?" },
      { step: 3, choice: "d", hint: "Read the last paragraph of Part 3. What does the thick coral do to the wind?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Tobin finds his voice", machine: "Change Tracker", icon: "trail", speaker: "nova", passage: ["A", "C", "D"],
    line: "Tobin at the end of the story doesn't sound like Tobin at the start. Let's track the change.",
    question: "Part 1: How does Tobin change from the beginning of the story to the end? Part 2: Highlight one sentence from the beginning (Part 1) and one from the end (Part 3 or 4) that show the change.",
    parts: [
      { type: "choice", prompt: "How does Tobin change?", choices: [
        { id: "a", text: "He goes from too shy to speak to speaking up clearly when it matters." },
        { id: "b", text: "He goes from careful to reckless." },
        { id: "c", text: "He goes from friendly to mean." },
        { id: "d", text: "He doesn't change at all." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from the beginning and one from the end.", passage: ["A", "C", "D"], count: 2 },
    ],
    hint: "How does Tobin answer the reporter in Part 1? How does he answer in Part 4?",
    meter: { supplies: 1, label: "Pilot badges +1", story: "Nova marks Tobin's change on the board" },
    discovery: { id: "swifts", name: "Birds that barely land", who: "Nova", fact: "Common swifts can stay in the air for about ten months at a time. They eat, drink, and even sleep while flying." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A3.3", "A4.4", "A4.5"], ["C2.3", "D3.2", "D3.3"]] },
    ] },
    rightFeedback: "Right! At first Tobin only nods. By the end, he shouts in the storm and speaks clearly to the reporter.",
    wrong: [
      { step: 1, choice: "b", hint: "Tobin guides them home \"slowly and carefully.\" Did he become reckless?" },
      { step: 1, choice: "c", hint: "Tobin says Mira is the bravest pilot he knows. Is that mean?" },
      { step: 1, choice: "d", hint: "Compare how Tobin answers the reporter in Part 1 and in Part 4." },
      { step: 2, sentence: "A3.1", hint: "That shows he is careful, and he stays careful. Find a sentence that shows he is shy at first." },
      { step: 2, sentence: "D2.2", hint: "That's about Mira. Find a sentence where Tobin speaks up." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's mixed-up report", machine: "Report Repair", icon: "log", speaker: "kai", passage: ["G", "C"],
    line: "I finished my race report for Mission Control! Nova read it and said, \"Kai, you got the most important part backward.\"",
    question: "Part 1: What did Kai get wrong about the story? Part 2: Tap each mistake in Kai's report and pick the fix.",
    parts: [
      { type: "choice", prompt: "What did Kai get wrong about the story?", choices: [
        { id: "a", text: "He mixed up who helped whom. Tobin towed Mira's broken skiff, not the other way around." },
        { id: "b", text: "He said there was a storm, but there wasn't one." },
        { id: "c", text: "He said Mira's fin broke, but it was Tobin's." },
        { id: "d", text: "He said both pilots landed safely, but they didn't." },
      ] },
      { type: "edit", prompt: "Fix the 4 mistakes in Kai's report.", passage: "G" },
    ],
    hint: "Reread the start of Part 3. Who throws the tow line? Then read each sentence of the report out loud in your head.",
    meter: { heat: 5, label: "Tailwind +5%", story: "Kai's report goes out correct" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "edit", fixes: { "G:was": "were", "G:brake": "broke", "G:Mira": "Tobin", "G:them": "They" } },
    ] },
    rightFeedback: "Report fixed! Tobin was the one who helped, and every sentence is correct now.",
    wrong: [
      { step: 1, choice: "b", hint: "There really was a storm in Part 2. Who threw the tow line in Part 3?" },
      { step: 1, choice: "c", hint: "Mira's fin did break. Read the report again. Who does Kai say towed the skiff?" },
      { step: 1, choice: "d", hint: "They did drift home safely. Who does Kai say did the towing?" },
      { step: 2, token: "G:was", hint: "Mira and Tobin are two people. Should it be \"was\" or \"were\"?" },
      { step: 2, token: "G:brake", hint: "A brake stops a skiff. Which word is the past tense of break?" },
      { step: 2, token: "G:Mira", hint: "Mira's skiff was the broken one. Who towed it?" },
      { step: 2, token: "G:them", hint: "This word starts a sentence and names who landed. \"Them landed\" or \"They landed\"?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Did Mira really change?", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["D"],
    line: "Kai: \"Mira didn't really change. At the end she says she's still going to win. She's the same old Mira!\"",
    nova: "Nova: \"She still wants to win, Kai. But look at how she treats Tobin and the wind now. That's a real change.\"",
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "A character can keep a goal and still change how they act. What does Mira do the next morning?",
    meter: { supplies: 1, label: "Pilot badges +1", story: "Kai scratches his head and rereads Part 4" },
    discovery: { id: "jetstream", name: "The jet stream", who: "Nova", fact: "The jet stream is a fast river of wind high above the ground. Airplanes flying with it can reach their stop early, and planes flying against it take longer." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Mira still wants to win, but now she studies the wind, listens to Tobin, and says she's sorry. How she acts has changed." },
      { id: "B", text: "Nova, because Mira stopped caring about racing." },
      { id: "C", text: "Kai. A character only changes if they give up their goal." },
      { id: "D", text: "Kai. Mira is still the fastest pilot, so nothing changed." },
    ],
    writtenPrompt: "Tell Kai in your own words how Mira changed, even though she still wants to win.",
    debateHints: {
      wrongWho: "Reread Part 4. What did Mira do all night, and what does she say to Tobin?",
      wrongReason: "Right person, check the reason. Mira says she's still going to win. What changed about how she acts?",
      right: "Nova is right. Mira kept her goal, but she learned to listen, study the wind, and say sorry. That's a real change.",
    },
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Inside Tobin's head", machine: "Journal Reader", icon: "brief", speaker: "vega", passage: ["E", "C"],
    line: "Tobin shared his pilot journal with the crew. It tells us things the story couldn't.",
    question: "Part 1: What does Tobin's journal show that the story doesn't tell us? Part 2: Highlight the sentence that tells the lesson Tobin learned.",
    parts: [
      { type: "choice", prompt: "What does the journal show that the story doesn't?", choices: [
        { id: "a", text: "Who won the Sky Race" },
        { id: "b", text: "Why Tobin used to stay quiet, and how he feels about speaking up" },
        { id: "c", text: "How to fix a steering fin" },
        { id: "d", text: "Where the gust lanes are" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that tells the lesson Tobin learned.", passage: "E" },
    ],
    hint: "A journal tells a person's private thoughts. Look for words like \"I was afraid\" and \"I learned.\"",
    meter: { heat: 5, label: "Tailwind +5%", story: "Vega adds the journal to the mission file" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["E2.3"]] },
    ] },
    rightFeedback: "Yes! The journal shows Tobin was afraid people would laugh, and he learned that staying quiet can be dangerous.",
    wrong: [
      { step: 1, choice: "a", hint: "No one won, and the journal doesn't talk about winning. What does Tobin say he was afraid of?" },
      { step: 1, choice: "c", hint: "The journal isn't about repairs. What private feelings does Tobin share?" },
      { step: 1, choice: "d", hint: "The journal doesn't describe the course. What does Tobin say about staying quiet?" },
      { step: 2, sentence: "E2.2", hint: "That tells why he stayed quiet. Which sentence starts with what he learned?" },
      { step: 2, sentence: "E1.1", hint: "That tells what happened. Find the sentence that says what he learned." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Next year's race", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["A", "B", "C", "D"],
    line: "Surprise! The Sky Race judges want to name a Most Changed Pilot award, and they asked our crew to explain the choice. Make it count.",
    question: "Part 1: How does Mira change? Part 2: Highlight one sentence from the beginning (Part 1 or 2) and one from the end (Part 3 or 4) that show her change. Part 3: Write 2–3 sentences explaining how ONE pilot changed and why. Use evidence from the story.",
    parts: [
      { type: "choice", prompt: "How does Mira change?", choices: [
        { id: "a", text: "She goes from bragging and ignoring advice to listening to others and saying sorry." },
        { id: "b", text: "She goes from brave to afraid of flying." },
        { id: "c", text: "She stops wanting to race." },
        { id: "d", text: "She goes from kind to rude." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from the beginning and one from the end.", passage: ["A", "B", "C", "D"], count: 2 },
      { type: "write", prompt: "Explain how Mira or Tobin changed and why. Use evidence from the story.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["Tells how the pilot was at the beginning and at the end", "Explains what caused the change (the storm, the other pilot)", "Uses evidence from the story", "Complete sentences with capitals and end punctuation"],
    hint: "What did Mira say about the wind at the start? What did she do all night after the storm?",
    meter: { heat: 10, label: "Tailwind +10%", story: "The judges read your explanation out loud" },
    discovery: { id: "anemometer", name: "Wind speed meter", who: "Kai", fact: "An anemometer measures how fast the wind blows. Many have little cups that spin faster when the wind is stronger." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A2.3", "A4.3", "B4.2"], ["C3.2", "C3.3", "D2.3"]] },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Award explanation sent! Your teacher will read what you wrote.",
    wrong: [
      { step: 1, choice: "b", hint: "Mira says she's still going to win next year. Is she afraid of flying?" },
      { step: 1, choice: "c", hint: "She plans to race next year. What changed about how she treats Tobin?" },
      { step: 1, choice: "d", hint: "At the start she laughed at Tobin's lost map. At the end she says sorry. Which way did she change?" },
      { step: 2, sentence: "A2.2", hint: "That shows how she walks. Find something Mira SAYS at the beginning that shows she won't listen or doesn't care." },
      { step: 2, sentence: "D4.2", hint: "That shows she still wants to win. Find an end sentence where she listens or says sorry." },
      { step: 2, sentence: "B4.1", hint: "That shows she ignores the judges, but find something she SAYS at the start and a sentence from the end." },
    ],
  },
};

// Passage G has no sentence ids from passage(); give its sentences ids for display.
passages.G.sentences = [
  { id: "G-s1", text: "Mira and Tobin was both in the Sky Race." },
  { id: "G-s2", text: "A storm brake Mira's steering fin." },
  { id: "G-s3", text: "Mira towed the broken skiff under the reef." },
  { id: "G-s4", text: "them both landed safely." },
];

export default {
  id: "ELA.4.8B-XP",
  standard: "ELA.4.8B-XP",
  engine: "expedition_station",
  title: "The Rival Pilots",
  planet: "Cloudreach",
  outpost: "Coral Clouds launch dock · race day",
  grade: 4,
  subject: "ELAR",
  teks: "4.8B",
  supportingTeks: ["4.8D", "4.8C", "4.6F", "4.7C", "4.3B", "4.11D"],
  skillsChip: "4.8B · Character interactions and changes",
  iCan: "I can explain how characters act toward each other and how they change, using evidence. I can explain how the setting shapes what happens.",
  blurb: "It's race day on Cloudreach. Two young sky-skiff pilots, one proud and one shy, can't stand each other. Then a storm sweeps across the Coral Clouds course.",
  mission: "Read the story of the Sky Race, a crew log, and a pilot's journal to explain how the two rivals change, then send the crew's report.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.8B · CLOUDREACH RACE DOCK",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Tailwind", heatUnit: "%", supplies: "Pilot badges", suppliesUnit: "badges" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega at the Cloudreach launch dock. It's Sky Race day!",
    "Two young pilots are the talk of the dock. Mira Dash is the champ, and she knows it. Tobin Reyes barely says a word.",
    "The race story is coming in over the radio in parts. Read closely. These two are about to surprise everyone. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Race day", "Act 2 · Under the reef", "Act 3 · The next morning"],
    completes: [
      "You met both pilots, {firstName}! But Mira's skiff is spinning in the storm.",
      "Both pilots made it home, {firstName}! The reef kept them safe.",
      "Report sent, {firstName}! The judges have their Most Changed Pilot, thanks to you.",
    ],
    teasers: [
      "Next on Cloudreach: will anyone help Mira? Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the morning after the storm. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Part 3 of the race story just came in, and so did my notes on the course.",
      "Mira's fin is broken, and the storm is getting worse.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The storm is over, and the sky is clear.",
      "Let's find out how these two pilots changed.",
    ],
  }),
  tasks,
};
