// Expedition Station — The Season Tracker (SCI.4.9A-XP)
// Grade 4 · Science · Frostveil (ice). Main standard 4.9A (collect and analyze
// data to identify sequences and predict patterns of change in seasons such as
// change in temperature and length of daylight); also practices 4.1E (collect
// observations and measurements as evidence), 4.1F (organize data in tables
// and bar graphs), 4.2B (analyze data for patterns), 4.2C (use math to compare
// patterns), 4.3A (explanations supported by data and models), 4.3C
// (respectful scientific discussion), 4.5A (use patterns to explain and
// predict), 4.5B (cause and effect).
//
// Earth-true rule: Frostveil and the relay dish are invented, but every data
// table tracks real places on Earth. Values are rounded monthly averages
// (approximate): Austin, Texas; Fairbanks, Alaska; and a town in southern
// Australia.
import { CREW, acts } from "./_shared.js";

const AUSTIN_DAYLIGHT = [
  { label: "Jan", value: 10.3 }, { label: "Feb", value: 11 }, { label: "Mar", value: 12 },
  { label: "Apr", value: 12.9 }, { label: "May", value: 13.7 }, { label: "Jun", value: 14.1 },
  { label: "Jul", value: 13.9 }, { label: "Aug", value: 13.3 }, { label: "Sep", value: 12.4 },
  { label: "Oct", value: 11.5 }, { label: "Nov", value: 10.7 }, { label: "Dec", value: 10.2 },
];
const AUSTIN_TEMP = [
  { label: "Jan", value: 53 }, { label: "Feb", value: 57 }, { label: "Mar", value: 64 },
  { label: "Apr", value: 70 }, { label: "May", value: 78 }, { label: "Jun", value: 84 },
  { label: "Jul", value: 86 }, { label: "Aug", value: 87 }, { label: "Sep", value: 81 },
  { label: "Oct", value: 72 }, { label: "Nov", value: 61 }, { label: "Dec", value: 54 },
];
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Line up the seasons", machine: "Season Wheel", icon: "trail", speaker: "nova",
    line: "The relay dish is pointed at Earth. Before the first data comes in, let's set up the season wheel on our tracker.",
    question: "Start with winter. Put Earth's seasons in order.",
    hint: "What season comes after the cold of winter, when flowers bloom? What comes after the hottest season, when leaves fall?",
    meter: { heat: 10, label: "Tracker +10%", story: "The season wheel is set" },
    answer: { kind: "order", correct: ["winter", "spring", "summer", "fall"] },
    items: [
      { id: "summer", text: "Summer" },
      { id: "fall", text: "Fall (autumn)" },
      { id: "spring", text: "Spring" },
      { id: "winter", text: "Winter" },
    ],
    rightFeedback: "Winter, spring, summer, fall. Then winter comes again, and the pattern repeats every year.",
    wrong: [
      { position: 0, hint: "We start with winter. Which season is first on the wheel?" },
      { position: 1, hint: "After winter, the days warm up and flowers bloom. Which season is that?" },
      { position: 2, hint: "Summer comes after spring. Fall comes after summer, when it cools down again." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The longest-day hunt", machine: "Relay Dish", icon: "scan", speaker: "kai",
    line: "First packet in! A weather station in Austin, Texas, sent how many hours of daylight it gets in each month.",
    question: "Which month has the most hours of daylight in Austin?",
    hint: "Look down the Daylight column. Find the biggest number.",
    meter: { supplies: 1, label: "Data packets +1", story: "The Austin daylight packet is logged" },
    data: {
      title: "Austin, Texas: daylight each month (about)",
      columns: ["Month", "Hours of daylight"],
      rows: AUSTIN_DAYLIGHT.map((m, i) => [MONTHS[i], String(m.value)]),
    },
    discovery: { id: "solstice", name: "The longest day", who: "Nova", fact: "In the northern half of Earth, the longest day of the year comes around June 21. It is called the summer solstice." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "June" },
      { id: "b", text: "December" },
      { id: "c", text: "March" },
      { id: "d", text: "August" },
    ],
    rightFeedback: "June has about 14.1 hours of daylight. That's the most all year.",
    wrong: [
      { choice: "b", hint: "December has about 10.2 hours. Is that the biggest or the smallest number in the table?" },
      { choice: "c", hint: "March has about 12 hours. Look lower in the table. Is there a bigger number?" },
      { choice: "d", hint: "August has about 13.3 hours. Check the months just before it. Is one bigger?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Summer or winter?", machine: "Clue Sorter", icon: "cells", speaker: "vega",
    line: "The Austin station also sent notes about what people see outside. The notes lost their dates.",
    question: "Sort each clue: is it from summer or winter in Texas?",
    hint: "Summer has long, hot days. Winter has short, cool days.",
    meter: { heat: 10, label: "Tracker +10%", story: "The clue notes are sorted" },
    answer: { kind: "sort", bins: { k1: "summer", k2: "winter", k3: "summer", k4: "winter", k5: "summer", k6: "winter" } },
    rightFeedback: "Long, hot days mean summer. Short days, early darkness, and frost mean winter.",
    sort: {
      bins: [{ id: "summer", label: "Summer in Texas" }, { id: "winter", label: "Winter in Texas" }],
      items: [
        { id: "k1", label: "The Sun is still up at 8:00 in the evening" },
        { id: "k2", label: "It is already dark by 6:00 in the evening" },
        { id: "k3", label: "Afternoons are near 97°F" },
        { id: "k4", label: "Light frost on the grass some mornings" },
        { id: "k5", label: "About 14 hours of daylight" },
        { id: "k6", label: "About 10 hours of daylight" },
      ],
    },
    wrong: [
      { item: "k1", hint: "The Sun stays up late when the days are long. Which season has the longest days?" },
      { item: "k2", hint: "Dark by 6:00 means a short day. Which season has short days?" },
      { item: "k3", hint: "97°F is very hot. Which season is hottest in Texas?" },
      { item: "k4", hint: "Frost is ice. It forms when it is freezing cold. Which season is that?" },
      { item: "k5", hint: "Check the Austin table. Which months had about 14 hours of daylight?" },
      { item: "k6", hint: "Check the Austin table. Which months had about 10 hours of daylight?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Warm-up gap", machine: "Thermo Screen", icon: "dial", speaker: "nova",
    line: "Next packet: the average temperature in Austin for each month. Let's see how big the change is.",
    question: "How many degrees warmer is July than January in Austin?",
    unit: "°F",
    hint: "Find July and January in the table. Subtract the smaller number from the bigger one.",
    meter: { supplies: 1, label: "Data packets +1", story: "The temperature packet is logged" },
    data: {
      title: "Austin, Texas: average temperature each month (about)",
      columns: ["Month", "Average temperature (°F)"],
      rows: AUSTIN_TEMP.map((m, i) => [MONTHS[i], String(m.value)]),
    },
    discovery: { id: "normals", name: "Weather averages", who: "Nova", fact: "Weather scientists find a month's average temperature by using 30 years of daily readings. That's why the numbers are called 'about.'" },
    answer: { kind: "number", value: 33 },
    rightFeedback: "86°F − 53°F = 33°F. July is about 33 degrees warmer than January.",
    wrong: [
      { value: 139, hint: "You want the difference between the two months. Should you add or subtract?" },
      { value: 86, hint: "86°F is July's temperature. How much warmer is it than January?" },
      { value: 34, hint: "Check the table again. Is July 86°F or 87°F? August is the 87°F month." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Static on the dish", machine: "Relay Dish", icon: "static", speaker: "vega",
    line: "Surprise! An ice storm hit the relay dish. The daylight table is lost, and only a bar graph made it through the static.",
    question: "Part 1: Which month has the shortest days? Part 2: About how many more hours of daylight does June have than December? Part 3: Which two months have about 12 hours of daylight?",
    parts: [
      { type: "choice", prompt: "Which month has the shortest days in Austin?", choices: [
        { id: "a", text: "December" },
        { id: "b", text: "June" },
        { id: "c", text: "September" },
        { id: "d", text: "April" },
      ], visual: { type: "bars", title: "Austin, Texas: hours of daylight (about)", categories: AUSTIN_DAYLIGHT, step: 2, max: 16, axis: "Hours of daylight" } },
      { type: "number", prompt: "About how many more hours of daylight does June have than December? Round to the nearest hour.", unit: "hours",
        visual: { type: "bars", title: "Austin, Texas: hours of daylight (about)", categories: AUSTIN_DAYLIGHT, step: 2, max: 16, axis: "Hours of daylight" } },
      { type: "choice", prompt: "Which two months have about 12 hours of daylight, so day and night are about the same length?", choices: [
        { id: "a", text: "March and September" },
        { id: "b", text: "June and December" },
        { id: "c", text: "January and July" },
        { id: "d", text: "May and August" },
      ], visual: { type: "bars", title: "Austin, Texas: hours of daylight (about)", categories: AUSTIN_DAYLIGHT, step: 2, max: 16, axis: "Hours of daylight" } },
    ],
    hint: "Compare the heights of the bars. Use the lines on the graph to read the hours.",
    meter: { heat: 10, label: "Tracker +10%", story: "The daylight pattern survives the storm" },
    discovery: { id: "equinox", name: "Equal day and night", who: "Nova", fact: "Around March 20 and September 22, day and night are about 12 hours each almost everywhere on Earth. These days are called equinoxes." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 4, tolerance: 0.5 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The days get longer from December to June, then shorter again. In March and September, day and night are about equal.",
    wrong: [
      { step: 1, choice: "b", hint: "June has the tallest bar. You want the shortest bar." },
      { step: 1, choice: "c", hint: "September's bar is in the middle. Look for the shortest bar." },
      { step: 1, choice: "d", hint: "April's bar is taller than most winter bars. Look for the shortest bar." },
      { step: 2, value: 24, hint: "You want how many MORE hours June has. Should you add or subtract?" },
      { step: 2, value: 14, hint: "About 14 hours is June's daylight. How many more is that than December's?" },
      { step: 2, value: 10, hint: "About 10 hours is December's daylight. How many more does June have?" },
      { step: 3, choice: "b", hint: "June has the longest days, and December has the shortest. Find the bars at the 12 line." },
      { step: 3, choice: "c", hint: "January is near 10 hours, and July is near 14. Find the bars at the 12 line." },
      { step: 3, choice: "d", hint: "May and August are both above 13 hours. Find the bars at the 12 line." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Closer means hotter?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Easy! Summer is hot because Earth moves closer to the Sun. Winter is cold because Earth moves farther away."',
    nova: 'Nova: "That\'s not it. Earth is tilted. When our half leans toward the Sun, we get more direct sunlight and longer days."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about a globe that leans to one side. Which half faces the Sun more?",
    meter: { heat: 5, label: "Tracker +5%", story: "Kai rethinks what makes seasons" },
    discovery: { id: "perihelion", name: "Closest in January", who: "Nova", fact: "Earth is closest to the Sun in early January. That's winter in Texas! Earth's distance from the Sun changes only a little, so it doesn't cause the seasons." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Earth's axis is tilted. When our half leans toward the Sun, sunlight hits it more directly and days are longer, so it's summer." },
      { id: "B", text: "Nova, because the Sun is always the exact same distance away." },
      { id: "C", text: "Kai. Hot things are close, so summer means Earth is close to the Sun." },
      { id: "D", text: "Kai. The Sun gets bigger in summer and smaller in winter." },
    ],
    writtenPrompt: "Tell Kai in your own words what causes the seasons.",
    debateHints: {
      wrongWho: "If being close to the Sun made summer, the whole Earth would have summer at the same time. Does it?",
      wrongReason: "Right person, check the reason. Earth's distance does change a little. What really makes the seasons?",
      right: "Nova is right. The tilt of Earth's axis causes the seasons, not how close Earth is to the Sun.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Far-north forecast", machine: "Relay Dish", icon: "relay", speaker: "nova",
    line: "A second station just checked in from Fairbanks, Alaska, far to the north. It sent daylight for January through June.",
    question: "Use the pattern. Predict about how many hours of daylight Fairbanks will get in July.",
    hint: "Which month has the longest day of the year? What happens to daylight after that?",
    meter: { supplies: 1, label: "Data packets +1", story: "The Fairbanks forecast is posted" },
    data: {
      title: "Fairbanks, Alaska: daylight each month (about)",
      columns: ["Month", "Hours of daylight"],
      rows: [["January", "5"], ["February", "9"], ["March", "12"], ["April", "15"], ["May", "19"], ["June", "22"], ["July", "?"]],
    },
    discovery: { id: "midnightsun", name: "The midnight sun", who: "Kai", fact: "In Utqiagvik, the northernmost town in Alaska, the Sun doesn't set at all for more than 80 days in summer. People call it the midnight sun." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "About 20 hours. The longest day comes in June, so the days start getting shorter." },
      { id: "b", text: "About 25 hours. The days keep getting longer by about 3 hours each month." },
      { id: "c", text: "About 5 hours, the same as January." },
      { id: "d", text: "About 12 hours, because every month after June has 12 hours." },
    ],
    rightFeedback: "The longest day is around June 21. After that, days slowly get shorter, so July has a little less daylight than June.",
    wrong: [
      { choice: "b", hint: "A whole day is only 24 hours long! Also, the longest day of the year comes in June. What happens after that?" },
      { choice: "c", hint: "January is deep winter. July comes right after the longest day. Will it be a lot shorter or just a little shorter?" },
      { choice: "d", hint: "Daylight changes a little each month. It doesn't jump straight to 12. Will July be close to June?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Two towns, one pattern", machine: "Data Table", icon: "grid", speaker: "vega",
    line: "Now we have two towns. Let's compare them before we build the tracker's daylight dial.",
    question: "Pick every statement the data supports.",
    data: {
      title: "Hours of daylight (about)",
      columns: ["Month", "Austin, Texas", "Fairbanks, Alaska"],
      rows: [["March", "12", "12"], ["June", "14", "22"], ["September", "12", "13"], ["December", "10", "4"]],
    },
    items: [
      { id: "junelong", text: "Both towns have their longest days in June." },
      { id: "decshort", text: "Both towns have their shortest days in December." },
      { id: "bigchange", text: "Daylight changes much more in Fairbanks than in Austin." },
      { id: "march", text: "In March, both towns get about 12 hours of daylight." },
      { id: "austinlonger", text: "Austin has longer days than Fairbanks all year." },
      { id: "same", text: "Daylight stays the same all year in Austin." },
    ],
    hint: "Check each statement against the table, one row at a time.",
    meter: { heat: 10, label: "Tracker +10%", story: "The daylight dial is built" },
    discovery: { id: "equator", name: "Steady days", who: "Nova", fact: "Near the equator, daylight stays close to 12 hours all year long. The farther a place is from the equator, the more its daylight changes." },
    answer: { kind: "multi", correct: ["junelong", "decshort", "bigchange", "march"] },
    rightFeedback: "Same pattern, different sizes. Fairbanks goes from about 4 hours to about 22, while Austin goes from about 10 to about 14.",
    wrong: [
      { pick: "austinlonger", hint: "Check the June row. Which town has more daylight in June?" },
      { pick: "same", hint: "Check the Austin column. Is the number the same in every row?" },
      { missing: true, hint: "There are four true statements. Check the June row, the December row, the March row, and how much each town changes." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Read the heat bars", machine: "Thermo Screen", icon: "dial", speaker: "kai",
    line: "I turned the Austin temperature table into a bar graph for the tracker screen. Now the pattern is easy to see.",
    question: "What pattern does the bar graph show?",
    visual: { type: "bars", title: "Austin, Texas: average temperature (°F, about)", categories: AUSTIN_TEMP, step: 10, max: 90, axis: "Degrees Fahrenheit" },
    hint: "Follow the tops of the bars from January to December. Where do they go up? Where do they go down?",
    meter: { supplies: 1, label: "Data packets +1", story: "The heat bars are on the tracker screen" },
    discovery: { id: "lag", name: "Hottest after longest", who: "Nova", fact: "The longest day comes in June, but Texas is usually hottest in July and August. Land and water take weeks to warm up, like a pool that stays chilly after the first hot day." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Temperatures rise from January to a high in July and August, then fall toward December." },
      { id: "b", text: "Temperatures stay about the same all year." },
      { id: "c", text: "Temperatures go down from January to July, then rise again." },
      { id: "d", text: "Temperatures go up every single month of the year." },
    ],
    rightFeedback: "The bars climb to a peak in summer and drop in winter. Then the pattern repeats the next year.",
    wrong: [
      { choice: "b", hint: "Compare the January bar with the August bar. Are they the same height?" },
      { choice: "c", hint: "Look at the July bar. Is it one of the shortest or one of the tallest?" },
      { choice: "d", hint: "Look at the bars after August. Do they keep going up?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The upside-down station", machine: "Relay Dish", icon: "quake", speaker: "vega",
    line: "Surprise! A mystery packet came in from a weather station in southern Australia. Kai says the dish must be broken, because the pattern looks backward!",
    question: "Part 1: Which month has the longest days at this station? Part 2: How many more hours of daylight does December have than June? Part 3: What season is December there? Part 4: Why is the pattern flipped?",
    data: {
      title: "Southern Australia station: daylight (about)",
      columns: ["Month", "Hours of daylight"],
      rows: [["March", "12"], ["June", "10"], ["September", "12"], ["December", "15"]],
    },
    parts: [
      { type: "choice", prompt: "Which month has the longest days at the Australia station?", choices: [
        { id: "a", text: "December" },
        { id: "b", text: "June" },
        { id: "c", text: "March" },
        { id: "d", text: "September" },
      ] },
      { type: "number", prompt: "How many more hours of daylight does December have than June there?", unit: "hours" },
      { type: "choice", prompt: "Long days mean warm weather. What season is December at the Australia station?", choices: [
        { id: "a", text: "Summer" },
        { id: "b", text: "Winter" },
        { id: "c", text: "Fall" },
        { id: "d", text: "It has no seasons" },
      ] },
      { type: "choice", prompt: "Why is the pattern flipped?", choices: [
        { id: "a", text: "Australia is on the southern half of Earth. In December, the southern half leans toward the Sun." },
        { id: "b", text: "The relay dish is broken and flipped the data." },
        { id: "c", text: "Australia is closer to the Sun than Texas is." },
        { id: "d", text: "The Sun only shines on Australia in December." },
      ] },
    ],
    hint: "Read the table first. Then think about the tilted globe. Can both halves lean toward the Sun at the same time?",
    meter: { heat: 10, label: "Tracker +10%", story: "The mystery packet makes sense" },
    discovery: { id: "opposite", name: "Opposite seasons", who: "Kai", fact: "When it's winter in the northern half of Earth, it's summer in the southern half. Many people in Australia go to the beach on the holidays in December." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 5 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The dish is fine! Earth's tilt gives the two halves opposite seasons.",
    wrong: [
      { step: 1, choice: "b", hint: "Check the June row. Is 10 the biggest number in the table?" },
      { step: 1, choice: "c", hint: "March has about 12 hours. Is there a bigger number in the table?" },
      { step: 1, choice: "d", hint: "September has about 12 hours. Is there a bigger number in the table?" },
      { step: 2, value: 25, hint: "You want how many MORE hours. Should you add or subtract?" },
      { step: 2, value: 15, hint: "15 hours is December's daylight. How many more is that than June's?" },
      { step: 2, value: 3, hint: "Check the table again. Use the December row and the June row." },
      { step: 3, choice: "b", hint: "Winter has the shortest days. December has the longest days at this station." },
      { step: 3, choice: "c", hint: "Fall days are about 12 hours and getting shorter. December has the longest days there." },
      { step: 3, choice: "d", hint: "The daylight changes from month to month. That means the station has seasons." },
      { step: 4, choice: "b", hint: "The Austin and Fairbanks data came through the same dish just fine. What is different about where Australia is?" },
      { step: 4, choice: "c", hint: "Distance to the Sun doesn't cause seasons. Think about the tilt." },
      { step: 4, choice: "d", hint: "The station got about 10 hours of sunlight even in June. What makes December its summer?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Kai's frosty note", machine: "Tracker Log", icon: "log", speaker: "kai",
    line: 'I wrote this in the tracker log: "Austin gets about 4 hours of daylight in December. Brrr! Also, let\'s take the daylight dial off the tracker. Daylight is the same all year anyway."',
    question: "Part 1: What went wrong in Kai's note? Part 2: What should the note say about Austin in December? Part 3: Should the tracker keep its daylight dial?",
    data: {
      title: "Hours of daylight (about)",
      columns: ["Month", "Austin, Texas", "Fairbanks, Alaska"],
      rows: [["March", "12", "12"], ["June", "14", "22"], ["September", "12", "13"], ["December", "10", "4"]],
    },
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's note about Austin?", choices: [
        { id: "a", text: "He read the Fairbanks column instead of the Austin column." },
        { id: "b", text: "He read the June row instead of the December row." },
        { id: "c", text: "He added the two towns together." },
        { id: "d", text: "Nothing. Austin really gets about 4 hours in December." },
      ] },
      { type: "choice", prompt: "What should the note say about Austin in December?", choices: [
        { id: "a", text: "About 10 hours of daylight" },
        { id: "b", text: "About 14 hours of daylight" },
        { id: "c", text: "About 22 hours of daylight" },
        { id: "d", text: "About 12 hours of daylight" },
      ] },
      { type: "choice", prompt: "Should the tracker keep its daylight dial?", choices: [
        { id: "a", text: "Yes. Daylight changes in a pattern all year, so the dial helps show the season." },
        { id: "b", text: "No. Daylight is the same every month." },
        { id: "c", text: "No. Only temperature changes with the seasons." },
        { id: "d", text: "Yes, but only for Fairbanks. Austin's daylight never changes." },
      ] },
    ],
    hint: "Find the December row. Then look at the column for the right town.",
    meter: { supplies: 1, label: "Data packets +1", story: "Kai's log is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Kai fixed his note: Austin gets about 10 hours in December, and the daylight dial stays!",
    wrong: [
      { step: 1, choice: "b", hint: "Austin's June number is 14, not 4. Which column has a 4 in the December row?" },
      { step: 1, choice: "c", hint: "10 + 4 would be 14, not 4. Which column has a 4 in the December row?" },
      { step: 1, choice: "d", hint: "Check the December row. What does the Austin column say?" },
      { step: 2, choice: "b", hint: "14 hours is Austin in June. Look at the December row." },
      { step: 2, choice: "c", hint: "22 hours is Fairbanks in June. Look at Austin in December." },
      { step: 2, choice: "d", hint: "12 hours is Austin in March and September. Look at the December row." },
      { step: 3, choice: "b", hint: "Check the Austin column. Is the number the same in every row?" },
      { step: 3, choice: "c", hint: "Daylight changes too. Check both columns from March to December." },
      { step: 3, choice: "d", hint: "Austin changes from about 10 hours to about 14 hours. Is that the same all year?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Noon shadow check", machine: "Shadow Stick", icon: "scan", speaker: "nova",
    line: "The Austin station measures the shadow of a 100 cm pole at noon on four special days. These numbers help show how high the Sun is.",
    question: "What does the shadow data show?",
    data: {
      title: "Austin, Texas: noon shadow of a 100 cm pole (about)",
      columns: ["Date", "Shadow length (cm)"],
      rows: [["March 20", "58"], ["June 21", "12"], ["September 22", "58"], ["December 21", "135"]],
    },
    hint: "A short shadow means the Sun is high overhead. A long shadow means the Sun is low in the sky.",
    meter: { heat: 10, label: "Tracker +10%", story: "The Sun-height dial is added" },
    discovery: { id: "direct", name: "Direct sunlight", who: "Nova", fact: "When the Sun is high in the sky, its light hits the ground more directly and heats it more. That's one big reason summer is warmer than winter." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The noon Sun is highest in June and lowest in December." },
      { id: "b", text: "The noon Sun is highest in December and lowest in June." },
      { id: "c", text: "The noon Sun is the same height all year." },
      { id: "d", text: "The pole grew taller in June." },
    ],
    rightFeedback: "The June shadow is shortest because the Sun is high. The December shadow is longest because the Sun is low.",
    wrong: [
      { choice: "b", hint: "The December shadow is the longest. Does a long shadow mean the Sun is high or low?" },
      { choice: "c", hint: "If the Sun stayed at the same height, the shadows would all be the same length. Are they?" },
      { choice: "d", hint: "The pole is always 100 cm. What changed was where the Sun was in the sky." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Predict December", machine: "Forecast Board", icon: "dial", speaker: "vega",
    line: "The Austin temperature packet for December got stuck in the ice. We'll have to predict it from the fall data.",
    question: "Use the pattern. Predict December's average temperature in Austin.",
    unit: "°F",
    data: {
      title: "Austin, Texas: average temperature (about)",
      columns: ["Month", "Average temperature (°F)"],
      rows: [["August", "87"], ["September", "81"], ["October", "72"], ["November", "61"], ["December", "?"]],
    },
    hint: "How much did the temperature drop from October to November? What if it drops about that much again?",
    meter: { supplies: 1, label: "Data packets +1", story: "The December forecast is posted" },
    answer: { kind: "number", value: 52, tolerance: 4 },
    rightFeedback: "Great prediction! The real average for December in Austin is about 54°F. The fall pattern points toward winter.",
    wrong: [
      { value: 61, hint: "That's the same as November. The temperatures have been dropping every month. Will December keep going down?" },
      { value: 70, hint: "The temperatures are going down in the fall, not up. Should December be warmer or cooler than November?" },
      { value: 41, hint: "That's a drop of 20 degrees. The temperature dropped about 10 degrees each month. Try a smaller drop." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Spring into summer", machine: "Forecast Board", icon: "trail", speaker: "kai",
    line: "The tracker is almost ready to predict! Let's test it. It's March in Austin right now.",
    question: "Predict: pick every change the Austin station will report between March and June.",
    items: [
      { id: "longer", text: "The days get longer." },
      { id: "warmer", text: "The average temperature goes up." },
      { id: "later", text: "The Sun sets later in the evening." },
      { id: "shorter", text: "Noon shadows get shorter." },
      { id: "colder", text: "The average temperature goes down." },
      { id: "less", text: "There are fewer hours of daylight." },
    ],
    hint: "Use the daylight table, the temperature bars, and the shadow data from March to June.",
    meter: { heat: 10, label: "Tracker +10%", story: "The tracker passes its spring test" },
    answer: { kind: "multi", correct: ["longer", "warmer", "later", "shorter"] },
    rightFeedback: "From March to June, days get longer, the Sun climbs higher, shadows shrink, and it gets warmer.",
    wrong: [
      { pick: "colder", hint: "Check the temperature bars. Is June warmer or colder than March?" },
      { pick: "less", hint: "Check the daylight table. Does June have more or fewer hours than March?" },
      { missing: true, hint: "There are four changes. Think about daylight, temperature, sunset time, and shadows." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Switch on the tracker", machine: "Season Tracker", icon: "relay", speaker: "vega",
    line: "This is it! The full Austin packet is in. Before we switch on the Season Tracker, the Frostveil science team wants proof that it can explain and predict Earth's seasons.",
    question: "Part 1: Which season has the longest days and the warmest weather? Part 2: Predict next January's daylight. Part 3: What causes this pattern? Part 4: Write 2–3 sentences to Commander Vega using the data.",
    data: {
      title: "Austin, Texas: a whole year (about)",
      columns: ["Month", "Hours of daylight", "Average temperature (°F)"],
      rows: AUSTIN_DAYLIGHT.map((m, i) => [MONTHS[i], String(m.value), String(AUSTIN_TEMP[i].value)]),
    },
    parts: [
      { type: "choice", prompt: "Which season has the longest days and the warmest weather in Austin?", choices: [
        { id: "a", text: "Summer" },
        { id: "b", text: "Winter" },
        { id: "c", text: "Spring" },
        { id: "d", text: "Fall" },
      ] },
      { type: "number", prompt: "Predict: about how many hours of daylight will Austin have next January? Round to the nearest hour.", unit: "hours" },
      { type: "choice", prompt: "What causes this pattern of changing seasons?", choices: [
        { id: "a", text: "Earth's tilted axis. As Earth travels around the Sun, our half leans toward the Sun in summer and away in winter." },
        { id: "b", text: "Earth gets closer to the Sun in summer." },
        { id: "c", text: "The Sun gets hotter in summer and cooler in winter." },
        { id: "d", text: "Clouds block the Sun all winter." },
      ] },
      { type: "write", prompt: "Explain to Commander Vega how daylight and temperature change over a year in Austin, and predict what comes next. Use numbers from the table.", minWords: 20 },
    ],
    rubric: ["Describes the pattern: longer, warmer days toward summer and shorter, cooler days toward winter", "Uses numbers from the table as evidence", "Makes a prediction that follows the pattern (for example, days will get longer again after December)"],
    hint: "Read the table from top to bottom. Where are the biggest numbers? What happens after December?",
    meter: { heat: 15, label: "Tracker +15%", story: "The Season Tracker is switched on" },
    discovery: { id: "tilt", name: "Earth's tilt", who: "Kai", fact: "Earth's axis is tilted about 23 and a half degrees. As Earth goes around the Sun, the axis keeps leaning the same way, so each half takes turns getting more sunlight." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 10, tolerance: 0.5 },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The Season Tracker is on! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "b", hint: "Winter months like December have the shortest days and coolest weather. Where are the biggest numbers?" },
      { step: 1, choice: "c", hint: "Spring is warming up, but it isn't the warmest yet. Look at June, July, and August." },
      { step: 1, choice: "d", hint: "Fall is cooling down. Look at June, July, and August." },
      { step: 2, value: 9, hint: "The shortest day is around December 21. After that, do the days get shorter or longer?" },
      { step: 2, value: 14, hint: "14 hours is June's daylight. January is in winter, right after December." },
      { step: 2, value: 12, hint: "About 12 hours comes in March. January is right after December. Look at December and last January." },
      { step: 3, choice: "b", hint: "Earth is actually closest to the Sun in early January. What really causes the seasons?" },
      { step: 3, choice: "c", hint: "The Sun gives off about the same energy all year. What about Earth changes?" },
      { step: 3, choice: "d", hint: "Clouds come and go in every season. What makes the daylight change every year in the same pattern?" },
    ],
  },
};

export default {
  id: "SCI.4.9A-XP",
  standard: "SCI.4.9A-XP",
  engine: "expedition_station",
  title: "The Season Tracker",
  planet: "Frostveil",
  outpost: "Ice Relay Station · Earth watch",
  grade: 4,
  subject: "Science",
  teks: "4.9A",
  supportingTeks: ["4.1E", "4.1F", "4.2B", "4.2C", "4.3A", "4.3C", "4.5A", "4.5B"],
  skillsChip: "4.9A · Patterns in the seasons",
  iCan: "I can collect and study data about daylight and temperature. I can use patterns to put the seasons in order and predict what will change next.",
  blurb: "The Frostveil crew is building a Season Tracker for planet Earth. Weather stations in Texas, Alaska, and Australia send data, and the crew finds the pattern.",
  mission: "Study real daylight and temperature data from Earth, find the pattern in the seasons, and switch on a tracker that can predict what comes next.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.9 · FROSTVEIL ICE RELAY",
  playableActs: [1, 2, 3],
  earthTrue: "Frostveil and the relay dish are invented. The towns are real places on Earth, and every data table uses approximate real averages.",
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "Tracker calibrated", heatUnit: "%", supplies: "Data packets", suppliesUnit: "packets" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Our ice relay dish can pick up signals from planet Earth.",
    "Earth weather stations are sending us daylight and temperature data. Our job is to build a Season Tracker that finds the pattern and predicts what comes next.",
    "Stay warm, and watch the numbers. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · First signals from Earth", "Act 2 · Two towns and a mystery packet", "Act 3 · Switch on the tracker"],
    completes: [
      "You found the daylight pattern in Austin, even through the static, {firstName}!",
      "You compared three towns and solved the upside-down mystery, {firstName}!",
      "The Season Tracker is on, {firstName}! It can explain and predict Earth's seasons.",
    ],
    teasers: [
      "Next on Frostveil: Kai has a big idea about why summer is hot, and a new station calls in from Alaska. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: Kai makes a mistake in the tracker log, and it's time to predict. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai thinks he knows why Earth has seasons, and I don't agree.",
      "And a station far to the north is about to check in.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The tracker is almost ready.",
      "Fix the log, test the predictions, and let's switch it on.",
    ],
  }),
  tasks,
};
