// Expedition Station — The Seed Crates (MA.3.4K-XP)
// Grade 3 · Math · Lumara. Main standard 3.4K (one- and two-step
// multiplication and division problems within 100); also practices 3.4D,
// 3.4E, 3.4H, 3.4J, and 3.5B. Grade 3 limits: numbers within 100, facts
// through 10 × 10.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Pack the first crates", machine: "Crate Packer", icon: "grid", speaker: "kai",
    line: "The first seed crates are ready! We have 4 crates. Each crate holds 6 glow seeds.",
    question: "Build 4 crates of 6 seeds on the packer. How many seeds is that in all?",
    unit: "seeds",
    visual: { type: "array", maxRows: 8, maxCols: 10, rowWord: "crates", icon: "🌱", fills: "product", title: "Crate Packer" },
    hint: "Make 4 rows with 6 seeds in each row. Count by 6s: 6, 12, ...",
    meter: { heat: 10, label: "Garden glow +10%", story: "The first crates are packed" },
    discovery: { id: "seedparts", name: "Inside a seed", who: "Nova", fact: "A seed holds a tiny baby plant and a store of food to help it start growing." },
    answer: { kind: "number", value: 24, build: { rows: 4, cols: 6 } },
    rightFeedback: "4 rows of 6 is 24. 4 × 6 = 24 seeds!",
    wrong: [
      { value: 10, hint: "4 + 6 = 10. But there are 4 crates, and EACH one has 6 seeds. Count by 6s four times." },
      { value: 18, hint: "That's 3 crates of 6. Did you count all 4 crates?" },
      { value: 30, hint: "That's 5 crates of 6. How many crates are there?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Hop along the seed path", machine: "Skip Counter", icon: "trail", speaker: "nova",
    line: "I'm filling 6 flower pots. I drop 5 seeds in each pot. That's 5 + 5 + 5 + 5 + 5 + 5.",
    question: "Make equal jumps of 5 on the number line, one jump for each pot. Tap where you land.",
    unit: "seeds",
    visual: { type: "numline", min: 0, max: 50, step: 5, pick: true, title: "Seed path · jumps of 5", label: "seeds" },
    hint: "Each pot is one jump of 5. Count 6 jumps: 5, 10, 15, ...",
    meter: { heat: 5, label: "Garden glow +5%", story: "Every pot has seeds" },
    answer: { kind: "number", value: 30 },
    rightFeedback: "6 jumps of 5 lands on 30. 5 + 5 + 5 + 5 + 5 + 5 = 6 × 5 = 30.",
    wrong: [
      { value: 11, hint: "6 + 5 = 11. But you add 5 six times, not once. Make 6 jumps of 5." },
      { value: 25, hint: "That's 5 jumps. There are 6 pots, so make 6 jumps." },
      { value: 35, hint: "That's 7 jumps. Count one jump for each of the 6 pots." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Share the sprouts", machine: "Share Bay", icon: "cells", speaker: "kai",
    line: "We have 18 glow sprouts. We need to share them equally into 3 crates.",
    question: "Build 3 crates on the packer so the sprouts are shared fairly. How many sprouts go in each crate?",
    unit: "sprouts",
    visual: { type: "array", maxRows: 6, maxCols: 10, rowWord: "crates", icon: "🌿", fills: "cols", title: "Share Bay" },
    hint: "Make 3 rows. Add one sprout to each row at a time until you use all 18. How many are in each row?",
    meter: { heat: 5, label: "Garden glow +5%", story: "The sprouts are shared fairly" },
    discovery: { id: "sprout", name: "Sprouting", who: "Nova", fact: "When a seed sprouts, the root grows first. It pushes down into the soil before the shoot grows up." },
    answer: { kind: "number", value: 6, build: { rows: 3, cols: 6 } },
    rightFeedback: "18 shared into 3 equal crates is 6 each. 18 ÷ 3 = 6.",
    wrong: [
      { value: 15, hint: "18 − 3 = 15. We aren't taking 3 away. We're splitting 18 into 3 equal groups." },
      { value: 9, hint: "9 is what you get for 2 crates. We have 3 crates." },
      { value: 3, hint: "3 is the number of crates. How many sprouts go in EACH crate?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Turn the planting tray", machine: "Row Planter", icon: "grid", speaker: "nova",
    line: "This planting tray has 3 rows of 7 cups. Kai wants to turn the tray so it fits on the cart. Now it will have 7 rows of 3.",
    question: "Part 1: How many cups are on the tray? Part 2: What happens when Kai turns the tray?",
    parts: [
      { type: "number", prompt: "How many cups are on the tray?", unit: "cups",
        visual: { type: "array", mode: "show", rows: 3, cols: 7, icon: "🪴", title: "3 rows of 7" } },
      { type: "choice", prompt: "Kai turns the tray to 7 rows of 3. How many cups are there now?",
        visual: { type: "array", mode: "show", rows: 7, cols: 3, icon: "🪴", title: "7 rows of 3" },
        choices: [
          { id: "a", text: "Still 21. 3 × 7 and 7 × 3 are the same amount." },
          { id: "b", text: "More, because 7 rows is more rows." },
          { id: "c", text: "Fewer, because each row is shorter now." },
          { id: "d", text: "10, because 7 + 3 = 10." },
        ] },
    ],
    hint: "Turning the tray moves it, but it does not add or take away any cups.",
    meter: { heat: 5, label: "Garden glow +5%", story: "The tray fits on the cart" },
    discovery: { id: "rows", name: "Rows of crops", who: "Kai", fact: "Farmers plant crops in straight rows. Rows leave paths so people can walk, water, and pick without stepping on plants." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 21 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "3 × 7 = 7 × 3 = 21. Turning an array doesn't change the total!",
    wrong: [
      { step: 1, value: 10, hint: "3 + 7 = 10. There are 3 rows, and each row has 7 cups. Count by 7s three times." },
      { step: 1, value: 14, hint: "That's 2 rows of 7. Count all 3 rows." },
      { step: 2, choice: "b", hint: "There are more rows, but each row has fewer cups. Did any cups get added?" },
      { step: 2, choice: "c", hint: "The rows are shorter, but there are more of them. Did any cups get taken away?" },
      { step: 2, choice: "d", hint: "Adding 7 + 3 counts the rows and cups in a row. How many cups are on the whole tray?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The beetle snack", machine: "Crate Packer", icon: "snap", speaker: "vega",
    line: "Surprise! We packed 5 crates with 8 seeds each. Then hungry glow beetles got into the crates and ate 4 seeds!",
    question: "Part 1: How many seeds did we pack? Part 2: How many seeds are left? Part 3: Plant the rest in 4 equal rows. How many seeds go in each row?",
    parts: [
      { type: "number", prompt: "5 crates with 8 seeds each. How many seeds did we pack?", unit: "seeds",
        visual: { type: "array", mode: "show", rows: 5, cols: 8, icon: "🌱", title: "5 crates of 8" } },
      { type: "number", prompt: "The beetles ate 4 seeds. How many seeds are left?", unit: "seeds" },
      { type: "number", prompt: "Plant the seeds that are left in 4 equal rows. Build it. How many seeds go in each row?", unit: "seeds",
        visual: { type: "array", maxRows: 6, maxCols: 10, rowWord: "rows", icon: "🌱", fills: "cols", title: "Planting rows" } },
    ],
    hint: "First multiply to find all the seeds. Then subtract what the beetles ate. Then share into 4 equal rows.",
    meter: { heat: 10, label: "Garden glow +10%", story: "The seeds are safe in the ground" },
    discovery: { id: "beetles", name: "Beetles", who: "Nova", fact: "There are more kinds of beetles than any other kind of animal on Earth." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 40 }, { kind: "number", value: 36 }, { kind: "number", value: 9, build: { rows: 4, cols: 9 } }] },
    rightFeedback: "5 × 8 = 40. 40 − 4 = 36. 36 ÷ 4 = 9 seeds in each row!",
    wrong: [
      { step: 1, value: 13, hint: "5 + 8 = 13. There are 5 crates with 8 seeds EACH. Count by 8s five times." },
      { step: 1, value: 45, hint: "Close! Count by 8s: 8, 16, 24, 32, ... How many for 5 crates?" },
      { step: 2, value: 44, hint: "The beetles ATE seeds. Should there be more seeds or fewer?" },
      { step: 2, value: 4, hint: "4 is what the beetles ate. How many are left out of 40?" },
      { step: 3, value: 32, hint: "36 − 4 = 32. We're sharing 36 into 4 equal rows, not taking 4 away." },
      { step: 3, value: 10, hint: "4 rows of 10 is 40. We only have 36 seeds now." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The fact family bed", machine: "Fact Family", icon: "cells", speaker: "nova",
    line: "This glowbell bed has 4 rows of 7 plants. That's 28 plants. The same array can show a whole fact family.",
    question: "Part 1: Use the array. What is 28 ÷ 4? Part 2: Pick every fact in this fact family.",
    parts: [
      { type: "number", prompt: "28 plants in 4 equal rows. What is 28 ÷ 4?",
        visual: { type: "array", mode: "show", rows: 4, cols: 7, icon: "🌷", title: "4 rows of 7 = 28" } },
      { type: "multi", prompt: "Pick every fact that belongs in the 4, 7, 28 fact family.", choices: [
        { id: "m1", text: "4 × 7 = 28" },
        { id: "m2", text: "7 × 4 = 28" },
        { id: "d1", text: "28 ÷ 4 = 7" },
        { id: "d2", text: "28 ÷ 7 = 4" },
        { id: "add", text: "4 + 7 = 11" },
        { id: "sub", text: "28 − 7 = 21" },
      ] },
    ],
    hint: "4 rows of 7 is 28. If you know 4 × 7 = 28, you know 28 ÷ 4 = 7.",
    meter: { supplies: 2, label: "Seed crates +2", story: "The glowbell bed is counted" },
    discovery: { id: "bellflower", name: "Bellflowers", who: "Kai", fact: "Bellflowers are named for their bell shape. Bees crawl right inside the bell to reach the nectar." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 7 }, { kind: "multi", correct: ["m1", "m2", "d1", "d2"] }] },
    rightFeedback: "4 × 7 = 28, 7 × 4 = 28, 28 ÷ 4 = 7, and 28 ÷ 7 = 4. One array, four facts!",
    wrong: [
      { step: 1, value: 24, hint: "28 − 4 = 24. Dividing splits 28 into 4 equal rows. How many are in each row?" },
      { step: 1, value: 4, hint: "4 is the number of rows. How many plants are in EACH row?" },
      { step: 2, pick: "add", hint: "A multiplication fact family uses × and ÷, not +." },
      { step: 2, pick: "sub", hint: "A multiplication fact family uses × and ÷, not −." },
      { step: 2, missing: true, hint: "There are 4 facts in this family: two × facts and two ÷ facts." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The 24 seed debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "We have 24 moonflower seeds for 4 pots. 24 ÷ 4 = 20. I just took 4 away!"',
    nova: 'Nova: "24 ÷ 4 = 6. When we share 24 seeds into 4 equal pots, each pot gets 6, because 4 × 6 = 24."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Dividing makes equal groups. What times 4 makes 24?",
    meter: { heat: 5, label: "Garden glow +5%", story: "Each moonflower pot gets a fair share" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Dividing shares 24 into 4 equal groups. 4 groups of 6 make 24, so 24 ÷ 4 = 6." },
      { id: "B", text: "Nova, because 6 is a smaller number than 20." },
      { id: "C", text: "Kai. Dividing means taking away, so 24 − 4 = 20." },
      { id: "D", text: "Kai. 20 is close to 24, so it must be right." },
    ],
    writtenPrompt: "Tell Kai in your own words why 24 ÷ 4 is 6, not 20.",
    debateHints: {
      wrongWho: "Picture 4 pots. Can each pot get 20 seeds if there are only 24 seeds in all?",
      wrongReason: "Right person, check the reason. What does dividing do to the 24 seeds?",
      right: "Nova is right. 24 ÷ 4 = 6, because 4 × 6 = 24.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The seed strip", machine: "Strip Planner", icon: "log", speaker: "nova",
    line: "I drew a strip diagram. The whole strip is 42 sunburst seeds. It is split into 6 equal parts, one part for each garden bed. [ ? | ? | ? | ? | ? | ? ] = 42",
    question: "Part 1: Pick the equation that matches the strip. Part 2: Solve it.",
    parts: [
      { type: "choice", prompt: "The strip shows 42 split into 6 equal parts. Which equation matches?", choices: [
        { id: "a", text: "42 ÷ 6 = ?" },
        { id: "b", text: "42 − 6 = ?" },
        { id: "c", text: "42 + 6 = ?" },
        { id: "d", text: "6 × 42 = ?" },
      ] },
      { type: "number", prompt: "How many seeds go in each bed?", unit: "seeds",
        visual: { type: "numline", min: 0, max: 42, step: 6, title: "Skip count by 6 to 42. How many jumps?", label: "seeds" } },
    ],
    hint: "Equal parts of a whole means division. What times 6 makes 42?",
    meter: { heat: 5, label: "Garden glow +5%", story: "Every bed gets its sunburst seeds" },
    discovery: { id: "sunflower", name: "Sunflower seeds", who: "Nova", fact: "One big sunflower head can hold more than 1,000 seeds." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 7 }] },
    rightFeedback: "42 ÷ 6 = 7, because 6 × 7 = 42. Each bed gets 7 seeds.",
    wrong: [
      { step: 1, choice: "b", hint: "The strip is split into equal parts. Nothing is taken away." },
      { step: 1, choice: "c", hint: "The whole strip is 42. We are splitting it, not adding more." },
      { step: 1, choice: "d", hint: "42 is the whole. 6 × 42 would be much bigger than the strip." },
      { step: 2, value: 36, hint: "42 − 6 = 36. We are sharing 42 into 6 equal parts." },
      { step: 2, value: 6, hint: "6 is the number of beds. How many seeds are in EACH part?" },
      { step: 2, value: 8, hint: "6 × 8 = 48. That's too many. Try one less." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's moonflower count", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote: "The moonflower bed has 8 rows of 6. I skip counted by 6: 6, 12, 18, 24, 30, 36, 42. So there are 42 moonflowers." Something is off.',
    question: "Part 1: What went wrong? Part 2: Tap the right total on the number line.",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He only counted 7 jumps of 6. There are 8 rows, so he needs 8 jumps." },
        { id: "b", text: "He should have counted by 8s instead of 6s." },
        { id: "c", text: "He should have added 8 + 6." },
        { id: "d", text: "Nothing. 42 is right." },
      ] },
      { type: "number", prompt: "Make 8 jumps of 6. Tap the right total.", unit: "moonflowers",
        visual: { type: "numline", min: 0, max: 60, step: 6, pick: true, title: "Jumps of 6", label: "moonflowers" } },
    ],
    hint: "Count Kai's numbers. One number for each row. Are there 8?",
    meter: { supplies: 1, label: "Seed crates +1", story: "The moonflower count is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 48 }] },
    rightFeedback: "Fixed! 8 jumps of 6 lands on 48. 8 × 6 = 48.",
    wrong: [
      { step: 1, choice: "b", hint: "Counting 6 jumps of 8 works too, since 8 × 6 = 6 × 8. So that's not the problem. Count Kai's numbers." },
      { step: 1, choice: "c", hint: "8 + 6 = 14. That's not how many are in 8 rows of 6." },
      { step: 1, choice: "d", hint: "Count Kai's numbers: 6, 12, 18, ... How many jumps did he make?" },
      { step: 2, value: 42, hint: "That's Kai's answer with 7 jumps. Make one more jump of 6." },
      { step: 2, value: 54, hint: "That's 9 jumps. There are 8 rows." },
      { step: 2, value: 14, hint: "8 + 6 = 14. We need 8 GROUPS of 6." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The pollinator count", machine: "Seed Chart", icon: "quake", speaker: "vega",
    line: "Surprise! The glow bees carried extra seeds to our base. Nova made a picture graph of the seeds they brought. Each 🌼 stands for 4 seeds.",
    question: "Part 1: How many glowbell seeds did the bees bring? Part 2: Put the sunburst and glowbell seeds together. Share them into 7 equal beds. How many seeds go in each bed?",
    parts: [
      { type: "number", prompt: "How many glowbell seeds did the bees bring?", unit: "seeds",
        visual: { type: "pictograph", title: "Seeds the bees brought", icon: "🌼", per: 4, unit: "seeds", categories: [
          { label: "Sunburst", value: 24 }, { label: "Glowbell", value: 32 }, { label: "Moonflower", value: 12 },
        ] } },
      { type: "number", prompt: "Sunburst + glowbell seeds, shared into 7 equal beds. How many seeds go in each bed?", unit: "seeds",
        visual: { type: "pictograph", title: "Seeds the bees brought", icon: "🌼", per: 4, unit: "seeds", categories: [
          { label: "Sunburst", value: 24 }, { label: "Glowbell", value: 32 }, { label: "Moonflower", value: 12 },
        ] } },
    ],
    hint: "Each picture is 4 seeds. Count the pictures and multiply by 4. Then add, then divide by 7.",
    meter: { heat: 10, label: "Garden glow +10%", story: "The bees' seeds are planted" },
    discovery: { id: "strawberry", name: "Strawberry seeds", who: "Nova", fact: "A strawberry wears its seeds on the outside. One berry can have about 200 of them." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 32 }, { kind: "number", value: 8 }] },
    rightFeedback: "8 × 4 = 32 glowbell seeds. 24 + 32 = 56, and 56 ÷ 7 = 8 seeds in each bed!",
    wrong: [
      { step: 1, value: 8, hint: "There are 8 pictures, but each picture stands for 4 seeds. What is 8 × 4?" },
      { step: 1, value: 12, hint: "8 + 4 = 12. Each of the 8 pictures is worth 4 seeds. Multiply." },
      { step: 2, value: 56, hint: "56 is all the sunburst and glowbell seeds. Now share them into 7 equal beds." },
      { step: 2, value: 49, hint: "56 − 7 = 49. We are sharing into 7 equal beds, not taking 7 away." },
      { step: 2, value: 7, hint: "7 is the number of beds. What times 7 makes 56?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Sort the garden jobs", machine: "Sort Bay", icon: "cells", speaker: "kai",
    line: "The garden job cards are all mixed up. Some jobs need multiplication. Some need division.",
    question: "Sort each job card. Does it need × or ÷?",
    hint: "If you know the groups and how many in each, multiply to find the total. If you know the total, divide to find the groups or how many in each.",
    meter: { supplies: 1, label: "Seed crates +1", story: "Every job has a plan" },
    discovery: { id: "burrs", name: "Hitchhiking seeds", who: "Nova", fact: "Some seeds have tiny hooks that stick to animal fur. Burrs like these gave an inventor the idea for Velcro." },
    answer: { kind: "sort", bins: { j1: "mult", j2: "div", j3: "mult", j4: "div", j5: "div", j6: "mult" } },
    rightFeedback: "Every job card is in the right bin!",
    sort: {
      bins: [
        { id: "mult", label: "Multiply ×" },
        { id: "div", label: "Divide ÷" },
      ],
      items: [
        { id: "j1", label: "5 trays with 6 bulbs each. How many bulbs in all?" },
        { id: "j2", label: "35 seeds shared into 5 pots. How many in each pot?" },
        { id: "j3", label: "9 rows of 3 lanterns. How many lanterns?" },
        { id: "j4", label: "40 sprouts, 8 in each crate. How many crates?" },
        { id: "j5", label: "18 fireflies split into 2 equal jars. How many in each jar?" },
        { id: "j6", label: "7 bees each visit 4 flowers. How many visits?" },
      ],
    },
    wrong: [
      { item: "j4", hint: "You know the total (40) and how many in each crate (8). You need the number of groups. That's division." },
      { item: "j2", hint: "You know the total (35) and the number of pots. Sharing a total into equal groups is division." },
      { item: "j6", hint: "7 groups of 4 visits. You know the groups and how many in each. Find the total." },
      { item: "j1", hint: "5 groups of 6 bulbs. You know the groups and how many in each. Find the total." },
      { item: "j3", hint: "9 rows of 3 makes an array. Find the total." },
      { item: "j5", hint: "You know the total (18) and it is split into equal jars. That's division." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The mystery trays", machine: "Numberless", icon: "water", speaker: "nova",
    line: "I set out some seed trays for the night garden. Every tray has the same number of cups. Each cup gets one seed.",
    question: "Part 1: Pick the questions we could answer with this story. Part 2: Now the numbers show up. Solve it.",
    parts: [
      { type: "multi", prompt: "Which questions could we answer once we know the numbers?", choices: [
        { id: "total", text: "How many cups are there in all?" },
        { id: "seeds", text: "How many seeds do we need to fill every cup?" },
        { id: "color", text: "What color are the trays?" },
        { id: "time", text: "What time did Nova set out the trays?" },
      ] },
      { type: "number", prompt: "Nova set out 9 trays. Each tray has 6 cups. How many seeds does she need to fill every cup? Build it.", unit: "seeds",
        visual: { type: "array", maxRows: 10, maxCols: 10, rowWord: "trays", icon: "🌱", fills: "product", title: "Night garden trays" } },
    ],
    hint: "Equal groups of cups: multiply the number of trays by the cups in each tray.",
    meter: { heat: 5, label: "Garden glow +5%", story: "The night garden trays are full" },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["total", "seeds"] }, { kind: "number", value: 54, build: { rows: 9, cols: 6 } }] },
    rightFeedback: "9 trays of 6 cups is 54. 9 × 6 = 54 seeds!",
    wrong: [
      { step: 1, pick: "color", hint: "The story tells us about trays and cups, not colors. Can we answer that?" },
      { step: 1, pick: "time", hint: "The story doesn't say anything about time. Pick questions about how many." },
      { step: 1, missing: true, hint: "Two questions can be answered. Each cup gets one seed, so the seeds match the cups." },
      { step: 2, value: 15, hint: "9 + 6 = 15. There are 9 trays with 6 cups EACH. Multiply." },
      { step: 2, value: 45, hint: "That's 9 × 5. Each tray has 6 cups." },
      { step: 2, value: 56, hint: "Close! Count by 6s nine times: 6, 12, 18, ... Check your last jump." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Build the lantern bed", machine: "Row Planter", icon: "grid", speaker: "kai",
    line: "The lantern-flower bed needs 63 square tiles of soil. The bed is 7 tiles across.",
    question: "Build a bed that is 7 tiles across and uses 63 tiles. How many rows does it have?",
    unit: "rows",
    visual: { type: "array", style: "tiles", maxRows: 10, maxCols: 10, rowWord: "rows", fills: "rows", title: "Lantern-flower bed" },
    hint: "Think: 7 × ? = 63. Add rows of 7 until you reach 63.",
    meter: { heat: 5, label: "Garden glow +5%", story: "The lantern bed is ready" },
    discovery: { id: "coconut", name: "Coconuts", who: "Nova", fact: "A coconut is a giant seed. It can float across the ocean and sprout on a faraway beach." },
    answer: { kind: "number", value: 9, build: { rows: 9, cols: 7 } },
    rightFeedback: "9 rows of 7 is 63. 63 ÷ 7 = 9, because 7 × 9 = 63.",
    wrong: [
      { value: 56, hint: "63 − 7 = 56. We need to know how many rows of 7 make 63." },
      { value: 8, hint: "8 rows of 7 is 56. You need a few more tiles. Add another row." },
      { value: 7, hint: "7 is how many tiles go across. How many rows make 63 tiles?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Nova's fact trick", machine: "Fact Finder", icon: "dial", speaker: "nova",
    line: "The starpetal bed has 6 rows of 8. I don't know 6 × 8 by heart. But I do know 5 × 8 = 40.",
    question: "Part 1: How can Nova use 5 × 8 to find 6 × 8? Part 2: How many starpetals are there?",
    parts: [
      { type: "choice", prompt: "How can Nova use 5 × 8 = 40?", choices: [
        { id: "a", text: "6 rows is 5 rows plus 1 more row. So add one more 8: 40 + 8." },
        { id: "b", text: "Add 1 to 40, because 6 is 1 more than 5." },
        { id: "c", text: "Add 6 to 40, because there are 6 rows." },
        { id: "d", text: "She can't. She has to count every flower." },
      ],
        visual: { type: "array", mode: "show", rows: 6, cols: 8, icon: "✨", title: "6 rows of 8" } },
      { type: "number", prompt: "How many starpetals are in 6 rows of 8?", unit: "starpetals" },
    ],
    hint: "Look at the array. 6 rows is 5 rows and 1 more row. How many flowers are in one row?",
    meter: { heat: 5, label: "Garden glow +5%", story: "The starpetal bed is counted" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 48 }] },
    rightFeedback: "5 × 8 = 40, plus one more row of 8 is 48. 6 × 8 = 48!",
    wrong: [
      { step: 1, choice: "b", hint: "One more row isn't one more flower. How many flowers are in one row?" },
      { step: 1, choice: "c", hint: "The new row has 8 flowers, not 6. Look at the array." },
      { step: 1, choice: "d", hint: "She can use a fact she knows. What does one more row add?" },
      { step: 2, value: 41, hint: "One more row adds a whole row of 8, not just 1." },
      { step: 2, value: 46, hint: "One more row has 8 flowers. 40 + 8 = ?" },
      { step: 2, value: 14, hint: "6 + 8 = 14. We need 6 rows of 8." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Moon-bloom night", machine: "Crate Packer", icon: "relay", speaker: "vega",
    line: "This is it! Moon-bloom night is tonight. We have 7 crates with 8 glow bulbs in each. Surprise! The glow bees just dropped off 16 more bulbs.",
    question: "Part 1: How many bulbs are in the crates? Part 2: How many bulbs do we have now? Part 3: Plant them all in 9 equal rows. How many bulbs go in each row?",
    parts: [
      { type: "number", prompt: "7 crates with 8 bulbs each. Build it. How many bulbs are in the crates?", unit: "bulbs",
        visual: { type: "array", maxRows: 10, maxCols: 10, rowWord: "crates", icon: "💡", fills: "product", title: "Crate Packer" } },
      { type: "number", prompt: "The bees dropped off 16 more bulbs. How many bulbs do we have now?", unit: "bulbs" },
      { type: "number", prompt: "Plant all the bulbs in 9 equal rows. How many bulbs go in each row?", unit: "bulbs",
        visual: { type: "numline", min: 0, max: 90, step: 9, title: "Skip count by 9s", label: "bulbs" } },
    ],
    hint: "Multiply the crates first. Then add the new bulbs. Then think: 9 × ? = the total.",
    meter: { heat: 10, label: "Garden glow +10%", story: "The glow garden blooms under the moons" },
    discovery: { id: "datepalm", name: "A very old seed", who: "Nova", fact: "Scientists planted a date palm seed that was about 2,000 years old, and it sprouted!" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 56, build: { rows: 7, cols: 8 } }, { kind: "number", value: 72 }, { kind: "number", value: 8 }] },
    rightFeedback: "7 × 8 = 56. 56 + 16 = 72. 72 ÷ 9 = 8 bulbs in each row. The glow garden is blooming!",
    wrong: [
      { step: 1, value: 15, hint: "7 + 8 = 15. There are 7 crates with 8 bulbs EACH. Multiply." },
      { step: 1, value: 54, hint: "Close! Count by 8s seven times: 8, 16, 24, ... Check your last jump." },
      { step: 2, value: 40, hint: "The bees ADDED bulbs. Should we have more or fewer now?" },
      { step: 2, value: 62, hint: "Check your adding. 56 + 10 = 66. Then add 6 more." },
      { step: 3, value: 63, hint: "72 − 9 = 63. We are sharing 72 into 9 equal rows, not taking 9 away." },
      { step: 3, value: 9, hint: "9 is the number of rows. What times 9 makes 72?" },
    ],
  },
};

export default {
  id: "MA.3.4K-XP",
  standard: "MA.3.4K-XP",
  engine: "expedition_station",
  title: "The Seed Crates",
  planet: "Lumara",
  outpost: "Glow Garden · planting season",
  grade: 3,
  subject: "Math",
  teks: "3.4K",
  supportingTeks: ["3.4D", "3.4E", "3.4H", "3.4J", "3.5B"],
  skillsChip: "3.4K · Multiply and divide to solve problems",
  iCan: "I can solve one-step and two-step multiplication and division problems using arrays, equal groups, number lines, and facts I know.",
  blurb: "Planting season has come to the glowing garden on Lumara. The crew has to pack seed crates in equal groups and plant them in rows before moon-bloom night.",
  mission: "Pack the seed crates, plant the glow rows, and get the garden blooming for moon-bloom night.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.4K · LUMARA GLOW GARDEN",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Garden glow", heatUnit: "%", supplies: "Seed crates", suppliesUnit: "crates" },
  journalMax: 10,
  grade3Limits: "Whole numbers within 100. Multiplication and division facts through 10 × 10.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. It's planting season on Lumara.",
    "The glow garden lights up the whole planet at night, but only if the seeds get planted in time.",
    "Help Kai and Nova pack the seed crates in equal groups and plant them in rows. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Pack the seed crates", "Act 2 · Plant the glow rows", "Act 3 · Moon-bloom night"],
    completes: [
      "The seed crates are packed, {firstName}!",
      "The glow rows are planted and the bees' seeds are in, {firstName}!",
      "The glow garden is blooming, {firstName}! Lumara shines tonight.",
    ],
    teasers: [
      "Next on Lumara: time to plant the glow rows. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: moon-bloom night is almost here. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The crates are packed, so now we plant them in rows.",
      "Kai's counts are a little mixed up, so let's check them together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Moon-bloom night is coming.",
      "Help the crew finish the last beds so the glow garden blooms on time.",
    ],
  }),
  tasks,
};
