// Expedition Station — The Sharing Station (MA.4.4F-XP)
// Grade 4 · Math · Solara. Main standard 4.4F (use strategies and algorithms,
// including the standard algorithm, to divide up to a four-digit dividend by a
// one-digit divisor); also practices 4.4E (represent the quotient with arrays,
// area models, or equations), 4.4G (round or use compatible numbers to
// estimate), and checking division with multiplication. Remainders are
// interpreted in context: round up, drop it, or report it. Answers are whole
// numbers or choices; a remainder is typed as its own number.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Split the seed pods", machine: "Share Table", icon: "grid", speaker: "kai",
    line: "The seed pods came in bundles: flats of 100, rods of 10, and single pods. We have to share them evenly with 4 canopy camps.",
    question: "Share the blocks equally among 4 camps. How many seed pods does each camp get?",
    unit: "seed pods",
    visual: { type: "blocks", mode: "show", places: ["hundreds", "tens", "ones"], counts: { hundreds: 4, tens: 8, ones: 4 }, title: "484 seed pods for 4 camps" },
    hint: "Share one place at a time. 4 flats to 4 camps is 1 flat each. 8 rods to 4 camps is 2 rods each. Then share the 4 ones.",
    meter: { heat: 10, label: "Fair share +10%", story: "The seed pods are shared" },
    discovery: { id: "orangnest", name: "Orangutan beds", who: "Nova", fact: "Orangutans build a fresh sleeping nest of leaves and branches high in the trees almost every night." },
    answer: { kind: "number", value: 121 },
    rightFeedback: "Each camp gets 1 flat, 2 rods, and 1 pod. 484 ÷ 4 = 121 seed pods!",
    wrong: [
      { value: 480, hint: "484 − 4 takes away 4 pods. We need to SHARE 484 into 4 equal groups." },
      { value: 1936, hint: "484 × 4 makes the pile bigger. Sharing makes each group smaller. Divide." },
      { value: 488, hint: "484 + 4 adds pods. Split the blocks into 4 equal groups instead." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "A letter for the share", machine: "Equation Board", icon: "log", speaker: "nova",
    line: "3 camps will share 936 rope clips. I like to write an equation first. The letter s stands for each camp's share.",
    question: "Part 1: Pick the equation that matches. Part 2: What is s?",
    parts: [
      { type: "choice", prompt: "936 rope clips are shared equally by 3 camps. Which equation shows each camp's share, s?", choices: [
        { id: "a", text: "936 ÷ 3 = s" },
        { id: "b", text: "936 × 3 = s" },
        { id: "c", text: "3 ÷ 936 = s" },
        { id: "d", text: "936 − 3 = s" },
      ] },
      { type: "number", prompt: "Solve it. What is s?", unit: "rope clips" },
    ],
    hint: "Sharing equally means dividing. The total goes first: 936 ÷ 3. Then divide the hundreds, the tens, and the ones.",
    meter: { heat: 5, label: "Fair share +5%", story: "The rope clips are shared" },
    discovery: { id: "stranglerfig", name: "Strangler figs", who: "Nova", fact: "A strangler fig starts as a seed dropped high in a tree. Its roots grow down around the tree to the ground, and over many years the fig can wrap the whole trunk." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 312 }] },
    rightFeedback: "936 ÷ 3 = s, and s = 312. 9 hundreds ÷ 3 = 3 hundreds, 3 tens ÷ 3 = 1 ten, 6 ones ÷ 3 = 2 ones!",
    wrong: [
      { step: 1, choice: "b", hint: "Multiplying makes the number bigger. Each camp gets a smaller part of the clips." },
      { step: 1, choice: "c", hint: "Put the total first. We split 936 into 3 groups, not 3 into 936 groups." },
      { step: 1, choice: "d", hint: "Subtracting 3 just takes away 3 clips. Sharing equally means dividing." },
      { step: 2, value: 2808, hint: "That's 936 × 3. Each camp gets PART of the clips. Divide." },
      { step: 2, value: 933, hint: "That's 936 − 3. Share 936 into 3 equal groups instead." },
      { step: 2, value: 302, hint: "Check the tens. 3 tens ÷ 3 = 1 ten, not 0 tens." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Ballpark the batteries", machine: "Estimate Scope", icon: "scan", speaker: "vega",
    line: "1,789 lantern batteries are going to 6 camps. Before we count exactly, let's get a quick estimate with compatible numbers.",
    question: "Part 1: Which compatible numbers are best for estimating 1,789 ÷ 6? Part 2: What is your estimate?",
    parts: [
      { type: "choice", prompt: "Pick the best compatible numbers for 1,789 ÷ 6.", choices: [
        { id: "a", text: "1,800 ÷ 6, because 18 ÷ 6 is a basic fact and 1,800 is close to 1,789" },
        { id: "b", text: "1,700 ÷ 6, because you always round down" },
        { id: "c", text: "1,789 ÷ 10, because 10 is easy to divide by" },
        { id: "d", text: "2,000 ÷ 6, because 2,000 is a round number" },
      ] },
      { type: "number", prompt: "Use your compatible numbers. About how many batteries does each camp get?", unit: "batteries" },
    ],
    hint: "Look for a number close to 1,789 that 6 divides easily. 18 ÷ 6 = 3, so 18 hundreds ÷ 6 = 3 hundreds.",
    meter: { heat: 5, label: "Fair share +5%", story: "The battery estimate is ready" },
    discovery: { id: "flyingdragon", name: "Flying dragons", who: "Kai", fact: "Flying dragon lizards live in Southeast Asian rainforests. They spread flaps of skin like wings and glide from tree to tree." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 300 }] },
    rightFeedback: "1,800 ÷ 6 = 300. Each camp gets about 300 batteries. Now we know what a good exact answer looks like!",
    wrong: [
      { step: 1, choice: "b", hint: "17 ÷ 6 is not a basic fact, so 1,700 is hard to divide by 6. Find a number that 6 divides easily." },
      { step: 1, choice: "c", hint: "There are 6 camps, not 10. Keep the 6 and change 1,789 to a friendly number." },
      { step: 1, choice: "d", hint: "20 ÷ 6 doesn't come out even. Which number close to 1,789 works with 6?" },
      { step: 2, value: 3000, hint: "18 hundreds ÷ 6 = 3 hundreds, not 3 thousands." },
      { step: 2, value: 30, hint: "Too small! 30 × 6 is only 180. 18 hundreds ÷ 6 = 3 hundreds." },
      { step: 2, value: 200, hint: "Check it: 200 × 6 = 1,200. What times 6 makes 1,800?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The area model awning", machine: "Area Model Awning", icon: "cells", speaker: "nova",
    line: "852 rain tarps are going to 4 camps. I drew an area model. One side is 4, and the inside is split into 800, 40, and 12. One top side is blank!",
    question: "Part 1: What is the blank top side? Part 2: What is 852 ÷ 4?",
    parts: [
      { type: "number", prompt: "4 × ? = 800. What goes on top of Box 1?",
        data: {
          title: "Area model · 852 ÷ 4",
          columns: ["", "Box 1", "Box 2", "Box 3"],
          rows: [["Top side", "?", "10", "3"], ["Area inside (other side is 4)", "800", "40", "12"]],
        } },
      { type: "number", prompt: "Add the three top sides. What is 852 ÷ 4?", unit: "tarps",
        data: {
          title: "Area model · 852 ÷ 4",
          columns: ["", "Box 1", "Box 2", "Box 3"],
          rows: [["Top side", "?", "10", "3"], ["Area inside (other side is 4)", "800", "40", "12"]],
        } },
    ],
    hint: "4 × 2 = 8, so 4 × 200 = 800. The quotient is all the top sides added together.",
    meter: { supplies: 1, label: "Camps supplied +1", story: "The rain tarps are shared" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 200 }, { kind: "number", value: 213 }] },
    rightFeedback: "4 × 200 = 800. The top sides are 200 + 10 + 3 = 213 tarps for each camp!",
    wrong: [
      { step: 1, value: 20, hint: "4 × 20 = 80. The box holds 800. What times 4 makes 800?" },
      { step: 1, value: 796, hint: "800 − 4 subtracts. The area model asks: 4 times what equals 800?" },
      { step: 1, value: 3200, hint: "800 × 4 is too big. Find the missing side: 4 × ? = 800." },
      { step: 2, value: 33, hint: "Box 1's top side is 200, not 20. Add 200 + 10 + 3." },
      { step: 2, value: 15, hint: "Box 1's top side is 200, not 2. Add 200 + 10 + 3." },
      { step: 2, value: 3408, hint: "852 × 4 is too big. Add the top sides of the area model." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The soggy fruit bars", machine: "Share Table", icon: "quake", speaker: "vega",
    line: "We packed 2,345 fruit bars to share equally with 5 camps. Surprise! A rain gush poured through the supply tent and soaked 45 bars. We can't send those.",
    question: "Part 1: How many bars would each camp get from 2,345? Part 2: Now share the 2,300 dry bars. How many does each camp get? Part 3: How many fewer bars does each camp get now?",
    parts: [
      { type: "number", prompt: "What is 2,345 ÷ 5?", unit: "fruit bars" },
      { type: "number", prompt: "45 bars got soaked, so 2,300 are left. What is 2,300 ÷ 5?", unit: "fruit bars" },
      { type: "number", prompt: "How many fewer bars does each camp get than before?", unit: "fruit bars" },
    ],
    hint: "Use the standard algorithm. 23 hundreds ÷ 5 = 4 hundreds with 3 hundreds left. Regroup into tens and keep going. Then compare the two shares.",
    meter: { heat: 10, label: "Fair share +10%", story: "The dry bars are shared" },
    discovery: { id: "pangolin", name: "Pangolin scales", who: "Nova", fact: "Pangolins are covered in hard scales made of keratin, the same stuff as your fingernails. They roll into a tight ball to stay safe." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 469 }, { kind: "number", value: 460 }, { kind: "number", value: 9 }] },
    rightFeedback: "2,345 ÷ 5 = 469 and 2,300 ÷ 5 = 460. Each camp gets 9 fewer bars. 45 soaked bars ÷ 5 camps = 9. It all fits!",
    wrong: [
      { step: 1, value: 2340, hint: "2,345 − 5 takes away only 5 bars. Share all 2,345 bars into 5 equal groups." },
      { step: 1, value: 11725, hint: "2,345 × 5 is too big. Each camp gets a PART of the bars. Divide." },
      { step: 1, value: 46, hint: "You stopped early. After 23 hundreds and 34 tens, bring down the 5 ones and divide again." },
      { step: 2, value: 469, hint: "That was the share before the rain. Now divide the 2,300 dry bars by 5." },
      { step: 2, value: 424, hint: "The 45 soaked bars came from the whole pile, not from each camp. Find 2,300 ÷ 5." },
      { step: 3, value: 45, hint: "45 bars were soaked in all. Those 45 were spread over 5 camps. How many fewer for EACH camp?" },
      { step: 3, value: 460, hint: "460 is the new share. Compare it to the old share of 469." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Chunk by chunk", machine: "Partial Quotient Press", icon: "split", speaker: "kai",
    line: "The canopy camps need 1,164 bamboo cups shared by 3 camps. I took away big chunks of 3 at a time. That's called partial quotients.",
    question: "Part 1: What goes in the blank box? Part 2: What is 1,164 ÷ 3?",
    parts: [
      { type: "number", prompt: "The last step takes away 24. How many groups of 3 is that?",
        data: {
          title: "Kai's partial quotients · 1,164 ÷ 3",
          columns: ["Left to share", "Take away", "Groups of 3"],
          rows: [["1,164", "900", "300"], ["264", "240", "80"], ["24", "24", "?"], ["0", "", ""]],
        } },
      { type: "number", prompt: "Add up all the groups. What is 1,164 ÷ 3?", unit: "cups",
        data: {
          title: "Kai's partial quotients · 1,164 ÷ 3",
          columns: ["Left to share", "Take away", "Groups of 3"],
          rows: [["1,164", "900", "300"], ["264", "240", "80"], ["24", "24", "?"], ["0", "", ""]],
        } },
    ],
    hint: "3 × 8 = 24. The quotient is all the groups added together: 300 + 80 + the last chunk.",
    meter: { supplies: 1, label: "Camps supplied +1", story: "The bamboo cups are shared" },
    discovery: { id: "stinglessbees", name: "Stingless bees", who: "Nova", fact: "Some rainforest bees have no stingers at all. These stingless bees still make honey, and they guard their nests by biting." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 8 }, { kind: "number", value: 388 }] },
    rightFeedback: "3 × 8 = 24. Then 300 + 80 + 8 = 388 cups for each camp!",
    wrong: [
      { step: 1, value: 24, hint: "24 is how many cups were taken away. How many groups of 3 make 24?" },
      { step: 1, value: 72, hint: "24 × 3 multiplies. Find how many 3s fit in 24." },
      { step: 1, value: 21, hint: "24 − 3 subtracts once. How many groups of 3 are in 24?" },
      { step: 2, value: 380, hint: "Don't forget the last chunk. Add 300 + 80 + 8." },
      { step: 2, value: 308, hint: "You left out the 80 groups. Add 300 + 80 + 8." },
      { step: 2, value: 88, hint: "You left out the first big chunk of 300 groups." },
      { step: 2, value: 3492, hint: "1,164 × 3 is too big. Add the groups in the last column." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "No seedling left behind", machine: "Tray Rack", icon: "relay", speaker: "nova",
    line: "We have 1,390 tree seedlings to plant. Each planting tray holds 8 seedlings. Every single seedling has to go in a tray today.",
    question: "Part 1: What is the whole-number part of 1,390 ÷ 8? Part 2: What is the remainder? Part 3: How many trays do we need for all the seedlings?",
    parts: [
      { type: "number", prompt: "1,390 ÷ 8. What is the whole-number part of the quotient?", unit: "trays" },
      { type: "number", prompt: "What is the remainder?", unit: "seedlings" },
      { type: "number", prompt: "Every seedling needs a tray. How many trays do we need?", unit: "trays" },
    ],
    hint: "Divide, then look at the leftover seedlings. They still need a spot, so they need one more tray, even if it isn't full.",
    meter: { supplies: 1, label: "Camps supplied +1", story: "Every seedling has a tray" },
    discovery: { id: "gibbons", name: "Swinging gibbons", who: "Kai", fact: "Gibbons swing arm over arm through the treetops. Their arms are much longer than their legs." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 173 }, { kind: "number", value: 6 }, { kind: "number", value: 174 }] },
    rightFeedback: "1,390 ÷ 8 = 173 R 6. The 6 leftover seedlings need a tray too, so we need 174 trays!",
    wrong: [
      { step: 1, value: 1382, hint: "1,390 − 8 fills only one tray. How many groups of 8 fit in 1,390?" },
      { step: 1, value: 11120, hint: "1,390 × 8 is too big. Divide to find how many trays of 8." },
      { step: 1, value: 163, hint: "Check the tens: 8 × 163 = 1,304, which leaves 86. That's enough for more trays." },
      { step: 2, value: 14, hint: "14 is more than 8, so another full tray fits. The remainder must be less than 8." },
      { step: 2, value: 0, hint: "Check it: 173 × 8 = 1,384. That's not 1,390, so some seedlings are left." },
      { step: 3, value: 173, hint: "With 173 trays, 6 seedlings would have no tray. They need one more." },
      { step: 3, value: 179, hint: "Don't add the 6 seedlings to the trays. The 6 leftovers fit in just ONE more tray." },
      { step: 3, value: 6, hint: "6 is the leftover seedlings. How many trays hold all 1,390?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Full ladders only", machine: "Ladder Works", icon: "tank", speaker: "kai",
    line: "I'm building rope ladders for the treehouse camps. Each ladder needs exactly 7 rungs. We have 500 rungs.",
    question: "Part 1: What is the whole-number part of 500 ÷ 7? Part 2: What is the remainder? Part 3: What do we do with the leftover rungs?",
    parts: [
      { type: "number", prompt: "500 ÷ 7. What is the whole-number part of the quotient?", unit: "ladders" },
      { type: "number", prompt: "What is the remainder?", unit: "rungs" },
      { type: "choice", prompt: "Every ladder must have all 7 rungs. How many ladders can Kai build?", choices: [
        { id: "a", text: "71 ladders. The 3 extra rungs can't make a whole ladder, so they go in the spare box." },
        { id: "b", text: "72 ladders. The last ladder can have just 3 rungs." },
        { id: "c", text: "74 ladders, because 71 + 3 = 74." },
        { id: "d", text: "3 ladders, because the remainder is the answer." },
      ] },
    ],
    hint: "7 × 70 = 490. How many rungs are left after that? A ladder only counts if it has all 7 rungs.",
    meter: { heat: 5, label: "Fair share +5%", story: "The rope ladders are built" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 71 }, { kind: "number", value: 3 }, { kind: "choice", correct: "a" }] },
    rightFeedback: "500 ÷ 7 = 71 R 3. Only full ladders count, so Kai builds 71 ladders and saves 3 spare rungs.",
    wrong: [
      { step: 1, value: 493, hint: "500 − 7 is only one ladder. How many groups of 7 fit in 500?" },
      { step: 1, value: 3500, hint: "500 × 7 is too big. Divide to find how many ladders of 7." },
      { step: 1, value: 61, hint: "Check it: 7 × 61 = 427, which leaves 73 rungs. That's enough for more ladders." },
      { step: 2, value: 10, hint: "10 rungs is more than 7, so one more ladder fits. The remainder must be less than 7." },
      { step: 2, value: 497, hint: "497 is how many rungs the ladders use. How many rungs are left over?" },
      { step: 3, choice: "b", hint: "A ladder with only 3 rungs is not a full ladder. Only full ladders count." },
      { step: 3, choice: "c", hint: "The 3 is rungs, not ladders. You can't add them to the number of ladders." },
      { step: 3, choice: "d", hint: "The question asks how many ladders, not how many rungs are left." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The missing zero", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "824 water flasks ÷ 4 camps is 26 flasks each. 8 ÷ 4 = 2. 2 ÷ 4 doesn\'t work, so I skip it. Then 4 ÷ 4 = 1... wait, 24 ÷ 4 = 6. So 26!"',
    nova: 'Nova: "Hold on, Kai. You can\'t just skip a place. 4 can\'t share 2 tens, so the tens place gets a 0. The answer is 206."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    visual: { type: "blocks", mode: "show", places: ["hundreds", "tens", "ones"], counts: { hundreds: 8, tens: 2, ones: 4 }, title: "824 water flasks for 4 camps" },
    hint: "Estimate first: 800 ÷ 4 = 200. Is 26 close to 200? Then try sharing the 2 tens rods among 4 camps.",
    meter: { heat: 5, label: "Fair share +5%", story: "Kai finds his missing zero" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. 4 can't share 2 tens, so the tens place gets a 0. Check: 206 × 4 = 824." },
      { id: "B", text: "Nova, because every quotient has a zero in it." },
      { id: "C", text: "Kai. If a place can't be shared, you skip it and leave it out." },
      { id: "D", text: "Kai. 26 × 4 = 824." },
    ],
    writtenPrompt: "Tell Kai in your own words why 824 ÷ 4 is 206 and not 26.",
    debateHints: {
      wrongWho: "Check Kai's answer: 26 × 4 = 104. Is that 824? Each camp should get about 200 flasks.",
      wrongReason: "Right person, check the reason. Not every quotient has a zero. Look at what happens with the 2 tens.",
      right: "Nova is right. The 2 tens can't be shared by 4 camps, so they're regrouped into 24 ones and the tens place holds a 0. 206 × 4 = 824!",
    },
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The gondola rush", machine: "Supply Manifest", icon: "static", speaker: "vega",
    line: "Surprise! A storm is rolling in, and the sky gondolas stop at sundown. Here is tonight's supply list for our 6 camps. Read each rule carefully.",
    question: "Part 1: How many water flasks does each camp get? Part 2: How many batteries does each camp get? Part 3: How many batteries go to Nova's spare box? Part 4: How many gondola trips so every camper rides?",
    parts: [
      { type: "number", prompt: "1,446 water flasks are shared equally by 6 camps. How many does each camp get?", unit: "flasks",
        data: {
          title: "Tonight's supply list",
          columns: ["Supply", "Amount", "Rule"],
          rows: [
            ["Water flasks", "1,446", "Share equally with 6 camps"],
            ["Headlamp batteries", "1,000", "Share equally with 6 camps. Extras go to Nova's spare box."],
            ["Campers", "950", "Each gondola trip carries 6. Everyone must ride."],
          ],
        } },
      { type: "number", prompt: "1,000 batteries are shared equally by 6 camps. How many does each camp get?", unit: "batteries" },
      { type: "number", prompt: "How many batteries are left over for Nova's spare box?", unit: "batteries" },
      { type: "number", prompt: "950 campers ride gondolas that carry 6 each trip. How many trips so everyone rides?", unit: "trips" },
    ],
    hint: "Divide each amount by 6. Then read the rule: extras go in a box (the remainder is the answer), and every camper rides (round up).",
    meter: { supplies: 2, label: "Camps supplied +2", story: "Every camp is ready for the storm" },
    discovery: { id: "tarsier", name: "Big-eyed tarsiers", who: "Nova", fact: "Tarsiers are tiny animals from Southeast Asian rainforests. Each of their eyes is about as big as their whole brain." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 241 }, { kind: "number", value: 166 }, { kind: "number", value: 4 }, { kind: "number", value: 159 }] },
    rightFeedback: "1,446 ÷ 6 = 241 flasks. 1,000 ÷ 6 = 166 R 4, so each camp gets 166 batteries and 4 go in the spare box. 950 ÷ 6 = 158 R 2, so 159 trips. Everyone made it before the storm!",
    wrong: [
      { step: 1, value: 1440, hint: "1,446 − 6 takes away only 6 flasks. Share all 1,446 into 6 equal groups." },
      { step: 1, value: 8676, hint: "1,446 × 6 is too big. Each camp gets a part. Divide." },
      { step: 1, value: 201, hint: "Check the tens. 24 tens ÷ 6 = 4 tens, not 0 tens." },
      { step: 2, value: 167, hint: "The rule says extras go to the spare box. Don't round up. Each camp gets the whole-number part." },
      { step: 2, value: 994, hint: "1,000 − 6 subtracts. Share 1,000 into 6 equal groups." },
      { step: 2, value: 16, hint: "Too small! 16 × 6 is only 96. 10 hundreds ÷ 6 is 1 hundred with some left." },
      { step: 3, value: 6, hint: "6 is the number of camps. What is left after 166 × 6 = 996?" },
      { step: 3, value: 10, hint: "10 is more than 6, so each camp could get one more. The leftover must be less than 6." },
      { step: 3, value: 166, hint: "166 is each camp's share. How many batteries are LEFT after sharing?" },
      { step: 4, value: 158, hint: "158 trips carry 948 campers. 2 campers would be left behind! They need one more trip." },
      { step: 4, value: 160, hint: "Don't add the 2 leftover campers to the trips. They fit in just ONE more trip." },
      { step: 4, value: 944, hint: "950 − 6 is only one trip. How many trips of 6 carry 950 campers?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "How big is the share?", machine: "Sort Bay", icon: "brief", speaker: "nova",
    line: "Before we divide, I like to guess how many digits the quotient will have. It's a quick way to catch mistakes.",
    question: "Sort each division by the size of its quotient.",
    hint: "Look at the first digit or two of the dividend. Can the divisor go into the thousands? Into the hundreds? That tells you where the quotient starts.",
    meter: { heat: 5, label: "Fair share +5%", story: "The share sizes are sorted" },
    discovery: { id: "silverback", name: "Silverbacks", who: "Kai", fact: "Gorillas live in family groups. The leader is often a grown male called a silverback, named for the silver hair on his back." },
    answer: { kind: "sort", bins: { q1: "small", q2: "hund", q3: "thou", q4: "small", q5: "hund", q6: "thou" } },
    rightFeedback: "Every card is in the right bin! 378 ÷ 6 = 63, 1,248 ÷ 4 = 312, 7,299 ÷ 3 = 2,433, 425 ÷ 5 = 85, 5,600 ÷ 7 = 800, 6,000 ÷ 5 = 1,200.",
    sort: {
      bins: [
        { id: "small", label: "Less than 100" },
        { id: "hund", label: "100 to 999" },
        { id: "thou", label: "1,000 or more" },
      ],
      items: [
        { id: "q1", label: "378 ÷ 6" },
        { id: "q2", label: "1,248 ÷ 4" },
        { id: "q3", label: "7,299 ÷ 3" },
        { id: "q4", label: "425 ÷ 5" },
        { id: "q5", label: "5,600 ÷ 7" },
        { id: "q6", label: "6,000 ÷ 5" },
      ],
    },
    wrong: [
      { item: "q1", hint: "6 can't go into 3 hundreds, so start with 37 tens. The quotient starts in the tens place." },
      { item: "q2", hint: "4 can't go into 1 thousand, so start with 12 hundreds. The quotient starts in the hundreds place." },
      { item: "q3", hint: "3 goes into 7 thousands. The quotient starts in the thousands place." },
      { item: "q4", hint: "5 can't go into 4 hundreds, so start with 42 tens. The quotient is less than 100." },
      { item: "q5", hint: "7 can't go into 5 thousands, so start with 56 hundreds. 56 hundreds ÷ 7 = 8 hundreds." },
      { item: "q6", hint: "5 goes into 6 thousands once. The quotient starts in the thousands place." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "One split, three answers", machine: "Leftover Lab", icon: "water", speaker: "vega",
    line: "Here's a puzzle. Three problems use the same division, 437 ÷ 4 = 109 R 1. But each one has a different answer! The question tells you what to do with the leftover.",
    question: "Part 1: How many canoes? Part 2: How many full bags? Part 3: How many stickers are left for Kai?",
    parts: [
      { type: "number", prompt: "437 campers cross the river in canoes that hold 4 each. How many canoes so everyone crosses?", unit: "canoes" },
      { type: "number", prompt: "437 mangoes are packed in bags of 4. How many FULL bags can we send?", unit: "bags" },
      { type: "number", prompt: "437 stickers are shared equally by 4 camps. Kai keeps the leftovers. How many does Kai get?", unit: "stickers" },
    ],
    hint: "Every camper must cross: round up. Only full bags count: drop the leftover. Kai gets what's left: the answer is the remainder.",
    meter: { supplies: 1, label: "Camps supplied +1", story: "The leftovers are sorted out" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 110 }, { kind: "number", value: 109 }, { kind: "number", value: 1 }] },
    rightFeedback: "110 canoes so nobody is left on the bank, 109 full bags of mangoes, and 1 sticker for Kai. Same division, three different answers!",
    wrong: [
      { step: 1, value: 109, hint: "With 109 canoes, 1 camper is left on the riverbank. Everyone has to cross." },
      { step: 1, value: 1, hint: "1 is the leftover camper. How many canoes carry ALL 437 campers?" },
      { step: 1, value: 19, hint: "Check the zero! 4 can't share 3 tens, so the tens place is 0. 437 ÷ 4 = 109 R 1." },
      { step: 2, value: 110, hint: "The last bag would only have 1 mango. Only FULL bags count." },
      { step: 2, value: 1, hint: "1 is the leftover mango. How many full bags of 4 are there?" },
      { step: 3, value: 109, hint: "109 is each camp's share. Kai gets only what is LEFT over." },
      { step: 3, value: 4, hint: "4 is the number of camps. What is the remainder of 437 ÷ 4?" },
      { step: 3, value: 0, hint: "Check it: 109 × 4 = 436. That's 1 less than 437." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Kai's giant leftover", machine: "Repair", icon: "snap", speaker: "nova",
    line: 'Kai shared 1,587 glow beads among 5 camps: "Each camp gets 316, and 7 are left over. 316 R 7!" Hmm. Something is off.',
    question: "Part 1: What went wrong? Part 2: What is the right quotient? Part 3: What is the right remainder? Part 4: Check it.",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "His remainder, 7, is more than 5. Each camp can get one more bead." },
        { id: "b", text: "He should have divided by 7 instead of 5." },
        { id: "c", text: "A remainder always has to be 0." },
        { id: "d", text: "Nothing. 316 R 7 is right." },
      ] },
      { type: "number", prompt: "What is the right whole-number part of 1,587 ÷ 5?", unit: "beads" },
      { type: "number", prompt: "What is the right remainder?", unit: "beads" },
      { type: "number", prompt: "Check it: multiply your quotient by 5, then add the remainder. What do you get?", unit: "beads" },
    ],
    hint: "If 7 beads are left, 5 of them can go out as one more bead for each camp. Then check: quotient × 5 + remainder should be 1,587.",
    meter: { supplies: 1, label: "Camps supplied +1", story: "Kai's leftover is fixed" },
    discovery: { id: "batshare", name: "Bats that share", who: "Nova", fact: "Vampire bats share food. A bat that ate well that night will share with a roost-mate that went hungry." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 317 }, { kind: "number", value: 2 }, { kind: "number", value: 1587 }] },
    rightFeedback: "Fixed! 1,587 ÷ 5 = 317 R 2. Check: 317 × 5 = 1,585, and 1,585 + 2 = 1,587. The remainder is always less than the divisor.",
    wrong: [
      { step: 1, choice: "b", hint: "There are 5 camps, so we divide by 5. Look at the size of Kai's leftover." },
      { step: 1, choice: "c", hint: "Remainders don't have to be 0. They just have to be less than the divisor." },
      { step: 1, choice: "d", hint: "7 beads are left, but there are only 5 camps. Could each camp get one more?" },
      { step: 2, value: 316, hint: "That's Kai's answer. 7 leftover beads are enough to give each camp one more." },
      { step: 2, value: 318, hint: "Check it: 318 × 5 = 1,590. That's more beads than we have." },
      { step: 3, value: 7, hint: "7 is more than 5, so it can't be the remainder. Take out 5 more beads for the camps." },
      { step: 3, value: 12, hint: "12 is more than 5. The remainder must be less than the divisor." },
      { step: 4, value: 1585, hint: "317 × 5 = 1,585 is right. Now add the remainder of 2." },
      { step: 4, value: 324, hint: "317 + 5 + 2 adds. Multiply 317 × 5 first, then add the 2." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The big tarp model", machine: "Area Model Awning", icon: "dial", speaker: "kai",
    line: "The festival tarp covers 2,736 square feet, and one side is 8 feet long. Nova drew an area model to find the other side, n. One top side is blank.",
    question: "Part 1: Pick every equation that matches. Part 2: What is the blank top side? Part 3: What is n?",
    parts: [
      { type: "multi", prompt: "Which equations match the area model? Pick every one.", choices: [
        { id: "div", text: "2,736 ÷ 8 = n" },
        { id: "mul", text: "8 × n = 2,736" },
        { id: "flip", text: "8 ÷ 2,736 = n" },
        { id: "add", text: "2,736 + 8 = n" },
        { id: "big", text: "2,736 × 8 = n" },
      ],
        data: {
          title: "Area model · 2,736 ÷ 8",
          columns: ["", "Box 1", "Box 2", "Box 3"],
          rows: [["Top side", "300", "?", "2"], ["Area inside (other side is 8)", "2,400", "320", "16"]],
        } },
      { type: "number", prompt: "8 × ? = 320. What goes on top of Box 2?",
        data: {
          title: "Area model · 2,736 ÷ 8",
          columns: ["", "Box 1", "Box 2", "Box 3"],
          rows: [["Top side", "300", "?", "2"], ["Area inside (other side is 8)", "2,400", "320", "16"]],
        } },
      { type: "number", prompt: "What is n, the other side of the tarp?", unit: "feet" },
    ],
    hint: "Division and multiplication undo each other, so 2,736 ÷ 8 = n and 8 × n = 2,736 say the same thing. 8 × 4 = 32, so 8 × 40 = 320.",
    meter: { heat: 5, label: "Fair share +5%", story: "The festival tarp is measured" },
    answer: { kind: "parts", parts: [{ kind: "multi", correct: ["div", "mul"] }, { kind: "number", value: 40 }, { kind: "number", value: 342 }] },
    rightFeedback: "8 × 40 = 320. The top sides add to 300 + 40 + 2 = 342, so n = 342 feet. 8 × 342 = 2,736!",
    wrong: [
      { step: 1, pick: "flip", hint: "The total goes first when you divide: 2,736 ÷ 8, not 8 ÷ 2,736." },
      { step: 1, pick: "add", hint: "Adding 8 doesn't find a side. The area is split into equal rows of 8." },
      { step: 1, pick: "big", hint: "2,736 is the whole area. Multiplying it by 8 makes it far too big." },
      { step: 1, missing: true, hint: "There are 2 equations that match. One divides, and one multiplies with n as a missing factor." },
      { step: 2, value: 4, hint: "8 × 4 = 32. The box holds 320. What times 8 makes 320?" },
      { step: 2, value: 312, hint: "320 − 8 subtracts. The area model asks: 8 times what equals 320?" },
      { step: 2, value: 2560, hint: "320 × 8 is too big. Find the missing side: 8 × ? = 320." },
      { step: 3, value: 302, hint: "You left out Box 2. Add 300 + 40 + 2." },
      { step: 3, value: 9, hint: "The top sides are 300, 40, and 2, not 3, 4, and 2." },
      { step: 3, value: 21888, hint: "2,736 × 8 is too big. Add the three top sides." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The lantern festival", machine: "Share Table", icon: "relay", speaker: "vega",
    line: "It's the Canopy Lantern Festival! We have 3,624 paper lanterns to share equally with 6 camps. Surprise! A 7th camp just swung in on a rope bridge. Now we have to share with 7 camps!",
    question: "Part 1: Estimate 3,624 ÷ 6. Part 2: Find 3,624 ÷ 6. Part 3: Check it. Part 4: Share with 7 camps. What is the whole-number part? Part 5: How many lanterns are left over?",
    parts: [
      { type: "choice", prompt: "Which is the best estimate for 3,624 ÷ 6?", choices: [
        { id: "a", text: "3,600 ÷ 6 = 600" },
        { id: "b", text: "3,600 ÷ 6 = 60" },
        { id: "c", text: "4,000 ÷ 6 = 700" },
        { id: "d", text: "3,624 ÷ 10 = 362" },
      ] },
      { type: "number", prompt: "What is 3,624 ÷ 6?", unit: "lanterns" },
      { type: "number", prompt: "Check it: what is your quotient × 6?", unit: "lanterns" },
      { type: "number", prompt: "Now share 3,624 lanterns with 7 camps. What is the whole-number part of 3,624 ÷ 7?", unit: "lanterns" },
      { type: "number", prompt: "The leftover lanterns hang at the crew's tent. How many hang there?", unit: "lanterns" },
    ],
    hint: "36 hundreds ÷ 6 = 6 hundreds. 6 can't share 2 tens, so write a 0 and regroup. Then for 7 camps, divide again and keep the leftover.",
    meter: { heat: 10, label: "Fair share +10%", story: "Every camp's lanterns glow" },
    discovery: { id: "pineapple", name: "One pineapple", who: "Kai", fact: "A pineapple plant usually grows just one pineapple at a time. That first pineapple can take up to two years to grow." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 604 }, { kind: "number", value: 3624 }, { kind: "number", value: 517 }, { kind: "number", value: 5 }] },
    rightFeedback: "3,624 ÷ 6 = 604, and 604 × 6 = 3,624. With 7 camps, 3,624 ÷ 7 = 517 R 5, so 5 lanterns glow at the crew's tent. What a festival, specialist!",
    wrong: [
      { step: 1, choice: "b", hint: "Check the place value. 36 hundreds ÷ 6 = 6 hundreds, not 6 tens." },
      { step: 1, choice: "c", hint: "40 ÷ 6 is not a basic fact, and 700 × 6 = 4,200. Pick numbers that divide evenly." },
      { step: 1, choice: "d", hint: "There are 6 camps, not 10. Keep the 6 and pick a friendly number close to 3,624." },
      { step: 2, value: 64, hint: "Don't skip the tens! 6 can't share 2 tens, so the tens place gets a 0." },
      { step: 2, value: 640, hint: "The 0 goes in the tens place, not the ones. Check: 640 × 6 = 3,840." },
      { step: 2, value: 21744, hint: "3,624 × 6 is too big. Each camp gets a part. Divide." },
      { step: 3, value: 384, hint: "That's 64 × 6. Multiply 604 × 6." },
      { step: 3, value: 3604, hint: "604 × 6: 4 × 6 = 24 ones and 6 × 6 = 36 hundreds. Add 3,600 + 24." },
      { step: 4, value: 518, hint: "Check it: 518 × 7 = 3,626. That's more lanterns than we have." },
      { step: 4, value: 57, hint: "Don't skip a place. 36 hundreds ÷ 7 = 5 hundreds, 12 tens ÷ 7 = 1 ten, 54 ones ÷ 7 = 7 ones." },
      { step: 4, value: 604, hint: "604 was the share for 6 camps. Now divide 3,624 by 7." },
      { step: 5, value: 12, hint: "12 is more than 7, so each camp could get another lantern. The leftover must be less than 7." },
      { step: 5, value: 7, hint: "7 is the number of camps. What is left after 517 × 7 = 3,619?" },
      { step: 5, value: 0, hint: "Check it: 517 × 7 = 3,619. That's not 3,624, so some lanterns are left." },
    ],
  },
};

export default {
  id: "MA.4.4F-XP",
  standard: "MA.4.4F-XP",
  engine: "expedition_station",
  title: "The Sharing Station",
  planet: "Solara",
  outpost: "Canopy Camps · sharing day",
  grade: 4,
  subject: "Math",
  teks: "4.4F",
  supportingTeks: ["4.4E", "4.4G"],
  skillsChip: "4.4F · Divide by one-digit numbers",
  iCan: "I can divide a number up to four digits by a one-digit number, show my thinking with models and equations, check with multiplication, and decide what to do with a remainder.",
  blurb: "The canopy camps on Solara's jungle moon share every supply evenly. The crew needs a sharp divider to split seed pods, water flasks, and lanterns among the camps.",
  mission: "Share the supplies evenly across the canopy camps, handle every leftover the right way, and get the Lantern Festival glowing.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.4F · SOLARA SHARING STATION",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Fair share", heatUnit: "%", supplies: "Camps supplied", suppliesUnit: "camps" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're at the Sharing Station in the canopy camps on Solara.",
    "Supply crates just arrived, and every camp must get a fair, equal share.",
    "Kai and Nova need help dividing, checking, and deciding what to do with leftovers. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Open the crates", "Act 2 · Leftover trouble", "Act 3 · The Lantern Festival"],
    completes: [
      "The first crates are shared fairly, {firstName}!",
      "Every leftover was handled, and the camps beat the storm, {firstName}!",
      "The Lantern Festival is glowing, {firstName}! Every camp got its fair share.",
    ],
    teasers: [
      "Next on Solara: some supplies don't split evenly. What do we do with the leftovers? Act 2 is open now, or come back to it next time.",
      "Next on Solara: the Lantern Festival is coming, and a surprise guest is on the way. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Not every supply splits evenly.",
      "Sometimes things are left over, and we have to decide what to do with them.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The Canopy Lantern Festival is almost here.",
      "Help the crew share the last supplies so every camp can join the celebration.",
    ],
  }),
  tasks,
};
