// Expedition Station — The Sighting Board (MA.3.8B-XP)
// Grade 3 · Math · Solara. Main standard 3.8B (solve one- and two-step
// problems using categorical data in a frequency table, dot plot, pictograph,
// or bar graph with scaled intervals); also practices 3.8A (summarize a data
// set with a frequency table, dot plot, pictograph, or scaled bar graph).
// Grade 3 limits: whole numbers within 1,000; scales of 2, 5, 10, 25; picture
// keys of 2 and 10 with half pictures.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Read the first bar", machine: "Sighting Board", icon: "scan", speaker: "nova",
    line: "The canopy tour is back! The crew made a bar graph of the animals they saw this morning. Look at the scale. Each line on the graph goes up by 10.",
    question: "How many howler monkeys did the crew see?",
    unit: "howler monkeys",
    visual: { type: "bars", title: "Morning sightings", categories: [
      { label: "Toucans", value: 40 }, { label: "Sloths", value: 20 }, { label: "Howler monkeys", value: 35 }, { label: "Macaws", value: 50 },
    ], step: 10, max: 50, axis: "Number seen" },
    hint: "Find the top of the howler monkey bar. It stops between two lines. What number is halfway between 30 and 40?",
    meter: { heat: 10, label: "Tour ready +10%", story: "The first bar is read" },
    discovery: { id: "howler", name: "Howler monkeys", who: "Nova", fact: "Howler monkeys are some of the loudest land animals on Earth. Their calls can be heard about 3 miles away." },
    answer: { kind: "number", value: 35 },
    rightFeedback: "The bar stops halfway between 30 and 40. That's 35 howler monkeys!",
    wrong: [
      { value: 30, hint: "The bar goes past the 30 line. It stops halfway to 40. What number is halfway between 30 and 40?" },
      { value: 40, hint: "The bar does not reach the 40 line. It stops halfway between 30 and 40." },
      { value: 4, hint: "It looks like you counted lines. Each line stands for 10 monkeys, not 1. Use the numbers on the scale." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The butterfly pictures", machine: "Picture Board", icon: "cells", speaker: "kai",
    line: "I made a picture graph of the butterflies at the flower stop. Check the key! Each 🦋 stands for 10 butterflies.",
    question: "How many blue morpho butterflies did the crew see?",
    unit: "butterflies",
    visual: { type: "pictograph", title: "Butterflies at the flower stop", icon: "🦋", per: 10, unit: "butterflies", categories: [
      { label: "Blue morphos", value: 45 }, { label: "Glasswings", value: 30 }, { label: "Owl butterflies", value: 25 }, { label: "Postmen", value: 20 },
    ] },
    hint: "Each whole 🦋 is 10. Half a 🦋 is 5. Count by 10s for the whole pictures, then add the half.",
    meter: { heat: 5, label: "Tour ready +5%", story: "The butterflies are counted" },
    discovery: { id: "morpho", name: "Blue morpho butterflies", who: "Kai", fact: "A blue morpho's wings are bright blue on top and brown underneath. When it closes its wings, it can seem to disappear." },
    answer: { kind: "number", value: 45 },
    rightFeedback: "4 whole pictures is 40, and half a picture is 5. 40 + 5 = 45 blue morphos!",
    wrong: [
      { value: 4, hint: "There are 4 whole pictures and a half. But each picture stands for 10 butterflies. Check the key." },
      { value: 40, hint: "You counted the whole pictures. Don't forget the half picture! Half of 10 is 5." },
      { value: 50, hint: "The last picture is only half. Half a 🦋 is 5, not 10." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Frogs at the pond", machine: "Sighting Board", icon: "water", speaker: "nova",
    line: "At the pond stop, we counted frogs. This bar graph has a scale of 2. Each line goes up by 2.",
    question: "How many frogs did the crew see at the pond in all?",
    unit: "frogs",
    visual: { type: "bars", orientation: "horizontal", title: "Frogs at the pond", categories: [
      { label: "Poison dart frogs", value: 9 }, { label: "Glass frogs", value: 6 }, { label: "Red-eyed tree frogs", value: 12 },
    ], step: 2, max: 12, axis: "Number seen" },
    hint: "Read each bar. The poison dart frog bar stops between 8 and 10. Then add all three numbers.",
    meter: { heat: 5, label: "Tour ready +5%", story: "The pond frogs are counted" },
    discovery: { id: "glassfrog", name: "Glass frogs", who: "Nova", fact: "Glass frogs have see-through skin on their bellies. You can look right in and see their hearts beating." },
    answer: { kind: "number", value: 27 },
    rightFeedback: "9 + 6 + 12 = 27 frogs at the pond!",
    wrong: [
      { value: 26, hint: "Check the poison dart frog bar. It stops halfway between 8 and 10. That's 9, not 8." },
      { value: 3, hint: "3 is how many kinds of frogs there are. How many frogs is that in all? Add the bars." },
      { value: 21, hint: "Did you add all three bars? 9 + 6 + 12 = ?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Capybaras by the river", machine: "Dot Plot", icon: "grid", speaker: "kai",
    line: "Capybaras hang out in groups by the river. I made a dot plot. Each ✕ is one group. The number under it tells how many capybaras were in that group.",
    question: "Part 1: How many groups had 5 capybaras? Part 2: How many groups had more than 5 capybaras?",
    parts: [
      { type: "number", prompt: "How many groups had 5 capybaras?", unit: "groups",
        visual: { type: "dotplot", title: "Capybaras in each group", values: [3, 4, 4, 5, 5, 5, 5, 6, 6, 8], min: 3, max: 8, axis: "Capybaras in the group" } },
      { type: "number", prompt: "How many groups had MORE than 5 capybaras?", unit: "groups",
        visual: { type: "dotplot", title: "Capybaras in each group", values: [3, 4, 4, 5, 5, 5, 5, 6, 6, 8], min: 3, max: 8, axis: "Capybaras in the group" } },
    ],
    hint: "Count the ✕ marks above a number. For Part 2, count the ✕ marks above 6, 7, and 8.",
    meter: { heat: 5, label: "Tour ready +5%", story: "The capybara groups are counted" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 4 }, { kind: "number", value: 3 }] },
    rightFeedback: "4 groups had 5 capybaras. 2 groups had 6 and 1 group had 8, so 3 groups had more than 5!",
    wrong: [
      { step: 1, value: 5, hint: "5 is the label under the column. Count the ✕ marks above the 5." },
      { step: 1, value: 10, hint: "10 is all the groups. How many ✕ marks are above the 5 only?" },
      { step: 2, value: 2, hint: "You found the 6s. Look farther right. Is there a group bigger than 6?" },
      { step: 2, value: 7, hint: "More than 5 does not include 5. Count only the ✕ marks above 6, 7, and 8." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The macaw flock", machine: "Sighting Board", icon: "snap", speaker: "vega",
    line: "Surprise! Just after the crew made this graph, a flock of 20 more macaws flew over the tour! This graph has a scale of 5.",
    question: "Part 1: How many macaws are on the graph? Part 2: Add the 20 new macaws. Now how many more macaws than toucans did the crew see?",
    parts: [
      { type: "number", prompt: "How many macaws are on the graph?", unit: "macaws",
        visual: { type: "bars", orientation: "horizontal", title: "Birds at the fruit tree", categories: [
          { label: "Toucans", value: 15 }, { label: "Macaws", value: 35 }, { label: "Parrots", value: 25 },
        ], step: 5, max: 40, axis: "Number seen" } },
      { type: "number", prompt: "20 more macaws flew over. Now how many more macaws than toucans?", unit: "macaws",
        visual: { type: "bars", orientation: "horizontal", title: "Birds at the fruit tree", categories: [
          { label: "Toucans", value: 15 }, { label: "Macaws", value: 35 }, { label: "Parrots", value: 25 },
        ], step: 5, max: 40, axis: "Number seen" } },
    ],
    hint: "Each line is 5. First add the 20 new macaws to the macaw bar. Then subtract the toucans.",
    meter: { heat: 10, label: "Tour ready +10%", story: "The macaw flock is on the board" },
    discovery: { id: "claylick", name: "Macaw clay licks", who: "Nova", fact: "Big flocks of macaws gather on riverbanks to eat clay. Scientists think the clay gives them salt they can't get from fruit." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 35 }, { kind: "number", value: 40 }] },
    rightFeedback: "35 + 20 = 55 macaws. 55 − 15 = 40 more macaws than toucans!",
    wrong: [
      { step: 1, value: 7, hint: "You counted 7 lines. Each line stands for 5 birds. Count by 5s." },
      { step: 1, value: 30, hint: "The macaw bar goes past 30. Count by 5s: 30, 35. Where does it stop?" },
      { step: 2, value: 20, hint: "35 − 15 = 20. But 20 more macaws flew over! Add them first." },
      { step: 2, value: 55, hint: "55 is all the macaws now. How many MORE than the 15 toucans? Subtract." },
      { step: 2, value: 70, hint: "\"How many more\" means compare. Subtract the toucans. Don't add them." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Match the night walk", machine: "Tally Tablet", icon: "log", speaker: "nova",
    line: "Last night we took a night walk. I wrote the animals in a frequency table. Kai drew three picture graphs, but only one matches.",
    question: "Part 1: Which picture graph matches the table? Part 2: How many more bats than kinkajous did we see?",
    data: {
      title: "Night walk sightings",
      columns: ["Animal", "Number seen"],
      rows: [["Kinkajous", "20"], ["Tree frogs", "30"], ["Bats", "50"]],
    },
    parts: [
      { type: "choice", prompt: "Which picture graph matches the table?", choices: [
        { id: "a", text: "Key 🐾 = 10 · Kinkajous 🐾🐾 · Tree frogs 🐾🐾🐾 · Bats 🐾🐾🐾🐾🐾" },
        { id: "b", text: "Key 🐾 = 5 · Kinkajous 🐾🐾 · Tree frogs 🐾🐾🐾 · Bats 🐾🐾🐾🐾🐾" },
        { id: "c", text: "Key 🐾 = 10 · Kinkajous 🐾🐾 · Tree frogs 🐾🐾🐾🐾🐾 · Bats 🐾🐾🐾" },
        { id: "d", text: "Key 🐾 = 1 · Kinkajous 🐾🐾 · Tree frogs 🐾🐾🐾 · Bats 🐾🐾🐾🐾🐾" },
      ] },
      { type: "number", prompt: "Nova also made a bar graph. How many more bats than kinkajous?", unit: "animals",
        visual: { type: "bars", title: "Night walk sightings", categories: [
          { label: "Kinkajous", value: 20 }, { label: "Tree frogs", value: 30 }, { label: "Bats", value: 50 },
        ], step: 10, max: 50, axis: "Number seen" } },
    ],
    hint: "Use the key. Multiply the pictures by the key and check each row against the table.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The night walk stop is planned" },
    discovery: { id: "kinkajou", name: "Kinkajous", who: "Kai", fact: "Kinkajous come out at night. They use their long tongues to lick nectar from flowers, so some people call them honey bears." },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 30 }] },
    rightFeedback: "2, 3, and 5 pictures worth 10 each make 20, 30, and 50. Bats 50 − kinkajous 20 = 30 more bats!",
    wrong: [
      { step: 1, choice: "b", hint: "With a key of 5, the bats would be 5 × 5 = 25. The table says 50. Check the key." },
      { step: 1, choice: "c", hint: "The tree frogs and bats got switched. The table says tree frogs 30 and bats 50." },
      { step: 1, choice: "d", hint: "With a key of 1, the bats would be only 5. The table says 50." },
      { step: 2, value: 70, hint: "50 + 20 = 70. \"How many more\" means compare. Subtract." },
      { step: 2, value: 3, hint: "The bat bar is 3 lines taller. But each line stands for 10. What is 50 − 20?" },
      { step: 2, value: 20, hint: "20 is the number of kinkajous. How many MORE bats are there than that?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The sloth picture debate", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Look at Stop 2 on the sloth graph. I counted 5 pictures. So we saw 5 sloths at Stop 2!"',
    nova: 'Nova: "Check the key. Each 🦥 stands for 2 sloths. 5 pictures of 2 is 10 sloths at Stop 2."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    data: {
      title: "Sloth sightings · Key: 🦥 = 2 sloths",
      columns: ["Tour stop", "Pictures"],
      rows: [["Stop 1", "🦥🦥🦥"], ["Stop 2", "🦥🦥🦥🦥🦥"], ["Stop 3", "🦥🦥"]],
    },
    hint: "Read the key first. How many sloths does one picture stand for?",
    meter: { heat: 5, label: "Tour ready +5%", story: "Kai learns to read the key" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. The key says each picture is 2 sloths. 5 pictures is 2 + 2 + 2 + 2 + 2 = 10 sloths." },
      { id: "B", text: "Nova, because 10 is a bigger number, and bigger is always better." },
      { id: "C", text: "Kai. Each picture is one sloth, so just count the pictures." },
      { id: "D", text: "Kai. The key doesn't matter when you read a picture graph." },
    ],
    writtenPrompt: "Tell Kai in your own words why Stop 2 had 10 sloths, not 5.",
    debateHints: {
      wrongWho: "Look at the key: 🦥 = 2 sloths. If one picture is 2 sloths, can 5 pictures be only 5 sloths?",
      wrongReason: "Right person, check the reason. What does the key tell you about each picture?",
      right: "Nova is right. Each picture is 2 sloths, so 5 pictures is 10 sloths.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Frog stops", machine: "Picture Board", icon: "cells", speaker: "nova",
    line: "Poison dart frogs are tiny, but we found lots of them! Each 🐸 stands for 10 frogs. A half 🐸 stands for 5.",
    question: "Part 1: How many frogs were at the fern and the tree hole in all? Part 2: How many more frogs were at the log than at the fern and tree hole together?",
    parts: [
      { type: "number", prompt: "How many frogs were at the fern and the tree hole in all?", unit: "frogs",
        visual: { type: "pictograph", title: "Poison dart frogs at each stop", icon: "🐸", per: 10, unit: "frogs", categories: [
          { label: "Stream", value: 35 }, { label: "Log", value: 50 }, { label: "Fern", value: 15 }, { label: "Tree hole", value: 20 },
        ] } },
      { type: "number", prompt: "How many more frogs were at the log than at the fern and tree hole together?", unit: "frogs",
        visual: { type: "pictograph", title: "Poison dart frogs at each stop", icon: "🐸", per: 10, unit: "frogs", categories: [
          { label: "Stream", value: 35 }, { label: "Log", value: 50 }, { label: "Fern", value: 15 }, { label: "Tree hole", value: 20 },
        ] } },
    ],
    hint: "Fern is 1 and a half pictures: 10 + 5. Tree hole is 2 pictures: 10 + 10. Add them. Then compare with the log.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The frog stops are planned" },
    discovery: { id: "tadpoleride", name: "Frog piggyback rides", who: "Nova", fact: "Some poison dart frog parents carry their tadpoles on their backs. They climb up trees to drop them into tiny pools of water inside plants." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 35 }, { kind: "number", value: 15 }] },
    rightFeedback: "15 + 20 = 35 frogs. The log had 50, and 50 − 35 = 15 more frogs!",
    wrong: [
      { step: 1, value: 30, hint: "Did you count the half picture at the fern as 0? Half a 🐸 is 5." },
      { step: 1, value: 40, hint: "The fern has only half of its second picture. Half a 🐸 is 5, not 10." },
      { step: 1, value: 3, hint: "There are 3 and a half pictures. But each picture stands for 10 frogs. Use the key." },
      { step: 2, value: 85, hint: "50 + 35 = 85. \"How many more\" means compare. Subtract." },
      { step: 2, value: 35, hint: "35 is the fern and tree hole together. How many MORE did the log have than that?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's bird count", machine: "Repair", icon: "log", speaker: "nova",
    line: 'Kai wrote in the log: "The toucan bar goes up 3 lines. So we saw 3 toucans this week." But this graph has a scale of 25. Something is off.',
    question: "Part 1: What went wrong? Part 2: How many toucans did the crew really see?",
    parts: [
      { type: "choice", prompt: "What did Kai do wrong?", choices: [
        { id: "a", text: "He counted the grid lines. Each line stands for 25 birds, so he needs to count by 25s." },
        { id: "b", text: "He read the wrong bar. He should have read the parrot bar." },
        { id: "c", text: "He should have added the lines: 25 + 3." },
        { id: "d", text: "Nothing. 3 toucans is right." },
      ],
        visual: { type: "bars", title: "Birds seen this week", categories: [
          { label: "Parrots", value: 150 }, { label: "Toucans", value: 75 }, { label: "Macaws", value: 125 }, { label: "Hummingbirds", value: 200 },
        ], step: 25, max: 200, axis: "Number seen" } },
      { type: "number", prompt: "Count by 25s up the toucan bar. How many toucans?", unit: "toucans",
        visual: { type: "bars", title: "Birds seen this week", categories: [
          { label: "Parrots", value: 150 }, { label: "Toucans", value: 75 }, { label: "Macaws", value: 125 }, { label: "Hummingbirds", value: 200 },
        ], step: 25, max: 200, axis: "Number seen" } },
    ],
    hint: "Look at the numbers on the scale: 0, 25, 50, 75. Each line jumps by 25, not by 1.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The bird log is fixed" },
    answer: { kind: "parts", parts: [{ kind: "choice", correct: "a" }, { kind: "number", value: 75 }] },
    rightFeedback: "Fixed! Count by 25s: 25, 50, 75. The crew saw 75 toucans.",
    wrong: [
      { step: 1, choice: "b", hint: "Kai read the toucan bar, and that's the right bar. The problem is how he read it." },
      { step: 1, choice: "c", hint: "25 + 3 = 28. That's not how a scale works. Each line is another 25." },
      { step: 1, choice: "d", hint: "Read the numbers on the scale. Does each line go up by 1?" },
      { step: 2, value: 3, hint: "That's Kai's answer. Each line stands for 25 birds. Count by 25s three times." },
      { step: 2, value: 30, hint: "Each line is 25, not 10. Count by 25s: 25, 50, ..." },
      { step: 2, value: 70, hint: "Close! Count by 25s: 25, 50, 75. Where does the toucan bar stop?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The monkey bridge", machine: "Sighting Board", icon: "quake", speaker: "vega",
    line: "Surprise! Monkeys swarmed the canopy bridge today. Nova graphed them fast. The scale goes up by 10.",
    question: "Part 1: How many howler monkeys and capuchins did the crew see in all? Part 2: How many more squirrel monkeys were there than howler monkeys and capuchins together?",
    parts: [
      { type: "number", prompt: "How many howler monkeys and capuchins in all?", unit: "monkeys",
        visual: { type: "bars", title: "Monkeys on the canopy bridge", categories: [
          { label: "Spider monkeys", value: 60 }, { label: "Howler monkeys", value: 45 }, { label: "Squirrel monkeys", value: 80 }, { label: "Capuchins", value: 25 },
        ], step: 10, max: 80, axis: "Number seen" } },
      { type: "number", prompt: "How many more squirrel monkeys than howler monkeys and capuchins together?", unit: "monkeys",
        visual: { type: "bars", title: "Monkeys on the canopy bridge", categories: [
          { label: "Spider monkeys", value: 60 }, { label: "Howler monkeys", value: 45 }, { label: "Squirrel monkeys", value: 80 }, { label: "Capuchins", value: 25 },
        ], step: 10, max: 80, axis: "Number seen" } },
    ],
    hint: "Two bars stop between lines. Howlers stop halfway between 40 and 50. Capuchins stop halfway between 20 and 30. Add them, then compare with the squirrel monkeys.",
    meter: { heat: 10, label: "Tour ready +10%", story: "The monkey bridge is counted" },
    discovery: { id: "spidermonkey", name: "Spider monkeys", who: "Kai", fact: "Spider monkeys use their long tails like an extra hand. They can hang from a branch by just their tail." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 70 }, { kind: "number", value: 10 }] },
    rightFeedback: "45 + 25 = 70. Squirrel monkeys 80 − 70 = 10 more squirrel monkeys!",
    wrong: [
      { step: 1, value: 60, hint: "Did you read 40 and 20? Both bars stop halfway past a line. They are 45 and 25." },
      { step: 1, value: 80, hint: "Did you read 50 and 30? Both bars stop halfway, not at the next line." },
      { step: 1, value: 7, hint: "Each line stands for 10 monkeys, not 1. Read the numbers on the scale." },
      { step: 2, value: 150, hint: "80 + 70 = 150. \"How many more\" means compare. Subtract." },
      { step: 2, value: 35, hint: "80 − 45 = 35. Compare with howlers AND capuchins together: 70." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "True or false at the river", machine: "Tally Tablet", icon: "water", speaker: "kai",
    line: "Here's the frequency table for the river stop. The crew wrote some statements for the tour sign, but some of them are false!",
    question: "Sort each statement. Is it true or false?",
    data: {
      title: "Animals at the river stop",
      columns: ["Animal", "Number seen"],
      rows: [["Capybaras", "60"], ["Caimans", "25"], ["Giant river otters", "15"], ["Tapirs", "10"]],
    },
    hint: "Check each statement with the table. For \"how many more,\" subtract. For \"in all,\" add.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The river sign is true" },
    discovery: { id: "giantotter", name: "Giant river otters", who: "Nova", fact: "Giant river otters can grow almost as long as a grown-up is tall. They live and hunt fish in family groups." },
    answer: { kind: "sort", bins: { s1: "true", s2: "true", s3: "false", s4: "false", s5: "true", s6: "false" } },
    rightFeedback: "Every statement is in the right bin! The river sign is ready.",
    sort: {
      bins: [
        { id: "true", label: "True" },
        { id: "false", label: "False" },
      ],
      items: [
        { id: "s1", label: "The crew saw 35 more capybaras than caimans." },
        { id: "s2", label: "Otters and tapirs together were 25 animals." },
        { id: "s3", label: "Caimans were seen the most." },
        { id: "s4", label: "The crew saw 100 animals in all." },
        { id: "s5", label: "There were more capybaras than caimans, otters, and tapirs put together." },
        { id: "s6", label: "There were 10 fewer otters than tapirs." },
      ],
    },
    wrong: [
      { item: "s1", hint: "60 − 25 = 35. So the crew did see 35 more capybaras than caimans." },
      { item: "s2", hint: "15 + 10 = 25. Check it again." },
      { item: "s3", hint: "Compare the numbers. Which animal has the biggest number?" },
      { item: "s4", hint: "Add all four: 60 + 25 + 15 + 10. Is that 100?" },
      { item: "s5", hint: "25 + 15 + 10 = 50. Is 60 more than 50?" },
      { item: "s6", hint: "There were 15 otters and 10 tapirs. Were there fewer otters?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Draw the bird graph", machine: "Picture Board", icon: "grid", speaker: "nova",
    line: "I tallied the birds at the fruit tree. Now Kai is drawing a picture graph. His key says each 🐦 stands for 2 birds.",
    question: "Part 1: How many pictures should Kai draw for the toucans? Part 2: Pick every true statement about the finished graph.",
    data: {
      title: "Birds at the fruit tree",
      columns: ["Bird", "Number seen"],
      rows: [["Toucans", "14"], ["Parrots", "9"], ["Macaws", "6"]],
    },
    parts: [
      { type: "number", prompt: "Each 🐦 = 2 birds. How many pictures should Kai draw for 14 toucans?", unit: "pictures" },
      { type: "multi", prompt: "Here is Kai's finished graph. Pick every true statement.", choices: [
        { id: "most", text: "Toucans were seen the most." },
        { id: "more8", text: "There were 8 more toucans than macaws." },
        { id: "all29", text: "The crew saw 29 birds in all." },
        { id: "parrot4", text: "There were 4 parrots, because there are 4 whole pictures." },
        { id: "macawmost", text: "Macaws were seen the most." },
      ],
        visual: { type: "pictograph", title: "Birds at the fruit tree", icon: "🐦", per: 2, unit: "birds", categories: [
          { label: "Toucans", value: 14 }, { label: "Parrots", value: 9 }, { label: "Macaws", value: 6 },
        ] } },
    ],
    hint: "Each picture is 2 birds. Count by 2s to 14. For the half picture, half of 2 is 1.",
    meter: { heat: 5, label: "Tour ready +5%", story: "The bird graph is drawn" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 7 }, { kind: "multi", correct: ["most", "more8", "all29"] }] },
    rightFeedback: "14 ÷ 2 = 7 pictures. Toucans 14 is the most, 14 − 6 = 8, and 14 + 9 + 6 = 29!",
    wrong: [
      { step: 1, value: 14, hint: "14 is the number of toucans. Each picture stands for 2 birds, so Kai needs fewer pictures." },
      { step: 1, value: 28, hint: "That's 14 pictures of 2 birds, which would be 28 toucans. Count by 2s up to 14." },
      { step: 1, value: 12, hint: "14 − 2 = 12. Count by 2s: 2, 4, 6, ... How many jumps to reach 14?" },
      { step: 2, pick: "parrot4", hint: "The parrots have 4 whole pictures AND a half. That's 8 + 1 = 9 parrots." },
      { step: 2, pick: "macawmost", hint: "Macaws have the fewest pictures. Which row is longest?" },
      { step: 2, missing: true, hint: "Three statements are true. Check the most, the \"how many more,\" and the \"in all.\"" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Rare animal dots", machine: "Dot Plot", icon: "scan", speaker: "kai",
    line: "Some rainforest animals are hard to spot. Every time the crew saw a rare animal, Nova put an ✕ above its name.",
    question: "Part 1: How many rare animals did the crew spot in all? Part 2: How many more ocelots than harpy eagles did they spot?",
    parts: [
      { type: "number", prompt: "How many rare animals did the crew spot in all?", unit: "animals",
        visual: { type: "dotplot", title: "Rare animal sightings", values: [0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3], min: 0, max: 3, labels: ["Jaguar", "Ocelot", "Harpy eagle", "Tapir"], axis: "Each ✕ is one sighting" } },
      { type: "number", prompt: "How many more ocelots than harpy eagles?", unit: "sightings",
        visual: { type: "dotplot", title: "Rare animal sightings", values: [0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3], min: 0, max: 3, labels: ["Jaguar", "Ocelot", "Harpy eagle", "Tapir"], axis: "Each ✕ is one sighting" } },
    ],
    hint: "Count the ✕ marks above each name. Then add them all. For Part 2, subtract.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The rare animal stop is planned" },
    discovery: { id: "harpy", name: "Harpy eagles", who: "Nova", fact: "Harpy eagles have back claws about as long as a grizzly bear's. They swoop through the canopy to catch sloths and monkeys." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 14 }, { kind: "number", value: 3 }] },
    rightFeedback: "3 + 5 + 2 + 4 = 14 rare animals. Ocelots 5 − harpy eagles 2 = 3 more!",
    wrong: [
      { step: 1, value: 4, hint: "4 is how many kinds of animals. Count every ✕ mark." },
      { step: 1, value: 13, hint: "Close! Count again: jaguar 3, ocelot 5, harpy eagle 2, tapir 4." },
      { step: 2, value: 7, hint: "5 + 2 = 7. \"How many more\" means compare. Subtract." },
      { step: 2, value: 5, hint: "5 is the number of ocelots. How many MORE than the 2 harpy eagles?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Plan the bridge", machine: "Tour Planner", icon: "trail", speaker: "vega",
    line: "Visitors picked the stops they want to see. The canopy bridge can hold 300 visitors today. The Monkey bridge and the Sloth tree are both on the bridge.",
    question: "Part 1: How many visitors want the Monkey bridge and the Sloth tree in all? Part 2: How many more visitors could still fit on the bridge today?",
    parts: [
      { type: "number", prompt: "How many visitors want the Monkey bridge and the Sloth tree in all?", unit: "visitors",
        visual: { type: "bars", orientation: "horizontal", title: "Visitors who want each stop", categories: [
          { label: "Frog pond", value: 175 }, { label: "Sloth tree", value: 125 }, { label: "Monkey bridge", value: 150 }, { label: "Butterfly garden", value: 100 },
        ], step: 25, max: 200, axis: "Number of visitors" } },
      { type: "number", prompt: "The bridge holds 300 visitors. How many more visitors could still fit?", unit: "visitors",
        visual: { type: "bars", orientation: "horizontal", title: "Visitors who want each stop", categories: [
          { label: "Frog pond", value: 175 }, { label: "Sloth tree", value: 125 }, { label: "Monkey bridge", value: 150 }, { label: "Butterfly garden", value: 100 },
        ], step: 25, max: 200, axis: "Number of visitors" } },
    ],
    hint: "Each line is 25. Read the two bars and add. Then subtract from 300.",
    meter: { supplies: 1, label: "Tour stops +1", story: "The bridge plan is set" },
    answer: { kind: "parts", parts: [{ kind: "number", value: 275 }, { kind: "number", value: 25 }] },
    rightFeedback: "150 + 125 = 275 visitors. 300 − 275 = 25 more visitors can fit!",
    wrong: [
      { step: 1, value: 250, hint: "Check the Sloth tree bar. It stops halfway between 100 and 150. That's 125." },
      { step: 1, value: 11, hint: "Each line stands for 25 visitors, not 1. Read the numbers on the scale." },
      { step: 1, value: 325, hint: "That's the Frog pond and the Monkey bridge. Read the Sloth tree bar instead." },
      { step: 2, value: 575, hint: "300 + 275 = 575. The bridge only holds 300. Subtract to find how many more can fit." },
      { step: 2, value: 275, hint: "275 visitors already want to go. How many more fit before the bridge is full at 300?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The last tour", machine: "Sighting Board", icon: "relay", speaker: "vega",
    line: "This is the last tour of the season! Here's the final graph. Surprise! A late tour group just radioed in. They saw 15 more sloths!",
    question: "Part 1: How many howler monkeys are on the graph? Part 2: Add the 15 new sloths. How many sloths now? Part 3: How many more howler monkeys than sloths are there now?",
    parts: [
      { type: "number", prompt: "How many howler monkeys are on the graph?", unit: "howler monkeys",
        visual: { type: "bars", title: "Last tour sightings", categories: [
          { label: "Toucans", value: 65 }, { label: "Sloths", value: 30 }, { label: "Howler monkeys", value: 85 }, { label: "Tree frogs", value: 50 },
        ], step: 10, max: 90, axis: "Number seen" } },
      { type: "number", prompt: "The late group saw 15 more sloths. How many sloths now?", unit: "sloths",
        visual: { type: "bars", title: "Last tour sightings", categories: [
          { label: "Toucans", value: 65 }, { label: "Sloths", value: 30 }, { label: "Howler monkeys", value: 85 }, { label: "Tree frogs", value: 50 },
        ], step: 10, max: 90, axis: "Number seen" } },
      { type: "number", prompt: "How many more howler monkeys than sloths are there now?", unit: "animals" },
    ],
    hint: "Read the howler bar: it stops halfway between 80 and 90. Add the new sloths to the sloth bar. Then subtract.",
    meter: { heat: 10, label: "Tour ready +10%", story: "The canopy tour is a success" },
    discovery: { id: "redeye", name: "Red-eyed tree frogs", who: "Kai", fact: "Red-eyed tree frogs sleep on leaves in the day. If something scares them, they pop open their big red eyes to surprise it." },
    answer: { kind: "parts", parts: [{ kind: "number", value: 85 }, { kind: "number", value: 45 }, { kind: "number", value: 40 }] },
    rightFeedback: "85 howler monkeys. 30 + 15 = 45 sloths. 85 − 45 = 40 more howler monkeys. The tour is a hit!",
    wrong: [
      { step: 1, value: 80, hint: "The howler bar goes past 80. It stops halfway to 90." },
      { step: 1, value: 90, hint: "The howler bar does not reach 90. It stops halfway between 80 and 90." },
      { step: 1, value: 8, hint: "Each line stands for 10 monkeys, not 1. Use the numbers on the scale." },
      { step: 2, value: 15, hint: "15 is how many new sloths. Add them to the 30 already on the graph." },
      { step: 2, value: 35, hint: "Check your adding: 30 + 15 = ?" },
      { step: 3, value: 55, hint: "85 − 30 = 55. But there are 45 sloths now. Use the new number." },
      { step: 3, value: 130, hint: "85 + 45 = 130. \"How many more\" means compare. Subtract." },
    ],
  },
};

export default {
  id: "MA.3.8B-XP",
  standard: "MA.3.8B-XP",
  engine: "expedition_station",
  title: "The Sighting Board",
  planet: "Solara",
  outpost: "Canopy Tour · animal season",
  grade: 3,
  subject: "Math",
  teks: "3.8B",
  supportingTeks: ["3.8A"],
  skillsChip: "3.8B · Solve problems with graphs",
  iCan: "I can read frequency tables, dot plots, picture graphs, and bar graphs with scales. I can use them to solve one-step and two-step problems.",
  blurb: "Solara's jungle moon is full of animals. The crew is running a canopy tour, and every sighting goes up on the board as a graph.",
  mission: "Graph the animal sightings on the canopy tour and use the graphs to plan the tour.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.8B · SOLARA CANOPY TOUR",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Tour ready", heatUnit: "%", supplies: "Tour stops", suppliesUnit: "stops" },
  journalMax: 10,
  grade3Limits: "Whole numbers within 1,000. Scales of 2, 5, 10, and 25. Picture keys of 2 and 10 with half pictures.",
  opening: [
    "Specialist {firstName}, this is Commander Vega. It's animal season on Solara's jungle moon.",
    "Our canopy tour spots toucans, sloths, monkeys, and frogs every day. Every sighting goes up on the Sighting Board as a graph.",
    "Help Kai and Nova read the graphs and plan the best tour yet. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The morning sightings", "Act 2 · Check the graphs", "Act 3 · Plan the tour"],
    completes: [
      "The morning sightings are on the board, {firstName}!",
      "The graphs are checked and Kai's log is fixed, {firstName}!",
      "The canopy tour is planned and it was a hit, {firstName}! Great graph reading.",
    ],
    teasers: [
      "Next on Solara: some of the crew's graphs need checking. Act 2 is open now, or come back to it next time.",
      "Next on Solara: time to plan the last tour of the season. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. We have more graphs from the night walk and the bird stops.",
      "Kai's counts are a little mixed up, so let's check them together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Visitors are lining up for the last canopy tour.",
      "Use the graphs to plan every stop.",
    ],
  }),
  tasks,
};
