// Expedition Station — The Signal Race (MA.3.2D-XP)
// Grade 3 · Math · Cloudreach. Main standard 3.2D (compare and order whole
// numbers up to 100,000 and represent comparisons using >, <, or =); also
// practices 3.2C (represent a number on a number line as being between two
// consecutive multiples of 10; 100; 1,000; or 10,000 and use words to describe
// relative size of numbers in order to round whole numbers).
// Number lines with pick: true let the student tap a tick; ticks are the only
// values a tap can enter, so wrong numline answers are also tick values.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Line up the places", machine: "Score Board", icon: "grid", speaker: "kai",
    line: "The first two sky-racers just zoomed through the cloud gate! Their signal scores popped up on the board. I put the digits in place-value columns.",
    question: "Part 1: Which place is the first place where the two scores are different? Part 2: Pick the symbol that makes this true: 4,725 ___ 4,752.",
    data: {
      title: "Cloud gate 1 · signal scores",
      columns: ["Racer", "Thousands", "Hundreds", "Tens", "Ones"],
      rows: [
        ["Wren", "4", "7", "2", "5"],
        ["Zephyr", "4", "7", "5", "2"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Start at the greatest place and move right. Which place is the first one with different digits?", choices: [
        { id: "a", text: "the tens place" },
        { id: "b", text: "the thousands place" },
        { id: "c", text: "the hundreds place" },
        { id: "d", text: "the ones place" },
      ] },
      { type: "choice", prompt: "4,725 ___ 4,752", choices: [
        { id: "a", text: "<" },
        { id: "b", text: ">" },
        { id: "c", text: "=" },
      ] },
    ],
    hint: "Compare from left to right. Skip the places that match. The first place that is different decides which number is greater.",
    meter: { heat: 10, label: "Signal strength +10%", story: "The score board is online" },
    discovery: { id: "morse", name: "Dots and dashes", who: "Nova", fact: "In 1844, Samuel Morse sent a message by telegraph from Washington, D.C., to Baltimore. His code turned letters into short and long clicks called dots and dashes." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The thousands and hundreds match. In the tens place, 2 tens is less than 5 tens, so 4,725 < 4,752!",
    wrong: [
      { step: 1, choice: "b", hint: "Both scores have 4 thousands. They match, so keep moving right." },
      { step: 1, choice: "c", hint: "Both scores have 7 hundreds. They match, so keep moving right." },
      { step: 1, choice: "d", hint: "The ones are different, but there is a place before the ones that is already different. Which one?" },
      { step: 2, choice: "b", hint: "Look at the tens. Wren has 2 tens and Zephyr has 5 tens. Which is less?" },
      { step: 2, choice: "c", hint: "Equal means every digit matches. These scores have different tens and ones." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Find the beacon spot", machine: "Sky Ruler", icon: "trail", speaker: "nova",
    line: "Racer Gale's beacon sent a score of 3,470. Let's put it on the sky ruler. Each jump on this ruler is 10.",
    question: "Part 1: Tap 3,470 on the sky ruler. Part 2: 3,470 is between which two hundreds?",
    parts: [
      { type: "number", prompt: "Count by tens from 3,400. Tap 3,470.", visual: { type: "numline", min: 3400, max: 3500, step: 10, pick: true, title: "Sky ruler · each jump is 10", label: "Signal score" } },
      { type: "choice", prompt: "3,470 is between which two hundreds?", choices: [
        { id: "a", text: "3,400 and 3,500" },
        { id: "b", text: "3,000 and 4,000" },
        { id: "c", text: "3,460 and 3,480" },
        { id: "d", text: "3,500 and 3,600" },
      ] },
    ],
    hint: "Start at 3,400 and count by tens: 3,410, 3,420, 3,430... Which two hundreds sit at the ends of the ruler?",
    meter: { heat: 5, label: "Signal strength +5%", story: "Gale's beacon is on the ruler" },
    discovery: { id: "zero", name: "The idea of zero", who: "Nova", fact: "Using zero as a number came from India more than 1,000 years ago. Zero holds an empty place, so we can tell 305 from 35." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 3470 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "3,470 sits 7 jumps past 3,400. It is between the hundreds 3,400 and 3,500!",
    wrong: [
      { step: 1, value: 3460, hint: "That's 3,460. Count one more jump of 10." },
      { step: 1, value: 3480, hint: "That's 3,480, one jump too far. Count by tens from 3,400 again." },
      { step: 1, value: 3500, hint: "3,500 is the end of the ruler. 3,470 comes before it." },
      { step: 2, choice: "b", hint: "Those are thousands, not hundreds. What hundreds are at the ends of the ruler?" },
      { step: 2, choice: "c", hint: "Those are tens, not hundreds. Look at the two ends of the ruler." },
      { step: 2, choice: "d", hint: "3,470 is less than 3,500, so it can't be between 3,500 and 3,600." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Neck and neck", machine: "Signal Scale", icon: "dial", speaker: "kai",
    line: "Whoa, two racers in the high clouds are almost tied! Nimbus sent 58,301 and Breeze sent 58,310.",
    question: "Part 1: Pick the symbol: 58,301 ___ 58,310. Part 2: Which sentence means the same thing?",
    data: {
      title: "High cloud gate · signal scores",
      columns: ["Racer", "Ten thousands", "Thousands", "Hundreds", "Tens", "Ones"],
      rows: [
        ["Nimbus", "5", "8", "3", "0", "1"],
        ["Breeze", "5", "8", "3", "1", "0"],
      ],
    },
    parts: [
      { type: "choice", prompt: "58,301 ___ 58,310", choices: [
        { id: "a", text: "<" },
        { id: "b", text: ">" },
        { id: "c", text: "=" },
      ] },
      { type: "choice", prompt: "Which sentence means the same thing as your answer?", choices: [
        { id: "a", text: "58,310 > 58,301" },
        { id: "b", text: "58,310 < 58,301" },
        { id: "c", text: "58,301 = 58,310" },
        { id: "d", text: "58,301 > 58,310" },
      ] },
    ],
    hint: "The ten thousands, thousands, and hundreds match. Look at the tens. The open side of the symbol faces the greater number.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "Nimbus and Breeze are compared" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "0 tens is less than 1 ten, so 58,301 < 58,310. Flip it around and 58,310 > 58,301!",
    wrong: [
      { step: 1, choice: "b", hint: "Nimbus has a 1 in the ones, but compare the tens first. 0 tens or 1 ten, which is more?" },
      { step: 1, choice: "c", hint: "The digits are the same, but they are in different places. The numbers are not equal." },
      { step: 2, choice: "b", hint: "That says 58,310 is less. Is it? Check the tens again." },
      { step: 2, choice: "c", hint: "The scores are not equal. Their tens are different." },
      { step: 2, choice: "d", hint: "That says Nimbus's score is greater. Check the tens place." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Line up the racers", machine: "Rank Rack", icon: "log", speaker: "nova",
    line: "Four racers finished the warm-up lap. Their scores all start with 6 thousands, so this will take careful eyes.",
    question: "Put the scores in order from least to greatest.",
    hint: "All four have 6 thousands. Compare the hundreds next. If the hundreds match, compare the tens.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "The warm-up lap is ranked" },
    answer: { kind: "order", correct: ["s6081", "s6108", "s6801", "s6810"] },
    items: [
      { id: "s6810", text: "6,810" },
      { id: "s6108", text: "6,108" },
      { id: "s6801", text: "6,801" },
      { id: "s6081", text: "6,081" },
    ],
    rightFeedback: "6,081 < 6,108 < 6,801 < 6,810. The hundreds did most of the work!",
    wrong: [
      { position: 0, hint: "Which score has the fewest hundreds? 6,081 has 0 hundreds." },
      { position: 1, hint: "After 6,081, which score has only 1 hundred?" },
      { position: 2, hint: "6,801 and 6,810 both have 8 hundreds. Compare their tens: 0 tens or 1 ten?" },
      { position: 3, hint: "The greatest score goes last. 6,810 has 8 hundreds and 1 ten." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Photo finish!", machine: "Rank Rack", icon: "snap", speaker: "vega",
    line: "Surprise! Three racers crossed the finish gate at almost the same second. The winner is the racer with the greatest signal score.",
    question: "Part 1: Order the scores from greatest to least. Part 2: Pick the symbol for Swift ___ Cirra. Part 3: Round the winning score to the nearest thousand.",
    data: {
      title: "Finish gate · photo finish scores",
      columns: ["Racer", "Signal score"],
      rows: [
        ["Swift", "72,450"],
        ["Cirra", "72,405"],
        ["Talon", "72,540"],
      ],
    },
    parts: [
      { type: "order", prompt: "Order the scores from greatest to least.", items: [
        { id: "cirra", text: "Cirra: 72,405" },
        { id: "talon", text: "Talon: 72,540" },
        { id: "swift", text: "Swift: 72,450" },
      ] },
      { type: "choice", prompt: "Swift's 72,450 ___ Cirra's 72,405", choices: [
        { id: "a", text: ">" },
        { id: "b", text: "<" },
        { id: "c", text: "=" },
      ] },
      { type: "number", prompt: "The winning score is 72,540. It is between 72,000 and 73,000. Tap the thousand it is closer to.", visual: { type: "numline", min: 72000, max: 73000, step: 100, pick: true, marks: [{ value: 72540, label: "72,540" }], title: "Sky ruler · 72,000 to 73,000", label: "Signal score" } },
    ],
    hint: "All three have 72 thousands. Compare the hundreds, then the tens. For rounding, the halfway point is 72,500.",
    meter: { heat: 10, label: "Signal strength +10%", story: "Talon wins the photo finish" },
    discovery: { id: "peregrine", name: "The fastest flyer", who: "Kai", fact: "A peregrine falcon can dive through the air at more than 200 miles per hour. That makes it the fastest animal on Earth." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["talon", "swift", "cirra"] },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 73000 },
    ] },
    rightFeedback: "Talon wins with 72,540! Swift's 72,450 > Cirra's 72,405, and 72,540 rounds up to 73,000.",
    wrong: [
      { step: 1, position: 0, hint: "Which score has the most hundreds? Talon has 5 hundreds." },
      { step: 1, position: 1, hint: "Swift and Cirra both have 4 hundreds. Compare the tens: 5 tens or 0 tens?" },
      { step: 1, position: 2, hint: "The least score goes last. Which one has 0 tens?" },
      { step: 2, choice: "b", hint: "Swift has 5 tens and Cirra has 0 tens. Which score is greater?" },
      { step: 2, choice: "c", hint: "The scores are close, but not equal. Look at the tens." },
      { step: 3, value: 72000, hint: "72,540 is past the halfway point, 72,500. Which thousand is it closer to?" },
      { step: 3, value: 72500, hint: "That's the halfway point, not a thousand. Round to 72,000 or 73,000." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Above or below the bar", machine: "Qualifier Gate", icon: "cells", speaker: "kai",
    line: "To get into the big race, a racer's signal score must be greater than 25,000. I have a stack of scores to check!",
    question: "Sort each score. Is it greater than 25,000 or less than 25,000?",
    hint: "First count the digits. A 4-digit number is always less than a 5-digit number. If both have 5 digits, compare from the left.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "The qualifiers are sorted" },
    discovery: { id: "pigeons", name: "Message pigeons", who: "Nova", fact: "Homing pigeons can find their way home from hundreds of miles away. Long ago, people tied tiny notes to their legs to send messages." },
    answer: { kind: "sort", bins: { q1: "less", q2: "more", q3: "less", q4: "more", q5: "less", q6: "more", q7: "less", q8: "more" } },
    rightFeedback: "Every score is sorted. Watch out for 9,999 and 2,500. They have fewer digits, so they are less than 25,000!",
    sort: {
      bins: [
        { id: "more", label: "Greater than 25,000" },
        { id: "less", label: "Less than 25,000" },
      ],
      items: [
        { id: "q1", label: "24,999" },
        { id: "q2", label: "25,100" },
        { id: "q3", label: "9,999" },
        { id: "q4", label: "52,000" },
        { id: "q5", label: "2,500" },
        { id: "q6", label: "25,010" },
        { id: "q7", label: "24,900" },
        { id: "q8", label: "100,000" },
      ],
    },
    wrong: [
      { item: "q1", hint: "24,999 has 4 thousands, and 25,000 has 5 thousands. So 24,999 is less, even though it's very close." },
      { item: "q3", hint: "9,999 has big digits, but only 4 digits. It doesn't have any ten thousands." },
      { item: "q5", hint: "2,500 looks like 25, but it only has 4 digits. It is much less than 25,000." },
      { item: "q6", hint: "25,010 matches 25,000 until the tens. 1 ten is more than 0 tens." },
      { item: "q2", hint: "25,100 has 1 hundred more than 25,000." },
      { item: "q4", hint: "52,000 has 5 ten thousands. 25,000 has only 2." },
      { item: "q7", hint: "24,900 has only 4 thousands. 25,000 has 5 thousands." },
      { item: "q8", hint: "100,000 has 6 digits. That's greater than any 5-digit number." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Fix Kai's score check", machine: "Repair", icon: "log", speaker: "nova",
    line: "Kai checked two scores and wrote 45,089 > 45,098 in the log. He said, \"9 is more than 8 in the ones place!\" Hmm. I'm not sure he started in the right place.",
    question: "Part 1: What went wrong? Part 2: Pick the right symbol for 45,089 ___ 45,098.",
    data: {
      title: "Kai's log",
      columns: ["Racer", "Ten thousands", "Thousands", "Hundreds", "Tens", "Ones"],
      rows: [
        ["Drift", "4", "5", "0", "8", "9"],
        ["Hover", "4", "5", "0", "9", "8"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's check?", choices: [
        { id: "a", text: "He started at the ones. He should start at the greatest place and find the first place that is different. That is the tens, and 8 tens < 9 tens." },
        { id: "b", text: "He should have added the digits and compared the sums." },
        { id: "c", text: "Nothing. 9 ones is more than 8 ones, so 45,089 is greater." },
      ] },
      { type: "choice", prompt: "45,089 ___ 45,098", choices: [
        { id: "a", text: "<" },
        { id: "b", text: ">" },
        { id: "c", text: "=" },
      ] },
    ],
    hint: "Tens are worth more than ones. Compare from the left, and stop at the first place that is different.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "Kai's log is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Fixed! The first different place is the tens. 8 tens < 9 tens, so 45,089 < 45,098.",
    wrong: [
      { step: 1, choice: "b", hint: "Both numbers use the same digits, so their sums are the same. Where should you start comparing?" },
      { step: 1, choice: "c", hint: "The ones place is the last place to look. Is there a greater place that is already different?" },
      { step: 2, choice: "b", hint: "That's Kai's mistake. Look at the tens: 8 tens or 9 tens?" },
      { step: 2, choice: "c", hint: "The digits are the same, but they sit in different places. The numbers are not equal." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Close to which ten?", machine: "Sky Ruler", icon: "trail", speaker: "kai",
    line: "Racer Mistral's beacon sent 3,467. The race rules round scores on the big screen. Let's zoom in on the sky ruler.",
    question: "Part 1: Round 3,467 to the nearest ten. Part 2: Round 3,467 to the nearest hundred.",
    parts: [
      { type: "number", prompt: "3,467 is between 3,460 and 3,470. Tap the ten it is closer to.", visual: { type: "numline", min: 3460, max: 3470, step: 1, pick: true, marks: [{ value: 3467, label: "3,467" }], title: "Zoomed in · each jump is 1", label: "Signal score" } },
      { type: "number", prompt: "3,467 is between 3,400 and 3,500. Tap the hundred it is closer to.", visual: { type: "numline", min: 3400, max: 3500, step: 10, pick: true, marks: [{ value: 3467, label: "3,467" }], title: "Zoomed out · each jump is 10", label: "Signal score" } },
    ],
    hint: "Find the halfway point. 3,465 is halfway between 3,460 and 3,470. 3,450 is halfway between 3,400 and 3,500.",
    meter: { heat: 5, label: "Signal strength +5%", story: "Mistral's score is on the big screen" },
    discovery: { id: "lighthouse", name: "Lighthouse signals", who: "Nova", fact: "Each lighthouse flashes its own pattern of light. Sailors at night can tell which lighthouse they see by counting the flashes." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 3470 },
      { kind: "number", value: 3500 },
    ] },
    rightFeedback: "3,467 is past halfway, so it rounds to 3,470. It is also past 3,450, so it rounds to 3,500!",
    wrong: [
      { step: 1, value: 3460, hint: "3,467 is past the halfway point, 3,465. Which ten is closer?" },
      { step: 1, value: 3467, hint: "That's the score itself. Round it to a ten: 3,460 or 3,470." },
      { step: 1, value: 3465, hint: "That's the halfway point. Pick a ten at one end of the ruler." },
      { step: 2, value: 3400, hint: "3,467 is past the halfway point, 3,450. Which hundred is closer?" },
      { step: 2, value: 3470, hint: "That's the nearest ten. Now round to a hundred: 3,400 or 3,500." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The long-range ruler", machine: "Sky Ruler", icon: "grid", speaker: "nova",
    line: "Racer Stratus flew the long route through the upper clouds and scored 46,300. This ruler is huge. Each jump is 1,000!",
    question: "Part 1: 46,300 is between which two thousands? Part 2: Round 46,300 to the nearest thousand. Part 3: Round 46,300 to the nearest ten thousand.",
    parts: [
      { type: "choice", prompt: "46,300 is between which two thousands that are next to each other?", visual: { type: "numline", min: 40000, max: 50000, step: 1000, marks: [{ value: 46300, label: "46,300" }], title: "Long-range ruler · each jump is 1,000", label: "Signal score" }, choices: [
        { id: "a", text: "46,000 and 47,000" },
        { id: "b", text: "45,000 and 46,000" },
        { id: "c", text: "46,300 and 46,400" },
        { id: "d", text: "47,000 and 48,000" },
      ] },
      { type: "number", prompt: "Tap the thousand that 46,300 is closer to.", visual: { type: "numline", min: 40000, max: 50000, step: 1000, pick: true, marks: [{ value: 46300, label: "46,300" }], title: "Long-range ruler · each jump is 1,000", label: "Signal score" } },
      { type: "number", prompt: "Now look at the ends of the ruler. Tap the ten thousand that 46,300 is closer to.", visual: { type: "numline", min: 40000, max: 50000, step: 1000, pick: true, marks: [{ value: 46300, label: "46,300" }], title: "Long-range ruler · each jump is 1,000", label: "Signal score" } },
    ],
    hint: "46,300 has 46 thousands and 3 hundreds. The halfway point between two thousands is 500 more. The halfway point between 40,000 and 50,000 is 45,000.",
    meter: { heat: 5, label: "Signal strength +5%", story: "Stratus is on the long-range ruler" },
    discovery: { id: "abacus", name: "The bead counter", who: "Kai", fact: "An abacus is a counting tool with beads on rods. Each rod stands for a place, like ones, tens, or hundreds. People have used them for thousands of years." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 46000 },
      { kind: "number", value: 50000 },
    ] },
    rightFeedback: "46,300 is between 46,000 and 47,000, and it rounds to 46,000. It's past 45,000, so it rounds to 50,000 to the nearest ten thousand!",
    wrong: [
      { step: 1, choice: "b", hint: "46,300 is more than 46,000, so it can't be below 46,000." },
      { step: 1, choice: "c", hint: "Those are hundreds. Look for the two thousands on the ruler." },
      { step: 1, choice: "d", hint: "46,300 is less than 47,000. Look one jump to the left." },
      { step: 2, value: 47000, hint: "46,300 is only 300 past 46,000. It hasn't reached halfway, 46,500." },
      { step: 2, value: 50000, hint: "That's the nearest ten thousand. Round to a thousand: 46,000 or 47,000." },
      { step: 3, value: 40000, hint: "46,300 is past 45,000, the halfway point. Which end is closer?" },
      { step: 3, value: 46000, hint: "That's the nearest thousand. Round to a ten thousand: 40,000 or 50,000." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Signal scramble", machine: "Signal Scale", icon: "quake", speaker: "vega",
    line: "Surprise! A lightning flash scrambled one of Nimbus's digits. The screen shows 63,_48. The judges know it is greater than 63,748 and less than 63,948.",
    question: "Part 1: What is the missing digit? Part 2: Order the scores from greatest to least. Part 3: Pick the symbol for the judges' note.",
    data: {
      title: "Storm lap · signal scores",
      columns: ["Racer", "Signal score"],
      rows: [
        ["Nimbus", "63,_48"],
        ["Aero", "63,748"],
        ["Plume", "63,948"],
        ["Vapor", "36,948"],
      ],
    },
    parts: [
      { type: "number", prompt: "Nimbus's score 63,_48 is greater than 63,748 and less than 63,948. What digit goes in the hundreds place?" },
      { type: "order", prompt: "Now Nimbus's score is fixed. Order all four scores from greatest to least.", items: [
        { id: "vapor", text: "Vapor: 36,948" },
        { id: "aero", text: "Aero: 63,748" },
        { id: "plume", text: "Plume: 63,948" },
        { id: "nimbus", text: "Nimbus: 63,848" },
      ] },
      { type: "choice", prompt: "The judges wrote Nimbus's score in words. sixty-three thousand, eight hundred forty-eight ___ 63,848", choices: [
        { id: "a", text: "=" },
        { id: "b", text: ">" },
        { id: "c", text: "<" },
      ] },
    ],
    hint: "Only the hundreds digit is missing. It has to be more than 7 and less than 9. Watch Vapor's score: the digits are switched around.",
    meter: { heat: 10, label: "Signal strength +10%", story: "The scrambled signal is fixed" },
    discovery: { id: "radiowaves", name: "Super-fast signals", who: "Nova", fact: "Radio waves travel as fast as light, about 186,000 miles every second. A radio signal could go around Earth more than 7 times in one second." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 8 },
      { kind: "order", correct: ["plume", "nimbus", "aero", "vapor"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The missing digit is 8, so Nimbus scored 63,848. 63,948 > 63,848 > 63,748 > 36,948, and the words and the digits are equal!",
    wrong: [
      { step: 1, value: 7, hint: "7 would make 63,748. That equals Aero's score. Nimbus's score is greater." },
      { step: 1, value: 9, hint: "9 would make 63,948. That equals Plume's score. Nimbus's score is less." },
      { step: 1, value: 800, hint: "The digit 8 is worth 800 here, but the question asks for the digit only." },
      { step: 2, position: 0, hint: "Plume has 63 thousands and 9 hundreds. That's the greatest." },
      { step: 2, position: 1, hint: "After Plume, which 63 thousand score has 8 hundreds?" },
      { step: 2, position: 3, hint: "Vapor has only 3 ten thousands. It goes last, even though its other digits are big." },
      { step: 3, choice: "b", hint: "Read the words slowly: sixty-three thousand, eight hundred forty-eight. Is that more than 63,848?" },
      { step: 3, choice: "c", hint: "Words and digits can name the same number. Write the words as digits." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The big first digit", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Racer Glint scored 9,876 and Racer Haze scored 12,345. Glint wins! 9 is way bigger than 1, so 9,876 > 12,345."',
    nova: 'Nova: "Wait, Kai. Line up the places first. 12,345 has a 1 in the ten thousands place. 9,876 has no ten thousands at all. So 12,345 > 9,876."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Write both numbers in place-value columns, lined up on the right. Which one reaches the ten thousands place?",
    data: {
      title: "Place-value check",
      columns: ["Racer", "Ten thousands", "Thousands", "Hundreds", "Tens", "Ones"],
      rows: [
        ["Glint", "", "9", "8", "7", "6"],
        ["Haze", "1", "2", "3", "4", "5"],
      ],
    },
    meter: { heat: 5, label: "Signal strength +5%", story: "Kai lines up his places" },
    discovery: { id: "semaphore", name: "Flag talk", who: "Nova", fact: "Sailors can send messages with two flags. Each way of holding the flags stands for a different letter. This is called semaphore." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. When the places are lined up, 12,345 has 1 ten thousand and 9,876 has 0. The greatest place decides, so 12,345 is greater." },
      { id: "B", text: "Nova, because 12,345 has smaller digits." },
      { id: "C", text: "Kai. The first digit decides, and 9 is more than 1." },
      { id: "D", text: "Kai. 9,876 has bigger digits in every spot, so it must be greater." },
    ],
    writtenPrompt: "Tell Kai in your own words why 12,345 is greater than 9,876.",
    debateHints: {
      wrongWho: "Line up the numbers by place. Does 9,876 have any ten thousands? Does 12,345?",
      wrongReason: "Right person, check the reason. What should you look at first when you compare?",
      right: "Nova is right. Line up the places first. A 5-digit number is greater than a 4-digit number.",
    },
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Round it three ways", machine: "Big Screen", icon: "battery", speaker: "nova",
    line: "Racer Zephyr's score is 8,352. The big screen can show it rounded to the nearest ten, hundred, or thousand. Let's figure out all three.",
    question: "Part 1: Round 8,352 to the nearest ten. Part 2: Round 8,352 to the nearest hundred. Part 3: Round 8,352 to the nearest thousand.",
    parts: [
      { type: "number", prompt: "8,352 is between 8,350 and 8,360. What is 8,352 rounded to the nearest ten?" },
      { type: "number", prompt: "8,352 is between 8,300 and 8,400. Tap the hundred it is closer to.", visual: { type: "numline", min: 8300, max: 8400, step: 10, pick: true, marks: [{ value: 8352, label: "8,352" }], title: "Sky ruler · each jump is 10", label: "Signal score" } },
      { type: "number", prompt: "8,352 is between 8,000 and 9,000. What is 8,352 rounded to the nearest thousand?" },
    ],
    hint: "Find the two numbers it is between. Then check the halfway point: 8,355, then 8,350, then 8,500.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "Zephyr's score is rounded three ways" },
    discovery: { id: "googol", name: "A googol", who: "Kai", fact: "A googol is a 1 followed by 100 zeros. A 9-year-old boy came up with the name for this giant number." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 8350 },
      { kind: "number", value: 8400 },
      { kind: "number", value: 8000 },
    ] },
    rightFeedback: "8,352 rounds to 8,350, then 8,400, then 8,000. The same score can round three different ways!",
    wrong: [
      { step: 1, value: 8360, hint: "8,352 has only 2 ones. That's less than halfway to the next ten." },
      { step: 1, value: 8400, hint: "That's the nearest hundred. Round to a ten: 8,350 or 8,360." },
      { step: 2, value: 8300, hint: "8,352 is just past 8,350, the halfway point. Which hundred is closer?" },
      { step: 2, value: 8350, hint: "That's the nearest ten. Tap a hundred at one end of the ruler." },
      { step: 3, value: 9000, hint: "8,352 has only 3 hundreds. It hasn't reached halfway, 8,500." },
      { step: 3, value: 8400, hint: "That's the nearest hundred. Round to a thousand: 8,000 or 9,000." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "True or false signals", machine: "Signal Scale", icon: "dial", speaker: "kai",
    line: "The fans are texting score comparisons to the race board. Only true ones get to show on the screen!",
    question: "Part 1: Which comparison is true? Part 2: Pick the symbol for 99,099 ___ 90,999.",
    parts: [
      { type: "choice", prompt: "Which comparison is true?", choices: [
        { id: "a", text: "100,000 > 99,999" },
        { id: "b", text: "70,605 > 70,650" },
        { id: "c", text: "8,999 > 80,001" },
        { id: "d", text: "34,120 = 34,012" },
      ] },
      { type: "choice", prompt: "99,099 ___ 90,999", choices: [
        { id: "a", text: ">" },
        { id: "b", text: "<" },
        { id: "c", text: "=" },
      ] },
    ],
    hint: "Count the digits first. If they have the same number of digits, compare from the left until you find a place that is different.",
    meter: { supplies: 1, label: "Scores ranked +1", story: "The fan board shows only true signals" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "100,000 has 6 digits, so it is greater than 99,999. And 99,099 has 9 thousands, so 99,099 > 90,999!",
    wrong: [
      { step: 1, choice: "b", hint: "Compare the tens: 70,605 has 0 tens and 70,650 has 5 tens. Which is greater?" },
      { step: 1, choice: "c", hint: "8,999 has only 4 digits. 80,001 has 5 digits." },
      { step: 1, choice: "d", hint: "Equal means every place matches. Look at the hundreds: 1 or 0?" },
      { step: 2, choice: "b", hint: "90,999 has lots of 9s, but compare the thousands: 9 thousands or 0 thousands?" },
      { step: 2, choice: "c", hint: "The numbers use similar digits, but the thousands are different." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The mixed-up leaderboard", machine: "Rank Rack", icon: "log", speaker: "nova",
    line: "The wind shook the leaderboard, and five scores fell off. Some have 4 digits and some have 5. Let's hang them back up.",
    question: "Put the scores in order from least to greatest.",
    hint: "The 4-digit score is the least. Then compare the ten thousands of the 5-digit scores. If they match, compare the thousands.",
    meter: { heat: 5, label: "Signal strength +5%", story: "The leaderboard is back up" },
    answer: { kind: "order", correct: ["r9540", "r10950", "r15090", "r19050", "r95400"] },
    items: [
      { id: "r15090", text: "15,090" },
      { id: "r95400", text: "95,400" },
      { id: "r10950", text: "10,950" },
      { id: "r9540", text: "9,540" },
      { id: "r19050", text: "19,050" },
    ],
    rightFeedback: "9,540 < 10,950 < 15,090 < 19,050 < 95,400. The leaderboard is back in order!",
    wrong: [
      { position: 0, hint: "Which score has only 4 digits? It's the least." },
      { position: 1, hint: "Three scores have 1 ten thousand. Which one has the fewest thousands?" },
      { position: 2, hint: "15,090 and 19,050 both have 1 ten thousand. Compare the thousands: 5 or 9?" },
      { position: 3, hint: "19,050 has 1 ten thousand and 9 thousands. Is there a score with more ten thousands?" },
      { position: 4, hint: "95,400 has 9 ten thousands. That's the greatest." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The final lap", machine: "Big Screen", icon: "relay", speaker: "vega",
    line: "This is it, the final lap of the Signal Race! Four racers sent their last scores. Crown the champion and put the scores on the big screen.",
    question: "Part 1: Order the scores from greatest to least. Part 2: Pick the symbol for Gale ___ Nimbus. Part 3: Round the champion's score to the nearest thousand. Part 4: Round Wren's score to the nearest hundred.",
    data: {
      title: "Final lap · signal scores",
      columns: ["Racer", "Signal score"],
      rows: [
        ["Wren", "81,375"],
        ["Zephyr", "81,735"],
        ["Gale", "18,753"],
        ["Nimbus", "81,357"],
      ],
    },
    parts: [
      { type: "order", prompt: "Order the scores from greatest to least.", items: [
        { id: "nimbus", text: "Nimbus: 81,357" },
        { id: "gale", text: "Gale: 18,753" },
        { id: "zephyr", text: "Zephyr: 81,735" },
        { id: "wren", text: "Wren: 81,375" },
      ] },
      { type: "choice", prompt: "Gale's 18,753 ___ Nimbus's 81,357", choices: [
        { id: "a", text: "<" },
        { id: "b", text: ">" },
        { id: "c", text: "=" },
      ] },
      { type: "number", prompt: "The champion is Zephyr with 81,735. Tap the thousand it is closer to.", visual: { type: "numline", min: 81000, max: 82000, step: 100, pick: true, marks: [{ value: 81735, label: "81,735" }], title: "Sky ruler · 81,000 to 82,000", label: "Signal score" } },
      { type: "number", prompt: "Wren scored 81,375. What is 81,375 rounded to the nearest hundred?" },
    ],
    hint: "Three scores have 81 thousands, so compare their hundreds, then their tens. Gale's digits are switched around. For rounding, find the halfway point first.",
    meter: { heat: 15, label: "Signal strength +15%", story: "Zephyr is the Signal Race champion" },
    discovery: { id: "romannumerals", name: "Letters for numbers", who: "Kai", fact: "Ancient Romans wrote numbers with letters. M stands for 1,000, C stands for 100, and X stands for 10. Roman numerals have no symbol for zero." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["zephyr", "wren", "nimbus", "gale"] },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 82000 },
      { kind: "number", value: 81400 },
    ] },
    rightFeedback: "Zephyr wins! 81,735 > 81,375 > 81,357 > 18,753. Zephyr's score rounds to 82,000, and Wren's rounds to 81,400.",
    wrong: [
      { step: 1, position: 0, hint: "Three scores have 81 thousands. Which one has the most hundreds?" },
      { step: 1, position: 1, hint: "Wren and Nimbus both have 81 thousands and 3 hundreds. Compare the tens: 7 tens or 5 tens?" },
      { step: 1, position: 3, hint: "Gale has only 1 ten thousand. It goes last, even with its big digits." },
      { step: 2, choice: "b", hint: "Gale's digits look big, but compare the ten thousands: 1 or 8?" },
      { step: 2, choice: "c", hint: "The digits are mixed up, so the numbers are not equal." },
      { step: 3, value: 81000, hint: "81,735 is past the halfway point, 81,500. Which thousand is closer?" },
      { step: 3, value: 81700, hint: "That's the nearest hundred. Tap a thousand at one end of the ruler." },
      { step: 4, value: 81300, hint: "81,375 has 7 tens. That's past halfway to the next hundred." },
      { step: 4, value: 81000, hint: "That's the nearest thousand. Round to a hundred: 81,300 or 81,400." },
      { step: 4, value: 81380, hint: "That's the nearest ten. Round to a hundred: 81,300 or 81,400." },
    ],
  },
};

export default {
  id: "MA.3.2D-XP",
  standard: "MA.3.2D-XP",
  engine: "expedition_station",
  title: "The Signal Race",
  planet: "Cloudreach",
  outpost: "Sky Reef · race day",
  grade: 3,
  subject: "Math",
  teks: "3.2D",
  supportingTeks: ["3.2C"],
  skillsChip: "3.2D · Compare and order numbers to 100,000",
  iCan: "I can compare and order whole numbers up to 100,000 using >, <, and =. I can find a number on a number line and round it to the nearest ten, hundred, thousand, or ten thousand.",
  blurb: "It's race day on Cloudreach! Sky-racers zoom through the cloud gates and beam back signal scores. The crew has to compare, order, and round every score to crown a champion.",
  mission: "Compare, order, and round the sky-racers' signal scores to crown the Signal Race champion.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.24 · CLOUDREACH SKY REEF",
  playableActs: [1, 2, 3],
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Signal strength", heatUnit: "%", supplies: "Scores ranked", suppliesUnit: "scores" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. It's race day on the Sky Reef of Cloudreach!",
    "Sky-racers are zooming through the cloud gates. Each racer's beacon sends back a signal score, some as big as 100,000.",
    "Help Kai and Nova compare the scores, put them in order, and round them for the big screen. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The warm-up laps", "Act 2 · The qualifier", "Act 3 · The final lap"],
    completes: [
      "The warm-up laps are ranked and the photo finish is solved, {firstName}!",
      "The qualifiers are sorted and the scrambled signal is fixed, {firstName}!",
      "Zephyr is the champion, {firstName}! The whole sky reef is cheering.",
    ],
    teasers: [
      "Next on Cloudreach: only the top scores get into the big race, and Kai's log has a mistake. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: Kai thinks a big first digit always wins, and the final lap is coming. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The qualifier round is starting over the clouds.",
      "Only racers with high enough scores get into the big race. Let's check every score carefully.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The final lap starts soon.",
      "Help the crew settle a debate, fix the leaderboard, and crown the champion.",
    ],
  }),
  tasks,
};
