// Expedition Station — The Sky Songs (ELA.3.9B-XP)
// Grade 3 · ELAR · Cloudreach (sky reef). Main standard 3.9B (explain rhyme
// scheme, sound devices, and structural elements such as stanzas in a variety
// of poems); also practices 3.10D (how imagery, literal and figurative language
// such as simile, and sound devices such as onomatopoeia achieve purposes),
// 3.6F (inferences), 3.3B (context clues), 3.12A (compose a poem), and 3.11D
// (edit). All poems are original, written for this quest: the crew holds a
// song night on the sky reef, and a Cloudreach reef-keeper sings a sky-ray song.
//
// Poem passages set `poem: true`. Each paragraph is a stanza and each
// "sentence" is one line, so ids like "B2.3" mean poem B, stanza 2, line 3.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "The Cloud Whales", genre: "Poem by Nova (rhyming)", poem: true }, [
    [
      "The cloud whales drift so slow and wide,",
      "with puffs of fog on every side.",
      "They sing a song as deep as the sea.",
      "Hooom, hooom, it rumbles down to me.",
    ],
    [
      "Their bellies shine like pearls so white.",
      "Their fins glow softly in the night.",
      "They circle round the coral towers,",
      "then nap on clouds for hours and hours.",
    ],
    [
      "Goodnight, cloud whales, big and gray.",
      "Come back to sing another day!",
    ],
  ]),
  B: passage("B", { title: "Wind Chime Reef", genre: "Poem by Kai (rhyming)", poem: true }, [
    [
      "The reef bells jingle, ding-a-ding.",
      "They twinkle in the morning light.",
      "Then all the sky crabs start to sing.",
      "Click-clack, click-clack, left and right!",
    ],
    [
      "Bubble-birds bounce by in a bunch.",
      "Pop, pop, pop go the bubbles they blow.",
      "They stop at the reef to munch their lunch,",
      "then zip away with a whoosh below.",
    ],
  ]),
  C: passage("C", { title: "Up Here", genre: "Poem by Commander Vega (free verse)", poem: true }, [
    [
      "Up here, the sky is my backyard.",
      "Up here, the clouds brush my cheeks, cool and damp.",
      "Up here, the reef glows pink at sunrise.",
    ],
    [
      "Slowly, slowly, the sun climbs over the coral.",
      "Far below, the ocean looks small enough to hold.",
      "But up here, with my crew,",
      "I feel big and brave and free.",
    ],
  ]),
  D: passage("D", { title: "The Sky Ray Song", genre: "Song sung by Reef-keeper Tamsin of Cloudreach", poem: true }, [
    [
      "Flap, flap, the sky rays fly",
      "across the purple evening sky.",
      "Their wings spread wide like giant kites.",
      "They swoop and swirl to dizzy heights.",
    ],
    [
      "Sing high, sing low,",
      "where the warm winds blow!",
    ],
    [
      "They dip and dive through clouds of cream.",
      "They skim across a misty stream.",
      "The little ones hold on so tight",
      "and ride their mothers through the night.",
    ],
    [
      "Sing high, sing low,",
      "where the warm winds blow!",
    ],
  ]),
  E: {
    id: "E",
    title: "Kai's card for the Song Shell Wall",
    genre: "Note (has mistakes)",
    ...editText(
      "E",
      "Tonight our crew {herd} the cloud whales sing. Nova's poem has three {stanzs} in it. The sky rays {flys} over the reef at dusk. {i} want to write a sky song too!",
      {
        herd: ["heard", "hurd"],
        stanzs: ["stanzas", "stanza"],
        flys: ["fly", "flying"],
        i: ["I", "eye"],
      }
    ),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Stack the stanzas", machine: "Poem Scanner", icon: "scan", speaker: "nova", passage: ["A"],
    line: "I wrote a poem about the cloud whales! Before I read it on the reef, can you count how many stanzas it has?",
    question: "Read Nova's poem, \"The Cloud Whales.\" How many stanzas does it have?",
    unit: "stanzas",
    hint: "A stanza is a group of lines, like a paragraph in a story. Look for the empty spaces between the groups.",
    meter: { heat: 10, label: "Reef chorus +10%", story: "The first reef bell rings" },
    discovery: { id: "humpbacksong", name: "Whale songs", who: "Nova", fact: "Male humpback whales sing long songs. One song can last up to 20 minutes, and a whale may sing it over and over for hours." },
    answer: { kind: "number", value: 3 },
    rightFeedback: "Right! Nova's poem has 3 stanzas. The first two have 4 lines, and the last one has 2 lines.",
    wrong: [
      { value: 10, hint: "10 is how many LINES there are. A stanza is a GROUP of lines. How many groups do you see?" },
      { value: 4, hint: "Some stanzas have 4 lines, but you're counting groups. Count the groups of lines, not the lines in one group." },
      { value: 1, hint: "Look again. There are empty spaces that split the poem into more than one group." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Rhyme catchers", machine: "Echo Net", icon: "static", speaker: "kai", passage: ["A"],
    line: "My Echo Net catches words that sound alike at the ends. Help me load it with the rhyming pairs from Nova's poem!",
    question: "Which word pairs from Nova's poem rhyme? Pick every one.",
    hint: "Rhyming words end with the same sound, like bee and tree. Look at the last word of each line.",
    meter: { supplies: 1, label: "Song shells +1", story: "Kai's Echo Net hums" },
    discovery: { id: "echo", name: "Echoes", who: "Kai", fact: "An echo is a sound that bounces back to you. It happens when sound hits something hard, like a cliff or a canyon wall." },
    answer: { kind: "multi", correct: ["a", "b", "c", "d"] },
    items: [
      { id: "a", text: "wide / side" },
      { id: "b", text: "sea / me" },
      { id: "c", text: "towers / hours" },
      { id: "d", text: "gray / day" },
      { id: "e", text: "whales / wide" },
      { id: "f", text: "white / towers" },
    ],
    rightFeedback: "Yes! Nova's lines come in rhyming pairs: wide / side, sea / me, white / night, towers / hours, and gray / day.",
    wrong: [
      { pick: "e", hint: "Whales and wide START with the same sound. That's not a rhyme. Rhymes END with the same sound." },
      { pick: "f", hint: "Say white and towers out loud. Do they end with the same sound?" },
      { missing: true, hint: "There are more rhyming pairs. Check the last word of every line." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "As deep as the sea", machine: "Picture Maker", icon: "crew", speaker: "vega", passage: ["A"],
    line: "Nova compared the cloud whales to other things to help us picture them. Find one of those comparisons.",
    question: "A simile compares two things using \"like\" or \"as.\" Highlight a line in Nova's poem that has a simile.",
    hint: "Look for the word \"like\" or the word \"as\" in a line that compares the whales to something else.",
    meter: { heat: 10, label: "Reef chorus +10%", story: "Vega hums along" },
    discovery: { id: "pearls", name: "How pearls form", who: "Nova", fact: "A pearl grows inside an oyster. When a tiny bit of something gets into its shell, the oyster covers it with layer after layer of shiny coating." },
    answer: { kind: "highlight", groups: [["A1.3", "A2.1"]] },
    rightFeedback: "Got it! The whale song is \"as deep as the sea,\" and their bellies \"shine like pearls.\" Both are similes.",
    wrong: [
      { sentence: "A1.1", hint: "That line tells how the whales move. Does it use like or as to compare them to something?" },
      { sentence: "A1.4", hint: "\"Hooom\" is a sound word, not a comparison. Look for like or as." },
      { sentence: "A3.1", hint: "That line says goodnight. It doesn't compare the whales to anything." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Drifting giants", machine: "Word Lens", icon: "static", speaker: "kai", passage: ["A"],
    line: "Nova says the whales \"drift so slow.\" I only know drift from when snow piles up. What does it mean here?",
    question: "\"The cloud whales drift so slow and wide.\" What does \"drift\" mean in this line?",
    hint: "Use the words around it. The whales are slow, and puffs of fog are all around them. How would they move?",
    meter: { supplies: 1, label: "Song shells +1", story: "Kai adds a word to his card" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Float along slowly, carried by the air" },
      { id: "b", text: "A big pile of snow" },
      { id: "c", text: "Dive down very fast" },
      { id: "d", text: "Stay still in one place" },
    ],
    rightFeedback: "Right! \"Slow\" is a clue. The whales float along slowly through the fog.",
    wrong: [
      { choice: "b", hint: "That's another meaning of drift, but the whales are MOVING here. What does \"slow\" tell you?" },
      { choice: "c", hint: "The line says the whales are slow. Do slow things dive fast?" },
      { choice: "d", hint: "The whales circle the towers later, so they do move. How do they move?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The whales sing back", machine: "Reef Stage", icon: "snap", speaker: "vega", passage: ["A"],
    line: "Surprise! As Nova finishes, three real cloud whales rise out of the fog and hum right back at us. The reef-keepers say they will stay only if we explain how Nova built her poem!",
    question: "Part 1: How many lines are in Nova's poem in all? Part 2: What is the rhyme scheme of stanza 1? Part 3: Highlight the line with a sound word that imitates the whales' song.",
    parts: [
      { type: "number", prompt: "How many lines are in Nova's whole poem?", unit: "lines" },
      { type: "choice", prompt: "In stanza 1, wide rhymes with side, and sea rhymes with me. What is the rhyme scheme?", choices: [
        { id: "a", text: "AABB: lines 1 and 2 rhyme, and lines 3 and 4 rhyme" },
        { id: "b", text: "ABAB: lines 1 and 3 rhyme, and lines 2 and 4 rhyme" },
        { id: "c", text: "AAAA: all four lines rhyme with each other" },
        { id: "d", text: "ABCD: none of the lines rhyme" },
      ] },
      { type: "highlight", prompt: "Highlight the line with a sound word (onomatopoeia) for the whales' song.", passage: "A" },
    ],
    hint: "Count every line in all 3 stanzas. For rhyme scheme, give the first rhyme sound the letter A and the next new sound the letter B.",
    meter: { heat: 15, label: "Reef chorus +15%", story: "The cloud whales circle the reef and stay" },
    discovery: { id: "frogsac", name: "Frog songs", who: "Nova", fact: "Many male frogs puff up a stretchy throat pouch when they call. The pouch helps make their song louder, so it carries farther." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 10 },
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A1.4"]] },
    ] },
    rightFeedback: "The cloud whales circle the reef and stay to listen! You explained how Nova's poem is built.",
    wrong: [
      { step: 1, value: 3, hint: "3 is the number of stanzas. How many LINES are there in all?" },
      { step: 1, value: 8, hint: "Don't forget the short last stanza. It has 2 more lines." },
      { step: 1, value: 4, hint: "4 is the lines in just one stanza. Add up the lines in all 3 stanzas." },
      { step: 2, choice: "b", hint: "Check line 1 and line 2: wide and side. They rhyme with each other, right next to each other." },
      { step: 2, choice: "c", hint: "Does wide rhyme with sea? Only pairs of lines rhyme here." },
      { step: 2, choice: "d", hint: "Wide and side DO rhyme. Look at the end words again." },
      { step: 3, sentence: "A1.3", hint: "That line tells about the song with a simile. Which line has a word that SOUNDS like the song?" },
      { step: 3, sentence: "A1.1", hint: "That line tells how the whales move. Look for a word that sounds like a hum." },
      { step: 3, sentence: "A2.2", hint: "Glowing is something you see, not hear. Find the sound word." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Sound bins", machine: "Sound Sorter", icon: "cells", speaker: "kai", passage: ["B", "C"],
    line: "I built a Sound Sorter with three bins. Poets use sound tricks, and I want to sort them from my poem and Vega's poem.",
    question: "Sort each part of the poems: onomatopoeia, alliteration, or repetition?",
    hint: "Onomatopoeia: a word that sounds like the sound it names (buzz). Alliteration: words close together that start with the same sound. Repetition: the same word or words used again and again.",
    meter: { supplies: 1, label: "Song shells +1", story: "Kai's sorter lights up in three colors" },
    discovery: { id: "windchimes", name: "Wind chimes", who: "Kai", fact: "In a set of wind chimes, the longer tubes make lower sounds and the shorter tubes make higher sounds." },
    answer: { kind: "sort", bins: { s1: "onomatopoeia", s2: "onomatopoeia", s3: "alliteration", s4: "alliteration", s5: "repetition", s6: "repetition" } },
    rightFeedback: "Sorted! Sound words go in onomatopoeia, same starting sounds go in alliteration, and words used again and again go in repetition.",
    sort: {
      bins: [
        { id: "onomatopoeia", label: "Onomatopoeia" },
        { id: "alliteration", label: "Alliteration" },
        { id: "repetition", label: "Repetition" },
      ],
      items: [
        { id: "s1", label: "ding-a-ding" },
        { id: "s2", label: "a whoosh below" },
        { id: "s3", label: "Bubble-birds bounce by in a bunch" },
        { id: "s4", label: "big and brave" },
        { id: "s5", label: "Up here... Up here... Up here..." },
        { id: "s6", label: "Slowly, slowly" },
      ],
    },
    wrong: [
      { item: "s1", hint: "Say ding-a-ding out loud. It sounds like a bell. What is a sound word called?" },
      { item: "s2", hint: "Whoosh sounds like something zooming by. That's a sound word." },
      { item: "s3", hint: "Listen to the start of each word: Bubble, bounce, by, bunch. What is that called?" },
      { item: "s4", hint: "Big and brave both start with the b sound. That's alliteration." },
      { item: "s5", hint: "Vega uses the same words, \"Up here,\" again and again. What is that called?" },
      { item: "s6", hint: "\"Slowly\" is said two times in a row. That's repetition." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Kai's rhyme mix-up", machine: "Card Repair", icon: "log", speaker: "kai", passage: ["B"],
    line: "I labeled my own poem card: \"Wind Chime Reef. Rhyme scheme: AABB.\" Nova looked at it and said, \"Hmm. Read your end words again, Kai.\"",
    question: "Part 1: What did Kai get wrong? Part 2: Highlight the line in stanza 1 that rhymes with line 1.",
    parts: [
      { type: "choice", prompt: "What did Kai get wrong?", choices: [
        { id: "a", text: "Line 1 rhymes with line 3, and line 2 rhymes with line 4. So the rhyme scheme is ABAB, not AABB." },
        { id: "b", text: "His poem does not rhyme at all, so it has no rhyme scheme." },
        { id: "c", text: "All four lines rhyme, so the rhyme scheme is AAAA." },
        { id: "d", text: "A rhyme scheme should use numbers, not letters." },
      ] },
      { type: "highlight", prompt: "Highlight the line in stanza 1 that rhymes with line 1 (ding).", passage: "B" },
    ],
    hint: "Write the last word of each line: ding, light, sing, right. Which words rhyme? Give the first sound A and the next new sound B.",
    meter: { supplies: 1, label: "Song shells +1", story: "Kai fixes his poem card" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B1.3"]] },
    ] },
    rightFeedback: "Card fixed! Ding rhymes with sing, and light rhymes with right. That's ABAB.",
    wrong: [
      { step: 1, choice: "b", hint: "Ding and sing DO rhyme. The poem rhymes, but in a different pattern." },
      { step: 1, choice: "c", hint: "Does ding rhyme with light? Only some of the lines rhyme with each other." },
      { step: 1, choice: "d", hint: "Letters are the right tool. The problem is WHICH letters Kai wrote." },
      { step: 2, sentence: "B1.2", hint: "Light doesn't rhyme with ding. Which end word sounds like ding?" },
      { step: 2, sentence: "B1.4", hint: "Right rhymes with light, not ding. Look for a word that ends in -ing." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Does it have to rhyme?", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["C"],
    line: "Kai: \"Commander Vega's poem doesn't rhyme. So it's not a real poem. Every poem has to rhyme!\"",
    nova: "Nova: \"Not true, Kai. Vega's poem is free verse. It is still a poem, even without rhymes.\"",
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about what makes Vega's writing a poem. Does it have lines and stanzas? Does it use sound tricks like repetition?",
    meter: { heat: 10, label: "Reef chorus +10%", story: "Kai grins and says, \"Okay, okay!\"" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Many poems do not rhyme. Vega's poem is still a poem because it is written in lines and stanzas and uses repetition and pictures." },
      { id: "B", text: "Nova, because a poem only needs to be short." },
      { id: "C", text: "Kai. If there are no rhyming words, it must be a story." },
      { id: "D", text: "Kai. Only songs are allowed to skip rhyming." },
    ],
    writtenPrompt: "Tell Kai in your own words why Vega's writing is still a poem.",
    debateHints: {
      wrongWho: "Look at Vega's writing. It has lines, stanzas, and the words \"Up here\" again and again. Do poems need rhymes to have those?",
      wrongReason: "Right person, check the reason. Short writing isn't always a poem. What does Vega's poem have that makes it a poem?",
      right: "Nova is right. A poem doesn't have to rhyme. Vega's free-verse poem uses lines, stanzas, and repetition.",
    },
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Why click-clack?", machine: "Sound Lab", icon: "brief", speaker: "nova", passage: ["B"],
    line: "Kai filled his poem with sound words like ding-a-ding, click-clack, pop, and whoosh. I think he did it on purpose.",
    question: "Why did Kai use so many sound words (onomatopoeia) in \"Wind Chime Reef\"?",
    hint: "Onomatopoeia words sound like the noises they name. What do they help a reader do?",
    meter: { heat: 10, label: "Reef chorus +10%", story: "The sky crabs click along" },
    discovery: { id: "owlfeathers", name: "Silent owls", who: "Nova", fact: "Owls can fly almost without a sound. The soft, fringed edges of their feathers quiet the rush of air." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "To make every line rhyme" },
      { id: "b", text: "To help readers hear how busy and noisy the reef is" },
      { id: "c", text: "To show that the reef is quiet and sleepy" },
      { id: "d", text: "To tell exactly how many bubble-birds there are" },
    ],
    rightFeedback: "Yes! The sound words let you hear the bells, the crabs, and the bubbles, so the reef feels lively.",
    wrong: [
      { choice: "a", hint: "Click-clack isn't at the end of a rhyming pair with ding. What do sound words help you do?" },
      { choice: "c", hint: "Would a quiet, sleepy place go ding, click-clack, pop, and whoosh?" },
      { choice: "d", hint: "The poem doesn't give any numbers. Think about what you HEAR when you read it." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The gust storm", machine: "Wind Shield", icon: "quake", speaker: "vega", passage: ["C", "B"],
    line: "Surprise! A gust storm is blowing across the reef, and the reef bells are ringing wildly. While Kai ties them down, the reef-keepers ask us to explain my poem to keep everyone calm.",
    question: "Part 1: How many lines are in Vega's poem? Part 2: Why does Vega repeat \"Up here\"? Part 3: How does Vega feel on the sky reef? Part 4: Highlight the line in Kai's poem that uses alliteration.",
    parts: [
      { type: "number", prompt: "How many lines are in \"Up Here\"?", unit: "lines" },
      { type: "choice", prompt: "Why does Vega repeat the words \"Up here\" again and again?", choices: [
        { id: "a", text: "To show how special it feels to be high up in the sky" },
        { id: "b", text: "Because she forgot what she already wrote" },
        { id: "c", text: "To make the lines rhyme" },
        { id: "d", text: "To tell readers the poem is about the ocean" },
      ] },
      { type: "choice", prompt: "Read the last line: \"I feel big and brave and free.\" How does Vega feel on the sky reef?", choices: [
        { id: "a", text: "Happy and proud to be there with her crew" },
        { id: "b", text: "Scared and lonely" },
        { id: "c", text: "Bored and tired" },
        { id: "d", text: "Upset that the ocean is so small" },
      ] },
      { type: "highlight", prompt: "Highlight the line in Kai's poem that uses alliteration.", passage: "B" },
    ],
    hint: "Count the lines in both stanzas. Then think about why a poet says something again and again. Alliteration means words close together start with the same sound.",
    meter: { heat: 15, label: "Reef chorus +15%", story: "The gust storm passes, and the bells ring softly again" },
    discovery: { id: "cloudweight", name: "Heavy clouds", who: "Kai", fact: "A big puffy cloud can weigh about a million pounds. It floats because its water drops are tiny and spread out over a huge space." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 7 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B2.1"]] },
    ] },
    rightFeedback: "The gust storm passes, and the reef bells ring softly again! You explained Vega's poem.",
    wrong: [
      { step: 1, value: 2, hint: "2 is the number of stanzas. Count every line." },
      { step: 1, value: 3, hint: "That's just the first stanza. Add the lines in stanza 2." },
      { step: 1, value: 4, hint: "That's just the second stanza. Add the lines in stanza 1." },
      { step: 2, choice: "b", hint: "Poets repeat words on purpose. What feeling do the words \"Up here\" build?" },
      { step: 2, choice: "c", hint: "Vega's poem is free verse, so it doesn't rhyme. Why else would she repeat words?" },
      { step: 2, choice: "d", hint: "Up here means up in the sky. The ocean is far below. What is the poem about?" },
      { step: 3, choice: "b", hint: "Vega is \"with my crew,\" so she isn't lonely. What do big, brave, and free tell you?" },
      { step: 3, choice: "c", hint: "Would a bored person write \"I feel big and brave and free\"?" },
      { step: 3, choice: "d", hint: "The small ocean just shows how high she is. Look at the feeling words in the last line." },
      { step: 4, sentence: "B2.2", hint: "Pop, pop, pop is onomatopoeia and repetition. Find the line where many words start with the same sound." },
      { step: 4, sentence: "B1.4", hint: "Click-clack is a sound word. Look for bubble, bounce, by, and bunch." },
      { step: 4, sentence: "B2.3", hint: "Munch and lunch rhyme, but they don't start with the same sound. Look for words that start alike." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Purple skies", machine: "Sense Detector", icon: "scan", speaker: "nova", passage: ["D"],
    line: "Reef-keeper Tamsin's song paints pictures in my head. I think she used imagery, words that help you see, hear, or feel.",
    question: "Highlight a line in \"The Sky Ray Song\" that helps you SEE a color.",
    hint: "Imagery uses words that help you use your senses. Look for a color word, like purple, pink, or cream.",
    meter: { heat: 10, label: "Reef chorus +10%", story: "The evening sky turns purple over the reef" },
    answer: { kind: "highlight", groups: [["D1.2", "D3.1"]] },
    rightFeedback: "Yes! \"The purple evening sky\" and \"clouds of cream\" help you see the colors of the reef.",
    wrong: [
      { sentence: "D1.1", hint: "\"Flap, flap\" helps you HEAR the rays. Find a line with a color word." },
      { sentence: "D3.3", hint: "Holding on tight is something you FEEL. Look for a color." },
      { sentence: "D2.2", hint: "That line is about wind. Which line names a color?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Sing it again", machine: "Song Map", icon: "relay", speaker: "vega", passage: ["D"],
    line: "Tamsin's song has something the other poems don't. Two of the stanzas are exactly the same. The whole reef sang along with those.",
    question: "Stanzas 2 and 4 of \"The Sky Ray Song\" are the same. Why did Tamsin repeat that stanza?",
    hint: "In a song, the part that comes back again and again is called the chorus. Why do songs have one?",
    meter: { supplies: 1, label: "Song shells +1", story: "The whole reef sings the chorus" },
    discovery: { id: "mockingbird", name: "Copycat singers", who: "Nova", fact: "Mockingbirds can copy the songs of dozens of other birds. Some even copy sounds like squeaky gates and phone rings." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It is a chorus. Repeating it makes the song easy to remember and sing together." },
      { id: "b", text: "Tamsin ran out of ideas, so she copied a stanza." },
      { id: "c", text: "Every poem must repeat a stanza." },
      { id: "d", text: "It tells a new part of the story about the sky rays." },
    ],
    rightFeedback: "Right! The repeated stanza is a chorus. It gives the song a pattern that everyone can join in on.",
    wrong: [
      { choice: "b", hint: "Poets repeat on purpose. What happens when a part of a song comes back again and again?" },
      { choice: "c", hint: "Nova's and Kai's poems don't repeat a stanza. So not every poem has to. Why did THIS song?" },
      { choice: "d", hint: "Stanzas 2 and 4 have the same words, so they don't tell anything new. Why repeat them?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Blown-away verse", machine: "Verse Catcher", icon: "log", speaker: "kai", passage: ["D"],
    line: "Tamsin wrote one more verse, but the wind blew the lines out of order! Her songs rhyme in pairs, AABB. Can you put them back?",
    question: "Put Tamsin's new stanza in order. Use the AABB rhyme pattern and what makes sense.",
    hint: "Lines 1 and 2 rhyme, and lines 3 and 4 rhyme. The sky rays rest in the morning, dream while they sleep, and wake up last.",
    meter: { supplies: 1, label: "Song shells +1", story: "Kai pins the verse back together" },
    discovery: { id: "songlearn", name: "Learning to sing", who: "Kai", fact: "Many young songbirds learn their songs by listening to grown-up birds, a little like how children learn to talk." },
    answer: { kind: "order", correct: ["rest", "nest", "rain", "again"] },
    items: [
      { id: "again", text: "and wake at dusk to fly again." },
      { id: "rest", text: "When morning comes, the sky rays rest," },
      { id: "rain", text: "They dream of wind and sun and rain," },
      { id: "nest", text: "each tucked inside a cloudy nest." },
    ],
    rightFeedback: "Verse caught! Rest rhymes with nest, and rain rhymes with again. That's AABB.",
    wrong: [
      { position: 0, hint: "The verse starts when morning comes. Which line tells that?" },
      { position: 1, hint: "Which line ends with a word that rhymes with rest?" },
      { position: 2, hint: "After they rest, the rays dream. Which line tells what they dream of?" },
      { position: 3, hint: "The last line rhymes with rain and tells when the rays wake up." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Wings like kites", machine: "Picture Maker", icon: "crew", speaker: "nova", passage: ["D"],
    line: "Tamsin sang, \"Their wings spread wide like giant kites.\" She could have just said the wings are big. Why a kite?",
    question: "Why did Tamsin compare the sky rays' wings to giant kites? Pick every reason that fits.",
    hint: "Picture a kite. What shape is it? How does it move in the wind?",
    meter: { heat: 10, label: "Reef chorus +10%", story: "The sky rays glide past like kites" },
    answer: { kind: "multi", correct: ["a", "b"] },
    items: [
      { id: "a", text: "It helps you picture big, flat, wide wings." },
      { id: "b", text: "It shows the rays float and glide on the wind, the way kites do." },
      { id: "c", text: "It tells you the sky rays are really made of paper and string." },
      { id: "d", text: "It tells you the sky rays are tied to people on the ground." },
    ],
    rightFeedback: "Yes! The simile shows the wings' shape AND how the rays float on the wind.",
    wrong: [
      { pick: "c", hint: "A simile compares. It doesn't mean the rays are really kites." },
      { pick: "d", hint: "The song says the rays swoop and swirl freely. The simile is about how they look and move." },
      { missing: true, hint: "There is more than one reason. Think about how a kite LOOKS and how it MOVES." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The Song Shell Wall", machine: "Song Shell Wall", icon: "relay", speaker: "vega", passage: ["E", "D"],
    line: "Surprise! The sky rays are landing on the reef to hear one last song. Tamsin says every guest must add two lines to the Song Shell Wall before the stars come out. That means you too!",
    question: "Part 1: Fix the 4 mistakes on Kai's card. Part 2: How many stanzas are in \"The Sky Ray Song\"? Part 3: Write two lines of your own sky reef poem that rhyme.",
    parts: [
      { type: "edit", prompt: "Fix the 4 mistakes on Kai's card.", passage: "E" },
      { type: "number", prompt: "How many stanzas are in \"The Sky Ray Song\"? Count the chorus stanzas too.", unit: "stanzas" },
      { type: "write", prompt: "Write two lines about the sky reef that rhyme. Try a sound word or a simile too.", minWords: 10 },
    ],
    teacherScoredPart: 3,
    rubric: ["Writes two lines of poetry about the sky reef", "The last words of the two lines rhyme", "Uses a sound device (like onomatopoeia or alliteration) or a simile"],
    hint: "For your poem: pick something on the reef. What does it look or sound like? End your two lines with words that rhyme, like sky and fly.",
    meter: { heat: 15, label: "Reef chorus +15%", story: "Your lines shine on the Song Shell Wall" },
    discovery: { id: "birdsyrinx", name: "Two-note birds", who: "Nova", fact: "Birds sing with a voice box deep in their chest called a syrinx. Some birds can make two different notes at the same time." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "E:herd": "heard", "E:stanzs": "stanzas", "E:flys": "fly", "E:i": "I" } },
      { kind: "number", value: 4 },
      { kind: "write", minWords: 10 },
    ] },
    rightFeedback: "Your lines are on the Song Shell Wall, and the sky rays flap their wings to cheer! Your teacher will read what you wrote.",
    wrong: [
      { step: 1, token: "E:herd", hint: "A herd is a group of animals. Which word means you listened with your ears?" },
      { step: 1, token: "E:stanzs", hint: "There are three of them. How do you spell more than one stanza?" },
      { step: 1, token: "E:flys", hint: "There are many rays. Do we say \"the rays flys\" or \"the rays fly\"?" },
      { step: 1, token: "E:i", hint: "When you write about yourself, how do you always write the word I?" },
      { step: 2, value: 2, hint: "Don't skip the short chorus stanzas. Count every group of lines." },
      { step: 2, value: 12, hint: "12 is the number of lines. How many GROUPS of lines are there?" },
      { step: 2, value: 3, hint: "The chorus shows up two times. Count both of them." },
    ],
  },
};

export default {
  id: "ELA.3.9B-XP",
  standard: "ELA.3.9B-XP",
  engine: "expedition_station",
  title: "The Sky Songs",
  planet: "Cloudreach",
  outpost: "Sky reef · song night",
  grade: 3,
  subject: "ELAR",
  teks: "3.9B",
  supportingTeks: ["3.10D", "3.6F", "3.3B", "3.12A", "3.11D"],
  skillsChip: "3.9B · Explain rhyme, sound, and stanzas in poems",
  iCan: "I can explain rhyme schemes, sound devices, and stanzas in poems. I can tell how a poet's words help me see and hear.",
  blurb: "On Cloudreach, the crew holds a song night on the sky reef. Nova, Kai, Vega, and a reef-keeper share poems about humming cloud whales, jingling reef bells, and sky rays that fly like kites.",
  mission: "Count stanzas and lines, find rhyme schemes and sound words, and add two lines of your own to the Song Shell Wall.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.9B · CLOUDREACH SKY REEF",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Reef chorus", heatUnit: "%", supplies: "Song shells", suppliesUnit: "shells" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega on the sky reef of Cloudreach.",
    "Tonight the reef-keepers invited our crew to song night. Each of us wrote a poem to share.",
    "On Cloudreach, a poem is only finished when someone explains how it was built. Help us do that. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Nova's cloud whales", "Act 2 · Kai's wind chimes", "Act 3 · The Song Shell Wall"],
    completes: [
      "The cloud whales stayed to listen, {firstName}! You explained Nova's poem.",
      "The gust storm is over, {firstName}. The reef bells are ringing softly again.",
      "Your lines shine on the Song Shell Wall, {firstName}! Song night was a success.",
    ],
    teasers: [
      "Next on Cloudreach: Kai and Commander Vega share their poems. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: Reef-keeper Tamsin sings the sky ray song, and the Song Shell Wall is waiting. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Kai here. My poem is full of sounds, and I can't wait to read it.",
      "Commander Vega's poem is next. Hers doesn't rhyme at all. Let's listen closely.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Reef-keeper Tamsin is singing the last song of the night.",
      "After that, every guest adds two lines to the Song Shell Wall. Get your best rhymes ready.",
    ],
  }),
  tasks,
};
