// Expedition Station — The Soil Makers (SCI.3.10B-XP)
// Grade 3 · Science · Cindara (lava world). Main standard 3.10B (investigate
// and explain how soils such as sand and clay are formed by weathering of
// rock and by decomposition of plant and animal remains); also 3.10C (model
// and describe rapid changes in Earth's surface such as volcanic eruptions,
// earthquakes, and landslides), and practices 3.1B (plan and conduct
// investigations), 3.1E (collect observations as evidence), 3.2B (analyze
// data for patterns), 3.2C (use math to compare data), 3.2D (evaluate a
// design using criteria), 3.3A (explanations supported by data), 3.3C
// (respectful scientific discussion), 3.4 (science and people), 3.5B (cause
// and effect), 3.5G (stability and change).
//
// Earth-true rule: Cindara and the crew are invented, but every soil, test,
// process, and data table is real Earth science.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Where did it come from?", machine: "Soil Sorter", icon: "cells", speaker: "nova",
    line: "Cindara's old lava rock is slowly turning into soil, just like rock does on Earth. I dug up a scoop of Earth garden soil to compare. Look at what's in it!",
    question: "Sort each thing in the soil: did it come from rock, or from living things that died?",
    hint: "Is it a hard, tiny bit of stone? Or was it once part of a plant or an animal?",
    meter: { heat: 5, label: "Garden +5%", story: "The soil scoop is sorted" },
    answer: { kind: "sort", bins: { s1: "rock", s2: "life", s3: "rock", s4: "life", s5: "rock", s6: "life" } },
    rightFeedback: "Sand, silt, and clay come from rock that broke into bits. Rotting leaves, old roots, and beetle shells come from living things.",
    sort: {
      bins: [{ id: "rock", label: "From rock" }, { id: "life", label: "From living things" }],
      items: [
        { id: "s1", label: "Gritty grains of sand" },
        { id: "s2", label: "Brown, crumbly bits of old leaves" },
        { id: "s3", label: "Sticky bits of clay" },
        { id: "s4", label: "A piece of a dead root" },
        { id: "s5", label: "Tiny pebbles" },
        { id: "s6", label: "A tiny bit of a beetle's shell" },
      ],
    },
    wrong: [
      { item: "s3", hint: "Clay is made of the tiniest bits of broken rock. It was never alive." },
      { item: "s1", hint: "Sand grains are hard little bits of stone. Were they ever alive?" },
      { item: "s5", hint: "Pebbles are small pieces of rock. Were they ever alive?" },
      { item: "s2", hint: "Leaves grow on plants. Were the leaves once part of a living thing?" },
      { item: "s4", hint: "Roots grow on plants. Was the root once alive?" },
      { item: "s6", hint: "A beetle is an animal. Was its shell once part of a living thing?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The sand question", machine: "Rock Lab", icon: "scan", speaker: "kai",
    line: "Nova, here's something I don't get. The garden soil has sand in it. Where does sand even come from?",
    question: "Where does the sand in soil come from?",
    hint: "Sand grains are hard, like tiny stones. What big thing could they have broken off from?",
    meter: { heat: 5, label: "Garden +5%", story: "The sand mystery is solved" },
    discovery: { id: "quartz", name: "Quartz sand", who: "Nova", fact: "A lot of sand is made of quartz. Quartz is a very hard mineral, so its grains last a long time after the rest of the rock has worn away." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Weathering broke big rocks into tiny pieces." },
      { id: "b", text: "Plants make sand in their roots." },
      { id: "c", text: "Sand falls from the sky when it rains." },
      { id: "d", text: "Worms make sand in their bodies." },
    ],
    rightFeedback: "Water, ice, wind, and roots slowly break rock into smaller and smaller bits. Tiny bits of rock become sand.",
    wrong: [
      { choice: "b", hint: "Roots can crack rock, but they don't make sand. What is sand made of?" },
      { choice: "c", hint: "Rain is water. Sand grains are hard like stone. Where could tiny stones come from?" },
      { choice: "d", hint: "Worms eat dead leaves and soil, but they don't make sand. What are sand grains made of?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "How soil is born", machine: "Soil Timeline", icon: "trail", speaker: "nova",
    line: "I wrote the story of how soil forms on bare rock, one step per card. Then Kai dropped the cards!",
    question: "Put the steps of soil forming in order, from first to last.",
    hint: "Plants need some bits of rock to grow in. And worms need soil to mix.",
    meter: { supplies: 1, label: "Soil cores +1", story: "The soil timeline is in order" },
    answer: { kind: "order", correct: ["weather", "grow", "decay", "worms", "layers"] },
    items: [
      { id: "decay", text: "Plants and animals die, and decomposers break them down into dark humus." },
      { id: "layers", text: "Over many years, layers form: dark topsoil on top, lighter soil and rock below." },
      { id: "weather", text: "Rock weathers and breaks into tiny bits." },
      { id: "worms", text: "Worms and other animals dig and mix the humus with the rock bits." },
      { id: "grow", text: "Small plants start to grow in the rock bits." },
    ],
    rightFeedback: "Rock breaks into bits, plants grow and die, decomposers make humus, worms mix it in, and layers form over a long time.",
    wrong: [
      { position: 0, hint: "Nothing can grow on solid rock. What has to happen to the rock first?" },
      { position: 1, hint: "Once there are rock bits, what can start to grow in them?" },
      { position: 2, hint: "Plants have to die before they can rot into humus." },
      { position: 3, hint: "Worms mix humus into the rock bits. So the humus has to be made first." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "The leaf bag test", machine: "Rot Lab", icon: "dial", speaker: "kai",
    line: "Two months ago, I buried a mesh bag with 40 whole leaves in Earth garden soil. Today I dug it up. Only 15 leaves are still whole. The rest broke down into crumbly bits.",
    question: "How many leaves broke down?",
    unit: "leaves",
    hint: "Start with 40 leaves. Take away the ones that are still whole.",
    meter: { supplies: 1, label: "Soil cores +1", story: "The leaf bag results are logged" },
    answer: { kind: "number", value: 25 },
    rightFeedback: "40 − 15 = 25. Decomposers broke down 25 leaves in two months.",
    wrong: [
      { value: 55, hint: "You want the leaves that broke down, not all the leaves put together. Should you add or subtract?" },
      { value: 15, hint: "15 leaves are still whole. How many of the 40 broke down?" },
      { value: 40, hint: "40 is how many leaves Kai started with. Some are still whole. How many broke down?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The fallen log", machine: "Rot Lab", icon: "quake", speaker: "vega",
    line: "Surprise! Nova's Earth videos show a fallen log in a forest. Scientists checked the same log once every year for 5 years.",
    question: "Part 1: What is breaking the log down? Part 2: Read the table. In what year could you first push a stick into the wood? Part 3: What will the rotted log become part of?",
    data: {
      title: "A fallen log in an Earth forest",
      columns: ["Year", "What scientists saw"],
      rows: [
        ["Year 1", "Hard log with bark. A few mushrooms growing."],
        ["Year 3", "Bark falling off. Beetles and pill bugs inside. Wood still hard."],
        ["Year 5", "Soft, crumbly wood. A stick pushes in easily. Worms underneath."],
      ],
    },
    parts: [
      { type: "choice", prompt: "What is breaking the log down?", choices: [
        { id: "a", text: "Decomposers, like fungi, beetles, pill bugs, and worms" },
        { id: "b", text: "Nothing. Logs stay the same forever." },
        { id: "c", text: "The sunlight melting the wood" },
        { id: "d", text: "The tree growing back" },
      ] },
      { type: "number", prompt: "In what year could you first push a stick into the wood?", unit: "year" },
      { type: "choice", prompt: "What will the rotted log become part of?", choices: [
        { id: "a", text: "The soil. It turns into humus that feeds new plants." },
        { id: "b", text: "A new rock" },
        { id: "c", text: "Sand on a beach" },
        { id: "d", text: "Lava" },
      ] },
    ],
    hint: "Look at who was living in and on the log. Then find the row where the wood got soft.",
    meter: { heat: 10, label: "Garden +10%", story: "The crew learns how dead wood becomes soil" },
    discovery: { id: "logs", name: "Rotting logs", who: "Kai", fact: "A big fallen tree can take many years, even decades, to rot away. Fungi, bacteria, and insects break it down little by little." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 5 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Decomposers turned the hard log into soft, crumbly humus. That's how dead plants become part of the soil!",
    wrong: [
      { step: 1, choice: "b", hint: "The table shows the log changing each year. Who was living in it?" },
      { step: 1, choice: "c", hint: "Sunlight can't melt wood. Look at the living things in the table." },
      { step: 1, choice: "d", hint: "The tree is dead and fallen. What living things were eating the wood?" },
      { step: 2, value: 3, hint: "In Year 3 the wood was still hard. Find the row where a stick pushes in." },
      { step: 2, value: 1, hint: "In Year 1 the log was hard with bark. Find the row where a stick pushes in." },
      { step: 3, choice: "b", hint: "Rocks come from cooled lava or pressed layers, not from wood. Where do the crumbly bits end up?" },
      { step: 3, choice: "c", hint: "Sand comes from broken rock. What is the dark part of soil made from rotted plants called?" },
      { step: 3, choice: "d", hint: "Lava is melted rock. What do rotted plants turn into?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Always been there?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Soil is just dirt. It has always been there, and it never forms. So Cindara\'s lava rock will never have soil."',
    nova: 'Nova: "Soil forms very slowly. Rock weathers into bits, and dead plants and animals rot into humus. Cindara\'s rock can become soil too, over a long time."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about the leaf bag and the fallen log. Did they turn into something new?",
    meter: { heat: 5, label: "Garden +5%", story: "Kai rethinks where soil comes from" },
    discovery: { id: "inch", name: "Slow soil", who: "Nova", fact: "It can take hundreds of years for nature to make just 2.5 centimeters (1 inch) of new topsoil. That's why people work hard to protect the soil we have." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Soil forms slowly from rock bits made by weathering and from dead plants and animals that decompose. The leaf bag and log showed this happening." },
      { id: "B", text: "Nova, because soil is brown." },
      { id: "C", text: "Kai. Soil was put on Earth all at once, long ago." },
      { id: "D", text: "Kai. Rock is too hard to ever break down." },
    ],
    writtenPrompt: "Tell Kai in your own words how new soil forms.",
    debateHints: {
      wrongWho: "Remember the leaves and the log. They broke down into crumbly bits. Where do those bits go?",
      wrongReason: "Right person, check the reason. What two things make soil?",
      right: "Nova is right. Soil forms slowly from weathered rock and decomposed plants and animals.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Feel the grains", machine: "Soil Sorter", icon: "cells", speaker: "nova",
    line: "Soil has four main parts: sand, silt, clay, and humus. I wrote clue cards about how each one looks and feels.",
    question: "Sort each clue card into the soil part it describes.",
    hint: "Sand grains are biggest, clay grains are tiniest, and silt is in between. Humus came from living things.",
    meter: { heat: 5, label: "Garden +5%", story: "The four soil parts are sorted" },
    discovery: { id: "pottery", name: "Clay pots", who: "Kai", fact: "People have made pots from clay for more than 10,000 years. Wet clay can be shaped, and it turns hard when it is baked very hot." },
    answer: { kind: "sort", bins: { c1: "sand", c2: "sand", c3: "silt", c4: "silt", c5: "clay", c6: "clay", c7: "humus", c8: "humus" } },
    rightFeedback: "Sand is big and gritty. Silt is smooth like flour. Clay is tiny and sticky. Humus is dark and spongy.",
    sort: {
      bins: [{ id: "sand", label: "Sand" }, { id: "silt", label: "Silt" }, { id: "clay", label: "Clay" }, { id: "humus", label: "Humus" }],
      items: [
        { id: "c1", label: "Biggest grains. Feels gritty and rough." },
        { id: "c2", label: "Water runs through it fast." },
        { id: "c3", label: "Feels smooth, like flour, when dry." },
        { id: "c4", label: "Grains are smaller than sand but bigger than clay." },
        { id: "c5", label: "Tiniest grains. Sticky when wet." },
        { id: "c6", label: "Holds water a long time. Can be rolled into a ribbon." },
        { id: "c7", label: "Dark brown. Made of rotted plants and animals." },
        { id: "c8", label: "Soft and spongy. Full of food for plants." },
      ],
    },
    wrong: [
      { item: "c3", hint: "Flour-smooth grains are in between sand and clay. That's silt." },
      { item: "c4", hint: "Which soil part is in the middle, between big sand and tiny clay?" },
      { item: "c6", hint: "Which grains are so tiny and packed so close that water gets stuck?" },
      { item: "c2", hint: "Big grains leave big spaces between them. Which soil part has the biggest grains?" },
      { item: "c5", hint: "Which soil part has the tiniest grains of all?" },
      { item: "c1", hint: "Which soil part has the biggest grains?" },
      { item: "c7", hint: "Only one part of soil came from living things. What is it called?" },
      { item: "c8", hint: "Rotted plants and animals feed new plants. Which soil part is that?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The clean-up crew", machine: "Rot Lab", icon: "flask", speaker: "kai",
    line: "Decomposers are the living things that break down dead plants and animals. I made a list of things found in soil. Not all of them are decomposers!",
    question: "Which of these are decomposers? Pick every one.",
    items: [
      { id: "worm", text: "Earthworms" },
      { id: "fungi", text: "Fungi, like mushrooms and mold" },
      { id: "bacteria", text: "Bacteria too small to see" },
      { id: "pillbug", text: "Pill bugs" },
      { id: "pebble", text: "Pebbles" },
      { id: "sun", text: "Sunlight" },
    ],
    hint: "A decomposer is ALIVE, and it breaks down dead things.",
    meter: { supplies: 1, label: "Soil cores +1", story: "The decomposer list is checked" },
    discovery: { id: "pillbugs", name: "Pill bugs", who: "Nova", fact: "Pill bugs, also called roly-polies, are not insects. They are related to crabs and shrimp, and they eat dead leaves and wood." },
    answer: { kind: "multi", correct: ["worm", "fungi", "bacteria", "pillbug"] },
    rightFeedback: "Worms, fungi, bacteria, and pill bugs are all alive, and they break down dead things. Pebbles and sunlight are not alive.",
    wrong: [
      { pick: "pebble", hint: "A pebble is a bit of rock. Is it alive? Can it eat dead leaves?" },
      { pick: "sun", hint: "Sunlight gives warmth, but it isn't alive. Decomposers are living things." },
      { missing: true, hint: "There are four decomposers. Some are too small to see!" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fast or slow?", machine: "Change Tracker", icon: "quake", speaker: "vega",
    line: "Cindara's surface changes in two ways, just like Earth's. Some changes take seconds or days. Others take hundreds of years.",
    question: "Sort each change: is it a fast change or a slow change?",
    hint: "Could you watch it happen in one day? Or would it take longer than your whole life?",
    meter: { heat: 5, label: "Garden +5%", story: "The change tracker is sorted" },
    discovery: { id: "quakes", name: "Tiny earthquakes", who: "Kai", fact: "Earth has many earthquakes every day, but most are so small that people can't feel them." },
    answer: { kind: "sort", bins: { f1: "fast", f2: "slow", f3: "fast", f4: "slow", f5: "fast", f6: "slow" } },
    rightFeedback: "Volcanoes, earthquakes, and landslides change the land fast. Weathering and soil forming are slow.",
    sort: {
      bins: [{ id: "fast", label: "Fast change" }, { id: "slow", label: "Slow change" }],
      items: [
        { id: "f1", label: "A volcano erupts and lava covers a field" },
        { id: "f2", label: "Rain and ice break a boulder into sand" },
        { id: "f3", label: "An earthquake cracks the ground" },
        { id: "f4", label: "Dead leaves and rock bits build a layer of topsoil" },
        { id: "f5", label: "A landslide slides mud down a hill" },
        { id: "f6", label: "Lichens slowly crumble a rock" },
      ],
    },
    wrong: [
      { item: "f2", hint: "Breaking a whole boulder into sand takes a very long time. Fast or slow?" },
      { item: "f4", hint: "Topsoil builds up over hundreds of years. Fast or slow?" },
      { item: "f6", hint: "The card says 'slowly.' Fast or slow?" },
      { item: "f5", hint: "A landslide can happen in just seconds or minutes. Fast or slow?" },
      { item: "f3", hint: "An earthquake shakes the ground in seconds. Fast or slow?" },
      { item: "f1", hint: "Lava can cover a field in hours or days. Fast or slow?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The drain race", machine: "Drain Test", icon: "water", speaker: "vega",
    line: "Surprise! A rainstorm is coming to camp, and our garden beds need soil that won't turn into a swamp. Nova ran a drain test. She put the same amount of three soils in three cups with holes. She poured 100 mL of water into each cup and measured what came out the bottom in 1 minute.",
    question: "Part 1: How many mL of water did the clay hold back? Part 2: How many more mL passed through sand than through clay? Part 3: Which soil holds water best? Part 4: Pick the things Nova kept the same.",
    data: {
      title: "Water that passed through in 1 minute (100 mL poured in)",
      columns: ["Soil", "Water that came out (mL)"],
      rows: [
        ["Sand", "80"],
        ["Potting soil", "45"],
        ["Clay", "10"],
      ],
    },
    parts: [
      { type: "number", prompt: "Nova poured 100 mL into the clay cup, and 10 mL came out. How many mL did the clay hold back?", unit: "mL" },
      { type: "number", prompt: "How many more mL of water passed through sand than through clay?", unit: "mL" },
      { type: "choice", prompt: "Which soil holds water best?", choices: [
        { id: "a", text: "Clay, because the least water came out of it." },
        { id: "b", text: "Sand, because the most water came out of it." },
        { id: "c", text: "Potting soil, because it is in the middle." },
        { id: "d", text: "They all hold the same amount of water." },
      ] },
      { type: "multi", prompt: "Pick the things Nova kept the same.", choices: [
        { id: "water", text: "The amount of water poured in" },
        { id: "soilamt", text: "The amount of soil in each cup" },
        { id: "time", text: "How long she waited (1 minute)" },
        { id: "type", text: "The kind of soil" },
        { id: "out", text: "How much water came out" },
      ] },
    ],
    hint: "Less water coming out means more water stayed in the soil.",
    meter: { heat: 10, label: "Garden +10%", story: "The crew knows which soil drains" },
    discovery: { id: "grains", name: "Grain sizes", who: "Nova", fact: "Clay grains are the tiniest soil grains. A big sand grain can be more than 1,000 times wider than a clay grain." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 90 },
      { kind: "number", value: 70 },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["water", "soilamt", "time"] },
    ] },
    rightFeedback: "Sand drains fast, and clay holds water tight. You spotted what kept the test fair, too!",
    wrong: [
      { step: 1, value: 10, hint: "10 mL is what came out. How much of the 100 mL stayed in the clay?" },
      { step: 1, value: 110, hint: "You want what stayed in the cup. Should you add or subtract?" },
      { step: 2, value: 90, hint: "Sand let 80 mL through, and clay let 10 mL through. What is the difference?" },
      { step: 2, value: 35, hint: "35 compares sand and potting soil. Compare sand with clay." },
      { step: 2, value: 80, hint: "80 mL is what passed through sand. How many MORE than clay's 10 mL?" },
      { step: 3, choice: "b", hint: "Lots of water ran out of the sand. Did the sand hold on to the water?" },
      { step: 3, choice: "c", hint: "Potting soil held some water. Which soil let the LEAST water out?" },
      { step: 3, choice: "d", hint: "The amounts were 80, 45, and 10 mL. Are those the same?" },
      { step: 4, pick: "type", hint: "The kind of soil is the one thing Nova changed on purpose." },
      { step: 4, pick: "out", hint: "The water that came out is what Nova measured. It was different for each soil." },
      { step: 4, missing: true, hint: "Three things stayed the same. Read Commander Vega's message again." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The first soil on Cindara", machine: "Rock Lab", icon: "scan", speaker: "nova",
    line: "Two lava fields on Cindara cooled at the same time. Field A is bare, dry rock. Field B gets rain, and lichens and moss grow in its cracks.",
    question: "Which field will start to make soil sooner, and why?",
    hint: "What two things help make soil? Which field has both?",
    meter: { heat: 10, label: "Garden +10%", story: "The crew finds where soil will start" },
    discovery: { id: "lichens", name: "Lichens", who: "Nova", fact: "Lichens can grow on bare rock. They slowly help break the rock apart. When they die, they add bits of living remains that help start new soil." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Field A, because nothing is in the way of the rock." },
      { id: "b", text: "Field B, because rain and living things help weather the rock and add remains that decompose." },
      { id: "c", text: "Both the same, because they cooled at the same time." },
      { id: "d", text: "Neither one. Lava rock can never become soil." },
    ],
    rightFeedback: "Rain and lichens help break rock into bits, and dead lichens and moss rot into humus. Field B will make soil first.",
    wrong: [
      { choice: "a", hint: "Bare, dry rock has no rain to weather it and nothing living to rot. Which field has both?" },
      { choice: "c", hint: "They started at the same time, but one field has rain and living things. Does that help?" },
      { choice: "d", hint: "All soil on Earth started as rock. Lava rock weathers too. Which field has more help?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's upside-down soil", machine: "Soil Core", icon: "snap", speaker: "kai",
    line: "I drew the layers of Earth soil for our garden guide. Top to bottom: solid bedrock, then broken rock pieces, then lighter subsoil, then dark topsoil. Done!",
    question: "Part 1: What went wrong in Kai's drawing? Part 2: Fix it. Put the layers in order from the top (the surface) down to the bottom.",
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's drawing?", choices: [
        { id: "a", text: "He drew it upside down. Dark topsoil is at the top, and solid bedrock is at the bottom." },
        { id: "b", text: "He forgot that soil has no layers." },
        { id: "c", text: "Bedrock should be in the middle." },
        { id: "d", text: "Nothing. Bedrock is always on top." },
      ] },
      { type: "order", prompt: "Put the layers in order from the top down.", items: [
        { id: "sub", text: "Subsoil: lighter, with more clay and rock bits" },
        { id: "bed", text: "Bedrock: solid rock" },
        { id: "top", text: "Topsoil: dark, with lots of humus and roots" },
        { id: "broken", text: "Broken rock pieces" },
      ] },
    ],
    hint: "Dead leaves fall on top of the ground. Where would the most humus be?",
    meter: { supplies: 1, label: "Soil cores +1", story: "Kai's garden guide is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "order", correct: ["top", "sub", "broken", "bed"] },
    ] },
    rightFeedback: "Dark topsoil is on top, where leaves fall and rot. Deeper down, the rock is less broken, until you reach solid bedrock.",
    wrong: [
      { step: 1, choice: "b", hint: "Kai drew four layers, and real soil has layers too. What's wrong with his order?" },
      { step: 1, choice: "c", hint: "Bedrock is the solid rock that soil forms from. Is it on top, in the middle, or at the bottom?" },
      { step: 1, choice: "d", hint: "Plants grow in the top layer. Can roots grow in solid rock?" },
      { step: 2, position: 0, hint: "Which layer gets the most dead leaves and roots? That one is on top." },
      { step: 2, position: 1, hint: "Under the topsoil is a lighter layer with more clay and rock bits." },
      { step: 2, position: 2, hint: "Just above the solid rock, the rock is broken into pieces." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Why so dark?", machine: "Soil Core", icon: "cells", speaker: "vega",
    line: "The Earth soil sample from Texas has a very dark top layer. The layers deeper down are lighter.",
    question: "Why is the top layer of soil usually the darkest?",
    hint: "What falls on the ground and rots there?",
    meter: { heat: 5, label: "Garden +5%", story: "The dark layer is explained" },
    discovery: { id: "houston", name: "The Texas state soil", who: "Nova", fact: "Texas has a state soil called Houston Black. It is a dark clay soil found in the Blackland Prairie, and it is great for growing crops." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "It has the most humus, from dead plants and animals that decompose at the surface." },
      { id: "b", text: "It is burned by the sun." },
      { id: "c", text: "It is made of lava." },
      { id: "d", text: "It is wet all the time." },
    ],
    rightFeedback: "Leaves, roots, and animals decompose at the top, so topsoil gets the most dark humus.",
    wrong: [
      { choice: "b", hint: "The sun doesn't burn soil black. What dark stuff do decomposers make at the surface?" },
      { choice: "c", hint: "This soil is from Texas, not a volcano. What dark stuff comes from rotted plants?" },
      { choice: "d", hint: "Wet soil looks darker, but the top layer stays dark even when dry. What is in it?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Soil helpers", machine: "Change Tracker", icon: "log", speaker: "kai",
    line: "I want to help Cindara make soil faster for the next crew. Which of these things actually help make new soil?",
    question: "Which things help make new soil? Pick every one.",
    items: [
      { id: "ice", text: "Water freezing in rock cracks and breaking the rock" },
      { id: "leaves", text: "Dead leaves rotting on the ground" },
      { id: "worms", text: "Worms mixing humus into rock bits" },
      { id: "fungi", text: "Fungi breaking down an old log" },
      { id: "plastic", text: "A plastic bag left on the ground" },
      { id: "pave", text: "Covering the ground with concrete" },
    ],
    hint: "Soil comes from broken rock and from things that were alive. Which choices do that?",
    meter: { heat: 5, label: "Garden +5%", story: "Kai's soil helper list is ready" },
    answer: { kind: "multi", correct: ["ice", "leaves", "worms", "fungi"] },
    rightFeedback: "Weathering breaks rock into bits, and decomposers turn dead things into humus. Plastic and concrete don't make soil.",
    wrong: [
      { pick: "plastic", hint: "Plastic was never alive, and decomposers can't break it down. Will it turn into humus?" },
      { pick: "pave", hint: "Concrete covers the ground, so no leaves, worms, or rain can get in. Does that help make soil?" },
      { missing: true, hint: "There are four helpers. Think about weathering AND decomposing." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The garden bed", machine: "Garden Dome", icon: "relay", speaker: "vega",
    line: "This is it! A small earthquake just shook camp, and a landslide of rocks covered our garden spot. We have to build new garden beds with soil from the ship. Vegetables need soil that holds some water but still lets extra water drain.",
    question: "Part 1: Was the landslide a fast or slow change? Part 2: Use the drain test. Which soil is best for the garden? Part 3: Each bed needs 3 bags of soil. How many bags for 4 beds? Part 4: Write to Commander Vega. Explain your soil choice using the drain test data.",
    data: {
      title: "Drain test: water that passed through in 1 minute (100 mL poured in)",
      columns: ["Soil", "Water that came out (mL)", "What we saw"],
      rows: [
        ["Sand", "80", "Dry again very fast"],
        ["Potting soil (sand, clay, and humus)", "45", "Damp and crumbly"],
        ["Clay", "10", "Puddle sat on top"],
      ],
    },
    parts: [
      { type: "choice", prompt: "Was the landslide a fast change or a slow change?", choices: [
        { id: "a", text: "Fast. It changed the land in just minutes." },
        { id: "b", text: "Slow. It took hundreds of years." },
        { id: "c", text: "It was not a change to the land." },
        { id: "d", text: "Slow, like soil forming." },
      ] },
      { type: "choice", prompt: "Which soil is best for the vegetable garden?", choices: [
        { id: "a", text: "Potting soil. It holds some water, drains the extra, and has humus for food." },
        { id: "b", text: "Sand. Water runs right through, so roots dry out." },
        { id: "c", text: "Clay. Water sits on top, so roots get soggy." },
        { id: "d", text: "Rocks from the landslide." },
      ] },
      { type: "number", prompt: "Each bed needs 3 bags of soil. How many bags for 4 beds?", unit: "bags" },
      { type: "write", prompt: "Explain to Commander Vega why your soil is best for the garden. Use the drain test data.", minWords: 20 },
    ],
    rubric: ["Chooses potting soil (or a mix with humus)", "Uses data from the table (a number of mL or what was seen)", "Explains that the soil holds some water but drains extra, or that humus feeds plants"],
    hint: "Vegetables want soil in the middle: not too dry, not too soggy.",
    meter: { heat: 10, label: "Garden +10%", story: "The garden beds are planted" },
    discovery: { id: "loam", name: "Loam", who: "Kai", fact: "Gardeners call soil with a good mix of sand, silt, and clay loam. Loam holds some water but still lets extra water drain away." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 12 },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The garden is planted in soil that is just right! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "b", hint: "The landslide happened just now, in one moment. Fast or slow?" },
      { step: 1, choice: "c", hint: "Rocks now cover the garden spot. Did the land change?" },
      { step: 1, choice: "d", hint: "Soil forming takes hundreds of years. The landslide happened today. Fast or slow?" },
      { step: 2, choice: "b", hint: "80 mL ran out of the sand and it dried fast. Would roots get enough water?" },
      { step: 2, choice: "c", hint: "Only 10 mL drained from clay, and a puddle sat on top. Would roots get too soggy?" },
      { step: 2, choice: "d", hint: "Rocks have no humus and hold almost no water. Which soil is in the middle?" },
      { step: 3, value: 7, hint: "3 bags for EACH of 4 beds. Should you add or multiply?" },
      { step: 3, value: 3, hint: "3 bags is for one bed. There are 4 beds." },
      { step: 3, value: 4, hint: "4 is the number of beds. Each bed needs 3 bags." },
    ],
  },
};

export default {
  id: "SCI.3.10B-XP",
  standard: "SCI.3.10B-XP",
  engine: "expedition_station",
  title: "The Soil Makers",
  planet: "Cindara",
  outpost: "Cinder Flats Garden · growing season",
  grade: 3,
  subject: "Science",
  teks: "3.10B",
  supportingTeks: ["3.10C", "3.1B", "3.1E", "3.2B", "3.2C", "3.2D", "3.3A", "3.3C", "3.5B", "3.5G"],
  skillsChip: "3.10B · How soil forms",
  iCan: "I can explain how soils like sand and clay form from weathered rock and from dead plants and animals that decompose. I can compare soils by grain size, feel, and how much water they hold, and tell fast changes from slow ones.",
  blurb: "Cindara's old lava rock is slowly turning into soil. To plant the first garden, the crew studies how real Earth soil forms and which soil is best for growing food.",
  mission: "Find out how soil forms, test sand, clay, and potting soil, and choose the best soil for the camp garden.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.10 · CINDARA CINDER FLATS",
  playableActs: [1, 2, 3],
  earthTrue: "Cindara and the crew are invented. Every soil, decomposer, test, and data table in this quest is real Earth science.",
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Garden grown", heatUnit: "%", supplies: "Soil cores", suppliesUnit: "cores" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Our crew wants to plant the first garden on Cindara.",
    "The old lava rock here is slowly breaking down into soil, just like rock does on Earth.",
    "Help us learn how real soil forms, and pick the best soil for our garden. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Where soil comes from", "Act 2 · Test the soil", "Act 3 · Plant the garden"],
    completes: [
      "You found out how rock and rotting leaves become soil, {firstName}!",
      "You sorted the soil parts and won the drain race, {firstName}!",
      "The garden beds are planted in just-right soil, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Cindara: Kai thinks soil never forms, and Nova races water through three soils. Act 2 is open now, or come back to it next time.",
      "Next on Cindara: Kai draws the soil upside down, and the ground starts to shake. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Today we test sand, silt, clay, and humus, and Kai and I already disagree about something.",
      "Let's get our hands dirty.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our soil tests are done. It's time to plant the garden.",
      "Choose soil that will help our plants grow.",
    ],
  }),
  tasks,
};
