// Expedition Station — The Spinning Earth (SCI.5.9-XP)
// Grade 5 · Science · Cloudreach (sky reef). Main standard 5.9 (2024 TEKS:
// demonstrate that Earth rotates on its axis once approximately every 24
// hours and explain how that causes the day/night cycle and the appearance of
// the Sun moving across the sky, resulting in changes in shadow positions and
// shapes); also practices 5.1E (collect observations and measurements as
// evidence), 5.1F (organize data in tables and bar graphs), 5.1G (develop and
// use models), 5.2B (analyze data for patterns), 5.2C (use math to compare
// data), 5.3A (explanations supported by data and models), 5.3B (communicate
// explanations), 5.3C (respectful scientific discussion), 5.5A (use patterns
// to explain and predict), 5.5B (cause and effect).
//
// Earth-true rule: Cloudreach and the crew are invented. The shadow-stick
// data are real Earth values, rounded: a 100 cm stick in central Texas
// (Austin, about 30° north) near the end of September. Times are "Sun time,"
// so 12:00 noon is when the Sun is highest (on a wall clock with daylight
// saving time, that happens a little after 1:00 p.m.).
import { CREW, acts } from "./_shared.js";

const SHADOW_DATA = {
  title: "Texas shadow stick: 100 cm stick, late September (about)",
  columns: ["Time (Sun time)", "Shadow length (cm)", "Shadow points toward"],
  rows: [
    ["8:00 a.m.", "210", "West"],
    ["10:00 a.m.", "90", "Northwest"],
    ["12:00 noon", "60", "North"],
    ["2:00 p.m.", "90", "Northeast"],
    ["4:00 p.m.", "210", "East"],
  ],
};
const SHADOW_BARS = {
  type: "bars",
  title: "Texas shadow stick: shadow length (cm, about)",
  categories: [
    { label: "8 a.m.", value: 210 }, { label: "10 a.m.", value: 90 }, { label: "Noon", value: 60 },
    { label: "2 p.m.", value: 90 }, { label: "4 p.m.", value: 210 },
  ],
  step: 50,
  max: 250,
  axis: "Shadow length (cm)",
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Texas wakes up", machine: "Reef Telescope", icon: "scan", speaker: "nova",
    line: "The reef telescope is locked on Earth. Look! Texas is just turning out of the dark side and into the sunlight.",
    question: "What time of day is it in Texas right now?",
    hint: "Texas is moving from night into day. What do we call that moment?",
    meter: { heat: 10, label: "Sky clock +10%", story: "The telescope finds Texas" },
    discovery: { id: "spinspeed", name: "Earth's spin speed", who: "Nova", fact: "At the equator, the ground spins with Earth at about 1,000 miles per hour. We don't feel it because we, the ground, and the air all move together." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Sunrise, the start of the day" },
      { id: "b", text: "Noon, the middle of the day" },
      { id: "c", text: "Sunset, the end of the day" },
      { id: "d", text: "Midnight, the middle of the night" },
    ],
    rightFeedback: "Right! As Earth turns, Texas rolls out of the dark and into sunlight. That's sunrise.",
    wrong: [
      { choice: "b", hint: "At noon, Texas would face the Sun straight on. Texas is only just coming out of the dark." },
      { choice: "c", hint: "At sunset, Texas would be turning from light INTO dark. Which way is it going?" },
      { choice: "d", hint: "At midnight, Texas would be in the middle of the dark side. Texas is at the edge, turning into light." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "One full turn", machine: "Spin Timer", icon: "dial", speaker: "kai",
    line: "I started the spin timer when Texas faced the Sun at noon. I'll stop it when Texas comes all the way around to noon again.",
    question: "About how many hours will the spin timer show?",
    unit: "hours",
    hint: "One full spin of Earth makes one day and one night. How many hours are in a day?",
    meter: { supplies: 1, label: "Shadow marks +1", story: "The spin timer is set" },
    discovery: { id: "starday", name: "A star day", who: "Kai", fact: "Measured against faraway stars, Earth spins once in about 23 hours and 56 minutes. Our 24-hour day is a few minutes longer because Earth also moves along its path around the Sun." },
    answer: { kind: "number", value: 24 },
    rightFeedback: "About 24 hours. Earth rotates on its axis once about every 24 hours.",
    wrong: [
      { value: 12, hint: "12 hours gets Texas only halfway around, to midnight. Keep going until it's back to noon." },
      { value: 365, hint: "365 is about how many DAYS Earth takes to go around the Sun. How many hours does one spin take?" },
      { value: 1, hint: "One spin takes one DAY, not one hour. How many hours is that?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The Sun's sky path", machine: "Sky Chart", icon: "trail", speaker: "vega",
    line: "The Texas partner station sent sky photos from one day. The photos got shuffled on the way up to the reef.",
    question: "Put the Sun's positions in order, from morning to evening.",
    hint: "The Sun rises in one direction, climbs highest near the middle of the day, and sets in the opposite direction.",
    meter: { heat: 10, label: "Sky clock +10%", story: "The sky photos are in order" },
    discovery: { id: "eastward", name: "Why things rise in the east", who: "Nova", fact: "Earth spins toward the east. That's why the Sun, the Moon, and the stars all seem to rise in the east and set in the west." },
    answer: { kind: "order", correct: ["rise", "morning", "noon", "set"] },
    items: [
      { id: "noon", text: "The Sun is at its highest, in the southern part of the sky." },
      { id: "set", text: "The Sun sinks low in the west." },
      { id: "rise", text: "The Sun peeks up low in the east." },
      { id: "morning", text: "The Sun climbs higher in the southeast." },
    ],
    rightFeedback: "East to south to west. The Sun seems to travel across the sky because Earth is spinning.",
    wrong: [
      { position: 0, hint: "The day starts at sunrise. In which direction does the Sun rise?" },
      { position: 1, hint: "After sunrise, the Sun climbs higher. It isn't at its highest yet." },
      { position: 2, hint: "The Sun is highest in the middle of the day, before it starts sinking." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Spin or orbit?", machine: "Motion Sorter", icon: "cells", speaker: "kai",
    line: "Earth does two motions at once. It spins on its axis, and it travels around the Sun. I keep mixing them up.",
    question: "Sort each effect: is it caused by Earth spinning (rotation) or by Earth traveling around the Sun (revolution)?",
    hint: "Rotation takes about one day. Revolution takes about one year. How long does each effect take?",
    meter: { supplies: 1, label: "Shadow marks +1", story: "Kai's motion chart is fixed" },
    discovery: { id: "jupiter", name: "Jupiter's short day", who: "Kai", fact: "Jupiter spins faster than any other planet in our solar system. One day on Jupiter lasts only about 10 hours." },
    answer: { kind: "sort", bins: { m1: "rot", m2: "rot", m3: "rot", m4: "rev", m5: "rev" } },
    rightFeedback: "Day, night, sunrise, and moving shadows come from the spin. A year and the seasons come from the trip around the Sun.",
    sort: {
      bins: [{ id: "rot", label: "Earth spinning (rotation)" }, { id: "rev", label: "Earth going around the Sun (revolution)" }],
      items: [
        { id: "m1", label: "Day and night" },
        { id: "m2", label: "The Sun rising and setting" },
        { id: "m3", label: "A shadow moving during one day" },
        { id: "m4", label: "One year, about 365 days" },
        { id: "m5", label: "The seasons changing" },
      ],
    },
    wrong: [
      { item: "m5", hint: "Seasons take a whole year to cycle. Does one spin take a year?" },
      { item: "m1", hint: "Day and night happen every 24 hours. Which motion takes about 24 hours?" },
      { item: "m3", hint: "A shadow moves in just a few hours. Which motion is that fast?" },
      { item: "m4", hint: "A year is one full trip around the Sun." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The shadow stick report", machine: "Shadow Stick", icon: "quake", speaker: "vega",
    line: "Surprise! A sky storm fogged the telescope. We can't see Earth, but the Texas partner station just sent its shadow-stick data. They set their clock so 12:00 noon is when the Sun is highest.",
    question: "Part 1: When is the shadow shortest? Part 2: How much longer is the 8:00 a.m. shadow than the noon shadow? Part 3: Which way does the shadow point at 4:00 p.m.?",
    data: SHADOW_DATA,
    parts: [
      { type: "choice", prompt: "When is the shadow the shortest?", choices: [
        { id: "a", text: "12:00 noon" },
        { id: "b", text: "8:00 a.m." },
        { id: "c", text: "4:00 p.m." },
        { id: "d", text: "It's the same all day." },
      ], visual: SHADOW_BARS },
      { type: "number", prompt: "How many centimeters longer is the 8:00 a.m. shadow than the noon shadow?", unit: "cm", visual: SHADOW_BARS },
      { type: "choice", prompt: "Which way does the shadow point at 4:00 p.m.?", choices: [
        { id: "a", text: "East" },
        { id: "b", text: "West" },
        { id: "c", text: "South" },
        { id: "d", text: "Straight down, with no shadow" },
      ] },
    ],
    hint: "Read one row at a time. A shadow always points away from the Sun.",
    meter: { heat: 10, label: "Sky clock +10%", story: "The storm clears, and the data is logged" },
    discovery: { id: "texasnorth", name: "Texas noon shadows", who: "Nova", fact: "Texas is too far north for the Sun to ever be straight overhead. So at midday, shadows in Texas point north all year long." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 150 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The shadow is shortest at noon, 150 cm shorter than at 8:00, and it swings to the east by late afternoon.",
    wrong: [
      { step: 1, choice: "b", hint: "The 8:00 a.m. shadow is 210 cm. That's one of the longest. Find the smallest number." },
      { step: 1, choice: "c", hint: "The 4:00 p.m. shadow is 210 cm. That's one of the longest. Find the smallest number." },
      { step: 1, choice: "d", hint: "Look at the Shadow length column. Are all the numbers the same?" },
      { step: 2, value: 270, hint: "You added. To find how much longer, subtract: 210 − 60." },
      { step: 2, value: 210, hint: "210 cm is the whole 8:00 shadow. How much longer is it than the 60 cm noon shadow?" },
      { step: 2, value: 60, hint: "60 cm is the noon shadow. How much longer is the 8:00 shadow?" },
      { step: 3, choice: "b", hint: "The shadow pointed west in the MORNING. By late afternoon the Sun is in the west. Which way does the shadow point now?" },
      { step: 3, choice: "c", hint: "In Texas the Sun is in the southern sky, so shadows never point south. Check the 4:00 p.m. row." },
      { step: 3, choice: "d", hint: "The table shows a 210 cm shadow at 4:00 p.m. Which way does it point?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Who's really moving?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Easy! The Sun goes all the way around Earth every day. That\'s why it crosses the sky."',
    nova: 'Nova: "It only looks that way. Earth is the one spinning."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "When a car drives past trees, the trees look like they zoom by. Who is really moving?",
    meter: { heat: 5, label: "Sky clock +5%", story: "Kai watches Earth spin in the telescope" },
    discovery: { id: "foucault", name: "Foucault's pendulum", who: "Nova", fact: "In 1851, Léon Foucault hung a heavy ball from a very long wire in Paris. Hour by hour, the direction of its swing slowly turned. That showed people Earth really spins." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Earth rotates toward the east about once every 24 hours, so the Sun only appears to move from east to west across the sky." },
      { id: "B", text: "Nova, because the Sun is very hot." },
      { id: "C", text: "Kai. We can see the Sun move, so it must be moving around Earth." },
      { id: "D", text: "Kai. The Sun goes around Earth once a year." },
    ],
    writtenPrompt: "Tell Kai in your own words why the Sun seems to move across the sky.",
    debateHints: {
      wrongWho: "Look through the telescope. Is the Sun circling Earth, or is Earth turning?",
      wrongReason: "Right person, check the reason. Which motion makes the Sun seem to cross the sky?",
      right: "Nova is right! Earth's rotation makes the Sun appear to move across the sky.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Flashlight and globe", machine: "Model Deck", icon: "snap", speaker: "nova",
    line: "Let's model it on the Model Deck. The flashlight is the Sun. The globe is Earth, with a sticker on Texas.",
    question: "Part 1: How should Kai move the globe to show one day and one night? Part 2: When the Texas sticker faces away from the flashlight, what time is it in Texas?",
    parts: [
      { type: "choice", prompt: "How should Kai move the globe to show one day and one night?", choices: [
        { id: "a", text: "Spin the globe one full turn on its axis while the flashlight stays still." },
        { id: "b", text: "Walk the flashlight in a circle around the globe." },
        { id: "c", text: "Carry the globe in one big circle around the flashlight." },
        { id: "d", text: "Turn the flashlight off and on." },
      ] },
      { type: "choice", prompt: "The Texas sticker faces away from the flashlight. What time is it in Texas?", choices: [
        { id: "a", text: "Night" },
        { id: "b", text: "Noon" },
        { id: "c", text: "Sunrise" },
        { id: "d", text: "Summer" },
      ] },
    ],
    hint: "In real life, the Sun stays put and Earth spins. Make the model do the same thing.",
    meter: { supplies: 1, label: "Shadow marks +1", story: "The globe model spins" },
    discovery: { id: "terminator", name: "The day-night line", who: "Nova", fact: "The edge between the day side and the night side of Earth is called the terminator. From space, astronauts can watch it slide across Earth as Earth turns." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "One spin of the globe shows one day and one night. The side facing away from the light is having night.",
    wrong: [
      { step: 1, choice: "b", hint: "That shows the Sun going around Earth. In real life, which one moves?" },
      { step: 1, choice: "c", hint: "Circling the flashlight shows a year. Day and night come from a different motion." },
      { step: 1, choice: "d", hint: "The real Sun never turns off. What makes Texas go dark?" },
      { step: 2, choice: "b", hint: "At noon, Texas would face the flashlight straight on." },
      { step: 2, choice: "c", hint: "At sunrise, Texas would be just turning INTO the light." },
      { step: 2, choice: "d", hint: "Summer is a season. It takes months. What happens when your side faces away from the Sun?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The 3 o'clock shadow", machine: "Shadow Stick", icon: "log", speaker: "kai",
    line: "The Texas station forgot to measure at 3:00 p.m. Can we predict the shadow from the pattern?",
    question: "Use the data. Predict the shadow at 3:00 p.m.",
    data: SHADOW_DATA,
    hint: "3:00 p.m. is between 2:00 and 4:00. What happens to the shadow between those times?",
    meter: { heat: 5, label: "Sky clock +5%", story: "The missing shadow is predicted" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Shorter than 60 cm, pointing north" },
      { id: "b", text: "Between 90 cm and 210 cm long, pointing between northeast and east" },
      { id: "c", text: "Between 90 cm and 210 cm long, pointing west" },
      { id: "d", text: "No shadow at all" },
    ],
    rightFeedback: "Good prediction! In the afternoon the Sun sinks lower in the west, so the shadow grows longer and swings toward the east.",
    wrong: [
      { choice: "a", hint: "The shortest shadow was at noon. After noon, does the shadow get longer or shorter?" },
      { choice: "c", hint: "West shadows happen in the morning, when the Sun is in the east. Where is the Sun at 3:00 p.m.?" },
      { choice: "d", hint: "The Sun is still up at 3:00 p.m., so the stick makes a shadow. How long?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The other side of Earth", machine: "Reef Telescope", icon: "scan", speaker: "vega",
    line: "Right now it's noon in Texas. Swing the telescope to the far side of Earth, the side directly opposite Texas.",
    question: "Pick every sentence that is true right now.",
    items: [
      { id: "night", text: "It is nighttime on the side of Earth opposite Texas." },
      { id: "faces", text: "Texas is facing the Sun." },
      { id: "later", text: "About 12 hours from now, Texas will be on the night side." },
      { id: "alldays", text: "It is daytime everywhere on Earth at the same time." },
      { id: "off", text: "The Sun has stopped shining on the far side." },
    ],
    hint: "The Sun lights only the half of Earth that faces it. As Earth spins, places take turns.",
    meter: { supplies: 1, label: "Shadow marks +1", story: "Both sides of Earth are logged" },
    answer: { kind: "multi", correct: ["night", "faces", "later"] },
    rightFeedback: "When it's day in Texas, it's night on the other side. In about 12 hours, they switch.",
    wrong: [
      { pick: "alldays", hint: "The Sun lights only the half of Earth facing it. What about the other half?" },
      { pick: "off", hint: "The Sun always shines. The far side is just turned away from it." },
      { missing: true, hint: "There are three true sentences." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The scrambled shadow log", machine: "Shadow Stick", icon: "static", speaker: "vega",
    line: "Surprise! A gust blew the Texas station's shadow cards off the table. The times rubbed off, but the lengths and directions are still there. Then a message came in from a station on the far side of Earth.",
    question: "Part 1: Put the shadow cards in order from morning to late afternoon. Part 2: Why does the shadow swing from west to east? Part 3: What does the far-side station see when the Texas shadow is shortest?",
    parts: [
      { type: "order", prompt: "Put the shadow cards in order, from morning to late afternoon.", items: [
        { id: "ne", text: "90 cm, pointing northeast" },
        { id: "w", text: "210 cm, pointing west" },
        { id: "e", text: "210 cm, pointing east" },
        { id: "n", text: "60 cm, pointing north" },
        { id: "nw", text: "90 cm, pointing northwest" },
      ] },
      { type: "choice", prompt: "Why does the shadow swing from west to east during the day?", choices: [
        { id: "a", text: "Earth spins, so the Sun appears to move from east to west, and the shadow always points away from the Sun." },
        { id: "b", text: "The wind pushes the shadow along." },
        { id: "c", text: "Earth's trip around the Sun moves the shadow every hour." },
        { id: "d", text: "The stick slowly turns in the ground." },
      ] },
      { type: "choice", prompt: "The Texas shadow is at its shortest. What does the station on the opposite side of Earth see?", choices: [
        { id: "a", text: "Night. Its side of Earth faces away from the Sun, so its stick has no Sun shadow." },
        { id: "b", text: "Noon, with the same short shadow" },
        { id: "c", text: "Sunrise" },
        { id: "d", text: "A long shadow pointing south" },
      ] },
    ],
    hint: "Morning shadows point west, midday shadows are short, and afternoon shadows point east.",
    meter: { heat: 10, label: "Sky clock +10%", story: "The shadow log is rebuilt" },
    discovery: { id: "nightlights", name: "Lights on the night side", who: "Kai", fact: "From space, the night side of Earth sparkles with city lights. Astronauts can trace coastlines and big cities just by their glow." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["w", "nw", "n", "ne", "e"] },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Log rebuilt! The shadow swings from west to east as Earth spins, and the far side of Earth is in the middle of its night.",
    wrong: [
      { step: 1, position: 0, hint: "Early morning comes first. The Sun is low in the east, so the shadow is long and points west." },
      { step: 1, position: 1, hint: "After the long west shadow, the Sun climbs higher, so the shadow gets shorter. It still points a little west." },
      { step: 1, position: 2, hint: "The shortest shadow comes in the middle of the day." },
      { step: 1, position: 3, hint: "After noon, the shadow starts growing again and turns toward the east." },
      { step: 2, choice: "b", hint: "Wind can't move a shadow. What makes the Sun seem to move?" },
      { step: 2, choice: "c", hint: "The trip around the Sun takes a whole year. Which motion happens in one day?" },
      { step: 2, choice: "d", hint: "The stick stays still. What is changing is where the Sun appears in the sky." },
      { step: 3, choice: "b", hint: "Only the half of Earth facing the Sun has day. Is the opposite side facing the Sun?" },
      { step: 3, choice: "c", hint: "Sunrise happens at the edge between night and day. The far side is right in the middle of the dark half." },
      { step: 3, choice: "d", hint: "A Sun shadow needs sunlight. Is the far side in sunlight?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Kai's shadow note", machine: "Shadow Stick", icon: "log", speaker: "kai",
    line: 'Kai wrote this in the shadow log: "Shadows are longest at noon, because that\'s when the Sun is highest in the sky."',
    question: "Part 1: What went wrong in Kai's note? Part 2: What should the note say?",
    data: SHADOW_DATA,
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's note?", choices: [
        { id: "a", text: "He mixed it up. A high Sun makes a SHORT shadow, so noon shadows are the shortest." },
        { id: "b", text: "Nothing. The note is correct." },
        { id: "c", text: "He should have said shadows are longest at midnight." },
        { id: "d", text: "He should have said shadows never change." },
      ] },
      { type: "choice", prompt: "What should the note say?", choices: [
        { id: "a", text: "Shadows are longest early in the morning and late in the afternoon, when the Sun is low in the sky." },
        { id: "b", text: "Shadows are longest at noon, when the Sun is low." },
        { id: "c", text: "Shadows are the same length all day." },
        { id: "d", text: "Shadows are longest in winter only." },
      ] },
    ],
    hint: "Check the table. Which time has the shortest shadow? When is the Sun highest?",
    meter: { supplies: 1, label: "Shadow marks +1", story: "Kai's note is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Fixed! A low Sun makes long shadows. A high Sun makes short shadows.",
    wrong: [
      { step: 1, choice: "b", hint: "Look at the noon row. Is 60 cm the longest shadow or the shortest?" },
      { step: 1, choice: "c", hint: "At midnight the Sun is down, so there's no Sun shadow at all." },
      { step: 1, choice: "d", hint: "The table shows shadows from 60 cm to 210 cm. Do they change?" },
      { step: 2, choice: "b", hint: "At noon the Sun is at its HIGHEST, not low. Which times have the long shadows?" },
      { step: 2, choice: "c", hint: "The lengths in the table change from hour to hour." },
      { step: 2, choice: "d", hint: "This table is from one day in September. When were the shadows longest that day?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Halfway around", machine: "Spin Timer", icon: "dial", speaker: "nova",
    line: "It's noon in Texas again. I'm resetting the spin timer.",
    question: "About how many hours from now will it be midnight in Texas?",
    unit: "hours",
    hint: "Noon is the middle of the day. Midnight is the middle of the night. How much of one spin is that?",
    meter: { heat: 10, label: "Sky clock +10%", story: "The spin timer is right on time" },
    answer: { kind: "number", value: 12 },
    rightFeedback: "About 12 hours. That's half of one full spin, so Texas ends up on the night side.",
    wrong: [
      { value: 24, hint: "24 hours brings Texas all the way back to noon. Midnight is only halfway around." },
      { value: 6, hint: "In 6 hours, Texas is only a quarter of the way around, near sunset. Keep going." },
      { value: 365, hint: "365 is days in a year. Earth spins once about every 24 hours. How far is halfway?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Stretchy shadows", machine: "Reef Telescope", icon: "scan", speaker: "nova",
    line: "The telescope zoomed in on a Texas playground. A student is standing in the same spot at noon and again at 5:00 p.m.",
    question: "How does the student's shadow look at 5:00 p.m. compared to noon?",
    hint: "At 5:00 p.m., the Sun is low in the west. What does a low Sun do to a shadow?",
    meter: { supplies: 1, label: "Shadow marks +1", story: "The playground shadows are logged" },
    discovery: { id: "lahaina", name: "Almost no shadow", who: "Nova", fact: "In Hawaii, the Sun is straight overhead at midday on a couple of days each year. People standing outside have almost no shadow. Hawaiians call it Lahaina Noon." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Short and stubby, pointing north" },
      { id: "b", text: "Long and stretched out, pointing west" },
      { id: "c", text: "Long and stretched out, pointing east" },
      { id: "d", text: "Exactly the same as at noon" },
    ],
    rightFeedback: "The low afternoon Sun stretches the shadow long and thin, and it points east, away from the Sun.",
    wrong: [
      { choice: "a", hint: "Short and stubby is the noon shadow, when the Sun is high. What happens when the Sun gets low?" },
      { choice: "b", hint: "The shadow is long, but it points away from the Sun. Where is the Sun in the late afternoon?" },
      { choice: "d", hint: "The Sun has moved across the sky since noon. Does the shadow stay the same?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Proof in the pattern", machine: "Sky Chart", icon: "trail", speaker: "vega",
    line: "The reef keepers asked us a tough question: how do people on Earth know Earth spins about once every 24 hours?",
    question: "Which evidence best supports the idea that Earth rotates about once every 24 hours?",
    hint: "Look for something that repeats once every day.",
    meter: { heat: 5, label: "Sky clock +5%", story: "The reef keepers are convinced" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Every day, the Sun rises in the east and sets in the west, and shadows repeat the same west-to-east pattern." },
      { id: "b", text: "Summer is warmer than winter." },
      { id: "c", text: "The Moon looks different over a month." },
      { id: "d", text: "Earth takes about 365 days to go around the Sun." },
    ],
    rightFeedback: "The Sun's path and the shadow pattern repeat about every 24 hours, one pattern for each spin.",
    wrong: [
      { choice: "b", hint: "Seasons take a year to repeat. That comes from Earth's trip around the Sun." },
      { choice: "c", hint: "The Moon's look changes over about a month. That's about the Moon, not Earth's spin." },
      { choice: "d", hint: "365 days is one trip around the Sun. Which pattern repeats every day?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The reef shadow clock", machine: "Shadow Stick", icon: "relay", speaker: "vega",
    line: "This is it! The reef keepers want a shadow clock like the one at the Texas station. Surprise: they want YOU to explain it at tonight's sky show.",
    question: "Part 1: A shadow is 60 cm long and points north. What time is it? Part 2: Sort the shadow cards into morning or afternoon. Part 3: Write 2–3 sentences to Commander Vega explaining why the shadow changes during the day.",
    data: SHADOW_DATA,
    parts: [
      { type: "choice", prompt: "The shadow is 60 cm long and points north. What time is it?", choices: [
        { id: "a", text: "About 12:00 noon" },
        { id: "b", text: "About 8:00 a.m." },
        { id: "c", text: "About 4:00 p.m." },
        { id: "d", text: "About midnight" },
      ] },
      { type: "sort", prompt: "Sort each shadow card: morning or afternoon?", bins: [
        { id: "am", label: "Morning" },
        { id: "pm", label: "Afternoon" },
      ], items: [
        { id: "c1", label: "Long shadow pointing west" },
        { id: "c2", label: "Long shadow pointing east" },
        { id: "c3", label: "Medium shadow pointing northwest" },
        { id: "c4", label: "Medium shadow pointing northeast" },
      ] },
      { type: "write", prompt: "Explain to Commander Vega why the shadow changes during the day. Use the data.", minWords: 20 },
    ],
    rubric: ["Says that Earth rotates on its axis about once every 24 hours", "Explains that the rotation makes the Sun appear to move from east to west", "Uses data to describe how the shadow's length and direction change"],
    hint: "A shadow points away from the Sun. Where is the Sun in the morning? In the afternoon?",
    meter: { heat: 10, label: "Sky clock +10%", story: "The reef shadow clock is ready for the show" },
    discovery: { id: "dinoday", name: "Shorter days long ago", who: "Kai", fact: "Earth's spin is slowing down very, very slowly. Back when dinosaurs lived, one day on Earth was about half an hour shorter than it is today." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "sort", bins: { c1: "am", c2: "pm", c3: "am", c4: "pm" } },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The reef shadow clock works! Your teacher will read your explanation.",
    wrong: [
      { step: 1, choice: "b", hint: "At 8:00 a.m. the shadow is long and points west. Find the 60 cm row." },
      { step: 1, choice: "c", hint: "At 4:00 p.m. the shadow is long and points east. Find the 60 cm row." },
      { step: 1, choice: "d", hint: "At midnight the Sun is down, so there's no Sun shadow." },
      { step: 2, item: "c1", hint: "A west shadow means the Sun is in the east. When is the Sun in the east?" },
      { step: 2, item: "c2", hint: "An east shadow means the Sun is in the west. When is the Sun in the west?" },
      { step: 2, item: "c3", hint: "Check the table. When does the shadow point northwest?" },
      { step: 2, item: "c4", hint: "Check the table. When does the shadow point northeast?" },
    ],
  },
};

export default {
  id: "SCI.5.9-XP",
  standard: "SCI.5.9-XP",
  engine: "expedition_station",
  title: "The Spinning Earth",
  planet: "Cloudreach",
  outpost: "Sky Reef · telescope deck",
  grade: 5,
  subject: "Science",
  teks: "5.9",
  supportingTeks: ["5.1E", "5.1F", "5.1G", "5.2B", "5.2C", "5.3A", "5.3B", "5.3C", "5.5A", "5.5B"],
  skillsChip: "5.9 · Earth's rotation, day and night, and shadows",
  iCan: "I can show that Earth spins on its axis about once every 24 hours. I can explain how that spin makes day and night, makes the Sun seem to move across the sky, and changes where shadows point and how long they are.",
  blurb: "From the sky reef's big telescope, the crew watches Earth turn. A Texas partner station sends shadow-stick data, and the reef keepers want a shadow clock of their own.",
  mission: "Watch Earth spin, read the shadow-stick data, model day and night, and build a shadow clock you can explain.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.9 · CLOUDREACH TELESCOPE DECK",
  playableActs: [1, 2, 3],
  earthTrue: "Cloudreach and the crew are invented. Earth's spin, the Sun's path, and the shadow-stick data are real Earth science. The shadow data are rounded values for a 100 cm stick in central Texas in late September, using Sun time (noon is when the Sun is highest).",
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Sky clock", heatUnit: "%", supplies: "Shadow marks", suppliesUnit: "marks" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. The sky reef's big telescope is pointed at Earth, and Earth is turning right in front of us.",
    "A partner station in Texas is tracking shadows, and the reef keepers want to build a shadow clock of their own.",
    "Watch closely, use the data, and keep every answer Earth-true. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Watch Earth turn", "Act 2 · Model day and night", "Act 3 · Build the shadow clock"],
    completes: [
      "You timed Earth's spin and read the Texas shadow data, {firstName}!",
      "You modeled day and night and rebuilt the shadow log, {firstName}!",
      "The reef shadow clock is ready for the sky show, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Cloudreach: Kai thinks the Sun circles Earth every day, and the shadow log gets scrambled. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the reef keepers want a shadow clock, and Kai's shadow note needs fixing. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Today we model day and night, and Kai and I already disagree about the Sun.",
      "Let's grab the flashlight and the globe.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The reef keepers want a shadow clock before tonight's sky show.",
      "Let's make sure every shadow on it is Earth-true.",
    ],
  }),
  tasks,
};
