// Expedition Station — The Summit Summary (ELA.4.6G-XP)
// Grade 4 · ELAR · Frostveil. Main standard 4.6G (evaluate details read to
// determine key ideas); also practices 4.7D (retell, paraphrase, or summarize
// in ways that keep meaning and logical order), 4.6F (inference), 4.7C (text
// evidence), 4.9D (informational text features: a timeline), 4.3B (context
// clues). All passages are original: articles the crew reads about real Earth
// mountains while they get ready to climb Frostveil's great ice summit. Every
// fact in the articles is Earth-true. The history article uses no invented
// quotes.
import { CREW, acts, passage } from "./_shared.js";

const passages = {
  A: passage("A", { title: "How Mountains Rise and Fall", genre: "Informational article" }, [
    [
      "Mountains look like they have been there forever.",
      "But mountains are always changing.",
      "They slowly rise up, and then they slowly wear down.",
      "Some mountain peaks poke up above the clouds.",
    ],
    [
      "Most tall mountains form when giant pieces of Earth's outer layer push against each other.",
      "These pieces are called plates, and they move about as fast as your fingernails grow.",
      "When two plates crash together, the land between them crumples and folds upward.",
      "The Himalayas, the tallest mountains on Earth, formed this way.",
      "Their name means \"home of snow\" in an old language called Sanskrit.",
    ],
    [
      "Some mountains are built by volcanoes instead.",
      "Hot, melted rock from deep inside Earth bursts out through an opening.",
      "The rock cools and hardens into a layer.",
      "Over thousands of years, the layers pile up into a tall, cone-shaped mountain.",
      "Mount Fuji in Japan is a volcano that people love to paint and photograph.",
    ],
    [
      "As soon as a mountain rises, wind, water, and ice start to wear it down.",
      "Rain washes away tiny bits of rock.",
      "Water seeps into cracks, freezes, and splits the rock apart.",
      "Over millions of years, sharp peaks can become rounded hills.",
      "The Appalachian Mountains in the eastern United States were once much taller than they are today.",
    ],
  ]),
  B: passage("B", { title: "Why Mountaintops Are Cold", genre: "Informational article" }, [
    [
      "If you climbed a tall mountain on a summer day, you might start in shorts and end in a heavy coat.",
      "The higher you go, the colder the air gets.",
      "This is true on mountains all over the world.",
    ],
    [
      "Sunlight does not warm the air very much as it passes through.",
      "Instead, sunlight warms the ground, and the warm ground heats the air right above it.",
      "High on a mountain, the air is far from the wide, warm land below.",
      "That is one reason the air up there stays chilly.",
    ],
    [
      "Air also cools off as it rises and spreads out.",
      "Near the ground, air is squeezed by all the air pressing down on it.",
      "Higher up, there is less air pressing down, so the air spreads out.",
      "When air spreads out, it gets cooler.",
      "At high altitudes, far above the level of the sea, the air can be freezing even when the valley below is warm.",
    ],
    [
      "On average, the air gets about 3 to 5 degrees Fahrenheit colder for every 1,000 feet you climb.",
      "That is why Mount Kilimanjaro in Africa can have snow and ice on top, even though it stands close to the equator.",
      "Its peak rises more than 19,000 feet into the sky.",
    ],
  ]),
  C: passage("C", { title: "Thin Air Up High", genre: "Informational article" }, [
    [
      "Air is made of tiny bits called particles that are too small to see.",
      "Near sea level, air particles are packed close together.",
      "High on a mountain, they are spread far apart.",
      "People call this thin air.",
    ],
    [
      "Thin air makes it harder for your body to get the oxygen it needs.",
      "Oxygen is a gas in the air that every part of your body uses.",
      "Each breath of thin air brings in less oxygen than a breath near the sea.",
      "At the top of Mount Everest, one breath has only about one-third as much oxygen as a breath at sea level.",
    ],
    [
      "When people climb too high too fast, they can get altitude sickness.",
      "They may get a headache, feel dizzy, or not want to eat.",
      "Some people feel very tired but cannot sleep well.",
    ],
    [
      "The best way to stay safe is to climb slowly.",
      "Climbers go up a little, then rest for a day or two.",
      "This gives their bodies time to get used to the thin air.",
      "Over time, their bodies make more red blood cells, which carry oxygen.",
      "If someone still feels sick, the surest fix is to go back down to thicker air.",
    ],
  ]),
  D: passage("D", { title: "Life on the Mountainside", genre: "Informational article" }, [
    [
      "High mountains are hard places to live.",
      "It is cold and windy, the air is thin, and food can be hard to find.",
      "Yet many animals have special body parts and habits that help them survive up high.",
    ],
    [
      "Mountain goats are expert climbers.",
      "Each hoof has a hard outer edge and a soft, rubbery pad in the middle.",
      "The pad grips rock like the bottom of a sneaker.",
      "This lets mountain goats walk along narrow ledges on steep cliffs.",
      "Their shaggy white coats make them look like they are wearing fluffy sweaters.",
    ],
    [
      "Pikas are small, round animals related to rabbits.",
      "They do not sleep through the winter.",
      "Instead, all summer long they gather grass and flowers and pile them under rocks.",
      "These haypiles become their food when snow covers the ground.",
      "Hikers often hear pikas before they see them.",
    ],
    [
      "Snow leopards live in the rocky mountains of Central Asia.",
      "Thick fur keeps them warm, and their wide, furry paws work like snowshoes.",
      "A long tail helps a snow leopard balance as it leaps from rock to rock.",
      "Its gray, spotted coat blends in with the rocks, so its prey does not see it coming.",
    ],
  ]),
  E: passage("E", { title: "The First Climb to the Top of the World", genre: "Informational article (history)" }, [
    [
      "For many years, no one had ever stood on top of Mount Everest.",
      "Climbers had tried again and again, but the cold, the wind, and the thin air turned them back.",
      "Then, in the spring of 1953, a new team set out to try once more.",
    ],
    [
      "Climbing Everest took a huge team working together.",
      "The team was led by a British army officer named John Hunt.",
      "Hundreds of people helped, including many Sherpa guides and porters who knew the mountains well.",
      "Together they carried tents, food, and oxygen tanks up the mountain.",
      "They set up a chain of camps, each one higher than the last.",
    ],
    [
      "Two climbers, Tom Bourdillon and Charles Evans, tried for the top first.",
      "They got within about 300 feet of the summit.",
      "But their oxygen gear was giving them trouble and time was running out, so they turned back.",
    ],
    [
      "Next came Edmund Hillary, a beekeeper from New Zealand, and Tenzing Norgay, a Sherpa mountain climber.",
      "Tenzing had been on several earlier trips to Everest.",
      "On May 29, 1953, the two men climbed a steep wall of rock and ice near the top.",
      "At about 11:30 in the morning, they stepped onto the highest point on Earth.",
    ],
    [
      "They stayed on top for only about 15 minutes.",
      "Hillary took photographs, and Tenzing left a small gift of sweets in the snow.",
      "Then they carefully climbed back down to their team.",
      "News of the climb spread around the world, and the two men became famous.",
    ],
  ]),
  F: passage("F", { title: "Kai's Summary: Life on the Mountainside", genre: "Summary (has a problem)" }, [
    [
      "This article is about snow leopards.",
      "Snow leopards are the coolest animals ever, and I think every zoo should have one.",
      "They have long tails and gray, spotted fur.",
    ],
  ]),
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Crumple zone", machine: "Summit Scope", icon: "scan", speaker: "nova", passage: ["A"],
    line: "Before we climb Frostveil's summit, we should know how Earth's mountains are made. Let's start with paragraph 2 of my first article.",
    question: "Read paragraph 2 of Passage A. What is the key idea of that paragraph?",
    hint: "The key idea is what the WHOLE paragraph is mostly about. The other sentences should fit under it like details.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The first page goes into the climb binder" },
    discovery: { id: "growingpeak", name: "Still growing", who: "Nova", fact: "The plates under the Himalayas are still pushing together. Because of that, Mount Everest grows a few millimeters taller each year." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Plates move about as fast as your fingernails grow." },
      { id: "b", text: "The word Himalayas means \"home of snow.\"" },
      { id: "c", text: "Many tall mountains form when Earth's plates push together and fold the land upward." },
      { id: "d", text: "The Himalayas are the tallest mountains on Earth." },
    ],
    rightFeedback: "Yes! Every sentence in paragraph 2 helps explain how pushing plates build mountains.",
    wrong: [
      { choice: "a", hint: "That tells how fast plates move. It is one detail. What is the whole paragraph explaining?" },
      { choice: "b", hint: "That is a fun fact about a name. Does the rest of the paragraph talk about names?" },
      { choice: "d", hint: "That is true, but it is one example. What does the paragraph say about how mountains FORM?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Spread out and cool down", machine: "Highlighter Beam", icon: "scan", speaker: "vega", passage: ["B"],
    line: "Frostveil's summit is much colder than our base camp. Nova's second article explains why. Find the sentence that sums up paragraph 3.",
    question: "Highlight the sentence that tells the key idea of paragraph 3 in Passage B.",
    hint: "Look for the sentence the other sentences explain. The details tell HOW or show an example.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The beam locks onto the key sentence" },
    discovery: { id: "slowpasta", name: "Slow cooking", who: "Kai", fact: "High on a mountain, water boils at a lower temperature than it does near the sea. That's why cooking noodles up high takes longer." },
    answer: { kind: "highlight", groups: [["B3.1"]] },
    rightFeedback: "Locked on! The other sentences explain how rising air spreads out and cools.",
    wrong: [
      { sentence: "B3.2", hint: "That tells what happens to air near the ground. It's a detail. Which sentence sums up the paragraph?" },
      { sentence: "B3.4", hint: "Close! That explains one step. Which sentence tells the big idea of the whole paragraph?" },
      { sentence: "B3.5", hint: "That is an example of what happens. Which sentence tells what the paragraph is mostly about?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "How high is high?", machine: "Word Scope", icon: "static", speaker: "kai", passage: ["B"],
    line: "Nova's article keeps saying \"high altitudes.\" I'm an engineer. I need to know exactly what that word means before I pack the gear.",
    question: "\"At high altitudes, far above the level of the sea, the air can be freezing.\" What does altitudes mean?",
    hint: "Read the words right after it: \"far above the level of the sea.\" They give you a clue.",
    meter: { supplies: 1, label: "Rope coils +1", story: "Kai adds a word card to the binder" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Very cold winds" },
      { id: "b", text: "Heights above the level of the sea" },
      { id: "c", text: "Deep valleys between mountains" },
      { id: "d", text: "Thick clouds of snow" },
    ],
    rightFeedback: "Right! The clue \"far above the level of the sea\" tells you altitude means height.",
    wrong: [
      { choice: "a", hint: "The sentence says the AIR is freezing there. What words tell you WHERE \"there\" is?" },
      { choice: "c", hint: "Valleys are low places. The clue says \"far above.\" Is that high or low?" },
      { choice: "d", hint: "The sentence doesn't mention clouds. Look at the words right after \"altitudes.\"" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Key or just cool?", machine: "Sort Bay", icon: "cells", speaker: "nova", passage: ["A"],
    line: "The key idea of my whole mountain article is: Mountains are always changing. They rise up, and they wear down. Some details prove that. Some are just interesting extras.",
    question: "Sort each detail from Passage A. Is it important to the key idea, or interesting but minor?",
    hint: "Ask: does this detail show how mountains rise or how they wear down? If not, it's a minor detail, even if it's fun.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The detail cards are sorted" },
    discovery: { id: "andes", name: "The longest range", who: "Nova", fact: "The Andes in South America are the longest mountain range above the ocean on Earth. They stretch about 7,000 kilometers (about 4,300 miles)." },
    answer: { kind: "sort", bins: { s1: "key", s2: "key", s3: "key", s4: "minor", s5: "minor", s6: "minor" } },
    rightFeedback: "Sorted! Folding plates, piling lava, and wearing down are key. The name, the paintings, and the clouds are fun extras.",
    sort: {
      bins: [{ id: "key", label: "Important to the key idea" }, { id: "minor", label: "Interesting, but minor" }],
      items: [
        { id: "s1", label: "When plates crash together, the land crumples and folds upward." },
        { id: "s2", label: "Layers of cooled volcano rock pile up into a mountain." },
        { id: "s3", label: "Wind, water, and ice wear mountains down." },
        { id: "s4", label: "Himalayas means \"home of snow\" in Sanskrit." },
        { id: "s5", label: "People love to paint and photograph Mount Fuji." },
        { id: "s6", label: "Some mountain peaks poke up above the clouds." },
      ],
    },
    wrong: [
      { item: "s1", hint: "The key idea says mountains RISE. Does this detail show one way they rise?" },
      { item: "s2", hint: "Volcanoes are another way mountains RISE. Is that important to the key idea?" },
      { item: "s3", hint: "The key idea says mountains WEAR DOWN. This detail tells what wears them down." },
      { item: "s4", hint: "A name's meaning is fun to know. Does it show how mountains rise or wear down?" },
      { item: "s5", hint: "That tells what people like to do. Does it explain how mountains change?" },
      { item: "s6", hint: "That's a cool picture, but does it show a mountain rising or wearing down?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The drone isn't broken!", machine: "Summit Scope", icon: "snap", speaker: "vega", passage: ["B"],
    line: "Surprise! Our weather drone just reached Frostveil's summit. It says it's freezing up there, but it's warm down here at base camp. Kai thinks the drone is broken. Use Nova's article to settle it before we pack.",
    question: "Part 1: What is the key idea of the whole article? Part 2: Highlight TWO sentences that explain why, one from paragraph 2 and one from paragraph 3. Part 3: Base camp is 60°F. The crew climbs 3,000 feet higher. What will the air most likely be?",
    parts: [
      { type: "choice", prompt: "What is the key idea of the whole article?", choices: [
        { id: "a", text: "Mount Kilimanjaro has snow on top." },
        { id: "b", text: "The higher you climb, the colder the air gets, because of how air is warmed and how it spreads out." },
        { id: "c", text: "You should wear shorts when you start a climb." },
        { id: "d", text: "Sunlight warms the ground." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from paragraph 2 and one from paragraph 3 that explain why it is colder up high.", passage: "B", count: 2 },
      { type: "choice", prompt: "Base camp is 60°F. The crew climbs 3,000 feet higher. What will the air most likely be?", choices: [
        { id: "a", text: "About 75°F, because they are closer to the sun" },
        { id: "b", text: "About 60°F, the same as base camp" },
        { id: "c", text: "About 48°F, colder than base camp" },
        { id: "d", text: "About 0°F, the coldest it can be" },
      ] },
    ],
    hint: "The key idea of the whole article covers every paragraph. For Part 3, use paragraph 4: about 3 to 5 degrees colder for every 1,000 feet.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The drone is fine. The crew packs warmer gear" },
    discovery: { id: "treeline", name: "The tree line", who: "Nova", fact: "Above a certain height on a mountain, it gets too cold and windy for trees to grow. That height is called the tree line." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["B2.2", "B2.3", "B2.4"], ["B3.3", "B3.4"]] },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Case closed! Air up high is far from the warm ground and spreads out, so it's colder. 3,000 feet higher means about 9 to 15 degrees colder.",
    wrong: [
      { step: 1, choice: "a", hint: "That is an example from paragraph 4. What does the WHOLE article explain?" },
      { step: 1, choice: "c", hint: "The shorts are just a picture to hook the reader. What is the article mostly about?" },
      { step: 1, choice: "d", hint: "That is one detail from paragraph 2. Does it cover the whole article?" },
      { step: 2, sentence: "B2.1", hint: "That tells what sunlight does NOT do. Which sentence explains what warms the air?" },
      { step: 2, sentence: "B3.1", hint: "That is the paragraph's key idea. Pick a detail that explains HOW the air cools." },
      { step: 2, sentence: "B3.5", hint: "That shows what happens, but not why. Which sentence explains the cause?" },
      { step: 3, choice: "a", hint: "The article says it gets COLDER as you climb. Reread paragraph 4." },
      { step: 3, choice: "b", hint: "3,000 feet is a big climb. Does the temperature stay the same?" },
      { step: 3, choice: "d", hint: "3 to 5 degrees for every 1,000 feet is only about 9 to 15 degrees for 3,000 feet." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Line up the mountain story", machine: "Summary Stack", icon: "log", speaker: "vega", passage: ["A"],
    line: "Kai wrote five summary sentences about how mountains rise and fall. They got shuffled in the wind. A summary has to follow the article's order.",
    question: "Put the summary sentences for Passage A in logical order, first to last.",
    hint: "Follow the article: first the big idea, then how mountains rise (two ways), then how they wear down, then what happens in the end.",
    meter: { heat: 5, label: "Climb ready +5%", story: "The summary is stacked in order" },
    discovery: { id: "denali", name: "North America's tallest", who: "Kai", fact: "Denali in Alaska is the tallest mountain in North America. Its top is about 20,310 feet above sea level." },
    answer: { kind: "order", correct: ["change", "plates", "volcano", "wear", "hills"] },
    items: [
      { id: "wear", text: "Then wind, water, and ice slowly wear the mountains down." },
      { id: "hills", text: "Over millions of years, sharp peaks can become rounded hills." },
      { id: "plates", text: "Many mountains form when Earth's plates push together and fold the land up." },
      { id: "change", text: "Mountains are always changing." },
      { id: "volcano", text: "Others are built by volcanoes, as layers of cooled rock pile up." },
    ],
    rightFeedback: "Perfect order! Big idea, two ways mountains rise, then how they wear down.",
    wrong: [
      { position: 0, hint: "A summary usually starts with the key idea of the whole article. Which sentence tells it?" },
      { position: 1, hint: "The article explains how mountains rise before how they wear down. Which way comes first?" },
      { position: 2, hint: "The word \"Others\" tells you this sentence comes right after another way mountains form." },
      { position: 3, hint: "Peaks become hills only AFTER they are worn down. What wears them down?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The longest summary ever", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["C"],
    line: 'Kai: "My summary of Thin Air has every single detail. Particles, headaches, red blood cells, all of it! A good summary should include every detail, so nothing is missing."',
    nova: 'Nova: "But your summary is as long as the article! A summary is short. It tells the key idea and only the most important details, in order."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about why people read a summary. Do they want the whole article again, or just the main points?",
    meter: { heat: 5, label: "Climb ready +5%", story: "The crew agrees on what a summary is" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. A summary is a short version. It keeps the key idea and the most important details and leaves out small ones." },
      { id: "B", text: "Nova, because a summary should only be one word long." },
      { id: "C", text: "Kai. If you leave out any detail, the summary is wrong." },
      { id: "D", text: "Kai. Longer writing is always better writing." },
    ],
    writtenPrompt: "Tell Kai in your own words what a good summary includes and what it leaves out.",
    debateHints: {
      wrongWho: "If a summary had every detail, it would be as long as the article. What is a summary for?",
      wrongReason: "Right person, check the reason. What does a summary keep, and what does it leave out?",
      right: "Nova is right. A summary is short: the key idea plus the most important details.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Same meaning, new words", machine: "Paraphrase Press", icon: "relay", speaker: "nova", passage: ["C"],
    line: "Mission Control wants our climb plan in our own words. Let's paraphrase two sentences from paragraph 4 without changing what they mean.",
    question: "\"Climbers go up a little, then rest for a day or two. This gives their bodies time to get used to the thin air.\" Which is the best paraphrase?",
    hint: "A good paraphrase uses new words but keeps the same facts. It doesn't add ideas or leave out the main point.",
    meter: { supplies: 1, label: "Rope coils +1", story: "Nova sends the climb plan" },
    answer: { kind: "choice", correct: "d" },
    choices: [
      { id: "a", text: "Climbers rest for a day or two because climbing is boring." },
      { id: "b", text: "Climbers should go as high as they can, as fast as they can, and then rest." },
      { id: "c", text: "Thin air is very high up." },
      { id: "d", text: "After climbing a short way, climbers stop and rest so their bodies can adjust to the thin air." },
    ],
    rightFeedback: "Yes! New words, same meaning: climb a bit, rest, and let your body adjust.",
    wrong: [
      { choice: "a", hint: "The article never says climbing is boring. A paraphrase can't add a new reason." },
      { choice: "b", hint: "That changes the meaning. Do climbers go fast, or a little at a time?" },
      { choice: "c", hint: "That leaves out the main point about resting. What do climbers DO?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Who lives up there?", machine: "Summary Scope", icon: "scan", speaker: "vega", passage: ["D"],
    line: "Nova says animals live high on Earth's mountains, even with thin air and cold wind. Pick the summary we should send to the climb team.",
    question: "Which is the best summary of Passage D?",
    hint: "The best summary tells the key idea of the whole article and the most important details, in the same order.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The animal summary goes in the binder" },
    discovery: { id: "noroar", name: "Quiet cats", who: "Nova", fact: "Snow leopards are big cats, but they cannot roar. Instead, they make soft puffing sounds, mews, and growls." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Mountains are cold, windy, and hard to live on, but many animals have ways to survive. Mountain goats have gripping hooves, pikas store haypiles for winter, and snow leopards have thick fur and long tails for balance." },
      { id: "b", text: "Mountain goats have shaggy white coats. Hikers hear pikas. Snow leopards live in Central Asia." },
      { id: "c", text: "Pikas gather grass and flowers all summer and pile them under rocks." },
      { id: "d", text: "Snow leopards have long tails. Mountains are cold. Mountain goats climb. Pikas are related to rabbits." },
    ],
    rightFeedback: "Right! It starts with the key idea and gives the most important details about each animal, in order.",
    wrong: [
      { choice: "b", hint: "Those are mostly minor details. Where is the key idea about surviving up high?" },
      { choice: "c", hint: "That only tells about one paragraph. A summary covers the whole article." },
      { choice: "d", hint: "The facts are mixed up and out of order, and the key idea is missing." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Headache at Camp Two", machine: "Summit Scope", icon: "quake", speaker: "vega", passage: ["C"],
    line: "Surprise! We climbed fast to Camp Two today, and now Kai has a headache and feels dizzy. Nova's Thin Air article can tell us what to do. Quick, read it!",
    question: "Part 1: What is the key idea of the whole article? Part 2: Highlight one sentence from paragraph 3 that describes Kai's problem and one sentence from paragraph 4 that tells the surest fix. Part 3: What should the crew do?",
    parts: [
      { type: "choice", prompt: "What is the key idea of the whole article?", choices: [
        { id: "a", text: "Oxygen is a gas in the air." },
        { id: "b", text: "At the top of Everest, a breath has one-third as much oxygen." },
        { id: "c", text: "High up, thin air has less oxygen and can make people sick, so climbers must go slowly to stay safe." },
        { id: "d", text: "Air particles are too small to see." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from paragraph 3 and one from paragraph 4.", passage: "C", count: 2 },
      { type: "choice", prompt: "What should the crew do?", choices: [
        { id: "a", text: "Keep climbing fast so Kai reaches the top sooner" },
        { id: "b", text: "Take Kai back down to a lower camp to rest" },
        { id: "c", text: "Give Kai a big meal and climb higher tonight" },
        { id: "d", text: "Ignore it, because headaches don't matter" },
      ] },
    ],
    hint: "The key idea covers every paragraph. For Part 3, think about what the article says is the surest fix.",
    meter: { heat: 10, label: "Climb ready +10%", story: "Kai rests at the lower camp and feels better" },
    discovery: { id: "strongsun", name: "Sunburn in the snow", who: "Kai", fact: "Sunlight is stronger high on a mountain, and bright snow bounces it back up at you. Climbers can get a sunburn fast, even on freezing days." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "c" },
      { kind: "highlight", groups: [["C3.1", "C3.2"], ["C4.5"]] },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Good call! Kai climbed too fast, so the surest fix is to go down to thicker air and rest.",
    wrong: [
      { step: 1, choice: "a", hint: "That defines one word. What does the WHOLE article teach?" },
      { step: 1, choice: "b", hint: "That is a striking detail from paragraph 2. Does it cover altitude sickness and staying safe?" },
      { step: 1, choice: "d", hint: "That detail is from paragraph 1. What is the article mostly about?" },
      { step: 2, sentence: "C3.3", hint: "Kai isn't too tired to sleep. Which sentence names his headache and dizziness?" },
      { step: 2, sentence: "C4.2", hint: "That tells how to climb. Which sentence says what to do if someone STILL feels sick?" },
      { step: 2, sentence: "C4.4", hint: "That takes a long time. Which sentence gives the surest fix right now?" },
      { step: 3, choice: "a", hint: "Climbing too fast caused the problem. Would climbing faster help?" },
      { step: 3, choice: "c", hint: "Going higher means even thinner air. What does paragraph 4 say to do?" },
      { step: 3, choice: "d", hint: "The article says a headache can be a sign of altitude sickness. Is it safe to ignore?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Kai's snow leopard summary", machine: "Repair", icon: "crew", speaker: "kai", passage: ["F", "D"],
    line: "I wrote a summary of Life on the Mountainside. Vega says it has two problems. I think it's great, but I guess I'll listen.",
    question: "Part 1: What went wrong in Kai's summary? Part 2: Pick the best fixed summary.",
    parts: [
      { type: "choice", prompt: "What went wrong in Kai's summary?", choices: [
        { id: "a", text: "It includes Kai's opinion, and it misses the key idea that many animals have ways to survive in the mountains." },
        { id: "b", text: "It is too short. A summary should tell every detail." },
        { id: "c", text: "It uses facts that are not in the article." },
        { id: "d", text: "It should begin with a question." },
      ] },
      { type: "choice", prompt: "Pick the best fixed summary.", choices: [
        { id: "a", text: "Snow leopards are the best mountain animals. They have spotted coats and live in Central Asia." },
        { id: "b", text: "Mountains are cold, windy, and hard to live on, but animals like mountain goats, pikas, and snow leopards have body parts and habits that help them survive there." },
        { id: "c", text: "I think everyone should visit the mountains to see the animals." },
        { id: "d", text: "Pikas are related to rabbits, and hikers hear them first." },
      ] },
    ],
    hint: "A summary tells the author's key idea, not your opinion. Does Kai's summary cover the whole article?",
    meter: { supplies: 1, label: "Rope coils +1", story: "Kai's summary is fixed and filed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Fixed! Now it tells the key idea about all the animals, with no opinions.",
    wrong: [
      { step: 1, choice: "b", hint: "Summaries are supposed to be short. Look for an opinion word like \"I think.\"" },
      { step: 1, choice: "c", hint: "Check paragraph 4. The tail and fur are in the article. So what's the real problem?" },
      { step: 1, choice: "d", hint: "A summary doesn't need a question. Does Kai's summary tell the key idea?" },
      { step: 2, choice: "a", hint: "\"The best\" is still an opinion, and it only covers one animal." },
      { step: 2, choice: "c", hint: "\"I think\" means that's an opinion. Which summary sticks to the article?" },
      { step: 2, choice: "d", hint: "That is only one animal, with a minor detail. Where is the key idea?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Timeline to the top", machine: "Chart Reader", icon: "grid", speaker: "nova", passage: ["E"],
    line: "Tomorrow we try for Frostveil's summit. Tonight let's read about the first people to reach the top of Everest. I made a timeline to go with the article.",
    question: "Part 1: Highlight the sentence that tells the key idea of paragraph 2 in Passage E. Part 2: Use the timeline. How many days after the first pair turned back did Hillary and Tenzing reach the top? Part 3: Why did Nova add a timeline?",
    data: {
      title: "Nova's Timeline: Everest, 1953",
      columns: ["When", "What happened"],
      rows: [
        ["March", "The team begins the long walk toward Everest."],
        ["April", "The team sets up base camp at the foot of the mountain."],
        ["May 26", "Bourdillon and Evans get close to the top but turn back."],
        ["May 29", "Hillary and Tenzing reach the top."],
      ],
    },
    parts: [
      { type: "highlight", prompt: "Highlight the sentence that tells the key idea of paragraph 2.", passage: "E" },
      { type: "choice", prompt: "How many days after the first pair turned back did Hillary and Tenzing reach the top?", choices: [
        { id: "a", text: "3 days" },
        { id: "b", text: "26 days" },
        { id: "c", text: "29 days" },
        { id: "d", text: "55 days" },
      ] },
      { type: "choice", prompt: "Why did Nova add a timeline?", choices: [
        { id: "a", text: "To show what the climbers looked like" },
        { id: "b", text: "To help readers see the order of events at a glance" },
        { id: "c", text: "To tell the reader her opinion of the climb" },
        { id: "d", text: "To add facts that the article got wrong" },
      ] },
    ],
    hint: "For the key idea, look for the sentence the rest of paragraph 2 explains. For the timeline, subtract the dates.",
    meter: { heat: 5, label: "Climb ready +5%", story: "The timeline is clipped into the binder" },
    discovery: { id: "chomolungma", name: "Other names", who: "Nova", fact: "Mount Everest has other names. In Tibet it is called Chomolungma, and in Nepal it is called Sagarmatha." },
    answer: { kind: "parts", parts: [
      { kind: "highlight", groups: [["E2.1"]] },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Right! Paragraph 2 is about teamwork, and the timeline shows the second try came just 3 days later.",
    wrong: [
      { step: 1, sentence: "E2.2", hint: "That tells who led the team. It's one detail. Which sentence sums up the paragraph?" },
      { step: 1, sentence: "E2.3", hint: "That tells who helped. Which sentence sums up what ALL the details show?" },
      { step: 1, sentence: "E2.5", hint: "That tells about the camps. Which sentence tells the big idea?" },
      { step: 2, choice: "b", hint: "26 is the date the first pair turned back. How many days from May 26 to May 29?" },
      { step: 2, choice: "c", hint: "29 is the date they reached the top. Subtract: 29 minus 26." },
      { step: 2, choice: "d", hint: "Did you add the dates? To find the days between, subtract." },
      { step: 3, choice: "a", hint: "A timeline has dates and events, not pictures. What does it help you see?" },
      { step: 3, choice: "c", hint: "The timeline only lists facts. Does it share an opinion?" },
      { step: 3, choice: "d", hint: "The timeline matches the article. What does lining up dates help you do?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Sweets in the snow", machine: "Sort Bay", icon: "cells", speaker: "kai", passage: ["E"],
    line: "The Everest article has so many cool details! A beekeeper! Sweets in the snow! But Vega says not all of them belong in a summary.",
    question: "Sort each detail from Passage E. Does it belong in a summary, or is it interesting but minor?",
    hint: "A summary detail helps tell the main story: how the team worked, who tried, and who reached the top. Fun extras stay out.",
    meter: { heat: 5, label: "Climb ready +5%", story: "Kai sorts the history cards" },
    discovery: { id: "tabei", name: "First woman on top", who: "Vega", fact: "In 1975, Junko Tabei of Japan became the first woman to reach the top of Mount Everest." },
    answer: { kind: "sort", bins: { t1: "summary", t2: "summary", t3: "summary", t4: "minor", t5: "minor", t6: "minor" } },
    rightFeedback: "Sorted! The teamwork, the first try, and the success tell the main story. The rest are fun extras.",
    sort: {
      bins: [{ id: "summary", label: "Belongs in a summary" }, { id: "minor", label: "Interesting, but minor" }],
      items: [
        { id: "t1", label: "A big team set up a chain of camps and carried supplies up the mountain." },
        { id: "t2", label: "The first pair got close to the top but had to turn back." },
        { id: "t3", label: "Hillary and Tenzing reached the top on May 29, 1953." },
        { id: "t4", label: "Hillary was a beekeeper." },
        { id: "t5", label: "Tenzing left a small gift of sweets in the snow." },
        { id: "t6", label: "They reached the top at about 11:30 in the morning." },
      ],
    },
    wrong: [
      { item: "t1", hint: "The article says climbing Everest took a huge team. Is the teamwork part of the main story?" },
      { item: "t2", hint: "The first try shows how hard it was and sets up what happens next. Is that important?" },
      { item: "t3", hint: "That's the big event of the whole article. Does it belong in a summary?" },
      { item: "t4", hint: "Beekeeping is a fun fact about Hillary. Does it help tell how they reached the top?" },
      { item: "t5", hint: "The sweets are a nice detail, but would the story still make sense without them?" },
      { item: "t6", hint: "The date matters most. Is the exact time of day needed in a short summary?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Big idea, fresh words", machine: "Paraphrase Press", icon: "relay", speaker: "vega", passage: ["E"],
    line: "Before we go to sleep, let's make sure we understand the Everest article. Find its key idea, then say one part in our own words.",
    question: "Part 1: What is the key idea of the whole article? Part 2: Which is the best paraphrase of paragraph 3?",
    parts: [
      { type: "choice", prompt: "What is the key idea of the whole article?", choices: [
        { id: "a", text: "Edmund Hillary was a beekeeper from New Zealand." },
        { id: "b", text: "Climbers stayed on the top of Everest for only 15 minutes." },
        { id: "c", text: "In 1953, after many failed tries, a big team worked together, and Hillary and Tenzing became the first people to reach the top of Everest." },
        { id: "d", text: "Oxygen gear can give climbers trouble." },
      ] },
      { type: "choice", prompt: "Which is the best paraphrase of paragraph 3?", choices: [
        { id: "a", text: "Bourdillon and Evans went first and made it within about 300 feet of the top, but oxygen trouble and running out of time made them turn back." },
        { id: "b", text: "Bourdillon and Evans reached the top first, but nobody believed them." },
        { id: "c", text: "Bourdillon and Evans turned back because they were scared of heights." },
        { id: "d", text: "Two climbers tried." },
      ] },
    ],
    hint: "The key idea covers the whole article. A paraphrase keeps every main fact true, in new words, without adding anything.",
    meter: { heat: 5, label: "Climb ready +5%", story: "The crew is ready to rest before the big climb" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "c" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! You found the big idea, and your paraphrase kept the meaning.",
    wrong: [
      { step: 1, choice: "a", hint: "That is a minor detail about one person. What is the WHOLE article about?" },
      { step: 1, choice: "b", hint: "That is one detail from the last paragraph. What is the main story?" },
      { step: 1, choice: "d", hint: "That is a detail from paragraph 3. Does it cover the whole article?" },
      { step: 2, choice: "b", hint: "That changes the meaning. Did they reach the top?" },
      { step: 2, choice: "c", hint: "The article never says they were scared. What were the real reasons?" },
      { step: 2, choice: "d", hint: "That is true, but it leaves out what happened and why. A paraphrase keeps the meaning." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Weather window!", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["E", "A", "C"],
    line: "Surprise! The storm over Frostveil's summit just cleared. We leave for the top in ten minutes! Mission Control wants a short summary of the Everest article in the climb log before we go. You're our summary expert, {firstName}!",
    question: "Part 1: Which sentence should start your summary? Part 2: Pick the details that belong in the summary. Part 3: Write a 2–3 sentence summary of Passage E in your own words.",
    parts: [
      { type: "choice", prompt: "Which sentence should start your summary?", choices: [
        { id: "a", text: "Tenzing left sweets in the snow." },
        { id: "b", text: "In 1953, a big team set out to reach the top of Mount Everest, where no one had ever stood." },
        { id: "c", text: "I think climbing Everest is the bravest thing ever." },
        { id: "d", text: "News spread around the world." },
      ] },
      { type: "multi", prompt: "Pick the details that belong in the summary.", choices: [
        { id: "a", text: "The team set up a chain of camps and carried supplies." },
        { id: "b", text: "The first pair got close but turned back." },
        { id: "c", text: "Hillary and Tenzing reached the top on May 29, 1953." },
        { id: "d", text: "Hillary took photographs on top." },
        { id: "e", text: "Hillary was a beekeeper." },
      ] },
      { type: "write", prompt: "Write a 2–3 sentence summary of the Everest article. Tell the key idea and the most important details, in order. Leave out opinions.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["Tells the key idea: after many tries, a team worked together and Hillary and Tenzing first reached the top in 1953", "Includes important details, not minor extras", "Keeps the article's order and meaning, in own words, with no opinions", "Complete sentences with capitals and end punctuation"],
    hint: "Start with the key idea. Add the most important events in the order they happened. Leave out fun extras and your own opinion.",
    meter: { heat: 10, label: "Climb ready +10%", story: "The summary is logged, and the crew heads for the summit" },
    discovery: { id: "yaklungs", name: "Built for thin air", who: "Nova", fact: "Yaks live high in the mountains of Asia. They have big lungs and hearts that help them get enough oxygen from thin air." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "multi", correct: ["a", "b", "c"] },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Summary logged! Your teacher will read what you wrote. Now, on to the summit!",
    wrong: [
      { step: 1, choice: "a", hint: "That is a minor detail from the end. A summary starts with the big idea." },
      { step: 1, choice: "c", hint: "\"I think\" is an opinion. A summary tells what the author says." },
      { step: 1, choice: "d", hint: "That comes at the very end of the story. What should come first?" },
      { step: 2, pick: "d", hint: "Photos are a small detail. Do they help tell the main story?" },
      { step: 2, pick: "e", hint: "Beekeeping is a fun fact, but it isn't part of how they reached the top." },
      { step: 2, missing: true, hint: "Three details belong: the teamwork, the first try, and the success." },
    ],
  },
};

export default {
  id: "ELA.4.6G-XP",
  standard: "ELA.4.6G-XP",
  engine: "expedition_station",
  title: "The Summit Summary",
  planet: "Frostveil",
  outpost: "Summit Base Camp · climbing season",
  grade: 4,
  subject: "ELAR",
  teks: "4.6G",
  supportingTeks: ["4.7D", "4.6F", "4.7C", "4.9D", "4.3B"],
  skillsChip: "4.6G · Key ideas & summaries",
  iCan: "I can decide which details are important to find the key idea. I can paraphrase and summarize a text in a way that keeps its meaning and order.",
  blurb: "The crew is getting ready to climb Frostveil's great ice summit. First they need to understand Earth's mountains, and Nova has a stack of articles to read.",
  mission: "Read articles about how mountains form, why it's cold up high, thin air, mountain animals, and the first climb of Everest. Find key ideas, sort important details from minor ones, and write summaries for the climb log.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.6G · FROSTVEIL SUMMIT BASE",
  playableActs: [1, 2, 3],
  meterStart: { heat: 5, supplies: 0, journal: 0 },
  meterLabels: { heat: "Climb ready", heatUnit: "%", supplies: "Rope coils", suppliesUnit: "coils" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega at Summit Base Camp on Frostveil.",
    "Frostveil's great ice summit towers above us. No crew has ever reached the top. To get ready, Nova collected articles about Earth's mountains.",
    "Help us find the key ideas and write short summaries for our climb log. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Rise and chill", "Act 2 · Thin air, tough animals", "Act 3 · Race for the top"],
    completes: [
      "Great work, {firstName}! We know how mountains form and why the top is so cold.",
      "Nice job, {firstName}! Kai feels better, and we know how to climb safely.",
      "The summary is logged, {firstName}! The crew is on its way to Frostveil's summit.",
    ],
    teasers: [
      "Next on Frostveil: the crew climbs higher, and the air gets thin. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the crew reads about the first climb of Everest before its own try for the top. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. We've reached Camp Two, and breathing is harder up here.",
      "Today we read about thin air and the animals that live high on mountains. Let's find what matters most.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Tomorrow we try for the summit!",
      "Tonight we read about the first people to climb Everest. Then we need one last summary for the log.",
    ],
  }),
  tasks,
};
