// Expedition Station — The Survival Suits (SCI.3.13A-XP)
// Grade 3 · Science · Frostveil (ice world). Main standard 3.13A (explore and
// explain how external structures and functions of animals such as the neck
// of a giraffe or webbed feet on a duck enable them to survive in their
// environment); also practices 3.1A (ask questions and define problems),
// 3.1B (plan investigations and design solutions), 3.1E (collect
// observations as evidence), 3.1G (develop and use models), 3.2B (analyze
// data for patterns), 3.2C (use math to compare data), 3.2D (evaluate a
// design using criteria), 3.3A (explanations supported by data and models),
// 3.3C (respectful scientific discussion), 3.5A (patterns), 3.5F (structure
// and function).
//
// Earth-true rule: Frostveil and the crew are invented, but every animal,
// body structure, and fact in this quest is real Earth science. The crew's
// glove and suit tests are classroom-style models with sample results.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Duck feet", machine: "Animal Files", icon: "scan", speaker: "nova",
    line: "Our suits have to work on ice, in snow, and maybe in icy water. Let's learn from Earth animals first. Here's a duck swimming in a cold pond.",
    question: "How do a duck's webbed feet help it survive?",
    hint: "The skin between the toes makes each foot wide and flat. What is a wide, flat foot good for in water?",
    meter: { heat: 5, label: "Suits +5%", story: "The first animal file is read" },
    discovery: { id: "duckoil", name: "Waterproof ducks", who: "Nova", fact: "Ducks have a special spot near their tails that makes oil. They spread the oil over their feathers with their beaks, so water rolls right off." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "They push lots of water, so the duck can paddle and swim well." },
      { id: "b", text: "They help the duck climb tall trees." },
      { id: "c", text: "They keep the duck's feet from ever getting wet." },
      { id: "d", text: "They help the duck dig holes in the ground." },
    ],
    rightFeedback: "Webbed feet work like paddles. Each kick pushes lots of water, so the duck can swim to find food and stay safe.",
    wrong: [
      { choice: "b", hint: "Ducks spend lots of time on ponds, not in treetops. What does a wide, flat foot push?" },
      { choice: "c", hint: "The feet go right into the water, so they get wet. What do they push when the duck kicks?" },
      { choice: "d", hint: "Digging takes sharp claws. Webbed feet are wide and flat. Where do ducks use them?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "What's it for?", machine: "Animal Files", icon: "cells", speaker: "kai",
    line: "Every animal body part has a job. If I know the job, I can build a suit part that does the same job!",
    question: "Sort each body part by its job.",
    hint: "Ask: does this part keep the animal warm, help it move, or help it get food?",
    meter: { heat: 5, label: "Suits +5%", story: "The body-part cards are sorted" },
    discovery: { id: "giraffeneck", name: "Giraffe necks", who: "Kai", fact: "A giraffe's neck can be taller than a grown-up person. But it has only 7 neck bones, the same number as your neck. Each bone is just much longer." },
    answer: { kind: "sort", bins: { b1: "warm", b2: "move", b3: "food", b4: "move", b5: "food", b6: "warm" } },
    rightFeedback: "Fat and fur keep animals warm. Webbed feet and flippers help them move. A long neck and a sticky tongue help them get food.",
    sort: {
      bins: [{ id: "warm", label: "Keeps it warm" }, { id: "move", label: "Helps it move" }, { id: "food", label: "Helps it get food" }],
      items: [
        { id: "b1", label: "A thick layer of fat on a seal" },
        { id: "b2", label: "Webbed feet on a duck" },
        { id: "b3", label: "The long neck of a giraffe" },
        { id: "b4", label: "Flippers on a sea turtle" },
        { id: "b5", label: "The long, sticky tongue of an anteater" },
        { id: "b6", label: "A thick, woolly coat on a musk ox" },
      ],
    },
    wrong: [
      { item: "b3", hint: "Giraffes eat leaves from the tops of tall trees. What does the long neck help them reach?" },
      { item: "b1", hint: "Seals swim in icy water. A thick layer of fat works like a blanket. What is its job?" },
      { item: "b4", hint: "A sea turtle uses its flippers to push through the water. What is their job?" },
      { item: "b5", hint: "An anteater pokes its tongue into ant nests. What does the sticky tongue catch?" },
      { item: "b6", hint: "Musk oxen live where winters are freezing. What does a thick coat do?" },
      { item: "b2", hint: "Ducks paddle with their feet. What is their job?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "The hump question", machine: "Animal Files", icon: "log", speaker: "kai",
    line: "Next file: a camel in a hot, dry desert. I always thought the hump was a big water tank. Nova says to check the file first.",
    question: "What does a camel's hump store?",
    hint: "The file says: \"When food is hard to find, the hump gets smaller and floppy.\" What does the camel use up when it has no food?",
    meter: { heat: 5, label: "Suits +5%", story: "The camel file is checked" },
    discovery: { id: "camelnose", name: "Camel sand shields", who: "Kai", fact: "Camels can close their nostrils to keep out blowing sand. They also have two rows of long eyelashes that help protect their eyes." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Water, for when there is nothing to drink" },
      { id: "b", text: "Fat, which the camel's body can use for energy when food is hard to find" },
      { id: "c", text: "Sand, to make the camel heavier in the wind" },
      { id: "d", text: "Air, to help the camel float" },
    ],
    rightFeedback: "The hump stores fat. When a desert has little food, the camel's body uses that fat for energy.",
    wrong: [
      { choice: "a", hint: "Lots of people think that! But the hump shrinks when the camel has no FOOD. What does the body use up when there's no food?" },
      { choice: "c", hint: "Sand can't get inside a camel's hump. Read the file again. What happens when food is hard to find?" },
      { choice: "d", hint: "Camels walk across dry sand, so they don't need to float. What does the hump hold that gives energy?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Built for the cold", machine: "Suit Lab", icon: "shield", speaker: "vega",
    line: "Frostveil is freezing. Our first job is to keep the crew warm. Which animal body parts should we study?",
    question: "Pick every structure that helps an Arctic animal keep warm.",
    items: [
      { id: "fur", text: "A thick fur coat" },
      { id: "fat", text: "A thick layer of fat under the skin" },
      { id: "small", text: "Small, round, furry ears" },
      { id: "big", text: "Huge, thin ears" },
      { id: "bare", text: "Thin skin with no fur" },
      { id: "tongue", text: "A long, sticky tongue" },
    ],
    hint: "Look for parts that hold heat in, like a blanket. Heat escapes from thin, bare parts.",
    meter: { heat: 5, label: "Suits +5%", story: "The warm-parts list is ready" },
    answer: { kind: "multi", correct: ["fur", "fat", "small"] },
    rightFeedback: "Thick fur, a layer of fat, and small furry ears all help an animal hold in heat.",
    wrong: [
      { pick: "big", hint: "Huge, thin ears let body heat escape. That helps in a hot desert. Is that good in the cold?" },
      { pick: "bare", hint: "Thin, bare skin lets heat get out fast. What covers the skin of Arctic animals?" },
      { pick: "tongue", hint: "A sticky tongue helps catch food, not stay warm. Look for parts that hold heat in." },
      { missing: true, hint: "There are three warm parts. Think about a coat, a blanket of fat, and ears that don't let much heat out." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Too hot inside!", machine: "Suit Lab", icon: "quake", speaker: "vega",
    line: "Surprise! Kai wore the first test suit inside our heated base, and he got way too hot. We need a way to let heat out. Nova pulled up data on three kinds of foxes.",
    question: "Part 1: How many centimeters longer are the fennec fox's ears than the Arctic fox's ears? Part 2: What pattern does the table show? Part 3: How do big ears help the fennec fox survive?",
    data: {
      title: "Fox ear length (about)",
      columns: ["Fox", "Where it lives", "Ear length"],
      rows: [
        ["Fennec fox", "Hot desert", "15 cm"],
        ["Red fox", "Forests and fields", "9 cm"],
        ["Arctic fox", "Cold Arctic", "5 cm"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many centimeters longer are the fennec fox's ears than the Arctic fox's ears?", unit: "cm" },
      { type: "choice", prompt: "What pattern does the table show?", choices: [
        { id: "a", text: "The hotter the place, the bigger the fox's ears." },
        { id: "b", text: "The colder the place, the bigger the fox's ears." },
        { id: "c", text: "All foxes have the same size ears." },
        { id: "d", text: "Foxes in forests have the biggest ears." },
      ] },
      { type: "choice", prompt: "How do big, thin ears help the fennec fox survive in the hot desert?", choices: [
        { id: "a", text: "Body heat escapes through the big ears, which helps the fox stay cool." },
        { id: "b", text: "Big ears keep the fox warm on hot days." },
        { id: "c", text: "Big ears help the fox swim." },
        { id: "d", text: "Big ears store water." },
      ] },
    ],
    hint: "Compare the Where it lives column with the Ear length column.",
    meter: { heat: 10, label: "Suits +10%", story: "The suits get heat vents for inside the base" },
    discovery: { id: "fennec", name: "Fennec foxes", who: "Nova", fact: "Fennec foxes are the smallest foxes, but their ears are huge for their size. The ears let off heat, and they can even hear bugs moving under the sand." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 10 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Big ears let heat out, so desert foxes stay cool. The crew will add vents that open like big ears when the base gets warm!",
    wrong: [
      { step: 1, value: 20, hint: "You want to know how much LONGER. Should you add or subtract?" },
      { step: 1, value: 15, hint: "15 cm is the fennec fox's ear. How much longer is that than the Arctic fox's 5 cm?" },
      { step: 1, value: 6, hint: "6 is the difference between the fennec fox and the red fox. Compare the fennec fox with the Arctic fox." },
      { step: 2, choice: "b", hint: "The Arctic fox lives in the coldest place. Are its ears the biggest or the smallest?" },
      { step: 2, choice: "c", hint: "Read the Ear length column: 15, 9, and 5 cm. Are they the same?" },
      { step: 2, choice: "d", hint: "The red fox lives in forests. Its ears are 9 cm. Whose ears are bigger?" },
      { step: 3, choice: "b", hint: "The desert is already hot. Does the fox need more heat or less heat?" },
      { step: 3, choice: "c", hint: "There's very little water in a hot desert. What escapes through big, thin ears?" },
      { step: 3, choice: "d", hint: "Ears don't hold water. What leaves the body through big, thin ears?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "The stretching giraffe", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Giraffes got long necks by stretching up to reach high leaves. If I stretch my neck every day, it will get longer too!"',
    nova: 'Nova: "A giraffe is born with a long neck. It got that structure from its parents. Stretching doesn\'t grow a longer neck."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about a baby giraffe on the day it is born. Does it already have a long neck?",
    meter: { heat: 5, label: "Suits +5%", story: "Kai stops stretching his neck" },
    discovery: { id: "babygiraffe", name: "Baby giraffes", who: "Nova", fact: "A baby giraffe is about 6 feet (almost 2 meters) tall on the day it is born. That's taller than most grown-ups! It can stand up about an hour later." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Baby giraffes are born with long necks. Animals get body structures like that from their parents, not from stretching." },
      { id: "B", text: "Nova, because giraffes don't like to stretch." },
      { id: "C", text: "Kai. A giraffe grows a long neck because it wants to reach the leaves." },
      { id: "D", text: "Kai. Any animal that stretches every day will grow a longer neck." },
    ],
    writtenPrompt: "Tell Kai in your own words where a giraffe's long neck comes from.",
    debateHints: {
      wrongWho: "A baby giraffe has a long neck on the day it is born. Did it have time to stretch?",
      wrongReason: "Right person, check the reason. Where did the baby giraffe's long neck come from?",
      right: "Nova is right. Animals are born with their body structures. They come from their parents.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Where do they live?", machine: "Animal Files", icon: "grid", speaker: "nova",
    line: "Body parts fit the place an animal lives. I mixed up cards from four Earth environments. Can you sort them back?",
    question: "Sort each body structure by the environment it fits best.",
    hint: "Ask: is this part good for cold and snow, hot sand, deep water, or tall trees?",
    meter: { heat: 5, label: "Suits +5%", story: "The environment cards are sorted" },
    answer: { kind: "sort", bins: { e1: "arctic", e2: "desert", e3: "ocean", e4: "rain", e5: "arctic", e6: "desert", e7: "ocean", e8: "rain" } },
    rightFeedback: "Fur and wide feet fit the snow. Big ears and a fat hump fit the desert. Gills and flippers fit the ocean. A grabbing tail and long arms fit the rainforest trees.",
    sort: {
      bins: [{ id: "arctic", label: "Arctic" }, { id: "desert", label: "Desert" }, { id: "ocean", label: "Ocean" }, { id: "rain", label: "Rainforest" }],
      items: [
        { id: "e1", label: "Thick fur and a layer of fat" },
        { id: "e2", label: "Big ears that let off heat" },
        { id: "e3", label: "Gills that take in oxygen from water" },
        { id: "e4", label: "A tail that can grab branches" },
        { id: "e5", label: "Wide, furry feet that don't sink in snow" },
        { id: "e6", label: "A hump that stores fat for times with little food" },
        { id: "e7", label: "Flippers for swimming" },
        { id: "e8", label: "Long, strong arms for swinging from tree to tree" },
      ],
    },
    wrong: [
      { item: "e2", hint: "Big ears let heat escape. Where does an animal need to get rid of extra heat?" },
      { item: "e6", hint: "Food and water are hard to find in this dry, sandy place. Think of the camel." },
      { item: "e5", hint: "Wide feet spread out an animal's weight so it doesn't sink. Where would it sink?" },
      { item: "e1", hint: "Fur and fat hold in heat. Which place is freezing cold?" },
      { item: "e3", hint: "Gills only work underwater. Which place is all water?" },
      { item: "e7", hint: "Flippers push through water. Which place is all water?" },
      { item: "e4", hint: "A grabbing tail holds on to branches. Which place is full of tall trees?" },
      { item: "e8", hint: "Swinging from tree to tree needs lots of trees. Which place is that?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The blubber glove", machine: "Model Bench", icon: "flask", speaker: "nova",
    line: "Seals and whales swim in icy water. They stay warm with blubber, a thick layer of fat under the skin. I want to build a model of blubber to test.",
    question: "Which glove would be the best model of a seal's blubber?",
    hint: "Blubber is a thick layer of fat that wraps around the body. Which glove has a thick layer of fat around the hand?",
    meter: { supplies: 1, label: "Swatches +1", story: "The blubber glove is built" },
    discovery: { id: "bowhead", name: "Bowhead whales", who: "Nova", fact: "Bowhead whales live in icy Arctic water. They have the thickest blubber of any animal. It can be thicker than a school ruler is long!" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "A glove inside a bag filled with a thick layer of solid fat, like shortening" },
      { id: "b", text: "A glove made of paper" },
      { id: "c", text: "A glove filled with ice cubes" },
      { id: "d", text: "A glove with holes cut in it" },
    ],
    rightFeedback: "A thick layer of solid fat around the hand works like a seal's blubber. Now we can test it!",
    wrong: [
      { choice: "b", hint: "Paper gets soggy in water and has no fat. What is blubber made of?" },
      { choice: "c", hint: "Ice would make the hand colder! Blubber is a layer of fat that keeps heat in." },
      { choice: "d", hint: "Holes would let cold water right in. Blubber is a thick layer with no holes. What is it made of?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Ice water test", machine: "Model Bench", icon: "dial", speaker: "kai",
    line: "I tested Nova's gloves! I put my hand in a bucket of ice water three times. Each time, I timed how long before my hand felt too cold.",
    question: "Part 1: How many more seconds did Kai's hand stay warm with the thick fat layer than with the empty bag? Part 2: What pattern does the table show? Part 3: Which animal's structure does this test help explain?",
    data: {
      title: "How long Kai's hand stayed warm in ice water",
      columns: ["Glove", "Seconds before too cold"],
      rows: [
        ["Empty bag, no fat", "20"],
        ["Thin layer of fat", "60"],
        ["Thick layer of fat", "150"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many more seconds did Kai's hand stay warm with the thick layer of fat than with the empty bag?", unit: "seconds" },
      { type: "choice", prompt: "What pattern does the table show?", choices: [
        { id: "a", text: "The thicker the layer of fat, the longer the hand stayed warm." },
        { id: "b", text: "The empty bag kept the hand warm the longest." },
        { id: "c", text: "Fat makes a hand colder." },
        { id: "d", text: "All three gloves worked the same." },
      ] },
      { type: "choice", prompt: "Which animal's structure does this test help explain?", choices: [
        { id: "a", text: "A seal's thick blubber in icy water" },
        { id: "b", text: "A giraffe's long neck" },
        { id: "c", text: "A duck's webbed feet" },
        { id: "d", text: "A fennec fox's big ears" },
      ] },
    ],
    hint: "Read the Seconds column from top to bottom. What changes as the fat gets thicker?",
    meter: { heat: 5, label: "Suits +5%", story: "The glove test is logged" },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 130 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "More fat kept the hand warm longer. That's how blubber keeps seals warm in icy water!",
    wrong: [
      { step: 1, value: 170, hint: "You want to know how many MORE seconds. Should you add or subtract?" },
      { step: 1, value: 150, hint: "150 is the time with the thick layer. How much more is that than the empty bag's 20 seconds?" },
      { step: 1, value: 90, hint: "90 is the difference between the thick and thin layers. Compare the thick layer with the empty bag." },
      { step: 2, choice: "b", hint: "The empty bag only lasted 20 seconds. Is that the longest or the shortest?" },
      { step: 2, choice: "c", hint: "The fat gloves lasted longer, not shorter. Did fat make the hand colder or keep it warm?" },
      { step: 2, choice: "d", hint: "The times were 20, 60, and 150 seconds. Were they the same?" },
      { step: 3, choice: "b", hint: "The test was about staying warm in icy water. Which animal has a thick layer of fat for that?" },
      { step: 3, choice: "c", hint: "Webbed feet help ducks swim, not stay warm. Which animal has a thick layer of fat?" },
      { step: 3, choice: "d", hint: "Big ears let heat OUT. The fat glove kept heat in. Which animal has a layer of fat?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The open water", machine: "Suit Lab", icon: "water", speaker: "vega",
    line: "Surprise! The ice shelf cracked, and there's a strip of icy open water across our route. The suits must help us swim AND stay warm. Nova found three cold-water animals to study.",
    question: "Part 1: What do all three animals have that helps them swim? Part 2: The sea otter has no blubber. What keeps it warm? Part 3: Pick the two suit parts the crew should add for the water crossing.",
    data: {
      title: "Cold-water animals",
      columns: ["Animal", "Helps it swim", "Keeps it warm"],
      rows: [
        ["Harp seal", "Flippers", "Thick blubber"],
        ["Sea otter", "Webbed back feet", "Super-thick fur"],
        ["Penguin", "Flipper-shaped wings", "Fat and tightly packed feathers"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What do all three animals have that helps them swim?", choices: [
        { id: "a", text: "Wide, flat body parts that push against the water" },
        { id: "b", text: "Long necks" },
        { id: "c", text: "Big ears" },
        { id: "d", text: "Tails that grab branches" },
      ] },
      { type: "choice", prompt: "The sea otter has no blubber. What keeps it warm?", choices: [
        { id: "a", text: "Its super-thick fur" },
        { id: "b", text: "Its webbed back feet" },
        { id: "c", text: "Swimming in warm water" },
        { id: "d", text: "Nothing. It is always cold." },
      ] },
      { type: "multi", prompt: "Pick the two suit parts the crew should add for the water crossing.", choices: [
        { id: "fins", text: "Swim fins on the boots, like webbed feet" },
        { id: "layer", text: "A thick, waterproof layer that holds in heat, like blubber" },
        { id: "vents", text: "Big vents that let heat out, like fennec fox ears" },
        { id: "neck", text: "A long neck tube, like a giraffe" },
      ] },
    ],
    hint: "Read the table one column at a time. What is the same in the Helps it swim column?",
    meter: { heat: 10, label: "Suits +10%", story: "The suits get swim fins and a warm water layer" },
    discovery: { id: "seaotter", name: "Sea otter fur", who: "Kai", fact: "Sea otters have the thickest fur of any animal. A patch the size of a postage stamp can have up to a million hairs!" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["fins", "layer"] },
    ] },
    rightFeedback: "Fins to push water and a warm layer to hold in heat, just like cold-water animals. The crew can cross!",
    wrong: [
      { step: 1, choice: "b", hint: "None of these animals has a long neck. Look at the Helps it swim column. What shape are those parts?" },
      { step: 1, choice: "c", hint: "Ears don't push water. Look at the Helps it swim column." },
      { step: 1, choice: "d", hint: "There are no branches in the ocean. Look at the Helps it swim column." },
      { step: 2, choice: "b", hint: "Webbed feet help it swim. Look at the Keeps it warm column for the sea otter." },
      { step: 2, choice: "c", hint: "Sea otters swim in cold water. Look at the Keeps it warm column." },
      { step: 2, choice: "d", hint: "Every animal in the table has a way to stay warm. Look at the Keeps it warm column." },
      { step: 3, pick: "vents", hint: "Letting heat out is great in a desert. In icy water, the crew needs to keep heat IN." },
      { step: 3, pick: "neck", hint: "A long neck helps giraffes reach leaves. Does it help swim or stay warm?" },
      { step: 3, missing: true, hint: "Pick two parts: one to help swim and one to stay warm." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Design the suit", machine: "Suit Lab", icon: "snap", speaker: "kai",
    line: "Time to put the suits together! Each suit part copies an animal structure we studied. Help me label them.",
    question: "Match each suit part to the animal structure it copies.",
    hint: "Think about the job of each suit part. Which animal body part does the same job?",
    meter: { heat: 10, label: "Suits +10%", story: "The suit parts are matched and stitched" },
    discovery: { id: "biomimicry", name: "Copying nature", who: "Kai", fact: "When people copy ideas from animals or plants to design things, it's called biomimicry. Bumps on humpback whale flippers gave engineers ideas for better fan blades." },
    answer: { kind: "sort", bins: { s1: "fur", s2: "webbed", s3: "ears", s4: "feet" } },
    rightFeedback: "Every suit part copies a real animal structure that does the same job. That's smart design!",
    sort: {
      bins: [
        { id: "fur", label: "Thick fur (musk ox)" },
        { id: "webbed", label: "Webbed feet (duck)" },
        { id: "ears", label: "Big ears (fennec fox)" },
        { id: "feet", label: "Wide, furry feet (Arctic hare)" },
      ],
      items: [
        { id: "s1", label: "A fluffy inner layer that traps warm air" },
        { id: "s2", label: "Clip-on swim fins for the boots" },
        { id: "s3", label: "Vents that open to let out extra heat indoors" },
        { id: "s4", label: "Wide boot bottoms that don't sink in snow" },
      ],
    },
    wrong: [
      { item: "s1", hint: "This layer keeps the crew warm. Which animal part holds in heat?" },
      { item: "s2", hint: "Fins push water when you swim. Which animal part does that?" },
      { item: "s3", hint: "These vents let heat escape. Which animal part lets off heat?" },
      { item: "s4", hint: "These boots spread out the crew's weight on snow. Which animal part keeps it from sinking?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's big-ear hood", machine: "Suit Lab", icon: "static", speaker: "kai",
    line: "I made the hood extra cool! I copied the fennec fox and gave it big, thin ear flaps that stay open all the time. Now we can hear better outside on the ice!",
    question: "Part 1: What went wrong with Kai's hood? Part 2: How should Kai fix it?",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's hood?", choices: [
        { id: "a", text: "Big, thin ears let heat escape. That helps in a hot desert, but outside on the ice the crew would lose body heat." },
        { id: "b", text: "The ear flaps are the wrong color." },
        { id: "c", text: "Big ears make it harder to hear." },
        { id: "d", text: "Nothing is wrong. Big ears work well in every environment." },
      ] },
      { type: "choice", prompt: "How should Kai fix the hood?", choices: [
        { id: "a", text: "Copy the Arctic fox: use small, round ear flaps covered in thick, fluffy lining." },
        { id: "b", text: "Make the ear flaps even bigger and thinner." },
        { id: "c", text: "Copy the giraffe and make the hood very tall." },
        { id: "d", text: "Take off the hood so the crew can hear everything." },
      ] },
    ],
    hint: "Remember the fox data. Where do foxes with big ears live? Where do foxes with small ears live?",
    meter: { heat: 5, label: "Suits +5%", story: "The hood is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Big ears are for letting heat out. In the cold, small furry ears keep heat in, just like the Arctic fox's.",
    wrong: [
      { step: 1, choice: "b", hint: "Color isn't the problem. What do big, thin ears let escape?" },
      { step: 1, choice: "c", hint: "Big ears are good for hearing. But what else do big, thin ears let out?" },
      { step: 1, choice: "d", hint: "Fennec foxes live in hot deserts. Would their big ears help in the freezing cold?" },
      { step: 2, choice: "b", hint: "Bigger, thinner flaps would let out even more heat. Which fox lives in the cold?" },
      { step: 2, choice: "c", hint: "A giraffe's neck helps it reach leaves. It doesn't keep heat in. Which fox lives in the cold?" },
      { step: 2, choice: "d", hint: "No hood means lots of heat escapes from the head. Which fox's ears keep heat in?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Who could live here?", machine: "Animal Files", icon: "crew", speaker: "nova",
    line: "Let's check our thinking. If these Earth animals came to Frostveil's ice fields, which ones have the body structures to survive the cold?",
    question: "Pick every animal whose body structures fit Frostveil's ice and cold.",
    items: [
      { id: "seal", text: "Harp seal (thick blubber)" },
      { id: "muskox", text: "Musk ox (long, thick, woolly coat)" },
      { id: "hare", text: "Arctic hare (thick fur, wide furry feet)" },
      { id: "fennec", text: "Fennec fox (huge, thin ears)" },
      { id: "camel", text: "Desert camel (short fur, fat hump)" },
      { id: "monkey", text: "Spider monkey (grabbing tail, long arms)" },
    ],
    hint: "Look at the body structures in each card. Which ones hold heat in?",
    meter: { heat: 5, label: "Suits +5%", story: "The cold-fit list is checked" },
    discovery: { id: "muskoxhair", name: "Musk ox hair", who: "Nova", fact: "Musk oxen have some of the longest hair of any wild animal. Their long outer hair can hang almost to the ground, with soft, warm wool underneath." },
    answer: { kind: "multi", correct: ["seal", "muskox", "hare"] },
    rightFeedback: "Blubber, woolly coats, thick fur, and wide feet fit the ice. Those animals are built for the cold.",
    wrong: [
      { pick: "fennec", hint: "Huge, thin ears let heat escape. Would that help on freezing ice?" },
      { pick: "camel", hint: "This camel lives in a hot desert. Its hump stores food energy, and its short fur doesn't hold much heat." },
      { pick: "monkey", hint: "A grabbing tail helps in rainforest trees. Are there trees on the ice fields? Does it keep the monkey warm?" },
      { missing: true, hint: "There are three animals built for the cold. Look for fat, thick fur, and a woolly coat." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Grippy boots", machine: "Model Bench", icon: "trail", speaker: "kai",
    line: "The ice ridges are steep and slippery. Mountain goats climb steep, rocky cliffs without slipping. Their hooves have a hard outer edge and a soft, rough pad in the middle.",
    question: "Which boot sole copies the mountain goat's hooves best?",
    hint: "The goat's hoof has two parts: a hard edge and a soft, rough pad. Which boot has both?",
    meter: { supplies: 1, label: "Swatches +1", story: "The grippy boot sole is chosen" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "A smooth, shiny plastic sole" },
      { id: "b", text: "A sole with a hard outer edge and a soft, rough, grippy pad in the middle" },
      { id: "c", text: "A sole covered in slippery oil" },
      { id: "d", text: "A round, rolling sole like a ball" },
    ],
    rightFeedback: "The hard edge bites into the ice, and the soft, rough pad grips. Just like a mountain goat's hoof!",
    wrong: [
      { choice: "a", hint: "Smooth and shiny would slide on ice. The goat's hoof has a rough pad. Which boot copies that?" },
      { choice: "c", hint: "Oil makes things slippery! The goat needs grip. Which boot has a rough pad?" },
      { choice: "d", hint: "A round sole would roll right down the ridge. Which boot has a hard edge and a rough pad?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The storm walk", machine: "Suit Lab", icon: "relay", speaker: "vega",
    line: "This is it! A snowstorm is coming, and the crew must walk to the far outpost. Nova tested three suit versions outside for 30 minutes and measured the temperature inside each one.",
    question: "Part 1: How many degrees warmer was Suit C than Suit A? Part 2: Which suit should the crew wear for the storm walk? Part 3: Write 2–3 sentences to Commander Vega explaining which animal structures your suit copies and how they help. Use the table.",
    data: {
      title: "Temperature inside each suit after 30 minutes on the ice",
      columns: ["Suit", "Layers", "Temperature inside"],
      rows: [
        ["A", "Thin cloth only", "10°C"],
        ["B", "Fluffy layer (like fur)", "22°C"],
        ["C", "Fluffy layer (like fur) + fat-like gel layer (like blubber)", "30°C"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many degrees warmer was Suit C than Suit A?", unit: "°C" },
      { type: "choice", prompt: "Which suit should the crew wear for the storm walk?", choices: [
        { id: "a", text: "Suit A, because it is the thinnest" },
        { id: "b", text: "Suit B, because it has fur but no fat layer" },
        { id: "c", text: "Suit C, because copying both fur and blubber kept the most heat in" },
        { id: "d", text: "Any suit. They all kept the crew the same temperature." },
      ] },
      { type: "write", prompt: "Explain to Commander Vega which animal structures your suit copies and how they help. Use the table.", minWords: 20 },
    ],
    rubric: ["Names at least one animal structure the suit copies (fur, blubber, webbed feet, small ears, wide feet)", "Explains how that structure helps an animal survive its environment", "Uses the table as evidence (a suit or a temperature)"],
    hint: "Find Suit A and Suit C in the Temperature inside column. Then compare them.",
    meter: { heat: 10, label: "Suits +10%", story: "The survival suits are ready for the storm walk" },
    discovery: { id: "reindeer", name: "Hollow hair", who: "Kai", fact: "Reindeer have hollow hairs filled with air. The air helps hold in body heat, and it even helps reindeer float when they swim across rivers." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 20 },
      { kind: "choice", correct: "c" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "The survival suits are ready, and you explained how animal structures inspired every part! Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 40, hint: "You want to know how much WARMER. Should you add or subtract?" },
      { step: 1, value: 30, hint: "30°C is how warm Suit C was. How much warmer is that than Suit A's 10°C?" },
      { step: 1, value: 8, hint: "8 is the difference between Suit C and Suit B. Compare Suit C with Suit A." },
      { step: 2, choice: "a", hint: "Suit A was only 10°C inside. Is that the warmest or the coldest?" },
      { step: 2, choice: "b", hint: "Suit B was warmer than A. But which suit had the highest temperature inside?" },
      { step: 2, choice: "d", hint: "The temperatures were 10, 22, and 30°C. Were they the same?" },
    ],
  },
};

export default {
  id: "SCI.3.13A-XP",
  standard: "SCI.3.13A-XP",
  engine: "expedition_station",
  title: "The Survival Suits",
  planet: "Frostveil",
  outpost: "Suit Lab · before the storm walk",
  grade: 3,
  subject: "Science",
  teks: "3.13A",
  supportingTeks: ["3.1A", "3.1B", "3.1E", "3.1G", "3.2B", "3.2C", "3.2D", "3.3A", "3.3C", "3.5A", "3.5F"],
  skillsChip: "3.13A · Animal structures help them survive",
  iCan: "I can explain how animal body parts, like a giraffe's long neck or a duck's webbed feet, help animals survive where they live. I can use those ideas to design a survival suit.",
  blurb: "The crew needs survival suits for Frostveil's ice. To design them, they study how real Earth animals survive in the Arctic, the desert, the ocean, and the rainforest.",
  mission: "Study animal body structures, test models, and design survival suits that copy what animals do to survive.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.13 · FROSTVEIL SUIT LAB",
  playableActs: [1, 2, 3],
  earthTrue: "Frostveil and the crew are invented. Every animal, body structure, and fact in this quest is real Earth science. The glove and suit tests are classroom-style models.",
  meterStart: { heat: 15, supplies: 0, journal: 0 },
  meterLabels: { heat: "Suits ready", heatUnit: "%", supplies: "Test swatches", suppliesUnit: "swatches" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Our crew needs survival suits before we can explore Frostveil's ice fields.",
    "Earth animals already know how to survive in cold, heat, and water. Their body parts help them do it.",
    "Study the animals, then help us build suits that copy them. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Animal files", "Act 2 · Test the models", "Act 3 · Build the suits"],
    completes: [
      "You matched body parts to their jobs and cooled Kai down, {firstName}!",
      "You tested blubber and got the crew across the open water, {firstName}!",
      "The survival suits are ready for the storm, {firstName}! Great science.",
    ],
    teasers: [
      "Next on Frostveil: Kai thinks stretching can grow a longer neck, and Nova builds a blubber glove. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: it's time to stitch the suits, and Kai's new hood has a big problem. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Today we test our ideas with models, and Kai and I already disagree about giraffes.",
      "Let's get started.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Our tests are done. It's time to build the survival suits.",
      "Every part should copy an animal structure that does the same job.",
    ],
  }),
  tasks,
};
