// Expedition Station — The Telescope Array (MA.4.7C-XP)
// Grade 4 · Math · Cloudreach. Main standard 4.7C (determine the approximate
// measure of an angle in degrees to the nearest whole number using a
// protractor); also practices 4.7A (angles are two rays with a shared
// endpoint), 4.7B (a one-degree angle turns 1/360 of a circle), 4.7D (draw an
// angle with a given measure), and 4.7E (find an unknown part of two
// adjacent, non-overlapping angles).
// The protractor visual labels its scale from 0 on the angle's starting ray.
// With from: "left", the starting ray points left, so the numbers count up
// from the left side. The classic wrong answer is always 180 − x.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Parts of the telescope angle", machine: "Telescope Dial", icon: "dial", speaker: "kai",
    line: "Each telescope sits on a pivot. The floor line and the telescope tube both start at the pivot and go out forever in one direction. Together they make an angle.",
    question: "Part 1: What do we call the point where the two rays meet? Part 2: What do we call the two straight paths that start at that point?",
    parts: [
      { type: "choice", prompt: "The point where the two rays meet is called the...", visual: { type: "angle", degrees: 50, title: "Telescope 1" }, choices: [
        { id: "a", text: "vertex" },
        { id: "b", text: "degree" },
        { id: "c", text: "ray" },
        { id: "d", text: "protractor" },
      ] },
      { type: "choice", prompt: "The two straight paths that start at the vertex are called...", choices: [
        { id: "a", text: "rays" },
        { id: "b", text: "line segments with two endpoints" },
        { id: "c", text: "circles" },
        { id: "d", text: "vertices" },
      ] },
    ],
    hint: "An angle is made of two rays that share one endpoint. The shared endpoint has a special name.",
    meter: { heat: 10, label: "Comet lock +10%", story: "Telescope 1 is awake" },
    discovery: { id: "snowball", name: "Dirty snowballs", who: "Nova", fact: "A comet is a big chunk of ice, dust, and rock. Scientists sometimes call comets \"dirty snowballs.\"" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "The vertex is the shared endpoint, and the two rays start there. That makes an angle!",
    wrong: [
      { step: 1, choice: "b", hint: "A degree is how we measure an angle. What is the name of the point in the corner?" },
      { step: 1, choice: "c", hint: "A ray is one of the straight paths. The point where they meet has a different name." },
      { step: 1, choice: "d", hint: "A protractor is the tool we measure with. What is the corner point called?" },
      { step: 2, choice: "b", hint: "A segment stops at both ends. These paths start at the vertex and go on forever the other way." },
      { step: 2, choice: "c", hint: "A circle is round. The sides of an angle are straight." },
      { step: 2, choice: "d", hint: "Vertices are corner points. What are the straight sides called?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Click the dial", machine: "Telescope Dial", icon: "dial", speaker: "nova",
    line: "The telescope dial clicks as it turns. Each click turns the telescope through a one-degree angle. That's 1/360 of a full circle.",
    question: "Part 1: How many one-degree clicks make one full turn? Part 2: Telescope 2 turned 90 clicks. What is the measure of its angle?",
    parts: [
      { type: "number", prompt: "How many one-degree angles make a full circle?", unit: "degrees" },
      { type: "number", prompt: "Telescope 2 turned through 90 one-degree angles. How many degrees is its angle?", unit: "degrees", visual: { type: "angle", degrees: 90, title: "Telescope 2" } },
    ],
    hint: "A one-degree angle is 1/360 of a circle. The degrees of an angle are the number of one-degree angles it turns.",
    meter: { heat: 5, label: "Comet lock +5%", story: "The dials are clicking" },
    discovery: { id: "tail", name: "Comet tails", who: "Kai", fact: "When a comet gets close to the Sun, its ice starts to melt into gas. That makes a glowing tail, and the tail always points away from the Sun." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 360 },
      { kind: "number", value: 90 },
    ] },
    rightFeedback: "360 one-degree angles make a full circle. 90 one-degree angles make a 90° angle, a right angle!",
    wrong: [
      { step: 1, value: 180, hint: "180° is a straight angle, only half a turn. How many for the whole circle?" },
      { step: 1, value: 100, hint: "A one-degree angle is 1/360 of a circle, not 1/100. How many fit in the whole circle?" },
      { step: 2, value: 360, hint: "360 is a full circle. The telescope only turned 90 clicks of 1 degree each." },
      { step: 2, value: 1, hint: "Each click is 1 degree. 90 clicks is how many degrees?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Read the first dial", machine: "Star Chart", icon: "trail", speaker: "kai",
    line: "The protractor is on Telescope 3. Its center is on the pivot, and 0 is lined up on the floor ray.",
    question: "How many degrees is Telescope 3's angle?",
    unit: "degrees",
    hint: "Start at the 0 on the floor ray. Count up the scale until you reach the telescope ray. Each small tick is 5 degrees.",
    meter: { heat: 5, label: "Comet lock +5%", story: "Telescope 3 is measured" },
    discovery: { id: "galileo", name: "Galileo's telescope", who: "Nova", fact: "In 1609, Galileo Galilei pointed a telescope at the night sky. He was one of the first people to see the Moon's craters and four of Jupiter's moons." },
    visual: { type: "angle", degrees: 40, title: "Telescope 3" },
    answer: { kind: "number", value: 40 },
    rightFeedback: "The telescope ray crosses the scale at 40. The angle is 40°!",
    wrong: [
      { value: 140, hint: "That's the scale that starts at the other end. Start at the 0 that sits on the floor ray." },
      { value: 30, hint: "The ray is past the 30 label. Count on by 5s from 30." },
      { value: 50, hint: "Count the ticks again. The ray is one tick past 30, then one more. Each tick is 5." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Write the measuring steps", machine: "Aim Lock", icon: "log", speaker: "nova",
    line: "New crew members are coming up to the reef. They need the steps for measuring any telescope angle with a protractor.",
    question: "Put the steps for measuring an angle in order.",
    hint: "First the protractor has to sit in the right spot. Then line up the 0. Only then can you read the number.",
    meter: { supplies: 1, label: "Telescopes aimed +1", story: "The new crew can measure angles" },
    answer: { kind: "order", correct: ["center", "zero", "read", "write"] },
    items: [
      { id: "read", text: "Find where the other ray crosses the scale that starts at 0." },
      { id: "write", text: "Write the number with a degree sign, like 40°." },
      { id: "center", text: "Put the center point of the protractor on the vertex." },
      { id: "zero", text: "Turn the protractor so 0 lines up on one ray." },
    ],
    rightFeedback: "Center on the vertex, 0 on one ray, read the other ray, then write it in degrees. That works for every angle!",
    wrong: [
      { position: 0, hint: "The protractor has to sit on the angle first. Where does its center point go?" },
      { position: 1, hint: "After the center is on the vertex, line up 0 with one of the rays." },
      { position: 2, hint: "Once 0 is on one ray, look at where the other ray crosses the scale." },
      { position: 3, hint: "Writing the answer comes last, after you read the scale." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Comet sighting!", machine: "Star Chart", icon: "snap", speaker: "vega",
    line: "Surprise! Nova spotted the comet low in the east! Telescope 4 swung toward it, but this time its floor ray points left.",
    question: "Part 1: Read Telescope 4's angle. Part 2: What kind of angle is it? Part 3: How many more degrees until it makes a straight angle?",
    parts: [
      { type: "number", prompt: "The floor ray points left. Use the scale that starts at 0 on the left. How many degrees is the angle?", unit: "degrees", visual: { type: "angle", degrees: 120, from: "left", title: "Telescope 4" } },
      { type: "choice", prompt: "What kind of angle is 120°?", choices: [
        { id: "a", text: "obtuse, more than 90° but less than 180°" },
        { id: "b", text: "acute, less than 90°" },
        { id: "c", text: "right, exactly 90°" },
        { id: "d", text: "straight, exactly 180°" },
      ] },
      { type: "number", prompt: "A straight angle is 180°. How many more degrees would Telescope 4 need to turn to make a straight angle?", unit: "degrees" },
    ],
    hint: "Start at the 0 that sits on the floor ray, on the left side. For Part 3, what adds to 120 to make 180?",
    meter: { heat: 10, label: "Comet lock +10%", story: "The comet is spotted" },
    discovery: { id: "halley", name: "Halley's Comet", who: "Nova", fact: "Halley's Comet comes back near Earth about every 76 years. It was last seen in 1986, and it will be back in 2061." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 120 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 60 },
    ] },
    rightFeedback: "120° is obtuse, and 60° more makes a straight angle: 120 + 60 = 180!",
    wrong: [
      { step: 1, value: 60, hint: "That's the scale that starts on the right. The floor ray points left, so start at the 0 on the left." },
      { step: 1, value: 130, hint: "The ray is right on a big label. Check which label it crosses." },
      { step: 2, choice: "b", hint: "Acute angles are smaller than a square corner. Is 120° smaller than 90°?" },
      { step: 2, choice: "c", hint: "A right angle is exactly 90°. This one opens wider." },
      { step: 2, choice: "d", hint: "A straight angle is 180° and looks like a flat line. Is 120° that wide?" },
      { step: 3, value: 300, hint: "Don't add 180. Find what goes with 120 to make 180." },
      { step: 3, value: 120, hint: "120° is how far it already turned. How much more to get to 180°?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Sort the sky angles", machine: "Star Chart", icon: "cells", speaker: "kai",
    line: "I wrote down every telescope angle on the reef, but the list is a mess. Let's sort them so Commander Vega can see them fast.",
    question: "Sort each telescope angle into the right bin.",
    hint: "Acute is less than 90°. Right is exactly 90°. Obtuse is more than 90° but less than 180°. Straight is exactly 180°.",
    meter: { supplies: 1, label: "Telescopes aimed +1", story: "The angle list is sorted" },
    discovery: { id: "sunstar", name: "Our star", who: "Nova", fact: "The Sun is a star. It looks bigger and brighter than other stars because it is so much closer to Earth." },
    answer: { kind: "sort", bins: { a1: "acute", a2: "right", a3: "obtuse", a4: "straight", a5: "acute", a6: "obtuse", a7: "acute" } },
    rightFeedback: "Every angle is in the right bin. 90° is the line between acute and obtuse!",
    sort: {
      bins: [
        { id: "acute", label: "Acute (less than 90°)" },
        { id: "right", label: "Right (90°)" },
        { id: "obtuse", label: "Obtuse (between 90° and 180°)" },
        { id: "straight", label: "Straight (180°)" },
      ],
      items: [
        { id: "a1", label: "Telescope A: 35°" },
        { id: "a2", label: "Telescope B: 90°" },
        { id: "a3", label: "Telescope C: 145°" },
        { id: "a4", label: "Telescope D: 180°" },
        { id: "a5", label: "Telescope E: 85°" },
        { id: "a6", label: "Telescope F: 95°" },
        { id: "a7", label: "Telescope G: 10°" },
      ],
    },
    wrong: [
      { item: "a5", hint: "85° is close to 90°, but it is still less than 90°." },
      { item: "a6", hint: "95° is just a little more than 90°. More than 90° but less than 180° is obtuse." },
      { item: "a2", hint: "Exactly 90° is a square corner. It has its own bin." },
      { item: "a4", hint: "180° makes a flat, straight line. It has its own bin." },
      { item: "a3", hint: "145° is more than 90° but less than 180°." },
      { item: "a1", hint: "35° is less than 90°." },
      { item: "a7", hint: "10° is a tiny angle, much less than 90°." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Fix Kai's reading", machine: "Repair", icon: "log", speaker: "nova",
    line: "Kai measured Telescope 5 and wrote 110° in the log. But the telescope is pointing up at a pretty small angle. Something doesn't look right.",
    question: "Part 1: What went wrong? Part 2: Read the angle the right way.",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's reading?", visual: { type: "angle", degrees: 70, from: "left", title: "Telescope 5" }, choices: [
        { id: "a", text: "He read the scale that starts at the wrong end. The floor ray points left, so he should count from the 0 on the left." },
        { id: "b", text: "He forgot to add 180." },
        { id: "c", text: "Nothing is wrong. The angle is 110°." },
      ] },
      { type: "number", prompt: "Start at 0 on the floor ray. How many degrees is Telescope 5's angle?", unit: "degrees", visual: { type: "angle", degrees: 70, from: "left", title: "Telescope 5" } },
    ],
    hint: "Look at the angle first. Is it smaller or bigger than a square corner? An angle smaller than 90° can't be 110°.",
    meter: { supplies: 1, label: "Telescopes aimed +1", story: "Kai's log is fixed" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 70 },
    ] },
    rightFeedback: "Fixed! The angle is acute, so it's 70°, not 110°. Kai read the other scale: 180 − 70 = 110.",
    wrong: [
      { step: 1, choice: "b", hint: "Adding 180 would make it bigger than a straight line. Which 0 did Kai start from?" },
      { step: 1, choice: "c", hint: "The angle is smaller than a square corner. Can it be 110°?" },
      { step: 2, value: 110, hint: "That's Kai's mistake. Start from the 0 that sits on the floor ray." },
      { step: 2, value: 60, hint: "The ray is past the 60 label. Count on by 5s." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Finish the turn", machine: "Aim Lock", icon: "battery", speaker: "kai",
    line: "The full turn to the comet is 110°. Telescope 6 already turned 45° before its motor got stuck. The rest of the turn sits right next to the first part.",
    question: "How many more degrees does Telescope 6 need to turn to reach the comet?",
    unit: "degrees",
    hint: "The two parts go together to make the whole 110° angle. 45 + ? = 110.",
    meter: { heat: 5, label: "Comet lock +5%", story: "Telescope 6 reaches the comet" },
    visual: { type: "angle", degrees: 110, title: "The full turn to the comet" },
    answer: { kind: "number", value: 65 },
    rightFeedback: "45° + 65° = 110°. The two parts make the whole turn!",
    wrong: [
      { value: 155, hint: "You added the parts. 110° is already the whole turn. Find the missing part." },
      { value: 45, hint: "45° is the part it already turned. How much is left?" },
      { value: 75, hint: "Check your subtraction. 110 − 45 = ?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Draw the aim line", machine: "Aim Lock", icon: "grid", speaker: "nova",
    line: "The comet is 65° above the horizon. I need to draw a 65° aim line on the star chart for Telescope 7.",
    question: "Part 1: Pick the right way to draw a 65° angle. Part 2: Read my drawing to check it.",
    parts: [
      { type: "choice", prompt: "Nova drew a ray and put the protractor's center on its endpoint, with 0 on the ray. What should she do next?", choices: [
        { id: "a", text: "Make a dot at 65 on the scale that starts at 0 on her ray. Then draw a ray from the vertex through the dot." },
        { id: "b", text: "Make a dot at 65 on the scale that starts at 180 on her ray. Then draw the ray." },
        { id: "c", text: "Draw a longer ray so the angle gets bigger." },
      ] },
      { type: "number", prompt: "Here is Nova's drawing. How many degrees is her angle?", unit: "degrees", visual: { type: "angle", degrees: 65, from: "left", title: "Nova's aim line" } },
    ],
    hint: "Drawing an angle is like measuring backwards. Use the scale whose 0 sits on your first ray.",
    meter: { heat: 5, label: "Comet lock +5%", story: "The aim line is drawn" },
    discovery: { id: "saturn", name: "Saturn's rings", who: "Kai", fact: "Saturn's rings are made of billions of pieces of ice and rock. Some are as small as dust, and some are as big as a house." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 65 },
    ] },
    rightFeedback: "Nova's aim line is 65°. She used the scale that starts at 0 on her ray!",
    wrong: [
      { step: 1, choice: "b", hint: "That scale starts at 180 on her ray. A dot at 65 there would make a 115° angle." },
      { step: 1, choice: "c", hint: "Ray length doesn't change an angle. Where does the dot go?" },
      { step: 2, value: 115, hint: "That's the other scale. The first ray points left, so start at the 0 on the left." },
      { step: 2, value: 60, hint: "The ray is one tick past 60. Each tick is 5." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The double scope", machine: "Telescope Dial", icon: "quake", speaker: "vega",
    line: "Surprise! The comet is moving fast. Telescope 8 turned 35° from the floor. Then its top lens turned 55° more, right next to the first angle, with no overlap.",
    question: "Part 1: What is the total angle? Part 2: What kind of angle is it? Part 3: A mirror angle sits next to it so the two make a straight line. How big is the mirror angle?",
    parts: [
      { type: "number", prompt: "35° and 55° are next to each other with no overlap. What is the whole angle?", unit: "degrees" },
      { type: "choice", prompt: "Check the protractor. What kind of angle is the whole turn?", visual: { type: "angle", degrees: 90, title: "Telescope 8's whole turn" }, choices: [
        { id: "a", text: "right" },
        { id: "b", text: "acute" },
        { id: "c", text: "obtuse" },
        { id: "d", text: "straight" },
      ] },
      { type: "number", prompt: "Together, the whole turn and the mirror angle make a straight line, 180°. How big is the mirror angle?", unit: "degrees" },
    ],
    hint: "Add the two parts to get the whole. A straight line is 180°, so the mirror angle is what's left after the whole turn.",
    meter: { heat: 10, label: "Comet lock +10%", story: "The double scope is locked" },
    discovery: { id: "hubble", name: "Hubble Space Telescope", who: "Nova", fact: "The Hubble Space Telescope was launched in 1990. It flies above Earth's air, so its pictures of space are very sharp." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 90 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 90 },
    ] },
    rightFeedback: "35° + 55° = 90°, a right angle. And 90° + 90° = 180°, a straight line!",
    wrong: [
      { step: 1, value: 20, hint: "You subtracted. The two parts sit side by side, so put them together." },
      { step: 1, value: 80, hint: "Check your adding. 35 + 55 = ?" },
      { step: 2, choice: "b", hint: "Acute is less than 90°. This angle is exactly 90°." },
      { step: 2, choice: "c", hint: "Obtuse is more than 90°. This angle is exactly 90°." },
      { step: 2, choice: "d", hint: "Straight is 180°. This angle is half of that." },
      { step: 3, value: 270, hint: "Don't add. The two angles together make 180°. What's left after 90°?" },
      { step: 3, value: 180, hint: "180° is the whole straight line. The mirror angle is only part of it." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The long telescope", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Telescope 9 has a super long tube, and Telescope 10 has a short one. They both say 50°, but the long one must make a bigger angle. Longer rays make a bigger angle!"',
    nova: 'Nova: "Nope! An angle measures how far the rays turn apart. How long the rays are doesn\'t matter. Both angles are 50°."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Picture opening a door a little bit. Does a bigger door open a bigger angle, or the same angle?",
    meter: { heat: 5, label: "Comet lock +5%", story: "Kai rethinks long rays" },
    discovery: { id: "mitchell", name: "Maria Mitchell", who: "Nova", fact: "In 1847, Maria Mitchell found a new comet with her telescope. She became America's first woman to work as an astronomer." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. An angle's measure is how far the rays turn from each other. Longer rays turn the same amount, so both are 50°." },
      { id: "B", text: "Nova, because short telescopes are better." },
      { id: "C", text: "Kai. Longer rays reach farther, so the angle is bigger." },
      { id: "D", text: "Kai. A bigger picture always has a bigger angle." },
    ],
    writtenPrompt: "Tell Kai in your own words why the long telescope and the short telescope both make a 50° angle.",
    debateHints: {
      wrongWho: "Put a protractor on both telescopes. The rays cross the scale at the same number. Does ray length change that?",
      wrongReason: "Right person, check the reason. What does an angle measure?",
      right: "Nova is right. An angle measures the turn between the rays, not how long they are.",
    },
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Count the tiny turns", machine: "Telescope Dial", icon: "dial", speaker: "nova",
    line: "The comet crossed the sky, and Telescope 11 followed it one click at a time. Each click is a one-degree angle. It clicked 150 times.",
    question: "Part 1: How many degrees did Telescope 11 turn? Part 2: What part of a full circle is one click?",
    parts: [
      { type: "number", prompt: "Telescope 11 turned through 150 one-degree angles. How many degrees is its angle?", unit: "degrees", visual: { type: "angle", degrees: 150, title: "Telescope 11" } },
      { type: "choice", prompt: "One click turns the telescope through a one-degree angle. What part of a full circle is that?", choices: [
        { id: "a", text: "1/360 of a circle" },
        { id: "b", text: "1/180 of a circle" },
        { id: "c", text: "1/100 of a circle" },
        { id: "d", text: "1/90 of a circle" },
      ] },
    ],
    hint: "The degrees of an angle are the number of one-degree angles it turns. A full circle is 360 one-degree angles.",
    meter: { supplies: 1, label: "Telescopes aimed +1", story: "Telescope 11 tracked the comet" },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 150 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "150 one-degree clicks make a 150° angle. Each click is 1/360 of a full circle!",
    wrong: [
      { step: 1, value: 30, hint: "That's the other scale. Start at 0 on the floor ray, or just count: 150 clicks of 1 degree." },
      { step: 1, value: 360, hint: "360 is a whole circle. The telescope clicked only 150 times." },
      { step: 2, choice: "b", hint: "180° is only half a circle. How many one-degree angles fit in the whole circle?" },
      { step: 2, choice: "c", hint: "Degrees don't come in hundreds. How many degrees in a full circle?" },
      { step: 2, choice: "d", hint: "90° is only a quarter of a circle. How many degrees in the whole circle?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Twin telescopes", machine: "Star Chart", icon: "trail", speaker: "kai",
    line: "Telescopes 12 and 13 are twins, but they face opposite ways. One floor ray points right, and one points left.",
    question: "Part 1: Read Telescope 12. Part 2: Read Telescope 13.",
    parts: [
      { type: "number", prompt: "Telescope 12's floor ray points right. How many degrees is the angle?", unit: "degrees", visual: { type: "angle", degrees: 155, title: "Telescope 12" } },
      { type: "number", prompt: "Telescope 13's floor ray points left. How many degrees is the angle?", unit: "degrees", visual: { type: "angle", degrees: 25, from: "left", title: "Telescope 13" } },
    ],
    hint: "Always start at the 0 that sits on the floor ray. Then check: is the angle smaller or bigger than a square corner?",
    meter: { heat: 5, label: "Comet lock +5%", story: "The twin telescopes are measured" },
    discovery: { id: "polaris", name: "The North Star", who: "Nova", fact: "Polaris, the North Star, sits almost right above Earth's North Pole. It hardly seems to move, so travelers used it to find north." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 155 },
      { kind: "number", value: 25 },
    ] },
    rightFeedback: "Telescope 12 is 155°, an obtuse angle. Telescope 13 is 25°, an acute angle!",
    wrong: [
      { step: 1, value: 25, hint: "This angle opens wider than a square corner, so it's more than 90°. Start at the 0 on the right." },
      { step: 1, value: 150, hint: "The ray is one tick past 150. Each tick is 5." },
      { step: 2, value: 155, hint: "This angle is small, less than 90°. The floor ray points left, so start at the 0 on the left." },
      { step: 2, value: 20, hint: "The ray is one tick past 20. Each tick is 5." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The horizon line", machine: "Aim Lock", icon: "grid", speaker: "nova",
    line: "The horizon is a straight line, 180°. Telescope 14 points up from the horizon and splits it into two angles that sit side by side. The angle on the left is 130°.",
    question: "How big is the angle on the right side of Telescope 14?",
    unit: "degrees",
    hint: "The two angles together make the straight horizon line, 180°. 130 + ? = 180.",
    meter: { supplies: 1, label: "Telescopes aimed +1", story: "Telescope 14 is aimed" },
    visual: { type: "angle", degrees: 130, from: "left", title: "Telescope 14 · left angle 130°" },
    answer: { kind: "number", value: 50 },
    rightFeedback: "130° + 50° = 180°. The two angles fill the straight horizon line!",
    wrong: [
      { value: 310, hint: "Don't add 180. The two angles together make 180°. Find the missing part." },
      { value: 130, hint: "130° is the left angle. The right angle is the part left over from 180°." },
      { value: 60, hint: "Check your subtraction. 180 − 130 = ?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Lock on the comet", machine: "Aim Lock", icon: "relay", speaker: "vega",
    line: "This is it! The comet is at its brightest. The main telescope's floor ray points left. It turned part of the way, and now it needs 40° more to lock on.",
    question: "Part 1: Read the main telescope. Part 2: Add the 40° turn. Part 3: What kind of angle is the final aim? Part 4: How many degrees short of a straight angle is it?",
    parts: [
      { type: "number", prompt: "The floor ray points left. How many degrees has the main telescope turned so far?", unit: "degrees", visual: { type: "angle", degrees: 75, from: "left", title: "Main telescope" } },
      { type: "number", prompt: "It turns 40° more, right next to the first angle with no overlap. What is the final angle?", unit: "degrees" },
      { type: "choice", prompt: "What kind of angle is the final aim?", choices: [
        { id: "a", text: "obtuse" },
        { id: "b", text: "acute" },
        { id: "c", text: "right" },
        { id: "d", text: "straight" },
      ] },
      { type: "number", prompt: "A straight angle is 180°. How many more degrees until the final aim would be a straight angle?", unit: "degrees" },
    ],
    hint: "Start at the 0 on the left. Add the two parts to find the whole. Then find what's left to make 180°.",
    meter: { heat: 15, label: "Comet lock +15%", story: "The comet is locked" },
    discovery: { id: "shoemaker", name: "Comet crash", who: "Kai", fact: "In 1994, pieces of Comet Shoemaker-Levy 9 crashed into Jupiter. Telescopes all over Earth watched the dark spots they left behind." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 75 },
      { kind: "number", value: 115 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 65 },
    ] },
    rightFeedback: "75° + 40° = 115°, an obtuse angle, 65° short of a straight line. The comet is locked!",
    wrong: [
      { step: 1, value: 105, hint: "That's the scale that starts on the right. The floor ray points left, so start at the 0 on the left." },
      { step: 1, value: 70, hint: "The ray is one tick past 70. Each tick is 5." },
      { step: 2, value: 35, hint: "You subtracted. The 40° turn is added right next to the first angle." },
      { step: 2, value: 145, hint: "You added 40 to 105, the wrong scale. Start with 75°." },
      { step: 3, choice: "b", hint: "Acute is less than 90°. Is 115° less than 90°?" },
      { step: 3, choice: "c", hint: "Right is exactly 90°. 115° is more than that." },
      { step: 3, choice: "d", hint: "Straight is 180°. 115° isn't that wide." },
      { step: 4, value: 295, hint: "Don't add 180. Find what goes with 115 to make 180." },
      { step: 4, value: 75, hint: "Check your subtraction. 180 − 115 = ?" },
    ],
  },
};

export default {
  id: "MA.4.7C-XP",
  standard: "MA.4.7C-XP",
  engine: "expedition_station",
  title: "The Telescope Array",
  planet: "Cloudreach",
  outpost: "Sky Reef · comet night",
  grade: 4,
  subject: "Math",
  teks: "4.7C",
  supportingTeks: ["4.7A", "4.7B", "4.7D", "4.7E"],
  skillsChip: "4.7C · Measure angles with a protractor",
  iCan: "I can measure angles in degrees with a protractor, reading the right scale. I can draw an angle, sort angles by size, and find a missing part of two angles that sit side by side.",
  blurb: "A new comet is streaking past Cloudreach! The crew has to aim every telescope on the sky reef at just the right angle before it's gone.",
  mission: "Measure and aim the sky reef's telescopes in degrees and lock onto the comet.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.73 · CLOUDREACH SKY REEF",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Comet lock", heatUnit: "%", supplies: "Telescopes aimed", suppliesUnit: "telescopes" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We're on the Sky Reef, high above the clouds of Cloudreach.",
    "A brand-new comet is passing tonight! The reef has a whole array of telescopes, and each one has to turn to exactly the right angle.",
    "Grab a protractor and help Kai and Nova measure every angle in degrees. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Wake the telescopes", "Act 2 · Aim at the comet", "Act 3 · Lock on"],
    completes: [
      "The telescopes are awake and the comet is spotted, {firstName}!",
      "The telescopes are aimed at the comet, {firstName}!",
      "The comet is locked, {firstName}! The whole reef is cheering.",
    ],
    teasers: [
      "Next on Cloudreach: Kai's log has a mistake, and a telescope motor gets stuck. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the comet is getting brighter, and Kai has a big idea about long telescopes. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. The comet is climbing higher over the clouds.",
      "Kai has been measuring angles on his own. Let's check his log before we aim.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The comet will be brightest tonight.",
      "Help the crew measure the last telescopes and lock onto the comet before it slips away.",
    ],
  }),
  tasks,
};
