// Expedition Station — The Three Reports (ELA.5.6H-XP)
// Grade 5 · ELAR · Cloudreach. Main standard 5.6H (synthesize information to
// create new understanding); also practices 5.7B (write responses that compare
// and contrast ideas across a variety of sources), 5.6G (evaluate details to
// determine key ideas), 5.7C (use text evidence), 5.9D (informational text
// features: sidebar, data table), 5.13C / 5.13E (gather relevant information
// and show understanding of it), and 5.3B (context clues). All passages are
// original, written for this quest; all storm facts are Earth-true. From the
// floating sky reef of Cloudreach, the crew watched a hurricane form over an
// Earth ocean through the reef telescope. Three very different reports came
// back, and the crew has to put them together.
import { CREW, acts, passage } from "./_shared.js";

const passages = {
  A: passage("A", { title: "How a Hurricane Is Born", genre: "Science report, by Dr. Lena Ortiz, weather scientist" }, [
    [
      "A hurricane is a giant, spinning storm that forms over warm ocean water.",
      "It needs water that is at least 80 degrees Fahrenheit.",
      "That warm water is the storm's fuel.",
    ],
    [
      "First, the sun-warmed ocean heats the air just above it, and some of the water evaporates.",
      "This warm, moist air rises, and as it rises, it cools and forms towering clouds.",
      "When the water vapor turns into cloud droplets, it gives off heat, which makes the air rise even faster.",
    ],
    [
      "As the air rises, the air pressure near the ocean surface drops, and more air rushes in to take its place.",
      "Because Earth spins, the rushing air curves, and the whole storm begins to turn.",
      "When its winds reach 74 miles per hour, the storm is called a hurricane.",
    ],
    [
      "In the center of a strong hurricane is the eye, a calm area where the sky can even be clear.",
      "Around the eye is a wall of clouds with the fastest winds.",
      "A hurricane weakens when it moves over land or cool water, because it loses its fuel.",
    ],
  ]),
  B: passage("B", { title: "Pelican Point Rides Out Hurricane Marisol", genre: "News report, from the Pelican Point Tide" }, [
    [
      "Pelican Point, Day 6.",
      "By Sam Reyes, staff reporter.",
    ],
    [
      "Three days before the storm arrived, forecasters warned that Hurricane Marisol was heading toward our town.",
      "The mayor ordered everyone living near the beach to evacuate, which means to leave for a safer place.",
      "Families boarded up windows, packed water and flashlights, and drove inland, away from the coast.",
    ],
    [
      "Marisol came ashore early on Day 5 as a Category 3 hurricane.",
      "Its worst danger was not the wind but the storm surge, a wall of seawater pushed onto land by the storm's winds.",
      "The surge flooded Shell Street with water up to five feet deep.",
    ],
    [
      "Almost no one was hurt, because nearly everyone had left in time.",
      "\"Leaving was hard, but it kept us safe,\" said Ana Brooks, who fishes from the town dock.",
      "By the next evening, Marisol had weakened to a tropical storm as it moved inland over farmland.",
    ],
  ]),
  C: passage("C", { title: "Into the Eye: A Pilot's Journal", genre: "Firsthand account, by Captain Joe Mendez, hurricane-hunter pilot" }, [
    [
      "Day 4. I have flown into hurricanes for eleven years, but today still made my hands sweat.",
      "Our job is to measure the storm from the inside, so forecasters can warn people on land.",
    ],
    [
      "As we flew toward the eyewall, rain hammered the windows, and the plane dropped and bounced.",
      "Then, all at once, we burst into sunshine.",
      "We were inside the eye, and a round wall of white clouds rose around us like a giant stadium.",
    ],
    [
      "Our crew dropped a measuring tube on a small parachute down through the storm.",
      "It radioed back that the winds near the eyewall were blowing 120 miles per hour.",
      "It also showed that the air pressure in the eye was very low, lower than on any day so far.",
    ],
    [
      "We sent our numbers to the forecasters right away.",
      "An hour later, they warned towns along the coast that Marisol was now a major hurricane.",
      "I thought about all the families who would read that warning and get to safety.",
    ],
  ]),
  D: passage("D", { title: "Sidebar: Sorting Hurricanes by Wind", genre: "Sidebar (from the science report)" }, [
    [
      "Scientists sort hurricanes into five categories using the Saffir-Simpson Hurricane Wind Scale.",
      "The scale is based only on a hurricane's strongest steady winds.",
    ],
    [
      "Category 1: 74 to 95 miles per hour.",
      "Category 2: 96 to 110 miles per hour.",
      "Category 3: 111 to 129 miles per hour.",
      "Category 4: 130 to 156 miles per hour.",
      "Category 5: 157 miles per hour or more.",
    ],
    [
      "Hurricanes in Category 3, 4, or 5 are called major hurricanes.",
      "The scale does not measure rain or storm surge, which can also be very dangerous.",
    ],
  ]),
};

const STORM_TABLE = {
  title: "Reef Telescope Log: Hurricane Marisol",
  columns: ["Day", "Strongest winds", "Air pressure in the center", "Where the storm was"],
  rows: [
    ["Day 1", "35 mph", "1008 millibars", "Far out over warm ocean water"],
    ["Day 2", "60 mph", "996 millibars", "Over the ocean, getting closer"],
    ["Day 3", "90 mph", "975 millibars", "Over the ocean"],
    ["Day 4", "120 mph", "950 millibars", "Over the ocean, near the coast"],
    ["Day 5", "115 mph", "955 millibars", "Came ashore at Pelican Point"],
    ["Day 6", "45 mph", "990 millibars", "Over farmland, far inland"],
  ],
};

const SOURCE_CHOICES = [
  { id: "a", text: "Passage A: the scientist's report" },
  { id: "b", text: "Passage B: the news report" },
  { id: "c", text: "Passage C: the pilot's journal" },
  { id: "d", text: "Passage D: the sidebar" },
];

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Three reports, one storm", machine: "Report Sorter", icon: "cells", speaker: "vega",
    passage: ["A", "B", "C"],
    line: "Three reports just floated up to the telescope deck. They all came from Earth, and they all watched the same storm.",
    question: "What do all three reports have in common?",
    hint: "Read the title of each report. What is each one about? Then think about who wrote it.",
    meter: { heat: 5, label: "Storm Book +5%", story: "The three reports are pinned side by side" },
    discovery: { id: "stormnames", name: "One storm, three names", who: "Nova", fact: "Hurricanes, typhoons, and cyclones are the same kind of storm. The name changes depending on which ocean the storm forms over." },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "They were all written by weather scientists." },
      { id: "b", text: "They are all about hurricanes like Marisol, but each one is written from a different point of view." },
      { id: "c", text: "They all tell what happened on Shell Street." },
      { id: "d", text: "They all describe flying a plane into the storm." },
    ],
    rightFeedback: "Right! Same storm, three writers: a scientist, a reporter, and a pilot. Each one saw it a different way.",
    wrong: [
      { choice: "a", hint: "Check who wrote each one. Is a news reporter a scientist? Is a pilot?" },
      { choice: "c", hint: "Only the news report mentions Shell Street. What do ALL three share?" },
      { choice: "d", hint: "Only the pilot flew into the storm. What do all three reports have in common?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "What feeds the storm?", machine: "Key Idea Lens", icon: "scan", speaker: "nova",
    passage: ["A"],
    line: "Dr. Ortiz's report is packed with details. Before we combine anything, I want the key idea about what a hurricane needs.",
    question: "Highlight the sentence in Passage A that tells what gives a hurricane its fuel.",
    hint: "Look for the word \"fuel.\" Which sentence names what powers the storm?",
    meter: { supplies: 1, label: "Report pins +1", story: "Nova pins the fuel idea" },
    discovery: { id: "spindirection", name: "Which way they spin", who: "Nova", fact: "Hurricanes north of the equator spin counterclockwise. Hurricanes south of the equator spin clockwise." },
    answer: { kind: "highlight", groups: [["A1.3"]] },
    rightFeedback: "Got it! Warm ocean water is the fuel. That key idea will help us explain a lot later.",
    wrong: [
      { sentence: "A1.1", hint: "That tells what a hurricane IS. Which sentence tells what its fuel is?" },
      { sentence: "A1.2", hint: "That tells how warm the water must be. Which sentence says the warm water is the storm's fuel?" },
      { sentence: "A3.3", hint: "That tells when a storm gets called a hurricane. Which sentence names its fuel?" },
      { sentence: "A4.3", hint: "That uses the word fuel, but it tells how a hurricane weakens. Which sentence says what the fuel IS?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Which way is inland?", machine: "Word Scope", icon: "static", speaker: "kai",
    passage: ["B"],
    line: "The news report says families \"drove inland.\" I thought that meant they drove into the water. That seems like a bad idea.",
    question: "In Passage B, what does the word \"inland\" mean?",
    hint: "Read the whole sentence. The words right after \"inland\" give you a clue.",
    meter: { heat: 5, label: "Storm Book +5%", story: "Kai learns which way is safe" },
    discovery: { id: "season", name: "Hurricane season", who: "Kai", fact: "In the Atlantic Ocean, hurricane season runs from June 1 to November 30. Most hurricanes happen in August, September, and October." },
    answer: { kind: "choice", correct: "c" },
    choices: [
      { id: "a", text: "Into the ocean" },
      { id: "b", text: "Along the beach" },
      { id: "c", text: "Away from the coast, farther into the land" },
      { id: "d", text: "Up to the top floor of a building" },
    ],
    rightFeedback: "Right! The clue \"away from the coast\" tells you. Inland means farther from the ocean, where the surge can't reach.",
    wrong: [
      { choice: "a", hint: "The families were trying to get safe from seawater. Would they drive into it? Read the words after \"inland.\"" },
      { choice: "b", hint: "The beach is where the danger was. The sentence says \"away from the coast.\" What does that tell you?" },
      { choice: "d", hint: "The families DROVE inland. What clue in the sentence tells which direction they went?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Only the pilot knows", machine: "Source Scanner", icon: "crew", speaker: "vega",
    passage: ["A", "B", "C"],
    line: "Every source adds something the others don't. Let's start with Captain Mendez's journal.",
    question: "What does the pilot's journal (Passage C) add that the other two reports do NOT?",
    hint: "The scientist explains. The reporter tells what happened in town. What could only someone INSIDE the storm tell us?",
    meter: { supplies: 1, label: "Report pins +1", story: "The pilot's journal gets its own pin" },
    discovery: { id: "firstflight", name: "The first flight into a hurricane", who: "Kai", fact: "In 1943, a pilot named Joseph Duckworth flew a small plane into a hurricane on a dare. He was the first person known to fly into a hurricane on purpose." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "A firsthand view from inside the eye, plus wind and pressure measured on Day 4" },
      { id: "b", text: "An explanation of why warm ocean water is the storm's fuel" },
      { id: "c", text: "How families in Pelican Point got ready to leave" },
      { id: "d", text: "The wind speeds for all five hurricane categories" },
    ],
    rightFeedback: "Right! Only the pilot was inside the storm. He tells what the eye looked like and what his crew measured.",
    wrong: [
      { choice: "b", hint: "That comes from the scientist's report, Passage A. What does ONLY the pilot give us?" },
      { choice: "c", hint: "That comes from the news report, Passage B. What did the pilot see and measure that no one else did?" },
      { choice: "d", hint: "Those come from the sidebar. What firsthand details does the pilot's journal add?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The storm fades on screen", machine: "Telescope Link", icon: "snap", speaker: "nova",
    passage: ["A", "B", "C", "D"],
    line: "Surprise! The telescope just showed Marisol's clouds falling apart over the land. The reef kids are asking why. Let's answer with two sources at once.",
    question: "Part 1: Which TWO sources both say a hurricane weakens once it moves over land? Part 2: Highlight one sentence from each of those sources. Part 3: Put them together. Why did Marisol weaken on Day 6?",
    parts: [
      { type: "multi", prompt: "Pick the TWO sources that both tell about a hurricane weakening over land.", choices: SOURCE_CHOICES },
      { type: "highlight", prompt: "Highlight one sentence from Passage A and one from Passage B that show the storm weakening over land.", passage: ["A", "B"], count: 2 },
      { type: "choice", prompt: "Combine the two sources. Why did Marisol weaken on Day 6?", choices: [
        { id: "a", text: "It moved inland over farmland, far from the warm ocean water that fuels it, so it lost its fuel." },
        { id: "b", text: "The people of Pelican Point boarded up their windows." },
        { id: "c", text: "The pilot's plane flew through it and broke it apart." },
        { id: "d", text: "It turned into a Category 5 hurricane." },
      ] },
    ],
    hint: "The scientist tells WHY hurricanes weaken. The reporter tells WHERE Marisol went. Put the why and the where together.",
    meter: { heat: 10, label: "Storm Book +10%", story: "The reef kids get their answer" },
    discovery: { id: "saffirsimpson", name: "Who made the scale", who: "Nova", fact: "The hurricane wind scale is named after engineer Herbert Saffir and weather scientist Robert Simpson. They made it in the early 1970s." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["a", "b"] },
      { kind: "highlight", groups: [["A4.3"], ["B4.3"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Nice synthesis! The scientist says land cuts off the fuel. The reporter says Marisol moved over farmland. Together they explain Day 6.",
    wrong: [
      { step: 1, pick: "c", hint: "The pilot flew on Day 4, while the storm was still over the ocean. Which sources talk about land?" },
      { step: 1, pick: "d", hint: "The sidebar sorts storms by wind. Does it say anything about land?" },
      { step: 1, missing: true, hint: "Pick two. One source explains why storms weaken. The other tells where Marisol went." },
      { step: 2, sentence: "A1.3", hint: "That tells what the fuel is. Which sentence in A tells what happens over land?" },
      { step: 2, sentence: "B3.1", hint: "That tells when Marisol came ashore. Which sentence in B says it weakened?" },
      { step: 2, sentence: "B2.3", hint: "That's the families driving inland. Which sentence tells about the STORM moving inland?" },
      { step: 3, choice: "b", hint: "Boarding windows protects homes, but can it weaken a storm? What does Passage A say weakens a hurricane?" },
      { step: 3, choice: "c", hint: "The plane measured the storm. It couldn't break it. What does Passage A say about land?" },
      { step: 3, choice: "d", hint: "Passage B says Marisol became a tropical storm. Is that stronger or weaker?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Just one report?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    passage: ["A", "B", "C"],
    line: 'Kai: "Dr. Ortiz\'s report has the most facts. She\'s the scientist! Let\'s just use her report and skip the other two."',
    nova: 'Nova: "Her report explains how hurricanes form, but it never tells what happened to Pelican Point or what the pilot measured inside Marisol."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Think about what each source tells that the others leave out. Could one report answer every question?",
    meter: { supplies: 1, label: "Report pins +1", story: "The crew keeps all three reports" },
    discovery: { id: "surge", name: "Moving water", who: "Nova", fact: "Storm surge is often the most dangerous part of a hurricane. Just 6 inches of fast-moving water can knock a grown-up off their feet." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Each report adds something the others don't. The scientist explains how hurricanes form, the reporter tells what happened to the town, and the pilot measured the storm from inside. Together they give the whole picture." },
      { id: "B", text: "Nova, because the news report is the longest." },
      { id: "C", text: "Kai. A scientist always knows everything, so the other reports aren't needed." },
      { id: "D", text: "Kai. Using more than one source is just confusing." },
    ],
    writtenPrompt: "Tell Kai in your own words why the crew needs more than one report.",
    debateHints: {
      wrongWho: "Does Dr. Ortiz's report tell about Shell Street or the pilot's measurements? What would we miss?",
      wrongReason: "Right person, check the reason. Why does each report matter?",
      right: "Nova is right. Each source fills in a piece the others leave out.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Three points of view", machine: "Sort Bay", icon: "cells", speaker: "nova",
    passage: ["A", "B", "C"],
    line: "Each writer sees the storm from a different spot. A scientist explains. A reporter tells about people. A pilot tells what he lived through.",
    question: "Sort each statement by the source it comes from.",
    hint: "Ask: Is it explaining how storms work? Is it about the town and its people? Or is it what the pilot saw and measured himself?",
    meter: { heat: 10, label: "Storm Book +10%", story: "The points of view are sorted" },
    answer: { kind: "sort", bins: { s1: "A", s2: "B", s3: "C", s4: "A", s5: "B", s6: "C" } },
    rightFeedback: "Sorted! The scientist explains, the reporter covers the town, and the pilot tells his own story from inside the storm.",
    sort: {
      bins: [
        { id: "A", label: "Scientist (A)" },
        { id: "B", label: "News report (B)" },
        { id: "C", label: "Pilot (C)" },
      ],
      items: [
        { id: "s1", label: "Explains why warm water is the storm's fuel" },
        { id: "s2", label: "Tells how families got ready and left their homes" },
        { id: "s3", label: "Describes the plane bouncing through heavy rain" },
        { id: "s4", label: "Explains how Earth's spin makes the storm turn" },
        { id: "s5", label: "Quotes a person who lives in the town" },
        { id: "s6", label: "Tells what the measuring tube found" },
      ],
    },
    wrong: [
      { item: "s1", hint: "Which writer explains how hurricanes work in general?" },
      { item: "s2", hint: "Which writer covered what happened to the people of Pelican Point?" },
      { item: "s3", hint: "Who was riding in the plane and felt it bounce?" },
      { item: "s4", hint: "Earth's spin is a science explanation. Which writer gives those?" },
      { item: "s5", hint: "Ana Brooks is quoted by a reporter. Which source is that?" },
      { item: "s6", hint: "Whose crew dropped the measuring tube?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Read the telescope log", machine: "Chart Reader", icon: "grid", speaker: "vega",
    passage: ["C", "D"],
    line: "Our telescope logged Marisol every day. Let's line up the numbers with the pilot's journal and the sidebar.",
    question: "Part 1: Use the table. What happened to the air pressure as the winds got stronger? Part 2: Which day in the table matches the pilot's flight? Part 3: Use the table and the sidebar. What category was Marisol on Day 3?",
    data: STORM_TABLE,
    parts: [
      { type: "choice", prompt: "What happened to the air pressure as the winds got stronger?", choices: [
        { id: "a", text: "It went up." },
        { id: "b", text: "It went down." },
        { id: "c", text: "It stayed the same." },
        { id: "d", text: "The table doesn't show air pressure." },
      ] },
      { type: "choice", prompt: "The pilot measured 120 mph winds and the lowest pressure so far. Which day matches?", choices: [
        { id: "a", text: "Day 2" },
        { id: "b", text: "Day 3" },
        { id: "c", text: "Day 4" },
        { id: "d", text: "Day 5" },
      ] },
      { type: "choice", prompt: "What category was Marisol on Day 3?", choices: [
        { id: "a", text: "Category 1" },
        { id: "b", text: "Category 2" },
        { id: "c", text: "Category 3" },
        { id: "d", text: "It was not a hurricane yet." },
      ] },
    ],
    hint: "Read down the wind and pressure columns together. Then match the Day 3 wind speed to a range in the sidebar.",
    meter: { supplies: 1, label: "Report pins +1", story: "The log is pinned next to the reports" },
    discovery: { id: "barometer", name: "Barometers", who: "Kai", fact: "A barometer measures air pressure. When the air pressure falls quickly, a storm is often on its way." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "choice", correct: "c" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! Stronger winds came with lower pressure. Day 4 matches the pilot, and 90 mph on Day 3 was Category 1.",
    wrong: [
      { step: 1, choice: "a", hint: "Look at Days 1 to 4. The wind goes 35, 60, 90, 120. Do the pressure numbers go up or down?" },
      { step: 1, choice: "c", hint: "Compare 1008 on Day 1 with 950 on Day 4. Did it stay the same?" },
      { step: 1, choice: "d", hint: "Look at the third column of the table. What does it measure?" },
      { step: 2, choice: "a", hint: "Day 2 winds were 60 mph. Find the row with 120 mph." },
      { step: 2, choice: "b", hint: "Day 3 winds were 90 mph. Find the row with 120 mph and the lowest pressure." },
      { step: 2, choice: "d", hint: "Day 5 is when Marisol came ashore. The pilot's journal says \"Day 4.\" Check the 120 mph row." },
      { step: 3, choice: "b", hint: "Category 2 starts at 96 mph. Day 3 was 90 mph. Which range does 90 fit in?" },
      { step: 3, choice: "c", hint: "Category 3 is 111 to 129 mph. That fits Day 4, not Day 3. Where does 90 mph fit?" },
      { step: 3, choice: "d", hint: "Passage A says a storm is a hurricane at 74 mph. Is 90 mph above that?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Why was the surge so big?", machine: "Evidence Weaver", icon: "log", speaker: "kai",
    passage: ["B", "C"],
    line: "The news report says the surge flooded Shell Street five feet deep. But WHY was it so big? Neither report says it all by itself.",
    question: "Part 1: Highlight one sentence from the news report and one from the pilot's journal that TOGETHER explain the huge storm surge. Part 2: What new idea do they show together?",
    parts: [
      { type: "highlight", prompt: "Highlight one sentence from Passage B and one from Passage C that together explain the big surge.", passage: ["B", "C"], count: 2 },
      { type: "choice", prompt: "What do the two sentences show together?", choices: [
        { id: "a", text: "Marisol's winds were very fast, and fast winds push seawater onto land, so the surge was huge." },
        { id: "b", text: "The surge happened because families left their homes." },
        { id: "c", text: "The eye of the storm was full of sunshine." },
        { id: "d", text: "Storm surge is caused by heavy rain falling on the town." },
      ] },
    ],
    hint: "Find where the reporter tells what CAUSES a storm surge. Then find where the pilot tells how strong the winds were.",
    meter: { heat: 10, label: "Storm Book +10%", story: "Kai links the wind to the water" },
    answer: { kind: "parts", parts: [
      { kind: "highlight", groups: [["B3.2"], ["C3.2", "C4.2"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Woven together! The reporter says wind pushes the surge. The pilot measured 120 mph winds. Put them together, and you see why the surge was so big.",
    wrong: [
      { step: 1, sentence: "B3.3", hint: "That shows HOW big the surge was. Which sentence in B tells what causes a surge?" },
      { step: 1, sentence: "B3.1", hint: "That tells when Marisol came ashore. Which sentence explains what a storm surge is?" },
      { step: 1, sentence: "C2.2", hint: "Bursting into sunshine is about the eye. Which sentence in C tells how fast the winds were?" },
      { step: 1, sentence: "C2.1", hint: "The rain and bouncing were bumpy, but which sentence gives the wind speed?" },
      { step: 2, choice: "b", hint: "Leaving kept families safe. It didn't cause the surge. What pushes the seawater?" },
      { step: 2, choice: "c", hint: "That's true, but does it explain the surge? Think about wind and water." },
      { step: 2, choice: "d", hint: "Passage B says the surge is seawater pushed by the winds. Is that rain?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Sky Radio calls in", machine: "Broadcast Link", icon: "quake", speaker: "vega",
    passage: ["A", "B", "C", "D"],
    line: "Surprise! Cloudreach Sky Radio is on the line, live. Their question: \"How did an airplane help keep a whole town safe?\" No single report answers that.",
    question: "Part 1: Pick the TWO sources you need to answer the radio's question. Part 2: Highlight one sentence from each that helps answer it. Part 3: Pick the best combined answer.",
    parts: [
      { type: "multi", prompt: "Pick the TWO sources you need to answer the question.", choices: SOURCE_CHOICES },
      { type: "highlight", prompt: "Highlight one sentence from the pilot's journal (C) and one from the news report (B) that help answer the question.", passage: ["C", "B"], count: 2 },
      { type: "choice", prompt: "Which answer puts the two sources together best?", choices: [
        { id: "a", text: "The plane measured Marisol from inside, forecasters used the numbers to warn the coast, and because people in Pelican Point left in time, almost no one was hurt." },
        { id: "b", text: "The plane flew into the eye and saw a wall of white clouds." },
        { id: "c", text: "Almost no one was hurt in Pelican Point." },
        { id: "d", text: "The plane blew the storm away from the town." },
      ] },
    ],
    hint: "One source tells what the plane's crew did with its numbers. The other tells what the town did and how it turned out.",
    meter: { heat: 10, label: "Storm Book +10%", story: "Sky Radio plays the crew's answer" },
    discovery: { id: "dropsonde", name: "Dropsondes", who: "Nova", fact: "The measuring tubes hurricane hunters drop are called dropsondes. As a dropsonde falls on its parachute, it sends back wind, temperature, and air pressure readings the whole way down." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["b", "c"] },
      { kind: "highlight", groups: [["C1.2", "C4.1", "C4.2"], ["B4.1", "B2.1", "B2.2"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "On the air! The pilot's numbers led to warnings, and the town's report shows the warnings worked.",
    wrong: [
      { step: 1, pick: "a", hint: "The scientist explains how hurricanes form, but not what the plane did. Which sources tell about the plane and the town?" },
      { step: 1, pick: "d", hint: "The sidebar sorts storms by wind. Does it tell about the plane or the town?" },
      { step: 1, missing: true, hint: "Pick two: the source about the plane and the source about the town." },
      { step: 2, sentence: "C2.3", hint: "That describes the eye. Which sentence tells how the crew's work helped people on land?" },
      { step: 2, sentence: "C3.1", hint: "That's how they measured. Which sentence tells what happened with the numbers?" },
      { step: 2, sentence: "B3.3", hint: "That's the flooding. Which sentence in B shows people were kept safe?" },
      { step: 2, sentence: "B4.3", hint: "That's the storm weakening. Which sentence in B shows the warnings worked?" },
      { step: 3, choice: "b", hint: "That's only from the pilot's journal. Where does the town come in?" },
      { step: 3, choice: "c", hint: "That's only from the news report. How did the plane help?" },
      { step: 3, choice: "d", hint: "No plane can blow away a hurricane. What did the plane's crew send to forecasters?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "A major question", machine: "Fact Fuser", icon: "brief", speaker: "nova",
    passage: ["B", "D"],
    line: "Here's a new question none of the reports answers straight out: Was Marisol a MAJOR hurricane when it hit Pelican Point?",
    question: "Combine Passage B and the sidebar. Was Marisol a major hurricane when it came ashore?",
    hint: "Find Marisol's category in the news report. Then check which categories the sidebar calls major.",
    meter: { supplies: 1, label: "Report pins +1", story: "Nova fuses two facts into one answer" },
    discovery: { id: "naming", name: "Storm names", who: "Nova", fact: "A storm gets a name when its winds reach 39 miles per hour. The name lists are reused every six years, but the names of very harmful hurricanes are retired for good." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Yes. The news report says it was Category 3, and the sidebar says Categories 3, 4, and 5 are major hurricanes." },
      { id: "b", text: "No. Only Category 5 hurricanes are major." },
      { id: "c", text: "Yes, because it flooded Shell Street." },
      { id: "d", text: "We can't tell. None of the sources gives its category." },
    ],
    rightFeedback: "Right! One fact from each source, and together they answer a question neither answers alone.",
    wrong: [
      { choice: "b", hint: "Reread paragraph 3 of the sidebar. Which categories count as major?" },
      { choice: "c", hint: "Flooding was serious, but the sidebar says the scale doesn't measure surge. What category was Marisol?" },
      { choice: "d", hint: "Check paragraph 3 of the news report. It names Marisol's category." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's copy-paste", machine: "Repair Bench", icon: "log", speaker: "kai",
    passage: ["A", "B", "C"],
    line: "I wrote our synthesis for the Storm Book! Here it is: \"Marisol came ashore early on Day 5 as a Category 3 hurricane.\" Done, right?",
    question: "Part 1: What went wrong with Kai's synthesis? Part 2: Pick the best fix.",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's synthesis?", choices: [
        { id: "a", text: "He copied one sentence from one source. He didn't combine sources or add any new understanding." },
        { id: "b", text: "The sentence is too short. A synthesis just needs more words." },
        { id: "c", text: "The fact is wrong. Marisol was a Category 5." },
        { id: "d", text: "He should have copied from the scientist's report instead." },
      ] },
      { type: "choice", prompt: "Which is the best fix?", choices: [
        { id: "a", text: "Marisol hit Pelican Point as a major hurricane, but because the pilot's measurements led to early warnings, nearly everyone left in time and stayed safe." },
        { id: "b", text: "A hurricane is a giant, spinning storm that forms over warm ocean water." },
        { id: "c", text: "Marisol came ashore early on Day 5 as a Category 3 hurricane, and it was very big and very scary." },
        { id: "d", text: "I think hurricanes are the coolest storms ever." },
      ] },
    ],
    hint: "A synthesis puts ideas from two or more sources together to say something new, in your own words.",
    meter: { heat: 10, label: "Storm Book +10%", story: "Kai's page gets a real synthesis" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Fixed! The new sentence joins the news report, the sidebar, and the pilot's journal into one new idea.",
    wrong: [
      { step: 1, choice: "b", hint: "Length isn't the problem. Where did Kai's sentence come from? Compare it with Passage B." },
      { step: 1, choice: "c", hint: "Passage B really does say Category 3. The fact is fine. What is Kai missing?" },
      { step: 1, choice: "d", hint: "Copying from any one source is still copying. What does a synthesis need to do?" },
      { step: 2, choice: "b", hint: "That's copied word for word from Passage A. Which fix combines sources in new words?" },
      { step: 2, choice: "c", hint: "That's still Kai's copied sentence with extra words tacked on. Which fix joins ideas from different sources?" },
      { step: 2, choice: "d", hint: "That's an opinion, not information from the sources. Which fix combines facts from two sources?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Where they agree", machine: "Match Finder", icon: "grid", speaker: "vega",
    passage: ["C"],
    line: "When two sources agree, we can trust a fact even more. Let's check the pilot's journal against our telescope log.",
    question: "Pick every fact that BOTH the pilot's journal and the telescope log show.",
    data: STORM_TABLE,
    hint: "A fact counts only if you can find it in the journal AND in the table.",
    meter: { supplies: 1, label: "Report pins +1", story: "The matching facts get a double pin" },
    discovery: { id: "satellites", name: "Eyes in space", who: "Kai", fact: "Weather satellites watch Earth's oceans from space all day and all night. They help forecasters spot new storms far out at sea." },
    answer: { kind: "multi", correct: ["a", "b"] },
    items: [
      { id: "a", text: "On Day 4, Marisol's winds were 120 miles per hour." },
      { id: "b", text: "On Day 4, the air pressure was the lowest it had been so far." },
      { id: "c", text: "The surge flooded Shell Street five feet deep." },
      { id: "d", text: "On Day 6, Marisol was over farmland." },
      { id: "e", text: "Hurricanes need water that is at least 80 degrees Fahrenheit." },
    ],
    rightFeedback: "Right! The journal and the table both show 120 mph and the lowest pressure yet on Day 4.",
    wrong: [
      { pick: "c", hint: "Shell Street is only in the news report. Is it in the journal or the table?" },
      { pick: "d", hint: "The table shows that, but the pilot's journal stops on Day 4. Does it need BOTH?" },
      { pick: "e", hint: "That's from the scientist's report. Is it in the journal or the table?" },
      { missing: true, hint: "There are two. Compare paragraph 3 of the journal with the Day 4 row." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Scientist versus pilot", machine: "Compare Deck", icon: "brief", speaker: "nova",
    passage: ["A", "C"],
    line: "Dr. Ortiz and Captain Mendez both wrote about the eye of a hurricane. But they wrote about it in very different ways.",
    question: "How is the pilot's description of the eye different from the scientist's? Write 1–2 sentences. Use a detail from each source.",
    hint: "The scientist explains what an eye is. What does the pilot tell that he saw and felt himself?",
    meter: { heat: 10, label: "Storm Book +10%", story: "Nova adds a compare-and-contrast page" },
    answer: { kind: "write", minWords: 15 },
    minWords: 15,
    teacherScored: true,
    rubric: ["Tells a clear difference between the two descriptions", "Uses a detail from Passage A and a detail from Passage C", "Complete sentences with capitals and end punctuation"],
    rightFeedback: "Thanks! Your teacher will read your answer.",
    wrong: [],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The reef's own Storm Book", machine: "Transmit", icon: "relay", speaker: "vega",
    passage: ["A", "B", "C", "D"],
    line: "Surprise! Cloudreach's storm watchers want a page for the reef's Storm Book. They don't want copied facts. They want NEW understanding built from our reports.",
    question: "Part 1: Which statement shows new understanding built from more than one source? Part 2: Write 2–3 sentences of your own new understanding. Use at least two sources.",
    data: STORM_TABLE,
    parts: [
      { type: "choice", prompt: "Which statement shows new understanding built from more than one source?", choices: [
        { id: "a", text: "Warm ocean water fuels a hurricane, so when Marisol left the ocean for farmland, it lost its fuel and dropped from 115 mph to 45 mph." },
        { id: "b", text: "The surge flooded Shell Street with water up to five feet deep." },
        { id: "c", text: "Category 4 is 130 to 156 miles per hour." },
        { id: "d", text: "Hurricanes are scary, and nobody should ever live near a beach." },
      ] },
      { type: "write", prompt: "Write 2–3 sentences of new understanding about Hurricane Marisol. Name at least two sources and tell what each one adds.", minWords: 20 },
    ],
    teacherScoredPart: 2,
    rubric: ["States a new idea that no single source says alone", "Uses information from at least two sources (or a source and the table)", "Complete sentences in the writer's own words"],
    hint: "Pick an idea from one source and a fact from another. Ask: what do they show TOGETHER that neither shows alone?",
    meter: { heat: 15, label: "Storm Book +15%", story: "Your page opens the reef's Storm Book" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Page sent! Your teacher will read your new understanding.",
    wrong: [
      { step: 1, choice: "b", hint: "That's copied from the news report. It's one source. Which statement joins two sources?" },
      { step: 1, choice: "c", hint: "That's straight from the sidebar. Which statement combines ideas into something new?" },
      { step: 1, choice: "d", hint: "That's an opinion, and the sources don't say it. Which statement combines facts from the sources?" },
    ],
  },
};

export default {
  id: "ELA.5.6H-XP",
  standard: "ELA.5.6H-XP",
  engine: "expedition_station",
  title: "The Three Reports",
  planet: "Cloudreach",
  outpost: "Sky Reef Telescope Deck · storm watch",
  grade: 5,
  subject: "ELAR",
  teks: "5.6H",
  supportingTeks: ["5.7B", "5.6G", "5.7C", "5.9D", "5.13C", "5.13E", "5.3B"],
  skillsChip: "5.6H · Synthesize information to create new understanding",
  iCan: "I can put together information from different sources to understand something new, and explain it in my own words.",
  blurb: "From the floating sky reef of Cloudreach, the crew watched a hurricane grow over an Earth ocean. A scientist, a reporter, and a pilot each sent a report, and each one tells a different part of the story.",
  mission: "Find what each report adds, spot where they agree, and put them together to explain things no single report can explain alone.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.6H · CLOUDREACH TELESCOPE DECK",
  playableActs: [1, 2, 3],
  meterStart: { heat: 20, supplies: 0, journal: 0 },
  meterLabels: { heat: "Storm Book", heatUnit: "%", supplies: "Report pins", suppliesUnit: "pins" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega on the Cloudreach sky reef. Our big telescope just tracked a hurricane across an ocean on Earth.",
    "Three reports came back about the storm. A scientist, a news reporter, and a pilot each tell a different part of the story.",
    "Help us put the pieces together for the reef's Storm Book. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Three reports arrive", "Act 2 · Weaving the evidence", "Act 3 · The Storm Book"],
    completes: [
      "Nice work, {firstName}! You found what each report adds and joined two of them for the first time.",
      "Great weaving, {firstName}! You used the log, the reports, and the sidebar together to explain the storm.",
      "Your page is in the Storm Book, {firstName}! The reef understands Marisol better than any one report could explain.",
    ],
    teasers: [
      "Next on Cloudreach: the telescope log comes in, and the crew argues about which report to keep. Act 2 is open now, or come back to it next time.",
      "Next on Cloudreach: the reef's storm watchers want a page of new understanding. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Our telescope log is ready, and Kai wants to throw out two of the reports.",
      "Let's weave the evidence together instead.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The Storm Book is open, and the reef is waiting.",
      "Help us turn three reports into brand-new understanding.",
    ],
  }),
  tasks,
};
