// Expedition Station — The Trader's Pitch (ELA.3.9E-XP)
// Grade 3 · ELAR · Mechara. Main standard 3.9E (argumentative text: identify
// the claim, tell facts from opinions, identify the intended audience); also
// practices 3.10A (author's purpose and message), 3.6F (inference), 3.7C (text
// evidence), 3.3B (context clues), 3.11D (edit), and 3.12C (compose an opinion).
// All passages are original, written for this quest. Robot-city traders pitch
// gadgets to the crew, and the crew learns to check what a pitch really says.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Ad: Meet the Super Scrub!", genre: "Advertisement" }, [
    [
      "Is your workshop covered in oil, dust, and bolt crumbs?",
      "The Super Scrub is the best cleaning bot in all of Mechara!",
      "Every home needs one.",
    ],
    [
      "The Super Scrub has six soft brushes and one strong vacuum.",
      "Its battery lasts four hours on one charge.",
      "It rolls up stairs on rubber tracks.",
      "Its metal shell is sturdy, so it will not dent or crack when it bumps into a wall.",
    ],
    [
      "It is the cutest robot you will ever see.",
      "Your friends will be so jealous!",
      "Cleaning with the Super Scrub is more fun than a party.",
    ],
    [
      "Visit Bolt's Bot Shop on Gear Street today!",
      "Trade two crates of copper bolts, and a Super Scrub is yours.",
    ],
  ]),
  B: passage("B", { title: "A Letter from Pip Sprocket", genre: "Letter" }, [
    ["Dear Commander Vega,"],
    [
      "My name is Pip Sprocket, and I am a trader in Mechara.",
      "I would like to trade my star charts for three tanks of your fresh water.",
      "Your ship will need good charts to fly safely past the Rust Rings.",
    ],
    [
      "My charts are accurate.",
      "They show all 12 moons of this planet in exactly the right places.",
      "A robot mapmaker drew them just last month.",
    ],
    [
      "I have heard that your crew is brave and fair.",
      "I think this is the best trade you will get all year.",
    ],
    [
      "Please radio me your answer before your ship leaves on Friday.",
      "Your friend, Pip Sprocket",
    ],
  ]),
  C: passage("C", { title: "Poster: The Robot Fair", genre: "Poster" }, [
    ["Hey, kids! Do you love robots?", "Then come to the Mechara Robot Fair!"],
    [
      "Build your own tiny robot in the Maker Tent.",
      "Race wind-up robot mice on the Twisty Track.",
      "Every kid gets a free glow sticker at the gate.",
    ],
    [
      "The fair is on Saturday from 9:00 in the morning to 4:00 in the afternoon.",
      "It is in Cog Park, next to the big clock tower.",
    ],
    ["It will be the best day of your whole life!", "Bring a grown-up and a friend!"],
  ]),
  D: passage("D", { title: "Kai's Proposal: The Zip Wrench", genre: "Proposal" }, [
    ["Commander Vega, I think our crew should trade for a Zip Wrench at the robot market."],
    [
      "Yesterday I tested one at the trader's stall.",
      "The Zip Wrench tightened ten bolts in one minute.",
      "My old hand wrench tightened only two bolts in one minute.",
    ],
    [
      "The Zip Wrench is the coolest tool in the galaxy, and everyone knows it.",
      "It weighs less than one of my boots.",
    ],
    ["The trader will take one box of our extra space crackers for it.", "Please say yes!"],
  ]),
  E: passage("E", { title: "Nova's Robot Review", genre: "Review" }, [
    [
      "Kai wanted a Super Scrub, so I tested one next to another cleaning bot, the Dust Buddy.",
      "I used a timer and a measuring cup for every test.",
    ],
    [
      "The Super Scrub cleaned our supply room in 20 minutes.",
      "The Dust Buddy took 35 minutes to clean the same room.",
      "Both robots picked up about two cups of dust.",
    ],
    [
      "The ad said the Super Scrub's battery lasts four hours.",
      "In my test, it lasted only two hours.",
      "The Dust Buddy's battery lasted five hours.",
    ],
    [
      "In my opinion, the Dust Buddy is the better robot for our ship.",
      "It is slower, but it can clean every room on one charge.",
      "My advice is simple: test what an ad says before you believe it.",
    ],
  ]),
  F: {
    id: "F",
    title: "Kai's new proposal (has mistakes)",
    genre: "Proposal (has mistakes)",
    ...editText(
      "F",
      "Commander Vega, our crew should trade for a Zip Wrench. {i} tested one at the robot market. It tightened ten bolts in one minute. My old wrench tightened only two. It {wayes} less than my boot. The trader wants one box of space crackers. We can visit the market on {friday}.",
      {
        i: ["I", "eye"],
        wayes: ["weighs", "ways"],
        friday: ["Friday", "fridays"],
      }
    ),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Spot the big claim", machine: "Claim Finder", icon: "scan", speaker: "vega", passage: ["A"],
    line: "A trader stuck this ad on our ship's door. Every pitch has a claim, the big idea the writer wants you to believe. Let's find it.",
    question: "Read Passage A. Highlight the sentence that tells the ad's claim.",
    hint: "A claim is what the writer wants you to believe. What does the ad want you to think about the Super Scrub?",
    meter: { heat: 10, label: "Deal meter +10%", story: "The claim finder beeps" },
    discovery: { id: "davinci", name: "A robot knight", who: "Kai", fact: "Around 1495, the artist Leonardo da Vinci drew plans for a robot knight. Ropes and pulleys inside it could make it sit up and move its arms." },
    answer: { kind: "highlight", groups: [["A1.2", "A1.3"]] },
    rightFeedback: "Got it! The ad wants you to believe the Super Scrub is the best cleaning bot, and that you need one.",
    wrong: [
      { sentence: "A1.1", hint: "That is a question to get your attention. Which sentence tells what the ad wants you to believe?" },
      { sentence: "A2.1", hint: "That tells what the robot has. It helps the claim. Which sentence IS the big claim?" },
      { sentence: "A4.1", hint: "That tells you where to go. Which sentence says what the ad thinks of the Super Scrub?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Tough as bolts", machine: "Word Decoder", icon: "static", speaker: "kai", passage: ["A"],
    line: "The ad says the shell is sturdy. I build robots, and I still want to be sure what that means!",
    question: "\"Its metal shell is sturdy, so it will not dent or crack when it bumps into a wall.\" What does sturdy mean?",
    hint: "Read the rest of the sentence. What happens when a sturdy shell bumps into a wall?",
    meter: { supplies: 1, label: "Fact chips +1", story: "Kai adds a word to his notebook" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Strong and hard to break" },
      { id: "b", text: "Soft and bendy" },
      { id: "c", text: "Shiny and new" },
      { id: "d", text: "Heavy and slow" },
    ],
    rightFeedback: "Right! A sturdy shell is strong, so it won't dent or crack.",
    wrong: [
      { choice: "b", hint: "Would a soft, bendy shell stay safe when it bumps a wall? Look at \"will not dent or crack.\"" },
      { choice: "c", hint: "A shell can be shiny and still crack. The sentence tells what sturdy does when it bumps a wall." },
      { choice: "d", hint: "The sentence doesn't talk about weight or speed. What does it say about bumping into a wall?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Fact or feeling?", machine: "Sort Bay", icon: "cells", speaker: "nova", passage: ["A"],
    line: "Some sentences in this ad can be checked. Others just tell how the writer feels. Help me sort them.",
    question: "Sort each sentence from the ad. Is it a fact or an opinion?",
    hint: "A fact can be checked or measured. An opinion tells what someone thinks or feels. Words like best, cutest, and fun are clues.",
    meter: { heat: 10, label: "Deal meter +10%", story: "The fact cards are sorted" },
    discovery: { id: "stickynote", name: "A lucky glue mistake", who: "Nova", fact: "The glue on sticky notes began as a mistake. A scientist was trying to make a super-strong glue, but his glue was weak. Later, someone used it for notes that stick and peel off again." },
    answer: { kind: "sort", bins: { s1: "fact", s2: "fact", s3: "fact", s4: "opinion", s5: "opinion", s6: "opinion" } },
    rightFeedback: "Sorted! Facts can be checked. Opinions tell feelings. Keep those facts in mind. Someone may check them later!",
    sort: {
      bins: [{ id: "fact", label: "Fact (can be checked)" }, { id: "opinion", label: "Opinion (a feeling or belief)" }],
      items: [
        { id: "s1", label: "The Super Scrub has six soft brushes and one strong vacuum." },
        { id: "s2", label: "It rolls up stairs on rubber tracks." },
        { id: "s3", label: "Its battery lasts four hours on one charge." },
        { id: "s4", label: "It is the cutest robot you will ever see." },
        { id: "s5", label: "Cleaning with the Super Scrub is more fun than a party." },
        { id: "s6", label: "The Super Scrub is the best cleaning bot in all of Mechara!" },
      ],
    },
    wrong: [
      { item: "s1", hint: "You could count the brushes and look for the vacuum. Can that be checked?" },
      { item: "s2", hint: "You could watch the robot try the stairs. Can that be checked?" },
      { item: "s3", hint: "You could time the battery with a clock. Can that be checked?" },
      { item: "s4", hint: "Cute to one person may not be cute to another. Is that a feeling?" },
      { item: "s5", hint: "Can you measure fun? This sentence tells how the writer feels." },
      { item: "s6", hint: "The word best is a clue. Could everyone agree on what is best?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Who's it for?", machine: "Audience Scanner", icon: "crew", speaker: "vega", passage: ["C"],
    line: "Another trader handed out this poster at the gate. Every writer has a reader in mind. Who is this poster talking to?",
    question: "Part 1: Who is the poster written for? Part 2: Highlight a sentence that shows it.",
    parts: [
      { type: "choice", prompt: "Who is the poster written for?", choices: [
        { id: "a", text: "Kids who like robots" },
        { id: "b", text: "Traders who sell robots" },
        { id: "c", text: "Commander Vega" },
        { id: "d", text: "Robots at the fair" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows who the poster is for.", passage: "C" },
    ],
    hint: "Look at who the poster talks to. Who says hi, and who gets a free sticker?",
    meter: { heat: 5, label: "Deal meter +5%", story: "The scanner locks on the reader" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["C1.1", "C2.3", "C4.2"]] },
    ] },
    rightFeedback: "Yes! \"Hey, kids!\" and \"Bring a grown-up\" show the poster is talking to kids.",
    wrong: [
      { step: 1, choice: "b", hint: "The poster never talks to traders. Who does it say \"Hey\" to?" },
      { step: 1, choice: "c", hint: "Pip's letter is for Vega, but this poster starts with a different greeting. Read the first line." },
      { step: 1, choice: "d", hint: "Robots are at the fair, but who is the poster inviting to come?" },
      { step: 2, sentence: "C3.2", hint: "That tells where the fair is. Which sentence names the reader?" },
      { step: 2, sentence: "C3.1", hint: "That tells when the fair is. Which sentence shows who should come?" },
      { step: 2, sentence: "C4.1", hint: "That is an opinion about the day. Which sentence talks right to the reader?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Bolt rolls up!", machine: "Pitch Breaker", icon: "snap", speaker: "vega", passage: ["A"],
    line: "Surprise! Bolt the trader just rolled a Super Scrub right up our ramp. He wants an answer now. Let's break his pitch apart before we say anything.",
    question: "Part 1: Why did Bolt write the ad? Part 2: Pick every FACT that could help support the claim. Part 3: Highlight the sentence where the ad tells readers what to do.",
    parts: [
      { type: "choice", prompt: "What is the author's purpose for the ad?", choices: [
        { id: "a", text: "To persuade people to get a Super Scrub" },
        { id: "b", text: "To inform people about how brushes are made" },
        { id: "c", text: "To entertain people with a funny robot story" },
        { id: "d", text: "To teach people how to build a cleaning bot" },
      ] },
      { type: "multi", prompt: "Pick every fact that could help support the claim.", choices: [
        { id: "a", text: "It has six soft brushes and one strong vacuum." },
        { id: "b", text: "It rolls up stairs on rubber tracks." },
        { id: "c", text: "It is the cutest robot you will ever see." },
        { id: "d", text: "Your friends will be so jealous!" },
        { id: "e", text: "Bolt's Bot Shop is on Gear Street." },
      ] },
      { type: "highlight", prompt: "Highlight the sentence where the ad tells readers what to do.", passage: "A" },
    ],
    hint: "Persuade means to try to get someone to do or believe something. A fact that supports the claim has to show the robot cleans well.",
    meter: { heat: 10, label: "Deal meter +10%", story: "Bolt's pitch is broken into pieces" },
    discovery: { id: "mower", name: "Robot lawn mowers", who: "Kai", fact: "Some robot lawn mowers follow a thin wire buried around the edge of a yard. The wire tells the mower where to stop and turn." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["a", "b"] },
      { kind: "highlight", groups: [["A4.1", "A4.2"]] },
    ] },
    rightFeedback: "Pitch broken! The ad wants to persuade, the brushes and tracks are facts, and it ends by telling you to go trade.",
    wrong: [
      { step: 1, choice: "b", hint: "The ad does give some facts, but what does it want the reader to DO at the end?" },
      { step: 1, choice: "c", hint: "Is the ad a story with characters and a problem? What does it want from you?" },
      { step: 1, choice: "d", hint: "The ad never shows how to build anything. It wants you to get something." },
      { step: 2, pick: "c", hint: "Cutest is an opinion, not a fact. Which choices can be checked?" },
      { step: 2, pick: "d", hint: "That tells how your friends might feel. It can't be checked, and it doesn't show the robot cleans well." },
      { step: 2, pick: "e", hint: "That is a fact, but does it show the Super Scrub is a good cleaner?" },
      { step: 2, missing: true, hint: "There are two facts that show the robot can clean well. Look at paragraph 2." },
      { step: 3, sentence: "A1.2", hint: "That is the claim. Which sentence tells readers where to go or what to do?" },
      { step: 3, sentence: "A3.2", hint: "That tells how friends might feel. Look at the end of the ad." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Pip's big ask", machine: "Claim Finder", icon: "scan", speaker: "vega", passage: ["B"],
    line: "A trader named Pip sent me a letter. It's polite, but what does Pip actually want from us?",
    question: "Read Passage B. Highlight the sentence that tells what Pip wants Commander Vega to do.",
    hint: "Look for the sentence where Pip says what he wants to trade.",
    meter: { heat: 10, label: "Deal meter +10%", story: "Pip's offer is on the screen" },
    discovery: { id: "microwave", name: "A melted snack", who: "Nova", fact: "In 1945, an engineer was working near a radar machine when a candy bar in his pocket melted. That clue helped him invent the microwave oven." },
    answer: { kind: "highlight", groups: [["B2.2"]] },
    rightFeedback: "Right! Pip wants to trade his star charts for three tanks of fresh water.",
    wrong: [
      { sentence: "B2.1", hint: "That tells who Pip is. Which sentence tells what he wants?" },
      { sentence: "B3.2", hint: "That is a fact about the charts. It supports the offer. Which sentence IS the offer?" },
      { sentence: "B4.2", hint: "That tells what Pip thinks of the trade. Which sentence tells what the trade is?" },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Written means true?", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["B"],
    line: 'Kai: "Pip wrote, \'This is the best trade you will get all year.\' It\'s written right there in a letter, so it has to be true!"',
    nova: 'Nova: "Being written down doesn\'t make something true. Pip says \'I think,\' so that\'s his opinion. Nobody can prove it."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Look at the words \"I think.\" Can anyone measure or check the best trade of the year?",
    meter: { supplies: 1, label: "Fact chips +1", story: "The crew agrees to check before they trust" },
    discovery: { id: "braille", name: "Reading with fingertips", who: "Nova", fact: "Louis Braille was only 15 when he made a way to read with raised dots you feel with your fingertips. People who are blind still read braille today." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. \"I think\" shows an opinion. An opinion tells what someone believes, and it can't be proven, even when it's written down." },
      { id: "B", text: "Nova, because traders never tell the truth." },
      { id: "C", text: "Kai. If words are written in a letter, they are facts." },
      { id: "D", text: "Kai. Pip is a grown-up trader, so whatever he writes is true." },
    ],
    writtenPrompt: "Tell Kai in your own words how to tell if a sentence in a letter is a fact or an opinion.",
    debateHints: {
      wrongWho: "Does writing something down make it true? Look at the words \"I think.\"",
      wrongReason: "Right person, check the reason. What do the words \"I think\" show?",
      right: "Nova is right. Written words can still be opinions. \"I think\" is a clue.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Right on the dot", machine: "Word Decoder", icon: "static", speaker: "nova", passage: ["B"],
    line: "Pip says his charts are accurate. If we fly past the Rust Rings, that word really matters!",
    question: "\"My charts are accurate. They show all 12 moons of this planet in exactly the right places.\" What does accurate mean?",
    hint: "Read the next sentence. Where are the moons on Pip's charts?",
    meter: { heat: 5, label: "Deal meter +5%", story: "Nova checks the word" },
    discovery: { id: "wipers", name: "Windshield wipers", who: "Kai", fact: "In 1903, a woman named Mary Anderson got a patent for windshield wipers. Drivers could clear rain and snow without leaning out the window." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Correct, with no mistakes" },
      { id: "b", text: "Very old" },
      { id: "c", text: "Full of bright colors" },
      { id: "d", text: "Hard to read" },
    ],
    rightFeedback: "Yes! Accurate charts are correct. The moons are in exactly the right places.",
    wrong: [
      { choice: "b", hint: "The letter says the charts were drawn last month. Does accurate mean old?" },
      { choice: "c", hint: "The letter never talks about colors. What does \"exactly the right places\" tell you?" },
      { choice: "d", hint: "Would Pip brag about charts that are hard to read? Look at \"exactly the right places.\"" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Kai's wrench wish", machine: "Proof Picker", icon: "log", speaker: "kai", passage: ["D"],
    line: "I wrote my own pitch! I really want a Zip Wrench. Which of my sentences are real facts that back up my claim?",
    question: "Read Kai's proposal. Pick every FACT that supports his claim.",
    hint: "A fact can be checked or measured. Opinions and begging don't count as proof.",
    meter: { heat: 10, label: "Deal meter +10%", story: "Kai's facts light up" },
    discovery: { id: "bicycle", name: "Bikes with no pedals", who: "Nova", fact: "The first bicycles, built in 1817, had no pedals. Riders pushed along the ground with their feet." },
    answer: { kind: "multi", correct: ["a", "b", "c"] },
    items: [
      { id: "a", text: "The Zip Wrench tightened ten bolts in one minute." },
      { id: "b", text: "My old hand wrench tightened only two bolts in one minute." },
      { id: "c", text: "It weighs less than one of my boots." },
      { id: "d", text: "The Zip Wrench is the coolest tool in the galaxy." },
      { id: "e", text: "Please say yes!" },
    ],
    rightFeedback: "Right! Kai timed the bolts and compared the weight. Those are facts you can check.",
    wrong: [
      { pick: "d", hint: "Coolest is a feeling. Can you measure cool?" },
      { pick: "e", hint: "That is Kai asking, not proof. Does it give a fact?" },
      { missing: true, hint: "There are three facts. Look for numbers and things you could measure." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Pip on the radio!", machine: "Audience Scanner", icon: "quake", speaker: "vega", passage: ["B"],
    line: "Surprise! Pip is calling on the radio. He says the Rust Rings are getting stormy, and he needs my answer in ten minutes. Help me read his letter fast.",
    question: "Part 1: Who is Pip's letter written for? Part 2: Highlight a sentence that shows it. Part 3: Pick the fact Vega can check before she says yes.",
    parts: [
      { type: "choice", prompt: "Who is Pip's letter written for?", choices: [
        { id: "a", text: "Commander Vega" },
        { id: "b", text: "Kids at the robot fair" },
        { id: "c", text: "Other traders in Mechara" },
        { id: "d", text: "The robot mapmaker" },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that shows who the letter is for.", passage: "B" },
      { type: "choice", prompt: "Which part of Pip's letter is a fact that Vega can check?", choices: [
        { id: "a", text: "They show all 12 moons of this planet in exactly the right places." },
        { id: "b", text: "I think this is the best trade you will get all year." },
        { id: "c", text: "I have heard that your crew is brave and fair." },
        { id: "d", text: "Your friend, Pip Sprocket" },
      ] },
    ],
    hint: "Look at how the letter starts and who it talks to. Then find a sentence Vega could test by looking at the charts.",
    meter: { heat: 10, label: "Deal meter +10%", story: "Vega checks the moons, and the charts pass" },
    discovery: { id: "helicopter", name: "A helicopter on Mars", who: "Nova", fact: "In 2021, a small robot helicopter named Ingenuity made the first powered flight on another planet. It flew in the thin air of Mars." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B1.1", "B2.3", "B5.1"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Nice and fast! The letter says \"Dear Commander Vega,\" and she can count the moons on the charts.",
    wrong: [
      { step: 1, choice: "b", hint: "That's who the poster was for. How does Pip's letter start?" },
      { step: 1, choice: "c", hint: "Pip is a trader, but who is he writing TO? Read the first line." },
      { step: 1, choice: "d", hint: "The letter tells about the mapmaker, but who does it talk to?" },
      { step: 2, sentence: "B3.3", hint: "That tells who drew the charts. Which sentence talks right to Vega or her ship?" },
      { step: 2, sentence: "B4.2", hint: "That is Pip's opinion. Which sentence shows who is reading the letter?" },
      { step: 2, sentence: "B2.1", hint: "That tells who the WRITER is. Which sentence shows who the READER is?" },
      { step: 3, choice: "b", hint: "\"I think\" is a clue. Can Vega check the best trade of the year?" },
      { step: 3, choice: "c", hint: "That is something Pip heard, not something Vega can test with the charts." },
      { step: 3, choice: "d", hint: "That's how Pip signs his letter. Which sentence could Vega test?" },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "The battery test", machine: "Test Bench", icon: "scan", speaker: "nova", passage: ["E"],
    line: "I tested the Super Scrub with a timer. Remember the ad's battery fact? My test found something surprising.",
    question: "Read Nova's review. Highlight the sentence that shows the ad's battery fact was wrong.",
    hint: "The ad said four hours. Which sentence tells how long the battery really lasted?",
    meter: { heat: 5, label: "Deal meter +5%", story: "The test results are in" },
    discovery: { id: "icepop", name: "A kid inventor", who: "Kai", fact: "In 1905, an 11-year-old boy left a cup of fruit drink with a stirring stick outside on a cold night. By morning it had frozen, and the ice pop was born." },
    answer: { kind: "highlight", groups: [["E3.2"]] },
    rightFeedback: "Right! The ad said four hours, but Nova's test showed only two.",
    wrong: [
      { sentence: "E3.1", hint: "That tells what the ad SAID. Which sentence tells what Nova's test found?" },
      { sentence: "E3.3", hint: "That is about the Dust Buddy's battery. Which sentence is about the Super Scrub?" },
      { sentence: "E2.1", hint: "That is about cleaning speed. Look for the battery test." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Nova's big message", machine: "Message Decoder", icon: "brief", speaker: "vega", passage: ["E"],
    line: "Nova's review is going on the ship's board. Let's be clear about why she wrote it and what she wants us to learn.",
    question: "Part 1: What is Nova's purpose for writing the review? Part 2: What is Nova's message?",
    parts: [
      { type: "choice", prompt: "Why did Nova write her review?", choices: [
        { id: "a", text: "To tell the crew what her tests showed and which robot she thinks is better" },
        { id: "b", text: "To entertain the crew with a silly story about robots" },
        { id: "c", text: "To get people in Mechara to trade for Dust Buddies" },
        { id: "d", text: "To teach the crew how to build a cleaning bot" },
      ] },
      { type: "choice", prompt: "What is Nova's message?", choices: [
        { id: "a", text: "Check what an ad says before you believe it." },
        { id: "b", text: "The fastest robot is always the best." },
        { id: "c", text: "Never trade for anything." },
        { id: "d", text: "Cleaning bots pick up a lot of dust." },
      ] },
    ],
    hint: "Nova shares her test results, then gives her opinion. Read her last sentence for the message.",
    meter: { supplies: 1, label: "Fact chips +1", story: "Nova's review goes up on the board" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Yes! Nova informs the crew with her tests, shares her opinion, and reminds us to check ads.",
    wrong: [
      { step: 1, choice: "b", hint: "Nova uses a timer and a measuring cup. Is that a silly story?" },
      { step: 1, choice: "c", hint: "Nova writes to her crew, not to people all over Mechara. Who is her review for?" },
      { step: 1, choice: "d", hint: "Nova tests robots. She doesn't explain how to build one." },
      { step: 2, choice: "b", hint: "The Super Scrub was faster, but Nova picked the Dust Buddy. So is fastest always best?" },
      { step: 2, choice: "c", hint: "Nova still picks a robot for the ship. What does she say to do first?" },
      { step: 2, choice: "d", hint: "That's a detail, not a lesson. Read Nova's advice at the end." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Slow but steady", machine: "Read the Crew", icon: "crew", speaker: "kai", passage: ["E"],
    line: "Wait. The Super Scrub was faster! Why would Nova pick the slow robot?",
    question: "Part 1: Why does Nova think the Dust Buddy is better for the ship? Part 2: Highlight a sentence that supports your answer.",
    parts: [
      { type: "choice", prompt: "Why does Nova pick the Dust Buddy?", choices: [
        { id: "a", text: "Its battery lasts long enough to clean every room on one charge." },
        { id: "b", text: "It is faster than the Super Scrub." },
        { id: "c", text: "It picked up much more dust." },
        { id: "d", text: "An ad told her to pick it." },
      ] },
      { type: "highlight", prompt: "Highlight a sentence that supports your answer.", passage: "E" },
    ],
    hint: "Compare the two batteries. Our ship has lots of rooms to clean.",
    meter: { heat: 5, label: "Deal meter +5%", story: "Kai understands Nova's choice" },
    discovery: { id: "breaderaser", name: "Bread erasers", who: "Nova", fact: "Before rubber erasers were invented, people rubbed out pencil marks with little balls of bread." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["E4.2", "E3.3"]] },
    ] },
    rightFeedback: "Right! The Dust Buddy is slower, but its battery lasts five hours, long enough for the whole ship.",
    wrong: [
      { step: 1, choice: "b", hint: "Check paragraph 2. Which robot took 35 minutes?" },
      { step: 1, choice: "c", hint: "Paragraph 2 says both robots picked up about the same amount. What else did Nova test?" },
      { step: 1, choice: "d", hint: "Nova didn't use an ad. She used her own tests. What did they show?" },
      { step: 2, sentence: "E2.1", hint: "That shows the Super Scrub was faster. Which sentence helps the Dust Buddy?" },
      { step: 2, sentence: "E4.1", hint: "That is Nova's opinion. Which sentence gives the reason for it?" },
      { step: 2, sentence: "E2.3", hint: "That shows the robots were the same at picking up dust. What made the Dust Buddy better?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Kai's mistake", machine: "Repair", icon: "log", speaker: "kai", passage: ["D", "F"],
    line: "Vega said my Zip Wrench pitch has a problem. I rewrote it, but I made some new mistakes too. Oops!",
    question: "Part 1: What was wrong with Kai's sentence, \"The Zip Wrench is the coolest tool in the galaxy, and everyone knows it\"? Part 2: Pick the best sentence to replace it. Part 3: Fix the 3 mistakes in Kai's new proposal.",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's sentence?", choices: [
        { id: "a", text: "It is an opinion, but Kai wrote it like a fact that everyone agrees with." },
        { id: "b", text: "It has a spelling mistake." },
        { id: "c", text: "It is a fact that Kai measured." },
        { id: "d", text: "It is too short." },
      ] },
      { type: "choice", prompt: "Pick the best sentence to replace it.", choices: [
        { id: "a", text: "The Zip Wrench is ten times cooler than any other tool." },
        { id: "b", text: "The Zip Wrench tightened five times as many bolts as my old wrench." },
        { id: "c", text: "Everyone loves the Zip Wrench." },
        { id: "d", text: "The Zip Wrench is totally awesome." },
      ] },
      { type: "edit", prompt: "Fix the 3 mistakes in Kai's new proposal.", passage: "F" },
    ],
    hint: "Saying \"everyone knows it\" doesn't make an opinion a fact. A better sentence uses something Kai measured.",
    meter: { supplies: 1, label: "Fact chips +1", story: "Kai's new pitch is ready for Vega" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "edit", fixes: { "F:i": "I", "F:wayes": "weighs", "F:friday": "Friday" } },
    ] },
    rightFeedback: "Pitch repaired! Ten bolts is five times as many as two. That's a fact Vega can check.",
    wrong: [
      { step: 1, choice: "b", hint: "Every word in that sentence is spelled right. Is \"coolest\" something you can check?" },
      { step: 1, choice: "c", hint: "Kai measured bolts, not coolness. Can you measure cool?" },
      { step: 1, choice: "d", hint: "Length isn't the problem. Is \"coolest tool\" a fact or a feeling?" },
      { step: 2, choice: "a", hint: "\"Cooler\" is still a feeling, even with a number. Which sentence uses Kai's test?" },
      { step: 2, choice: "c", hint: "\"Everyone loves\" is the same problem again. Which sentence can be checked?" },
      { step: 2, choice: "d", hint: "Awesome is an opinion. Which choice uses what Kai measured?" },
      { step: 3, token: "F:i", hint: "When you write about yourself, how do you always write the word I?" },
      { step: 3, token: "F:wayes", hint: "This word tells how heavy something is. Which spelling means that?" },
      { step: 3, token: "F:friday", hint: "Days of the week are names. What do names start with?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Vega's final call", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["E", "A"],
    line: "Surprise! Both traders are waiting outside, and I have to pick ONE cleaning bot for the ship today. I want your opinion, backed up with a fact.",
    question: "Part 1: Pick the sentence that is a claim. Part 2: Pick the reason that uses a fact from Nova's test. Part 3: Write 2–3 sentences telling which robot the crew should get and why.",
    parts: [
      { type: "choice", prompt: "Which sentence is a claim?", choices: [
        { id: "a", text: "Our ship should get the Dust Buddy." },
        { id: "b", text: "The Dust Buddy's battery lasted five hours." },
        { id: "c", text: "Nova tested two robots." },
        { id: "d", text: "The supply room has dust in it." },
      ] },
      { type: "choice", prompt: "Which reason uses a fact from Nova's test?", choices: [
        { id: "a", text: "It is the cutest robot on Mechara." },
        { id: "b", text: "Its battery lasted five hours, so it can clean every room on one charge." },
        { id: "c", text: "My friends would think it is cool." },
        { id: "d", text: "The ad said it was the best." },
      ] },
      { type: "write", prompt: "Write 2–3 sentences. Tell which robot the crew should get, give a reason, and use a fact from Nova's review.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["States a clear opinion (claim) about which robot to get", "Gives a reason", "Uses a fact from Nova's review to support the reason", "Complete sentences with capitals and end punctuation"],
    hint: "A claim tells what you believe. A strong reason uses a fact that can be checked, like a number from Nova's test.",
    meter: { heat: 10, label: "Deal meter +10%", story: "Vega makes the deal" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Deal done! Your teacher will read your opinion.",
    wrong: [
      { step: 1, choice: "b", hint: "That is a fact from Nova's test. Which sentence tells what someone believes the crew should do?" },
      { step: 1, choice: "c", hint: "That is a fact about what Nova did. Which sentence is a claim?" },
      { step: 1, choice: "d", hint: "That is a fact about the room. Which sentence says what the ship should do?" },
      { step: 2, choice: "a", hint: "Cutest is an opinion. Which reason uses a number from Nova's test?" },
      { step: 2, choice: "c", hint: "That's about feelings, not a fact from Nova's test." },
      { step: 2, choice: "d", hint: "Nova's test showed the ad got something wrong. Which reason uses Nova's facts?" },
    ],
  },
};

export default {
  id: "ELA.3.9E-XP",
  standard: "ELA.3.9E-XP",
  engine: "expedition_station",
  title: "The Trader's Pitch",
  planet: "Mechara",
  outpost: "Gear Street Market · trading day",
  grade: 3,
  subject: "ELAR",
  teks: "3.9E",
  supportingTeks: ["3.10A", "3.6F", "3.7C", "3.3B", "3.11D", "3.12C"],
  skillsChip: "3.9E · Claims, facts, opinions, and audience",
  iCan: "I can find the claim in a pitch, tell facts from opinions, and name who the writer is talking to. I can write my own opinion with a reason.",
  blurb: "In the robot city of Mechara, traders line up to pitch gadgets to the crew. Ads, letters, and posters all promise something, but which parts are facts?",
  mission: "Read each trader's pitch, find the claims, sort facts from opinions, and help Commander Vega make a smart deal.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.9E · MECHARA GEAR STREET",
  playableActs: [1, 2, 3],
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Deal meter", heatUnit: "%", supplies: "Fact chips", suppliesUnit: "chips" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega. We've landed at the Gear Street Market on Mechara.",
    "Word got out that we have fresh water and space crackers. Now every trader in the robot city wants to make a deal with us.",
    "Their pitches sound great. Help us find out which parts are facts and which are just opinions. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The shiny ad", "Act 2 · Letters and wishes", "Act 3 · Put it to the test"],
    completes: [
      "Great work, {firstName}! Bolt's pitch doesn't fool us. We know the claim, the facts, and the feelings.",
      "Nice job, {firstName}! Pip's charts check out, and Kai's pitch has real facts.",
      "Deal done, {firstName}! The crew picked a robot using facts, not just a fancy pitch.",
    ],
    teasers: [
      "Next on Mechara: a trader sends Vega a letter, and Kai writes a pitch of his own. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: Nova puts the Super Scrub to the test. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Commander Vega here. A trader named Pip sent me a letter this morning.",
      "And Kai has written a pitch of his own. Let's see which one has real facts.",
    ],
    openings3: [
      "Specialist {firstName}, Nova here. I didn't trust the Super Scrub ad, so I tested it.",
      "Read my review, then help Vega make her final choice.",
    ],
  }),
  tasks,
};
