// Expedition Station — The Trusted Source (ELA.5.13D-XP)
// Grade 5 · ELAR · Mechara. Main standard 5.13D (understand credibility of
// primary and secondary sources); also practices 5.13C (identify and gather
// relevant information from a variety of sources), 5.13E (demonstrate
// understanding of information gathered), 5.13F (paraphrasing vs. plagiarism),
// 5.13G (bibliography entries), 5.9E (argumentative text: claim and audience),
// 5.6F (inferences), 5.6H (synthesize), 5.7C (text evidence). All passages are
// original, written for this quest. The lights in Mechara's Gearford District
// keep flickering, and six sources give six different answers. The crew has to
// decide which sources to trust before the city council votes on a fix.
import { CREW, acts, passage } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Engineer Pell-7's Measurement Log", genre: "Measurement log (primary source)" }, [
    [
      "Measurement Log, Substation 4, Gearford District, May 2031.",
      "Written by Engineer Pell-7, City Power Team.",
      "I am recording what I measure with my own meters, every day, at the same times.",
    ],
    [
      "May 3: At 5:00 p.m., the voltage on the main cable read 240 volts, which is normal.",
      "At 6:00 p.m., the street lamps switched on and about 4,000 robots plugged in to recharge.",
      "The voltage dropped to 205 volts, and lights across the district flickered for 14 minutes.",
    ],
    [
      "May 4: I measured again and saw the same pattern.",
      "The flickers began at 6:02 p.m. and stopped when most robots finished charging.",
      "At noon, when few robots were charging, the lights never flickered once.",
    ],
    [
      "May 5: I checked the cable itself.",
      "It is the original cable from when Substation 4 was built, and it was warm to the touch at 6:10 p.m.",
      "My data shows the flickers happen when too many robots charge at the same time.",
    ],
  ]),
  B: passage("B", { title: "FlickerFree Shield", genre: "Advertisement from ZapCo" }, [
    [
      "Tired of flickering lights?",
      "Buy the FlickerFree Shield today!",
      "Flickers are annoying, confusing, and terrible for your eyes.",
    ],
    [
      "Everyone knows that flickers are caused by invisible static clouds floating through your home.",
      "The FlickerFree Shield sucks up static clouds and stops every flicker forever.",
      "Our shield was designed by the smartest robots in the galaxy.",
      "Nine out of ten robots say they love it!",
    ],
    [
      "Don't wait for the city to fix things.",
      "Only 3 shields are left, so buy now before they are gone!",
      "Just 199 credits, sold only by ZapCo.",
      "Your home deserves to shine like new, and your family will thank you.",
    ],
  ]),
  C: passage("C", { title: "Gearford Chat Board Post", genre: "Online post (anonymous)" }, [
    [
      "Posted by: user GearFan_2000 (real name not given).",
      "No date is shown on this post.",
      "This account was made two days ago.",
    ],
    [
      "OK, so my cousin's friend heard that the flickers are caused by the giant magnet at the Robot History Museum.",
      "When they turn it on, it pulls the power right out of the wires!",
      "I haven't checked, but I'm 100% sure it's true.",
      "My lights flickered right when I walked past the museum yesterday, so that proves it.",
    ],
    [
      "I bet the power team already knows and just isn't telling us.",
      "Share this so everyone knows!",
      "This post has 3,406 likes and 912 shares.",
    ],
  ]),
  D: passage("D", { title: "Power Grids", genre: "Reference entry (secondary source)" }, [
    [
      "A power grid is a network of wires that carries electricity from power stations to homes, shops, and charging stations.",
      "Along the way, electricity passes through substations, which control how the power flows to each neighborhood.",
    ],
    [
      "Every wire can safely carry only a certain amount of electric current.",
      "When too many devices use power from the same wire at once, the wire can become overloaded.",
      "An overloaded wire heats up, and the voltage drops, which can make lights dim or flicker.",
    ],
    [
      "The busiest time of day on a power grid is called peak demand.",
      "Engineers can reduce overloads by adding thicker cables or by spreading out the times when devices use power.",
    ],
    [
      "From the Mechara Library Encyclopedia.",
      "Entry reviewed by the Mechara Institute of Engineering.",
      "Last updated: January 2031.",
    ],
  ]),
  E: passage("E", { title: "Flickering Lights Puzzle Gearford", genre: "News report (secondary source)" }, [
    [
      "Mechara Daily News, May 6, 2031.",
      "By Rina Bolt, science reporter.",
    ],
    [
      "For two weeks, lights in the Gearford District have flickered almost every evening.",
      "The trouble began soon after 30 new fast-charging stations opened in the district in April.",
    ],
    [
      "\"Our meters show the flickers start when thousands of robots charge at once,\" said Engineer Pell-7 of the City Power Team.",
      "Dr. Ohma Watt, who studies power grids at the Mechara Institute of Engineering, agreed.",
      "\"An old cable can only carry so much current,\" she explained.",
    ],
    [
      "Not everyone agrees.",
      "\"I think it's that museum magnet,\" said one shopper, who did not give her name.",
      "The city council will vote next week on how to fix the problem.",
    ],
  ]),
  F: passage("F", { title: "Gearford District Power Guide", genre: "Guidebook (old edition)" }, [
    [
      "Gearford District Power Guide, First Edition, 2004.",
      "Published by the City Power Team.",
    ],
    [
      "Substation 4 serves about 500 homes and shops.",
      "Its main cable can carry more than twice the power the district needs, even at the busiest hour.",
    ],
    [
      "Most robots in Gearford recharge once a week, usually on weekends.",
      "Because of this, flickering lights should never be a problem in this district.",
      "If your lights flicker, check the bulb first.",
    ],
    [
      "Lights may also flicker during big storms.",
      "Call the City Power Team if a problem lasts more than one day.",
      "Keep this guide in a safe place for future use.",
    ],
  ]),
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Firsthand or secondhand?", machine: "Sort Bay", icon: "cells", speaker: "nova",
    line: "The city's source files are a jumble. A primary source comes from someone who was there. A secondary source explains or reports what others found.",
    question: "Sort each source: primary or secondary?",
    hint: "Ask: did the maker see, measure, or record it firsthand? Or are they explaining information from other people?",
    meter: { heat: 10, label: "City power +10%", story: "The source files are sorted" },
    discovery: { id: "volta", name: "Volts", who: "Nova", fact: "Voltage is measured in volts, named after Alessandro Volta. He built the first battery in 1800 by stacking metal discs with salty cloth between them." },
    answer: { kind: "sort", bins: { s1: "primary", s2: "primary", s3: "primary", s4: "secondary", s5: "secondary", s6: "secondary" } },
    rightFeedback: "Sorted! The log, the interview, and the photo are firsthand. The encyclopedia, textbook, and history book explain what others found.",
    sort: {
      bins: [{ id: "primary", label: "Primary source" }, { id: "secondary", label: "Secondary source" }],
      items: [
        { id: "s1", label: "Engineer Pell-7's measurement log (Passage A)" },
        { id: "s2", label: "A recording of an interview with Engineer Pell-7" },
        { id: "s3", label: "A photo Nova took of the warm cable" },
        { id: "s4", label: "The encyclopedia entry on power grids (Passage D)" },
        { id: "s5", label: "A textbook chapter about how electricity works" },
        { id: "s6", label: "A book about the history of Mechara's power grid, written 50 years later" },
      ],
    },
    wrong: [
      { item: "s1", hint: "Pell-7 wrote down what she measured with her own meters. Is that firsthand?" },
      { item: "s2", hint: "In an interview, Pell-7 tells what she saw herself. Is that firsthand or secondhand?" },
      { item: "s3", hint: "Nova was there and took the photo herself. That's a firsthand record." },
      { item: "s4", hint: "The encyclopedia explains facts that other experts found. Did the writer measure Gearford's cable?" },
      { item: "s6", hint: "Someone writing 50 years later wasn't there. They're explaining what others recorded." },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "She was there", machine: "Trace", icon: "scan", speaker: "vega",
    passage: ["A"],
    line: "Pell-7's log is our first file. Before we trust it, I want to know how she got her information.",
    question: "Highlight the sentence in Passage A that shows Pell-7 gathered the information herself.",
    hint: "Look for a sentence that tells HOW she got her facts, not what the facts are.",
    meter: { supplies: 1, label: "Source cards +1", story: "Pell-7's log gets a source card" },
    discovery: { id: "lightningrod", name: "Lightning rods", who: "Kai", fact: "Benjamin Franklin invented the lightning rod. It is a metal rod that guides lightning safely down into the ground." },
    answer: { kind: "highlight", groups: [["A1.3"]] },
    rightFeedback: "Locked on! She measured with her own meters, every day. That makes her log a primary source.",
    wrong: [
      { sentence: "A1.1", hint: "That tells what the log is and where. Which sentence tells how Pell-7 got her facts?" },
      { sentence: "A1.2", hint: "That tells who wrote it. Does it show she measured things herself?" },
      { sentence: "A4.3", hint: "That's her conclusion. Which sentence tells HOW she collected her data?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "No proof", machine: "Decipher", icon: "static", speaker: "kai",
    passage: ["B"],
    line: "ZapCo sent us an ad. It sounds pretty sure of itself. Maybe they know the answer?",
    question: "Highlight the sentence where ZapCo claims to know what causes the flickers but gives no evidence.",
    hint: "Find the sentence that names a cause. Does it tell how anyone knows?",
    meter: { heat: 5, label: "City power +5%", story: "Kai spots the sales pitch" },
    discovery: { id: "acpower", name: "Alternating current", who: "Kai", fact: "The electricity in most homes is alternating current, or AC. In the United States, it flows back and forth 60 times every second." },
    answer: { kind: "highlight", groups: [["B2.1"]] },
    rightFeedback: "Right! \"Everyone knows\" isn't evidence. No measurements, no expert, no proof.",
    wrong: [
      { sentence: "B1.2", hint: "That's a command to buy. It shows the ad is selling, but which sentence claims what CAUSES flickers?" },
      { sentence: "B3.2", hint: "That rushes you to buy. Which sentence names a cause for the flickers?" },
      { sentence: "B1.1", hint: "That's a question to grab your attention. Which sentence claims a cause with no proof?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Warning signs", machine: "Trace", icon: "scan", speaker: "nova",
    passage: ["C"],
    line: "Someone forwarded us a post from the Gearford Chat Board. It's spreading fast.",
    question: "Pick every reason the crew should NOT trust this post.",
    hint: "Check who wrote it, when, and where the information came from.",
    meter: { supplies: 1, label: "Source cards +1", story: "The post is flagged" },
    answer: { kind: "multi", correct: ["a", "b", "c", "f"] },
    items: [
      { id: "a", text: "The writer's real name is not given." },
      { id: "b", text: "There is no date." },
      { id: "c", text: "The information came from a cousin's friend, not someone who checked." },
      { id: "d", text: "It is about the Gearford District." },
      { id: "e", text: "It is short." },
      { id: "f", text: "The writer admits they haven't checked." },
    ],
    rightFeedback: "Right! No name, no date, secondhand gossip, and nothing checked.",
    wrong: [
      { pick: "d", hint: "Being about Gearford makes it on topic. Does that make it untrustworthy?" },
      { pick: "e", hint: "A short source can still be true. Look at who wrote it and where the facts came from." },
      { missing: true, hint: "There are four warning signs. Reread paragraph 1 and paragraph 2 of the post." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Flicker at the Command Tower", machine: "Timeline", icon: "snap", speaker: "vega",
    passage: ["A", "B", "C", "D"],
    line: "Surprise! The lights just flickered in the Command Tower. The council wants to know right now which sources we can count on.",
    question: "Part 1: Rank the sources from most to least credible. Part 2: Highlight one sentence from the ad and one from the post that show there is no proof. Part 3: Decide what to do with the ad and the post.",
    parts: [
      { type: "order", prompt: "Rank the sources from most credible (top) to least credible (bottom).", items: [
        { id: "C", text: "Passage C: Gearford Chat Board Post" },
        { id: "A", text: "Passage A: Engineer Pell-7's Measurement Log" },
        { id: "B", text: "Passage B: ZapCo's FlickerFree Shield ad" },
        { id: "D", text: "Passage D: Power Grids encyclopedia entry" },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from the ad (B) and one from the post (C) that show the source has no proof.", passage: ["B", "C"], count: 2 },
      { type: "choice", prompt: "What should the crew do with the ad and the post?", choices: [
        { id: "a", text: "Use them for ideas only, and check every claim against credible sources." },
        { id: "b", text: "Trust the post, because thousands of robots liked it." },
        { id: "c", text: "Trust the ad, because a real company made it." },
        { id: "d", text: "Buy a FlickerFree Shield just in case." },
      ] },
    ],
    hint: "Credible sources are firsthand or expert-reviewed, dated, and backed by evidence. A source selling something or passing on gossip is weaker.",
    meter: { heat: 10, label: "City power +10%", story: "The council gets a source ranking" },
    discovery: { id: "robotword", name: "The word robot", who: "Nova", fact: "The word robot comes from a 1920 play by Czech writer Karel Čapek. It comes from a Czech word meaning hard, forced work." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["A", "D", "B", "C"], alsoAccept: [["A", "D", "C", "B"]] },
      { kind: "highlight", groups: [["B2.1", "B2.2", "B2.3", "B2.4"], ["C2.1", "C2.3", "C2.4"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Great ranking! Pell-7's measurements and the reviewed encyclopedia come first. The ad and the post have no proof.",
    wrong: [
      { step: 1, position: 0, hint: "Which source has dated measurements taken firsthand in Gearford? Put it on top." },
      { step: 1, position: 1, hint: "Of the rest, which source is reviewed by experts and has a date?" },
      { step: 2, sentence: "B1.1", hint: "That's a question to hook you. Which sentence makes a claim with no proof?" },
      { step: 2, sentence: "C3.3", hint: "Likes and shares show a post is popular, not that it's true. Find where the writer admits there's no proof." },
      { step: 2, sentence: "C1.1", hint: "A missing name is a warning sign, but which sentence makes a claim with no proof?" },
      { step: 3, choice: "b", hint: "Likes measure popularity, not truth. What should we do with claims that have no proof?" },
      { step: 3, choice: "c", hint: "ZapCo wants to sell shields. Does that make its claim more believable, or less?" },
      { step: 3, choice: "d", hint: "Nothing proves the shield works. What should the crew do with unproven claims?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Most likes wins?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "The chat board post has 3,406 likes! That many robots can\'t be wrong. It\'s the museum magnet, and that\'s way more exciting than a cable."',
    nova: 'Nova: "Pell-7 measured the voltage every day. Her log shows the flickers start when thousands of robots charge at once."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Popular and exciting aren't the same as credible. Which source has names, dates, and measurements?",
    meter: { heat: 5, label: "City power +5%", story: "The crew agrees on what counts as proof" },
    discovery: { id: "unimate", name: "The first factory robot", who: "Kai", fact: "The first industrial robot, called Unimate, went to work in a car factory in 1961. It lifted hot metal parts." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Pell-7's log is a primary source with dates and measurements. The post has no name, no date, and no proof. Likes show a post is popular, not true." },
      { id: "B", text: "Nova, because logs are always longer than posts." },
      { id: "C", text: "Kai. If thousands of robots liked it, it must be true." },
      { id: "D", text: "Kai. The magnet idea is the most exciting, so it's probably right." },
    ],
    writtenPrompt: "Tell Kai in your own words why likes don't make a source credible.",
    debateHints: {
      wrongWho: "Count the evidence, not the likes. Which source has dates and measurements?",
      wrongReason: "Right person, check the reason. What makes Pell-7's log credible?",
      right: "Nova is right. Evidence beats likes every time.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The old guide", machine: "Timeline", icon: "log", speaker: "vega",
    passage: ["F", "A", "E"],
    line: "The Power Guide says our cable carries more than twice the power we need. So why are the lights flickering?",
    question: "Part 1: Why can't the crew trust the Power Guide's facts today? Part 2: Highlight one outdated sentence in the guide and one sentence from Passage A or E that shows things have changed.",
    parts: [
      { type: "choice", prompt: "Why can't the crew trust the Power Guide's facts today?", choices: [
        { id: "a", text: "It was written in 2004, before the new charging stations, when robots charged much less often." },
        { id: "b", text: "It was published by the City Power Team." },
        { id: "c", text: "It gives advice about light bulbs." },
        { id: "d", text: "It doesn't have any numbers in it." },
      ] },
      { type: "highlight", prompt: "Highlight one outdated sentence in Passage F and one sentence in Passage A or E that shows what has changed.", passage: ["F", "A", "E"], count: 2 },
    ],
    hint: "Check the date on each source. What has changed in Gearford since 2004?",
    meter: { supplies: 1, label: "Source cards +1", story: "The old guide gets an \"outdated\" stamp" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["F2.1", "F2.2", "F3.1", "F3.2"], ["A2.2", "E2.2"]] },
    ] },
    rightFeedback: "Right! In 2004 robots charged once a week. Now thousands charge every evening at 30 new stations.",
    wrong: [
      { step: 1, choice: "b", hint: "The City Power Team is a good publisher. Look at the date instead." },
      { step: 1, choice: "c", hint: "Checking a bulb is fine advice. What about the guide's facts could be out of date?" },
      { step: 1, choice: "d", hint: "The guide does have numbers, like 500 homes. When were those numbers true?" },
      { step: 2, sentence: "F1.2", hint: "That tells who published the guide. Which sentence gives a fact that may no longer be true?" },
      { step: 2, sentence: "F3.3", hint: "That advice could still be fine. Which sentence gives facts about power use that have changed?" },
      { step: 2, sentence: "A4.2", hint: "That shows the cable is old, the same one the guide describes. Which sentence shows what has CHANGED?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Right source, right question", machine: "Decipher", icon: "static", speaker: "nova",
    passage: ["A", "C", "D", "E", "F"],
    line: "Every source is good for some questions and not others. I have two questions for the council's fact sheet.",
    question: "Part 1: Which source best tells what time the flickers start? Part 2: Which source best explains what \"overloaded\" means and why it makes lights flicker?",
    parts: [
      { type: "choice", prompt: "Which source best tells what time the flickers start?", choices: [
        { id: "a", text: "Passage A: Pell-7's measurement log" },
        { id: "c", text: "Passage C: the chat board post" },
        { id: "e", text: "Passage E: the news report" },
        { id: "f", text: "Passage F: the 2004 Power Guide" },
      ] },
      { type: "choice", prompt: "Which source best explains what \"overloaded\" means and why it makes lights flicker?", choices: [
        { id: "a", text: "Passage A: Pell-7's measurement log" },
        { id: "b", text: "Passage B: the ZapCo ad" },
        { id: "d", text: "Passage D: the encyclopedia entry" },
        { id: "f", text: "Passage F: the 2004 Power Guide" },
      ] },
    ],
    hint: "Match each question to the source made for it. Exact times come from records. Word meanings and explanations come from reference books.",
    meter: { heat: 5, label: "City power +5%", story: "The fact sheet has its sources" },
    discovery: { id: "thickwire", name: "Thick and thin wires", who: "Nova", fact: "A thick wire can carry more electric current than a thin wire of the same metal, and it doesn't get as hot." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "d" },
    ] },
    rightFeedback: "Right! The log gives exact times, like 6:02 p.m. The encyclopedia explains overloads.",
    wrong: [
      { step: 1, choice: "e", hint: "The news report says \"almost every evening.\" Which source gives exact times?" },
      { step: 1, choice: "c", hint: "The post doesn't give any times, and it has no proof. Which source recorded the times?" },
      { step: 1, choice: "f", hint: "The guide is from 2004, before the flickers began. Which source recorded them?" },
      { step: 2, choice: "a", hint: "The log shows what happened, but does it explain what \"overloaded\" means?" },
      { step: 2, choice: "b", hint: "The ad blames \"static clouds\" with no proof. Which source explains how wires work?" },
      { step: 2, choice: "f", hint: "The old guide says flickers shouldn't happen at all. Which source explains overloads?" },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Weigh the quotes", machine: "Read the Crew", icon: "crew", speaker: "kai",
    passage: ["E"],
    line: "Wait, the news report mentions the museum magnet too! Doesn't that mean a real newspaper backs the magnet idea?",
    question: "Part 1: Highlight the quote in the news report the crew should trust LEAST. Part 2: Why is it the weakest?",
    parts: [
      { type: "highlight", prompt: "Highlight the quote the crew should trust least.", passage: "E" },
      { type: "choice", prompt: "Why is it the weakest quote?", choices: [
        { id: "a", text: "The speaker gave no name and no evidence. She only said what she thinks." },
        { id: "b", text: "It is the last quote in the article." },
        { id: "c", text: "The speaker is a shopper, and shoppers are never right." },
        { id: "d", text: "It disagrees with the other quotes." },
      ] },
    ],
    hint: "A reporter can quote anyone. Ask who each speaker is and how they know.",
    meter: { supplies: 1, label: "Source cards +1", story: "Kai sorts the strong quotes from the weak" },
    answer: { kind: "parts", parts: [
      { kind: "highlight", groups: [["E4.2"]] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! Reporting what someone said doesn't make it true. The engineer and the expert give reasons.",
    wrong: [
      { step: 1, sentence: "E3.1", hint: "Pell-7 is an engineer who measured the flickers. Is that the weakest quote?" },
      { step: 1, sentence: "E3.3", hint: "Dr. Watt studies power grids. Is an expert's quote the weakest?" },
      { step: 1, sentence: "E3.2", hint: "That introduces an expert. Which quote comes from someone with no name and no proof?" },
      { step: 2, choice: "b", hint: "Where a quote appears doesn't make it weak. What does the speaker base her idea on?" },
      { step: 2, choice: "c", hint: "Anyone can be right. The problem is what this speaker is missing. What is it?" },
      { step: 2, choice: "d", hint: "Disagreeing isn't the problem. Does she give a name or any evidence?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "ZapCo strikes back", machine: "Trace", icon: "quake", speaker: "vega",
    passage: ["A", "D", "E"],
    line: "Surprise! ZapCo just flashed a new sign across the city: \"City engineer says only the FlickerFree Shield can stop the flickers!\" Robots are lining up to buy.",
    question: "Part 1: Is ZapCo's new claim supported? Part 2: Highlight one sentence from the log and one from the encyclopedia that explain the real cause. Part 3: Pick every statement that BOTH Passage A and Passage D support.",
    parts: [
      { type: "choice", prompt: "Is ZapCo's new claim supported by the sources?", choices: [
        { id: "a", text: "No. Pell-7's log and her quote in the news never mention a shield. She says the flickers start when thousands of robots charge at once." },
        { id: "b", text: "Yes. ZapCo says a city engineer said it, so it must be true." },
        { id: "c", text: "Yes. The sign is big and bright, so lots of robots will see it." },
        { id: "d", text: "No. Engineers never talk about flickers." },
      ] },
      { type: "highlight", prompt: "Highlight one sentence from Passage A and one from Passage D that explain the real cause.", passage: ["A", "D"], count: 2 },
      { type: "multi", prompt: "Pick every statement that BOTH Passage A and Passage D support.", choices: [
        { id: "a", text: "Lights can flicker when too many devices use one cable at once." },
        { id: "b", text: "A cable carrying too much power gets warm." },
        { id: "c", text: "Static clouds cause flickers." },
        { id: "d", text: "The museum magnet pulls power out of wires." },
        { id: "e", text: "Thicker cables can reduce overloads." },
      ] },
    ],
    hint: "Check a claim against the original source. Then put the log and the encyclopedia side by side. What do they BOTH say?",
    meter: { heat: 10, label: "City power +10%", story: "The line at ZapCo's shop disappears" },
    discovery: { id: "breaker", name: "Circuit breakers", who: "Kai", fact: "A circuit breaker is a safety switch. It turns off the power by itself when too much current flows, so wires don't overheat." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["A4.3", "A2.2", "A2.3", "A3.2", "A3.3"], ["D2.2", "D2.3"]] },
      { kind: "multi", correct: ["a", "b"] },
    ] },
    rightFeedback: "Busted! The engineer never said that. The log and the encyclopedia both point to an overloaded cable.",
    wrong: [
      { step: 1, choice: "b", hint: "Anyone can claim an expert said something. What did Pell-7 actually say in Passages A and E?" },
      { step: 1, choice: "c", hint: "A big sign gets attention, but is it evidence? Check what Pell-7 really said." },
      { step: 1, choice: "d", hint: "Pell-7 is an engineer who talks about flickers a lot. What does she say causes them?" },
      { step: 2, sentence: "D1.1", hint: "That defines a power grid. Which sentence explains what goes wrong when a wire has too much to carry?" },
      { step: 2, sentence: "D4.2", hint: "That shows the entry is credible, but it doesn't explain the cause." },
      { step: 2, sentence: "A1.2", hint: "That tells who wrote the log. Which sentence tells what she found?" },
      { step: 3, pick: "c", hint: "Only the ad says that, with no proof. Neither A nor D mentions static clouds." },
      { step: 3, pick: "d", hint: "Only the anonymous post says that. Neither A nor D mentions a magnet." },
      { step: 3, pick: "e", hint: "Passage D says that, but does Pell-7's log? The statement needs BOTH sources." },
      { step: 3, missing: true, hint: "There are two statements. Compare paragraph 4 of the log with paragraph 2 of the encyclopedia." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "In your own words", machine: "Brief", icon: "brief", speaker: "nova",
    passage: ["D"],
    line: "I want to use the encyclopedia's idea in our report to the council. But I can't just copy it.",
    question: "Passage D says: \"An overloaded wire heats up, and the voltage drops, which can make lights dim or flicker.\" Which sentence is a good paraphrase that gives credit?",
    hint: "A paraphrase keeps the same meaning in new words, and it still names the source.",
    meter: { supplies: 1, label: "Source cards +1", story: "Nova's report is in her own words" },
    discovery: { id: "insulator", name: "Insulators", who: "Nova", fact: "Rubber and plastic are insulators. Electricity can't flow through them easily, so they cover wires to keep us safe." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "When a wire carries too much, it gets hot and the power weakens, so lights may flicker (Mechara Library Encyclopedia)." },
      { id: "b", text: "An overloaded wire heats up, and the voltage drops, which can make lights dim or flicker." },
      { id: "c", text: "Hot wires make robots charge faster (Mechara Library Encyclopedia)." },
      { id: "d", text: "Lights flicker because of static clouds, says the encyclopedia." },
    ],
    rightFeedback: "Right! Same meaning, new words, and the source gets credit.",
    wrong: [
      { choice: "b", hint: "That's copied word for word with no credit. Copying without credit is plagiarism." },
      { choice: "c", hint: "That changes the meaning. Does the encyclopedia say hot wires make charging faster?" },
      { choice: "d", hint: "The encyclopedia never says that. Static clouds came from the ad." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "The source list", machine: "Brief", icon: "log", speaker: "vega",
    passage: ["A", "B", "C", "D", "E"],
    line: "Every council report ends with a source list. Each entry needs an author, a title, and a date.",
    question: "Part 1: Pick the correct source-list entry for Passage A. Part 2: Which sources are missing an author's name or a date?",
    parts: [
      { type: "choice", prompt: "Pick the correct source-list entry for Passage A.", choices: [
        { id: "a", text: "Pell-7. Measurement Log, Substation 4. City Power Team, May 2031." },
        { id: "b", text: "Some log I read about the lights." },
        { id: "c", text: "Measurement Log." },
        { id: "d", text: "Pell-7, and she is very smart." },
      ] },
      { type: "multi", prompt: "Pick every source that is missing an author's name or a date.", choices: [
        { id: "a", text: "Passage A: the measurement log" },
        { id: "b", text: "Passage B: the ZapCo ad" },
        { id: "c", text: "Passage C: the chat board post" },
        { id: "d", text: "Passage D: the encyclopedia entry" },
        { id: "e", text: "Passage E: the news report" },
      ] },
    ],
    hint: "Look at the top and bottom of each source for a name and a date.",
    meter: { supplies: 1, label: "Source cards +1", story: "The source list is ready" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["b", "c"] },
    ] },
    rightFeedback: "Right! A full entry lets anyone find the source. The ad has no date, and the post has no name or date.",
    wrong: [
      { step: 1, choice: "b", hint: "That doesn't tell who wrote it, what it's called, or when. Which entry has all three?" },
      { step: 1, choice: "c", hint: "That has a title, but no author or date. Which entry has all three?" },
      { step: 1, choice: "d", hint: "An opinion about the author doesn't belong in a source list. Which entry has author, title, and date?" },
      { step: 2, pick: "a", hint: "The log names Pell-7 and says May 2031. Is anything missing?" },
      { step: 2, pick: "d", hint: "The encyclopedia names the Mechara Institute and says January 2031. Is anything missing?" },
      { step: 2, pick: "e", hint: "The news report names Rina Bolt and says May 6, 2031. Is anything missing?" },
      { step: 2, missing: true, hint: "There are two. Check the ad for a date, and check the post for a name and a date." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "What ZapCo wants", machine: "Read the Crew", icon: "crew", speaker: "kai",
    passage: ["B"],
    line: "I get it now. ZapCo's ad is an argument. It's trying to get somebody to do something.",
    question: "Part 1: What is ZapCo's claim? Part 2: Who is the ad written for?",
    parts: [
      { type: "choice", prompt: "What is ZapCo's claim?", choices: [
        { id: "a", text: "The FlickerFree Shield stops every flicker, so you should buy it." },
        { id: "b", text: "The city should fix the old cable." },
        { id: "c", text: "Static clouds are dangerous to robots." },
        { id: "d", text: "Nine out of ten robots have flickering lights." },
      ] },
      { type: "choice", prompt: "Who is the ad written for?", choices: [
        { id: "a", text: "Robots at home who are tired of flickering lights and might buy a shield" },
        { id: "b", text: "Power engineers who measure voltage" },
        { id: "c", text: "The city council members voting on a fix" },
        { id: "d", text: "Workers at the Robot History Museum" },
      ] },
    ],
    hint: "An ad's claim is what it wants you to believe and do. Its audience is who it's talking to.",
    meter: { heat: 5, label: "City power +5%", story: "Kai can read an ad like a pro" },
    discovery: { id: "edison", name: "Long-lasting light bulbs", who: "Kai", fact: "In 1879, Thomas Edison's team made a light bulb that could glow for many hours, after testing thousands of materials." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Right! ZapCo wants tired homeowners to buy a shield, so it says only what helps sell it.",
    wrong: [
      { step: 1, choice: "b", hint: "The ad says, \"Don't wait for the city to fix things.\" What does ZapCo want you to do?" },
      { step: 1, choice: "c", hint: "The ad mentions static clouds, but what is it trying to get you to do?" },
      { step: 1, choice: "d", hint: "The ad says nine out of ten robots LOVE the shield. What is its main claim?" },
      { step: 2, choice: "b", hint: "Would engineers fall for \"static clouds\"? Who does the ad talk to with \"Your home\"?" },
      { step: 2, choice: "c", hint: "The ad tells readers NOT to wait for the city. Who is it trying to sell to?" },
      { step: 2, choice: "d", hint: "The ad never mentions the museum. Who does it speak to with \"Your home\" and \"your family\"?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Explain it to Kai", machine: "Brief", icon: "brief", speaker: "kai",
    passage: ["A", "C"],
    line: "Okay, I trusted the post because it had so many likes. Help me explain to the rest of Mechara why that was a mistake.",
    question: "Why is Pell-7's log more credible than the chat board post? Write 1–2 sentences. Use at least one detail from each source.",
    hint: "Think about who wrote each source, when, and what evidence each one gives.",
    meter: { heat: 5, label: "City power +5%", story: "Kai posts a correction on the chat board" },
    answer: { kind: "write", minWords: 15 },
    minWords: 15,
    teacherScored: true,
    rubric: ["Explains why the log is more credible", "Uses a detail from Passage A and a detail from Passage C", "Complete sentences with capitals and end punctuation"],
    rightFeedback: "Thanks! Your teacher will read your answer.",
    wrong: [],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The council votes", machine: "Transmit", icon: "relay", speaker: "vega",
    passage: ["A", "B", "C", "D", "E", "F"],
    line: "Surprise! The council moved the vote up. It's in one hour, and they want our recommendation, backed by the sources we trust most.",
    question: "Part 1: Pick the three most credible sources. Part 2: Pick the fix the credible sources support. Part 3: Write your recommendation to the council, naming at least two credible sources.",
    parts: [
      { type: "multi", prompt: "Pick the THREE most credible sources for the council.", choices: [
        { id: "a", text: "Passage A: Pell-7's measurement log" },
        { id: "b", text: "Passage B: the ZapCo ad" },
        { id: "c", text: "Passage C: the chat board post" },
        { id: "d", text: "Passage D: the encyclopedia entry" },
        { id: "e", text: "Passage E: the news report" },
        { id: "f", text: "Passage F: the 2004 Power Guide" },
      ] },
      { type: "choice", prompt: "Which fix do the credible sources support?", choices: [
        { id: "a", text: "Replace Substation 4's old cable with a thicker one, and spread out robot charging times." },
        { id: "b", text: "Give every home a FlickerFree Shield." },
        { id: "c", text: "Turn off the magnet at the Robot History Museum." },
        { id: "d", text: "Follow the 2004 guide and check every light bulb." },
      ] },
      { type: "write", prompt: "Write your recommendation to the council. Name at least two credible sources and tell what each one shows.", minWords: 20 },
    ],
    teacherScoredPart: 3,
    rubric: ["Makes a clear recommendation", "Names at least two credible sources and tells what each shows", "Complete sentences with capitals and end punctuation"],
    hint: "Credible means firsthand or expert-reviewed, dated, and up to date, with real evidence.",
    meter: { heat: 15, label: "City power +15%", story: "The council votes yes, and Gearford's lights hold steady" },
    discovery: { id: "rover", name: "Robots on Mars", who: "Nova", fact: "NASA's Mars rovers are robots. The first one, Sojourner, rolled onto Mars in 1997." },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["a", "d", "e"] },
      { kind: "choice", correct: "a" },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Recommendation sent! Your teacher will read what you wrote.",
    wrong: [
      { step: 1, pick: "b", hint: "ZapCo is selling something and gives no proof. Is that one of the most credible?" },
      { step: 1, pick: "c", hint: "The post has no name, no date, and no proof. Leave it out." },
      { step: 1, pick: "f", hint: "The guide comes from a good publisher, but it's from 2004. Are its facts still true?" },
      { step: 1, missing: true, hint: "Pick three: the firsthand log, the expert-reviewed reference, and the dated report that quotes experts." },
      { step: 2, choice: "b", hint: "Only ZapCo says the shield works, and it gives no proof. What do the log and encyclopedia point to?" },
      { step: 2, choice: "c", hint: "Only the anonymous post blames the magnet. What cause did Pell-7 measure?" },
      { step: 2, choice: "d", hint: "The 2004 guide is outdated. The bulbs aren't the problem. What is?" },
    ],
  },
};

export default {
  id: "ELA.5.13D-XP",
  standard: "ELA.5.13D-XP",
  engine: "expedition_station",
  title: "The Trusted Source",
  planet: "Mechara",
  outpost: "Gearford District Relay · evening shift",
  grade: 5,
  subject: "ELAR",
  teks: "5.13D",
  supportingTeks: ["5.13C", "5.13E", "5.13F", "5.13G", "5.9E", "5.6F", "5.6H", "5.7C"],
  skillsChip: "5.13D · Credibility of primary and secondary sources",
  iCan: "I can tell primary sources from secondary sources, decide which sources are credible, and use the best sources to make a recommendation.",
  blurb: "In the robot city of Mechara, the lights keep flickering. A measurement log, an ad, a rumor, an encyclopedia, a news report, and an old guide all give different answers.",
  mission: "Sort the sources, check each one for proof, bias, and dates, and help the city council choose a fix backed by the sources you trust most.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.13D · MECHARA GEARFORD",
  playableActs: [1, 2, 3],
  meterStart: { heat: 25, supplies: 0, journal: 0 },
  meterLabels: { heat: "City power", heatUnit: "%", supplies: "Source cards", suppliesUnit: "cards" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega in the robot city of Mechara. The lights in the Gearford District flicker every evening.",
    "The city council has to choose a fix, and six sources all say different things. Some are trustworthy. Some are not.",
    "Help us figure out which sources to trust. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · The flicker files", "Act 2 · Testing the claims", "Act 3 · The council's choice"],
    completes: [
      "Nice sorting, {firstName}! We know which sources have real proof and which ones don't.",
      "Great work, {firstName}! You spotted outdated facts, weak quotes, and a fake expert claim.",
      "Your recommendation is with the council, {firstName}! Gearford's lights are holding steady.",
    ],
    teasers: [
      "Next on Mechara: a news report and an old guidebook arrive. Act 2 is open now, or come back to it next time.",
      "Next on Mechara: the council gets ready to vote. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Two more sources just came in: a news report and the old Power Guide.",
      "Let's test every claim against the sources we trust.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. The council is almost ready to vote.",
      "Help us give credit to our sources and write a recommendation they can trust.",
    ],
  }),
  tasks,
};
