// Expedition Station — The Tug-of-War (SCI.5.7A-XP)
// Grade 5 · Science · Frostveil. Main standard 5.7A (2024 TEKS): investigate
// and explain how equal and opposite forces act on objects and how unequal
// forces change the motion of objects (balanced and unbalanced forces, net
// force in newtons). Supporting: 5.7B (design a simple investigation that
// tests the effect of force on an object, like a balloon rocket on a string
// or a car on a ramp), 5.1A (ask questions and define problems), 5.1B (plan
// and conduct fair tests), 5.1G (develop and use models), 5.2B (analyze
// data), 5.2D (evaluate experimental design), 5.3A (develop explanations
// supported by evidence), 5.3B (communicate explanations and solutions),
// 5.3C (listen to and evaluate others' ideas), 5.5A (cause and effect).
//
// Earth-true rule: every force, friction value, and test works just as it
// does on Earth. Only the planet, rover, and crew are invented.
import { CREW, acts } from "./_shared.js";

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Even or uneven?", machine: "Force Sorter", icon: "cells", speaker: "nova",
    line: "Before we touch the rover, let's warm up. Each card shows the forces on one object.",
    question: "Sort each card: are the forces balanced or unbalanced?",
    hint: "Add up the forces going each way. Are the two sides equal?",
    meter: { heat: 5, label: "Rover freed +5%", story: "The crew is warmed up" },
    answer: { kind: "sort", bins: { b1: "balanced", b2: "unbalanced", b3: "balanced", b4: "unbalanced", b5: "balanced", b6: "unbalanced" } },
    rightFeedback: "Balanced forces cancel out. Unbalanced forces leave a net force that changes motion.",
    sort: {
      bins: [{ id: "balanced", label: "Balanced forces" }, { id: "unbalanced", label: "Unbalanced forces" }],
      items: [
        { id: "b1", label: "250 N pulling left and 250 N pulling right" },
        { id: "b2", label: "180 N pulling left and 240 N pulling right" },
        { id: "b3", label: "Gravity pulls a crate down with 500 N. The floor pushes up with 500 N." },
        { id: "b4", label: "A 90 N push to the right on smooth ice. Friction pushes back with only 5 N." },
        { id: "b5", label: "Two 100 N pulls to the right and one 200 N pull to the left" },
        { id: "b6", label: "A lift rope pulls a box up with 400 N. Gravity pulls it down with 350 N." },
      ],
    },
    wrong: [
      { item: "b5", hint: "Add the two pulls going right first. 100 N + 100 N is how much? Compare it to the 200 N going left." },
      { item: "b3", hint: "The crate isn't moving. Gravity pulls down 500 N and the floor pushes up 500 N. Are those equal?" },
      { item: "b4", hint: "90 N one way and only 5 N the other way. Are those equal?" },
      { item: "b6", hint: "400 N up and 350 N down. Is one side stronger?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The practice tug", machine: "Tug Rope", icon: "dial", speaker: "kai",
    line: "The crew held a practice tug-of-war on the ice. My force meters logged each team's pull.",
    question: "What is the net force on the rope, in newtons?",
    unit: "N",
    data: {
      title: "Practice tug-of-war",
      columns: ["Team", "Direction", "Pull (newtons)"],
      rows: [
        ["Kai and two helper bots", "Left", "300 N"],
        ["Vega and Nova", "Right", "450 N"],
      ],
    },
    hint: "The teams pull in opposite directions. How much stronger is one side?",
    meter: { heat: 5, label: "Rover freed +5%", story: "The force meters are working" },
    discovery: { id: "newtonapple", name: "One newton", who: "Nova", fact: "Scientists measure force in newtons. A small apple resting in your hand pushes down with a force of about 1 newton." },
    answer: { kind: "number", value: 150 },
    rightFeedback: "450 N − 300 N = 150 N. The net force is 150 N to the right, so the rope moves toward Vega and Nova.",
    wrong: [
      { value: 750, hint: "You added. The teams pull in opposite directions, so their forces work against each other. Subtract." },
      { value: 450, hint: "450 N is only the right team's pull. How much of it is left after the left team pulls back?" },
      { value: 300, hint: "300 N is the left team's pull. Find the difference between the two teams." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Predict the slide", machine: "Motion Track", icon: "trail", speaker: "vega",
    line: "Our supply sleds slide around the camp all day. Tell me what each sled will do next.",
    question: "Sort each card: what will the sled do?",
    hint: "Balanced forces: no change. Unbalanced forces: the motion changes. Which way does the net force point?",
    meter: { heat: 5, label: "Rover freed +5%", story: "The sleds are under control" },
    answer: { kind: "sort", bins: { p1: "still", p2: "start", p3: "faster", p4: "slower", p5: "turn", p6: "turn" } },
    rightFeedback: "Balanced forces keep the motion the same. An unbalanced force can start, speed up, slow down, or turn a sled.",
    sort: {
      bins: [
        { id: "still", label: "Stays still" },
        { id: "start", label: "Starts moving" },
        { id: "faster", label: "Speeds up" },
        { id: "slower", label: "Slows down" },
        { id: "turn", label: "Changes direction" },
      ],
      items: [
        { id: "p1", label: "A parked sled. Kai pulls left with 200 N and Nova pulls right with 200 N." },
        { id: "p2", label: "A parked sled on smooth ice. Kai pulls right with 150 N. Friction pushes back with only 10 N." },
        { id: "p3", label: "A sled sliding east. Nova gives it an extra push to the east." },
        { id: "p4", label: "A sled sliding east reaches rough ground. Friction pushes it toward the west." },
        { id: "p5", label: "A sled sliding east. Vega pushes hard on its side, toward the north." },
        { id: "p6", label: "A sled sliding east. It hits a hard snowbank, which pushes it back, and it bounces off toward the west." },
      ],
    },
    wrong: [
      { item: "p1", hint: "200 N left and 200 N right. Are those forces balanced or unbalanced?" },
      { item: "p4", hint: "The sled moves east, but friction pushes west, against the motion. What does that do to its speed?" },
      { item: "p5", hint: "The push comes from the side, not from behind. What happens to the sled's path?" },
      { item: "p3", hint: "The push is in the same direction the sled is already moving. What happens to its speed?" },
      { item: "p6", hint: "The sled ends up moving west instead of east. Which bin fits?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Slippery to sticky", machine: "Friction Lab", icon: "scan", speaker: "nova",
    line: "I pulled the same sled with the same load across four surfaces. My force meter shows how hard I had to pull to get it sliding.",
    question: "Put the surfaces in order from LEAST friction to MOST friction.",
    data: {
      title: "Pull needed to start the sled sliding",
      columns: ["Surface", "Pull (newtons)"],
      rows: [
        ["Gravel", "110 N"],
        ["Smooth ice", "20 N"],
        ["Rubber floor mat", "150 N"],
        ["Packed snow", "45 N"],
      ],
    },
    hint: "More friction means Nova had to pull harder. Which surface needed the smallest pull?",
    meter: { supplies: 1, label: "Tow lines +1", story: "Nova maps the slippery spots" },
    discovery: { id: "tobogganing", name: "Belly-sliding penguins", who: "Nova", fact: "Penguins sometimes flop onto their bellies and slide across the snow and ice, pushing with their feet. This is called tobogganing, and it can be faster than waddling." },
    answer: { kind: "order", correct: ["ice", "snow", "gravel", "mat"] },
    items: [
      { id: "gravel", text: "Gravel" },
      { id: "mat", text: "Rubber floor mat" },
      { id: "ice", text: "Smooth ice" },
      { id: "snow", text: "Packed snow" },
    ],
    rightFeedback: "Ice has the least friction and the rubber mat has the most. Friction is a force that pushes against sliding.",
    wrong: [
      { position: 0, hint: "Least friction means the smallest pull was needed. Find the smallest number in the table." },
      { position: 1, hint: "After ice, which surface needed the next smallest pull?" },
      { position: 2, hint: "Gravel needed 110 N and the mat needed 150 N. Which comes first?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "The first tow", machine: "Tow Rig", icon: "quake", speaker: "vega",
    line: "Surprise! A wind gust just buried Rover Two's back wheels in a snowdrift. Kai and Nova tied on ropes and pulled forward. The drift holds the rover back.",
    question: "Part 1: How much total force pulls the rover forward? Part 2: What does the rover do? Part 3: Vega hooks up the winch and adds 150 N forward. What is the net force now? Part 4: What does the rover do now?",
    data: {
      title: "Forces on Rover Two",
      columns: ["Force", "Direction", "Newtons"],
      rows: [
        ["Kai's rope", "Forward", "180 N"],
        ["Nova's rope", "Forward", "220 N"],
        ["Snowdrift holding it back", "Backward", "400 N"],
      ],
    },
    parts: [
      { type: "number", prompt: "How much total force pulls the rover forward?", unit: "N" },
      { type: "choice", prompt: "With only Kai and Nova pulling, what does the rover do?", choices: [
        { id: "a", text: "It stays still. The forces are balanced." },
        { id: "b", text: "It moves forward, because two ropes beat one drift." },
        { id: "c", text: "It slides backward into the drift." },
        { id: "d", text: "It moves forward, because no forces act on a stuck rover." },
      ] },
      { type: "number", prompt: "Vega's winch adds 150 N forward. What is the net force on the rover now?", unit: "N" },
      { type: "choice", prompt: "What does the rover do now?", choices: [
        { id: "a", text: "It starts moving forward, because the forces are unbalanced toward the front." },
        { id: "b", text: "It stays still, because the forces are still balanced." },
        { id: "c", text: "It starts moving backward." },
        { id: "d", text: "It moves sideways out of the drift." },
      ] },
    ],
    hint: "Forces in the same direction add. Forces in opposite directions subtract.",
    meter: { heat: 15, label: "Rover freed +15%", story: "Rover Two lurches out of the drift, then snags on an ice ridge" },
    discovery: { id: "springscale", name: "Spring scales", who: "Kai", fact: "A spring scale measures force. When you pull on its hook, a spring inside stretches, and the harder you pull, the farther it stretches." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 400 },
      { kind: "choice", correct: "a" },
      { kind: "number", value: 150 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "400 N forward and 400 N back were balanced. The winch's extra 150 N made the forces unbalanced, and the rover moved!",
    wrong: [
      { step: 1, value: 40, hint: "Both ropes pull forward, in the same direction. Should you add or subtract them?" },
      { step: 1, value: 220, hint: "220 N is only Nova's rope. Kai's rope pulls forward too." },
      { step: 1, value: 0, hint: "Part 1 asks only about the forward pulls. Add Kai's and Nova's ropes." },
      { step: 2, choice: "b", hint: "Two ropes add up to 400 N forward. The drift holds back with 400 N. Is either side stronger?" },
      { step: 2, choice: "c", hint: "The drift pushes back with 400 N, but the ropes pull forward with 400 N. Which side wins?" },
      { step: 2, choice: "d", hint: "A stuck object still has forces on it. Here, they are equal and opposite." },
      { step: 3, value: 550, hint: "550 N is the total forward pull. The drift still pulls back 400 N. What's left over?" },
      { step: 3, value: 950, hint: "The drift pulls the opposite way. Subtract it, don't add it." },
      { step: 3, value: 0, hint: "The winch added a force, so the forces aren't balanced anymore. Forward total minus backward total is how much?" },
      { step: 4, choice: "b", hint: "Forward is now 550 N and backward is 400 N. Are those equal?" },
      { step: 4, choice: "c", hint: "The net force points forward. Which way will the rover move?" },
      { step: 4, choice: "d", hint: "Every pull here is forward or backward. None pushes sideways." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Keep pulling?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "When we tow Rover Two across the frozen lake, the winch has to pull hard the whole way. If we stop pulling, the rover stops right away. Moving things need a force to keep moving!"',
    nova: 'Nova: "On smooth ice, friction is small. I pulled a sled, then let go. It kept sliding. A force changes motion. You don\'t need one just to keep something moving."',
    data: {
      title: "Nova's let-go test: how far the sled slid after she stopped pulling",
      columns: ["Surface", "Distance after letting go"],
      rows: [
        ["Smooth ice", "12 meters"],
        ["Packed snow", "4 meters"],
        ["Gravel", "1 meter"],
      ],
    },
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Did the sled stop the instant Nova let go? What changed from surface to surface?",
    meter: { heat: 5, label: "Rover freed +5%", story: "Kai rethinks the winch plan" },
    discovery: { id: "voyager", name: "Coasting through space", who: "Nova", fact: "The Voyager 1 space probe launched in 1977. Its main rocket stopped firing long ago, but with almost nothing to slow it down, it keeps coasting through space far beyond the planets." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. The sled kept sliding after she stopped pulling, and it slid farthest on ice, where friction is smallest. Friction slows moving things down. They don't stop just because the pull stops." },
      { id: "B", text: "Nova, because ice is cold." },
      { id: "C", text: "Kai. The sled stopped in the end, so it needed a pull the whole time." },
      { id: "D", text: "Kai. Heavy things can't move unless something keeps pushing them." },
    ],
    writtenPrompt: "Tell Kai in your own words why the rover won't stop the moment the winch stops. Use Nova's test.",
    debateHints: {
      wrongWho: "Look at Nova's table. Did the sled stop right away when she let go?",
      wrongReason: "Right person, check the reason. What slowed the sled down, and where did it slide farthest?",
      right: "Nova is right. Friction slowed the sled, and on ice, with little friction, it slid a long way.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The parked rover", machine: "Force Scanner", icon: "scan", speaker: "vega",
    line: "Rover Three is parked on flat ice, not moving at all. Kai says the force scanner is broken because it shows forces on it.",
    question: "Which statement is true about the parked rover?",
    hint: "Does gravity stop pulling when something sits still? What keeps the rover from sinking into the ice?",
    meter: { heat: 5, label: "Rover freed +5%", story: "The force scanner checks out" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Gravity pulls it down and the ice pushes up with an equal force. The forces are balanced, so it stays still." },
      { id: "b", text: "No forces act on it, because it isn't moving." },
      { id: "c", text: "Only gravity acts on it, pulling it down." },
      { id: "d", text: "The forces are unbalanced, but the rover is too heavy to move." },
    ],
    rightFeedback: "The scanner works! A still object can have forces on it. They are just balanced.",
    wrong: [
      { choice: "b", hint: "Gravity pulls on everything, moving or not. What else acts on the rover?" },
      { choice: "c", hint: "If only gravity acted, the rover would sink or fall. What pushes back up?" },
      { choice: "d", hint: "Unbalanced forces change motion, no matter how heavy the object is. Is the rover's motion changing?" },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "The tug-of-war tournament", machine: "Tug Rope", icon: "dial", speaker: "kai",
    line: "We ran a camp tug-of-war tournament to test the new force meters. Four matches, four sets of readings!",
    question: "Part 1: In which matches did the rope move? Part 2: What was the net force in Match C? Part 3: Which way did the rope move in Match C?",
    data: {
      title: "Tournament force readings",
      columns: ["Match", "Left team pull", "Right team pull"],
      rows: [
        ["A", "320 N", "410 N"],
        ["B", "380 N", "380 N"],
        ["C", "500 N", "260 N"],
        ["D", "275 N", "275 N"],
      ],
    },
    parts: [
      { type: "multi", prompt: "Pick every match where the rope moved.", choices: [
        { id: "A", text: "Match A" },
        { id: "B", text: "Match B" },
        { id: "C", text: "Match C" },
        { id: "D", text: "Match D" },
      ] },
      { type: "number", prompt: "What was the net force in Match C?", unit: "N" },
      { type: "choice", prompt: "Which way did the rope move in Match C?", choices: [
        { id: "left", text: "Left, toward the stronger team" },
        { id: "right", text: "Right, toward the weaker team" },
        { id: "none", text: "It didn't move." },
      ] },
    ],
    hint: "The rope moves only when one side pulls harder. Subtract to find the net force.",
    meter: { supplies: 1, label: "Tow lines +1", story: "The force meters pass the test" },
    answer: { kind: "parts", parts: [
      { kind: "multi", correct: ["A", "C"] },
      { kind: "number", value: 240 },
      { kind: "choice", correct: "left" },
    ] },
    rightFeedback: "Matches A and C were unbalanced. In Match C, the net force was 240 N to the left.",
    wrong: [
      { step: 1, pick: "B", hint: "In Match B both teams pulled 380 N. Balanced forces don't change the rope's motion." },
      { step: 1, pick: "D", hint: "In Match D both teams pulled 275 N. Are those forces balanced?" },
      { step: 1, missing: true, hint: "Two matches had unbalanced forces. Check each row." },
      { step: 2, value: 760, hint: "The teams pull in opposite directions. Subtract instead of adding." },
      { step: 2, value: 500, hint: "500 N is the left team's pull. How much is left after the right team pulls back?" },
      { step: 2, value: 90, hint: "90 N is the net force in Match A. Look at Match C." },
      { step: 3, choice: "right", hint: "The net force points toward the team pulling harder. Which team pulled harder in Match C?" },
      { step: 3, choice: "none", hint: "500 N and 260 N are not equal. The forces are unbalanced." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Balloon rockets", machine: "Test Planner", icon: "log", speaker: "nova",
    line: "I built balloon rockets on a string to test a bigger push. I blew a different number of puffs of air into the balloon each time, taped it to a straw on the string, and let go.",
    question: "Part 1: What did Nova change on purpose? Part 2: What did she measure? Part 3: Pick everything she kept the same. Part 4: What does the data show?",
    data: {
      title: "Balloon rocket test (same string, same balloon type, same straw)",
      columns: ["Puffs of air", "Trial 1", "Trial 2", "Trial 3"],
      rows: [
        ["5 puffs", "160 cm", "155 cm", "165 cm"],
        ["10 puffs", "310 cm", "320 cm", "305 cm"],
        ["15 puffs", "470 cm", "460 cm", "475 cm"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What did Nova change on purpose? (the independent variable)", choices: [
        { id: "puffs", text: "The number of puffs of air" },
        { id: "distance", text: "How far the rocket traveled" },
        { id: "string", text: "The length of the string" },
        { id: "balloon", text: "The type of balloon" },
      ] },
      { type: "choice", prompt: "What did Nova measure? (the dependent variable)", choices: [
        { id: "distance", text: "How far the rocket traveled along the string" },
        { id: "puffs", text: "The number of puffs of air" },
        { id: "color", text: "The color of the balloon" },
        { id: "straw", text: "The size of the straw" },
      ] },
      { type: "multi", prompt: "Pick everything Nova kept the same. (the controlled variables)", choices: [
        { id: "string", text: "The string" },
        { id: "balloon", text: "The type of balloon" },
        { id: "straw", text: "The straw" },
        { id: "puffs", text: "The number of puffs" },
        { id: "distance", text: "The distance traveled" },
      ] },
      { type: "choice", prompt: "What does the data show?", choices: [
        { id: "a", text: "More air made a bigger push, so the rocket traveled farther." },
        { id: "b", text: "More air made the rocket travel a shorter distance." },
        { id: "c", text: "The amount of air did not change the distance." },
        { id: "d", text: "The string pulled the rocket along." },
      ] },
    ],
    hint: "The thing you change is the independent variable. The thing you measure is the dependent variable. Everything else stays the same.",
    meter: { heat: 10, label: "Rover freed +10%", story: "Nova's test gives Kai a winch idea" },
    discovery: { id: "rocketpush", name: "Rocket launches", who: "Kai", fact: "A rocket's engines blast hot gas down out of the bottom. The gas pushes back up on the rocket with an equal and opposite force, and that lifts it off the ground." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "puffs" },
      { kind: "choice", correct: "distance" },
      { kind: "multi", correct: ["string", "balloon", "straw"] },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Puffs of air were changed, distance was measured, and everything else stayed the same. A bigger push sent the rocket farther!",
    wrong: [
      { step: 1, choice: "distance", hint: "The distance is what happened after she let go. What did Nova choose before each launch?" },
      { step: 1, choice: "string", hint: "Look at the table title. Did the string change?" },
      { step: 1, choice: "balloon", hint: "Nova used the same balloon type every time. What number changes in the first column?" },
      { step: 2, choice: "puffs", hint: "Nova picked the puffs before each launch. What did she find out after it flew?" },
      { step: 2, choice: "color", hint: "Color isn't in the table. What was written in the Trial columns?" },
      { step: 2, choice: "straw", hint: "The straw stayed the same. What was recorded in the Trial columns?" },
      { step: 3, pick: "puffs", hint: "The puffs are the one thing Nova changed on purpose." },
      { step: 3, pick: "distance", hint: "The distance is what Nova measured. It was different each time." },
      { step: 3, missing: true, hint: "Three things stayed the same. Read the table title." },
      { step: 4, choice: "b", hint: "Compare 5 puffs with 15 puffs. Which one went farther?" },
      { step: 4, choice: "c", hint: "The distances went from about 160 cm to about 470 cm. Did the air matter?" },
      { step: 4, choice: "d", hint: "The string only guides the rocket. What pushed the rocket forward?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The ramp mix-up", machine: "Ramp Lab", icon: "quake", speaker: "vega",
    line: "Surprise! Kai rushed his own test while Nova was out. He wanted to know if a higher ramp gives a cart a bigger push, so it rolls farther across the ice. Kai's note: \"For the last trial I loaded three rocks into the cart. It looked more exciting.\"",
    question: "Part 1: What is wrong with Kai's last trial? Part 2: Which variable should Kai have kept the same? Part 3: Put the steps of a fair ramp test in order. Part 4: Predict: with an empty cart and a 30 cm ramp, how far will it roll?",
    data: {
      title: "Kai's ramp test on the ice",
      columns: ["Ramp height", "Cart", "Distance rolled past the ramp"],
      rows: [
        ["10 cm", "Empty", "120 cm"],
        ["20 cm", "Empty", "230 cm"],
        ["30 cm", "Loaded with 3 rocks", "190 cm"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What is wrong with Kai's last trial?", choices: [
        { id: "a", text: "He changed two things at once, the ramp height and the load, so he can't tell which one changed the result." },
        { id: "b", text: "The ramp was too tall to test." },
        { id: "c", text: "Nothing. It proves higher ramps make carts roll a shorter distance." },
        { id: "d", text: "He should have measured in meters." },
      ] },
      { type: "choice", prompt: "Which variable should Kai have kept the same?", choices: [
        { id: "load", text: "The load in the cart" },
        { id: "height", text: "The ramp height" },
        { id: "distance", text: "The distance rolled" },
      ] },
      { type: "order", prompt: "Put the steps of a fair ramp test in order.", items: [
        { id: "measure", text: "Measure how far the cart rolls past the ramp each time." },
        { id: "question", text: "Ask a question: does ramp height change how far the cart rolls?" },
        { id: "conclude", text: "Compare the results and write a conclusion." },
        { id: "roll", text: "Let the cart go from 10, 20, and 30 cm, three trials each." },
        { id: "controls", text: "Use the same empty cart, the same ramp, and the same ice every time." },
      ] },
      { type: "choice", prompt: "Predict: an empty cart on a 30 cm ramp will roll...", choices: [
        { id: "more", text: "more than 230 cm, because each higher ramp gave the cart a bigger push" },
        { id: "less", text: "less than 120 cm, because higher ramps slow carts down" },
        { id: "same", text: "exactly 190 cm, the same as the loaded cart" },
      ] },
    ],
    hint: "In a fair test, you change only one thing. Look at every column in Kai's table.",
    meter: { heat: 10, label: "Rover freed +10%", story: "Kai reruns the test the fair way" },
    discovery: { id: "bobsled", name: "Bobsled starts", who: "Kai", fact: "Bobsled teams push their sled as hard as they can for the first few seconds, then jump in. Gravity keeps pulling the sled down the icy track, so it speeds up as it goes." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "load" },
      { kind: "order", correct: ["question", "controls", "roll", "measure", "conclude"] },
      { kind: "choice", correct: "more" },
    ] },
    rightFeedback: "You caught Kai's unfair trial and planned a fair test. A higher ramp gives the cart a bigger push, so it should roll farther than 230 cm.",
    wrong: [
      { step: 1, choice: "b", hint: "30 cm isn't too tall. Compare the Cart column in each row." },
      { step: 1, choice: "c", hint: "The last cart was loaded with rocks. Can you blame the ramp for the shorter roll?" },
      { step: 1, choice: "d", hint: "Centimeters work fine. Read Kai's note again." },
      { step: 2, choice: "height", hint: "Ramp height is what Kai wanted to test. It's supposed to change." },
      { step: 2, choice: "distance", hint: "Distance is what Kai measured. What changed that shouldn't have?" },
      { step: 3, position: 0, hint: "Every investigation starts with a question." },
      { step: 3, position: 1, hint: "Before you let the cart go, decide what stays the same." },
      { step: 3, position: 2, hint: "You have to let the cart go before you can measure how far it rolled." },
      { step: 3, position: 3, hint: "Measure each roll before you compare the results." },
      { step: 4, choice: "less", hint: "Going from 10 cm to 20 cm made the empty cart roll farther. What pattern does that show?" },
      { step: 4, choice: "same", hint: "190 cm came from a loaded cart. The question asks about an empty cart." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Get a grip", machine: "Wheel Bay", icon: "shield", speaker: "kai",
    line: "Rover Two's wheels keep spinning on the ice ridge. They can't push against the ground if they just slip.",
    question: "Pick every change that would give the rover's wheels MORE friction on the ice.",
    items: [
      { id: "chains", text: "Wrap metal chains around the tires" },
      { id: "sand", text: "Spread sand and gravel under the wheels" },
      { id: "tread", text: "Switch to tires with deep, bumpy treads" },
      { id: "water", text: "Pour water on the ice so it freezes smooth" },
      { id: "wax", text: "Coat the tires with slippery wax" },
    ],
    hint: "Friction is bigger when surfaces are rough and can grip each other.",
    meter: { supplies: 1, label: "Tow lines +1", story: "The wheels finally grip" },
    discovery: { id: "tirechains", name: "Tire chains", who: "Kai", fact: "In snowy places, drivers sometimes wrap metal chains around their tires. The chains dig into ice and packed snow so the tires grip instead of spinning." },
    answer: { kind: "multi", correct: ["chains", "sand", "tread"] },
    rightFeedback: "Chains, sand, and bumpy treads all make the surfaces rougher, so there's more friction.",
    wrong: [
      { pick: "water", hint: "Smooth, fresh ice is even more slippery. Does that add friction?" },
      { pick: "wax", hint: "People wax skis to help them slide. Does that add grip?" },
      { missing: true, hint: "Three changes make the surfaces rougher. Look again." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Kai's mistake", machine: "Tow Computer", icon: "relay", speaker: "kai",
    line: "I did the math for the winch! It pulls Rover Two forward with 600 N. The snow drags backward on it with 250 N. So the net force is 600 + 250 = 850 N forward. It's going to rocket out!",
    question: "Part 1: What went wrong? Part 2: What is the correct net force? Part 3: What will the rover do?",
    parts: [
      { type: "choice", prompt: "What went wrong with Kai's math?", choices: [
        { id: "a", text: "He added forces that point in opposite directions. He should subtract them." },
        { id: "b", text: "He should have multiplied the forces." },
        { id: "c", text: "Snow drag doesn't count as a force." },
        { id: "d", text: "He should have added another 250 N." },
      ] },
      { type: "number", prompt: "What is the correct net force on the rover?", unit: "N" },
      { type: "choice", prompt: "What will the rover do?", choices: [
        { id: "a", text: "Start moving forward, because the forces are unbalanced toward the winch" },
        { id: "b", text: "Stay still, because the forces are balanced" },
        { id: "c", text: "Slide backward into the snow" },
      ] },
    ],
    hint: "Forward and backward work against each other. How much of the winch's pull is left after the drag?",
    meter: { heat: 10, label: "Rover freed +10%", story: "The tow computer is fixed" },
    discovery: { id: "roadsand", name: "Sand on icy roads", who: "Nova", fact: "In winter, road crews spread sand on icy roads. The rough grains add friction, so tires can grip instead of sliding." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "number", value: 350 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "600 N − 250 N = 350 N forward. Not a rocket, but enough to get the rover moving!",
    wrong: [
      { step: 1, choice: "b", hint: "We combine forces by adding or subtracting, not multiplying. Which way does each force point?" },
      { step: 1, choice: "c", hint: "Drag pushes against the rover's motion, so it is a force. Which way does it point?" },
      { step: 1, choice: "d", hint: "The drag pulls backward. Should it make the net force bigger or smaller?" },
      { step: 2, value: 850, hint: "That's Kai's answer. The drag pulls the opposite way, so subtract it." },
      { step: 2, value: 600, hint: "600 N is only the winch. The snow drags back 250 N." },
      { step: 2, value: 250, hint: "250 N is only the drag. How much of the 600 N pull is left after it?" },
      { step: 3, choice: "b", hint: "600 N forward and 250 N back aren't equal. Are the forces balanced?" },
      { step: 3, choice: "c", hint: "The winch pulls harder than the snow drags. Which way does the net force point?" },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Rank the ropes", machine: "Tow Computer", icon: "grid", speaker: "nova",
    line: "The tow computer tested four rope setups on a practice crate. I need them ranked by net force.",
    question: "Put the rope setups in order from SMALLEST net force to LARGEST net force.",
    hint: "Find the net force for each setup first. Subtract the smaller pull from the larger one.",
    meter: { supplies: 1, label: "Tow lines +1", story: "The strongest setup is picked" },
    answer: { kind: "order", correct: ["n1", "n2", "n3", "n4"] },
    items: [
      { id: "n3", text: "100 N left and 380 N right" },
      { id: "n1", text: "250 N left and 250 N right" },
      { id: "n4", text: "500 N left and 150 N right" },
      { id: "n2", text: "300 N left and 420 N right" },
    ],
    rightFeedback: "0 N, 120 N, 280 N, then 350 N. The net force is the difference between the pulls, whichever way it points.",
    wrong: [
      { position: 0, hint: "A balanced setup has a net force of 0 N. Which setup is balanced?" },
      { position: 1, hint: "420 N − 300 N = 120 N. Is that the next smallest?" },
      { position: 2, hint: "380 N − 100 N = 280 N and 500 N − 150 N = 350 N. Which is smaller?" },
      { position: 3, hint: "The biggest net force can point left. 500 N − 150 N is how much?" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The skate push", machine: "Ice Deck", icon: "trail", speaker: "vega",
    line: "Kai put on ice skates and pushed hard on the side of the heavy rover to help. The rover barely moved, but Kai went sliding backward across the ice!",
    question: "Why did Kai slide backward?",
    hint: "When you push on something, does it push back on you?",
    meter: { heat: 5, label: "Rover freed +5%", story: "Kai learns to plant his feet" },
    discovery: { id: "squidjet", name: "Squid jets", who: "Nova", fact: "A squid can shoot water out of its body in a fast jet. The water pushes back on the squid, zooming it forward through the ocean." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "When Kai pushed on the rover, the rover pushed back on Kai with an equal force in the opposite direction. On slippery skates, that push moved him." },
      { id: "b", text: "The rover is magnetic and pushed Kai away." },
      { id: "c", text: "Only Kai felt a force. The rover felt nothing." },
      { id: "d", text: "The ice pushed Kai backward on its own." },
    ],
    rightFeedback: "Forces come in pairs. Kai pushed the rover, and the rover pushed Kai back just as hard.",
    wrong: [
      { choice: "b", hint: "No magnets here. What happens every time you push on something?" },
      { choice: "c", hint: "Kai's push acted on the rover. What acted on Kai?" },
      { choice: "d", hint: "Kai was standing still until he pushed. What started him moving?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Free Rover Two", machine: "Tow Rig", icon: "relay", speaker: "vega",
    line: "This is it! Rover Two is stuck on the ice ridge, and a storm is coming. The ridge and snow hold it back with 900 N. We have one try. Choose the plan that gets it out.",
    question: "Part 1: What is the net force for Plan B? Part 2: Which plan frees the rover? Part 3: Pick two ways to make the winning plan even stronger. Part 4: Explain your plan to Commander Vega.",
    data: {
      title: "Tow plans (the ridge holds the rover back with 900 N)",
      columns: ["Plan", "Forces pulling forward", "Forces pulling backward"],
      rows: [
        ["A", "Winch 600 N", "Ridge 900 N"],
        ["B", "Winch 600 N + two crew ropes, 200 N each", "Ridge 900 N"],
        ["C", "Winch 600 N", "Ridge 900 N + crew rope tied to the back, 300 N"],
        ["D", "Two crew ropes, 200 N each + tow bot 450 N", "Ridge 900 N"],
      ],
    },
    parts: [
      { type: "number", prompt: "What is the net force on the rover with Plan B?", unit: "N" },
      { type: "choice", prompt: "Which plan frees the rover?", choices: [
        { id: "A", text: "Plan A" },
        { id: "B", text: "Plan B" },
        { id: "C", text: "Plan C" },
        { id: "D", text: "Plan D" },
      ] },
      { type: "multi", prompt: "Pick two ways to make the winning plan even stronger.", choices: [
        { id: "dig", text: "Dig away the snow piled in front of the wheels, so less force holds the rover back" },
        { id: "extra", text: "Add one more crew rope pulling forward" },
        { id: "back", text: "Tie another rope to the back and pull backward" },
        { id: "pile", text: "Pile snow on top of the rover" },
      ] },
      { type: "write", prompt: "Explain to Commander Vega why your plan works. Use net force and the numbers.", minWords: 20 },
    ],
    rubric: ["Names the plan", "Finds the net force with numbers (forward total minus backward total)", "Explains that unbalanced forces toward the front start the rover moving"],
    hint: "For each plan, add the forward forces, add the backward forces, then subtract. The rover moves only if forward wins.",
    meter: { heat: 15, label: "Rover freed +15%", story: "Rover Two rolls free before the storm" },
    discovery: { id: "newtonlaws", name: "Newton's laws", who: "Kai", fact: "In 1687, Isaac Newton published his laws of motion. One says an object keeps doing what it is doing, staying still or moving the same way, unless an unbalanced force acts on it." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 100 },
      { kind: "choice", correct: "B" },
      { kind: "multi", correct: ["dig", "extra"] },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Plan B wins: 1,000 N forward minus 900 N back leaves 100 N forward. Rover Two is free! Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 1000, hint: "1,000 N is the total forward pull. The ridge still pulls back 900 N. What's left?" },
      { step: 1, value: 1900, hint: "The ridge pulls the opposite way. Subtract it instead of adding." },
      { step: 1, value: 300, hint: "Don't forget both crew ropes. 600 N + 200 N + 200 N is how much forward?" },
      { step: 2, choice: "A", hint: "600 N forward against 900 N back. Which side is stronger?" },
      { step: 2, choice: "C", hint: "The rope on the back pulls the wrong way. Add up the backward forces: 900 N + 300 N." },
      { step: 2, choice: "D", hint: "200 N + 200 N + 450 N = 850 N. Is that more than 900 N?" },
      { step: 3, pick: "back", hint: "A backward pull adds to the force holding the rover back." },
      { step: 3, pick: "pile", hint: "More snow on top presses the rover down and adds friction. Does that help it move?" },
      { step: 3, missing: true, hint: "Pick two: one that adds forward force and one that lowers the backward force." },
    ],
  },
};

export default {
  id: "SCI.5.7A-XP",
  standard: "SCI.5.7A-XP",
  engine: "expedition_station",
  title: "The Tug-of-War",
  planet: "Frostveil",
  outpost: "Drift Camp · before the storm",
  grade: 5,
  subject: "Science",
  teks: "5.7A",
  supportingTeks: ["5.7B", "5.1A", "5.1B", "5.1G", "5.2B", "5.2D", "5.3A", "5.3B", "5.3C", "5.5A"],
  skillsChip: "5.7A · Balanced and unbalanced forces",
  iCan: "I can explain how equal and opposite forces act on objects, find the net force in newtons, and predict how unbalanced forces change motion. I can design a fair test of how force affects an object.",
  blurb: "A snowdrift has trapped Rover Two on Frostveil, and a storm is on the way. The crew measures pulls in newtons, tests friction on ice and snow, and uses net force to plan the tow that sets the rover free.",
  mission: "Measure forces, find the net force, run fair tests, and pick the tow plan that frees Rover Two.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 5.70 · FROSTVEIL DRIFT CAMP",
  playableActs: [1, 2, 3],
  earthTrue: "Frostveil, the rover, and the crew are invented. Every force, friction test, balloon rocket, and ramp result works just as it would on Earth.",
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Rover freed", heatUnit: "%", supplies: "Tow lines", suppliesUnit: "lines" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Rover Two is stuck in a snowdrift at Frostveil's Drift Camp.",
    "Pulling harder isn't enough. We need to know exactly how the forces add up.",
    "Forces here work just like they do on Earth. Measure, test, and explain. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Balanced or unbalanced", "Act 2 · Testing forces", "Act 3 · Free the rover"],
    completes: [
      "You found the net force and got Rover Two out of the first drift, {firstName}!",
      "You planned fair tests and caught Kai's ramp mix-up, {firstName}!",
      "Rover Two is free, {firstName}! Your net force plan beat the storm.",
    ],
    teasers: [
      "Next on Frostveil: Kai and Nova argue about keeping the rover moving, and Kai tries a ramp test. Act 2 is open now, or come back to it next time.",
      "Next on Frostveil: the rover is snagged on an ice ridge, and the storm is coming. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Rover Two is loose, but Kai and I disagree about how to tow it.",
      "Let's test some forces.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Rover Two is snagged on an ice ridge, and a storm is closing in.",
      "Get a grip, check the math, and pick the plan that frees it.",
    ],
  }),
  tasks,
};
