// Expedition Station — The Web of Life (SCI.4.12B-XP)
// Grade 4 · Science · Solara (jungle moon). Main standard 4.12B (2024 TEKS:
// describe the cycling of matter and flow of energy through food webs,
// including the roles of the Sun, producers, consumers, and decomposers);
// also practices 4.1G (develop and use models), 4.2B (analyze data for
// patterns), 4.2C (use math to compare data), 4.3A (explanations supported by
// data and models), 4.3B (communicate explanations), 4.3C (respectful
// scientific discussion), 4.5B (cause and effect), 4.5D (parts of a system),
// 4.5E (flow of energy and cycling of matter), 4.5G (stability and change).
//
// Grade 4 focus is WEBS, not single chains (grade 3, food-chain-crew.js) or a
// whole rainforest ecosystem (grade 5, ecosystem-balance.js): many paths, one
// animal in several chains, counting chains through an organism, changes that
// spread across a web, decomposers returning nutrients to the soil, and energy
// entering from the Sun and flowing one way while matter cycles.
//
// Earth-true rule: Solara and the crew are invented. The observatory shows
// REAL Earth food webs (a Texas salt marsh, the Chihuahuan Desert, an East
// Texas forest, and the Gulf of Mexico), and every organism, feeding link, and
// data pattern is real Earth science (webs are simplified to key links).
import { CREW, acts } from "./_shared.js";

const MARSH_WEB = {
  title: "Texas salt marsh: who eats whom",
  columns: ["Living thing", "What it eats in this web"],
  rows: [
    ["Smooth cordgrass", "Nothing. It makes its own food from sunlight."],
    ["Algae", "Nothing. It makes its own food from sunlight."],
    ["Grasshopper", "Cordgrass"],
    ["Periwinkle snail", "Algae and cordgrass leaves"],
    ["Grass shrimp", "Algae"],
    ["Seaside sparrow", "Grasshoppers and cordgrass seeds"],
    ["Blue crab", "Periwinkle snails, grass shrimp, and bits of cordgrass"],
    ["Red drum (a fish)", "Blue crabs and grass shrimp"],
    ["Northern harrier (a hawk)", "Seaside sparrows"],
    ["Bacteria and fungi", "Dead plants, dead animals, and animal waste"],
  ],
};

const DESERT_WEB = {
  title: "Chihuahuan Desert: who eats whom",
  columns: ["Living thing", "What it eats in this web"],
  rows: [
    ["Mesquite tree", "Nothing. It makes its own food from sunlight."],
    ["Prickly pear cactus", "Nothing. It makes its own food from sunlight."],
    ["Kangaroo rat", "Mesquite seeds"],
    ["Jackrabbit", "Mesquite leaves and prickly pear pads"],
    ["Rattlesnake", "Kangaroo rats and jackrabbits"],
    ["Coyote", "Kangaroo rats, jackrabbits, and prickly pear fruit"],
    ["Red-tailed hawk", "Kangaroo rats, jackrabbits, and rattlesnakes"],
  ],
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Jobs in the marsh", machine: "Web Board", icon: "cells", speaker: "nova",
    line: "The telescope is locked on a salt marsh on the Texas coast. I listed who eats whom. Now every living thing needs a job tag.",
    question: "Use the table. Sort each living thing by its role in the food web.",
    hint: "Does it make its own food? Does it eat only plants, only animals, or both? Or does it break down dead things?",
    meter: { heat: 10, label: "Web strength +10%", story: "Every marsh living thing has a job tag" },
    data: MARSH_WEB,
    answer: { kind: "sort", bins: { s1: "producer", s2: "herbivore", s3: "herbivore", s4: "omnivore", s5: "omnivore", s6: "carnivore", s7: "carnivore", s8: "decomposer" } },
    rightFeedback: "Cordgrass is a producer. Grasshoppers and snails eat only plants or algae. Sparrows and blue crabs eat both. Red drum and harriers eat only animals. Bacteria and fungi are decomposers.",
    sort: {
      bins: [
        { id: "producer", label: "Producer" },
        { id: "herbivore", label: "Herbivore" },
        { id: "carnivore", label: "Carnivore" },
        { id: "omnivore", label: "Omnivore" },
        { id: "decomposer", label: "Decomposer" },
      ],
      items: [
        { id: "s1", label: "Smooth cordgrass" },
        { id: "s2", label: "Grasshopper" },
        { id: "s3", label: "Periwinkle snail" },
        { id: "s4", label: "Seaside sparrow" },
        { id: "s5", label: "Blue crab" },
        { id: "s6", label: "Red drum" },
        { id: "s7", label: "Northern harrier" },
        { id: "s8", label: "Bacteria and fungi" },
      ],
    },
    wrong: [
      { item: "s4", hint: "Check the table. The sparrow eats grasshoppers AND cordgrass seeds. An animal that eats both plants and animals is an omnivore." },
      { item: "s5", hint: "Check the table. The blue crab eats snails and shrimp, but also bits of cordgrass. What do we call an animal that eats both?" },
      { item: "s3", hint: "The snail eats algae and cordgrass leaves. Those are producers, so the snail is a plant eater." },
      { item: "s1", hint: "Cordgrass makes its own food from sunlight. What is that role called?" },
      { item: "s2", hint: "The grasshopper eats only cordgrass. What do we call an animal that eats only plants?" },
      { item: "s6", hint: "The red drum eats blue crabs and shrimp. Those are both animals." },
      { item: "s7", hint: "The harrier eats sparrows, which are animals. It doesn't eat plants." },
      { item: "s8", hint: "Bacteria and fungi break down dead things and waste. What is that job called?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "The only way in", machine: "Sky Deck", icon: "battery", speaker: "kai",
    line: "I'm drawing a power map of the marsh. Energy has to get into this web somewhere, and I think there's only one door.",
    question: "Where does energy enter the marsh food web?",
    hint: "Look at the two producers in the table. How do they make their food?",
    meter: { heat: 10, label: "Web strength +10%", story: "The energy door is on the map" },
    discovery: { id: "saltgrass", name: "Salty grass", who: "Nova", fact: "Smooth cordgrass can grow in salty water that would kill most plants. It pushes extra salt out through its leaves, and you can sometimes see tiny salt crystals on them." },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Sunlight, captured by the cordgrass and algae when they make food" },
      { id: "b", text: "The bacteria and fungi, which make brand-new energy from dead things" },
      { id: "c", text: "The red drum, because it is at the top of the web" },
      { id: "d", text: "The salty water, which gives energy to the snails" },
    ],
    rightFeedback: "Producers capture the Sun's energy and store it in food. Every other living thing in the web gets energy from them.",
    wrong: [
      { choice: "b", hint: "Decomposers get energy from dead things, but they don't make new energy. Where did the dead plant get its energy first?" },
      { choice: "c", hint: "The red drum gets its energy from what it eats. Energy flows TO it. Where does the energy start?" },
      { choice: "d", hint: "Salt water gives the snails a place to live, not energy. What do producers use to make food?" },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Chain or web?", machine: "Web Board", icon: "relay", speaker: "kai",
    line: "Nova keeps saying \"food web.\" Isn't a web just a food chain with a fancy name?",
    question: "What makes the marsh a food web instead of one food chain?",
    hint: "Look at the blue crab row. How many things does it eat?",
    meter: { supplies: 1, label: "Paths traced +1", story: "Kai sees the web" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "Many food chains connect, because most living things eat more than one thing or are eaten by more than one thing." },
      { id: "b", text: "A web has more plants than a food chain does." },
      { id: "c", text: "Food webs only happen in water." },
      { id: "d", text: "In a web, the arrows point from the eater to its food." },
    ],
    rightFeedback: "A food web is many food chains woven together. The blue crab alone eats three different things!",
    wrong: [
      { choice: "b", hint: "The number of plants isn't what makes a web. Look at how many things the blue crab eats." },
      { choice: "c", hint: "Deserts and forests have food webs too. What connects the chains?" },
      { choice: "d", hint: "In a web, arrows still point from the food to the eater. They show where energy goes." },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Count the crab's chains", machine: "Path Counter", icon: "trail", speaker: "nova",
    line: "The blue crab shows up all over this web. Let's count how many food chains run through it. Start each chain at a producer and end it at the red drum.",
    question: "How many different food chains pass through the blue crab?",
    unit: "chains",
    hint: "Find every path INTO the blue crab. It eats cordgrass, snails, and shrimp, and the snail eats two different things.",
    meter: { supplies: 1, label: "Paths traced +1", story: "The crab's chains are counted" },
    data: MARSH_WEB,
    discovery: { id: "crabpaddles", name: "Swimming crabs", who: "Kai", fact: "Blue crabs have back legs shaped like flat paddles. They use them to swim through the water, not just to walk." },
    answer: { kind: "number", value: 4 },
    rightFeedback: "Cordgrass → crab, cordgrass → snail → crab, algae → snail → crab, and algae → shrimp → crab. That's 4 chains, and each one goes on to the red drum.",
    wrong: [
      { value: 3, hint: "Close! The snail eats algae AND cordgrass leaves. That makes two paths through the snail." },
      { value: 5, hint: "Algae → grass shrimp → red drum skips the blue crab. Count only chains that pass through the crab." },
      { value: 1, hint: "A web has many paths. List each food the crab eats, then each path that leads to that food." },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Snatched by a red drum", machine: "Sky Deck", icon: "quake", speaker: "vega",
    line: "Surprise! The telescope just caught a red drum grabbing a blue crab in the marsh. Nova wants to trace every path its energy took.",
    question: "Part 1: Put one of the red drum's food chains in order. Part 2: How many food chains end at the red drum? Part 3: Where did the red drum's energy come from first?",
    data: MARSH_WEB,
    parts: [
      { type: "order", prompt: "Put this food chain in order, starting with the producer.", items: [
        { id: "crab", text: "Blue crab" },
        { id: "drum", text: "Red drum" },
        { id: "snail", text: "Periwinkle snail" },
        { id: "algae", text: "Algae" },
      ] },
      { type: "number", prompt: "How many different food chains end at the red drum?", unit: "chains" },
      { type: "choice", prompt: "Where did the red drum's energy come from first?", choices: [
        { id: "a", text: "The Sun. Producers stored its energy, and it passed from eater to eater." },
        { id: "b", text: "The blue crab made the energy itself." },
        { id: "c", text: "The mud at the bottom of the marsh." },
        { id: "d", text: "The red drum makes its own food from sunlight." },
      ] },
    ],
    hint: "The red drum eats blue crabs and grass shrimp. Count the 4 crab chains, then look for a path that skips the crab.",
    meter: { heat: 10, label: "Web strength +10%", story: "Every path to the red drum is traced" },
    discovery: { id: "drumspot", name: "The fake eye", who: "Nova", fact: "Red drum have a black spot near the tail. Scientists think it can fool a predator into attacking the tail instead of the head." },
    answer: { kind: "parts", parts: [
      { kind: "order", correct: ["algae", "snail", "crab", "drum"] },
      { kind: "number", value: 5 },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Five chains feed the red drum, and every one starts with the Sun's energy in a producer.",
    wrong: [
      { step: 1, position: 0, hint: "A food chain starts with a producer. Which one makes food from sunlight?" },
      { step: 1, position: 1, hint: "Check the table. What does the periwinkle snail eat? What eats the snail?" },
      { step: 1, position: 2, hint: "Check the table. Does the red drum eat blue crabs, or do blue crabs eat red drum?" },
      { step: 2, value: 4, hint: "Those are the 4 chains through the crab. The red drum also eats grass shrimp directly. Add that path." },
      { step: 2, value: 7, hint: "7 is every chain in the whole web. Two of them end at the harrier, not the red drum." },
      { step: 2, value: 2, hint: "The red drum eats 2 things, but each of those has more than one path leading to it. Count whole chains." },
      { step: 3, choice: "b", hint: "Animals can't make energy. The crab got its energy from its food. Where did that food get its energy?" },
      { step: 3, choice: "c", hint: "Mud gives no energy to a fish. Follow the chain back to the producer. What powers it?" },
      { step: 3, choice: "d", hint: "Fish can't make food from sunlight. Only producers can. Follow the chain back." },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "Around and around?", machine: "Crew Debate", icon: "debate", speaker: "kai",
    line: 'Kai: "Decomposers are the best recyclers! They send the energy from dead things back to the plants. So energy goes around and around, just like nutrients."',
    nova: 'Nova: "Decomposers send nutrients back to the soil. But energy doesn\'t go around. Plants need new sunlight every single day."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "What happens to the energy an animal uses to run and stay warm? Could a plant ever get that energy back?",
    meter: { heat: 5, label: "Web strength +5%", story: "Kai sorts out matter and energy" },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Matter, like nutrients, cycles back to the plants. But energy flows one way. Living things use it and give it off as heat, so new energy must keep coming from the Sun." },
      { id: "B", text: "Nova, because decomposers are too small to carry energy." },
      { id: "C", text: "Kai. Decomposers turn dead things back into sunlight." },
      { id: "D", text: "Kai. Plants get all of their energy from the soil." },
    ],
    writtenPrompt: "Tell Kai in your own words how matter and energy move differently in a food web.",
    debateHints: {
      wrongWho: "If energy went around and around, would plants still need the Sun? What happens in a dark room?",
      wrongReason: "Right person, check the reason. What happens to the energy living things use?",
      right: "Nova is right. Matter cycles, but energy flows one way, from the Sun, through the web, and out as heat.",
    },
  },
  7: {
    id: 7, act: 2, level: "On level", title: "Cycle or one-way?", machine: "Web Board", icon: "log", speaker: "nova",
    line: "Now the telescope shows an East Texas forest. Some things here go around in a cycle. Other things only go one way.",
    question: "Sort each event: is it matter cycling, or energy flowing one way?",
    hint: "Matter is stuff, like nutrients, soil, and droppings. Energy is sunlight, heat, and the power to move.",
    meter: { supplies: 1, label: "Paths traced +1", story: "The forest events are sorted" },
    answer: { kind: "sort", bins: { f1: "matter", f2: "matter", f3: "energy", f4: "energy", f5: "matter", f6: "energy" } },
    rightFeedback: "Nutrients and droppings are matter that cycles. Sunlight, body heat, and the energy to fly flow one way.",
    sort: {
      bins: [{ id: "matter", label: "Matter cycling" }, { id: "energy", label: "Energy flowing one way" }],
      items: [
        { id: "f1", label: "Nutrients from a rotting log go into the soil" },
        { id: "f2", label: "An oak tree's roots take in nutrients from the soil" },
        { id: "f3", label: "Sunlight gives an oak leaf energy to make food" },
        { id: "f4", label: "A running deer gives off body heat into the air" },
        { id: "f5", label: "Fungi break down a squirrel's droppings into soil" },
        { id: "f6", label: "A hawk uses energy from its meal to fly" },
      ],
    },
    wrong: [
      { item: "f4", hint: "Body heat leaves the deer and goes into the air. No plant can catch it and use it again." },
      { item: "f6", hint: "The hawk uses the energy from its meal up. It can't be passed back to the soil." },
      { item: "f3", hint: "Sunlight is energy. It comes in from the Sun, one way." },
      { item: "f1", hint: "Nutrients are matter. They leave the log and can be used again." },
      { item: "f2", hint: "The roots take in nutrients, which are matter coming back around." },
      { item: "f5", hint: "Droppings become soil. That's matter being used again." },
    ],
  },
  8: {
    id: 8, act: 2, level: "On level", title: "One rat, many chains", machine: "Path Counter", icon: "trail", speaker: "vega",
    line: "The telescope has moved to the Chihuahuan Desert in West Texas. The kangaroo rat is a favorite meal out here.",
    question: "Use the table. Pick every food chain that really is in this desert web and includes the kangaroo rat.",
    data: DESERT_WEB,
    items: [
      { id: "k1", text: "Mesquite → Kangaroo rat → Coyote" },
      { id: "k2", text: "Mesquite → Kangaroo rat → Rattlesnake → Red-tailed hawk" },
      { id: "k3", text: "Mesquite → Kangaroo rat → Red-tailed hawk" },
      { id: "k4", text: "Prickly pear → Kangaroo rat → Coyote" },
      { id: "k5", text: "Mesquite → Jackrabbit → Coyote" },
      { id: "k6", text: "Kangaroo rat → Mesquite → Rattlesnake" },
    ],
    hint: "Check each arrow against the table. Does the eater really eat that food? Is the kangaroo rat in the chain?",
    meter: { supplies: 1, label: "Paths traced +1", story: "The kangaroo rat's chains are traced" },
    discovery: { id: "krat", name: "No drinks needed", who: "Nova", fact: "Kangaroo rats can live their whole lives without drinking water. They get the water they need from the seeds they eat." },
    answer: { kind: "multi", correct: ["k1", "k2", "k3"] },
    rightFeedback: "The kangaroo rat is in three chains. Coyotes, rattlesnakes, and hawks all depend on it.",
    wrong: [
      { pick: "k4", hint: "Check the table. What does the kangaroo rat eat? Does it eat prickly pear?" },
      { pick: "k5", hint: "That is a real desert chain, but is the kangaroo rat in it?" },
      { pick: "k6", hint: "Kangaroo rats eat mesquite seeds. Which way should that arrow point?" },
      { missing: true, hint: "There are three good chains. Check who eats the kangaroo rat: the coyote, the rattlesnake, and the hawk." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "The missing recyclers", machine: "Web Board", icon: "snap", speaker: "kai",
    line: "Back to the forest! My web board has plants and animals, but no decomposers. On this board, arrows show where matter goes.",
    question: "Pick every arrow Kai should add to show decomposers returning matter to the web.",
    items: [
      { id: "a1", text: "Dead oak leaves → Fungi" },
      { id: "a2", text: "Dead deer → Bacteria" },
      { id: "a3", text: "Fungi → Nutrients in the soil" },
      { id: "a4", text: "Nutrients in the soil → Oak tree roots" },
      { id: "a5", text: "Fungi → The Sun" },
      { id: "a6", text: "Nutrients in the soil → Hawk" },
    ],
    hint: "Decomposers eat dead things and waste. Then where do the nutrients go? Who can take them in?",
    meter: { heat: 5, label: "Web strength +5%", story: "The decomposers join the forest web" },
    discovery: { id: "dungbeetle", name: "Dung beetles", who: "Kai", fact: "Dung beetles roll animal droppings into balls and bury them. This puts nutrients back into the soil and helps plants grow." },
    answer: { kind: "multi", correct: ["a1", "a2", "a3", "a4"] },
    rightFeedback: "Dead things go to decomposers, nutrients go into the soil, and plant roots take them back up. The matter loop is closed!",
    wrong: [
      { pick: "a5", hint: "Nothing sends matter or energy back to the Sun. Where do decomposers put the nutrients?" },
      { pick: "a6", hint: "Hawks can't take in nutrients from soil. Which living things have roots?" },
      { missing: true, hint: "There are four arrows. Think: dead things to decomposers, decomposers to soil, soil to plants." },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "The rainy year", machine: "Population Log", icon: "static", speaker: "vega",
    line: "Surprise! The Chihuahuan Desert just had its rainiest year in a long time. Nova has been counting animals in one study area.",
    question: "Part 1: How many more kangaroo rats were there in Year 2 than in Year 1? Part 2: Why did the kangaroo rats go up? Part 3: Why did the rattlesnakes and coyotes go up in Year 3? Part 4: Predict what happens if Year 4 is very dry.",
    data: {
      title: "Desert study area counts",
      columns: ["Year", "Rain", "Mesquite seeds", "Kangaroo rats", "Rattlesnakes", "Coyotes"],
      rows: [
        ["1", "Dry", "Few", "40", "6", "3"],
        ["2", "Very rainy", "Many", "95", "7", "4"],
        ["3", "Normal", "Some", "70", "11", "6"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many more kangaroo rats were there in Year 2 than in Year 1?", unit: "kangaroo rats" },
      { type: "choice", prompt: "Why did the kangaroo rats go up in Year 2?", choices: [
        { id: "a", text: "The rain helped the mesquite trees make many seeds, so the kangaroo rats had more food." },
        { id: "b", text: "The rain washed the rattlesnakes away." },
        { id: "c", text: "Kangaroo rats drink rainwater to grow bigger." },
        { id: "d", text: "The coyotes brought them more food." },
      ] },
      { type: "choice", prompt: "Why did the rattlesnakes and coyotes go up in Year 3?", choices: [
        { id: "a", text: "There were more kangaroo rats to eat, so more young predators survived." },
        { id: "b", text: "Rattlesnakes and coyotes eat mesquite seeds." },
        { id: "c", text: "The rain made new rattlesnakes." },
        { id: "d", text: "The kangaroo rats went down, so the predators went up." },
      ] },
      { type: "multi", prompt: "Predict: Year 4 is very dry. Pick every likely result.", choices: [
        { id: "seeds", text: "The mesquite trees make fewer seeds." },
        { id: "rats", text: "The kangaroo rats go down because they have less food." },
        { id: "later", text: "Later, the rattlesnakes and coyotes go down too." },
        { id: "morerats", text: "The kangaroo rats go up." },
        { id: "nochange", text: "Nothing changes for the predators, because they don't eat seeds." },
      ] },
    ],
    hint: "Follow the web from the bottom up: rain, then seeds, then kangaroo rats, then the animals that eat them.",
    meter: { heat: 10, label: "Web strength +10%", story: "The crew tracks the rainy year through the web" },
    discovery: { id: "heatpits", name: "Heat-seeing snakes", who: "Nova", fact: "Rattlesnakes have heat-sensing pits on their faces. They can find warm animals, like kangaroo rats, even in the dark." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 55 },
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["seeds", "rats", "later"] },
    ] },
    rightFeedback: "One rainy year spread up the whole web: more seeds, then more kangaroo rats, then more predators.",
    wrong: [
      { step: 1, value: 95, hint: "95 is how many there were in Year 2. How many MORE than in Year 1?" },
      { step: 1, value: 135, hint: "You want the difference. Should you add or subtract?" },
      { step: 1, value: 40, hint: "40 is the Year 1 count. How much did the number go up?" },
      { step: 2, choice: "b", hint: "Check the Rattlesnakes column. Did the rattlesnakes go away in Year 2?" },
      { step: 2, choice: "c", hint: "Kangaroo rats get their water from seeds. Check the Mesquite seeds column." },
      { step: 2, choice: "d", hint: "Coyotes eat kangaroo rats. They don't feed them. Check the Mesquite seeds column." },
      { step: 3, choice: "b", hint: "Check the desert table. What do rattlesnakes and coyotes eat?" },
      { step: 3, choice: "c", hint: "Rain can't make animals. What happened to the predators' food in Year 2?" },
      { step: 3, choice: "d", hint: "The kangaroo rats had just jumped way up in Year 2. More food means what for predators?" },
      { step: 4, pick: "morerats", hint: "In the dry Year 1, there were few seeds. What happens to kangaroo rats with little food?" },
      { step: 4, pick: "nochange", hint: "Predators don't eat seeds, but their food does. What happens to predators when kangaroo rats go down?" },
      { step: 4, missing: true, hint: "There are three results. Follow the change from seeds, to kangaroo rats, to predators." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Kai's bear blunder", machine: "Web Board", icon: "snap", speaker: "kai",
    line: "I watched a black bear in the East Texas forest catch a fish. So I put black bears with the carnivores. Easy!",
    question: "Nova's notes say this week the bear ate blackberries, acorns, grass, ants, and one fish. Part 1: What did Kai get wrong? Part 2: How should Kai fix his sort?",
    data: {
      title: "Kai's sort",
      columns: ["Producers", "Herbivores", "Carnivores", "Omnivores", "Decomposers"],
      rows: [
        ["Oak tree", "White-tailed deer", "Barred owl", "Raccoon", "Fungi"],
        ["Blackberry bush", "Gray squirrel", "Black bear", "", "Bacteria"],
      ],
    },
    parts: [
      { type: "choice", prompt: "What did Kai get wrong?", choices: [
        { id: "a", text: "The bear eats plants and animals, so it is not a carnivore. Kai used only one meal to decide." },
        { id: "b", text: "Black bears only eat plants, so they are herbivores." },
        { id: "c", text: "The owl should be a producer because it lives in a tree." },
        { id: "d", text: "Kai didn't get anything wrong. Catching a fish makes the bear a carnivore." },
      ] },
      { type: "choice", prompt: "How should Kai fix his sort?", choices: [
        { id: "a", text: "Move the black bear to the Omnivores column, next to the raccoon." },
        { id: "b", text: "Move the black bear to the Herbivores column." },
        { id: "c", text: "Move the black bear to the Decomposers column." },
        { id: "d", text: "Move the raccoon to the Carnivores column, next to the bear." },
      ] },
    ],
    hint: "Read Nova's notes. Count how many of the bear's foods are plants and how many are animals.",
    meter: { supplies: 1, label: "Paths traced +1", story: "Kai's sort is fixed" },
    discovery: { id: "bearfood", name: "Berry-loving bears", who: "Nova", fact: "Black bears eat mostly plants, like berries, acorns, and grasses. Insects and meat are only a small part of what they eat." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "One fish doesn't make a carnivore. The bear eats plants and animals, so it's an omnivore.",
    wrong: [
      { step: 1, choice: "b", hint: "Look at Nova's notes again. Ants and a fish are animals." },
      { step: 1, choice: "c", hint: "Owls hunt mice and other animals. They can't make food from sunlight. Look at the bear instead." },
      { step: 1, choice: "d", hint: "Read Nova's notes. Is fish the only thing the bear eats?" },
      { step: 2, choice: "b", hint: "Herbivores eat only plants. The bear also ate ants and a fish." },
      { step: 2, choice: "c", hint: "Decomposers break down dead things. The bear eats living plants and animals." },
      { step: 2, choice: "d", hint: "Raccoons eat plants and animals, so the raccoon is already in the right place. Which card is wrong?" },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Out in the Gulf", machine: "Sky Deck", icon: "water", speaker: "nova",
    line: "The telescope is over the Gulf of Mexico. Out here, the producers are so tiny you need a microscope to see them.",
    question: "Put this Gulf food chain in order. Start where the energy comes from.",
    hint: "Energy starts at the Sun. Then find the producer, and then who eats whom.",
    meter: { supplies: 1, label: "Paths traced +1", story: "A Gulf food chain is traced" },
    discovery: { id: "phyto", name: "Tiny ocean producers", who: "Nova", fact: "Tiny ocean producers called phytoplankton make about half of the oxygen on Earth. They float near the surface, where sunlight reaches them." },
    answer: { kind: "order", correct: ["sun", "phyto", "copepod", "menhaden", "pelican"] },
    items: [
      { id: "menhaden", text: "Menhaden (a small fish that eats copepods)" },
      { id: "sun", text: "The Sun" },
      { id: "pelican", text: "Brown pelican (a bird that eats menhaden)" },
      { id: "copepod", text: "Copepods (tiny animals that eat phytoplankton)" },
      { id: "phyto", text: "Phytoplankton (tiny producers)" },
    ],
    rightFeedback: "Sun → phytoplankton → copepods → menhaden → brown pelican. Even ocean webs run on sunlight.",
    wrong: [
      { position: 0, hint: "Where does the energy for every food chain come from first?" },
      { position: 1, hint: "The producer comes right after the Sun. Which one makes its own food?" },
      { position: 2, hint: "Copepods eat phytoplankton. Menhaden eat copepods. Which comes first?" },
      { position: 3, hint: "The brown pelican eats menhaden, so it comes last." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Fewer menhaden", machine: "Prediction Pad", icon: "grid", speaker: "vega",
    line: "Menhaden are a big part of the Gulf web. Lots of animals eat them. What if their numbers suddenly dropped?",
    question: "Predict: if most of the menhaden in a bay disappeared, what could happen across the web? Pick every one.",
    data: {
      title: "Gulf web: menhaden links",
      columns: ["Living thing", "Link to menhaden"],
      rows: [
        ["Copepods", "Eaten by menhaden"],
        ["Brown pelican", "Eats menhaden"],
        ["Bottlenose dolphin", "Eats menhaden and other fish"],
        ["Osprey", "Eats menhaden and other fish"],
        ["Red drum", "Eats menhaden, crabs, and shrimp"],
      ],
    },
    items: [
      { id: "pelicans", text: "Brown pelicans have less food and may raise fewer chicks." },
      { id: "switch", text: "Dolphins, ospreys, and red drum eat more of their other foods." },
      { id: "copepods", text: "Copepods could increase, because fewer menhaden eat them." },
      { id: "nothing", text: "Nothing changes, because only menhaden were affected." },
      { id: "sun", text: "The Sun sends less energy to the bay." },
      { id: "plants", text: "Pelicans start eating phytoplankton instead." },
    ],
    hint: "Look at the table. Who eats menhaden? Who do menhaden eat?",
    meter: { heat: 10, label: "Web strength +10%", story: "The crew predicts the menhaden ripple" },
    discovery: { id: "pelicandive", name: "Diving pelicans", who: "Kai", fact: "Brown pelicans dive headfirst into the water from high in the air. They scoop up fish in the stretchy pouch under their bill." },
    answer: { kind: "multi", correct: ["pelicans", "switch", "copepods"] },
    rightFeedback: "One change ripples both ways: the menhaden's eaters lose food, and the copepods they ate can increase.",
    wrong: [
      { pick: "nothing", hint: "In a web, living things are connected. Look at the table. Who depends on menhaden?" },
      { pick: "sun", hint: "Fish can't change the Sun. Think about who eats menhaden and who menhaden eat." },
      { pick: "plants", hint: "Brown pelicans are fish eaters. They can't live on tiny producers." },
      { missing: true, hint: "There are three changes. Think about the eaters that lose food AND the food that is eaten less." },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "The sealed globe", machine: "Test Bay", icon: "flask", speaker: "nova",
    line: "On Earth, people build sealed glass globes with salt water, algae, tiny shrimp, and bacteria inside. Nothing can go in or out through the glass except light and heat. Some globes last for years!",
    question: "Part 1: What must keep coming in from outside for the globe to stay alive? Part 2: What would happen if the globe sat in a dark closet for months?",
    parts: [
      { type: "choice", prompt: "What must keep coming in from outside the globe?", choices: [
        { id: "a", text: "Light energy, so the algae can keep making food" },
        { id: "b", text: "New food for the shrimp every week" },
        { id: "c", text: "New nutrients for the algae" },
        { id: "d", text: "Nothing at all. Energy is recycled inside, just like matter." },
      ] },
      { type: "choice", prompt: "What would happen if the globe sat in a dark closet for months?", choices: [
        { id: "a", text: "The algae couldn't make food, so the shrimp would run out of food too." },
        { id: "b", text: "The bacteria would make new energy, so everything would be fine." },
        { id: "c", text: "The shrimp would start making their own food." },
        { id: "d", text: "Nothing would change, because the globe is sealed." },
      ] },
    ],
    hint: "Inside the globe, shrimp eat algae, and bacteria break down waste into nutrients. What can't be made inside?",
    meter: { heat: 5, label: "Web strength +5%", story: "The sealed globe proves the big idea" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "a" },
    ] },
    rightFeedback: "Matter cycles inside the globe, but energy flows one way. It needs new light to keep the web alive.",
    wrong: [
      { step: 1, choice: "b", hint: "The globe is sealed, so no food can go in. The shrimp eat algae. What do the algae need?" },
      { step: 1, choice: "c", hint: "Bacteria break down waste into nutrients inside the globe. Matter cycles. What can't be recycled?" },
      { step: 1, choice: "d", hint: "Energy is not recycled. Living things give it off as heat. What has to keep coming in?" },
      { step: 2, choice: "b", hint: "Decomposers can't make new energy. Where does all the energy in the globe start?" },
      { step: 2, choice: "c", hint: "Shrimp are consumers. Only producers can make food, and they need light." },
      { step: 2, choice: "d", hint: "Sealed means no matter gets in or out. But what does the dark closet take away?" },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "The bare mud mystery", machine: "Population Log", icon: "relay", speaker: "vega",
    line: "Surprise! Part of the Texas salt marsh is turning into bare mud. Nova checked her study plots, and the blue crab counts have dropped. Can you predict what comes next?",
    question: "Part 1: How many more snails were there in Year 3 than in Year 1? Part 2: Why did the snails go up? Part 3: Predict: pick every likely effect across the web. Part 4: Write 2–3 sentences to Commander Vega explaining how one change spread through the web. Use the table.",
    data: {
      title: "Salt marsh study plots",
      columns: ["Year", "Blue crabs (per plot)", "Periwinkle snails (per square meter)", "Cordgrass cover"],
      rows: [
        ["1", "20", "50", "90%"],
        ["2", "8", "300", "70%"],
        ["3", "3", "600", "35%"],
      ],
    },
    parts: [
      { type: "number", prompt: "How many more snails per square meter were there in Year 3 than in Year 1?", unit: "snails" },
      { type: "choice", prompt: "Why did the snails go up?", choices: [
        { id: "a", text: "There were fewer blue crabs to eat them." },
        { id: "b", text: "The cordgrass was growing better." },
        { id: "c", text: "The snails started eating blue crabs." },
        { id: "d", text: "The red drum brought the snails more food." },
      ] },
      { type: "multi", prompt: "Predict: pick every likely effect across the marsh web.", choices: [
        { id: "hoppers", text: "Grasshoppers have less cordgrass to eat." },
        { id: "sparrows", text: "Seaside sparrows lose food and places to nest in the grass." },
        { id: "drum", text: "Red drum have fewer blue crabs to eat." },
        { id: "moregrass", text: "The cordgrass grows back thicker than ever." },
        { id: "harriers", text: "Northern harriers find more sparrows to eat." },
      ] },
      { type: "write", prompt: "Explain to Commander Vega how the drop in blue crabs spread through the marsh web. Use the table.", minWords: 20 },
    ],
    rubric: ["Says fewer blue crabs meant more snails", "Explains that more snails ate more cordgrass, so the cordgrass shrank", "Uses numbers from the table as evidence", "Names at least one other living thing affected across the web"],
    hint: "Read each column from Year 1 to Year 3. When one number goes down, which one goes up? Then check the web table: who needs cordgrass?",
    meter: { heat: 15, label: "Web strength +15%", story: "The crew cracks the bare mud mystery" },
    discovery: { id: "cranecrabs", name: "Whooping crane winters", who: "Nova", fact: "Endangered whooping cranes spend the winter in salt marshes on the Texas coast. Blue crabs are one of their most important winter foods." },
    answer: { kind: "parts", parts: [
      { kind: "number", value: 550 },
      { kind: "choice", correct: "a" },
      { kind: "multi", correct: ["hoppers", "sparrows", "drum"] },
      { kind: "write", minWords: 20 },
    ] },
    rightFeedback: "Mystery solved! Fewer crabs meant more snails, more snails meant less cordgrass, and the change spread across the web. Your teacher will read your explanation.",
    wrong: [
      { step: 1, value: 600, hint: "600 is the Year 3 count. How many MORE than in Year 1?" },
      { step: 1, value: 650, hint: "You want the difference between the years. Should you add or subtract?" },
      { step: 1, value: 50, hint: "50 is the Year 1 count. How much did the number go up?" },
      { step: 2, choice: "b", hint: "Check the Cordgrass cover column. Was the cordgrass growing better or worse?" },
      { step: 2, choice: "c", hint: "Blue crabs eat snails, not the other way around. Check the Blue crabs column." },
      { step: 2, choice: "d", hint: "Red drum eat blue crabs. They don't feed snails. What eats snails?" },
      { step: 3, pick: "moregrass", hint: "Check the Cordgrass cover column. With more snails eating it, what is happening to the cordgrass?" },
      { step: 3, pick: "harriers", hint: "If sparrows lose food and nests, will there be more sparrows or fewer for the harriers?" },
      { step: 3, missing: true, hint: "There are three effects. Think about who eats cordgrass, who nests in it, and who eats blue crabs." },
    ],
  },
};

export default {
  id: "SCI.4.12B-XP",
  standard: "SCI.4.12B-XP",
  engine: "expedition_station",
  title: "The Web of Life",
  planet: "Solara",
  outpost: "Canopy Observatory · web watch",
  grade: 4,
  subject: "Science",
  teks: "4.12B",
  supportingTeks: ["4.1G", "4.2B", "4.2C", "4.3A", "4.3B", "4.3C", "4.5B", "4.5D", "4.5E", "4.5G"],
  skillsChip: "4.12B · Food webs",
  iCan: "I can describe how energy flows from the Sun through a food web and how matter cycles back to the soil. I can explain the roles of producers, consumers, and decomposers.",
  blurb: "From the treetop observatory on Solara, the crew points the telescope at real Earth food webs: a Texas salt marsh, a desert, a forest, and the Gulf of Mexico. They trace the paths, count the chains, and predict what happens when one living thing changes.",
  mission: "Trace the paths in real Earth food webs, follow the Sun's energy one way, and show how decomposers send matter back around.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 4.12 · SOLARA CANOPY OBSERVATORY",
  playableActs: [1, 2, 3],
  earthTrue: "Solara and the crew are invented. Every food web the telescope shows is a real place on Earth, and every living thing, feeding link, and data pattern is real Earth science.",
  meterStart: { heat: 30, supplies: 0, journal: 0 },
  meterLabels: { heat: "Web strength", heatUnit: "%", supplies: "Paths traced", suppliesUnit: "paths" },
  journalMax: 10,
  opening: [
    "Specialist {firstName}, this is Commander Vega. Our observatory in Solara's jungle is pointed at Earth again.",
    "This time we're studying food webs, where many food chains cross and connect. First stop: a salt marsh on the Texas coast.",
    "Trace every path, follow the Sun's energy, and find out where the matter goes. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Trace the marsh web", "Act 2 · Matter, energy, and the desert", "Act 3 · Ripples across the web"],
    completes: [
      "You traced every path to the red drum, {firstName}!",
      "You sorted matter from energy and tracked a rainy year through the desert, {firstName}!",
      "You solved the bare mud mystery, {firstName}! Mission complete.",
    ],
    teasers: [
      "Next on Solara: Kai thinks energy goes around and around, and the telescope heads to the desert. Act 2 is open now, or come back to it next time.",
      "Next on Solara: Kai sorts a black bear, the telescope dives into the Gulf, and part of the marsh turns to mud. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Kai has a big idea about decomposers, and I don't agree with it.",
      "Then we'll visit a forest and a desert to follow matter and energy.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. In a food web, one change can ripple a long way.",
      "Let's see how far those ripples go.",
    ],
  }),
  tasks,
};
