// Expedition Station — The Word Garden (ELA.3.3B-XP)
// Grade 3 · ELAR · Lumara (glowing garden). Main standard 3.3B (use context
// within and beyond a sentence to find the meaning of unfamiliar and
// multiple-meaning words); also practices 3.3C (affixes: im-, non-, dis-, in-,
// pre-, -ness, -y, -ful) and 3.3D (synonyms, antonyms, idioms, homographs).
// All passages are original, written for this quest: a gardener's guide, a
// short story about a lost glow-seed, a garden newsletter, and two messages
// with wrongly used words.
import { CREW, acts, passage, editText } from "./_shared.js";

const passages = {
  A: passage("A", { title: "Gardener Pim's Guide to the Glow Garden", genre: "Guide (informational)" }, [
    [
      "Welcome to the Glow Garden on Lumara!",
      "Every plant here is luminous.",
      "At night, the leaves give off a soft light, like tiny lamps.",
      "You can even read a book by their glow.",
    ],
    [
      "The glow-trees have silver bark.",
      "The bark is rough and thick, and it keeps the tree safe, the way your skin keeps you safe.",
      "Please do not peel it off.",
    ],
    [
      "The garden sits on the bank of the Shimmer Stream.",
      "The ground there is soft and muddy, so step with care.",
      "A spring bubbles up from under a big rock and fills the stream with fresh water.",
    ],
    [
      "To plant a glow-seed, dig a hole as deep as your thumb.",
      "Glow-seeds are light, so hold them tight, or the wind will carry them off.",
      "Water them every morning, and they will sprout in a few days.",
    ],
  ]),
  B: passage("B", { title: "The Lost Glow-Seed", genre: "Short story" }, [
    [
      "Juniper had one glow-seed left, and it was the brightest seed in the whole garden.",
      "She kept it in a tiny pouch tied with a blue bow.",
      "One windy morning, she opened the pouch, and the seed was gone!",
    ],
    [
      "Juniper felt dejected.",
      "Her shoulders drooped, and a tear rolled down her cheek.",
      "\"I will never find it,\" she sighed.",
    ],
    [
      "Her friend Tam put a hand on her arm.",
      "\"Keep your chin up,\" he said. \"We will look together.\"",
      "They searched high and low, from the berry bushes to the stream.",
    ],
    [
      "At last, Tam spotted a faint twinkle under a leaf.",
      "It was not bright, but it was not dark, either.",
      "Juniper scooped up the seed and grinned from ear to ear.",
      "She planted it that very day, close to the spring.",
    ],
  ]),
  C: passage("C", { title: "The Glow Garden News", genre: "Newsletter" }, [
    [
      "This week, the glow-moths flew nonstop from sunset to sunrise.",
      "Their brightness lit up the leafy paths.",
      "By morning, they seemed to disappear, but they were only resting under the leaves.",
    ],
    [
      "Gardeners, please be careful near the muddy bank.",
      "Some glow-roots are almost invisible in the dark, and it is easy to trip on them.",
      "Presoak your glow-seeds in water for one hour before you plant them.",
    ],
    [
      "Next week, our helpers will import new soil into the garden in big carts.",
      "Rocks and old shells are nonliving, but they help the garden, too.",
      "Please do not dislike the glow-snails! They are helpful because they eat dead leaves.",
    ],
  ]),
  D: {
    id: "D",
    title: "Kai's garden sign",
    genre: "Sign (has mistakes)",
    ...editText(
      "D",
      "Welcome to the Glow Garden! Please be {careless} near the muddy bank. Glow-seeds are {heavy}, so hold them tight when the wind blows. {Postsoak} your seeds in water before you plant them. Some roots are {visible} in the dark, so watch your step.",
      {
        careless: ["careful", "cared"],
        heavy: ["light", "dark"],
        Postsoak: ["Presoak", "Resoak"],
        visible: ["invisible", "visibly"],
      }
    ),
  },
  F: {
    id: "F",
    title: "Mission Report draft",
    genre: "Report (has mistakes)",
    ...editText(
      "F",
      "The Glow Garden sits on the {bench} of the Shimmer Stream. A {fall} bubbles up from under a big rock and fills the stream. When Juniper lost her last glow-seed, she felt {hopeful}. The seed was almost {unvisible} under a leaf, but Tam found it.",
      {
        bench: ["bank", "bark"],
        fall: ["spring", "summer"],
        hopeful: ["hopeless", "helpful"],
        unvisible: ["invisible", "nonvisible"],
      }
    ),
  },
};

const tasks = {
  1: {
    id: 1, act: 1, level: "Warm-up", title: "Glow-word decoder", machine: "Word Lens", icon: "static", speaker: "vega", passage: ["A"],
    line: "Pim's guide uses a word I don't know: luminous. Kai wants to skip it. Let's use the sentences around it instead.",
    question: "Read paragraph 1 of Passage A. \"Every plant here is luminous.\" What does luminous mean?",
    hint: "Read the next two sentences. What do the leaves give off at night?",
    meter: { heat: 10, label: "Glow bloom +10%", story: "The first glow-bud opens" },
    answer: { kind: "choice", correct: "b" },
    choices: [
      { id: "a", text: "Very tall" },
      { id: "b", text: "Giving off light" },
      { id: "c", text: "Soft and fuzzy" },
      { id: "d", text: "Easy to read" },
    ],
    rightFeedback: "Right! The next sentences tell us the leaves glow like tiny lamps, so luminous means giving off light.",
    wrong: [
      { choice: "a", hint: "Nothing in the paragraph tells how tall the plants are. What do the leaves do at night?" },
      { choice: "c", hint: "The paragraph says the LIGHT is soft, not the plants. What do the leaves give off?" },
      { choice: "d", hint: "You can read a book by the glow, but the plants are not books. What makes reading possible at night?" },
    ],
  },
  2: {
    id: 2, act: 1, level: "Warm-up", title: "Not that kind of bark", machine: "Clue Finder", icon: "scan", speaker: "kai", passage: ["A"],
    line: "The guide says glow-trees have silver bark. Trees don't bark like dogs! Wait... maybe bark means something else here?",
    question: "Bark can mean a dog's sound or the outer covering of a tree. Highlight the sentence that proves bark means the tree's covering in Passage A.",
    hint: "Find the sentence that tells what the bark feels like and what it does for the tree.",
    meter: { heat: 10, label: "Glow bloom +10%", story: "Kai stops barking at the trees" },
    discovery: { id: "treebark", name: "Tree bark", who: "Nova", fact: "Bark is like a tree's skin. It protects the tree from insects, bad weather, and hungry animals." },
    answer: { kind: "highlight", groups: [["A2.2"]] },
    rightFeedback: "Found it! Rough, thick bark that keeps the tree safe, like skin, is the tree's covering.",
    wrong: [
      { sentence: "A2.1", hint: "That sentence uses the word bark, but it only tells the color. Which sentence tells what the bark is like and what it does?" },
      { sentence: "A2.3", hint: "That tells us not to peel it off. Which sentence compares bark to skin?" },
      { sentence: "A1.3", hint: "That is about the leaves. Look in paragraph 2, where the bark is." },
    ],
  },
  3: {
    id: 3, act: 1, level: "Warm-up", title: "Light or light?", machine: "Sort Bay", icon: "cells", speaker: "nova", passage: ["A"],
    line: "Light is a tricky word. It can mean a glow you can see, or it can mean not heavy. Help me sort my garden notes.",
    question: "Sort each sentence. Which meaning of light fits?",
    hint: "Ask: is the sentence about how something LOOKS, or about how much it WEIGHS?",
    meter: { heat: 5, label: "Glow bloom +5%", story: "Nova's notes are sorted" },
    discovery: { id: "foxfire", name: "Glowing mushrooms", who: "Kai", fact: "Some mushrooms glow in the dark with a soft green light. People sometimes call this glow foxfire." },
    answer: { kind: "sort", bins: { l1: "glow", l2: "weight", l3: "glow", l4: "weight", l5: "glow", l6: "weight" } },
    rightFeedback: "Sorted! Glowing leaves and lamps give off light. Seeds and petals that float away are light, not heavy.",
    sort: {
      bins: [{ id: "glow", label: "Light = a glow you can see" }, { id: "weight", label: "Light = not heavy" }],
      items: [
        { id: "l1", label: "At night, the leaves give off a soft light." },
        { id: "l2", label: "Glow-seeds are light, so the wind can carry them off." },
        { id: "l3", label: "Turn off your lamp and read by the light of the glow-trees." },
        { id: "l4", label: "The basket was so light that Juniper carried it with one finger." },
        { id: "l5", label: "The light from the moss turned the path green." },
        { id: "l6", label: "A petal is light enough to float on the stream." },
      ],
    },
    wrong: [
      { item: "l1", hint: "Leaves that give off a soft light are glowing. Is that about weight or something you see?" },
      { item: "l2", hint: "The wind can carry the seeds. Is that because they glow, or because they don't weigh much?" },
      { item: "l3", hint: "You can read BY this light. Is that about weight?" },
      { item: "l4", hint: "Carrying a basket with one finger is about weight. Does it weigh a lot?" },
      { item: "l5", hint: "Light that turns a path green is something you see." },
      { item: "l6", hint: "Floating on water is about weight. Is the petal heavy?" },
    ],
  },
  4: {
    id: 4, act: 1, level: "Warm-up", title: "Which bank?", machine: "Word Lens", icon: "static", speaker: "vega", passage: ["A"],
    line: "The guide says the garden sits on the bank of the Shimmer Stream. I don't think Pim keeps money in the stream.",
    question: "\"The garden sits on the bank of the Shimmer Stream.\" What does bank mean here?",
    hint: "Read the next sentence too. What is the ground like there?",
    meter: { supplies: 1, label: "Word seeds +1", story: "Vega plants a word seed by the stream" },
    answer: { kind: "choice", correct: "a" },
    choices: [
      { id: "a", text: "The land along the side of a stream" },
      { id: "b", text: "A place where people keep money" },
      { id: "c", text: "To tip to one side while flying" },
      { id: "d", text: "A big box for keeping seeds" },
    ],
    rightFeedback: "Yes! The next sentence says the ground there is soft and muddy. That's the land beside the stream.",
    wrong: [
      { choice: "b", hint: "That is one meaning of bank. But would a money bank be soft and muddy ground next to a stream?" },
      { choice: "c", hint: "Planes can bank when they turn. Does a garden fly? Read the next sentence." },
      { choice: "d", hint: "Nothing in the guide talks about a seed box. What is the ground like by the stream?" },
    ],
  },
  5: {
    id: 5, act: 1, level: "Challenge", challenge: true, title: "Seed pod burst!", machine: "Double Meaning", icon: "snap", speaker: "vega", passage: ["A"],
    line: "Surprise! A giant glow-pod just popped, and seeds are everywhere! Pim's guide tells us what to do, but we have to read two tricky words right.",
    question: "Part 1: In paragraph 4, what does plant mean? Part 2: Highlight the sentence where plant means a living thing that grows. Part 3: In paragraph 3, what does spring mean?",
    parts: [
      { type: "choice", prompt: "\"To plant a glow-seed, dig a hole as deep as your thumb.\" What does plant mean?", choices: [
        { id: "a", text: "A green living thing" },
        { id: "b", text: "To put something in the ground so it can grow" },
        { id: "c", text: "A big building where things are made" },
        { id: "d", text: "To stand very still" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence where plant means a living thing that grows.", passage: "A" },
      { type: "choice", prompt: "\"A spring bubbles up from under a big rock and fills the stream with fresh water.\" What does spring mean?", choices: [
        { id: "a", text: "The season after winter" },
        { id: "b", text: "A bouncy metal coil" },
        { id: "c", text: "A place where water comes up out of the ground" },
        { id: "d", text: "A big jump" },
      ] },
    ],
    hint: "Look at what each word DOES in its sentence. Is plant an action or a thing? What does the spring bubble up with?",
    meter: { heat: 10, label: "Glow bloom +10%", story: "Every seed from the pod is planted" },
    discovery: { id: "springs", name: "Springs", who: "Nova", fact: "A spring is a place where water from under the ground flows up to the surface all by itself." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["A1.2"]] },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Great reading! Here plant is an action, and the spring is water bubbling up from under a rock.",
    wrong: [
      { step: 1, choice: "a", hint: "That is plant as a thing. In this sentence, you dig a hole to plant. Is it an action?" },
      { step: 1, choice: "c", hint: "A factory can be called a plant, but you don't dig a thumb-deep hole for a building." },
      { step: 1, choice: "d", hint: "You can plant your feet and stand still, but here you are digging a hole for a seed." },
      { step: 2, sentence: "A4.1", hint: "In that sentence, plant is an action. Find the sentence where plant is a living thing." },
      { step: 2, sentence: "A2.1", hint: "That sentence is about trees, but it doesn't use the word plant. Look in paragraph 1." },
      { step: 2, sentence: "A1.3", hint: "Close! That's about the leaves. Which sentence uses the word plant?" },
      { step: 3, choice: "a", hint: "Spring is a season, too. But can a season bubble up from under a rock?" },
      { step: 3, choice: "b", hint: "A metal spring can bounce, but can it fill a stream with fresh water?" },
      { step: 3, choice: "d", hint: "Spring can mean jump. Does a jump fill a stream with water?" },
    ],
  },
  6: {
    id: 6, act: 2, level: "On level", title: "A drooping feeling", machine: "Clue Finder", icon: "scan", speaker: "nova", passage: ["B"],
    line: "Juniper's story has a big word: dejected. The sentence doesn't explain it, so we have to look beyond it.",
    question: "Part 1: \"Juniper felt dejected.\" What does dejected mean? Part 2: Highlight the sentence that gives the best clue.",
    parts: [
      { type: "choice", prompt: "What does dejected mean?", choices: [
        { id: "a", text: "Sad and without hope" },
        { id: "b", text: "Excited and happy" },
        { id: "c", text: "Sleepy and tired" },
        { id: "d", text: "Angry and loud" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that gives the best clue about dejected.", passage: "B" },
    ],
    hint: "The next sentence shows what Juniper's body does. What do drooping shoulders and a tear tell you?",
    meter: { heat: 10, label: "Glow bloom +10%", story: "Nova adds dejected to the word wall" },
    discovery: { id: "dandelion", name: "Dandelions", who: "Kai", fact: "The name dandelion comes from French words that mean \"lion's tooth.\" Its leaves have jagged edges, like teeth." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B2.2", "B2.3"]] },
    ] },
    rightFeedback: "Yes! Drooping shoulders, a tear, and \"I will never find it\" all show Juniper is sad and without hope.",
    wrong: [
      { step: 1, choice: "b", hint: "Would an excited person cry and say \"I will never find it\"?" },
      { step: 1, choice: "c", hint: "Nothing says Juniper is sleepy. Why might a tear roll down her cheek?" },
      { step: 1, choice: "d", hint: "Juniper doesn't shout. She sighs. How does she really feel?" },
      { step: 2, sentence: "B2.1", hint: "That's the sentence with the hard word. Which sentence AFTER it gives a clue?" },
      { step: 2, sentence: "B1.3", hint: "That tells what happened. Which sentence shows how Juniper feels about it?" },
      { step: 2, sentence: "B3.2", hint: "That's Tam trying to cheer her up. Look for a clue right after the word dejected." },
    ],
  },
  7: {
    id: 7, act: 2, level: "On level", title: "The bow debate", machine: "Crew Debate", icon: "debate", speaker: "kai", passage: ["B"],
    line: 'Kai: "A word has just one meaning. A bow is when you bend at the waist, like at the end of a show. So the story makes no sense. You can\'t tie a pouch with a bend!"',
    nova: 'Nova: "Lots of words have more than one meaning. The words around it, \'tied with a blue bow,\' show that this bow is a knot made of ribbon."',
    question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
    hint: "Can you tie something with a bend at the waist? What else can a bow be?",
    meter: { supplies: 1, label: "Word seeds +1", story: "The crew agrees that words can wear more than one meaning" },
    discovery: { id: "kingfisher", name: "Kingfisher tunnels", who: "Nova", fact: "Some kingfishers dig long tunnels into the muddy banks of rivers. They lay their eggs at the end of the tunnel." },
    answer: { kind: "debate", who: "nova", reason: "A" },
    reasons: [
      { id: "A", text: "Nova. Many words have more than one meaning. The clue \"tied with a blue bow\" shows this bow is a ribbon knot." },
      { id: "B", text: "Nova, because hard words should be skipped." },
      { id: "C", text: "Kai. Every word has only one meaning, so the story is wrong." },
      { id: "D", text: "Kai. The first meaning you learn is always the right one." },
    ],
    writtenPrompt: "Tell Kai in your own words how to figure out which meaning of a word fits.",
    debateHints: {
      wrongWho: "Can a pouch be tied with a bend at the waist? Look at the words around bow.",
      wrongReason: "Right person, check the reason. Do we skip words, or use clues to find the meaning?",
      right: "Nova is right. Many words have more than one meaning, and the clues around a word show which one fits.",
    },
  },
  8: {
    id: 8, act: 2, level: "On level", title: "Sayings in the story", machine: "Idiom Net", icon: "crew", speaker: "vega", passage: ["B"],
    line: "Tam uses some sayings that don't mean exactly what the words say. They're called idioms. Catch them all.",
    question: "Which of these from the story are idioms? Pick every one.",
    hint: "An idiom means something different from its exact words. Would you really lift your chin, or grin all the way to your ears?",
    meter: { heat: 5, label: "Glow bloom +5%", story: "Vega's idiom net is full" },
    discovery: { id: "clover", name: "Four-leaf clovers", who: "Kai", fact: "Most clover leaves are split into three small parts. Only about 1 in every 5,000 clovers has four." },
    answer: { kind: "multi", correct: ["a", "b", "c"] },
    items: [
      { id: "a", text: "Keep your chin up" },
      { id: "b", text: "Searched high and low" },
      { id: "c", text: "Grinned from ear to ear" },
      { id: "d", text: "Tied with a blue bow" },
      { id: "e", text: "Put a hand on her arm" },
    ],
    rightFeedback: "Caught them! Keep your chin up means stay hopeful, high and low means everywhere, and ear to ear means a huge smile.",
    wrong: [
      { pick: "d", hint: "The pouch really was tied with a bow. Do these words mean exactly what they say?" },
      { pick: "e", hint: "Tam really did put his hand on her arm. An idiom means something different from its words." },
      { missing: true, hint: "There are three idioms. Look at what Tam says, how they searched, and how Juniper smiled." },
    ],
  },
  9: {
    id: 9, act: 2, level: "On level", title: "Fix Kai's sign", machine: "Repair", icon: "log", speaker: "kai", passage: ["D"],
    line: "I made a sign for the garden gate. Nova says four of my words say the opposite of what I meant. Oops!",
    question: "Tap each wrongly used word in Kai's sign and pick the word that makes sense.",
    hint: "Read each sentence and ask: does this word match the rest of the sentence?",
    meter: { heat: 5, label: "Glow bloom +5%", story: "The sign goes up at the garden gate" },
    answer: { kind: "edit", fixes: { "D:careless": "careful", "D:heavy": "light", "D:Postsoak": "Presoak", "D:visible": "invisible" } },
    rightFeedback: "Sign fixed! Now it tells visitors to be careful, hold light seeds tight, soak seeds first, and watch for roots they can't see.",
    wrong: [
      { token: "D:careless", hint: "Careless means without care. Near a muddy bank, should people be full of care?" },
      { token: "D:heavy", hint: "If the seeds were heavy, would you need to hold them tight in the wind?" },
      { token: "D:Postsoak", hint: "You soak the seeds BEFORE you plant them. Which prefix means before?" },
      { token: "D:visible", hint: "If you could see the roots, you wouldn't trip. Which word means NOT able to be seen?" },
    ],
  },
  10: {
    id: 10, act: 2, level: "Challenge", challenge: true, title: "Where did the moths go?", machine: "Affix Decoder", icon: "quake", speaker: "nova", passage: ["C"],
    line: "Surprise! The glow-moths are gone, and Kai thinks they flew away forever! The new Glow Garden News just arrived. Let's decode its words.",
    question: "Part 1: What does disappear mean in paragraph 1? Part 2: Highlight the sentence with a word that means \"without stopping.\" Part 3: What does brightness mean?",
    parts: [
      { type: "choice", prompt: "\"By morning, they seemed to disappear, but they were only resting under the leaves.\" What does disappear mean?", choices: [
        { id: "a", text: "To show up" },
        { id: "b", text: "To go out of sight" },
        { id: "c", text: "To fly very fast" },
        { id: "d", text: "To glow again" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence with a word that means \"without stopping.\"", passage: "C" },
      { type: "choice", prompt: "\"Their brightness lit up the leafy paths.\" What does brightness mean?", choices: [
        { id: "a", text: "Less bright" },
        { id: "b", text: "Bright again" },
        { id: "c", text: "Being bright" },
        { id: "d", text: "Before it is bright" },
      ] },
    ],
    hint: "Break each word into parts. Dis- means the opposite. Non- means not. -ness means being something.",
    meter: { heat: 10, label: "Glow bloom +10%", story: "The moths are found napping under the leaves" },
    discovery: { id: "morningglory", name: "Morning glories", who: "Nova", fact: "Morning glory flowers open in the morning and close up later in the day." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "b" },
      { kind: "highlight", groups: [["C1.1"]] },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Mystery solved! The moths only went out of sight to rest. They flew nonstop all night, and their brightness lit the paths.",
    wrong: [
      { step: 1, choice: "a", hint: "Dis- means the opposite. Appear means show up. What is the opposite?" },
      { step: 1, choice: "c", hint: "The sentence says they were resting, not flying. What does dis- do to appear?" },
      { step: 1, choice: "d", hint: "The moths were resting under the leaves where you couldn't see them. Did they glow again?" },
      { step: 2, sentence: "C2.3", hint: "Presoak has a prefix, but pre- means before. Find the word with non-." },
      { step: 2, sentence: "C3.2", hint: "Nonliving has non-, but it means not living. Which word means not stopping?" },
      { step: 2, sentence: "C1.3", hint: "That sentence tells where the moths went. Which one tells HOW they flew all night?" },
      { step: 3, choice: "a", hint: "The suffix -ness doesn't mean less. Did the paths get darker?" },
      { step: 3, choice: "b", hint: "Again would be re-. What does the suffix -ness add?" },
      { step: 3, choice: "d", hint: "Before would be pre-, at the start of a word. -ness is at the end." },
    ],
  },
  11: {
    id: 11, act: 3, level: "On level", title: "Affix sorting shed", machine: "Sort Bay", icon: "cells", speaker: "nova", passage: ["C"],
    line: "The newsletter is full of words with prefixes and suffixes. Let's sort them by what the word part means.",
    question: "Sort each word by what its prefix or suffix means.",
    hint: "Find the added part. In-, non-, and dis- can mean not. Pre- means before. -ful and -y mean full of or having.",
    meter: { heat: 5, label: "Glow bloom +5%", story: "Every word is in its shed" },
    discovery: { id: "pumpkinfruit", name: "Pumpkins are fruits", who: "Nova", fact: "A pumpkin is a fruit! Scientists call the part of a plant that grows from a flower and holds seeds a fruit." },
    answer: { kind: "sort", bins: { w1: "not", w2: "not", w3: "before", w4: "before", w5: "full", w6: "full" } },
    rightFeedback: "Sorted! Invisible and nonliving mean not. Presoak and preheat mean before. Careful and leafy mean full of or having.",
    sort: {
      bins: [
        { id: "not", label: "Means not" },
        { id: "before", label: "Means before" },
        { id: "full", label: "Means full of or having" },
      ],
      items: [
        { id: "w1", label: "invisible" },
        { id: "w2", label: "nonliving" },
        { id: "w3", label: "presoak" },
        { id: "w4", label: "preheat" },
        { id: "w5", label: "careful" },
        { id: "w6", label: "leafy" },
      ],
    },
    wrong: [
      { item: "w1", hint: "Invisible starts with in-. Here in- means not. Invisible means not able to be seen." },
      { item: "w2", hint: "Nonliving starts with non-. What does non- mean?" },
      { item: "w3", hint: "Presoak starts with pre-. You soak the seeds before you plant them." },
      { item: "w4", hint: "Preheat means heat before. Which bin means before?" },
      { item: "w5", hint: "Careful ends with -ful. What does -ful mean?" },
      { item: "w6", hint: "Leafy ends with -y. A leafy path is full of leaves." },
    ],
  },
  12: {
    id: 12, act: 3, level: "On level", title: "Word workshop", machine: "Word Builder", icon: "relay", speaker: "kai", passage: ["C"],
    line: "I'm building new words for the garden signs. I have the base words. You pick the parts that fit!",
    question: "Build each word. Pick the prefix or suffix that makes the meaning.",
    parts: [
      { type: "choice", prompt: "Add a prefix to port (carry) to make a word that means \"to carry into a place.\"", choices: [
        { id: "a", text: "im + port = import" },
        { id: "b", text: "ex + port = export" },
        { id: "c", text: "pre + port = preport" },
        { id: "d", text: "non + port = nonport" },
      ] },
      { type: "choice", prompt: "Add a suffix to dark to make a word that means \"the state of being dark.\"", choices: [
        { id: "a", text: "dark + ful = darkful" },
        { id: "b", text: "dark + ness = darkness" },
        { id: "c", text: "dark + er = darker" },
        { id: "d", text: "dark + pre = darkpre" },
      ] },
      { type: "choice", prompt: "Add a suffix to help to make a word that means \"full of help.\"", choices: [
        { id: "a", text: "help + ness = helpness" },
        { id: "b", text: "help + y = helpy" },
        { id: "c", text: "help + ful = helpful" },
        { id: "d", text: "dis + help = dishelp" },
      ] },
    ],
    hint: "Im- can mean into. -ness means the state of being. -ful means full of.",
    meter: { supplies: 1, label: "Word seeds +1", story: "Kai's new words go on the garden signs" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
      { kind: "choice", correct: "c" },
    ] },
    rightFeedback: "Great building! Import, darkness, and helpful are all real words, and each part does its job.",
    wrong: [
      { step: 1, choice: "b", hint: "Export means to carry OUT of a place. Which prefix means into?" },
      { step: 1, choice: "c", hint: "Pre- means before. The helpers carry soil INTO the garden. Which prefix means into?" },
      { step: 1, choice: "d", hint: "Non- means not. Which prefix means into?" },
      { step: 2, choice: "a", hint: "-ful means full of. Which suffix means the state of being something?" },
      { step: 2, choice: "c", hint: "-er means more. Darker means more dark, not the state of being dark. Which suffix means the state of being?" },
      { step: 2, choice: "d", hint: "Pre- is a prefix. It goes at the start of a word, not the end." },
      { step: 3, choice: "a", hint: "-ness means the state of being. Which suffix means full of?" },
      { step: 3, choice: "b", hint: "Helpy isn't a real word. Which suffix means full of?" },
      { step: 3, choice: "d", hint: "Dis- means not. We want a word that means FULL of help." },
    ],
  },
  13: {
    id: 13, act: 3, level: "On level", title: "Same and opposite", machine: "Word Lens", icon: "static", speaker: "vega", passage: ["B"],
    line: "Tam and Juniper looked everywhere, and then Tam saw a faint twinkle. Let's find words that mean the same and the opposite.",
    question: "Part 1: Which word is a synonym for searched in paragraph 3? Part 2: Highlight the sentence that gives an antonym clue for faint.",
    parts: [
      { type: "choice", prompt: "\"They searched high and low.\" Which word means almost the same as searched?", choices: [
        { id: "a", text: "Looked" },
        { id: "b", text: "Slept" },
        { id: "c", text: "Hid" },
        { id: "d", text: "Planted" },
      ] },
      { type: "highlight", prompt: "Highlight the sentence that shows faint is the opposite of bright.", passage: "B" },
    ],
    hint: "A synonym means the same. An antonym means the opposite. Look for the word NOT near faint.",
    meter: { heat: 5, label: "Glow bloom +5%", story: "The word pairs glow on the wall" },
    discovery: { id: "bamboo", name: "Speedy bamboo", who: "Kai", fact: "Bamboo is a giant grass. Some kinds of bamboo can grow almost 3 feet in just one day." },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "highlight", groups: [["B4.2"]] },
    ] },
    rightFeedback: "Right! Searched and looked mean the same. \"It was not bright\" shows that faint is the opposite of bright.",
    wrong: [
      { step: 1, choice: "b", hint: "They were looking for the seed, not resting. Which word means the same as searched?" },
      { step: 1, choice: "c", hint: "Hid is almost the opposite. They were trying to FIND the seed." },
      { step: 1, choice: "d", hint: "Juniper planted the seed later. Which word tells what they did to find it?" },
      { step: 2, sentence: "B4.1", hint: "That sentence has the word faint. Which sentence AFTER it tells what faint is not?" },
      { step: 2, sentence: "B1.1", hint: "That tells the seed was the brightest. Which sentence tells about the faint twinkle?" },
      { step: 2, sentence: "B4.3", hint: "That shows how Juniper felt. Look for the sentence with \"not bright.\"" },
    ],
  },
  14: {
    id: 14, act: 3, level: "On level", title: "Kai's mistake: a torn cheek?", machine: "Repair", icon: "brief", speaker: "kai", passage: ["B"],
    line: "Yikes! The story says a tear rolled down Juniper's cheek. So her cheek ripped?! That sounds like it hurts.",
    question: "Part 1: What went wrong when Kai read the word tear? Part 2: Pick the meaning of tear that fits the story.",
    parts: [
      { type: "choice", prompt: "What went wrong?", choices: [
        { id: "a", text: "He used the meaning of tear that means to rip. The sentence is about Juniper crying." },
        { id: "b", text: "He read the wrong story." },
        { id: "c", text: "He skipped the word tear." },
        { id: "d", text: "Nothing. Juniper's cheek really ripped." },
      ] },
      { type: "choice", prompt: "What does tear mean in \"a tear rolled down her cheek\"?", choices: [
        { id: "a", text: "To rip something apart" },
        { id: "b", text: "A drop of water that comes from your eye" },
        { id: "c", text: "A hole in a piece of cloth" },
        { id: "d", text: "To run very fast" },
      ] },
    ],
    hint: "Tear is a homograph. It is spelled the same but has two meanings and two sounds. What is Juniper feeling?",
    meter: { heat: 5, label: "Glow bloom +5%", story: "Kai reads the story again, and it makes sense" },
    answer: { kind: "parts", parts: [
      { kind: "choice", correct: "a" },
      { kind: "choice", correct: "b" },
    ] },
    rightFeedback: "Fixed! Juniper felt sad, so a tear, a drop from her eye, rolled down her cheek.",
    wrong: [
      { step: 1, choice: "b", hint: "Kai read the right story. Which meaning of tear did he use?" },
      { step: 1, choice: "c", hint: "Kai didn't skip it. He read it, but he picked the wrong meaning." },
      { step: 1, choice: "d", hint: "Juniper felt dejected and sighed. Does a ripped cheek fit that?" },
      { step: 2, choice: "a", hint: "That is Kai's meaning. Can a rip roll down a cheek?" },
      { step: 2, choice: "c", hint: "A tear can be a hole in cloth, but this one rolls down her cheek. What rolls down when you're sad?" },
      { step: 2, choice: "d", hint: "Tear can mean to rush, but here something ROLLS down her cheek." },
    ],
  },
  15: {
    id: 15, act: 3, level: "Challenge", challenge: true, title: "Report before the bloom", machine: "Transmit", icon: "relay", speaker: "vega", passage: ["F", "A", "B"],
    line: "Surprise! Juniper's glow-seed is about to bloom tonight, and Mission Control wants our report first. Fix it, check one more word, and add a sentence of your own.",
    question: "Part 1: Fix the 4 wrongly used words in the report. Part 2: Pick the sentence where close means near. Part 3: Write one sentence about the Glow Garden that uses a new word from this quest.",
    parts: [
      { type: "edit", prompt: "Fix the 4 wrongly used words in the report.", passage: "F" },
      { type: "choice", prompt: "In which sentence does close mean near?", choices: [
        { id: "a", text: "Please close the garden gate." },
        { id: "b", text: "She planted it that very day, close to the spring." },
        { id: "c", text: "The shop will close at sunset." },
        { id: "d", text: "Close your eyes and make a wish." },
      ] },
      { type: "write", prompt: "Write one sentence about the Glow Garden. Use one of these words: luminous, dejected, invisible, or nonstop.", minWords: 8 },
    ],
    teacherScoredPart: 3,
    rubric: ["Uses luminous, dejected, invisible, or nonstop correctly", "The sentence gives a clue to the word's meaning", "Complete sentence with a capital and end punctuation"],
    hint: "Read each sentence in the report and ask: does this word fit? Use clues from the guide and the story.",
    meter: { heat: 10, label: "Glow bloom +10%", story: "The report is sent as Juniper's seed blooms" },
    discovery: { id: "sunflowers", name: "Young sunflowers", who: "Nova", fact: "Young sunflowers turn to follow the Sun across the sky. Grown-up sunflowers stop moving and face east." },
    answer: { kind: "parts", parts: [
      { kind: "edit", fixes: { "F:bench": "bank", "F:fall": "spring", "F:hopeful": "hopeless", "F:unvisible": "invisible" } },
      { kind: "choice", correct: "b" },
      { kind: "write", minWords: 8 },
    ] },
    rightFeedback: "Report sent! Your teacher will read your sentence.",
    wrong: [
      { step: 1, token: "F:bench", hint: "A bench is a seat. What is the land along the side of a stream called?" },
      { step: 1, token: "F:fall", hint: "Fall and spring are both seasons, but only one word also means water bubbling up from the ground." },
      { step: 1, token: "F:hopeful", hint: "Juniper said, \"I will never find it.\" Was she full of hope, or without hope?" },
      { step: 1, token: "F:unvisible", hint: "Unvisible isn't a real word. Which prefix goes with visible to mean not able to be seen?" },
      { step: 2, choice: "a", hint: "Close the gate means shut it. Which sentence means near?" },
      { step: 2, choice: "c", hint: "Close at sunset means stop being open. Which sentence tells where something is?" },
      { step: 2, choice: "d", hint: "Close your eyes means shut them. Which sentence means near?" },
    ],
  },
};

export default {
  id: "ELA.3.3B-XP",
  standard: "ELA.3.3B-XP",
  engine: "expedition_station",
  title: "The Word Garden",
  planet: "Lumara",
  outpost: "Glow Garden Gate · evening shift",
  grade: 3,
  subject: "ELAR",
  teks: "3.3B",
  supportingTeks: ["3.3C", "3.3D"],
  skillsChip: "3.3B · Use context clues for word meanings",
  iCan: "I can use clues in and around a sentence to figure out new words and words with more than one meaning. I can use prefixes, suffixes, synonyms, antonyms, and idioms to understand words.",
  blurb: "In the glowing garden on Lumara, words are as tricky as the plants. Bark isn't a dog sound, a bank holds no money, and a lost glow-seed needs finding.",
  mission: "Read the gardener's guide, a story, and the garden newsletter. Use clues to decode tricky words, then send a word-perfect report to Mission Control.",
  length: "15 tasks · 3 station visits",
  crew: CREW,
  channel: "CH 3.3B · LUMARA GLOW GARDEN",
  playableActs: [1, 2, 3],
  meterStart: { heat: 10, supplies: 0, journal: 0 },
  meterLabels: { heat: "Glow bloom", heatUnit: "%", supplies: "Word seeds", suppliesUnit: "seeds" },
  journalMax: 10,
  passages,
  opening: [
    "Specialist {firstName}, this is Commander Vega in the Glow Garden on Lumara.",
    "The garden is full of words with more than one meaning, and Kai keeps mixing them up.",
    "When you meet a tricky word, don't skip it. Hunt for clues around it. Vega out.",
  ],
  acts: acts({
    titles: ["Act 1 · Pim's guide", "Act 2 · The lost glow-seed", "Act 3 · The word workshop"],
    completes: [
      "Great decoding, {firstName}! Every seed from the pod is in the ground.",
      "Wonderful work, {firstName}! The moths are safe, and Kai's sign is fixed.",
      "Your report is on its way to Mission Control, {firstName}! Juniper's seed is blooming.",
    ],
    teasers: [
      "Next on Lumara: Juniper loses her brightest glow-seed. Act 2 is open now, or come back to it next time.",
      "Next on Lumara: Kai opens a word workshop. Act 3 is open now, or come back to it next time.",
    ],
    openings2: [
      "Welcome back, {firstName}. Nova here. Juniper, a young gardener, lost her last glow-seed.",
      "Her story is full of tricky words and sayings. Let's read it together.",
    ],
    openings3: [
      "Specialist {firstName}, Commander Vega. Kai wants to build new words for the garden signs.",
      "Help him with prefixes, suffixes, and word pairs, then send our report.",
    ],
  }),
  tasks,
};
