// Official student-expectation wording for grades 3-5.
// Math: 19 TAC §§111.5-111.7, adopted 2012.
// ELAR: 19 TAC §§110.5-110.7, adopted 2017.
// Science: 19 TAC §§112.5-112.7, adopted 2021.
// Social Studies is read from lib/briefings/teks/ss-teks-3-5.js.
// Taken from the TEA elementary subchapter PDFs on Sept 28, 2026.

export const TEKS_WORDING = {
  "Math": {
    "3.1A": "Apply mathematics to problems arising in everyday life, society, and the workplace.",
    "3.1B": "Use a problem-solving model that incorporates analyzing given information, formulating a plan or strategy, determining a solution, justifying the solution, and evaluating the problem-solving process and the reasonableness of the solution.",
    "3.1C": "Select tools, including real objects, manipulatives, paper and pencil, and technology as appropriate, and techniques, including mental math, estimation, and number sense as appropriate, to solve problems.",
    "3.1D": "Communicate mathematical ideas, reasoning, and their implications using multiple representations, including symbols, diagrams, graphs, and language as appropriate.",
    "3.1E": "Create and use representations to organize, record, and communicate mathematical ideas.",
    "3.1F": "Analyze mathematical relationships to connect and communicate mathematical ideas.",
    "3.1G": "Display, explain, and justify mathematical ideas and arguments using precise mathematical language in written or oral communication.",
    "3.2A": "Compose and decompose numbers up to 100,000 as a sum of so many ten thousands, so many thousands, so many hundreds, so many tens, and so many ones using objects, pictorial models, and numbers, including expanded notation as appropriate.",
    "3.2B": "Describe the mathematical relationships found in the base-10 place value system through the hundred thousands place.",
    "3.2C": "Represent a number on a number line as being between two consecutive multiples of 10; 100; 1,000; or 10,000 and use words to describe relative size of numbers in order to round whole numbers.",
    "3.2D": "Compare and order whole numbers up to 100,000 and represent comparisons using the symbols >, <, or =.",
    "3.3A": "Represent fractions greater than zero and less than or equal to one with denominators of 2, 3, 4, 6, and 8 using concrete objects and pictorial models, including strip diagrams and number lines.",
    "3.3B": "Determine the corresponding fraction greater than zero and less than or equal to one with denominators of 2, 3, 4, 6, and 8 given a specified point on a number line.",
    "3.3C": "Explain that the unit fraction 1/b represents the quantity formed by one part of a whole that has been partitioned into b equal parts where b is a non-zero whole number.",
    "3.3D": "Compose and decompose a fraction a/b with a numerator greater than zero and less than or equal to b as a sum of parts 1/b.",
    "3.3E": "Solve problems involving partitioning an object or a set of objects among two or more recipients using pictorial representations of fractions with denominators of 2, 3, 4, 6, and 8.",
    "3.3F": "Represent equivalent fractions with denominators of 2, 3, 4, 6, and 8 using a variety of objects and pictorial models, including number lines.",
    "3.3G": "Explain that two fractions are equivalent if and only if they are both represented by the same point on the number line or represent the same portion of a same size whole for an area model.",
    "3.3H": "Compare two fractions having the same numerator or denominator in problems by reasoning about their sizes and justifying the conclusion using symbols, words, objects, and pictorial models.",
    "3.4A": "Solve with fluency one-step and two-step problems involving addition and subtraction within 1,000 using strategies based on place value, properties of operations, and the relationship between addition and subtraction.",
    "3.4B": "Round to the nearest 10 or 100 or use compatible numbers to estimate solutions to addition and subtraction problems.",
    "3.4C": "Determine the value of a collection of coins and bills.",
    "3.4D": "Determine the total number of objects when equally-sized groups of objects are combined or arranged in arrays up to 10 by 10.",
    "3.4E": "Represent multiplication facts by using a variety of approaches such as repeated addition, equal-sized groups, arrays, area models, equal jumps on a number line, and skip counting.",
    "3.4F": "Recall facts to multiply up to 10 by 10 with automaticity and recall the corresponding division facts.",
    "3.4G": "Use strategies and algorithms, including the standard algorithm, to multiply a two-digit number by a one-digit number. Strategies may include mental math, partial products, and the commutative, associative, and distributive properties.",
    "3.4H": "Determine the number of objects in each group when a set of objects is partitioned into equal shares or a set of objects is shared equally.",
    "3.4I": "Determine if a number is even or odd using divisibility rules.",
    "3.4J": "Determine a quotient using the relationship between multiplication and division.",
    "3.4K": "Solve one-step and two-step problems involving multiplication and division within 100 using strategies based on objects; pictorial models, including arrays, area models, and equal groups; properties of operations; or recall of facts.",
    "3.5A": "Represent one-and two-step problems involving addition and subtraction of whole numbers to 1,000 using pictorial models, number lines, and equations.",
    "3.5B": "Represent and solve one-and two-step multiplication and division problems within 100 using arrays, strip diagrams, and equations.",
    "3.5C": "Describe a multiplication expression as a comparison such as 3 x 24 represents 3 times as much as 24.",
    "3.5D": "Determine the unknown whole number in a multiplication or division equation relating three whole numbers when the unknown is either a missing factor or product.",
    "3.5E": "Represent real-world relationships using number pairs in a table and verbal descriptions.",
    "3.6A": "Classify and sort two-and three-dimensional figures, including cones, cylinders, spheres, triangular and rectangular prisms, and cubes, based on attributes using formal geometric language.",
    "3.6B": "Use attributes to recognize rhombuses, parallelograms, trapezoids, rectangles, and squares as examples of quadrilaterals and draw examples of quadrilaterals that do not belong to any of these subcategories.",
    "3.6C": "Determine the area of rectangles with whole number side lengths in problems using multiplication related to the number of rows times the number of unit squares in each row.",
    "3.6D": "Decompose composite figures formed by rectangles into non-overlapping rectangles to determine the area of the original figure using the additive property of area.",
    "3.6E": "Decompose two congruent two-dimensional figures into parts with equal areas and express the area of each part as a unit fraction of the whole and recognize that equal shares of identical wholes need not have the same shape.",
    "3.7A": "Represent fractions of halves, fourths, and eighths as distances from zero on a number line.",
    "3.7B": "Determine the perimeter of a polygon or a missing length when given perimeter and remaining side lengths in problems.",
    "3.7C": "Determine the solutions to problems involving addition and subtraction of time intervals in minutes using pictorial models or tools such as a 15-minute event plus a 30-minute event equals 45 minutes.",
    "3.7D": "Determine when it is appropriate to use measurements of liquid volume (capacity) or weight.",
    "3.7E": "Determine liquid volume (capacity) or weight using appropriate units and tools.",
    "3.8A": "Summarize a data set with multiple categories using a frequency table, dot plot, pictograph, or bar graph with scaled intervals.",
    "3.8B": "Solve one-and two-step problems using categorical data represented with a frequency table, dot plot, pictograph, or bar graph with scaled intervals.",
    "3.9A": "Explain the connection between human capital/labor and income.",
    "3.9B": "Describe the relationship between the availability or scarcity of resources and how that impacts cost.",
    "3.9C": "Identify the costs and benefits of planned and unplanned spending decisions.",
    "3.9D": "Explain that credit is used when wants or needs exceed the ability to pay and that it is the borrower's responsibility to pay it back to the lender, usually with interest.",
    "3.9E": "List reasons to save and explain the benefit of a savings plan, including for college.",
    "3.9F": "Identify decisions involving income, spending, saving, credit, and charitable giving.",
    "4.1A": "Apply mathematics to problems arising in everyday life, society, and the workplace.",
    "4.1B": "Use a problem-solving model that incorporates analyzing given information, formulating a plan or strategy, determining a solution, justifying the solution, and evaluating the problem-solving process and the reasonableness of the solution.",
    "4.1C": "Select tools, including real objects, manipulatives, paper and pencil, and technology as appropriate, and techniques, including mental math, estimation, and number sense as appropriate, to solve problems.",
    "4.1D": "Communicate mathematical ideas, reasoning, and their implications using multiple representations, including symbols, diagrams, graphs, and language as appropriate.",
    "4.1E": "Create and use representations to organize, record, and communicate mathematical ideas.",
    "4.1F": "Analyze mathematical relationships to connect and communicate mathematical ideas.",
    "4.1G": "Display, explain, and justify mathematical ideas and arguments using precise mathematical language in written or oral communication.",
    "4.2A": "Interpret the value of each place-value position as 10 times the position to the right and as one-tenth of the value of the place to its left.",
    "4.2B": "Represent the value of the digit in whole numbers through 1,000,000,000 and decimals to the hundredths using expanded notation and numerals.",
    "4.2C": "Compare and order whole numbers to 1,000,000,000 and represent comparisons using the symbols >, <, or =.",
    "4.2D": "Round whole numbers to a given place value through the hundred thousands place.",
    "4.2E": "Represent decimals, including tenths and hundredths, using concrete and visual models and money.",
    "4.2F": "Compare and order decimals using concrete and visual models to the hundredths.",
    "4.2G": "Relate decimals to fractions that name tenths and hundredths.",
    "4.2H": "Determine the corresponding decimal to the tenths or hundredths place of a specified point on a number line.",
    "4.3A": "Represent a fraction a/b as a sum of fractions 1/b, where a and b are whole numbers and b > 0, including when a > b.",
    "4.3B": "Decompose a fraction in more than one way into a sum of fractions with the same denominator using concrete and pictorial models and recording results with symbolic representations.",
    "4.3C": "Determine if two given fractions are equivalent using a variety of methods.",
    "4.3D": "Compare two fractions with different numerators and different denominators and represent the comparison using the symbols >, =, or <.",
    "4.3E": "Represent and solve addition and subtraction of fractions with equal denominators using objects and pictorial models that build to the number line and properties of operations.",
    "4.3F": "Evaluate the reasonableness of sums and differences of fractions using benchmark fractions 0, 1/4, 1/2, 3/4, and 1, referring to the same whole.",
    "4.3G": "Represent fractions and decimals to the tenths or hundredths as distances from zero on a number line.",
    "4.4A": "Add and subtract whole numbers and decimals to the hundredths place using the standard algorithm.",
    "4.4B": "Determine products of a number and 10 or 100 using properties of operations and place value understandings.",
    "4.4C": "Represent the product of 2 two-digit numbers using arrays, area models, or equations, including perfect squares through 15 by 15.",
    "4.4D": "Use strategies and algorithms, including the standard algorithm, to multiply up to a four-digit number by a one-digit number and to multiply a two-digit number by a two-digit number. Strategies may include mental math, partial products, and the commutative, associative, and distributive properties.",
    "4.4E": "Represent the quotient of up to a four-digit whole number divided by a one-digit whole number using arrays, area models, or equations.",
    "4.4F": "Use strategies and algorithms, including the standard algorithm, to divide up to a four-digit dividend by a one-digit divisor.",
    "4.4G": "Round to the nearest 10, 100, or 1,000 or use compatible numbers to estimate solutions involving whole numbers.",
    "4.4H": "Solve with fluency one-and two-step problems involving multiplication and division, including interpreting remainders.",
    "4.5A": "Represent multi-step problems involving the four operations with whole numbers using strip diagrams and equations with a letter standing for the unknown quantity.",
    "4.5B": "Represent problems using an input-output table and numerical expressions to generate a number pattern that follows a given rule representing the relationship of the values in the resulting sequence and their position in the sequence.",
    "4.5C": "Use models to determine the formulas for the perimeter of a rectangle (l + w + l + w or 2l + 2w), including the special form for perimeter of a square (4s) and the area of a rectangle (l x w).",
    "4.5D": "Solve problems related to perimeter and area of rectangles where dimensions are whole numbers.",
    "4.6A": "Identify points, lines, line segments, rays, angles, and perpendicular and parallel lines.",
    "4.6B": "Identify and draw one or more lines of symmetry, if they exist, for a two-dimensional figure.",
    "4.6C": "Apply knowledge of right angles to identify acute, right, and obtuse triangles.",
    "4.6D": "Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines or the presence or absence of angles of a specified size.",
    "4.7A": "Illustrate the measure of an angle as the part of a circle whose center is at the vertex of the angle that is \"cut out\" by the rays of the angle. Angle measures are limited to whole numbers.",
    "4.7B": "Illustrate degrees as the units used to measure an angle, where 1/360 of any circle is one degree and an angle that \"cuts\" n/360 out of any circle whose center is at the angle's vertex has a measure of n degrees. Angle measures are limited to whole numbers.",
    "4.7C": "Determine the approximate measures of angles in degrees to the nearest whole number using a protractor.",
    "4.7D": "Draw an angle with a given measure.",
    "4.7E": "Determine the measure of an unknown angle formed by two non-overlapping adjacent angles given one or both angle measures.",
    "4.8A": "Identify relative sizes of measurement units within the customary and metric systems.",
    "4.8B": "Convert measurements within the same measurement system, customary or metric, from a smaller unit into a larger unit or a larger unit into a smaller unit when given other equivalent measures represented in a table.",
    "4.8C": "Solve problems that deal with measurements of length, intervals of time, liquid volumes, mass, and money using addition, subtraction, multiplication, or division as appropriate.",
    "4.9A": "Represent data on a frequency table, dot plot, or stem-and-leaf plot marked with whole numbers and fractions.",
    "4.9B": "Solve one-and two-step problems using data in whole number, decimal, and fraction form in a frequency table, dot plot, or stem-and-leaf plot.",
    "4.10A": "Distinguish between fixed and variable expenses.",
    "4.10B": "Calculate profit in a given situation.",
    "4.10C": "Compare the advantages and disadvantages of various savings options.",
    "4.10D": "Describe how to allocate a weekly allowance among spending; saving, including for college; and sharing.",
    "4.10E": "Describe the basic purpose of financial institutions, including keeping money safe, borrowing money, and lending.",
    "5.1A": "Apply mathematics to problems arising in everyday life, society, and the workplace.",
    "5.1B": "Use a problem-solving model that incorporates analyzing given information, formulating a plan or strategy, determining a solution, justifying the solution, and evaluating the problem-solving process and the reasonableness of the solution; §111.A. Elementary.",
    "5.1C": "Select tools, including real objects, manipulatives, paper and pencil, and technology as appropriate, and techniques, including mental math, estimation, and number sense as appropriate, to solve problems.",
    "5.1D": "Communicate mathematical ideas, reasoning, and their implications using multiple representations, including symbols, diagrams, graphs, and language as appropriate.",
    "5.1E": "Create and use representations to organize, record, and communicate mathematical ideas.",
    "5.1F": "Analyze mathematical relationships to connect and communicate mathematical ideas.",
    "5.1G": "Display, explain, and justify mathematical ideas and arguments using precise mathematical language in written or oral communication.",
    "5.2A": "Represent the value of the digit in decimals through the thousandths using expanded notation and numerals.",
    "5.2B": "Compare and order two decimals to thousandths and represent comparisons using the symbols >, <, or =.",
    "5.2C": "Round decimals to tenths or hundredths.",
    "5.3A": "Estimate to determine solutions to mathematical and real-world problems involving addition, subtraction, multiplication, or division.",
    "5.3B": "Multiply with fluency a three-digit number by a two-digit number using the standard algorithm.",
    "5.3C": "Solve with proficiency for quotients of up to a four-digit dividend by a two-digit divisor using strategies and the standard algorithm.",
    "5.3D": "Represent multiplication of decimals with products to the hundredths using objects and pictorial models, including area models.",
    "5.3E": "Solve for products of decimals to the hundredths, including situations involving money, using strategies based on place-value understandings, properties of operations, and the relationship to the multiplication of whole numbers.",
    "5.3F": "Represent quotients of decimals to the hundredths, up to four-digit dividends and two-digit whole number divisors, using objects and pictorial models, including area models.",
    "5.3G": "Solve for quotients of decimals to the hundredths, up to four-digit dividends and two-digit whole number divisors, using strategies and algorithms, including the standard algorithm.",
    "5.3H": "Represent and solve addition and subtraction of fractions with unequal denominators referring to the same whole using objects and pictorial models and properties of operations.",
    "5.3I": "Represent and solve multiplication of a whole number and a fraction that refers to the same whole using objects and pictorial models, including area models.",
    "5.3J": "Represent division of a unit fraction by a whole number and the division of a whole number by a unit fraction such as 1/3 ÷ 7 and 7 ÷ 1/3 using objects and pictorial models, including area models.",
    "5.3K": "Add and subtract positive rational numbers fluently.",
    "5.3L": "Divide whole numbers by unit fractions and unit fractions by whole numbers.",
    "5.4A": "Identify prime and composite numbers.",
    "5.4B": "Represent and solve multi-step problems involving the four operations with whole numbers using equations with a letter standing for the unknown quantity.",
    "5.4C": "Generate a numerical pattern when given a rule in the form y = ax or y = x + a and graph.",
    "5.4D": "Recognize the difference between additive and multiplicative numerical patterns given in a table or graph.",
    "5.4E": "Describe the meaning of parentheses and brackets in a numeric expression.",
    "5.4F": "Simplify numerical expressions that do not involve exponents, including up to two levels of grouping.",
    "5.4G": "Use concrete objects and pictorial models to develop the formulas for the volume of a rectangular prism, including the special form for a cube (V = l x w x h, V = s x s x s, and V = Bh).",
    "5.4H": "Represent and solve problems related to perimeter and/or area and related to volume.",
    "5.5": "Classify two-dimensional figures in a hierarchy of sets and subsets using graphic organizers based on their attributes and properties.",
    "5.6A": "Recognize a cube with side length of one unit as a unit cube having one cubic unit of volume and the volume of a three-dimensional figure as the number of unit cubes (n cubic units) needed to fill it with no gaps or overlaps if possible.",
    "5.6B": "Determine the volume of a rectangular prism with whole number side lengths in problems related to the number of layers times the number of unit cubes in the area of the base.",
    "5.7": "Solve problems by calculating conversions within a measurement system, customary or metric.",
    "5.8A": "Describe the key attributes of the coordinate plane, including perpendicular number lines (axes) where the intersection (origin) of the two lines coincides with zero on each number line and the given point (0, 0); the x-coordinate, the first number in an ordered pair, indicates movement parallel to the x-axis starting at the origin; and the y-coordinate, the second number, indicates movement parallel to the y-axis starting at the origin.",
    "5.8B": "Describe the process for graphing ordered pairs of numbers in the first quadrant of the coordinate plane.",
    "5.8C": "Graph in the first quadrant of the coordinate plane ordered pairs of numbers arising from mathematical and real-world problems, including those generated by number patterns or found in an input-output table.",
    "5.9A": "Represent categorical data with bar graphs or frequency tables and numerical data, including data sets of measurements in fractions or decimals, with dot plots or stem-and-leaf plots.",
    "5.9B": "Represent discrete paired data on a scatterplot.",
    "5.9C": "Solve one-and two-step problems using data from a frequency table, dot plot, bar graph, stem-and-leaf plot, or scatterplot.",
    "5.10A": "Define income tax, payroll tax, sales tax, and property tax.",
    "5.10B": "Explain the difference between gross income and net income.",
    "5.10C": "Identify the advantages and disadvantages of different methods of payment, including check, credit card, debit card, and electronic payments.",
    "5.10D": "Develop a system for keeping and using financial records.",
    "5.10E": "Describe actions that might be taken to balance a budget when expenses exceed income.",
    "5.10F": "Balance a simple budget."
  },
  "ELAR": {
    "3.1A": "Listen actively, ask relevant questions to clarify information, and make pertinent comments.",
    "3.1B": "Follow, restate, and give oral instructions that involve a series of related sequences of action.",
    "3.1C": "Speak coherently about the topic under discussion, employing eye contact, speaking rate, volume, enunciation, and the conventions of language to communicate ideas effectively; §110.A. Elementary.",
    "3.1D": "Work collaboratively with others by following agreed-upon rules, norms, and protocols.",
    "3.1E": "Develop social communication such as conversing politely in all situations.",
    "3.2A": "Demonstrate and apply phonetic knowledge by: (i) decoding multisyllabic words with multiple sound-spelling patterns such as eigh, ough, and en; (ii) decoding multisyllabic words with closed syllables; open syllables; VCe syllables; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (iii) decoding compound words, contractions, and abbreviations; (iv) decoding words using knowledge of syllable division patterns such as VCCV, VCV, and VCCCV with accent shifts; (v) decoding words using knowledge of prefixes; (vi) decoding words using knowledge of suffixes, including how they can change base words such as dropping e, changing y to i, and doubling final consonants; and (vii) identifying and reading high-frequency words from a research-based list.",
    "3.2B": "Demonstrate and apply spelling knowledge by: (i) spelling multisyllabic words with closed syllables; open syllables; VCe syllables; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (ii) spelling homophones; (iii) spelling compound words, contractions, and abbreviations; (iv) spelling multisyllabic words with multiple sound-spelling patterns; (v) spelling words using knowledge of syllable division patterns such as VCCV, VCV, and VCCCV; (vi) spelling words using knowledge of prefixes; and (vii) spelling words using knowledge of suffixes, including how they can change base words such as dropping e, changing y to i, and doubling final consonants.",
    "3.2C": "Alphabetize a series of words to the third letter.",
    "3.2D": "Write complete words, thoughts, and answers legibly in cursive leaving appropriate spaces between words.",
    "3.3A": "Use print or digital resources to determine meaning, syllabication, and pronunciation.",
    "3.3B": "Use context within and beyond a sentence to determine the meaning of unfamiliar words and multiple-meaning words.",
    "3.3C": "Identify the meaning of and use words with affixes such as im- (into), non-, dis-, in- (not, non), pre-, -ness, -y, and -ful.",
    "3.3D": "Identify, use, and explain the meaning of antonyms, synonyms, idioms, homophones, and homographs in a text.",
    "3.4": "Use appropriate fluency (rate, accuracy, and prosody) when reading grade-level text.",
    "3.5": "Self-select text and read independently for a sustained period of time.",
    "3.6A": "Establish purpose for reading assigned and self-selected texts.",
    "3.6B": "Generate questions about text before, during, and after reading to deepen understanding and gain information.",
    "3.6C": "Make and correct or confirm predictions using text features, characteristics of genre, and structures.",
    "3.6D": "Create mental images to deepen understanding.",
    "3.6E": "Make connections to personal experiences, ideas in other texts, and society.",
    "3.6F": "Make inferences and use evidence to support understanding.",
    "3.6G": "Evaluate details read to determine key ideas.",
    "3.6H": "Synthesize information to create new understanding.",
    "3.6I": "Monitor comprehension and make adjustments such as re-reading, using background knowledge, asking questions, and annotating when understanding breaks down.",
    "3.7A": "Describe personal connections to a variety of sources, including self-selected texts.",
    "3.7B": "Write a response to a literary or informational text that demonstrates an understanding of a text.",
    "3.7C": "Use text evidence to support an appropriate response.",
    "3.7D": "Retell and paraphrase texts in ways that maintain meaning and logical order.",
    "3.7E": "Interact with sources in meaningful ways such as notetaking, annotating, freewriting, or illustrating.",
    "3.7F": "Respond using newly acquired vocabulary as appropriate.",
    "3.7G": "Discuss specific ideas in the text that are important to the meaning.",
    "3.8A": "Infer the theme of a work, distinguishing theme from topic.",
    "3.8B": "Explain the relationships among the major and minor characters; §110.A. Elementary.",
    "3.8C": "Analyze plot elements, including the sequence of events, the conflict, and the resolution.",
    "3.8D": "Explain the influence of the setting on the plot.",
    "3.9A": "Demonstrate knowledge of distinguishing characteristics of well-known children's literature such as folktales, fables, fairy tales, legends, and myths.",
    "3.9B": "Explain rhyme scheme, sound devices, and structural elements such as stanzas in a variety of poems.",
    "3.9C": "Discuss elements of drama such as characters, dialogue, setting, and acts.",
    "3.9D": "Recognize characteristics and structures of informational text, including: (i) the central idea with supporting evidence; (ii) features such as sections, tables, graphs, timelines, bullets, numbers, and bold and italicized font to support understanding; and (iii) organizational patterns such as cause and effect and problem and solution.",
    "3.9E": "Recognize characteristics and structures of argumentative text by: (i) identifying the claim; (ii) distinguishing facts from opinion; and (iii) identifying the intended audience or reader.",
    "3.9F": "Recognize characteristics of multimodal and digital texts.",
    "3.10A": "Explain the author's purpose and message within a text.",
    "3.10B": "Explain how the use of text structure contributes to the author's purpose.",
    "3.10C": "Explain the author's use of print and graphic features to achieve specific purposes.",
    "3.10D": "Describe how the author's use of imagery, literal and figurative language such as simile, and sound devices such as onomatopoeia achieves specific purposes.",
    "3.10E": "Identify the use of literary devices, including first-or third-person point of view.",
    "3.10F": "Discuss how the author's use of language contributes to voice.",
    "3.10G": "Identify and explain the use of hyperbole.",
    "3.11A": "Plan a first draft by selecting a genre for a particular topic, purpose, and audience using a range of strategies such as brainstorming, freewriting, and mapping.",
    "3.11B": "Develop drafts into a focused, structured, and coherent piece of writing by: (i) organizing with purposeful structure, including an introduction and a conclusion; and (ii) developing an engaging idea with relevant details.",
    "3.11C": "Revise drafts to improve sentence structure and word choice by adding, deleting, combining, and rearranging ideas for coherence and clarity.",
    "3.11D": "Edit drafts using standard English conventions, including: (i) complete simple and compound sentences with subject-verb agreement; (ii) past, present, and future verb tense; (iii) singular, plural, common, and proper nouns; (iv) adjectives, including their comparative and superlative forms; (v) adverbs that convey time and adverbs that convey manner; (vi) prepositions and prepositional phrases; (vii) pronouns, including subjective, objective, and possessive cases; (viii) coordinating conjunctions to form compound subjects, predicates, and sentences; (ix) capitalization of official titles of people, holidays, and geographical names and places; (x) punctuation marks, including apostrophes in contractions and possessives and commas in compound sentences and items in a series; and (xi) correct spelling of words with grade-appropriate orthographic patterns and rules and high-frequency words.",
    "3.11E": "Publish written work for appropriate audiences.",
    "3.12A": "Compose literary texts, including personal narratives and poetry, using genre characteristics and craft.",
    "3.12B": "Compose informational texts, including brief compositions that convey information about a topic, using a clear central idea and genre characteristics and craft.",
    "3.12C": "Compose argumentative texts, including opinion essays, using genre characteristics and craft.",
    "3.12D": "Compose correspondence such as thank you notes or letters.",
    "3.13A": "Generate questions on a topic for formal and informal inquiry.",
    "3.13B": "Develop and follow a research plan with adult assistance.",
    "3.13C": "Identify and gather relevant information from a variety of sources.",
    "3.13D": "Identify primary and secondary sources.",
    "3.13E": "Demonstrate understanding of information gathered.",
    "3.13F": "Recognize the difference between paraphrasing and plagiarism when using source materials; §110.A. Elementary.",
    "3.13G": "Create a works cited page.",
    "3.13H": "Use an appropriate mode of delivery, whether written, oral, or multimodal, to present results.",
    "4.1A": "Listen actively, ask relevant questions to clarify information, and make pertinent comments.",
    "4.1B": "Follow, restate, and give oral instructions that involve a series of related sequences of action.",
    "4.1C": "Express an opinion supported by accurate information, employing eye contact, speaking rate, volume, enunciation, and the conventions of language to communicate ideas effectively.",
    "4.1D": "Work collaboratively with others to develop a plan of shared responsibilities.",
    "4.2A": "Demonstrate and apply phonetic knowledge by: (i) decoding words with specific orthographic patterns and rules, including regular and irregular plurals; (ii) decoding multisyllabic words with closed syllables; open syllables; VCe syllables; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (iii) decoding words using advanced knowledge of syllable division patterns such as VV; (iv) decoding words using knowledge of prefixes; (v) decoding words using knowledge of suffixes, including how they can change base words such as dropping e, changing y to i, and doubling final consonants; and (vi) identifying and reading high-frequency words from a research-based list.",
    "4.2B": "Demonstrate and apply spelling knowledge by: (i) spelling multisyllabic words with closed syllables; open syllables; VCe syllables; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (ii) spelling homophones; (iii) spelling multisyllabic words with multiple sound-spelling patterns; (iv) spelling words using advanced knowledge of syllable division patterns; (v) spelling words using knowledge of prefixes; and §110.A. Elementary (vi) spelling words using knowledge of suffixes, including how they can change base words such as dropping e, changing y to i, and doubling final consonants.",
    "4.2C": "Write legibly in cursive to complete assignments.",
    "4.3A": "Use print or digital resources to determine meaning, syllabication, and pronunciation.",
    "4.3B": "Use context within and beyond a sentence to determine the relevant meaning of unfamiliar words or multiple-meaning words.",
    "4.3C": "Determine the meaning of and use words with affixes such as mis-, sub-, -ment, and -ity/ty and roots such as auto, graph, and meter.",
    "4.3D": "Identify, use, and explain the meaning of homophones such as reign/rain.",
    "4.4": "Use appropriate fluency (rate, accuracy, and prosody) when reading grade-level text.",
    "4.5": "Self-select text and read independently for a sustained period of time.",
    "4.6A": "Establish purpose for reading assigned and self-selected texts.",
    "4.6B": "Generate questions about text before, during, and after reading to deepen understanding and gain information.",
    "4.6C": "Make and correct or confirm predictions using text features, characteristics of genre, and structures.",
    "4.6D": "Create mental images to deepen understanding.",
    "4.6E": "Make connections to personal experiences, ideas in other texts, and society.",
    "4.6F": "Make inferences and use evidence to support understanding.",
    "4.6G": "Evaluate details read to determine key ideas.",
    "4.6H": "Synthesize information to create new understanding.",
    "4.6I": "Monitor comprehension and make adjustments such as re-reading, using background knowledge, asking questions, and annotating when understanding breaks down.",
    "4.7A": "Describe personal connections to a variety of sources, including self-selected texts.",
    "4.7B": "Write responses that demonstrate understanding of texts, including comparing and contrasting ideas across a variety of sources.",
    "4.7C": "Use text evidence to support an appropriate response.",
    "4.7D": "Retell, paraphrase, or summarize texts in ways that maintain meaning and logical order.",
    "4.7E": "Interact with sources in meaningful ways such as notetaking, annotating, freewriting, or illustrating.",
    "4.7F": "Respond using newly acquired vocabulary as appropriate.",
    "4.7G": "Discuss specific ideas in the text that are important to the meaning.",
    "4.8A": "Infer basic themes supported by text evidence.",
    "4.8B": "Explain the interactions of the characters and the changes they undergo.",
    "4.8C": "Analyze plot elements, including the rising action, climax, falling action, and resolution.",
    "4.8D": "Explain the influence of the setting, including historical and cultural settings, on the plot.",
    "4.9A": "Demonstrate knowledge of distinguishing characteristics of well-known children's literature such as folktales, fables, legends, myths, and tall tales.",
    "4.9B": "Explain figurative language such as simile, metaphor, and personification that the poet uses to create images.",
    "4.9C": "Explain structure in drama such as character tags, acts, scenes, and stage directions.",
    "4.9D": "Recognize characteristics and structures of informational text, including: (i) the central idea with supporting evidence; (ii) features such as pronunciation guides and diagrams to support understanding; and (iii) organizational patterns such as compare and contrast.",
    "4.9E": "Recognize characteristics and structures of argumentative text by: (i) identifying the claim; (ii) explaining how the author has used facts for an argument; and (iii) identifying the intended audience or reader.",
    "4.9F": "Recognize characteristics of multimodal and digital texts.",
    "4.10A": "Explain the author's purpose and message within a text.",
    "4.10B": "Explain how the use of text structure contributes to the author's purpose.",
    "4.10C": "Analyze the author's use of print and graphic features to achieve specific purposes.",
    "4.10D": "Describe how the author's use of imagery, literal and figurative language such as simile and metaphor, and sound devices such as alliteration and assonance achieves specific purposes; §110.A. Elementary.",
    "4.10E": "Identify and understand the use of literary devices, including first-or third-person point of view.",
    "4.10F": "Discuss how the author's use of language contributes to voice.",
    "4.10G": "Identify and explain the use of anecdote.",
    "4.11A": "Plan a first draft by selecting a genre for a particular topic, purpose, and audience using a range of strategies such as brainstorming, freewriting, and mapping.",
    "4.11B": "Develop drafts into a focused, structured, and coherent piece of writing by: (i) organizing with purposeful structure, including an introduction, transitions, and a conclusion; and (ii) developing an engaging idea with relevant details.",
    "4.11C": "Revise drafts to improve sentence structure and word choice by adding, deleting, combining, and rearranging ideas for coherence and clarity.",
    "4.11D": "Edit drafts using standard English conventions, including: (i) complete simple and compound sentences with subject-verb agreement and avoidance of splices, run-ons, and fragments; (ii) past tense of irregular verbs; (iii) singular, plural, common, and proper nouns; (iv) adjectives, including their comparative and superlative forms; (v) adverbs that convey frequency and adverbs that convey degree; (vi) prepositions and prepositional phrases; (vii) pronouns, including reflexive; (viii) coordinating conjunctions to form compound subjects, predicates, and sentences; (ix) capitalization of historical periods, events, and documents; titles of books; stories and essays; and languages, races, and nationalities; (x) punctuation marks, including apostrophes in possessives, commas in compound sentences, and quotation marks in dialogue; and (xi) correct spelling of words with grade-appropriate orthographic patterns and rules and high-frequency words.",
    "4.11E": "Publish written work for appropriate audiences.",
    "4.12A": "Compose literary texts such as personal narratives and poetry using genre characteristics and craft.",
    "4.12B": "Compose informational texts, including brief compositions that convey information about a topic, using a clear central idea and genre characteristics and craft.",
    "4.12C": "Compose argumentative texts, including opinion essays, using genre characteristics and craft.",
    "4.12D": "Compose correspondence that requests information.",
    "4.13A": "Generate and clarify questions on a topic for formal and informal inquiry.",
    "4.13B": "Develop and follow a research plan with adult assistance.",
    "4.13C": "Identify and gather relevant information from a variety of sources.",
    "4.13D": "Identify primary and secondary sources.",
    "4.13E": "Demonstrate understanding of information gathered.",
    "4.13F": "Recognize the difference between paraphrasing and plagiarism when using source materials.",
    "4.13G": "Develop a bibliography.",
    "4.13H": "Use an appropriate mode of delivery, whether written, oral, or multimodal, to present results.",
    "5.1A": "Listen actively to interpret verbal and non-verbal messages, ask relevant questions, and make pertinent comments.",
    "5.1B": "Follow, restate, and give oral instructions that include multiple action steps.",
    "5.1C": "Give an organized presentation employing eye contact, speaking rate, volume, enunciation, natural gestures, and conventions of language to communicate ideas effectively.",
    "5.1D": "Work collaboratively with others to develop a plan of shared responsibilities.",
    "5.2A": "Demonstrate and apply phonetic knowledge by: (i) decoding words with consonant changes, including/t/ to/sh/ such as in select and selection and/k/ to/sh/ such as music and musician; (ii) decoding multisyllabic words with closed syllables; open syllables; VCe syllable; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (iii) decoding words using advanced knowledge of syllable division patterns; (iv) decoding words using advanced knowledge of the influence of prefixes and suffixes on base words; and (v) identifying and reading high-frequency words from a research-based list.",
    "5.2B": "Demonstrate and apply spelling knowledge by: (i) spelling multisyllabic words with closed syllables; open syllables; VCe syllables; vowel teams, including digraphs and diphthongs; r-controlled syllables; and final stable syllables; (ii) spelling words with consonant changes, including/t/ to/sh/ such as in select and selection and/k/ to/sh/ such as music and musician; (iii) spelling multisyllabic words with multiple sound-spelling patterns; (iv) spelling words using advanced knowledge of syllable division patterns; (v) spelling words using knowledge of prefixes; and (vi) spelling words using knowledge of suffixes, including how they can change base words such as dropping e, changing y to i, and doubling final consonants.",
    "5.2C": "Write legibly in cursive.",
    "5.3A": "Use print or digital resources to determine meaning, syllabication, pronunciation, and word origin.",
    "5.3B": "Use context within and beyond a sentence to determine the relevant meaning of unfamiliar words or multiple-meaning words.",
    "5.3C": "Identify the meaning of and use words with affixes such as trans-, super-, -ive, and -logy and roots such as geo and photo.",
    "5.3D": "Identify, use, and explain the meaning of adages and puns.",
    "5.4": "Use appropriate fluency (rate, accuracy, and prosody) when reading grade-level text.",
    "5.5": "Self-select text and read independently for a sustained period of time.",
    "5.6A": "Establish purpose for reading assigned and self-selected texts.",
    "5.6B": "Generate questions about text before, during, and after reading to deepen understanding and gain information.",
    "5.6C": "Make and correct or confirm predictions using text features, characteristics of genre, and structures.",
    "5.6D": "Create mental images to deepen understanding.",
    "5.6E": "Make connections to personal experiences, ideas in other texts, and society.",
    "5.6F": "Make inferences and use evidence to support understanding.",
    "5.6G": "Evaluate details read to determine key ideas.",
    "5.6H": "Synthesize information to create new understanding; and §110.A. Elementary.",
    "5.6I": "Monitor comprehension and make adjustments such as re-reading, using background knowledge, asking questions, and annotating when understanding breaks down.",
    "5.7A": "Describe personal connections to a variety of sources, including self-selected texts.",
    "5.7B": "Write responses that demonstrate understanding of texts, including comparing and contrasting ideas across a variety of sources.",
    "5.7C": "Use text evidence to support an appropriate response.",
    "5.7D": "Retell, paraphrase, or summarize texts in ways that maintain meaning and logical order.",
    "5.7E": "Interact with sources in meaningful ways such as notetaking, annotating, freewriting, or illustrating.",
    "5.7F": "Respond using newly acquired vocabulary as appropriate.",
    "5.7G": "Discuss specific ideas in the text that are important to the meaning.",
    "5.8A": "Infer multiple themes within a text using text evidence.",
    "5.8B": "Analyze the relationships of and conflicts among the characters.",
    "5.8C": "Analyze plot elements, including rising action, climax, falling action, and resolution.",
    "5.8D": "Analyze the influence of the setting, including historical and cultural settings, on the plot.",
    "5.9A": "Demonstrate knowledge of distinguishing characteristics of well-known children's literature such as folktales, fables, legends, myths, and tall tales.",
    "5.9B": "Explain the use of sound devices and figurative language and distinguish between the poet and the speaker in poems across a variety of poetic forms.",
    "5.9C": "Explain structure in drama such as character tags, acts, scenes, and stage directions.",
    "5.9D": "Recognize characteristics and structures of informational text, including: (i) the central idea with supporting evidence; (ii) features such as insets, timelines, and sidebars to support understanding; and (iii) organizational patterns such as logical order and order of importance.",
    "5.9E": "Recognize characteristics and structures of argumentative text by: (i) identifying the claim; (ii) explaining how the author has used facts for or against an argument; and (iii) identifying the intended audience or reader.",
    "5.9F": "Recognize characteristics of multimodal and digital texts.",
    "5.10A": "Explain the author's purpose and message within a text.",
    "5.10B": "Analyze how the use of text structure contributes to the author's purpose.",
    "5.10C": "Analyze the author's use of print and graphic features to achieve specific purposes.",
    "5.10D": "Describe how the author's use of imagery, literal and figurative language such as simile and metaphor, and sound devices achieves specific purposes.",
    "5.10E": "Identify and understand the use of literary devices, including first-or third-person point of view.",
    "5.10F": "Examine how the author's use of language contributes to voice.",
    "5.10G": "Explain the purpose of hyperbole, stereotyping, and anecdote.",
    "5.11A": "Plan a first draft by selecting a genre for a particular topic, purpose, and audience using a range of strategies such as brainstorming, freewriting, and mapping.",
    "5.11B": "Develop drafts into a focused, structured, and coherent piece of writing by: (i) organizing with purposeful structure, including an introduction, transitions, and a conclusion; and (ii) developing an engaging idea reflecting depth of thought with specific facts and details.",
    "5.11C": "Revise drafts to improve sentence structure and word choice by adding, deleting, combining, and rearranging ideas for coherence and clarity.",
    "5.11D": "Edit drafts using standard English conventions, including: (i) complete simple and compound sentences with subject-verb agreement and avoidance of splices, run-ons, and fragments; (ii) past tense of irregular verbs; (iii) collective nouns; (iv) adjectives, including their comparative and superlative forms; (v) conjunctive adverbs; (vi) prepositions and prepositional phrases and their influence on subject-verb agreement; (vii) pronouns, including indefinite; (viii) subordinating conjunctions to form complex sentences; (ix) capitalization of abbreviations, initials, acronyms, and organizations; (x) italics and underlining for titles and emphasis and punctuation marks, including quotation marks in dialogue and commas in compound and complex sentences; and (xi) correct spelling of words with grade-appropriate orthographic patterns and rules and high-frequency words; and §110.A. Elementary.",
    "5.11E": "Publish written work for appropriate audiences.",
    "5.12A": "Compose literary texts such as personal narratives, fiction, and poetry using genre characteristics and craft.",
    "5.12B": "Compose informational texts, including brief compositions that convey information about a topic, using a clear central idea and genre characteristics and craft.",
    "5.12C": "Compose argumentative texts, including opinion essays, using genre characteristics and craft.",
    "5.12D": "Compose correspondence that requests information.",
    "5.13A": "Generate and clarify questions on a topic for formal and informal inquiry.",
    "5.13B": "Develop and follow a research plan with adult assistance.",
    "5.13C": "Identify and gather relevant information from a variety of sources.",
    "5.13D": "Understand credibility of primary and secondary sources.",
    "5.13E": "Demonstrate understanding of information gathered.",
    "5.13F": "Differentiate between paraphrasing and plagiarism when using source materials.",
    "5.13G": "Develop a bibliography.",
    "5.13H": "Use an appropriate mode of delivery, whether written, oral, or multimodal, to present results."
  },
  "Science": {
    "3.1A": "Ask questions and define problems based on observations or information from text, phenomena, models, or investigations.",
    "3.1B": "Use scientific practices to plan and conduct descriptive investigations and use engineering practices to design solutions to problems.",
    "3.1C": "Demonstrate safe practices and the use of safety equipment during classroom and field investigations as outlined in Texas Education Agency-approved safety standards.",
    "3.1D": "Use tools, including hand lenses; metric rulers; Celsius thermometers; wind vanes; rain gauges; graduated cylinders; beakers; digital scales; hot plates; meter sticks; magnets; notebooks; Sun, Earth, Moon system models; timing devices; materials to support observation of habitats of organisms such as terrariums, aquariums, and collecting nets; and materials to support digital data collection such as computers, tablets, and cameras, to observe, measure, test, and analyze information.",
    "3.1E": "Collect observations and measurements as evidence.",
    "3.1F": "Construct appropriate graphic organizers to collect data, including tables, bar graphs, line graphs, tree maps, concept maps, Venn diagrams, flow charts or sequence maps, and input-output tables that show cause and effect.",
    "3.1G": "Develop and use models to represent phenomena, objects, and processes or design a prototype for a solution to a problem.",
    "3.2A": "Identify advantages and limitations of models such as their size, scale, properties, and materials.",
    "3.2B": "Analyze data by identifying any significant features, patterns, or sources of error.",
    "3.2C": "Use mathematical calculations to compare patterns and relationships.",
    "3.2D": "Evaluate a design or object using criteria.",
    "3.3A": "Develop explanations and propose solutions supported by data and models.",
    "3.3B": "Communicate explanations and solutions individually and collaboratively in a variety of settings and formats.",
    "3.3C": "Listen actively to others' explanations to identify relevant evidence and engage respectfully in scientific discussion.",
    "3.4A": "Explain how scientific discoveries and innovative solutions to problems impact science and society.",
    "3.4B": "Research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field to investigate STEM careers.",
    "3.5A": "Identify and use patterns to explain scientific phenomena or to design solutions.",
    "3.5B": "Identify and investigate cause-and-effect relationships to explain scientific phenomena or analyze problems.",
    "3.5C": "Use scale, proportion, and quantity to describe, compare, or model different systems.",
    "3.5D": "Examine and model the parts of a system and their interdependence in the function of the system.",
    "3.5E": "Investigate the flow of energy and cycling of matter through systems.",
    "3.5F": "Explain the relationship between the structure and function of objects, organisms, and systems.",
    "3.5G": "Explain how factors or conditions impact stability and change in objects, organisms, and systems.",
    "3.6A": "Measure, test, and record physical properties of matter, including temperature, mass, magnetism, and the ability to sink or float in water.",
    "3.6B": "Describe and classify samples of matter as solids, liquids, and gases and demonstrate that solids have a definite shape and that liquids and gases take the shape of their container.",
    "3.6C": "Predict, observe, and record changes in the state of matter caused by heating or cooling in a variety of substances such as ice becoming liquid water, condensation forming on the outside of a glass, or liquid water being heated to the point of becoming water vapor (gas).",
    "3.6D": "Demonstrate that materials can be combined based on their physical properties to create or modify objects such as building a tower or adding clay to sand to make a stronger brick and justify the selection of materials based on their physical properties.",
    "3.7A": "Demonstrate and describe forces acting on an object in contact or at a distance, including magnetism, gravity, and pushes and pulls.",
    "3.7B": "Plan and conduct a descriptive investigation to demonstrate and explain how position and motion can be changed by pushing and pulling objects such as swings, balls, and wagons.",
    "3.8A": "Identify everyday examples of energy, including light, sound, thermal, and mechanical.",
    "3.8B": "Plan and conduct investigations that demonstrate how the speed of an object is related to its mechanical energy.",
    "3.9A": "Construct models and explain the orbits of the Sun, Earth, and Moon in relation to each other.",
    "3.9B": "Identify the order of the planets in Earth's solar system in relation to the Sun.",
    "3.10A": "Compare and describe day-to-day weather in different locations at the same time, including air temperature, wind direction, and precipitation.",
    "3.10B": "Investigate and explain how soils such as sand and clay are formed by weathering of rock and by decomposition of plant and animal remains.",
    "3.10C": "Model and describe rapid changes in Earth's surface such as volcanic eruptions, earthquakes, and landslides.",
    "3.11A": "Explore and explain how humans use natural resources such as in construction, in agriculture, in transportation, and to make products.",
    "3.11B": "Explain why the conservation of natural resources is important.",
    "3.11C": "Identify ways to conserve natural resources through reducing, reusing, or recycling.",
    "3.12A": "Explain how temperature and precipitation affect animal growth and behavior through migration and hibernation and plant responses through dormancy.",
    "3.12B": "Identify and describe the flow of energy in a food chain and predict how changes in a food chain such as removal of frogs from a pond or bees from a field affect the ecosystem.",
    "3.12C": "Describe how natural changes to the environment such as floods and droughts cause some organisms to thrive and others to perish or move to new locations.",
    "3.12D": "Identify fossils as evidence of past living organisms and environments, including common Texas fossils.",
    "3.13A": "Explore and explain how external structures and functions of animals such as the neck of a giraffe or webbed feet on a duck enable them to survive in their environment.",
    "3.13B": "Explore, illustrate, and compare life cycles in organisms such as beetles, crickets, radishes, or lima beans.",
    "4.1A": "Ask questions and define problems based on observations or information from text, phenomena, models, or investigations.",
    "4.1B": "Use scientific practices to plan and conduct descriptive investigations and use engineering practices to design solutions to problems.",
    "4.1C": "Demonstrate safe practices and the use of safety equipment during classroom and field investigations as outlined in Texas Education Agency-approved safety standards.",
    "4.1D": "Use tools, including hand lenses; metric rulers; Celsius thermometers; calculators; laser pointers; mirrors; digital scales; balances; graduated cylinders; beakers; hot plates; meter sticks; magnets; notebooks; timing devices; sieves; materials for building circuits; materials to support observation of habitats of organisms such as terrariums, aquariums, and collecting nets; and materials to support digital data collection such as computers, tablets, and cameras, to observe, measure, test, and analyze information.",
    "4.1E": "Collect observations and measurements as evidence.",
    "4.1F": "Construct appropriate graphic organizers used to collect data, including tables, bar graphs, line graphs, tree maps, concept maps, Venn diagrams, flow charts or sequence maps, and input-output tables that show cause and effect.",
    "4.1G": "Develop and use models to represent phenomena, objects, and processes or design a prototype for a solution to a problem.",
    "4.2A": "Identify advantages and limitations of models such as their size, scale, properties, and materials.",
    "4.2B": "Analyze data by identifying any significant features, patterns, or sources of error.",
    "4.2C": "Use mathematical calculations to compare patterns and relationships.",
    "4.2D": "Evaluate a design or object using criteria.",
    "4.3A": "Develop explanations and propose solutions supported by data and models.",
    "4.3B": "Communicate explanations and solutions individually and collaboratively in a variety of settings and formats.",
    "4.3C": "Listen actively to others' explanations to identify relevant evidence and engage respectfully in scientific discussion.",
    "4.4A": "Explain how scientific discoveries and innovative solutions to problems impact science and society.",
    "4.4B": "Research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field to investigate STEM careers.",
    "4.5A": "Identify and use patterns to explain scientific phenomena or to design solutions.",
    "4.5B": "Identify and investigate cause-and-effect relationships to explain scientific phenomena or analyze problems.",
    "4.5C": "Use scale, proportion, and quantity to describe, compare, or model different systems.",
    "4.5D": "Examine and model the parts of a system and their interdependence in the function of the system.",
    "4.5E": "Investigate how energy flows and matter cycles through systems and how matter is conserved.",
    "4.5F": "Explain the relationship between the structure and function of objects, organisms, and systems.",
    "4.5G": "Explain how factors or conditions impact stability and change in objects, organisms, and systems.",
    "4.6A": "Classify and describe matter using observable physical properties, including temperature, mass, magnetism, relative density (the ability to sink or float in water), and physical state (solid, liquid, gas).",
    "4.6B": "Investigate and compare a variety of mixtures, including solutions that are composed of liquids in liquids and solids in liquids.",
    "4.6C": "Demonstrate that matter is conserved when mixtures such as soil and water or oil and water are formed.",
    "4.7": "Plan and conduct descriptive investigations to explore the patterns of forces such as gravity, friction, or magnetism in contact or at a distance on an object.",
    "4.8A": "Investigate and identify the transfer of energy by objects in motion, waves in water, and sound.",
    "4.8B": "Identify conductors and insulators of thermal and electrical energy.",
    "4.8C": "Demonstrate and describe how electrical energy travels in a closed path that can produce light and thermal energy.",
    "4.9A": "Collect and analyze data to identify sequences and predict patterns of change in seasons such as change in temperature and length of daylight.",
    "4.9B": "Collect and analyze data to identify sequences and predict patterns of change in the observable appearance of the Moon from Earth.",
    "4.10A": "Describe and illustrate the continuous movement of water above and on the surface of Earth through the water cycle and explain the role of the Sun as a major source of energy in this process.",
    "4.10B": "Model and describe slow changes to Earth's surface caused by weathering, erosion, and deposition from water, wind, and ice.",
    "4.10C": "Differentiate between weather and climate.",
    "4.11A": "Identify and explain advantages and disadvantages of using Earth's renewable and nonrenewable natural resources such as wind, water, sunlight, plants, animals, coal, oil, and natural gas.",
    "4.11B": "Explain the critical role of energy resources to modern life and how conservation, disposal, and recycling of natural resources impact the environment.",
    "4.11C": "Determine the physical properties of rocks that allow Earth's natural resources to be stored there.",
    "4.12A": "Investigate and explain how most producers can make their own food using sunlight, water, and carbon dioxide through the cycling of matter.",
    "4.12B": "Describe the cycling of matter and flow of energy through food webs, including the roles of the Sun, producers, consumers, and decomposers.",
    "4.12C": "Identify and describe past environments based on fossil evidence, including common Texas fossils.",
    "4.13A": "Explore and explain how structures and functions of plants such as waxy leaves and deep roots enable them to survive in their environment.",
    "4.13B": "Differentiate between inherited and acquired physical traits of organisms.",
    "5.1A": "Ask questions and define problems based on observations or information from text, phenomena, models, or investigations.",
    "5.1B": "Use scientific practices to plan and conduct descriptive and simple experimental investigations and use engineering practices to design solutions to problems.",
    "5.1C": "Demonstrate safe practices and the use of safety equipment during classroom and field investigations as outlined in Texas Education Agency-approved safety standards.",
    "5.1D": "Use tools, including calculators, microscopes, hand lenses, metric rulers, Celsius thermometers, prisms, concave and convex lenses, laser pointers, mirrors, digital scales, balances, spring scales, graduated cylinders, beakers, hot plates, meter sticks, magnets, collecting nets, notebooks, timing devices, materials for building circuits, materials to support observations of habitats or organisms such as terrariums and aquariums, and materials to support digital data collection such as computers, tablets, and cameras to observe, measure, test, and analyze information.",
    "5.1E": "Collect observations and measurements as evidence.",
    "5.1F": "Construct appropriate graphic organizers used to collect data, including tables, bar graphs, line graphs, tree maps, concept maps, Venn diagrams, flow charts or sequence maps, and input-output tables that show cause and effect.",
    "5.1G": "Develop and use models to represent phenomena, objects, and processes or design a prototype for a solution to a problem.",
    "5.2A": "Identify advantages and limitations of models such as their size, scale, properties, and materials.",
    "5.2B": "Analyze data by identifying any significant features, patterns, or sources of error.",
    "5.2C": "Use mathematical calculations to compare patterns and relationships.",
    "5.2D": "Evaluate experimental and engineering designs.",
    "5.3A": "Develop explanations and propose solutions supported by data and models.",
    "5.3B": "Communicate explanations and solutions individually and collaboratively in a variety of settings and formats.",
    "5.3C": "Listen actively to others' explanations to identify relevant evidence and engage respectfully in scientific discussion.",
    "5.4A": "Explain how scientific discoveries and innovative solutions to problems impact science and society.",
    "5.4B": "Research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field to investigate STEM careers.",
    "5.5A": "Identify and use patterns to explain scientific phenomena or to design solutions.",
    "5.5B": "Identify and investigate cause-and-effect relationships to explain scientific phenomena or analyze problems.",
    "5.5C": "Use scale, proportion, and quantity to describe, compare, or model different systems.",
    "5.5D": "Examine and model the parts of a system and their interdependence in the function of the system.",
    "5.5E": "Investigate how energy flows and matter cycles through systems and how matter is conserved.",
    "5.5F": "Explain the relationship between the structure and function of objects, organisms, and systems.",
    "5.5G": "Explain how factors or conditions impact stability and change in objects, organisms, and systems.",
    "5.6A": "Compare and contrast matter based on measurable, testable, or observable physical properties, including mass, magnetism, relative density (sinking and floating using water as a reference point), physical state (solid, liquid, gas), volume, solubility in water, and the ability to conduct or insulate thermal energy and electric energy.",
    "5.6B": "Demonstrate and explain that some mixtures maintain physical properties of their substances such as iron filings and sand or sand and water.",
    "5.6C": "Compare the properties of substances before and after they are combined into a solution and demonstrate that matter is conserved in solutions.",
    "5.6D": "Illustrate how matter is made up of particles that are too small to be seen such as air in a balloon.",
    "5.7A": "Investigate and explain how equal and unequal forces acting on an object cause patterns of motion and transfer of energy.",
    "5.7B": "Design a simple experimental investigation that tests the effect of force on an object in a system such as a car on a ramp or a balloon rocket on a string.",
    "5.8A": "Investigate and describe the transformation of energy in systems such as energy in a flashlight battery that changes from chemical energy to electrical energy to light energy.",
    "5.8B": "Demonstrate that electrical energy in complete circuits can be transformed into motion, light, sound, or thermal energy and identify the requirements for a functioning electrical circuit.",
    "5.8C": "Demonstrate and explain how light travels in a straight line and can be reflected , refracted, or absorbed.",
    "5.9": "Demonstrate that Earth rotates on its axis once approximately every 24 hours and explain how that causes the day/night cycle and the appearance of the Sun moving across the sky, resulting in changes in shadow positions and shapes.",
    "5.10A": "Explain how the Sun and the ocean interact in the water cycle and affect weather.",
    "5.10B": "Model and describe the processes that led to the formation of sedimentary rocks and fossil fuels.",
    "5.10C": "Model and identify how changes to Earth's surface by wind, water, or ice result in the formation of landforms, including deltas, canyons, and sand dunes.",
    "5.11": "Design and explain solutions such as conservation, recycling, or proper disposal to minimize environmental impact of the use of natural resources.",
    "5.12A": "Observe and describe how a variety of organisms survive by interacting with biotic and abiotic factors in a healthy ecosystem.",
    "5.12B": "Predict how changes in the ecosystem affect the cycling of matter and flow of energy in a food web.",
    "5.12C": "Describe a healthy ecosystem and how human activities can be beneficial or harmful to an ecosystem.",
    "5.13A": "Analyze the structures and functions of different species to identify how organisms survive in the same environment.",
    "5.13B": "Explain how instinctual behavioral traits such as turtle hatchlings returning to the sea and learned behavioral traits such as orcas hunting in packs increase chances of survival."
  }
};
