// Expedition Station — The Frozen Relay (MA.4.3E-XP)
// Content from Frozen_Relay_4.3E_Content_v1.md. Answer keys stay server-side.
// Act 1 (tasks 1–5) is playable; Acts 2–3 are listed for the mission map only.

export const QUESTS = {
  "MA.4.3E-XP": {
    id: "MA.4.3E-XP",
    standard: "MA.4.3E-XP",
    engine: "expedition_station",
    title: "The Frozen Relay",
    planet: "Frostveil",
    outpost: "Relay Outpost · −41°C",
    grade: 4,
    subject: "Math",
    teks: "4.3E",
    skillsChip: "4.3E · Add and subtract fractions",
    iCan:
      "I can add and subtract fractions that have the same bottom number. I can show how with pictures, a number line, and by adding in a different order.",
    blurb:
      "The relay tower on Frostveil went silent, and the crew is running low on heat and fuel. Every tank, cable, and power cell on this outpost is measured in fractions.",
    mission: "Add and subtract fractions to warm the outpost and restart the relay tower.",
    length: "15 tasks · 3 station visits",
    crew: ["Commander Vega", "Kai (engineer)", "Nova (scientist)", "S.A.M. (helper)"],
    channel: "CH 4.35 · FROSTVEIL RELAY",
    playableActs: [1],
    meterStart: { heat: 40, supplies: 3, journal: 0 },
    journalMax: 10,
    opening: [
      "Specialist {name}, this is Commander Vega. The relay tower on Frostveil went silent.",
      "Our crew is low on heat and fuel, and every tank, cable, and power cell here is measured in fractions.",
      "Help Kai and Nova add and subtract those fractions, and we'll get that tower talking again. Vega out.",
    ],
    acts: {
      1: {
        title: "Act 1 · Refuel the heater and find the beacon",
        short: "Refuel and find the beacon",
        complete: "The heater is warm and the beacon is back, {firstName}!",
        teaser:
          "Next on Frostveil: a storm is coming, and the cables and solar panels need fixing. Act 2 opens on your next station visit.",
        tasks: [1, 2, 3, 4],
        challenge: 5,
      },
      2: {
        title: "Act 2 · Fix the cables and clear the panels",
        short: "Fix cables and panels",
        locked: true,
        tasks: [6, 7, 8, 9],
        challenge: 10,
      },
      3: {
        title: "Act 3 · Reach the tower and restart the relay",
        short: "Reach the tower",
        locked: true,
        tasks: [11, 12, 13, 14],
        challenge: 15,
      },
    },
    tasks: {
      1: {
        id: 1,
        act: 1,
        level: "Warm-up",
        title: "Refuel the heater",
        machine: "Fill",
        icon: "tank",
        speaker: "kai",
        line: "Brrr! The heater is almost out of fuel. I poured in 3/8 of a tank. Then I poured in 2/8 more. Can you set the gauge so it matches?",
        question: "How much fuel is in the heater now? Set the gauge, then press Pour.",
        hint: "Both pours are in eighths. How many eighths in all?",
        meter: { heat: 20, label: "Heat +20%", story: "Warms up the tents" },
        answer: { kind: "frac", n: 5, d: 8 },
        wrong: [
          { n: 5, d: 16, hint: "Look at the gauge. Did the pieces change size when Kai poured? Both pours are eighths." },
          { n: 1, d: 8, hint: "Kai poured fuel in two times. Does the tank get more fuel or less?" },
        ],
        fill: {
          denom: 8,
          start: 0,
          pours: [
            { n: 3, d: 8 },
            { n: 2, d: 8 },
          ],
        },
      },
      2: {
        id: 2,
        act: 1,
        level: "Warm-up",
        title: "Settle the tank debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "I poured 1/3 of a tank into the reserve tank. Then I poured another 1/3. That makes 2/6. Easy: 1 + 1 = 2 and 3 + 3 = 6!"',
        nova: 'Nova: "No way. The tank has 2/3 now. The parts are still thirds."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Draw 1/3 and 1/3 on the same tank. What size are the parts?",
        meter: { heat: 15, label: "Heat +15%", story: "The reserve fuel goes to the heater" },
        discovery: {
          id: "crystal",
          name: "Ice crystal",
          who: "Nova",
          fact: "Snowflakes are made of ice crystals. They usually have 6 sides or 6 arms because of the way water freezes.",
        },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. Both pours are thirds. 1 third + 1 third = 2 thirds. Adding doesn't change the size of the parts." },
          { id: "B", text: "Nova, because 2/3 has smaller numbers than 2/6." },
          { id: "C", text: "Kai. You add the top numbers and add the bottom numbers." },
          { id: "D", text: "Kai. Two pours means twice as many parts, so the bottom number doubles." },
        ],
        writtenPrompt: "Tell Kai in your own words why 1/3 + 1/3 is not 2/6.",
      },
      3: {
        id: 3,
        act: 1,
        level: "Warm-up",
        title: "Find the backup beacon",
        machine: "Tune",
        icon: "dial",
        speaker: "kai",
        line: "The backup beacon is buried in the snow. Its battery was at 5/6 before the storm. The cold used up 3/6. If I set the dial to what's left, the beacon will beep back!",
        question: "How much battery is left? Turn the dial, then press Lock signal.",
        hint: "Start at 5/6. Jump back one sixth at a time.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The beacon marks a buried supply crate" },
        discovery: {
          id: "aurora",
          name: "Aurora",
          who: "Kai",
          fact: "On Earth, auroras glow in the sky near the North and South Poles. They happen when tiny bits from the Sun crash into the air high above us.",
        },
        answer: { kind: "frac", n: 2, d: 6 },
        wrong: [
          { n: 3, d: 6, hint: "Start at 5/6 on the dial. Which way do you turn to take some away?" },
          { n: 1, d: 6, hint: "Count the jumps between marks, not the marks. Start counting after 5/6." },
          { n: 8, d: 6, hint: "The cold used up some battery. Should the number go up or down?" },
        ],
        tune: { denom: 6, start: { n: 5, d: 6 }, used: { n: 3, d: 6 } },
      },
      4: {
        id: 4,
        act: 1,
        level: "Warm-up",
        title: "Fuel the sled",
        machine: "Fill",
        icon: "scoop",
        speaker: "nova",
        line: "The sled needs 7/10 of a tank to reach the supply crate. Its tank already has 3/10 in it. Our scoops hold 1/10 or 2/10.",
        question: "How much more fuel does the sled need? Then fill it with scoops two different ways.",
        hint: "Start at 3/10. Count up by tenths to 7/10.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The sled hauls the crate back to camp" },
        discovery: {
          id: "moth",
          name: "Frost moth",
          who: "Nova",
          fact: "Some moths fly in winter. They shiver the muscles that move their wings to warm up before they take off.",
        },
        answer: {
          kind: "scoops",
          missing: { n: 4, d: 10 },
          target: { n: 7, d: 10 },
          start: { n: 3, d: 10 },
          scoopSizes: [1, 2],
          waysNeeded: 2,
        },
        wrong: [
          { n: 10, d: 10, hint: "The tank already has some fuel. How much more to get from 3/10 up to 7/10?" },
          { n: 7, d: 10, hint: "Look at the tank before you pour. Is it empty?" },
        ],
        fill: { denom: 10, start: 3, target: 7 },
      },
      5: {
        id: 5,
        act: 1,
        level: "Challenge",
        challenge: true,
        title: "The cold snap",
        machine: "Fill",
        icon: "snap",
        speaker: "vega",
        line: "Surprise, the cold snap! The heater tank was at 7/8. The heater burned 2/8 each night for 2 nights. Then Kai added 3/8. The heater runs safely at the 5/8 line or above.",
        question: "What is the tank level now? How far above the safe line is the fuel?",
        hint: "Take it one night at a time. Then count the jumps from the safe line to the fuel.",
        meter: { heat: 10, label: "Heat +10%", story: "The heater stays safe through the cold snap" },
        discovery: {
          id: "sundog",
          name: "Sun dog",
          who: "Nova",
          fact: "Sun dogs are bright spots on each side of the Sun. Tiny ice crystals in the air bend the sunlight to make them.",
        },
        answer: { kind: "challenge", level: { n: 6, d: 8 }, above: { n: 1, d: 8 } },
        wrong: [
          { step: 1, n: 8, d: 8, hint: "Take it one night at a time. How many times did the heater burn fuel?" },
          { step: 1, n: 0, d: 8, hint: "Kai added fuel. Does adding make the tank go up or down?" },
          { step: 1, n: 3, d: 8, hint: "Read the story again. What happened after the two nights?" },
          { step: 2, n: 11, d: 8, hint: "You're finding the space between two lines on the same tank. Can that be bigger than the tank?" },
          { step: 2, n: 2, d: 8, hint: "Count the jumps from the safe line up to the fuel, not the lines." },
        ],
        fill: { denom: 8, start: 7, burn: 2, nights: 2, refill: 3, safe: 5 },
      },
      6: { id: 6, act: 2, title: "Cut the antenna cable", machine: "Travel", locked: true },
      7: { id: 7, act: 2, title: "Check Kai's cable log", machine: "Repair", locked: true },
      8: { id: 8, act: 2, title: "Clear the solar grid", machine: "Fill", locked: true },
      9: { id: 9, act: 2, title: "Fill the water tank", machine: "Numberless", locked: true },
      10: { id: 10, act: 2, title: "The ice quake", machine: "Travel", challenge: true, locked: true },
      11: { id: 11, act: 3, title: "Reach the tower", machine: "Travel", locked: true },
      12: { id: 12, act: 3, title: "The charger debate", machine: "Crew Debate", locked: true },
      13: { id: 13, act: 3, title: "Pack the power cells", machine: "Sort Bay", locked: true },
      14: { id: 14, act: 3, title: "Top off the tower battery", machine: "Fill", locked: true },
      15: { id: 15, act: 3, title: "Restart the relay", machine: "Fill", challenge: true, locked: true },
    },
  },
};

export function getExpeditionQuest(standard) {
  return QUESTS[standard] || null;
}
