// Expedition Station — The Frozen Relay (MA.4.3E-XP)
// Content from Frozen_Relay_4.3E_Content_v1.md. Answer keys stay server-side.
// Act 1 (tasks 1–5) is playable. Acts 2–3 (tasks 6–15) are written (Sept 26,
// rebuilt from the live Act 1 because the original content .md was not in the
// repo) but stay locked until the client supports their machines.
//
// CONTENT_NOTES for the build session — new answer kinds used in Acts 2–3:
//   frac      (existing)  tasks 6, 8, 14
//   debate    (existing)  task 12
//   mistake   task 7   body { tap, error, n, d } — tap the wrong part, pick the error, write the fix
//   numberless task 9  body { step: "questions", picks: [...] } then { step: "solve", n, d }
//   steps     tasks 10, 15  body { step, n, d } — one fraction per step, in order
//   compare   task 11  body { who, n, d } — who went farther, and by how much
//   sort      task 13  body { placements: { itemId: binId } }
// New machine configs: travel (6, 10, 11), repair (7), numberless (9), sort (13),
// fill.grid (8), fill.cells (15). Wrong-answer entries may carry step / error /
// who / item keys so the grader can pick the matching hint.
//
// Also used by The Glow Garden Harvest (MA.3.3A-XP, Sept 26):
//   meterLabels   quest-level names for the heat/supplies meters (Lumara: Glow, Harvest baskets)
//   supportingTeks  extra standards the quest shows up under on Assign (read by lib/standardCodes.js)
//   rightFeedback task-level correct-answer message (the grader prefers it over its default)
//   tune.mode "point"  find/set the fraction at a point (no start/used story); tune.lines for two lines
//   travel.mode "point", travel.marks  labeled points on the path
//   fill.strip / fill.shade  strip-diagram fill; fill.lit  sections lit in order
//   scoops with waysNeeded 1 (task 14)
//   sort items carry image paths; the images are requested in image-prompts/

import TIDE_POOLS from "./quests/tide-pools.js";
import LAVA_LOCK from "./quests/lava-lock.js";
import ROBOT_REBUILD from "./quests/robot-rebuild.js";
import CANOPY_SUPPLY_DROP from "./quests/canopy-supply-drop.js";

export const QUESTS = {
  "MA.4.3E-XP": {
    id: "MA.4.3E-XP",
    standard: "MA.4.3E-XP",
    engine: "expedition_station",
    title: "The Frozen Relay",
    planet: "Frostveil",
    outpost: "Relay Outpost · −41°C",
    grade: 4,
    subject: "Math",
    teks: "4.3E",
    skillsChip: "4.3E · Add and subtract fractions",
    iCan:
      "I can add and subtract fractions that have the same bottom number. I can show how with pictures, a number line, and by adding in a different order.",
    blurb:
      "The relay tower on Frostveil went silent, and the crew is running low on heat and fuel. Every tank, cable, and power cell on this outpost is measured in fractions.",
    mission: "Add and subtract fractions to warm the outpost and restart the relay tower.",
    length: "15 tasks · 3 station visits",
    crew: ["Commander Vega", "Kai (engineer)", "Nova (scientist)", "S.A.M. (helper)"],
    channel: "CH 4.35 · FROSTVEIL RELAY",
    playableActs: [1],
    meterStart: { heat: 40, supplies: 3, journal: 0 },
    journalMax: 10,
    opening: [
      "Specialist {name}, this is Commander Vega. The relay tower on Frostveil went silent.",
      "Our crew is low on heat and fuel, and every tank, cable, and power cell here is measured in fractions.",
      "Help Kai and Nova add and subtract those fractions, and we'll get that tower talking again. Vega out.",
    ],
    acts: {
      1: {
        title: "Act 1 · Refuel the heater and find the beacon",
        short: "Refuel and find the beacon",
        complete: "The heater is warm and the beacon is back, {firstName}!",
        teaser:
          "Next on Frostveil: a storm is coming, and the cables and solar panels need fixing. Act 2 opens on your next station visit.",
        tasks: [1, 2, 3, 4],
        challenge: 5,
      },
      2: {
        title: "Act 2 · Fix the cables and clear the panels",
        short: "Fix cables and panels",
        // Content is written (Sept 26). Keep locked until the client supports
        // the Travel, Repair, and Numberless machines (see CONTENT_NOTES below).
        locked: true,
        opening: [
          "Welcome back, {firstName}. Nova here. A storm is rolling in over the ice ridge.",
          "The antenna cable snapped, and snow is piling up on the solar panels. Kai's cable log looks messy, too.",
          "Let's get everything fixed before the storm hits.",
        ],
        complete: "The cables are fixed and the panels are clear, {firstName}!",
        teaser:
          "Next on Frostveil: the path to the relay tower is open. Act 3 opens on your next station visit.",
        tasks: [6, 7, 8, 9],
        challenge: 10,
      },
      3: {
        title: "Act 3 · Reach the tower and restart the relay",
        short: "Reach the tower",
        locked: true,
        opening: [
          "Specialist {firstName}, Commander Vega again. The storm has passed, and the path to the relay tower is clear.",
          "Kai and Nova are hiking up the ridge with the power cells. The tower needs every bit of charge we can give it.",
          "Get that tower talking, and Frostveil is back on the map.",
        ],
        complete: "The relay tower is back online, {firstName}! Frostveil can talk to the whole station again.",
        teaser: "Mission complete. Commander Vega will send your next transmission soon.",
        tasks: [11, 12, 13, 14],
        challenge: 15,
      },
    },
    tasks: {
      1: {
        id: 1,
        act: 1,
        level: "Warm-up",
        title: "Refuel the heater",
        machine: "Fill",
        icon: "tank",
        speaker: "kai",
        line: "Brrr! The heater is almost out of fuel. I poured in 3/8 of a tank. Then I poured in 2/8 more. Can you set the gauge so it matches?",
        question: "How much fuel is in the heater now? Set the gauge, then press Pour.",
        hint: "Both pours are in eighths. How many eighths in all?",
        meter: { heat: 20, label: "Heat +20%", story: "Warms up the tents" },
        answer: { kind: "frac", n: 5, d: 8 },
        wrong: [
          { n: 5, d: 16, hint: "Look at the gauge. Did the pieces change size when Kai poured? Both pours are eighths." },
          { n: 1, d: 8, hint: "Kai poured fuel in two times. Does the tank get more fuel or less?" },
        ],
        fill: {
          denom: 8,
          start: 0,
          pours: [
            { n: 3, d: 8 },
            { n: 2, d: 8 },
          ],
        },
      },
      2: {
        id: 2,
        act: 1,
        level: "Warm-up",
        title: "Settle the tank debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "I poured 1/3 of a tank into the reserve tank. Then I poured another 1/3. That makes 2/6. Easy: 1 + 1 = 2 and 3 + 3 = 6!"',
        nova: 'Nova: "No way. The tank has 2/3 now. The parts are still thirds."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Draw 1/3 and 1/3 on the same tank. What size are the parts?",
        meter: { heat: 15, label: "Heat +15%", story: "The reserve fuel goes to the heater" },
        discovery: {
          id: "crystal",
          name: "Ice crystal",
          who: "Nova",
          fact: "Snowflakes are made of ice crystals. They usually have 6 sides or 6 arms because of the way water freezes.",
        },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. Both pours are thirds. 1 third + 1 third = 2 thirds. Adding doesn't change the size of the parts." },
          { id: "B", text: "Nova, because 2/3 has smaller numbers than 2/6." },
          { id: "C", text: "Kai. You add the top numbers and add the bottom numbers." },
          { id: "D", text: "Kai. Two pours means twice as many parts, so the bottom number doubles." },
        ],
        writtenPrompt: "Tell Kai in your own words why 1/3 + 1/3 is not 2/6.",
      },
      3: {
        id: 3,
        act: 1,
        level: "Warm-up",
        title: "Find the backup beacon",
        machine: "Tune",
        icon: "dial",
        speaker: "kai",
        line: "The backup beacon is buried in the snow. Its battery was at 5/6 before the storm. The cold used up 3/6. If I set the dial to what's left, the beacon will beep back!",
        question: "How much battery is left? Turn the dial, then press Lock signal.",
        hint: "Start at 5/6. Jump back one sixth at a time.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The beacon marks a buried supply crate" },
        discovery: {
          id: "aurora",
          name: "Aurora",
          who: "Kai",
          fact: "On Earth, auroras glow in the sky near the North and South Poles. They happen when tiny bits from the Sun crash into the air high above us.",
        },
        answer: { kind: "frac", n: 2, d: 6 },
        wrong: [
          { n: 3, d: 6, hint: "Start at 5/6 on the dial. Which way do you turn to take some away?" },
          { n: 1, d: 6, hint: "Count the jumps between marks, not the marks. Start counting after 5/6." },
          { n: 8, d: 6, hint: "The cold used up some battery. Should the number go up or down?" },
        ],
        tune: { denom: 6, start: { n: 5, d: 6 }, used: { n: 3, d: 6 } },
      },
      4: {
        id: 4,
        act: 1,
        level: "Warm-up",
        title: "Fuel the sled",
        machine: "Fill",
        icon: "scoop",
        speaker: "nova",
        line: "The sled needs 7/10 of a tank to reach the supply crate. Its tank already has 3/10 in it. Our scoops hold 1/10 or 2/10.",
        question: "How much more fuel does the sled need? Then fill it with scoops two different ways.",
        hint: "Start at 3/10. Count up by tenths to 7/10.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The sled hauls the crate back to camp" },
        discovery: {
          id: "moth",
          name: "Frost moth",
          who: "Nova",
          fact: "Some moths fly in winter. They shiver the muscles that move their wings to warm up before they take off.",
        },
        answer: {
          kind: "scoops",
          missing: { n: 4, d: 10 },
          target: { n: 7, d: 10 },
          start: { n: 3, d: 10 },
          scoopSizes: [1, 2],
          waysNeeded: 2,
        },
        wrong: [
          { n: 10, d: 10, hint: "The tank already has some fuel. How much more to get from 3/10 up to 7/10?" },
          { n: 7, d: 10, hint: "Look at the tank before you pour. Is it empty?" },
        ],
        fill: { denom: 10, start: 3, target: 7 },
      },
      5: {
        id: 5,
        act: 1,
        level: "Challenge",
        challenge: true,
        title: "The cold snap",
        machine: "Fill",
        icon: "snap",
        speaker: "vega",
        line: "Surprise, the cold snap! The heater tank was at 7/8. The heater burned 2/8 each night for 2 nights. Then Kai added 3/8. The heater runs safely at the 5/8 line or above.",
        question: "What is the tank level now? How far above the safe line is the fuel?",
        hint: "Take it one night at a time. Then count the jumps from the safe line to the fuel.",
        meter: { heat: 10, label: "Heat +10%", story: "The heater stays safe through the cold snap" },
        discovery: {
          id: "sundog",
          name: "Sun dog",
          who: "Nova",
          fact: "Sun dogs are bright spots on each side of the Sun. Tiny ice crystals in the air bend the sunlight to make them.",
        },
        answer: { kind: "challenge", level: { n: 6, d: 8 }, above: { n: 1, d: 8 } },
        wrong: [
          { step: 1, n: 8, d: 8, hint: "Take it one night at a time. How many times did the heater burn fuel?" },
          { step: 1, n: 0, d: 8, hint: "Kai added fuel. Does adding make the tank go up or down?" },
          { step: 1, n: 3, d: 8, hint: "Read the story again. What happened after the two nights?" },
          { step: 2, n: 11, d: 8, hint: "You're finding the space between two lines on the same tank. Can that be bigger than the tank?" },
          { step: 2, n: 2, d: 8, hint: "Count the jumps from the safe line up to the fuel, not the lines." },
        ],
        fill: { denom: 8, start: 7, burn: 2, nights: 2, refill: 3, safe: 5 },
      },
      6: {
        id: 6,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Cut the antenna cable",
        machine: "Travel",
        icon: "cable",
        speaker: "kai",
        line: "The storm snapped our antenna cable! The cable on the spool is 2 3/4 meters long. The new antenna needs 1 1/4 meters. I'll cut that much off the spool.",
        question: "How much cable will be left on the spool? Jump back on the measuring line, then press Cut.",
        hint: "Start at 2 3/4. Take away the 1 whole first, then the 1 fourth.",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The leftover cable goes in the repair kit" },
        discovery: {
          id: "fox",
          name: "Arctic fox paws",
          who: "Nova",
          fact: "Arctic foxes have thick fur on the bottoms of their paws. It helps keep their feet warm when they walk on snow and ice.",
        },
        answer: { kind: "frac", n: 6, d: 4 },
        wrong: [
          { n: 16, d: 4, hint: "Kai is cutting some cable off. Should the spool have more cable or less?" },
          { n: 5, d: 4, hint: "Check the fourths. 3 fourths take away 1 fourth is how many fourths?" },
          { n: 10, d: 4, hint: "Did you take away the whole meter, too? Take away the wholes, then the fourths." },
        ],
        // Travel machine: a measuring line in fourths from 0 to 3. The rover
        // (here, a cable marker) starts at `start` and the student jumps back.
        travel: { denom: 4, max: 3, start: { n: 11, d: 4 }, move: { n: -5, d: 4 }, label: "meters", mixed: true },
      },
      7: {
        id: 7,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Check Kai's cable log",
        machine: "Repair",
        icon: "log",
        speaker: "nova",
        line: "Kai wrote this in his cable log last night: \"I joined a 3/5 meter cable and a 1/5 meter cable. Now I have 4/10 of a meter.\" That doesn't look right to me.",
        question: "Tap the part of Kai's math that is wrong. Pick what went wrong, then write the right answer.",
        hint: "When you put two fifths of a meter together, are the pieces still fifths?",
        meter: { heat: 5, label: "Heat +5%", story: "The heater cable is joined the right way" },
        answer: { kind: "mistake", tap: "denominator", error: "A", fix: { n: 4, d: 5 } },
        repair: {
          log: [
            { id: "a", text: "3/5" },
            { id: "op", text: "+" },
            { id: "b", text: "1/5" },
            { id: "eq", text: "=" },
            { id: "numerator", text: "4" },
            { id: "denominator", text: "/10" },
          ],
          errors: [
            { id: "A", text: "He added the bottom numbers. The parts are still fifths." },
            { id: "B", text: "He added the top numbers wrong. 3 + 1 is not 4." },
            { id: "C", text: "He should have subtracted. Joining cables makes them shorter." },
          ],
        },
        wrong: [
          { error: "B", hint: "Check the top numbers again: 3 fifths and 1 fifth. How many fifths is that?" },
          { error: "C", hint: "When Kai joins two cables, does he get a longer cable or a shorter one?" },
          { n: 4, d: 10, hint: "That's Kai's answer (it's the same as 2/5). Joining cables makes them longer, and the pieces stay fifths." },
        ],
      },
      8: {
        id: 8,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Clear the solar grid",
        machine: "Fill",
        icon: "grid",
        speaker: "kai",
        line: "Snow is covering 9/12 of the solar grid. I swept off 4/12 this morning. Nova swept off 3/12 after lunch.",
        question: "How much of the solar grid is still covered in snow? Shade the grid, then press Check.",
        hint: "Start with 9 twelfths covered. Take away each sweep, one at a time.",
        meter: { heat: 5, label: "Heat +5%", story: "The panels charge the heater's backup battery" },
        discovery: {
          id: "snowhouse",
          name: "Snow shelter",
          who: "Kai",
          fact: "Fluffy snow is mostly trapped air. That's why a snow shelter can stay much warmer inside than the freezing air outside.",
        },
        answer: { kind: "frac", n: 2, d: 12 },
        wrong: [
          { n: 7, d: 12, hint: "That's how much Kai and Nova swept off. How much snow is left on the grid?" },
          { n: 5, d: 12, hint: "Nova swept after lunch, too. Did you take away both sweeps?" },
          { n: 16, d: 12, hint: "Sweeping takes snow away. Should the covered part get bigger or smaller?" },
        ],
        // Fill machine, grid variant: 12 squares, 9 start shaded.
        fill: { denom: 12, start: 9, grid: { rows: 3, cols: 4 }, sweeps: [{ n: 4, d: 12 }, { n: 3, d: 12 }] },
      },
      9: {
        id: 9,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Fill the water tank",
        machine: "Numberless",
        icon: "water",
        speaker: "nova",
        line: "Nova filled part of the water tank. Then Kai added some more. The tank still isn't full.",
        question: "First, pick the questions we could answer with this story. Then the numbers will show up.",
        hint: "A full tank is 10/10. How much water is in it now?",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The crew has drinking water for the storm" },
        answer: {
          kind: "numberless",
          sensible: ["total", "more", "who"],
          missing: { n: 3, d: 10 },
        },
        numberless: {
          questions: [
            { id: "total", text: "How much water is in the tank now?" },
            { id: "more", text: "How much more water will fill the tank?" },
            { id: "who", text: "Who added more water, Nova or Kai?" },
            { id: "color", text: "What color is the water tank?" },
          ],
          reveal: "Nova filled 3/10 of the tank. Kai added 4/10 more.",
          ask: "How much more water will fill the tank?",
          denom: 10,
          pours: [
            { n: 3, d: 10 },
            { n: 4, d: 10 },
          ],
        },
        wrong: [
          { step: "questions", hint: "Can the story tell us that? Pick only questions that use the amounts of water." },
          { n: 7, d: 10, hint: "That's how much is in the tank now. How much more to reach full?" },
          { n: 1, d: 10, hint: "That's how much more Kai added than Nova. The question asks about filling the tank." },
          { n: 17, d: 10, hint: "A full tank is 10/10. Can the tank need more than a whole tank?" },
        ],
      },
      10: {
        id: 10,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "Challenge",
        challenge: true,
        title: "The ice quake",
        machine: "Travel",
        icon: "quake",
        speaker: "vega",
        line: "Surprise, an ice quake! Kai drove the rover 5/8 km toward the tower. A crack opened, so he backed up 2/8 km. Then he found a safe path and drove 6/8 km more. The tower is at the 1 4/8 km mark.",
        question: "Where is the rover now? How much farther is the tower?",
        hint: "Follow the rover one move at a time on the track. Backing up means going back.",
        meter: { heat: 5, label: "Heat +5%", story: "The rover makes it past the crack" },
        discovery: {
          id: "glacier",
          name: "Glacier",
          who: "Nova",
          fact: "A glacier is a huge sheet of ice that moves very slowly, like a frozen river. Some move less than a meter a day.",
        },
        answer: { kind: "steps", steps: [{ n: 9, d: 8 }, { n: 3, d: 8 }] },
        wrong: [
          { step: 1, n: 13, d: 8, hint: "Kai backed up. Does backing up move the rover forward or back?" },
          { step: 1, n: 11, d: 8, hint: "Kai backed up 2/8 km in the middle. Did you count that move?" },
          { step: 1, n: 3, d: 8, hint: "The rover drove forward twice and back once. Follow each move on the track." },
          { step: 2, n: 21, d: 8, hint: "You're finding the distance between the rover and the tower. Should you add or subtract?" },
          { step: 2, n: 4, d: 8, hint: "Count the jumps from the rover to the tower, not the marks." },
        ],
        travel: {
          denom: 8,
          max: 2,
          start: { n: 0, d: 8 },
          moves: [
            { n: 5, d: 8 },
            { n: -2, d: 8 },
            { n: 6, d: 8 },
          ],
          goal: { n: 12, d: 8 },
          label: "km",
          mixed: true,
        },
      },
      11: {
        id: 11,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Reach the tower",
        machine: "Travel",
        icon: "trail",
        speaker: "nova",
        line: "Kai and I took different trails up the ridge. Kai hiked 2/6 of a kilometer, rested, then hiked 3/6 more. I hiked 4/6 of a kilometer without stopping.",
        question: "Who hiked farther? How much farther?",
        hint: "Find Kai's total first. Then compare it to Nova's 4/6 on the same track.",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The crew finds the tower's supply locker" },
        discovery: {
          id: "penguins",
          name: "Penguin huddle",
          who: "Kai",
          fact: "On Earth, emperor penguins huddle close together during Antarctic winter storms. They take turns in the warm middle of the group.",
        },
        answer: { kind: "compare", who: "kai", diff: { n: 1, d: 6 } },
        wrong: [
          { who: "nova", hint: "Add Kai's two hikes together first. Then compare." },
          { n: 5, d: 6, hint: "That's how far Kai hiked. The question asks how much farther." },
          { n: 9, d: 6, hint: "You're comparing the two hikes. Should you add Nova's hike or subtract it?" },
        ],
        travel: {
          denom: 6,
          max: 1,
          tracks: [
            { who: "kai", moves: [{ n: 2, d: 6 }, { n: 3, d: 6 }] },
            { who: "nova", moves: [{ n: 4, d: 6 }] },
          ],
          label: "km",
        },
      },
      12: {
        id: 12,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "The charger debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "The charger shows three cells: 2/8, 5/8, and 6/8. You HAVE to add them in order, left to right. Any other way is cheating!"',
        nova: 'Nova: "I added 2/8 + 6/8 first, because that makes 1 whole. Then I added 5/8. I got 1 5/8 — the same answer."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Try it both ways. Do you get the same total?",
        meter: { heat: 5, label: "Heat +5%", story: "The charger warms up" },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. You can add fractions in any order and get the same total. Making 1 whole first just makes it easier." },
          { id: "B", text: "Nova, because 6/8 is the biggest number, so it should go first." },
          { id: "C", text: "Kai. Changing the order changes the answer." },
          { id: "D", text: "Kai. You always have to add from left to right, or it doesn't count." },
        ],
        writtenPrompt: "Tell Kai in your own words why Nova's way still works.",
        debateHints: {
          wrongWho: "Try adding the cells both ways. Do you get the same total?",
          wrongReason: "Right person, check the reason. Does changing the order change the total?",
          right: "Nova is right — you can add in any order and get the same total.",
        },
      },
      13: {
        id: 13,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Pack the power cells",
        machine: "Sort Bay",
        icon: "cells",
        speaker: "kai",
        line: "Each power pack holds two cells. The tower needs packs with at least 1 whole charge. Help me sort them before we carry them in.",
        question: "Add the two cells in each pack. Sort each pack into the right bin.",
        hint: "Add the top numbers. Then check: is it fewer parts than 1 whole, exactly 1 whole, or more?",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The strongest packs go to the tower" },
        discovery: {
          id: "icicle",
          name: "Icicles",
          who: "Nova",
          fact: "Icicles grow when melting snow drips and freezes again. They get longer one drop at a time.",
        },
        answer: {
          kind: "sort",
          bins: { p1: "one", p2: "less", p3: "more", p4: "less", p5: "one", p6: "more" },
        },
        sort: {
          bins: [
            { id: "less", label: "Less than 1 whole" },
            { id: "one", label: "Exactly 1 whole" },
            { id: "more", label: "More than 1 whole" },
          ],
          items: [
            { id: "p1", label: "3/4 + 1/4" },
            { id: "p2", label: "2/5 + 2/5" },
            { id: "p3", label: "5/6 + 2/6" },
            { id: "p4", label: "3/8 + 4/8" },
            { id: "p5", label: "7/10 + 3/10" },
            { id: "p6", label: "4/12 + 9/12" },
          ],
        },
        wrong: [
          { item: "p2", hint: "2 fifths + 2 fifths is 4 fifths. How many fifths make 1 whole?" },
          { item: "p4", hint: "3 eighths + 4 eighths is 7 eighths. Is that enough for 1 whole?" },
          { item: "p3", hint: "5 sixths + 2 sixths is 7 sixths. How many sixths make 1 whole?" },
          { item: "p6", hint: "4 twelfths + 9 twelfths is 13 twelfths. Is that more than 12 twelfths?" },
        ],
      },
      14: {
        id: 14,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Top off the tower battery",
        machine: "Fill",
        icon: "battery",
        speaker: "kai",
        line: "The tower battery is at 5/12. It needs to reach 11/12 before the relay can start.",
        question: "How much charge do we need to add? Set the charger, then press Charge.",
        hint: "Start at 5/12. Count up by twelfths to 11/12.",
        meter: { heat: 5, label: "Heat +5%", story: "The tower's heaters turn on" },
        answer: { kind: "frac", n: 6, d: 12 },
        wrong: [
          { n: 16, d: 12, hint: "The battery already has some charge. How much more to get from 5/12 to 11/12?" },
          { n: 11, d: 12, hint: "Look at the battery before you charge it. Is it empty?" },
          { n: 7, d: 12, hint: "Count the jumps from 5/12 to 11/12 again, one twelfth at a time." },
        ],
        fill: { denom: 12, start: 5, target: 11 },
      },
      15: {
        id: 15,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "Challenge",
        challenge: true,
        title: "Restart the relay",
        machine: "Fill",
        icon: "relay",
        speaker: "vega",
        line: "This is it! The three power cells hold 3/6, 5/6, and 2/6 of a charge. The relay needs 1 2/6 to restart. Nova's radio needs 1/6 from whatever is left over.",
        question: "Step 1: What is the total charge? Step 2: How much is left after the relay restarts? Step 3: How much is left after Nova charges her radio?",
        hint: "Add all three cells first. Then take away one amount at a time.",
        meter: { heat: 10, label: "Heat +10%", story: "The relay tower comes back online" },
        discovery: {
          id: "frost",
          name: "Frost",
          who: "Kai",
          fact: "Frost forms when water vapor in the air freezes right onto a cold surface. It turns into ice without becoming liquid water first.",
        },
        answer: { kind: "steps", steps: [{ n: 10, d: 6 }, { n: 2, d: 6 }, { n: 1, d: 6 }] },
        wrong: [
          { step: 1, n: 10, d: 18, hint: "The cells are all sixths. Do the parts change size when you add them?" },
          { step: 1, n: 8, d: 6, hint: "There are three cells. Did you add all three?" },
          { step: 2, n: 18, d: 6, hint: "The relay uses up charge. Should you add or subtract?" },
          { step: 2, n: 8, d: 6, hint: "That's what the relay needs. How much is left after the relay takes it?" },
          { step: 3, n: 3, d: 6, hint: "Nova's radio uses charge, too. Should the leftover go up or down?" },
        ],
        fill: { denom: 6, cells: [{ n: 3, d: 6 }, { n: 5, d: 6 }, { n: 2, d: 6 }], need: { n: 8, d: 6 }, radio: { n: 1, d: 6 } },
      },
    },
  },
  "MA.3.3A-XP": {
    id: "MA.3.3A-XP",
    standard: "MA.3.3A-XP",
    engine: "expedition_station",
    title: "The Glow Garden Harvest",
    planet: "Lumara",
    outpost: "Glow Garden · festival night",
    grade: 3,
    subject: "Math",
    teks: "3.3A",
    // Main focus is 3.3A. The quest also shows up under these standards on
    // the Assign page (lib/standardCodes.js reads this list).
    supportingTeks: ["3.3B", "3.3C", "3.3D", "3.7A"],
    skillsChip: "3.3A · Show fractions with pictures and number lines",
    iCan: "I can show a fraction with pictures, strip diagrams, and number lines. I can find the fraction at a point on a number line.",
    blurb:
      "Lumara's Glow Garden is getting ready for its harvest festival, but the garden's lights are going dim. Every basket, lantern, and path here is split into equal parts.",
    mission: "Split the harvest into equal parts and light the path to the festival stage.",
    length: "15 tasks · 3 station visits",
    crew: ["Commander Vega", "Kai (engineer)", "Nova (scientist)", "S.A.M. (helper)"],
    channel: "CH 3.30 · LUMARA GLOW GARDEN",
    playableActs: [1],
    // Same meter keys as Frostveil so the client works unchanged; the labels
    // tell the client what to call them on this planet (see CONTENT_NOTES).
    meterStart: { heat: 30, supplies: 0, journal: 0 },
    meterLabels: { heat: "Glow", heatUnit: "%", supplies: "Harvest", suppliesUnit: "baskets" },
    journalMax: 10,
    grade3Limits: "Denominators 2, 3, 4, 6, 8 only. Every fraction is more than 0 and no more than 1. Students count equal parts; no adding fractions with symbols.",
    opening: [
      "Specialist {name}, this is Commander Vega. The Glow Garden on Lumara is going dim, right before its harvest festival.",
      "The crew needs to split the harvest into equal parts and power the garden lights. Every basket, lantern, and path here is measured in fractions.",
      "Help Kai and Nova, and the festival can start on time. Vega out.",
    ],
    acts: {
      1: {
        title: "Act 1 · Split the harvest",
        short: "Split the harvest",
        complete: "The harvest is split and the lanterns are glowing, {firstName}!",
        teaser: "Next on Lumara: the festival path needs lanterns from the gate to the stage. Act 2 opens on your next station visit.",
        tasks: [1, 2, 3, 4],
        challenge: 5,
      },
      2: {
        title: "Act 2 · Light the firefly path",
        short: "Light the firefly path",
        locked: true,
        opening: [
          "Welcome back, {firstName}. Nova here. The festival path runs through the garden from the gate to the stage.",
          "We need to place lanterns along it, and Kai's notes are a little mixed up.",
        ],
        complete: "The firefly path is lit from the gate halfway to the stage, {firstName}!",
        teaser: "Next on Lumara: the festival starts at moonrise. Act 3 opens on your next station visit.",
        tasks: [6, 7, 8, 9],
        challenge: 10,
      },
      3: {
        title: "Act 3 · Open the festival",
        short: "Open the festival",
        locked: true,
        opening: [
          "Specialist {firstName}, Commander Vega. The festival starts at moonrise.",
          "Help the crew finish the lanterns and light up the stage.",
        ],
        complete: "The Glow Garden is shining, and the harvest festival can begin, {firstName}!",
        teaser: "Mission complete. Commander Vega will send your next transmission soon.",
        tasks: [11, 12, 13, 14],
        challenge: 15,
      },
    },
    tasks: {
      1: {
        id: 1,
        act: 1,
        level: "Warm-up",
        title: "Fill the juice tank",
        machine: "Fill",
        icon: "tank",
        speaker: "kai",
        line: "The glowberry juice tank has 4 equal parts. I filled 1 part. Can you set the gauge so it matches?",
        question: "What fraction of the tank is full? Set the gauge, then press Pour.",
        hint: "Count the equal parts in the whole tank. How many are full?",
        meter: { heat: 15, label: "Glow +15%", story: "Glowberry juice powers the garden lamps" },
        answer: { kind: "frac", n: 1, d: 4 },
        rightFeedback: "Yes — 1 of 4 equal parts is 1/4.",
        wrong: [
          { n: 1, d: 3, hint: "Count the parts, not the lines between them. How many equal parts does the whole tank have?" },
          { n: 4, d: 1, hint: "The bottom number tells how many equal parts make the whole. The top number tells how many are full." },
        ],
        fill: { denom: 4, start: 0, pours: [{ n: 1, d: 4 }] },
      },
      2: {
        id: 2,
        act: 1,
        level: "Warm-up",
        title: "The moon-leaf debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "I cut this moon-leaf into 4 pieces, so each piece is 1/4!" (Two pieces are big and two are tiny.)',
        nova: 'Nova: "Those pieces aren\'t the same size. They aren\'t fourths."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Look at the size of each piece. Are they all the same?",
        meter: { heat: 10, label: "Glow +10%", story: "The moon-leaf is cut fairly for the festival table" },
        discovery: {
          id: "firefly",
          name: "Fireflies",
          who: "Nova",
          fact: "Fireflies make light with a chemical reaction inside their bodies. Their light gives off almost no heat.",
        },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. Fourths are 4 EQUAL parts. Kai's pieces are different sizes." },
          { id: "B", text: "Nova, because a leaf can't be cut into 4 pieces." },
          { id: "C", text: "Kai. Any 4 pieces are fourths." },
          { id: "D", text: "Kai. The number of pieces is all that matters." },
        ],
        writtenPrompt: "Tell Kai in your own words why his pieces are not fourths.",
        debateHints: {
          wrongWho: "Look at the pieces. Would you want the tiny piece if someone said it was a fair share?",
          wrongReason: "Right person, check the reason. What has to be true about the pieces?",
          right: "Nova is right — fourths have to be 4 equal parts.",
        },
      },
      3: {
        id: 3,
        act: 1,
        level: "Warm-up",
        title: "Tune the light beacon",
        machine: "Tune",
        icon: "dial",
        speaker: "kai",
        line: "The light beacon's dial goes from 0 to 1, and it's split into thirds. The signal is 2 jumps from 0. If I set the dial right, the beacon will glow!",
        question: "What fraction is the signal at? Turn the dial, then press Lock signal.",
        hint: "Count the jumps from 0, not the tick marks.",
        meter: { heat: 10, label: "Glow +10%", story: "The beacon lights the garden gate" },
        discovery: {
          id: "foxfire",
          name: "Glowing mushrooms",
          who: "Kai",
          fact: "Some mushrooms glow in the dark. People have called their soft green light \"foxfire.\"",
        },
        answer: { kind: "frac", n: 2, d: 3 },
        rightFeedback: "Locked! 2 jumps of 1/3 lands on 2/3.",
        wrong: [
          { n: 2, d: 4, hint: "There are 4 tick marks, but how many equal spaces are between 0 and 1?" },
          { n: 1, d: 3, hint: "The signal is 2 jumps from 0. Count both jumps." },
          { n: 3, d: 3, hint: "3/3 is all the way at 1. The signal is 2 jumps from 0." },
        ],
        tune: { denom: 3, mode: "point", start: { n: 0, d: 3 }, jumps: 2 },
      },
      4: {
        id: 4,
        act: 1,
        level: "Warm-up",
        title: "Fill the nectar jar",
        machine: "Fill",
        icon: "scoop",
        speaker: "nova",
        line: "The nectar jar is empty. It needs to be filled to 5/6 for the festival. Our scoops hold 1/6 or 2/6.",
        question: "How much nectar will you pour in all? Then fill the jar with scoops two different ways.",
        missingPrompt: "How much nectar will you pour in all?",
        hint: "Count by sixths as each scoop goes in.",
        meter: { supplies: 1, label: "Harvest +1 basket", story: "Nectar for the festival treats" },
        discovery: {
          id: "beevision",
          name: "Bee vision",
          who: "Nova",
          fact: "Bees can see ultraviolet light. Many flowers have patterns that bees can see but people can't.",
        },
        answer: {
          kind: "scoops",
          missing: { n: 5, d: 6 },
          target: { n: 5, d: 6 },
          start: { n: 0, d: 6 },
          scoopSizes: [1, 2],
          waysNeeded: 2,
        },
        rightFeedback: "Two ways to 5/6 — the nectar jar is ready!",
        wrong: [
          { n: 6, d: 6, hint: "6/6 fills the whole jar. The jar only needs to reach 5/6." },
          { n: 4, d: 6, hint: "Count the sixths again. Where is the 5/6 line?" },
        ],
        fill: { denom: 6, start: 0, target: 5 },
      },
      5: {
        id: 5,
        act: 1,
        level: "Challenge",
        challenge: true,
        title: "The flickering lanterns",
        machine: "Fill",
        icon: "snap",
        speaker: "vega",
        line: "Surprise, the lantern strip is flickering! The strip has 8 equal sections. Nova lit 3 sections. Then Kai lit 2 more sections.",
        question: "Step 1: What fraction of the strip is lit? Step 2: What fraction of the strip is still dark?",
        stepPrompts: ["Step 1: What fraction of the lantern strip is lit?", "Step 2: What fraction of the strip is still dark?"],
        stepButtons: ["Check lit part", "Check dark part"],
        hint: "Count the lit sections out of 8. Then count the dark ones.",
        meter: { heat: 10, label: "Glow +10%", story: "The lantern strip stays lit" },
        discovery: {
          id: "moonlight",
          name: "Moonlight",
          who: "Nova",
          fact: "The Moon doesn't make its own light. Moonlight is sunlight bouncing off the Moon.",
        },
        answer: { kind: "steps", steps: [{ n: 5, d: 8 }, { n: 3, d: 8 }] },
        rightFeedback: "5/8 lit and 3/8 dark — all 8 eighths are accounted for!",
        wrong: [
          { step: 1, n: 5, d: 16, hint: "The strip still has 8 equal sections. How many of the 8 are lit?" },
          { step: 1, n: 3, d: 8, hint: "Kai lit 2 more sections after Nova. Count all the lit sections." },
          { step: 1, n: 2, d: 8, hint: "Nova lit some sections first. Count all the lit sections." },
          { step: 2, n: 5, d: 8, hint: "That's the lit part. How many sections are still dark?" },
        ],
        fill: { denom: 8, strip: true, start: 0, lit: [3, 2] },
      },
      6: {
        id: 6,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Follow the glow sprite",
        machine: "Travel",
        icon: "trail",
        speaker: "nova",
        line: "The firefly path goes from the gate at 0 to the stage at 1. It's split into 6 equal spaces. A glow sprite flew from the gate and landed at the 4th mark.",
        question: "What fraction of the path did the glow sprite fly? Mark it, then press Land.",
        hint: "Count the equal spaces from 0 to where the sprite landed.",
        meter: { heat: 5, label: "Glow +5%", story: "The sprite shows where the first lantern goes" },
        discovery: {
          id: "glowworm",
          name: "Glowworm caves",
          who: "Kai",
          fact: "In some caves in New Zealand, glowworms hang glowing, sticky threads to catch insects.",
        },
        answer: { kind: "frac", n: 4, d: 6 },
        rightFeedback: "The sprite flew 4 of 6 equal spaces: 4/6 of the path.",
        wrong: [
          { n: 4, d: 7, hint: "There are 7 tick marks, but how many equal spaces are between 0 and 1?" },
          { n: 2, d: 6, hint: "That's how far the sprite is from the stage. How far did it fly from the gate?" },
          { n: 5, d: 6, hint: "Start counting after 0. The first jump lands on the first mark." },
        ],
        travel: { denom: 6, max: 1, start: { n: 0, d: 6 }, mode: "point", label: "of the path" },
      },
      7: {
        id: 7,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Check Kai's vine notes",
        machine: "Repair",
        icon: "log",
        speaker: "nova",
        line: "Kai wrote this in his garden notes: \"I split the glow vine into 3 equal parts and picked 1 part. That's 3/1 of the vine.\" Something is off.",
        question: "Tap the part of Kai's note that is wrong. Pick what went wrong, then write the right fraction.",
        hint: "The bottom number tells how many equal parts make the whole vine.",
        meter: { supplies: 1, label: "Harvest +1 basket", story: "The vine fruit is picked the right way" },
        answer: { kind: "mistake", tap: "frac", error: "A", fix: { n: 1, d: 3 } },
        rightFeedback: "Fixed! 1 of 3 equal parts is 1/3.",
        repair: {
          log: [
            { id: "split", text: "split the vine into 3 equal parts" },
            { id: "picked", text: "picked 1 part" },
            { id: "frac", text: "That's 3/1" },
          ],
          errors: [
            { id: "A", text: "The numbers are flipped. The top number is the parts he picked; the bottom is the equal parts in the whole." },
            { id: "B", text: "He should have split the vine into 1 part." },
            { id: "C", text: "He picked too many parts." },
          ],
        },
        wrong: [
          { error: "B", hint: "A vine in 1 part isn't split at all. Look at how Kai wrote the fraction." },
          { error: "C", hint: "Kai picked just 1 part. Look at how he wrote the fraction." },
          { n: 3, d: 1, hint: "That's Kai's answer. Which number tells how many equal parts the vine has?" },
          { n: 1, d: 1, hint: "1/1 is the whole vine. Kai picked 1 of 3 equal parts." },
        ],
      },
      8: {
        id: 8,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Plant the moss strip",
        machine: "Fill",
        icon: "grid",
        speaker: "kai",
        line: "This moss strip is 1 whole, and it's cut into fourths. The glow moss needs to cover 3/4 of it.",
        question: "Shade 3/4 of the moss strip, then press Plant.",
        hint: "The strip has 4 equal parts. How many should you shade?",
        meter: { heat: 5, label: "Glow +5%", story: "The glow moss lights the path edges" },
        discovery: {
          id: "sunflower",
          name: "Sunflowers",
          who: "Nova",
          fact: "Young sunflowers turn to face the Sun as it moves across the sky.",
        },
        answer: { kind: "frac", n: 3, d: 4 },
        rightFeedback: "3 of 4 equal parts shaded — that's 3/4!",
        wrong: [
          { n: 1, d: 4, hint: "You shaded 1 part. The moss needs to cover 3 of the 4 parts." },
          { n: 4, d: 4, hint: "That covers the whole strip. The moss only needs 3/4." },
        ],
        fill: { denom: 4, strip: true, start: 0, shade: true },
      },
      9: {
        id: 9,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "The glowberry pie",
        machine: "Numberless",
        icon: "pie",
        speaker: "nova",
        line: "The crew baked a glowberry pie and cut it into equal slices. They ate some at lunch.",
        question: "First, pick the questions we could answer with this story. Then the numbers will show up.",
        hint: "The whole pie is all the slices. How many slices are left?",
        meter: { supplies: 1, label: "Harvest +1 basket", story: "Leftover pie goes to the festival table" },
        answer: { kind: "numberless", sensible: ["left", "ate", "slices"], missing: { n: 3, d: 8 } },
        rightFeedback: "3 of 8 slices are left: 3/8 of the pie.",
        numberless: {
          questions: [
            { id: "left", text: "What fraction of the pie is left?" },
            { id: "ate", text: "What fraction of the pie did they eat?" },
            { id: "slices", text: "How many slices were there?" },
            { id: "time", text: "What time did they eat lunch?" },
          ],
          reveal: "The pie was cut into 8 equal slices. The crew ate 5 slices.",
          ask: "What fraction of the pie is left?",
          denom: 8,
          eaten: 5,
        },
        wrong: [
          { step: "questions", hint: "Can the story tell us that? Pick only questions about the pie and its slices." },
          { n: 5, d: 8, hint: "That's the part they ate. How much of the pie is left?" },
          { n: 3, d: 5, hint: "The whole pie had 8 equal slices. Out of 8, how many are left?" },
        ],
      },
      10: {
        id: 10,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "Challenge",
        challenge: true,
        title: "The smudged path map",
        machine: "Tune",
        icon: "quake",
        speaker: "vega",
        line: "Surprise, the rain smudged the path map! Only 0 and 1 are still labeled on each line.",
        question: "Step 1: This line is cut into fourths. The first beacon is halfway between 1/4 and 3/4. What fraction is it at? Step 2: This line is cut into sixths. The second beacon is one jump before 1. What fraction is it at?",
        hint: "Label each tick mark yourself, starting from 0.",
        meter: { heat: 5, label: "Glow +5%", story: "Both beacons light the way" },
        discovery: {
          id: "glowwave",
          name: "Glowing waves",
          who: "Nova",
          fact: "Some ocean waves glow blue at night because of tiny living things in the water.",
        },
        answer: { kind: "steps", steps: [{ n: 2, d: 4 }, { n: 5, d: 6 }] },
        rightFeedback: "Both beacons found: 2/4 and 5/6!",
        wrong: [
          { step: 1, n: 2, d: 5, hint: "Count the equal spaces between 0 and 1, not the tick marks." },
          { step: 1, n: 1, d: 4, hint: "The beacon is between 1/4 and 3/4. Which mark is in the middle?" },
          { step: 2, n: 1, d: 6, hint: "That's the size of the jump. Where does the beacon sit?" },
          { step: 2, n: 5, d: 7, hint: "Count the equal spaces between 0 and 1, not the tick marks." },
        ],
        tune: { mode: "point", lines: [{ denom: 4, labeled: [0, 4] }, { denom: 6, labeled: [0, 6] }] },
      },
      11: {
        id: 11,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Sort the lantern shades",
        machine: "Sort Bay",
        icon: "cells",
        speaker: "kai",
        line: "Each lantern shade has one part that glows. Sort them by the fraction that glows. Watch out: one shade isn't split fairly!",
        question: "Sort each lantern shade into the right bin.",
        hint: "Count the parts. Then check: are they all the same size?",
        meter: { supplies: 1, label: "Harvest +1 basket", story: "The lanterns are hung around the stage" },
        discovery: {
          id: "pollen",
          name: "Pollen",
          who: "Nova",
          fact: "Bees carry pollen from flower to flower. This helps plants make seeds.",
        },
        answer: {
          kind: "sort",
          bins: { s1: "half", s2: "fourth", s3: "third", s4: "unequal", s5: "half", s6: "third" },
        },
        rightFeedback: "Every shade is sorted — and you caught the unfair one!",
        sort: {
          bins: [
            { id: "half", label: "1/2 glows" },
            { id: "third", label: "1/3 glows" },
            { id: "fourth", label: "1/4 glows" },
            { id: "unequal", label: "Not a fraction (parts aren't equal)" },
          ],
          // Images: see image-prompts/expedition-station/glow-garden-harvest.md
          items: [
            { id: "s1", label: "Circle, 2 equal parts, 1 glowing", image: "/expedition/glow-garden/shade-circle-halves.png" },
            { id: "s2", label: "Square, 4 equal parts, 1 glowing", image: "/expedition/glow-garden/shade-square-fourths.png" },
            { id: "s3", label: "Strip, 3 equal parts, 1 glowing", image: "/expedition/glow-garden/shade-strip-thirds.png" },
            { id: "s4", label: "Circle, 4 unequal parts, 1 glowing", image: "/expedition/glow-garden/shade-circle-unequal.png" },
            { id: "s5", label: "Rectangle, 2 equal parts, 1 glowing", image: "/expedition/glow-garden/shade-rectangle-halves.png" },
            { id: "s6", label: "Hexagon, 3 equal parts, 1 glowing", image: "/expedition/glow-garden/shade-hexagon-thirds.png" },
          ],
        },
        wrong: [
          { item: "s4", hint: "Look closely at the circle with 4 parts. Are all 4 parts the same size?" },
          { item: "s3", hint: "Count the parts in the strip. How many equal parts are there?" },
          { item: "s6", hint: "Count the parts in the hexagon. How many equal parts are there?" },
          { item: "s2", hint: "Count the parts in the square. How many equal parts are there?" },
        ],
      },
      12: {
        id: 12,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "The tick mark debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "This number line has 5 tick marks, and the dot is on the 4th one. So the dot is at 3/5."',
        nova: 'Nova: "No — there are 4 equal spaces between 0 and 1. The dot is 3 spaces from 0, so it\'s at 3/4."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Count the spaces between 0 and 1, not the tick marks.",
        meter: { heat: 5, label: "Glow +5%", story: "The stage map is fixed" },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. The bottom number is the number of equal SPACES from 0 to 1. There are 4 spaces, and the dot is 3 spaces from 0." },
          { id: "B", text: "Nova, because 3/4 is a friendlier number than 3/5." },
          { id: "C", text: "Kai. Count the tick marks to find the bottom number." },
          { id: "D", text: "Kai. The dot is on the 4th mark, so the answer has to have a 5 in it." },
        ],
        writtenPrompt: "Tell Kai in your own words how to find the fraction for a point on a number line.",
        debateHints: {
          wrongWho: "Count the spaces between 0 and 1. How many equal jumps are there?",
          wrongReason: "Right person, check the reason. What does the bottom number count on a number line?",
          right: "Nova is right — count the equal spaces, not the tick marks.",
        },
      },
      13: {
        id: 13,
        locked: true, // remove when the client supports point mode on the Tune machine
        act: 3,
        level: "On level",
        title: "Brighten the stage lights",
        machine: "Tune",
        icon: "dial",
        speaker: "nova",
        line: "The stage lights glow brightest when the dial is at 7/8. The dial goes from 0 to 1 in eighths.",
        question: "Set the dial to 7/8, then press Lock signal.",
        hint: "Count 7 jumps of 1/8 from 0. That's one jump before 1.",
        meter: { heat: 10, label: "Glow +10%", story: "The stage lights shine" },
        discovery: {
          id: "anglerfish",
          name: "Anglerfish",
          who: "Kai",
          fact: "Deep in the ocean, anglerfish use a glowing lure on their heads to attract food.",
        },
        answer: { kind: "frac", n: 7, d: 8 },
        rightFeedback: "7/8 — the stage lights are at full glow!",
        wrong: [
          { n: 1, d: 8, hint: "You counted from 1 back toward 0. Start at 0 and count 7 jumps." },
          { n: 7, d: 9, hint: "Count the equal spaces between 0 and 1, not the tick marks." },
          { n: 8, d: 8, hint: "8/8 is all the way at 1. The lights need 7/8." },
        ],
        tune: { denom: 8, mode: "point", start: { n: 0, d: 8 } },
      },
      14: {
        id: 14,
        locked: true, // remove when the client supports one-way scoops
        act: 3,
        level: "On level",
        title: "Pour the lantern oil",
        machine: "Fill",
        icon: "scoop",
        speaker: "kai",
        line: "The big stage lantern needs 4/6 of a jar of glow oil. The only scoop left holds 1/6.",
        question: "How much oil does the lantern need? Then show it with 1/6 scoops.",
        missingPrompt: "How much oil does the lantern need?",
        hint: "Each scoop is 1/6. How many sixths make 4/6?",
        meter: { supplies: 1, label: "Harvest +1 basket", story: "The stage lantern is full" },
        answer: {
          kind: "scoops",
          missing: { n: 4, d: 6 },
          target: { n: 4, d: 6 },
          start: { n: 0, d: 6 },
          scoopSizes: [1],
          waysNeeded: 1,
        },
        rightFeedback: "Four 1/6 scoops make 4/6: 1/6 + 1/6 + 1/6 + 1/6!",
        wrong: [
          { n: 3, d: 6, hint: "Count the sixths again. How many make 4/6?" },
          { n: 5, d: 6, hint: "That's one scoop too many. The lantern needs 4/6." },
        ],
        fill: { denom: 6, start: 0, target: 4 },
      },
      15: {
        id: 15,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "Challenge",
        challenge: true,
        title: "Light the stage",
        machine: "Travel",
        icon: "relay",
        speaker: "vega",
        line: "This is it! The path from the gate (0) to the stage (1) has 8 equal spaces between lantern posts. Nova's lantern is at the 3rd post. The stage light is at 6/8.",
        question: "Step 1: What fraction of the path is Nova's lantern at? Step 2: How many eighths is it from Nova's lantern to the stage light? Step 3: What fraction of the path is past the stage light?",
        hint: "Count the equal spaces. Each space is 1/8 of the path.",
        meter: { heat: 10, label: "Glow +10%", story: "The festival stage lights up" },
        discovery: {
          id: "plantfood",
          name: "Plant food",
          who: "Nova",
          fact: "Plants use sunlight, water, and air to make their own food.",
        },
        answer: { kind: "steps", steps: [{ n: 3, d: 8 }, { n: 3, d: 8 }, { n: 2, d: 8 }] },
        rightFeedback: "The whole path is lit — let the festival begin!",
        wrong: [
          { step: 1, n: 3, d: 9, hint: "There are 9 posts, but how many equal spaces are between 0 and 1?" },
          { step: 1, n: 4, d: 8, hint: "Start counting after the gate at 0. The first post after it is 1/8." },
          { step: 2, n: 6, d: 8, hint: "That's where the stage light is. How many jumps is it from Nova's lantern?" },
          { step: 2, n: 9, d: 8, hint: "You're counting the jumps between the lantern and the stage light. Count them one at a time." },
          { step: 3, n: 6, d: 8, hint: "That's the part up to the stage light. How much of the path is past it?" },
        ],
        travel: {
          denom: 8,
          max: 1,
          mode: "point",
          marks: [{ n: 3, d: 8, label: "Nova's lantern" }, { n: 6, d: 8, label: "Stage light" }],
          label: "of the path",
        },
      },
    },
  },
  // Quests written as separate files (Sept 26): lib/cases/expedition-station/quests/
  [TIDE_POOLS.standard]: TIDE_POOLS,
  [LAVA_LOCK.standard]: LAVA_LOCK,
  [ROBOT_REBUILD.standard]: ROBOT_REBUILD,
  [CANOPY_SUPPLY_DROP.standard]: CANOPY_SUPPLY_DROP,
};

export function getExpeditionQuest(standard) {
  return QUESTS[standard] || null;
}
