// Expedition Station — The Frozen Relay (MA.4.3E-XP)
// Content from Frozen_Relay_4.3E_Content_v1.md. Answer keys stay server-side.
// Act 1 (tasks 1–5) is playable. Acts 2–3 (tasks 6–15) are written (Sept 26,
// rebuilt from the live Act 1 because the original content .md was not in the
// repo) but stay locked until the client supports their machines.
//
// CONTENT_NOTES for the build session — new answer kinds used in Acts 2–3:
//   frac      (existing)  tasks 6, 8, 14
//   debate    (existing)  task 12
//   mistake   task 7   body { tap, error, n, d } — tap the wrong part, pick the error, write the fix
//   numberless task 9  body { step: "questions", picks: [...] } then { step: "solve", n, d }
//   steps     tasks 10, 15  body { step, n, d } — one fraction per step, in order
//   compare   task 11  body { who, n, d } — who went farther, and by how much
//   sort      task 13  body { placements: { itemId: binId } }
// New machine configs: travel (6, 10, 11), repair (7), numberless (9), sort (13),
// fill.grid (8), fill.cells (15). Wrong-answer entries may carry step / error /
// who / item keys so the grader can pick the matching hint.

export const QUESTS = {
  "MA.4.3E-XP": {
    id: "MA.4.3E-XP",
    standard: "MA.4.3E-XP",
    engine: "expedition_station",
    title: "The Frozen Relay",
    planet: "Frostveil",
    outpost: "Relay Outpost · −41°C",
    grade: 4,
    subject: "Math",
    teks: "4.3E",
    skillsChip: "4.3E · Add and subtract fractions",
    iCan:
      "I can add and subtract fractions that have the same bottom number. I can show how with pictures, a number line, and by adding in a different order.",
    blurb:
      "The relay tower on Frostveil went silent, and the crew is running low on heat and fuel. Every tank, cable, and power cell on this outpost is measured in fractions.",
    mission: "Add and subtract fractions to warm the outpost and restart the relay tower.",
    length: "15 tasks · 3 station visits",
    crew: ["Commander Vega", "Kai (engineer)", "Nova (scientist)", "S.A.M. (helper)"],
    channel: "CH 4.35 · FROSTVEIL RELAY",
    playableActs: [1],
    meterStart: { heat: 40, supplies: 3, journal: 0 },
    journalMax: 10,
    opening: [
      "Specialist {name}, this is Commander Vega. The relay tower on Frostveil went silent.",
      "Our crew is low on heat and fuel, and every tank, cable, and power cell here is measured in fractions.",
      "Help Kai and Nova add and subtract those fractions, and we'll get that tower talking again. Vega out.",
    ],
    acts: {
      1: {
        title: "Act 1 · Refuel the heater and find the beacon",
        short: "Refuel and find the beacon",
        complete: "The heater is warm and the beacon is back, {firstName}!",
        teaser:
          "Next on Frostveil: a storm is coming, and the cables and solar panels need fixing. Act 2 opens on your next station visit.",
        tasks: [1, 2, 3, 4],
        challenge: 5,
      },
      2: {
        title: "Act 2 · Fix the cables and clear the panels",
        short: "Fix cables and panels",
        // Content is written (Sept 26). Keep locked until the client supports
        // the Travel, Repair, and Numberless machines (see CONTENT_NOTES below).
        locked: true,
        opening: [
          "Welcome back, {firstName}. Nova here. A storm is rolling in over the ice ridge.",
          "The antenna cable snapped, and snow is piling up on the solar panels. Kai's cable log looks messy, too.",
          "Let's get everything fixed before the storm hits.",
        ],
        complete: "The cables are fixed and the panels are clear, {firstName}!",
        teaser:
          "Next on Frostveil: the path to the relay tower is open. Act 3 opens on your next station visit.",
        tasks: [6, 7, 8, 9],
        challenge: 10,
      },
      3: {
        title: "Act 3 · Reach the tower and restart the relay",
        short: "Reach the tower",
        locked: true,
        opening: [
          "Specialist {firstName}, Commander Vega again. The storm has passed, and the path to the relay tower is clear.",
          "Kai and Nova are hiking up the ridge with the power cells. The tower needs every bit of charge we can give it.",
          "Get that tower talking, and Frostveil is back on the map.",
        ],
        complete: "The relay tower is back online, {firstName}! Frostveil can talk to the whole station again.",
        teaser: "Mission complete. Commander Vega will send your next transmission soon.",
        tasks: [11, 12, 13, 14],
        challenge: 15,
      },
    },
    tasks: {
      1: {
        id: 1,
        act: 1,
        level: "Warm-up",
        title: "Refuel the heater",
        machine: "Fill",
        icon: "tank",
        speaker: "kai",
        line: "Brrr! The heater is almost out of fuel. I poured in 3/8 of a tank. Then I poured in 2/8 more. Can you set the gauge so it matches?",
        question: "How much fuel is in the heater now? Set the gauge, then press Pour.",
        hint: "Both pours are in eighths. How many eighths in all?",
        meter: { heat: 20, label: "Heat +20%", story: "Warms up the tents" },
        answer: { kind: "frac", n: 5, d: 8 },
        wrong: [
          { n: 5, d: 16, hint: "Look at the gauge. Did the pieces change size when Kai poured? Both pours are eighths." },
          { n: 1, d: 8, hint: "Kai poured fuel in two times. Does the tank get more fuel or less?" },
        ],
        fill: {
          denom: 8,
          start: 0,
          pours: [
            { n: 3, d: 8 },
            { n: 2, d: 8 },
          ],
        },
      },
      2: {
        id: 2,
        act: 1,
        level: "Warm-up",
        title: "Settle the tank debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "I poured 1/3 of a tank into the reserve tank. Then I poured another 1/3. That makes 2/6. Easy: 1 + 1 = 2 and 3 + 3 = 6!"',
        nova: 'Nova: "No way. The tank has 2/3 now. The parts are still thirds."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Draw 1/3 and 1/3 on the same tank. What size are the parts?",
        meter: { heat: 15, label: "Heat +15%", story: "The reserve fuel goes to the heater" },
        discovery: {
          id: "crystal",
          name: "Ice crystal",
          who: "Nova",
          fact: "Snowflakes are made of ice crystals. They usually have 6 sides or 6 arms because of the way water freezes.",
        },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. Both pours are thirds. 1 third + 1 third = 2 thirds. Adding doesn't change the size of the parts." },
          { id: "B", text: "Nova, because 2/3 has smaller numbers than 2/6." },
          { id: "C", text: "Kai. You add the top numbers and add the bottom numbers." },
          { id: "D", text: "Kai. Two pours means twice as many parts, so the bottom number doubles." },
        ],
        writtenPrompt: "Tell Kai in your own words why 1/3 + 1/3 is not 2/6.",
      },
      3: {
        id: 3,
        act: 1,
        level: "Warm-up",
        title: "Find the backup beacon",
        machine: "Tune",
        icon: "dial",
        speaker: "kai",
        line: "The backup beacon is buried in the snow. Its battery was at 5/6 before the storm. The cold used up 3/6. If I set the dial to what's left, the beacon will beep back!",
        question: "How much battery is left? Turn the dial, then press Lock signal.",
        hint: "Start at 5/6. Jump back one sixth at a time.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The beacon marks a buried supply crate" },
        discovery: {
          id: "aurora",
          name: "Aurora",
          who: "Kai",
          fact: "On Earth, auroras glow in the sky near the North and South Poles. They happen when tiny bits from the Sun crash into the air high above us.",
        },
        answer: { kind: "frac", n: 2, d: 6 },
        wrong: [
          { n: 3, d: 6, hint: "Start at 5/6 on the dial. Which way do you turn to take some away?" },
          { n: 1, d: 6, hint: "Count the jumps between marks, not the marks. Start counting after 5/6." },
          { n: 8, d: 6, hint: "The cold used up some battery. Should the number go up or down?" },
        ],
        tune: { denom: 6, start: { n: 5, d: 6 }, used: { n: 3, d: 6 } },
      },
      4: {
        id: 4,
        act: 1,
        level: "Warm-up",
        title: "Fuel the sled",
        machine: "Fill",
        icon: "scoop",
        speaker: "nova",
        line: "The sled needs 7/10 of a tank to reach the supply crate. Its tank already has 3/10 in it. Our scoops hold 1/10 or 2/10.",
        question: "How much more fuel does the sled need? Then fill it with scoops two different ways.",
        hint: "Start at 3/10. Count up by tenths to 7/10.",
        meter: { supplies: 2, label: "Supplies +2 days", story: "The sled hauls the crate back to camp" },
        discovery: {
          id: "moth",
          name: "Frost moth",
          who: "Nova",
          fact: "Some moths fly in winter. They shiver the muscles that move their wings to warm up before they take off.",
        },
        answer: {
          kind: "scoops",
          missing: { n: 4, d: 10 },
          target: { n: 7, d: 10 },
          start: { n: 3, d: 10 },
          scoopSizes: [1, 2],
          waysNeeded: 2,
        },
        wrong: [
          { n: 10, d: 10, hint: "The tank already has some fuel. How much more to get from 3/10 up to 7/10?" },
          { n: 7, d: 10, hint: "Look at the tank before you pour. Is it empty?" },
        ],
        fill: { denom: 10, start: 3, target: 7 },
      },
      5: {
        id: 5,
        act: 1,
        level: "Challenge",
        challenge: true,
        title: "The cold snap",
        machine: "Fill",
        icon: "snap",
        speaker: "vega",
        line: "Surprise, the cold snap! The heater tank was at 7/8. The heater burned 2/8 each night for 2 nights. Then Kai added 3/8. The heater runs safely at the 5/8 line or above.",
        question: "What is the tank level now? How far above the safe line is the fuel?",
        hint: "Take it one night at a time. Then count the jumps from the safe line to the fuel.",
        meter: { heat: 10, label: "Heat +10%", story: "The heater stays safe through the cold snap" },
        discovery: {
          id: "sundog",
          name: "Sun dog",
          who: "Nova",
          fact: "Sun dogs are bright spots on each side of the Sun. Tiny ice crystals in the air bend the sunlight to make them.",
        },
        answer: { kind: "challenge", level: { n: 6, d: 8 }, above: { n: 1, d: 8 } },
        wrong: [
          { step: 1, n: 8, d: 8, hint: "Take it one night at a time. How many times did the heater burn fuel?" },
          { step: 1, n: 0, d: 8, hint: "Kai added fuel. Does adding make the tank go up or down?" },
          { step: 1, n: 3, d: 8, hint: "Read the story again. What happened after the two nights?" },
          { step: 2, n: 11, d: 8, hint: "You're finding the space between two lines on the same tank. Can that be bigger than the tank?" },
          { step: 2, n: 2, d: 8, hint: "Count the jumps from the safe line up to the fuel, not the lines." },
        ],
        fill: { denom: 8, start: 7, burn: 2, nights: 2, refill: 3, safe: 5 },
      },
      6: {
        id: 6,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Cut the antenna cable",
        machine: "Travel",
        icon: "cable",
        speaker: "kai",
        line: "The storm snapped our antenna cable! The cable on the spool is 2 3/4 meters long. The new antenna needs 1 1/4 meters. I'll cut that much off the spool.",
        question: "How much cable will be left on the spool? Jump back on the measuring line, then press Cut.",
        hint: "Start at 2 3/4. Take away the 1 whole first, then the 1 fourth.",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The leftover cable goes in the repair kit" },
        discovery: {
          id: "fox",
          name: "Arctic fox paws",
          who: "Nova",
          fact: "Arctic foxes have thick fur on the bottoms of their paws. It helps keep their feet warm when they walk on snow and ice.",
        },
        answer: { kind: "frac", n: 6, d: 4 },
        wrong: [
          { n: 16, d: 4, hint: "Kai is cutting some cable off. Should the spool have more cable or less?" },
          { n: 5, d: 4, hint: "Check the fourths. 3 fourths take away 1 fourth is how many fourths?" },
          { n: 10, d: 4, hint: "Did you take away the whole meter, too? Take away the wholes, then the fourths." },
        ],
        // Travel machine: a measuring line in fourths from 0 to 3. The rover
        // (here, a cable marker) starts at `start` and the student jumps back.
        travel: { denom: 4, max: 3, start: { n: 11, d: 4 }, move: { n: -5, d: 4 }, label: "meters", mixed: true },
      },
      7: {
        id: 7,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Check Kai's cable log",
        machine: "Repair",
        icon: "log",
        speaker: "nova",
        line: "Kai wrote this in his cable log last night: \"I joined a 3/5 meter cable and a 1/5 meter cable. Now I have 4/10 of a meter.\" That doesn't look right to me.",
        question: "Tap the part of Kai's math that is wrong. Pick what went wrong, then write the right answer.",
        hint: "When you put two fifths of a meter together, are the pieces still fifths?",
        meter: { heat: 5, label: "Heat +5%", story: "The heater cable is joined the right way" },
        answer: { kind: "mistake", tap: "denominator", error: "A", fix: { n: 4, d: 5 } },
        repair: {
          log: [
            { id: "a", text: "3/5" },
            { id: "op", text: "+" },
            { id: "b", text: "1/5" },
            { id: "eq", text: "=" },
            { id: "numerator", text: "4" },
            { id: "denominator", text: "/10" },
          ],
          errors: [
            { id: "A", text: "He added the bottom numbers. The parts are still fifths." },
            { id: "B", text: "He added the top numbers wrong. 3 + 1 is not 4." },
            { id: "C", text: "He should have subtracted. Joining cables makes them shorter." },
          ],
        },
        wrong: [
          { error: "B", hint: "Check the top numbers again: 3 fifths and 1 fifth. How many fifths is that?" },
          { error: "C", hint: "When Kai joins two cables, does he get a longer cable or a shorter one?" },
          { n: 4, d: 10, hint: "That's Kai's answer. What size are the pieces when you join fifths?" },
          { n: 2, d: 5, hint: "Joining makes the cable longer. Should you add or subtract?" },
        ],
      },
      8: {
        id: 8,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Clear the solar grid",
        machine: "Fill",
        icon: "grid",
        speaker: "kai",
        line: "Snow is covering 9/12 of the solar grid. I swept off 4/12 this morning. Nova swept off 3/12 after lunch.",
        question: "How much of the solar grid is still covered in snow? Shade the grid, then press Check.",
        hint: "Start with 9 twelfths covered. Take away each sweep, one at a time.",
        meter: { heat: 5, label: "Heat +5%", story: "The panels charge the heater's backup battery" },
        discovery: {
          id: "snowhouse",
          name: "Snow shelter",
          who: "Kai",
          fact: "Fluffy snow is mostly trapped air. That's why a snow shelter can stay much warmer inside than the freezing air outside.",
        },
        answer: { kind: "frac", n: 2, d: 12 },
        wrong: [
          { n: 7, d: 12, hint: "That's how much Kai and Nova swept off. How much snow is left on the grid?" },
          { n: 5, d: 12, hint: "Nova swept after lunch, too. Did you take away both sweeps?" },
          { n: 16, d: 12, hint: "Sweeping takes snow away. Should the covered part get bigger or smaller?" },
        ],
        // Fill machine, grid variant: 12 squares, 9 start shaded.
        fill: { denom: 12, start: 9, grid: { rows: 3, cols: 4 }, sweeps: [{ n: 4, d: 12 }, { n: 3, d: 12 }] },
      },
      9: {
        id: 9,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "On level",
        title: "Fill the water tank",
        machine: "Numberless",
        icon: "water",
        speaker: "nova",
        line: "Nova filled part of the water tank. Then Kai added some more. The tank still isn't full.",
        question: "First, pick the questions we could answer with this story. Then the numbers will show up.",
        hint: "A full tank is 10/10. How much water is in it now?",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The crew has drinking water for the storm" },
        answer: {
          kind: "numberless",
          sensible: ["total", "more", "who"],
          missing: { n: 3, d: 10 },
        },
        numberless: {
          questions: [
            { id: "total", text: "How much water is in the tank now?" },
            { id: "more", text: "How much more water will fill the tank?" },
            { id: "who", text: "Who added more water, Nova or Kai?" },
            { id: "color", text: "What color is the water tank?" },
          ],
          reveal: "Nova filled 3/10 of the tank. Kai added 4/10 more.",
          ask: "How much more water will fill the tank?",
          denom: 10,
          pours: [
            { n: 3, d: 10 },
            { n: 4, d: 10 },
          ],
        },
        wrong: [
          { step: "questions", hint: "Can the story tell us that? Pick only questions that use the amounts of water." },
          { n: 7, d: 10, hint: "That's how much is in the tank now. How much more to reach full?" },
          { n: 1, d: 10, hint: "That's how much more Kai added than Nova. The question asks about filling the tank." },
          { n: 17, d: 10, hint: "A full tank is 10/10. Can the tank need more than a whole tank?" },
        ],
      },
      10: {
        id: 10,
        locked: true, // remove when the client supports this machine
        act: 2,
        level: "Challenge",
        challenge: true,
        title: "The ice quake",
        machine: "Travel",
        icon: "quake",
        speaker: "vega",
        line: "Surprise, an ice quake! Kai drove the rover 5/8 km toward the tower. A crack opened, so he backed up 2/8 km. Then he found a safe path and drove 6/8 km more. The tower is at the 1 4/8 km mark.",
        question: "Where is the rover now? How much farther is the tower?",
        hint: "Follow the rover one move at a time on the track. Backing up means going back.",
        meter: { heat: 5, label: "Heat +5%", story: "The rover makes it past the crack" },
        discovery: {
          id: "glacier",
          name: "Glacier",
          who: "Nova",
          fact: "A glacier is a huge sheet of ice that moves very slowly, like a frozen river. Some move less than a meter a day.",
        },
        answer: { kind: "steps", steps: [{ n: 9, d: 8 }, { n: 3, d: 8 }] },
        wrong: [
          { step: 1, n: 13, d: 8, hint: "Kai backed up. Does backing up move the rover forward or back?" },
          { step: 1, n: 11, d: 8, hint: "Kai backed up 2/8 km in the middle. Did you count that move?" },
          { step: 1, n: 3, d: 8, hint: "The rover drove forward twice and back once. Follow each move on the track." },
          { step: 2, n: 21, d: 8, hint: "You're finding the distance between the rover and the tower. Should you add or subtract?" },
          { step: 2, n: 4, d: 8, hint: "Count the jumps from the rover to the tower, not the marks." },
        ],
        travel: {
          denom: 8,
          max: 2,
          start: { n: 0, d: 8 },
          moves: [
            { n: 5, d: 8 },
            { n: -2, d: 8 },
            { n: 6, d: 8 },
          ],
          goal: { n: 12, d: 8 },
          label: "km",
          mixed: true,
        },
      },
      11: {
        id: 11,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Reach the tower",
        machine: "Travel",
        icon: "trail",
        speaker: "nova",
        line: "Kai and I took different trails up the ridge. Kai hiked 2/6 of a kilometer, rested, then hiked 3/6 more. I hiked 4/6 of a kilometer without stopping.",
        question: "Who hiked farther? How much farther?",
        hint: "Find Kai's total first. Then compare it to Nova's 4/6 on the same track.",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The crew finds the tower's supply locker" },
        discovery: {
          id: "penguins",
          name: "Penguin huddle",
          who: "Kai",
          fact: "On Earth, emperor penguins huddle close together during Antarctic winter storms. They take turns in the warm middle of the group.",
        },
        answer: { kind: "compare", who: "kai", diff: { n: 1, d: 6 } },
        wrong: [
          { who: "nova", hint: "Add Kai's two hikes together first. Then compare." },
          { n: 5, d: 6, hint: "That's how far Kai hiked. The question asks how much farther." },
          { n: 9, d: 6, hint: "You're comparing the two hikes. Should you add Nova's hike or subtract it?" },
        ],
        travel: {
          denom: 6,
          max: 1,
          tracks: [
            { who: "kai", moves: [{ n: 2, d: 6 }, { n: 3, d: 6 }] },
            { who: "nova", moves: [{ n: 4, d: 6 }] },
          ],
          label: "km",
        },
      },
      12: {
        id: 12,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "The charger debate",
        machine: "Crew Debate",
        icon: "debate",
        speaker: "kai",
        line: 'Kai: "The charger shows three cells: 2/8, 5/8, and 6/8. You HAVE to add them in order, left to right. Any other way is cheating!"',
        nova: 'Nova: "I added 2/8 + 6/8 first, because that makes 1 whole. Then I added 5/8. I got 1 5/8 — the same answer."',
        question: "Who is right, Kai or Nova? Pick the best reason, then tell Kai why.",
        hint: "Try it both ways. Do you get the same total?",
        meter: { heat: 5, label: "Heat +5%", story: "The charger warms up" },
        answer: { kind: "debate", who: "nova", reason: "A" },
        reasons: [
          { id: "A", text: "Nova. You can add fractions in any order and get the same total. Making 1 whole first just makes it easier." },
          { id: "B", text: "Nova, because 6/8 is the biggest number, so it should go first." },
          { id: "C", text: "Kai. Changing the order changes the answer." },
          { id: "D", text: "Kai. You always have to add from left to right, or it doesn't count." },
        ],
        writtenPrompt: "Tell Kai in your own words why Nova's way still works.",
        debateHints: {
          wrongWho: "Try adding the cells both ways. Do you get the same total?",
          wrongReason: "Right person, check the reason. Does changing the order change the total?",
          right: "Nova is right — you can add in any order and get the same total.",
        },
      },
      13: {
        id: 13,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Pack the power cells",
        machine: "Sort Bay",
        icon: "cells",
        speaker: "kai",
        line: "Each power pack holds two cells. The tower needs packs with at least 1 whole charge. Help me sort them before we carry them in.",
        question: "Add the two cells in each pack. Sort each pack into the right bin.",
        hint: "Add the top numbers. Then check: is it fewer parts than 1 whole, exactly 1 whole, or more?",
        meter: { supplies: 1, label: "Supplies +1 day", story: "The strongest packs go to the tower" },
        discovery: {
          id: "icicle",
          name: "Icicles",
          who: "Nova",
          fact: "Icicles grow when melting snow drips and freezes again. They get longer one drop at a time.",
        },
        answer: {
          kind: "sort",
          bins: { p1: "one", p2: "less", p3: "more", p4: "less", p5: "one", p6: "more" },
        },
        sort: {
          bins: [
            { id: "less", label: "Less than 1 whole" },
            { id: "one", label: "Exactly 1 whole" },
            { id: "more", label: "More than 1 whole" },
          ],
          items: [
            { id: "p1", label: "3/4 + 1/4" },
            { id: "p2", label: "2/5 + 2/5" },
            { id: "p3", label: "5/6 + 2/6" },
            { id: "p4", label: "3/8 + 4/8" },
            { id: "p5", label: "7/10 + 3/10" },
            { id: "p6", label: "4/12 + 9/12" },
          ],
        },
        wrong: [
          { item: "p2", hint: "2 fifths + 2 fifths is 4 fifths. How many fifths make 1 whole?" },
          { item: "p4", hint: "3 eighths + 4 eighths is 7 eighths. Is that enough for 1 whole?" },
          { item: "p3", hint: "5 sixths + 2 sixths is 7 sixths. How many sixths make 1 whole?" },
          { item: "p6", hint: "4 twelfths + 9 twelfths is 13 twelfths. Is that more than 12 twelfths?" },
        ],
      },
      14: {
        id: 14,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "On level",
        title: "Top off the tower battery",
        machine: "Fill",
        icon: "battery",
        speaker: "kai",
        line: "The tower battery is at 5/12. It needs to reach 11/12 before the relay can start.",
        question: "How much charge do we need to add? Set the charger, then press Charge.",
        hint: "Start at 5/12. Count up by twelfths to 11/12.",
        meter: { heat: 5, label: "Heat +5%", story: "The tower's heaters turn on" },
        answer: { kind: "frac", n: 6, d: 12 },
        wrong: [
          { n: 16, d: 12, hint: "The battery already has some charge. How much more to get from 5/12 to 11/12?" },
          { n: 11, d: 12, hint: "Look at the battery before you charge it. Is it empty?" },
          { n: 7, d: 12, hint: "Count the jumps from 5/12 to 11/12 again, one twelfth at a time." },
        ],
        fill: { denom: 12, start: 5, target: 11 },
      },
      15: {
        id: 15,
        locked: true, // remove when the client supports this machine
        act: 3,
        level: "Challenge",
        challenge: true,
        title: "Restart the relay",
        machine: "Fill",
        icon: "relay",
        speaker: "vega",
        line: "This is it! The three power cells hold 3/6, 5/6, and 2/6 of a charge. The relay needs 1 2/6 to restart. Nova's radio needs 1/6 from whatever is left over.",
        question: "Step 1: What is the total charge? Step 2: How much is left after the relay restarts? Step 3: How much is left after Nova charges her radio?",
        hint: "Add all three cells first. Then take away one amount at a time.",
        meter: { heat: 10, label: "Heat +10%", story: "The relay tower comes back online" },
        discovery: {
          id: "frost",
          name: "Frost",
          who: "Kai",
          fact: "Frost forms when water vapor in the air freezes right onto a cold surface. It turns into ice without becoming liquid water first.",
        },
        answer: { kind: "steps", steps: [{ n: 10, d: 6 }, { n: 2, d: 6 }, { n: 1, d: 6 }] },
        wrong: [
          { step: 1, n: 10, d: 18, hint: "The cells are all sixths. Do the parts change size when you add them?" },
          { step: 1, n: 8, d: 6, hint: "There are three cells. Did you add all three?" },
          { step: 2, n: 18, d: 6, hint: "The relay uses up charge. Should you add or subtract?" },
          { step: 2, n: 8, d: 6, hint: "That's what the relay needs. How much is left after the relay takes it?" },
          { step: 3, n: 3, d: 6, hint: "Nova's radio uses charge, too. Should the leftover go up or down?" },
        ],
        fill: { denom: 6, cells: [{ n: 3, d: 6 }, { n: 5, d: 6 }, { n: 2, d: 6 }], need: { n: 8, d: 6 }, radio: { n: 1, d: 6 } },
      },
    },
  },
};

export function getExpeditionQuest(standard) {
  return QUESTS[standard] || null;
}
