// Stacking Cups — Simulation Lab (animated scene: components/simulation-lab/scenes/cups.js).
// TEKS Math 5.8C — graph in the first quadrant of the coordinate plane ordered pairs of
// numbers arising from mathematical and real-world problems, including those generated by
// number patterns or found in an input-output table. Grade 5 Mathematics.
// Supports 5.4D (additive vs. multiplicative patterns) through the pattern check.
//
// PUBLIC case file: safe to import from client code. The lookup tables are the
// case's "physics" (what the scene shows), not a secret. Answer keys and
// feedback live ONLY in MA-5-8C-SL.server.js. Authored Sept 25 2026 in the
// scene format (ClearCenters_STATE.md §9 rule 22, components/simulation-lab/README.md).

export const PUBLIC_CASE = {
  "standard": "MA.5.8C-SL",
  "title": "Stacking Cups",
  "grade": 5,
  "subject": "Math",
  "system": {
    "title": "Stacking Cups",
    "framing": "Cadet, Mission Control stacks paper cups to build a signal tower. Every cup nests inside the one below it, so each new cup only adds its rim. How does the height of the stack change as you add cups? Stack the cups, fill in the input-output table, and graph the number pairs.",
    "question": "How does the stack's height change each time you add one more cup?"
  },
  "variables": [
    {
      "id": "cups",
      "label": "Number of Cups",
      "min": 1,
      "max": 10,
      "step": 1,
      "unit": " cups"
    }
  ],
  "outcome": {
    "id": "height",
    "label": "Stack Height",
    "unit": "cm",
    "displayMin": 0,
    "displayMax": 40
  },
  "roundOne": {
    "lookupTable": [
      {
        "cups": 1,
        "height": 8
      },
      {
        "cups": 2,
        "height": 10
      },
      {
        "cups": 3,
        "height": 12
      },
      {
        "cups": 4,
        "height": 14
      },
      {
        "cups": 5,
        "height": 16
      },
      {
        "cups": 6,
        "height": 18
      },
      {
        "cups": 7,
        "height": 20
      },
      {
        "cups": 8,
        "height": 22
      },
      {
        "cups": 9,
        "height": 24
      },
      {
        "cups": 10,
        "height": 26
      }
    ]
  },
  "roundTwoLabel": "taller cups",
  "roundTwo": {
    "conditionChangeDescription": "Mission Control switched to a taller kind of cup with a taller rim. Same stacking, new cups. Does the same kind of pattern still hold?",
    "lookupTable": [
      {
        "cups": 1,
        "height": 12
      },
      {
        "cups": 2,
        "height": 15
      },
      {
        "cups": 3,
        "height": 18
      },
      {
        "cups": 4,
        "height": 21
      },
      {
        "cups": 5,
        "height": 24
      },
      {
        "cups": 6,
        "height": 27
      },
      {
        "cups": 7,
        "height": 30
      },
      {
        "cups": 8,
        "height": 33
      },
      {
        "cups": 9,
        "height": 36
      },
      {
        "cups": 10,
        "height": 39
      }
    ]
  },
  "checkpoints": [
    {
      "id": "cp1",
      "type": "mc",
      "prompt": "Look at your table and graph. What happens to the height each time you add ONE cup?",
      "choices": [
        {
          "id": "sameStep",
          "text": "It goes up by the same amount every time."
        },
        {
          "id": "biggerStep",
          "text": "It goes up by more and more each time."
        },
        {
          "id": "same",
          "text": "It stays the same height."
        }
      ]
    },
    {
      "id": "fair",
      "type": "mc",
      "sceneOnly": true,
      "prompt": "Mathematicians change just ONE input at a time. Which one did YOU change between stacks?",
      "choices": [
        {
          "id": "type",
          "text": "Which kind of cup we used",
          "icon": "cup"
        },
        {
          "id": "count",
          "text": "How many cups were in the stack",
          "icon": "cups"
        },
        {
          "id": "table",
          "text": "Which table we stacked on",
          "icon": "table"
        },
        {
          "id": "ruler",
          "text": "How we measured the height",
          "icon": "ruler"
        }
      ]
    }
  ],
  "dataTableStep": {
    "phase": "postRound2",
    "targetRound": "roundTwo",
    "tolerance": 2.0,
    "instructions": "Round 2 prediction (made with the flag before that setting was run). Informational only."
  },
  "scene": {
    "id": "cups",
    "r1Runs": 3,
    "r2Runs": 2,
    "predictSetting": 6,
    "snap": 1,
    "unit": "cm",
    "outcomeAxis": "Height (cm)",
    "variableAxis": "Cups",
    "ghostFormat": "{v} cups",
    "pairLabels": true,
    "explainTitle": "Explain your pattern",
    "checkpointIds": [
      "cp1",
      "fair"
    ],
    "choiceIcons": {
      "cp1": {
        "sameStep": "grow1",
        "biggerStep": "grow2",
        "same": "flat"
      }
    },
    "twist": {
      "type": "tallCups",
      "banner": "New cups!",
      "question": "These cups are taller. What is the new pattern?"
    }
  },
  "machineBackground": {
    "imageUrl": "/simulation-lab/console.jpg"
  },
  "responseStems": [
    "Each cup I added made the stack ___ cm taller.",
    "With ___ cups the stack was ___ cm, so the ordered pair is (___, ___).",
    "To find the height, I can start at ___ cm and add ___ for each extra cup.",
    "With the taller cups, each cup added ___ cm instead."
  ],
  "generalizePrompt": "Describe the pattern in your table and graph. How much does each cup add? Use two ordered pairs from your graph, and explain how the pattern changed with the taller cups.",
  "selfCheckQuestions": [
    "I said how much each cup adds to the height.",
    "I wrote at least two ordered pairs (cups, height).",
    "I explained how to find the height for any number of cups.",
    "I compared the short cups and the taller cups."
  ]
};
